import type { Estrutura } from '../tipos'

/** Vasos e coração. */
export const ESTRUTURAS_CARDIOVASCULAR: Estrutura[] = [
  {
    id: 'tunica-intima',
    nome: 'Túnica íntima',
    sinonimos: ['íntima', 'intima', 'camada subendotelial'],
    tipo: 'camada',
    resumo: 'Camada mais interna do vaso: endotélio, camada subendotelial de conjuntivo e, nas artérias, a lâmina elástica interna.',
    caracteristicas: ['Fina nos jovens; espessa-se com a idade (espessamento intimal fisiológico).', 'Endotélio achatado revestindo a luz.'],
    aprofundado: [
      'É onde começa a aterosclerose: lipoproteínas retidas, células espumosas, capa fibrosa.',
      'Na aorta a íntima é relativamente espessa, com células musculares lisas esparsas.',
    ],
    funcoes: ['Superfície não trombogênica e controle da permeabilidade e do tônus vascular.'],
    regeneracao: { nivel: 'alta', texto: 'O endotélio se refaz rapidamente; a lesão repetida leva a espessamento fibroso.' },
    ondeEncontrar: ['Todos os vasos e o endocárdio.'],
    alteracoes: ['Placa aterosclerótica.', 'Hiperplasia fibromuscular da íntima (reestenose após angioplastia).', 'Endarterite obliterante.'],
  },
  {
    id: 'tunica-media',
    nome: 'Túnica média',
    sinonimos: ['média', 'media'],
    tipo: 'camada',
    resumo: 'Camada intermediária do vaso: músculo liso circular, com muitas lâminas elásticas nas artérias elásticas.',
    caracteristicas: [
      'Artéria elástica (aorta): 40–70 lâminas elásticas fenestradas intercaladas com músculo liso.',
      'Artéria muscular: 10–40 camadas de músculo liso, delimitadas pelas lâminas elásticas interna e externa.',
      'Veias: média fina e pouco organizada.',
    ],
    aprofundado: ['Nas artérias elásticas, a média armazena energia na sístole e a devolve na diástole (efeito Windkessel).'],
    funcoes: ['Resistência à pressão, elasticidade (artérias elásticas) e controle do calibre (artérias musculares).'],
    regeneracao: { nivel: 'moderada', texto: 'O músculo liso prolifera e remodela a parede; lâminas elásticas perdidas não se refazem bem.' },
    ondeEncontrar: ['Artérias e veias; mais espessa nas artérias.'],
    alteracoes: ['Necrose cística da média (Marfan, aneurisma e dissecção de aorta).', 'Esclerose calcificante de Mönckeberg.', 'Hipertrofia da média na hipertensão.'],
  },
  {
    id: 'tunica-adventicia',
    nome: 'Túnica adventícia',
    sinonimos: ['adventícia', 'adventitia', 'túnica externa'],
    tipo: 'camada',
    resumo: 'Camada externa do vaso: conjuntivo com colágeno, fibras elásticas, vasa vasorum e nervos.',
    caracteristicas: ['Conjuntivo frouxo a denso que se continua com o tecido vizinho.', 'Nas veias grandes, é a camada mais espessa.'],
    aprofundado: ['Abriga os vasa vasorum e os nervos vasomotores (nervi vasorum).'],
    funcoes: ['Ancorar o vaso e nutrir a parte externa da parede.'],
    regeneracao: { nivel: 'alta', texto: 'Conjuntivo.' },
    ondeEncontrar: ['Todos os vasos, exceto capilares.'],
    alteracoes: ['Aortite sifilítica: endarterite dos vasa vasorum (aspecto em "casca de árvore").', 'Inflamação adventicial nas vasculites de grandes vasos.'],
  },
  {
    id: 'vasa-vasorum',
    nome: 'Vasa vasorum',
    sinonimos: ['vasos dos vasos'],
    tipo: 'vaso',
    resumo: 'Pequenas artérias, veias e capilares na adventícia dos grandes vasos, que nutrem a parte externa da parede.',
    caracteristicas: ['Pequenos vasos com hemácias na adventícia (e na média externa da aorta).'],
    aprofundado: ['A íntima e a média interna são nutridas por difusão a partir da luz.'],
    funcoes: ['Nutrir a parede de vasos grossos.'],
    regeneracao: { nivel: 'alta', texto: 'Proliferam em placas ateroscleróticas avançadas (neovascularização).' },
    ondeEncontrar: ['Adventícia da aorta, das grandes artérias e das grandes veias.'],
    alteracoes: ['Endarterite obliterante na sífilis terciária.', 'Neovasos frágeis na placa aterosclerótica (hemorragia intraplaca).'],
  },
  {
    id: 'lamina-elastica',
    nome: 'Lâminas elásticas da média',
    sinonimos: ['lamelas elásticas', 'membranas fenestradas'],
    tipo: 'fibra',
    resumo: 'Lâminas concêntricas e onduladas de elastina, com janelas (fenestras), que dão elasticidade à aorta.',
    caracteristicas: ['Linhas escuras e onduladas com orceína, Verhoeff ou resorcina; rosa-claras e refringentes em HE.'],
    aprofundado: ['Unidas às células musculares lisas por microfibrilas, formando a "unidade lamelar" da média.'],
    funcoes: ['Distensão e recolhimento elástico da aorta a cada batimento.'],
    regeneracao: { nivel: 'baixa', texto: 'A elastina quase não é reposta no adulto.' },
    ondeEncontrar: ['Média da aorta, do tronco pulmonar e de outras artérias elásticas.'],
    alteracoes: ['Fragmentação e perda na síndrome de Marfan e no envelhecimento.'],
  },
  {
    id: 'lamina-elastica-interna',
    nome: 'Lâmina elástica interna',
    sinonimos: ['internal elastic lamina', 'LEI'],
    tipo: 'fibra',
    resumo: 'Faixa ondulada e refringente de elastina entre a íntima e a média das artérias musculares.',
    caracteristicas: ['Linha ondulada logo abaixo do endotélio (ondulada pela contração pós-morte).', 'Rosa brilhante em HE; preta em colorações elásticas.'],
    aprofundado: ['É fenestrada, permitindo a difusão de nutrientes para a média.'],
    funcoes: ['Delimitar íntima e média; elasticidade.'],
    regeneracao: { nivel: 'baixa', texto: 'Fragmentada, não se refaz bem.' },
    ondeEncontrar: ['Artérias musculares e arteríolas maiores.'],
    alteracoes: ['Fragmentação e duplicação na aterosclerose e na hipertensão.', 'Destruição na arterite de células gigantes (temporal).'],
  },
  {
    id: 'lamina-elastica-externa',
    nome: 'Lâmina elástica externa',
    sinonimos: ['external elastic lamina', 'LEE'],
    tipo: 'fibra',
    resumo: 'Camada de fibras elásticas entre a média e a adventícia, menos nítida que a interna.',
    caracteristicas: ['Linha ou faixa elástica descontínua na borda externa da média.'],
    aprofundado: ['Mais evidente nas artérias musculares de grande calibre.'],
    funcoes: ['Delimitar média e adventícia.'],
    regeneracao: { nivel: 'baixa', texto: 'Elastina: reposição pobre.' },
    ondeEncontrar: ['Artérias musculares.'],
    alteracoes: ['Referência para medir a espessura da média e o remodelamento arterial.'],
  },
  {
    id: 'arteria-muscular',
    nome: 'Artéria muscular (distributiva)',
    sinonimos: ['artéria média', 'artéria distributiva', 'muscular artery'],
    tipo: 'vaso',
    resumo: 'Artéria de médio calibre com média de músculo liso espessa entre as lâminas elásticas interna e externa.',
    caracteristicas: ['Luz redonda, parede espessa em relação à luz.', 'Lâmina elástica interna nítida e ondulada.', 'Média muscular; adventícia de espessura semelhante.'],
    aprofundado: ['Regula a distribuição do sangue aos órgãos pela contração do músculo liso.'],
    funcoes: ['Distribuir o sangue aos órgãos, ajustando o calibre.'],
    regeneracao: { nivel: 'moderada', texto: 'Remodela a parede sob estímulos de pressão e fluxo.' },
    ondeEncontrar: ['Artérias coronárias, radial, femoral, tibial, renal, mesentéricas.'],
    alteracoes: ['Aterosclerose coronária.', 'Poliarterite nodosa.', 'Displasia fibromuscular (artéria renal).'],
  },
  {
    id: 'endotelio',
    nome: 'Endotélio',
    sinonimos: ['endothelium', 'célula endotelial'],
    tipo: 'epitelio',
    resumo: 'Epitélio simples pavimentoso que reveste por dentro todos os vasos e o coração.',
    caracteristicas: ['Células achatadas com núcleo alongado que faz saliência na luz.'],
    aprofundado: ['Produz NO, prostaciclina, endotelina e fator de von Willebrand (corpos de Weibel-Palade).'],
    funcoes: ['Barreira, anticoagulação, controle do tônus e da passagem de leucócitos.'],
    regeneracao: { nivel: 'alta', texto: 'Recobre rapidamente áreas desnudas.' },
    ondeEncontrar: ['Todos os vasos sanguíneos e linfáticos; endocárdio.'],
    alteracoes: ['Disfunção endotelial (início da aterosclerose).', 'Angiossarcoma e hemangioma.'],
  },
  {
    id: 'fibra-muscular-cardiaca',
    nome: 'Cardiomiócito (fibra muscular cardíaca)',
    sinonimos: ['cardiomiócito', 'músculo cardíaco', 'miocárdio', 'cardiac muscle'],
    tipo: 'celula',
    resumo: 'Célula estriada ramificada com um ou dois núcleos centrais, unida às vizinhas pelos discos intercalares.',
    caracteristicas: [
      'Estrias transversais como no músculo esquelético, mas com núcleo central e fibras que se ramificam.',
      'Halo claro perinuclear (sarcoplasma com glicogênio e lipofuscina).',
      'Discos intercalares em degrau cruzando a fibra.',
    ],
    aprofundado: ['Rica em mitocôndrias (~35 % do volume).', 'Acoplamento elétrico pelas junções comunicantes dos discos: o miocárdio funciona como um sincício funcional.'],
    funcoes: ['Contração rítmica e involuntária do coração.'],
    regeneracao: { nivel: 'nula', texto: 'Renovação mínima no adulto (< 1 % ao ano); o infarto cicatriza com fibrose.' },
    ondeEncontrar: ['Miocárdio; bainha muscular das veias pulmonares e da cava junto ao coração.'],
    alteracoes: ['Infarto: necrose de coagulação, depois tecido de granulação e cicatriz.', 'Hipertrofia (núcleos grandes, "em vagão").', 'Miocardite e cardiomiopatias.'],
  },
  {
    id: 'disco-intercalar',
    nome: 'Disco intercalar',
    sinonimos: ['intercalated disc', 'discos intercalares'],
    tipo: 'celula',
    resumo: 'Junção entre dois cardiomiócitos, que cruza a fibra em linhas escuras transversais, muitas vezes em degraus.',
    caracteristicas: ['Linha transversal mais escura que as estrias, em forma de escada.', 'Melhor vista com hematoxilina férrica ou em grande aumento.'],
    aprofundado: [
      'Parte transversal: fáscias aderentes (ancoram a actina) e desmossomos (resistência mecânica).',
      'Parte lateral: junções comunicantes (conexina 43) para a passagem do estímulo elétrico.',
    ],
    funcoes: ['União mecânica e elétrica das células do miocárdio.'],
    regeneracao: { nivel: 'nao-se-aplica', texto: 'Junção celular.' },
    ondeEncontrar: ['Somente no músculo cardíaco.'],
    alteracoes: ['Cardiomiopatia arritmogênica (mutações em desmossomos).', 'Redistribuição da conexina 43 na insuficiência cardíaca.'],
  },
  {
    id: 'epicardio',
    nome: 'Epicárdio',
    sinonimos: ['pericárdio visceral', 'epicardium'],
    tipo: 'camada',
    resumo: 'Camada externa do coração: mesotélio sobre conjuntivo com gordura, vasos coronários e nervos.',
    caracteristicas: ['Mesotélio simples pavimentoso na superfície; conjuntivo frouxo e tecido adiposo abaixo.', 'Artérias e veias coronárias correm nele.'],
    aprofundado: ['É o folheto visceral do pericárdio seroso.'],
    funcoes: ['Superfície deslizante do coração; leito dos vasos coronários.'],
    regeneracao: { nivel: 'alta', texto: 'Mesotélio e conjuntivo reparáveis.' },
    ondeEncontrar: ['Superfície externa do coração.'],
    alteracoes: ['Pericardite fibrinosa ("pão com manteiga").', 'Metástases e mesotelioma pericárdico.'],
  },
]
