import type { Estrutura } from '../tipos'

/** Vasos e coração. */
export const ESTRUTURAS_CARDIOVASCULAR: Estrutura[] = [
  {
    id: 'tunica-intima',
    nome: 'Túnica íntima',
    sinonimos: ['íntima', 'intima', 'camada subendotelial'],
    tipo: 'camada',
    resumo: 'Camada mais interna do vaso: endotélio, camada subendotelial de conjuntivo e, nas artérias, a lâmina elástica interna.',
    caracteristicas: ['Fina nos jovens; espessa-se com a idade (espessamento intimal fisiológico).', 'Endotélio achatado revestindo a luz.'],
    aprofundado: [
      'É onde começa a aterosclerose: lipoproteínas retidas, células espumosas, capa fibrosa.',
      'Na aorta a íntima é relativamente espessa, com células musculares lisas esparsas.',
    ],
    funcoes: ['Superfície não trombogênica e controle da permeabilidade e do tônus vascular.', 'O endotélio produz óxido nítrico e prostaciclina (vasodilatação, antiagregação) e endotelina (vasoconstrição): regula o tônus minuto a minuto.', 'Controla a passagem de água, proteínas e leucócitos (moléculas de adesão como selectinas e ICAM na inflamação).', 'É o local onde começa a aterosclerose: lipoproteínas retidas no subendotélio, macrófagos espumosos e migração de músculo liso formam a placa.'],
    regeneracao: { nivel: 'alta', texto: 'O endotélio se refaz rapidamente; a lesão repetida leva a espessamento fibroso.' },
    ondeEncontrar: ['Todos os vasos e o endocárdio.'],
    alteracoes: ['Placa aterosclerótica.', 'Hiperplasia fibromuscular da íntima (reestenose após angioplastia).', 'Endarterite obliterante.'],
  },
  {
    id: 'tunica-media',
    nome: 'Túnica média',
    sinonimos: ['média', 'media'],
    tipo: 'camada',
    resumo: 'Camada intermediária do vaso: músculo liso circular, com muitas lâminas elásticas nas artérias elásticas.',
    caracteristicas: [
      'Artéria elástica (aorta): 40–70 lâminas elásticas fenestradas intercaladas com músculo liso.',
      'Artéria muscular: 10–40 camadas de músculo liso, delimitadas pelas lâminas elásticas interna e externa.',
      'Veias: média fina e pouco organizada.',
    ],
    aprofundado: ['Nas artérias elásticas, a média armazena energia na sístole e a devolve na diástole (efeito Windkessel).'],
    funcoes: ['Resistência à pressão, elasticidade (artérias elásticas) e controle do calibre (artérias musculares).', 'Nas artérias elásticas (aorta), as lâminas elásticas guardam energia na sístole e a devolvem na diástole (efeito Windkessel), mantendo o fluxo contínuo.', 'Nas artérias musculares e arteríolas, o músculo liso contrai ou relaxa sob controle simpático e local, definindo a resistência periférica e a pressão arterial.', 'O músculo liso da média produz o próprio colágeno, a elastina e os proteoglicanos da parede.'],
    regeneracao: { nivel: 'moderada', texto: 'O músculo liso prolifera e remodela a parede; lâminas elásticas perdidas não se refazem bem.' },
    ondeEncontrar: ['Artérias e veias; mais espessa nas artérias.'],
    alteracoes: ['Necrose cística da média (Marfan, aneurisma e dissecção de aorta).', 'Esclerose calcificante de Mönckeberg.', 'Hipertrofia da média na hipertensão.'],
  },
  {
    id: 'tunica-adventicia',
    nome: 'Túnica adventícia',
    sinonimos: ['adventícia', 'adventitia', 'túnica externa'],
    tipo: 'camada',
    resumo: 'Camada externa do vaso: conjuntivo com colágeno, fibras elásticas, vasa vasorum e nervos.',
    caracteristicas: ['Conjuntivo frouxo a denso que se continua com o tecido vizinho.', 'Nas veias grandes, é a camada mais espessa.'],
    aprofundado: ['Abriga os vasa vasorum e os nervos vasomotores (nervi vasorum).'],
    funcoes: ['Ancorar o vaso e nutrir a parte externa da parede.', 'Levar vasa vasorum e nervos (nervi vasorum, simpáticos) à parede.', 'Limitar a distensão excessiva do vaso (colágeno I).', 'Nas veias grandes, é a camada mais espessa e contém feixes longitudinais de músculo liso.'],
    regeneracao: { nivel: 'alta', texto: 'Conjuntivo.' },
    ondeEncontrar: ['Todos os vasos, exceto capilares.'],
    alteracoes: ['Aortite sifilítica: endarterite dos vasa vasorum (aspecto em "casca de árvore").', 'Inflamação adventicial nas vasculites de grandes vasos.'],
  },
  {
    id: 'vasa-vasorum',
    nome: 'Vasa vasorum',
    sinonimos: ['vasos dos vasos'],
    tipo: 'vaso',
    resumo: 'Pequenas artérias, veias e capilares na adventícia dos grandes vasos, que nutrem a parte externa da parede.',
    caracteristicas: ['Pequenos vasos com hemácias na adventícia (e na média externa da aorta).'],
    aprofundado: ['A íntima e a média interna são nutridas por difusão a partir da luz.'],
    funcoes: ['Nutrir a parede de vasos grossos.', 'Irrigar os dois terços externos da parede de artérias e veias grandes; o terço interno é nutrido por difusão a partir da luz.', 'Drenar a parede (vênulas e linfáticos da adventícia).'],
    regeneracao: { nivel: 'alta', texto: 'Proliferam em placas ateroscleróticas avançadas (neovascularização).' },
    ondeEncontrar: ['Adventícia da aorta, das grandes artérias e das grandes veias.'],
    alteracoes: ['Endarterite obliterante na sífilis terciária.', 'Neovasos frágeis na placa aterosclerótica (hemorragia intraplaca).', 'Aortite sifilítica: endarterite obliterante dos vasa vasorum, com isquemia da média e aneurisma da aorta ascendente.'],
  },
  {
    id: 'lamina-elastica',
    nome: 'Lâminas elásticas da média',
    sinonimos: ['lamelas elásticas', 'membranas fenestradas'],
    tipo: 'fibra',
    resumo: 'Lâminas concêntricas e onduladas de elastina, com janelas (fenestras), que dão elasticidade à aorta.',
    caracteristicas: ['Linhas escuras e onduladas com orceína, Verhoeff ou resorcina; rosa-claras e refringentes em HE.'],
    aprofundado: ['Unidas às células musculares lisas por microfibrilas, formando a "unidade lamelar" da média.'],
    funcoes: ['Distensão e recolhimento elástico da aorta a cada batimento.', 'Distribuir a tensão da parede de modo uniforme entre as camadas de músculo liso.', 'Amortecer o pulso: sem elas a pressão sistólica sobe e a diastólica cai (como no idoso com aorta rígida).'],
    regeneracao: { nivel: 'baixa', texto: 'A elastina quase não é reposta no adulto.' },
    ondeEncontrar: ['Média da aorta, do tronco pulmonar e de outras artérias elásticas.'],
    alteracoes: ['Fragmentação e perda na síndrome de Marfan e no envelhecimento.', 'Fragmentação com a idade e na hipertensão (aumenta a rigidez arterial).', 'Síndrome de Marfan (fibrilina-1): degeneração da média, aneurisma e dissecção da aorta.'],
  },
  {
    id: 'lamina-elastica-interna',
    nome: 'Lâmina elástica interna',
    sinonimos: ['internal elastic lamina', 'LEI'],
    tipo: 'fibra',
    resumo: 'Faixa ondulada e refringente de elastina entre a íntima e a média das artérias musculares.',
    caracteristicas: ['Linha ondulada logo abaixo do endotélio (ondulada pela contração pós-morte).', 'Rosa brilhante em HE; preta em colorações elásticas.'],
    aprofundado: ['É fenestrada, permitindo a difusão de nutrientes para a média.'],
    funcoes: ['Delimitar íntima e média; elasticidade.', 'Permitir a difusão de nutrientes da luz para a média pelas fenestras.', 'Servir de marco histológico: define a artéria muscular e aparece ondulada porque a artéria contrai na fixação.'],
    regeneracao: { nivel: 'baixa', texto: 'Fragmentada, não se refaz bem.' },
    ondeEncontrar: ['Artérias musculares e arteríolas maiores.'],
    alteracoes: ['Fragmentação e duplicação na aterosclerose e na hipertensão.', 'Destruição na arterite de células gigantes (temporal).'],
  },
  {
    id: 'lamina-elastica-externa',
    nome: 'Lâmina elástica externa',
    sinonimos: ['external elastic lamina', 'LEE'],
    tipo: 'fibra',
    resumo: 'Camada de fibras elásticas entre a média e a adventícia, menos nítida que a interna.',
    caracteristicas: ['Linha ou faixa elástica descontínua na borda externa da média.'],
    aprofundado: ['Mais evidente nas artérias musculares de grande calibre.'],
    funcoes: ['Delimitar média e adventícia.', 'Dar elasticidade à parte externa da média.', 'Servir de marco para medir a espessura da média.'],
    regeneracao: { nivel: 'baixa', texto: 'Elastina: reposição pobre.' },
    ondeEncontrar: ['Artérias musculares.'],
    alteracoes: ['Referência para medir a espessura da média e o remodelamento arterial.', 'Mais evidente em artérias musculares grandes; ausente ou descontínua nas pequenas.'],
  },
  {
    id: 'arteria-muscular',
    nome: 'Artéria muscular (distributiva)',
    sinonimos: ['artéria média', 'artéria distributiva', 'muscular artery'],
    tipo: 'vaso',
    resumo: 'Artéria de médio calibre com média de músculo liso espessa entre as lâminas elásticas interna e externa.',
    caracteristicas: ['Luz redonda, parede espessa em relação à luz.', 'Lâmina elástica interna nítida e ondulada.', 'Média muscular; adventícia de espessura semelhante.'],
    aprofundado: ['Regula a distribuição do sangue aos órgãos pela contração do músculo liso.'],
    funcoes: ['Distribuir o sangue aos órgãos, ajustando o calibre.', 'Controlar a resistência vascular e a distribuição do débito cardíaco entre os órgãos (vasoconstrição simpática, vasodilatação local).', 'Resistir à pressão pulsátil sem se distender em excesso.'],
    regeneracao: { nivel: 'moderada', texto: 'Remodela a parede sob estímulos de pressão e fluxo.' },
    ondeEncontrar: ['Artérias coronárias, radial, femoral, tibial, renal, mesentéricas.'],
    alteracoes: ['Aterosclerose coronária.', 'Poliarterite nodosa.', 'Displasia fibromuscular (artéria renal).'],
  },
  {
    id: 'endotelio',
    nome: 'Endotélio',
    sinonimos: ['endothelium', 'célula endotelial'],
    tipo: 'epitelio',
    resumo: 'Epitélio simples pavimentoso que reveste por dentro todos os vasos e o coração.',
    caracteristicas: ['Células achatadas com núcleo alongado que faz saliência na luz.'],
    aprofundado: ['Produz NO, prostaciclina, endotelina e fator de von Willebrand (corpos de Weibel-Palade).'],
    funcoes: ['Barreira, anticoagulação, controle do tônus e da passagem de leucócitos.', 'Manter o sangue fluido: produz trombomodulina, heparan sulfato, prostaciclina e ativador do plasminogênio (tPA); lesado, expõe fator tecidual e fator de von Willebrand e desencadeia a coagulação.', 'Regular o tônus vascular (óxido nítrico, endotelina) e a pressão arterial (enzima conversora da angiotensina na superfície, sobretudo no pulmão).', 'Controlar a inflamação: expressa selectinas e integrinas que capturam leucócitos e permite a diapedese nas vênulas pós-capilares.', 'Formar barreiras especializadas (hematoencefálica, hematotesticular) ou deixar passar livremente (sinusoides do fígado, capilares fenestrados do rim).'],
    regeneracao: { nivel: 'alta', texto: 'Recobre rapidamente áreas desnudas.' },
    ondeEncontrar: ['Todos os vasos sanguíneos e linfáticos; endocárdio.'],
    alteracoes: ['Disfunção endotelial (início da aterosclerose).', 'Angiossarcoma e hemangioma.'],
  },
  {
    id: 'fibra-muscular-cardiaca',
    nome: 'Cardiomiócito (fibra muscular cardíaca)',
    sinonimos: ['cardiomiócito', 'músculo cardíaco', 'miocárdio', 'cardiac muscle'],
    tipo: 'celula',
    resumo: 'Célula estriada ramificada com um ou dois núcleos centrais, unida às vizinhas pelos discos intercalares.',
    caracteristicas: [
      'Estrias transversais como no músculo esquelético, mas com núcleo central e fibras que se ramificam.',
      'Halo claro perinuclear (sarcoplasma com glicogênio e lipofuscina).',
      'Discos intercalares em degrau cruzando a fibra.',
    ],
    aprofundado: ['Rica em mitocôndrias (~35 % do volume).', 'Acoplamento elétrico pelas junções comunicantes dos discos: o miocárdio funciona como um sincício funcional.'],
    funcoes: ['Contração rítmica e involuntária do coração.', 'Contrair de forma sincronizada graças ao acoplamento elétrico pelos discos intercalares (sincício funcional).', 'Acoplamento excitação-contração dependente de cálcio extracelular (canais tipo L) que dispara a liberação de cálcio do retículo sarcoplasmático.', 'Produzir hormônios: os cardiomiócitos atriais secretam o peptídeo natriurético atrial (ANP) e os ventriculares, o BNP, que aumentam a excreção de sódio.', 'Obter energia quase só do metabolismo aeróbio (ácidos graxos) — por isso tem mitocôndrias abundantes e sofre rápido na isquemia.'],
    regeneracao: { nivel: 'nula', texto: 'Renovação mínima no adulto (< 1 % ao ano); o infarto cicatriza com fibrose.' },
    ondeEncontrar: ['Miocárdio; bainha muscular das veias pulmonares e da cava junto ao coração.'],
    alteracoes: ['Infarto: necrose de coagulação, depois tecido de granulação e cicatriz.', 'Hipertrofia (núcleos grandes, "em vagão").', 'Miocardite e cardiomiopatias.'],
  },
  {
    id: 'disco-intercalar',
    nome: 'Disco intercalar',
    sinonimos: ['intercalated disc', 'discos intercalares'],
    tipo: 'celula',
    resumo: 'Junção entre dois cardiomiócitos, que cruza a fibra em linhas escuras transversais, muitas vezes em degraus.',
    caracteristicas: ['Linha transversal mais escura que as estrias, em forma de escada.', 'Melhor vista com hematoxilina férrica ou em grande aumento.'],
    aprofundado: [
      'Parte transversal: fáscias aderentes (ancoram a actina) e desmossomos (resistência mecânica).',
      'Parte lateral: junções comunicantes (conexina 43) para a passagem do estímulo elétrico.',
    ],
    funcoes: ['União mecânica e elétrica das células do miocárdio.', 'Transmitir a força de contração de uma célula para a outra (fáscias aderentes e desmossomos).', 'Propagar o impulso elétrico por junções comunicantes (conexina 43), fazendo o miocárdio contrair como uma unidade.'],
    regeneracao: { nivel: 'nao-se-aplica', texto: 'Junção celular.' },
    ondeEncontrar: ['Somente no músculo cardíaco.'],
    alteracoes: ['Cardiomiopatia arritmogênica (mutações em desmossomos).', 'Redistribuição da conexina 43 na insuficiência cardíaca.'],
  },
  {
    id: 'epicardio',
    nome: 'Epicárdio',
    sinonimos: ['pericárdio visceral', 'epicardium'],
    tipo: 'camada',
    resumo: 'Camada externa do coração: mesotélio sobre conjuntivo com gordura, vasos coronários e nervos.',
    caracteristicas: ['Mesotélio simples pavimentoso na superfície; conjuntivo frouxo e tecido adiposo abaixo.', 'Artérias e veias coronárias correm nele.'],
    aprofundado: ['É o folheto visceral do pericárdio seroso.'],
    funcoes: ['Superfície deslizante do coração; leito dos vasos coronários.', 'Produzir líquido pericárdico que reduz o atrito.', 'Abrigar a gordura epicárdica, que amortece os vasos coronários e é fonte de energia e de citocinas para o miocárdio.'],
    regeneracao: { nivel: 'alta', texto: 'Mesotélio e conjuntivo reparáveis.' },
    ondeEncontrar: ['Superfície externa do coração.'],
    alteracoes: ['Pericardite fibrinosa ("pão com manteiga").', 'Metástases e mesotelioma pericárdico.'],
  },
  {
    id: 'endocardio',
    nome: 'Endocárdio',
    sinonimos: ['endocardium', 'camada endocárdica'],
    tipo: 'camada',
    resumo: 'Camada interna do coração: endotélio sobre conjuntivo frouxo delicado (subendotelial) e, mais fundo, a camada subendocárdica, que liga o endocárdio ao miocárdio.',
    caracteristicas: ['Linha fina de endotélio na superfície voltada para a cavidade.', 'Abaixo, conjuntivo frouxo claro com fibras elásticas e algumas células musculares lisas.', 'Na camada subendocárdica dos ventrículos correm as fibras de Purkinje, maiores e mais claras que os cardiomiócitos comuns.'],
    aprofundado: ['Continua-se com a íntima dos vasos que entram e saem do coração e reveste as valvas.', 'As valvas cardíacas são dobras do endocárdio com um eixo de conjuntivo denso (camada fibrosa), sem vasos.'],
    funcoes: ['Superfície lisa e não trombogênica para o sangue dentro das câmaras.', 'Abrigar o sistema de condução (fibras de Purkinje) na camada subendocárdica.', 'Formar as valvas cardíacas.'],
    regeneracao: { nivel: 'moderada', texto: 'Endotélio renovável; as valvas cicatrizam com fibrose e retração.' },
    ondeEncontrar: ['Toda a superfície interna das câmaras cardíacas e das valvas.'],
    alteracoes: ['Endocardite infecciosa: vegetações de fibrina e bactérias nas valvas.', 'Febre reumática: endocardite com valvulite e sequela de estenose mitral.', 'Fibroelastose endocárdica: espessamento difuso em lactentes.', 'Trombo mural sobre área de infarto.'],
  },
  {
    id: 'miocardio',
    nome: 'Miocárdio',
    sinonimos: ['myocardium', 'músculo cardíaco'],
    tipo: 'camada',
    resumo: 'Camada média e mais espessa do coração, formada por cardiomiócitos em feixes espiralados, com conjuntivo e capilares abundantes entre eles.',
    caracteristicas: ['Fibras ramificadas, estriadas, com um ou dois núcleos centrais.', 'Feixes cortados em direções diferentes (longitudinais, oblíquos e transversais) no mesmo corte, por causa da disposição em espiral.', 'Muito mais espesso no ventrículo esquerdo que no direito e nos átrios.'],
    aprofundado: ['A densidade capilar é de cerca de um capilar por cardiomiócito — reflete o metabolismo aeróbio intenso.', 'O esqueleto fibroso (anéis das valvas e trígonos) ancora o miocárdio e isola eletricamente átrios de ventrículos, deixando só o feixe de His passar.', 'Nos átrios, os cardiomiócitos têm grânulos de peptídeo natriurético atrial.'],
    funcoes: ['Gerar a força que bombeia o sangue (sístole) e relaxar para o enchimento (diástole).', 'Conduzir o impulso elétrico célula a célula pelos discos intercalares.', 'Função endócrina (ANP e BNP), usada clinicamente como marcador de insuficiência cardíaca.'],
    regeneracao: { nivel: 'baixa', texto: 'Renovação muito baixa (cerca de 1 % ao ano no adulto jovem); o miocárdio infartado é substituído por cicatriz de colágeno.' },
    ondeEncontrar: ['Parede das quatro câmaras cardíacas; extensões nas bainhas das veias pulmonares e da cava.'],
    alteracoes: ['Infarto: necrose de coagulação com neutrófilos (1–3 dias), macrófagos e tecido de granulação (1–2 semanas) e cicatriz (a partir de 6 semanas).', 'Hipertrofia (hipertensão, estenose aórtica): fibras e núcleos grandes, "em vagão".', 'Miocardite viral: infiltrado linfocitário com necrose de cardiomiócitos.', 'Cardiomiopatia hipertrófica: desarranjo das fibras (disarray).'],
  },
  {
    id: 'nucleo-central-do-cardiomiocito',
    nome: 'Núcleo central do cardiomiócito',
    sinonimos: ['núcleo do cardiomiócito', 'núcleo central da fibra cardíaca'],
    tipo: 'celula',
    resumo: 'Núcleo oval e alongado, único ou duplo, no centro da fibra cardíaca, muitas vezes com um halo claro em cada polo.',
    caracteristicas: ['Um (às vezes dois) por célula, no centro — diferente do músculo esquelético, que tem vários núcleos na periferia.', 'Halo claro perinuclear com glicogênio, lipofuscina e mitocôndrias (mais evidente no idoso).'],
    aprofundado: ['Muitos cardiomiócitos adultos são binucleados ou poliploides e não voltam a se dividir.', 'Na hipertrofia o núcleo fica grande, retangular e escuro ("núcleo em vagão").'],
    funcoes: ['Comandar a síntese das proteínas contráteis e mitocondriais da fibra.', 'Servir de critério diagnóstico: núcleo central + estriação + ramificação + discos intercalares = músculo cardíaco.'],
    regeneracao: { nivel: 'baixa', texto: 'Cardiomiócitos quase não se dividem no adulto.' },
    ondeEncontrar: ['Miocárdio de átrios e ventrículos.'],
    alteracoes: ['Lipofuscina perinuclear (pigmento de desgaste) no idoso e na atrofia marrom.', 'Núcleos grandes e hipercromáticos na hipertrofia.'],
  },
]
