import type { Estrutura } from '../tipos'

/** Tubo digestivo. */
export const ESTRUTURAS_DIGESTORIO: Estrutura[] = [
  {
    id: 'muscular-externa',
    nome: 'Muscular externa (muscular própria)',
    sinonimos: ['muscularis externa', 'muscular própria', 'camada muscular'],
    tipo: 'camada',
    resumo: 'Camada muscular do tubo digestivo, em geral circular interna e longitudinal externa, com o plexo mioentérico entre elas.',
    caracteristicas: ['Duas camadas de músculo em direções perpendiculares.', 'Esôfago: esquelético no terço superior, misto no médio e liso no inferior; daí em diante, liso.', 'Estômago: três camadas (oblíqua interna, circular, longitudinal).'],
    aprofundado: ['O plexo de Auerbach (mioentérico) coordena o peristaltismo.', 'No cólon, a longitudinal se concentra nas tênias.'],
    funcoes: ['Peristaltismo e mistura do conteúdo.', 'Camada circular interna estreita a luz (segmentação, mistura); a longitudinal externa encurta o segmento — juntas produzem o peristaltismo.', 'Abrigar o plexo mioentérico (de Auerbach) entre as duas camadas, que comanda a motilidade de forma autônoma.', 'Formar esfíncteres por espessamento da camada circular (esofágico inferior, pilórico, ileocecal, anal interno).'],
    regeneracao: { nivel: 'moderada', texto: 'Músculo liso: hipertrofia e reparo parcial.' },
    ondeEncontrar: ['Todo o tubo digestivo, do esôfago ao reto.'],
    alteracoes: ['Estenose hipertrófica do piloro.', 'Acalasia; doença de Hirschsprung (sem plexo).', 'Tumor estromal gastrointestinal (GIST).', 'Doença de Hirschsprung: ausência de neurônios do plexo mioentérico no cólon distal.', 'Acalasia: perda dos neurônios inibitórios do esfíncter esofágico inferior.'],
  },
  {
    id: 'mucosa-gastrica',
    nome: 'Mucosa gástrica',
    sinonimos: ['gastric mucosa', 'rugas gástricas', 'fovéolas'],
    tipo: 'camada',
    resumo: 'Mucosa com epitélio simples colunar mucoso, fovéolas (criptas) e glândulas que variam de região para região.',
    caracteristicas: ['Superfície com fovéolas (poços) revestidas por células mucosas.', 'Glândulas abaixo: cárdicas, fúndicas (corpo/fundo) ou pilóricas.', 'Pregas (rugas) no estômago vazio.'],
    aprofundado: ['A camada de muco e bicarbonato protege o epitélio do ácido.'],
    funcoes: ['Secretar ácido, enzimas, muco e hormônios.', 'Formar a barreira mucosa-bicarbonato que impede a autodigestão.', 'Secretar fator intrínseco (absorção de vitamina B12 no íleo).', 'Produzir grelina (fome) e, no antro, gastrina.'],
    regeneracao: { nivel: 'alta', texto: 'O epitélio superficial se renova a cada 3–5 dias a partir do istmo das glândulas.' },
    ondeEncontrar: ['Estômago.'],
    alteracoes: ['Gastrite por H. pylori.', 'Gastrite atrófica e metaplasia intestinal.', 'Adenocarcinoma gástrico.'],
  },
  {
    id: 'glandula-gastrica-fundica',
    nome: 'Glândulas gástricas fúndicas (oxínticas)',
    sinonimos: ['glândulas oxínticas', 'glândulas do corpo', 'células principais'],
    tipo: 'glandula',
    resumo: 'Glândulas tubulares retas e longas do corpo e fundo, com células parietais (ácido) e principais (pepsinogênio).',
    caracteristicas: ['Ocupam a maior parte da espessura da mucosa.', 'Células parietais eosinófilas no meio da glândula; principais basófilas no fundo.', 'Células mucosas do colo e enteroendócrinas.'],
    aprofundado: ['As células principais secretam pepsinogênio e lipase; as enterocromafins-like, histamina.'],
    funcoes: ['Produzir o suco gástrico ácido e as enzimas digestivas.', 'Células parietais: ácido clorídrico e fator intrínseco.', 'Células principais: pepsinogênio e lipase gástrica.', 'Células enteroendócrinas (tipo ECL): histamina, que estimula a célula parietal.', 'Células mucosas do colo: muco e renovação da glândula (células-tronco no istmo).'],
    regeneracao: { nivel: 'moderada', texto: 'Renovação a partir do istmo, mais lenta que a do epitélio superficial.' },
    ondeEncontrar: ['Corpo e fundo do estômago.'],
    alteracoes: ['Gastrite atrófica autoimune (perda das parietais, anemia perniciosa).', 'Pólipos de glândulas fúndicas (inibidores de bomba de prótons).'],
  },
  {
    id: 'celula-parietal',
    nome: 'Célula parietal (oxíntica)',
    sinonimos: ['parietal cell', 'oxyntic cell'],
    tipo: 'celula',
    resumo: 'Célula grande, arredondada, de citoplasma eosinófilo e núcleo central ("ovo frito"), que secreta HCl e fator intrínseco.',
    caracteristicas: ['Grande e piramidal ou redonda, rosa intensa, às vezes binucleada.', 'Mais numerosa na metade superior das glândulas fúndicas.'],
    aprofundado: ['Canalículos intracelulares e bomba H⁺/K⁺-ATPase; estimulada por gastrina, histamina e acetilcolina.', 'O fator intrínseco é indispensável para absorver vitamina B12.'],
    funcoes: ['Secretar ácido clorídrico e fator intrínseco.', 'Bombear H+ pela H+/K+-ATPase (bomba de prótons), alvo dos inibidores como omeprazol.', 'Responder a três estímulos: acetilcolina (vago), gastrina e histamina (receptor H2).', 'Liberar bicarbonato no sangue (maré alcalina) enquanto secreta ácido.'],
    regeneracao: { nivel: 'moderada', texto: 'Vive meses; reposta a partir de células-tronco do istmo.' },
    ondeEncontrar: ['Glândulas fúndicas do estômago.'],
    alteracoes: ['Anemia perniciosa (anticorpos anticélula parietal).', 'Hiperplasia na síndrome de Zollinger-Ellison.'],
  },
  {
    id: 'glandula-pilorica',
    nome: 'Glândulas pilóricas',
    sinonimos: ['glândulas do antro', 'células G'],
    tipo: 'glandula',
    resumo: 'Glândulas mucosas ramificadas e enoveladas do antro e piloro, com fovéolas profundas e células G (gastrina).',
    caracteristicas: ['Fovéolas ocupando cerca de metade da mucosa.', 'Glândulas de células claras mucosas, sem parietais (ou raras).'],
    aprofundado: ['As células G liberam gastrina, que estimula as parietais do corpo.'],
    funcoes: ['Secretar muco protetor e gastrina.', 'Células G liberam gastrina, que estimula o ácido nas glândulas do corpo e fundo.', 'Células D liberam somatostatina, que freia a gastrina quando o pH cai.'],
    regeneracao: { nivel: 'alta', texto: 'Epitélio renovável.' },
    ondeEncontrar: ['Antro e canal pilórico.'],
    alteracoes: ['Gastrite antral por H. pylori; úlcera péptica.'],
  },
  {
    id: 'vilosidade-intestinal',
    nome: 'Vilosidade intestinal',
    sinonimos: ['villus', 'vilo', 'enterócito'],
    tipo: 'orgao-parte',
    resumo: 'Projeção digitiforme da mucosa do intestino delgado, com eixo de lâmina própria e vaso quilífero, revestida por enterócitos e caliciformes.',
    caracteristicas: ['Epitélio simples colunar com borda estriada (microvilosidades) e caliciformes.', 'Eixo com capilares, músculo liso e quilífero (linfático central).'],
    aprofundado: ['Multiplica a superfície de absorção cerca de 10 vezes (e as microvilosidades, mais 20).'],
    funcoes: ['Absorver nutrientes; os lipídios vão pelos quilíferos.', 'Aumentar a superfície de absorção cerca de 10 vezes (e as microvilosidades, mais 20).', 'Enterócitos digerem na borda em escova (dissacaridases, peptidases) e absorvem monossacarídeos, aminoácidos e lipídios.', 'Os lipídios saem como quilomícrons para o quilífero central; açúcares e aminoácidos, para os capilares e a veia porta.'],
    regeneracao: { nivel: 'alta', texto: 'O epitélio se renova a cada 3–5 dias a partir das criptas.' },
    ondeEncontrar: ['Duodeno, jejuno e íleo (ausente no cólon).'],
    alteracoes: ['Atrofia vilositária na doença celíaca.', 'Doença de Whipple (macrófagos PAS+ na lâmina própria).'],
  },
  {
    id: 'cripta-de-lieberkuhn',
    nome: 'Cripta de Lieberkühn',
    sinonimos: ['cripta intestinal', 'glândula intestinal', 'intestinal crypt', 'células de Paneth'],
    tipo: 'glandula',
    resumo: 'Glândula tubular simples do intestino, entre as vilosidades (delgado) ou sozinha (cólon), onde fica o nicho de células-tronco.',
    caracteristicas: ['Tubos retos e paralelos que se abrem na superfície.', 'No cólon, repletas de caliciformes; no delgado, células de Paneth na base.'],
    aprofundado: ['Células-tronco Lgr5+ na base renovam todo o epitélio.', 'Paneth secretam lisozima e defensinas.'],
    funcoes: ['Renovar o epitélio e secretar muco, água e peptídeos antimicrobianos.', 'Abrigar as células-tronco (LGR5+) que renovam todo o epitélio a cada 3–5 dias.', 'Secretar cloreto e água (via CFTR), o que mantém o conteúdo fluido.', 'Células de Paneth na base secretam defensinas e lisozima; células enteroendócrinas liberam secretina, CCK, GIP, serotonina.'],
    regeneracao: { nivel: 'alta', texto: 'Um dos tecidos que mais se renova no corpo.' },
    ondeEncontrar: ['Intestino delgado, cólon, apêndice, reto.'],
    alteracoes: ['Abscessos de cripta e distorção arquitetural na colite ulcerativa.', 'Adenoma e adenocarcinoma colorretal.'],
  },
  {
    id: 'glandula-de-brunner',
    nome: 'Glândulas de Brunner',
    sinonimos: ['glândulas duodenais', "Brunner's glands"],
    tipo: 'glandula',
    resumo: 'Glândulas mucosas ramificadas na submucosa do duodeno, que secretam muco alcalino.',
    caracteristicas: ['Lóbulos de células claras e espumosas na submucosa, abaixo da muscular da mucosa.', 'Glândulas tubuloacinosas mucosas, claras, na submucosa do duodeno — marca histológica do duodeno.'],
    aprofundado: ['Secretam bicarbonato e urogastrona (EGF), que inibe a secreção ácida.'],
    funcoes: ['Neutralizar o quimo ácido que chega do estômago.', 'Secretar muco alcalino rico em bicarbonato que protege o duodeno do ácido gástrico.', 'Liberar fator de crescimento epidérmico e inibidores de protease que protegem a mucosa.'],
    regeneracao: { nivel: 'moderada', texto: 'Epitélio glandular renovável.' },
    ondeEncontrar: ['Submucosa do duodeno — o que identifica o segmento.'],
    alteracoes: ['Hiperplasia e hamartoma de glândulas de Brunner.', 'Hiperplasia nas úlceras duodenais; úlcera duodenal na hipersecreção ácida e por H. pylori.'],
  },
  {
    id: 'placa-de-peyer',
    nome: 'Placa de Peyer',
    sinonimos: ["Peyer's patch", 'GALT', 'folículos agregados'],
    tipo: 'orgao-parte',
    resumo: 'Agregado de folículos linfoides na mucosa e submucosa do íleo, coberto por epitélio com células M.',
    caracteristicas: ['Área densa e basófila de linfócitos, com folículos e centros germinativos.', 'Na borda antimesentérica do íleo.'],
    aprofundado: ['As células M captam antígenos do lúmen e os entregam às células dendríticas; origem da IgA intestinal.'],
    funcoes: ['Vigilância imune da mucosa intestinal.', 'Células M do epitélio sobre a placa capturam antígenos da luz e os entregam aos linfócitos.', 'Gerar plasmócitos produtores de IgA que povoam toda a lâmina própria intestinal.'],
    regeneracao: { nivel: 'alta', texto: 'Tecido linfoide renovável; involui com a idade.' },
    ondeEncontrar: ['Íleo, sobretudo o terminal.'],
    alteracoes: ['Ulceração na febre tifoide.', 'Ponto de partida de intussuscepção em crianças.', 'Linfomas MALT.'],
  },
  {
    id: 'prega-circular',
    nome: 'Prega circular (de Kerckring)',
    sinonimos: ['plica circularis', 'válvula coniventes'],
    tipo: 'orgao-parte',
    resumo: 'Dobra permanente da mucosa e submucosa do intestino delgado, coberta de vilosidades.',
    caracteristicas: ['Eixo de submucosa com vasos, coberto por mucosa vilosa.', 'Mais alta e numerosa no jejuno; desaparece no íleo distal.', 'Dobras permanentes da mucosa e da submucosa (não desaparecem com a distensão); mais altas no jejuno e ausentes no íleo distal e no cólon.'],
    aprofundado: ['Não desaparece com a distensão (ao contrário das rugas gástricas).'],
    funcoes: ['Aumentar a superfície e desacelerar o trânsito.', 'Aumentar cerca de 3 vezes a superfície de absorção.'],
    regeneracao: { nivel: 'alta', texto: 'Mucosa renovável.' },
    ondeEncontrar: ['Duodeno distal, jejuno e íleo proximal.'],
    alteracoes: ['Pregas espessadas no edema e na infiltração da parede (sinal radiológico).'],
  },
  {
    id: 'submucosa',
    nome: 'Submucosa',
    sinonimos: ['tela submucosa'],
    tipo: 'camada',
    resumo: 'Camada de conjuntivo frouxo a moderadamente denso sob a mucosa, com vasos maiores, nervos (plexo de Meissner) e, em alguns órgãos, glândulas.',
    caracteristicas: ['Entre a muscular da mucosa e a muscular externa.', 'Mais clara que a mucosa, com vasos e às vezes glândulas (esôfago, duodeno) ou tecido linfoide.'],
    aprofundado: ['Contém o plexo submucoso (Meissner), que controla a secreção e o fluxo sanguíneo da mucosa.'],
    funcoes: ['Sustentar a mucosa e levar vasos e nervos.', 'Abrigar o plexo submucoso (Meissner), que controla secreção e fluxo sanguíneo local.', 'Conter glândulas (esôfago, duodeno) e tecido linfoide (íleo, apêndice).'],
    regeneracao: { nivel: 'moderada', texto: 'Conjuntivo renovável.' },
    ondeEncontrar: ['Todo o tubo digestivo, traqueia e brônquios.'],
    alteracoes: ['Invasão da submucosa define o carcinoma pT1.', 'Fibrose na doença de Crohn.'],
  },
  {
    id: 'muscular-da-mucosa',
    nome: 'Muscular da mucosa',
    sinonimos: ['muscularis mucosae', 'lâmina muscular da mucosa'],
    tipo: 'camada',
    resumo: 'Faixa fina de músculo liso no limite inferior da mucosa, separando-a da submucosa.',
    caracteristicas: ['Uma ou duas camadas finas de células musculares lisas logo abaixo das glândulas.', 'Camada fina de músculo liso (circular interna e longitudinal externa) no limite entre lâmina própria e submucosa.'],
    aprofundado: ['Movimenta as pregas e as vilosidades independentemente do peristaltismo.', 'É o marco para o estadiamento de tumores: carcinoma que a ultrapassa passa de intramucoso a invasivo da submucosa.'],
    funcoes: ['Mobilizar a mucosa.', 'Mover as vilosidades e as pregas da mucosa, mantendo o contato com o conteúdo.', 'Ajudar a expulsar a secreção das glândulas.'],
    regeneracao: { nivel: 'moderada', texto: 'Músculo liso pode se regenerar.' },
    ondeEncontrar: ['Esôfago ao ânus.'],
    alteracoes: ['Uma úlcera verdadeira ultrapassa a muscular da mucosa; a erosão não.', 'Espessada e desorganizada na colite crônica e no prolapso mucoso.'],
  },
  {
    id: 'serosa',
    nome: 'Serosa',
    sinonimos: ['túnica serosa', 'peritônio visceral'],
    tipo: 'camada',
    resumo: 'Camada mais externa dos órgãos intraperitoneais: conjuntivo frouxo revestido por mesotélio simples pavimentoso.',
    caracteristicas: ['Linha fina de células achatadas na superfície externa, sobre conjuntivo com vasos e gordura.', 'Mesotélio simples pavimentoso sobre conjuntivo frouxo, na face externa das vísceras intraperitoneais.'],
    aprofundado: ['Onde não há peritônio (esôfago torácico, reto baixo), a camada externa é a adventícia.', 'Onde a víscera é retroperitoneal ou no esôfago, há adventícia em vez de serosa.'],
    funcoes: ['Reduzir o atrito entre as vísceras.', 'Produzir o líquido peritoneal que lubrifica a superfície.'],
    regeneracao: { nivel: 'alta', texto: 'O mesotélio se renova rápido.' },
    ondeEncontrar: ['Estômago, intestino delgado e grosso, vesícula biliar.'],
    alteracoes: ['Peritonite; carcinomatose peritoneal.', 'Peritonite e aderências.', 'Carcinomatose peritoneal.'],
  },
  {
    id: 'foveola-gastrica',
    nome: 'Fovéola gástrica',
    sinonimos: ['fosseta gástrica', 'cripta gástrica'],
    tipo: 'regiao',
    resumo: 'Invaginação da superfície do estômago revestida por células mucosas superficiais, onde desembocam as glândulas.',
    caracteristicas: ['Tubos curtos e retos na parte superficial da mucosa, com epitélio colunar de citoplasma claro (muco).', 'Rasas no corpo, profundas (metade da mucosa) no antro.'],
    aprofundado: ['As células mucosas secretam muco rico em bicarbonato que protege do ácido.'],
    funcoes: ['Proteger a mucosa gástrica.', 'Secretar muco neutro e bicarbonato (células mucosas superficiais), formando a camada protetora.', 'Renovar a superfície a cada 3–5 dias a partir do istmo.'],
    regeneracao: { nivel: 'alta', texto: 'Renovação em 3–5 dias.' },
    ondeEncontrar: ['Mucosa gástrica.'],
    alteracoes: ['Hiperplasia foveolar na gastropatia química.', 'Metaplasia intestinal.'],
  },
  {
    id: 'celula-principal-gastrica',
    nome: 'Célula principal (zimogênica) gástrica',
    sinonimos: ['célula péptica', 'chief cell'],
    tipo: 'celula',
    resumo: 'Célula da base das glândulas fúndicas, de citoplasma basofílico (azulado) e grânulos de pepsinogênio no ápice.',
    caracteristicas: ['No terço inferior das glândulas, mais azulada que a célula parietal rosa.', 'Célula basofílica na base das glândulas fúndicas, com grânulos de zimogênio no ápice.'],
    aprofundado: ['Secreta pepsinogênio e lipase gástrica.', 'Rica em retículo endoplasmático rugoso, por isso é basofílica — diferente da parietal, eosinofílica.'],
    funcoes: ['Iniciar a digestão de proteínas.', 'Secretar pepsinogênio, ativado a pepsina pelo ácido.', 'Secretar lipase gástrica.'],
    regeneracao: { nivel: 'moderada', texto: 'Renovação lenta.' },
    ondeEncontrar: ['Glândulas do corpo e fundo gástrico.'],
    alteracoes: ['Perda na gastrite atrófica.', 'Destruída na gastrite atrófica autoimune.'],
  },
  {
    id: 'celula-de-paneth',
    nome: 'Célula de Paneth',
    sinonimos: ['Paneth cell'],
    tipo: 'celula',
    resumo: 'Célula na base das criptas do intestino delgado com grânulos apicais grandes e intensamente eosinofílicos.',
    caracteristicas: ['Grânulos vermelhos vivos no ápice, no fundo das criptas.', 'Célula piramidal na base das criptas do intestino delgado, com grânulos eosinofílicos grandes no ápice.'],
    aprofundado: ['Secretam lisozima, defensinas e fosfolipase: controlam a microbiota; também sustentam as células-tronco.', 'Metaplasia de Paneth no cólon indica inflamação crônica (doença inflamatória intestinal).'],
    funcoes: ['Defesa antimicrobiana da cripta.', 'Secretar defensinas, lisozima e fosfolipase A2, controlando a microbiota da cripta.', 'Sinalizar para as células-tronco vizinhas (Wnt, EGF), mantendo o nicho.'],
    regeneracao: { nivel: 'moderada', texto: 'Vivem cerca de 20 dias.' },
    ondeEncontrar: ['Criptas do intestino delgado; no cólon esquerdo só em inflamação crônica.'],
    alteracoes: ['Metaplasia de Paneth no cólon (colite crônica).', 'Disfunção na doença de Crohn (NOD2).'],
  },
]
