import type { Estrutura } from '../tipos'

/** Anexos embrionários e órgãos dos sentidos. */
export const ESTRUTURAS_EMBRIOLOGIA_SENTIDOS: Estrutura[] = [
  {
    id: 'vilosidade-corial',
    nome: 'Vilosidade coriônica (corial)',
    sinonimos: ['chorionic villus', 'vilosidade placentária'],
    tipo: 'orgao-parte',
    resumo: 'Projeção fetal da placenta: eixo de conjuntivo com capilares fetais, revestido por trofoblasto, banhado pelo sangue materno.',
    caracteristicas: ['Perfis arredondados de vários tamanhos, soltos no espaço interviloso.', 'Revestimento de sinciciotrofoblasto; citotrofoblasto escasso no termo.', 'Capilares fetais junto à superfície no termo (membranas vasculossinciciais).'],
    aprofundado: ['Vilosidades de ancoragem prendem a placenta à decídua; as terminais fazem a troca.'],
    funcoes: ['Troca de gases, nutrientes e resíduos entre mãe e feto; produção hormonal.'],
    regeneracao: { nivel: 'nao-se-aplica', texto: 'Órgão temporário da gestação.' },
    ondeEncontrar: ['Placenta.'],
    alteracoes: ['Mola hidatiforme (vilosidades edemaciadas).', 'Vilosite.', 'Imaturidade vilosa no diabetes gestacional.'],
  },
  {
    id: 'sinciciotrofoblasto',
    nome: 'Sinciciotrofoblasto',
    sinonimos: ['syncytiotrophoblast', 'nós sinciciais'],
    tipo: 'epitelio',
    resumo: 'Camada multinucleada contínua, sem limites celulares, que reveste as vilosidades e fica em contato direto com o sangue materno.',
    caracteristicas: ['Faixa fina de citoplasma com núcleos escuros; nós sinciciais (grupos de núcleos) no termo.'],
    aprofundado: ['Formado pela fusão do citotrofoblasto; produz hCG, lactogênio placentário e progesterona.'],
    funcoes: ['Barreira e troca placentária; produção de hormônios.'],
    regeneracao: { nivel: 'moderada', texto: 'Renovado pela fusão contínua do citotrofoblasto.' },
    ondeEncontrar: ['Superfície das vilosidades coriônicas.'],
    alteracoes: ['Coriocarcinoma.', 'Excesso de nós sinciciais na hipóxia placentária (pré-eclâmpsia).'],
  },
  {
    id: 'capilar-fetal',
    nome: 'Capilar fetal da vilosidade',
    sinonimos: ['fetal capillary'],
    tipo: 'vaso',
    resumo: 'Capilar no eixo da vilosidade, com hemácias fetais, cada vez mais junto ao sinciciotrofoblasto perto do termo.',
    caracteristicas: ['Pequenos vasos com hemácias dentro da vilosidade.'],
    aprofundado: ['No termo a distância entre sangue fetal e materno cai para ~4 µm.'],
    funcoes: ['Levar o sangue fetal até a superfície de troca.'],
    regeneracao: { nivel: 'alta', texto: 'Angiogênese ao longo da gestação.' },
    ondeEncontrar: ['Vilosidades coriônicas.'],
    alteracoes: ['Corangiose (capilares em excesso).', 'Vasculopatia trombótica fetal.'],
  },
  {
    id: 'espaco-interviloso',
    nome: 'Espaço interviloso',
    sinonimos: ['intervillous space'],
    tipo: 'regiao',
    resumo: 'Espaço entre as vilosidades, preenchido pelo sangue materno que chega pelas artérias espiraladas.',
    caracteristicas: ['Áreas claras ou com hemácias maternas entre as vilosidades.'],
    aprofundado: ['A remodelação das artérias espiraladas pelo trofoblasto garante fluxo de baixa resistência.'],
    funcoes: ['Banhar as vilosidades com sangue materno.'],
    regeneracao: { nivel: 'nao-se-aplica', texto: 'Espaço da placenta.' },
    ondeEncontrar: ['Placenta.'],
    alteracoes: ['Infartos e depósitos de fibrina.', 'Intervilosite (malária, Zika).'],
  },
  {
    id: 'veia-umbilical',
    nome: 'Vasos umbilicais',
    sinonimos: ['veia umbilical', 'artérias umbilicais', 'umbilical vessels'],
    tipo: 'vaso',
    resumo: 'Duas artérias e uma veia de parede muscular espessa, sem adventícia distinta, no cordão umbilical.',
    caracteristicas: ['Artérias: luz pequena, muscular grossa; veia: luz maior, parede mais fina e com lâmina elástica.'],
    aprofundado: ['A veia leva sangue oxigenado ao feto; as artérias trazem o desoxigenado de volta.'],
    funcoes: ['Circulação fetoplacentária.'],
    regeneracao: { nivel: 'nao-se-aplica', texto: 'Estrutura temporária.' },
    ondeEncontrar: ['Cordão umbilical.'],
    alteracoes: ['Artéria umbilical única (associada a malformações).', 'Funisite (inflamação).'],
  },
  {
    id: 'geleia-de-wharton',
    nome: 'Geleia de Wharton',
    sinonimos: ["Wharton's jelly", 'tecido conjuntivo mucoso'],
    tipo: 'matriz',
    resumo: 'Tecido conjuntivo mucoso do cordão: células estreladas esparsas em matriz gelatinosa rica em ácido hialurônico.',
    caracteristicas: ['Matriz clara abundante, poucos fibroblastos estrelados, fibras finas.'],
    aprofundado: ['Protege os vasos de compressão e torção; fonte de células-tronco mesenquimais.'],
    funcoes: ['Proteger os vasos umbilicais.'],
    regeneracao: { nivel: 'nao-se-aplica', texto: 'Tecido temporário.' },
    ondeEncontrar: ['Cordão umbilical.'],
    alteracoes: ['Cordão fino (pouca geleia) associado a restrição de crescimento.'],
  },
  {
    id: 'amnio-corio',
    nome: 'Âmnio e cório',
    sinonimos: ['membranas fetais', 'amnion', 'chorion'],
    tipo: 'camada',
    resumo: 'Membranas que envolvem o feto: âmnio (epitélio cúbico sobre conjuntivo) e cório (conjuntivo e trofoblasto), coladas à decídua.',
    caracteristicas: ['Camadas finas de conjuntivo com epitélio amniótico cúbico de um lado.'],
    aprofundado: ['O âmnio produz parte do líquido amniótico; não tem vasos.'],
    funcoes: ['Conter o líquido amniótico e proteger o feto.'],
    regeneracao: { nivel: 'nao-se-aplica', texto: 'Estrutura temporária.' },
    ondeEncontrar: ['Membranas ovulares, placenta, cordão.'],
    alteracoes: ['Corioamnionite (neutrófilos nas membranas).', 'Âmnio nodoso (oligoâmnio).'],
  },
  {
    id: 'cristalino',
    nome: 'Cristalino',
    sinonimos: ['lens', 'lente'],
    tipo: 'orgao-parte',
    resumo: 'Lente biconvexa transparente e avascular de fibras (células alongadas sem organelas), envolta por uma cápsula espessa.',
    caracteristicas: ['Fibras longas eosinófilas em lamelas; epitélio cúbico só na face anterior.', 'Cápsula PAS+ na superfície.'],
    aprofundado: ['As fibras perdem núcleo e organelas para ficar transparentes; proteínas cristalinas duram a vida inteira.'],
    funcoes: ['Focalizar a luz na retina (acomodação).'],
    regeneracao: { nivel: 'baixa', texto: 'O epitélio forma fibras novas a vida toda, mas lesões não se reparam.' },
    ondeEncontrar: ['Olho, atrás da íris.'],
    alteracoes: ['Catarata.', 'Presbiopia (perda de elasticidade).'],
  },
  {
    id: 'capsula-do-cristalino',
    nome: 'Cápsula do cristalino',
    sinonimos: ['lens capsule'],
    tipo: 'camada',
    resumo: 'Membrana basal muito espessa e elástica que envolve o cristalino; intensamente PAS positiva.',
    caracteristicas: ['Faixa homogênea magenta no PAS, na superfície da lente.'],
    aprofundado: ['Rica em colágeno IV; nela se prendem as fibras zonulares.'],
    funcoes: ['Dar forma ao cristalino e ancorar a zônula.'],
    regeneracao: { nivel: 'baixa', texto: 'Produzida pelo epitélio do cristalino.' },
    ondeEncontrar: ['Superfície do cristalino.'],
    alteracoes: ['Síndrome de pseudoexfoliação.', 'Ruptura na cirurgia de catarata.'],
  },
  {
    id: 'processos-ciliares',
    nome: 'Processos ciliares',
    sinonimos: ['corpo ciliar', 'ciliary processes', 'epitélio ciliar'],
    tipo: 'orgao-parte',
    resumo: 'Pregas do corpo ciliar revestidas por epitélio duplo (externo pigmentado, interno não pigmentado), que produzem o humor aquoso.',
    caracteristicas: ['Projeções digitiformes com eixo vascular e epitélio de duas camadas, uma escura (melanina).'],
    aprofundado: ['O epitélio não pigmentado secreta o humor aquoso; as fibras zonulares partem daqui.'],
    funcoes: ['Produzir humor aquoso e sustentar o cristalino.'],
    regeneracao: { nivel: 'baixa', texto: 'Epitélio de renovação limitada.' },
    ondeEncontrar: ['Corpo ciliar, entre a íris e a retina.'],
    alteracoes: ['Glaucoma (desequilíbrio de produção e drenagem do humor aquoso).', 'Melanoma do corpo ciliar.'],
  },
  {
    id: 'esclera',
    nome: 'Esclera',
    sinonimos: ['sclera', 'branco do olho'],
    tipo: 'camada',
    resumo: 'Túnica externa do olho: conjuntivo denso de feixes colágenos entrelaçados, opaco, contínuo com a córnea.',
    caracteristicas: ['Feixes colágenos densos e poucos fibroblastos; pouco vascularizada.'],
    aprofundado: ['A opacidade vem do arranjo irregular das fibras (ao contrário da córnea).'],
    funcoes: ['Proteger o olho e dar inserção aos músculos extrínsecos.'],
    regeneracao: { nivel: 'baixa', texto: 'Cicatriza lentamente.' },
    ondeEncontrar: ['Parede posterior do globo ocular.'],
    alteracoes: ['Esclerite (artrite reumatoide).', 'Esclera azul na osteogênese imperfeita.'],
  },
  {
    id: 'estroma-corneano',
    nome: 'Estroma da córnea',
    sinonimos: ['substância própria', 'corneal stroma', 'ceratócitos'],
    tipo: 'matriz',
    resumo: 'Cerca de 90 % da espessura da córnea: lamelas de colágeno paralelas e muito regulares, com ceratócitos achatados, avascular e transparente.',
    caracteristicas: ['Lamelas eosinófilas regulares com núcleos achatados esparsos; sem vasos.'],
    aprofundado: ['A transparência depende do diâmetro uniforme das fibrilas e da desidratação mantida pelo endotélio.'],
    funcoes: ['Refração da luz (a maior parte do poder dióptrico do olho).'],
    regeneracao: { nivel: 'baixa', texto: 'Cicatriza com opacidade (leucoma).' },
    ondeEncontrar: ['Córnea.'],
    alteracoes: ['Ceratocone.', 'Edema corneano (falência endotelial).', 'Distrofias corneanas.'],
  },
]
