import type { Estrutura } from '../tipos'

/** Glândulas endócrinas. */
export const ESTRUTURAS_ENDOCRINO: Estrutura[] = [
  {
    id: 'celula-acidofila',
    nome: 'Célula acidófila da adeno-hipófise',
    sinonimos: ['acidófila', 'somatotrofo', 'lactotrofo', 'célula alfa hipofisária'],
    tipo: 'celula',
    resumo: 'Célula da adeno-hipófise de citoplasma rosa-vermelho (grânulos acidófilos), que produz GH (somatotrofos) ou prolactina (lactotrofos).',
    caracteristicas: ['Citoplasma intensamente eosinófilo em HE, vermelho no Mallory/Azan.', 'Núcleo redondo central; em cordões entre capilares sinusoides.', 'Cerca de 40 % das células da pars distalis.'],
    aprofundado: ['A identificação exata do hormônio exige imuno-histoquímica.', 'A secreção de prolactina é inibida pela dopamina do hipotálamo.'],
    funcoes: ['Secretar hormônio do crescimento e prolactina.'],
    regeneracao: { nivel: 'baixa', texto: 'Renovação lenta; hiperplasia de lactotrofos na gestação.' },
    ondeEncontrar: ['Pars distalis da adeno-hipófise, sobretudo nas laterais.'],
    alteracoes: ['Adenoma somatotrófico (gigantismo, acromegalia).', 'Prolactinoma (galactorreia, amenorreia).'],
  },
  {
    id: 'celula-basofila',
    nome: 'Célula basófila da adeno-hipófise',
    sinonimos: ['basófila', 'corticotrofo', 'tireotrofo', 'gonadotrofo'],
    tipo: 'celula',
    resumo: 'Célula da adeno-hipófise de citoplasma azul-violáceo, PAS positiva, que produz ACTH, TSH, FSH ou LH (hormônios glicoproteicos).',
    caracteristicas: ['Citoplasma basófilo, azulado no Mallory; PAS+.', 'Maior que a acidófila, cerca de 10 % das células.'],
    aprofundado: ['O ACTH vem da pró-opiomelanocortina (POMC).'],
    funcoes: ['Controlar tireoide, adrenal e gônadas.'],
    regeneracao: { nivel: 'baixa', texto: 'Renovação lenta.' },
    ondeEncontrar: ['Pars distalis, sobretudo na região central.'],
    alteracoes: ['Doença de Cushing (adenoma corticotrófico).', 'Alteração de Crooke nos corticotrofos com excesso de cortisol.'],
  },
  {
    id: 'celula-cromofoba',
    nome: 'Célula cromófoba',
    sinonimos: ['cromófoba', 'chromophobe'],
    tipo: 'celula',
    resumo: 'Célula da adeno-hipófise de citoplasma pálido, com poucos grânulos: células degranuladas ou precursoras.',
    caracteristicas: ['Citoplasma claro e escasso; núcleos agrupados.', 'Em grupos, entre acidófilas e basófilas.'],
    aprofundado: ['Muitas são células secretoras que liberaram os grânulos; outras, foliculoestreladas de suporte.'],
    funcoes: ['Reserva e suporte da glândula.'],
    regeneracao: { nivel: 'baixa', texto: 'Renovação lenta.' },
    ondeEncontrar: ['Pars distalis.'],
    alteracoes: ['Adenomas não funcionantes, historicamente chamados "cromófobos".'],
  },
  {
    id: 'neuro-hipofise',
    nome: 'Neuro-hipófise (pars nervosa)',
    sinonimos: ['neurohypophysis', 'pars nervosa', 'hipófise posterior', 'pituícitos', 'corpos de Herring'],
    tipo: 'regiao',
    resumo: 'Parte nervosa da hipófise: axônios amielínicos vindos do hipotálamo, pituícitos e capilares; aspecto fibrilar e pálido.',
    caracteristicas: ['Tecido fibrilar claro, com núcleos esparsos de pituícitos.', 'Corpos de Herring: dilatações axonais com grânulos de hormônio.'],
    aprofundado: ['Armazena e libera ocitocina e ADH produzidos nos núcleos supraóptico e paraventricular.'],
    funcoes: ['Liberar ADH (retenção de água) e ocitocina (contração uterina, ejeção do leite).'],
    regeneracao: { nivel: 'baixa', texto: 'Tecido do SNC.' },
    ondeEncontrar: ['Lobo posterior da hipófise.'],
    alteracoes: ['Diabetes insípido central (lesão da haste ou do hipotálamo).'],
  },
  {
    id: 'foliculo-tireoidiano',
    nome: 'Folículo tireoidiano',
    sinonimos: ['thyroid follicle', 'tirócito', 'célula folicular'],
    tipo: 'glandula',
    resumo: 'Unidade da tireoide: esfera de epitélio simples cúbico (tirócitos) em volta de uma luz cheia de coloide.',
    caracteristicas: ['Folículos de tamanhos variados, 50–500 µm.', 'Epitélio cúbico (baixo quando inativo, alto quando estimulado pelo TSH).', 'Células C (parafoliculares) claras entre os folículos.'],
    aprofundado: ['Os tirócitos sintetizam tireoglobulina, iodam a tireoglobulina no coloide e reabsorvem-na para liberar T3/T4.'],
    funcoes: ['Produzir e armazenar os hormônios tireoidianos.'],
    regeneracao: { nivel: 'moderada', texto: 'Proliferam sob estímulo do TSH (bócio).' },
    ondeEncontrar: ['Tireoide.'],
    alteracoes: ['Doença de Graves (epitélio alto, coloide com vacúolos de reabsorção).', 'Tireoidite de Hashimoto.', 'Carcinoma papilífero (núcleos em vidro fosco).'],
  },
  {
    id: 'coloide',
    nome: 'Coloide',
    sinonimos: ['colloid', 'tireoglobulina'],
    tipo: 'matriz',
    resumo: 'Material homogêneo eosinófilo na luz dos folículos tireoidianos: a tireoglobulina, reserva extracelular de hormônio.',
    caracteristicas: ['Rosa homogêneo, PAS+, às vezes retraído da parede (artefato).', 'Vacúolos na borda indicam reabsorção ativa.'],
    aprofundado: ['Guarda hormônio para semanas a meses.'],
    funcoes: ['Armazenar tireoglobulina iodada.'],
    regeneracao: { nivel: 'nao-se-aplica', texto: 'Produto de secreção renovado.' },
    ondeEncontrar: ['Luz dos folículos da tireoide.'],
    alteracoes: ['Bócio coloide (folículos enormes, epitélio achatado).'],
  },
  {
    id: 'celula-principal-paratireoide',
    nome: 'Célula principal da paratireoide',
    sinonimos: ['chief cell', 'célula oxífila', 'paratormônio'],
    tipo: 'celula',
    resumo: 'Célula pequena e poligonal da paratireoide, em cordões e ninhos, que secreta paratormônio (PTH).',
    caracteristicas: ['Núcleo redondo central, citoplasma pálido a levemente eosinófilo, às vezes claro (glicogênio).', 'Células oxífilas maiores e rosadas em grupos, aumentam com a idade.', 'Adipócitos no estroma do adulto.'],
    aprofundado: ['Sensor de cálcio (CaSR) na membrana: o cálcio baixo aumenta a secreção de PTH.'],
    funcoes: ['Elevar o cálcio sanguíneo (osso, rim, vitamina D).'],
    regeneracao: { nivel: 'moderada', texto: 'Hiperplasia na insuficiência renal crônica.' },
    ondeEncontrar: ['Paratireoides, na face posterior da tireoide.'],
    alteracoes: ['Adenoma de paratireoide (hiperparatireoidismo primário).', 'Hiperplasia secundária na doença renal crônica.'],
  },
  {
    id: 'capsula-adrenal',
    nome: 'Cápsula da adrenal',
    sinonimos: ['adrenal capsule'],
    tipo: 'camada',
    resumo: 'Conjuntivo denso que envolve a adrenal e emite trabéculas com vasos para o córtex.',
    caracteristicas: ['Faixa fibrosa externa, com artérias e gordura periadrenal em volta.'],
    aprofundado: ['Abriga progenitores que repõem o córtex a partir da periferia.'],
    funcoes: ['Proteção e entrada de vasos.'],
    regeneracao: { nivel: 'alta', texto: 'Conjuntivo.' },
    ondeEncontrar: ['Adrenal.'],
    alteracoes: ['Nódulos corticais extracapsulares.'],
  },
  {
    id: 'zona-glomerulosa',
    nome: 'Zona glomerulosa',
    sinonimos: ['zona glomerulosa', 'aldosterona'],
    tipo: 'camada',
    resumo: 'Camada externa e fina do córtex adrenal, com células em arcos e ninhos arredondados, que produz aldosterona.',
    caracteristicas: ['Logo abaixo da cápsula; células pequenas, núcleo escuro, pouco lipídio.', 'Descontínua no adulto humano.'],
    aprofundado: ['Regulada pela angiotensina II e pelo potássio, não pelo ACTH.'],
    funcoes: ['Secretar aldosterona (retenção de sódio, excreção de potássio).'],
    regeneracao: { nivel: 'moderada', texto: 'Renovada a partir da periferia do córtex.' },
    ondeEncontrar: ['Córtex adrenal externo.'],
    alteracoes: ['Hiperaldosteronismo primário (adenoma de Conn).'],
  },
  {
    id: 'zona-fasciculada',
    nome: 'Zona fasciculada',
    sinonimos: ['zona fasciculata', 'espongiócitos', 'cortisol'],
    tipo: 'camada',
    resumo: 'Camada média e mais espessa do córtex adrenal: cordões radiais de células claras, cheias de lipídio (espongiócitos), que produzem cortisol.',
    caracteristicas: ['Colunas de células grandes com citoplasma vacuolizado claro, separadas por capilares retos.'],
    aprofundado: ['Regulada pelo ACTH; o lipídio é colesterol, precursor dos esteroides.'],
    funcoes: ['Secretar glicocorticoides (cortisol).'],
    regeneracao: { nivel: 'moderada', texto: 'Hipertrofia sob ACTH; atrofia com corticoide exógeno.' },
    ondeEncontrar: ['Córtex adrenal, entre glomerulosa e reticular.'],
    alteracoes: ['Síndrome de Cushing (adenoma, hiperplasia).', 'Atrofia por uso crônico de corticoide.'],
  },
  {
    id: 'pinealocito',
    nome: 'Pinealócito',
    sinonimos: ['pinealocyte', 'melatonina'],
    tipo: 'celula',
    resumo: 'Célula principal da pineal: núcleo redondo a lobulado, cromatina fina, citoplasma claro; secreta melatonina à noite.',
    caracteristicas: ['Em cordões e lóbulos, muito numerosos.', 'Prolongamentos visíveis só com prata.'],
    aprofundado: ['Neurônio modificado, derivado de fotorreceptores ancestrais; controlado pelo núcleo supraquiasmático via simpático.'],
    funcoes: ['Produzir melatonina e sincronizar o ritmo circadiano.'],
    regeneracao: { nivel: 'nula', texto: 'Não se renova.' },
    ondeEncontrar: ['Glândula pineal.'],
    alteracoes: ['Pineocitoma e pineoblastoma.'],
  },
  {
    id: 'celula-folicular-tireoide',
    nome: 'Célula folicular (tireócito)',
    sinonimos: ['tireócito', 'célula epitelial folicular'],
    tipo: 'celula',
    resumo: 'Célula cúbica que reveste o folículo tireoidiano, produz tireoglobulina e forma T3 e T4.',
    caracteristicas: ['Epitélio simples cúbico; fica colunar quando ativo (TSH alto) e achatado quando inativo.'],
    aprofundado: ['Capta iodeto (NIS), iodina a tireoglobulina no coloide e a recaptura para liberar T3/T4.'],
    funcoes: ['Produzir hormônios tireoidianos.'],
    regeneracao: { nivel: 'moderada', texto: 'Proliferam sob TSH.' },
    ondeEncontrar: ['Folículos da tireoide.'],
    alteracoes: ['Doença de Graves (epitélio alto com reabsorção do coloide).', 'Carcinoma papilífero e folicular.'],
  },
  {
    id: 'celula-parafolicular',
    nome: 'Célula parafolicular (célula C)',
    sinonimos: ['célula C', 'célula clara'],
    tipo: 'celula',
    resumo: 'Célula maior e mais clara que a folicular, isolada entre os folículos ou na base do epitélio, que produz calcitonina.',
    caracteristicas: ['Citoplasma pálido e abundante, sem contato com o coloide.'],
    aprofundado: ['Origem na crista neural (corpo ultimobranquial).'],
    funcoes: ['Secretar calcitonina.'],
    regeneracao: { nivel: 'baixa', texto: 'Poucas mitoses.' },
    ondeEncontrar: ['Tireoide, sobretudo no terço médio dos lobos.'],
    alteracoes: ['Carcinoma medular da tireoide (NEM 2).'],
  },
  {
    id: 'zona-reticular',
    nome: 'Zona reticular',
    sinonimos: ['zona reticulada'],
    tipo: 'camada',
    resumo: 'Camada mais interna do córtex adrenal: cordões anastomosados de células menores e mais eosinofílicas, com lipofuscina.',
    caracteristicas: ['Rede irregular de cordões, mais escura que a fasciculada, junto à medula.'],
    aprofundado: ['Produz andrógenos (DHEA) e um pouco de glicocorticoide.'],
    funcoes: ['Síntese de androgênios adrenais.'],
    regeneracao: { nivel: 'moderada', texto: 'Repovoada a partir das zonas externas.' },
    ondeEncontrar: ['Córtex adrenal, junto à medula.'],
    alteracoes: ['Hiperplasia adrenal congênita (virilização).'],
  },
  {
    id: 'medula-adrenal',
    nome: 'Medula adrenal',
    sinonimos: ['medula suprarrenal', 'células cromafins'],
    tipo: 'regiao',
    resumo: 'Centro da adrenal: células cromafins grandes, basofílicas, em ninhos, entre vasos e veias largas.',
    caracteristicas: ['Células poligonais de citoplasma granular azulado ou acinzentado, sem lipídio.', 'Veia central grande com músculo liso na parede.'],
    aprofundado: ['Neurônios pós-ganglionares modificados que secretam adrenalina e noradrenalina.'],
    funcoes: ['Resposta de luta ou fuga.'],
    regeneracao: { nivel: 'baixa', texto: 'Renovação limitada.' },
    ondeEncontrar: ['Centro das glândulas adrenais.'],
    alteracoes: ['Feocromocitoma.', 'Neuroblastoma na infância.'],
  },
  {
    id: 'adeno-hipofise',
    nome: 'Adeno-hipófise (pars distalis)',
    sinonimos: ['hipófise anterior', 'pars distalis', 'lobo anterior'],
    tipo: 'regiao',
    resumo: 'Parte glandular da hipófise: cordões de células acidófilas, basófilas e cromófobas entre capilares sinusoides.',
    caracteristicas: ['Mosaico de células de cores diferentes (rosa, azul e pálidas), muito vascularizado.'],
    aprofundado: ['Produz GH, prolactina, ACTH, TSH, FSH e LH, sob controle dos hormônios hipotalâmicos (sistema porta).'],
    funcoes: ['Controlar as glândulas endócrinas periféricas.'],
    regeneracao: { nivel: 'baixa', texto: 'Renovação lenta.' },
    ondeEncontrar: ['Sela túrcica.'],
    alteracoes: ['Adenoma hipofisário (prolactinoma, acromegalia, Cushing).', 'Síndrome de Sheehan.'],
  },
]
