import type { Estrutura } from '../tipos'

/** Glândulas digestivas: salivares, pâncreas, fígado e vesícula biliar. */
export const ESTRUTURAS_GLANDULAS: Estrutura[] = [
  {
    id: 'acino-seroso',
    nome: 'Ácino seroso',
    sinonimos: ['serous acinus', 'célula serosa'],
    tipo: 'glandula',
    resumo: 'Unidade secretora arredondada de células piramidais com núcleo redondo basal, base basófila e ápice com grânulos de secreção proteica.',
    caracteristicas: ['Luz pequena, quase invisível.', 'Citoplasma basal basófilo (retículo rugoso) e apical eosinófilo (grânulos de zimogênio).', 'Núcleo redondo, na metade basal.'],
    aprofundado: ['Secreta proteínas (amilase, enzimas) por exocitose; células mioepiteliais abraçam o ácino.'],
    funcoes: ['Produzir secreção aquosa rica em enzimas.'],
    regeneracao: { nivel: 'moderada', texto: 'Proliferam a partir de células dos ductos intercalares e dos próprios ácinos.' },
    ondeEncontrar: ['Parótida (só serosos), submandibular (maioria), pâncreas exócrino, glândulas de von Ebner.'],
    alteracoes: ['Parotidite (caxumba).', 'Carcinoma de células acinares.', 'Sialadenose (hipertrofia acinar no alcoolismo e bulimia).'],
  },
  {
    id: 'acino-mucoso',
    nome: 'Ácino (túbulo) mucoso',
    sinonimos: ['mucous acinus', 'célula mucosa', 'semilua serosa'],
    tipo: 'glandula',
    resumo: 'Unidade secretora de células claras e espumosas, com núcleo achatado contra a base, e luz mais ampla que a do ácino seroso.',
    caracteristicas: ['Citoplasma pálido e vacuolizado em HE (o muco é pouco corado); PAS e azul alciano positivos.', 'Núcleo achatado e basal.', 'Às vezes coberto por uma semilua de células serosas.'],
    aprofundado: ['A semilua serosa (de von Ebner/Giannuzzi) pode ser artefato de fixação, em parte.'],
    funcoes: ['Produzir muco que lubrifica e protege.'],
    regeneracao: { nivel: 'moderada', texto: 'Epitélio glandular renovável.' },
    ondeEncontrar: ['Sublingual (predomínio), submandibular, glândulas salivares menores, glândulas das vias aéreas.'],
    alteracoes: ['Mucocele e rânula.', 'Carcinoma mucoepidermoide.'],
  },
  {
    id: 'ducto-excretor',
    nome: 'Ducto glandular (intercalar, estriado, excretor)',
    sinonimos: ['ducto estriado', 'ducto intercalar', 'ducto interlobular'],
    tipo: 'epitelio',
    resumo: 'Sistema de ductos que leva a secreção dos ácinos para fora, com epitélio que passa de cúbico baixo a colunar e estratificado.',
    caracteristicas: ['Intercalar: cúbico baixo, luz pequena.', 'Estriado: colunar eosinófilo, com estriações basais (mitocôndrias).', 'Excretor: no septo, colunar a pseudoestratificado, com conjuntivo em volta.'],
    aprofundado: ['Os ductos estriados modificam a saliva, reabsorvendo sódio e secretando potássio (saliva hipotônica).'],
    funcoes: ['Conduzir e modificar a secreção.'],
    regeneracao: { nivel: 'moderada', texto: 'Contêm células progenitoras que repõem ácinos.' },
    ondeEncontrar: ['Glândulas salivares, pâncreas, glândula mamária, glândulas sudoríparas.'],
    alteracoes: ['Sialolitíase (cálculos no ducto).', 'Carcinoma de ducto salivar.'],
  },
  {
    id: 'acino-pancreatico',
    nome: 'Ácino pancreático',
    sinonimos: ['pancreatic acinus', 'pâncreas exócrino', 'célula centroacinar'],
    tipo: 'glandula',
    resumo: 'Ácino seroso do pâncreas exócrino: células piramidais com base basófila e ápice cheio de zimogênio; células centroacinares na luz.',
    caracteristicas: ['Ácinos serosos compactos, sem ductos estriados.', 'Células centroacinares claras no centro (início do ducto intercalar).'],
    aprofundado: ['Secretam tripsinogênio, quimotripsinogênio, lipase, amilase; estimulados por colecistocinina.', 'O bicarbonato vem das células dos ductos (secretina).'],
    funcoes: ['Produzir as enzimas digestivas do suco pancreático.'],
    regeneracao: { nivel: 'moderada', texto: 'Regenera após lesão leve; lesões repetidas levam a fibrose.' },
    ondeEncontrar: ['Pâncreas (98 % do órgão).'],
    alteracoes: ['Pancreatite aguda (autodigestão, necrose gordurosa).', 'Pancreatite crônica (fibrose e atrofia acinar).', 'Fibrose cística.'],
  },
  {
    id: 'graos-de-zimogenio',
    nome: 'Grânulos de zimogênio',
    sinonimos: ['zymogen granules', 'grânulos de secreção'],
    tipo: 'celula',
    resumo: 'Vesículas de secreção com as pró-enzimas, concentradas no polo apical das células acinares, voltadas para a luz.',
    caracteristicas: ['Grânulos redondos, eosinófilos em HE e escuros em semifinos com azul de toluidina.', 'Somem após a refeição e reaparecem no jejum.'],
    aprofundado: ['Formados no Golgi a partir do retículo rugoso: o caminho clássico da secreção regulada (experimentos de Palade com autorradiografia).'],
    funcoes: ['Armazenar enzimas inativas até a estimulação.'],
    regeneracao: { nivel: 'nao-se-aplica', texto: 'Organela de secreção renovada continuamente.' },
    ondeEncontrar: ['Células acinares do pâncreas e glândulas serosas; células principais do estômago; células de Paneth.'],
    alteracoes: ['Ativação intracelular precoce na pancreatite aguda.'],
  },
  {
    id: 'graos-de-prata',
    nome: 'Grãos de prata (autorradiografia)',
    sinonimos: ['autorradiografia', 'grânulos de prata', 'emulsão fotográfica'],
    tipo: 'artefato',
    resumo: 'Pontos pretos da emulsão fotográfica sobre o corte, revelados onde havia uma molécula radioativa incorporada pela célula.',
    caracteristicas: ['Grãos negros pequenos sobre (ou perto de) estruturas que incorporaram o marcador.', 'A densidade dos grãos indica a quantidade de marcador.'],
    aprofundado: ['Com aminoácido marcado (³H-leucina) e tempos diferentes, os grãos migram do retículo rugoso ao Golgi e aos grânulos de zimogênio — a demonstração clássica da via secretora.'],
    funcoes: ['Técnica: localizar onde e quando a célula sintetiza ou incorpora uma molécula.'],
    regeneracao: { nivel: 'nao-se-aplica', texto: 'Produto da técnica.' },
    ondeEncontrar: ['Preparações de autorradiografia.'],
    alteracoes: ['Grãos de fundo aleatórios (ruído) devem ser distinguidos dos grãos sobre a célula.'],
  },
  {
    id: 'ilhota-de-langerhans',
    nome: 'Ilhota de Langerhans',
    sinonimos: ['islet of Langerhans', 'ilhota pancreática', 'pâncreas endócrino'],
    tipo: 'glandula',
    resumo: 'Agrupamento arredondado e mais pálido de células endócrinas entre os ácinos do pâncreas, cheio de capilares.',
    caracteristicas: ['Área redonda e clara em HE, com células menores em cordões e muitos capilares.', 'Cerca de 1–2 % do volume do pâncreas.'],
    aprofundado: ['Células beta (~70 %, insulina), alfa (glucagon), delta (somatostatina) e PP; identificadas por imuno-histoquímica.'],
    funcoes: ['Controlar a glicemia.'],
    regeneracao: { nivel: 'baixa', texto: 'Células beta se renovam lentamente no adulto.' },
    ondeEncontrar: ['Todo o pâncreas; mais na cauda.'],
    alteracoes: ['Diabetes tipo 1 (insulite, perda de células beta).', 'Amiloide nas ilhotas no diabetes tipo 2.', 'Tumores neuroendócrinos (insulinoma).'],
  },
  {
    id: 'celula-beta',
    nome: 'Célula beta',
    sinonimos: ['beta cell', 'célula B', 'insulina'],
    tipo: 'celula',
    resumo: 'Célula mais numerosa da ilhota, que produz insulina; fica marcada na imuno-histoquímica anti-insulina.',
    caracteristicas: ['Ocupa sobretudo o centro da ilhota (em roedores; mais misturada no humano).'],
    aprofundado: ['Secreta insulina em resposta à glicose via GLUT2, glicoquinase e canais de K-ATP.'],
    funcoes: ['Baixar a glicemia pela insulina.'],
    regeneracao: { nivel: 'baixa', texto: 'Proliferação limitada no adulto; aumenta na gestação e obesidade.' },
    ondeEncontrar: ['Ilhotas de Langerhans.'],
    alteracoes: ['Destruição autoimune no diabetes tipo 1.', 'Insulinoma.'],
  },
  {
    id: 'hepatocito',
    nome: 'Hepatócito',
    sinonimos: ['hepatocyte', 'célula hepática', 'placa de hepatócitos'],
    tipo: 'celula',
    resumo: 'Célula poligonal grande do fígado, eosinófila, com núcleo redondo central (às vezes dois), arranjada em placas entre sinusoides.',
    caracteristicas: ['Poligonal, 20–30 µm, citoplasma eosinófilo e granuloso.', 'Núcleo central com nucléolo; binucleação frequente.', 'Placas de uma a duas células de espessura.'],
    aprofundado: ['Polo sinusoidal com microvilosidades no espaço de Disse; polo biliar formando os canalículos biliares.', 'Zonas do ácino hepático com funções metabólicas diferentes.'],
    funcoes: ['Metabolismo de glicose, lipídios e proteínas; síntese de albumina e fatores de coagulação; produção de bile; detoxificação.'],
    regeneracao: { nivel: 'alta', texto: 'O fígado regenera a massa após hepatectomia parcial (até 2/3) por divisão dos hepatócitos.' },
    ondeEncontrar: ['Fígado.'],
    alteracoes: ['Esteatose.', 'Balonização e corpos de Mallory (esteato-hepatite).', 'Carcinoma hepatocelular.'],
  },
  {
    id: 'sinusoide-hepatico',
    nome: 'Sinusoide hepático',
    sinonimos: ['hepatic sinusoid', 'espaço de Disse'],
    tipo: 'vaso',
    resumo: 'Capilar largo e descontínuo entre as placas de hepatócitos, onde o sangue portal e arterial se mistura rumo à veia central.',
    caracteristicas: ['Espaço claro entre as placas, revestido por endotélio fenestrado sem lâmina basal.', 'Células de Kupffer na luz.'],
    aprofundado: ['Entre o endotélio e o hepatócito fica o espaço de Disse, com células estreladas (de Ito) que guardam vitamina A.'],
    funcoes: ['Troca ampla entre sangue e hepatócitos.'],
    regeneracao: { nivel: 'alta', texto: 'Endotélio renovável.' },
    ondeEncontrar: ['Fígado; sinusoides semelhantes no baço e na medula óssea.'],
    alteracoes: ['Congestão centrolobular na insuficiência cardíaca.', 'Capilarização e fibrose na cirrose.', 'Síndrome de obstrução sinusoidal.'],
  },
  {
    id: 'celula-de-kupffer',
    nome: 'Célula de Kupffer',
    sinonimos: ['Kupffer cell', 'macrófago hepático'],
    tipo: 'celula',
    resumo: 'Macrófago residente na luz dos sinusoides hepáticos.',
    caracteristicas: ['Núcleo ovalado dentro do sinusoide, citoplasma irregular; às vezes com pigmento fagocitado.'],
    aprofundado: ['Retira bactérias e endotoxinas do sangue portal e hemácias velhas.'],
    funcoes: ['Defesa e limpeza do sangue que vem do intestino.'],
    regeneracao: { nivel: 'alta', texto: 'Autorrenovação local e recrutamento de monócitos.' },
    ondeEncontrar: ['Sinusoides hepáticos.'],
    alteracoes: ['Hemossiderina nas células de Kupffer em sobrecarga de ferro.', 'Hiperplasia em infecções sistêmicas.'],
  },
  {
    id: 'espaco-porta',
    nome: 'Espaço-porta (tríade portal)',
    sinonimos: ['portal tract', 'tríade portal', 'espaço de Kiernan'],
    tipo: 'regiao',
    resumo: 'Conjuntivo nos cantos do lóbulo hepático com um ramo da veia porta, um da artéria hepática e um ducto biliar.',
    caracteristicas: ['Veia porta: maior, parede fina.', 'Artéria: menor, parede muscular espessa.', 'Ducto biliar: epitélio cúbico.', 'Placa limitante de hepatócitos em volta.'],
    aprofundado: ['Também contém linfáticos e nervos.', 'O ácino hepático de Rappaport se organiza a partir do eixo portal.'],
    funcoes: ['Levar sangue ao lóbulo e drenar a bile.'],
    regeneracao: { nivel: 'alta', texto: 'Proliferação ductular reativa após lesões.' },
    ondeEncontrar: ['Fígado.'],
    alteracoes: ['Hepatite de interface (atividade inflamatória).', 'Fibrose portal e em ponte.', 'Colangite biliar primária (destruição dos ductos).'],
  },
  {
    id: 'epitelio-simples-colunar',
    nome: 'Epitélio simples colunar',
    sinonimos: ['simple columnar epithelium'],
    tipo: 'epitelio',
    resumo: 'Uma camada de células mais altas que largas, com núcleos alinhados perto da base.',
    caracteristicas: ['Células colunares com núcleo oval basal, todas apoiadas na membrana basal.', 'Pode ter microvilosidades, cílios ou células caliciformes, conforme o órgão.'],
    aprofundado: ['Na vesícula biliar, as células concentram a bile reabsorvendo água e sal.'],
    funcoes: ['Absorção e secreção.'],
    regeneracao: { nivel: 'alta', texto: 'Renovação contínua.' },
    ondeEncontrar: ['Estômago, intestinos, vesícula biliar, tuba uterina, endométrio, ductos maiores.'],
    alteracoes: ['Metaplasia, displasia e adenocarcinoma.'],
  },
  {
    id: 'prega-da-mucosa',
    nome: 'Pregas da mucosa',
    sinonimos: ['pregas mucosas', 'mucosal folds'],
    tipo: 'orgao-parte',
    resumo: 'Dobras da mucosa, com eixo de lâmina própria, que aumentam a superfície e permitem distensão.',
    caracteristicas: ['Projeções finas e ramificadas recobertas pelo epitélio do órgão.'],
    aprofundado: ['Na vesícula biliar se achatam quando ela está cheia.'],
    funcoes: ['Aumentar a superfície de absorção e permitir distensão.'],
    regeneracao: { nivel: 'alta', texto: 'Mucosa renovável.' },
    ondeEncontrar: ['Vesícula biliar, tuba uterina, vesícula seminal, ureter.'],
    alteracoes: ['Seios de Rokitansky-Aschoff (divertículos da mucosa) na colecistite crônica.'],
  },
]
