import type { Estrutura } from '../tipos'

/** Órgãos linfoides e epitélios de revestimento associados. */
export const ESTRUTURAS_LINFOIDE: Estrutura[] = [
  {
    id: 'foliculo-linfoide',
    nome: 'Folículo linfoide (nódulo linfático)',
    sinonimos: ['nódulo linfoide', 'centro germinativo', 'folículo secundário', 'lymphoid follicle'],
    tipo: 'orgao-parte',
    resumo: 'Aglomerado arredondado de linfócitos B; quando ativado, tem um centro germinativo claro cercado por um manto escuro.',
    caracteristicas: [
      'Folículo primário: esfera uniforme de linfócitos pequenos.',
      'Folículo secundário: centro germinativo pálido (centroblastos, centrócitos, macrófagos com corpos tingíveis) e zona do manto escura.',
    ],
    aprofundado: ['No centro germinativo ocorrem a hipermutação somática e a troca de classe dos anticorpos, com seleção pelas células dendríticas foliculares.'],
    funcoes: ['Resposta imune humoral: ativação e maturação de linfócitos B.'],
    regeneracao: { nivel: 'alta', texto: 'Formam-se e involuem conforme a estimulação antigênica.' },
    ondeEncontrar: ['Córtex do linfonodo, polpa branca do baço, tonsilas, placas de Peyer, apêndice, MALT.'],
    alteracoes: ['Hiperplasia folicular reativa.', 'Linfoma folicular: folículos monótonos, sem polaridade nem corpos tingíveis (BCL2+).'],
  },
  {
    id: 'capsula-do-linfonodo',
    nome: 'Cápsula do linfonodo',
    sinonimos: ['cápsula', 'lymph node capsule'],
    tipo: 'camada',
    resumo: 'Conjuntivo denso que envolve o linfonodo; recebe os vasos linfáticos aferentes e emite trabéculas.',
    caracteristicas: ['Faixa fibrosa fina na periferia, com o seio subcapsular logo abaixo.'],
    aprofundado: ['Os linfáticos aferentes a perfuram em vários pontos; o eferente sai pelo hilo.'],
    funcoes: ['Delimitar e sustentar o linfonodo.'],
    regeneracao: { nivel: 'alta', texto: 'Conjuntivo.' },
    ondeEncontrar: ['Todo linfonodo.'],
    alteracoes: ['Invasão capsular e extensão extranodal de metástases (fator prognóstico).'],
  },
  {
    id: 'seio-subcapsular',
    nome: 'Seio subcapsular (marginal)',
    sinonimos: ['seio marginal', 'subcapsular sinus'],
    tipo: 'vaso',
    resumo: 'Espaço estreito sob a cápsula por onde a linfa aferente entra no linfonodo, atravessado por fibras reticulares e macrófagos.',
    caracteristicas: ['Faixa clara entre a cápsula e o córtex, com células esparsas.'],
    aprofundado: ['Continua-se com os seios trabeculares e medulares até o hilo.'],
    funcoes: ['Filtrar a linfa: macrófagos capturam antígenos e partículas.'],
    regeneracao: { nivel: 'alta', texto: 'Estrutura estromal renovável.' },
    ondeEncontrar: ['Linfonodos.'],
    alteracoes: ['É o primeiro lugar das micrometástases de carcinoma e melanoma.', 'Histiocitose sinusal reativa.'],
  },
  {
    id: 'fibras-reticulares',
    nome: 'Fibras reticulares',
    sinonimos: ['reticulina', 'colágeno tipo III', 'reticular fibers'],
    tipo: 'fibra',
    resumo: 'Fibras finas de colágeno III que formam uma rede de sustentação; invisíveis em HE, pretas na prata (argirófilas).',
    caracteristicas: ['Rede delicada e ramificada, preta na impregnação argêntica (Gomori, Gordon-Sweet).'],
    aprofundado: ['Produzidas por células reticulares (fibroblastos especializados) nos órgãos linfoides e hematopoéticos.'],
    funcoes: ['Arcabouço de órgãos linfoides, medula óssea, fígado e glândulas.'],
    regeneracao: { nivel: 'alta', texto: 'Primeiras fibras depositadas na cicatrização.' },
    ondeEncontrar: ['Linfonodos, baço, medula óssea, fígado (espaço de Disse), membranas basais.'],
    alteracoes: ['Mielofibrose (aumento de reticulina na medula).', 'Colapso da rede no fígado com necrose.'],
  },
  {
    id: 'polpa-branca',
    nome: 'Polpa branca do baço',
    sinonimos: ['white pulp', 'bainha linfoide periarteriolar', 'PALS', 'corpúsculo de Malpighi'],
    tipo: 'regiao',
    resumo: 'Tecido linfoide do baço em volta das arteríolas centrais: bainhas de linfócitos T e folículos B.',
    caracteristicas: ['Áreas densas e basófilas espalhadas na polpa vermelha, com arteríola central (excêntrica nos folículos).'],
    aprofundado: ['Zona marginal entre polpa branca e vermelha: macrófagos e linfócitos B que respondem a antígenos do sangue.'],
    funcoes: ['Resposta imune a antígenos do sangue.'],
    regeneracao: { nivel: 'alta', texto: 'Linfócitos renovados continuamente.' },
    ondeEncontrar: ['Baço.'],
    alteracoes: ['Hiperplasia em infecções; linfomas esplênicos da zona marginal.'],
  },
  {
    id: 'polpa-vermelha',
    nome: 'Polpa vermelha do baço',
    sinonimos: ['red pulp', 'cordões de Billroth', 'sinusoides esplênicos'],
    tipo: 'regiao',
    resumo: 'Maior parte do baço: cordões de Billroth e sinusoides venosos cheios de sangue, onde as hemácias velhas são retiradas.',
    caracteristicas: ['Tecido rico em hemácias, com sinusoides de endotélio alongado entre cordões celulares.'],
    aprofundado: ['As hemácias precisam se espremer pelas fendas da parede dos sinusoides; as rígidas ficam retidas e são fagocitadas.'],
    funcoes: ['Filtrar e remover hemácias velhas ou alteradas; reservar plaquetas e monócitos.'],
    regeneracao: { nivel: 'alta', texto: 'Tecido de alta renovação celular.' },
    ondeEncontrar: ['Baço.'],
    alteracoes: ['Congestão na hipertensão portal.', 'Hematopoese extramedular.', 'Sequestro de hemácias na esferocitose e anemia falciforme.'],
  },
  {
    id: 'trabecula-esplenica',
    nome: 'Trabécula esplênica',
    sinonimos: ['trabécula do baço'],
    tipo: 'orgao-parte',
    resumo: 'Septo de conjuntivo denso que parte da cápsula e leva artérias e veias trabeculares para dentro do baço.',
    caracteristicas: ['Faixas eosinófilas e densas, às vezes com vasos de parede fina (veias trabeculares).'],
    aprofundado: ['Em animais contém muito músculo liso (baço contrátil); no humano, pouco.'],
    funcoes: ['Sustentação e condução dos vasos.'],
    regeneracao: { nivel: 'alta', texto: 'Conjuntivo.' },
    ondeEncontrar: ['Baço.'],
    alteracoes: ['Nódulos de Gamna-Gandy (ferro e cálcio) na congestão crônica.'],
  },
  {
    id: 'cortex-timico',
    nome: 'Córtex do timo',
    sinonimos: ['cortex thymi'],
    tipo: 'regiao',
    resumo: 'Periferia do lóbulo tímico: timócitos em densidade máxima, por isso muito escura; é onde ocorre a seleção positiva.',
    caracteristicas: ['Faixa basófila densa de linfócitos pequenos, com células epiteliais reticulares e macrófagos (céu estrelado).'],
    aprofundado: ['Barreira hematotímica em volta dos capilares corticais.', 'Cerca de 95 % dos timócitos morrem por apoptose durante a seleção.'],
    funcoes: ['Maturação e seleção positiva dos linfócitos T.'],
    regeneracao: { nivel: 'baixa', texto: 'Involui com a idade (substituído por gordura); regenera após estresse agudo em jovens.' },
    ondeEncontrar: ['Timo.'],
    alteracoes: ['Involução acidental por estresse ou corticoides.', 'Timoma e linfoma linfoblástico T.'],
  },
  {
    id: 'medula-timica',
    nome: 'Medula do timo',
    sinonimos: ['medulla thymi'],
    tipo: 'regiao',
    resumo: 'Centro do lóbulo tímico, mais clara que o córtex, com células epiteliais abundantes e corpúsculos de Hassall.',
    caracteristicas: ['Zona pálida com menos linfócitos e mais células epiteliais reticulares.', 'Corpúsculos de Hassall.'],
    aprofundado: ['As células epiteliais medulares expressam antígenos de outros tecidos (AIRE) para a seleção negativa de clones autorreativos.'],
    funcoes: ['Seleção negativa e tolerância central; geração de linfócitos T reguladores.'],
    regeneracao: { nivel: 'baixa', texto: 'Involui com a idade.' },
    ondeEncontrar: ['Timo.'],
    alteracoes: ['Folículos linfoides na medula na miastenia grave (hiperplasia tímica).', 'Síndrome APECED (mutação do AIRE).'],
  },
  {
    id: 'corpusculo-de-hassall',
    nome: 'Corpúsculo de Hassall',
    sinonimos: ['corpúsculo tímico', "Hassall's corpuscle"],
    tipo: 'orgao-parte',
    resumo: 'Estrutura redonda e eosinófila na medula do timo, formada por células epiteliais achatadas em camadas concêntricas, às vezes queratinizadas.',
    caracteristicas: ['Espirais concêntricas de células epiteliais, centro eosinófilo ou calcificado.', '20–100 µm; exclusivo do timo.'],
    aprofundado: ['Produz TSLP, que ativa células dendríticas a induzir linfócitos T reguladores.'],
    funcoes: ['Participar da indução de tolerância na medula tímica.'],
    regeneracao: { nivel: 'nao-se-aplica', texto: 'Estrutura epitelial que aumenta de tamanho com a idade.' },
    ondeEncontrar: ['Medula do timo — serve para identificar o órgão.'],
    alteracoes: ['Calcificação e cistos com a idade.'],
  },
  {
    id: 'cripta-tonsilar',
    nome: 'Cripta tonsilar',
    sinonimos: ['cripta', 'tonsillar crypt'],
    tipo: 'orgao-parte',
    resumo: 'Invaginação profunda do epitélio da tonsila, que amplia a superfície de contato com antígenos da boca.',
    caracteristicas: ['Fenda revestida por epitélio estratificado pavimentoso, muitas vezes infiltrado por linfócitos (epitélio reticulado).', 'Pode conter restos celulares e bactérias.'],
    aprofundado: ['As células M do epitélio da cripta transportam antígenos para o tecido linfoide.'],
    funcoes: ['Amostrar antígenos da orofaringe.'],
    regeneracao: { nivel: 'alta', texto: 'Epitélio renovável.' },
    ondeEncontrar: ['Tonsilas palatinas (10–20 criptas ramificadas) e, rasas, na tonsila lingual.'],
    alteracoes: ['Cáseos tonsilares (tonsilólitos).', 'Tonsilite e abscesso periamigdaliano.', 'Carcinoma de orofaringe associado ao HPV nasce no epitélio da cripta.'],
  },
  {
    id: 'epitelio-estratificado-pavimentoso',
    nome: 'Epitélio estratificado pavimentoso',
    sinonimos: ['epitélio escamoso', 'squamous epithelium', 'não queratinizado'],
    tipo: 'epitelio',
    resumo: 'Várias camadas de células, as superficiais achatadas; resiste ao atrito. Pode ser queratinizado (pele) ou não (mucosas úmidas).',
    caracteristicas: ['Camada basal cúbica, camadas intermediárias poligonais e superfície achatada.', 'Não queratinizado: células superficiais mantêm o núcleo.'],
    aprofundado: ['Unido por desmossomos (pontes intercelulares visíveis na camada espinhosa).'],
    funcoes: ['Proteção contra atrito e desidratação.'],
    regeneracao: { nivel: 'alta', texto: 'Renovado pela camada basal.' },
    ondeEncontrar: ['Epiderme, boca, orofaringe, esôfago, vagina, colo do útero (ectocérvice), córnea.'],
    alteracoes: ['Carcinoma espinocelular.', 'Leucoplasia e displasia.', 'Metaplasia escamosa em epitélios glandulares.'],
  },
]
