import type { Estrutura } from '../tipos'

/** Órgãos linfoides e epitélios de revestimento associados. */
export const ESTRUTURAS_LINFOIDE: Estrutura[] = [
  {
    id: 'foliculo-linfoide',
    nome: 'Folículo linfoide (nódulo linfático)',
    sinonimos: ['nódulo linfoide', 'centro germinativo', 'folículo secundário', 'lymphoid follicle'],
    tipo: 'orgao-parte',
    resumo: 'Aglomerado arredondado de linfócitos B; quando ativado, tem um centro germinativo claro cercado por um manto escuro.',
    caracteristicas: [
      'Folículo primário: esfera uniforme de linfócitos pequenos.',
      'Folículo secundário: centro germinativo pálido (centroblastos, centrócitos, macrófagos com corpos tingíveis) e zona do manto escura.',
    ],
    aprofundado: ['No centro germinativo ocorrem a hipermutação somática e a troca de classe dos anticorpos, com seleção pelas células dendríticas foliculares.', 'Folículo primário: agregado uniforme de linfócitos B pequenos. Folículo secundário: centro germinativo claro + zona do manto escura.'],
    funcoes: ['Resposta imune humoral: ativação e maturação de linfócitos B.', 'Concentrar antígenos nas células dendríticas foliculares, para seleção dos linfócitos B.', 'Folículo secundário: gerar plasmócitos e linfócitos B de memória no centro germinativo.'],
    regeneracao: { nivel: 'alta', texto: 'Formam-se e involuem conforme a estimulação antigênica.' },
    ondeEncontrar: ['Córtex do linfonodo, polpa branca do baço, tonsilas, placas de Peyer, apêndice, MALT.'],
    alteracoes: ['Hiperplasia folicular reativa.', 'Linfoma folicular: folículos monótonos, sem polaridade nem corpos tingíveis (BCL2+).'],
  },
  {
    id: 'capsula-do-linfonodo',
    nome: 'Cápsula do linfonodo',
    sinonimos: ['cápsula', 'lymph node capsule'],
    tipo: 'camada',
    resumo: 'Conjuntivo denso que envolve o linfonodo; recebe os vasos linfáticos aferentes e emite trabéculas.',
    caracteristicas: ['Faixa fibrosa fina na periferia, com o seio subcapsular logo abaixo.', 'Conjuntivo denso fino que envolve o linfonodo; no hilo fica mais espessa e leva artéria, veia e linfático eferente.'],
    aprofundado: ['Os linfáticos aferentes a perfuram em vários pontos; o eferente sai pelo hilo.'],
    funcoes: ['Delimitar e sustentar o linfonodo.', 'Receber os vasos linfáticos aferentes, que atravessam a cápsula e desembocam no seio subcapsular.', 'Emitir trabéculas que dividem o córtex e levam vasos.'],
    regeneracao: { nivel: 'alta', texto: 'Conjuntivo.' },
    ondeEncontrar: ['Todo linfonodo.'],
    alteracoes: ['Invasão capsular e extensão extranodal de metástases (fator prognóstico).'],
  },
  {
    id: 'seio-subcapsular',
    nome: 'Seio subcapsular (marginal)',
    sinonimos: ['seio marginal', 'subcapsular sinus'],
    tipo: 'vaso',
    resumo: 'Espaço estreito sob a cápsula por onde a linfa aferente entra no linfonodo, atravessado por fibras reticulares e macrófagos.',
    caracteristicas: ['Faixa clara entre a cápsula e o córtex, com células esparsas.'],
    aprofundado: ['Continua-se com os seios trabeculares e medulares até o hilo.'],
    funcoes: ['Filtrar a linfa: macrófagos capturam antígenos e partículas.', 'Receber a linfa dos vasos aferentes e distribuí-la aos seios trabeculares.', 'Primeiro local onde chegam células tumorais metastáticas (exame do linfonodo sentinela).'],
    regeneracao: { nivel: 'alta', texto: 'Estrutura estromal renovável.' },
    ondeEncontrar: ['Linfonodos.'],
    alteracoes: ['É o primeiro lugar das micrometástases de carcinoma e melanoma.', 'Histiocitose sinusal reativa.'],
  },
  {
    id: 'fibras-reticulares',
    nome: 'Fibras reticulares',
    sinonimos: ['reticulina', 'colágeno tipo III', 'reticular fibers'],
    tipo: 'fibra',
    resumo: 'Fibras finas de colágeno III que formam uma rede de sustentação; invisíveis em HE, pretas na prata (argirófilas).',
    caracteristicas: ['Rede delicada e ramificada, preta na impregnação argêntica (Gomori, Gordon-Sweet).', 'Finas, ramificadas, em rede; invisíveis no HE e pretas na impregnação pela prata (argirofilia).'],
    aprofundado: ['Produzidas por células reticulares (fibroblastos especializados) nos órgãos linfoides e hematopoéticos.'],
    funcoes: ['Arcabouço de órgãos linfoides, medula óssea, fígado e glândulas.', 'Formar uma rede de colágeno III que sustenta células livres sem impedir que circulem.', 'Nos linfonodos, formar condutos que levam pequenas moléculas da linfa até as vênulas de endotélio alto.'],
    regeneracao: { nivel: 'alta', texto: 'Primeiras fibras depositadas na cicatrização.' },
    ondeEncontrar: ['Linfonodos, baço, medula óssea, fígado (espaço de Disse), membranas basais.'],
    alteracoes: ['Mielofibrose (aumento de reticulina na medula).', 'Colapso da rede no fígado com necrose.'],
  },
  {
    id: 'polpa-branca',
    nome: 'Polpa branca do baço',
    sinonimos: ['white pulp', 'bainha linfoide periarteriolar', 'PALS', 'corpúsculo de Malpighi'],
    tipo: 'regiao',
    resumo: 'Tecido linfoide do baço em volta das arteríolas centrais: bainhas de linfócitos T e folículos B.',
    caracteristicas: ['Áreas densas e basófilas espalhadas na polpa vermelha, com arteríola central (excêntrica nos folículos).', 'Nódulos azulados (linfócitos) espalhados na polpa vermelha, cada um com uma arteríola central.'],
    aprofundado: ['Zona marginal entre polpa branca e vermelha: macrófagos e linfócitos B que respondem a antígenos do sangue.'],
    funcoes: ['Resposta imune a antígenos do sangue.', 'Gerar anticorpos contra bactérias encapsuladas (pneumococo, meningococo, hemófilo): por isso a esplenectomia exige vacinação.', 'Abrigar linfócitos T na bainha periarteriolar e linfócitos B nos folículos.'],
    regeneracao: { nivel: 'alta', texto: 'Linfócitos renovados continuamente.' },
    ondeEncontrar: ['Baço.'],
    alteracoes: ['Hiperplasia em infecções; linfomas esplênicos da zona marginal.'],
  },
  {
    id: 'polpa-vermelha',
    nome: 'Polpa vermelha do baço',
    sinonimos: ['red pulp', 'cordões de Billroth', 'sinusoides esplênicos'],
    tipo: 'regiao',
    resumo: 'Maior parte do baço: cordões de Billroth e sinusoides venosos cheios de sangue, onde as hemácias velhas são retiradas.',
    caracteristicas: ['Tecido rico em hemácias, com sinusoides de endotélio alongado entre cordões celulares.'],
    aprofundado: ['As hemácias precisam se espremer pelas fendas da parede dos sinusoides; as rígidas ficam retidas e são fagocitadas.'],
    funcoes: ['Filtrar e remover hemácias velhas ou alteradas; reservar plaquetas e monócitos.', 'Retirar inclusões das hemácias sem destruí-las (corpúsculos de Howell-Jolly, Heinz), pelo "pitting".', 'Hematopoese extramedular em doenças da medula óssea e no feto.'],
    regeneracao: { nivel: 'alta', texto: 'Tecido de alta renovação celular.' },
    ondeEncontrar: ['Baço.'],
    alteracoes: ['Congestão na hipertensão portal.', 'Hematopoese extramedular.', 'Sequestro de hemácias na esferocitose e anemia falciforme.'],
  },
  {
    id: 'trabecula-esplenica',
    nome: 'Trabécula esplênica',
    sinonimos: ['trabécula do baço'],
    tipo: 'orgao-parte',
    resumo: 'Septo de conjuntivo denso que parte da cápsula e leva artérias e veias trabeculares para dentro do baço.',
    caracteristicas: ['Faixas eosinófilas e densas, às vezes com vasos de parede fina (veias trabeculares).', 'Faixas de conjuntivo denso, rosadas, que saem da cápsula e cruzam a polpa, muitas vezes com um vaso no meio.'],
    aprofundado: ['Em animais contém muito músculo liso (baço contrátil); no humano, pouco.'],
    funcoes: ['Sustentação e condução dos vasos.', 'Levar artérias e veias trabeculares da cápsula e do hilo para o interior do órgão.', 'Em alguns animais contém músculo liso que contrai e expulsa sangue armazenado (no homem, pouco).'],
    regeneracao: { nivel: 'alta', texto: 'Conjuntivo.' },
    ondeEncontrar: ['Baço.'],
    alteracoes: ['Nódulos de Gamna-Gandy (ferro e cálcio) na congestão crônica.'],
  },
  {
    id: 'cortex-timico',
    nome: 'Córtex do timo',
    sinonimos: ['cortex thymi'],
    tipo: 'regiao',
    resumo: 'Periferia do lóbulo tímico: timócitos em densidade máxima, por isso muito escura; é onde ocorre a seleção positiva.',
    caracteristicas: ['Faixa basófila densa de linfócitos pequenos, com células epiteliais reticulares e macrófagos (céu estrelado).'],
    aprofundado: ['Barreira hematotímica em volta dos capilares corticais.', 'Cerca de 95 % dos timócitos morrem por apoptose durante a seleção.'],
    funcoes: ['Maturação e seleção positiva dos linfócitos T.', 'Seleção positiva: sobrevivem só os timócitos que reconhecem MHC próprio apresentado pelas células epiteliais reticulares corticais.', 'Produzir grande quantidade de timócitos, dos quais mais de 95 % morrem por apoptose (macrófagos de corpos tingíveis).'],
    regeneracao: { nivel: 'baixa', texto: 'Involui com a idade (substituído por gordura); regenera após estresse agudo em jovens.' },
    ondeEncontrar: ['Timo.'],
    alteracoes: ['Involução acidental por estresse ou corticoides.', 'Timoma e linfoma linfoblástico T.'],
  },
  {
    id: 'medula-timica',
    nome: 'Medula do timo',
    sinonimos: ['medulla thymi'],
    tipo: 'regiao',
    resumo: 'Centro do lóbulo tímico, mais clara que o córtex, com células epiteliais abundantes e corpúsculos de Hassall.',
    caracteristicas: ['Zona pálida com menos linfócitos e mais células epiteliais reticulares.', 'Corpúsculos de Hassall.'],
    aprofundado: ['As células epiteliais medulares expressam antígenos de outros tecidos (AIRE) para a seleção negativa de clones autorreativos.'],
    funcoes: ['Seleção negativa e tolerância central; geração de linfócitos T reguladores.', 'Expressar antígenos de outros órgãos (gene AIRE) para eliminar os timócitos autorreativos.', 'Liberar os linfócitos T maduros para o sangue pelas vênulas da junção corticomedular.'],
    regeneracao: { nivel: 'baixa', texto: 'Involui com a idade.' },
    ondeEncontrar: ['Timo.'],
    alteracoes: ['Folículos linfoides na medula na miastenia grave (hiperplasia tímica).', 'Síndrome APECED (mutação do AIRE).'],
  },
  {
    id: 'corpusculo-de-hassall',
    nome: 'Corpúsculo de Hassall',
    sinonimos: ['corpúsculo tímico', "Hassall's corpuscle"],
    tipo: 'orgao-parte',
    resumo: 'Estrutura redonda e eosinófila na medula do timo, formada por células epiteliais achatadas em camadas concêntricas, às vezes queratinizadas.',
    caracteristicas: ['Espirais concêntricas de células epiteliais, centro eosinófilo ou calcificado.', '20–100 µm; exclusivo do timo.'],
    aprofundado: ['Produz TSLP, que ativa células dendríticas a induzir linfócitos T reguladores.'],
    funcoes: ['Participar da indução de tolerância na medula tímica.', 'Produzir TSLP, que instrui as células dendríticas a gerar linfócitos T reguladores.', 'Marcar a medula tímica: é o critério diagnóstico do timo em histologia.'],
    regeneracao: { nivel: 'nao-se-aplica', texto: 'Estrutura epitelial que aumenta de tamanho com a idade.' },
    ondeEncontrar: ['Medula do timo — serve para identificar o órgão.'],
    alteracoes: ['Calcificação e cistos com a idade.'],
  },
  {
    id: 'cripta-tonsilar',
    nome: 'Cripta tonsilar',
    sinonimos: ['cripta', 'tonsillar crypt'],
    tipo: 'orgao-parte',
    resumo: 'Invaginação profunda do epitélio da tonsila, que amplia a superfície de contato com antígenos da boca.',
    caracteristicas: ['Fenda revestida por epitélio estratificado pavimentoso, muitas vezes infiltrado por linfócitos (epitélio reticulado).', 'Pode conter restos celulares e bactérias.'],
    aprofundado: ['As células M do epitélio da cripta transportam antígenos para o tecido linfoide.'],
    funcoes: ['Amostrar antígenos da orofaringe.', 'Aumentar muito a superfície de contato com antígenos da boca e da faringe.', 'Seu epitélio reticulado (com células M) deixa linfócitos e antígenos passarem.'],
    regeneracao: { nivel: 'alta', texto: 'Epitélio renovável.' },
    ondeEncontrar: ['Tonsilas palatinas (10–20 criptas ramificadas) e, rasas, na tonsila lingual.'],
    alteracoes: ['Cáseos tonsilares (tonsilólitos).', 'Tonsilite e abscesso periamigdaliano.', 'Carcinoma de orofaringe associado ao HPV nasce no epitélio da cripta.'],
  },
  {
    id: 'epitelio-estratificado-pavimentoso',
    nome: 'Epitélio estratificado pavimentoso',
    sinonimos: ['epitélio escamoso', 'squamous epithelium', 'não queratinizado'],
    tipo: 'epitelio',
    resumo: 'Várias camadas de células, as superficiais achatadas; resiste ao atrito. Pode ser queratinizado (pele) ou não (mucosas úmidas).',
    caracteristicas: ['Camada basal cúbica, camadas intermediárias poligonais e superfície achatada.', 'Não queratinizado: células superficiais mantêm o núcleo.'],
    aprofundado: ['Unido por desmossomos (pontes intercelulares visíveis na camada espinhosa).'],
    funcoes: ['Proteção contra atrito e desidratação.', 'Renovar-se continuamente a partir da camada basal, repondo as células que descamam.', 'Na versão não queratinizada (boca, esôfago, vagina, córnea), manter a superfície úmida e flexível; na queratinizada (pele), impermeabilizar.', 'Barreira contra microrganismos (junções, descamação, peptídeos antimicrobianos).'],
    regeneracao: { nivel: 'alta', texto: 'Renovado pela camada basal.' },
    ondeEncontrar: ['Epiderme, boca, orofaringe, esôfago, vagina, colo do útero (ectocérvice), córnea.'],
    alteracoes: ['Carcinoma espinocelular.', 'Leucoplasia e displasia.', 'Metaplasia escamosa em epitélios glandulares.'],
  },
  {
    id: 'paracortex',
    nome: 'Paracórtex (zona T)',
    sinonimos: ['zona paracortical', 'córtex profundo'],
    tipo: 'regiao',
    resumo: 'Faixa difusa de linfócitos T entre os folículos e a medula do linfonodo, com vênulas de endotélio alto.',
    caracteristicas: ['Linfócitos densos sem formar folículos; vênulas com endotélio cúbico (HEV).', 'Zona de linfócitos pequenos, sem folículos, entre o córtex folicular e a medula.'],
    aprofundado: ['Pelas HEV os linfócitos entram no linfonodo; células dendríticas apresentam antígenos aos T.', 'Contém as vênulas de endotélio alto (endotélio cúbico), por onde os linfócitos saem do sangue.', 'Cresce muito nas respostas virais e é atrofiado na síndrome de DiGeorge (sem timo).'],
    funcoes: ['Resposta imune celular.', 'Receber linfócitos do sangue pelas vênulas de endotélio alto.', 'Local onde células dendríticas apresentam antígenos aos linfócitos T, que se ativam e proliferam.'],
    regeneracao: { nivel: 'alta', texto: 'Linfócitos recirculam.' },
    ondeEncontrar: ['Linfonodos.'],
    alteracoes: ['Hiperplasia paracortical nas infecções virais.', 'Aplasia na síndrome de DiGeorge.'],
  },
  {
    id: 'medula-do-linfonodo',
    nome: 'Medula do linfonodo (cordões e seios medulares)',
    sinonimos: ['cordões medulares', 'seios medulares'],
    tipo: 'regiao',
    resumo: 'Região central do linfonodo: cordões de plasmócitos e linfócitos separados por seios medulares claros.',
    caracteristicas: ['Cordões celulares ramificados alternando com espaços claros com macrófagos.', 'Cordões de linfócitos e plasmócitos separados por seios claros, perto do hilo.'],
    aprofundado: ['Os plasmócitos dos cordões secretam anticorpos na linfa eferente.'],
    funcoes: ['Filtrar a linfa e produzir anticorpos.', 'Abrigar plasmócitos nos cordões medulares, que secretam anticorpos na linfa eferente.', 'Filtrar a linfa nos seios medulares antes da saída pelo hilo.'],
    regeneracao: { nivel: 'alta', texto: 'Células renovadas.' },
    ondeEncontrar: ['Centro do linfonodo, junto ao hilo.'],
    alteracoes: ['Histiocitose sinusal reativa.'],
  },
  {
    id: 'centro-germinativo',
    nome: 'Centro germinativo',
    sinonimos: ['germinal center', 'centro claro do folículo'],
    tipo: 'regiao',
    resumo: 'Área central e mais clara de um folículo linfoide secundário, onde linfócitos B ativados proliferam e amadurecem a afinidade dos anticorpos.',
    caracteristicas: ['Mais claro que a coroa em volta, porque as células são maiores (centroblastos e centrócitos) e têm mais citoplasma.', 'Macrófagos com corpos apoptóticos ("macrófagos de corpos tingíveis") dão aspecto de "céu estrelado".', 'Polarizado: zona escura (centroblastos em mitose) voltada para dentro e zona clara (centrócitos e células dendríticas foliculares) voltada para a cápsula.'],
    aprofundado: ['Só aparece depois de estímulo antigênico: folículo sem centro = primário; com centro = secundário.', 'Na zona escura, os centroblastos sofrem hipermutação somática (enzima AID); na clara, só sobrevivem os que reconhecem bem o antígeno apresentado pelas células dendríticas foliculares, com ajuda dos linfócitos T auxiliares foliculares.', 'Ali também ocorre a troca de classe (IgM para IgG, IgA ou IgE).'],
    funcoes: ['Gerar anticorpos de alta afinidade (maturação da afinidade).', 'Produzir plasmócitos de vida longa e linfócitos B de memória — base da imunidade após infecção e vacinação.', 'Eliminar por apoptose os linfócitos B autorreativos ou de baixa afinidade.'],
    regeneracao: { nivel: 'alta', texto: 'Forma-se e desaparece conforme o estímulo antigênico, em dias a semanas.' },
    ondeEncontrar: ['Folículos secundários de linfonodos, baço (polpa branca), tonsilas, placas de Peyer e apêndice.'],
    alteracoes: ['Hiperplasia folicular reativa (infecções, artrite reumatoide, HIV inicial).', 'Linfoma folicular: folículos monótonos, sem polaridade e sem macrófagos de corpos tingíveis, com BCL2 positivo.', 'Linfoma de Burkitt: padrão em "céu estrelado" difuso.'],
  },
  {
    id: 'zona-do-manto',
    nome: 'Zona do manto (coroa do folículo)',
    sinonimos: ['coroa', 'manto', 'mantle zone'],
    tipo: 'regiao',
    resumo: 'Faixa escura de linfócitos B pequenos e virgens que envolve o centro germinativo como uma coroa.',
    caracteristicas: ['Células pequenas, com núcleo redondo e escuro e pouco citoplasma, muito juntas — por isso a faixa é basofílica.', 'Geralmente mais espessa do lado voltado para a cápsula.'],
    aprofundado: ['São linfócitos B que ainda não encontraram o antígeno (IgM e IgD de superfície), empurrados para a periferia pela expansão do centro germinativo.', 'No baço, por fora do manto existe ainda a zona marginal, com linfócitos B que respondem rápido a antígenos polissacarídicos do sangue.'],
    funcoes: ['Guardar linfócitos B virgens, prontos para entrar em uma resposta.', 'Delimitar o centro germinativo.'],
    regeneracao: { nivel: 'alta', texto: 'População em renovação constante por recirculação de linfócitos.' },
    ondeEncontrar: ['Folículos secundários de todos os órgãos linfoides.'],
    alteracoes: ['Linfoma de células do manto: proliferação de células pequenas com ciclina D1 (translocação t(11;14)).'],
  },
  {
    id: 'arteriola-central',
    nome: 'Arteríola central da polpa branca',
    sinonimos: ['artéria central', 'arteríola folicular'],
    tipo: 'vaso',
    resumo: 'Pequena artéria dentro da polpa branca do baço, envolvida por uma bainha de linfócitos T (bainha linfoide periarteriolar, PALS).',
    caracteristicas: ['Luz pequena, parede com poucas camadas de músculo liso, geralmente fora do centro do nódulo.', 'Em volta dela, linfócitos pequenos (zona T); o folículo B fica ao lado, deslocando a arteríola para a periferia.'],
    aprofundado: ['Ramo da artéria trabecular; depois da polpa branca continua como arteríolas peniciladas, que se abrem na polpa vermelha (circulação aberta) ou nos sinusoides (fechada).'],
    funcoes: ['Levar o sangue (e os antígenos que ele carrega) para dentro da polpa branca.', 'Servir de eixo para a bainha periarteriolar de linfócitos T.'],
    regeneracao: { nivel: 'moderada', texto: 'Vaso de parede renovável.' },
    ondeEncontrar: ['Polpa branca do baço.'],
    alteracoes: ['Lesões "em casca de cebola" (fibrose periarteriolar concêntrica) no lúpus eritematoso sistêmico.', 'Hialinose arteriolar na hipertensão.'],
  },
  {
    id: 'seio-medular',
    nome: 'Seio medular do linfonodo',
    sinonimos: ['seios medulares', 'medullary sinus'],
    tipo: 'regiao',
    resumo: 'Canais claros e largos na medula do linfonodo, entre os cordões medulares, por onde a linfa passa antes de sair pelo hilo.',
    caracteristicas: ['Espaços claros, frouxos, com macrófagos e poucos linfócitos, entre cordões mais escuros de células.', 'Revestidos por endotélio descontínuo e atravessados por fibras reticulares.'],
    aprofundado: ['Recebem a linfa dos seios subcapsular e trabeculares e a levam aos vasos linfáticos eferentes do hilo.'],
    funcoes: ['Última etapa de filtração da linfa: macrófagos fagocitam microrganismos, restos celulares e partículas.', 'Levar para a linfa eferente os anticorpos produzidos pelos plasmócitos dos cordões.'],
    regeneracao: { nivel: 'moderada', texto: 'Endotélio e macrófagos renováveis.' },
    ondeEncontrar: ['Medula dos linfonodos.'],
    alteracoes: ['Histiocitose sinusal reativa (linfonodos que drenam tumores ou inflamação).', 'Metástases que chegam pela linfa ocupam primeiro os seios.', 'Antracose: macrófagos com pigmento de carvão nos linfonodos do pulmão.'],
  },
]
