import type { Estrutura } from '../tipos'

/** Medula espinal: cornos, funículos, canal central, raízes e meninges. */
export const ESTRUTURAS_MEDULA_ESPINAL: Estrutura[] = [
  {
    id: 'corno-anterior',
    nome: 'Corno anterior (ventral) da medula',
    sinonimos: ['ventral horn', 'coluna anterior', 'corno ventral', 'lâminas VIII e IX de Rexed'],
    tipo: 'regiao',
    resumo: 'Projeção ventral da substância cinzenta, com os grandes neurônios motores que inervam o músculo esquelético.',
    caracteristicas: [
      'Mais largo e arredondado que o corno posterior.',
      'Contém neurônios grandes e multipolares (motoneurônios alfa), em grupos (colunas motoras), além de motoneurônios gama e interneurônios.',
      'Entre os neurônios, neurópilo com dendritos, axônios amielínicos e glia.',
      'Nas intumescências cervical (membros superiores) e lombar (membros inferiores) é muito mais volumoso.',
    ],
    aprofundado: [
      'Corresponde às lâminas VII–IX de Rexed. Os núcleos motores têm organização somatotópica: medial para musculatura axial, lateral para os membros; dorsal para flexores, ventral para extensores.',
      'Os axônios dos motoneurônios saem pela raiz anterior, que emerge do sulco anterolateral.',
      'As células de Renshaw (interneurônios inibitórios) fazem inibição recorrente dos próprios motoneurônios.',
    ],
    funcoes: ['Via final comum da motricidade: comando do músculo esquelético.', 'Reflexos segmentares (miotático, de retirada).', 'Abrigar os motoneurônios gama, que ajustam a sensibilidade dos fusos musculares e o tônus.'],
    regeneracao: { nivel: 'nula', texto: 'Motoneurônios perdidos não são repostos; o axônio periférico pode regenerar se o corpo celular sobreviver.' },
    ondeEncontrar: ['Toda a extensão da medula espinal; neurônios equivalentes nos núcleos motores dos nervos cranianos do tronco encefálico.'],
    alteracoes: [
      'Esclerose lateral amiotrófica: perda de motoneurônios com gliose; inclusões (corpos de Bunina, TDP-43).',
      'Poliomielite: destruição dos motoneurônios pelo poliovírus, com neuronofagia.',
      'Atrofia muscular espinal (gene SMN1): perda de motoneurônios na infância.',
    ],
  },
  {
    id: 'motoneuronio-alfa',
    nome: 'Motoneurônio alfa',
    sinonimos: ['neurônio motor inferior', 'alpha motor neuron', 'célula do corno anterior'],
    tipo: 'celula',
    resumo: 'Neurônio multipolar grande do corno anterior, com Nissl grosseiro, que inerva as fibras do músculo esquelético.',
    caracteristicas: [
      'Corpo celular grande (até 70–100 µm), poligonal, com vários dendritos saindo em direções diferentes.',
      'Núcleo grande, claro, central, com nucléolo evidente ("olho de coruja").',
      'Citoplasma cheio de corpúsculos de Nissl (retículo endoplasmático rugoso) — azul-violeta intenso na tionina.',
      'O cone de implantação do axônio não tem Nissl: aparece como área clara.',
    ],
    aprofundado: [
      'Os corpúsculos de Nissl refletem a enorme síntese proteica necessária para manter um axônio que pode passar de 1 m.',
      'Cada motoneurônio e as fibras musculares que ele inerva formam a unidade motora.',
      'Após secção do axônio ocorre cromatólise central: o Nissl se dispersa, o corpo incha e o núcleo vai para a periferia — sinal de tentativa de regeneração.',
    ],
    funcoes: ['Comanda a contração do músculo esquelético (placa motora, acetilcolina).', 'Formar a unidade motora: um motoneurônio e todas as fibras musculares que ele inerva (poucas nos músculos oculares, milhares no quadríceps) — quanto menor a unidade, mais fino o controle.', 'Integrar milhares de sinapses (tratos descendentes, aferências dos fusos, interneurônios) e decidir se dispara: é a "via final comum" de Sherrington.', 'Manter o trofismo do músculo: sem ele, a fibra atrofia e fibrila (sinais de neurônio motor inferior).'],
    regeneracao: { nivel: 'nula', texto: 'O corpo celular não se renova; o axônio periférico regenera cerca de 1–3 mm/dia se a bainha endoneural estiver preservada.' },
    ondeEncontrar: ['Corno anterior da medula espinal; núcleos motores dos nervos cranianos (III, IV, V, VI, VII, IX, X, XI, XII).'],
    alteracoes: ['Cromatólise (lesão axonal).', 'Degeneração na ELA e na atrofia muscular espinal.', 'Neuronofagia na poliomielite.'],
  },
  {
    id: 'corno-posterior',
    nome: 'Corno posterior (dorsal) da medula',
    sinonimos: ['dorsal horn', 'coluna posterior', 'corno dorsal', 'lâminas I–VI de Rexed'],
    tipo: 'regiao',
    resumo: 'Projeção dorsal, mais estreita, da substância cinzenta, onde chegam as fibras sensitivas da raiz posterior.',
    caracteristicas: [
      'Mais longo e estreito que o anterior, chegando quase à superfície no sulco posterolateral.',
      'Neurônios pequenos e médios, sem os grandes motoneurônios.',
      'No ápice, a substância gelatinosa (lâmina II), densa em neurônios pequenos e pobre em mielina.',
      'Recoberto na ponta pelo trato de Lissauer (dorsolateral).',
    ],
    aprofundado: [
      'Lâminas I (zona marginal) e II (substância gelatinosa): dor e temperatura (fibras Aδ e C); III–IV (núcleo próprio): tato; V: convergência visceral e somática, base da dor referida.',
      'É o local da "comporta da dor" (Melzack e Wall): interneurônios da lâmina II modulam a transmissão nociceptiva.',
    ],
    funcoes: ['Recepção e processamento da informação sensitiva (dor, temperatura, tato, propriocepção).', 'Retransmitir a sensibilidade ao encéfalo pelos tratos espinotalâmico, espinorreticular e espinocerebelares.', 'Modular a dor (comporta da dor e controle descendente por serotonina, noradrenalina e opioides).', 'Participar dos reflexos de retirada via interneurônios.'],
    regeneracao: { nivel: 'nula', texto: 'Neurônios centrais pós-mitóticos.' },
    ondeEncontrar: ['Toda a medula espinal; equivalente no núcleo espinal do trigêmeo, no tronco encefálico.'],
    alteracoes: [
      'Siringomielia: cavidade central que destrói as fibras que cruzam na comissura, com perda de dor e temperatura "em capa".',
      'Tabes dorsalis (neurossífilis): degeneração das raízes e dos funículos posteriores.',
      'Herpes-zóster: reativação viral no gânglio sensitivo, com inflamação que chega ao corno posterior.',
    ],
  },
  {
    id: 'canal-central',
    nome: 'Canal central da medula',
    sinonimos: ['central canal', 'canal ependimário', 'canal do epêndima'],
    tipo: 'regiao',
    resumo: 'Canal no centro da comissura cinzenta, revestido por epêndima, continuação do sistema ventricular.',
    caracteristicas: [
      'Pequena luz no meio da substância cinzenta central, entre as comissuras anterior e posterior.',
      'Revestido por células ependimárias cúbicas a cilíndricas, às vezes ciliadas.',
      'No adulto é frequentemente estreito, irregular ou obliterado por células ependimárias.',
    ],
    aprofundado: [
      'Continua o quarto ventrículo e termina numa dilatação no cone medular (ventrículo terminal).',
      'A obliteração com a idade é normal e não deve ser lida como doença.',
    ],
    funcoes: ['Resquício da luz do tubo neural; contém líquido cefalorraquidiano.', 'Serve de marco: fica na comissura cinzenta, entre as metades do H, e tem à frente a comissura branca anterior.', 'O epêndima que o reveste guarda células com potencial de célula-tronco, que proliferam após lesão medular.'],
    regeneracao: { nivel: 'baixa', texto: 'O epêndima tem células com potencial progenitor, ativadas após lesão medular, mas com regeneração muito limitada.' },
    ondeEncontrar: ['Toda a medula espinal; contínuo com o sistema ventricular do encéfalo.'],
    alteracoes: ['Hidromielia e siringomielia (dilatação ou cavidade).', 'Ependimoma: tumor intramedular mais comum no adulto.', 'Siringomielia e hidromielia (cavidades a partir do canal).'],
  },
  {
    id: 'ependima',
    nome: 'Epêndima',
    sinonimos: ['ependymal cells', 'células ependimárias', 'ependimócitos'],
    tipo: 'epitelio',
    resumo: 'Revestimento epitelioide de células gliais cúbicas a cilíndricas que forra os ventrículos e o canal central.',
    caracteristicas: [
      'Uma camada de células cúbicas a cilíndricas, justapostas, com núcleo ovalado.',
      'Superfície apical com cílios e microvilos.',
      'Sem lâmina basal verdadeira: repousa sobre prolongamentos gliais, não sobre conjuntivo.',
    ],
    aprofundado: [
      'É glia (derivada do neuroepitélio), embora pareça epitélio.',
      'Os tanicitos, variante do assoalho do terceiro ventrículo, têm prolongamentos longos até os capilares do hipotálamo.',
      'Nos plexos coroides o revestimento se modifica em epitélio coroide, que secreta o líquido cefalorraquidiano.',
    ],
    funcoes: ['Revestir as cavidades do SNC.', 'Movimentar o líquido cefalorraquidiano (batimento ciliar).', 'Troca entre líquor e parênquima.'],
    regeneracao: { nivel: 'baixa', texto: 'Proliferação limitada após lesão.' },
    ondeEncontrar: ['Ventrículos laterais, terceiro e quarto ventrículos, aqueduto cerebral e canal central da medula.'],
    alteracoes: ['Ependimoma (rosetas e pseudorrosetas perivasculares).', 'Ependimite granular (nódulos gliais subependimários após infecções).'],
  },
  {
    id: 'fissura-mediana-anterior',
    nome: 'Fissura mediana anterior',
    sinonimos: ['anterior median fissure', 'fissura ventral'],
    tipo: 'orgao-parte',
    resumo: 'Sulco profundo na face ventral da medula, que a divide em metades e leva os ramos sulcais da artéria espinal anterior.',
    caracteristicas: [
      'Fenda profunda revestida por pia-máter, que penetra até perto da comissura branca anterior.',
      'Contém vasos: os ramos sulcais (centrais) da artéria espinal anterior.',
      'É o marco que identifica o lado ventral num corte de medula.',
    ],
    aprofundado: [
      'O sulco mediano posterior (dorsal) é raso e continua por um septo glial; a fissura anterior é larga e profunda — é assim que se orienta o corte.',
      'A artéria espinal anterior irriga os dois terços anteriores da medula.',
    ],
    funcoes: ['Marco anatômico; conduz a irrigação da parte anterior da medula.', 'Orientar o corte: é o lado anterior (ventral) da medula.', 'Receber a artéria espinal anterior, cujos ramos sulcais penetram pelo fundo da fissura.'],
    regeneracao: { nivel: 'nao-se-aplica', texto: 'Estrutura anatômica, não um tecido.' },
    ondeEncontrar: ['Face ventral de toda a medula espinal; continua no bulbo, entre as pirâmides.'],
    alteracoes: ['Síndrome da artéria espinal anterior: infarto dos dois terços anteriores, com paralisia e perda de dor e temperatura, poupando a propriocepção.', 'Infarto da artéria espinal anterior: paralisia e perda de dor e temperatura abaixo da lesão, com propriocepção preservada (funículos posteriores são irrigados pelas artérias espinais posteriores).'],
  },
  {
    id: 'funiculo-anterior',
    nome: 'Funículo anterior',
    sinonimos: ['anterior funiculus', 'coluna branca anterior'],
    tipo: 'regiao',
    resumo: 'Substância branca entre a fissura mediana anterior e a saída das raízes ventrais.',
    caracteristicas: [
      'Fibras mielinizadas cortadas transversalmente; poucas células (glia).',
      'Limitado pela fissura mediana anterior e pelo sulco anterolateral.',
    ],
    aprofundado: [
      'Contém tratos descendentes posturais (corticoespinal anterior, vestibuloespinal, reticuloespinal, tectoespinal) e o espinotalâmico anterior.',
      'A comissura branca anterior, que o une ao lado oposto, é onde cruzam as fibras de dor e temperatura.',
    ],
    funcoes: ['Conduz tratos motores posturais e parte do tato grosseiro.', 'Controle da postura e do tônus da musculatura axial e proximal (vestibuloespinal, reticuloespinal).', 'Movimentos reflexos da cabeça em resposta a estímulos visuais e auditivos (tectoespinal).'],
    regeneracao: { nivel: 'baixa', texto: 'Axônios centrais não regeneram de forma funcional; a remielinização é parcial.' },
    ondeEncontrar: ['Toda a medula espinal.'],
    alteracoes: ['Degeneração walleriana após lesões de tratos descendentes.', 'Infarto na síndrome da artéria espinal anterior.'],
  },
  {
    id: 'funiculo-lateral',
    nome: 'Funículo lateral',
    sinonimos: ['lateral funiculus', 'coluna branca lateral'],
    tipo: 'regiao',
    resumo: 'Substância branca entre as raízes anterior e posterior, com os grandes tratos motor e da dor.',
    caracteristicas: [
      'Fibras mielinizadas de calibres variados, cortadas transversalmente.',
      'Ocupa a face lateral, entre os sulcos anterolateral e posterolateral.',
    ],
    aprofundado: [
      'Trato corticoespinal lateral (movimento voluntário fino), espinotalâmico lateral (dor e temperatura), espinocerebelares dorsal e ventral (propriocepção inconsciente) e rubroespinal.',
      'Organização somatotópica: no trato corticoespinal lateral as fibras dos membros inferiores ficam por fora, as dos superiores por dentro — por isso uma compressão externa atinge primeiro as pernas.',
    ],
    funcoes: ['Motricidade voluntária (corticoespinal) e sensibilidade térmica e dolorosa (espinotalâmico).', 'Propriocepção inconsciente para o cerebelo (espinocerebelares).', 'Controle autônomo descendente (fibras hipotalamoespinais para os neurônios simpáticos).'],
    regeneracao: { nivel: 'baixa', texto: 'Axônios centrais praticamente não regeneram.' },
    ondeEncontrar: ['Toda a medula espinal.'],
    alteracoes: ['Esclerose do trato corticoespinal na ELA.', 'Degeneração combinada subaguda (deficiência de B12), que acomete funículos laterais e posteriores.'],
  },
  {
    id: 'funiculo-posterior',
    nome: 'Funículo posterior',
    sinonimos: ['posterior funiculus', 'colunas dorsais', 'fascículo grácil', 'fascículo cuneiforme'],
    tipo: 'regiao',
    resumo: 'Substância branca entre os cornos posteriores: tato fino, vibração e propriocepção consciente.',
    caracteristicas: [
      'Fibras mielinizadas grossas, entre os dois cornos posteriores.',
      'Dividido pelo septo mediano posterior; acima de T6, cada lado tem fascículo grácil (medial) e cuneiforme (lateral).',
    ],
    aprofundado: [
      'São axônios dos neurônios dos gânglios sensitivos que sobem sem cruzar até os núcleos grácil e cuneiforme do bulbo (via coluna dorsal–lemnisco medial).',
      'Em colorações de mielina (Weil) o funículo posterior fica intensamente escuro.',
      'Fascículo grácil (medial) carrega fibras dos membros inferiores e da parte baixa do tronco; o cuneiforme (lateral, só acima de T6) carrega as dos membros superiores.',
    ],
    funcoes: ['Tato epicrítico, vibração, propriocepção consciente e estereognosia.', 'Levar ao córtex a posição das articulações sem precisar olhar (sinal de Romberg depende dele).', 'Discriminação entre dois pontos e reconhecimento de objetos pelo tato (estereognosia).'],
    regeneracao: { nivel: 'baixa', texto: 'Os ramos centrais dos neurônios sensitivos não regeneram dentro da medula.' },
    ondeEncontrar: ['Toda a medula espinal.'],
    alteracoes: ['Tabes dorsalis (neurossífilis): palidez dos funículos posteriores e ataxia sensitiva.', 'Deficiência de vitamina B12 e ataxia de Friedreich.'],
  },
  {
    id: 'radicula-posterior',
    nome: 'Radícula da raiz posterior (dorsal)',
    sinonimos: ['dorsal rootlet', 'raiz sensitiva', 'raiz dorsal'],
    tipo: 'fibra',
    resumo: 'Feixe de fibras sensitivas que entra na medula pelo sulco posterolateral, vindo do gânglio sensitivo.',
    caracteristicas: [
      'Feixe de fibras nervosas paralelas, com núcleos de células de Schwann, envolto por pia-máter.',
      'Entra na medula junto ao ápice do corno posterior.',
    ],
    aprofundado: [
      'Na zona de entrada ocorre a transição entre mielina periférica (Schwann) e central (oligodendrócito) — a zona de Obersteiner-Redlich.',
      'As fibras finas (dor) vão ao trato de Lissauer e ao corno posterior; as grossas sobem pelo funículo posterior.',
    ],
    funcoes: ['Trazer a informação sensitiva somática e visceral do segmento para a medula.', 'Levar as fibras grossas (tato e propriocepção) ao funículo posterior e as finas (dor e temperatura) ao trato de Lissauer.', 'Fechar o arco do reflexo miotático: a fibra Ia do fuso faz sinapse direta no motoneurônio alfa.'],
    regeneracao: { nivel: 'baixa', texto: 'A parte periférica pode regenerar, mas os axônios não atravessam a zona de entrada para dentro da medula (barreira glial).' },
    ondeEncontrar: ['Sulco posterolateral de cada segmento medular.'],
    alteracoes: ['Radiculopatia compressiva (hérnia de disco).', 'Tabes dorsalis.', 'Herpes-zóster no gânglio correspondente.'],
  },
  {
    id: 'pia-mater',
    nome: 'Pia-máter',
    sinonimos: ['pia mater', 'leptomeninge', 'meninge'],
    tipo: 'camada',
    resumo: 'Meninge mais interna, delicada, aderida à superfície do encéfalo e da medula, acompanhando todos os sulcos.',
    caracteristicas: [
      'Camada fina de células achatadas (meningoteliais) e fibras colágenas, colada ao tecido nervoso.',
      'Os vasos passam por ela antes de penetrar o parênquima.',
      'Acima dela, o espaço subaracnóideo com líquor e vasos, e a aracnoide.',
    ],
    aprofundado: [
      'Separada do tecido nervoso pela glia limitante (pés astrocitários com lâmina basal).',
      'Na medula forma os ligamentos denticulados, que a fixam lateralmente à dura-máter.',
    ],
    funcoes: ['Proteção e suporte vascular do sistema nervoso central.', 'Levar os vasos que penetram no tecido nervoso (acompanhados pelo espaço perivascular).', 'Fixar lateralmente a medula na dura-máter (ligamentos denticulados).'],
    regeneracao: { nivel: 'moderada', texto: 'Células meningoteliais proliferam e formam cicatriz fibrosa após lesão.' },
    ondeEncontrar: ['Toda a superfície do encéfalo e da medula espinal, inclusive dentro de sulcos e fissuras.'],
    alteracoes: ['Meningite (exsudato inflamatório no espaço subaracnóideo).', 'Hemorragia subaracnóidea.', 'Meningioma (tumor de células meningoteliais, sobretudo da aracnoide).'],
  },
  {
    id: 'substancia-gelatinosa',
    nome: 'Substância gelatinosa (de Rolando)',
    sinonimos: ['substantia gelatinosa', 'lâmina II de Rexed', 'Rolando'],
    tipo: 'regiao',
    resumo: 'Faixa em forma de capuz no ápice do corno posterior, de neurônios pequenos e muito juntos e quase sem mielina — a primeira estação da dor e da temperatura.',
    caracteristicas: [
      'Ocupa o ápice (cabeça) do corno posterior, logo abaixo da zona marginal (lâmina I).',
      'Neurônios pequenos e densamente agrupados, com pouco Nissl; neurópilo fino e homogêneo.',
      'Nas colorações de mielina fica clara (quase sem fibras mielinizadas), daí o aspecto "gelatinoso" a fresco.',
    ],
    aprofundado: [
      'Corresponde à lâmina II de Rexed; recebe as fibras amielínicas C e finas Aδ que chegam pela raiz posterior e pelo trato de Lissauer.',
      'Interneurônios inibitórios (GABA, glicina, encefalina) modulam a entrada nociceptiva — é a base anatômica da teoria do portão da dor.',
      'Rica em receptores opioides: é um dos alvos da morfina espinal e da analgesia epidural.',
    ],
    funcoes: ['Processamento e modulação da dor, temperatura e prurido antes da ascensão ao encéfalo.', 'Integrar as fibras finas (Aδ e C) que chegam pelo trato de Lissauer.', 'Local de ação dos opioides espinais: receptores mu na terminação pré-sináptica reduzem a liberação de glutamato e substância P.'],
    regeneracao: { nivel: 'nula', texto: 'Neurônios do SNC: não se regeneram; lesões deixam gliose.' },
    ondeEncontrar: ['Ápice do corno posterior em toda a medula; continua no núcleo espinal do trigêmeo, no bulbo.'],
    alteracoes: [
      'Siringomielia: a cavidade central interrompe as fibras que cruzam na comissura, com perda da dor e temperatura "em xale".',
      'Herpes-zóster: inflamação do gânglio sensitivo e do corno posterior correspondente.',
      'Dor neuropática crônica: perda de interneurônios inibitórios e sensibilização central.',
    ],
  },
  {
    id: 'neuronio-do-corno-posterior',
    nome: 'Neurônio sensitivo do corno posterior (de 2ª ordem)',
    sinonimos: ['neurônio do corno dorsal', 'neurônio de projeção do corno posterior', 'neurônio do núcleo próprio', 'neurônio sensitivo da medula'],
    tipo: 'celula',
    resumo: 'Neurônio de tamanho pequeno a médio do corno posterior, que recebe as fibras dos neurônios sensitivos do gânglio da raiz dorsal e leva a informação adiante (neurônio de 2ª ordem) ou a modula (interneurônio).',
    caracteristicas: ['Corpo celular menor que o do motoneurônio alfa (cerca de 10–40 µm), fusiforme, triangular ou estrelado, com Nissl mais fino.', 'Núcleo claro com nucléolo visível; em volta, neurópilo com muitos núcleos pequenos de glia.', 'Pequenos e muito numerosos no ápice (substância gelatinosa); médios no núcleo próprio e na base do corno.', 'O corpo do neurônio sensitivo PRIMÁRIO não está na medula: fica no gânglio da raiz dorsal (neurônio pseudounipolar).'],
    aprofundado: ['Organização em lâminas de Rexed: I (zona marginal, neurônios de projeção para dor), II (substância gelatinosa, interneurônios), III–IV (núcleo próprio: tato e pressão), V (neurônios de ampla faixa dinâmica, que convergem estímulos da pele e das vísceras), VI (propriocepção, só nas intumescências).', 'Os neurônios de projeção das lâminas I e V enviam axônios que cruzam na comissura branca anterior e sobem no funículo lateral contralateral como trato espinotalâmico (dor e temperatura) — por isso a lesão de meia medula (Brown-Séquard) tira dor e temperatura do lado oposto.', 'A convergência de aferências viscerais e cutâneas no mesmo neurônio da lâmina V explica a dor referida (dor do infarto no braço esquerdo, da vesícula no ombro direito).', 'Neurotransmissor da aferência primária: glutamato, com substância P e CGRP nas fibras C; os interneurônios inibitórios usam GABA, glicina e encefalinas.', 'No segmento T1–L2, na base do corno posterior, o núcleo dorsal de Clarke tem neurônios grandes que originam o trato espinocerebelar dorsal (propriocepção inconsciente).'],
    funcoes: ['Receber a informação dos neurônios sensitivos primários (dor, temperatura, tato, pressão, propriocepção) e retransmiti-la ao tálamo, ao tronco encefálico e ao cerebelo.', 'Originar os tratos ascendentes: espinotalâmico lateral e anterior, espinorreticular, espinomesencefálico e espinocerebelares.', 'Modular a dor antes de ela subir (comporta da dor): interneurônios inibitórios e as vias descendentes da substância cinzenta periaquedutal e do núcleo magno da rafe (serotonina, noradrenalina, opioides) reduzem a transmissão.', 'Participar dos reflexos segmentares, como o reflexo de retirada (flexor), por meio de interneurônios que ativam motoneurônios do corno anterior.'],
    regeneracao: { nivel: 'nula', texto: 'Neurônios centrais pós-mitóticos: não se renovam. Depois de lesão, o circuito se reorganiza (plasticidade), o que contribui para a dor neuropática.' },
    ondeEncontrar: ['Corno posterior de toda a medula espinal; equivalentes no núcleo espinal do trigêmeo (face) e nos núcleos grácil e cuneiforme do bulbo (3ª ordem é o tálamo).'],
    alteracoes: ['Sensibilização central: após dor intensa ou prolongada, esses neurônios passam a responder a estímulos leves (alodinia e hiperalgesia) — base da dor crônica e da fibromialgia.', 'Siringomielia: a cavidade destrói primeiro as fibras que cruzam na comissura, com perda de dor e temperatura "em capa" e tato preservado.', 'Herpes-zóster e neuralgia pós-herpética: inflamação do gânglio que se estende ao corno posterior.', 'Tabes dorsalis (neurossífilis): degeneração das raízes posteriores e dos funículos posteriores, com ataxia sensitiva.'],
  },
  {
    id: 'comissura-cinzenta',
    nome: 'Comissura cinzenta',
    sinonimos: ['comissura cinzenta central', 'substância cinzenta intermédia central', 'lâmina X de Rexed'],
    tipo: 'regiao',
    resumo: 'Faixa transversal de substância cinzenta que une as duas metades do "H" da medula e contém, no centro, o canal central.',
    caracteristicas: ['Barra de neurópilo com neurônios pequenos, entre os cornos dos dois lados.', 'O canal central, revestido de epêndima, fica no meio dela.', 'Dividida em parte anterior (à frente do canal) e posterior (atrás do canal).'],
    aprofundado: ['Corresponde à lâmina X de Rexed: neurônios que recebem aferências viscerais e nociceptivas dos dois lados.', 'À frente dela, entre o canal e o fundo da fissura mediana anterior, passa a comissura branca anterior.'],
    funcoes: ['Ligar as duas metades da substância cinzenta: integração bilateral de reflexos e de informação visceral.', 'Processar dor visceral e da linha média (inclusive a via visceral da coluna dorsal, importante na dor pélvica).', 'Abrigar o canal central, resquício da luz do tubo neural.'],
    regeneracao: { nivel: 'nula', texto: 'Neurônios pós-mitóticos; o epêndima em volta do canal tem células com potencial de célula-tronco que proliferam após lesão.' },
    ondeEncontrar: ['Toda a extensão da medula espinal.'],
    alteracoes: ['Siringomielia: cavidade que se expande a partir do canal central e destrói a comissura.', 'Hidromielia: dilatação do próprio canal central.'],
  },
  {
    id: 'comissura-branca-anterior',
    nome: 'Comissura branca anterior',
    sinonimos: ['comissura branca ventral', 'comissura anterior da medula'],
    tipo: 'regiao',
    resumo: 'Faixa de axônios mielinizados que cruzam a linha média entre o fundo da fissura mediana anterior e a comissura cinzenta.',
    caracteristicas: ['Fica logo à frente do canal central, no fundo da fissura mediana anterior.', 'Fibras correm no plano do corte, de um lado para o outro; em Nissl aparece como neurópilo claro e fibroso, e em Weil fica escura.'],
    aprofundado: ['É onde cruzam os axônios dos neurônios de 2ª ordem do corno posterior que formam o trato espinotalâmico: sobem um ou dois segmentos e cruzam aqui.', 'Também cruzam fibras do trato corticoespinal anterior (no seu nível de término) e axônios de interneurônios comissurais que coordenam os dois lados.'],
    funcoes: ['Cruzar a via da dor e da temperatura (espinotalâmica) para o lado oposto.', 'Coordenar os dois lados da medula (locomoção alternada, reflexos bilaterais) por meio de interneurônios comissurais.'],
    regeneracao: { nivel: 'nula', texto: 'Axônios centrais praticamente não regeneram.' },
    ondeEncontrar: ['Toda a medula espinal, na frente do canal central.'],
    alteracoes: ['Siringomielia: a cavidade central rompe primeiro estas fibras — perda bilateral e segmentar de dor e temperatura com tato preservado (dissociação siringomiélica).', 'Cordotomia anterolateral e mielotomia comissural: cirurgias para dor intratável que interrompem essa via.'],
  },
  {
    id: 'trato-dorsolateral',
    nome: 'Trato dorsolateral (de Lissauer)',
    sinonimos: ['trato de Lissauer', 'fascículo dorsolateral', 'zona de Lissauer'],
    tipo: 'regiao',
    resumo: 'Faixa estreita de fibras finas, pouco mielinizadas, entre o ápice do corno posterior e a superfície da medula, onde entra a raiz posterior.',
    caracteristicas: ['Fica como um "capuz" claro sobre a ponta do corno posterior, junto à zona de entrada da raiz dorsal.', 'Axônios finos (Aδ e C), por isso cora pouco nas colorações de mielina.'],
    aprofundado: ['Ao entrarem, as fibras de dor e temperatura sobem ou descem um ou dois segmentos no trato de Lissauer antes de fazer sinapse nas lâminas I e II.', 'Contém também axônios de neurônios da substância gelatinosa que ligam segmentos vizinhos.'],
    funcoes: ['Distribuir a informação de dor e temperatura para segmentos vizinhos da medula.', 'Levar a aferência nociceptiva para a substância gelatinosa e a zona marginal.'],
    regeneracao: { nivel: 'nula', texto: 'Axônios centrais: regeneração mínima.' },
    ondeEncontrar: ['Toda a medula espinal, no ápice do corno posterior.'],
    alteracoes: ['A extensão por segmentos vizinhos explica por que a perda de dor numa lesão medular começa 1–2 segmentos abaixo do nível da lesão.', 'Lesionado na rizotomia dorsal e na DREZotomia (lesão da zona de entrada da raiz dorsal), cirurgias para dor após avulsão do plexo braquial.'],
  },
  {
    id: 'septo-mediano-posterior',
    nome: 'Sulco e septo mediano posterior',
    sinonimos: ['septo mediano dorsal', 'sulco mediano posterior', 'sulco mediano dorsal'],
    tipo: 'regiao',
    resumo: 'Sulco raso na face posterior da medula que se continua, para dentro, com um septo fino de glia até a comissura cinzenta, separando os dois funículos posteriores.',
    caracteristicas: ['Diferente da fissura anterior, é raso: o que se vê é uma linha fina, quase reta, do sulco até o canal central.', 'Formado por astrócitos (septo glial) e pequenos vasos.'],
    aprofundado: ['Nos níveis cervical e torácico alto, um septo intermédio posterior separa, de cada lado, o fascículo grácil (medial, fibras dos membros inferiores) do cuneiforme (lateral, fibras dos membros superiores).'],
    funcoes: ['Separar os funículos posteriores direito e esquerdo.', 'Servir de marco para orientar o corte: o lado com fissura larga e profunda é o anterior; o com sulco raso e septo é o posterior.'],
    regeneracao: { nivel: 'nao-se-aplica', texto: 'Estrutura glial de sustentação.' },
    ondeEncontrar: ['Face posterior de toda a medula espinal.'],
    alteracoes: ['Mielotomia mediana posterior (punctata): pequena lesão cirúrgica aqui alivia a dor visceral do câncer pélvico, por interromper a via visceral da coluna dorsal.'],
  },
  {
    id: 'zona-intermedia',
    nome: 'Zona intermédia da medula',
    sinonimos: ['lâmina VII de Rexed', 'substância cinzenta intermédia', 'zona intermediária'],
    tipo: 'regiao',
    resumo: 'Região da substância cinzenta entre o corno anterior e o posterior, com interneurônios de tamanho médio e, nos segmentos torácicos, o corno lateral.',
    caracteristicas: ['Neurônios médios, dispersos, entre os grandes motoneurônios (anterior) e os pequenos neurônios sensitivos (posterior).', 'Em T1–L2 projeta-se lateralmente como corno lateral (coluna intermédio-lateral); na base do corno posterior, o núcleo dorsal de Clarke.'],
    aprofundado: ['Corresponde à lâmina VII de Rexed.', 'Coluna intermédio-lateral (T1–L2): neurônios pré-ganglionares simpáticos, cujos axônios saem pela raiz anterior e pelo ramo comunicante branco. Em S2–S4, o núcleo parassimpático sacral ocupa a posição equivalente.', 'Contém interneurônios que formam geradores centrais de padrão (ritmo da marcha) e as células de Renshaw (na junção com o corno anterior).'],
    funcoes: ['Integrar a informação sensitiva e descendente e distribuí-la aos motoneurônios (interneurônios).', 'Originar o comando autônomo simpático (T1–L2) e parassimpático sacral (S2–S4).', 'Originar o trato espinocerebelar dorsal (núcleo de Clarke), que leva propriocepção inconsciente ao cerebelo.'],
    regeneracao: { nivel: 'nula', texto: 'Neurônios pós-mitóticos.' },
    ondeEncontrar: ['Toda a medula; corno lateral nítido apenas de T1 a L2.'],
    alteracoes: ['Lesão medular acima de T6: perda do controle simpático descendente e disreflexia autonômica.', 'Síndrome de Horner por lesão da coluna intermédio-lateral em C8–T1.'],
  },
]
