import type { Estrutura } from '../tipos'

/** Músculo e mucosas que aparecem junto a ele. */
export const ESTRUTURAS_MUSCULO: Estrutura[] = [
  {
    id: 'estriacao-transversal',
    nome: 'Estriação transversal (sarcômeros)',
    sinonimos: ['estrias', 'banda A', 'banda I', 'linha Z', 'sarcômero'],
    tipo: 'fibra',
    resumo: 'Faixas alternadas escuras (A) e claras (I) que cruzam a fibra muscular estriada, formadas pelo alinhamento dos sarcômeros.',
    caracteristicas: [
      'Bandas A escuras (anisotrópicas) e I claras (isotrópicas), perpendiculares ao eixo da fibra.',
      'Linha Z no meio da banda I; zona H no meio da banda A (em grande aumento ou ME).',
      'Mais nítidas em cortes semifinos e com hematoxilina férrica.',
    ],
    aprofundado: [
      'Sarcômero (linha Z a linha Z, ~2,5 µm): filamentos finos de actina ancorados na linha Z e grossos de miosina na banda A.',
      'Na contração, as bandas I e H encurtam e a A não muda (teoria dos filamentos deslizantes).',
    ],
    funcoes: ['Unidade contrátil do músculo estriado.', 'Mostrar o alinhamento dos sarcômeros: bandas A (miosina, escuras) e I (actina, claras), linha Z no meio da banda I.', 'Na contração, a banda I e a zona H encurtam e a banda A não muda (teoria do deslizamento dos filamentos).'],
    regeneracao: { nivel: 'nao-se-aplica', texto: 'Estrutura da miofibrila; refeita nas fibras regeneradas.' },
    ondeEncontrar: ['Músculo esquelético e músculo cardíaco.'],
    alteracoes: ['Perda de estrias na necrose muscular; bandas de contração no infarto e na reperfusão.', 'Corpos em bastão (nemalínicos) nas miopatias congênitas.'],
  },
  {
    id: 'nucleo-periferico-da-fibra-muscular',
    nome: 'Núcleos periféricos da fibra esquelética',
    sinonimos: ['núcleo subsarcolemal', 'mionúcleo'],
    tipo: 'celula',
    resumo: 'Muitos núcleos achatados logo abaixo do sarcolema — característica que separa o músculo esquelético do cardíaco e do liso.',
    caracteristicas: ['Alongados, na borda da fibra, em número de centenas por fibra.', 'Em corte transversal: 1–3 núcleos na periferia de cada perfil poligonal.'],
    aprofundado: ['Células satélites (tronco) ficam entre o sarcolema e a lâmina basal, com núcleo semelhante.', 'A fibra se forma pela fusão de mioblastos, por isso tem centenas de núcleos; as células satélites, sob a lâmina basal, são as células-tronco que regeneram a fibra.'],
    funcoes: ['Controlar a síntese proteica de trechos da fibra (domínios mionucleares).', 'Distinguir o músculo esquelético (núcleos periféricos, fibra multinucleada) do cardíaco e do liso (núcleo central).'],
    regeneracao: { nivel: 'moderada', texto: 'Fibras regeneradas mostram núcleos centrais por algum tempo.' },
    ondeEncontrar: ['Músculo esquelético.'],
    alteracoes: ['Núcleos centrais em muitas fibras: miopatias (miotubular, distrofias) e regeneração.', 'Núcleos centrais em muitas fibras indicam regeneração ou miopatia (distrofias, miopatia centronuclear).'],
  },
  {
    id: 'endomisio',
    nome: 'Endomísio',
    sinonimos: ['endomysium'],
    tipo: 'camada',
    resumo: 'Conjuntivo delicado em volta de cada fibra muscular, com capilares.',
    caracteristicas: ['Fina camada entre fibras vizinhas, com fibras reticulares e capilares.', 'Camada delicada de fibras reticulares e lâmina basal em volta de cada fibra, com capilares.'],
    aprofundado: ['Junto com a lâmina basal, transmite a força da fibra ao tendão.', 'Cada fibra fica rodeada por 3 a 4 capilares no músculo de contração lenta, menos no rápido.'],
    funcoes: ['Sustentar cada fibra e levar capilares até ela.', 'Transmitir a força de cada fibra ao tendão.', 'Conter a lâmina basal que guia a regeneração da fibra.'],
    regeneracao: { nivel: 'alta', texto: 'Conjuntivo.' },
    ondeEncontrar: ['Entre as fibras de todo músculo esquelético.'],
    alteracoes: ['Fibrose endomisial nas distrofias musculares.', 'Infiltrado inflamatório endomisial na polimiosite.'],
  },
  {
    id: 'perimisio',
    nome: 'Perimísio',
    sinonimos: ['perimysium', 'septo muscular'],
    tipo: 'camada',
    resumo: 'Septo de conjuntivo que envolve cada fascículo de fibras musculares, com vasos e nervos maiores.',
    caracteristicas: ['Faixas mais largas separando grupos de fibras (fascículos).', 'Contém arteríolas, vênulas e nervos.'],
    aprofundado: ['O epimísio envolve o músculo inteiro e se continua com os septos do perimísio.'],
    funcoes: ['Organizar o músculo em fascículos e distribuir vasos e nervos.', 'Conter os fusos musculares (receptores de estiramento).', 'Permitir que os fascículos deslizem entre si durante a contração.'],
    regeneracao: { nivel: 'alta', texto: 'Conjuntivo.' },
    ondeEncontrar: ['Músculo esquelético.'],
    alteracoes: ['Atrofia perifascicular na dermatomiosite.', 'Infiltrado perimisial perivascular nas miosites.'],
  },
  {
    id: 'feixe-de-musculo-liso',
    nome: 'Feixe de músculo liso',
    sinonimos: ['fascículo de músculo liso', 'detrusor'],
    tipo: 'orgao-parte',
    resumo: 'Grupo de células musculares lisas paralelas, separado dos vizinhos por conjuntivo; nas vísceras, os feixes correm em direções diferentes.',
    caracteristicas: ['Faixas eosinófilas homogêneas com núcleos alongados, separadas por septos claros.', 'No mesmo corte aparecem feixes longitudinais e transversais.'],
    aprofundado: ['Na bexiga (detrusor), os feixes se entrelaçam em três camadas mal definidas, o que permite esvaziar em todas as direções.', 'Em corte transversal, as células aparecem com diâmetros diferentes e poucos núcleos (o núcleo só aparece nas células cortadas no meio); em corte longitudinal, núcleos alongados "em charuto".'],
    funcoes: ['Contração coordenada da parede das vísceras.', 'Gerar peristaltismo e tônus nas vísceras ocas.', 'Controlar o calibre de vasos, brônquios e ductos.'],
    regeneracao: { nivel: 'moderada', texto: 'Hipertrofia e hiperplasia sob sobrecarga.' },
    ondeEncontrar: ['Bexiga, útero, trato gastrointestinal, vasos, vias aéreas.'],
    alteracoes: ['Hipertrofia trabeculada do detrusor na obstrução prostática.', 'Hipertrofia (bexiga de esforço, asma).', 'Leiomioma (tumor benigno comum no útero).'],
  },
  {
    id: 'urotelio',
    nome: 'Urotélio (epitélio de transição)',
    sinonimos: ['epitélio de transição', 'urothelium', 'células em guarda-chuva'],
    tipo: 'epitelio',
    resumo: 'Epitélio estratificado das vias urinárias, cujas células superficiais grandes (em guarda-chuva) mudam de forma com a distensão.',
    caracteristicas: [
      'Várias camadas (3–7 na bexiga vazia): basal, intermediárias e superficiais.',
      'Células superficiais grandes, às vezes binucleadas, com citoplasma eosinófilo denso na borda apical.',
      'Na bexiga cheia, fica fino (2–3 camadas) e achatado.',
    ],
    aprofundado: ['A membrana apical tem placas de uroplaquinas: barreira impermeável à urina.', 'Vesículas fusiformes guardam membrana que se insere na distensão.'],
    funcoes: ['Barreira contra a urina hipertônica e tóxica, permitindo grande distensão.', 'Permitir grande variação de volume: as células em guarda-chuva mudam de forma e inserem vesículas de membrana ao se distender.', 'Impedir a passagem de água e ureia (placas de uroplaquina e junções de oclusão).'],
    regeneracao: { nivel: 'alta', texto: 'Normalmente lento, mas regenera rápido após lesão.' },
    ondeEncontrar: ['Pelve renal, ureter, bexiga e parte da uretra.'],
    alteracoes: ['Carcinoma urotelial (papilar ou in situ).', 'Cistite; metaplasia escamosa (esquistossomose).', 'Ninhos de von Brunn e cistite cística (reativos).'],
  },
  {
    id: 'lamina-propria',
    nome: 'Lâmina própria',
    sinonimos: ['lamina propria', 'córion'],
    tipo: 'camada',
    resumo: 'Conjuntivo frouxo logo abaixo do epitélio de uma mucosa, com vasos, nervos e células de defesa.',
    caracteristicas: ['Conjuntivo frouxo celular, com capilares e linfócitos, entre o epitélio e a camada seguinte.', 'Tecido conjuntivo frouxo, rico em células, logo abaixo do epitélio de uma mucosa.'],
    aprofundado: ['Sustenta e nutre o epitélio; é a primeira linha imune das mucosas.', 'Com o epitélio e a muscular da mucosa (quando existe), forma a mucosa.'],
    funcoes: ['Nutrir o epitélio e abrigar a defesa imune da mucosa.', 'Sustentar o epitélio e levar capilares e vasos linfáticos até ele.', 'Abrigar linfócitos, plasmócitos (IgA), macrófagos e mastócitos: primeira linha de defesa da mucosa.', 'Nos intestinos, absorver e transportar lipídios (quilíferos) e água.'],
    regeneracao: { nivel: 'alta', texto: 'Conjuntivo bem vascularizado.' },
    ondeEncontrar: ['Todas as mucosas: digestiva, respiratória, urinária, genital.'],
    alteracoes: ['Infiltrado inflamatório (cistite, gastrite, colite).', 'Invasão da lâmina própria define estadiamento de carcinomas (pT1).'],
  },
]
