import type { Estrutura } from '../tipos'

const OSSO = (e: Estrutura): Estrutura => e

/** Osso, cartilagem e ossificação. */
export const ESTRUTURAS_OSSO: Estrutura[] = [
  OSSO({
    id: 'osteon',
    nome: 'Ósteon (sistema de Havers)',
    sinonimos: ['osteon', 'sistema haversiano', 'Havers'],
    tipo: 'orgao-parte',
    resumo: 'Unidade do osso compacto: cilindro de 4 a 20 lamelas concêntricas em volta de um canal central com vasos.',
    caracteristicas: [
      'Lamelas concêntricas com lacunas de osteócitos entre elas.',
      'Canal de Havers no centro; limite externo marcado pela linha cimentante.',
      'Diâmetro de 100–400 µm, eixo paralelo ao maior eixo do osso.',
    ],
    aprofundado: [
      'As fibras colágenas mudam de direção de uma lamela para a outra (padrão em "compensado"), o que dá resistência.',
      'Formado pela unidade de remodelação: osteoclastos escavam um túnel (cone de corte) e osteoblastos o preenchem em camadas.',
    ],
    funcoes: ['Resistência mecânica do osso cortical.', 'Nutrição dos osteócitos a partir do canal central.'],
    regeneracao: { nivel: 'alta', texto: 'O osso cortical é remodelado continuamente (~5 % ao ano no adulto) e se consolida após fratura.' },
    ondeEncontrar: ['Diáfise dos ossos longos e cortical de todos os ossos.'],
    alteracoes: ['Osteoporose: ósteons com canais alargados e cortical porosa.', 'Doença de Paget: padrão em mosaico de linhas cimentantes.'],
  }),
  OSSO({
    id: 'canal-de-havers',
    nome: 'Canal de Havers',
    sinonimos: ['Haversian canal', 'canal central'],
    tipo: 'vaso',
    resumo: 'Canal central do ósteon, com capilares, vênulas e nervos, revestido por células osteoprogenitoras.',
    caracteristicas: ['Orifício redondo de 20–100 µm no centro das lamelas concêntricas.', 'Escuro no osso desgastado (cheio de resíduo); claro com vaso nos cortes descalcificados.', 'Canal redondo no centro do ósteon, com vasos e conjuntivo frouxo; no osso desgastado aparece vazio e escuro.'],
    aprofundado: ['Liga-se a outros canais de Havers e ao periósteo pelos canais de Volkmann, oblíquos e sem lamelas concêntricas.', 'Os canais de Volkmann atravessam as lamelas em ângulo reto e não são rodeados por lamelas concêntricas.'],
    funcoes: ['Levar sangue e nervos ao interior do osso compacto.', 'Conduzir capilares, vênulas e nervos no eixo do ósteon.', 'Comunicar-se com o periósteo, a medula e outros canais pelos canais de Volkmann (transversais).'],
    regeneracao: { nivel: 'alta', texto: 'Novos canais surgem a cada ciclo de remodelação.' },
    ondeEncontrar: ['Osso compacto.'],
    alteracoes: ['Canais alargados por reabsorção na osteoporose e no hiperparatireoidismo.', 'Aumentados e irregulares na osteoporose cortical e na remodelação acelerada (hiperparatireoidismo).'],
  }),
  OSSO({
    id: 'osteocito',
    nome: 'Osteócito',
    sinonimos: ['osteocyte', 'lacuna óssea'],
    tipo: 'celula',
    resumo: 'Osteoblasto que ficou preso na matriz: corpo numa lacuna e prolongamentos finos pelos canalículos.',
    caracteristicas: [
      'Célula achatada/fusiforme dentro de uma lacuna entre as lamelas.',
      'No osso desgastado, só a lacuna escura aparece; no descalcificado, o núcleo corado.',
    ],
    aprofundado: [
      'Forma uma rede de células ligadas por junções comunicantes nos canalículos.',
      'É o sensor mecânico do osso e produz esclerostina e FGF23 (regula o fósforo).',
    ],
    funcoes: ['Manter a matriz e comandar a remodelação conforme a carga.', 'Regular o cálcio e o fosfato.'],
    regeneracao: { nivel: 'moderada', texto: 'Osteócitos mortos são repostos quando o osso é remodelado.' },
    ondeEncontrar: ['Todo tecido ósseo.'],
    alteracoes: ['Lacunas vazias na necrose óssea (osteonecrose da cabeça do fêmur).'],
  }),
  OSSO({
    id: 'canaliculo-osseo',
    nome: 'Canalículos ósseos',
    sinonimos: ['canaliculi'],
    tipo: 'matriz',
    resumo: 'Canais finíssimos que irradiam das lacunas e as ligam entre si e ao canal de Havers — o aspecto de "aranha" das lacunas.',
    caracteristicas: ['Linhas escuras e radiais no osso desgastado; quase invisíveis no descalcificado em HE.', 'Não atravessam a linha cimentante.', 'Canais finíssimos, radiados, que saem das lacunas e as unem entre si e ao canal central.'],
    aprofundado: ['Por eles circulam nutrientes e sinais; nenhum osteócito fica a mais de ~0,2 mm de um vaso.'],
    funcoes: ['Comunicação e nutrição entre osteócitos.', 'Formar a rede lacunocanalicular: o líquido que circula nela é o sinal mecânico sentido pelos osteócitos.', 'Permitir junções comunicantes entre prolongamentos de osteócitos vizinhos.'],
    regeneracao: { nivel: 'alta', texto: 'Refeitos a cada ciclo de remodelação.' },
    ondeEncontrar: ['Todo tecido ósseo.'],
    alteracoes: ['Rede canalicular reduzida no envelhecimento e na osteoporose.'],
  }),
  OSSO({
    id: 'linha-cimentante',
    nome: 'Linha cimentante',
    sinonimos: ['cement line', 'linha de reversão'],
    tipo: 'matriz',
    resumo: 'Contorno fino e nítido em volta de cada ósteon, pobre em colágeno, que marca onde a reabsorção parou e a formação começou.',
    caracteristicas: ['Linha refringente (clara no desgaste, basófila no descalcificado) limitando o ósteon.', 'Os canalículos não a atravessam.', 'Linha fina, basofílica e refringente que contorna cada ósteon; não é atravessada pelos canalículos.'],
    aprofundado: ['É a "cicatriz" de cada ciclo de remodelação; o número delas conta a história do osso.'],
    funcoes: ['Delimitar ósteons; desviar a propagação de microfissuras.', 'Marcar onde a reabsorção parou e a formação começou (linha de reversão).'],
    regeneracao: { nivel: 'nao-se-aplica', texto: 'Marca estrutural da remodelação.' },
    ondeEncontrar: ['Osso compacto remodelado.'],
    alteracoes: ['Padrão em mosaico, com muitas linhas irregulares, na doença de Paget.', 'Linhas cimentantes numerosas e irregulares ("em mosaico") na doença de Paget do osso.'],
  }),
  OSSO({
    id: 'trabecula-ossea',
    nome: 'Trabécula óssea',
    sinonimos: ['trabécula', 'osso esponjoso', 'trabecular bone', 'espícula'],
    tipo: 'matriz',
    resumo: 'Placa ou barra de osso lamelar do osso esponjoso, cercada pela medula óssea.',
    caracteristicas: ['Faixas ramificadas de matriz eosinófila (HE) ou verde (Masson-Goldner) com osteócitos.', 'Superfície revestida por osteoblastos, células de revestimento ou osteoclastos.'],
    aprofundado: ['Orientadas segundo as linhas de força (lei de Wolff).', 'Superfície grande: remodela mais rápido que o osso cortical.'],
    funcoes: ['Leveza com resistência; abrigo da medula hematopoética; reserva rápida de cálcio.', 'Orientar-se conforme as linhas de força (lei de Wolff).', 'Ter remodelação muito mais rápida que o osso cortical: é a primeira a se perder na osteoporose (vértebras, colo do fêmur, rádio distal).'],
    regeneracao: { nivel: 'alta', texto: 'Remodelação intensa, cerca de 25 % ao ano.' },
    ondeEncontrar: ['Epífises, metáfises, corpos vertebrais, ossos chatos.'],
    alteracoes: ['Afinamento e perda de conexões na osteoporose.', 'Trabéculas espessas na osteopetrose.'],
  }),
  OSSO({
    id: 'osso-cortical',
    nome: 'Osso cortical (compacto)',
    sinonimos: ['cortical', 'compact bone'],
    tipo: 'camada',
    resumo: 'Camada densa e contínua de osso na periferia dos ossos, formada por ósteons.',
    caracteristicas: ['Faixa óssea sem espaços medulares visíveis a pequeno aumento.', 'Fina nos corpos vertebrais, espessa nas diáfises.'],
    aprofundado: ['Coberto por periósteo por fora e endósteo por dentro.', 'Cerca de 80 % da massa óssea do esqueleto.'],
    funcoes: ['Suporte e proteção mecânica.', 'Resistir à flexão e à torção nas diáfises (80 % da massa óssea do esqueleto).', 'Reservatório de cálcio, fosfato e fatores de crescimento.'],
    regeneracao: { nivel: 'alta', texto: 'Consolida fraturas pelo calo ósseo.' },
    ondeEncontrar: ['Periferia de todos os ossos.'],
    alteracoes: ['Afinamento cortical na osteoporose e no hiperparatireoidismo.'],
  }),
  OSSO({
    id: 'osteoide',
    nome: 'Osteoide',
    sinonimos: ['osteoid', 'matriz não mineralizada'],
    tipo: 'matriz',
    resumo: 'Matriz óssea recém-depositada e ainda não mineralizada: faixa sobre as trabéculas, vermelha no Masson-Goldner.',
    caracteristicas: ['Faixa fina (< 10 µm) entre os osteoblastos e o osso mineralizado.', 'Vermelho-alaranjada no Masson-Goldner, que cora o osso mineralizado de verde.'],
    aprofundado: ['Colágeno tipo I e proteínas não colágenas; mineraliza em ~10 dias.', 'Só se vê em cortes sem descalcificar (inclusão em plástico).'],
    funcoes: ['Primeira etapa da formação óssea.', 'Servir de molde que será mineralizado (hidroxiapatita) em dias.', 'Sua espessura indica o equilíbrio entre formação e mineralização.'],
    regeneracao: { nivel: 'alta', texto: 'Depositado continuamente onde há formação.' },
    ondeEncontrar: ['Superfícies ósseas em formação: crescimento, remodelação, consolidação de fraturas.'],
    alteracoes: ['Osteomalácia e raquitismo (falta de vitamina D): faixas de osteoide largas e excessivas.', 'Osteomalácia e raquitismo (falta de vitamina D): excesso de osteoide não mineralizado.'],
  }),
  OSSO({
    id: 'osteoblasto',
    nome: 'Osteoblasto',
    sinonimos: ['osteoblast'],
    tipo: 'celula',
    resumo: 'Célula que fabrica osso: cúbica, basófila, enfileirada como um epitélio sobre a superfície em formação.',
    caracteristicas: ['Fileira de células cúbicas com núcleo excêntrico e citoplasma basófilo.', 'Halo claro perto do núcleo (Golgi).'],
    aprofundado: ['Secreta colágeno I, osteocalcina e fosfatase alcalina; controla os osteoclastos via RANKL/OPG.', 'Termina como osteócito, célula de revestimento ou em apoptose.'],
    funcoes: ['Síntese e mineralização da matriz óssea.', 'Secretar colágeno I, osteocalcina e fosfatase alcalina (marcadores de formação óssea).', 'Controlar os osteoclastos: produz RANKL (estimula) e osteoprotegerina (inibe).', 'Tornar-se osteócito ao ficar preso na matriz, ou célula de revestimento na superfície inativa.'],
    regeneracao: { nivel: 'alta', texto: 'Recrutado de células osteoprogenitoras do periósteo, endósteo e medula.' },
    ondeEncontrar: ['Superfícies ósseas em formação.'],
    alteracoes: ['Osteossarcoma (osteoide produzido por células malignas).', 'Osteogênese imperfeita.'],
  }),
  OSSO({
    id: 'medula-ossea-hematopoetica',
    nome: 'Medula óssea hematopoética (vermelha)',
    sinonimos: ['medula vermelha', 'bone marrow'],
    tipo: 'regiao',
    resumo: 'Tecido entre as trabéculas que produz as células do sangue, com adipócitos e sinusoides.',
    caracteristicas: ['Mistura de precursores hematopoéticos, megacariócitos, adipócitos e sinusoides.', 'Celularidade (fração não gordurosa) de ~100 menos a idade, em %.'],
    aprofundado: ['No adulto persiste no esqueleto axial (vértebras, esterno, bacia) e nas epífises proximais.'],
    funcoes: ['Hematopoese.', 'Produzir hemácias, leucócitos e plaquetas (cerca de 500 bilhões de células por dia).', 'Abrigar o nicho das células-tronco hematopoéticas (osteoblastos, células reticulares, endotélio sinusoidal).', 'Local de maturação dos linfócitos B e reservatório de plasmócitos de vida longa.'],
    regeneracao: { nivel: 'alta', texto: 'Células-tronco hematopoéticas repovoam a medula (base do transplante).' },
    ondeEncontrar: ['Vértebras, esterno, costelas, bacia, crânio, epífises proximais do fêmur e do úmero.'],
    alteracoes: ['Aplasia medular.', 'Infiltração por leucemia, mieloma ou metástases.', 'Mielofibrose.'],
  }),
  OSSO({
    id: 'placa-terminal-vertebral',
    nome: 'Placa terminal vertebral',
    sinonimos: ['endplate', 'placa cartilaginosa'],
    tipo: 'camada',
    resumo: 'Lâmina de cartilagem hialina que separa o corpo vertebral do disco intervertebral.',
    caracteristicas: ['Faixa de cartilagem sobre a superfície do corpo vertebral, com condrócitos em lacunas.', 'Camada de cartilagem hialina entre o disco e o osso do corpo vertebral.'],
    aprofundado: ['É por ela que o disco, avascular, recebe nutrientes por difusão a partir dos vasos do corpo vertebral.'],
    funcoes: ['Distribuir a carga e nutrir o disco.', 'Impedir que o núcleo pulposo penetre no corpo vertebral.'],
    regeneracao: { nivel: 'baixa', texto: 'Cartilagem: reparo limitado.' },
    ondeEncontrar: ['Faces superior e inferior dos corpos vertebrais.'],
    alteracoes: ['Nódulos de Schmorl (herniação do disco para o corpo vertebral).', 'Alterações de Modic na RM.', 'Nódulos de Schmorl: herniação do disco através da placa terminal.'],
  }),
  OSSO({
    id: 'anel-fibroso',
    nome: 'Anel fibroso do disco intervertebral',
    sinonimos: ['annulus fibrosus', 'disco intervertebral'],
    tipo: 'orgao-parte',
    resumo: 'Parte externa do disco: lamelas concêntricas de fibrocartilagem, com fibras em direções alternadas.',
    caracteristicas: ['Feixes colágenos densos em lamelas, com condrócitos em fileiras.', 'Envolve o núcleo pulposo, gelatinoso.'],
    aprofundado: ['Fibras cruzadas a ~60° em lamelas vizinhas, resistindo à torção.', 'O núcleo pulposo é resto da notocorda.'],
    funcoes: ['Conter o núcleo pulposo e resistir à compressão e à torção.', 'Transmitir e distribuir a carga entre vértebras, com o núcleo pulposo funcionando como amortecedor hidráulico.'],
    regeneracao: { nivel: 'baixa', texto: 'Quase avascular: cicatriza mal.' },
    ondeEncontrar: ['Entre os corpos vertebrais.'],
    alteracoes: ['Fissuras radiais e hérnia de disco.', 'Degeneração discal com a idade.'],
  }),
  OSSO({
    id: 'cartilagem-hialina',
    nome: 'Cartilagem hialina',
    sinonimos: ['hyaline cartilage', 'cartilagem articular'],
    tipo: 'matriz',
    resumo: 'Cartilagem de matriz homogênea e vítrea, com condrócitos em lacunas e grupos isógenos; molde do esqueleto fetal.',
    caracteristicas: ['Matriz lisa, levemente basófila (azul-violeta com corantes básicos).', 'Condrócitos em lacunas, isolados ou em grupos isógenos.', 'Pericôndrio na periferia (exceto na cartilagem articular).'],
    aprofundado: ['Colágeno tipo II e agrecano, que retém água e resiste à compressão.', 'Avascular e sem nervos.'],
    funcoes: ['Superfícies articulares de baixo atrito; molde para a ossificação endocondral; sustentação de vias aéreas.', 'Crescer e sustentar sem vasos: nutrição por difusão pela matriz (daí a baixa capacidade de reparo).', 'Formar o esqueleto do feto e os discos de crescimento.'],
    regeneracao: { nivel: 'baixa', texto: 'A articular adulta praticamente não se regenera.' },
    ondeEncontrar: ['Articulações, costelas, traqueia, brônquios, nariz, laringe, discos epifisários, esqueleto fetal.'],
    alteracoes: ['Osteoartrite (fibrilação e perda da cartilagem).', 'Condrossarcoma.', 'Acondroplasia.'],
  }),
  OSSO({
    id: 'pericondrio',
    nome: 'Pericôndrio',
    sinonimos: ['perichondrium'],
    tipo: 'camada',
    resumo: 'Conjuntivo denso que envolve a cartilagem; sua camada interna forma novos condroblastos.',
    caracteristicas: ['Camada fibrosa externa e camada celular interna, condrogênica.', 'Conjuntivo denso em volta da cartilagem hialina e elástica: camada fibrosa externa e condrogênica interna.'],
    aprofundado: ['No início da ossificação endocondral, o pericôndrio da diáfise passa a formar osso e vira periósteo.', 'A cartilagem articular e a fibrocartilagem não têm pericôndrio.'],
    funcoes: ['Crescimento aposicional da cartilagem; nutrição por difusão.', 'Fornecer condroblastos (camada condrogênica interna) para o crescimento aposicional.', 'Levar vasos que nutrem a cartilagem por difusão.'],
    regeneracao: { nivel: 'moderada', texto: 'Fonte de células para reparo limitado da cartilagem.' },
    ondeEncontrar: ['Cartilagens hialina e elástica (não na articular nem na fibrocartilagem).'],
    alteracoes: ['Pericondrite da orelha (deformidade em couve-flor).', 'Pericondrite da orelha (piercing) com deformidade "em couve-flor" após perda da nutrição.'],
  }),
  OSSO({
    id: 'disco-epifisario',
    nome: 'Disco (placa) epifisário',
    sinonimos: ['placa de crescimento', 'fise', 'growth plate', 'cartilagem de conjugação'],
    tipo: 'camada',
    resumo: 'Faixa de cartilagem entre a epífise e a metáfise, responsável pelo crescimento do osso em comprimento.',
    caracteristicas: ['Zonas em sequência: repouso, proliferação (colunas), hipertrofia, calcificação e ossificação.', 'Condrócitos em colunas paralelas ao eixo do osso.'],
    aprofundado: ['Controlado por GH/IGF-1, hormônios tireoidianos e sexuais; fecha no fim da puberdade (linha epifisária).'],
    funcoes: ['Crescimento longitudinal dos ossos.', 'Responder a hormônios: GH/IGF-1 aceleram, estrógenos fecham o disco no fim da puberdade.', 'Organizar as zonas de repouso, proliferação, hipertrofia, calcificação e ossificação.'],
    regeneracao: { nivel: 'baixa', texto: 'Lesões podem fechar a fise precocemente e encurtar o membro.' },
    ondeEncontrar: ['Ossos longos de crianças e adolescentes.'],
    alteracoes: ['Acondroplasia (FGFR3).', 'Raquitismo: zona hipertrófica alargada e desorganizada.', 'Fraturas de Salter-Harris.'],
  }),
  OSSO({
    id: 'zona-proliferativa',
    nome: 'Zona proliferativa',
    sinonimos: ['zona de proliferação', 'colunas de condrócitos'],
    tipo: 'camada',
    resumo: 'Condrócitos achatados, empilhados em colunas longitudinais, em divisão rápida.',
    caracteristicas: ['Colunas de células achatadas como "pilhas de moedas".', 'Condrócitos achatados em colunas longitudinais ("pilhas de moedas").'],
    aprofundado: ['A taxa de divisão aqui determina a velocidade de crescimento.', 'Controlada pelo eixo PTHrP–Indian hedgehog, que regula quando os condrócitos param de proliferar.'],
    funcoes: ['Gerar os condrócitos que alongam o osso.', 'Dividir condrócitos que se empilham em colunas no sentido do crescimento.'],
    regeneracao: { nivel: 'nao-se-aplica', texto: 'Zona transitória do crescimento.' },
    ondeEncontrar: ['Disco epifisário.'],
    alteracoes: ['Colunas curtas e desorganizadas na acondroplasia.', 'Acondroplasia (FGFR3 ativado): proliferação reduzida, nanismo de membros curtos.'],
  }),
  OSSO({
    id: 'zona-hipertrofica',
    nome: 'Zona hipertrófica',
    sinonimos: ['condrócitos hipertróficos', 'zona de maturação'],
    tipo: 'camada',
    resumo: 'Condrócitos grandes e claros, que incham, secretam colágeno X e VEGF e preparam a matriz para calcificar.',
    caracteristicas: ['Células volumosas e vacuoladas em lacunas grandes, ainda em colunas.', 'Condrócitos grandes, claros, vacuolizados, em lacunas amplas, com septos de matriz finos.'],
    aprofundado: ['Os condrócitos hipertróficos morrem ou se transdiferenciam em osteoblastos; o VEGF atrai os vasos.', 'Os condrócitos hipertróficos morrem por apoptose ou se transformam em osteoblastos.'],
    funcoes: ['Aumentar o comprimento e preparar a matriz para a ossificação.', 'Secretar colágeno X e VEGF, que atrai vasos para a invasão da cartilagem.', 'Aumentar de volume: é o principal motor do crescimento em comprimento.'],
    regeneracao: { nivel: 'nao-se-aplica', texto: 'Zona transitória.' },
    ondeEncontrar: ['Disco epifisário; centros primários e secundários de ossificação.'],
    alteracoes: ['Alargada no raquitismo (a matriz não calcifica).', 'Raquitismo: zona hipertrófica desorganizada e alargada, sem calcificação.'],
  }),
  OSSO({
    id: 'zona-de-calcificacao',
    nome: 'Zona de calcificação',
    sinonimos: ['cartilagem calcificada'],
    tipo: 'camada',
    resumo: 'Faixa onde a matriz entre as colunas de condrócitos hipertróficos se mineraliza e fica basófila.',
    caracteristicas: ['Septos de matriz escura e basófila entre lacunas vazias.', 'Septos de matriz cartilaginosa calcificada, basofílicos, entre lacunas vazias.'],
    aprofundado: ['Os septos longitudinais calcificados servem de molde onde os osteoblastos depositam osso.', 'A matriz calcificada é reabsorvida por condroclastos e osteoclastos.'],
    funcoes: ['Arcabouço para a espongiosa primária.', 'Mineralizar os septos longitudinais de matriz, que serão o suporte para os osteoblastos.'],
    regeneracao: { nivel: 'nao-se-aplica', texto: 'Zona transitória.' },
    ondeEncontrar: ['Disco epifisário, junto à metáfise.'],
    alteracoes: ['Falha de calcificação no raquitismo.', 'Escorbuto: pouca formação de osso sobre os septos (linha de Frankel).'],
  }),
  OSSO({
    id: 'espongiosa-primaria',
    nome: 'Espongiosa primária (zona de ossificação)',
    sinonimos: ['zona de ossificação', 'metáfise'],
    tipo: 'camada',
    resumo: 'Trabéculas com núcleo de cartilagem calcificada revestido por osso novo, invadidas por vasos e medula.',
    caracteristicas: ['Espículas com centro basófilo (cartilagem) e borda eosinófila (osso), osteoblastos na superfície.', 'Trabéculas com eixo azulado (cartilagem calcificada) coberto por osso rosado e osteoblastos.'],
    aprofundado: ['É remodelada em espongiosa secundária, de osso lamelar.', 'Será remodelada em espongiosa secundária (osso lamelar sem cartilagem).'],
    funcoes: ['Transformar o molde de cartilagem em osso.', 'Depositar osso sobre os restos de cartilagem calcificada, formando trabéculas com núcleo basofílico de cartilagem.'],
    regeneracao: { nivel: 'alta', texto: 'Constantemente formada e remodelada durante o crescimento.' },
    ondeEncontrar: ['Metáfise, logo abaixo do disco epifisário.'],
    alteracoes: ['Persistência de cartilagem calcificada na osteopetrose.', 'Osteopetrose: a cartilagem calcificada não é reabsorvida (osteoclastos defeituosos).'],
  }),
  OSSO({
    id: 'centro-de-ossificacao-secundario',
    nome: 'Centro de ossificação secundário',
    sinonimos: ['epífise ossificada', 'secondary ossification center'],
    tipo: 'regiao',
    resumo: 'Área de ossificação dentro da epífise, separada da diáfise pelo disco epifisário.',
    caracteristicas: ['Osso trabecular com medula no interior da epífise, cercado por cartilagem.', 'Área de ossificação dentro da cartilagem da epífise, com medula e trabéculas.'],
    aprofundado: ['Aparece geralmente após o nascimento, em datas típicas de cada osso — usadas para estimar a idade óssea.', 'Separa a cartilagem articular (em cima) do disco epifisário (embaixo).'],
    funcoes: ['Formar o osso da epífise, preservando a cartilagem articular e o disco.', 'Aparecer em idades típicas, usado para estimar a idade óssea em radiografias.'],
    regeneracao: { nivel: 'alta', texto: 'Osso trabecular.' },
    ondeEncontrar: ['Epífises dos ossos longos em crescimento.'],
    alteracoes: ['Doença de Legg-Calvé-Perthes (necrose do núcleo de ossificação da cabeça do fêmur).', 'Epifisiólise do fêmur proximal no adolescente.'],
  }),
  OSSO({
    id: 'colar-osseo-periosteal',
    nome: 'Colar ósseo periosteal',
    sinonimos: ['bone collar', 'colar periosteal'],
    tipo: 'camada',
    resumo: 'Manga de osso formada pelo periósteo em volta da diáfise do molde de cartilagem — o primeiro osso da ossificação endocondral.',
    caracteristicas: ['Faixa eosinófila de osso em volta do meio do molde, sobre os condrócitos hipertróficos.', 'Faixa de osso formada sob o pericôndrio (que vira periósteo) em volta da diáfise do molde cartilaginoso.'],
    aprofundado: ['Formado por ossificação intramembranosa do pericôndrio, que vira periósteo; depois o broto periosteal leva vasos ao centro.', 'Impede a difusão de nutrientes, e os condrócitos centrais hipertrofiam e morrem, abrindo espaço para a invasão vascular.'],
    funcoes: ['Sustentar o molde enquanto a cartilagem central é substituída.', 'Originar o osso cortical da diáfise por ossificação intramembranosa no periósteo.'],
    regeneracao: { nivel: 'alta', texto: 'Base do crescimento em espessura do osso.' },
    ondeEncontrar: ['Diáfise de ossos em ossificação endocondral (embrião e feto).'],
    alteracoes: ['Defeitos na ossificação em displasias esqueléticas.', 'Reação periosteal (tumores, infecção) é a retomada dessa formação na superfície.'],
  }),
  OSSO({
    id: 'conjuntivo-denso-modelado',
    nome: 'Conjuntivo denso modelado',
    sinonimos: ['tendão', 'ligamento', 'dense regular'],
    tipo: 'matriz',
    resumo: 'Feixes colágenos grossos e paralelos, com fibroblastos enfileirados entre eles: tendões e ligamentos.',
    caracteristicas: ['Fibras paralelas e compactas, eosinófilas; núcleos alongados em fila.', 'Feixes de colágeno paralelos, com fibroblastos (tenócitos) alongados em fileiras entre eles; pouca substância fundamental e poucos vasos.'],
    aprofundado: ['Resiste à tração em uma só direção; pouco vascularizado.', 'Pouco vascularizado: por isso tendões e ligamentos cicatrizam devagar.'],
    funcoes: ['Transmitir força do músculo ao osso e ligar ossos.', 'Resistir a grandes forças de tração numa só direção.'],
    regeneracao: { nivel: 'baixa', texto: 'Cicatriza devagar e com fibras menos organizadas.' },
    ondeEncontrar: ['Tendões, ligamentos, aponeuroses, estroma da córnea.'],
    alteracoes: ['Tendinopatia e rupturas.', 'Xantomas tendíneos na hipercolesterolemia familiar.'],
  }),
]
