import type { Estrutura } from '../tipos'

/** Pele e anexos. */
export const ESTRUTURAS_PELE: Estrutura[] = [
  {
    id: 'epiderme',
    nome: 'Epiderme',
    sinonimos: ['epidermis', 'epitélio estratificado pavimentoso queratinizado'],
    tipo: 'epitelio',
    resumo: 'Epitélio estratificado pavimentoso queratinizado que reveste a pele; avascular, renovado a partir da camada basal.',
    caracteristicas: [
      'Camadas, da profundidade para a superfície: basal, espinhosa, granulosa, lúcida (só na pele espessa) e córnea.',
      'Limite ondulado com a derme: cristas epidérmicas e papilas dérmicas.',
      'Sem vasos: nutrida por difusão a partir da derme papilar.',
    ],
    aprofundado: [
      'Queratinócitos (~90 %), melanócitos, células de Langerhans e células de Merkel.',
      'Renovação completa em ~4 semanas.',
      'Pele espessa (palmas e plantas) tem córnea espessa e camada lúcida, sem pelos.',
    ],
    funcoes: ['Barreira contra água, microrganismos e radiação UV.', 'Síntese de vitamina D.', 'Sensibilidade (células de Merkel).'],
    regeneracao: { nivel: 'alta', texto: 'Células-tronco da camada basal e do bulge folicular renovam e reepitelizam feridas.' },
    ondeEncontrar: ['Toda a superfície corporal.'],
    alteracoes: ['Psoríase (acantose e paraqueratose).', 'Carcinoma basocelular e espinocelular.', 'Melanoma (melanócitos).'],
  },
  {
    id: 'camada-cornea',
    nome: 'Camada córnea',
    sinonimos: ['estrato córneo', 'stratum corneum', 'queratina'],
    tipo: 'camada',
    resumo: 'Camada mais superficial da epiderme: células mortas, achatadas, sem núcleo, cheias de queratina.',
    caracteristicas: ['Lâminas eosinófilas sem núcleo, em "cesta de vime" (frouxa) na pele fina e compactas na espessa.', 'Camada mais superficial: células mortas, achatadas, sem núcleo, eosinofílicas; muito espessa na pele espessa (palmas e plantas) e fina e frouxa ("em cesta") na pele fina.'],
    aprofundado: ['Corneócitos com envelope proteico e lipídios intercelulares (ceramidas) formam a barreira de água.', 'Corneócitos têm envelope cornificado (loricrina, involucrina) em vez de membrana plasmática; a filagrina agrega os filamentos de queratina e, degradada, forma o fator de hidratação natural.'],
    funcoes: ['Barreira física e contra perda de água.', 'Formar o "tijolo e argamassa": corneócitos (tijolos) cheios de queratina, unidos por lipídios lamelares (argamassa) que impedem a perda de água.', 'Descamar continuamente (descamação regulada por proteases), eliminando microrganismos aderidos.', 'Manter pH ácido e peptídeos antimicrobianos na superfície (manto ácido).'],
    regeneracao: { nivel: 'alta', texto: 'Descama e é reposta continuamente.' },
    ondeEncontrar: ['Superfície da epiderme.'],
    alteracoes: ['Hiperqueratose (calo, ictiose).', 'Paraqueratose: núcleos retidos na córnea (psoríase).'],
  },
  {
    id: 'derme-papilar',
    nome: 'Derme papilar',
    sinonimos: ['papillary dermis', 'papilas dérmicas'],
    tipo: 'camada',
    resumo: 'Camada superficial e fina da derme, de conjuntivo frouxo, que forma as papilas entre as cristas da epiderme.',
    caracteristicas: ['Fibras colágenas finas e fibras elásticas delicadas perpendiculares à epiderme.', 'Muitos capilares e terminações nervosas.'],
    aprofundado: ['Abriga as alças capilares que nutrem a epiderme e os corpúsculos de Meissner.', 'As alças capilares das papilas nutrem a epiderme avascular por difusão; os corpúsculos de Meissner (tato fino) ficam nas papilas da pele espessa.'],
    funcoes: ['Nutrir a epiderme e ancorá-la à derme.', 'Termorregulação.', 'Abrigar receptores de tato fino (corpúsculos de Meissner).'],
    regeneracao: { nivel: 'alta', texto: 'Conjuntivo bem vascularizado.' },
    ondeEncontrar: ['Logo abaixo da epiderme em toda a pele.'],
    alteracoes: ['Elastose solar na derme superficial.', 'Edema papilar em dermatites.'],
  },
  {
    id: 'derme-reticular',
    nome: 'Derme reticular',
    sinonimos: ['reticular dermis'],
    tipo: 'camada',
    resumo: 'Camada profunda e espessa da derme: conjuntivo denso não modelado, com feixes grossos de colágeno e fibras elásticas grossas.',
    caracteristicas: ['Feixes colágenos grossos em todas as direções.', 'Fibras elásticas grossas; anexos cutâneos e vasos maiores.'],
    aprofundado: ['Dá à pele a resistência e as linhas de tensão (linhas de Langer) que orientam as incisões cirúrgicas.', 'A orientação dos feixes define as linhas de Langer: incisões paralelas a elas cicatrizam melhor.'],
    funcoes: ['Resistência mecânica e elasticidade da pele.', 'Abrigar folículos, glândulas, vasos maiores e corpúsculos de Pacini (vibração).', 'Dar à pele a resistência à tração (colágeno I) e a elasticidade (fibras elásticas).'],
    regeneracao: { nivel: 'moderada', texto: 'Cicatriza com fibrose; perde anexos na cicatriz.' },
    ondeEncontrar: ['Abaixo da derme papilar, até a hipoderme.'],
    alteracoes: ['Esclerodermia (colágeno espessado).', 'Queloide.', 'Estrias (ruptura de fibras).'],
  },
  {
    id: 'foliculo-piloso',
    nome: 'Folículo piloso',
    sinonimos: ['hair follicle', 'pelo', 'bainha radicular'],
    tipo: 'orgao-parte',
    resumo: 'Invaginação da epiderme que produz o pelo: bainhas epiteliais concêntricas em volta da haste.',
    caracteristicas: [
      'Em corte transversal: anéis concêntricos — haste do pelo, bainha radicular interna, externa e bainha conjuntiva.',
      'Na base, o bulbo com a papila dérmica.',
      'Associado à glândula sebácea e ao músculo eretor do pelo.',
    ],
    aprofundado: ['O bulge (inserção do eretor) guarda células-tronco que também regeneram a epiderme.', 'Ciclo: anágena, catágena, telógena.'],
    funcoes: ['Produzir o pelo.', 'Reservatório de células-tronco epidérmicas.', 'Participar da reepitelização de feridas (células-tronco do bulge migram para a superfície).', 'Sensibilidade tátil (terminações nervosas em volta do folículo).'],
    regeneracao: { nivel: 'moderada', texto: 'Cicla a vida inteira; destruído por cicatriz, não volta.' },
    ondeEncontrar: ['Toda a pele, exceto palmas, plantas, lábios e glande.'],
    alteracoes: ['Alopecia areata (infiltrado linfoide no bulbo).', 'Foliculite.', 'Cisto epidérmico.'],
  },
  {
    id: 'glandula-sebacea',
    nome: 'Glândula sebácea',
    sinonimos: ['sebaceous gland', 'sebo'],
    tipo: 'glandula',
    resumo: 'Glândula holócrina em lóbulos de células claras e espumosas que se desintegram para formar o sebo.',
    caracteristicas: [
      'Lóbulos (ácinos) junto ao folículo, com células grandes de citoplasma vacuolizado e núcleo central.',
      'Camada de células basais pequenas na periferia do lóbulo.',
      'Desemboca no folículo piloso.',
    ],
    aprofundado: ['Secreção holócrina: a célula inteira vira secreção.', 'Estimulada por andrógenos — cresce na puberdade.'],
    funcoes: ['Lubrificar pelo e pele; barreira e ação antimicrobiana.', 'Secretar sebo por secreção holócrina (a célula inteira se desintegra e vira secreção).', 'Espalhar lipídios que tornam a pele impermeável e macia e têm ação antifúngica (ácidos graxos livres).', 'Responder a andrógenos: cresce muito na puberdade.'],
    regeneracao: { nivel: 'alta', texto: 'As células basais repõem continuamente as que se desintegram.' },
    ondeEncontrar: ['Pele com pelos; mais abundante na face, couro cabeludo e tronco; glândulas livres em pálpebras (Meibômio) e lábios.'],
    alteracoes: ['Acne.', 'Hiperplasia sebácea.', 'Carcinoma sebáceo (pálpebra; síndrome de Muir-Torre).'],
  },
  {
    id: 'glandula-sudoripara-ecrina',
    nome: 'Glândula sudorípara écrina',
    sinonimos: ['eccrine gland', 'glândula merócrina', 'suor'],
    tipo: 'glandula',
    resumo: 'Glândula tubular enovelada na derme profunda, de luz estreita, que secreta o suor aquoso da termorregulação.',
    caracteristicas: [
      'Novelo de perfis pequenos: porção secretora (células claras e escuras, com mioepiteliais) e ducto (duas camadas de células cúbicas escuras).',
      'Luz pequena; desemboca direto na superfície da pele.',
    ],
    aprofundado: ['Inervação simpática colinérgica.', 'O ducto reabsorve sódio: o suor sai hipotônico (alterado na fibrose cística).'],
    funcoes: ['Termorregulação pela evaporação do suor.', 'Produzir suor hipotônico: a porção secretora forma um líquido parecido com o plasma e o ducto reabsorve sódio e cloreto.', 'Eliminar água e eletrólitos e secretar peptídeos antimicrobianos (dermcidina).', 'Inervação simpática colinérgica (acetilcolina, receptores muscarínicos) — exceção no simpático.'],
    regeneracao: { nivel: 'moderada', texto: 'Epitélio renovável, mas as glândulas não se refazem em cicatrizes profundas.' },
    ondeEncontrar: ['Toda a pele; muito numerosa em palmas, plantas e fronte.'],
    alteracoes: ['Hiperidrose.', 'Siringoma e poroma (tumores benignos).', 'Suor salgado na fibrose cística.', 'Fibrose cística: o ducto não reabsorve cloreto, e o suor fica salgado (teste do suor).', 'Hiperidrose primária (tratada com toxina botulínica).'],
  },
  {
    id: 'glandula-sudoripara-apocrina',
    nome: 'Glândula sudorípara apócrina',
    sinonimos: ['apocrine gland', 'glândula odorífera'],
    tipo: 'glandula',
    resumo: 'Glândula tubular de luz ampla, com epitélio que forma brotos apicais; secreção viscosa que desemboca no folículo piloso.',
    caracteristicas: [
      'Túbulos dilatados, luz larga, epitélio cúbico a colunar eosinófilo com "focinhos" apicais (decapitação).',
      'Células mioepiteliais na base.',
      'Maiores que as écrinas, em lóbulos na derme profunda e hipoderme.',
      'Luz ampla, células cúbicas a colunares eosinofílicas, com projeções apicais (secreção por "decapitação"), abrindo no folículo piloso.',
    ],
    aprofundado: ['Ativa a partir da puberdade.', 'A secreção é inodora; o odor vem da ação de bactérias.', 'Glândulas ceruminosas e de Moll são apócrinas modificadas.'],
    funcoes: ['Secreção odorífera (sinalização química).', 'Secretar, a partir da puberdade, um líquido viscoso rico em lipídios e proteínas que as bactérias da pele transformam em odor.', 'Responder a estímulos emocionais (inervação adrenérgica).'],
    regeneracao: { nivel: 'moderada', texto: 'Epitélio renovável.' },
    ondeEncontrar: ['Axila, aréola, região anogenital; conduto auditivo (ceruminosas) e pálpebras (Moll).'],
    alteracoes: ['Hidradenite supurativa.', 'Doença de Fox-Fordyce.', 'Doença de Paget extramamária.'],
  },
  {
    id: 'ducto-sudoriparo',
    nome: 'Ducto sudoríparo',
    sinonimos: ['sweat duct', 'ducto excretor'],
    tipo: 'epitelio',
    resumo: 'Ducto de duas camadas de células cúbicas, mais escuro e de luz menor que a porção secretora.',
    caracteristicas: ['Epitélio estratificado cúbico (duas camadas), citoplasma basófilo, luz pequena e redonda.', 'Sem células mioepiteliais.', 'Duas camadas de células cúbicas pequenas e basofílicas, luz estreita — mais escuro que a porção secretora.'],
    aprofundado: ['Na epiderme, o trajeto é espiralado (acrossiríngio).', 'Na epiderme, o ducto não tem parede própria: é um canal espiral entre os queratinócitos (acrossiríngio).'],
    funcoes: ['Conduzir o suor e reabsorver sódio.', 'Reabsorver sódio e cloreto (canal CFTR), tornando o suor hipotônico.', 'Atravessar a epiderme em espiral (acrossiríngio) até o poro.'],
    regeneracao: { nivel: 'alta', texto: 'Participa da reepitelização de feridas superficiais.' },
    ondeEncontrar: ['Derme, ao lado das porções secretoras das glândulas sudoríparas.'],
    alteracoes: ['Miliária (obstrução do ducto).'],
  },
  {
    id: 'camada-basal',
    nome: 'Camada basal (germinativa)',
    sinonimos: ['estrato basal', 'stratum basale', 'camada germinativa'],
    tipo: 'camada',
    resumo: 'Fileira única de queratinócitos cúbicos a colunares sobre a membrana basal; é onde a epiderme se divide.',
    caracteristicas: ['Células pequenas, basófilas, em paliçada, apoiadas na membrana basal.', 'Entre elas, melanócitos (citoplasma claro) e células de Merkel.'],
    aprofundado: ['Presa à membrana basal por hemidesmossomos.', 'Contém as células-tronco da epiderme e as mitoses.'],
    funcoes: ['Renovar a epiderme.', 'Abrigar os melanócitos, que transferem melanina aos queratinócitos.'],
    regeneracao: { nivel: 'alta', texto: 'É a fonte da regeneração epidérmica.' },
    ondeEncontrar: ['Base de toda epiderme e dos epitélios estratificados pavimentosos.'],
    alteracoes: ['Carcinoma basocelular (paliçada periférica).', 'Penfigoide bolhoso (bolha subepidérmica).', 'Vitiligo (perda de melanócitos basais).'],
  },
  {
    id: 'camada-espinhosa',
    nome: 'Camada espinhosa',
    sinonimos: ['estrato espinhoso', 'stratum spinosum', 'Malpighi'],
    tipo: 'camada',
    resumo: 'Várias camadas de queratinócitos poligonais unidos por desmossomos, que aparecem como "espinhos" entre as células.',
    caracteristicas: ['Células poligonais, citoplasma eosinófilo, núcleo central.', 'Pontes intercelulares finas (desmossomos) em grande aumento.'],
    aprofundado: ['Rica em filamentos de queratina (tonofilamentos) ligados aos desmossomos.', 'Células de Langerhans ficam aqui.'],
    funcoes: ['Resistência mecânica da epiderme.', 'Unir os queratinócitos por desmossomos (as "espinhas" do nome), distribuindo as forças mecânicas.', 'Abrigar as células de Langerhans, que capturam antígenos e os levam aos linfonodos.'],
    regeneracao: { nivel: 'alta', texto: 'Renovada a partir da basal.' },
    ondeEncontrar: ['Epiderme e mucosas de epitélio estratificado pavimentoso.'],
    alteracoes: ['Acantose (espessamento) na psoríase.', 'Acantólise no pênfigo vulgar (desmogleína 3).', 'Espongiose no eczema.'],
  },
  {
    id: 'camada-granulosa',
    nome: 'Camada granulosa',
    sinonimos: ['estrato granuloso', 'stratum granulosum', 'querato-hialina'],
    tipo: 'camada',
    resumo: 'Uma a cinco camadas de células achatadas cheias de grânulos basófilos de querato-hialina, logo abaixo da córnea.',
    caracteristicas: ['Faixa fina e escura (grânulos roxos) entre a espinhosa e a córnea.', 'Mais espessa na pele espessa.'],
    aprofundado: ['Grânulos de querato-hialina (filagrina) e lamelares (lipídios da barreira).', 'Aqui as células começam a morrer e perder o núcleo.'],
    funcoes: ['Formar a barreira de água da epiderme.', 'Produzir os grânulos de querato-hialina (filagrina) e os corpos lamelares, cujos lipídios selam os espaços entre as células.', 'Iniciar a morte programada do queratinócito (cornificação).'],
    regeneracao: { nivel: 'alta', texto: 'Renovada continuamente.' },
    ondeEncontrar: ['Epiderme (ausente na maioria das mucosas não queratinizadas).'],
    alteracoes: ['Hipergranulose no líquen plano.', 'Ausente ou reduzida na ictiose vulgar (filagrina) e na psoríase.'],
  },
  {
    id: 'musculo-eretor-do-pelo',
    nome: 'Músculo eretor do pelo',
    sinonimos: ['arrector pili', 'eretor do pelo'],
    tipo: 'orgao-parte',
    resumo: 'Feixe de músculo liso que vai da derme papilar ao folículo piloso, logo abaixo da glândula sebácea.',
    caracteristicas: ['Faixa oblíqua de músculo liso eosinófilo na derme, com núcleos alongados.', 'Feixe de músculo liso oblíquo que vai da derme papilar à bainha do folículo, do mesmo lado da glândula sebácea.'],
    aprofundado: ['Inervação simpática: contrai no frio e no medo ("arrepio"), ajudando a expulsar o sebo.', 'Sua inserção no folículo marca o bulge, nicho de células-tronco.'],
    funcoes: ['Eriçar o pelo e comprimir a glândula sebácea.', 'Contrair por estímulo simpático (frio, medo), produzindo a "pele arrepiada".', 'Marcar a região do bulge do folículo, onde ficam as células-tronco epidérmicas.'],
    regeneracao: { nivel: 'moderada', texto: 'Músculo liso.' },
    ondeEncontrar: ['Pele com pelos.'],
    alteracoes: ['Leiomioma cutâneo (piloleiomioma).'],
  },
]
