import type { Estrutura } from '../tipos'

/** Sistema reprodutor masculino. */
export const ESTRUTURAS_REPRODUTOR_MASCULINO: Estrutura[] = [
  {
    id: 'tubulo-seminifero',
    nome: 'Túbulo seminífero',
    sinonimos: ['seminiferous tubule', 'epitélio germinativo', 'célula de Sertoli'],
    tipo: 'orgao-parte',
    resumo: 'Túbulo enovelado do testículo revestido pelo epitélio seminífero: células germinativas em maturação apoiadas nas células de Sertoli.',
    caracteristicas: [
      'Da base para a luz: espermatogônias, espermatócitos, espermátides e espermatozoides.',
      'Células de Sertoli: núcleo claro, triangular, com nucléolo nítido, apoiadas na base.',
      'Envolto pela túnica própria; entre os túbulos, o interstício com células de Leydig.',
    ],
    aprofundado: [
      'As junções de oclusão entre as Sertoli formam a barreira hematotesticular.',
      'Um ciclo completo de espermatogênese leva ~64–74 dias no humano.',
    ],
    funcoes: ['Produzir espermatozoides.', 'Produzir espermatozoides (cerca de 100 milhões por dia).', 'Formar a barreira hematotesticular (junções entre células de Sertoli), protegendo as células meióticas do sistema imune.'],
    regeneracao: { nivel: 'moderada', texto: 'Espermatogônias-tronco repovoam o epitélio; lesões graves deixam só células de Sertoli.' },
    ondeEncontrar: ['Lóbulos do testículo.'],
    alteracoes: ['Parada de maturação e síndrome só-Sertoli (infertilidade).', 'Neoplasia de células germinativas in situ.', 'Atrofia na criptorquidia.'],
  },
  {
    id: 'espermatocito',
    nome: 'Espermatócito',
    sinonimos: ['spermatocyte', 'espermatócito primário'],
    tipo: 'celula',
    resumo: 'Célula germinativa em meiose, a maior do epitélio seminífero, com núcleo grande de cromatina em fios ou grumos.',
    caracteristicas: ['Núcleo grande e redondo com cromatina filamentosa (prófase I longa).', 'Fica na camada média do epitélio, acima das espermatogônias.', 'Espermatócito primário: a maior célula germinativa, com núcleo redondo e cromatina em filamentos (prófase I longa), acima das espermatogônias.'],
    aprofundado: ['O primário passa ~3 semanas em prófase I (paquíteno); o secundário existe por poucas horas e raramente é visto.'],
    funcoes: ['Reduzir o número de cromossomos pela meiose.', 'Fazer a meiose: recombinação (crossing-over) no espermatócito primário e redução a haploide no secundário.'],
    regeneracao: { nivel: 'alta', texto: 'Produzido continuamente a partir das espermatogônias.' },
    ondeEncontrar: ['Epitélio dos túbulos seminíferos.'],
    alteracoes: ['Parada meiótica em infertilidade; seminoma deriva de células germinativas.', 'Parada da maturação na infertilidade masculina.'],
  },
  {
    id: 'tunica-propria-seminifera',
    nome: 'Túnica própria do túbulo seminífero',
    sinonimos: ['células mioides', 'lâmina limitante'],
    tipo: 'camada',
    resumo: 'Envoltório fino do túbulo seminífero: lâmina basal, colágeno e células mioides achatadas e contráteis.',
    caracteristicas: ['Faixa eosinófila fina com núcleos alongados e achatados em volta de cada túbulo.', 'Camada fina de membrana basal, colágeno e células mioides achatadas em volta de cada túbulo.'],
    aprofundado: ['As células mioides contraem e empurram os espermatozoides para a rede testicular.'],
    funcoes: ['Sustentar o túbulo e impulsionar o conteúdo.', 'Contrair (células mioides) e empurrar os espermatozoides para a rede testicular.', 'Sustentar o túbulo com a membrana basal.'],
    regeneracao: { nivel: 'moderada', texto: 'Conjuntivo.' },
    ondeEncontrar: ['Em volta dos túbulos seminíferos.'],
    alteracoes: ['Espessamento e hialinização na atrofia testicular e na infertilidade.', 'Espessamento e hialinização na atrofia testicular e na criptorquidia.'],
  },
  {
    id: 'epitelio-pseudoestratificado-estereociliado',
    nome: 'Epitélio pseudoestratificado com estereocílios',
    sinonimos: ['estereocílios', 'epitélio do epidídimo', 'epitélio do ducto deferente'],
    tipo: 'epitelio',
    resumo: 'Epitélio de células colunares altas com estereocílios (microvilosidades longas) e células basais, que reveste epidídimo e ducto deferente.',
    caracteristicas: ['Núcleos em dois níveis (colunares e basais).', 'Tufo apical de estereocílios.', 'Células colunares altas com estereocílios (microvilosidades longas, imóveis) e células basais; no epidídimo e no ducto deferente.'],
    aprofundado: ['Os estereocílios são microvilosidades imóveis que absorvem o líquido testicular.'],
    funcoes: ['Absorver líquido e secretar substâncias que ajudam na maturação dos espermatozoides.', 'Reabsorver a maior parte do líquido que sai do testículo, concentrando os espermatozoides.', 'Secretar glicoproteínas que ajudam a maturação dos espermatozoides no epidídimo.'],
    regeneracao: { nivel: 'moderada', texto: 'Células basais repõem o epitélio.' },
    ondeEncontrar: ['Epidídimo e ducto deferente.'],
    alteracoes: ['Granuloma espermático após vasectomia.'],
  },
  {
    id: 'glandula-prostatica',
    nome: 'Glândula prostática',
    sinonimos: ['ácino prostático', 'corpos amiláceos'],
    tipo: 'glandula',
    resumo: 'Glândula túbulo-alveolar de luz ampla e contorno irregular, com epitélio colunar secretor sobre uma camada de células basais.',
    caracteristicas: ['Pregas papilares para a luz.', 'Duas camadas: luminal colunar e basal achatada.', 'Corpos amiláceos (concreções lamelares) na luz, sobretudo com a idade.'],
    aprofundado: ['Secreta PSA, fosfatase ácida prostática, citrato e zinco.', 'A ausência da camada basal (p63/CK34βE12) sugere carcinoma.'],
    funcoes: ['Produzir parte do líquido seminal.', 'Secretar líquido que forma cerca de 30 % do sêmen: PSA (liquefaz o coágulo seminal), fosfatase ácida, zinco e citrato.'],
    regeneracao: { nivel: 'moderada', texto: 'Dependente de andrógenos.' },
    ondeEncontrar: ['Próstata (zonas periférica, central e de transição).'],
    alteracoes: ['Hiperplasia prostática benigna (zona de transição).', 'Adenocarcinoma de próstata (zona periférica).', 'Prostatite.'],
  },
  {
    id: 'estroma-fibromuscular',
    nome: 'Estroma fibromuscular',
    sinonimos: ['estroma prostático'],
    tipo: 'matriz',
    resumo: 'Conjuntivo denso misturado a músculo liso, entre as glândulas da próstata.',
    caracteristicas: ['Faixas eosinófilas com núcleos alongados de fibroblastos e células musculares lisas.', 'Estroma denso de músculo liso e colágeno entre as glândulas da próstata.'],
    aprofundado: ['A contração do músculo liso expele a secreção na ejaculação; é alvo dos alfabloqueadores.'],
    funcoes: ['Sustentar as glândulas e expulsar a secreção.', 'Contrair na ejaculação, expulsando a secreção prostática.'],
    regeneracao: { nivel: 'moderada', texto: 'Hiperplasia com a idade.' },
    ondeEncontrar: ['Próstata.'],
    alteracoes: ['Nódulos estromais na hiperplasia prostática benigna.', 'Hiperplasia prostática benigna (estroma e glândulas).'],
  },
  {
    id: 'uretra-peniana',
    nome: 'Uretra peniana (esponjosa)',
    sinonimos: ['uretra esponjosa', 'glândulas de Littré'],
    tipo: 'orgao-parte',
    resumo: 'Segmento da uretra dentro do corpo esponjoso, com epitélio pseudoestratificado a estratificado colunar e glândulas mucosas de Littré.',
    caracteristicas: ['Luz em fenda ou pregueada.', 'Epitélio que passa a estratificado pavimentoso na fossa navicular.'],
    aprofundado: ['O corpo esponjoso em volta não fica tão rígido na ereção, deixando a uretra aberta.'],
    funcoes: ['Conduzir urina e sêmen.', 'Suas glândulas de Littré secretam muco que lubrifica a uretra.'],
    regeneracao: { nivel: 'moderada', texto: 'Epitélio renovável; lesões levam a estenose.' },
    ondeEncontrar: ['Corpo esponjoso do pênis.'],
    alteracoes: ['Uretrite (gonocócica, clamídia).', 'Estenose uretral.'],
  },
  {
    id: 'corpo-cavernoso',
    nome: 'Corpo cavernoso',
    sinonimos: ['corpus cavernosum', 'tecido erétil', 'túnica albugínea'],
    tipo: 'regiao',
    resumo: 'Tecido erétil: espaços vasculares irregulares revestidos por endotélio, separados por trabéculas de músculo liso e colágeno, envoltos pela túnica albugínea.',
    caracteristicas: ['Espaços vasculares amplos, muitas vezes com hemácias.', 'Trabéculas fibromusculares; artérias helicinas.'],
    aprofundado: ['Na ereção, o óxido nítrico relaxa o músculo liso, os espaços enchem e comprimem as veias contra a albugínea.'],
    funcoes: ['Ereção do pênis.', 'Encher-se de sangue na ereção: o óxido nítrico relaxa o músculo liso das trabéculas e das artérias helicinas (via GMPc — alvo da sildenafila).', 'Comprimir as veias contra a túnica albugínea, retendo o sangue.'],
    regeneracao: { nivel: 'moderada', texto: 'Fibrose após priapismo ou trauma.' },
    ondeEncontrar: ['Pênis (dois corpos cavernosos dorsais) e clitóris.'],
    alteracoes: ['Doença de Peyronie (placa fibrosa na albugínea).', 'Disfunção erétil vascular.', 'Fibrose pós-priapismo.'],
  },
  {
    id: 'celula-de-leydig',
    nome: 'Célula de Leydig',
    sinonimos: ['célula intersticial', 'Leydig cell'],
    tipo: 'celula',
    resumo: 'Célula poligonal grande, de citoplasma eosinofílico e vacuolado, em grupos no interstício entre os túbulos seminíferos.',
    caracteristicas: ['Grupos perto de capilares, fora dos túbulos; núcleo redondo com nucléolo.', 'Às vezes com cristais de Reinke.', 'Células grandes, poligonais, eosinofílicas, com núcleo redondo e gotículas lipídicas, em grupos no interstício entre os túbulos, perto dos vasos.'],
    aprofundado: ['Produz testosterona sob estímulo do LH.', 'Os cristaloides de Reinke (bastonetes eosinofílicos) são típicos da célula de Leydig humana.'],
    funcoes: ['Síntese de testosterona.', 'Produzir testosterona sob LH: espermatogênese (alta concentração local), caracteres sexuais secundários e libido.', 'Produzir INSL3, envolvido na descida do testículo.'],
    regeneracao: { nivel: 'baixa', texto: 'Renovação lenta.' },
    ondeEncontrar: ['Interstício do testículo.'],
    alteracoes: ['Tumor de células de Leydig.', 'Hipogonadismo.'],
  },
  {
    id: 'celula-de-sertoli',
    nome: 'Célula de Sertoli',
    sinonimos: ['célula sustentacular'],
    tipo: 'celula',
    resumo: 'Célula de sustentação do túbulo seminífero, apoiada na membrana basal, com núcleo triangular e claro e nucléolo evidente.',
    caracteristicas: ['Núcleo pálido, oval ou triangular, perto da base, com nucléolo grande; limites celulares invisíveis.', 'Célula alta, que vai da membrana basal à luz; núcleo grande, claro, triangular ou oval, com nucléolo evidente, perto da base.'],
    aprofundado: ['Forma a barreira hematotesticular, nutre as células germinativas e secreta inibina e ABP.', 'Não se divide no adulto; o número de células de Sertoli define a capacidade máxima de produzir espermatozoides.'],
    funcoes: ['Sustentar a espermatogênese.', 'Sustentar e nutrir as células germinativas e formar a barreira hematotesticular.', 'Secretar proteína ligadora de andrógeno (mantém testosterona alta no túbulo) e inibina (freia o FSH).', 'Fagocitar o citoplasma residual das espermátides.', 'No feto, secretar o hormônio antimülleriano, que faz regredir os ductos de Müller.'],
    regeneracao: { nivel: 'nula', texto: 'Não se dividem no adulto.' },
    ondeEncontrar: ['Túbulos seminíferos.'],
    alteracoes: ['Síndrome de células de Sertoli isoladas (infertilidade).', 'Síndrome de células de Sertoli isoladas (túbulos sem células germinativas).', 'Tumor de células de Sertoli.'],
  },
  {
    id: 'espermatogonia',
    nome: 'Espermatogônia',
    sinonimos: ['spermatogonium'],
    tipo: 'celula',
    resumo: 'Célula germinativa diploide na base do túbulo, junto à membrana basal, com núcleo redondo e pequeno.',
    caracteristicas: ['Fileira mais externa de células germinativas.', 'Célula pequena, redonda, junto à membrana basal do túbulo, com núcleo escuro (tipo A escura), claro (A pálida) ou redondo com grumos (B).'],
    aprofundado: ['Tipo A escura (reserva), tipo A pálida e tipo B, que dá os espermatócitos.', 'Fica fora da barreira hematotesticular, no compartimento basal.'],
    funcoes: ['Manter a linhagem germinativa.', 'Ser a célula-tronco da espermatogênese: dividir-se por mitose para se renovar e gerar espermatócitos.'],
    regeneracao: { nivel: 'alta', texto: 'Células-tronco da espermatogênese.' },
    ondeEncontrar: ['Base do túbulo seminífero.'],
    alteracoes: ['Destruídas por quimioterapia e radioterapia.', 'Destruída por quimioterapia e radiação (infertilidade).', 'Origem das neoplasias de células germinativas (seminoma).'],
  },
  {
    id: 'espermatide',
    nome: 'Espermátide',
    sinonimos: ['spermatid'],
    tipo: 'celula',
    resumo: 'Célula haploide pequena perto da luz do túbulo, que se transforma em espermatozoide (espermiogênese); núcleo pequeno e depois alongado e denso.',
    caracteristicas: ['Camadas mais internas do epitélio seminífero; as tardias têm cabeça escura e alongada voltada para a base.', 'Células pequenas, haploides, perto da luz do túbulo; redondas (iniciais) ou alongadas com núcleo escuro (tardias).'],
    aprofundado: ['Formam acrossomo, flagelo e condensam a cromatina.'],
    funcoes: ['Originar espermatozoides.', 'Transformar-se em espermatozoide (espermiogênese): formar acrossomo, flagelo, condensar a cromatina e perder o citoplasma.'],
    regeneracao: { nivel: 'alta', texto: 'Produzidas continuamente.' },
    ondeEncontrar: ['Perto da luz do túbulo seminífero.'],
    alteracoes: ['Parada de maturação na infertilidade.', 'Parada da espermiogênese e espermatozoides anormais (teratozoospermia).'],
  },
  {
    id: 'rede-testicular',
    nome: 'Rede testicular (rete testis)',
    sinonimos: ['rete testis', 'rede de Haller'],
    tipo: 'regiao',
    resumo: 'Rede de canais anastomosados, de paredes finas e luz irregular, no mediastino do testículo, que recebe os túbulos retos e leva os espermatozoides aos dúctulos eferentes.',
    caracteristicas: ['Espaços irregulares e interligados, revestidos por epitélio simples pavimentoso a cúbico, dentro de conjuntivo denso (mediastino).', 'Fica perto do hilo, onde entram e saem vasos e ductos.'],
    aprofundado: ['Os túbulos seminíferos terminam em túbulos retos, revestidos só por células de Sertoli, que desembocam na rede testicular.', 'Da rede saem 10–20 dúctulos eferentes (epitélio com células ciliadas e não ciliadas alternadas, luz "em dente de serra") até a cabeça do epidídimo.', 'O fluido testicular é parcialmente reabsorvido já na rede e nos dúctulos eferentes.'],
    funcoes: ['Conduzir espermatozoides e fluido testicular dos túbulos seminíferos para os dúctulos eferentes.', 'Iniciar a reabsorção do fluido, concentrando os espermatozoides.'],
    regeneracao: { nivel: 'moderada', texto: 'Epitélio de renovação lenta.' },
    ondeEncontrar: ['Mediastino do testículo.'],
    alteracoes: ['Transformação cística da rede testicular (dilatação por obstrução), comum no idoso.', 'Adenocarcinoma da rede testicular (raro).'],
  },
  {
    id: 'tunica-albuginea-testicular',
    nome: 'Túnica albugínea do testículo',
    sinonimos: ['albugínea', 'cápsula do testículo'],
    tipo: 'camada',
    resumo: 'Cápsula espessa de conjuntivo denso, branca e inextensível, que envolve o testículo e emite septos que o dividem em lóbulos.',
    caracteristicas: ['Faixa grossa de colágeno denso, pobre em células, logo abaixo da túnica vaginal (mesotélio).', 'Da face interna saem septos finos em direção ao mediastino.'],
    aprofundado: ['Por dentro dela fica a túnica vascular, com os vasos que irrigam o parênquima.', 'Por ser inextensível, o edema do testículo aumenta a pressão interna e pode causar isquemia (orquite, torção).'],
    funcoes: ['Proteger os túbulos seminíferos e manter a pressão interna que ajuda a empurrar os espermatozoides para a rede testicular.', 'Dividir o testículo em cerca de 250 lóbulos pelos septos.'],
    regeneracao: { nivel: 'baixa', texto: 'Colágeno denso cicatriza com fibrose.' },
    ondeEncontrar: ['Testículo; no pênis, uma albugínea semelhante envolve os corpos cavernosos.'],
    alteracoes: ['Ruptura na trauma testicular (exige cirurgia).', 'Placas fibrosas na albugínea do pênis (doença de Peyronie).'],
  },
  {
    id: 'concrecao-prostatica',
    nome: 'Concreção prostática (corpo amiláceo)',
    sinonimos: ['corpora amylacea', 'corpo amiláceo', 'concreção prostática'],
    tipo: 'matriz',
    resumo: 'Corpo arredondado, eosinofílico e em lamelas concêntricas, dentro da luz das glândulas da próstata.',
    caracteristicas: ['Esfera rosa (às vezes roxa se calcificada), com anéis concêntricos como casca de cebola, maior que as células em volta.', 'Fica solta na luz glandular.'],
    aprofundado: ['Formada pela condensação de secreção prostática (glicoproteínas) e restos celulares; aumenta em número com a idade.', 'Pode calcificar e formar cálculos prostáticos, visíveis na ultrassonografia.', 'Sua presença ajuda a reconhecer a próstata e é rara no adenocarcinoma (onde aparecem cristaloides).'],
    funcoes: ['Não tem função: é marco diagnóstico da próstata normal e do envelhecimento glandular.', 'Indica acúmulo de secreção na luz das glândulas.'],
    regeneracao: { nivel: 'nao-se-aplica', texto: 'Depósito na luz: não se renova.' },
    ondeEncontrar: ['Próstata; corpos amiláceos de outro tipo aparecem no SNC do idoso (astrócitos) e no pulmão.'],
    alteracoes: ['Cálculos prostáticos associados a prostatite crônica.', 'Reação inflamatória a concreções rotas.'],
  },
]
