import type { Estrutura } from '../tipos'

/** Sistema reprodutor masculino. */
export const ESTRUTURAS_REPRODUTOR_MASCULINO: Estrutura[] = [
  {
    id: 'tubulo-seminifero',
    nome: 'Túbulo seminífero',
    sinonimos: ['seminiferous tubule', 'epitélio germinativo', 'célula de Sertoli'],
    tipo: 'orgao-parte',
    resumo: 'Túbulo enovelado do testículo revestido pelo epitélio seminífero: células germinativas em maturação apoiadas nas células de Sertoli.',
    caracteristicas: [
      'Da base para a luz: espermatogônias, espermatócitos, espermátides e espermatozoides.',
      'Células de Sertoli: núcleo claro, triangular, com nucléolo nítido, apoiadas na base.',
      'Envolto pela túnica própria; entre os túbulos, o interstício com células de Leydig.',
    ],
    aprofundado: [
      'As junções de oclusão entre as Sertoli formam a barreira hematotesticular.',
      'Um ciclo completo de espermatogênese leva ~64–74 dias no humano.',
    ],
    funcoes: ['Produzir espermatozoides.'],
    regeneracao: { nivel: 'moderada', texto: 'Espermatogônias-tronco repovoam o epitélio; lesões graves deixam só células de Sertoli.' },
    ondeEncontrar: ['Lóbulos do testículo.'],
    alteracoes: ['Parada de maturação e síndrome só-Sertoli (infertilidade).', 'Neoplasia de células germinativas in situ.', 'Atrofia na criptorquidia.'],
  },
  {
    id: 'espermatocito',
    nome: 'Espermatócito',
    sinonimos: ['spermatocyte', 'espermatócito primário'],
    tipo: 'celula',
    resumo: 'Célula germinativa em meiose, a maior do epitélio seminífero, com núcleo grande de cromatina em fios ou grumos.',
    caracteristicas: ['Núcleo grande e redondo com cromatina filamentosa (prófase I longa).', 'Fica na camada média do epitélio, acima das espermatogônias.'],
    aprofundado: ['O primário passa ~3 semanas em prófase I (paquíteno); o secundário existe por poucas horas e raramente é visto.'],
    funcoes: ['Reduzir o número de cromossomos pela meiose.'],
    regeneracao: { nivel: 'alta', texto: 'Produzido continuamente a partir das espermatogônias.' },
    ondeEncontrar: ['Epitélio dos túbulos seminíferos.'],
    alteracoes: ['Parada meiótica em infertilidade; seminoma deriva de células germinativas.'],
  },
  {
    id: 'tunica-propria-seminifera',
    nome: 'Túnica própria do túbulo seminífero',
    sinonimos: ['células mioides', 'lâmina limitante'],
    tipo: 'camada',
    resumo: 'Envoltório fino do túbulo seminífero: lâmina basal, colágeno e células mioides achatadas e contráteis.',
    caracteristicas: ['Faixa eosinófila fina com núcleos alongados e achatados em volta de cada túbulo.'],
    aprofundado: ['As células mioides contraem e empurram os espermatozoides para a rede testicular.'],
    funcoes: ['Sustentar o túbulo e impulsionar o conteúdo.'],
    regeneracao: { nivel: 'moderada', texto: 'Conjuntivo.' },
    ondeEncontrar: ['Em volta dos túbulos seminíferos.'],
    alteracoes: ['Espessamento e hialinização na atrofia testicular e na infertilidade.'],
  },
  {
    id: 'epitelio-pseudoestratificado-estereociliado',
    nome: 'Epitélio pseudoestratificado com estereocílios',
    sinonimos: ['estereocílios', 'epitélio do epidídimo', 'epitélio do ducto deferente'],
    tipo: 'epitelio',
    resumo: 'Epitélio de células colunares altas com estereocílios (microvilosidades longas) e células basais, que reveste epidídimo e ducto deferente.',
    caracteristicas: ['Núcleos em dois níveis (colunares e basais).', 'Tufo apical de estereocílios.'],
    aprofundado: ['Os estereocílios são microvilosidades imóveis que absorvem o líquido testicular.'],
    funcoes: ['Absorver líquido e secretar substâncias que ajudam na maturação dos espermatozoides.'],
    regeneracao: { nivel: 'moderada', texto: 'Células basais repõem o epitélio.' },
    ondeEncontrar: ['Epidídimo e ducto deferente.'],
    alteracoes: ['Granuloma espermático após vasectomia.'],
  },
  {
    id: 'glandula-prostatica',
    nome: 'Glândula prostática',
    sinonimos: ['ácino prostático', 'corpos amiláceos'],
    tipo: 'glandula',
    resumo: 'Glândula túbulo-alveolar de luz ampla e contorno irregular, com epitélio colunar secretor sobre uma camada de células basais.',
    caracteristicas: ['Pregas papilares para a luz.', 'Duas camadas: luminal colunar e basal achatada.', 'Corpos amiláceos (concreções lamelares) na luz, sobretudo com a idade.'],
    aprofundado: ['Secreta PSA, fosfatase ácida prostática, citrato e zinco.', 'A ausência da camada basal (p63/CK34βE12) sugere carcinoma.'],
    funcoes: ['Produzir parte do líquido seminal.'],
    regeneracao: { nivel: 'moderada', texto: 'Dependente de andrógenos.' },
    ondeEncontrar: ['Próstata (zonas periférica, central e de transição).'],
    alteracoes: ['Hiperplasia prostática benigna (zona de transição).', 'Adenocarcinoma de próstata (zona periférica).', 'Prostatite.'],
  },
  {
    id: 'estroma-fibromuscular',
    nome: 'Estroma fibromuscular',
    sinonimos: ['estroma prostático'],
    tipo: 'matriz',
    resumo: 'Conjuntivo denso misturado a músculo liso, entre as glândulas da próstata.',
    caracteristicas: ['Faixas eosinófilas com núcleos alongados de fibroblastos e células musculares lisas.'],
    aprofundado: ['A contração do músculo liso expele a secreção na ejaculação; é alvo dos alfabloqueadores.'],
    funcoes: ['Sustentar as glândulas e expulsar a secreção.'],
    regeneracao: { nivel: 'moderada', texto: 'Hiperplasia com a idade.' },
    ondeEncontrar: ['Próstata.'],
    alteracoes: ['Nódulos estromais na hiperplasia prostática benigna.'],
  },
  {
    id: 'uretra-peniana',
    nome: 'Uretra peniana (esponjosa)',
    sinonimos: ['uretra esponjosa', 'glândulas de Littré'],
    tipo: 'orgao-parte',
    resumo: 'Segmento da uretra dentro do corpo esponjoso, com epitélio pseudoestratificado a estratificado colunar e glândulas mucosas de Littré.',
    caracteristicas: ['Luz em fenda ou pregueada.', 'Epitélio que passa a estratificado pavimentoso na fossa navicular.'],
    aprofundado: ['O corpo esponjoso em volta não fica tão rígido na ereção, deixando a uretra aberta.'],
    funcoes: ['Conduzir urina e sêmen.'],
    regeneracao: { nivel: 'moderada', texto: 'Epitélio renovável; lesões levam a estenose.' },
    ondeEncontrar: ['Corpo esponjoso do pênis.'],
    alteracoes: ['Uretrite (gonocócica, clamídia).', 'Estenose uretral.'],
  },
  {
    id: 'corpo-cavernoso',
    nome: 'Corpo cavernoso',
    sinonimos: ['corpus cavernosum', 'tecido erétil', 'túnica albugínea'],
    tipo: 'regiao',
    resumo: 'Tecido erétil: espaços vasculares irregulares revestidos por endotélio, separados por trabéculas de músculo liso e colágeno, envoltos pela túnica albugínea.',
    caracteristicas: ['Espaços vasculares amplos, muitas vezes com hemácias.', 'Trabéculas fibromusculares; artérias helicinas.'],
    aprofundado: ['Na ereção, o óxido nítrico relaxa o músculo liso, os espaços enchem e comprimem as veias contra a albugínea.'],
    funcoes: ['Ereção do pênis.'],
    regeneracao: { nivel: 'moderada', texto: 'Fibrose após priapismo ou trauma.' },
    ondeEncontrar: ['Pênis (dois corpos cavernosos dorsais) e clitóris.'],
    alteracoes: ['Doença de Peyronie (placa fibrosa na albugínea).', 'Disfunção erétil vascular.', 'Fibrose pós-priapismo.'],
  },
]
