import type { Estrutura } from '../tipos'

/** Sistema reprodutor feminino e mama. */
export const ESTRUTURAS_REPRODUTOR_FEMININO: Estrutura[] = [
  {
    id: 'epitelio-superficial-ovario',
    nome: 'Epitélio superficial do ovário',
    sinonimos: ['epitélio germinativo', 'mesotélio ovariano', 'túnica albugínea'],
    tipo: 'epitelio',
    resumo: 'Epitélio simples cúbico a pavimentoso (mesotélio modificado) que reveste o ovário, sobre a túnica albugínea.',
    caracteristicas: ['Uma camada de células cúbicas baixas na superfície.', 'Abaixo, a túnica albugínea de conjuntivo denso.'],
    aprofundado: ['Apesar do nome histórico "epitélio germinativo", não forma células germinativas.', 'Participa do reparo da superfície após cada ovulação.'],
    funcoes: ['Revestir o ovário e reparar a superfície após a ovulação.'],
    regeneracao: { nivel: 'alta', texto: 'Prolifera para fechar a ferida da ovulação.' },
    ondeEncontrar: ['Superfície do ovário.'],
    alteracoes: ['Cistos de inclusão; parte dos carcinomas serosos (a maioria nasce na tuba).'],
  },
  {
    id: 'estroma-ovariano',
    nome: 'Estroma ovariano',
    sinonimos: ['estroma cortical', 'ovarian stroma'],
    tipo: 'matriz',
    resumo: 'Tecido de células fusiformes muito juntas, em redemoinhos, onde ficam os folículos.',
    caracteristicas: ['Células alongadas de núcleo escuro em arranjo estoriforme (em redemoinho).', 'Vasos numerosos, sobretudo na medula.'],
    aprofundado: ['As células do estroma formam as tecas dos folículos em crescimento.'],
    funcoes: ['Sustentar os folículos e dar origem às tecas.'],
    regeneracao: { nivel: 'moderada', texto: 'Remodela-se a cada ciclo.' },
    ondeEncontrar: ['Córtex e medula do ovário.'],
    alteracoes: ['Hiperplasia estromal e hipertecose.', 'Fibroma e tecoma ovarianos.'],
  },
  {
    id: 'ovocito',
    nome: 'Ovócito',
    sinonimos: ['oócito', 'oocyte', 'zona pelúcida'],
    tipo: 'celula',
    resumo: 'Célula germinativa feminina: grande, redonda, com núcleo claro (vesícula germinativa) e nucléolo evidente, dentro do folículo.',
    caracteristicas: ['Maior célula do ovário (até ~120 µm).', 'Zona pelúcida eosinófila em volta, a partir do folículo primário.'],
    aprofundado: ['Parado na prófase I da meiose desde a vida fetal até a ovulação.'],
    funcoes: ['Gerar o gameta feminino.'],
    regeneracao: { nivel: 'nula', texto: 'Reserva fixa desde o nascimento, em declínio até a menopausa.' },
    ondeEncontrar: ['Folículos ovarianos.'],
    alteracoes: ['Atresia folicular.', 'Teratomas derivam de células germinativas.'],
  },
  {
    id: 'foliculo-primario',
    nome: 'Folículo primário',
    sinonimos: ['primary follicle', 'folículo primordial'],
    tipo: 'orgao-parte',
    resumo: 'Folículo inicial: ovócito envolto por uma camada de células foliculares cúbicas.',
    caracteristicas: ['Primordial: células achatadas; primário: células cúbicas em uma camada.', 'Localizado no córtex superficial.'],
    aprofundado: ['O crescimento inicial independe do FSH.'],
    funcoes: ['Iniciar o crescimento folicular.'],
    regeneracao: { nivel: 'nula', texto: 'A reserva não é reposta.' },
    ondeEncontrar: ['Córtex ovariano.'],
    alteracoes: ['Insuficiência ovariana prematura (depleção).'],
  },
  {
    id: 'foliculo-secundario',
    nome: 'Folículo secundário (pré-antral)',
    sinonimos: ['secondary follicle', 'folículo em crescimento'],
    tipo: 'orgao-parte',
    resumo: 'Folículo com várias camadas de granulosa, que começam a acumular líquido em pequenas cavidades.',
    caracteristicas: ['Granulosa estratificada; tecas se diferenciando por fora.', 'Pequenos espaços de líquido (corpos de Call-Exner) antes do antro.'],
    aprofundado: ['Passa a depender do FSH.'],
    funcoes: ['Crescer e produzir estrógenos.'],
    regeneracao: { nivel: 'nula', texto: 'Recrutado da reserva fixa.' },
    ondeEncontrar: ['Córtex ovariano.'],
    alteracoes: ['Tumor de células da granulosa (corpos de Call-Exner).'],
  },
  {
    id: 'foliculo-antral',
    nome: 'Folículo antral (terciário)',
    sinonimos: ['antral follicle', 'folículo de De Graaf', 'antro'],
    tipo: 'orgao-parte',
    resumo: 'Folículo com uma cavidade única (antro) cheia de líquido folicular, cercada pela granulosa e pelas tecas.',
    caracteristicas: ['Antro claro; ovócito no cúmulo oóforo.', 'Granulosa em volta e tecas interna (células claras) e externa (fibrosa).'],
    aprofundado: ['O folículo dominante (de Graaf) chega a ~20 mm antes de ovular.'],
    funcoes: ['Amadurecer o ovócito e produzir estradiol.'],
    regeneracao: { nivel: 'nula', texto: 'Os não dominantes sofrem atresia.' },
    ondeEncontrar: ['Ovário em idade reprodutiva.'],
    alteracoes: ['Cisto folicular.', 'Síndrome dos ovários policísticos.'],
  },
  {
    id: 'granulosa',
    nome: 'Células da granulosa',
    sinonimos: ['granulosa cells', 'membrana granulosa'],
    tipo: 'celula',
    resumo: 'Células epiteliais do folículo, pequenas e densas, que envolvem o ovócito e revestem o antro.',
    caracteristicas: ['Camadas de células pequenas de núcleo redondo e escuro, sem vasos.', 'Separadas da teca por membrana basal.'],
    aprofundado: ['Convertem andrógenos da teca em estradiol pela aromatase (modelo das duas células).', 'Após a ovulação viram células luteínicas da granulosa.'],
    funcoes: ['Nutrir o ovócito e produzir estrógeno.'],
    regeneracao: { nivel: 'moderada', texto: 'Proliferam intensamente no crescimento folicular.' },
    ondeEncontrar: ['Folículos ovarianos.'],
    alteracoes: ['Tumor de células da granulosa.'],
  },
  {
    id: 'teca-folicular',
    nome: 'Teca folicular',
    sinonimos: ['teca interna', 'teca externa', 'theca'],
    tipo: 'camada',
    resumo: 'Envoltório do folículo formado pelo estroma: teca interna (células claras, produtoras de andrógeno, vascularizada) e teca externa (fibrosa).',
    caracteristicas: ['Camadas concêntricas de células fusiformes e epitelioides por fora da granulosa.'],
    aprofundado: ['A teca interna responde ao LH produzindo androstenediona.'],
    funcoes: ['Produzir andrógenos precursores do estrógeno; sustentar o folículo.'],
    regeneracao: { nivel: 'moderada', texto: 'Formada de novo a cada folículo recrutado.' },
    ondeEncontrar: ['Folículos secundários e antrais.'],
    alteracoes: ['Hiperplasia tecal na síndrome dos ovários policísticos.', 'Tecoma.'],
  },
  {
    id: 'epitelio-tubario',
    nome: 'Epitélio da tuba uterina',
    sinonimos: ['células ciliadas', 'células intercalares', 'células secretoras', 'Peg cells'],
    tipo: 'epitelio',
    resumo: 'Epitélio simples colunar com células ciliadas e secretoras, sobre pregas longas e ramificadas.',
    caracteristicas: ['Mistura de células ciliadas (citoplasma claro) e secretoras (sem cílios, núcleo alongado).'],
    aprofundado: ['Os cílios batem em direção ao útero; a proporção varia com o ciclo hormonal.'],
    funcoes: ['Transportar e nutrir o ovócito e o embrião inicial.'],
    regeneracao: { nivel: 'alta', texto: 'Renovado ciclicamente.' },
    ondeEncontrar: ['Tuba uterina (mais pregueada na ampola).'],
    alteracoes: ['Salpingite e hidrossalpinge.', 'Gravidez ectópica.', 'Carcinoma seroso de alto grau (lesão precursora STIC nas fímbrias).'],
  },
  {
    id: 'glandula-endometrial',
    nome: 'Glândula endometrial',
    sinonimos: ['endometrial gland'],
    tipo: 'glandula',
    resumo: 'Glândula tubular simples do endométrio, cuja forma muda ao longo do ciclo menstrual.',
    caracteristicas: ['Proliferativa: retas, com mitoses e núcleos pseudoestratificados.', 'Secretora: tortuosas, com vacúolos de glicogênio e secreção na luz.'],
    aprofundado: ['Renovam-se a partir da camada basal após cada menstruação.'],
    funcoes: ['Nutrir o embrião antes da placenta (secreção uterina).'],
    regeneracao: { nivel: 'alta', texto: 'Regeneração completa a cada ciclo.' },
    ondeEncontrar: ['Endométrio.'],
    alteracoes: ['Hiperplasia endometrial.', 'Adenocarcinoma endometrioide.', 'Endometriose (glândulas fora do útero).'],
  },
  {
    id: 'estroma-endometrial',
    nome: 'Estroma endometrial',
    sinonimos: ['células deciduais', 'decídua'],
    tipo: 'matriz',
    resumo: 'Tecido muito celular de células pequenas e núcleo oval entre as glândulas do endométrio, com artérias espiraladas.',
    caracteristicas: ['Núcleos densos com pouco citoplasma; na fase secretora tardia, células deciduais grandes e rosadas.'],
    aprofundado: ['A decidualização prepara a implantação; o colapso das artérias espiraladas causa a menstruação.'],
    funcoes: ['Sustentar as glândulas e formar a decídua na gestação.'],
    regeneracao: { nivel: 'alta', texto: 'Regenera a cada ciclo.' },
    ondeEncontrar: ['Endométrio.'],
    alteracoes: ['Endometrite crônica (plasmócitos).', 'Sarcoma do estroma endometrial.'],
  },
  {
    id: 'miometrio',
    nome: 'Miométrio',
    sinonimos: ['myometrium'],
    tipo: 'camada',
    resumo: 'Camada muscular espessa do útero: feixes de músculo liso entrelaçados, com vasos calibrosos na camada média.',
    caracteristicas: ['Feixes cortados em várias direções; conjuntivo entre eles.'],
    aprofundado: ['Na gestação cresce por hipertrofia e hiperplasia; contrai sob ocitocina no parto.'],
    funcoes: ['Contração no parto e na menstruação.'],
    regeneracao: { nivel: 'moderada', texto: 'Grande plasticidade na gestação.' },
    ondeEncontrar: ['Parede do útero.'],
    alteracoes: ['Leiomioma (mioma).', 'Adenomiose (glândulas endometriais no miométrio).'],
  },
  {
    id: 'estroma-cervical',
    nome: 'Estroma do colo uterino',
    sinonimos: ['cervical stroma'],
    tipo: 'matriz',
    resumo: 'Conjuntivo fibroso denso com pouco músculo liso que forma a parede do colo uterino.',
    caracteristicas: ['Colágeno denso com fibroblastos; glândulas endocervicais mergulhadas nele.'],
    aprofundado: ['Amadurece (amolece) no fim da gestação pela reorganização do colágeno, permitindo a dilatação.'],
    funcoes: ['Manter o colo fechado durante a gestação.'],
    regeneracao: { nivel: 'moderada', texto: 'Conjuntivo.' },
    ondeEncontrar: ['Colo uterino.'],
    alteracoes: ['Insuficiência istmo-cervical.', 'Invasão por carcinoma cervical.'],
  },
  {
    id: 'cisto-de-naboth',
    nome: 'Cisto de Naboth',
    sinonimos: ['nabothian cyst'],
    tipo: 'orgao-parte',
    resumo: 'Glândula endocervical dilatada por muco retido quando o orifício é coberto por epitélio escamoso.',
    caracteristicas: ['Cavidade redonda, revestida por epitélio achatado, cheia de muco.'],
    aprofundado: ['Comum na zona de transformação, onde a metaplasia escamosa cobre as glândulas.'],
    funcoes: ['Nenhuma: achado benigno.'],
    regeneracao: { nivel: 'nao-se-aplica', texto: 'Alteração benigna.' },
    ondeEncontrar: ['Colo uterino.'],
    alteracoes: ['Benigno; não confundir com adenocarcinoma de desvio mínimo.'],
  },
  {
    id: 'lobulo-mamario',
    nome: 'Lóbulo mamário (UDLT)',
    sinonimos: ['unidade ductolobular terminal', 'TDLU', 'ácinos mamários'],
    tipo: 'glandula',
    resumo: 'Unidade funcional da mama: um ducto terminal com seus pequenos ácinos, num estroma intralobular frouxo.',
    caracteristicas: ['Grupos de pequenos túbulos com epitélio luminal e camada mioepitelial.', 'Estroma intralobular mais frouxo que o interlobular denso.'],
    aprofundado: ['Origem da maioria dos carcinomas mamários.'],
    funcoes: ['Produzir leite na lactação.'],
    regeneracao: { nivel: 'alta', texto: 'Proliferam e involuem a cada ciclo e gestação.' },
    ondeEncontrar: ['Glândula mamária.'],
    alteracoes: ['Alterações fibrocísticas.', 'Fibroadenoma.', 'Carcinoma lobular e ductal.'],
  },
  {
    id: 'alveolo-mamario',
    nome: 'Alvéolo mamário secretor',
    sinonimos: ['alvéolo lactante'],
    tipo: 'glandula',
    resumo: 'Ácino dilatado da mama na gestação e lactação, com células secretoras vacuolizadas e leite na luz.',
    caracteristicas: ['Luz ampla, epitélio cúbico com vacúolos de lipídio; lóbulos ocupam quase todo o tecido.'],
    aprofundado: ['Secreção merócrina (proteínas) e apócrina (gotas de lipídio).'],
    funcoes: ['Secretar leite.'],
    regeneracao: { nivel: 'alta', texto: 'Involui após o desmame.' },
    ondeEncontrar: ['Mama gestante e lactante.'],
    alteracoes: ['Mastite puerperal; galactocele.'],
  },
  {
    id: 'celula-mioepitelial',
    nome: 'Célula mioepitelial',
    sinonimos: ['myoepithelial cell', 'célula em cesto'],
    tipo: 'celula',
    resumo: 'Célula contrátil entre o epitélio secretor e a membrana basal, positiva para actina de músculo liso (SMA) e p63.',
    caracteristicas: ['Achatada ou estrelada, abraçando ductos e alvéolos.'],
    aprofundado: ['Contrai sob ocitocina (ejeção do leite).', 'Sua presença em volta de proliferações diferencia lesões benignas de carcinoma invasor.'],
    funcoes: ['Expulsar a secreção glandular.'],
    regeneracao: { nivel: 'moderada', texto: 'Renovada com o epitélio.' },
    ondeEncontrar: ['Mama, glândulas salivares, sudoríparas, lacrimais.'],
    alteracoes: ['Perda da camada mioepitelial no carcinoma invasor.', 'Adenoma pleomórfico e mioepitelioma.'],
  },
  {
    id: 'corpo-luteo',
    nome: 'Corpo lúteo',
    sinonimos: ['corpo amarelo'],
    tipo: 'orgao-parte',
    resumo: 'Estrutura grande e pregueada formada após a ovulação: células luteínicas grandes e pálidas (granulosa-luteínicas) e menores (teca-luteínicas).',
    caracteristicas: ['Parede espessa e ondulada de células grandes de citoplasma claro e vacuolado, com centro de fibrina ou coágulo.'],
    aprofundado: ['Secreta progesterona e estrogênio; mantém-se na gravidez por ação do hCG.'],
    funcoes: ['Preparar e manter o endométrio para a implantação.'],
    regeneracao: { nivel: 'nula', texto: 'Involui em corpo albicans.' },
    ondeEncontrar: ['Córtex do ovário na fase lútea e na gravidez.'],
    alteracoes: ['Cisto de corpo lúteo hemorrágico.'],
  },
  {
    id: 'corpo-albicans',
    nome: 'Corpo albicans',
    sinonimos: ['corpo branco'],
    tipo: 'orgao-parte',
    resumo: 'Cicatriz hialina, pálida e acelular de um corpo lúteo que regrediu.',
    caracteristicas: ['Massa ondulada rosa-pálida e homogênea no estroma ovariano.'],
    aprofundado: ['Acumulam-se com a idade.'],
    funcoes: ['Nenhuma (cicatriz).'],
    regeneracao: { nivel: 'nula', texto: 'Reabsorção lenta.' },
    ondeEncontrar: ['Ovário adulto.'],
    alteracoes: ['Numerosos na pós-menopausa.'],
  },
  {
    id: 'endometrio',
    nome: 'Endométrio',
    sinonimos: ['mucosa uterina'],
    tipo: 'camada',
    resumo: 'Mucosa do útero: epitélio simples colunar, glândulas tubulares e estroma celular, dividida em camada funcional e basal.',
    caracteristicas: ['Glândulas em estroma denso de células pequenas, sobre o miométrio.'],
    aprofundado: ['A camada funcional descama na menstruação e é refeita a partir da basal.'],
    funcoes: ['Receber o embrião.'],
    regeneracao: { nivel: 'alta', texto: 'Regenera a cada ciclo.' },
    ondeEncontrar: ['Cavidade uterina.'],
    alteracoes: ['Hiperplasia e adenocarcinoma de endométrio.', 'Endometriose.'],
  },
  {
    id: 'decidua',
    nome: 'Decídua (células deciduais)',
    sinonimos: ['células deciduais', 'reação decidual', 'decidua'],
    tipo: 'celula',
    resumo: 'Estroma endometrial transformado na gravidez: células grandes, poligonais, de citoplasma amplo, pálido e eosinofílico, com limites nítidos.',
    caracteristicas: ['Lençóis de células grandes e claras, parecidas com células epiteliais, com núcleo redondo central.', 'Vasos dilatados; no útero gravídico, vilosidades coriais podem aparecer ao lado.'],
    aprofundado: ['A progesterona faz as células do estroma acumularem glicogênio e lipídios e secretarem prolactina e IGFBP-1.'],
    funcoes: ['Nutrir o embrião e limitar a invasão do trofoblasto.'],
    regeneracao: { nivel: 'alta', texto: 'Eliminada no pós-parto e refeita a cada gravidez.' },
    ondeEncontrar: ['Útero gravídico, gravidez ectópica, uso de progestágenos.'],
    alteracoes: ['Acretismo placentário quando falta decídua.', 'Reação decidual em ovário ou peritônio pode imitar tumor.'],
  },
  {
    id: 'glandula-endometrial-secretora',
    nome: 'Glândula endometrial secretora',
    sinonimos: ['glândula em dente de serra', 'fase secretora'],
    tipo: 'glandula',
    resumo: 'Glândula do endométrio na fase lútea: tortuosa, serrilhada, com luz ampla contendo secreção e epitélio com vacúolos de glicogênio.',
    caracteristicas: ['Contorno em "dente de serra" e luz dilatada com secreção rosa.', 'Estroma edemaciado entre as glândulas.'],
    aprofundado: ['A progesterona do corpo lúteo converte as glândulas proliferativas retas em secretoras.'],
    funcoes: ['Nutrir o embrião antes da implantação.'],
    regeneracao: { nivel: 'alta', texto: 'Descamam na menstruação.' },
    ondeEncontrar: ['Endométrio na fase secretora e na gravidez inicial.'],
    alteracoes: ['Datação do endométrio na investigação de infertilidade.'],
  },
]
