import type { Estrutura } from '../tipos'

/** Células do sangue periférico e da medula óssea (esfregaços em May-Grünwald-Giemsa). */
export const ESTRUTURAS_SANGUE: Estrutura[] = [
  {
    id: 'neutrofilo',
    nome: 'Neutrófilo',
    sinonimos: ['neutrophil', 'polimorfonuclear', 'segmentado', 'PMN'],
    tipo: 'celula',
    resumo: 'Leucócito mais numeroso (50–70 %): núcleo com 3–5 lóbulos ligados por filamentos e citoplasma rosado com grânulos finos.',
    caracteristicas: [
      'Célula de 10–12 µm, maior que a hemácia.',
      'Núcleo segmentado em 3–5 lóbulos de cromatina condensada.',
      'Citoplasma rosa-claro com granulação fina, quase neutra (daí o nome).',
    ],
    aprofundado: [
      'Grânulos primários (azurófilos: mieloperoxidase), secundários (específicos: lactoferrina) e terciários (gelatinase).',
      'Primeira célula a chegar à inflamação aguda; mata por fagocitose, explosão respiratória e NETs.',
      'Vive ~1 dia no sangue; baqueta de tambor (cromatina sexual) em parte dos neutrófilos de mulheres.',
    ],
    funcoes: ['Fagocitar e destruir bactérias e fungos.', 'Iniciar a inflamação aguda.', 'Liberar armadilhas extracelulares de DNA (NETs) que prendem microrganismos.', 'Ser o primeiro leucócito a chegar à inflamação aguda (minutos a horas), atraído por IL-8 e C5a.'],
    regeneracao: { nivel: 'alta', texto: 'A medula produz ~10¹¹ por dia, e mais na infecção (desvio à esquerda).' },
    ondeEncontrar: ['Sangue periférico; tecidos com inflamação aguda (pus).'],
    alteracoes: [
      'Neutrofilia com desvio à esquerda (bastões) nas infecções bacterianas.',
      'Hipersegmentação (≥ 6 lóbulos) na deficiência de B12 e folato.',
      'Granulações tóxicas e corpúsculos de Döhle na sepse; neutropenia por quimioterapia.',
    ],
  },
  {
    id: 'linfocito',
    nome: 'Linfócito',
    sinonimos: ['lymphocyte', 'linfócito pequeno', 'linfócito T', 'linfócito B', 'NK'],
    tipo: 'celula',
    resumo: 'Leucócito de núcleo redondo e escuro que ocupa quase toda a célula, com um aro fino de citoplasma azul-claro.',
    caracteristicas: [
      'Pequeno (7–9 µm, do tamanho de uma hemácia) ou grande (até 15 µm, com mais citoplasma).',
      'Núcleo redondo, cromatina densa em blocos, sem nucléolo visível.',
      'Citoplasma escasso, basófilo; o grande pode ter alguns grânulos azurófilos (células NK).',
    ],
    aprofundado: [
      'T, B e NK são indistinguíveis na coloração de rotina: precisam de imunofenotipagem (CD3, CD19, CD56).',
      '20–40 % dos leucócitos do adulto; maioria na infância.',
      'Recirculam entre sangue, linfonodos e baço; alguns vivem anos (memória).',
    ],
    funcoes: ['Imunidade adaptativa: anticorpos (B), citotoxicidade e regulação (T).', 'Imunidade inata contra células infectadas e tumorais (NK).', 'Guardar memória imunológica por anos (linfócitos de memória).', 'Recircular entre sangue, linfonodos e linfa, patrulhando o corpo.'],
    regeneracao: { nivel: 'alta', texto: 'Produzidos na medula e no timo; expandem-se clonalmente diante de antígenos.' },
    ondeEncontrar: ['Sangue, linfonodos, baço, timo, tonsilas, MALT, linfa.'],
    alteracoes: [
      'Linfócitos atípicos (reativos) na mononucleose infecciosa.',
      'Leucemia linfoide crônica: linfócitos pequenos maduros e "manchas de Gumprecht".',
      'Linfopenia no HIV e com corticoides.',
    ],
  },
  {
    id: 'monocito',
    nome: 'Monócito',
    sinonimos: ['monocyte'],
    tipo: 'celula',
    resumo: 'Maior leucócito do sangue (12–20 µm): núcleo em rim ou ferradura, cromatina frouxa e citoplasma cinza-azulado abundante.',
    caracteristicas: [
      'Núcleo excêntrico, reniforme ou dobrado, com cromatina rendada (mais clara que a do linfócito).',
      'Citoplasma amplo, azul-acinzentado ("vidro fosco"), às vezes com vacúolos e grânulos finos.',
    ],
    aprofundado: [
      '2–8 % dos leucócitos; circula 1–3 dias e migra para os tecidos, onde vira macrófago ou célula dendrítica.',
      'Precursor dos osteoclastos, das células de Kupffer e da micróglia (esta, em parte, de origem embrionária).',
    ],
    funcoes: ['Fagocitose e apresentação de antígenos.', 'Origem dos macrófagos teciduais.', 'Diferenciar-se em macrófagos teciduais e em células dendríticas.', 'Produzir citocinas (IL-1, TNF, IL-6) que causam febre e resposta de fase aguda.'],
    regeneracao: { nivel: 'alta', texto: 'Produzido continuamente na medula a partir do monoblasto.' },
    ondeEncontrar: ['Sangue periférico; nos tecidos, como macrófago.'],
    alteracoes: ['Monocitose na tuberculose, endocardite e recuperação de neutropenia.', 'Leucemia mielomonocítica crônica.'],
  },
  {
    id: 'basofilo',
    nome: 'Basófilo',
    sinonimos: ['basophil'],
    tipo: 'celula',
    resumo: 'Leucócito mais raro (< 1 %): grânulos grosseiros roxo-escuros que cobrem o núcleo bilobado.',
    caracteristicas: [
      'Célula de 10–12 µm.',
      'Grânulos grandes, metacromáticos, azul-violeta intenso, espalhados sobre o núcleo e o citoplasma.',
      'Núcleo bi ou trilobado, muitas vezes escondido pelos grânulos.',
    ],
    aprofundado: [
      'Grânulos com histamina, heparina e leucotrienos; receptores de IgE de alta afinidade.',
      'Parente funcional do mastócito, mas de linhagem distinta.',
    ],
    funcoes: ['Reações alérgicas (hipersensibilidade tipo I) e defesa contra parasitas.', 'Liberar histamina, heparina e leucotrienos quando a IgE ligada à superfície encontra o alérgeno.', 'Produzir IL-4, que direciona a resposta imune para o padrão Th2.'],
    regeneracao: { nivel: 'alta', texto: 'Produzido na medula.' },
    ondeEncontrar: ['Sangue periférico (raro).'],
    alteracoes: ['Basofilia é marcador de leucemia mieloide crônica.'],
  },
  {
    id: 'eosinofilo',
    nome: 'Eosinófilo',
    sinonimos: ['eosinophil'],
    tipo: 'celula',
    resumo: 'Leucócito com grânulos grandes e alaranjados (eosinófilos) e núcleo bilobado "em óculos".',
    caracteristicas: ['Célula de 12–15 µm.', 'Grânulos grosseiros, refringentes, laranja-avermelhados, enchendo o citoplasma.', 'Núcleo geralmente com dois lóbulos.'],
    aprofundado: [
      'Grânulos com núcleo cristaloide de proteína básica principal, proteína catiônica eosinofílica e peroxidase.',
      '1–4 % dos leucócitos; vive sobretudo nos tecidos (mucosa intestinal, respiratória).',
    ],
    funcoes: ['Defesa contra helmintos.', 'Modulação da alergia e da asma.', 'Liberar proteína básica principal e peroxidase eosinofílica, tóxicas para helmintos (e para o epitélio brônquico na asma).', 'Controlar as reações alérgicas, degradando histamina e leucotrienos.'],
    regeneracao: { nivel: 'alta', texto: 'Produzido na medula sob estímulo da IL-5.' },
    ondeEncontrar: ['Sangue, medula óssea, lâmina própria do intestino e das vias aéreas.'],
    alteracoes: ['Eosinofilia em parasitoses, alergias, asma, reações a fármacos e síndrome hipereosinofílica.', 'Cristais de Charcot-Leyden no escarro asmático.'],
  },
  {
    id: 'metamielocito',
    nome: 'Metamielócito',
    sinonimos: ['metamyelocyte', 'bastonete jovem', 'precursor granulocítico'],
    tipo: 'celula',
    resumo: 'Precursor do neutrófilo na medula: núcleo em rim (endentado), cromatina já condensada e citoplasma com grânulos específicos.',
    caracteristicas: [
      'Núcleo reniforme, com endentação menor que metade da largura.',
      'Citoplasma rosado, granular; célula de 10–15 µm.',
      'Não se divide mais.',
    ],
    aprofundado: [
      'Sequência granulocítica: mieloblasto → promielócito → mielócito → metamielócito → bastão → segmentado.',
      'A partir do metamielócito a célula só amadurece; é a última etapa com núcleo não segmentado antes do bastão.',
    ],
    funcoes: ['Etapa da granulopoese.', 'Representar a transição entre célula que ainda sintetiza grânulos (mielócito) e célula madura (bastão, segmentado): já não se divide.', 'Aparecer no sangue indica desvio à esquerda (infecção grave) ou reação leucemoide.'],
    regeneracao: { nivel: 'alta', texto: 'Compartimento de maturação renovado continuamente.' },
    ondeEncontrar: ['Medula óssea; no sangue só em infecções graves (desvio à esquerda) ou leucemia mieloide crônica.'],
    alteracoes: ['Presença no sangue: reação leucemoide, leucemia mieloide crônica, mielofibrose (leucoeritroblastose).'],
  },
  {
    id: 'plaqueta',
    nome: 'Plaqueta',
    sinonimos: ['trombócito', 'platelet'],
    tipo: 'celula',
    resumo: 'Fragmento anucleado do citoplasma do megacariócito (2–3 µm), roxo e granuloso, espalhado entre as hemácias.',
    caracteristicas: [
      'Pequena, irregular, de centro granular roxo (granulômero) e borda clara (hialômero).',
      'Sem núcleo; muitas vezes em pequenos grupos no esfregaço.',
    ],
    aprofundado: [
      'Grânulos α (fibrinogênio, fator de von Willebrand) e densos (ADP, serotonina, cálcio).',
      'Vive 7–10 dias; 150.000–450.000/µL.',
    ],
    funcoes: ['Hemostasia primária: adesão, agregação e formação do tampão plaquetário.', 'Liberação de fatores de crescimento no reparo.', 'Fornecer a superfície de fosfolipídio onde a cascata da coagulação se monta.', 'Contrair o coágulo (retração) com actina e miosina.'],
    regeneracao: { nivel: 'alta', texto: 'Megacariócitos da medula liberam milhares por célula, sob controle da trombopoetina.' },
    ondeEncontrar: ['Sangue periférico; medula óssea (em volta dos megacariócitos).'],
    alteracoes: ['Plaquetopenia (púrpura trombocitopênica imune, dengue).', 'Plaquetas gigantes (Bernard-Soulier).', 'Pseudoplaquetopenia por agregação com EDTA.'],
  },
  {
    id: 'equinocito',
    nome: 'Equinócito (hemácia crenada)',
    sinonimos: ['echinocyte', 'hemácia crenada', 'burr cell'],
    tipo: 'celula',
    resumo: 'Hemácia com muitas projeções curtas e regulares na borda — na maioria dos esfregaços, um artefato de secagem.',
    caracteristicas: ['Contorno em "roda dentada", com 10–30 espículas curtas e iguais.', 'Isolada entre hemácias normais, geralmente em áreas mais finas.'],
    aprofundado: [
      'Surge quando o sangue fica muito tempo em EDTA, com pH alto ou secagem lenta.',
      'Distinguir do acantócito, que tem poucas espículas irregulares e é patológico (abetalipoproteinemia, hepatopatia).',
    ],
    funcoes: ['Nenhuma — alteração de forma.', 'Reconhecê-lo evita confundir com acantócito: as espículas são curtas e regulares, em geral artefato de secagem lenta ou de sangue estocado; também aparece na uremia.'],
    regeneracao: { nivel: 'nao-se-aplica', texto: 'Alteração de forma da hemácia.' },
    ondeEncontrar: ['Esfregaços de sangue (artefato); de verdade na uremia e após transfusão de sangue estocado.'],
    alteracoes: ['Equinócitos verdadeiros na uremia, deficiência de piruvato-quinase e em corredores de longa distância.'],
  },
  {
    id: 'megacariocito',
    nome: 'Megacariócito',
    sinonimos: ['megakaryocyte', 'célula gigante da medula'],
    tipo: 'celula',
    resumo: 'Maior célula da medula óssea (50–100 µm), com núcleo único muito lobulado e citoplasma granular abundante, que se fragmenta em plaquetas.',
    caracteristicas: ['Célula gigante com núcleo lobulado (poliploide, até 64N) e citoplasma azul-arroxeado finamente granular.', 'Bordas irregulares, às vezes com plaquetas se desprendendo; muito maior que qualquer outra célula do esfregaço.'],
    aprofundado: ['Faz endomitose: replica o DNA sem se dividir, por isso o núcleo é enorme e lobulado.', 'Emite pró-plaquetas para dentro dos sinusoides da medula; cada megacariócito libera milhares de plaquetas.', 'Controlado pela trombopoetina, produzida no fígado.'],
    funcoes: ['Produzir plaquetas (cerca de 100 bilhões por dia).', 'Participar do nicho das células-tronco hematopoéticas e liberar fatores de crescimento (TGF-β, PDGF).'],
    regeneracao: { nivel: 'alta', texto: 'Renovado continuamente a partir de precursores da medula.' },
    ondeEncontrar: ['Medula óssea vermelha; em pequeno número no pulmão.'],
    alteracoes: ['Aumentados na trombocitopenia imune (consumo periférico) e na trombocitemia essencial.', 'Megacariócitos displásicos (micromegacariócitos) nas síndromes mielodisplásicas.', 'Reduzidos na aplasia medular e na infiltração por leucemia.'],
  },
  {
    id: 'eritroblasto',
    nome: 'Eritroblasto (normoblasto)',
    sinonimos: ['normoblasto', 'precursor eritroide', 'eritroblasto ortocromático'],
    tipo: 'celula',
    resumo: 'Precursor nucleado da hemácia na medula óssea; no estágio final (ortocromático) tem núcleo pequeno, redondo e muito escuro, e citoplasma já com a cor da hemácia.',
    caracteristicas: ['Núcleo redondo, central, de cromatina densa (ortocromático: núcleo picnótico, quase negro).', 'Citoplasma azul (basofílico) nos estágios iniciais, cinza-arroxeado (policromático) e depois rosado (ortocromático) conforme acumula hemoglobina.', 'Células pequenas agrupadas em ilhotas eritroblásticas em volta de um macrófago.'],
    aprofundado: ['Sequência: proeritroblasto → eritroblasto basófilo → policromático → ortocromático → reticulócito → hemácia; o núcleo é expulso e fagocitado pelo macrófago central.', 'Controlada pela eritropoetina, produzida pelo rim em resposta à hipóxia.'],
    funcoes: ['Sintetizar hemoglobina e amadurecer até hemácia.', 'Gerar cerca de 200 bilhões de hemácias por dia.'],
    regeneracao: { nivel: 'alta', texto: 'Linhagem de proliferação muito rápida.' },
    ondeEncontrar: ['Medula óssea vermelha; no feto, fígado e baço.'],
    alteracoes: ['Eritroblastos no sangue periférico (leucoeritroblastose): hemólise grave, mielofibrose, infiltração medular.', 'Alterações megaloblásticas (núcleo imaturo e citoplasma maduro) na deficiência de B12 e folato.', 'Sideroblastos em anel na anemia sideroblástica.'],
  },
  {
    id: 'mielocito',
    nome: 'Mielócito',
    sinonimos: ['myelocyte', 'mielócito neutrófilo'],
    tipo: 'celula',
    resumo: 'Precursor granulocítico com núcleo redondo a oval, excêntrico, e citoplasma com grânulos específicos; é a última célula da série que ainda se divide.',
    caracteristicas: ['Núcleo redondo ou oval, sem reentrância, cromatina mais condensada que a do promielócito.', 'Citoplasma rosado-lilás com grânulos finos (específicos) e uma área clara perto do núcleo (Golgi).'],
    aprofundado: ['Sequência: mieloblasto → promielócito (grânulos azurófilos) → mielócito (grânulos específicos) → metamielócito (núcleo reniforme) → bastonete → segmentado.', 'Dos mielócitos em diante já se distinguem neutrófilo, eosinófilo e basófilo pelos grânulos.'],
    funcoes: ['Multiplicar e amadurecer a linhagem de granulócitos.', 'Produzir os grânulos específicos (lactoferrina, colagenase) que o neutrófilo maduro usa.'],
    regeneracao: { nivel: 'alta', texto: 'Linhagem em proliferação contínua.' },
    ondeEncontrar: ['Medula óssea vermelha.'],
    alteracoes: ['Mielócitos no sangue: reação leucemoide, infecção grave ou leucemia mieloide crônica (desvio à esquerda escalonado).'],
  },
]
