import type { Estrutura } from '../tipos'

/** Sistema nervoso periférico: nervos, raízes, gânglios e seus envoltórios. */
export const ESTRUTURAS_SNP: Estrutura[] = [
  {
    id: 'fibra-nervosa-mielinizada',
    nome: 'Fibra nervosa mielinizada',
    sinonimos: ['myelinated fiber', 'axônio mielinizado', 'bainha de mielina', 'mielina'],
    tipo: 'fibra',
    resumo: 'Axônio envolto por uma bainha de mielina — camadas compactas de membrana de célula de Schwann (SNP) ou de oligodendrócito (SNC).',
    caracteristicas: [
      'Em corte transversal: axônio central envolto por um anel. Com ósmio ou Weigert, o anel é preto; em HE, a mielina é extraída e sobra um anel claro e rendado (neuroqueratina).',
      'Em corte longitudinal ou fibra dissociada: cilindro interrompido a intervalos regulares pelos nós de Ranvier.',
      'Calibres variados no mesmo nervo (1–20 µm): as fibras grossas conduzem mais rápido.',
    ],
    aprofundado: [
      'A mielina é ~70 % lipídio (colesterol, galactocerebrosídeos) e ~30 % proteína (P0 e PMP22 no SNP; PLP e MBP no SNC).',
      'Condução saltatória: o potencial de ação salta de nó em nó, até 100 m/s, com gasto energético muito menor.',
      'Incisuras de Schmidt-Lanterman: fendas oblíquas de citoplasma dentro da mielina, visíveis em fibras dissociadas.',
    ],
    funcoes: ['Isolar o axônio e permitir a condução saltatória, rápida e econômica.'],
    regeneracao: {
      nivel: 'moderada',
      texto:
        'No SNP, após secção, o coto distal degenera (degeneração walleriana) e o axônio volta a crescer ~1–3 mm/dia guiado pelas células de Schwann (bandas de Büngner). No SNC, a regeneração praticamente não ocorre.',
    },
    ondeEncontrar: ['Nervos periféricos, raízes espinais, substância branca do encéfalo e da medula.'],
    alteracoes: [
      'Desmielinização segmentar: síndrome de Guillain-Barré (SNP), esclerose múltipla (SNC).',
      'Neuropatia axonal (diabetes, álcool, quimioterápicos): perda de fibras com degeneração walleriana.',
      'Doença de Charcot-Marie-Tooth: bulbos de cebola por ciclos de desmielinização e remielinização.',
    ],
  },
  {
    id: 'celula-de-schwann',
    nome: 'Célula de Schwann',
    sinonimos: ['Schwann cell', 'neurolemócito', 'neurilema'],
    tipo: 'celula',
    resumo: 'Glia do SNP que forma a mielina de um único internodo de um axônio, ou envolve vários axônios amielínicos.',
    caracteristicas: [
      'Núcleo alongado ou oval, colado à fibra, dentro do endoneuro.',
      'Em corte transversal, o núcleo aparece como uma meia-lua na borda de uma fibra.',
      'Cada célula mieliniza só um segmento (internodo) de um só axônio.',
    ],
    aprofundado: [
      'Nas fibras amielínicas (C), uma célula de Schwann aloja vários axônios em goteiras do citoplasma (feixe de Remak).',
      'Tem lâmina basal própria, que persiste após a lesão e forma o tubo que guia o axônio em regeneração.',
      'Deriva da crista neural.',
    ],
    funcoes: ['Formar a mielina do SNP.', 'Sustentar e nutrir o axônio.', 'Guiar e promover a regeneração axonal.'],
    regeneracao: { nivel: 'alta', texto: 'Proliferam após lesão do nervo e se alinham em bandas de Büngner, guiando o novo axônio.' },
    ondeEncontrar: ['Nervos periféricos, raízes espinais e cranianas (exceto o nervo óptico, que é SNC).'],
    alteracoes: [
      'Schwannoma: tumor benigno encapsulado, com áreas Antoni A (paliçadas de Verocay) e Antoni B.',
      'Neurofibroma (neurofibromatose tipo 1): proliferação difusa de células de Schwann e fibroblastos.',
    ],
  },
  {
    id: 'no-de-ranvier',
    nome: 'Nó de Ranvier',
    sinonimos: ['node of Ranvier', 'nodo de Ranvier', 'estrangulamento de Ranvier'],
    tipo: 'fibra',
    resumo: 'Intervalo curto (~1 µm) sem mielina entre dois internodos, onde o axônio fica exposto e o potencial de ação é regenerado.',
    caracteristicas: [
      'Em fibra dissociada com ósmio: interrupção nítida ou estreitamento da bainha preta, repetido a intervalos regulares.',
      'A distância entre nós (0,2–2 mm) cresce com o calibre da fibra.',
    ],
    aprofundado: [
      'O axolema do nó concentra canais de sódio dependentes de voltagem (Nav1.6); os canais de potássio ficam na região justaparanodal, sob a mielina.',
      'No SNP, microvilosidades das células de Schwann vizinhas cobrem o nó; no SNC, prolongamentos de astrócitos.',
    ],
    funcoes: ['Regenerar o potencial de ação a cada salto na condução saltatória.'],
    regeneracao: { nivel: 'moderada', texto: 'Refaz-se quando o axônio regenera e é remielinizado, com internodos mais curtos que os originais.' },
    ondeEncontrar: ['Toda fibra mielinizada, do SNP e do SNC.'],
    alteracoes: [
      'Neuropatias nodais autoimunes (anticorpos contra neurofascina, contactina): bloqueio de condução.',
      'Internodos curtos e irregulares denunciam fibras remielinizadas.',
    ],
  },
  {
    id: 'internodo',
    nome: 'Internodo',
    sinonimos: ['internode', 'segmento internodal'],
    tipo: 'fibra',
    resumo: 'Trecho mielinizado de uma fibra entre dois nós de Ranvier; no SNP, corresponde a uma única célula de Schwann.',
    caracteristicas: [
      'Segmento cilíndrico de mielina de comprimento regular, delimitado por dois nós.',
      'O núcleo da célula de Schwann fica mais ou menos no meio do internodo.',
    ],
    aprofundado: [
      'Comprimento proporcional ao calibre: fibras grossas têm internodos longos e condução mais rápida.',
      'Após desmielinização e remielinização, os internodos ficam curtos e de tamanho desigual.',
    ],
    funcoes: ['Isolar o axônio entre os nós, obrigando a corrente a saltar.'],
    regeneracao: { nivel: 'moderada', texto: 'Remielinizado por células de Schwann após a lesão, com segmentos mais curtos.' },
    ondeEncontrar: ['Toda fibra mielinizada.'],
    alteracoes: ['Desmielinização segmentar: perda de internodos isolados com o axônio preservado (Guillain-Barré, CIDP).'],
  },
  {
    id: 'fasciculo-nervoso',
    nome: 'Fascículo nervoso',
    sinonimos: ['nerve fascicle', 'feixe nervoso', 'fascículo'],
    tipo: 'orgao-parte',
    resumo: 'Feixe de fibras nervosas envolto pelo perineuro; um nervo é feito de um ou muitos fascículos unidos pelo epineuro.',
    caracteristicas: [
      'Perfil redondo ou oval, bem delimitado pelo perineuro.',
      'Dentro: fibras mielinizadas e amielínicas, núcleos de células de Schwann e fibroblastos do endoneuro, capilares.',
      'Em nervos pequenos (como os feixes em volta de gânglios), um único fascículo forma o nervo inteiro.',
    ],
    aprofundado: [
      'Os fascículos trocam fibras entre si ao longo do trajeto (plexos intraneurais), o que importa na cirurgia de reparo.',
      'Na sutura de nervos, o alinhamento fascicular melhora a recuperação.',
    ],
    funcoes: ['Organizar as fibras e protegê-las num microambiente controlado pelo perineuro.'],
    regeneracao: { nivel: 'moderada', texto: 'As fibras regeneram dentro dos tubos endoneurais se o fascículo estiver alinhado.' },
    ondeEncontrar: ['Todos os nervos periféricos e raízes; feixes nervosos no conjuntivo de todos os órgãos.'],
    alteracoes: [
      'Neuroma traumático: fascículos desorganizados em cicatriz após secção.',
      'Hanseníase: infiltrado inflamatório dentro dos fascículos, com bacilos nas células de Schwann.',
    ],
  },
  {
    id: 'endoneuro',
    nome: 'Endoneuro',
    sinonimos: ['endoneurium'],
    tipo: 'matriz',
    resumo: 'Conjuntivo frouxo e delicado dentro do fascículo, em volta de cada fibra nervosa, com capilares e fibroblastos esparsos.',
    caracteristicas: [
      'Espaços claros entre as fibras, com fibrilas colágenas finas (tipo III e I).',
      'Núcleos de fibroblastos e capilares contínuos.',
    ],
    aprofundado: [
      'Os capilares endoneurais formam a barreira hematoneural, junto com o perineuro.',
      'O líquido endoneural tem pressão controlada; o edema endoneural comprime as fibras (síndromes compressivas).',
    ],
    funcoes: ['Sustentar e nutrir cada fibra.', 'Barreira hematoneural (capilares).'],
    regeneracao: { nivel: 'alta', texto: 'Conjuntivo: repara-se, e em excesso vira fibrose endoneural.' },
    ondeEncontrar: ['Dentro de todo fascículo nervoso.'],
    alteracoes: ['Edema e fibrose endoneural em neuropatias compressivas e diabéticas.', 'Espessamento dos microvasos na neuropatia diabética.'],
  },
  {
    id: 'perineuro',
    nome: 'Perineuro',
    sinonimos: ['perineurium', 'bainha perineural'],
    tipo: 'camada',
    resumo: 'Bainha de camadas concêntricas de células achatadas, unidas por junções de oclusão, que envolve cada fascículo.',
    caracteristicas: [
      'Faixa lamelar e compacta, com núcleos alongados e achatados, colada à borda do fascículo.',
      'Mais espessa nos fascículos grandes; pode enviar septos que subdividem o fascículo.',
    ],
    aprofundado: [
      'As células perineurais têm lâmina basal dos dois lados e junções de oclusão — é um epitélio funcional, apesar de derivar de fibroblastos.',
      'É a principal barreira de difusão do nervo (barreira hematoneural): isola o endoneuro de fármacos e toxinas.',
      'Precisa ser atravessada pelo anestésico local no bloqueio de nervos.',
    ],
    funcoes: ['Barreira de difusão e proteção mecânica do fascículo.'],
    regeneracao: { nivel: 'moderada', texto: 'Refaz-se após lesão, mas o reparo cirúrgico precisa aproximar os fascículos.' },
    ondeEncontrar: ['Todo fascículo de nervo periférico; termina junto às terminações nervosas.'],
    alteracoes: ['Perineurioma: tumor raro de células perineurais (EMA positivas).', 'Espessamento perineural na hanseníase.'],
  },
  {
    id: 'epineuro',
    nome: 'Epineuro',
    sinonimos: ['epineurium'],
    tipo: 'camada',
    resumo: 'Conjuntivo denso não modelado que envolve o nervo inteiro e preenche o espaço entre os fascículos, com vasos e adipócitos.',
    caracteristicas: [
      'Colágeno grosso e eosinófilo, fibroblastos, vasos nutrícios (vasa nervorum) e gordura.',
      'Mais abundante nos nervos grandes e perto das articulações, onde amortece compressão e estiramento.',
    ],
    aprofundado: [
      'Continua-se com a dura-máter onde as raízes saem do canal vertebral.',
      'É a camada que o cirurgião sutura na neurorrafia epineural.',
    ],
    funcoes: ['Proteção mecânica e nutrição (vasa nervorum) do nervo.'],
    regeneracao: { nivel: 'alta', texto: 'Conjuntivo denso: repara-se por fibrose.' },
    ondeEncontrar: ['Todos os nervos periféricos com mais de um fascículo.'],
    alteracoes: ['Vasculite dos vasa nervorum: mononeurite múltipla (poliarterite nodosa).', 'Lipomatose do nervo.'],
  },
  {
    id: 'raiz-nervosa-espinal',
    nome: 'Raiz nervosa espinal',
    sinonimos: ['raiz anterior', 'raiz posterior', 'raiz ventral', 'raiz dorsal', 'cauda equina', 'spinal root'],
    tipo: 'orgao-parte',
    resumo: 'Feixe de fibras que liga a medula ao nervo espinal: a raiz anterior leva fibras motoras; a posterior traz as sensitivas, com o gânglio no trajeto.',
    caracteristicas: [
      'Fascículos de fibras mielinizadas dentro do espaço subaracnóideo, banhados pelo líquor.',
      'Envoltório fino, sem epineuro espesso: por isso são mais vulneráveis que os nervos.',
      'Abaixo de L1–L2, as raízes descem no saco dural formando a cauda equina.',
    ],
    aprofundado: [
      'A zona de transição entre mielina central (oligodendrócito) e periférica (Schwann) fica perto da medula: a zona de Obersteiner-Redlich.',
      'A raiz posterior tem fibras de todos os calibres; a anterior, motoneurônios alfa (grossas) e gama (médias), além das pré-ganglionares autônomas em T1–L2 e S2–S4.',
    ],
    funcoes: ['Conduzir as fibras motoras para fora e as sensitivas para dentro da medula.'],
    regeneracao: {
      nivel: 'baixa',
      texto: 'A parte periférica pode regenerar, mas o axônio não reentra na medula após avulsão da raiz.',
    },
    ondeEncontrar: ['Espaço subaracnóideo em toda a medula; cauda equina abaixo do cone medular.'],
    alteracoes: [
      'Radiculopatia por hérnia de disco: dor e déficit no dermátomo.',
      'Síndrome da cauda equina: compressão das raízes sacrais — retenção urinária e anestesia em sela.',
      'Polirradiculoneurite (Guillain-Barré) acomete as raízes precocemente.',
    ],
  },
  {
    id: 'ganglio-sensitivo',
    nome: 'Gânglio sensitivo (da raiz posterior)',
    sinonimos: ['gânglio espinal', 'dorsal root ganglion', 'DRG', 'gânglio sensorial'],
    tipo: 'orgao-parte',
    resumo: 'Aglomerado de corpos de neurônios pseudounipolares na raiz posterior, envoltos por células satélites, entre feixes de fibras.',
    caracteristicas: [
      'Neurônios grandes e redondos, de tamanhos variados, agrupados sobretudo na periferia do gânglio.',
      'Cada neurônio rodeado por uma camada contínua de células satélites.',
      'Feixes de fibras atravessando o gânglio; cápsula de conjuntivo contínua com o epineuro.',
      'Não há sinapses: os neurônios só passam o sinal adiante.',
    ],
    aprofundado: [
      'O tamanho do neurônio acompanha a fibra: grandes para propriocepção e tato (Aα/Aβ), pequenos para dor e temperatura (Aδ/C).',
      'Fica no forame intervertebral, fora do saco dural.',
      'Os gânglios dos nervos cranianos sensitivos (trigêmeo, geniculado, espiral) têm a mesma estrutura.',
    ],
    funcoes: ['Abrigar os corpos dos neurônios sensitivos primários.'],
    regeneracao: { nivel: 'nula', texto: 'Os neurônios não se dividem; um neurônio perdido não é reposto.' },
    ondeEncontrar: ['Raiz posterior de cada nervo espinal, no forame intervertebral; gânglios sensitivos de nervos cranianos.'],
    alteracoes: [
      'Herpes-zóster: reativação do vírus varicela-zóster latente no gânglio, com necrose neuronal e nódulos de Nageotte.',
      'Ganglionopatia sensitiva (síndrome de Sjögren, paraneoplásica anti-Hu).',
    ],
  },
  {
    id: 'neuronio-pseudounipolar',
    nome: 'Neurônio pseudounipolar',
    sinonimos: ['neurônio sensitivo primário', 'neurônio em T', 'pseudounipolar neuron'],
    tipo: 'celula',
    resumo: 'Neurônio sensitivo do gânglio da raiz posterior: corpo redondo, núcleo central com nucléolo, e um único prolongamento que se divide em T.',
    caracteristicas: [
      'Corpo grande (20–100 µm) e esférico, sem dendritos.',
      'Núcleo central, claro, com nucléolo evidente; Nissl fino e disperso.',
      'Anel de células satélites em volta; halos de retração são comuns.',
    ],
    aprofundado: [
      'O prolongamento único se divide em um ramo periférico (até o receptor) e um central (até a medula); o potencial de ação passa direto, sem atravessar o corpo.',
      'Com a idade acumula lipofuscina.',
    ],
    funcoes: ['Transmitir tato, propriocepção, dor e temperatura da periferia para a medula.'],
    regeneracao: { nivel: 'nula', texto: 'O corpo não se divide; o ramo periférico do axônio pode regenerar.' },
    ondeEncontrar: ['Gânglios da raiz posterior e gânglios sensitivos dos nervos cranianos.'],
    alteracoes: ['Necrose neuronal no herpes-zóster.', 'Perda neuronal na ataxia de Friedreich e na ganglionopatia paraneoplásica.'],
  },
  {
    id: 'ganglio-autonomo',
    nome: 'Gânglio autônomo',
    sinonimos: ['gânglio simpático', 'gânglio parassimpático', 'gânglio intramural', 'autonomic ganglion'],
    tipo: 'orgao-parte',
    resumo: 'Aglomerado de neurônios pós-ganglionares multipolares onde fazem sinapse as fibras pré-ganglionares do SNC.',
    caracteristicas: [
      'Neurônios multipolares, menores e mais espaçados que os do gânglio sensitivo, distribuídos por todo o gânglio.',
      'Núcleo muitas vezes excêntrico; células satélites em camada incompleta.',
      'Neurópilo com fibras e sinapses entre os neurônios; cápsula conjuntiva.',
    ],
    aprofundado: [
      'Simpáticos: cadeia paravertebral e gânglios pré-vertebrais (celíaco, mesentéricos) — longe do órgão.',
      'Parassimpáticos: perto ou dentro do órgão (intramurais: bexiga, coração, intestino — plexos de Meissner e Auerbach).',
      'Transmissão pré-ganglionar colinérgica (receptores nicotínicos).',
    ],
    funcoes: ['Integrar e distribuir o comando autônomo a músculo liso, músculo cardíaco e glândulas.'],
    regeneracao: { nivel: 'nula', texto: 'Os neurônios não se dividem.' },
    ondeEncontrar: ['Cadeia simpática, gânglios pré-vertebrais, parede de vísceras (bexiga, coração, trato gastrointestinal), gânglios cranianos parassimpáticos.'],
    alteracoes: [
      'Doença de Hirschsprung: ausência de gânglios intramurais no cólon distal.',
      'Acalasia e doença de Chagas: destruição dos neurônios do plexo mioentérico.',
      'Neuroblastoma e ganglioneuroma: tumores da crista neural simpática.',
    ],
  },
  {
    id: 'neuronio-ganglionar-autonomo',
    nome: 'Neurônio ganglionar autônomo',
    sinonimos: ['neurônio pós-ganglionar', 'célula ganglionar', 'ganglion cell'],
    tipo: 'celula',
    resumo: 'Neurônio multipolar grande do gânglio autônomo, com núcleo claro e nucléolo nítido, cercado por células satélites.',
    caracteristicas: [
      'Corpo poligonal ou oval, citoplasma amplo e levemente basófilo (Nissl fino).',
      'Núcleo vesiculoso, muitas vezes excêntrico, com nucléolo evidente.',
      'Vários dendritos curtos (multipolar), que não aparecem em HE.',
    ],
    aprofundado: [
      'Neurônios simpáticos pós-ganglionares liberam noradrenalina (exceto os das glândulas sudoríparas, colinérgicos); os parassimpáticos, acetilcolina.',
      'Acumulam lipofuscina com a idade.',
    ],
    funcoes: ['Levar o comando autônomo ao órgão efetor.'],
    regeneracao: { nivel: 'nula', texto: 'Pós-mitótico; o axônio pós-ganglionar pode regenerar.' },
    ondeEncontrar: ['Gânglios simpáticos e parassimpáticos, e plexos intramurais das vísceras.'],
    alteracoes: ['Perda neuronal no Chagas (megaesôfago, megacólon) e na acalasia.', 'Corpos de Lewy em gânglios simpáticos na doença de Parkinson.'],
  },
  {
    id: 'celula-satelite-ganglionar',
    nome: 'Célula satélite do gânglio',
    sinonimos: ['célula anfícito', 'satellite glial cell', 'glia satélite'],
    tipo: 'celula',
    resumo: 'Célula glial achatada que envolve o corpo de cada neurônio dos gânglios periféricos; núcleo pequeno colado ao neurônio.',
    caracteristicas: [
      'Núcleos pequenos, ovais ou achatados, em fila na borda do neurônio.',
      'Formam uma camada contínua no gânglio sensitivo e incompleta no autônomo.',
    ],
    aprofundado: [
      'Derivam da crista neural, como as células de Schwann.',
      'Regulam o microambiente do neurônio e participam da dor crônica (acoplamento por junções comunicantes, liberação de citocinas).',
    ],
    funcoes: ['Suporte metabólico, isolamento elétrico e tamponamento iônico do neurônio ganglionar.'],
    regeneracao: { nivel: 'moderada', texto: 'Proliferam após lesão do neurônio e ocupam o lugar dos que morrem (nódulos de Nageotte).' },
    ondeEncontrar: ['Gânglios sensitivos e autônomos.'],
    alteracoes: ['Nódulos de Nageotte: proliferação de células satélites no lugar de um neurônio perdido (herpes-zóster, ganglionopatias).'],
  },
]
