import type { MetadataRoute } from 'next'
import { CANONICAL_ORIGIN } from '@/lib/seo'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: 'Googlebot',
        allow: ['/', '/lead/', '/doar', '/politica-de-privacidade', '/termos-de-servico'],
        disallow: [
          '/api/',
          '/admin/',
          '/auth/',
          '/dashboard/',
          '/profile/',
          '/exam/',
          '/exams/',
          '/banco-questoes/',
          '/cronogramas/',
          '/flashcards/',
          '/forum/',
          '/aulas/',
          '/materiais/',
          '/manual-clinico/',
          '/buy/',
          '/doar/sucesso',
          '/doar/pendente',
          '/doar/falha',
          '/games/',
          '/_next/',
          '/*.json$',
        ],
      },
      {
        userAgent: 'Googlebot-Image',
        allow: ['/img/', '/favicon.png', '/logo.png', '/logo3d.png'],
        disallow: ['/api/'],
      },
      {
        userAgent: 'Bingbot',
        allow: ['/', '/lead/', '/doar', '/politica-de-privacidade', '/termos-de-servico'],
        disallow: [
          '/api/',
          '/admin/',
          '/auth/',
          '/dashboard/',
          '/profile/',
          '/exam/',
          '/exams/',
          '/banco-questoes/',
          '/cronogramas/',
          '/flashcards/',
          '/forum/',
          '/aulas/',
          '/materiais/',
          '/manual-clinico/',
          '/buy/',
          '/doar/sucesso',
          '/doar/pendente',
          '/doar/falha',
          '/games/',
          '/_next/',
        ],
      },
      {
        userAgent: '*',
        allow: ['/', '/lead/', '/doar', '/politica-de-privacidade', '/termos-de-servico'],
        disallow: [
          '/api/',
          '/admin/',
          '/auth/',
          '/dashboard/',
          '/profile/',
          '/exam/',
          '/exams/',
          '/banco-questoes/',
          '/cronogramas/',
          '/flashcards/',
          '/forum/',
          '/aulas/',
          '/materiais/',
          '/manual-clinico/',
          '/buy/',
          '/doar/sucesso',
          '/doar/pendente',
          '/doar/falha',
          '/games/',
          '/_next/',
        ],
      },
    ],
    sitemap: `${CANONICAL_ORIGIN}/sitemap.xml`,
    host: CANONICAL_ORIGIN,
  }
}
