import type { LucideIcon } from 'lucide-react'
import {
  Accessibility,
  Activity,
  Apple,
  Atom,
  Award,
  Baby,
  Banknote,
  BarChart,
  Beaker,
  Bed,
  Bell,
  Biohazard,
  Bone,
  Book,
  BookHeart,
  BookMarked,
  BookOpen,
  BookOpenCheck,
  Bookmark,
  Box,
  Brain,
  BrainCircuit,
  Calculator,
  Calendar,
  CalendarDays,
  Camera,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Coins,
  Compass,
  Cpu,
  Cross,
  Crosshair,
  Database,
  Dices,
  Dna,
  Droplet,
  Droplets,
  Dumbbell,
  Ear,
  Eye,
  FileCheck,
  FileHeart,
  FileSearch,
  FileText,
  Files,
  Film,
  Flame,
  FlaskConical,
  FlaskRound,
  Folder,
  FolderHeart,
  FolderOpen,
  Footprints,
  Gamepad2,
  Gauge,
  Globe,
  GraduationCap,
  Heart,
  HeartPulse,
  Highlighter,
  Home,
  Image,
  Key,
  Layers,
  Leaf,
  Library,
  Lightbulb,
  List,
  ListChecks,
  Lock,
  Map,
  Medal,
  Megaphone,
  MessageCircle,
  Microscope,
  Monitor,
  Moon,
  Network,
  Newspaper,
  Orbit,
  Pencil,
  Percent,
  PersonStanding,
  PieChart,
  Pill,
  Puzzle,
  Radiation,
  Rocket,
  Ruler,
  Scale,
  Scan,
  ScanLine,
  Scroll,
  ScrollText,
  Search,
  Share2,
  Shield,
  ShieldPlus,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Smile,
  Sparkles,
  Star,
  Stethoscope,
  Store,
  Sun,
  Swords,
  Syringe,
  Table,
  Tag,
  Target,
  TestTube,
  TestTube2,
  TestTubes,
  Thermometer,
  Ticket,
  Timer,
  TrendingUp,
  Trophy,
  User,
  Users,
  Video,
  Wallet,
  Wand2,
  Waves,
  Wind,
  Zap,
} from 'lucide-react'

/**
 * Desenho de cada ícone do catálogo (`lib/sidebar-icons.ts`).
 *
 * Os imports são explícitos de propósito: `import * as Icons from 'lucide-react'`
 * anularia o tree-shaking e arrastaria os ~1.400 ícones do pacote para o bundle
 * do cliente. Um teste garante que este mapa e o catálogo têm exatamente as
 * mesmas chaves — nome sem desenho vira buraco no menu, desenho sem nome vira
 * peso morto no bundle.
 */
export const SIDEBAR_ICON_COMPONENTS: Record<string, LucideIcon> = {
  'stethoscope': Stethoscope,
  'heart-pulse': HeartPulse,
  'activity': Activity,
  'heart': Heart,
  'pill': Pill,
  'syringe': Syringe,
  'thermometer': Thermometer,
  'cross': Cross,
  'shield-plus': ShieldPlus,
  'clipboard-check': ClipboardCheck,
  'clipboard-list': ClipboardList,
  'bed': Bed,
  'brain': Brain,
  'brain-circuit': BrainCircuit,
  'bone': Bone,
  'dna': Dna,
  'ear': Ear,
  'eye': Eye,
  'footprints': Footprints,
  'person-standing': PersonStanding,
  'accessibility': Accessibility,
  'baby': Baby,
  'microscope': Microscope,
  'test-tube': TestTube,
  'test-tubes': TestTubes,
  'test-tube-2': TestTube2,
  'flask-conical': FlaskConical,
  'flask-round': FlaskRound,
  'beaker': Beaker,
  'atom': Atom,
  'biohazard': Biohazard,
  'droplet': Droplet,
  'droplets': Droplets,
  'scan-line': ScanLine,
  'scan': Scan,
  'radiation': Radiation,
  'waves': Waves,
  'orbit': Orbit,
  'gauge': Gauge,
  'camera': Camera,
  'image': Image,
  'film': Film,
  'video': Video,
  'layers': Layers,
  'box': Box,
  'book-open': BookOpen,
  'book': Book,
  'book-marked': BookMarked,
  'book-heart': BookHeart,
  'book-open-check': BookOpenCheck,
  'library': Library,
  'graduation-cap': GraduationCap,
  'scroll': Scroll,
  'scroll-text': ScrollText,
  'newspaper': Newspaper,
  'file-text': FileText,
  'file-check': FileCheck,
  'file-heart': FileHeart,
  'files': Files,
  'highlighter': Highlighter,
  'pencil': Pencil,
  'folder': Folder,
  'folder-open': FolderOpen,
  'folder-heart': FolderHeart,
  'bookmark': Bookmark,
  'list': List,
  'list-checks': ListChecks,
  'table': Table,
  'database': Database,
  'network': Network,
  'calendar': Calendar,
  'calendar-days': CalendarDays,
  'clock': Clock,
  'timer': Timer,
  'calculator': Calculator,
  'ruler': Ruler,
  'scale': Scale,
  'compass': Compass,
  'target': Target,
  'crosshair': Crosshair,
  'search': Search,
  'bar-chart': BarChart,
  'pie-chart': PieChart,
  'trending-up': TrendingUp,
  'percent': Percent,
  'cpu': Cpu,
  'monitor': Monitor,
  'smartphone': Smartphone,
  'star': Star,
  'sparkles': Sparkles,
  'trophy': Trophy,
  'medal': Medal,
  'award': Award,
  'flame': Flame,
  'rocket': Rocket,
  'lightbulb': Lightbulb,
  'puzzle': Puzzle,
  'gamepad-2': Gamepad2,
  'dices': Dices,
  'swords': Swords,
  'zap': Zap,
  'wand-2': Wand2,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  'store': Store,
  'ticket': Ticket,
  'tag': Tag,
  'banknote': Banknote,
  'coins': Coins,
  'wallet': Wallet,
  'users': Users,
  'user': User,
  'message-circle': MessageCircle,
  'megaphone': Megaphone,
  'bell': Bell,
  'share-2': Share2,
  'leaf': Leaf,
  'apple': Apple,
  'dumbbell': Dumbbell,
  'sun': Sun,
  'moon': Moon,
  'wind': Wind,
  'smile': Smile,
  'globe': Globe,
  'map': Map,
  'shield': Shield,
  'lock': Lock,
  'key': Key,
  'home': Home,
  'file-search': FileSearch,
}

/** Componente do ícone escolhido, com queda para um padrão seguro. */
export function getSidebarIconComponent(name?: string | null): LucideIcon {
  return (name && SIDEBAR_ICON_COMPONENTS[name]) || SIDEBAR_ICON_COMPONENTS['book-open']
}
