/**
 * Glossário editorial inglês → português brasileiro.
 *
 * ## Por que um glossário, e não tradução automática
 *
 * `LICENCA_E_PUBLICACAO.md` proíbe declarar como revisado o que não passou por
 * revisão. Passar 2.398 rótulos por um tradutor automático e exibi-los como
 * texto final violaria isso e produziria erros caros: em histologia, "lamina
 * propria" não é "lâmina apropriada", "chief cells" não são "células chefes" e
 * "brush border" não é "borda de escova" em qualquer contexto.
 *
 * Este arquivo é o oposto: cada entrada foi decidida termo a termo, com a
 * terminologia consagrada em português (Junqueira & Carneiro; Ross & Pawlina;
 * Terminologia Histologica). É trabalho editorial versionado e auditável — dá
 * para revisar linha por linha, e é isso que um revisor biomédico vai fazer.
 *
 * ## Regras de uso
 *
 * - **Só há correspondência exata.** Não existe fallback morfológico ("-ium →
 *   -io"), porque uma regra dessas gera termo plausível e errado exatamente
 *   onde ninguém vai conferir.
 * - Termo ausente do glossário **permanece em inglês** e é marcado na interface
 *   como pendente de tradução. Lacuna visível é melhor que preenchimento falso.
 * - Traduzir aqui **não** promove nada a `publicado`: o estado editorial
 *   continua `pendente-de-revisao` até um revisor humano assinar.
 */

/** Rótulos que não nomeiam estrutura: são crédito, navegação ou metainformação. */
export const CLASSIFICACAO_DE_MARCADOR: Record<string, 'credito' | 'navegacao'> = {
  'image source': 'credito',
  'image sources': 'credito',
  'image credit': 'credito',
  'image credits': 'credito',
  'next image': 'navegacao',
  'previous image': 'navegacao',
  'area shown in next image': 'navegacao',
  'area shown in the next image': 'navegacao',
  'begin again': 'navegacao',
  'section location': 'navegacao',
  'plane of section': 'navegacao',
  'right image': 'navegacao',
  'left image': 'navegacao',
  'comparison': 'navegacao',
  'orientation': 'navegacao',
  'stage': 'navegacao',
  'subdivisions': 'navegacao',
  'test': 'navegacao',
}

/**
 * Chave: rótulo original em minúsculas, sem espaços nas pontas.
 * Valor: termo em português brasileiro.
 */
export const GLOSSARIO: Record<string, string> = {
  /* ── Célula: compartimentos e organelas ── */
  'nucleus': 'Núcleo',
  'nuclei': 'Núcleos',
  'nucleolus': 'Nucléolo',
  'nucleoli': 'Nucléolos',
  'nuclear envelope': 'Envoltório nuclear',
  'nuclear envelopes': 'Envoltórios nucleares',
  'inner nuclear membrane': 'Membrana nuclear interna',
  'outer nuclear membrane': 'Membrana nuclear externa',
  'perinuclear space': 'Espaço perinuclear',
  'nuclear pores': 'Poros nucleares',
  'heterochromatin': 'Heterocromatina',
  'euchromatin': 'Eucromatina',
  'chromatin': 'Cromatina',
  'chromosomes': 'Cromossomos',
  'sister chromatids': 'Cromátides-irmãs',
  'centromeres': 'Centrômeros',
  'cytoplasm': 'Citoplasma',
  'plasma membrane': 'Membrana plasmática',
  'plasma membranes': 'Membranas plasmáticas',
  'mitochondria': 'Mitocôndrias',
  'mitochondrion': 'Mitocôndria',
  'cristae': 'Cristas mitocondriais',
  'rer': 'Retículo endoplasmático rugoso (RER)',
  'ser': 'Retículo endoplasmático liso (REL)',
  'rough endoplasmic reticulum': 'Retículo endoplasmático rugoso',
  'smooth endoplasmic reticulum': 'Retículo endoplasmático liso',
  'endoplasmic reticulum': 'Retículo endoplasmático',
  'golgi': 'Complexo de Golgi',
  'golgi apparatus': 'Complexo de Golgi',
  'lysosomes': 'Lisossomos',
  'lysosome': 'Lisossomo',
  'peroxisomes': 'Peroxissomos',
  'ribosomes': 'Ribossomos',
  'polysomes': 'Polissomos',
  'secretory granules': 'Grânulos de secreção',
  'granules': 'Grânulos',
  'mucin granules': 'Grânulos de mucinogênio',
  'glycogen': 'Glicogênio',
  'glycogen granules': 'Grânulos de glicogênio',
  'lipid': 'Lipídio',
  'lipid droplets': 'Gotículas lipídicas',
  'residual bodies': 'Corpos residuais',
  'transport vesicles': 'Vesículas de transporte',
  'vesicles': 'Vesículas',
  'centrioles': 'Centríolos',
  'centrosomes': 'Centrossomos',
  'basal bodies': 'Corpúsculos basais',
  'microtubules': 'Microtúbulos',
  'microfilament bundles': 'Feixes de microfilamentos',
  'keratin filaments': 'Filamentos de queratina',
  'tonofibrils': 'Tonofibrilas',
  'intermediate filaments': 'Filamentos intermediários',
  'axoneme': 'Axonema',
  'cilia': 'Cílios',
  'microvilli': 'Microvilosidades',
  'stereocilia': 'Estereocílios',
  'brush border': 'Borda em escova',
  'cell body': 'Corpo celular',
  'cell processes': 'Prolongamentos celulares',
  'intercellular space': 'Espaço intercelular',
  'mitotic spindle': 'Fuso mitótico',
  'mitosis': 'Mitose',
  'meiosis': 'Meiose',
  'meiosis i': 'Meiose I',
  'meiosis ii': 'Meiose II',
  'daughter cells': 'Células-filhas',

  /* ── Junções e membrana basal ── */
  'desmosomes': 'Desmossomos',
  'hemidesmosomes': 'Hemidesmossomos',
  'zonula occludens': 'Zônula de oclusão',
  'zonula adherens': 'Zônula de adesão',
  'junctional complex': 'Complexo juncional',
  'attachment plaques': 'Placas de ancoragem',
  'basement membrane': 'Membrana basal',
  'basal lamina': 'Lâmina basal',
  'basal laminae': 'Lâminas basais',
  'external lamina': 'Lâmina externa',
  'lamina lucida': 'Lâmina lúcida',
  'lamina densa': 'Lâmina densa',
  'reticular lamina': 'Lâmina reticular',
  'anchoring fibrils': 'Fibrilas de ancoragem',

  /* ── Epitélios ── */
  'epithelium': 'Epitélio',
  'epithelial cell': 'Célula epitelial',
  'epithelial cells': 'Células epiteliais',
  'simple squamous epithelium': 'Epitélio simples pavimentoso',
  'simple cuboidal epithelium': 'Epitélio simples cúbico',
  'simple columnar epithelium': 'Epitélio simples colunar',
  'stratified squamous epithelium': 'Epitélio estratificado pavimentoso',
  'stratified squamous moist epithelium': 'Epitélio estratificado pavimentoso não queratinizado',
  'stratified columnar epithelium': 'Epitélio estratificado colunar',
  'pseudostratified epithelium': 'Epitélio pseudoestratificado',
  'pseudostratified columnar epithelium': 'Epitélio pseudoestratificado colunar',
  'transitional epithelium': 'Epitélio de transição (urotélio)',
  'mesothelium': 'Mesotélio',
  'endothelium': 'Endotélio',
  'endothelial cells': 'Células endoteliais',
  'endothelial cell': 'Célula endotelial',
  'endothelial cell nuclei': 'Núcleos de células endoteliais',
  'fenestrated endothelium': 'Endotélio fenestrado',
  'fenestrations': 'Fenestrações',
  'squamous cells': 'Células pavimentosas',
  'basal cells': 'Células basais',
  'goblet cell': 'Célula caliciforme',
  'goblet cells': 'Células caliciformes',
  'ciliated cells': 'Células ciliadas',
  'absorptive cells': 'Células absortivas',
  'secretory cells': 'Células secretoras',
  'supporting cells': 'Células de sustentação',
  'principal cells': 'Células principais',
  'chief cells': 'Células principais (zimogênicas)',
  'enteroendocrine cells': 'Células enteroendócrinas',
  'endocrine cells': 'Células endócrinas',

  /* ── Glândulas ── */
  'glands': 'Glândulas',
  'gland': 'Glândula',
  'sheet gland': 'Glândula em lençol',
  'acini': 'Ácinos',
  'acinus': 'Ácino',
  'acinar cells': 'Células acinosas',
  'acinar lumens': 'Luzes acinosas',
  'serous acini': 'Ácinos serosos',
  'serous demilunes': 'Semiluas serosas',
  'mucous tubules': 'Túbulos mucosos',
  'mucus-secreting tubules': 'Túbulos secretores de muco',
  'mixed glands': 'Glândulas mistas',
  'secretory tubule': 'Túbulo secretor',
  'duct': 'Ducto',
  'ducts': 'Ductos',
  'intercalated duct': 'Ducto intercalar',
  'intralobular duct': 'Ducto intralobular',
  'intralobular ducts': 'Ductos intralobulares',
  'interlobular duct': 'Ducto interlobular',
  'interlobular ducts': 'Ductos interlobulares',
  'lobule': 'Lóbulo',
  'lobules': 'Lóbulos',
  'mucus': 'Muco',
  'mucin': 'Mucina',
  'sebum': 'Sebo',

  /* ── Tecido conjuntivo ── */
  'connective tissue': 'Tecido conjuntivo',
  'connective tissue proper': 'Tecido conjuntivo propriamente dito',
  'loose connective tissue': 'Tecido conjuntivo frouxo',
  'dense connective tissue': 'Tecido conjuntivo denso',
  'dense regular connective tissue': 'Tecido conjuntivo denso modelado',
  'dense irregular connective tissue': 'Tecido conjuntivo denso não modelado',
  'interlobular connective tissue': 'Tecido conjuntivo interlobular',
  'intralobular connective tissue': 'Tecido conjuntivo intralobular',
  'connective tissue core': 'Eixo de tecido conjuntivo',
  'connective tissue septa': 'Septos de tecido conjuntivo',
  'extracellular matrix': 'Matriz extracelular',
  'ground substance': 'Substância fundamental',
  'matrix': 'Matriz',
  'territorial matrix': 'Matriz territorial',
  'interterritorial matrix': 'Matriz interterritorial',
  'collagen fibers': 'Fibras colágenas',
  'collagen fibrils': 'Fibrilas colágenas',
  'collagen bundles': 'Feixes de colágeno',
  'elastic fibers': 'Fibras elásticas',
  'reticular fibers': 'Fibras reticulares',
  'fibroblast': 'Fibroblasto',
  'fibroblasts': 'Fibroblastos',
  'fibroblast nuclei': 'Núcleos de fibroblastos',
  'active fibroblast nuclei': 'Núcleos de fibroblastos ativos',
  'inactive fibroblast nuclei': 'Núcleos de fibroblastos inativos (fibrócitos)',
  'fibroblast processes': 'Prolongamentos de fibroblastos',
  'macrophage': 'Macrófago',
  'macrophages': 'Macrófagos',
  'mast cell': 'Mastócito',
  'mast cells': 'Mastócitos',
  'plasma cells': 'Plasmócitos',
  'adipocytes': 'Adipócitos',
  'adipocyte nuclei': 'Núcleos de adipócitos',
  'stroma': 'Estroma',
  'parenchyma': 'Parênquima',
  'capsule': 'Cápsula',
  'trabeculum': 'Trabécula',
  'trabeculae': 'Trabéculas',

  /* ── Cartilagem ── */
  'cartilage': 'Cartilagem',
  'hyaline cartilage': 'Cartilagem hialina',
  'elastic cartilage': 'Cartilagem elástica',
  'fibrocartilage': 'Fibrocartilagem',
  'cartilage plates': 'Placas de cartilagem',
  'calcified cartilage': 'Cartilagem calcificada',
  'chondrocytes': 'Condrócitos',
  'chondroblasts': 'Condroblastos',
  'perichondrium': 'Pericôndrio',
  'perichondrium: chondrogenic layer': 'Pericôndrio: camada condrogênica',
  'perichondrium: fibrous layer': 'Pericôndrio: camada fibrosa',
  'isogenous groups': 'Grupos isógenos',
  'fibrous layer': 'Camada fibrosa',

  /* ── Osso ── */
  'bone': 'Osso',
  'compact bone': 'Osso compacto',
  'spongy bone': 'Osso esponjoso',
  'woven bone': 'Osso primário (não lamelar)',
  'lamellar bone': 'Osso lamelar',
  'osteocytes': 'Osteócitos',
  'osteoblasts': 'Osteoblastos',
  'osteoclasts': 'Osteoclastos',
  'osteoid': 'Osteoide',
  'osteons': 'Ósteons',
  'forming osteon': 'Ósteon em formação',
  'haversian canals': 'Canais de Havers',
  'haversian systems': 'Sistemas de Havers',
  "volkmann's canal": 'Canal de Volkmann',
  "volkmann's canals": 'Canais de Volkmann',
  "howship's lacunae": 'Lacunas de Howship',
  'osteocyte lacunae': 'Lacunas de osteócitos',
  'canaliculi': 'Canalículos',
  'lamellae': 'Lamelas',
  'periosteum': 'Periósteo',
  'endosteum': 'Endósteo',
  'bone lining cells': 'Células de revestimento ósseo',
  'periosteal collar': 'Colar periosteal',
  'spicules': 'Espículas ósseas',
  'diaphysis': 'Diáfise',
  'epiphysis': 'Epífise',
  'zone of ossification': 'Zona de ossificação',
  'bone marrow': 'Medula óssea',
  'red bone marrow': 'Medula óssea vermelha',
  'red marrow': 'Medula vermelha',
  'megakaryocytes': 'Megacariócitos',

  /* ── Sangue ── */
  'blood cells': 'Células sanguíneas',
  'red blood cells': 'Hemácias',
  'platelets': 'Plaquetas',
  'lymphocytes': 'Linfócitos',
  'basophils': 'Basófilos',
  'eosinophils': 'Eosinófilos',
  'neutrophils': 'Neutrófilos',
  'monocytes': 'Monócitos',

  /* ── Músculo ── */
  'smooth muscle': 'Músculo liso',
  'smooth muscle cells': 'Células musculares lisas',
  'smooth muscle fibers': 'Fibras musculares lisas',
  'smooth muscle fascicles': 'Fascículos de músculo liso',
  'skeletal muscle': 'Músculo esquelético',
  'skeletal muscle fibers': 'Fibras musculares esqueléticas',
  'cardiac muscle': 'Músculo cardíaco',
  'muscle fiber': 'Fibra muscular',
  'muscle fibers': 'Fibras musculares',
  'myofibrils': 'Miofibrilas',
  'myofilaments': 'Miofilamentos',
  'sarcomeres': 'Sarcômeros',
  'sarcolemma': 'Sarcolema',
  'sarcoplasmic reticulum': 'Retículo sarcoplasmático',
  'a bands': 'Bandas A',
  'i bands': 'Bandas I',
  'z lines': 'Linhas Z',
  'striations': 'Estriações',
  'intercalated discs': 'Discos intercalares',
  'endomysium': 'Endomísio',
  'perimysium': 'Perimísio',
  'epimysium': 'Epimísio',

  /* ── Tecido nervoso ── */
  'axon': 'Axônio',
  'axons': 'Axônios',
  'myelinated axons': 'Axônios mielinizados',
  'unmyelinated axons': 'Axônios amielínicos',
  'myelin sheath': 'Bainha de mielina',
  'myelin sheaths': 'Bainhas de mielina',
  'dendrites': 'Dendritos',
  'neuronal cell bodies': 'Corpos celulares de neurônios',
  'nissl substance': 'Substância de Nissl',
  'schwann cells': 'Células de Schwann',
  'schwann cell nuclei': 'Núcleos de células de Schwann',
  'peripheral nerve': 'Nervo periférico',
  'peripheral nerves': 'Nervos periféricos',
  'perineurium': 'Perineuro',
  'endoneurium': 'Endoneuro',
  'epineurium': 'Epineuro',

  /* ── Vasos ── */
  'blood vessel': 'Vaso sanguíneo',
  'blood vessels': 'Vasos sanguíneos',
  'pulmonary vessels': 'Vasos pulmonares',
  'pulmonary artery': 'Artéria pulmonar',
  'capillary': 'Capilar',
  'capillaries': 'Capilares',
  'capillary lumen': 'Luz do capilar',
  'arteriole': 'Arteríola',
  'afferent arteriole': 'Arteríola aferente',
  'efferent arteriole': 'Arteríola eferente',
  'venule': 'Vênula',
  'venules': 'Vênulas',
  'high endothelial venules': 'Vênulas de endotélio alto',
  'small artery': 'Artéria de pequeno calibre',
  'medium vein': 'Veia de médio calibre',
  'sinusoids': 'Sinusoides',
  'vasa recta': 'Vasa recta',
  'tunica intima': 'Túnica íntima',
  'tunica media': 'Túnica média',
  'tunica adventitia': 'Túnica adventícia',
  'adventitia': 'Adventícia',
  'internal elastic lamina': 'Lâmina elástica interna',
  'external elastic lamina': 'Lâmina elástica externa',
  'elastic lamellae': 'Lamelas elásticas',
  'endocardium': 'Endocárdio',
  'lumen': 'Luz',
  'lumens': 'Luzes',

  /* ── Tubo digestório ── */
  'mucosa': 'Mucosa',
  'lining mucosa': 'Mucosa de revestimento',
  'submucosa': 'Submucosa',
  'lamina propria': 'Lâmina própria',
  'muscularis mucosae': 'Muscular da mucosa',
  'muscularis externa': 'Muscular externa',
  'inner circular layer': 'Camada circular interna',
  'outer longitudinal layer': 'Camada longitudinal externa',
  'serosa': 'Serosa',
  'villi': 'Vilosidades',
  'intestinal glands': 'Glândulas intestinais (criptas de Lieberkühn)',
  'intestinal lumen': 'Luz intestinal',
  'gastric pits': 'Fovéolas gástricas',
  'pyloric glands': 'Glândulas pilóricas',
  'esophagus': 'Esôfago',
  'rectum': 'Reto',
  'hepatocytes': 'Hepatócitos',
  'portal canals': 'Espaços porta',
  'islets of langerhans': 'Ilhotas de Langerhans',

  /* ── Dente e periodonto ── */
  'enamel': 'Esmalte',
  'dentin': 'Dentina',
  'predentin': 'Pré-dentina',
  'cementum': 'Cemento',
  'odontoblasts': 'Odontoblastos',
  'gingiva': 'Gengiva',
  'periodontal ligament': 'Ligamento periodontal',
  'alveolar bone': 'Osso alveolar',
  'outer enamel epithelium': 'Epitélio externo do esmalte',
  'inner enamel epithelium': 'Epitélio interno do esmalte',

  /* ── Respiratório ── */
  'trachea': 'Traqueia',
  'bronchus': 'Brônquio',
  'bronchiole': 'Bronquíolo',
  'terminal bronchiole': 'Bronquíolo terminal',
  'respiratory bronchiole': 'Bronquíolo respiratório',
  'alveoli': 'Alvéolos',
  'alveolar duct': 'Ducto alveolar',
  'alveolar ducts': 'Ductos alveolares',
  'alveolar sacs': 'Sacos alveolares',
  'alveolar lumens': 'Luzes alveolares',
  'interalveolar septa': 'Septos interalveolares',
  'air-blood barrier': 'Barreira hematoaérea',

  /* ── Pele ── */
  'skin': 'Pele',
  'epidermis': 'Epiderme',
  'dermis': 'Derme',
  'hypodermis': 'Hipoderme',
  'stratum basale': 'Estrato basal',
  'stratum spinosum': 'Estrato espinhoso',
  'stratum granulosum': 'Estrato granuloso',
  'stratum corneum': 'Estrato córneo',
  'papillary layer': 'Camada papilar',
  'papillary layer of dermis': 'Camada papilar da derme',
  'reticular layer': 'Camada reticular',
  'reticular layer of dermis': 'Camada reticular da derme',
  'dermal papillae': 'Papilas dérmicas',
  'epidermal ridges (pegs)': 'Cristas epidérmicas',
  'melanocytes': 'Melanócitos',
  'hair follicle': 'Folículo piloso',
  'hair follicles': 'Folículos pilosos',
  'sebaceous glands': 'Glândulas sebáceas',
  'apocrine sweat glands': 'Glândulas sudoríparas apócrinas',

  /* ── Linfoide ── */
  'diffuse lymphoid tissue': 'Tecido linfoide difuso',
  'lymphoid nodules': 'Nódulos linfoides',
  'germinal center': 'Centro germinativo',
  'germinal centers': 'Centros germinativos',
  'mantle': 'Zona do manto',
  'outer cortex': 'Córtex externo',
  'subcapsular sinus': 'Seio subcapsular',
  'medullary cords': 'Cordões medulares',
  'medullary sinuses': 'Seios medulares',
  'splenic sinuses': 'Seios esplênicos',
  'red pulp': 'Polpa vermelha',
  'white pulp': 'Polpa branca',
  'periarterial lymphoid sheath (pals)': 'Bainha linfoide periarteriolar (PALS)',
  'epithelial reticular cells': 'Células reticulares epiteliais',

  /* ── Urinário ── */
  'renal corpuscle': 'Corpúsculo renal',
  'glomerulus': 'Glomérulo',
  "bowman's space": 'Espaço de Bowman',
  'macula densa': 'Mácula densa',
  'proximal convoluted tubule': 'Túbulo contorcido proximal',
  'distal convoluted tubule': 'Túbulo contorcido distal',
  'ascending thick limb': 'Ramo ascendente espesso',
  'collecting duct': 'Ducto coletor',
  'renal sinus': 'Seio renal',
  'interlobular artery': 'Artéria interlobular',
  'tubule lumens': 'Luzes tubulares',
  'tubules': 'Túbulos',
  'urethra': 'Uretra',
  'glands of littre': 'Glândulas de Littré',
  'corpus spongiosum': 'Corpo esponjoso',

  /* ── Reprodutor ── */
  'rete testis': 'Rede testicular',
  'sertoli cells': 'Células de Sertoli',
  'spermatogonia': 'Espermatogônias',
  'primary spermatocytes': 'Espermatócitos primários',
  'spermatids (early)': 'Espermátides iniciais',
  'spermatozoa': 'Espermatozoides',
  'spermiogenesis': 'Espermiogênese',
  'spermiation': 'Espermiação',
  'tunica albuginea': 'Túnica albugínea',
  'tunica propria': 'Túnica própria',
  'mediastinum': 'Mediastino testicular',
  'myometrium': 'Miométrio',
  'endometrium': 'Endométrio',
  'basal zone': 'Camada basal',
  'functional zone': 'Camada funcional',
  'granulosa lutein cells': 'Células granulosa-luteínicas',
  'theca lutein cells': 'Células teca-luteínicas',
  'cytotrophoblast': 'Citotrofoblasto',
  'syncytiotrophoblast': 'Sinciciotrofoblasto',
  'floating villi': 'Vilosidades flutuantes',
  'intervillous space': 'Espaço interviloso',

  /* ── Olho ── */
  'sclera': 'Esclera',
  'choroid': 'Coroide',
  'retina': 'Retina',
  'iris': 'Íris',
  'lens': 'Cristalino',
  'pigment epithelium': 'Epitélio pigmentar',
  'anterior chamber': 'Câmara anterior',
  'vitreous chamber': 'Câmara vítrea',

  /* ── Ouvido ── */
  'middle ear': 'Orelha média',
  'cochlea': 'Cóclea',
  'cochlear duct': 'Ducto coclear',
  'utricle': 'Utrículo',
  'saccule': 'Sáculo',
  'vestibule': 'Vestíbulo',
  'semicircular canals': 'Canais semicirculares',
  'semicircular ducts': 'Ductos semicirculares',
  'organ of corti': 'Órgão de Corti',
  'basilar membrane': 'Membrana basilar',
  'vestibular membrane': 'Membrana vestibular',
  'osseous spiral lamina': 'Lâmina espiral óssea',
  'scala vestibuli': 'Rampa vestibular',
  'scala tympani': 'Rampa timpânica',
  'tympanic membrane': 'Membrana timpânica',
  'stapes': 'Estribo',
  'temporal bone': 'Osso temporal',
  'cn viii': 'Nervo vestibulococlear (NC VIII)',

  /* ══════════ Ampliação editorial — 2ª rodada ══════════ */

  /* ── Boca, dente e periodonto ── */
  'masticatory mucosa': 'Mucosa mastigatória',
  'oral (lining) mucosa': 'Mucosa oral de revestimento',
  'specialized mucosa': 'Mucosa especializada',
  'oral cavity': 'Cavidade oral',
  'taste buds': 'Botões gustativos',
  'taste pore': 'Poro gustativo',
  'filiform papillae': 'Papilas filiformes',
  'fungiform papillae': 'Papilas fungiformes',
  'circumvallate papilla': 'Papila circunvalada',
  'serous glands of von ebner': 'Glândulas serosas de von Ebner',
  'vermillion zone': 'Zona do vermelhão',
  'orbicularis oris muscle': 'Músculo orbicular da boca',
  'ducts of labial glands': 'Ductos das glândulas labiais',
  'ducts of glands': 'Ductos das glândulas',
  'sulcular epithelium': 'Epitélio sulcular',
  'gingival sulcus': 'Sulco gengival',
  'cellular cementum': 'Cemento celular',
  'acellular cementum': 'Cemento acelular',
  'cementoblasts': 'Cementoblastos',
  'cementocytes': 'Cementócitos',
  'cemento-enamel junction': 'Junção cemento-esmalte',
  'dentino-enamel junction': 'Junção dentino-esmalte',
  'dentinal tubules': 'Túbulos dentinários',
  'dental lamina': 'Lâmina dentária',
  'vestibular lamina': 'Lâmina vestibular',
  'tooth germ': 'Germe dentário',
  'tooth bud': 'Broto dentário',
  'enamel organ': 'Órgão do esmalte',
  'reduced enamel epithelium': 'Epitélio reduzido do esmalte',
  'stellate reticulum': 'Retículo estrelado',
  'ameloblasts': 'Ameloblastos',
  'dental papilla': 'Papila dentária',
  'dental follicle': 'Folículo dentário',
  'dental pulp': 'Polpa dentária',
  'dental pulp organ': 'Órgão da polpa dentária',
  'pulp chamber': 'Câmara pulpar',
  'pulp cavity': 'Cavidade pulpar',
  'pulp': 'Polpa',
  'cervical loop': 'Alça cervical',
  'bud stage': 'Estágio de broto',
  'cap stage': 'Estágio de capuz',
  'dental alveolus': 'Alvéolo dentário',
  'alveolar bone proper': 'Osso alveolar propriamente dito',
  'apical foramen': 'Forame apical',
  'tooth': 'Dente',
  'neck (cervix)': 'Colo do dente',

  /* ── Glândulas salivares ── */
  'striated duct': 'Ducto estriado',
  'striated ducts': 'Ductos estriados',
  'intralobular (striated) ducts': 'Ductos intralobulares estriados',
  'intercalated ducts': 'Ductos intercalares',
  'secretory units': 'Unidades secretoras',
  'secretory product': 'Produto de secreção',
  'serous-secreting acini': 'Ácinos de secreção serosa',
  'acinar lumen': 'Luz acinosa',
  'acinar cell nuclei': 'Núcleos de células acinosas',
  'mucous tubule lumens': 'Luzes dos túbulos mucosos',
  'compound acinar gland': 'Glândula acinosa composta',
  'simple tubular glands': 'Glândulas tubulares simples',
  'gland cells': 'Células glandulares',
  'gland lumens': 'Luzes glandulares',

  /* ── Tubo digestório ── */
  'cardiac stomach': 'Região cárdica do estômago',
  'pyloric stomach': 'Região pilórica do estômago',
  'cardiac glands': 'Glândulas cárdicas',
  'fundic glands': 'Glândulas fúndicas',
  'gastric glands': 'Glândulas gástricas',
  'parietal cells': 'Células parietais (oxínticas)',
  'stomach lumen': 'Luz gástrica',
  'esophageal glands proper': 'Glândulas esofágicas propriamente ditas',
  'duodenum': 'Duodeno',
  'small intestine': 'Intestino delgado',
  'large intestine': 'Intestino grosso',
  'enterocytes': 'Enterócitos',
  'paneth cells': 'Células de Paneth',
  'plicae circulares': 'Pregas circulares (válvulas de Kerckring)',
  'glycocalyx': 'Glicocálice',
  'peyer’s patch': 'Placa de Peyer',
  "peyer's patch": 'Placa de Peyer',
  'malt': 'Tecido linfoide associado à mucosa (MALT)',
  'taeniae coli': 'Tênias do cólon',
  'inner muscularis externa': 'Camada interna da muscular externa',
  'outer muscularis externa': 'Camada externa da muscular externa',
  'muscularis': 'Muscular',
  'inner circular muscle': 'Camada muscular circular interna',
  'middle circular muscle': 'Camada muscular circular média',
  'inner longitudinal muscle': 'Camada muscular longitudinal interna',
  'anal canal': 'Canal anal',
  'anus': 'Ânus',
  'recto-anal junction': 'Junção retoanal',
  'external anal sphincter': 'Esfíncter anal externo',
  'mesentery': 'Mesentério',
  'myenteric plexus': 'Plexo mientérico',
  "myenteric (auerbach's) plexus": 'Plexo mientérico (de Auerbach)',
  "submucosal (meissner's) plexus": 'Plexo submucoso (de Meissner)',
  'neuron cell bodies': 'Corpos celulares de neurônios',
  'stratified squamous, keratinized (dry) epithelium':
    'Epitélio estratificado pavimentoso queratinizado',
  'stratified squamous, nonkeratinized (moist) epithelium':
    'Epitélio estratificado pavimentoso não queratinizado',

  /* ── Fígado e pâncreas ── */
  'central veins': 'Veias centrolobulares',
  'space of disse': 'Espaço de Disse',
  'fenestrations and discontinuities': 'Fenestrações e descontinuidades',
  'centroacinar cells': 'Células centroacinosas',
  'islet of langerhans': 'Ilhota de Langerhans',

  /* ── Osso e cartilagem ── */
  'resorption canal': 'Canal de reabsorção',
  'zone of degeneration': 'Zona de degeneração',
  'zone of proliferation': 'Zona de proliferação',
  'zones of m-h-c': 'Zonas de maturação, hipertrofia e calcificação',
  'hemopoietic tissue': 'Tecido hemopoiético',
  'lacunae': 'Lacunas',
  'marrow': 'Medula óssea',
  'marrow cavity': 'Cavidade medular',
  'compact, woven bone': 'Osso compacto não lamelar',
  'circumferential lamellae': 'Lamelas circunferenciais',
  'inner circumferential lamellae': 'Lamelas circunferenciais internas',
  'interstitial lamellae': 'Lamelas intersticiais',
  'osteon': 'Ósteon',
  'cement lines': 'Linhas cementantes',
  'metaphysis': 'Metáfise',
  'epiphyseal plate': 'Disco epifisário',
  'epiphyseal plates': 'Discos epifisários',
  'normal cartilage': 'Cartilagem normal',
  'chondrogenic layer': 'Camada condrogênica',
  'artifactual space': 'Espaço de artefato',

  /* ── Divisão celular e gametogênese ── */
  'interphase': 'Intérfase',
  'interphase nuclei': 'Núcleos em intérfase',
  'metaphase': 'Metáfase',
  'cleavage furrow': 'Sulco de clivagem',
  'pair of homologous chromosomes': 'Par de cromossomos homólogos',
  'spermatogenesis': 'Espermatogênese',
  'oogenesis': 'Ovogênese',
  'fertilization': 'Fecundação',

  /* ── Célula: complementos ── */
  'junctional complexes': 'Complexos juncionais',
  'columnar cells': 'Células colunares',
  'cell outlines': 'Contornos celulares',
  'cell junction': 'Junção celular',
  'terminal bars': 'Barras terminais',
  'terminal web': 'Trama terminal',
  'basal cell nuclei': 'Núcleos de células basais',
  'basal layer cells': 'Células da camada basal',
  'pars fibrosa': 'Pars fibrosa',
  'pars granulosa': 'Pars granulosa',
  'ribosomes on rer': 'Ribossomos no retículo endoplasmático rugoso',
  'nissl bodies': 'Corpúsculos de Nissl',
  'golgi complexes': 'Complexos de Golgi',
  'organelles': 'Organelas',
  'dense bodies': 'Corpos densos',
  'melanosomes': 'Melanossomos',
  'keratohyalin granules': 'Grânulos de querato-hialina',
  'myelin': 'Mielina',
  'fibers': 'Fibras',

  /* ── Sangue ── */
  'white blood cells': 'Leucócitos',
  'red blood cell': 'Hemácia',
  'neutrophil': 'Neutrófilo',
  'eosinophil': 'Eosinófilo',
  'plasma cell': 'Plasmócito',
  'lymphoid tissue': 'Tecido linfoide',

  /* ── Músculo ── */
  'cardiac muscle fibers': 'Fibras musculares cardíacas',
  'cardiac muscle fibers of the myocardium': 'Fibras musculares cardíacas do miocárdio',
  'muscle fibers, longitudinal section': 'Fibras musculares em corte longitudinal',
  'muscle fibers, cross section': 'Fibras musculares em corte transversal',
  'h band': 'Banda H',
  'm lines': 'Linhas M',
  'purkinje fibers': 'Fibras de Purkinje',
  'peripheral nuclei': 'Núcleos periféricos',
  'central nuclei': 'Núcleos centrais',
  'myocardium': 'Miocárdio',

  /* ── Tecido nervoso ── */
  'nerve': 'Nervo',
  'nerves': 'Nervos',
  'neurons': 'Neurônios',
  'spinal cord': 'Medula espinal',
  'astrocytes': 'Astrócitos',
  'oligodendrocytes': 'Oligodendrócitos',
  'glial cell nuclei': 'Núcleos de células gliais',
  "meissner's corpuscle": 'Corpúsculo de Meissner',
  'schwann cell cytoplasm': 'Citoplasma da célula de Schwann',
  'axon hillock': 'Cone de implantação do axônio',
  'multipolar neuron': 'Neurônio multipolar',
  'pseudounipolar neurons': 'Neurônios pseudounipolares',
  'pia mater': 'Pia-máter',

  /* ── Vasos e coração ── */
  'muscular artery': 'Artéria muscular',
  'medium artery': 'Artéria de médio calibre',
  'small vein': 'Veia de pequeno calibre',
  'veins': 'Veias',
  'arterioles': 'Arteríolas',
  'endothelial cell nucleus': 'Núcleo de célula endotelial',
  'fenestrae': 'Fenestras',
  'subendothelial connective tissue': 'Tecido conjuntivo subendotelial',
  'valve leaflets': 'Cúspides valvares',
  'valves': 'Válvulas',
  'aortic valve leaflet': 'Cúspide da valva aórtica',
  'annulus fibrosus': 'Ânulo fibroso',
  'elastic lamina': 'Lâmina elástica',
  'blood supply': 'Irrigação sanguínea',

  /* ── Urinário ── */
  'renal pyramid': 'Pirâmide renal',
  'renal pelvis': 'Pelve renal',
  'renal papilla': 'Papila renal',
  'minor calyx': 'Cálice menor',
  'medullary ray': 'Raio medular',
  'connecting tubule': 'Túbulo conector',
  'proximal convoluted tubules': 'Túbulos contorcidos proximais',
  'proximal straight tubules': 'Túbulos retos proximais',
  'proximal tubules': 'Túbulos proximais',
  'distal tubules': 'Túbulos distais',
  'collecting ducts': 'Ductos coletores',
  'papillary ducts': 'Ductos papilares',
  'thin limbs': 'Ramos delgados',
  'ascending thick limbs': 'Ramos ascendentes espessos',
  'urinary pole': 'Polo urinário',
  'vascular pole': 'Polo vascular',
  'juxtaglomerular apparatus': 'Aparelho justaglomerular',
  'juxtaglomerular cells': 'Células justaglomerulares',
  'podocytes': 'Podócitos',
  'pedicels': 'Pedicelos',
  'glomerular capillaries': 'Capilares glomerulares',
  "parietal layer of bowman's capsule": 'Folheto parietal da cápsula de Bowman',
  'bowman’s space': 'Espaço de Bowman',
  'intercalated cells': 'Células intercaladas',
  'principle cells': 'Células principais',
  'convoluted portions': 'Porções contorcidas',

  /* ── Linfoide ── */
  'lymphoid nodule': 'Nódulo linfoide',
  'secondary nodule': 'Nódulo secundário',
  'secondary nodules': 'Nódulos secundários',
  'lymph nodes': 'Linfonodos',
  'lymph vessels': 'Vasos linfáticos',
  'hilum': 'Hilo',
  'trabecular sinuses': 'Seios trabeculares',
  'central arteriole': 'Arteríola central',
  'splenic cords': 'Cordões esplênicos',
  'immunoblasts': 'Imunoblastos',
  'reticular cells': 'Células reticulares',
  "hassall's corpuscles": 'Corpúsculos de Hassall',
  'connective tissue reticulum': 'Retículo de tecido conjuntivo',

  /* ── Reprodutor masculino ── */
  'testis proper': 'Testículo propriamente dito',
  'seminiferous tubules': 'Túbulos seminíferos',
  'seminiferous tubules - convoluted portions': 'Túbulos seminíferos — porções contorcidas',
  'coni vasculosi': 'Cones eferentes (coni vasculosi)',
  'efferent ducts': 'Ductos eferentes',
  'duct of epididymis': 'Ducto do epidídimo',
  'ductus deferens': 'Ducto deferente',
  'processus vaginalis': 'Processo vaginal',
  'leydig cells': 'Células de Leydig',
  'leydig (interstitial) cells': 'Células de Leydig (intersticiais)',
  'spermatids (late)': 'Espermátides tardias',
  'testicular artery': 'Artéria testicular',
  'corpora cavernosa': 'Corpos cavernosos',
  'cavernous spaces': 'Espaços cavernosos',
  'outer longitudinal muscle': 'Camada muscular longitudinal externa',

  /* ── Reprodutor feminino e placenta ── */
  'germinal epithelium': 'Epitélio germinativo',
  'follicles': 'Folículos',
  'primary oocyte': 'Ovócito primário',
  'zona pellucida': 'Zona pelúcida',
  'theca interna': 'Teca interna',
  'theca externa': 'Teca externa',
  'active follicle cells': 'Células foliculares ativas',
  'plicae palmatae': 'Pregas palmadas',
  'external os': 'Óstio externo',
  'endocervical canal': 'Canal endocervical',
  'chorionic plate': 'Placa coriônica',
  'chorionic villi': 'Vilosidades coriônicas',
  'embryonic blood vessels': 'Vasos sanguíneos embrionários',
  'embryonic connective tissue': 'Tecido conjuntivo embrionário',
  'fetal connective tissue': 'Tecido conjuntivo fetal',
  'fetal blood vessels': 'Vasos sanguíneos fetais',
  'fibrinoid': 'Fibrinoide',

  /* ── Pele ── */
  'thin skin': 'Pele fina',
  'stratum lucidum': 'Estrato lúcido',
  'adipose tissue': 'Tecido adiposo',
  'sweat glands': 'Glândulas sudoríparas',
  'keratinized epithelium': 'Epitélio queratinizado',

  /* ── Olho ── */
  'cornea': 'Córnea',
  'corneal epithelium': 'Epitélio corneano',
  'ciliary body': 'Corpo ciliar',
  'ciliary processes': 'Processos ciliares',
  'lens capsule': 'Cápsula do cristalino',
  'lens epithelium': 'Epitélio do cristalino',
  'lens fibers': 'Fibras do cristalino',
  'posterior chamber': 'Câmara posterior',
  'optic disc': 'Disco óptico',
  "bruch's membrane": 'Membrana de Bruch',
  'nerve fiber layer': 'Camada de fibras nervosas',
  'outer plexiform layer': 'Camada plexiforme externa',
  'inner plexiform layer': 'Camada plexiforme interna',
  'photoreceptor layer': 'Camada de fotorreceptores',
  'choriocapillaris': 'Coriocapilar',
  'tarsus': 'Tarso',
  'palpebral conjunctiva': 'Conjuntiva palpebral',
  'orbicularis oculi muscle': 'Músculo orbicular do olho',

  /* ── Ouvido ── */
  'oval window': 'Janela oval',
  'ossicles': 'Ossículos',
  'endolymphatic duct': 'Ducto endolinfático',
  'eustachian tube': 'Tuba auditiva',
  'ampullae': 'Ampolas',
  'maculae': 'Máculas',
  'hair cells': 'Células ciliadas (sensoriais)',
  'crista ampullaris': 'Crista ampular',
  'cristae ampullares': 'Cristas ampulares',
  'tectorial membrane': 'Membrana tectória',
  'stria vascularis': 'Estria vascular',
  'modiolus': 'Modíolo',

  /* ── Respiratório ── */
  'nasal cavities': 'Cavidades nasais',
  'nasal septum': 'Septo nasal',
  'olfactory epithelium': 'Epitélio olfatório',
  'primary bronchi': 'Brônquios principais',
  'bronchioles': 'Bronquíolos',
  'respiratory bronchioles': 'Bronquíolos respiratórios',
  'bronchial vessels': 'Vasos brônquicos',
  'bronchial blood vessels': 'Vasos sanguíneos brônquicos',
  'cartilage plate': 'Placa de cartilagem',
  'interalveolar septum': 'Septo interalveolar',
  'alveolar lumen': 'Luz alveolar',
  'associated alveoli': 'Alvéolos associados',
  'type i cell': 'Pneumócito tipo I',
  'type ii cells': 'Pneumócitos tipo II',
  'pulmonary veins': 'Veias pulmonares',
  'visceral pleura': 'Pleura visceral',
  'smooth muscle knobs': 'Feixes salientes de músculo liso',

  /* ── Endócrino ── */
  'pars distalis': 'Pars distalis',
  'pars tuberalis': 'Pars tuberalis',
  'infundibulum': 'Infundíbulo',
  'chromophobes': 'Cromófobas',
  'herring bodies': 'Corpos de Herring',
  'pituicytes': 'Pituícitos',
  'thyroglobulin': 'Tireoglobulina',
  'oxyphil cells': 'Células oxífilas',
  'zona fasciculata': 'Zona fasciculada',
  'zona reticularis': 'Zona reticular',
  'pinealocytes': 'Pinealócitos',

  /* ── Microscopia ── */
  'light microscopy': 'Microscopia óptica',
  'objective lens': 'Objetiva',

  /* ══════════ 3ª rodada — cobertura ampla ══════════ */

  /* ── Preparo e microscopia ── */
  'tissue': 'Tecido',
  'tissue block holder': 'Suporte do bloco',
  'handwheel': 'Volante',
  'sections': 'Cortes',
  'lenses': 'Lentes',
  'substage condenser': 'Condensador',
  'ocular lens': 'Ocular',
  'micrograph': 'Fotomicrografia',
  'electron dense': 'Elétron-denso',
  'electron lucent': 'Elétron-lucente',
  'basophilia': 'Basofilia',
  'eosinophilia': 'Eosinofilia',
  'metachromasia (mast cells)': 'Metacromasia (mastócitos)',

  /* ── Tecidos: nomes gerais ── */
  'muscle tissue': 'Tecido muscular',
  'nervous tissue': 'Tecido nervoso',
  'lining epithelium': 'Epitélio de revestimento',
  'connective tissue cells': 'Células do tecido conjuntivo',
  'cells of connective tissue': 'Células do tecido conjuntivo',
  'epithelia': 'Epitélios',
  'blood': 'Sangue',
  'cells': 'Células',
  'tissue block': 'Bloco de tecido',
  'body': 'Corpo',
  'muscle': 'Músculo',
  'artery': 'Artéria',
  'valve': 'Válvula',
  'components': 'Componentes',
  'processes': 'Prolongamentos',
  'sulcus': 'Sulco',
  'stria': 'Estria',
  'knobs': 'Saliências',

  /* ── Célula e organelas (ampliação) ── */
  'outer membrane': 'Membrana externa',
  'inner membrane': 'Membrana interna',
  'perinuclear chromatin': 'Cromatina perinuclear',
  'nucleolar organizing centers': 'Regiões organizadoras do nucléolo',
  'connection with nuclear envelope': 'Continuidade com o envoltório nuclear',
  'cell outline': 'Contorno celular',
  'cistern lumen': 'Luz da cisterna',
  'rer cisterns': 'Cisternas do retículo endoplasmático rugoso',
  'basal rough endoplasmic reticulum': 'Retículo endoplasmático rugoso basal',
  'forming (cis) face': 'Face de formação (cis)',
  'maturing (trans) face': 'Face de maturação (trans)',
  'cis face': 'Face cis',
  'trans face': 'Face trans',
  'negative golgi image': 'Imagem negativa do Golgi',
  'matrix granules': 'Grânulos da matriz',
  'tubular cristae': 'Cristas tubulares',
  'infoldings': 'Invaginações',
  'mucosal infoldings': 'Pregas da mucosa',
  'microfilaments': 'Microfilamentos',
  'intermediate filaments and microtubules': 'Filamentos intermediários e microtúbulos',
  'microvillus': 'Microvilosidade',
  'microvilli (brush border)': 'Microvilosidades (borda em escova)',
  'tonofilaments': 'Tonofilamentos',
  'neurofilaments': 'Neurofilamentos',
  'diplosome': 'Diplossomo',
  'diplosome and mtoc': 'Diplossomo e centro organizador de microtúbulos',
  'desmosome': 'Desmossomo',
  'pinocytic vesicles': 'Vesículas pinocíticas',
  'diaphragms': 'Diafragmas',
  'barr body': 'Corpúsculo de Barr',
  'nuclear indentation': 'Indentação nuclear',
  'nuclear lobes': 'Lobos nucleares',
  'bilobed nucleus': 'Núcleo bilobulado',
  'clumped nuclei': 'Núcleos condensados',
  'melanin': 'Melanina',
  'melanin pigment': 'Pigmento melânico',
  'melanocyte': 'Melanócito',
  'fibroblast nucleus': 'Núcleo de fibroblasto',
  'fibroblast process': 'Prolongamento de fibroblasto',
  'lymphocyte': 'Linfócito',
  'osteoclast': 'Osteoclasto',
  'hepatocyte': 'Hepatócito',
  'secretory cell': 'Célula secretora',
  'supporting cell': 'Célula de sustentação',
  'proliferating cells': 'Células em proliferação',
  'proliferative cells': 'Células proliferativas',
  'degenerating cells': 'Células em degeneração',
  'living cells': 'Células vivas',
  'dead cells (squames)': 'Células mortas (escamas)',
  'migrating cells': 'Células em migração',
  'cuboidal cells': 'Células cúbicas',
  'columnar': 'Colunar',
  'free surface': 'Superfície livre',
  'dome cells': 'Células em cúpula',

  /* ── Divisão celular ── */
  'prophase': 'Prófase',
  'anaphase': 'Anáfase',
  'telophase': 'Telófase',
  'early anaphase': 'Anáfase inicial',
  'mid-anaphase': 'Anáfase média',
  'late anaphase': 'Anáfase tardia',
  'contractile ring': 'Anel contrátil',
  'metaphase plates': 'Placas metafásicas',
  'spindle fibers': 'Fibras do fuso',
  'mitotic spindles': 'Fusos mitóticos',
  'mitotic figures': 'Figuras de mitose',
  'centrosome': 'Centrossomo',
  'centromere': 'Centrômero',
  'gametes': 'Gametas',

  /* ── Sangue ── */
  'segmented neutrophils': 'Neutrófilos segmentados',
  'capillaries with red blood cells': 'Capilares com hemácias',
  'lymphocytes and macrophages': 'Linfócitos e macrófagos',

  /* ── Osso ── */
  'osteoblasts becoming osteocytes': 'Osteoblastos tornando-se osteócitos',
  'osteocytes in lacunae': 'Osteócitos em lacunas',
  'ostocytes': 'Osteócitos',
  'ruffled border': 'Borda pregueada',
  'marrow spaces': 'Espaços medulares',
  'spongy, woven bone': 'Osso esponjoso não lamelar',
  'spongy, lamellar bone': 'Osso esponjoso lamelar',
  'articular cartilages': 'Cartilagens articulares',
  'epiphyses': 'Epífises',
  'osteogenic layer': 'Camada osteogênica',
  'yellow bone marrow': 'Medula óssea amarela',
  'hemopoietic tissue in yellow marrow': 'Tecido hemopoiético na medula amarela',
  'bone spicules': 'Espículas ósseas',
  'outer circumferential': 'Circunferenciais externas',
  'inner circumferential': 'Circunferenciais internas',
  'outer circumferential lamellae': 'Lamelas circunferenciais externas',
  'pre-existing bone': 'Osso preexistente',
  'haversian canal': 'Canal de Havers',
  'resorption canals': 'Canais de reabsorção',
  'lining (endosteal) cells': 'Células de revestimento endosteal',
  'parallel lamellae': 'Lamelas paralelas',
  'resting lines': 'Linhas de repouso',
  'regressive cartilage': 'Cartilagem em regressão',
  'resting zone': 'Zona de repouso',
  'zones of maturation-hypertrophy-calcification':
    'Zonas de maturação, hipertrofia e calcificação',
  'zone of resorption': 'Zona de reabsorção',
  'collagen fibers (ls)': 'Fibras colágenas (corte longitudinal)',
  'collagen fibers (xs)': 'Fibras colágenas (corte transversal)',

  /* ── Músculo ── */
  'smooth muscle longitudinal section': 'Músculo liso em corte longitudinal',
  'skeletal muscle longitudinal section': 'Músculo esquelético em corte longitudinal',
  'smooth muscle cross section': 'Músculo liso em corte transversal',
  'skeletal muscle cross section': 'Músculo esquelético em corte transversal',
  'smooth muscle nuclei': 'Núcleos de músculo liso',
  'skeletal muscle nuclei': 'Núcleos de músculo esquelético',
  'smooth muscle layer': 'Camada de músculo liso',
  'thin myofilaments': 'Miofilamentos finos',
  'thick myofilaments': 'Miofilamentos grossos',
  'a band': 'Banda A',
  'i band': 'Banda I',
  'm line': 'Linha M',
  'cross striations': 'Estriações transversais',
  'branching fibers': 'Fibras ramificadas',
  'neuromuscular junctions': 'Junções neuromusculares',
  'nuclear bag fibers': 'Fibras de saco nuclear',
  'nuclear chain fibers': 'Fibras de cadeia nuclear',
  'extrafusal muscle fibers': 'Fibras musculares extrafusais',
  'longitudinal muscle fibers': 'Fibras musculares longitudinais',
  'transverse muscle fibers': 'Fibras musculares transversais',
  'elastic sheets': 'Lâminas elásticas',

  /* ── Nervoso ── */
  'autonomic ganglion': 'Gânglio autônomo',
  'spinal nerve': 'Nervo espinal',
  'grey matter': 'Substância cinzenta',
  'white matter': 'Substância branca',
  'cell bodies': 'Corpos celulares',
  'neuronal cell body': 'Corpo celular do neurônio',
  'nerve cells': 'Células nervosas',
  'dorsal roots': 'Raízes dorsais',
  'ventral roots': 'Raízes ventrais',
  'central canal': 'Canal central',
  'dorsal root ganglia': 'Gânglios da raiz dorsal',
  'schwann cell plasma membrane': 'Membrana plasmática da célula de Schwann',
  'schwann cell nucleus': 'Núcleo da célula de Schwann',
  'endoneurial and schwann cells': 'Células endoneurais e de Schwann',
  'synaptic vesicles': 'Vesículas sinápticas',
  'synaptic cleft': 'Fenda sináptica',
  'postsynaptic density': 'Densidade pós-sináptica',
  'postsynaptic neuron': 'Neurônio pós-sináptico',
  'dendritic spines': 'Espinhas dendríticas',
  'multipolar neurons': 'Neurônios multipolares',
  'pyramidal neuron': 'Neurônio piramidal',
  'fibrous astrocytes': 'Astrócitos fibrosos',
  'pacinian corpuscle': 'Corpúsculo de Pacini',
  'pacinian corpuscles': 'Corpúsculos de Pacini',
  'myelin internodes': 'Internódulos de mielina',
  'node of ranvier': 'Nó de Ranvier',
  'paranode': 'Paranó',
  'paranodal loops': 'Alças paranodais',
  'nerve fascicles': 'Fascículos nervosos',
  'dura mater': 'Dura-máter',
  'subdural space': 'Espaço subdural',
  'arachnoid membrane': 'Aracnoide',
  'subarachnoid space': 'Espaço subaracnóideo',
  'ganglia': 'Gânglios',

  /* ── Vasos e coração ── */
  'basal lamina of endothelial cell': 'Lâmina basal da célula endotelial',
  'basal lamina of endocrine cell': 'Lâmina basal da célula endócrina',
  'pericyte process': 'Prolongamento de pericito',
  'pericyte processes': 'Prolongamentos de pericitos',
  'endothelium of tunica intima': 'Endotélio da túnica íntima',
  'capillary lumens': 'Luzes capilares',
  'venules and small veins': 'Vênulas e veias de pequeno calibre',
  'epicardium': 'Epicárdio',
  'right atrioventricular valve leaflet': 'Cúspide da valva atrioventricular direita',
  'interventricular septum': 'Septo interventricular',
  'membranous portion': 'Porção membranácea',
  'muscular portion': 'Porção muscular',
  'atrioventricular bundle': 'Fascículo atrioventricular (de His)',
  'right bundle branch': 'Ramo direito',
  'left bundle branch': 'Ramo esquerdo',
  'subendocardial layer': 'Camada subendocárdica',
  'aortic wall': 'Parede da aorta',
  'ventricle': 'Ventrículo',

  /* ── Digestório ── */
  'appendix': 'Apêndice vermiforme',
  'esophagogastric junction': 'Junção esofagogástrica',
  'opening of gastric pits': 'Abertura das fovéolas gástricas',
  'gastric pit': 'Fovéola gástrica',
  'pits': 'Fovéolas',
  'opening of pits': 'Abertura das fovéolas',
  'middle circular layer': 'Camada circular média',
  'necks of glands': 'Colos das glândulas',
  'lumens of glands': 'Luzes das glândulas',
  'lumen of gland': 'Luz da glândula',
  'bodies of glands': 'Corpos das glândulas',
  'branching glands': 'Glândulas ramificadas',
  'fundus': 'Fundo',
  'fundic stomach': 'Região fúndica do estômago',
  'body of stomach': 'Corpo do estômago',
  'body and fundic regions': 'Regiões do corpo e fundo',
  'cardiac region': 'Região cárdica',
  'pyloric region': 'Região pilórica',
  'pylorus': 'Piloro',
  'pyloric sphincter': 'Esfíncter pilórico',
  'stomach': 'Estômago',
  'stomach lumen ': 'Luz gástrica',
  'plica circularis': 'Prega circular',
  'lacteals': 'Vasos quilíferos',
  'lacteal': 'Vaso quilífero',
  'lymphatic vessels': 'Vasos linfáticos',
  'lymph capillaries': 'Capilares linfáticos',
  'submucosal plexus': 'Plexo submucoso',
  "submucosal (meissner’s) plexus": 'Plexo submucoso (de Meissner)',
  "myenteric (auerbach’s) plexus": 'Plexo mientérico (de Auerbach)',
  'intestinal gland': 'Glândula intestinal',
  'intestinal glands with goblet cells': 'Glândulas intestinais com células caliciformes',
  'intestinal villi': 'Vilosidades intestinais',
  'absorptive cells (enterocytes)': 'Células absortivas (enterócitos)',
  'primary lymphoid nodule': 'Nódulo linfoide primário',
  'secondary lymphoid nodule': 'Nódulo linfoide secundário',
  'secondary lymphoid nodules': 'Nódulos linfoides secundários',
  'nodular lymphoid tissue': 'Tecido linfoide nodular',
  "nodule aggregate (peyer’s patch)": 'Agregado de nódulos (placa de Peyer)',
  'region of junction with anus': 'Região da junção com o ânus',
  'internal anal sphincter': 'Esfíncter anal interno',
  'jejunum': 'Jejuno',
  'ileum': 'Íleo',
  'colon': 'Cólon',
  'esophageal glands': 'Glândulas esofágicas',
  'lumen of the esophagus': 'Luz do esôfago',
  'sloughing nucleated cells': 'Células nucleadas em descamação',
  'outermost tunic: adventitia': 'Túnica mais externa: adventícia',
  'outermost tunic: serosa': 'Túnica mais externa: serosa',
  'basal part of cells': 'Porção basal das células',
  'mucous neck cells': 'Células mucosas do colo',
  'mucous cells': 'Células mucosas',
  'parietal cell': 'Célula parietal',
  'enteroendocrine': 'Enteroendócrina',
  'enteroendocrine cell': 'Célula enteroendócrina',
  "brunner's glands (submucosal glands)": 'Glândulas de Brunner (submucosas)',
  "brunner’s glands (submucosal glands)": 'Glândulas de Brunner (submucosas)',
  "submucosal gland (brunner's gland)": 'Glândula submucosa (de Brunner)',
  "submucosal glands (brunner's glands)": 'Glândulas submucosas (de Brunner)',
  "submucosal glands (brunner’s glands)": 'Glândulas submucosas (de Brunner)',
  'connection with intestinal glands': 'Comunicação com as glândulas intestinais',
  'simple columnar epithelium with goblet cells':
    'Epitélio simples colunar com células caliciformes',
  'muscularis externa inner layer': 'Camada interna da muscular externa',
  'muscularis externa outer layer': 'Camada externa da muscular externa',
  'stratified squamous keratinized epithelium': 'Epitélio estratificado pavimentoso queratinizado',
  'keratinized stratified squamous epithelium': 'Epitélio estratificado pavimentoso queratinizado',
  'unicellular glands (goblet cells)': 'Glândulas unicelulares (células caliciformes)',
  'goblet cell nuclei': 'Núcleos de células caliciformes',
  'columnar cell nuclei': 'Núcleos de células colunares',
  'columnar cells (ciliated)': 'Células colunares ciliadas',
  'simple tubular gland': 'Glândula tubular simples',
  'simple, branched tubular gland': 'Glândula tubular simples ramificada',
  'secretory tubules': 'Túbulos secretores',
  'nuclei of acinar cells': 'Núcleos de células acinosas',
  'squamous cell nuclei': 'Núcleos de células pavimentosas',
  'serous membrane': 'Membrana serosa',
  'peritoneal cavity': 'Cavidade peritoneal',
  'interlobular ct': 'Tecido conjuntivo interlobular',
  'intercalated duct cells': 'Células do ducto intercalar',
  'centroacinar cell nuclei': 'Núcleos de células centroacinosas',
  'beta cells': 'Células beta',
  'alpha cells': 'Células alfa',

  /* ── Fígado ── */
  'liver lobule': 'Lóbulo hepático',
  'liver lobules': 'Lóbulos hepáticos',
  'liver sinusoids': 'Sinusoides hepáticos',
  'hepatic sinusoids': 'Sinusoides hepáticos',
  'sinusoid': 'Sinusoide',
  'direction of blood flow': 'Sentido do fluxo sanguíneo',
  'direction of bile flow': 'Sentido do fluxo biliar',
  'hepatic arteries': 'Artérias hepáticas',
  'hepatic artery': 'Artéria hepática',
  'hepatic portal veins': 'Veias porta hepáticas',
  'hepatic portal vein': 'Veia porta hepática',
  'bile ducts': 'Ductos biliares',
  'bile duct': 'Ducto biliar',
  'central vein': 'Veia centrolobular',
  'kupffer cells': 'Células de Kupffer',
  'kupffer cell': 'Célula de Kupffer',
  'cell margins': 'Limites celulares',
  'bile canaliculi': 'Canalículos biliares',
  'ultrastructure of the bile canaliculus': 'Ultraestrutura do canalículo biliar',
  'hepatocyte nuclei': 'Núcleos de hepatócitos',
  'hepatocyte microvilli': 'Microvilosidades do hepatócito',

  /* ── Urinário ── */
  'renal columns': 'Colunas renais',
  'minor calyces': 'Cálices menores',
  'ureter': 'Ureter',
  'arcuate vessels': 'Vasos arqueados',
  'renal corpuscles': 'Corpúsculos renais',
  'medullary rays': 'Raios medulares',
  'proximal straight tubule': 'Túbulo reto proximal',
  'thin limb': 'Ramo delgado',
  'loop of henle': 'Alça de Henle',
  'collecting passageways': 'Vias coletoras',
  'papillary duct': 'Ducto papilar',
  'distal convoluted tubules': 'Túbulos contorcidos distais',
  "bowman's capsule": 'Cápsula de Bowman',
  'podocyte': 'Podócito',
  'primary process': 'Processo primário',
  'connecting tubules': 'Túbulos conectores',
  'peritubular capillaries': 'Capilares peritubulares',
  'area cribosa': 'Área cribosa',
  'urethral lumen': 'Luz uretral',
  'central lumen': 'Luz central',
  'lumen of duct': 'Luz do ducto',

  /* ── Linfoide ── */
  'thymus': 'Timo',
  'spleen': 'Baço',
  'thymocytes': 'Timócitos',
  'tingible body macrophages': 'Macrófagos de corpos tingíveis',
  'deep cortex': 'Córtex profundo',
  'paracortex': 'Paracórtex',
  'deep cortex (paracortex)': 'Córtex profundo (paracórtex)',
  'marginal zone': 'Zona marginal',
  'central arterioles': 'Arteríolas centrais',

  /* ── Reprodutor ── */
  'penis': 'Pênis',
  'scrotum': 'Escroto',
  'head of epididymis': 'Cabeça do epidídimo',
  'head': 'Cabeça',
  'secondary spermatocytes': 'Espermatócitos secundários',
  'early spermatids': 'Espermátides iniciais',
  'late spermatids': 'Espermátides tardias',
  'efferent ductules': 'Dúctulos eferentes',
  'efferent ductule': 'Dúctulo eferente',
  'seminiferous tubules - straight portions': 'Túbulos seminíferos — porções retas',
  'vasculature': 'Vascularização',
  'spermatic cord': 'Funículo espermático',
  'pampiniform plexus': 'Plexo pampiniforme',
  'cremaster muscle': 'Músculo cremaster',
  'venous plexus': 'Plexo venoso',
  'deep artery': 'Artéria profunda',
  'prostatic concretions': 'Concreções prostáticas',
  'cervix': 'Colo do útero',
  'vagina': 'Vagina',
  'ovulation': 'Ovulação',
  'implantation': 'Implantação',
  'primary oocytes': 'Ovócitos primários',
  'primordial follicles': 'Folículos primordiais',
  'follicular cells': 'Células foliculares',
  'cumulus oophorus': 'Cumulus oophorus',
  'antrum': 'Antro',
  'mesosalpinx': 'Mesossalpinge',
  'degeneration': 'Degeneração',
  'extravasated blood': 'Sangue extravasado',
  'uterine lumen': 'Luz uterina',
  'ectocervix': 'Ectocérvice',
  'mucous secretions': 'Secreções mucosas',
  'trophoblastic shell': 'Concha trofoblástica',
  'decidua': 'Decídua',
  'stem villus': 'Vilosidade-tronco',
  'mammary glands': 'Glândulas mamárias',

  /* ── Pele ── */
  'keratinized layer': 'Camada queratinizada',
  'thick skin': 'Pele espessa',
  'hypodermis (subcutis)': 'Hipoderme (tela subcutânea)',
  'dermis (papillary layer)': 'Derme (camada papilar)',
  'epidermis of skin': 'Epiderme',
  'langerhans cell': 'Célula de Langerhans',
  'ducts of sweat glands': 'Ductos das glândulas sudoríparas',
  'duct of sweat gland': 'Ducto de glândula sudorípara',
  'apocrine sweat gland': 'Glândula sudorípara apócrina',
  'vascular papillae': 'Papilas vasculares',
  'bulb': 'Bulbo piloso',
  'papilla': 'Papila',
  'hair shaft': 'Haste do pelo',
  'follicle sheath': 'Bainha do folículo',
  'sebaceous gland': 'Glândula sebácea',
  'epidermal pegs': 'Cristas epidérmicas',
  'adipocytes filled with lipid': 'Adipócitos repletos de lipídio',

  /* ── Olho ── */
  'bulbar conjunctiva': 'Conjuntiva bulbar',
  'optic nerve': 'Nervo óptico',
  "bowman's membrane": 'Camada de Bowman',
  "descemet's membrane": 'Membrana de Descemet',
  'canal of schlemm': 'Canal de Schlemm',
  'pupil': 'Pupila',
  'zonular fibers': 'Fibras zonulares',
  'posterior iris epithelium': 'Epitélio posterior da íris',
  'dilator pupillae muscle': 'Músculo dilatador da pupila',
  'choroidal stroma': 'Estroma coroidal',
  'choriocapillary layer': 'Camada coriocapilar',
  'non-sensory retina': 'Retina não sensorial',
  'ora serrata': 'Ora serrata',
  'outer segments': 'Segmentos externos',
  'inner segments': 'Segmentos internos',
  'outer limiting membrane': 'Membrana limitante externa',
  'outer nuclear layer': 'Camada nuclear externa',
  'inner nuclear layer': 'Camada nuclear interna',
  'ganglion cell layer': 'Camada de células ganglionares',
  'inner limiting membrane': 'Membrana limitante interna',
  'bruch’s membrane': 'Membrana de Bruch',
  'outer segments of rods and cones': 'Segmentos externos de cones e bastonetes',
  'membranous discs': 'Discos membranosos',
  'fovea': 'Fóvea',
  'retinal blood vessels': 'Vasos sanguíneos da retina',

  /* ── Ouvido ── */
  'external ear': 'Orelha externa',
  'auricle': 'Aurícula',
  'external meatus': 'Meato acústico externo',
  'ceruminous glands': 'Glândulas ceruminosas',
  'tensor tympani': 'Músculo tensor do tímpano',
  'macula of utricle': 'Mácula do utrículo',
  'utricular macula': 'Mácula utricular',
  'ganglion of cn viii': 'Gânglio do nervo vestibulococlear',
  'helicotrema': 'Helicotrema',
  'spiral ganglia': 'Gânglios espirais',

  /* ── Respiratório ── */
  'pharynx': 'Faringe',
  'larynx': 'Laringe',
  'secondary bronchi': 'Brônquios secundários',
  'alveolar sac': 'Saco alveolar',
  'respiratory mucosa': 'Mucosa respiratória',
  'respiratory epithelium': 'Epitélio respiratório',
  'olfactory mucosa': 'Mucosa olfatória',
  "bowman's glands": 'Glândulas de Bowman',
  'vocal folds': 'Pregas vocais',
  'vocalis muscle': 'Músculo vocal',
  'vocal ligament': 'Ligamento vocal',
  'cartilage ring': 'Anel cartilaginoso',
  'club cells': 'Células clara (de Club)',
  'non-associated alveoli': 'Alvéolos não associados',
  'pulmonary arteries': 'Artérias pulmonares',
  'type i cells': 'Pneumócitos tipo I',
  'type ii cell': 'Pneumócito tipo II',
  'alveolar macrophage': 'Macrófago alveolar',
  'pulmonary capillaries': 'Capilares pulmonares',
  'alveolar (pulmonary) capillaries': 'Capilares alveolares (pulmonares)',
  'bronchiolar vessels': 'Vasos bronquiolares',
  'bronchial vein': 'Veia brônquica',
  'bronchial mucosa': 'Mucosa brônquica',
  'connective tissue layer': 'Camada de tecido conjuntivo',
  'pleural space': 'Cavidade pleural',
  'air spaces': 'Espaços aéreos',

  /* ── Endócrino ── */
  'neurohypophysis': 'Neuro-hipófise',
  'adenohypophysis': 'Adeno-hipófise',
  "remnants of rathke's pouch": 'Remanescentes da bolsa de Rathke',
  "cystic remnants of rathke's pouch": 'Remanescentes císticos da bolsa de Rathke',
  'inactive follicle cells': 'Células foliculares inativas',
  'zona glomerulosa': 'Zona glomerulosa',
  'chromaffin cells': 'Células cromafins',
  'corpus arenaceum': 'Corpo arenáceo (areia cerebral)',

  /* ── Boca, língua e dente ── */
  'labial glands': 'Glândulas labiais',
  'labial gland': 'Glândula labial',
  'labial glands in submucosa': 'Glândulas labiais na submucosa',
  'orbicularis oris (skeletal muscle)': 'Orbicular da boca (músculo esquelético)',
  'orbicularis oris muscle fibers': 'Fibras do músculo orbicular da boca',
  'vermilion zone': 'Zona do vermelhão',
  'vermilion border': 'Limite do vermelhão',
  'lip': 'Lábio',
  'mucosal epithelium': 'Epitélio da mucosa',
  'minor salivary glands': 'Glândulas salivares menores',
  'minor salivary gland': 'Glândula salivar menor',
  'gland ducts': 'Ductos glandulares',
  'papillary layer of lamina propria': 'Camada papilar da lâmina própria',
  'reticular layer of lamina propria': 'Camada reticular da lâmina própria',
  'muco-gingival junction': 'Junção mucogengival',
  'free gingiva': 'Gengiva livre',
  'attachment epithelium': 'Epitélio de inserção',
  'junctional epithelium': 'Epitélio juncional',
  'cementum and dentin': 'Cemento e dentina',
  'dorsum of the tongue': 'Dorso da língua',
  'ventral surface': 'Superfície ventral',
  'conical tips of papillae': 'Ápices cônicos das papilas',
  'fungiform papilla': 'Papila fungiforme',
  'connective tissue cores': 'Eixos de tecido conjuntivo',
  'neuroepithelial cells': 'Células neuroepiteliais',
  'masticatory epithelium': 'Epitélio mastigatório',
  'tongue': 'Língua',
  'palate': 'Palato',
  'nasal cavity': 'Cavidade nasal',
  'developing mandible': 'Mandíbula em desenvolvimento',
  'ectoderm': 'Ectoderma',
  'ectomesenchyme': 'Ectomesênquima',
  'developing alveolar bone': 'Osso alveolar em desenvolvimento',
  'dental papillae': 'Papilas dentárias',
  'successional lamina': 'Lâmina sucessional',
  'stratum intermedium': 'Estrato intermédio',
  'pre-odontoblasts': 'Pré-odontoblastos',
  'developing cusp': 'Cúspide em desenvolvimento',
  'pulp organ': 'Órgão pulpar',
  "tomes' processes": 'Processos de Tomes',
  "tomes' fibers": 'Fibras de Tomes',
  'hertwig’s epithelial root sheath': 'Bainha epitelial radicular de Hertwig',
  'bell stage': 'Estágio de campânula',
  'crown stage': 'Estágio de coroa',
  'anatomical crown': 'Coroa anatômica',
  'crown': 'Coroa',
  'root': 'Raiz',
  'roots': 'Raízes',
  'coronal pulp': 'Polpa coronária',
  'radicular pulp': 'Polpa radicular',
  'odontoblastic layer': 'Camada odontoblástica',
  'cell free zone (of weil)': 'Zona acelular (de Weil)',
  'cell rich zone': 'Zona rica em células',
  'contour lines of owen': 'Linhas de contorno de Owen',
  'dentino-enamel-cementum junction': 'Junção dentina-esmalte-cemento',
  'dentino-cementum junction': 'Junção dentina-cemento',
  'spongy supporting alveolar bone': 'Osso alveolar de suporte esponjoso',
  'cortical plate alveolar bone': 'Lâmina cortical do osso alveolar',
  'alveolar crest bone': 'Osso da crista alveolar',
  'alveolar crest': 'Crista alveolar',
  'aleolar crest': 'Crista alveolar',
  'alveolar crest principal fibers': 'Fibras principais da crista alveolar',
  'horizontal principal fibers': 'Fibras principais horizontais',
  'oblique principal fibers': 'Fibras principais oblíquas',
  'apical principal fibers': 'Fibras principais apicais',
  'dento-gingival group': 'Grupo dentogengival',
  'dento-periosteal group': 'Grupo dentoperiosteal',
  'alveolar-gingival group': 'Grupo alveologengival',
  'circumferential fibers': 'Fibras circunferenciais',
  'fiber groups': 'Grupos de fibras',
  'interradicular septum': 'Septo inter-radicular',
  'apex of the tooth': 'Ápice do dente',
  'interstitial space': 'Espaço intersticial',

  /* ── Glândulas salivares (detalhe) ── */
  'junction of acini with intercalated duct': 'Junção dos ácinos com o ducto intercalar',
  'basal striations': 'Estriações basais',
  'mucus tubules': 'Túbulos mucosos',
  'mucous tubule': 'Túbulo mucoso',
  'mucous granules': 'Grânulos mucosos',
  'serous cells': 'Células serosas',
  'serous acinus': 'Ácino seroso',
  'serous granules': 'Grânulos serosos',
  'wide lumen with mucus': 'Luz ampla com muco',
  'small lumen with serous product': 'Luz estreita com produto seroso',
  'gland cell nuclei': 'Núcleos de células glandulares',
  'location of mitochondria and granules': 'Localização das mitocôndrias e grânulos',
  'basal nuclei': 'Núcleos basais',

  /* ── Epitélio (detalhe) ── */
  'pseudostratified, columnar epithelium': 'Epitélio pseudoestratificado colunar',
  'lumen of the oviduct': 'Luz da tuba uterina',
  'luminal subdivisions': 'Subdivisões da luz',

  /* ── Genérico de corte e microscopia ── */
  'cortex': 'Córtex',
  'medulla': 'Medula',
  'acidophils': 'Acidófilas',
  'basophils (pituitary)': 'Basófilas',
  'pars nervosa': 'Pars nervosa',
  'pars intermedia': 'Pars intermedia',
  'electron microscopy': 'Microscopia eletrônica',
  'illustration': 'Ilustração',
  'orientation': 'Orientação',
}

/** Traduz um rótulo, ou devolve `null` quando não há entrada no glossário. */
export function traduzirTermo(original: string): string | null {
  const chave = original.trim().toLowerCase()
  return GLOSSARIO[chave] ?? null
}

/** Um rótulo nomeia estrutura, ou é crédito/navegação? */
export function classificarMarcador(original: string): 'estrutura' | 'credito' | 'navegacao' {
  return CLASSIFICACAO_DE_MARCADOR[original.trim().toLowerCase()] ?? 'estrutura'
}

/**
 * Colorações histológicas reconhecidas no texto de origem. A chave é o padrão
 * procurado (minúsculo, sem acento); o valor descreve a técnica em português.
 * Só entram colorações efetivamente presentes no acervo — nada de inventar uma
 * reação histoquímica que a lâmina não sofreu.
 */
export const COLORACOES: Array<{
  id: string
  nome: string
  padroes: string[]
  finalidade: string
  afinidade: string
  resultado: string
}> = [
  {
    id: 'he',
    nome: 'Hematoxilina e eosina (H&E)',
    padroes: ['h&e', 'hematoxylin and eosin', 'hematoxylin', 'eosin'],
    finalidade: 'Coloração de rotina; dá o contraste básico entre núcleo e citoplasma.',
    afinidade:
      'A hematoxilina é um corante básico e cora estruturas ácidas (basofilia): DNA nuclear, RNA ribossômico e matriz rica em glicosaminoglicanos. A eosina é ácida e cora estruturas básicas (acidofilia/eosinofilia): a maior parte das proteínas citoplasmáticas e do colágeno.',
    resultado: 'Núcleos em azul-violeta; citoplasma e matriz extracelular em rosa a vermelho.',
  },
  {
    id: 'pas',
    nome: 'PAS (ácido periódico–Schiff)',
    padroes: ['pas', 'periodic acid', 'periodic acid-schiff'],
    finalidade: 'Evidencia carboidratos: glicogênio, mucinas neutras e membranas basais.',
    afinidade:
      'O ácido periódico oxida os grupos 1,2-glicol dos açúcares a aldeídos, que reagem com o reativo de Schiff.',
    resultado: 'Magenta a púrpura onde há carboidrato; contracoloração nuclear com hematoxilina.',
  },
  {
    id: 'tricromico',
    nome: 'Tricrômico de Masson',
    padroes: ['masson', 'trichrome'],
    finalidade: 'Separa colágeno de músculo e citoplasma — base da avaliação de fibrose.',
    afinidade:
      'Corantes aniônicos de tamanhos diferentes competem pelos tecidos conforme a densidade e a permeabilidade da matriz.',
    resultado: 'Colágeno em azul ou verde; músculo e citoplasma em vermelho; núcleos em preto.',
  },
  {
    id: 'prata',
    nome: 'Impregnação argêntica',
    padroes: ['silver', 'reticulin', 'argyrophil'],
    finalidade: 'Revela fibras reticulares (colágeno III) e o arcabouço de órgãos parenquimatosos.',
    afinidade: 'Sais de prata precipitam sobre as fibras reticulares e são reduzidos a prata metálica.',
    resultado: 'Fibras reticulares em preto sobre fundo claro.',
  },
  {
    id: 'orceina',
    nome: 'Orceína / resorcina-fucsina',
    padroes: ['orcein', 'resorcin', 'elastic stain', 'verhoeff'],
    finalidade: 'Demonstra fibras elásticas em artérias, pulmão e cartilagem elástica.',
    afinidade: 'Ligação preferencial do corante à elastina.',
    resultado: 'Fibras elásticas em castanho-escuro a preto-arroxeado.',
  },
  {
    id: 'toluidina',
    nome: 'Azul de toluidina',
    padroes: ['toluidine'],
    finalidade: 'Cortes semifinos de resina e demonstração de metacromasia.',
    afinidade:
      'Corante básico que muda de cor ao se ligar a polianions muito concentrados — a metacromasia dos grânulos de mastócito e da matriz cartilaginosa.',
    resultado: 'Azul no geral; púrpura-avermelhado onde há metacromasia.',
  },
  {
    id: 'imuno',
    nome: 'Imuno-histoquímica',
    padroes: ['immunohistochem', 'immunofluorescence', 'antibody', 'immunostain'],
    finalidade: 'Localiza uma proteína específica com anticorpo.',
    afinidade: 'Ligação antígeno-anticorpo, revelada por enzima cromógena ou fluoróforo.',
    resultado: 'Marcação restrita ao antígeno-alvo; o restante recebe contracoloração.',
  },
]
