/**
 * Tradução editorial dos títulos de lâmina.
 *
 * O título é o cabeçalho da página — o primeiro texto que o aluno lê e o que
 * aparece na busca, na trilha e nos resultados. Deixá-lo em inglês enquanto o
 * resto da página está em português é a incoerência mais visível do módulo.
 *
 * Mesma regra do glossário de estruturas: **correspondência exata, sem
 * fallback**. Título ausente daqui permanece no original e recebe a marca de
 * pendência na interface. Traduzir aqui não promove nada a `publicado`.
 *
 * A chave é o título original em minúsculas, com espaços aparados.
 */

export const TITULOS: Record<string, string> = {
  /* ── Genéricos e estruturais ── */
  'overview': 'Visão geral',
  'general': 'Generalidades',
  'components': 'Componentes',
  'tunics': 'Túnicas',
  'regions': 'Regiões',
  'classification': 'Classificação',
  'diagnostic features': 'Características diagnósticas',
  'cells': 'Células',
  'tissues': 'Tecidos',
  'organs': 'Órgãos',
  'fibers': 'Fibras',
  'glands': 'Glândulas',
  'receptors': 'Receptores',
  'terminals': 'Terminações',
  'simple': 'Simples',
  'loose': 'Frouxo',
  'dense irregular': 'Denso não modelado',
  'dense regular': 'Denso modelado',
  'hyaline': 'Hialina',
  'endocrine': 'Endócrina',
  'lumen': 'Luz',
  'polarity': 'Polaridade',
  'medulla': 'Medula',
  'stroma and parenchyma': 'Estroma e parênquima',
  'cortex and medullla': 'Córtex e medula',
  'basic tissues in organs': 'Os tecidos básicos nos órgãos',
  'associated structures': 'Estruturas associadas',
  'blood supply': 'Irrigação sanguínea',
  'secretory units': 'Unidades secretoras',
  'muscle types': 'Tipos de músculo',
  'cell cycle': 'Ciclo celular',
  'blood': 'Sangue',

  /* ── Colorações ── */
  'stains': 'Colorações',
  'stains 01': 'Colorações',
  'hematoxylin and esosin (h&e) staining': 'Coloração por hematoxilina e eosina (H&E)',
  'metal stains for electron microscopy (em)': 'Contrastes metálicos para microscopia eletrônica',
  'toluidine blue': 'Azul de toluidina',
  'osmium': 'Tetróxido de ósmio',
  'periodic acid-schiff (pas) stain': 'Coloração pelo ácido periódico-Schiff (PAS)',
  'cresyl violet-luxol fast blue': 'Violeta de cresila com Luxol fast blue',
  "masson's trichrome": 'Tricrômico de Masson',
  "movat's pentachrome stain": 'Pentacrômico de Movat',
  "elastin stain (verhoeff's-van gieson)": 'Coloração para elastina (Verhoeff–van Gieson)',
  'silver stain': 'Impregnação argêntica',

  /* ── Célula ── */
  'nucleus': 'Núcleo',
  'nucleolus': 'Nucléolo',
  'chromatin': 'Cromatina',
  'nuclear envelope': 'Envoltório nuclear',
  'nuclear pores': 'Poros nucleares',
  'mitochondria': 'Mitocôndrias',
  'lysosomes': 'Lisossomos',
  'golgi apparatus': 'Complexo de Golgi',
  'rough endoplasmic reticulum': 'Retículo endoplasmático rugoso',
  'smooth endoplasmic reticulum': 'Retículo endoplasmático liso',
  'rough endoplasmic reticulum and polysomes': 'Retículo endoplasmático rugoso e polissomos',
  'nissl substance': 'Substância de Nissl',
  'secretory granules': 'Grânulos de secreção',
  'glycogen': 'Glicogênio',
  'lipid droplets': 'Gotículas lipídicas',
  'centrioles': 'Centríolos',
  'cytoskeleton': 'Citoesqueleto',
  'microfilaments': 'Microfilamentos',
  'intermediate filaments': 'Filamentos intermediários',
  'intermediate filaments and microtubules': 'Filamentos intermediários e microtúbulos',
  'microvilli': 'Microvilosidades',
  'cilia': 'Cílios',
  'stereocilia': 'Estereocílios',
  'desmosomes': 'Desmossomos',
  'junctional complex': 'Complexo juncional',
  'membranes': 'Membranas',
  'basal lamina': 'Lâmina basal',
  'basement membrane': 'Membrana basal',
  'overview of cell structures': 'Visão geral das estruturas celulares',
  'cell shapes: squamous': 'Formas celulares: pavimentosa',
  'cell shapes: spherical': 'Formas celulares: esférica',

  /* ── Divisão celular ── */
  'mitosis': 'Mitose',
  'meiosis': 'Meiose',
  'interphase': 'Intérfase',
  'prophase': 'Prófase',
  'metaphase': 'Metáfase',
  'anaphase': 'Anáfase',
  'telophase': 'Telófase',
  'late telophase and cytokinesis': 'Telófase tardia e citocinese',
  'gametogenesis': 'Gametogênese',

  /* ── Epitélios ── */
  'simple squamous epithelium': 'Epitélio simples pavimentoso',
  'simple cuboidal epithelium': 'Epitélio simples cúbico',
  'simple columnar epithelium': 'Epitélio simples colunar',
  'pseudostratified columnar epithelium': 'Epitélio pseudoestratificado colunar',
  'stratified squamous, nonkeratinized (moist) epithelium':
    'Epitélio estratificado pavimentoso não queratinizado',
  'stratified squamous, keratinized (dry) epithelium':
    'Epitélio estratificado pavimentoso queratinizado',
  'mucosal membrane': 'Membrana mucosa',

  /* ── Glândulas ── */
  'overview of exocrine glands': 'Visão geral das glândulas exócrinas',
  'structure of compound glands': 'Estrutura das glândulas compostas',
  'unicellular gland': 'Glândula unicelular',
  'sheet gland': 'Glândula em lençol',
  'simple tubular gland': 'Glândula tubular simples',
  'simple, coiled tubular gland': 'Glândula tubular simples enovelada',
  'simple, branched tubular gland': 'Glândula tubular simples ramificada',
  'simple, branched acinar gland': 'Glândula acinosa simples ramificada',
  'compound acinar gland': 'Glândula acinosa composta',
  'compound tubuloacinar gland': 'Glândula tubuloacinosa composta',

  /* ── Conjuntivo ── */
  'connective tissue proper': 'Tecido conjuntivo propriamente dito',
  'connective tissue proper overview': 'Visão geral do tecido conjuntivo propriamente dito',
  'overview of connective tissue proper': 'Visão geral do tecido conjuntivo propriamente dito',
  'connective tissue proper classification overview':
    'Visão geral da classificação do tecido conjuntivo propriamente dito',
  'connective tissue cells': 'Células do tecido conjuntivo',
  'loose connective tissue': 'Tecido conjuntivo frouxo',
  'dense irregular connective tissue': 'Tecido conjuntivo denso não modelado',
  'dense regular connective tissue': 'Tecido conjuntivo denso modelado',
  'reticular connective tissue': 'Tecido conjuntivo reticular',
  'mucous connective tissue': 'Tecido conjuntivo mucoso',
  'white adipose connective tissue': 'Tecido adiposo branco',
  'brown adipose connective tissue': 'Tecido adiposo pardo',
  'collagen fibers': 'Fibras colágenas',
  'collagen fibrils': 'Fibrilas colágenas',
  'collagen fibrils and fibers': 'Fibrilas e fibras colágenas',
  'elastic fibers': 'Fibras elásticas',
  'elastic membrane': 'Membrana elástica',
  'elastic laminae': 'Lâminas elásticas',
  'elastic and collagen fibers': 'Fibras elásticas e colágenas',
  'reticular fibers': 'Fibras reticulares',
  'fibroblasts': 'Fibroblastos',
  'active fibroblast': 'Fibroblasto ativo',
  'inactive fibroblast': 'Fibroblasto inativo',
  'adipocyte': 'Adipócito',
  'mast cell': 'Mastócito',
  'plasma cell': 'Plasmócito',
  'macrophage': 'Macrófago',
  'macrophage and mast cell': 'Macrófago e mastócito',
  'lymphocyte': 'Linfócito',
  'neutrophil': 'Neutrófilo',
  'eosinophil': 'Eosinófilo',
  'blood: neutrophil': 'Sangue: neutrófilo',
  'blood: lymphocyte': 'Sangue: linfócito',
  'hemopoiesis': 'Hemopoiese',
  'bone marrow: adult': 'Medula óssea do adulto',

  /* ── Cartilagem e osso ── */
  'overview of cartilage': 'Visão geral da cartilagem',
  'hyaline cartilage': 'Cartilagem hialina',
  'elastic cartilage': 'Cartilagem elástica',
  'fibrocartilage': 'Fibrocartilagem',
  'regressing cartilage': 'Cartilagem em regressão',
  'bone matrix': 'Matriz óssea',
  'bone cells: osteoblasts': 'Células ósseas: osteoblastos',
  'bone cells: osteoclasts': 'Células ósseas: osteoclastos',
  'bone: deposition': 'Osso: deposição',
  'bone: resorption': 'Osso: reabsorção',
  'bone remodeling': 'Remodelação óssea',
  'bone matrix: remodeling (compact bone)': 'Matriz óssea: remodelação do osso compacto',
  'bone matrix: remodeling (spongy bone)': 'Matriz óssea: remodelação do osso esponjoso',
  'bone: interstitial lamellae': 'Osso: lamelas intersticiais',
  "bone: volkmann's canal": 'Osso: canal de Volkmann',
  'bone: intramembranous formation': 'Osso: ossificação intramembranosa',
  'bone: endochondral ossification': 'Osso: ossificação endocondral',
  'endochondral ossification': 'Ossificação endocondral',

  /* ── Músculo ── */
  'skeletal muscle': 'Músculo esquelético',
  'cardiac muscle': 'Músculo cardíaco',
  'smooth muscle': 'Músculo liso',
  'myocardium': 'Miocárdio',
  'purkinje fibers': 'Fibras de Purkinje',

  /* ── Nervoso ── */
  'neurons': 'Neurônios',
  'multipolar neuron': 'Neurônio multipolar',
  'bipolar neuron': 'Neurônio bipolar',
  'pseudounipolar neuron': 'Neurônio pseudounipolar',
  'astrocytes': 'Astrócitos',
  'oligodendrocytes': 'Oligodendrócitos',
  'schwann cell': 'Célula de Schwann',
  'schwann cells': 'Células de Schwann',
  'peripheral nerve': 'Nervo periférico',
  'peripheral nerve: investments': 'Nervo periférico: envoltórios',
  'spinal cord': 'Medula espinal',
  'meninges': 'Meninges',
  "meissner's corpuscle": 'Corpúsculo de Meissner',
  'pacinian corpuscle': 'Corpúsculo de Pacini',

  /* ── Vasos e coração ── */
  'arteries vs veins': 'Artérias × veias',
  'elastic artery': 'Artéria elástica',
  'medium (muscular) artery': 'Artéria muscular de médio calibre',
  'small artery': 'Artéria de pequeno calibre',
  'arteriole': 'Arteríola',
  'venule': 'Vênula',
  'high endothelial venules': 'Vênulas de endotélio alto',
  'veins': 'Veias',
  'medium vein': 'Veia de médio calibre',
  'small vein': 'Veia de pequeno calibre',
  'large vein (vena cava)': 'Veia de grande calibre (veia cava)',
  'continuous capillary': 'Capilar contínuo',
  'fenestrated capillaries': 'Capilares fenestrados',
  'sinusoid': 'Sinusoide',
  'heart': 'Coração',
  'interventricular septum': 'Septo interventricular',
  'semilunar valve': 'Valva semilunar',

  /* ── Urinário ── */
  'nephron': 'Néfron',
  'renal corpuscle': 'Corpúsculo renal',
  'glomerulus': 'Glomérulo',
  'cortex: convoluted portion': 'Córtex: porção contorcida',
  'cortex: juxtaglomerular apparatus': 'Córtex: aparelho justaglomerular',
  'cortex: medullary ray': 'Córtex: raio medular',
  'renal papilla': 'Papila renal',
  'excretory passageways': 'Vias excretoras',
  'ureter': 'Ureter',
  'urinary bladder': 'Bexiga urinária',

  /* ── Linfoide ── */
  'diffuse lymphoid tissue': 'Tecido linfoide difuso',
  'primary lymphoid nodule': 'Nódulo linfoide primário',
  'secondary lymphoid nodule': 'Nódulo linfoide secundário',
  'germinal center': 'Centro germinativo',
  'aggregated lymphoid nodules: tonsils': 'Nódulos linfoides agregados: tonsilas',
  'lymph node': 'Linfonodo',
  'lymph node: cortex': 'Linfonodo: córtex',
  'spleen': 'Baço',
  'spleen: white pulp': 'Baço: polpa branca',
  'spleen: red pulp': 'Baço: polpa vermelha',
  'thymus': 'Timo',
  'thymus: cortex': 'Timo: córtex',

  /* ── Endócrino ── */
  'pituitary': 'Hipófise',
  'pars distalis': 'Pars distalis',
  'pars intermedia': 'Pars intermedia',
  'pars nervosa': 'Pars nervosa',
  'thyroid gland': 'Glândula tireoide',
  'parathyroid gland': 'Glândula paratireoide',
  'adrenal gland': 'Glândula suprarrenal',
  'adrenal cortex': 'Córtex da suprarrenal',
  'pineal gland': 'Glândula pineal',
  'individual endocrine cells': 'Células endócrinas isoladas',
  'clusters of endocrine cells': 'Agrupamentos de células endócrinas',

  /* ── Respiratório ── */
  'respiratory': 'Sistema respiratório',
  'nasal cavities: mucosae': 'Cavidades nasais: mucosas',
  'nasal cavities: olfactory epithelium': 'Cavidades nasais: epitélio olfatório',
  'larynx': 'Laringe',
  'trachea': 'Traqueia',
  'trachea and primary bronchus': 'Traqueia e brônquio principal',
  'bronchus': 'Brônquio',
  'bronchiole': 'Bronquíolo',
  'terminal bronchiole': 'Bronquíolo terminal',
  'respiratory bronchiole': 'Bronquíolo respiratório',
  'alveolar duct': 'Ducto alveolar',
  'alveolar ducts': 'Ductos alveolares',
  'alveolus': 'Alvéolo',
  'interalveolar septum': 'Septo interalveolar',
  'alveolar macrophage': 'Macrófago alveolar',
  'pulmonary artery': 'Artéria pulmonar',
  'pulmonary vein': 'Veia pulmonar',
  'pulmonary capillaries': 'Capilares pulmonares',
  'bronchial blood vessels': 'Vasos sanguíneos brônquicos',
  'pleura': 'Pleura',

  /* ── Digestório ── */
  'digestive': 'Sistema digestório',
  'tubular digestive system': 'Sistema digestório tubular',
  'overview of the tubular digestive system': 'Visão geral do sistema digestório tubular',
  'esophagus': 'Esôfago',
  'esophagus: epithelium': 'Esôfago: epitélio',
  'esophagus: mucosa': 'Esôfago: mucosa',
  'esophagus: muscularis externa': 'Esôfago: muscular externa',
  'esophagogastric junction': 'Junção esofagogástrica',
  'stomach': 'Estômago',
  'overview of the stomach': 'Visão geral do estômago',
  'stomach: fundus and body': 'Estômago: fundo e corpo',
  'stomach: fundus and pylorus': 'Estômago: fundo e piloro',
  'stomach: cardiac region': 'Estômago: região cárdica',
  'stomach: pylorus': 'Estômago: piloro',
  'gastro-duodenal junction': 'Junção gastroduodenal',
  'overview: surface epithelium': 'Visão geral: epitélio de superfície',
  'overview: gastric mucosa': 'Visão geral: mucosa gástrica',
  'overview: mucosal innervation': 'Visão geral: inervação da mucosa',
  'overview: muscularis externa': 'Visão geral: muscular externa',
  'overview: innervation': 'Visão geral: inervação',
  'small intestine': 'Intestino delgado',
  'large intestine': 'Intestino grosso',
  'large intestine and anus': 'Intestino grosso e ânus',
  'mucosa: villi': 'Mucosa: vilosidades',
  'mucosa: epithelium': 'Mucosa: epitélio',
  'mucosa: intestinal glands': 'Mucosa: glândulas intestinais',
  'mucosa: malt': 'Mucosa: tecido linfoide associado (MALT)',
  'mucosa: lacteals': 'Mucosa: vasos quilíferos',
  'submucosa': 'Submucosa',
  "submucosa: brunner's glands": 'Submucosa: glândulas de Brunner',
  'submucosa: submucosal plexus': 'Submucosa: plexo submucoso',
  'muscularis externa': 'Muscular externa',
  'muscularis externa: myenteric plexus': 'Muscular externa: plexo mientérico',
  'serosa': 'Serosa',
  'appendix': 'Apêndice vermiforme',
  'recto-anal junction': 'Junção retoanal',
  'recto-anal junctions': 'Junções retoanais',
  'anus': 'Ânus',
  'liver': 'Fígado',
  'liver: sinusoids': 'Fígado: sinusoides',
  'liver: portal canals': 'Fígado: espaços porta',
  'liver: central veins': 'Fígado: veias centrolobulares',
  'liver: central vein': 'Fígado: veia centrolobular',
  'liver: hepatocytes': 'Fígado: hepatócitos',
  'liver: hepatocyte': 'Fígado: hepatócito',
  'gall bladder': 'Vesícula biliar',
  'gall bladder: epithelium': 'Vesícula biliar: epitélio',
  'gall bladder: mucosa': 'Vesícula biliar: mucosa',
  'gall bladder: muscularis externa': 'Vesícula biliar: muscular externa',
  'pancreas': 'Pâncreas',
  'major glands': 'Glândulas anexas',

  /* ── Boca, língua e dente ── */
  'oral cavity': 'Cavidade oral',
  'developing oral cavity': 'Cavidade oral em desenvolvimento',
  'oral mucosa': 'Mucosa oral',
  'oral mucosa: lining': 'Mucosa oral: de revestimento',
  'oral mucosa: gingiva': 'Mucosa oral: gengiva',
  'lip': 'Lábio',
  'lip: mucosal surface': 'Lábio: superfície mucosa',
  'lip: vermilion zone': 'Lábio: zona do vermelhão',
  'lip: comparison of epithelia': 'Lábio: comparação entre epitélios',
  'tongue': 'Língua',
  'tongue: filiform papillae': 'Língua: papilas filiformes',
  'tongue: fungiform papillae': 'Língua: papilas fungiformes',
  'tongue: filiform and fungiform papillae': 'Língua: papilas filiformes e fungiformes',
  'tongue: circumvallate papillae': 'Língua: papilas circunvaladas',
  'tongue: taste buds': 'Língua: botões gustativos',
  'tongue: musculature': 'Língua: musculatura',
  'salivary glands': 'Glândulas salivares',
  'major salivary glands': 'Glândulas salivares maiores',
  'parotid gland': 'Glândula parótida',
  'submandibular gland': 'Glândula submandibular',
  'sublingual gland': 'Glândula sublingual',
  'tooth': 'Dente',
  'tooth and dental alveolus': 'Dente e alvéolo dentário',
  'molar and dental alveolus': 'Molar e alvéolo dentário',
  'dental pulp': 'Polpa dentária',
  'periodondium': 'Periodonto',
  'tooth peridontium': 'Periodonto do dente',
  'tooth apex and periodontium': 'Ápice do dente e periodonto',
  'periodontal ligament principal fiber groups':
    'Grupos de fibras principais do ligamento periodontal',
  'gingival fibers of the periodontal ligament': 'Fibras gengivais do ligamento periodontal',
  'dentogingival junction': 'Junção dentogengival',
  'stages of tooth development': 'Estágios do desenvolvimento dentário',
  'laminae, bud and cap stages': 'Lâminas e estágios de broto e capuz',
  'bud stage of tooth development': 'Estágio de broto',
  'cap stage of tooth development': 'Estágio de capuz',
  'cap stage of tooth development (early)': 'Estágio de capuz (inicial)',
  'bell stage of tooth development': 'Estágio de campânula',
  'late bell stage of tooth development': 'Estágio de campânula tardio',
  'crown stage of tooth development': 'Estágio de coroa',
  'root stage of tooth development': 'Estágio de raiz',
  'root stage of tooth development - crown region': 'Estágio de raiz — região da coroa',
  'root stage of tooth development - neck region': 'Estágio de raiz — região do colo',
  'root stage of tooth development - apex': 'Estágio de raiz — ápice',

  /* ── Pele ── */
  'skin overview': 'Visão geral da pele',
  'epidermis': 'Epiderme',
  'dermis': 'Derme',
  'stratum basale': 'Estrato basal',
  'stratum basale: melanocytes': 'Estrato basal: melanócitos',
  'stratum spinosum': 'Estrato espinhoso',
  'stratum granulosum': 'Estrato granuloso',
  'eccrine sweat gland': 'Glândula sudorípara écrina',
  'apocrine sweat gland': 'Glândula sudorípara apócrina',
  'sebaceous gland': 'Glândula sebácea',

  /* ── Reprodutor ── */
  'testis overview': 'Visão geral do testículo',
  'testis proper: endocrine portion': 'Testículo: porção endócrina',
  'seminiferous tubules - convoluted portion': 'Túbulos seminíferos — porção contorcida',
  'intratesticular ducts': 'Ductos intratesticulares',
  'epididymis': 'Epidídimo',
  'epididymis: head': 'Epidídimo: cabeça',
  'epididymis: body and tail': 'Epidídimo: corpo e cauda',
  'spermatic cord': 'Funículo espermático',
  'seminal vesicle': 'Glândula seminal',
  'prostate': 'Próstata',
  'penis': 'Pênis',
  'ovary': 'Ovário',
  'ovary: secondary follicle': 'Ovário: folículo secundário',
  'ovary: corpus luteum': 'Ovário: corpo lúteo',
  'oviduct': 'Tuba uterina',
  'oviduct: ampulla': 'Tuba uterina: ampola',
  'uterus': 'Útero',
  'uterus: proliferative phase (days 6-14)': 'Útero: fase proliferativa (dias 6–14)',
  'uterus: secretory phase (days 14-26)': 'Útero: fase secretora (dias 14–26)',
  'uterus: pre-menstrual phase (days 26-28)': 'Útero: fase pré-menstrual (dias 26–28)',
  'uterus: menstrual phase (days 1-5)': 'Útero: fase menstrual (dias 1–5)',
  'uterus: cervix': 'Útero: colo',
  'vagina': 'Vagina',
  'placenta: 1st trimester': 'Placenta: 1º trimestre',
  'placenta: 3rd trimester': 'Placenta: 3º trimestre',
  'breast: inactive': 'Mama: inativa',
  'breast: pregnancy': 'Mama: na gestação',
  'breast: lactation': 'Mama: na lactação',

  /* ── Olho ── */
  'globe': 'Bulbo do olho',
  'globe: cornea': 'Bulbo do olho: córnea',
  'globe: limbus': 'Bulbo do olho: limbo',
  'globe: sclera': 'Bulbo do olho: esclera',
  'globe: ciliary body': 'Bulbo do olho: corpo ciliar',
  'globe: iris': 'Bulbo do olho: íris',
  'globe: choroid': 'Bulbo do olho: coroide',
  'globe: lens': 'Bulbo do olho: cristalino',
  'retina': 'Retina',
  'sensory retina': 'Retina sensorial',
  'eyelid': 'Pálpebra',

  /* ── Ouvido ── */
  'external ear: external auditory meatus': 'Orelha externa: meato acústico externo',
  'middle ear': 'Orelha média',
  'vestibule': 'Vestíbulo',
  'semicircular canals': 'Canais semicirculares',
  'vestibular macula': 'Mácula vestibular',
  'cochlea': 'Cóclea',
  'cochlear duct': 'Ducto coclear',
  'cochlea: innervation': 'Cóclea: inervação',
}

/** Traduz um título de lâmina, ou devolve `null` quando não há entrada. */
export function traduzirTitulo(original: string): string | null {
  return TITULOS[original.trim().toLowerCase()] ?? null
}
