export const AFYA_UNITS = [
  'Afya Abaetetuba - Abaetetuba (PA)',
  'Afya Araguaína - Araguaína (TO)',
  'Afya Barreiras - Barreiras (BA)',
  'Afya Bragança - Bragança (PA)',
  'Afya Contagem - Contagem (MG)',
  'Afya Cruzeiro do Sul - Cruzeiro do Sul (AC)',
  'Afya Garanhuns - Garanhuns (PE)',
  'Afya Guanambi - Guanambi (BA)',
  'Afya Ipatinga - Ipatinga (MG)',
  'Afya Itabuna - Itabuna (BA)',
  'Afya Itacoatiara - Itacoatiara (AM)',
  'Afya Itajubá - Itajubá (MG)',
  'Afya Itaperuna - Itaperuna (RJ)',
  'Afya Jaboatão - Jaboatão dos Guararapes (PE)',
  'Afya Ji-Paraná - Ji-Paraná (RO)',
  'Afya Luís Eduardo Magalhães - Luís Eduardo Magalhães (BA)',
  'Afya Maceió - Maceió (AL)',
  'Afya Manacapuru - Manacapuru (AM)',
  'Afya Marabá - Marabá (PA)',
  'Afya Montes Claros - Montes Claros (MG)',
  'Afya Palmas - Palmas (TO)',
  'Afya Paraíba - Paraíba (PB)',
  'Afya Parnaíba - Parnaíba (PI)',
  'Afya Pato Branco - Pato Branco (PR)',
  'Afya Porto Nacional - Porto Nacional (TO)',
  'Afya Porto Velho - Porto Velho (RO)',
  'Afya Redenção - Redenção (PA)',
  'Afya Salvador - Salvador (BA)',
  'Afya Santa Inês - Santa Inês (MA)',
  'Afya São João del-Rei - São João del-Rei (MG)',
  'Afya Unigranrio Barra da Tijuca - Rio de Janeiro (RJ)',
  'Afya Unigranrio Duque de Caxias - Duque de Caxias (RJ)',
  'Afya UNINOVAFAPI - Teresina (PI)',
  'Afya UNIVAÇO - Governador Valadares (MG)',
  'Não encontro minha unidade aqui',
]
