export const INSTITUTION_UNITS = [
  'Unigranrio Barra da Tijuca - Rio de Janeiro (RJ)',
  'Unigranrio Duque de Caxias - Duque de Caxias (RJ)',
  'Abaetetuba - Abaetetuba (PA)',
  'Araguaína - Araguaína (TO)',
  'Barreiras - Barreiras (BA)',
  'Bragança - Bragança (PA)',
  'Contagem - Contagem (MG)',
  'Cruzeiro do Sul - Cruzeiro do Sul (AC)',
  'Garanhuns - Garanhuns (PE)',
  'Guanambi - Guanambi (BA)',
  'Ipatinga - Ipatinga (MG)',
  'Itabuna - Itabuna (BA)',
  'Itacoatiara - Itacoatiara (AM)',
  'Itajubá - Itajubá (MG)',
  'Itaperuna - Itaperuna (RJ)',
  'Jaboatão - Jaboatão dos Guararapes (PE)',
  'Ji-Paraná - Ji-Paraná (RO)',
  'Luís Eduardo Magalhães - Luís Eduardo Magalhães (BA)',
  'Maceió - Maceió (AL)',
  'Manacapuru - Manacapuru (AM)',
  'Marabá - Marabá (PA)',
  'Montes Claros - Montes Claros (MG)',
  'Palmas - Palmas (TO)',
  'Paraíba - Paraíba (PB)',
  'Parnaíba - Parnaíba (PI)',
  'Pato Branco - Pato Branco (PR)',
  'Porto Nacional - Porto Nacional (TO)',
  'Porto Velho - Porto Velho (RO)',
  'Redenção - Redenção (PA)',
  'Salvador - Salvador (BA)',
  'Santa Inês - Santa Inês (MA)',
  'São João del-Rei - São João del-Rei (MG)',
  'UNINOVAFAPI - Teresina (PI)',
  'UNIVAÇO - Governador Valadares (MG)',
  'Não encontro minha unidade aqui',
]
