// Escolas médicas (cursos de graduação em Medicina) do Brasil, agrupadas por
// estado (UF). Base: portal Escolas Médicas do Brasil (escolasmedicas.com.br),
// que espelha o cadastro do e-MEC — 385 cursos ativos, consultados em jul/2026.
//
// O rótulo segue o padrão "Nome da instituição (SIGLA) - Cidade". Cada estado
// ganha, na hora de exibir, uma opção de fallback (`OTHER_SCHOOL_OPTION`) para
// quem cursa numa escola recém-aberta ou fora do país: a UI troca o select por
// um campo de texto livre, então nunca perdemos o dado.
import { getAfyaUnitsByState } from '@/lib/institution-units'

export const MEDICAL_SCHOOLS_BY_STATE: Record<string, string[]> = {
  AC: [
    'Centro Universitário Uninorte - Rio Branco',
    'ITPAC Cruzeiro do Sul',
    'Universidade Federal do Acre (UFAC) - Rio Branco',
  ],
  AL: [
    'Centro Universitário Cesmac - Maceio',
    'CENTRO UNIVERSITÁRIO DE MACEIÓ (UNIMA)',
    'Universidade Estadual de Ciências da Saúde de Alagoas (UNCISAL) - Maceio',
    'Universidade Federal de Alagoas (UFAL) - Maceio',
    'Universidade Federal de Alagoas (UFAL/Arapiraca) - Arapiraca',
  ],
  AP: [
    'Faculdade Integrado de Macapá',
    'Universidade Federal do Amapá (UNIFAP) - Macapá',
  ],
  AM: [
    'Afya Faculdade de Ciências Médicas de Itacoatiara (AFYA ITACOATIARA)',
    'Afya Faculdade de Ciências Médicas de Manacapuru (AFYA MANACAPURU)',
    'Centro Universitário CEUNI-FAMETRO - Manaus',
    'Universidade do Estado do Amazonas (UEA) - Manaus',
    'Universidade Federal do Amazonas (UFAM) - Manaus',
    'Universidade Federal do Amazonas - campus Coari (UFAM/Coari)',
    'Universidade Nilton Lins (UNINILTONLINS) - Manaus',
  ],
  BA: [
    'AFYA FACULDADE DE CIÊNCIAS MÉDICAS DE ITABUNA (AFYA ITABUNA)',
    'Centro Universitário AGES (UniAGES) - Paripiranga',
    'Centro Universitário Dom Pedro II (UNIDOMPEDRO) - Salvador',
    'Centro Universitário Nobre de Feira de Santana (UNIFAN)',
    'Centro Universitário UniFG - Guanambi',
    'Escola Bahiana de Medicina e Saúde Pública (EBMSP) - Salvador',
    'Faculdade AGES de Medicina (FAM) - Jacobina',
    'Faculdade AGES de Medicina de Irecê',
    'Faculdade de Medicina Pitágoras de Eunápolis (Pitágoras/Eunápolis)',
    'Faculdade de Saúde Santo Agostinho de Vitoria da Conquista (FASA)',
    'Faculdade de Tecnologia e Ciências-Salvador (FTC)',
    'Faculdade Estácio de Alagoinhas (Estácio/Alagoinhas)',
    'Faculdade Estácio de Juazeiro (Estácio/Juazeiro) - Juazeiro do Norte',
    'Faculdades Integradas Padrão (FIP Guanambi) - Guanambi',
    'Faculdades Sulamérica Bahia - Luís Eduardo Magalhães',
    'Fundação Universidade Federal do Vale do São Francisco (UFVSF) - Paulo Afonso',
    'Unime Lauro de Freitas',
    'Universidade do Estado da Bahia - Cabula/Salvador (UNEB/Cabula)',
    'Universidade Estadual de Feira de Santana (UEFS)',
    'Universidade Estadual de Santa Cruz (UESC) - Ilhéus',
    'Universidade Estadual do Sudoeste da Bahia (UESB) - Jequié',
    'Universidade Estadual do Sudoeste da Bahia-Vitória da Conquista (UESB)',
    'Universidade Federal da Bahia (UFBA) - Salvador',
    'Universidade Federal da Bahia - campus Anísio Teixeira (CAT) - Vitoria da Conquista',
    'Universidade Federal do Oeste da Bahia (UFOB/Barreiras) - Barreiras',
    'Universidade Federal do Recôncavo da Bahia - (BA) (UFRB) - Santo Antonio de Jesus',
    'Universidade Federal do Sul da Bahia (UFSBA/Teixeira de Freitas) - Teixeira de Freitas',
    'Universidade Salvador (UNIFACS)',
  ],
  CE: [
    'Centro Universitário INTA-UNINTA - Sobral',
    'Centro Universitário Unichristus - Fortaleza',
    'Faculdade 05 de Julho-5 (F5) - Sobral',
    'Faculdade de Medicina Estácio de Juazeiro do Norte ESTÁCIO FMJ',
    'Faculdade Uninta Fortaleza',
    'Faculdade Via Sapiens (FVS) - Tianguá',
    'Universidade de Fortaleza (UNIFOR)',
    'Universidade Estadual do Ceará (UECE) - Fortaleza',
    'Universidade Federal do Cariri - Campus de Barbalha (UFCA/Barbalha)',
    'Universidade Federal do Ceará (UFC) - Fortaleza',
    'Universidade Federal do Ceará - Campus de Sobral (UFC/Sobral)',
    'Universidade Regional do Cariri (URCA) - Crato',
  ],
  DF: [
    'Centro Universitário de Brasília (UNICEUB)',
    'Centro Universitário do Planalto Central Apparecido dos Santos  UNICEPLAC - Brasília',
    'Centro Universitário-Instituto Euro Americano de Educação Ciência Tecnologia SCES (SCES/UNINEURO) - Brasília',
    'Escola Superior de Ciências da Saúde (ESCS) - Brasília',
    'Universidade Católica de Brasília (UCB)',
    'Universidade de Brasília (UnB)',
  ],
  ES: [
    'Centro Universitário do Espirito Santo (UNESC) - Colatina',
    'Escola Superior de Ciências da Santa Casa de Misericórdia de Vitória (EMESCAM)',
    'Faculdade Brasileira (MULTIVIX VITORIA) - Vitória',
    'Faculdade Multivix Cachoeiro de Itapemirim',
    'Universidade Federal do Espírito Santo (UFES) - Vitória',
    'Universidade Vila Velha (UVV)',
  ],
  GO: [
    'Centro de Ensino Superior Morgana Potrich Eireli (FAMP) - Mineiros',
    'Centro Universitário de Anápolis (UniEVANGELICA)',
    'Centro Universitário de Goiatuba (UNICERRADO)',
    'Centro Universitário de Mineiros (UNIFIMES)',
    'Centro Universitário de Mineiros (UNIFIMES/Trindade/GO) - Trindade',
    'Faculdade Alfredo Nasser (UNIFAN) - Aparecida de Goiania',
    'Pontifícia Universidade Católica de Goiás (PUC/GO) - Goiania',
    'Universidade de Rio Verde (UniRV)',
    'Universidade de Rio Verde (UniRV) - Aparecida de Goiania',
    'Universidade de Rio Verde (UNIRV/FORMOSA) - Formosa',
    'Universidade de Rio Verde (UniRV/Goianésia) - Goianésia',
    'Universidade Estadual de Goiás/campus Itumbiara (UEG/Itumbiara)',
    'Universidade Federal de Goiás (UFG) - Goiania',
    'Universidade Federal de Goias - Campus de Catalão - UFG-UC (UFG/Catalão)',
    'Universidade Federal de Goiás - Jataí/Go (UFG/Jataí)',
  ],
  MA: [
    'Centro Universitário Unidade de Ensino Superior Dom Bosco (UNDB) - São Luís',
    'Faculdade Pitágoras - Codó (Pitágoras/Maranhão) - São Sebastião, Codó',
    'Universidade Ceuma (UNICEUMA/Imperatriz) - Imperatriz',
    'Universidade do Ceuma-UNICEUMA - São Luis',
    'Universidade Estadual do Maranhão (UEMA) - Caxias',
    'Universidade Federal do Maranhão (UFMA/Imperatriz) - Imperatriz',
    'Universidade Federal do Maranhão (UFMA/Pinheiro) - Pinheiro',
    'Universidade Federal do Maranhão - São Luis (UFMA) - São Luiz',
  ],
  MT: [
    'Centro Universitário de Várzea Grande (UNIVAG)',
    'Centro Universitário do Vale do Araguaia (UNIVAR) - Barra do Garças',
    'Faculdade Estácio do Pantanal (FAPAN) - Cáceres',
    'Universidade de Cuiabá (UNIC)',
    'Universidade do Estado de Mato Grosso (UNEMAT) - Cáceres',
    'Universidade Federal de Mato Grosso (UFMT) - Cuiaba',
    'Universidade Federal do Mato Grosso (UFMT/Sinop)) - Sinop',
    'Universidade Federal do Mato Grosso-UFMT - Rondonópolis (MT)',
  ],
  MS: [
    'Universidade Anhanguera-Uniderp - Campo Grande',
    'Universidade Estadual de Mato Grosso do Sul (UEMS) - Campo Grande',
    'Universidade Federal da Grande Dourados (UFGD)',
    'Universidade Federal de Mato Grosso do Sul (UFMS) - Campo Grande',
    'Universidade Federal de Rondonópolis (UFR)',
    'Universidade Federal do Mato Grosso do Sul (UFMS/Três lagoas) - Três Lagoas',
  ],
  MG: [
    'AFYA Faculdade de Ciências Médicas de Contagem (Afya Contagem)',
    'Afya Faculdade de Ciências Médicas de Ipatinga (AFYA IPATINGA)',
    'Centro Universitário Atenas (UNIATENAS) - Paracatu',
    'Centro Universitário de Belo Horizonte (UNI/BH)',
    'Centro Universitário de Caratinga (UNEC)',
    'Centro Universitário de Manhuaçu (UNIFACIG)',
    'Centro Universitário de Patos de Minas (UNIPAM)',
    'Centro Universitário Presidente Tancredo de Almeida Neves - S.João del Rei (UNIPTAN) - São João Del Rei',
    'Centro Universitário UNIFAGOC - Ubá',
    'Faculdade Atenas-Passos',
    'Faculdade da Saúde e Ecologia Humana (FASEH) - Vespasiano',
    'Faculdade de Ciências Médicas de Minas Gerais - FELUMA (FCM/MG) - Belo Horizonte',
    'Faculdade de Ciências Médicas e da Saúde de Juiz de Fora - SUPREMA (FCMS/JF)',
    'Faculdade de Medicina (FATRA) - Uberlândia',
    'Faculdade de Medicina de Barbacena (FAME)',
    'Faculdade de Medicina de Itajubá (FMIt)',
    'Faculdade de Minas BH (FAMINAS) - Belo Horizonte',
    'Faculdade Dinâmica do Vale do Piranga (FADIP) - Ponte Nova',
    'Faculdade Sete Lagoas (Atenas Sete Lagoas)',
    'Faculdade Vértice (UNIVERTIIX) - Matipó',
    'Fundação Universidade Federal de Viçosa (UFV)',
    'Instituto de Ciências da Saúde (ICS) - Montes Claros',
    'Pontifícia Universidade Católica de Minas Gerais (PUC MINAS) - Betim',
    'Pontifícia Universidade Católica de Minas Gerais (PUC/CONTAGEM/MG) - Contagem',
    'Pontifícia Universidade Católica de Minas Gerais (PUC/Poços de Caldas) - Pocos de Caldas',
    'Uni-Faminas Minas (UNI/FAMINAS Muriaé) - Muriaé',
    'UNIFIPMoc - Montes Claros',
    'Universidade de Itaúna (UIt)',
    'Universidade de Uberaba (UNIUBE)',
    'Universidade do Estado de Minas Gerais (UEMG/PASSOS) - Passos',
    'Universidade do Vale do Sapucaí (UNIVAS) - Pouso Alegre',
    'Universidade Estadual de Montes Claros (UNIMONTES)',
    'Universidade Federal de Alfenas - Alfenas (MG) (UNIFAL)',
    'Universidade Federal de Juiz de Fora (UFJF)',
    'Universidade Federal de Juiz de Fora (UFJF/Governador Valadares) - Governador Valadares',
    'Universidade Federal de Juiz de Fora - Governador Valadares Autorizado UFJF (UFJF.br/GV)',
    'Universidade Federal de Lavras (UFLA)',
    'Universidade Federal de Minas Gerais (UFMG) - Belo Horizonte',
    'Universidade Federal de Ouro Preto - UFOP (UF0P)',
    'Universidade Federal de São João Del Rei (UFSJ)',
    'Universidade Federal de São João Del Rei /Divinópolis (UFSJ)',
    'Universidade Federal de Uberlândia (UFU)',
    'Universidade Federal do Triângulo Mineiro (UFTM) - Uberaba',
    'Universidade Federal dos Vales do Jequitinhonha e Mucuri (UFVJM) - Diamantina',
    'Universidade Federal dos Vales doo Jequitinhonha e Mucuri (UFVJM/Teófilo Otoni) - Teófilo Otoni',
    'Universidade Presidente Antônio Carlos (UNIPAC) - Juiz de Fora',
    'Universidade Professor Edson Antônio Velano (UNIFENAS) - Alfenas',
    'Universidade Professor Edson Antônio Velano (UNIFENAS/BH) - Belo Horizonte',
    'Universidade Vale do Rio Doce (UNIVALE MG) - Governador Valadares',
  ],
  PA: [
    'Afya Faculdade de Ciências Médicas de Abaetetuba (AFYA ABAETETUBA)',
    'AFYA Faculdade de Ciências Médicas de Bragança (AFYA Bragança)',
    'Centro Universitário da Amazônia (UNAMA) - Santarém',
    'Centro Universitário do Estado do Pará (CESUPA) - Belem',
    'Centro Universitário Fibra (Unifibra) - Belém',
    'Faculdade de Ensino Superior da Amazônia Reunida (FESAR) - Redenção',
    'Faculdade Metropolitana da Amazônia (FAMAZ) - Belem',
    'Universidade do Estado do Pará (UEPA) - Belem',
    'Universidade do Estado do Pará (UEPA/Marabá) - Marabá',
    'Universidade do Estado do Pará - Santarém (UEPA) - Belem',
    'Universidade Federal do Pará (UFPA) - Belem',
  ],
  PB: [
    'AFYA FACULDADE DE CIÊNCIAS MÉDICAS DA PARAÍBA (AFYA PARAÍBA) - Cabedelo',
    'Centro Universitário de João Pessoa (UNIPÊ)',
    'Centro Universitário de Patos (UNIFIP)',
    'Centro Universitário Santa Maria (UNIFSM) - Cajazeiras',
    'Faculdade de Ciências Médicas de Campina Grande (UNIFACISA/FCM)',
    'Faculdade de Medicina Nova Esperança - J.Pessoa (FAMENE) - João Pessoa',
    'Universidade Federal da Paraíba - J. Pessoa (UFPB) - João Pessoa',
    'Universidade Federal de Campina Grande (UFCG)',
    'Universidade Federal de Campina Grande (UFCG) - Cajazeiras',
  ],
  PR: [
    'Centro Universitário Assis Gurgacz (FAG) - Cascavel',
    'Centro Universitário Campo Real - Guarapuava',
    'Centro Universitário Ingá (UNINGÁ) - Maringá',
    'Centro Universitário Integrado de Campo Mourão',
    'Faculdade de Medicina de Toledo (UFPR/Toledo)',
    'Faculdade Evangélica Mackenzie do Paraná (FEMPAR) - Curitiba',
    'Faculdades Pequeno Principe (FPP) - Curitiba',
    'Pontifícia Universidade Católica do Paraná (PUC PR) - Londrina',
    'Pontifícia Universidade Católica do Paraná (PUCPR) - Curitiba',
    'UNIVEL Centro Universitário - Cascavel',
    'Universidade de Maringá (UNICESUMAR)',
    'Universidade de Pato Branco (UNIDEP)',
    'Universidade Estadual de Londrina (UEL)',
    'Universidade Estadual de Maringá (UEM)',
    'Universidade Estadual de Ponta Grossa (UEPG)',
    'Universidade Estadual do Centro Oeste (UNICENTRO) - Guarapuava',
    'Universidade Estadual do Oeste do Paraná (UNIOESTE) - Cascavel',
    'Universidade Estadual do Oeste do Paraná (UNIOESTE/Francisco Beltrão) - Francisco Beltão',
    'Universidade Federal da Integração Latino-Americana (UNILA _ Foz do Iguaçu) - Foz do Iguaçu',
    'Universidade Federal do Paraná (UFPR) - Curitiba',
    'Universidade Federal do Paraná - campus de TOLEDO (UFPR/TOLEDO)',
    'Universidade Paranaense (UNIPAR) - Umuarama',
    'Universidade Positivo (UP) - Curitiba',
  ],
  PE: [
    'Afya Faculdade de Ciências Médicas de Garanhuns (FAMEG)',
    'AFYA FACULDADE DE CIÊNCIAS MÉDICAS DE JABOATÃO DOS GUARARAPES (AFYA JABOATAO)',
    'Centro Universitário Mauricio de Nassau (UNINASSAU) - Recife',
    'Centro Universitário Universo Recife',
    'Faculdade de Ciências Aplicadas e Sociais de Petrolina (FACAPE)',
    'Faculdade de Medicina de Olinda (FMO)',
    'Faculdade de Medicina do Sertão (FMS) - Arcoverde',
    'Faculdade Paraíso Araripina (FAP)',
    'Faculdade Pernambucana de Saúde/Recife (FPS)',
    'Faculdade Tiradentes de Goiana (FITS)',
    'Universidade Católica de Pernambuco (UNICAP) - Recife',
    'Universidade de Pernambuco (UPE/Serra Talhada) - Serra Talhada',
    'Universidade de Pernambuco-/Recife (UPE)',
    'Universidade de Pernambuco/Garanhuns (UPE/Garanhuns)',
    'Universidade Federal de Pernambuco (UFPE) - Caruaru (PE)',
    'Universidade Federal de Pernambuco (UFPE) - Recife',
    'Universidade Federal do Vale do São Francisco/Petrolina (UNIVASF)',
  ],
  PI: [
    'Centro Universitário Uninovafapi - Piauí - Teresina',
    'Faculdade de Ciências Humanas, Exatas e da Saúde do Piauí (FAHESP/iESVAP) - Parnaiba',
    'Universidade Estadual do Piauí (UESPI) - Teresina',
    'Universidade Federal do Piauí (UFP/Parnaíba) - Parnaíba',
    'Universidade Federal do Piauí (UFPI) - Teresina',
    'Universidade Federal do Piauí - campus Senador Elvidio N. de Barros (UFPI/Picos) - Picos',
  ],
  RJ: [
    'Centro Universitário de Valença (UNIFAA)',
    'Centro Universitário de Volta Redonda (UniFOA)',
    'Centro Universitário Redentor (UNIREDENTOR) - Itaperuna',
    'Centro Universitário Serra dos Órgãos (UNIFESO) - Teresópolis',
    'Escola de Medicina Souza Marques (EMSM) - Rio de Janeiro',
    'Faculdade de Medicina de Campos (FMC) - Campos dos Goytacazes',
    'Faculdade de Medicina de Petrópolis (UNIFASE)',
    'Faculdade Metropolitana São Carlos BJI - FAMESC (FMMSCBJI) - B.J.Itabapoana',
    'Faculdade União Araruama de Ensino S/S Ltda (FAC/UNILAGOS)',
    'Suprema Faculdade de Ciências Médicas de Três Rios (FCM/TR)',
    'Universidade Castelo Branco (UCB) - Rio de Janeiro',
    'Universidade de Vassouras (UNIVASSOURAS)',
    'Universidade do Estado do Rio de Janeiro (UERJ)',
    'Universidade do Grande Rio Professor José de Souza Herdy (UNIGRANRIO) - Duque de Caxias',
    'Universidade do Grande Rio Professor José de Souza Herdy (UNIGRANRIO) - Rio de Janeiro',
    'Universidade Estácio de Sá (UNESA) - Rio de Janeiro',
    'Universidade Estácio de Sá (UNESA/Angra dos Reis) - Angra dos Reis',
    'Universidade Estácio de Sá - Campus João Uchoa - UNESA (ESTÁCIO/JOÀO UCHOA) - Rio de Janeiro',
    'Universidade Federal do Estado do Rio de Janeiro (UNIRIO)',
    'Universidade Federal do Rio de Janeiro (UFRJ)',
    'Universidade Federal do Rio de Janeiro/Macaé (UFRJ/Macaé)',
    'Universidade Federal Fluminense (UFF) - Niteroi',
    'Universidade Iguaçu (UNIG/Itaperuna) - Itaperuna',
    'Universidade Iguaçu (UNIG/Nova Iguaçu) - Nova Iguaçu',
    'Universidade Veiga de Almeida (UVA) - Rio de Janeiro',
  ],
  RN: [
    'Faculdade Nova Esperança de Mossoro (FACENE/RN)',
    'Universidade do Estado do Rio Grande do Norte (UERN) - Mossoró',
    'Universidade Federal do Rio Grande do Norte (UFRN) - Natal',
    'Universidade Federal do Rio Grande do Norte (UFRN/Caicó) - Caicó',
    'Universidade Federal Rural do Semi-Árido - campus de Mossoró (UFERSA/Mossoró)',
    'Universidade Potiguar (UnP) - Natal',
  ],
  RS: [
    'Centro Universitário Ideau (UNIDEAU) - Caxias do Sul',
    'Centro Universitário Univates - Lajeado',
    'Cesuca Centro Universiärio - Cachoeirinha',
    'Pontificia Universidade Católica do Rio Grande do Sul (PUCRS) - Porto Alegre',
    'Universidade Católica de Pelotas (UCPEL)',
    'Universidade de Caxias do Sul (UCS)',
    'Universidade de Passo Fundo (UPF)',
    'Universidade de Santa Cruz do Sul (UNISC)',
    'Universidade do Vale do Rio dos Sinos (UNISINOS) - São Leopoldo',
    'Universidade Federal da Fronteira Sul (UFFS) - Passo Fundo',
    'Universidade Federal de Ciências da Saúde de Porto Alegre (UFCSPA)',
    'Universidade Federal de Pelotas (UFPel)',
    'Universidade Federal de Santa Maria (UFSM)',
    'Universidade Federal do Pampa (UNIPAMPA/URUGUAIANA) - Uruguaiana',
    'Universidade Federal do Rio Grande (FURG)',
    'Universidade Federal do Rio Grande do Sul (UFRGS) - Porto Alegre',
    'Universidade Feevale - Novo Hamburgo',
    'Universidade Franciscana (UFN) - Santa Maria',
    'Universidade Luterana do Brasil (ULBRA) - Canoas',
    'Universidade Regional do Noroeste do Estado do Rio Grande do Sul (UNIJUI) - Ijui',
    'Universidade Regional Integrada do Alto Uruguai e das Missões (URI ERECHIM) - Erechim',
  ],
  RO: [
    'Centro Universitário Aparício Carvalho (FIMCA) - Jaru',
    'CENTRO UNIVERSITÁRIO SÃO LUCAS PORTO VELHO (SÃO LUCAS PVH) (UniSL)',
    'Centro Universitário UNIFACIMED - Cacoal',
    'Faculdade de Educação e Cultura de Vilhena (UNESC/Rondônia)',
    'Faculdades Integradas Aparício Carvalho (FIMCA) - Porto Velho',
    'Fundação Universidade Federal de Rondônia (UNIR) - Porto Velho',
  ],
  RR: [
    'Universidade Estadual de Roraima (UERR) - Boa Vista',
    'Universidade Federal de Roraima (UFRR) - Boa Vista',
  ],
  SC: [
    'Centro Univ.p/ o Desenvolvimento do Alto Vale do Itajaí (Unidavi) - Rio do Sul',
    'Faculdade Estácio de Jaraguá do Sul - ESTÁCIO/JARAGUÁ',
    'Faculdade Life Unic Education - Joinville',
    'Universidade Alto Vale do Rio do Peixe (UNIARP) - Caçador',
    'Universidade Comunitária da Região de Chapecó (UNOCHAPECO)',
    'Universidade da Região de Joinville (UNIVILLE)',
    'Universidade de Brusque (UNIFEBE)',
    'Universidade do Contestado - UcN (UnC) - Mafra',
    'Universidade do Extremo Sul Catarinense (UNESC) - Criciúma',
    'Universidade do Oeste de Santa Catarina (UNOESC) - Joaçaba',
    'Universidade do Planalto Catarinense (UNIPLAC) - Lages',
    'Universidade do Sul de Santa Catarina (UNISUL) - Palhoça',
    'Universidade do Sul de Santa Catarina - Campus Tubarão (UNISUL)',
    'Universidade do Vale do Itajaí (UNIVALI)',
    'Universidade Federal da Fronteira Sul - Chapecó UFFS (UFFS/Chapecó)',
    'Universidade Federal de Santa Catarina (UFSC) - Florianópolis',
    'Universidade Federal de Santa Catarina - Campus ARARANGUÁ (UFSC/ARAGUANGUÁ)',
    'Universidade Regional de Blumenau (FURB)',
  ],
  SP: [
    'Centro Universitário Adventista de São Paulo (UNASP) - Hortolândia',
    'Centro Universitário Barão de Mauá (UFBM) - Ribeirão Preto',
    'Centro Universitário Campo Limpo Paulista (UNIFACCAMP)',
    'Centro Universitário Católico Salesiano Aux (UNISALESIANO) - Aracatuba',
    'Centro Universitário Claretiano (CEUCLAR) - Rio Claro',
    'Centro Universitário das Faculdade Associadas de Ensino - S.João da Boa Vista (UNIFAE) - São João da Boa Vista',
    'Centro Universitário de Adamantina (FAI)',
    'Centro Universitário de Araraquara (UNIARA)',
    'Centro Universitário de Indaiatuba - Grupo UniEduK (UniMax)',
    'Centro Universitário de Jaguariúna - Grupo UniEduK (UNIFAJ)',
    'Centro Universitário de Santa Fé do Sul (UNIFUNEC)',
    'Centro Universitário de Votuporanga (UNIFEV)',
    'Centro Universitário Estácio de Ribeirão Preto (UNISEB)',
    'Centro Universitário FUNVIC (UNIFUNVIC) - Pindamonhangaba',
    'Centro Universitário Lusíada (UNILUS) - Santos',
    'Centro Universitário Municipal de Franca (UNI/FACEF)',
    'Centro Universitário Padre Albino (UNIFIPA) - Catanduva',
    'Centro Universitário São Camilo - São Paulo',
    'Centro Universitário Sudoeste Paulista (UniFSP) - Avaré',
    'Faculdade das Américas (FAM) - São Paulo',
    'Faculdade de Ciências da Saúde de Barretos Dr. Paulo Prata (FACISB)',
    'Faculdade de Ciências da Saúde Sírio-Libanês (FSL) - São Paulo',
    'Faculdade de Ciências Médicas da Santa Casa de São Paulo (FCMSCSP)',
    'Faculdade de Ciências Médicas de São José dos Campos (Humanitas)',
    'Faculdade de Medicina - Unoeste - Campus/Guarujá (Medicina/Guarujá)',
    'Faculdade de Medicina de Jundiaí (FMJ)',
    'Faculdade de Medicina de Marília (FAMEMA)',
    'Faculdade de Medicina de Penápolis (FUNEPE)',
    'Faculdade de Medicina de São José do Rio Preto (FAMERP)',
    'Faculdade de Medicina do ABC (FMABC) - Santo André',
    'Faculdade de Medicina FACERES - São José do Rio Preto',
    'Faculdade Israelita de Ciências da Saúde Albert Einsten (FICSAE) - São Paulo',
    'Faculdade Municipal de Medicina Prof. Franco Montoro (FMPFM) - Mogi Guaçu',
    'Faculdade Santa Marcelina (FASM) - Itaquera',
    'Faculdade São Leopoldo Mandic (SLMANDIC) - Campinas',
    'Faculdade São Leopoldo Mandic - FMANDIC (FSLM) - Araras',
    'Faculdade São Leopoldo Mandic de Limeira (SLM Limeira)',
    'Faculdade Unifadra Dracena',
    'Fundação Educacional do Município de Assis (FEMA)',
    'Pontifícia Universidade Católica de Campinas (PUC/CAMPINAS)',
    'Pontifícia Universidade Católica de São Paulo - Campus Sorocaba (PUCSP/Sorocaba)',
    'União das Faculdades dos Grandes Lagos - S. José do Rio Preto (UNILAGO) - São José do Rio Preto',
    'Universidade Anhembi Morumbi (UAM) - São Paulo',
    'Universidade Anhembi-Morumbi (UAM/Piracicaba) - Piracicaba',
    'Universidade Anhembi-Morumbi (UAM/São José dos Campos) - São José dos Campos',
    'Universidade Brasil (UB) - Fernandópolis',
    'Universidade Cidade de São Paulo (UNICID)',
    'Universidade de Franca (UNIFRAN)',
    'Universidade de Marília (UNIMAR)',
    'Universidade de Mogi das Cruzes (UMC)',
    'Universidade de Ribeirão Preto (UNAERP)',
    'Universidade de Ribeirão Preto - Campus Guarujá (UNAERP)',
    'Universidade de Santo Amaro (UNISA) - São Paulo',
    'Universidade de São Caetano do Sul - S.Paulo (USCS/SP) - São Paulo',
    'Universidade de São Paulo (USP/Baurú) - Baurú',
    'Universidade de São Paulo - Campus Ribeirão Preto - USP-RP (FMRP/USP)',
    'Universidade de São Paulo - Campus São Paulo (FMSP/USP)',
    'Universidade de Taubaté (UNITAU)',
    'Universidade do Oeste Paulista (UNOESTE) - Presidente Prudente',
    'Universidade do Oeste Paulista - SÃO PAULO (UNOESTE/JAÚ) - Jaú',
    'Universidade Estadual de Campinas (UNICAMP)',
    'Universidade Estadual Paulista Júlio de Mesquita Filho - Botucatu (UNESP) - São Paulo',
    'Universidade Federal de São Carlos (UFSCAR)',
    'Universidade Federal de São Paulo (UNIFESP)',
    'Universidade Metropolitana de Santos (UNIMES)',
    'Universidade Municipal de São Caetano do Sul (USCS)',
    'Universidade Municipal de São Caetano do Sul - Campus Bela Vista (USCS/SP) - São Paulo',
    'Universidade Nove de Julho (UNINOVE) - Osasco',
    'Universidade Nove de Julho (UNINOVE) - São Paulo',
    'Universidade Nove de Julho (UNINOVE/Guarulhos) - Guarulhos',
    'Universidade Nove de Julho (UNINOVE/Mauá) - Mauá',
    'Universidade Nove de Julho (UNINOVE/S.Bernardo do Campo) - São Bernardo do Campo',
    'Universidade São Francisco (USF) - Bragança Paulista',
    'Universidade São Judas Tadeu (USJT) - Cubatão',
  ],
  SE: [
    'Universidade Federal de Sergipe (UFS) - São Cristovão',
    'Universidade Federal de Sergipe - UFS/Campus Lagarto (UFS/Campus de Lagarto)',
    'UNIVERSIDADE TIRADENTES (UNIT) - Aracaju',
    'Universidade Tiradentes (UNIT/Estância) - Estância',
  ],
  TO: [
    'Centro Universitário Tocantinense Presidente Antônio Carlos (UNITPAC) - Araguaina',
    'Centro Universitário Unirg - GurupiTO',
    'Faculdade Presidente Antonio Carlos (FAPAC) - Porto Nacional',
    'Instituto Presidente Antonio Carlos (ITPAC/PALMAS) - Palmas',
    'Universidade de Gurupi - Campus Paraíso (UNIRG)',
    'Universidade Estadual do Tocantins (Unitins) - Palmas',
    'Universidade Federal de Tocantins (UFT/Araguaína) - Araguaía',
    'Universidade Federal do Tocantins (UFT) - Palmas',
  ],
}

/** Opção de escape exibida no fim de todo select de instituição. */
export const OTHER_SCHOOL_OPTION = 'Não encontro minha instituição na lista'

/**
 * Lista de um estado, com as unidades Afya no topo (é como o aluno chama a
 * própria faculdade) e a opção de escape no fim. As entradas do e-MEC que já
 * são Afya saem da lista nacional para não aparecer o mesmo curso duas vezes
 * com nomes diferentes — o rótulo Afya vira o valor canônico.
 */
export function getMedicalSchoolsByState(uf?: string | null): string[] {
  if (!uf) return []
  const national = (MEDICAL_SCHOOLS_BY_STATE[uf] || []).filter(
    (school) => !/afya/i.test(school)
  )
  return [...getAfyaUnitsByState(uf), ...national, OTHER_SCHOOL_OPTION]
}

/** Todas as escolas do país, com a UF no rótulo — para busca sem filtrar estado. */
export function getAllMedicalSchools(): string[] {
  return Object.entries(MEDICAL_SCHOOLS_BY_STATE)
    .flatMap(([uf, schools]) => schools.map((school) => `${school} (${uf})`))
    .sort((a, b) => a.localeCompare(b, 'pt-BR'))
}
