import type { FonteId } from '../esquemas'

export type AumentoVisualExterno = 'macroscopia' | 'panoramica' | 'pequeno' | 'medio' | 'grande' | 'especial'

export interface ReferenciaVisualExterna {
  id: string
  fonteId: Extract<FonteId, 'pathology-outlines' | 'webpathology' | 'webpath-utah'>
  titulo: string
  tituloOriginal: string
  urlPaginaFonte: string
  /** URL remota exibível apenas quando a fonte possui autorização registrada. */
  urlImagem?: string
  aumento: AumentoVisualExterno
  modalidade: string
  descricaoDidatica: string
  oQueObservar: string[]
}

/**
 * Referências visuais selecionadas manualmente, sem copiar imagem ou legenda.
 *
 * `descricaoDidatica` e `oQueObservar` são redação original do Domine Aqui. Os
 * Para WebPath, a autorização escrita permite registrar a URL remota do arquivo
 * e exibi-lo no Domine Aqui. As demais fontes continuam limitadas à página pública.
 */
export const REFERENCIAS_VISUAIS_EXTERNAS: Record<string, ReferenciaVisualExterna[]> = {
  'carcinoma-papilifero-da-tireoide': [
    {
      id: 'pathology-outlines-cpt-visao-geral',
      fonteId: 'pathology-outlines',
      titulo: 'Carcinoma papilífero da tireoide — revisão morfológica ilustrada',
      tituloOriginal: 'Papillary thyroid carcinoma overview',
      urlPaginaFonte: 'https://www.pathologyoutlines.com/topic/thyroidpapillary.html',
      aumento: 'especial',
      modalidade: 'Tópico ilustrado — histologia e diagnóstico',
      descricaoDidatica: 'Revisão externa para integrar arquitetura, alterações nucleares, variantes e imunofenótipo. Use as imagens como uma sequência comparativa e confronte cada campo com os critérios explicados no capítulo do Domine Aqui.',
      oQueObservar: ['papilas verdadeiras e padrões foliculares', 'distribuição das alterações nucleares', 'variantes que mudam prognóstico ou diferencial'],
    },
    {
      id: 'webpathology-cpt-arquitetura-41425',
      fonteId: 'webpathology',
      titulo: 'Carcinoma papilífero da tireoide — arquitetura papilífera',
      tituloOriginal: 'Papillary Carcinoma of Thyroid',
      urlPaginaFonte: 'https://www.webpathology.com/images/endocrine/thyroid/papillary-carcinoma/41425',
      aumento: 'pequeno',
      modalidade: 'Histologia — HE',
      descricaoDidatica: 'Campo para reconhecer papilas verdadeiras: eixo fibrovascular central revestido por células neoplásicas. A papila precisa conter estroma e capilar; apenas dobras epiteliais sem eixo não bastam.',
      oQueObservar: ['eixos fibrovasculares ramificados', 'revestimento epitelial relativamente uniforme', 'contraste com folículos tireoidianos residuais'],
    },
    {
      id: 'webpathology-cpt-nucleos-41431',
      fonteId: 'webpathology',
      titulo: 'Carcinoma papilífero — alterações nucleares diagnósticas',
      tituloOriginal: 'Papillary Thyroid Carcinoma',
      urlPaginaFonte: 'https://www.webpathology.com/images/endocrine/thyroid/papillary-carcinoma/41431',
      aumento: 'grande',
      modalidade: 'Histologia — HE',
      descricaoDidatica: 'A identidade do tumor depende mais do núcleo do que da arquitetura. Compare tamanho, sobreposição, clareamento da cromatina, sulcos e pseudoinclusões, evitando transformar um único sulco em diagnóstico.',
      oQueObservar: ['clareamento nuclear difuso', 'sulcos longitudinais em vários núcleos', 'pseudoinclusões intranucleares verdadeiras'],
    },
    {
      id: 'webpathology-cpt-metastase-38592',
      fonteId: 'webpathology',
      titulo: 'Metástase linfonodal de carcinoma papilífero da tireoide',
      tituloOriginal: 'Metastatic Papillary Thyroid Carcinoma',
      urlPaginaFonte: 'https://www.webpathology.com/images/hematopathology/lymph-node-non-hematopoietic/lymph-node-metastases/38592',
      aumento: 'pequeno',
      modalidade: 'Histologia — HE',
      descricaoDidatica: 'Referência para procurar tecido epitelial tireoidiano dentro do linfonodo e separar depósito metastático de inclusões benignas. O contexto arquitetural e as feições nucleares precisam concordar.',
      oQueObservar: ['substituição focal da arquitetura linfonodal', 'papilas ou folículos com núcleos típicos', 'relação do depósito com seios subcapsulares'],
    },
    {
      id: 'webpath-utah-cpt-macro-endo063',
      fonteId: 'webpath-utah',
      titulo: 'Carcinoma papilífero da tireoide — peça macroscópica',
      tituloOriginal: 'Thyroid, papillary carcinoma, gross',
      urlPaginaFonte: 'https://webpath.med.utah.edu/ENDOHTML/ENDO063.html',
      urlImagem: 'https://webpath.med.utah.edu/jpeg4/ENDO063.jpg',
      aumento: 'macroscopia',
      modalidade: 'Macroscopia',
      descricaoDidatica: 'Use a peça para mapear limites, multifocalidade e relação com a cápsula. Áreas firmes, esbranquiçadas e eventualmente calcificadas orientam a amostragem, mas a aparência isolada não define subtipo.',
      oQueObservar: ['limite entre tumor e parênquima', 'focos satélites ou multifocais', 'áreas calcificadas e fibrosas'],
    },
    {
      id: 'webpath-utah-cpt-baixo-endo026',
      fonteId: 'webpath-utah',
      titulo: 'Carcinoma papilífero — visão em pequeno aumento',
      tituloOriginal: 'Thyroid, papillary carcinoma, low power microscopic',
      urlPaginaFonte: 'https://webpath.med.utah.edu/ENDOHTML/ENDO026.html',
      urlImagem: 'https://webpath.med.utah.edu/jpeg4/ENDO026.jpg',
      aumento: 'pequeno',
      modalidade: 'Histologia — HE',
      descricaoDidatica: 'A visão panorâmica estabelece se a lesão é infiltrativa, encapsulada, papilífera ou predominantemente folicular. Essa leitura antecede a procura de detalhes nucleares.',
      oQueObservar: ['interface com a tireoide não neoplásica', 'distribuição das papilas', 'fibrose e corpos psamomatosos'],
    },
    {
      id: 'webpath-utah-cpt-alto-endo027',
      fonteId: 'webpath-utah',
      titulo: 'Carcinoma papilífero — detalhe nuclear',
      tituloOriginal: 'Thyroid, papillary carcinoma, high power microscopic',
      urlPaginaFonte: 'https://webpath.med.utah.edu/ENDOHTML/ENDO027.html',
      urlImagem: 'https://webpath.med.utah.edu/jpeg4/ENDO027.jpg',
      aumento: 'grande',
      modalidade: 'Histologia — HE',
      descricaoDidatica: 'Campo complementar para treinar o conjunto nuclear em população celular, não em célula isolada. A distribuição difusa das alterações pesa mais que uma pseudoinclusão ocasional.',
      oQueObservar: ['núcleos aumentados e sobrepostos', 'cromatina clara marginalizada', 'sulcos e pseudoinclusões no mesmo contexto'],
    },
  ],
  'melanoma-cutaneo': [
    {
      id: 'pathology-outlines-melanoma-invasivo',
      fonteId: 'pathology-outlines',
      titulo: 'Melanoma invasivo — revisão morfológica ilustrada',
      tituloOriginal: 'Invasive melanoma',
      urlPaginaFonte: 'https://www.pathologyoutlines.com/topic/skintumormelanocyticmelanoma.html',
      aumento: 'especial',
      modalidade: 'Tópico ilustrado — histologia e estadiamento',
      descricaoDidatica: 'Referência externa para consolidar crescimento radial e vertical, profundidade de Breslow, ulceração e mitoses. Percorra as imagens na ordem da arquitetura para a citologia e só depois aplique os parâmetros de estadiamento.',
      oQueObservar: ['assimetria e dispersão pagetoide', 'componente dérmico sem maturação', 'pontos corretos para medir Breslow'],
    },
    {
      id: 'webpathology-melanoma-radial-40606',
      fonteId: 'webpathology',
      titulo: 'Melanoma — fase de crescimento radial',
      tituloOriginal: 'Melanoma: Radial Growth Phase',
      urlPaginaFonte: 'https://www.webpathology.com/images/dermpath/proliferations-and-neoplasms/melanoma---general/40606',
      aumento: 'pequeno',
      modalidade: 'Histologia — HE',
      descricaoDidatica: 'A fase radial se espalha pela epiderme e derme papilar antes de formar nódulo expansivo profundo. O exercício é reconhecer assimetria, confluência juncional e dispersão pagetoide.',
      oQueObservar: ['assimetria lateral', 'melanócitos isolados acima da camada basal', 'ninhos juncionais confluentes e irregulares'],
    },
    {
      id: 'webpathology-melanoma-vertical-40608',
      fonteId: 'webpathology',
      titulo: 'Melanoma — fase de crescimento vertical',
      tituloOriginal: 'Melanoma: Vertical Growth Phase',
      urlPaginaFonte: 'https://www.webpathology.com/images/dermpath/proliferations-and-neoplasms/melanoma---general/40608',
      aumento: 'pequeno',
      modalidade: 'Histologia — HE',
      descricaoDidatica: 'Procure um clone dérmico expansivo maior que os ninhos superficiais. O componente vertical marca capacidade de crescimento autônomo na derme e precisa ser medido em profundidade.',
      oQueObservar: ['nódulo dérmico expansivo', 'ausência de maturação com a profundidade', 'mitoses no componente profundo'],
    },
    {
      id: 'webpathology-melanoma-breslow-40611',
      fonteId: 'webpathology',
      titulo: 'Melanoma — como interpretar a espessura de Breslow',
      tituloOriginal: 'Melanoma: Breslow Thickness',
      urlPaginaFonte: 'https://www.webpathology.com/images/dermpath/proliferations-and-neoplasms/melanoma---general/40611',
      aumento: 'panoramica',
      modalidade: 'Histologia — HE / mensuração',
      descricaoDidatica: 'A medida vai do topo da camada granulosa, ou da base da úlcera, até a célula invasiva mais profunda. Satélites descontínuos não entram na medida do foco primário.',
      oQueObservar: ['ponto epidérmico correto de origem da medida', 'célula tumoral invasiva mais profunda', 'ulceração que modifica o ponto inicial'],
    },
    {
      id: 'webpath-utah-melanoma-macro-neopl024',
      fonteId: 'webpath-utah',
      titulo: 'Melanoma cutâneo — aspecto macroscópico',
      tituloOriginal: 'Melanoma, skin, gross',
      urlPaginaFonte: 'https://webpath.med.utah.edu/NEOHTML/NEOPL024.html',
      urlImagem: 'https://webpath.med.utah.edu/jpeg3/SKIN097.jpg',
      aumento: 'macroscopia',
      modalidade: 'Macroscopia clínica',
      descricaoDidatica: 'A macroscopia treina assimetria, borda irregular, variação de cor e áreas nodulares. Esses sinais escolhem a lesão para biópsia; o diagnóstico e o estadiamento permanecem histológicos.',
      oQueObservar: ['assimetria dos eixos', 'bordas recortadas', 'heterogeneidade de pigmentação e relevo'],
    },
    {
      id: 'webpath-utah-melanoma-melanossomos-em029',
      fonteId: 'webpath-utah',
      titulo: 'Melanoma — melanossomos à microscopia eletrônica',
      tituloOriginal: 'Melanosomes from a malignant melanoma, electron micrograph',
      urlPaginaFonte: 'https://webpath.med.utah.edu/HISTHTML/EM/EM029.html',
      urlImagem: 'https://webpath.med.utah.edu/jpeg3/SKIN034.jpg',
      aumento: 'especial',
      modalidade: 'Microscopia eletrônica',
      descricaoDidatica: 'Referência ultraestrutural para relacionar o pigmento castanho da HE a organelas especializadas. Hoje a microscopia eletrônica raramente é necessária no diagnóstico, mas esclarece a biologia melanocítica.',
      oQueObservar: ['organelas elipsoidais eletrondensas', 'diferentes estágios de melanização', 'relação entre melanossomo e pigmento citoplasmático'],
    },
  ],
  osteossarcoma: [
    {
      id: 'pathology-outlines-osteossarcoma-geral',
      fonteId: 'pathology-outlines',
      titulo: 'Osteossarcoma — revisão morfológica ilustrada',
      tituloOriginal: 'Osteosarcoma',
      urlPaginaFonte: 'https://www.pathologyoutlines.com/topic/boneosteosarcomageneral.html',
      aumento: 'especial',
      modalidade: 'Tópico ilustrado — histologia e diagnóstico',
      descricaoDidatica: 'Coleção externa para comparar osso reativo, osteoide maligno e variantes osteoblástica, condroblástica e fibroblástica. O exercício central é demonstrar produção direta de osteoide por células francamente malignas.',
      oQueObservar: ['continuidade entre célula tumoral e osteoide', 'pleomorfismo nas áreas celulares', 'heterogeneidade de matriz entre variantes'],
    },
    {
      id: 'webpathology-osteossarcoma-micro-58931',
      fonteId: 'webpathology',
      titulo: 'Osteossarcoma — osteoide tumoral em detalhe',
      tituloOriginal: 'Osteosarcoma: Microscopic Features',
      urlPaginaFonte: 'https://www.webpathology.com/images/orthopedic/bone-tumors---ii/osteosarcoma/58931',
      aumento: 'medio',
      modalidade: 'Histologia — HE',
      descricaoDidatica: 'O critério definidor é osteoide produzido diretamente por células malignas. Procure matriz eosinofílica irregular entre células atípicas, e não apenas osso reativo aprisionado.',
      oQueObservar: ['osteoide rendilhado e desorganizado', 'continuidade entre célula tumoral e matriz', 'atipia nas células que margeiam o osteoide'],
    },
    {
      id: 'webpathology-osteoblastico-58933',
      fonteId: 'webpathology',
      titulo: 'Osteossarcoma osteoblástico',
      tituloOriginal: 'Osteoblastic Osteosarcoma',
      urlPaginaFonte: 'https://www.webpathology.com/images/orthopedic/bone-tumors---ii/osteosarcoma/58933',
      aumento: 'medio',
      modalidade: 'Histologia — HE',
      descricaoDidatica: 'Padrão com produção abundante de matriz óssea maligna. A quantidade de osteoide pode ocultar as células; percorra as lacunas e superfícies para localizar núcleos francamente atípicos.',
      oQueObservar: ['matriz osteoide extensa', 'células pleomórficas entre trabéculas', 'mitoses atípicas nas áreas mais celulares'],
    },
    {
      id: 'webpathology-condroblastico-58914',
      fonteId: 'webpathology',
      titulo: 'Osteossarcoma condroblástico',
      tituloOriginal: 'Chondroblastic Osteosarcoma',
      urlPaginaFonte: 'https://www.webpathology.com/images/orthopedic/bone-tumors---ii/osteosarcoma/58914',
      aumento: 'medio',
      modalidade: 'Histologia — HE',
      descricaoDidatica: 'A matriz cartilaginosa domina o campo, mas a busca precisa encontrar osteoide maligno focal para separar osteossarcoma condroblástico de condrossarcoma.',
      oQueObservar: ['lóbulos de cartilagem atípica', 'transição para osteoide tumoral', 'células malignas produzindo as duas matrizes'],
    },
    {
      id: 'webpath-utah-osteossarcoma-macro-neopl049',
      fonteId: 'webpath-utah',
      titulo: 'Osteossarcoma — peça macroscópica',
      tituloOriginal: 'Osteosarcoma of bone, gross',
      urlPaginaFonte: 'https://webpath.med.utah.edu/NEOHTML/NEOPL049.html',
      urlImagem: 'https://webpath.med.utah.edu/jpeg3/BONE001.jpg',
      aumento: 'macroscopia',
      modalidade: 'Macroscopia',
      descricaoDidatica: 'Observe a massa metafisária destrutiva, a substituição da medula e a extensão através do córtex para partes moles. Esses eixos orientam amostragem, resposta terapêutica e margens.',
      oQueObservar: ['destruição cortical', 'extensão extraóssea', 'heterogeneidade por necrose e mineralização'],
    },
    {
      id: 'webpath-utah-osteossarcoma-micro-neopl050',
      fonteId: 'webpath-utah',
      titulo: 'Osteossarcoma — visão microscópica intermediária',
      tituloOriginal: 'Osteosarcoma of bone, medium power microscopic',
      urlPaginaFonte: 'https://webpath.med.utah.edu/NEOHTML/NEOPL050.html',
      urlImagem: 'https://webpath.med.utah.edu/jpeg3/BONE004.jpg',
      aumento: 'medio',
      modalidade: 'Histologia — HE',
      descricaoDidatica: 'Campo para integrar matriz e citologia: primeiro confirme que o material róseo é osteoide e depois demonstre que as próprias células produtoras são malignas.',
      oQueObservar: ['osteoide irregular entre células', 'pleomorfismo e hipercromasia', 'produção de matriz sem organização lamelar'],
    },
  ],
  seminoma: [
    {
      id: 'pathology-outlines-seminoma-classico',
      fonteId: 'pathology-outlines',
      titulo: 'Seminoma testicular — revisão morfológica ilustrada',
      tituloOriginal: 'Seminoma',
      urlPaginaFonte: 'https://www.pathologyoutlines.com/topic/testisseminomas.html',
      aumento: 'especial',
      modalidade: 'Tópico ilustrado — histologia e imunofenótipo',
      descricaoDidatica: 'Revisão externa para integrar arquitetura lobular, citoplasma claro, septos linfocitários, neoplasia germinativa in situ e painel imuno-histoquímico. Compare as imagens com os principais simuladores antes de concluir o subtipo.',
      oQueObservar: ['lóbulos de células germinativas uniformes', 'septos fibrosos ricos em linfócitos', 'contraste com carcinoma embrionário e linfoma'],
    },
    {
      id: 'webpathology-seminoma-macro-36453',
      fonteId: 'webpathology',
      titulo: 'Seminoma — morfologia macroscópica',
      tituloOriginal: 'Seminoma: Gross Morphology',
      urlPaginaFonte: 'https://www.webpathology.com/images/genitourinary/testis/germ-cell-tumors---i/36453',
      aumento: 'macroscopia',
      modalidade: 'Macroscopia',
      descricaoDidatica: 'A massa costuma ser homogênea, lobulada e branco-acinzentada. Hemorragia e necrose extensas devem levantar a possibilidade de componente não seminomatoso ou tumor volumoso.',
      oQueObservar: ['superfície homogênea e carnosa', 'lóbulos separados por septos', 'relação com túnica e cordão espermático'],
    },
    {
      id: 'webpathology-seminoma-he-36465',
      fonteId: 'webpathology',
      titulo: 'Seminoma clássico — células claras e septos fibrosos',
      tituloOriginal: 'Seminoma',
      urlPaginaFonte: 'https://www.webpathology.com/images/genitourinary/testis/germ-cell-tumors---i/36465',
      aumento: 'medio',
      modalidade: 'Histologia — HE',
      descricaoDidatica: 'Procure ninhos de células germinativas grandes e relativamente uniformes, citoplasma claro rico em glicogênio e septos fibrosos com linfócitos. O conjunto é mais informativo que qualquer célula isolada.',
      oQueObservar: ['células grandes com membrana nítida', 'núcleo central e nucléolo evidente', 'septos fibrovasculares linfocitários'],
    },
    {
      id: 'webpathology-seminoma-linfocitos-36476',
      fonteId: 'webpathology',
      titulo: 'Seminoma — infiltrado linfoide nos septos',
      tituloOriginal: 'Seminoma: Lymphoid Infiltrate',
      urlPaginaFonte: 'https://www.webpathology.com/images/genitourinary/testis/germ-cell-tumors---i/36476',
      aumento: 'grande',
      modalidade: 'Histologia — HE',
      descricaoDidatica: 'O infiltrado linfoide acompanha septos e pode formar folículos. Ele ajuda a reconhecer o padrão, mas não substitui a demonstração da população germinativa neoplásica.',
      oQueObservar: ['linfócitos maduros entre ninhos', 'septos colagenizados', 'eventuais granulomas sem necrose'],
    },
    {
      id: 'webpath-utah-seminoma-macro-male084',
      fonteId: 'webpath-utah',
      titulo: 'Seminoma testicular — peça de orquiectomia',
      tituloOriginal: 'Testis, seminoma, gross',
      urlPaginaFonte: 'https://webpath.med.utah.edu/MALEHTML/MALE084.html',
      urlImagem: 'https://webpath.med.utah.edu/jpeg1/MALE084.jpg',
      aumento: 'macroscopia',
      modalidade: 'Macroscopia',
      descricaoDidatica: 'Use a peça para reconhecer substituição do parênquima por massa sólida e planejar amostragem de hilo, rede testicular, túnicas e cordão. A extensão anatômica interfere no estadiamento.',
      oQueObservar: ['massa bem delimitada e pálida', 'parênquima residual comprimido', 'extensão ao hilo e às túnicas'],
    },
    {
      id: 'webpath-utah-seminoma-baixo-male096',
      fonteId: 'webpath-utah',
      titulo: 'Seminoma — visão em pequeno aumento',
      tituloOriginal: 'Testis, seminoma, low power microscopic',
      urlPaginaFonte: 'https://webpath.med.utah.edu/MALEHTML/MALE096.html',
      urlImagem: 'https://webpath.med.utah.edu/jpeg1/MALE096.jpg',
      aumento: 'pequeno',
      modalidade: 'Histologia — HE',
      descricaoDidatica: 'A panorâmica evidencia lóbulos tumorais separados por septos. Antes de ampliar, procure túbulos seminíferos residuais na periferia para avaliar neoplasia germinativa in situ.',
      oQueObservar: ['arquitetura lobular', 'septos fibrovasculares', 'interface com túbulos seminíferos residuais'],
    },
    {
      id: 'webpath-utah-seminoma-medio-male087',
      fonteId: 'webpath-utah',
      titulo: 'Seminoma — visão em aumento intermediário',
      tituloOriginal: 'Testis, seminoma, medium power microscopic',
      urlPaginaFonte: 'https://webpath.med.utah.edu/MALEHTML/MALE087.html',
      urlImagem: 'https://webpath.med.utah.edu/jpeg1/MALE087.jpg',
      aumento: 'medio',
      modalidade: 'Histologia — HE',
      descricaoDidatica: 'Campo para comparar uniformidade das células neoplásicas, clareza citoplasmática e resposta linfoide. Áreas com maior pleomorfismo ou outras matrizes exigem busca de componente misto.',
      oQueObservar: ['contornos celulares bem definidos', 'nucléolos proeminentes', 'linfócitos interpostos'],
    },
  ],
  'poliarterite-nodosa': [
    {
      id: 'webpathology-pan-43313',
      fonteId: 'webpathology',
      titulo: 'Poliarterite nodosa na vesícula biliar — visão panorâmica',
      tituloOriginal: 'Gallbladder: Polyarteritis Nodosa',
      urlPaginaFonte: 'https://www.webpathology.com/images/gastrointestinal/gallbladder/other-inflammatory-infectious-disorders/43313',
      aumento: 'panoramica',
      modalidade: 'Histologia — HE',
      descricaoDidatica: 'A baixa magnificação localiza artérias musculares afetadas em meio à parede do órgão. Lesões de idades diferentes no mesmo material são uma pista importante de poliarterite nodosa sistêmica.',
      oQueObservar: ['distribuição segmentar na circunferência arterial', 'vasos acometidos ao lado de vasos preservados', 'isquemia no tecido dependente'],
    },
    {
      id: 'webpathology-pan-43314',
      fonteId: 'webpathology',
      titulo: 'Poliarterite nodosa — necrose fibrinoide da parede arterial',
      tituloOriginal: 'Gallbladder: Polyarteritis Nodosa',
      urlPaginaFonte: 'https://www.webpathology.com/images/gastrointestinal/gallbladder/other-inflammatory-infectious-disorders/43314',
      aumento: 'medio',
      modalidade: 'Histologia — HE',
      descricaoDidatica: 'A parede muscular é substituída por material intensamente eosinofílico e infiltrado inflamatório transmural. Não confunda fibrina intraluminal com necrose fibrinoide da própria parede.',
      oQueObservar: ['perda da arquitetura da média', 'material eosinofílico mural', 'inflamação neutrofílica e mononuclear'],
    },
    {
      id: 'webpathology-pan-43315',
      fonteId: 'webpathology',
      titulo: 'Poliarterite nodosa — trombose e estreitamento luminal',
      tituloOriginal: 'Gallbladder: Polyarteritis Nodosa',
      urlPaginaFonte: 'https://www.webpathology.com/images/gastrointestinal/gallbladder/other-inflammatory-infectious-disorders/43315',
      aumento: 'medio',
      modalidade: 'Histologia — HE',
      descricaoDidatica: 'Relacione o dano endotelial e mural à formação de trombo. A oclusão explica infartos, dor visceral e neuropatia isquêmica em territórios diferentes.',
      oQueObservar: ['trombo aderido à parede lesada', 'redução crítica da luz', 'hemorragia e reparo na adventícia'],
    },
    {
      id: 'webpath-utah-pan-skin117',
      fonteId: 'webpath-utah',
      titulo: 'Poliarterite nodosa — artéria muscular em corte transversal',
      tituloOriginal: 'Muscular artery, polyarteritis nodosa, microscopic',
      urlPaginaFonte: 'https://webpath.med.utah.edu/CVHTML/SKIN117.html',
      urlImagem: 'https://webpath.med.utah.edu/jpeg3/SKIN117.jpg',
      aumento: 'medio',
      modalidade: 'Histologia — HE',
      descricaoDidatica: 'Referência para reconhecer vasculite necrosante de artéria de médio calibre. A ausência de capilarite glomerular e de inflamação de pequenas vênulas ajuda a separar PAN de vasculites ANCA-associadas.',
      oQueObservar: ['artéria muscular de médio calibre', 'inflamação transmural segmentar', 'necrose fibrinoide e possível trombose'],
    },
  ],
  'pericardite-fibrinosa': [
    {
      id: 'webpath-utah-pericardite-diagrama-cv044',
      fonteId: 'webpath-utah',
      titulo: 'Pericardite fibrinosa — esquema do padrão',
      tituloOriginal: 'Fibrinous pericarditis, diagram',
      urlPaginaFonte: 'https://webpath.med.utah.edu/CVHTML/CV044.html',
      urlImagem: 'https://webpath.med.utah.edu/jpeg5/CV044.jpg',
      aumento: 'especial',
      modalidade: 'Esquema anatomopatológico',
      descricaoDidatica: 'O esquema ajuda a entender por que o aumento de permeabilidade deposita fibrina sobre as superfícies pericárdicas. A fricção entre folhetos ásperos produz o atrito auscultatório.',
      oQueObservar: ['fibrina sobre pericárdio visceral e parietal', 'espaço pericárdico entre os folhetos', 'relação com inflamação subjacente'],
    },
    {
      id: 'webpath-utah-pericardite-macro-cv045',
      fonteId: 'webpath-utah',
      titulo: 'Pericardite fibrinosa — aspecto macroscópico',
      tituloOriginal: 'Fibrinous pericarditis, gross',
      urlPaginaFonte: 'https://webpath.med.utah.edu/CVHTML/CV045.html',
      urlImagem: 'https://webpath.med.utah.edu/jpeg5/CV045.jpg',
      aumento: 'macroscopia',
      modalidade: 'Macroscopia',
      descricaoDidatica: 'A superfície perde o brilho e recebe filamentos amarelados de fibrina. O aspecto viloso clássico descreve a textura, mas não identifica sozinho a causa clínica.',
      oQueObservar: ['superfície opaca e áspera', 'filamentos de fibrina entre os folhetos', 'ausência ou presença de pus e sangue'],
    },
    {
      id: 'webpath-utah-pericardite-macro-cv046',
      fonteId: 'webpath-utah',
      titulo: 'Pericardite fibrinosa — distribuição sobre o epicárdio',
      tituloOriginal: 'Fibrinous pericarditis, gross',
      urlPaginaFonte: 'https://webpath.med.utah.edu/CVHTML/CV046.html',
      urlImagem: 'https://webpath.med.utah.edu/jpeg5/CV046.jpg',
      aumento: 'macroscopia',
      modalidade: 'Macroscopia',
      descricaoDidatica: 'Compare áreas recobertas e preservadas e procure extensão difusa. A distribuição ajuda a diferenciar reação sistêmica de foco contíguo localizado.',
      oQueObservar: ['extensão do exsudato', 'espessamento dos folhetos', 'aderências em organização'],
    },
    {
      id: 'webpath-utah-pericardite-micro-cv048',
      fonteId: 'webpath-utah',
      titulo: 'Pericardite fibrinosa — microscopia',
      tituloOriginal: 'Fibrinous pericarditis, microscopic',
      urlPaginaFonte: 'https://webpath.med.utah.edu/CVHTML/CV048.html',
      urlImagem: 'https://webpath.med.utah.edu/jpeg5/CV048.jpg',
      aumento: 'medio',
      modalidade: 'Histologia — HE',
      descricaoDidatica: 'A fibrina forma rede eosinofílica superficial sobre mesotélio lesado, acompanhada por inflamação variável. Em evolução, fibroblastos e capilares organizam o exsudato em aderência fibrosa.',
      oQueObservar: ['rede de fibrina superficial', 'perda ou reatividade do mesotélio', 'neutrófilos, tecido de granulação ou fibrose conforme a fase'],
    },
  ],
  broncopneumonia: [
    {
      id: 'webpath-utah-bronco-macro-lung006',
      fonteId: 'webpath-utah',
      titulo: 'Broncopneumonia — consolidações multifocais',
      tituloOriginal: 'Lung, bronchopneumonia, gross',
      urlPaginaFonte: 'https://webpath.med.utah.edu/LUNGHTML/LUNG006.html',
      urlImagem: 'https://webpath.med.utah.edu/jpeg1/LUNG006.jpg',
      aumento: 'macroscopia',
      modalidade: 'Macroscopia',
      descricaoDidatica: 'Os focos supurativos distribuem-se ao redor de bronquíolos e podem confluir. O padrão lobular, irregular e bilateral contrasta com a consolidação uniforme de um lobo inteiro.',
      oQueObservar: ['focos amarelo-acinzentados mal delimitados', 'distribuição peribrônquica', 'parênquima aerado entre áreas consolidadas'],
    },
    {
      id: 'webpath-utah-bronco-abscesso-lung013',
      fonteId: 'webpath-utah',
      titulo: 'Broncopneumonia abscedada',
      tituloOriginal: 'Lung, abscessing bronchopneumonia, gross',
      urlPaginaFonte: 'https://webpath.med.utah.edu/LUNGHTML/LUNG013.html',
      urlImagem: 'https://webpath.med.utah.edu/jpeg1/LUNG013.jpg',
      aumento: 'macroscopia',
      modalidade: 'Macroscopia',
      descricaoDidatica: 'A necrose liquefativa transforma o foco de pneumonia em cavidade purulenta. Procure comunicação com via aérea e tecido hemorrágico ou necrótico ao redor.',
      oQueObservar: ['cavidade irregular com material purulento', 'destruição do parênquima', 'múltiplos focos satélites'],
    },
    {
      id: 'webpath-utah-bronco-baixo-lung014',
      fonteId: 'webpath-utah',
      titulo: 'Broncopneumonia — visão em pequeno aumento',
      tituloOriginal: 'Lung, bronchopneumonia, low power microscopic',
      urlPaginaFonte: 'https://webpath.med.utah.edu/LUNGHTML/LUNG014.html',
      urlImagem: 'https://webpath.med.utah.edu/jpeg1/LUNG014.jpg',
      aumento: 'pequeno',
      modalidade: 'Histologia — HE',
      descricaoDidatica: 'A baixa magnificação demonstra preenchimento alveolar centrado em bronquíolo, com transição abrupta para parênquima menos comprometido. Essa geografia sustenta o padrão broncopneumônico.',
      oQueObservar: ['bronquíolo no centro do foco', 'alvéolos adjacentes preenchidos por exsudato', 'distribuição descontínua entre lóbulos'],
    },
    {
      id: 'webpath-utah-bronco-alto-lung015',
      fonteId: 'webpath-utah',
      titulo: 'Broncopneumonia — exsudato neutrofílico alveolar',
      tituloOriginal: 'Lung, bronchopneumonia, high power microscopic',
      urlPaginaFonte: 'https://webpath.med.utah.edu/LUNGHTML/LUNG015.html',
      urlImagem: 'https://webpath.med.utah.edu/jpeg1/LUNG015.jpg',
      aumento: 'grande',
      modalidade: 'Histologia — HE',
      descricaoDidatica: 'Em grande aumento, o espaço aéreo contém neutrófilos, fibrina e edema. A parede alveolar deve ser examinada para necrose, dano difuso associado ou organização.',
      oQueObservar: ['neutrófilos intra-alveolares', 'fibrina e material proteináceo', 'congestão dos septos alveolares'],
    },
  ],
}

export function referenciasVisuaisDaDoenca(slug: string): ReferenciaVisualExterna[] {
  return REFERENCIAS_VISUAIS_EXTERNAS[slug] ?? []
}
