import { d } from '@/lib/radiologia/casos-tc-tipos'
import type { QuestaoSemiologia } from './quiz-tipos'

/** Quiz de neurologia. Pacientes fictícios; mídia do acervo licenciado. */
export const QUIZ_NEURO: QuestaoSemiologia[] = [
  {
    id: 'paralisia-facial-bell',
    sinal: 'paralisia-facial-periferica',
    cenario: 'Pronto-socorro',
    identificacao: 'Mulher de 32 anos, professora, gestante de 34 semanas.',
    queixa: 'Acordou com o rosto torto e sem conseguir fechar o olho direito.',
    historia: 'Na véspera sentiu dor atrás da orelha direita. Ao acordar, a água escorreu pelo canto da boca ao escovar os dentes e o olho direito não fechava. Os sons parecem mais altos no ouvido direito e a comida perdeu o gosto na metade da língua. Nega fraqueza nos braços ou nas pernas, dificuldade para falar ou dor de cabeça forte.',
    antecedentes: {
      pessoais: ['Previamente hígida', 'Herpes labial recorrente'],
      gestacionais: ['Primeira gestação, 34 semanas, pré-natal sem intercorrências', 'Pressão arterial normal em todas as consultas'],
      familiares: ['Sem doenças neurológicas'],
      habitos: ['Nega tabagismo e álcool'],
    },
    vitais: { pa: '118 × 74 mmHg', fc: '88 bpm', fr: '16 irpm', satO2: '99% em ar ambiente', temp: '36,6 °C' },
    exame: ['Não enruga a testa à direita', 'Fechamento ocular incompleto à direita, com o globo rodando para cima', 'Apagamento do sulco nasolabial e desvio da boca para a esquerda ao sorrir', 'Força e sensibilidade dos membros normais, sem vesículas no ouvido'],
    pergunta: 'A fotografia mostra outro paciente com o mesmo achado. Qual é a lesão?',
    achado: 'Paralisia facial periférica',
    veredito: 'Paralisia facial periférica idiopática, paralisia de Bell, com hiperacusia e perda do paladar',
    distratores: [
      d('Paralisia facial central por AVC', 'Poupa a testa, porque o andar superior da face recebe fibras dos dois hemisférios, e costuma vir com fraqueza do braço e alteração da fala. Esta paciente não enruga a testa e não tem outros déficits.'),
      d('Síndrome de Ramsay Hunt otológica', 'É paralisia periférica pelo herpes zóster do gânglio geniculado, com dor intensa e vesículas no pavilhão ou no conduto auditivo, além de surdez e vertigem. Não há vesículas aqui.'),
      d('Miastenia gravis com fraqueza facial', 'Causa fraqueza facial bilateral e flutuante, com ptose e diplopia que pioram ao fim do dia, sem perda do paladar nem hiperacusia. O quadro aqui é unilateral e súbito.'),
    ],
    olhar: 'Na foto, compare as duas metades do rosto: do lado afetado a testa fica lisa sem rugas, a pálpebra não fecha e a boca é puxada para o lado sadio. É o andar superior da face acometido que define a lesão periférica.',
    explicacao: 'O nervo facial sai do tronco, atravessa o canal estreito do osso temporal e se distribui por toda a hemiface. Edema inflamatório no canal, provavelmente por reativação do herpes simples, comprime o nervo e paralisa todos os ramos: testa, olho e boca. Ramos que saem dentro do canal explicam a hiperacusia, pelo músculo estapédio, e a perda do paladar nos dois terços anteriores da língua, pela corda do tímpano. Na lesão central, o núcleo que comanda a testa recebe fibras dos dois hemisférios, por isso a testa é poupada. Gestação no terceiro trimestre aumenta a incidência de paralisia de Bell.',
    conduta: 'Corticoide oral nas primeiras 72 horas, permitido na gestação, proteção ocular com lubrificante, oclusão noturna e óculos, e reavaliação; investigar se houver déficits associados, bilateralidade ou ausência de melhora em três meses. Aferir pressão para afastar pré-eclâmpsia.',
  },
  {
    id: 'horner-pancoast',
    sinal: 'sindrome-de-horner',
    cenario: 'Ambulatório de clínica médica',
    identificacao: 'Homem de 63 anos, pedreiro.',
    queixa: 'Dor no ombro e no braço direito há quatro meses e pálpebra caída.',
    historia: 'A dor começou no ombro direito, foi descendo pela face interna do braço até o dedo mínimo e piora à noite. Fez fisioterapia para bursite sem melhora. Há um mês a esposa notou que a pálpebra direita caiu um pouco e que aquele lado do rosto não sua no calor. Perdeu 7 kg.',
    antecedentes: {
      pessoais: ['DPOC', 'Tratado como bursite de ombro'],
      familiares: ['Pai faleceu de câncer de pulmão'],
      habitos: ['Tabagista de 50 maços-ano, ativo'],
    },
    vitais: { pa: '132 × 82 mmHg', fc: '84 bpm', fr: '18 irpm', satO2: '94% em ar ambiente', temp: '36,7 °C' },
    exame: ['Ptose discreta à direita com elevação da pálpebra inferior', 'Pupila direita menor, com anisocoria maior no escuro', 'Anidrose na hemiface direita', 'Fraqueza e atrofia dos músculos intrínsecos da mão direita'],
    pergunta: 'A fotografia mostra o olho de outro paciente com o mesmo achado. Qual é a síndrome?',
    achado: 'Síndrome de Claude Bernard-Horner',
    veredito: 'Síndrome de Horner à direita por tumor do ápice pulmonar, tumor de Pancoast',
    distratores: [
      d('Paralisia do terceiro nervo craniano', 'Também causa ptose, mas acentuada, com pupila dilatada e olho desviado para baixo e para fora. A pupila deste paciente é menor, não maior.'),
      d('Pupila tônica de Adie', 'É pupila dilatada que reage pouco à luz e lentamente à convergência, em mulheres jovens, sem ptose nem anidrose. Aqui a pupila afetada é a menor.'),
      d('Ptose aponeurótica senil', 'Cai a pálpebra pelo afrouxamento da aponeurose do levantador, com prega palpebral alta e pupilas iguais. Este paciente tem miose e anidrose do mesmo lado.'),
    ],
    olhar: 'Na foto, compare os olhos: de um lado a pálpebra superior desce um ou dois milímetros e a inferior sobe, deixando a fenda menor, e a pupila é menor. A diferença entre as pupilas fica maior no escuro, quando a pupila sadia dilata e a afetada não.',
    explicacao: 'A via simpática do olho tem três neurônios: do hipotálamo à medula torácica alta, da medula ao gânglio cervical superior passando pelo ápice do pulmão e do gânglio ao olho pela carótida. A interrupção tira o músculo dilatador da pupila, que fica menor, o músculo de Müller, que dá a ptose leve, e as fibras sudomotoras da face. Um tumor no ápice do pulmão invade a cadeia simpática e o plexo braquial inferior, C8 e T1, explicando a dor que desce para o dedo mínimo e a atrofia da mão. Tabagismo e emagrecimento completam o tumor de Pancoast.',
    conduta: 'Radiografia e tomografia de tórax com atenção ao ápice, ressonância do plexo braquial, biópsia e estadiamento, e tratamento oncológico combinado.',
  },
  {
    id: 'tremor-repouso-parkinson',
    sinal: 'tremor-de-repouso',
    midia: 1,
    cenario: 'Ambulatório de neurologia',
    identificacao: 'Homem de 67 anos, marceneiro aposentado.',
    queixa: 'Tremor na mão direita há um ano e lentidão para fazer as coisas.',
    historia: 'O tremor começou no polegar e no indicador da mão direita, aparece quando a mão está parada no colo e some quando ele pega um copo. Ficou mais lento para se vestir e abotoar camisa, a letra diminuiu e a esposa diz que ele quase não mexe o rosto. Há anos perdeu o olfato e se mexe muito dormindo, como se brigasse em sonhos.',
    antecedentes: {
      pessoais: ['Constipação intestinal há vários anos', 'Depressão tratada há três anos'],
      familiares: ['Sem tremor ou Parkinson na família'],
      habitos: ['Trabalhou anos com pesticidas na lavoura antes da marcenaria', 'Nunca fumou', 'Nega uso de antipsicóticos ou metoclopramida'],
    },
    vitais: { pa: '128 × 78 mmHg deitado e 104 × 66 mmHg em pé', fc: '70 bpm', fr: '14 irpm', satO2: '98% em ar ambiente', temp: '36,4 °C' },
    exame: ['Tremor de repouso de 4 a 6 Hz na mão direita que some ao movimento', 'Bradicinesia com decremento na abertura e fechamento da mão direita', 'Rigidez em roda denteada no punho direito', 'Hipomimia e diminuição do balanço do braço direito ao andar'],
    pergunta: 'Assista ao vídeo do tremor. Qual é o tipo de tremor e a síndrome que ele sugere?',
    achado: 'Tremor de repouso parkinsoniano',
    veredito: 'Tremor de repouso em contar dinheiro dentro de uma síndrome parkinsoniana assimétrica: doença de Parkinson provável',
    distratores: [
      d('Tremor essencial postural e cinético', 'Aparece ao manter as mãos estendidas e ao usar, como ao levar o copo à boca, é bilateral, melhora com álcool e tem história familiar. O tremor deste paciente some ao movimento.'),
      d('Parkinsonismo induzido por drogas', 'Também dá tremor e lentidão, mas simétrico, após antipsicóticos, metoclopramida ou flunarizina. Este paciente não usa essas drogas e o quadro é assimétrico.'),
      d('Tremor cerebelar de intenção com dismetria', 'Piora ao se aproximar do alvo, como na prova índex-nariz, com dismetria e marcha atáxica. Este tremor aparece com a mão parada e diminui ao agir.'),
    ],
    olhar: 'No vídeo, veja a mão apoiada e relaxada tremer num ritmo lento, com o polegar esfregando o indicador como quem conta dinheiro ou enrola uma pílula. Repare que o tremor diminui ou some quando a mão inicia um movimento e volta após alguns segundos parada.',
    explicacao: 'A perda de neurônios dopaminérgicos da substância negra desequilibra o circuito dos núcleos da base. O resultado é a tríade motora: bradicinesia, obrigatória para o diagnóstico, rigidez e tremor de repouso, que começa num lado e permanece assimétrico. Muito antes dos sinais motores, a doença já atinge o tronco e o olfato, o que explica a anosmia, a constipação, a depressão e o transtorno comportamental do sono REM, quando o paciente encena os sonhos. A hipotensão ortostática é disautonomia. Exposição a pesticidas é fator de risco descrito.',
    conduta: 'Diagnóstico clínico pelos critérios da Movement Disorder Society, levodopa ou agonista dopaminérgico conforme idade e incapacidade, fisioterapia e atividade física regular, manejo da hipotensão ortostática e da constipação.',
  },
  {
    id: 'asterixe-encefalopatia',
    sinal: 'asterixe',
    cenario: 'Pronto-socorro',
    identificacao: 'Homem de 56 anos, ex-funcionário de bar.',
    queixa: 'Confuso e sonolento há dois dias, segundo a família.',
    historia: 'A esposa conta que ele começou trocando o dia pela noite, depois ficou confuso e hoje responde devagar. Está com prisão de ventre há quatro dias e as fezes ficaram escuras ontem. Tem cirrose conhecida e já foi internado por barriga d’água.',
    antecedentes: {
      pessoais: ['Cirrose alcoólica Child-Pugh B', 'Ascite tratada com espironolactona e furosemida', 'Varizes de esôfago em profilaxia com propranolol'],
      familiares: ['Pai etilista, falecido por cirrose'],
      habitos: ['Abstinente há seis meses', 'Uso recente de comprimido para dormir por conta própria'],
    },
    vitais: { pa: '102 × 64 mmHg', fc: '92 bpm', fr: '18 irpm', satO2: '96% em ar ambiente', temp: '36,9 °C' },
    exame: ['Sonolento, desorientado no tempo, obedece a comandos', 'Hálito adocicado', 'Icterícia, aranhas vasculares e ascite moderada', 'Toque retal com melena'],
    pergunta: 'Assista ao vídeo das mãos estendidas. Qual é o sinal?',
    achado: 'Asterixe da encefalopatia hepática',
    veredito: 'Asterixe, ou flapping, na encefalopatia hepática desencadeada por sangramento digestivo, constipação e sedativo',
    distratores: [
      d('Tremor essencial das mãos', 'É rítmico, regular e contínuo nas mãos estendidas, sem confusão nem doença hepática. O movimento do vídeo é uma queda irregular e arrítmica da postura.'),
      d('Mioclonias multifocais', 'São abalos positivos, súbitos e breves de contração muscular em várias regiões. O asterixe é o contrário: uma perda breve do tônus que deixa a mão cair.'),
      d('Crise focal motora clônica', 'Produz abalos rítmicos de um lado do corpo, que podem marchar pelo membro, com eletroencefalograma epiléptico. O movimento aqui é bilateral, irregular e só com postura mantida.'),
    ],
    olhar: 'No vídeo, veja o paciente manter os braços estendidos e os punhos dorsifletidos: a cada poucos segundos as mãos caem de repente e voltam, como uma ave batendo as asas. É uma interrupção do tônus, não uma contração.',
    explicacao: 'O asterixe é uma mioclonia negativa: lapsos breves no tônus postural por disfunção dos circuitos que sustentam a postura. Na cirrose, a amônia e outras toxinas intestinais escapam da depuração hepática, pelos desvios portossistêmicos, e alteram a neurotransmissão cerebral. Os desencadeantes clássicos estão todos aqui: sangramento digestivo, que oferece uma carga de proteína no intestino, constipação, que aumenta a absorção, e o sedativo. O sinal não é exclusivo do fígado: uremia, hipercapnia e intoxicações também o produzem.',
    conduta: 'Tratar o sangramento com endoscopia e vasoativo, lactulose para duas a três evacuações pastosas por dia, rifaximina, suspender o sedativo, corrigir distúrbios eletrolíticos e investigar infecção, incluindo paracentese para peritonite bacteriana espontânea.',
  },
  {
    id: 'babinski-mielopatia',
    sinal: 'sinal-de-babinski',
    midia: 2,
    cenario: 'Ambulatório de neurologia',
    identificacao: 'Mulher de 58 anos, costureira.',
    queixa: 'Pernas duras, desequilíbrio e mãos desajeitadas há oito meses.',
    historia: 'Há oito meses tem dificuldade para abotoar roupas e costurar, deixa cair objetos e sente as mãos dormentes. As pernas ficaram rígidas e ela tropeça. Há dois meses precisa correr ao banheiro para urinar. Sente dor no pescoço há anos, pior ao olhar para cima.',
    antecedentes: {
      pessoais: ['Cervicalgia crônica', 'Hipertensão'],
      gestacionais: ['Quatro gestações'],
      familiares: ['Sem doenças neurológicas hereditárias'],
      habitos: ['Trabalha há 30 anos com o pescoço fletido na máquina de costura'],
    },
    vitais: { pa: '138 × 84 mmHg', fc: '74 bpm', fr: '14 irpm', satO2: '98% em ar ambiente', temp: '36,5 °C' },
    exame: ['Hiperreflexia nos quatro membros com sinal de Hoffmann bilateral', 'Espasticidade nos membros inferiores com clônus aquileu', 'Hipotrofia dos músculos intrínsecos das mãos', 'Marcha de base alargada e Romberg positivo'],
    pergunta: 'Assista ao vídeo do estímulo plantar. Qual é a resposta e o que ela indica?',
    achado: 'Sinal de Babinski por lesão piramidal',
    veredito: 'Sinal de Babinski: lesão do neurônio motor superior, aqui por mielopatia cervical espondilótica',
    distratores: [
      d('Reflexo cutâneo plantar em flexão', 'É a resposta normal do adulto: os dedos fletem para baixo ao estímulo da borda lateral da planta. No vídeo, o hálux se estende para cima.'),
      d('Resposta de retirada ao estímulo', 'É o pé inteiro que foge do estímulo doloroso ou das cócegas, com flexão do quadril e do joelho, sem extensão lenta e sustentada do hálux.'),
      d('Neuropatia periférica sensitivo-motora', 'Daria arreflexia, fraqueza distal flácida e perda de sensibilidade em bota, com resposta plantar indiferente ou em flexão. Esta paciente tem hiperreflexia e espasticidade.'),
    ],
    olhar: 'No vídeo, observe o estímulo deslizando pela borda lateral da planta do calcanhar até a base dos dedos: o hálux se estende lentamente para cima e os outros dedos se abrem em leque. É essa extensão do hálux que define o sinal.',
    explicacao: 'O reflexo cutâneo plantar normal em flexão depende da integridade do trato corticoespinal. No recém-nascido, com o trato ainda não mielinizado, a resposta é em extensão; quando o trato é lesado em qualquer ponto, do córtex à medula, o padrão primitivo reaparece. Nesta paciente, osteófitos e discos degenerados estreitam o canal cervical e comprimem a medula: o neurônio motor superior das pernas explica a espasticidade, a hiperreflexia, o clônus e o Babinski; a compressão das raízes e da substância cinzenta no nível cervical explica a atrofia das mãos; a coluna posterior lesada explica o Romberg.',
    conduta: 'Ressonância da coluna cervical, eletroneuromiografia se houver dúvida com doença do neurônio motor, dosar vitamina B12 e cobre, e avaliação neurocirúrgica para descompressão nos casos progressivos.',
  },
  {
    id: 'miastenia-ptose',
    sinal: 'ptose-fatigavel',
    cenario: 'Ambulatório de neurologia',
    identificacao: 'Mulher de 28 anos, operadora de telemarketing.',
    queixa: 'Pálpebras caindo e visão dupla no fim do dia há três meses.',
    historia: 'Acorda bem, mas no fim da tarde as pálpebras caem, alternando de lado, e ela passa a ver dobrado ao assistir televisão. Há duas semanas sente cansaço para mastigar carne e a voz fica fanhosa quando fala muito no trabalho. Descansar os olhos melhora.',
    antecedentes: {
      pessoais: ['Hipotireoidismo autoimune em uso de levotiroxina', 'Vitiligo'],
      gestacionais: ['Nuligesta'],
      familiares: ['Mãe com artrite reumatoide'],
      habitos: ['Uso recente de ciprofloxacino para infecção urinária, com piora dos sintomas'],
    },
    vitais: { pa: '114 × 72 mmHg', fc: '76 bpm', fr: '14 irpm', satO2: '99% em ar ambiente', temp: '36,4 °C' },
    exame: ['Ptose que piora após olhar para cima por 60 segundos', 'Melhora da ptose após dois minutos de gelo sobre a pálpebra', 'Diplopia ao olhar lateral sustentado', 'Pupilas normais e reflexos tendinosos preservados'],
    pergunta: 'Assista ao vídeo da pálpebra. Qual é o achado e a doença?',
    achado: 'Ptose fatigável da miastenia gravis',
    veredito: 'Ptose fatigável da miastenia gravis, com piora ao esforço, melhora com o gelo e sinais bulbares iniciais',
    distratores: [
      d('Síndrome de Horner simpática', 'Causa ptose leve e fixa com miose e anidrose do mesmo lado, sem variação ao longo do dia nem diplopia. As pupilas desta paciente são normais e a ptose flutua.'),
      d('Paralisia do terceiro nervo craniano', 'Dá ptose fixa com pupila dilatada e olho desviado para baixo e para fora, sem melhora com repouso ou gelo. Aqui a pupila é normal e a ptose varia.'),
      d('Distrofia miotônica de Steinert', 'Produz ptose bilateral e face alongada com fraqueza distal, miotonia ao apertar a mão, catarata e calvície frontal, de evolução lenta, sem flutuação diária.'),
    ],
    olhar: 'No vídeo, acompanhe a pálpebra durante o olhar sustentado para cima: ela vai descendo aos poucos. Quando se levanta a pálpebra mais caída com o dedo, a do outro olho cai — a lei de Hering, porque o comando para levantar as duas é o mesmo.',
    explicacao: 'Na miastenia gravis, anticorpos contra o receptor de acetilcolina, ou contra MuSK, reduzem os receptores disponíveis na junção neuromuscular. A cada contração repetida, menos acetilcolina é liberada e menos fibras respondem: a fraqueza piora com o uso e melhora com o repouso. Os músculos oculares são os primeiros e muitas vezes os únicos. O frio melhora a transmissão porque reduz a ação da acetilcolinesterase — daí o teste do gelo. A associação com outras doenças autoimunes é frequente, e antibióticos como fluoroquinolonas e aminoglicosídeos pioram a doença.',
    conduta: 'Anticorpos antirreceptor de acetilcolina e anti-MuSK, eletroneuromiografia com estimulação repetitiva e fibra única, tomografia de tórax para timoma, piridostigmina, imunossupressão conforme a gravidade, timectomia em casos selecionados e orientação sobre drogas que pioram a crise.',
  },
  {
    id: 'trousseau-hipocalcemia',
    sinal: 'sinal-de-trousseau',
    cenario: 'Enfermaria de cirurgia',
    identificacao: 'Mulher de 45 anos, segundo dia após tireoidectomia total.',
    queixa: 'Formigamento em volta da boca e nas pontas dos dedos desde a manhã.',
    historia: 'Foi operada de bócio multinodular volumoso há dois dias. Hoje acordou com formigamento perioral e nas mãos, câimbras nas pernas e sensação de que as mãos ficam travadas. Está ansiosa e respirando rápido.',
    antecedentes: {
      pessoais: ['Bócio multinodular mergulhante com compressão traqueal', 'Tireoidectomia total há dois dias'],
      gestacionais: ['Duas gestações'],
      familiares: ['Mãe e irmã com bócio'],
      habitos: ['Morou na infância em região de deficiência de iodo'],
    },
    vitais: { pa: '128 × 80 mmHg', fc: '96 bpm', fr: '22 irpm', satO2: '98% em ar ambiente', temp: '36,8 °C' },
    exame: ['Espasmo carpal após três minutos com o manguito acima da pressão sistólica', 'Contração do canto da boca à percussão do nervo facial', 'Ferida operatória sem hematoma', 'Eletrocardiograma com intervalo QT prolongado'],
    pergunta: 'A fotografia mostra a mão de outro paciente durante o mesmo teste. Qual é o sinal e o distúrbio?',
    achado: 'Sinal de Trousseau da hipocalcemia',
    veredito: 'Sinal de Trousseau por hipocalcemia aguda após lesão das paratireoides na tireoidectomia',
    distratores: [
      d('Contratura de Dupuytren palmar', 'Flete os dedos de forma fixa e indolor por espessamento da fáscia palmar, com cordões palpáveis, ao longo de anos. O espasmo aqui surge com o manguito e desaparece ao soltá-lo.'),
      d('Mão em garra ulnar', 'Hiperestende as metacarpofalângicas e flete as interfalângicas do quarto e quinto dedos de forma permanente, por lesão do ulnar. O espasmo carpal flete as metacarpofalângicas e estende as interfalângicas.'),
      d('Alcalose respiratória por ansiedade isolada', 'Também provoca parestesias e espasmo carpal ao reduzir o cálcio ionizado, mas o cálcio total fica normal e não há cirurgia cervical recente. A taquipneia aqui é consequência, não causa.'),
    ],
    olhar: 'Na foto, veja a posição da mão: punho e metacarpofalângicas fletidos, interfalângicas estendidas e polegar aduzido — a mão de parteiro. Ela aparece quando o manguito insufla acima da pressão sistólica e deixa o nervo isquêmico.',
    explicacao: 'A queda do cálcio ionizado aumenta a permeabilidade ao sódio das membranas dos nervos e reduz o limiar de disparo; o nervo passa a descarregar espontaneamente, causando parestesias e espasmos. O manguito acrescenta isquemia ao nervo mediano e ulnar e revela a hiperexcitabilidade latente. As paratireoides ficam coladas à tireoide, e na tireoidectomia total podem ser retiradas, desvascularizadas ou traumatizadas, o que explica a hipocalcemia no primeiro ou segundo dia. O QT longo mostra que o coração também sente.',
    conduta: 'Dosar cálcio iônico, magnésio, fósforo e paratormônio, gluconato de cálcio venoso lento em sintomáticos com monitorização, depois cálcio oral e calcitriol, e corrigir o magnésio.',
  },
  {
    id: 'kayser-fleischer-wilson',
    sinal: 'anel-de-kayser-fleischer',
    cenario: 'Ambulatório de hepatologia',
    identificacao: 'Rapaz de 19 anos, universitário.',
    queixa: 'Tremor nas mãos, fala arrastada e notas caindo na faculdade.',
    historia: 'Há um ano a família notou mudança de comportamento, com irritabilidade e queda no rendimento. Há seis meses surgiu tremor nas mãos que piora ao segurar o copo e a fala ficou arrastada. Um exame mostrou enzimas do fígado alteradas e plaquetas baixas.',
    antecedentes: {
      pessoais: ['Hepatite aguda sem causa definida aos 14 anos', 'Episódio de anemia hemolítica'],
      gestacionais: ['Sem intercorrências'],
      familiares: ['Pais primos de segundo grau', 'Irmã mais velha falecida aos 16 anos por insuficiência hepática aguda'],
      habitos: ['Nega álcool e drogas'],
    },
    vitais: { pa: '116 × 72 mmHg', fc: '78 bpm', fr: '14 irpm', satO2: '99% em ar ambiente', temp: '36,5 °C' },
    exame: ['Anel acastanhado na periferia da córnea, mais denso nos polos superior e inferior', 'Tremor em bater de asas ao estender os braços', 'Disartria e distonia leve na face', 'Esplenomegalia discreta'],
    pergunta: 'A fotografia mostra o olho de outro paciente com o mesmo achado. Qual é o achado e a doença?',
    achado: 'Anel de Kayser-Fleischer da doença de Wilson',
    veredito: 'Anel de Kayser-Fleischer da doença de Wilson com acometimento neurológico e hepático',
    distratores: [
      d('Arco corneano senil ou lipídico', 'É anel branco-acinzentado na periferia da córnea, separado do limbo por uma faixa clara, ligado à idade ou à dislipidemia. O anel deste paciente é castanho-dourado e chega ao limbo.'),
      d('Anel de pigmento da hemocromatose', 'A hemocromatose pigmenta a pele de bronze e acomete fígado, pâncreas e articulações, mas não forma anel corneano. Este paciente é jovem com doença neuropsiquiátrica e hepática.'),
      d('Esclerite anterior difusa', 'Avermelha intensamente a esclera com dor profunda que acorda o paciente, sem anel pigmentado na córnea. O olho aqui não está inflamado.'),
    ],
    olhar: 'Na foto, olhe a borda da córnea junto ao limbo: uma faixa castanho-dourada ou esverdeada, mais evidente em cima e embaixo, que pode escurecer a borda de uma íris clara. Em olhos escuros, muitas vezes só a lâmpada de fenda mostra.',
    explicacao: 'A doença de Wilson é autossômica recessiva, por mutação no ATP7B, que transporta o cobre do hepatócito para a bile e para a ceruloplasmina. O cobre acumula primeiro no fígado, causando hepatite e cirrose, e depois extravasa para o sangue e se deposita nos núcleos da base, causando tremor, disartria, distonia e sintomas psiquiátricos, e na membrana de Descemet da córnea, formando o anel. A hemólise ocorre quando o cobre livre é liberado de uma vez. Quase todos os pacientes com doença neurológica têm o anel. A consanguinidade e a irmã com insuficiência hepática fulminante são pistas fortes.',
    conduta: 'Ceruloplasmina, cobre urinário de 24 horas, lâmpada de fenda e, se necessário, cobre hepático e teste genético; quelante como penicilamina ou trientina, ou zinco, dieta pobre em cobre, tratamento para toda a vida e rastreio dos irmãos.',
  },
]
