import { d } from '@/lib/radiologia/casos-tc-tipos'
import type { QuestaoSemiologia } from './quiz-tipos'

/** Quiz cardiovascular e respiratório. Pacientes fictícios; mídia do acervo licenciado. */
export const QUIZ_CARDIORRESPIRATORIO: QuestaoSemiologia[] = [
  {
    id: 'estenose-aortica-sincope',
    sinal: 'sopro-de-estenose-aortica',
    cenario: 'Ambulatório de cardiologia',
    identificacao: 'Homem de 78 anos, contador aposentado.',
    queixa: 'Desmaiou duas vezes ao subir a ladeira de casa.',
    historia: 'Há seis meses sente aperto no peito e falta de ar ao caminhar rápido, que passam com repouso. No último mês desmaiou duas vezes durante esforço, recuperando-se em segundos, sem convulsão. Um médico do posto ouviu um sopro há anos e disse que era coisa da idade.',
    antecedentes: {
      pessoais: ['Hipertensão e dislipidemia', 'Doença renal crônica leve'],
      familiares: ['Sem cardiopatias congênitas conhecidas'],
      habitos: ['Ex-tabagista de 30 maços-ano', 'Sedentário'],
    },
    vitais: { pa: '118 × 86 mmHg', fc: '68 bpm', fr: '16 irpm', satO2: '96% em ar ambiente', temp: '36,4 °C' },
    exame: ['Pulso carotídeo de ascensão lenta e amplitude reduzida', 'Ictus sustentado, não desviado', 'Frêmito sistólico no foco aórtico', 'Segunda bulha inaudível no foco aórtico'],
    pergunta: 'Ouça a gravação do foco aórtico, com fone de ouvido. Qual é o achado auscultatório que responde ao quadro?',
    achado: 'Sopro ejetivo de estenose aórtica grave',
    veredito: 'Sopro sistólico ejetivo rude em diamante com B2 ausente: estenose aórtica grave calcífica e sintomática',
    distratores: [
      d('Sopro de insuficiência mitral crônica', 'É holossistólico, em platô, mais audível no ápice e irradiado para a axila, com B1 hipofonética. O sopro deste paciente é em diamante no foco aórtico, com pulso lento e B2 que sumiu.'),
      d('Esclerose aórtica sem obstrução', 'Produz sopro ejetivo curto e suave no foco aórtico em idosos, mas com pulso carotídeo normal, B2 preservada e sem sintomas. Aqui há síncope, angina e B2 inaudível.'),
      d('Cardiomiopatia hipertrófica obstrutiva', 'Dá sopro sistólico e síncope ao esforço, mas em jovens, mais audível na borda esternal esquerda, que aumenta com Valsalva e ao ficar em pé, com pulso bífido. Este é um idoso com pulso lento e tardio.'),
    ],
    olhar: 'Na gravação, procure o sopro que começa logo depois da primeira bulha, cresce até o meio da sístole e decresce, com timbre rude, como um diamante. Repare no que falta: a segunda bulha quase não aparece, porque a valva calcificada não fecha de forma audível.',
    explicacao: 'A calcificação degenerativa da valva aórtica reduz progressivamente a área de abertura. O ventrículo esquerdo hipertrofia para gerar pressão, e o fluxo turbulento pelo orifício estreito produz o sopro ejetivo. Quanto mais grave, mais tardio é o pico do sopro, mais lento e fraco o pulso carotídeo e mais apagada a B2. A tríade de sintomas — angina, síncope e insuficiência cardíaca — marca a fase em que a sobrevida cai de forma abrupta sem troca valvar. A síncope ao esforço acontece porque o débito não aumenta através da valva fixa enquanto a vasodilatação muscular derruba a pressão.',
    conduta: 'Ecocardiograma com gradiente e área valvar, evitar esforço intenso e vasodilatadores, e encaminhar para troca valvar cirúrgica ou implante transcateter, decidida em equipe conforme risco e anatomia.',
  },
  {
    id: 'terceira-bulha-cardiomiopatia',
    sinal: 'terceira-bulha',
    cenario: 'Pronto-socorro',
    identificacao: 'Mulher de 38 anos, cabeleireira, há quatro meses do parto.',
    queixa: 'Falta de ar que piora deitada e inchaço nas pernas há três semanas.',
    historia: 'Teve o terceiro filho há quatro meses, parto normal sem intercorrências. Há três semanas começou a cansar para amamentar e subir escadas, passou a dormir com três travesseiros e acorda à noite com falta de ar. As pernas incharam e ela ganhou 5 kg em duas semanas.',
    antecedentes: {
      pessoais: ['Pré-eclâmpsia na última gestação', 'Sem cardiopatia prévia'],
      gestacionais: ['Três gestações, a última gemelar', 'Pré-eclâmpsia com sulfato de magnésio no parto'],
      familiares: ['Sem cardiomiopatia conhecida'],
      habitos: ['Nega álcool e drogas', 'Amamentando'],
    },
    vitais: { pa: '104 × 72 mmHg', fc: '112 bpm', fr: '26 irpm', satO2: '92% em ar ambiente', temp: '36,6 °C' },
    exame: ['Ictus desviado para a esquerda e para baixo', 'Turgência jugular a 45 graus', 'Estertores crepitantes em bases', 'Edema depressível até os joelhos'],
    pergunta: 'Ouça a gravação no ápice, em decúbito lateral esquerdo e com a campânula. Qual é o som extra que responde ao quadro?',
    achado: 'Terceira bulha em galope ventricular',
    veredito: 'Galope de terceira bulha: disfunção ventricular esquerda com sobrecarga de volume na cardiomiopatia periparto',
    distratores: [
      d('Quarta bulha por hipertrofia', 'É grave, mas vem logo antes da primeira bulha, pela contração atrial contra um ventrículo rígido. O som desta gravação vem logo depois da segunda bulha.'),
      d('Desdobramento fixo da segunda bulha', 'São dois componentes próximos da segunda bulha que não variam com a respiração, na comunicação interatrial. O som extra aqui é grave e mais afastado, no início da diástole.'),
      d('Estalido de abertura mitral', 'Aparece logo após a segunda bulha, mas é agudo e seco, seguido de ruflar diastólico, na estenose mitral reumática. O som desta gravação é grave e abafado.'),
    ],
    olhar: 'Na gravação, conte as batidas: depois do par tum-tá aparece um terceiro som grave e abafado logo após a segunda bulha, formando o ritmo de galope, como a palavra Ken-tu-cky. Fica mais claro com a campânula no ápice e a paciente virada para a esquerda.',
    explicacao: 'A terceira bulha nasce no início da diástole, quando o sangue entra rápido num ventrículo dilatado e com pressão elevada, e a parede desacelera o fluxo de forma brusca. No jovem e na gestante pode ser fisiológica; num adulto com dispneia, ortopneia e congestão, indica disfunção sistólica com sobrecarga de volume. A cardiomiopatia periparto surge no último mês da gestação ou nos cinco meses seguintes, com fatores de risco como multiparidade, gestação gemelar, pré-eclâmpsia e idade materna mais alta — todos presentes aqui.',
    conduta: 'Ecocardiograma, peptídeo natriurético, diurético para a congestão, tratamento da insuficiência cardíaca compatível com a amamentação, discutir bromocriptina em centro especializado, anticoagulação se fração de ejeção muito baixa e contracepção, pelo risco de recorrência em nova gestação.',
  },
  {
    id: 'turgencia-jugular-icc',
    sinal: 'turgencia-jugular',
    cenario: 'Enfermaria de clínica médica',
    identificacao: 'Homem de 69 anos, aposentado.',
    queixa: 'Barriga e pernas inchadas e cansaço há dois meses.',
    historia: 'Há dois meses sente cansaço, perda de apetite e saciedade precoce. As pernas incharam, a barriga cresceu e ele sente peso do lado direito, abaixo das costelas. Nega falta de ar deitado. Teve febre reumática na juventude e foi operado do coração há 20 anos.',
    antecedentes: {
      pessoais: ['Febre reumática na adolescência', 'Troca da valva mitral há 20 anos', 'Fibrilação atrial em uso de varfarina'],
      familiares: ['Sem cardiopatias familiares'],
      habitos: ['Abandonou o diurético há três meses', 'Dieta rica em sal'],
    },
    vitais: { pa: '108 × 70 mmHg', fc: '94 bpm, irregular', fr: '20 irpm', satO2: '95% em ar ambiente', temp: '36,4 °C' },
    exame: ['Distensão das veias do pescoço sentado a 90 graus, com pulsação sistólica', 'Fígado aumentado, doloroso e pulsátil, com refluxo hepatojugular', 'Sopro holossistólico em borda esternal esquerda baixa que aumenta na inspiração', 'Ascite e edema de membros inferiores'],
    pergunta: 'A fotografia mostra o pescoço de outro paciente com o mesmo achado. O que o achado indica?',
    achado: 'Pressão venosa jugular muito elevada',
    veredito: 'Turgência jugular: pressão venosa central elevada por insuficiência cardíaca direita com insuficiência tricúspide',
    distratores: [
      d('Síndrome da veia cava superior', 'Também distende as jugulares, mas sem pulsação, com edema e pletora de face e braços e circulação colateral no tórax, sem refluxo hepatojugular. As veias deste paciente pulsam e o fígado está congesto.'),
      d('Pulso carotídeo amplo da insuficiência aórtica', 'É pulsação arterial palpável, rápida e com queda abrupta, que não varia com a posição nem com a respiração. A pulsação das jugulares não se palpa e muda com a posição.'),
      d('Bócio mergulhante comprimindo veias', 'Comprime as veias de forma fixa, com massa cervical que sobe com a deglutição e sinal de Pemberton. Este paciente não tem massa e a distensão pulsa com o ciclo cardíaco.'),
    ],
    olhar: 'Na foto, veja a veia que desenha um cordão distendido ao longo do pescoço com o paciente sentado. Com o tronco a 45 graus, a coluna de sangue não deveria passar de 3 a 4 cm acima do ângulo esternal; quando a veia fica cheia mesmo sentado, a pressão no átrio direito está alta.',
    explicacao: 'A veia jugular interna funciona como um manômetro do átrio direito. Quando o ventrículo direito falha ou a valva tricúspide vaza, a pressão sobe para trás e a coluna de sangue se eleva no pescoço. Na insuficiência tricúspide, a onda v gigante faz a jugular pulsar em sístole, o fígado congesto também pulsa, e o sopro aumenta na inspiração porque o retorno venoso ao coração direito cresce — o sinal de Rivero-Carvallo. Doença mitral reumática de longa data leva à hipertensão pulmonar e à falência do coração direito, agravada aqui pela suspensão do diurético e pelo sal.',
    conduta: 'Diurético venoso, restrição de sódio, controle da frequência da fibrilação atrial, ecocardiograma para avaliar a prótese mitral, a pressão pulmonar e a tricúspide, e ajuste da anticoagulação.',
  },
  {
    id: 'baqueteamento-osteoartropatia',
    sinal: 'baqueteamento-digital',
    cenario: 'Ambulatório de pneumologia',
    identificacao: 'Homem de 52 anos, ex-funcionário de estaleiro.',
    queixa: 'Tosse seca e falta de ar progressiva há um ano; notou as unhas diferentes.',
    historia: 'Há um ano tem tosse seca e cansaço que evoluiu de subir ladeiras para andar no plano. Perdeu 6 kg. A esposa reparou que as pontas dos dedos ficaram grossas e as unhas curvadas. Há dois meses sente dor nos punhos e nos tornozelos.',
    antecedentes: {
      pessoais: ['Sem doenças crônicas conhecidas'],
      familiares: ['Pai faleceu de câncer de pulmão'],
      habitos: ['Trabalhou 20 anos cortando placas isolantes com amianto sem proteção', 'Tabagista de 40 maços-ano'],
    },
    vitais: { pa: '128 × 80 mmHg', fc: '92 bpm', fr: '22 irpm', satO2: '90% em ar ambiente', temp: '36,6 °C' },
    exame: ['Falanges distais alargadas com unhas convexas', 'Perda do ângulo entre a unha e a prega ungueal', 'Estertores finos em bases', 'Edema doloroso em punhos e tornozelos'],
    pergunta: 'A fotografia mostra as mãos de outro paciente com o mesmo achado. Qual é o sinal?',
    achado: 'Baqueteamento digital com osteoartropatia',
    veredito: 'Baqueteamento digital com osteoartropatia hipertrófica, que exige investigar câncer de pulmão e asbestose',
    distratores: [
      d('Unha em colher da ferropenia', 'É a coiloníquia: unha fina e côncava, que segura uma gota de água, por deficiência de ferro. As unhas deste paciente são convexas e as falanges estão alargadas.'),
      d('Nódulos de Heberden da osteoartrite', 'São nódulos ósseos nas interfalângicas distais, nas articulações, sem alterar a unha nem a polpa. Aqui a polpa da falange inteira aumentou e a unha curvou.'),
      d('Paroníquia crônica com edema', 'Inflama a prega ungueal com vermelhidão e perda da cutícula, geralmente em um ou poucos dedos, em quem molha as mãos. O alargamento aqui é simétrico em todos os dedos.'),
    ],
    olhar: 'Na foto, olhe o dedo de perfil: o ângulo entre a unha e a pele da prega, normalmente de cerca de 160 graus, desapareceu e passou de 180. A polpa ficou bulbosa como baqueta de tambor. Juntando as unhas de dois dedos opostos, a janela em losango entre elas some — o sinal de Schamroth.',
    explicacao: 'O baqueteamento resulta do aumento do tecido conjuntivo e da vascularização da polpa digital. Uma das explicações é que megacariócitos e agregados de plaquetas, que normalmente ficam retidos no pulmão, passam por desvios ou leitos alterados e chegam aos dedos, liberando fatores de crescimento como PDGF e VEGF. Câncer de pulmão, doenças supurativas, fibrose pulmonar, cardiopatias cianóticas e doença inflamatória intestinal são causas clássicas. Quando o baqueteamento vem com dor e edema nos punhos e tornozelos, é a osteoartropatia hipertrófica, que tem forte associação com câncer de pulmão. Exposição ao amianto e tabagismo multiplicam esse risco.',
    conduta: 'Tomografia de tórax, espirometria com difusão, investigar asbestose, mesotelioma e carcinoma brônquico, radiografia de ossos longos para periostite e cessação do tabagismo.',
  },
  {
    id: 'janeway-endocardite',
    sinal: 'lesoes-de-janeway',
    cenario: 'Pronto-socorro',
    identificacao: 'Homem de 29 anos, desempregado.',
    queixa: 'Febre há duas semanas, calafrios e manchas nas palmas e nas plantas.',
    historia: 'Há duas semanas tem febre diária com calafrios, sudorese noturna e perda de peso. Há três dias apareceram manchas avermelhadas indolores nas palmas e nas plantas dos pés. Hoje acordou com dificuldade para falar e fraqueza no braço direito por uma hora, que melhorou.',
    antecedentes: {
      pessoais: ['Hepatite C diagnosticada há dois anos, não tratada', 'Abscesso no braço há seis meses'],
      familiares: ['Sem doenças relevantes'],
      habitos: ['Uso de drogas injetáveis há cinco anos, compartilha seringas', 'Tabagista e etilista'],
    },
    vitais: { pa: '108 × 52 mmHg', fc: '118 bpm', fr: '22 irpm', satO2: '94% em ar ambiente', temp: '39,1 °C' },
    exame: ['Máculas eritemato-hemorrágicas indolores nas palmas e plantas', 'Hemorragias em estilhaço sob as unhas', 'Sopro holossistólico novo em borda esternal esquerda baixa', 'Esplenomegalia palpável'],
    pergunta: 'A fotografia mostra as lesões palmares de outro paciente com a mesma doença. Qual é o diagnóstico que as explica?',
    achado: 'Endocardite infecciosa estafilocócica',
    veredito: 'Endocardite infecciosa com lesões de Janeway, hemorragias em estilhaço e provável embolia cerebral',
    distratores: [
      d('Sífilis secundária palmoplantar', 'Forma máculas e pápulas acobreadas nas palmas e plantas, com febre baixa e linfadenopatia, mas sem sopro novo, esplenomegalia por bacteremia ou eventos embólicos.'),
      d('Febre maculosa brasileira', 'Exantema que começa em punhos e tornozelos e alcança palmas e plantas, com febre alta, após picada de carrapato. Não explica sopro novo nem embolia cerebral.'),
      d('Vasculite por crioglobulinemia da hepatite C', 'Pode dar púrpura e lesões cutâneas em portador de hepatite C, mas nos membros inferiores, com artralgia e nefropatia, sem febre séptica nem sopro valvar novo.'),
    ],
    olhar: 'Na imagem, veja as máculas pequenas, avermelhadas ou hemorrágicas e irregulares nas palmas. São indolores, ao contrário dos nódulos de Osler, que doem e ficam nas polpas digitais.',
    explicacao: 'As lesões de Janeway são microabscessos sépticos na derme, com necrose e hemorragia, causados por êmbolos de vegetações infectadas — típicas da endocardite aguda por Staphylococcus aureus. Já os nódulos de Osler são dolorosos e de natureza imunológica. O uso de drogas injetáveis leva bactérias da pele direto à corrente sanguínea; a valva tricúspide é a mais acometida, mas o déficit neurológico transitório sugere vegetação também no coração esquerdo ou passagem por forame oval. Febre, sopro novo, fenômenos vasculares e esplenomegalia somam critérios de Duke.',
    conduta: 'Três pares de hemoculturas antes do antibiótico, ecocardiograma transtorácico e transesofágico, antibioticoterapia empírica com cobertura para estafilococo resistente, imagem do crânio e avaliação cirúrgica precoce; oferecer tratamento da dependência e da hepatite C.',
  },
  {
    id: 'raynaud-esclerodermia',
    sinal: 'fenomeno-de-raynaud',
    cenario: 'Ambulatório de reumatologia',
    identificacao: 'Mulher de 36 anos, auxiliar de laboratório.',
    queixa: 'Dedos que ficam brancos e roxos no frio há dois anos.',
    historia: 'Há dois anos, ao pegar algo na geladeira ou ao lavar louça com água fria, os dedos ficam brancos, depois roxos e, ao aquecer, vermelhos e doloridos. Nos últimos meses a pele dos dedos ficou mais grossa e esticada, ela tem azia e engasga com comida sólida. Uma pequena ferida na ponta do indicador demorou a cicatrizar.',
    antecedentes: {
      pessoais: ['Refluxo gastroesofágico recente', 'Sem uso de betabloqueador ou ergotamina'],
      gestacionais: ['Duas gestações, uma perda fetal no segundo trimestre'],
      familiares: ['Tia com lúpus'],
      habitos: ['Tabagista de 10 cigarros por dia', 'Trabalho com câmara fria'],
    },
    vitais: { pa: '124 × 80 mmHg', fc: '76 bpm', fr: '16 irpm', satO2: '97% em ar ambiente', temp: '36,4 °C' },
    exame: ['Palidez bem delimitada dos dedos após teste com água fria', 'Esclerodactilia com pele espessada até as metacarpofalângicas', 'Cicatriz puntiforme na polpa do indicador', 'Telangiectasias em face e lábios'],
    pergunta: 'A fotografia mostra os dedos de outro paciente durante uma crise. Qual é o fenômeno?',
    achado: 'Fenômeno de Raynaud secundário',
    veredito: 'Fenômeno de Raynaud secundário à esclerose sistêmica, com esclerodactilia e cicatriz digital',
    distratores: [
      d('Acrocianose primária benigna persistente', 'Deixa as mãos roxas, frias e suadas de forma persistente e simétrica, sem a fase branca bem delimitada e sem úlceras. Esta paciente tem episódios trifásicos e pele espessada.'),
      d('Isquemia aguda por embolia arterial', 'Causa palidez súbita e dolorosa de um dedo ou membro inteiro, persistente, sem relação com o frio e sem episódios repetidos. Aqui as crises são reversíveis e desencadeadas pelo frio.'),
      d('Frostbite superficial por câmara fria', 'É lesão por congelamento após exposição prolongada, com bolhas e necrose, num episódio só. As crises desta paciente se repetem há dois anos e revertem ao aquecer.'),
    ],
    olhar: 'Na foto, veja a palidez de limites nítidos em alguns dedos, como se alguém tivesse traçado uma linha, contrastando com a cor normal do resto da mão. Depois da fase branca vêm a roxa, pela dessaturação, e a vermelha, pela hiperemia reativa.',
    explicacao: 'O fenômeno de Raynaud é vasoespasmo exagerado das artérias digitais diante do frio ou do estresse emocional. A fase branca é a isquemia, a roxa é a estase com dessaturação e a vermelha é a reperfusão. O primário surge em jovens, é simétrico e benigno. O secundário aparece mais tarde, com úlceras ou cicatrizes digitais, alterações nos capilares da prega ungueal e sinais de doença sistêmica: aqui a esclerodactilia, as telangiectasias, a disfagia e o refluxo apontam para esclerose sistêmica, em que a lesão estrutural dos vasos se soma ao espasmo. O tabagismo e o trabalho no frio agravam.',
    conduta: 'Capilaroscopia periungueal, FAN e autoanticorpos anticentrômero e anti-Scl-70, avaliação pulmonar e cardíaca pela esclerose sistêmica, proteção contra o frio, cessação do tabagismo e bloqueador de canal de cálcio como primeira linha.',
  },
  {
    id: 'ulcera-arterial-claudicacao',
    sinal: 'ulcera-arterial',
    cenario: 'Ambulatório de cirurgia vascular',
    identificacao: 'Homem de 71 anos, aposentado.',
    queixa: 'Ferida no pé que dói muito, principalmente à noite.',
    historia: 'Há dois anos sente dor na panturrilha ao caminhar dois quarteirões, que melhora ao parar. Há dois meses surgiu uma ferida no dorso do pé depois de bater no móvel, que não cicatriza e dói tanto à noite que ele dorme sentado com a perna pendurada para aliviar.',
    antecedentes: {
      pessoais: ['Diabetes tipo 2 e hipertensão', 'Infarto há cinco anos com stent'],
      familiares: ['Irmão amputado por doença arterial'],
      habitos: ['Tabagista ativo de 50 maços-ano', 'Sedentário'],
    },
    vitais: { pa: '152 × 84 mmHg', fc: '78 bpm', fr: '16 irpm', satO2: '96% em ar ambiente', temp: '36,3 °C' },
    exame: ['Úlcera pequena, redonda, de bordas nítidas, com fundo pálido e seco no dorso do pé', 'Pé frio, pele fina, brilhante e sem pelos', 'Pulsos pedioso e tibial posterior ausentes', 'Palidez à elevação e rubor quando o pé fica pendente'],
    pergunta: 'A fotografia mostra uma lesão semelhante à do paciente. Qual é o tipo de úlcera?',
    achado: 'Úlcera arterial isquêmica',
    veredito: 'Úlcera arterial por isquemia crítica de membro, com dor de repouso e pulsos distais ausentes',
    distratores: [
      d('Úlcera neuropática do diabético', 'É indolor, plantar, sob pontos de pressão, com calo em volta, num pé quente com pulsos presentes. Esta úlcera é muito dolorosa, no dorso, num pé frio sem pulsos.'),
      d('Úlcera venosa de estase crônica', 'Fica acima do maléolo medial, é rasa, com bordas irregulares, fundo úmido e exsudativo, edema e dermatite ocre, e melhora com a elevação da perna. Este paciente melhora com a perna pendente.'),
      d('Pioderma gangrenoso ulcerado', 'Forma úlcera dolorosa de borda violácea e solapada que cresce rápido após trauma, associada a doença inflamatória intestinal. Os pulsos ausentes e a claudicação apontam para isquemia.'),
    ],
    olhar: 'Na foto, veja a ferida pequena e redonda, como feita com um furador, de bordas nítidas e fundo pálido, sem tecido de granulação vivo, numa pele fina e brilhante sem pelos. Tudo diz falta de sangue.',
    explicacao: 'A aterosclerose das artérias dos membros inferiores reduz o fluxo; primeiro aparece a claudicação, dor muscular por isquemia ao esforço. Quando a obstrução progride, o fluxo não basta nem em repouso: a dor piora à noite, com a perna elevada, e alivia pendurando-a, porque a gravidade ajuda a perfusão. Qualquer trauma pequeno vira úlcera que não cicatriza. Tabagismo, diabetes, hipertensão e doença coronariana são a mesma doença em outro território. Dor de repouso ou úlcera com pulsos ausentes é isquemia crônica que ameaça o membro.',
    conduta: 'Índice tornozelo-braquial, doppler e angiotomografia, revascularização endovascular ou cirúrgica, antiagregante e estatina em alta intensidade, cessação do tabagismo e cuidados locais sem compressão.',
  },
  {
    id: 'veia-cava-superior-tumor',
    sinal: 'sindrome-da-veia-cava-superior',
    cenario: 'Pronto-socorro',
    identificacao: 'Homem de 61 anos, motorista de caminhão.',
    queixa: 'Rosto inchado e vermelho de manhã e falta de ar há três semanas.',
    historia: 'Há três semanas acorda com o rosto e as pálpebras inchados, que melhoram um pouco ao longo do dia. A camisa ficou apertada no colarinho. Tem falta de ar ao deitar, tosse e rouquidão. Quando se abaixa para amarrar o sapato, sente a cabeça pesada e o rosto fica roxo. Perdeu 8 kg em dois meses.',
    antecedentes: {
      pessoais: ['DPOC leve', 'Hipertensão'],
      familiares: ['Irmão com câncer de pulmão'],
      habitos: ['Tabagista de 60 maços-ano, ativo', 'Etilismo moderado'],
    },
    vitais: { pa: '146 × 88 mmHg', fc: '98 bpm', fr: '24 irpm', satO2: '93% em ar ambiente', temp: '36,8 °C' },
    exame: ['Edema e pletora da face, do pescoço e dos braços', 'Veias jugulares distendidas e sem pulsação', 'Circulação colateral venosa na parte superior do tórax', 'Linfonodo supraclavicular direito endurecido'],
    pergunta: 'A fotografia mostra o aspecto de outro paciente com a mesma síndrome. Qual é o diagnóstico sindrômico?',
    achado: 'Síndrome da veia cava superior',
    veredito: 'Síndrome da veia cava superior por provável neoplasia pulmonar com metástase linfonodal',
    distratores: [
      d('Insuficiência cardíaca direita descompensada', 'Distende as jugulares, mas elas pulsam e há edema de membros inferiores, hepatomegalia e ascite, com refluxo hepatojugular. Este paciente tem edema só na metade superior do corpo.'),
      d('Angioedema hereditário por deficiência de C1', 'Incha face e lábios em crises de horas a dias, sem pletora, sem veias distendidas e sem circulação colateral. Aqui o inchaço é progressivo com veias torácicas visíveis.'),
      d('Síndrome de Cushing por corticoide exógeno', 'Arredonda e avermelha a face, com giba e estrias violáceas, em uso de corticoide. Não distende as jugulares nem forma circulação colateral no tórax.'),
    ],
    olhar: 'Na foto, veja a face e o pescoço inchados e avermelhados, e procure as veias superficiais dilatadas na parte alta do tórax, que levam o sangue por caminhos alternativos até a veia cava inferior.',
    explicacao: 'A veia cava superior tem parede fina e baixa pressão; tumores do mediastino a comprimem ou invadem com facilidade. O sangue da cabeça, do pescoço e dos braços não consegue voltar ao coração: as veias distendem sem pulsar, a face incha e fica pletórica, e abrem-se colaterais pela parede torácica, ázigos e mamárias. Os sintomas pioram ao deitar e ao abaixar, quando a gravidade deixa de ajudar. Câncer de pulmão, principalmente de pequenas células, e linfomas respondem pela maioria dos casos; trombose por cateter é a principal causa benigna.',
    conduta: 'Cabeceira elevada, tomografia de tórax com contraste, diagnóstico histológico do linfonodo antes de tratar quando possível, stent endovascular para alívio rápido em casos graves e tratamento oncológico conforme o tipo; intubação e emergência se houver estridor ou edema cerebral.',
  },
]
