import type { Sinal } from './esquemas'

/**
 * Quinta leva, parte 4 — musculoesquelético e trauma (18): deformidades,
 * derrames, luxações e sequelas que a fotografia mostra antes da radiografia.
 */
export const SINAIS_LEVA_5_MSK: Sinal[] = [
  {
    slug: 'nodulos-de-bouchard',
    nome: 'Nódulos de Bouchard',
    sinonimos: ['Osteoartrite das interfalangianas proximais', 'Nódulos de Heberden e Bouchard', 'Artrose nodal das mãos'],
    sistema: 'musculoesqueletico',
    resumo: 'Alargamentos ósseos duros e indolores nas articulações do meio dos dedos (interfalangianas proximais), quase sempre acompanhando os de Heberden nas pontas — a artrose nodal das mãos, hereditária, da mulher após a menopausa.',
    definicao: 'Nódulos ósseos (osteófitos marginais) firmes, de 2 a 5 mm, nas faces dorsolaterais das interfalangianas proximais, frequentemente bilaterais e simétricos, com desvio angular do dedo, rigidez matinal curta (< 30 minutos) e, na fase ativa, dor e discreto edema; associados aos nódulos de Heberden (distais) e à rizartrose (base do polegar); sem sinovite de metacarpofalangianas nem de punhos; radiografia com redução do espaço, esclerose e osteófitos.',
    comoProcurar: [
      { passo: 'Olhe e palpe o dorso das interfalangianas proximais: alargamento ósseo duro, não elástico.', detalhe: 'Sinovite reumatoide é mole, fusiforme e quente.' },
      { passo: 'Confira as distais (Heberden) e a base do polegar (rizartrose com "ombro" quadrado).', detalhe: 'O padrão nodal é quase diagnóstico.' },
      { passo: 'Metacarpofalangianas e punhos poupados; se estiverem pegos, pense em artrite reumatoide ou hemocromatose.', detalhe: 'Radiografia e, se dúvida, fator reumatoide e anti-CCP.' },
    ],
    mecanismo: 'Degeneração da cartilagem articular com remodelação óssea subcondral e formação de osteófitos marginais nas bordas da interfalangiana; a predisposição genética (mãe e filha) e o estrogênio explicam o predomínio em mulheres após os 50; os episódios inflamatórios (artrose erosiva) explicam a dor e o edema intermitentes.',
    significado: 'A artrose nodal das mãos é um marcador de osteoartrite generalizada (joelhos, quadris, coluna) e um diagnóstico clínico que evita exames desnecessários: nódulos duros em IFP e IFD com MCF poupadas não são artrite reumatoide. Pouca perda funcional; analgesia, exercício e órteses para a rizartrose.',
    armadilhas: ['Artrite psoriásica de IFD: dactilite, unhas com pitting, sinovite mole.', 'Artrose erosiva: episódios inflamatórios que simulam reumatoide.', 'Gota tofácea: tofos amarelados e assimétricos sobre as articulações.'],
    causas: [
      { titulo: 'Osteoartrite das mãos', mecanismo: 'Osteófitos marginais.', itens: ['Artrose nodal hereditária', 'Artrose erosiva', 'Secundária (hemocromatose — MCF 2 e 3)'] },
    ],
    referencias: ['Kloppenburg M et al. 2018 update of the EULAR recommendations for the management of hand osteoarthritis. Ann Rheum Dis, 2019.'],
  },
  {
    slug: 'mao-reumatoide',
    nome: 'Mão reumatoide',
    sinonimos: ['Desvio ulnar', 'Dedos em pescoço de cisne e em botoeira', 'Sinovite de metacarpofalangianas', 'Polegar em Z'],
    sistema: 'musculoesqueletico',
    resumo: 'Metacarpofalangianas inchadas e subluxadas com os dedos desviados para o lado ulnar, punhos com sinovite, dedos em pescoço de cisne ou em botoeira e polegar em Z — as deformidades da artrite reumatoide de anos, que hoje o tratamento precoce quase aboliu.',
    definicao: 'Conjunto de deformidades da mão na artrite reumatoide evoluída: sinovite (edema fusiforme, mole, quente) de metacarpofalangianas e punhos, poupando interfalangianas distais; desvio ulnar dos dedos com subluxação volar das metacarpofalangianas; dedo em pescoço de cisne (hiperextensão da IFP + flexão da IFD), dedo em botoeira (flexão da IFP + hiperextensão da IFD), polegar em Z; atrofia dos interósseos, proeminência da ulna distal ("tecla de piano"), ruptura de extensores (queda de dedos), nódulos reumatoides nos cotovelos; rigidez matinal > 1 hora.',
    comoProcurar: [
      { passo: 'Aperte lateralmente as metacarpofalangianas (squeeze): dor indica sinovite precoce, antes da deformidade.', detalhe: 'Palpe cada MCF e o punho: edema mole e elástico.' },
      { passo: 'Olhe as mãos apoiadas: desvio ulnar, dedos em cisne e botoeira, polegar em Z.', detalhe: 'Peça para estender os dedos: um que não estende pode ser ruptura de tendão.' },
      { passo: 'Cotovelos (nódulos), pés (MTF), coluna cervical (subluxação atlantoaxial — pergunte dor e parestesias).', detalhe: 'Fator reumatoide, anti-CCP, radiografia das mãos e pés.' },
    ],
    mecanismo: 'Sinovite crônica autoimune que destrói cartilagem, erode o osso e distende cápsulas e ligamentos; a frouxidão das MCF com a tração dos flexores e dos extensores deslocados para o lado ulnar produz o desvio; o desequilíbrio entre o aparelho extensor e o flexor nas interfalangianas cria o cisne e a botoeira; a sinovite tenossinovial rompe extensores sobre a ulna proeminente.',
    significado: 'A mão reumatoide deformada é hoje uma marca de doença antiga ou não tratada; o objetivo do tratamento precoce (metotrexato, biológicos) é que ela nunca aconteça. Reconhecer a sinovite de MCF e punhos com IFD poupadas é o que diferencia artrite reumatoide de artrose e psoriásica na primeira consulta.',
    armadilhas: ['Artropatia de Jaccoud (lúpus, febre reumática): desvio ulnar redutível, sem erosões.', 'Artrose nodal: IFD e IFP com MCF poupadas.', 'Artrite psoriásica: IFD, dactilite, unhas.'],
    causas: [
      { titulo: 'Artrite reumatoide', mecanismo: 'Sinovite erosiva crônica.', itens: ['AR soropositiva (FR, anti-CCP)', 'AR soronegativa'] },
      { titulo: 'Deformidades semelhantes', mecanismo: 'Frouxidão sem erosão.', itens: ['Artropatia de Jaccoud', 'Ehlers-Danlos (cisne por hipermobilidade)'] },
    ],
    referencias: ['Smolen JS et al. Rheumatoid arthritis. Lancet, 2016.'],
  },
  {
    slug: 'artrite-mutilante',
    nome: 'Artrite mutilante',
    sinonimos: ['Dedos em telescópio', 'Mão em lorgnette (binóculo de ópera)', 'Artrite psoriásica mutilante'],
    sistema: 'musculoesqueletico',
    resumo: 'Dedos encurtados, flácidos, com a pele redundante em pregas, que podem ser puxados e "alongados" como um telescópio — o osso das falanges foi reabsorvido pela artrite psoriásica (ou, raramente, reumatoide), e sobrou só o envelope.',
    definicao: 'Forma destrutiva de artrite (psoriásica em 5% dos casos, raramente reumatoide) com osteólise das falanges e metacarpos: dedos encurtados, instáveis e móveis em todos os planos, pele excedente em pregas concêntricas, deformidade "em telescópio" (o dedo se encurta e alonga à tração), mão "em lorgnette"; radiografia com "lápis na xícara" (pencil-in-cup) e desaparecimento de falanges; nos pés, dedos flutuantes; placas de psoríase e unhas com pitting e onicólise.',
    comoProcurar: [
      { passo: 'Puxe delicadamente o dedo: alonga (telescópio) — o osso não está lá.', detalhe: 'Instabilidade em todas as direções.' },
      { passo: 'Procure a psoríase: couro cabeludo, umbigo, prega interglútea, unhas.', detalhe: 'Às vezes a pele é discreta e a artrite, devastadora.' },
      { passo: 'Radiografia das mãos e pés: pencil-in-cup, acro-osteólise.', detalhe: 'Biológicos (anti-TNF, IL-17) freiam a destruição.' },
    ],
    mecanismo: 'Sinovite e entesite intensas com ativação osteoclástica mediada por TNF, IL-17 e RANKL reabsorvem a extremidade das falanges e o osso periarticular; sem osso, a articulação vira uma pseudoartrose e o dedo colapsa; a pele, não reabsorvida, sobra em pregas.',
    significado: 'A forma mais grave e incapacitante da artrite psoriásica — irreversível quando instalada; indica doença agressiva que exige tratamento biológico. Vê-la é reconhecer a psoríase articular que ninguém tratou.',
    armadilhas: ['Artrite reumatoide mutilante: raro, com nódulos e fator reumatoide.', 'Hanseníase virchowiana: reabsorção de falanges com anestesia e espessamento de nervos.', 'Esclerodermia com acro-osteólise: reabsorção das pontas, sem instabilidade articular.'],
    causas: [
      { titulo: 'Artrite psoriásica', mecanismo: 'Osteólise inflamatória.', itens: ['Forma mutilante (5%)'] },
      { titulo: 'Outras osteólises', mecanismo: 'Destruição óssea de outra origem.', itens: ['Artrite reumatoide grave', 'Hanseníase', 'Artropatia neuropática (Charcot)', 'Esclerodermia'] },
    ],
    referencias: ['Haddad A, Chandran V. Arthritis mutilans. Curr Rheumatol Rep, 2013.'],
  },
  {
    slug: 'artrite-septica-de-tornozelo',
    nome: 'Artrite séptica de tornozelo',
    sinonimos: ['Monoartrite aguda séptica', 'Piartrose', 'Tornozelo séptico'],
    sistema: 'musculoesqueletico',
    resumo: 'Tornozelo vermelho, quente, muito inchado, que o paciente não deixa mover nem apoiar, com febre — a monoartrite que é emergência até a punção dizer o contrário, porque cada dia de pus destrói cartilagem.',
    definicao: 'Monoartrite aguda (< 2 semanas) com edema difuso periarticular, eritema, calor, derrame tenso, dor intensa à mobilização ativa e passiva (o paciente resiste a qualquer movimento), impossibilidade de apoiar o peso, febre e leucocitose; em usuários de drogas injetáveis, diabéticos, imunossuprimidos, próteses, ou após ferida penetrante; líquido sinovial turvo com > 50.000 leucócitos/mm³ e predomínio de neutrófilos; S. aureus em 50 a 60%, gonococo no jovem sexualmente ativo.',
    comoProcurar: [
      { passo: 'Diferencie celulite de artrite: na artrite, a mobilização passiva mínima dói muito e o derrame é intra-articular.', detalhe: 'Celulite dói na pele; a articulação move.' },
      { passo: 'Puncione antes do antibiótico: aspecto, celularidade, Gram, cultura, cristais.', detalhe: 'Gota e séptica coexistem — cristais não excluem infecção.' },
      { passo: 'Hemoculturas, radiografia (basal); antibiótico venoso e drenagem (artroscópica ou aspirações seriadas).', detalhe: 'Gonococo: lesões cutâneas pustulosas e tenossinovite migratória — pergunte e colha swabs.' },
    ],
    mecanismo: 'Bactérias chegam à sinóvia por via hematogênica (bacteremia transitória, endocardite, drogas injetáveis), por inoculação direta (ferida, punção) ou por contiguidade (osteomielite, úlcera); a resposta inflamatória com enzimas proteolíticas e a pressão intra-articular destroem a cartilagem em poucos dias e o osso subcondral em semanas.',
    significado: 'Emergência ortopédica: mortalidade de 10% e perda funcional em um terço; o atraso de 48 horas na drenagem já aumenta a sequela. Toda monoartrite aguda febril é séptica até a punção — e a punção é obrigatória.',
    armadilhas: ['Gota do tornozelo: pode ser idêntica; os cristais dizem, mas a infecção pode coexistir.', 'Celulite e bursite: mobilização articular preservada.', 'Artrite de Lyme, reativa e viral: menos agudas, líquido menos inflamatório.', 'Imunossuprimido e idoso: sem febre nem leucocitose.'],
    causas: [
      { titulo: 'Infecção articular', mecanismo: 'Hematogênica, direta ou contígua.', itens: ['S. aureus (inclusive MRSA)', 'Estreptococos', 'N. gonorrhoeae (jovens)', 'Gram-negativos (idosos, imunossuprimidos, usuários de drogas)', 'Micobactérias e fungos (crônicas)'] },
    ],
    referencias: ['Ross JJ. Septic arthritis of native joints. Infect Dis Clin North Am, 2017.'],
  },
  {
    slug: 'derrame-articular-de-joelho',
    nome: 'Derrame articular de joelho',
    sinonimos: ['Sinal da tecla (rechaço patelar)', 'Sinal da onda (bulge sign)', 'Hidrartrose', 'Joelho inchado'],
    sistema: 'musculoesqueletico',
    resumo: 'Joelho com o contorno apagado, os sulcos ao lado da patela cheios, e a patela que afunda e rebate ao ser empurrada contra o fêmur (tecla) — líquido na articulação, cuja natureza (sangue, pus, cristais, sinovite) só a punção diz.',
    definicao: 'Acúmulo de líquido intra-articular: apagamento das depressões parapatelares e da fosseta suprapatelar, abaulamento em ferradura acima e ao lado da patela; sinal da onda (bulge) para derrames pequenos (deslocar o líquido do lado medial e vê-lo reaparecer ao pressionar o lateral); sinal da tecla ou rechaço patelar para derrames médios (comprimir o fundo de saco suprapatelar e empurrar a patela contra o fêmur — afunda e volta); derrame tenso limita a flexão; comparar sempre com o outro joelho.',
    comoProcurar: [
      { passo: 'Paciente deitado, joelho estendido e relaxado. Compare os contornos dos dois joelhos.', detalhe: 'Apagamento dos sulcos parapatelares é o primeiro sinal.' },
      { passo: 'Bulge: com a palma, "varra" a face medial de baixo para cima; depois pressione a face lateral e veja a onda medial.', detalhe: 'Detecta 5 a 10 mL.' },
      { passo: 'Tecla: uma mão comprime a bolsa suprapatelar de cima; o indicador da outra empurra a patela — ela afunda e rebate.', detalhe: 'Puncione: aspecto, celularidade, cristais, Gram/cultura; sangue = hemartrose (ligamento cruzado, fratura, hemofilia).' },
    ],
    mecanismo: 'A sinóvia inflamada, traumatizada ou infectada produz líquido em excesso (ou sangue, na lesão vascular ou coagulopatia); o líquido enche a cavidade e a bolsa suprapatelar (que se comunica com a articulação), levanta a patela do fêmur e apaga as depressões peripatelares.',
    significado: 'O derrame diz que a articulação está doente, não o porquê: hemartrose imediata após trauma = ligamento cruzado anterior ou fratura; derrame tardio = menisco; derrame com febre = séptico até a punção; derrames recorrentes com cristais = gota ou pseudogota; crônico bilateral = artrite reumatoide ou artrose com sinovite. A punção é diagnóstica e terapêutica.',
    armadilhas: ['Bursite pré-patelar: abaulamento na frente da patela, a articulação está seca.', 'Cisto de Baker: massa poplítea, pode coexistir com derrame.', 'Edema periarticular (celulite, hematoma) sem tecla.', 'Joelho gordo: sulcos apagados sem líquido — a tecla não rebate.'],
    causas: [
      { titulo: 'Traumático', mecanismo: 'Sangue ou reação sinovial.', itens: ['Ruptura do ligamento cruzado anterior (hemartrose em < 2 h)', 'Fratura intra-articular, luxação de patela', 'Lesão meniscal (derrame tardio)'] },
      { titulo: 'Inflamatório e infeccioso', mecanismo: 'Sinovite.', itens: ['Artrite séptica', 'Gota e pseudogota', 'Artrite reumatoide, espondiloartrites, reativa', 'Artrose com sinovite', 'Hemofilia, anticoagulação, sinovite vilonodular'] },
    ],
    referencias: ['Maricar N et al. Clinical assessment of effusion in knee osteoarthritis — a systematic review. Semin Arthritis Rheum, 2016.'],
  },
  {
    slug: 'cisto-de-baker',
    nome: 'Cisto de Baker',
    sinonimos: ['Cisto poplíteo', 'Cisto sinovial poplíteo', 'Pseudotromboflebite'],
    sistema: 'musculoesqueletico',
    resumo: 'Massa mole, lisa, indolor na fossa poplítea medial, que fica tensa com o joelho estendido e desaparece ou amolece com a flexão — a bolsa entre o gastrocnêmio e o semimembranoso cheia pelo líquido de um joelho doente; quando rompe, imita uma trombose venosa.',
    definicao: 'Distensão da bolsa gastrocnêmio-semimembranosa por líquido sinovial que se comunica com a articulação do joelho: tumoração poplítea medial, arredondada, lisa, elástica, transilumina, mais evidente com o joelho estendido e o paciente em pé, que amolece à flexão a 45° (sinal de Foucher); frequentemente associada a artrose, artrite reumatoide ou lesão meniscal; rotura: dor súbita na panturrilha, edema, eritema e crescente equimótico no maléolo (sinal do crescente), simulando trombose venosa profunda; em crianças, cisto poplíteo primário sem doença articular.',
    comoProcurar: [
      { passo: 'Em pé, olhe a fossa poplítea por trás: abaulamento medial.', detalhe: 'Palpe com o joelho estendido e depois fletido: tenso → mole (Foucher).' },
      { passo: 'Examine o joelho: derrame, crepitação, meniscos — o cisto é consequência.', detalhe: 'Ultrassom confirma e exclui aneurisma poplíteo e tumor.' },
      { passo: 'Panturrilha dolorosa e inchada em quem tinha cisto: ultrassom com Doppler — rotura ou trombose (ou ambos).', detalhe: 'Crescente equimótico no maléolo é a pista da rotura.' },
    ],
    mecanismo: 'A bolsa gastrocnêmio-semimembranosa se comunica com o joelho por uma abertura capsular com mecanismo valvular unidirecional; qualquer derrame articular a enche, e a pressão ao estender o joelho a mantém distendida; a rotura ou a dissecção do líquido para a panturrilha causa inflamação difusa, com o mesmo quadro clínico da trombose.',
    significado: 'Benigno e secundário — trata-se a articulação, não o cisto; punção ou excisão só quando sintomático. O valor clínico é o diferencial com trombose venosa profunda, aneurisma poplíteo (pulsátil) e tumor de partes moles: o Doppler resolve, e a trombose pode coexistir com o cisto (compressão venosa).',
    armadilhas: ['Aneurisma da artéria poplítea: pulsátil, expansível — não puncione.', 'Trombose venosa profunda: pode ser causada pelo cisto comprimindo a veia; sempre Doppler.', 'Sarcoma de partes moles e cisto de menisco (lateral, menor).'],
    causas: [
      { titulo: 'Derrame articular do joelho', mecanismo: 'Enchimento da bolsa comunicante.', itens: ['Osteoartrite', 'Artrite reumatoide e outras sinovites', 'Lesão meniscal, ligamentar', 'Cisto poplíteo primário da criança'] },
    ],
    referencias: ['Frush TJ, Noyes FR. Baker\'s cyst: diagnostic and surgical considerations. Sports Health, 2015.'],
  },
  {
    slug: 'deformidade-de-haglund',
    nome: 'Deformidade de Haglund',
    sinonimos: ['Calcanhar de Haglund', 'Pump bump', 'Bursite retrocalcânea', 'Exostose posterior do calcâneo'],
    sistema: 'musculoesqueletico',
    resumo: 'Uma proeminência óssea dura na parte de trás e de cima do calcanhar, com a pele avermelhada e calosa onde o contraforte do sapato esfrega, e dor ao subir escadas — a exostose posterossuperior do calcâneo que inflama a bolsa e o tendão de Aquiles.',
    definicao: 'Proeminência óssea da tuberosidade posterossuperior do calcâneo, visível e palpável lateralmente à inserção do tendão de Aquiles, com bursite retrocalcânea (edema e dor de cada lado do tendão, anterior a ele) e bursite subcutânea (pele espessada, eritematosa, calosa — o "pump bump" das mulheres que usam sapato de salto com contraforte rígido); dor ao início da marcha, ao subir escadas e à dorsiflexão passiva; tendinopatia insercional de Aquiles associada; radiografia lateral com ângulo posterior do calcâneo aumentado e calcificações insercionais.',
    comoProcurar: [
      { passo: 'Olhe o calcanhar por trás e de lado: proeminência dura, pele vermelha e espessa no ponto de atrito.', detalhe: 'Frequentemente bilateral; pergunte pelos sapatos.' },
      { passo: 'Palpe de cada lado do Aquiles, 2 cm acima da inserção: dor e edema = bursite retrocalcânea.', detalhe: 'Aperte a bolsa entre polegar e indicador (teste de compressão).' },
      { passo: 'Dorsiflexão passiva dói; radiografia lateral confirma a exostose.', detalhe: 'Calçado, gelo, alongamento; cirurgia para ressecar a exostose se falhar.' },
    ],
    mecanismo: 'Variante anatômica do calcâneo (tuberosidade posterossuperior proeminente, calcâneo em pé cavo) é comprimida contra o tendão de Aquiles e o contraforte rígido do sapato a cada dorsiflexão; o atrito repetido inflama a bolsa retrocalcânea (entre osso e tendão) e a subcutânea (entre tendão e pele) e degenera a inserção do tendão.',
    significado: 'Causa comum de dor posterior do calcanhar em adultos jovens e de meia-idade, especialmente mulheres; benigna e mecânica, resolve com mudança de calçado na maioria. Distinguir da tendinopatia de Aquiles pura e da entesite das espondiloartrites (jovem com lombalgia inflamatória, HLA-B27) muda o tratamento.',
    armadilhas: ['Entesite de Aquiles das espondiloartrites: bilateral, sem exostose, em jovem com lombalgia.', 'Tendinopatia de Aquiles do corpo (2 a 6 cm acima): nódulo no tendão, não no osso.', 'Xantoma do tendão de Aquiles: espessamento difuso, hipercolesterolemia familiar.'],
    causas: [
      { titulo: 'Conflito osso-tendão-calçado', mecanismo: 'Atrito repetido.', itens: ['Calcâneo com tuberosidade proeminente', 'Pé cavo, varo do retropé', 'Contraforte rígido, salto alto', 'Corrida em subida'] },
    ],
    referencias: ['Vaishya R et al. Haglund\'s syndrome: a commonly seen mysterious condition. Cureus, 2016.'],
  },
  {
    slug: 'pe-plano-vs-cavo',
    nome: 'Pé plano × pé cavo',
    sinonimos: ['Pé chato', 'Pé plano valgo', 'Pé cavo varo', 'Arco plantar', 'Sinal dos muitos dedos'],
    sistema: 'musculoesqueletico',
    resumo: 'Visto por trás, o pé plano mostra o calcanhar virado para fora e mais dedos do que deveria aparecer lateralmente; o pé cavo mostra o calcanhar virado para dentro, o arco alto, os dedos em garra e as calosidades sob a cabeça dos metatarsos — e o cavo, quando unilateral ou progressivo, é neurológico até prova contrária.',
    definicao: 'Pé plano: desabamento do arco longitudinal medial com o pé apoiado, valgo do retropé (calcanhar virado para fora), abdução do antepé com "sinal dos muitos dedos" (mais de dois dedos visíveis lateralmente ao olhar por trás); flexível quando o arco reaparece na ponta dos pés ou ao estender o hálux (teste de Jack) e rígido quando não (coalizão tarsal, artrose); em adultos, disfunção do tibial posterior (incapacidade de ficar na ponta de um pé só). Pé cavo: arco medial elevado que não desaba com a carga, varo do retropé (calcanhar para dentro), dedos em garra, calosidades sob os metatarsos e no calcanhar, entorses de repetição; bilateral e simétrico nas neuropatias hereditárias (Charcot-Marie-Tooth), unilateral ou progressivo na medula presa, siringomielia, poliomielite.',
    comoProcurar: [
      { passo: 'Paciente em pé, visto por trás: alinhamento do calcanhar e quantos dedos aparecem por fora.', detalhe: 'Depois de lado: altura do arco com carga.' },
      { passo: 'Pé plano: ponta dos pés e teste de Jack (arco reaparece = flexível). Ponta de um pé só: tibial posterior.', detalhe: 'Rígido ou doloroso no adolescente: coalizão tarsal — TC.' },
      { passo: 'Pé cavo: bloco de Coleman (retropé corrige com o antepé lateral apoiado num bloco = cavo flexível, dirigido pelo antepé); exame neurológico completo — reflexos, sensibilidade, força dos fibulares, coluna lombar (tufo de pelos, fosseta).', detalhe: 'Cavo unilateral, progressivo ou com déficit: ressonância de coluna e eletroneuromiografia.' },
    ],
    mecanismo: 'O arco plantar depende de ligamentos (mola), fáscia plantar e do tibial posterior; frouxidão (criança, hipermobilidade), falência do tendão (adulto obeso, diabético) ou artrose o desabam. O pé cavo resulta do desequilíbrio muscular: fibular longo forte contra tibial anterior fraco deprime o primeiro raio, o retropé compensa em varo, e a fraqueza dos intrínsecos coloca os dedos em garra — o padrão das neuropatias motoras periféricas.',
    significado: 'Pé plano flexível da criança é fisiológico até os 6 a 8 anos e não se trata; o do adulto com disfunção do tibial posterior é progressivo e cirúrgico se tardio. O pé cavo é a face ortopédica da doença neurológica: Charcot-Marie-Tooth é a causa mais comum e o pé cavo é seu primeiro sinal na infância; o cavo unilateral é sinal de lesão medular ou de nervo até prova contrária.',
    armadilhas: ['Pé plano "aparente" do lactente pelo coxim adiposo.', 'Coalizão tarsal: pé plano rígido e doloroso no adolescente, entorses repetidas.', 'Pé cavo idiopático existe, mas só depois de excluir neuropatia.', 'Ruptura do tibial posterior aguda simulando entorse medial.'],
    causas: [
      { titulo: 'Pé plano', mecanismo: 'Falência dos suportes do arco.', itens: ['Fisiológico da infância', 'Hipermobilidade (Ehlers-Danlos, Down)', 'Disfunção do tibial posterior', 'Coalizão tarsal', 'Artrose, Charcot, pós-traumático'] },
      { titulo: 'Pé cavo', mecanismo: 'Desequilíbrio muscular.', itens: ['Charcot-Marie-Tooth', 'Ataxia de Friedreich', 'Medula presa, siringomielia, mielomeningocele', 'Sequela de pólio, paralisia cerebral', 'Idiopático (após exclusão)'] },
    ],
    referencias: ['Wicart P. Cavus foot, from neonates to adolescents. Orthop Traumatol Surg Res, 2012.', 'Harris EJ et al. Diagnosis and treatment of pediatric flatfoot. J Foot Ankle Surg, 2004.'],
  },
  {
    slug: 'dedos-em-martelo-e-bunionette',
    nome: 'Dedos em martelo, em garra e bunionette',
    sinonimos: ['Hammer toe', 'Claw toe', 'Joanete de alfaiate', 'Joanete do quinto dedo', 'Calo dorsal'],
    sistema: 'musculoesqueletico',
    resumo: 'Dedos do pé dobrados na articulação do meio com um calo doloroso no dorso onde o sapato roça (martelo), ou dobrados em todas as articulações com as pontas cravadas no chão (garra), e uma proeminência óssea na borda externa do pé na base do dedo mínimo (bunionette) — as deformidades do antepé do sapato apertado e da neuropatia.',
    definicao: 'Dedo em martelo: flexão da interfalangiana proximal com metatarsofalangiana neutra ou estendida e IFD estendida, calo dorsal sobre a IFP; comum no segundo dedo, associado ao hálux valgo. Dedo em garra: hiperextensão da MTF com flexão de IFP e IFD, calos dorsais e nas pontas, frequentemente em todos os dedos — padrão de pé cavo neuropático. Dedo em maço (mallet): flexão isolada da IFD. Bunionette (joanete de alfaiate): proeminência da cabeça do quinto metatarso na borda lateral do pé, com bursite e calo, por varo do quinto dedo ou metatarso divergente; hálux valgo frequentemente associado (antepé triangular).',
    comoProcurar: [
      { passo: 'Pé apoiado e depois pendente: classifique cada dedo pelo padrão de flexão e verifique se a deformidade é flexível (corrige passivamente) ou rígida.', detalhe: 'Push-up test: empurrar a cabeça do metatarso de baixo — o martelo flexível endireita.' },
      { passo: 'Procure calos: dorsal na IFP (martelo), pontas dos dedos e sob as cabeças metatarsais (garra), lateral ao quinto metatarso (bunionette).', detalhe: 'Calo é o mapa da pressão.' },
      { passo: 'Dedos em garra em todos os dedos, bilateral: exame neurológico (neuropatia diabética, CMT).', detalhe: 'Diabético com garra e calo plantar: risco de úlcera — pé de risco.' },
    ],
    mecanismo: 'Desequilíbrio entre extensores longos, flexores longos e intrínsecos (lumbricais e interósseos, que fletem a MTF e estendem as IF): quando os intrínsecos enfraquecem (neuropatia) ou são vencidos por calçado que comprime os dedos em flexão, os extrínsecos deformam o dedo; a placa plantar da MTF rompe-se e o dedo sobe; a pele sob pressão contra o sapato ou o chão forma calo, depois úlcera. O bunionette segue a mesma lógica do hálux valgo, no quinto raio.',
    significado: 'Causa cotidiana de dor no antepé e de úlceras no diabético (o calo sob a cabeça metatarsal é o pré-úlcera); calçado largo e órteses para o flexível, cirurgia para o rígido. Dedos em garra generalizados apontam para pé neuropático e disparam a avaliação neurológica e a prevenção de úlcera.',
    armadilhas: ['Hálux valgo empurrando o segundo dedo para martelo cruzado.', 'Artrite reumatoide do antepé: garras com subluxação de MTF e calos plantares — sinovite associada.', 'Calo interdigital (olho de perdiz) entre quarto e quinto dedos, não é bunionette.'],
    causas: [
      { titulo: 'Mecânica', mecanismo: 'Calçado e desequilíbrio local.', itens: ['Sapato de bico fino e salto', 'Hálux valgo, segundo metatarso longo', 'Ruptura da placa plantar'] },
      { titulo: 'Neurológica e inflamatória', mecanismo: 'Fraqueza dos intrínsecos ou sinovite.', itens: ['Neuropatia diabética', 'Charcot-Marie-Tooth, pé cavo', 'Artrite reumatoide, psoriásica', 'Sequela de AVC e paralisia cerebral'] },
    ],
    referencias: ['Coughlin MJ. Lesser toe abnormalities. J Bone Joint Surg Am, 2002.'],
  },
  {
    slug: 'fratura-em-galho-verde',
    nome: 'Fratura em galho verde e em torus',
    sinonimos: ['Fratura incompleta da criança', 'Fratura em toro (buckle)', 'Fratura em cabo de vassoura'],
    sistema: 'pediatrico',
    resumo: 'O antebraço da criança que caiu com a mão espalmada está angulado e dolorido, mas sem crepitação nem deformidade grosseira — o osso infantil, flexível como um galho verde, quebrou de um lado e dobrou do outro (galho verde) ou apenas amassou a cortical (torus).',
    definicao: 'Fraturas incompletas exclusivas da criança: galho verde — ruptura da cortical de tensão (convexa) com encurvamento plástico da cortical de compressão, angulação visível, dor e edema, sem mobilidade anormal grosseira; torus (buckle, "em toro") — abaulamento da cortical metafisária por compressão axial, sem angulação, com dor localizada e edema discreto, radiografia com pequena saliência cortical; deformidade plástica — encurvamento sem traço de fratura; sítios: rádio e ulna distais (queda sobre a mão), clavícula; a criança "poupa" o membro e chora à palpação do ponto.',
    comoProcurar: [
      { passo: 'Inspecione com o membro contralateral ao lado: angulação sutil, edema.', detalhe: 'Criança que não usa o braço após queda tem fratura até prova contrária.' },
      { passo: 'Palpe metáfise por metáfise: dor pontual na radial distal.', detalhe: 'Não teste crepitação — desnecessário e cruel.' },
      { passo: 'Radiografia em duas incidências, incluindo as articulações adjacentes; compare com o lado oposto se dúvida.', detalhe: 'Torus: tala removível por 3 semanas. Galho verde angulada: redução (às vezes completar a fratura) e gesso.' },
    ],
    mecanismo: 'O osso da criança tem mais colágeno e água, menor mineralização e periósteo espesso e resistente: sob carga angular, a cortical do lado convexo (tensão) falha enquanto a do lado côncavo (compressão) se deforma plasticamente sem romper — como um galho verde; sob carga axial na metáfise porosa, a cortical apenas abaula (torus). O periósteo íntegro mantém a estabilidade e acelera a consolidação.',
    significado: 'As fraturas mais comuns da infância, estáveis e de consolidação rápida, com remodelação que corrige angulações residuais (quanto mais nova a criança e mais perto da fise, mais corrige). O galho verde tende a reangular no gesso — a redução às vezes exige completar a fratura. Padrão de fratura incompatível com a história (lactente que não anda, múltiplas idades de consolidação) é maus-tratos.',
    armadilhas: ['Fratura de Salter-Harris (fise): dor sobre a placa de crescimento com radiografia normal — tratar como fratura.', 'Deformidade plástica sem traço: passa despercebida na radiografia.', 'Fratura de Monteggia: ulna em galho verde com luxação da cabeça do rádio — olhe o cotovelo.', 'Múltiplas fraturas em idades diferentes: violência.'],
    causas: [
      { titulo: 'Trauma na criança', mecanismo: 'Osso elástico com periósteo espesso.', itens: ['Queda sobre a mão espalmada (rádio e ulna distais)', 'Queda sobre o ombro (clavícula)', 'Trauma direto', 'Maus-tratos (padrões incompatíveis)'] },
    ],
    referencias: ['Randsborg PH, Sivertsen EA. Distal radius fractures in children: substantial difference in stability between buckle and greenstick fractures. Acta Orthop, 2009.'],
  },
  {
    slug: 'luxacao-de-cotovelo',
    nome: 'Luxação de cotovelo',
    sinonimos: ['Luxação posterior do cotovelo', 'Cotovelo luxado', 'Tríade terrível'],
    sistema: 'musculoesqueletico',
    resumo: 'Cotovelo travado em semiflexão com o olécrano saliente atrás e o antebraço encurtado — o triângulo de Nélaton (epicôndilos e olécrano) desfeito: a segunda luxação mais comum do adulto, após queda sobre a mão estendida, que exige checar pulso e nervos antes e depois de reduzir.',
    definicao: 'Perda completa da congruência ulnoumeral, posterior ou posterolateral em 90%: cotovelo bloqueado em 45° de flexão, dor intensa, antebraço aparentemente encurtado, olécrano proeminente posteriormente com depressão acima dele, epicôndilos palpáveis à frente, desaparecimento da relação isósceles entre epicôndilos e olécrano (triângulo de Nélaton, linha de Hüter); edema rápido; avaliar pulso radial, enchimento capilar e nervos mediano (oponência, sensibilidade do indicador), ulnar (abdução dos dedos, sensibilidade do mínimo) e radial (extensão do punho); radiografia antes e depois da redução; fraturas associadas (cabeça do rádio, coronoide, epicôndilo medial na criança) definem a "tríade terrível" e a instabilidade.',
    comoProcurar: [
      { passo: 'Palpe os três pontos ósseos: com o cotovelo fletido a 90°, formam um triângulo isósceles; na luxação, o olécrano está atrás e acima.', detalhe: 'Na fratura supracondiliana, a relação está preservada — o diferencial na criança.' },
      { passo: 'Pulso radial e exame dos três nervos, documentado, antes de qualquer manobra.', detalhe: 'Pulso ausente após a redução: artéria braquial — cirurgia vascular.' },
      { passo: 'Radiografia AP e perfil; redução sob sedação com tração e flexão; radiografia de controle; tala por 1 a 2 semanas e mobilização precoce.', detalhe: 'Fragmento do epicôndilo medial preso na articulação após a redução na criança: cirurgia.' },
    ],
    mecanismo: 'Queda sobre a mão estendida com o cotovelo em extensão e valgo: a força axial e rotacional rompe o complexo ligamentar lateral (primeiro), a cápsula e, na luxação completa, o ligamento colateral medial — o círculo de Horii; o antebraço desliza para trás do úmero; o edema e o espasmo muscular bloqueiam o cotovelo. O nervo ulnar e a artéria braquial estão em risco pelo estiramento.',
    significado: 'Emergência ortopédica que se reduz na primeira hora; sem fratura, o prognóstico é bom com mobilização precoce (a imobilização longa gera rigidez, o problema tardio do cotovelo). Com fraturas (cabeça do rádio + coronoide = tríade terrível), a instabilidade recorrente exige cirurgia. A avaliação neurovascular documentada antes da redução é medicolegal.',
    armadilhas: ['Fratura supracondiliana do úmero na criança: cotovelo deformado com triângulo de Nélaton preservado — não tente "reduzir".', 'Pronação dolorosa (subluxação da cabeça do rádio) no pré-escolar: sem deformidade, reduz com supinação-flexão.', 'Luxação com ausência de pulso que "volta" após redução: ainda pode haver lesão íntima da braquial — observe.'],
    causas: [
      { titulo: 'Trauma', mecanismo: 'Queda sobre a mão estendida.', itens: ['Esportes (adolescentes e adultos jovens)', 'Quedas da própria altura em idosos', 'Acidentes de trânsito (tríade terrível)'] },
    ],
    referencias: ['O\'Driscoll SW et al. Elbow subluxation and dislocation. A spectrum of instability. Clin Orthop Relat Res, 1992.'],
  },
  {
    slug: 'luxacao-de-patela',
    nome: 'Luxação de patela',
    sinonimos: ['Luxação lateral da patela', 'Instabilidade patelofemoral', 'Sinal da apreensão'],
    sistema: 'musculoesqueletico',
    resumo: 'A patela sentada na face lateral do joelho, com o joelho travado em flexão e uma depressão onde ela deveria estar — a adolescente que girou com o pé fixo; ou, se já voltou sozinha, o joelho inchado de sangue com dor na borda medial da patela e pânico quando o examinador a empurra para fora (apreensão).',
    definicao: 'Deslocamento lateral da patela para fora da tróclea femoral: joelho em flexão de 20 a 30°, patela palpável e visível na face lateral do côndilo, depressão anterior, incapacidade de estender; a maioria reduz espontaneamente ao estender o joelho antes da chegada ao pronto-socorro — restam hemartrose, dor à palpação da borda medial da patela e do epicôndilo medial (ligamento patelofemoral medial rompido) e o sinal da apreensão positivo (o paciente contrai e afasta o examinador ao empurrar a patela lateralmente com o joelho a 30°); fatores predisponentes: patela alta, tróclea rasa, joelho valgo, hipermobilidade, sexo feminino, adolescência; fratura osteocondral em 25%.',
    comoProcurar: [
      { passo: 'Luxada: palpe a patela lateralmente e a depressão anterior; a radiografia pode esperar a redução (estender o joelho com pressão medial suave).', detalhe: 'Não confunda com luxação do joelho (tibiofemoral), emergência vascular.' },
      { passo: 'Reduzida: hemartrose, dor na borda medial, apreensão a 30°.', detalhe: 'Compare o deslizamento lateral (glide) com o outro joelho.' },
      { passo: 'Radiografia (axial de patela) e ressonância: fragmento osteocondral, lesão do LPFM.', detalhe: 'Primeiro episódio sem fragmento: conservador; recorrente: reconstrução do LPFM.' },
    ],
    mecanismo: 'Com o joelho semifletido, o pé fixo e o corpo rodando para dentro (valgo + rotação externa da tíbia), o quadríceps traciona a patela lateralmente; se a tróclea é rasa ou a patela alta, ela escapa, rompendo o ligamento patelofemoral medial — o principal freio — e raspando a faceta medial contra o côndilo lateral (fratura osteocondral, hemartrose).',
    significado: 'Luxação frequente na adolescência, com recidiva em 15 a 50% quando há predisposição anatômica; a hemartrose "sem ligamento cruzado" da adolescente é luxação de patela até prova contrária. Fragmento osteocondral livre é cirúrgico; sem ele, fisioterapia do vasto medial.',
    armadilhas: ['Luxação tibiofemoral: joelho grosseiramente deformado, pulso pedioso em risco — outra emergência.', 'Ruptura do ligamento cruzado anterior: mesma história de rotação e hemartrose; Lachman decide.', 'Luxação congênita ou habitual (a cada flexão) na criança com síndromes.'],
    causas: [
      { titulo: 'Instabilidade patelofemoral', mecanismo: 'Anatomia predisponente + torção.', itens: ['Displasia troclear, patela alta', 'Joelho valgo, anteversão femoral', 'Hipermobilidade (Ehlers-Danlos, Down)', 'Trauma direto na face medial'] },
    ],
    referencias: ['Fithian DC et al. Epidemiology and natural history of acute patellar dislocation. Am J Sports Med, 2004.'],
  },
  {
    slug: 'hemartrose-na-hemofilia',
    nome: 'Hemartrose na hemofilia',
    sinonimos: ['Artropatia hemofílica', 'Joelho hemofílico', 'Articulação-alvo'],
    sistema: 'musculoesqueletico',
    resumo: 'Menino com o joelho ou o cotovelo quente, inchado e tenso, sem trauma que justifique, que "sente" o sangramento começar como formigamento antes do inchaço — e, anos depois, a articulação deformada, com atrofia do quadríceps e contratura em flexão do hemofílico sem profilaxia.',
    definicao: 'Sangramento intra-articular espontâneo ou após trauma mínimo em pacientes com hemofilia A ou B (deficiência de fator VIII ou IX): aura (formigamento, calor), depois dor, edema tenso, calor e limitação, sem equimose externa proporcional; joelhos, cotovelos e tornozelos; "articulação-alvo" quando ≥ 3 sangramentos em 6 meses; artropatia crônica: sinovite hipertrófica, atrofia muscular (quadríceps), contratura em flexão, crepitação, deformidade e perda de movimento, com radiografia de osteopenia, epífises alargadas, alargamento da incisura intercondilar e erosões (escore de Pettersson); hemorragias musculares (iliopsoas) e pseudotumores em casos graves.',
    comoProcurar: [
      { passo: 'Hemofílico com dor e aura articular: trate como hemartrose antes de qualquer exame — infunda o fator.', detalhe: 'Não puncione de rotina; não faça injeção intramuscular.' },
      { passo: 'Meça a circunferência da coxa (atrofia) e a amplitude do joelho; procure contratura em flexão e valgo.', detalhe: 'Compare com a outra articulação; escore HJHS.' },
      { passo: 'Sangramento de iliopsoas: dor inguinal com quadril em flexão e parestesia do femoral — ultrassom.', detalhe: 'Ultrassom (HEAD-US) detecta sinovite e hemartrose subclínica.' },
    ],
    mecanismo: 'A sinóvia é vascular e o menor trauma sangra; sem fator de coagulação, o sangue se acumula na cavidade; o ferro e as enzimas dos macrófagos inflamam a sinóvia (sinovite hipertrófica, mais friável, que sangra mais — o ciclo da articulação-alvo) e degradam a cartilagem; a dor e a imobilização atrofiam o quadríceps; a contratura em flexão se instala. O resultado é a artropatia hemofílica, semelhante à artrose precoce.',
    significado: 'A hemartrose é a manifestação mais frequente da hemofilia e a artropatia, sua principal sequela; a profilaxia com fator (ou emicizumabe) desde a infância a previne e transformou a doença. Ver uma artropatia hemofílica estabelecida hoje é ver a hemofilia sem acesso a tratamento — ou um inibidor não diagnosticado.',
    armadilhas: ['Artrite séptica no hemofílico: febre e leucocitose — puncione com reposição de fator.', 'Hemartrose em quem não tem diagnóstico: história familiar, sangramentos de circuncisão, hematomas exagerados — coagulograma (TTPa alargado).', 'Doença de von Willebrand grave e deficiências raras também dão hemartrose.'],
    causas: [
      { titulo: 'Coagulopatia hereditária', mecanismo: 'Deficiência de fator.', itens: ['Hemofilia A (fator VIII)', 'Hemofilia B (fator IX)', 'Von Willebrand tipo 3', 'Deficiências raras (VII, X, XIII)'] },
      { titulo: 'Adquirida', mecanismo: 'Anticoagulação ou inibidor.', itens: ['Varfarina, anticoagulantes diretos', 'Hemofilia adquirida (autoanticorpo anti-VIII)'] },
    ],
    referencias: ['Srivastava A et al. WFH Guidelines for the Management of Hemophilia, 3rd edition. Haemophilia, 2020.'],
  },
  {
    slug: 'sinovite-de-punho',
    nome: 'Sinovite de punho',
    sistema: 'musculoesqueletico',
    sinonimos: ['Artrite de punho', 'Tenossinovite dos extensores', 'Punho inflamado', 'Tecla de piano da ulna'],
    resumo: 'Punho dorsalmente inchado, com edema mole e elástico que apaga os tendões, quente, doloroso à flexão e extensão passivas, às vezes com a ulna distal "solta" que afunda e rebate — a sinovite que na primeira consulta é artrite reumatoide precoce, e na gota ou na séptica, uma emergência.',
    definicao: 'Edema do punho de origem sinovial: tumefação dorsal difusa, mole, elástica, que se estende além dos tendões e não segue seu trajeto (diferente da tenossinovite, que forma salsicha sobre um tendão e move com ele), calor, dor à palpação da interlinha radiocárpica e à mobilização passiva, redução da amplitude; bilateral e simétrica na artrite reumatoide (com MCF), monoarticular na gota, pseudogota e infecção; sinal da tecla de piano (ulna distal instável e dolorosa) na sinovite radioulnar distal; sinovite crônica: cistos, ruptura de extensores (queda do dedo mínimo e anular — síndrome de Vaughan-Jackson).',
    comoProcurar: [
      { passo: 'Compare os dois punhos de dorso: os tendões extensores desaparecem sob o edema.', detalhe: 'Palpe a interlinha entre polegar e indicador em pinça, sem apertar demais.' },
      { passo: 'Diferencie tenossinovite (edema linear sobre o tendão, dor ao movê-lo contra resistência) de sinovite articular (dor à mobilização passiva do punho).', detalhe: 'Ultrassom com Doppler mostra sinóvia e vascularização.' },
      { passo: 'Bilateral com MCF: artrite reumatoide — FR, anti-CCP, radiografia, encaminhamento em semanas (janela de oportunidade). Mono aguda: puncione.', detalhe: 'Gota do punho é comum e simula séptica.' },
    ],
    mecanismo: 'A membrana sinovial das articulações radiocárpica, intercárpica e radioulnar distal, ou as bainhas dos tendões extensores, proliferam e produzem líquido inflamatório (autoimunidade, cristais, infecção); o pannus reumatoide erode o osso (estiloide ulnar é o primeiro sítio) e desgasta tendões sobre a ulna dorsal proeminente, que se rompem.',
    significado: 'O punho é, com as MCF, a articulação de apresentação da artrite reumatoide; sinovite persistente > 6 semanas em punhos e mãos pede reumatologia sem esperar, porque o tratamento nos primeiros meses muda o prognóstico. Sinovite monoarticular aguda é punção. Sinovite crônica com dedos que caem é tendão rompido — cirurgia.',
    armadilhas: ['Cisto sinovial dorsal (gânglio): nódulo localizado, tenso, transilumina — não é sinovite difusa.', 'Tenossinovite de De Quervain: dor no estiloide radial com Finkelstein positivo, sem sinovite articular.', 'Fratura de escafoide: dor na tabaqueira, sem edema difuso, radiografia inicial normal.', 'Doença por pirofosfato (pseudogota) no idoso: punho agudo com condrocalcinose no ligamento triangular.'],
    causas: [
      { titulo: 'Poliarticular', mecanismo: 'Sinovite autoimune.', itens: ['Artrite reumatoide', 'Artrite psoriásica', 'Lúpus', 'Artrite viral (parvovírus, chikungunya)'] },
      { titulo: 'Monoarticular', mecanismo: 'Cristais ou infecção.', itens: ['Gota', 'Pseudogota', 'Artrite séptica', 'Tuberculose do punho (crônica)'] },
    ],
    referencias: ['Aletaha D et al. 2010 rheumatoid arthritis classification criteria. Ann Rheum Dis, 2010.'],
  },
  {
    slug: 'escoliose-congenita-hemivertebra',
    nome: 'Escoliose congênita por hemivértebra',
    sinonimos: ['Hemivértebra', 'Malformação vertebral congênita', 'Escoliose congênita', 'Barra unilateral'],
    sistema: 'pediatrico',
    resumo: 'Uma curva curta, angular e rígida na coluna de uma criança pequena, que já estava lá no primeiro ano de vida e cresce com ela — uma vértebra que se formou pela metade (hemivértebra) ou duas que não se separaram (barra), e que exige olhar para os rins, o coração e a medula, porque se formaram na mesma semana.',
    definicao: 'Escoliose por malformação vertebral (falha de formação — hemivértebra em cunha, ou de segmentação — barra unilateral, bloco vertebral), visível ou palpável nos primeiros anos: curva curta e angular, rígida (não corrige com inclinação lateral), com giba precoce e assimetria do tronco, progressiva sobretudo no estirão; cutâneos: tufo de pelos, hemangioma, fosseta ou lipoma na linha média (disrafismo); associações: anomalias renais (20 a 30%), cardíacas (10 a 25%), medulares (siringomielia, medula presa, diastematomielia em 30 a 40%), VACTERL, síndrome de Klippel-Feil; radiografia mostra a hemivértebra (triangular, com pedículo único) e a ressonância, a medula.',
    comoProcurar: [
      { passo: 'Criança despida em pé (ou sustentada): curva curta, angular; teste de Adams com giba; inclinação lateral não corrige.', detalhe: 'Idiopática é longa, harmoniosa e do adolescente; congênita é curta e precoce.' },
      { passo: 'Linha média do dorso: pelos, hemangioma, fosseta, lipoma — marcadores de disrafismo.', detalhe: 'Exame neurológico dos membros inferiores, pés (cavo, assimetria), reflexos, controle esfincteriano.' },
      { passo: 'Radiografia panorâmica; ressonância de toda a coluna; ultrassom renal e ecocardiograma.', detalhe: 'Hemivértebra isolada progressiva: ressecção precoce (2 a 5 anos) evita a curva grande.' },
    ],
    mecanismo: 'Entre a 4ª e a 6ª semana embrionária, os somitos se segmentam e formam os corpos vertebrais; falha na formação de uma metade (hemivértebra) ou na segmentação entre dois níveis (barra) cria um crescimento assimétrico da coluna: o lado que tem placa de crescimento cresce, o outro não, e a curva aumenta a cada centímetro de altura. Os mesmos dias embrionários formam rins, coração e medula — daí as associações.',
    significado: 'A progressão depende da malformação: hemivértebra com barra contralateral é a pior (progride 5 a 10° por ano); hemivértebra incarcerada, quase não progride. Não responde a colete. O diagnóstico é uma triagem de malformações (rim, coração, medula) e a cirurgia precoce em curvas progressivas evita a deformidade grande e a doença pulmonar restritiva (síndrome da insuficiência torácica).',
    armadilhas: ['Escoliose infantil idiopática: curva longa, flexível, sem malformação — muitas resolvem sozinhas.', 'Escoliose neuromuscular (paralisia cerebral, mielomeningocele): curva longa em C com obliquidade pélvica.', 'Operar a coluna sem ressonância: medula presa ou diastematomielia não descoberta paralisa na correção.'],
    causas: [
      { titulo: 'Malformação vertebral', mecanismo: 'Falha de formação ou segmentação.', itens: ['Hemivértebra (segmentada, semisegmentada, incarcerada)', 'Barra unilateral não segmentada', 'Vértebra em borboleta, bloco vertebral', 'Associações: VACTERL, Klippel-Feil, diabetes materno, ácido valproico'] },
    ],
    referencias: ['Hedequist D, Emans J. Congenital scoliosis: a review and update. J Pediatr Orthop, 2007.'],
  },
  {
    slug: 'osteomielite-cronica-com-fistula',
    nome: 'Osteomielite crônica com fístula',
    sinonimos: ['Fístula osteocutânea', 'Sequestro ósseo', 'Osteomielite pós-traumática', 'Úlcera de Marjolin (complicação)'],
    sistema: 'musculoesqueletico',
    resumo: 'Um orifício na pele sobre a tíbia ou o fêmur, com bordas violáceas e pele cicatricial ao redor, que drena secreção purulenta intermitentemente há meses ou anos, fecha e reabre — sob ele, um osso morto (sequestro) que o corpo não consegue eliminar nem esterilizar.',
    definicao: 'Infecção óssea persistente (> 6 semanas, geralmente anos) com trajeto fistuloso da cavidade óssea à pele: orifício cutâneo único ou múltiplo com secreção purulenta ou serossanguinolenta intermitente, bordas retraídas e pele adjacente espessada, hiperpigmentada ou cicatricial, às vezes com fragmento ósseo saindo pelo orifício; dor surda, edema local, deformidade ou encurtamento do membro após fratura exposta ou osteomielite hematogênica da infância mal tratada; episódios de agudização com celulite e febre; radiografia com sequestro (osso denso, morto) envolvido por invólucro (osso reativo) e cloaca; fístula de décadas com massa vegetante e sangrante: carcinoma espinocelular (úlcera de Marjolin).',
    comoProcurar: [
      { passo: 'Sonde a fístula com estilete estéril: se toca osso (probe-to-bone), é osteomielite.', detalhe: 'Cultura do swab da fístula não serve — cresce flora de pele; biópsia óssea sim.' },
      { passo: 'Procure a cicatriz de fratura exposta ou de cirurgia; meça o encurtamento e a deformidade.', detalhe: 'Osteomielite hematogênica da infância deixa o membro curto.' },
      { passo: 'Radiografia (sequestro, invólucro); ressonância ou TC para planejar; biópsia com cultura para guiar o antibiótico.', detalhe: 'Mudança recente da fístula (crescimento, sangramento, dor): biópsia da borda — Marjolin.' },
    ],
    mecanismo: 'Osso desvitalizado (por trauma, isquemia da infecção aguda ou material de síntese) não é penetrado por antibióticos nem por células de defesa; bactérias formam biofilme sobre ele e sobre implantes; o organismo isola o sequestro com osso novo (invólucro) e drena o pus por aberturas (cloacas) até a pele — a fístula. Sem remover o sequestro, o ciclo não termina. Décadas de inflamação crônica e reepitelização induzem carcinoma na borda da fístula.',
    significado: 'Doença de países com fraturas expostas mal tratadas e osteomielite infantil não resolvida; o tratamento é cirúrgico (sequestrectomia, desbridamento, cobertura de partes moles) com antibiótico guiado por cultura óssea — antibiótico sozinho nunca cura. A fístula antiga que muda é câncer até a biópsia dizer o contrário.',
    armadilhas: ['Swab da fístula orientando antibiótico: erro clássico — biópsia óssea.', 'Tuberculose óssea e micetoma (pé de Madura — grãos na secreção) na fístula crônica.', 'Osteomielite do pé diabético: mesma lógica (probe-to-bone), outra circulação.', 'Úlcera de Marjolin diagnosticada tarde: amputação.'],
    causas: [
      { titulo: 'Osteomielite crônica', mecanismo: 'Sequestro e biofilme.', itens: ['Pós-traumática (fratura exposta)', 'Pós-cirúrgica (implante)', 'Hematogênica da infância mal tratada', 'Contígua (úlcera de pressão, pé diabético)', 'Tuberculose, micetoma, brucelose'] },
    ],
    referencias: ['Lew DP, Waldvogel FA. Osteomyelitis. Lancet, 2004.'],
  },
  {
    slug: 'pe-equino-na-paralisia-cerebral',
    nome: 'Pé equino na paralisia cerebral',
    sinonimos: ['Equino espástico', 'Marcha na ponta dos pés', 'Pé equinovaro espástico', 'Diplegia espástica'],
    sistema: 'neurologico',
    resumo: 'Criança que anda e fica em pé na ponta dos pés, com o calcanhar sem tocar o chão, os joelhos semifletidos e as coxas cruzando (tesoura) — o tríceps sural espástico da paralisia cerebral que, com os anos, encurta e vira contratura fixa.',
    definicao: 'Flexão plantar persistente do tornozelo por espasticidade do tríceps sural: em pé, apoio no antepé com calcanhar elevado; dinâmico (corrige passivamente com o joelho fletido e estendido; catch ao alongamento rápido — sinal de Tardieu) ou fixo (contratura: dorsiflexão passiva não chega a 0° mesmo lentamente, com o joelho estendido — teste de Silfverskiöld diferencia gastrocnêmio de sóleo); varo do retropé e adução do antepé associados (equinovaro, hemiplegia) ou valgo (diplegia); marcha em tesoura por espasticidade dos adutores, joelhos em flexão (crouch) na diplegia tardia; reflexos exaltados, clônus de tornozelo, Babinski; calosidades sob os metatarsos.',
    comoProcurar: [
      { passo: 'Observe a criança em pé e andando, descalça: apoio inicial pelo antepé, calcanhar não toca.', detalhe: 'Na criança que anda na ponta sem espasticidade, pense em marcha idiopática na ponta dos pés, autismo, distrofia muscular.' },
      { passo: 'Dorsiflexão passiva lenta com o joelho fletido e estendido (Silfverskiöld) e depois rápida (Tardieu, ângulo do catch).', detalhe: 'Lenta não chega a neutro = contratura; só rápida trava = espasticidade dinâmica.' },
      { passo: 'Classifique a função (GMFCS) e o padrão (hemi, di, quadriplegia); avalie quadris (subluxação) e coluna.', detalhe: 'Dinâmico: toxina botulínica + órtese + fisioterapia; fixo: alongamento cirúrgico.' },
    ],
    mecanismo: 'Lesão do neurônio motor superior no cérebro imaturo (prematuridade, hipóxia, malformação) libera o reflexo de estiramento: o tríceps sural, mais forte que o tibial anterior, mantém o tornozelo em flexão plantar; o músculo espástico cresce menos que o osso (sarcômeros em série não aumentam) e encurta relativamente — a espasticidade dinâmica vira contratura fixa; deformidades ósseas secundárias seguem.',
    significado: 'Deformidade mais comum da paralisia cerebral e a que mais impacta a marcha; tratada por fases (toxina, órteses, alongamentos, cirurgia multinível) para manter a marcha e evitar o crouch. O exame que distingue dinâmico de fixo (Silfverskiöld, Tardieu) decide entre toxina e bisturi.',
    armadilhas: ['Marcha idiopática na ponta dos pés: criança normal, corrige à vontade, sem espasticidade.', 'Distrofia muscular de Duchenne: equino por fraqueza com pseudo-hipertrofia de panturrilhas e Gowers.', 'Pé torto congênito residual: rígido desde o nascimento.', 'Alongar demais o Aquiles na diplegia: crouch gait irreversível.'],
    causas: [
      { titulo: 'Espasticidade do tríceps sural', mecanismo: 'Lesão do neurônio motor superior.', itens: ['Paralisia cerebral (hemi, di, quadriplegia)', 'Sequela de AVC infantil ou adulto', 'Lesão medular, paraparesia espástica hereditária', 'Traumatismo cranioencefálico'] },
    ],
    referencias: ['Graham HK et al. Cerebral palsy. Nat Rev Dis Primers, 2016.'],
  },
  {
    slug: 'coto-de-amputacao',
    nome: 'Coto de amputação — o que examinar',
    sinonimos: ['Coto transtibial e transfemoral', 'Avaliação do coto', 'Neuroma de coto', 'Dor fantasma'],
    sistema: 'musculoesqueletico',
    resumo: 'O coto bem feito tem forma cônica ou cilíndrica, cicatriz fina fora da zona de carga, coxim muscular acolchoando o osso e pele íntegra; o coto problemático tem osso saliente sob pele fina, cicatriz aderente, bolsa de pele redundante, verrucosidades, úlceras de pressão do encaixe e um ponto que dispara choque ao toque — o neuroma.',
    definicao: 'Exame do membro residual: nível (transtibial, transfemoral, desarticulação, parcial de pé), comprimento (curto < 12 cm tibial dificulta a prótese), forma (cônica ideal; bulbosa, cilíndrica ou em "cauda de peixe" com pele redundante), cicatriz (posição, aderência, deiscência, queloide), pele (úlceras e eritema nas zonas de pressão do encaixe — crista tibial, cabeça da fíbula; hiperplasia verrucosa distal por edema crônico; foliculite e dermatite de contato), coxim de partes moles sobre o osso, proeminências e esporões ósseos, sensibilidade (sinal de Tinel no ponto de neuroma — dor em choque irradiada), dor fantasma × dor de coto, amplitude articular proximal (contratura em flexão do joelho ou do quadril impede a prótese), força e equilíbrio; estado vascular e do membro contralateral no vasculopata.',
    comoProcurar: [
      { passo: 'Coto despido e prótese ao lado: forma, cicatriz, pele, pontos de pressão marcados pelo encaixe.', detalhe: 'Peça para mostrar onde dói e onde a prótese aperta.' },
      { passo: 'Palpe a extremidade óssea (proeminência, esporão) e percuta em busca de neuroma (Tinel).', detalhe: 'Dor no coto ao toque é neuroma ou osso; dor no pé que não existe é fantasma.' },
      { passo: 'Mobilize joelho e quadril: contratura em flexão > 15° compromete a marcha.', detalhe: 'No vasculopata, examine o outro pé — é o próximo em risco.' },
    ],
    mecanismo: 'O coto é uma interface biológica com uma peça mecânica: o osso sem coxim ulcera a pele contra o encaixe; a pele redundante e o edema distal (encaixe frouxo, efeito de pistão) produzem hiperplasia verrucosa; os nervos seccionados regeneram desordenadamente em neuromas que descarregam à pressão; a representação cortical do membro persiste e gera sensação e dor fantasma (mais em amputações traumáticas e com dor pré-amputação); a posição de conforto (flexão) contrai as articulações proximais se não alongadas desde o pós-operatório.',
    significado: 'O sucesso da reabilitação depende do coto: forma, cobertura e articulações livres definem se o paciente andará. O exame identifica o que a prótese precisa mudar (encaixe), o que a cirurgia precisa revisar (osso, neuroma, pele) e o que o remédio precisa tratar (dor fantasma — gabapentinoides, terapia do espelho). No vasculopata, o exame do coto inclui o outro pé.',
    armadilhas: ['Tratar dor de neuroma como dor fantasma (e vice-versa): exame do coto decide.', 'Úlcera do coto no diabético atribuída à prótese: pode ser isquemia — Doppler.', 'Contratura em flexão de joelho ignorada até a prótese pronta.', 'Hiperplasia verrucosa tratada como infecção: é edema por encaixe inadequado.'],
    causas: [
      { titulo: 'Amputação', mecanismo: 'Perda do segmento.', itens: ['Vasculopatia periférica e diabetes (80% no adulto)', 'Trauma (jovens)', 'Tumor ósseo (sarcoma)', 'Infecção (fasciíte, osteomielite)', 'Congênita (deficiência de membro)'] },
    ],
    referencias: ['Dillingham TR et al. Limb amputation and limb deficiency: epidemiology and recent trends in the United States. South Med J, 2002.', 'Highsmith MJ et al. Prosthetic interventions for people with transtibial amputation: systematic review and meta-analysis of high-quality prospective literature and systematic reviews. J Rehabil Res Dev, 2016.'],
  },
]
