import type { Sinal } from './esquemas'

/**
 * Quarta leva, parte 1 — pele e infecções cutâneas do dia a dia do
 * pronto-socorro e da atenção primária, mais a dermatologia tropical que o
 * atlas estrangeiro não cobre e o Brasil vê toda semana.
 */
export const SINAIS_LEVA_4_PELE: Sinal[] = [
  {
    slug: 'tinha-do-corpo',
    nome: 'Tinha do corpo',
    sinonimos: ['Tinea corporis', 'Impingem', 'Ringworm'],
    sistema: 'pele',
    resumo: 'Placa anular com borda ativa, elevada e descamativa, que avança para fora enquanto o centro clareia — o dermatófito caminha na periferia.',
    definicao: 'Uma ou mais placas eritematodescamativas de crescimento centrífugo, com borda nítida, elevada, às vezes vesiculosa, e centro mais claro ("cura central"); prurido variável. Pele glabra do tronco e membros.',
    comoProcurar: [
      { passo: 'Procure a borda: é ela que está viva.', detalhe: 'Descamação e pequenas vesículas na periferia; o centro é apagado.' },
      { passo: 'Raspe a borda para exame direto com KOH.', detalhe: 'Raspar o centro dá falso-negativo — lá o fungo já foi embora.' },
      { passo: 'Examine pés, virilha e unhas: a fonte costuma estar lá.', detalhe: 'E pergunte por animais em casa (Microsporum canis).' },
    ],
    mecanismo: 'Dermatófitos (Trichophyton, Microsporum, Epidermophyton) digerem queratina e migram radialmente pelo estrato córneo; a resposta inflamatória vem atrás e limpa o centro, deixando a borda como frente de avanço.',
    significado: 'Diagnóstico clínico que o KOH confirma. Placas múltiplas, extensas ou refratárias pedem pesquisa de imunossupressão e diabetes. Corticoide tópico antes do diagnóstico produz a "tinha incógnita": borda apagada, lesão irreconhecível.',
    armadilhas: ['Eritema anular centrífugo, granuloma anular e pitiríase rósea também são anulares — sem descamação na borda e com KOH negativo.', 'Tinha incógnita depois de corticoide: quase sem borda.'],
    causas: [
      { titulo: 'Dermatófitos', mecanismo: 'Queratinofilia com avanço radial.', itens: ['Trichophyton rubrum', 'Trichophyton mentagrophytes', 'Microsporum canis (contato com gato e cão)'] },
    ],
    referencias: ['Ely JW et al. Diagnosis and management of tinea infections. Am Fam Physician, 2014.'],
  },
  {
    slug: 'tinha-do-pe',
    nome: 'Tinha do pé',
    sinonimos: ['Pé de atleta', 'Tinea pedis', 'Frieira', 'Intertrigo interdigital'],
    sistema: 'pele',
    resumo: 'Maceração esbranquiçada e fissura entre o quarto e o quinto dedos, ou descamação seca "em mocassim" — a micose mais comum do mundo e a porta de entrada da erisipela.',
    definicao: 'Três padrões: interdigital (maceração, fissura e odor nos espaços laterais), em mocassim (hiperceratose e descamação fina difusa da planta e bordas) e vesicobolhoso (vesículas no arco plantar). Prurido e ardor.',
    comoProcurar: [
      { passo: 'Afaste os dedos, sobretudo o quarto espaço.', detalhe: 'É o mais fechado e úmido; a fissura no fundo é a porta da erisipela.' },
      { passo: 'Olhe a planta e as bordas: descamação em mocassim é fácil de tomar por pele seca.', detalhe: 'Unilateral ou assimétrica fala por fungo.' },
      { passo: 'Em toda erisipela de perna, procure a tinha entre os dedos.', detalhe: 'Tratar a porta de entrada previne a recorrência.' },
    ],
    mecanismo: 'Umidade e oclusão do calçado favorecem o dermatófito; a maceração interdigital costuma ser mista (fungo + bactérias). As fissuras rompem a barreira epidérmica e deixam estreptococo entrar para a derme.',
    significado: 'Quase sempre benigna, mas é o fator de risco modificável mais frequente para erisipela e celulite de membro inferior; no diabético, porta de entrada para infecção do pé.',
    armadilhas: ['Eczema disidrótico e psoríase plantar imitam a forma vesicobolhosa e a forma seca — KOH decide.', 'Eritrasma interdigital (fluorescência vermelho-coral à luz de Wood) é bactéria, não fungo.'],
    causas: [
      { titulo: 'Dermatófitos', mecanismo: 'Umidade, oclusão e contato em pisos molhados.', itens: ['Trichophyton rubrum (mocassim)', 'Trichophyton interdigitale (interdigital e vesicular)'] },
    ],
    referencias: ['Ilkit M, Durdu M. Tinea pedis. Crit Rev Microbiol, 2015.'],
  },
  {
    slug: 'onicomicose',
    nome: 'Onicomicose',
    sinonimos: ['Tinea unguium', 'Micose de unha'],
    sistema: 'pele',
    resumo: 'Unha espessa, amarelada, quebradiça, com detrito sob a lâmina que a descola a partir da borda livre — a onicólise distal que começa num canto e avança.',
    definicao: 'Alteração da lâmina ungueal por fungo: onicólise e hiperceratose subungueal a partir da borda distal ou lateral (subungueal distal-lateral, a forma mais comum), manchas brancas superficiais, ou destruição total distrófica.',
    comoProcurar: [
      { passo: 'Compare com as outras unhas: assimetria e início distal-lateral.', detalhe: 'Psoríase ungueal costuma ser simétrica e ter pitting.' },
      { passo: 'Raspe o detrito subungueal, o mais proximal possível, para KOH e cultura.', detalhe: 'A ponta da unha está morta — o fungo vivo fica na frente de avanço.' },
      { passo: 'Procure tinha do pé associada.', detalhe: 'Está presente em um terço; sem tratá-la, a unha reinfecta.' },
    ],
    mecanismo: 'O dermatófito entra pelo hiponíquio, invade o leito e a face inferior da lâmina, produz queratina defeituosa e detrito que descola a unha; o crescimento lento da unha do pé (um ano para renovar) explica a cronicidade.',
    significado: 'Mais que estética: no diabético e no vasculopata, a unha deformada lesa o dedo vizinho e abre porta para infecção. Confirmar antes de tratar — 50% das distrofias ungueais não são fungo e a terbinafina oral não é inócua.',
    armadilhas: ['Psoríase, líquen plano, trauma repetido e onicogrifose do idoso imitam — todos KOH-negativos.', 'Melanoníquia ou massa subungueal: pense em melanoma antes de chamar de micose.'],
    causas: [
      { titulo: 'Dermatófitos', mecanismo: 'Invasão distal do leito ungueal.', itens: ['Trichophyton rubrum (90%)', 'Trichophyton interdigitale'] },
      { titulo: 'Não dermatófitos', mecanismo: 'Oportunistas em unha já lesada.', itens: ['Candida (mãos, paroníquia crônica)', 'Fusarium, Scopulariopsis'] },
    ],
    referencias: ['Lipner SR, Scher RK. Onychomycosis: clinical overview and diagnosis. J Am Acad Dermatol, 2019.'],
  },
  {
    slug: 'paroniquia',
    nome: 'Paroníquia aguda',
    sinonimos: ['Panarício periungueal', 'Unheiro'],
    sistema: 'pele',
    resumo: 'Prega ungueal lateral vermelha, quente, tensa e muito dolorosa, às vezes com ponto de pus visível — abscesso da dobra da unha, quase sempre por estafilococo.',
    definicao: 'Inflamação aguda (< 6 semanas) da prega ungueal proximal ou lateral: eritema, edema e dor intensa, com ou sem coleção purulenta flutuante sob a dobra ou sob a lâmina.',
    comoProcurar: [
      { passo: 'Pressione a prega: flutuação e saída de pus dizem que há coleção.', detalhe: 'Sem flutuação, ainda é celulite — antibiótico e compressa morna.' },
      { passo: 'Veja se o pus estende-se sob a lâmina (abscesso subungueal).', detalhe: 'Precisa remover parte da unha para drenar.' },
      { passo: 'Pergunte por cutícula arrancada, roer unha, manicure.', detalhe: 'É a porta de entrada em quase todos.' },
    ],
    mecanismo: 'Rompimento da barreira entre a cutícula e a lâmina permite que Staphylococcus aureus (ou anaeróbios da boca em quem rói unhas) colonize o espaço sob a prega, que é fechado e se transforma em abscesso sob pressão.',
    significado: 'Problema pequeno com solução mecânica: drenar. Não confundir com a forma crônica (Candida, exposição a água, prega tumefeita sem pus) nem com o panarício herpético, que não deve ser incisado.',
    armadilhas: ['Panarício herpético: vesículas agrupadas sobre base eritematosa, dor desproporcional — incisar espalha o vírus.', 'Paroníquia crônica de quem trabalha com as mãos molhadas: Candida e irritantes, sem abscesso.'],
    causas: [
      { titulo: 'Aguda', mecanismo: 'Infecção bacteriana da dobra ungueal.', itens: ['Staphylococcus aureus', 'Streptococcus', 'Anaeróbios orais (roer unhas)'] },
      { titulo: 'Crônica', mecanismo: 'Dermatite irritativa com Candida.', itens: ['Exposição a água e detergentes', 'Diabetes', 'Retinoides e inibidores de EGFR'] },
    ],
    referencias: ['Leggit JC. Acute and chronic paronychia. Am Fam Physician, 2017.'],
  },
  {
    slug: 'unha-encravada',
    nome: 'Unha encravada',
    sinonimos: ['Onicocriptose'],
    sistema: 'pele',
    resumo: 'Borda lateral da unha do hálux enterrada na prega, que responde com dor, eritema e um tecido de granulação vermelho e úmido que sangra ao toque.',
    definicao: 'Penetração da borda lateral da lâmina ungueal na prega periungueal, com inflamação (estágio 1), infecção e drenagem (estágio 2) ou tecido de granulação hipertrófico cobrindo a unha (estágio 3). Quase sempre no hálux.',
    comoProcurar: [
      { passo: 'Afaste a prega com cuidado e veja a espícula da unha entrando na pele.', detalhe: 'É ela que precisa sair; antibiótico sozinho não resolve.' },
      { passo: 'Classifique: só inflamação, pus, ou granulação.', detalhe: 'Define entre curativo, espiculectomia e matricectomia.' },
      { passo: 'Pergunte como corta a unha e que calçado usa.', detalhe: 'Corte curvo e bico estreito são as causas que voltam.' },
    ],
    mecanismo: 'O corte arredondado deixa uma espícula lateral que, ao crescer, perfura a prega; o corpo estranho (a própria unha) desencadeia inflamação, infecção secundária e granulação exuberante.',
    significado: 'Banal no saudável; no diabético e no arteriopata é ferida de pé que pode evoluir para osteomielite da falange — merece o mesmo respeito de qualquer úlcera de pé.',
    armadilhas: ['Granulação exuberante crônica em adolescente pode ser confundida com granuloma piogênico ou até melanoma amelanótico — se atípica, biopsie.'],
    causas: [
      { titulo: 'Mecânica', mecanismo: 'Espícula lateral perfura a prega.', itens: ['Corte curvo da unha', 'Calçado apertado', 'Hiperidrose', 'Deformidade da unha (pinça)'] },
    ],
    referencias: ['Mayeaux EJ et al. Ingrown toenail management. Am Fam Physician, 2019.'],
  },
  {
    slug: 'verruga-vulgar',
    nome: 'Verruga vulgar e plantar',
    sinonimos: ['Verruca vulgaris', 'Olho de peixe', 'Verruga viral'],
    sistema: 'pele',
    resumo: 'Pápula áspera, hiperceratósica, que apaga as linhas da pele e mostra pontos pretos ao ser raspada — os capilares trombosados que a distinguem do calo.',
    definicao: 'Pápula ou placa ceratósica de superfície verrucosa, com pontos pretos (capilares trombosados) e interrupção dos dermatóglifos; na planta, cresce para dentro (endofítica), dolorosa à compressão lateral, sob pontos de apoio.',
    comoProcurar: [
      { passo: 'Raspe a superfície com lâmina: pontos pretos e sangramento puntiforme.', detalhe: 'O calo raspado mostra só queratina homogênea.' },
      { passo: 'Veja se as linhas da pele contornam ou atravessam a lesão.', detalhe: 'Verruga interrompe os dermatóglifos; calo os preserva.' },
      { passo: 'Aperte lateralmente: dói na verruga plantar; o calo dói à pressão direta.', detalhe: 'Diferença simples e confiável.' },
    ],
    mecanismo: 'Papilomavírus humano (HPV 1, 2, 4, 27, 57) infecta queratinócitos basais por microtrauma e induz hiperproliferação epidérmica com acantose e papilomatose; os vasos das papilas dérmicas alongadas trombosam e aparecem como pontos pretos.',
    significado: 'Autolimitada em dois terços dos casos em dois anos. Verrugas numerosas, extensas ou recalcitrantes em adulto pedem avaliação de imunossupressão (HIV, transplante).',
    armadilhas: ['Calo e clavo plantar são a confusão clássica — o teste da raspagem resolve.', 'Lesão verrucosa única, crescendo, em idoso ou sob unha: carcinoma espinocelular verrucoso até prova contrária.'],
    causas: [
      { titulo: 'HPV cutâneo', mecanismo: 'Infecção epidérmica por microtrauma.', itens: ['HPV 1 (plantar profunda)', 'HPV 2, 27, 57 (vulgar)', 'HPV 4 (plantar em mosaico)'] },
    ],
    referencias: ['Sterling JC et al. BAD guidelines for the management of cutaneous warts. Br J Dermatol, 2014.'],
  },
  {
    slug: 'herpes-labial',
    nome: 'Herpes labial',
    sinonimos: ['Herpes simples recorrente', 'Cold sore', 'Febre no lábio'],
    sistema: 'pele',
    resumo: 'Vesículas agrupadas em cacho sobre base vermelha na junção do vermelhão do lábio, precedidas de ardor e formigamento — a recorrência do HSV-1 no mesmo lugar de sempre.',
    definicao: 'Agrupamento de vesículas de 1 a 3 mm, tensas, sobre base eritematosa, na borda do vermelhão ou pele perioral, que se rompem em 2 a 3 dias e viram erosões e crostas; pródromo sensitivo local. Recorre no mesmo sítio.',
    comoProcurar: [
      { passo: 'Procure o padrão em cacho: várias vesículas do mesmo tamanho, juntas.', detalhe: 'Impetigo tem crosta melicérica e não respeita o cacho.' },
      { passo: 'Pergunte pelo pródromo e por episódios anteriores no mesmo lugar.', detalhe: 'Recorrência no mesmo sítio é quase diagnóstica.' },
      { passo: 'Em imunossuprimido, olhe extensão e profundidade.', detalhe: 'Úlceras grandes e persistentes: herpes crônico.' },
    ],
    mecanismo: 'HSV-1 latente no gânglio trigeminal reativa-se (sol, febre, estresse, menstruação), desce pelo axônio e replica na epiderme, formando vesículas intraepidérmicas por degeneração balonizante dos queratinócitos.',
    significado: 'Benigno e autolimitado; o problema está nas exceções — eczema herpético no atópico, ceratite quando alcança o olho, e disseminação no imunossuprimido. Contagioso enquanto há vesícula.',
    armadilhas: ['Impetigo, queilite angular e aftas — a afta é dentro da boca, em mucosa não queratinizada; herpes recorrente é na borda do lábio ou no palato duro/gengiva.', 'Panarício herpético em quem chupa o dedo ou em profissional de saúde.'],
    causas: [
      { titulo: 'HSV-1 (raramente HSV-2)', mecanismo: 'Reativação a partir do gânglio trigeminal.', itens: ['Exposição solar', 'Febre e infecções', 'Estresse e privação de sono', 'Trauma local, procedimentos dentários'] },
    ],
    referencias: ['Arduino PG, Porter SR. Herpes simplex virus type 1 infection: overview on relevant clinico-pathological features. J Oral Pathol Med, 2008.'],
  },
  {
    slug: 'furunculo-e-carbunculo',
    nome: 'Furúnculo e carbúnculo',
    sinonimos: ['Furunculose', 'Antraz estafilocócico', 'Boil'],
    sistema: 'pele',
    resumo: 'Nódulo vermelho, quente e doloroso centrado num pelo, que amolece e drena pus com um "carnegão" — quando vários se fundem num placa com múltiplos orifícios, é carbúnculo.',
    definicao: 'Furúnculo: abscesso agudo do folículo piloso e tecido perifolicular, nódulo eritematoso doloroso de 1 a 2 cm que evolui para flutuação e drenagem de pus com o tampão necrótico. Carbúnculo: coalescência de vários furúnculos em placa indurada com múltiplas fístulas, febre e mal-estar, típica da nuca e do dorso.',
    comoProcurar: [
      { passo: 'Identifique o pelo no centro: é folicular.', detalhe: 'Hidradenite é em dobras e não centra em pelo; cisto epidérmico inflamado tem história de nódulo prévio.' },
      { passo: 'Toque para flutuação: define drenagem.', detalhe: 'Furúnculo sem flutuação: calor local e aguardar; não esprema.' },
      { passo: 'Conte os orifícios de drenagem: mais de um, é carbúnculo.', detalhe: 'Carbúnculo pede antibiótico sistêmico e exclusão de diabetes.' },
    ],
    mecanismo: 'Staphylococcus aureus penetra pelo óstio folicular e provoca necrose do folículo com abscesso perifolicular; no carbúnculo a infecção dissemina pelos septos do tecido subcutâneo espesso da nuca e do dorso, conectando folículos vizinhos.',
    significado: 'Furúnculo isolado: drenagem resolve. Recorrência (furunculose) aponta para portador nasal de S. aureus, diabetes, obesidade ou imunodeficiência; carbúnculo e lesões da face (triângulo nasolabial) exigem antibiótico pelo risco de bacteremia e trombose de seio cavernoso.',
    armadilhas: ['Cisto epidérmico roto e inflamado é o principal imitador — tem história e cápsula.', 'Furúnculo no triângulo da face: não esprema.', 'Miíase furunculoide em quem viajou: orifício central com serosidade e o "movimento".'],
    causas: [
      { titulo: 'Infecção folicular', mecanismo: 'Abscesso perifolicular.', itens: ['Staphylococcus aureus (MSSA e MRSA comunitário)'] },
      { titulo: 'Predisponentes da recorrência', mecanismo: 'Colonização e imunidade local.', itens: ['Portador nasal', 'Diabetes', 'Obesidade e atrito', 'Imunossupressão, HIV'] },
    ],
    referencias: ['Stevens DL et al. IDSA practice guidelines for skin and soft tissue infections. Clin Infect Dis, 2014.'],
  },
  {
    slug: 'dermatite-atopica',
    nome: 'Dermatite atópica',
    sinonimos: ['Eczema atópico', 'Liquenificação flexural'],
    sistema: 'pele',
    resumo: 'Placas eczematosas nas dobras dos cotovelos e joelhos, com pele espessada e riscada pela coçadura crônica — a liquenificação que conta a história do prurido.',
    definicao: 'Dermatose crônica pruriginosa com padrão por idade: no lactente, eczema exsudativo em face e superfícies extensoras; na criança e no adulto, placas liquenificadas nas fossas antecubitais e poplíteas, pescoço e punhos; xerose difusa; história pessoal ou familiar de atopia.',
    comoProcurar: [
      { passo: 'Vá às dobras: fossas antecubital e poplítea.', detalhe: 'Liquenificação (pele espessa com quadriculado acentuado) marca cronicidade.' },
      { passo: 'Procure sinais menores: prega de Dennis-Morgan, escurecimento periorbital, ceratose pilar, xerose.', detalhe: 'Apoiam quando a distribuição é atípica.' },
      { passo: 'Pergunte por asma, rinite e prurido noturno.', detalhe: 'O prurido é o sintoma cardinal: sem coceira, não é atópica.' },
    ],
    mecanismo: 'Defeito de barreira (mutações de filagrina) deixa entrar alérgenos e irritantes; resposta Th2 com IL-4, IL-13 e IL-31 gera inflamação e prurido; a coçadura engrossa a epiderme (liquenificação) e perpetua o ciclo.',
    significado: 'Diagnóstico clínico pelos critérios de Hanifin-Rajka ou UK Working Party. Sinaliza risco de infecções cutâneas (S. aureus, eczema herpético) e de asma. Gravidade se mede pela extensão e pelo sono perdido.',
    armadilhas: ['Escabiose em criança com prurido difuso — procure túneis nos espaços interdigitais.', 'Dermatite de contato sobreposta em adulto com atopia de longa data.', 'Eczema herpético: piora súbita com vesículas monomórficas e erosões "em saca-bocado" — emergência.'],
    causas: [
      { titulo: 'Barreira e imunidade', mecanismo: 'Filagrina deficiente e inflamação Th2.', itens: ['Predisposição genética (filagrina)', 'Marcha atópica: asma, rinite'] },
      { titulo: 'Gatilhos', mecanismo: 'Irritação e sensibilização.', itens: ['Sabões e banhos quentes', 'Lã e suor', 'Colonização por S. aureus', 'Estresse'] },
    ],
    referencias: ['Langan SM et al. Atopic dermatitis. Lancet, 2020.'],
  },
  {
    slug: 'dermatite-seborreica',
    nome: 'Dermatite seborreica',
    sinonimos: ['Caspa', 'Eczema seborreico', 'Crosta láctea (lactente)'],
    sistema: 'pele',
    resumo: 'Escamas amareladas e gordurosas sobre base rosada nos sulcos nasogenianos, sobrancelhas, couro cabeludo e tórax — onde há sebo, há Malassezia.',
    definicao: 'Placas eritematosas mal delimitadas com escamas oleosas amareladas nas áreas seborreicas: couro cabeludo, sulcos nasolabiais, glabela, sobrancelhas, região retroauricular, conduto auditivo e região pré-esternal. No lactente, crosta láctea aderente no couro cabeludo.',
    comoProcurar: [
      { passo: 'Olhe os sulcos nasogenianos e a glabela.', detalhe: 'Escama gordurosa amarelada, não a prateada seca da psoríase.' },
      { passo: 'Afaste o cabelo e veja o couro cabeludo e a região retroauricular.', detalhe: 'Fissura retroauricular é típica.' },
      { passo: 'Se for extensa, súbita ou refratária em adulto jovem, pense em HIV.', detalhe: 'Seborreica explosiva é sinal de imunossupressão.' },
    ],
    mecanismo: 'Malassezia, lipofílica, metaboliza os triglicerídeos do sebo em ácidos graxos livres irritantes; em indivíduos suscetíveis a resposta inflamatória gera eritema e descamação nas áreas de maior densidade de glândulas sebáceas. Piora com estresse, frio e doença neurológica.',
    significado: 'Crônica e recidivante, benigna. Ganha importância como marcador: forma grave e extensa em adulto jovem está associada ao HIV (até 80% dos pacientes com AIDS), e é frequente na doença de Parkinson.',
    armadilhas: ['Psoríase do couro cabeludo e da face ("sebopsoríase") — escama mais espessa e prateada, placas bem delimitadas, unhas.', 'Rosácea: pápulas e pústulas, sem escama.', 'Lúpus cutâneo na face: fotossensível, poupa os sulcos.'],
    causas: [
      { titulo: 'Malassezia e sebo', mecanismo: 'Irritação por ácidos graxos livres.', itens: ['Constitucional', 'Adolescência e adulto jovem'] },
      { titulo: 'Associações', mecanismo: 'Imunossupressão ou hipocinesia facial.', itens: ['HIV/AIDS', 'Doença de Parkinson', 'Neurolépticos'] },
    ],
    referencias: ['Borda LJ, Wikramanayake TC. Seborrheic dermatitis and dandruff: a comprehensive review. J Clin Investig Dermatol, 2015.'],
  },
  {
    slug: 'dermatite-de-contato',
    nome: 'Dermatite de contato',
    sinonimos: ['Eczema de contato', 'Dermatite alérgica de contato', 'Dermatite irritativa'],
    sistema: 'pele',
    resumo: 'Eczema com bordas geométricas — retas, angulosas, no formato exato do relógio, do botão da calça ou da tira da sandália — que denuncia o objeto que encostou.',
    definicao: 'Eczema agudo (eritema, vesículas, exsudação) ou crônico (liquenificação, fissuras) limitado à área de contato com um agente irritante ou alérgeno, com margens artificiais que reproduzem a forma do objeto. Forma alérgica pode se estender além do contato.',
    comoProcurar: [
      { passo: 'Descreva a forma: linha reta, ângulo, círculo.', detalhe: 'A natureza não faz ângulo reto; um objeto faz.' },
      { passo: 'Localize e pergunte o que toca ali: níquel (umbigo, lóbulo, pulso), borracha, cosmético, planta.', detalhe: 'Dermatite periumbilical em jovem é o botão de metal.' },
      { passo: 'Mãos de profissional: irritativa (dorso, espaços interdigitais) por água e detergentes.', detalhe: 'Alérgica precisa de teste de contato (patch test).' },
    ],
    mecanismo: 'Irritativa: dano direto à barreira por substância cáustica ou por exposição repetida a água e sabão, sem sensibilização. Alérgica: hipersensibilidade tardia tipo IV — o hapteno liga-se a proteínas da pele, é apresentado a linfócitos T e, em nova exposição, gera eczema em 24 a 72 horas.',
    significado: 'A forma diz o diagnóstico e a história diz o agente. Irritativa é a dermatose ocupacional mais comum; alérgica exige identificar e afastar o alérgeno — sem isso, nenhum corticoide resolve.',
    armadilhas: ['Dermatite atópica das mãos e disidrose entram no diferencial da forma crônica.', 'Fitofotodermatose: eritema e bolhas lineares onde o limão respingou e o sol bateu — hiperpigmentação depois.', 'Dermatite de contato por corticoide tópico: o remédio virou o alérgeno.'],
    causas: [
      { titulo: 'Alérgica (tipo IV)', mecanismo: 'Sensibilização a hapteno.', itens: ['Níquel', 'Fragrâncias e conservantes', 'Borracha (tiossulfatos)', 'Parafenilenodiamina (tinturas, henna preta)', 'Plantas (Toxicodendron)'] },
      { titulo: 'Irritativa', mecanismo: 'Dano direto à barreira.', itens: ['Água e detergentes (trabalho úmido)', 'Solventes', 'Cimento', 'Fralda (urina e fezes)'] },
    ],
    referencias: ['Nassau S, Fonacier L. Allergic contact dermatitis. Med Clin North Am, 2020.'],
  },
  {
    slug: 'rosacea',
    nome: 'Rosácea e rinofima',
    sinonimos: ['Acne rosácea', 'Rinofima', 'Eritema centrofacial'],
    sistema: 'pele',
    resumo: 'Eritema persistente no centro da face com telangiectasias e surtos de pápulas e pústulas sem comedões; no homem de longa data, o nariz cresce bulboso e lobulado — rinofima.',
    definicao: 'Eritema centrofacial fixo (bochechas, nariz, queixo, fronte) com flushing, telangiectasias e, nos surtos, pápulas e pústulas inflamatórias sem comedões; poupa a região periocular. Fenótipo fimatoso: espessamento e nódulos do nariz com poros dilatados. Ocular: blefarite e conjuntivite em metade.',
    comoProcurar: [
      { passo: 'Procure comedões: se houver, é acne; se não, rosácea.', detalhe: 'A ausência de comedão é o critério mais útil.' },
      { passo: 'Pergunte por flushing com calor, álcool, comida picante.', detalhe: 'O gatilho vascular é a assinatura da doença.' },
      { passo: 'Olhe as pálpebras e a conjuntiva.', detalhe: 'Blefarite e olho seco fazem parte; ceratite é a complicação.' },
    ],
    mecanismo: 'Desregulação neurovascular (flushing repetido leva a telangiectasias fixas) e imunidade inata exagerada (catelicidina, Demodex) produzem inflamação crônica; no fenótipo fimatoso, hiperplasia sebácea e fibrose deformam o nariz.',
    significado: 'Diagnóstico clínico; crônica, com impacto social grande. Rinofima é tratável cirurgicamente e não indica alcoolismo — o mito faz mal ao paciente. Rosácea ocular não tratada pode levar a ceratite e perda visual.',
    armadilhas: ['Lúpus cutâneo agudo: rash malar poupa os sulcos nasolabiais e não tem pústula.', 'Dermatite seborreica: escama gordurosa nos sulcos.', 'Rosácea esteroide: piora após corticoide tópico prolongado na face.'],
    causas: [
      { titulo: 'Predisposição', mecanismo: 'Vascular e imune.', itens: ['Fototipo claro, história familiar', 'Demodex folliculorum'] },
      { titulo: 'Gatilhos', mecanismo: 'Vasodilatação.', itens: ['Sol, calor, frio', 'Álcool, alimentos picantes e quentes', 'Corticoide tópico', 'Estresse'] },
    ],
    referencias: ['Gallo RL et al. Standard classification and pathophysiology of rosacea: 2017 update by the National Rosacea Society Expert Committee. J Am Acad Dermatol, 2018.'],
  },
  {
    slug: 'acne-nodulo-cistica',
    nome: 'Acne nódulo-cística',
    sinonimos: ['Acne conglobata', 'Acne grave', 'Acne vulgar grau IV'],
    sistema: 'pele',
    resumo: 'Comedões, pápulas, pústulas e nódulos profundos e dolorosos que se comunicam por trajetos e deixam cicatrizes — a acne que precisa de isotretinoína, não de sabonete.',
    definicao: 'Acne com nódulos inflamatórios profundos (> 5 mm), cistos e abscessos, frequentemente interligados, em face, dorso e tórax, sobre um fundo de comedões abertos e fechados; cicatrizes atróficas ("ice-pick") e hipertróficas.',
    comoProcurar: [
      { passo: 'Confirme comedões: são eles que dizem que é acne.', detalhe: 'Sem comedão, pense em rosácea, foliculite ou hidradenite.' },
      { passo: 'Palpe os nódulos e veja o dorso.', detalhe: 'Acne do tronco é frequentemente subestimada e cicatriza pior.' },
      { passo: 'Em mulher, pergunte por hirsutismo e irregularidade menstrual; em atleta, por anabolizantes.', detalhe: 'Hiperandrogenismo e esteroides fazem acne explosiva.' },
    ],
    mecanismo: 'Hiperqueratinização folicular e sebo aumentado por andrógenos formam o comedão; Cutibacterium acnes prolifera e ativa a inflamação; a ruptura do folículo na derme profunda gera nódulos, abscessos e trajetos, que cicatrizam com fibrose.',
    significado: 'Forma grave que deixa cicatriz permanente e marca psicossocial — indicação direta de isotretinoína. Início abrupto e grave com febre e artralgia é acne fulminans; em adulto com lesões em dobras, é hidradenite.',
    armadilhas: ['Hidradenite supurativa: axilas, virilhas, nádegas, sem comedão típico (tem comedões duplos).', 'Foliculite por gram-negativo em quem usou antibiótico por meses.', 'Acne induzida por esteroide, lítio, isoniazida: monomórfica, sem comedões.'],
    causas: [
      { titulo: 'Acne vulgar grave', mecanismo: 'Andrógenos, sebo, queratinização, C. acnes.', itens: ['Predisposição genética', 'Puberdade', 'Síndrome dos ovários policísticos'] },
      { titulo: 'Induzida', mecanismo: 'Estímulo androgênico ou folicular exógeno.', itens: ['Anabolizantes', 'Corticoides', 'Lítio, isoniazida, EGFR-inibidores'] },
    ],
    referencias: ['Zaenglein AL et al. Guidelines of care for the management of acne vulgaris. J Am Acad Dermatol, 2016.'],
  },
  {
    slug: 'melasma',
    nome: 'Melasma',
    sinonimos: ['Cloasma', 'Máscara da gravidez'],
    sistema: 'pele',
    resumo: 'Manchas acastanhadas simétricas, de bordas irregulares e recortadas, nas maçãs do rosto, fronte e lábio superior — a hiperpigmentação que o sol e o estrogênio escrevem na face.',
    definicao: 'Máculas e manchas hipercrômicas castanho-claras a escuras, simétricas, de contorno geográfico, nas áreas fotoexpostas da face (padrão centrofacial, malar ou mandibular); sem inflamação nem descamação. Mais em mulheres de fototipo intermediário.',
    comoProcurar: [
      { passo: 'Note a simetria e o contorno irregular "em mapa".', detalhe: 'Lentigos são pontuais; melasma é mancha.' },
      { passo: 'Use a luz de Wood: pigmento epidérmico acentua, dérmico não.', detalhe: 'Orienta o prognóstico com clareadores.' },
      { passo: 'Pergunte por gravidez, anticoncepcional, fotoproteção.', detalhe: 'Sem filtro solar, qualquer tratamento fracassa.' },
    ],
    mecanismo: 'Radiação UV e luz visível, estrogênio e progesterona estimulam melanócitos geneticamente suscetíveis a produzir mais melanina e transferi-la para queratinócitos (epidérmico) ou depositá-la em melanófagos dérmicos (dérmico); vasos dérmicos aumentados participam.',
    significado: 'Benigno, crônico e recidivante; o peso é estético e psicológico. Reconhecer evita biópsias desnecessárias e orienta o pilar do tratamento: fotoproteção diária contra UV e luz visível.',
    armadilhas: ['Hiperpigmentação pós-inflamatória (após acne ou dermatite) tem história e distribuição das lesões prévias.', 'Ocronose exógena por hidroquinona prolongada: pigmento azul-acinzentado com pápulas — o tratamento virou doença.', 'Lúpus discoide em remissão deixa hipercromia com atrofia.'],
    causas: [
      { titulo: 'Hormonal e solar', mecanismo: 'Estímulo melanocítico.', itens: ['Gravidez', 'Anticoncepcionais e reposição hormonal', 'Exposição solar e luz visível', 'Predisposição genética e fototipo III-V'] },
    ],
    referencias: ['Ogbechie-Godec OA, Elbuluk N. Melasma: an up-to-date comprehensive review. Dermatol Ther, 2017.'],
  },
  {
    slug: 'pitiriase-rosea',
    nome: 'Pitiríase rósea',
    sinonimos: ['Pitiríase rósea de Gibert', 'Medalhão precursor', 'Padrão em árvore de Natal'],
    sistema: 'pele',
    resumo: 'Uma placa oval maior (o medalhão) que precede em uma ou duas semanas uma erupção de placas menores no tronco, orientadas ao longo das linhas de clivagem — a "árvore de Natal" nas costas.',
    definicao: 'Exantema autolimitado (6 a 8 semanas): placa inicial ("medalhão precursor") ovalada, rósea, de 2 a 5 cm, com colarete descamativo interno; depois, múltiplas placas semelhantes e menores no tronco e raiz dos membros, com o eixo maior seguindo as linhas de Langer. Prurido leve. Poupa face, palmas e plantas.',
    comoProcurar: [
      { passo: 'Pergunte pela primeira lesão, maior que as outras.', detalhe: 'O medalhão frequentemente é tomado por tinha do corpo.' },
      { passo: 'Peça para o paciente ficar de costas e olhe o eixo das placas.', detalhe: 'Oblíquas, convergindo para a coluna: árvore de Natal.' },
      { passo: 'Olhe palmas e plantas e peça sorologia para sífilis.', detalhe: 'Sífilis secundária é o grande imitador — e acomete palmas e plantas.' },
    ],
    mecanismo: 'Associada à reativação dos herpesvírus humanos 6 e 7; a erupção segue as linhas de tensão da pele, provavelmente por disseminação viral com resposta imune cutânea organizada pela orientação das fibras dérmicas.',
    significado: 'Benigna e autolimitada; o valor está em não confundir com tinha (medalhão) nem com sífilis secundária (erupção). Na gestante no primeiro trimestre, associação com desfechos adversos — acompanhar.',
    armadilhas: ['Sífilis secundária: sempre sorologia — palmas, plantas e sintomas sistêmicos falam por ela.', 'Tinha do corpo: KOH no medalhão.', 'Farmacodermia pitiríase-símile (captopril, ouro, metronidazol).', 'Pitiríase rósea invertida: nas dobras e membros, em fototipos altos.'],
    causas: [
      { titulo: 'Viral', mecanismo: 'Reativação de HHV-6/7.', itens: ['Pitiríase rósea clássica'] },
      { titulo: 'Erupção pitiríase-símile', mecanismo: 'Reação a fármaco.', itens: ['Captopril', 'Metronidazol', 'Isotretinoína', 'Vacinas'] },
    ],
    referencias: ['Drago F et al. Pityriasis rosea: a comprehensive classification. Dermatology, 2016.'],
  },
  {
    slug: 'liquen-plano-cutaneo',
    nome: 'Líquen plano cutâneo',
    sinonimos: ['Pápulas dos 6 P', 'Estrias de Wickham'],
    sistema: 'pele',
    resumo: 'Pápulas poligonais, planas, púrpuras, pruriginosas, brilhantes, com finas estrias brancas na superfície (Wickham) — nos punhos, tornozelos e região lombar.',
    definicao: 'Pápulas de 2 a 5 mm, poligonais, de topo plano, violáceas, brilhantes à luz tangencial, com retículo esbranquiçado (estrias de Wickham) na superfície, agrupadas em placas nas faces flexoras dos punhos, antebraços, tornozelos e região sacral; muito pruriginosas; fenômeno de Koebner. Deixa hipercromia residual.',
    comoProcurar: [
      { passo: 'Ilumine de lado: o brilho e as estrias de Wickham aparecem.', detalhe: 'Uma gota de óleo ou o dermatoscópio realça o retículo branco.' },
      { passo: 'Procure Koebner: pápulas em linha sobre arranhadura.', detalhe: 'Também na psoríase — a morfologia da pápula separa.' },
      { passo: 'Olhe a boca: retículo branco na mucosa jugal em até 70%.', detalhe: 'E as unhas: pterígio dorsal, estrias longitudinais.' },
    ],
    mecanismo: 'Linfócitos T CD8+ atacam queratinócitos basais (dermatite de interface liquenoide), produzindo degeneração vacuolar, corpos de Civatte e hipergranulose focal — a hipergranulose é o que se vê como estria de Wickham.',
    significado: 'Autolimitado em 1 a 2 anos na forma cutânea; a forma oral erosiva é crônica e tem risco pequeno de carcinoma espinocelular. Associação com hepatite C (sobretudo na forma oral) e com fármacos — sempre revisar a lista.',
    armadilhas: ['Erupção liquenoide por fármaco (betabloqueador, tiazídico, antimalárico, anti-TNF): mais eczematosa e fotodistribuída.', 'Sífilis secundária papulosa e psoríase gutata no diferencial das pápulas.', 'Líquen plano pilar no couro cabeludo: alopecia cicatricial — não confundir com areata.'],
    causas: [
      { titulo: 'Idiopático', mecanismo: 'Autoimunidade T contra queratinócitos basais.', itens: ['Líquen plano clássico', 'Variantes: hipertrófico, bolhoso, pilar, oral'] },
      { titulo: 'Associações', mecanismo: 'Gatilho antigênico.', itens: ['Hepatite C', 'Fármacos (tiazídicos, betabloqueadores, antimaláricos)', 'Amálgama dentário (forma oral)'] },
    ],
    referencias: ['Le Cleach L, Chosidow O. Lichen planus. N Engl J Med, 2012.'],
  },
  {
    slug: 'dermografismo',
    nome: 'Dermografismo',
    sinonimos: ['Urticária factícia', 'Escrita na pele'],
    sistema: 'pele',
    resumo: 'Riscar a pele com um objeto rombo faz aparecer, em minutos, uma linha elevada e pálida com halo vermelho exatamente no traçado — a urtica que reproduz o que se escreveu.',
    definicao: 'Urtica linear (edema esbranquiçado com eritema ao redor) que surge 1 a 5 minutos após atrito firme sobre a pele e reproduz a forma do estímulo, desaparecendo em 15 a 30 minutos. Sintomático quando acompanhado de prurido; fisiológico (leve, sem prurido) em até 5% da população.',
    comoProcurar: [
      { passo: 'Risque o dorso com a ponta de uma espátula, pressão moderada.', detalhe: 'Escreva uma letra: a urtica vai reproduzi-la.' },
      { passo: 'Cronometre: a tríplice resposta de Lewis (linha vermelha, halo, pápula) em até 5 minutos.', detalhe: 'Leia também em 15 minutos — pode desaparecer rápido.' },
      { passo: 'Pergunte por prurido ao coçar, vestir, secar-se com toalha.', detalhe: 'Dermografismo sintomático é urticária crônica induzível.' },
    ],
    mecanismo: 'Atrito degranula mastócitos dérmicos por mecanismo IgE-dependente ou direto; histamina dilata arteríolas (eritema), aumenta permeabilidade (edema = pápula) e dispara o reflexo axonal (halo). Exagero da tríplice resposta de Lewis normal.',
    significado: 'É a urticária física mais comum. Isolado e assintomático não requer investigação; sintomático e persistente entra no grupo das urticárias crônicas induzíveis, com resposta a anti-histamínicos. Mastocitose e urticária pigmentosa têm dermografismo exuberante.',
    armadilhas: ['Dermografismo branco (linha branca sem urtica) na dermatite atópica: vasoconstrição, não urticária.', 'Sinal de Darier na mastocitose: a urtica aparece sobre a mácula pigmentada, não em pele sã.'],
    causas: [
      { titulo: 'Urticária induzível', mecanismo: 'Degranulação mastocitária por pressão.', itens: ['Dermografismo sintomático idiopático', 'Após infecções e escabiose', 'Fármacos (penicilina)'] },
      { titulo: 'Exagerado', mecanismo: 'Excesso de mastócitos.', itens: ['Mastocitose cutânea', 'Urticária pigmentosa'] },
    ],
    referencias: ['Zuberbier T et al. EAACI/GA²LEN/EuroGuiDerm/APAAACI guideline for urticaria. Allergy, 2022.'],
  },
  {
    slug: 'queloide',
    nome: 'Queloide e cicatriz hipertrófica',
    sinonimos: ['Cicatriz queloidiana', 'Cicatriz hipertrófica'],
    sistema: 'pele',
    resumo: 'Cicatriz que virou tumor: firme, brilhante, rosada ou escura, que ultrapassa as bordas da ferida original e cresce em garra — no lóbulo da orelha, no ombro, no tórax.',
    definicao: 'Queloide: proliferação fibrosa que se estende além dos limites da lesão original, com projeções em garra, não regride e pode surgir meses após o trauma; pruriginoso e doloroso. Cicatriz hipertrófica: elevada mas confinada às margens da ferida, surge em semanas, tende a regredir em 1 a 2 anos.',
    comoProcurar: [
      { passo: 'Pergunte onde era a ferida e compare com a extensão da cicatriz.', detalhe: 'Ultrapassou: queloide. Ficou dentro: hipertrófica.' },
      { passo: 'Localize: lóbulo, região deltoide, pré-esternal, mandíbula, dorso.', detalhe: 'Zonas de tensão e de maior densidade de mastócitos.' },
      { passo: 'Pergunte por evolução: hipertrófica melhora sozinha; queloide não.', detalhe: 'A resposta a tratamento também difere.' },
    ],
    mecanismo: 'Fibroblastos hiper-responsivos a TGF-β produzem colágeno tipo I e III em excesso e por tempo prolongado; no queloide há feixes espessos hialinizados, desorganizados, e a proliferação invade a derme normal ao redor. Predisposição genética e pele mais pigmentada.',
    significado: 'Diagnóstico clínico com implicação prática: excisão simples do queloide recidiva em 50 a 100% e piora — precisa de corticoide intralesional, silicone, pressão ou radioterapia associados. Informar antes de qualquer cirurgia eletiva em quem tem tendência.',
    armadilhas: ['Dermatofibrossarcoma protuberans começa como placa endurecida "cicatricial" sem trauma prévio — biópsia se não houve ferida.', 'Lesão queloidiana espontânea no tórax: acne queloidiana, cicatriz de varicela.'],
    causas: [
      { titulo: 'Cicatrização exagerada', mecanismo: 'Fibroblastos hiper-responsivos.', itens: ['Predisposição genética, fototipos altos', 'Piercing, cirurgia, queimadura, acne', 'Tensão na ferida', 'Adolescência e gravidez'] },
    ],
    referencias: ['Ogawa R. Keloid and hypertrophic scars are the result of chronic inflammation in the reticular dermis. Int J Mol Sci, 2017.'],
  },
  {
    slug: 'pioderma-gangrenoso',
    nome: 'Pioderma gangrenoso',
    sinonimos: ['Pyoderma gangrenosum', 'Úlcera de borda violácea solapada'],
    sistema: 'pele',
    resumo: 'Úlcera que cresce rápido a partir de uma pústula, com borda violácea, elevada e solapada (descolada), muito dolorosa — e que piora se for desbridada, porque a doença é inflamação, não infecção.',
    definicao: 'Úlcera necrótica de crescimento rápido, dolorosa, com borda irregular, violácea, edematosa e escavada por baixo (solapada), fundo purulento e exsudativo, geralmente na perna; inicia como pápula-pústula ou nódulo, frequentemente após trauma mínimo (patergia). Cicatriza com cicatriz cribriforme.',
    comoProcurar: [
      { passo: 'Passe uma sonda sob a borda: ela está descolada da base.', detalhe: 'O solapamento violáceo é a assinatura.' },
      { passo: 'Pergunte por trauma ou cirurgia prévios no local (patergia) e por doença inflamatória intestinal, artrite, doença hematológica.', detalhe: 'Metade tem doença sistêmica associada.' },
      { passo: 'Biopsie a borda para excluir infecção, vasculite e neoplasia; a cultura será negativa.', detalhe: 'É diagnóstico de exclusão — mas não deixe de excluir.' },
    ],
    mecanismo: 'Dermatose neutrofílica: disfunção da imunidade inata (IL-1, IL-8, IL-17) recruta neutrófilos para a derme sem infecção; a inflamação destrói o tecido e o trauma (patergia) a desencadeia. Não há vasculite primária nem microrganismo.',
    significado: 'Diagnóstico que muda a conduta ao contrário: desbridamento e enxerto pioram, imunossupressão (corticoide, ciclosporina, anti-TNF) cura. Associada a retocolite, Crohn, artrite reumatoide, gamopatia monoclonal e leucemia mieloide — investigar.',
    armadilhas: ['Úlcera venosa, arterial e infecciosa (ectima, micobactéria, fungo profundo) precisam ser excluídas — a biópsia com culturas é obrigatória.', 'Vasculite e calcifilaxia no diferencial da úlcera dolorosa de perna.', 'Pioderma peristomal em quem tem doença inflamatória intestinal com ostomia.'],
    causas: [
      { titulo: 'Doenças associadas', mecanismo: 'Dermatose neutrofílica reativa.', itens: ['Retocolite ulcerativa e doença de Crohn', 'Artrite reumatoide e espondiloartrites', 'Gamopatia monoclonal IgA, leucemia mieloide', 'Síndromes autoinflamatórias (PAPA)'] },
      { titulo: 'Idiopático', mecanismo: 'Sem doença de base (50%).', itens: ['Pioderma gangrenoso clássico', 'Pós-cirúrgico (patergia)'] },
    ],
    referencias: ['Maverakis E et al. Diagnostic criteria of ulcerative pyoderma gangrenosum: a Delphi consensus. JAMA Dermatol, 2018.'],
  },
  {
    slug: 'pediculose',
    nome: 'Pediculose do couro cabeludo',
    sinonimos: ['Piolho', 'Lêndeas', 'Pediculosis capitis'],
    sistema: 'pele',
    resumo: 'Lêndeas coladas ao fio a menos de um centímetro do couro cabeludo, sobretudo atrás das orelhas e na nuca, com prurido e escoriações — e, se houver piolho vivo, infestação ativa.',
    definicao: 'Infestação por Pediculus humanus capitis: presença de piolhos adultos ou ninfas vivas no couro cabeludo, ou lêndeas (ovos) firmemente aderidas à haste a menos de 1 cm da base; prurido, escoriações, impetiginização secundária e adenopatia occipital.',
    comoProcurar: [
      { passo: 'Passe o pente fino no cabelo úmido, da raiz à ponta, mecha por mecha, sobre papel branco.', detalhe: 'Achar o piolho vivo é o que define infestação ativa.' },
      { passo: 'Procure lêndeas atrás das orelhas e na nuca: firmemente presas, não deslizam.', detalhe: 'Caspa e resíduos de cosmético saem com o dedo; a lêndea não.' },
      { passo: 'Meça a distância da lêndea ao couro cabeludo.', detalhe: 'Mais de 1 cm: ovo antigo, provavelmente vazio — não indica infestação atual.' },
    ],
    mecanismo: 'O piolho alimenta-se de sangue do couro cabeludo várias vezes ao dia; a saliva produz prurido por sensibilização. A fêmea cola os ovos à haste com uma substância cimentante próxima à raiz, onde a temperatura é ideal; com o crescimento do fio a lêndea se afasta da pele.',
    significado: 'Problema de saúde pública em escolares, sem gravidade mas com estigma; a impetiginização e a adenopatia occipital são as consequências. O diagnóstico exige piolho vivo ou lêndea viável próxima à raiz — lêndeas distantes não justificam tratamento.',
    armadilhas: ['Piedra branca e moldes de queratina (hair casts) deslizam pelo fio — a lêndea não.', 'Escoriações e crostas na nuca em criança: procure o piolho antes de chamar de dermatite.'],
    causas: [
      { titulo: 'Infestação', mecanismo: 'Contato direto cabeça a cabeça.', itens: ['Pediculus humanus capitis', 'Convívio escolar, compartilhamento de pentes e bonés'] },
    ],
    referencias: ['Devore CD, Schutze GE. Head lice. Pediatrics, 2015.'],
  },
  {
    slug: 'paracoccidioidomicose',
    nome: 'Paracoccidioidomicose — estomatite moriforme',
    sinonimos: ['Blastomicose sul-americana', 'Estomatite moriforme de Aguiar-Pupo', 'PCM'],
    sistema: 'pele',
    resumo: 'Úlcera de mucosa oral com fundo granuloso e fino pontilhado hemorrágico — a "amora" — em lavrador de meia-idade com tosse crônica e adenomegalia: a micose sistêmica endêmica do Brasil.',
    definicao: 'Lesão ulcerada de mucosa oral (gengiva, lábio, palato, orofaringe) de fundo granuloso com múltiplos pontos hemorrágicos finos (aspecto de amora — estomatite moriforme), indolor ou pouco dolorosa, de evolução lenta; associada a lesões cutâneas ulcerovegetantes perioral e nasal, adenomegalia cervical e comprometimento pulmonar.',
    comoProcurar: [
      { passo: 'Abra bem a boca e ilumine: procure o pontilhado hemorrágico fino sobre fundo granuloso.', detalhe: 'É o aspecto de amora; a úlcera do carcinoma é lisa e endurecida.' },
      { passo: 'Pergunte pela profissão e origem: trabalho rural em área endêmica, tabagismo, etilismo.', detalhe: 'Homem de 30 a 60 anos que lidou com a terra.' },
      { passo: 'Peça exame direto do raspado (KOH) e radiografia de tórax.', detalhe: 'Levedura com múltiplos brotamentos em "roda de leme" é diagnóstica.' },
    ],
    mecanismo: 'Inalação de conídios de Paracoccidioides brasiliensis/lutzii no solo; infecção pulmonar primária com disseminação linfo-hematogênica anos depois. Na mucosa, granulomas com microabscessos e hiperplasia pseudoepiteliomatosa; os pontos hemorrágicos são vasos das papilas hiperplásicas.',
    significado: 'Micose sistêmica mais prevalente da América Latina; forma crônica do adulto acomete pulmões (fibrose), mucosas e adrenais (Addison). A lesão oral costuma ser o que leva o paciente ao médico — muitas vezes ao dentista. Tratável com itraconazol por meses.',
    armadilhas: ['Carcinoma espinocelular de boca: mesmo perfil de paciente (fumante, etilista), úlcera endurecida — biopsie na dúvida.', 'Leishmaniose mucosa: destrói o septo nasal e o palato, sem o pontilhado moriforme.', 'Tuberculose oral e histoplasmose no diferencial.'],
    causas: [
      { titulo: 'Fúngica endêmica', mecanismo: 'Disseminação a partir de foco pulmonar.', itens: ['Paracoccidioides brasiliensis', 'Paracoccidioides lutzii (Centro-Oeste e Norte)'] },
    ],
    referencias: ['Shikanai-Yasuda MA et al. Brazilian guidelines for the clinical management of paracoccidioidomycosis. Rev Soc Bras Med Trop, 2017.'],
  },
  {
    slug: 'esporotricose',
    nome: 'Esporotricose linfangítica',
    sinonimos: ['Doença do jardineiro', 'Esporotricose cutâneo-linfática', 'Micose do gato'],
    sistema: 'pele',
    resumo: 'Nódulo ulcerado no ponto de inoculação e, subindo pelo membro, um rosário de nódulos ao longo do trajeto linfático — em quem foi arranhado por gato ou mexeu com plantas.',
    definicao: 'Forma linfocutânea: lesão inicial papulonodular que ulcera no sítio de inoculação (mão, antebraço, face), seguida em semanas por nódulos subcutâneos firmes, eritematosos, alinhados no trajeto linfático proximal, que podem ulcerar; sem sintomas sistêmicos. Forma cutânea fixa: placa verrucosa ou ulcerada única.',
    comoProcurar: [
      { passo: 'Siga o trajeto linfático a partir da lesão inicial: palpe os nódulos em cordão.', detalhe: 'O "rosário" ascendente é a assinatura.' },
      { passo: 'Pergunte por gatos doentes em casa e por trabalho com terra, espinhos e madeira.', detalhe: 'No Brasil, a transmissão zoonótica por gato (S. brasiliensis) é hoje a principal.' },
      { passo: 'Peça cultura do exsudato ou biópsia; o exame direto é quase sempre negativo.', detalhe: 'Cultura em Sabouraud cresce em 1 a 2 semanas.' },
    ],
    mecanismo: 'Inoculação traumática do fungo dimórfico Sporothrix (spp. schenckii, brasiliensis) na derme; conversão para levedura, granuloma supurativo local e disseminação pelos linfáticos, formando nódulos sequenciais que abscedam. A infecção pelo gato leva inóculo maior e quadros mais graves, incluindo forma ocular.',
    significado: 'A micose subcutânea mais frequente no Brasil, em expansão epidêmica (Rio de Janeiro, Sul e Sudeste) pela transmissão felina. Diagnóstico clínico-epidemiológico com confirmação por cultura; itraconazol resolve na maioria.',
    armadilhas: ['Leishmaniose cutânea, micobacteriose atípica (M. marinum de aquário) e nocardiose fazem o mesmo padrão esporotricoide — a cultura decide.', 'Forma extracutânea e disseminada no imunossuprimido e no etilista: osteoarticular, pulmonar, meníngea.'],
    causas: [
      { titulo: 'Inoculação fúngica', mecanismo: 'Trauma com material contaminado ou arranhadura/mordida de gato.', itens: ['Sporothrix brasiliensis (zoonótica, gatos)', 'Sporothrix schenckii (vegetal, solo)'] },
    ],
    referencias: ['Gremião IDF et al. Zoonotic epidemic of sporotrichosis: cat to human transmission. PLoS Pathog, 2017.'],
  },
  {
    slug: 'cromomicose',
    nome: 'Cromomicose',
    sinonimos: ['Cromoblastomicose', 'Dermatite verrucosa'],
    sistema: 'pele',
    resumo: 'Placa verrucosa, vegetante, com pontos pretos na superfície, crescendo por anos na perna ou no pé de um trabalhador rural — os "corpos muriformes" do fungo dematiáceo estão nos pontos pretos.',
    definicao: 'Lesão cutânea crônica, de crescimento lento (anos), no membro inferior ou superior: placas verrucosas, nodulares, tumorais ("couve-flor") ou cicatriciais, com pequenos pontos escuros (eliminação transepidérmica de fungos e detritos) na superfície; indolor, com prurido; áreas de cicatriz central e fibrose; linfedema e infecção secundária tardios.',
    comoProcurar: [
      { passo: 'Procure os pontos pretos na superfície verrucosa e raspe ali para o KOH.', detalhe: 'Células muriformes (esclerotes de Medlar) castanhas, septadas, são patognomônicas.' },
      { passo: 'Pergunte pelo tempo de evolução e pela atividade: trabalhador rural descalço, trauma com madeira.', detalhe: 'Evolução de anos é a regra.' },
      { passo: 'Meça e fotografe: o tratamento é longo e a resposta se avalia por área.', detalhe: 'Lesões extensas podem exigir associação de antifúngico com calor ou crioterapia.' },
    ],
    mecanismo: 'Inoculação traumática de fungos dematiáceos (pigmentados) do solo e da madeira; na derme, formam células muriformes resistentes que induzem granuloma supurativo crônico e hiperplasia pseudoepiteliomatosa — a verrucosidade. A eliminação transepidérmica de elementos fúngicos produz os pontos pretos.',
    significado: 'Micose de implantação crônica, negligenciada, endêmica em áreas tropicais e no Brasil (Pará, Maranhão, Minas). Incapacita pela fibrose e linfedema; carcinoma espinocelular pode surgir sobre lesões antigas. Tratamento prolongado com itraconazol e/ou terbinafina, meses a anos.',
    armadilhas: ['Carcinoma espinocelular verrucoso, tuberculose verrucosa, leishmaniose e esporotricose fixa — a biópsia com PAS diferencia.', 'Confundir com feo-hifomicose: mesmos fungos, sem células muriformes, geralmente cisto subcutâneo.'],
    causas: [
      { titulo: 'Fungos dematiáceos', mecanismo: 'Implantação traumática.', itens: ['Fonsecaea pedrosoi (mais comum no Brasil)', 'Cladophialophora carrionii', 'Phialophora verrucosa'] },
    ],
    referencias: ['Queiroz-Telles F et al. Chromoblastomycosis. Clin Microbiol Rev, 2017.'],
  },
  {
    slug: 'micetoma',
    nome: 'Micetoma',
    sinonimos: ['Pé de Madura', 'Maduromicose', 'Eumicetoma e actinomicetoma'],
    sistema: 'pele',
    resumo: 'Pé aumentado de volume, endurecido, com múltiplos nódulos e fístulas que drenam grãos — a tríade tumefação, fístulas e grãos, crescendo por anos até o osso.',
    definicao: 'Infecção crônica subcutânea com tríade característica: tumefação indolor e progressiva do segmento acometido (pé em 70%), múltiplos trajetos fistulosos e eliminação de grãos (agregados do agente) pretos, brancos ou amarelos; extensão a fáscia, músculo e osso com deformidade.',
    comoProcurar: [
      { passo: 'Procure fístulas e esprema com cuidado: veja a cor dos grãos.', detalhe: 'Grãos pretos: eumicetoma (fungo); brancos ou amarelos: actinomicetoma (bactéria) ou fungo hialino.' },
      { passo: 'Pergunte por tempo (anos), profissão rural e andar descalço.', detalhe: 'O trauma inicial com espinho é frequentemente esquecido.' },
      { passo: 'Radiografe: cavidades ósseas e periostite dizem que já chegou ao osso.', detalhe: 'Muda o prognóstico e a necessidade de cirurgia.' },
    ],
    mecanismo: 'Implantação traumática de fungos (eumicetoma: Madurella mycetomatis) ou actinomicetos filamentosos (actinomicetoma: Nocardia, Actinomadura) que se organizam em grãos cercados de neutrófilos; a inflamação crônica forma múltiplos abscessos com fístulas e fibrose progressiva, invadindo por contiguidade fáscia e osso.',
    significado: 'Doença tropical negligenciada; no Brasil, mais actinomicetoma (Nocardia brasiliensis), que responde a antibiótico. Eumicetoma exige antifúngico prolongado e frequentemente cirurgia; casos tardios terminam em amputação. Diagnosticar cedo é a diferença.',
    armadilhas: ['Osteomielite bacteriana crônica, tuberculose cutânea e cromomicose no diferencial — a presença de grãos é o que define micetoma.', 'Botriomicose: bactérias comuns (S. aureus) formando grãos — mesma aparência, tratamento diferente.'],
    causas: [
      { titulo: 'Actinomicetoma (bacteriano)', mecanismo: 'Actinomicetos aeróbios do solo.', itens: ['Nocardia brasiliensis (Brasil, México)', 'Actinomadura madurae', 'Streptomyces somaliensis'] },
      { titulo: 'Eumicetoma (fúngico)', mecanismo: 'Fungos dematiáceos ou hialinos.', itens: ['Madurella mycetomatis (grão preto)', 'Scedosporium apiospermum (grão branco)'] },
    ],
    referencias: ['Zijlstra EE et al. Mycetoma: a unique neglected tropical disease. Lancet Infect Dis, 2016.'],
  },
  {
    slug: 'elefantiase-filarial',
    nome: 'Elefantíase filarial',
    sinonimos: ['Filariose linfática', 'Linfedema filarial', 'Bancroftose'],
    sistema: 'pele',
    resumo: 'Perna gigantesca, dura, com pele espessada, verrucosa e com dobras profundas, em área endêmica de Wuchereria bancrofti — o linfedema de décadas transformado em pele de elefante.',
    definicao: 'Linfedema crônico irreversível (estágio avançado), tipicamente de membro inferior, escroto ou mama, com pele espessada, hiperceratósica, nodular e verrucosa, dobras profundas e crises agudas recorrentes de adenolinfangite; hidrocele associada no homem.',
    comoProcurar: [
      { passo: 'Compare os membros, palpe a consistência e tente pinçar a pele do dorso do segundo dedo do pé (sinal de Stemmer).', detalhe: 'Não conseguir pregueá-la é linfedema.' },
      { passo: 'Inspecione a pele: hiperceratose, papilomatose, fissuras e intertrigo nas dobras.', detalhe: 'As fissuras são portas de entrada das crises de linfangite.' },
      { passo: 'Pergunte pela origem (Recife e Região Metropolitana, Belém, Maceió, áreas endêmicas da África e Ásia) e por hidrocele.', detalhe: 'Pesquisa de antígeno circulante ou microfilária noturna.' },
    ],
    mecanismo: 'Vermes adultos de Wuchereria bancrofti vivem nos linfáticos e induzem dilatação e disfunção valvar; a lesão dos vasos, agravada pela morte do verme e por infecções bacterianas recorrentes da pele, leva a linfedema progressivo com fibrose dérmica, hiperceratose e proliferação epidérmica — a elefantíase. Wolbachia endossimbionte participa da inflamação.',
    significado: 'Segunda maior causa mundial de incapacidade crônica; o dano linfático é permanente, mas a higiene da pele, a elevação e o tratamento precoce das crises bacterianas reduzem progressão. No Brasil, o foco residual está em Pernambuco.',
    armadilhas: ['Linfedema não filarial (podoconiose por solo vulcânico, congênito, pós-erisipelas de repetição, pós-cirúrgico) tem a mesma pele — a epidemiologia e a sorologia diferenciam.', 'Insuficiência venosa crônica avançada: lipodermatoesclerose e úlcera, sem papilomatose exuberante.'],
    causas: [
      { titulo: 'Filariose linfática', mecanismo: 'Obstrução e disfunção linfática por vermes adultos.', itens: ['Wuchereria bancrofti (Américas, África, Ásia)', 'Brugia malayi e timori (Ásia)'] },
    ],
    referencias: ['Taylor MJ, Hoerauf A, Bockarie M. Lymphatic filariasis and onchocerciasis. Lancet, 2010.'],
  },
  {
    slug: 'difteria',
    nome: 'Difteria — pseudomembrana',
    sinonimos: ['Crupe diftérico', 'Pseudomembrana faríngea', 'Pescoço de touro'],
    sistema: 'cabeca-pescoco',
    resumo: 'Membrana branco-acinzentada, aderente, que cobre amígdalas, palato e úvula e sangra quando se tenta removê-la, em criança não vacinada com pescoço edemaciado — a toxina começa aqui e vai ao coração.',
    definicao: 'Placa pseudomembranosa acinzentada, espessa, firmemente aderida, que ultrapassa as amígdalas para pilares, palato mole e úvula, sangrando à tentativa de descolamento; halitose, febre baixa, adenomegalia cervical com edema periganglionar volumoso ("pescoço de touro"); pode estender-se à laringe com estridor e obstrução.',
    comoProcurar: [
      { passo: 'Toque a membrana com a espátula: aderida e sangra ao descolar.', detalhe: 'O exsudato da amigdalite estreptocócica e da mononucleose sai fácil e fica na amígdala.' },
      { passo: 'Veja se ultrapassa a amígdala para úvula e palato.', detalhe: 'Extensão além da amígdala é o que mais sugere difteria.' },
      { passo: 'Pergunte pela vacinação e olhe o pescoço.', detalhe: 'Edema cervical com aspecto de touro é sinal de gravidade; não espere cultura para tratar.' },
    ],
    mecanismo: 'Corynebacterium diphtheriae toxigênico coloniza a mucosa e produz exotoxina que inibe a síntese proteica (ADP-ribosilação do EF-2), necrosando o epitélio; fibrina, células mortas e bactérias formam a pseudomembrana aderente. A toxina absorvida causa miocardite, neurite e necrose tubular.',
    significado: 'Doença reemergente onde a cobertura vacinal cai — surtos recentes na Venezuela, Haiti e casos importados no Brasil. Emergência: soro antidiftérico o mais cedo possível, isolamento, antibiótico, monitorização cardíaca; a obstrução laríngea pode exigir via aérea cirúrgica.',
    armadilhas: ['Mononucleose infecciosa e angina de Vincent produzem membranas — mas descoláveis e sem o pescoço de touro.', 'Candidíase oral extensa em imunossuprimido: placas removíveis.', 'Difteria cutânea: úlcera com membrana em pessoa em situação de rua — reservatório.'],
    causas: [
      { titulo: 'Infecção toxigênica', mecanismo: 'Exotoxina diftérica.', itens: ['Corynebacterium diphtheriae', 'Corynebacterium ulcerans (zoonótico)'] },
    ],
    referencias: ['Sharma NC et al. Diphtheria. Nat Rev Dis Primers, 2019.'],
  },
]
