import type { Sinal } from './esquemas'

/**
 * Quinta leva, parte 3 — cabeça, pescoço e tórax (12) e abdome, genital e
 * proctologia (12): o que se vê no paciente despido, da tireoide ao períneo.
 */
export const SINAIS_LEVA_5_TRONCO: Sinal[] = [
  {
    slug: 'linfonodo-de-virchow',
    nome: 'Linfonodo de Virchow',
    sinonimos: ['Gânglio de Virchow-Troisier', 'Linfonodo supraclavicular esquerdo', 'Sinal de Troisier'],
    sistema: 'cabeca-pescoco',
    resumo: 'Um linfonodo duro, fixo e indolor na fossa supraclavicular esquerda, atrás da clavícula, em quem emagreceu — a metástase que subiu pelo ducto torácico de um câncer de estômago, pâncreas, ovário ou testículo.',
    definicao: 'Linfonodo palpável na fossa supraclavicular esquerda (junção do ducto torácico com a veia subclávia), tipicamente > 1 cm, duro, irregular, fixo ou pouco móvel, indolor, sem sinais inflamatórios, em adulto com sintomas constitucionais; à direita, associa-se a câncer de pulmão, esôfago e mediastino; linfonodo supraclavicular palpável de qualquer lado tem probabilidade de malignidade de 50 a 90%.',
    comoProcurar: [
      { passo: 'Paciente sentado, ombros relaxados; palpe a fossa supraclavicular com os dedos em gancho, atrás da clavícula, enquanto ele inspira fundo ou faz Valsalva.', detalhe: 'A manobra de Valsalva empurra o gânglio para cima.' },
      { passo: 'Duro, fixo, indolor: não espere — biópsia (PAAF ou excisional) e imagem do tórax e abdome.', detalhe: 'É frequentemente o primeiro sinal de um tumor silencioso.' },
      { passo: 'Compare com o lado direito e examine todas as cadeias.', detalhe: 'Linfadenopatia generalizada muda o diferencial (linfoma, HIV).' },
    ],
    mecanismo: 'O ducto torácico drena a linfa de todo o abdome, pelve e hemitórax esquerdo e desemboca na junção jugulo-subclávia esquerda; células tumorais que chegam ao ducto se implantam nos linfonodos sentinelas da fossa supraclavicular — o "sinal de Troisier" — antes de entrar na circulação venosa.',
    significado: 'Linfonodo supraclavicular é o mais preditivo de malignidade entre todas as cadeias; à esquerda, câncer abdominal (estômago, pâncreas, ovário, próstata, testículo, rim); à direita, torácico. Encontrá-lo muda o estadiamento (metástase a distância) e frequentemente o prognóstico.',
    armadilhas: ['Linfonodo supraclavicular reativo em jovem com infecção de couro cabeludo ou de pescoço — mole, doloroso, transitório.', 'Costela cervical, bulbo da carótida e tendão do escaleno simulando massa.', 'Tuberculose ganglionar e linfoma: também duros; a biópsia decide.'],
    causas: [
      { titulo: 'Metástase (esquerda)', mecanismo: 'Via ducto torácico.', itens: ['Câncer gástrico', 'Pâncreas, vias biliares', 'Ovário, próstata, testículo, rim', 'Colorretal'] },
      { titulo: 'Metástase (direita) e outras', mecanismo: 'Drenagem torácica ou doença linfática.', itens: ['Câncer de pulmão, esôfago, mama', 'Linfoma', 'Tuberculose ganglionar'] },
    ],
    referencias: ['Mizutani M et al. Anatomy and histology of Virchow\'s node. Anat Sci Int, 2006.'],
  },
  {
    slug: 'plagiocefalia-posicional',
    nome: 'Plagiocefalia posicional',
    sinonimos: ['Cabeça achatada', 'Plagiocefalia deformacional', 'Braquicefalia posicional'],
    sistema: 'cabeca-pescoco',
    resumo: 'Achatamento do occipício de um lado com a orelha do mesmo lado empurrada para a frente e a fronte abaulada — a cabeça em paralelogramo do lactente que dorme sempre virado para o mesmo lado, e que se corrige com posição, não com capacete de urgência.',
    definicao: 'Assimetria craniana de aparecimento pós-natal (2 a 4 meses): achatamento occipital unilateral, deslocamento anterior da orelha ipsilateral, abaulamento frontal ipsilateral e occipital contralateral — o crânio em paralelogramo visto de cima; suturas abertas e normais; frequentemente com torcicolo congênito ou preferência posicional; braquicefalia (achatamento occipital bilateral, cabeça larga e curta) na variante simétrica.',
    comoProcurar: [
      { passo: 'Olhe o crânio de cima (vista de vértex) com o bebê no colo: paralelogramo.', detalhe: 'De frente, a assimetria da fronte e das orelhas.' },
      { passo: 'Palpe as suturas: abertas e sem cristas.', detalhe: 'Crista óssea sobre a sutura lambdoide e orelha deslocada para trás: craniossinostose — encaminhe.' },
      { passo: 'Teste a rotação cervical passiva dos dois lados e palpe o esternocleidomastóideo.', detalhe: 'Torcicolo associado precisa de fisioterapia junto.' },
    ],
    mecanismo: 'Forças externas sobre o crânio maleável do lactente — pressão do colchão sempre no mesmo ponto por preferência posicional, torcicolo ou pouco tempo de bruços acordado — deformam o osso em crescimento sem fechar suturas; a incidência subiu com a campanha "dormir de barriga para cima" (que salva vidas e deve continuar).',
    significado: 'Benigna e cosmética; melhora com reposicionamento, tempo de bruços supervisionado e fisioterapia para o torcicolo; órtese só nos casos graves após os 5 meses. O que importa é distingui-la da craniossinostose lambdoide (rara), que exige cirurgia — e a forma de trapézio versus paralelogramo faz isso.',
    armadilhas: ['Craniossinostose lambdoide: crânio em trapézio, orelha para trás e para baixo, crista na sutura.', 'Plagiocefalia com atraso de desenvolvimento ou hipotonia: investigar a causa da preferência posicional.', 'Macrocefalia com plagiocefalia: medir e acompanhar o perímetro.'],
    causas: [
      { titulo: 'Deformação externa', mecanismo: 'Pressão sobre crânio maleável.', itens: ['Posição supina prolongada', 'Torcicolo muscular congênito', 'Prematuridade, gemelaridade', 'Pouco tempo de bruços acordado'] },
    ],
    referencias: ['Flannery AM et al. Congress of Neurological Surgeons systematic review and evidence-based guidelines for the management of patients with positional plagiocephaly. Neurosurgery, 2016.'],
  },
  {
    slug: 'facies-hipocratica',
    nome: 'Fácies hipocrática',
    sinonimos: ['Fácies peritoneal', 'Fácies terminal', 'Fácies de Hipócrates'],
    sistema: 'cabeca-pescoco',
    resumo: 'Olhos fundos e sem brilho, têmporas escavadas, nariz afilado, orelhas frias e retraídas, pele da testa seca, tensa e terrosa, lábios cianóticos entreabertos — a face da desidratação grave, da peritonite e da morte próxima, descrita há 2.400 anos.',
    definicao: 'Conjunto de alterações faciais do paciente gravemente enfermo: olhos encovados com olhar apagado, têmporas e bochechas escavadas, nariz proeminente e afilado com asas retraídas, orelhas frias e contraídas com lóbulos virados para fora, pele fria, seca, pálida ou terrosa, lábios cianóticos e entreabertos, sudorese fria; expressão de sofrimento ou apatia; em peritonite, sepse, choque, desidratação grave e agonia.',
    comoProcurar: [
      { passo: 'Olhe a face antes de tocar no abdome: a expressão diz a gravidade.', detalhe: 'Hipócrates comparava com a face de antes da doença — pergunte à família.' },
      { passo: 'Confira os sinais objetivos: turgor, enchimento capilar, extremidades, pressão, consciência.', detalhe: 'A fácies é o resumo; os sinais vitais são a medida.' },
      { passo: 'Abdome em tábua com fácies hipocrática: peritonite — cirurgia.', detalhe: 'Sem causa cirúrgica: reanimação, sepse, e a conversa sobre fim de vida quando for o caso.' },
    ],
    mecanismo: 'Hipoperfusão periférica (vasoconstrição adrenérgica e hipovolemia) esvazia a microcirculação da face, a desidratação reduz o volume dos tecidos moles (têmporas, órbitas), a hipóxia cianosa os lábios, e a dor visceral e a acidose imprimem a expressão; é a face do choque em qualquer etiologia.',
    significado: 'Sinal de gravidade extrema e mau prognóstico imediato; hoje serve para o reconhecimento à beira do leito de quem precisa de reanimação agora — e, no paciente terminal, para reconhecer a proximidade da morte e conduzir o cuidado e a família.',
    armadilhas: ['Caquexia crônica (câncer, AIDS) tem face escavada sem os sinais de hipoperfusão aguda.', 'Anorexia nervosa e desnutrição grave.', 'Máscara facial da esclerodermia e da paralisia facial bilateral são outra coisa.'],
    causas: [
      { titulo: 'Choque e hipoperfusão', mecanismo: 'Vasoconstrição, desidratação, hipóxia.', itens: ['Peritonite e sepse abdominal', 'Choque de qualquer etiologia', 'Desidratação grave (cólera, gastroenterite)', 'Agonia'] },
    ],
    referencias: ['Hipócrates. Prognóstico, II (trad.). In: Cairus HF, Ribeiro Jr WA. Textos hipocráticos. Fiocruz, 2005.'],
  },
  {
    slug: 'acromegalia-progressao',
    nome: 'Acromegalia — a face ao longo dos anos',
    sinonimos: ['Progressão da fácies acromegálica', 'Fotografias seriadas na acromegalia', 'Crescimento das extremidades'],
    sistema: 'endocrino',
    resumo: 'A comparação de fotografias de dez, vinte anos atrás com a face de hoje — testa e arcadas que avançaram, nariz e lábios que engrossaram, mandíbula que cresceu, dentes que se afastaram — é o exame que faz o diagnóstico que ninguém fez, porque a mudança de um ano é invisível.',
    definicao: 'Alterações progressivas da face e das extremidades por excesso de GH/IGF-1 documentadas em série temporal: bossa frontal e arcadas supraorbitárias proeminentes, alargamento do nariz e espessamento labial, prognatismo com diastemas e má oclusão, macroglossia, espessamento da pele com sulcos profundos e poros dilatados, aumento do número do sapato e do anel (mãos e pés em pá); voz grave, sudorese, artralgia, apneia do sono; média de 8 a 10 anos entre início e diagnóstico.',
    comoProcurar: [
      { passo: 'Peça fotos antigas — carteira de identidade, casamento, formatura — e compare lado a lado.', detalhe: 'É o teste mais sensível da beira do leito.' },
      { passo: 'Pergunte: mudou o número do sapato, do anel, do chapéu? Os dentes se afastaram?', detalhe: 'O paciente atribui à idade; a esposa sabe.' },
      { passo: 'Dose IGF-1 (ajustado à idade) e GH após glicose; RM de hipófise.', detalhe: 'Procure as comorbidades: hipertensão, diabetes, apneia, pólipos de cólon, cardiomiopatia.' },
    ],
    mecanismo: 'Adenoma hipofisário secretor de GH estimula o fígado a produzir IGF-1, que promove crescimento periosteal (não epifisário, fechado no adulto) dos ossos da face, mãos e pés, hipertrofia de cartilagens, tecidos moles e vísceras, e espessamento da pele; a lentidão da mudança é o que a torna invisível ao olhar cotidiano.',
    significado: 'Doença rara com diagnóstico tardio quase universal, e mortalidade dobrada por doença cardiovascular e câncer quando não tratada; a comparação fotográfica encurta em anos o tempo até o diagnóstico. Cirurgia transesfenoidal, análogos de somatostatina e pegvisomanto controlam.',
    armadilhas: ['Traços familiares grosseiros sem progressão: não é acromegalia — as fotos mostram estabilidade.', 'Paquidermoperiostose: baqueteamento e pele espessa sem GH alto.', 'Hipotireoidismo grave: face inchada, não crescida.'],
    causas: [
      { titulo: 'Excesso de GH', mecanismo: 'Crescimento periosteal e de partes moles.', itens: ['Adenoma hipofisário somatotrófico (98%)', 'Secreção ectópica de GHRH (carcinoide, raro)', 'Gigantismo quando antes do fechamento epifisário'] },
    ],
    referencias: ['Melmed S et al. A consensus statement on acromegaly therapeutic outcomes. Nat Rev Endocrinol, 2018.'],
  },
  {
    slug: 'noonan-e-klinefelter',
    nome: 'Hábito de Noonan e de Klinefelter',
    sinonimos: ['Síndrome de Noonan', 'Síndrome de Klinefelter (47,XXY)', 'Pescoço alado', 'Hábito eunucoide'],
    sistema: 'endocrino',
    resumo: 'Noonan: baixa estatura, pescoço alado, hipertelorismo, ptose, orelhas baixas e tórax com pectus, em menino ou menina — o "Turner masculino" com estenose pulmonar. Klinefelter: rapaz alto, de pernas longas, ginecomastia, testículos pequenos e firmes, pouca barba — o 47,XXY que passa despercebido até a infertilidade.',
    definicao: 'Noonan: baixa estatura, dismorfias faciais (hipertelorismo, fendas palpebrais oblíquas para baixo, ptose, orelhas de implantação baixa e rodadas), pescoço curto e alado com implantação baixa dos cabelos, pectus carinatum superior e excavatum inferior, criptorquidia, cardiopatia (estenose pulmonar, cardiomiopatia hipertrófica), tendência a sangramento; ambos os sexos. Klinefelter: estatura alta com envergadura e pernas longas (hábito eunucoide), ginecomastia, testículos pequenos (< 4 mL) e firmes, pelos escassos, distribuição feminina de gordura, infertilidade; frequentemente dificuldades de aprendizagem.',
    comoProcurar: [
      { passo: 'Noonan: meça altura, olhe a face e o pescoço, ausculte o coração (sopro de estenose pulmonar).', detalhe: 'Cariótipo normal — o diagnóstico é clínico e por painel genético (PTPN11).' },
      { passo: 'Klinefelter: meça envergadura e segmento inferior; palpe os testículos com orquidômetro; olhe as mamas.', detalhe: 'Testículos pequenos e firmes em adolescente alto: cariótipo.' },
      { passo: 'Nos dois, pergunte por escola, puberdade e fertilidade.', detalhe: 'Klinefelter: testosterona baixa, FSH/LH altos; reposição melhora osso, humor e composição corporal.' },
    ],
    mecanismo: 'Noonan: mutações ativadoras da via RAS-MAPK (PTPN11, SOS1, RAF1) alteram o desenvolvimento cardíaco, linfático (higroma fetal → pescoço alado) e o crescimento. Klinefelter: o cromossomo X extra causa fibrose e hialinização dos túbulos seminíferos (testículos pequenos, azoospermia) e hipogonadismo hipergonadotrófico; o estrogênio relativo dá ginecomastia; as epífises fecham tarde (pernas longas).',
    significado: 'Noonan (1:2.000) precisa de acompanhamento cardíaco e de crescimento (GH aprovado). Klinefelter (1:600 homens) é a aneuploidia mais comum e a mais subdiagnosticada — metade nunca descobre; a reposição de testosterona e a preservação de fertilidade (extração de espermatozoides) mudam a vida quando o diagnóstico chega na adolescência.',
    armadilhas: ['Turner (45,X): só meninas, pescoço alado, coarctação — Noonan tem cariótipo normal.', 'Marfan: alto e de pernas longas, mas com testículos normais e ectopia do cristalino.', 'Ginecomastia puberal fisiológica: transitória, com testículos normais.'],
    causas: [
      { titulo: 'Noonan', mecanismo: 'RASopatia.', itens: ['PTPN11 (50%)', 'SOS1, RAF1, KRAS', 'Autossômica dominante ou de novo'] },
      { titulo: 'Klinefelter', mecanismo: 'Aneuploidia sexual.', itens: ['47,XXY (80 a 90%)', 'Mosaicos 46,XY/47,XXY', 'Variantes 48,XXXY (mais grave)'] },
    ],
    referencias: ['Roberts AE et al. Noonan syndrome. Lancet, 2013.', 'Bonomi M et al. Klinefelter syndrome (KS): genetics, clinical phenotype and hypogonadism. J Endocrinol Invest, 2017.'],
  },
  {
    slug: 'sulco-de-harrison',
    nome: 'Sulco de Harrison',
    sinonimos: ['Sulco diafragmático', 'Depressão de Harrison', 'Tórax de raquitismo ou de asma crônica'],
    sistema: 'pediatrico',
    resumo: 'Um sulco horizontal permanente na parede torácica inferior, seguindo a linha de inserção do diafragma, com as costelas viradas para fora abaixo dele — o tórax mole do raquitismo ou da obstrução respiratória crônica da infância, puxado para dentro a cada inspiração até ficar marcado.',
    definicao: 'Depressão horizontal ou oblíqua bilateral na parede torácica anterolateral inferior, ao nível da inserção do diafragma (6ª a 7ª costelas), com abaulamento do rebordo costal abaixo; permanente, visível em repouso; em crianças com raquitismo (com rosário raquítico e alargamento de punhos) ou com obstrução respiratória crônica (asma grave, adenoides com respiração bucal, fibrose cística, bronquiolite obliterante) durante o crescimento.',
    comoProcurar: [
      { passo: 'Criança despida, de frente e de perfil, em repouso: o sulco acima do rebordo costal.', detalhe: 'Diferente da tiragem, que é dinâmica e some.' },
      { passo: 'Procure os companheiros: rosário raquítico, punhos alargados, pernas arqueadas (raquitismo) ou sibilos, respiração bucal, baqueteamento (pulmão).', detalhe: 'Radiografia de punho e 25-OH-vitamina D; ou espirometria e teste do suor.' },
      { passo: 'Em adulto, é sequela — pergunte pela infância.', detalhe: 'Não regride, mas a causa pode já ter passado.' },
    ],
    mecanismo: 'Durante anos de crescimento, a tração do diafragma sobre costelas amolecidas (raquitismo: osteoide não mineralizado) ou o esforço inspiratório contra obstrução (pressão pleural muito negativa) deformam a parede torácica no ponto de inserção diafragmática, e o osso se consolida na forma deformada.',
    significado: 'Marca de doença crônica na infância — deficiência de vitamina D grave ou doença pulmonar obstrutiva não controlada por anos. Raro em países ricos hoje; ainda visto no Brasil em raquitismo carencial, asma grave sem tratamento e fibrose cística tardia.',
    armadilhas: ['Tiragem subcostal aguda: dinâmica, de desconforto respiratório atual.', 'Pectus excavatum: depressão esternal mediana, não sulco horizontal.', 'Variante anatômica discreta em crianças magras.'],
    causas: [
      { titulo: 'Raquitismo', mecanismo: 'Costelas amolecidas.', itens: ['Deficiência de vitamina D', 'Raquitismo hipofosfatêmico', 'Doença renal crônica'] },
      { titulo: 'Obstrução respiratória crônica', mecanismo: 'Pressão pleural negativa repetida.', itens: ['Asma grave não controlada', 'Hipertrofia adenoamigdaliana', 'Fibrose cística', 'Bronquiolite obliterante, laringomalácia grave'] },
    ],
    referencias: ['Kliegman RM et al. Nelson Textbook of Pediatrics, 21ª ed. — Rickets; Chest wall deformities.'],
  },
  {
    slug: 'escoliose-teste-de-adams',
    nome: 'Escoliose — teste de Adams',
    sinonimos: ['Giba costal', 'Teste de flexão anterior', 'Escoliose idiopática do adolescente'],
    sistema: 'musculoesqueletico',
    resumo: 'Ombros e escápulas em alturas diferentes, um flanco mais fundo que o outro, e — ao inclinar o tronco para a frente — uma giba: o lado das costas que fica mais alto porque as costelas rodaram com as vértebras.',
    definicao: 'Curvatura lateral da coluna com rotação vertebral: em pé, assimetria de ombros, escápulas (uma mais proeminente), triângulos do talhe (espaço entre o braço e o flanco) e cristas ilíacas, desvio do tronco em relação à pelve (fio de prumo de C7 fora do sulco interglúteo); no teste de Adams (flexão anterior do tronco com joelhos estendidos e mãos juntas), giba costal (torácica) ou lombar do lado da convexidade; escoliômetro ≥ 7° indica radiografia; adolescente de 10 a 16 anos, meninas 8:1 nas curvas progressivas.',
    comoProcurar: [
      { passo: 'De costas, despido: ombros, escápulas, talhe, cristas ilíacas. Fio de prumo de C7.', detalhe: 'Assimetria de talhe é o sinal mais sensível em pé.' },
      { passo: 'Adams: peça para inclinar o tronco lentamente com as palmas juntas; olhe tangencialmente ao dorso.', detalhe: 'Giba = rotação = escoliose estrutural; sem giba, postural.' },
      { passo: 'Escoliômetro no ápice da giba; ≥ 7°: radiografia panorâmica em pé (ângulo de Cobb).', detalhe: 'Procure sinais de causa: manchas café-com-leite, tufo de pelos lombar, pés cavos, dor noturna, déficit neurológico.' },
    ],
    mecanismo: 'Na escoliose estrutural, as vértebras da curva rodam em torno do eixo longitudinal (corpos para a convexidade, processos espinhosos para a concavidade), arrastando as costelas — que se elevam do lado convexo e formam a giba quando o tronco flete; a idiopática do adolescente progride no estirão de crescimento por assimetria de crescimento vertebral de origem multifatorial.',
    significado: 'O rastreio escolar por Adams detecta a escoliose idiopática na fase em que o colete evita a cirurgia (curvas de 25 a 45° em esqueleto imaturo). Escoliose com dor, rigidez, déficit neurológico, curva torácica esquerda ou em criança pequena não é idiopática — ressonância.',
    armadilhas: ['Escoliose postural (discrepância de membros): some ao sentar ou ao calçar o lado curto; sem giba.', 'Curva torácica esquerda, dor ou pé cavo unilateral: siringomielia, tumor, medula presa.', 'Assimetria de escápulas por escápula alada (serrátil) sem escoliose.'],
    causas: [
      { titulo: 'Idiopática (80%)', mecanismo: 'Assimetria de crescimento vertebral.', itens: ['Escoliose idiopática do adolescente', 'Infantil e juvenil'] },
      { titulo: 'Secundária', mecanismo: 'Malformação ou desequilíbrio muscular.', itens: ['Congênita (hemivértebra, barra)', 'Neuromuscular (paralisia cerebral, Duchenne, mielomeningocele)', 'Sindrômica (Marfan, NF1)', 'Degenerativa do adulto'] },
    ],
    referencias: ['Hresko MT. Idiopathic scoliosis in adolescents. N Engl J Med, 2013.'],
  },
  {
    slug: 'cifose-de-scheuermann',
    nome: 'Cifose de Scheuermann',
    sinonimos: ['Cifose juvenil', 'Dorso curvo do adolescente', 'Osteocondrose vertebral'],
    sistema: 'musculoesqueletico',
    resumo: 'Adolescente com as costas arredondadas que não endireitam quando ele tenta — a cifose torácica rígida, angular, que persiste ao deitar e ao estender, diferente da postural que some ao pedir "endireite-se".',
    definicao: 'Hipercifose torácica ou toracolombar (> 45°) rígida, de ápice angular, que não se corrige com a extensão ativa nem com a hiperextensão passiva em decúbito ventral, em adolescente de 12 a 17 anos; hiperlordose lombar e cervical compensatórias, ombros protraídos, encurtamento de isquiotibiais; dor dorsal em metade; radiografia: acunhamento anterior ≥ 5° de três ou mais vértebras adjacentes, irregularidade dos platôs e nódulos de Schmorl.',
    comoProcurar: [
      { passo: 'De perfil, peça para "endireitar as costas" e para estender o tronco: a cifose de Scheuermann fica; a postural some.', detalhe: 'Deite o paciente de bruços e levante os ombros: a rigidez persiste.' },
      { passo: 'No Adams visto de lado, a cifose é angular (ápice agudo), não arredondada.', detalhe: 'Postural é uma curva harmoniosa.' },
      { passo: 'Radiografia de perfil da coluna em pé: Cobb e acunhamento.', detalhe: 'Encaminhe > 60° ou dor persistente.' },
    ],
    mecanismo: 'Alteração da ossificação endocondral dos platôs vertebrais anteriores durante o estirão de crescimento (herança e carga mecânica), com acunhamento anterior progressivo de vértebras consecutivas e herniação do disco para o corpo (Schmorl); a cifose resultante é estrutural e rígida.',
    significado: 'Segunda causa de deformidade da coluna do adolescente depois da escoliose; a maioria só precisa de exercício e vigilância, o colete funciona em esqueleto imaturo com 50 a 70°, e a cirurgia é rara. Distingui-la da cifose postural evita rotular má postura como doença — e vice-versa.',
    armadilhas: ['Cifose postural: flexível, corrige-se voluntariamente.', 'Espondilite anquilosante em rapaz com dor inflamatória: rigidez lombar e sacroilíacas.', 'Cifose congênita (vértebra em cunha única) e pós-infecciosa (mal de Pott, giba angular aguda).'],
    causas: [
      { titulo: 'Osteocondrose vertebral', mecanismo: 'Crescimento assimétrico dos corpos vertebrais.', itens: ['Cifose de Scheuermann (torácica)', 'Variante toracolombar (atletas, carga)'] },
    ],
    referencias: ['Lowe TG, Line BG. Evidence based medicine: analysis of Scheuermann kyphosis. Spine, 2007.'],
  },
  {
    slug: 'politelia',
    nome: 'Politelia — mamilo supranumerário',
    sinonimos: ['Mamilo acessório', 'Terceiro mamilo', 'Polimastia'],
    sistema: 'geral',
    resumo: 'Uma pequena mancha ou pápula acastanhada, às vezes com aréola e um mamilo miniatura, ao longo da linha que vai da axila à virilha — a linha mamária embrionária que deixou um resto, frequentemente tomado por nevo.',
    definicao: 'Mamilo acessório: pápula ou mácula castanha ou rósea de 2 a 10 mm, umbilicada ou com relevo central, com ou sem aréola pigmentada ao redor, situada na linha mamária (do oco axilar à região inguinal, passando lateral aos mamilos normais), mais comum abaixo da mama normal; único ou múltiplos; polimastia quando há tecido glandular associado (que pode inchar na gestação e lactação); presente em 1 a 5% da população, congênito.',
    comoProcurar: [
      { passo: 'Trace mentalmente a linha mamária e olhe as "pintas" nela.', detalhe: 'Mamilo acessório tem relevo central e às vezes uma aréola discreta; nevo não.' },
      { passo: 'Dermatoscopia se dúvida: aréola com sulcos radiais e ponto central.', detalhe: 'Pode ter pelos e glândulas.' },
      { passo: 'Pergunte se incha, dói ou secreta na gestação: polimastia.', detalhe: 'Tecido mamário acessório tem as mesmas doenças da mama, inclusive câncer (raro).' },
    ],
    mecanismo: 'Durante a 6ª semana embrionária, a linha mamária (crista mamária) vai da axila à virilha; normalmente só o par torácico persiste; falha na regressão de um segmento deixa mamilo, aréola ou glândula acessórios ao longo da linha.',
    significado: 'Variante congênita benigna e comum, que importa por três razões: não confundir com nevo (e não excisar por engano nem deixar de reconhecer), reconhecer o tecido mamário acessório que incha na lactação (e pode ter mastite e neoplasia), e a associação discutida com malformações renais (baixa evidência; investigar só se houver outras anomalias).',
    armadilhas: ['Nevo melanocítico e ceratose seborreica: sem estrutura de mamilo.', 'Tecido mamário axilar (polimastia) confundido com linfonodo ou lipoma axilar na gestante.', 'Excisar um mamilo acessório como "nevo suspeito": histologia mostra glândula mamária.'],
    causas: [
      { titulo: 'Persistência da linha mamária', mecanismo: 'Falha de regressão embrionária.', itens: ['Politelia isolada (esporádica ou familiar)', 'Polimastia', 'Síndromes raras (Simpson-Golabi-Behmel)'] },
    ],
    referencias: ['Grossl NA. Supernumerary breast tissue: historical perspectives and clinical features. South Med J, 2000.'],
  },
  {
    slug: 'mastite-e-abscesso-mamario',
    nome: 'Mastite e abscesso mamário',
    sinonimos: ['Mastite puerperal', 'Mastite lactacional', 'Abscesso subareolar', 'Ingurgitamento mamário'],
    sistema: 'geral',
    resumo: 'Área vermelha, quente, endurecida e dolorosa em cunha numa mama que amamenta, com febre e calafrios — mastite; se aparece uma zona flutuante e a febre persiste com antibiótico, virou abscesso. Fora da lactação, na fumante, é o abscesso subareolar recorrente.',
    definicao: 'Mastite lactacional: eritema, calor, edema e dor em segmento da mama (em cunha), com febre > 38,5 °C, mal-estar e mialgia, geralmente nas primeiras 6 semanas pós-parto, associada a fissura mamilar e estase de leite. Abscesso: área de flutuação, massa dolorosa bem delimitada, pele brilhante e às vezes necrótica, persistência da febre após 48 h de antibiótico; ultrassom confirma coleção. Não lactacional: abscesso subareolar periductal em fumante, recorrente, com fístula periareolar; ou carcinoma inflamatório simulando mastite em mulher fora da lactação que não responde.',
    comoProcurar: [
      { passo: 'Delimite a área: cunha segmentar (mastite) ou massa flutuante (abscesso).', detalhe: 'Ingurgitamento é bilateral, difuso, sem febre alta.' },
      { passo: 'Examine o mamilo: fissura é a porta de entrada; corrija a pega.', detalhe: 'Continue amamentando ou esvazie a mama — a estase piora tudo.' },
      { passo: 'Sem melhora em 48 h ou flutuação: ultrassom e aspiração/drenagem guiada.', detalhe: 'Mastite fora da lactação sem resposta: biópsia de pele — carcinoma inflamatório.' },
    ],
    mecanismo: 'Estase de leite (pega inadequada, mamadas espaçadas) mais fissura mamilar permitem que S. aureus da pele e da boca do lactente invada os ductos e o tecido intersticial; a inflamação do segmento obstruído evolui para necrose e coleção. No abscesso subareolar da fumante, metaplasia escamosa dos ductos os obstrui e infecta repetidamente.',
    significado: 'Acomete 10% das lactantes; tratada cedo (esvaziamento + antibiótico anti-estafilocócico) resolve sem interromper a amamentação. Abscesso exige drenagem (aspiração seriada guiada por ultrassom evita a incisão). O diagnóstico que não pode atrasar é o carcinoma inflamatório na mama "com mastite" que não melhora.',
    armadilhas: ['Carcinoma inflamatório: mama vermelha e edemaciada em não lactante, sem febre, sem resposta a antibiótico.', 'Ingurgitamento e ducto obstruído: sem febre alta, resolve com esvaziamento.', 'Candidíase mamilar: dor em queimação bilateral com mamilo brilhante — outra doença.'],
    causas: [
      { titulo: 'Lactacional', mecanismo: 'Estase + porta de entrada.', itens: ['S. aureus (inclusive MRSA)', 'Estreptococos', 'Fissura mamilar, pega inadequada'] },
      { titulo: 'Não lactacional', mecanismo: 'Obstrução ductal ou doença de base.', itens: ['Abscesso subareolar periductal (tabagismo)', 'Mastite granulomatosa idiopática', 'Tuberculose mamária', 'Carcinoma inflamatório (diferencial)'] },
    ],
    referencias: ['Amir LH; Academy of Breastfeeding Medicine. ABM clinical protocol #4: Mastitis, revised 2014. Breastfeed Med, 2014.'],
  },
  {
    slug: 'hernia-epigastrica-e-de-spiegel',
    nome: 'Hérnia epigástrica e de Spiegel',
    sinonimos: ['Hérnia da linha alba', 'Hérnia ventral', 'Hérnia da linha semilunar'],
    sistema: 'abdome',
    resumo: 'Um nódulo pequeno, doloroso, na linha média entre o umbigo e o xifoide, que aparece ao contrair o abdome — gordura pré-peritoneal pela linha alba (epigástrica); ou um abaulamento discreto na borda lateral do reto, abaixo do umbigo, difícil de palpar porque fica sob a aponeurose (Spiegel) e que encarcera com frequência.',
    definicao: 'Epigástrica: pequeno defeito (0,5 a 2 cm) na linha alba supraumbilical por onde hernia gordura pré-peritoneal (às vezes peritônio), formando nódulo mediano firme, doloroso à palpação e ao esforço, frequentemente irredutível por ser gordura aprisionada; múltiplas em 20%. Spiegel: hérnia pela linha semilunar (borda lateral do reto), tipicamente abaixo do umbigo no cinturão de Spiegel, interparietal (sob o oblíquo externo), com abaulamento mal definido ou só dor localizada, mais em obesos e idosos; risco de encarceramento de 20 a 25%.',
    comoProcurar: [
      { passo: 'Epigástrica: palpe a linha alba com o paciente deitado e depois erguendo a cabeça — o nódulo aparece e dói.', detalhe: 'Diferente da diástase (abaulamento longitudinal amplo, sem anel).' },
      { passo: 'Spiegel: com o paciente em pé e em Valsalva, palpe a borda lateral do reto abaixo do umbigo; dor localizada com abaulamento sutil.', detalhe: 'Ultrassom ou TC confirmam — é a hérnia que o exame físico mais perde.' },
      { passo: 'Dor abdominal aguda com nódulo irredutível e doloroso: encarceramento — cirurgia.', detalhe: 'Spiegel encarcerada em idoso simula obstrução sem causa.' },
    ],
    mecanismo: 'Epigástrica: orifícios da linha alba por onde passam vasos perfurantes alargam-se com a pressão intra-abdominal e deixam passar gordura pré-peritoneal, que fica presa (dor). Spiegel: a linha semilunar é fraca onde a aponeurose do transverso e do oblíquo interno se separam, abaixo da linha arqueada; o saco atravessa a aponeurose do transverso e fica contido pelo oblíquo externo — por isso é interparietal e pouco visível.',
    significado: 'Ambas são cirúrgicas: a epigástrica pela dor e pelo crescimento, a de Spiegel pelo alto risco de encarceramento. A de Spiegel entra no diferencial da dor abdominal lateral crônica "sem causa" em obesos — pensar nela é o exame.',
    armadilhas: ['Diástase de retos: sem anel, sem risco de encarceramento, não se opera por si.', 'Lipoma da parede e endometrioma de cicatriz.', 'Hérnia de Spiegel confundida com hérnia inguinal ou apendicite quando dói à direita.'],
    causas: [
      { titulo: 'Fraqueza da parede', mecanismo: 'Orifícios aponeuróticos sob pressão.', itens: ['Obesidade, tosse crônica, esforço', 'Gestações múltiplas', 'Colagenopatias', 'Cirurgia prévia (trocarte)'] },
    ],
    referencias: ['Larson DW, Farley DR. Spigelian hernias: repair and outcome for 81 patients. World J Surg, 2002.'],
  },
  {
    slug: 'onfalite-e-granuloma-umbilical',
    nome: 'Onfalite e granuloma umbilical',
    sinonimos: ['Infecção do coto umbilical', 'Granuloma do umbigo', 'Umbigo do recém-nascido'],
    sistema: 'pediatrico',
    resumo: 'Eritema e edema que avançam da base do coto para a pele ao redor, com secreção fétida, no recém-nascido — onfalite, que em horas vira sepse. O granuloma é o botão rosado, úmido e mole que fica depois que o coto cai, benigno, mas que pede olhar para excluir um resto do úraco ou do ducto onfalomesentérico.',
    definicao: 'Onfalite: eritema, edema e endurecimento da pele periumbilical (> 5 mm além da base do coto), secreção purulenta ou fétida, dor, com ou sem febre, letargia e recusa alimentar; nos primeiros 15 dias de vida; celulite que pode progredir para fasciíte necrosante e sepse. Granuloma umbilical: tecido de granulação rosado, mole, úmido, séssil ou pediculado, de 3 a 10 mm, no fundo do umbigo após a queda do coto, com secreção serosa, sem eritema ao redor; diferente de pólipo umbilical (mucosa vermelho-brilhante, firme — resto de ducto onfalomesentérico) e de secreção clara persistente ou urinosa (úraco).',
    comoProcurar: [
      { passo: 'Meça o eritema a partir da base do coto: mais de 5 mm ou endurecimento = onfalite; internar e antibiótico venoso.', detalhe: 'Cheiro ruim do coto sozinho não é onfalite.' },
      { passo: 'Após a queda: granuloma é rosa-pálido e mole; pólipo é vermelho-vivo e firme; secreção que aumenta ao chorar ou com cheiro de urina é úraco.', detalhe: 'Granuloma: nitrato de prata; pólipo e úraco: ultrassom e cirurgia.' },
      { passo: 'Cordão que demora > 3 semanas para cair com onfalites de repetição: deficiência de adesão leucocitária.', detalhe: 'Raro, mas o umbigo é a pista.' },
    ],
    mecanismo: 'O coto umbilical é tecido necrótico colonizado; com higiene inadequada ou parto em condições precárias, S. aureus, estreptococos e gram-negativos invadem a parede abdominal pelos vasos umbilicais ainda pérvios — via direta para a veia porta e a circulação. O granuloma é a resposta de reparo exagerada após a separação; pólipo e seio urácico são remanescentes embrionários.',
    significado: 'Onfalite é emergência neonatal com mortalidade alta em países pobres; clorexidina no coto a reduz. Granuloma é benigno e trivial de tratar; o que não pode ser tratado com nitrato de prata é o pólipo do ducto onfalomesentérico (pode ter intestino no fundo) e o úraco patente (infecção urinária recorrente).',
    armadilhas: ['Hérnia umbilical do lactente: abaulamento redutível, benigno, que fecha até os 4 anos.', 'Aplicar nitrato de prata num pólipo de mucosa intestinal.', 'Onfalite sem eritema em prematuro séptico: a pele pode não reagir.'],
    causas: [
      { titulo: 'Onfalite', mecanismo: 'Infecção do coto e da parede.', itens: ['S. aureus, estreptococos', 'Gram-negativos', 'Parto domiciliar, higiene do coto', 'Deficiência de adesão leucocitária (recorrente)'] },
      { titulo: 'Massa umbilical do lactente', mecanismo: 'Reparo ou remanescente embrionário.', itens: ['Granuloma umbilical', 'Pólipo do ducto onfalomesentérico', 'Úraco patente ou cisto de úraco'] },
    ],
    referencias: ['Stewart D, Benitz W; AAP Committee on Fetus and Newborn. Umbilical cord care in the newborn infant. Pediatrics, 2016.'],
  },
  {
    slug: 'hernia-femoral',
    nome: 'Hérnia femoral',
    sinonimos: ['Hérnia crural', 'Hérnia abaixo do ligamento inguinal'],
    sistema: 'abdome',
    resumo: 'Massa pequena, arredondada, abaixo e lateral ao tubérculo púbico, na raiz da coxa de uma mulher idosa — muitas vezes irredutível e descoberta só quando encarcera, porque o anel femoral é estreito e rígido.',
    definicao: 'Protrusão pelo canal femoral, medial à veia femoral, abaixo do ligamento inguinal: tumoração de 2 a 4 cm na parte medial da raiz da coxa, abaixo e lateral ao tubérculo púbico (a inguinal fica acima e medial), frequentemente irredutível, com pouco impulso à tosse; mulheres idosas 4:1; 40% se apresentam encarceradas ou estranguladas (dor, obstrução intestinal, sinais inflamatórios locais).',
    comoProcurar: [
      { passo: 'Localize o tubérculo púbico: massa abaixo e lateral a ele é femoral; acima e medial é inguinal.', detalhe: 'O ligamento inguinal é a fronteira.' },
      { passo: 'Em idosa com obstrução intestinal "sem hérnia", examine a raiz da coxa com a perna estendida — a hérnia é pequena e escondida pela gordura.', detalhe: 'Um terço das hérnias femorais encarceradas é diagnosticado na cirurgia.' },
      { passo: 'Toda hérnia femoral é cirúrgica eletiva, mesmo assintomática.', detalhe: 'O risco de estrangulamento é alto demais para esperar.' },
    ],
    mecanismo: 'O canal femoral (medial à veia femoral, sob o ligamento inguinal) é um espaço estreito de paredes rígidas (ligamento lacunar, púbis); com a pelve mais larga da mulher e a frouxidão da idade, o peritônio hernia por ele, e o anel inelástico estrangula facilmente o conteúdo (frequentemente uma alça parcial — hérnia de Richter, que obstrui sem obstruir).',
    significado: 'Representa 3% das hérnias, mas 40% das estranguladas; a alta taxa de encarceramento justifica operar sempre. Em mulher idosa com vômitos e distensão, a raiz da coxa é o lugar que salva vida ao ser examinado.',
    armadilhas: ['Linfonodo inguinal (mais lateral e superficial), lipoma, varizes da safena (safenectasia, que some ao deitar) e aneurisma femoral (pulsátil).', 'Hérnia de Richter: encarcera parte da parede da alça — dor local sem obstrução completa.', 'Confundir com hérnia inguinal e operar pelo acesso errado.'],
    causas: [
      { titulo: 'Fraqueza do canal femoral', mecanismo: 'Anatomia e pressão.', itens: ['Sexo feminino, idade', 'Multiparidade', 'Emagrecimento (perda da gordura do canal)', 'Pressão intra-abdominal crônica'] },
    ],
    referencias: ['HerniaSurge Group. International guidelines for groin hernia management. Hernia, 2018.'],
  },
  {
    slug: 'eventracao-com-perda-de-domicilio',
    nome: 'Eventração com perda de domicílio',
    sinonimos: ['Hérnia incisional gigante', 'Hérnia com perda de domicílio', 'Loss of domain'],
    sistema: 'abdome',
    resumo: 'A hérnia incisional cresceu tanto que boa parte das vísceras vive fora da cavidade abdominal, num saco pendente coberto por pele fina e ulcerada — e o abdome, que encolheu ao redor do que sobrou, não as aceita de volta sem preparo.',
    definicao: 'Hérnia incisional volumosa em que o volume do saco herniário é ≥ 20 a 25% do volume da cavidade abdominal (TC), com defeito aponeurótico amplo (> 10 cm), saco pendente com pele atrófica, hiperpigmentada, com dermatite de estase e ulcerações, alças e omento palpáveis através da pele, irredutibilidade parcial, dor lombar por desequilíbrio postural e limitação funcional; geralmente após múltiplas laparotomias, infecção de ferida e obesidade.',
    comoProcurar: [
      { passo: 'Em pé e deitado: meça o defeito e estime o volume do saco; observe a pele.', detalhe: 'Pele ulcerada e alças visíveis por transparência são risco de fístula.' },
      { passo: 'Tente reduzir com o paciente deitado: não volta — perda de domicílio.', detalhe: 'TC com volumetria calcula a relação saco/cavidade.' },
      { passo: 'Avalie função respiratória, obesidade e tabagismo: o reparo exige preparo (pneumoperitônio progressivo, toxina botulínica, perda de peso).', detalhe: 'Reduzir à força causa síndrome compartimental abdominal.' },
    ],
    mecanismo: 'Um defeito da parede não reparado cresce com a pressão intra-abdominal e a tração lateral dos músculos; as vísceras que migram para o saco deixam a cavidade, que se retrai e perde complacência; a pele sobre o saco sofre estase e atrofia. Devolver o conteúdo aumenta bruscamente a pressão intra-abdominal (compartimental) e a restrição diafragmática.',
    significado: 'O estágio final da hérnia incisional negligenciada; cirurgia complexa (separação de componentes, tela) com preparo pré-operatório que expande a cavidade. Complicações do saco (ulceração, fístula, encarceramento) e a incapacidade funcional são as indicações.',
    armadilhas: ['Ascite volumosa e obesidade central sem hérnia.', 'Tumor de parede (desmoide, sarcoma) ou endometrioma de cicatriz.', 'Encarceramento em hérnia gigante é difícil de reconhecer porque ela "nunca reduz".'],
    causas: [
      { titulo: 'Hérnia incisional evoluída', mecanismo: 'Defeito crescente com migração visceral.', itens: ['Laparotomias repetidas e infecção de ferida', 'Obesidade, DPOC, tabagismo', 'Abdome aberto (peritoneostomia) prévio', 'Colagenopatias'] },
    ],
    referencias: ['Parker SG et al. Definitions for loss of domain: an international Delphi consensus. World J Surg, 2020.'],
  },
  {
    slug: 'distensao-abdominal-obstrutiva',
    nome: 'Distensão abdominal por obstrução',
    sinonimos: ['Abdome distendido', 'Meteorismo obstrutivo', 'Timpanismo difuso', 'Peristaltismo visível'],
    sistema: 'abdome',
    resumo: 'Abdome globoso, tenso, timpânico à percussão, às vezes com as alças desenhando ondas sob a pele magra, em paciente que parou de evacuar e eliminar gases e vomita — o intestino cheio de gás e líquido acima de um obstáculo.',
    definicao: 'Aumento do volume abdominal simétrico e progressivo, com timpanismo difuso à percussão, parede tensa, ruídos hidroaéreos aumentados e metálicos (fase inicial) ou abolidos (tardia), peristaltismo visível (ondas de contração sob a pele em pacientes magros), dor em cólica, vômitos (biliosos, depois fecaloides) e parada de eliminação de gases e fezes; mais distensão quanto mais distal a obstrução (cólon); cicatrizes cirúrgicas e hérnias como pistas da causa.',
    comoProcurar: [
      { passo: 'Percuta em várias direções: timpânico difuso é gás; maciço com macicez móvel é ascite.', detalhe: 'Distensão "gasosa" tensa com dor: obstrução até prova contrária.' },
      { passo: 'Ausculte 2 minutos: ruídos metálicos, em jato, com timbre de gota caindo no metal.', detalhe: 'Silêncio depois de horas de ruídos altos é sinal de exaustão ou isquemia.' },
      { passo: 'Procure cicatrizes (bridas), hérnias em todas as regiões (inclusive femoral) e faça o toque retal (fecaloma, tumor, ampola vazia).', detalhe: 'Radiografia em pé: níveis hidroaéreos; TC define nível e causa.' },
    ],
    mecanismo: 'Acima do obstáculo, gás deglutido e produzido, secreções digestivas (7 a 8 L/dia) e líquido sequestrado distendem as alças; o peristaltismo luta contra a obstrução (cólica, ruídos metálicos, ondas visíveis) até fatigar; a distensão comprime a parede da alça e reduz a perfusão — daí isquemia, perfuração e sepse na obstrução em alça fechada e no estrangulamento.',
    significado: 'Os 6 F da distensão (fat, fluid, flatus, feces, fetus, fatal growth) começam pela percussão; distensão timpânica com dor e vômitos é obstrução — brida, hérnia e tumor de cólon respondem por 80%. Dor contínua, febre, defesa ou acidose indicam estrangulamento e cirurgia imediata.',
    armadilhas: ['Íleo paralítico pós-operatório ou metabólico: distensão sem cólica, ruídos abolidos desde o início.', 'Pseudo-obstrução colônica (Ogilvie) no idoso acamado: ceco enorme sem obstáculo.', 'Ascite tensa e gestação avançada: percussão decide.', 'Obstrução alta (jejuno): pouca distensão, muitos vômitos — não subestime pela barriga plana.'],
    causas: [
      { titulo: 'Obstrução mecânica', mecanismo: 'Obstáculo à progressão.', itens: ['Bridas e aderências (pós-operatório)', 'Hérnias encarceradas', 'Tumor colorretal', 'Volvo de sigmoide, intussuscepção', 'Fecaloma, bezoar, cálculo biliar'] },
      { titulo: 'Funcional', mecanismo: 'Paralisia da motilidade.', itens: ['Íleo pós-operatório', 'Hipocalemia, opioides', 'Peritonite', 'Pseudo-obstrução (Ogilvie)'] },
    ],
    referencias: ['Ten Broek RPG et al. Bologna guidelines for diagnosis and management of adhesive small bowel obstruction (ASBO): 2017 update. World J Emerg Surg, 2018.'],
  },
  {
    slug: 'linha-nigra-e-estrias-gravidicas',
    nome: 'Linha nigra e estrias gravídicas',
    sinonimos: ['Striae gravidarum', 'Hiperpigmentação da gravidez', 'Melasma gravídico'],
    sistema: 'geral',
    resumo: 'Uma linha escura vertical do púbis ao umbigo (e às vezes ao xifoide), aréolas mais escuras e estrias róseas nos flancos e mamas do abdome gravídico — o estrogênio e o MSH pintando a pele, e o colágeno cedendo ao crescimento rápido.',
    definicao: 'Linha nigra: hiperpigmentação da linha alba, do púbis ao umbigo ou além, a partir do segundo trimestre, mais intensa em pele escura, que clareia meses após o parto; acompanhada de escurecimento de aréolas, axilas, genitais, cicatrizes e nevos, e melasma facial. Estrias gravídicas: lesões lineares atróficas, róseas a violáceas (recentes) que se tornam esbranquiçadas e nacaradas (antigas), nos flancos, abdome inferior, mamas, coxas e nádegas, a partir do terceiro trimestre, em 50 a 90% das gestantes.',
    comoProcurar: [
      { passo: 'Inspecione o abdome gravídico: linha nigra mediana, estrias lateral e inferiormente.', detalhe: 'São achados esperados — o valor é reconhecê-los como fisiológicos e diferenciá-los das estrias violáceas largas do Cushing.' },
      { passo: 'Nevos que escureceram uniformemente na gestação são esperados; os que ficaram assimétricos ou cresceram, não.', detalhe: 'Melanoma não tem folga na gravidez.' },
      { passo: 'Estrias fora da gestação e da adolescência, largas e violáceas, com fraqueza e giba: Cushing.', detalhe: 'Corticoide tópico potente também estria.' },
    ],
    mecanismo: 'Estrogênio, progesterona e o hormônio melanócito-estimulante (MSH), elevados na gestação, ativam melanócitos das áreas já mais pigmentadas (linha alba, aréolas, genitais). As estrias resultam da ruptura das fibras elásticas e do colágeno dérmico sob distensão rápida, com influência do cortisol e da relaxina — genética e ganho de peso determinam quem as tem.',
    significado: 'Fisiológicos e sem tratamento eficaz comprovado (cremes não previnem estrias). A linha nigra some; as estrias clareiam mas ficam. O que importa: reconhecer o padrão para não confundir com doença e usar o exame da pele da gestante para pegar o que não é fisiológico (melanoma, colestase com prurido e escoriações, penfigoide gestacional).',
    armadilhas: ['Estrias de Cushing: largas (> 1 cm), violáceas, no tronco e raiz dos membros, com outros sinais.', 'Estrias da adolescência (estirão) e do fisiculturismo: mesmas lesões, outro contexto.', 'Hiperpigmentação de Addison: mucosas e pregas palmares, com hipotensão e fadiga.'],
    causas: [
      { titulo: 'Fisiologia da gestação', mecanismo: 'Hormônios e distensão.', itens: ['Estrogênio, progesterona, MSH', 'Distensão rápida da pele', 'Genética e ganho de peso'] },
    ],
    referencias: ['Tunzi M, Gray GR. Common skin conditions during pregnancy. Am Fam Physician, 2007.'],
  },
  {
    slug: 'varicocele-exame-fisico',
    nome: 'Varicocele — "saco de vermes"',
    sinonimos: ['Varizes do cordão espermático', 'Plexo pampiniforme dilatado'],
    sistema: 'geral',
    resumo: 'Acima do testículo esquerdo, em pé, um emaranhado de veias moles que se enchem com a manobra de Valsalva e esvaziam ao deitar — o "saco de vermes" da varicocele, que se vê em 15% dos homens e em 40% dos inférteis.',
    definicao: 'Dilatação e tortuosidade das veias do plexo pampiniforme, palpável ou visível no escroto acima do testículo, à esquerda em 85 a 90%: grau I (palpável só com Valsalva), II (palpável em repouso, não visível), III (visível através da pele, "saco de vermes"); aumenta em pé e com Valsalva, reduz em decúbito; testículo ipsilateral pode ser menor e mais mole (hipotrofia); dor em peso vespertina; varicocele direita isolada, súbita ou que não esvazia deitado sugere massa retroperitoneal.',
    comoProcurar: [
      { passo: 'Examine em pé, em sala aquecida (o cremáster contraído esconde tudo); palpe o cordão acima do testículo e peça Valsalva.', detalhe: 'Deitado, a varicocele esvazia — se não esvaziar, procure obstrução venosa (tumor renal).' },
      { passo: 'Compare o volume dos testículos com orquidômetro: diferença > 20% indica hipotrofia.', detalhe: 'No adolescente, é a indicação de tratamento.' },
      { passo: 'Ultrassom com Doppler quantifica (veias > 3 mm, refluxo).', detalhe: 'Espermograma no adulto com infertilidade.' },
    ],
    mecanismo: 'A veia espermática esquerda desemboca em ângulo reto na veia renal (a direita, oblíqua na cava), com coluna hidrostática mais longa e válvulas frequentemente incompetentes; o refluxo dilata o plexo pampiniforme. O calor e a estase alteram a espermatogênese e o crescimento testicular.',
    significado: 'A causa corrigível mais comum de infertilidade masculina; a correção melhora parâmetros seminais e, em casos selecionados, a taxa de gravidez. No adolescente, hipotrofia testicular indica cirurgia. Varicocele direita ou de início súbito no adulto: tumor renal comprimindo a veia até prova contrária.',
    armadilhas: ['Hidrocele, espermatocele e hérnia inguinoescrotal no diferencial da massa escrotal — a varicocele é mole, tubular e muda com a posição.', 'Varicocele subclínica só ao Doppler: pouca relevância.', 'Cremáster contraído em sala fria: exame falso-negativo.'],
    causas: [
      { titulo: 'Insuficiência valvular da espermática', mecanismo: 'Refluxo venoso.', itens: ['Varicocele primária (esquerda, adolescência)', 'Anatomia da veia renal esquerda (nutcracker)'] },
      { titulo: 'Secundária', mecanismo: 'Obstrução venosa.', itens: ['Tumor renal com trombo de veia renal/cava', 'Massa retroperitoneal', 'Fibrose retroperitoneal'] },
    ],
    referencias: ['Practice Committee of the ASRM. Report on varicocele and infertility: a committee opinion. Fertil Steril, 2014.'],
  },
  {
    slug: 'hidrocele-vs-hernia',
    nome: 'Hidrocele × hérnia inguinoescrotal',
    sinonimos: ['Transiluminação escrotal', 'Massa escrotal', 'Hérnia inguinoescrotal'],
    sistema: 'geral',
    resumo: 'Duas bolsas escrotais aumentadas: a hidrocele é tensa, lisa, transilumina em vermelho e permite chegar acima dela no cordão; a hérnia é irredutível ou redutível com gorgolejo, não transilumina, tem impulso à tosse e continua para o canal inguinal — os dedos no cordão decidem.',
    definicao: 'Hidrocele: aumento escrotal indolor, liso, tenso ou flutuante, que transilumina (brilho vermelho homogêneo com lanterna atrás), com o polo superior delimitável (o cordão espermático é palpável acima da massa), testículo às vezes não palpável dentro do líquido; comunicante no lactente (varia de tamanho ao longo do dia, aumenta ao chorar). Hérnia inguinoescrotal: massa que vem do canal inguinal (não se consegue "passar por cima" dela), impulso à tosse, redutível com gorgolejo ou irredutível, não transilumina (exceto alça muito fina em lactente), pode ter ruídos hidroaéreos.',
    comoProcurar: [
      { passo: 'Tente pinçar o cordão acima da massa: consegue = escrotal (hidrocele, tumor); não consegue = vem do canal (hérnia).', detalhe: 'É a manobra decisiva.' },
      { passo: 'Transilumine em sala escura: hidrocele brilha; hérnia e tumor não.', detalhe: 'No lactente, alça fina pode transiluminar — cuidado.' },
      { passo: 'Peça para tossir e tente reduzir; palpe o testículo.', detalhe: 'Testículo não palpável por hidrocele tensa em adulto: ultrassom — pode esconder tumor.' },
    ],
    mecanismo: 'Hidrocele: líquido entre as camadas da túnica vaginal — por desequilíbrio secreção/absorção (idiopática do adulto), reação a orquiepididimite, torção ou tumor, ou por conduto peritônio-vaginal patente (comunicante do lactente). Hérnia: o mesmo conduto patente, largo o suficiente para passar intestino ou omento, ou defeito adquirido da parede posterior.',
    significado: 'Hidrocele do lactente resolve sozinha até 1 a 2 anos (não operar antes); hérnia inguinal do lactente se opera ao diagnóstico (encarcera). No adulto, hidrocele idiopática é benigna, mas hidrocele nova em jovem esconde tumor até o ultrassom dizer que não. Hérnia inguinoescrotal encarcerada é urgência.',
    armadilhas: ['Tumor testicular com hidrocele reativa: transilumina — o ultrassom vê o testículo.', 'Espermatocele: cisto na cabeça do epidídimo, acima e atrás do testículo, transilumina.', 'Torção testicular com hidrocele reativa em adolescente com dor: emergência.'],
    causas: [
      { titulo: 'Hidrocele', mecanismo: 'Líquido na túnica vaginal.', itens: ['Comunicante (lactente)', 'Idiopática do adulto', 'Reativa (epididimite, torção, tumor, trauma)', 'Filariose (endêmica)'] },
      { titulo: 'Hérnia inguinoescrotal', mecanismo: 'Conteúdo abdominal pelo canal.', itens: ['Indireta congênita (lactente)', 'Indireta e direta do adulto'] },
    ],
    referencias: ['Dagur G et al. Classifying hydroceles of the pelvis and groin: an overview of etiology, secondary complications, evaluation, and management. Curr Urol, 2017.'],
  },
  {
    slug: 'criptorquidia',
    nome: 'Criptorquidia',
    sinonimos: ['Testículo não descido', 'Escroto vazio', 'Testículo retrátil (diferencial)'],
    sistema: 'pediatrico',
    resumo: 'Hemiescroto vazio e hipoplásico no lactente, com o testículo palpável no canal inguinal ou em lugar nenhum — o que não desceu até os 6 meses não desce mais, e cada mês fora da bolsa custa espermatogênese e adiciona risco de câncer.',
    definicao: 'Ausência de um ou ambos os testículos na bolsa escrotal, com hemiescroto pequeno e pouco pregueado: testículo palpável no canal inguinal (80%, não pode ser trazido à bolsa ou volta imediatamente) ou não palpável (abdominal, ausente, atrófico); 3% dos recém-nascidos a termo e 30% dos prematuros, com descida espontânea até os 6 meses em metade; bilateral com hipospádia: investigar diferença de desenvolvimento sexual. Testículo retrátil: sobe pelo cremáster mas é trazido à bolsa e lá permanece — normal.',
    comoProcurar: [
      { passo: 'Criança relaxada, mãos aquecidas, em decúbito ou sentada de pernas cruzadas; "ordenhe" o canal inguinal de cima para baixo com uma mão e tente pegar o testículo com a outra.', detalhe: 'Frio e medo contraem o cremáster e escondem o retrátil.' },
      { passo: 'Se trouxe à bolsa e ele fica: retrátil (acompanhar). Se não trouxe ou volta na hora: criptorquidia.', detalhe: 'Encaminhe aos 6 meses; orquidopexia entre 6 e 18 meses.' },
      { passo: 'Não palpável bilateral, ou unilateral com hipospádia: cariótipo e hormônios antes de qualquer cirurgia.', detalhe: 'Ultrassom não muda a conduta no não palpável — laparoscopia diagnostica.' },
    ],
    mecanismo: 'A descida testicular tem fase transabdominal (INSL3) e inguinoescrotal (andrógenos, nervo genitofemoral, gubernáculo) no terceiro trimestre; prematuridade, deficiência androgênica ou anomalias anatômicas a interrompem. O testículo fora da bolsa fica 2 a 3 °C mais quente, perde células germinativas a partir do primeiro ano e tem risco de malignização 3 a 5 vezes maior (menor se corrigido antes da puberdade).',
    significado: 'A anomalia genital mais comum do menino; a cirurgia precoce (6 a 18 meses) preserva fertilidade e facilita a vigilância do câncer. O erro mais frequente é chamar o retrátil de criptorquidia (cirurgia desnecessária) ou o contrário (perda de tempo).',
    armadilhas: ['Testículo retrátil: cremáster ativo, normal, mas deve ser reexaminado anualmente (10% ascendem).', 'Testículo ascendente: estava na bolsa e subiu — também é cirúrgico.', 'Bilateral não palpável no recém-nascido: menina virilizada (hiperplasia adrenal congênita) até prova contrária — emergência.'],
    causas: [
      { titulo: 'Falha de descida', mecanismo: 'Hormonal ou anatômica.', itens: ['Prematuridade e baixo peso', 'Idiopática', 'Hipogonadismo (Kallmann, Prader-Willi)', 'Diferenças do desenvolvimento sexual', 'Gastrosquise, hérnia diafragmática'] },
    ],
    referencias: ['Kolon TF et al. Evaluation and treatment of cryptorchidism: AUA guideline. J Urol, 2014.'],
  },
  {
    slug: 'priapismo',
    nome: 'Priapismo',
    sinonimos: ['Ereção prolongada', 'Priapismo isquêmico e não isquêmico'],
    sistema: 'geral',
    resumo: 'Ereção rígida e dolorosa dos corpos cavernosos, com a glande mole, que já dura horas sem estímulo — isquêmica, em falcêmico, usuário de injeção intracavernosa ou de trazodona, e cada hora a mais custa tecido erétil.',
    definicao: 'Ereção persistente (> 4 horas) sem estímulo sexual. Isquêmico (95%): corpos cavernosos rígidos e dolorosos, glande e corpo esponjoso flácidos, evolução para dor intensa; gasometria cavernosa com hipóxia e acidose; emergência. Não isquêmico (fístula arteriocavernosa pós-trauma perineal): ereção parcial, não dolorosa, tumescente mas não rígida, sangue cavernoso arterial. Recorrente (stuttering) na anemia falciforme: episódios noturnos repetidos.',
    comoProcurar: [
      { passo: 'Pergunte a duração e a dor; palpe: cavernosos rígidos com glande mole = isquêmico.', detalhe: 'Não isquêmico é parcial e indolor.' },
      { passo: 'Causa: falciforme, injeção intracavernosa, trazodona/antipsicóticos, cocaína, leucemia, trauma perineal.', detalhe: 'Hemograma e eletroforese em quem não tem diagnóstico.' },
      { passo: 'Isquêmico: aspiração e irrigação com fenilefrina agora; após 24 h, a chance de preservar a função cai.', detalhe: 'Não isquêmico: Doppler mostra a fístula; conduta expectante ou embolização.' },
    ],
    mecanismo: 'Isquêmico: falha da drenagem venosa (compartimento fechado de baixo fluxo) por obstrução (hemácias falcizadas, células leucêmicas) ou por relaxamento persistente do músculo liso (fármacos alfa-bloqueadores, injeção intracavernosa) — hipóxia, acidose e fibrose do tecido erétil em 24 a 48 h. Não isquêmico: fluxo arterial alto por fístula, sem isquemia.',
    significado: 'Emergência urológica: o isquêmico causa disfunção erétil permanente em > 90% quando ultrapassa 36 horas. Em criança e adolescente negro, é apresentação de anemia falciforme; em adulto, checar fármacos e drogas. O paciente demora a procurar por vergonha — pergunte diretamente.',
    armadilhas: ['Ereção fisiológica prolongada em quem usou inibidor de PDE5 (< 4 h): não é priapismo.', 'Trauma perineal com ereção parcial indolor semanas depois: não isquêmico — não aspirar.', 'Priapismo recorrente noturno em falcêmico tratado como "normal".'],
    causas: [
      { titulo: 'Isquêmico', mecanismo: 'Baixo fluxo, oclusão venosa.', itens: ['Anemia falciforme', 'Injeção intracavernosa (papaverina, alprostadil)', 'Trazodona, antipsicóticos, cocaína', 'Leucemia, mieloma, tumores pélvicos', 'Idiopático'] },
      { titulo: 'Não isquêmico', mecanismo: 'Alto fluxo por fístula.', itens: ['Trauma perineal ou peniano', 'Pós-cirúrgico'] },
    ],
    referencias: ['Bivalacqua TJ et al. Acute ischemic priapism: an AUA/SMSNA guideline. J Urol, 2021.'],
  },
  {
    slug: 'prolapso-uterino-e-cistocele',
    nome: 'Prolapso uterino e cistocele',
    sinonimos: ['Distopia genital', 'Prolapso de órgão pélvico', 'Bexiga caída', 'Sistema POP-Q'],
    sistema: 'geral',
    resumo: 'Abaulamento na vagina que aparece ao fazer força ou que "sai" quando está de pé, em mulher multípara — a parede anterior (bexiga), o colo do útero ou a parede posterior (reto) descendo pelo assoalho pélvico enfraquecido.',
    definicao: 'Descida de órgãos pélvicos pela vagina: cistocele (abaulamento da parede vaginal anterior), prolapso uterino (colo visível ao introito ou além, até a procidência total com o útero fora), retocele (parede posterior), enterocele (fundo de saco); graduado pelo POP-Q em relação ao hímen (estágio I a IV); sensação de peso, "bola" na vagina, incontinência ou retenção urinária, dificuldade evacuatória; exame em posição ginecológica e em pé, com esforço; mucosa exposta pode ulcerar e ceratinizar.',
    comoProcurar: [
      { passo: 'Espéculo de uma valva afastando a parede posterior para ver a anterior descer ao esforço, e vice-versa.', detalhe: 'Peça Valsalva e tosse; repita em pé se a queixa não se reproduz deitada.' },
      { passo: 'Localize o colo com o esforço: acima do hímen, no hímen, ou além.', detalhe: 'Procidência total: útero inteiro exteriorizado, com mucosa ceratinizada e úlceras.' },
      { passo: 'Avalie o resíduo pós-miccional e a incontinência com o prolapso reduzido (incontinência oculta).', detalhe: 'Pessário ou cirurgia conforme sintomas e desejo.' },
    ],
    mecanismo: 'Lesão e frouxidão dos suportes do assoalho pélvico — ligamentos uterossacros e cardinais, fáscia pubocervical e retovaginal, levantador do ânus — por partos vaginais, idade e hipoestrogenismo, obesidade, esforço crônico e colagenopatias; a pressão intra-abdominal empurra os órgãos pela vagina, o ponto de menor resistência.',
    significado: 'Afeta metade das multíparas em algum grau, com sintomas em 10 a 20%; tratamento só quando incomoda (pessário, fisioterapia, cirurgia). O prolapso total exposto ulcera e pode obstruir os ureteres — reduzir e tratar. Incontinência urinária oculta aparece ao corrigir o prolapso; avalie antes.',
    armadilhas: ['Cisto de Gartner, cisto de Bartholin e pólipo cervical simulando abaulamento.', 'Mioma parido pelo colo.', 'Prolapso de cúpula vaginal em histerectomizada.'],
    causas: [
      { titulo: 'Fraqueza do assoalho pélvico', mecanismo: 'Lesão dos suportes.', itens: ['Partos vaginais (múltiplos, instrumentados, macrossomia)', 'Idade e menopausa', 'Obesidade, constipação, tosse crônica', 'Histerectomia prévia', 'Colagenopatias'] },
    ],
    referencias: ['Barber MD. Pelvic organ prolapse. BMJ, 2016.'],
  },
  {
    slug: 'hemorroidas-internas-prolapsadas',
    nome: 'Hemorroidas internas prolapsadas',
    sinonimos: ['Hemorroidas grau III e IV', 'Prolapso hemorroidário', 'Hemorroidas mistas'],
    sistema: 'abdome',
    resumo: 'Mamilos avermelhados e úmidos de mucosa que saem pelo ânus ao evacuar e voltam com o dedo (grau III) ou não voltam mais (grau IV), com sangue vivo e muco — as três almofadas vasculares que desceram, diferentes das externas trombosadas e do prolapso retal.',
    definicao: 'Hemorroidas internas (acima da linha pectínea, cobertas por mucosa, indolores) classificadas por prolapso: I, sangram sem prolapsar; II, prolapsam ao esforço e retornam espontaneamente; III, prolapsam e exigem redução manual; IV, permanentemente prolapsadas, irredutíveis. Ao exame: mamilos de mucosa rósea a avermelhada nas posições 3, 7 e 11 horas (litotomia), com sulcos radiais entre eles, sangue vivo, muco, prurido e sujidade; grau IV encarcerado e trombosado: edema, dor intensa, necrose.',
    comoProcurar: [
      { passo: 'Inspecione afastando as nádegas, depois peça esforço evacuatório: os mamilos aparecem e mostram o grau.', detalhe: 'Melhor sentado no vaso ou em cócoras, se possível.' },
      { passo: 'Sulcos radiais entre mamilos = hemorroidas; anéis concêntricos = prolapso retal.', detalhe: 'Não confunda com plicomas (pele) nem com hemorroida externa trombosada (abaixo da linha pectínea, dolorosa).' },
      { passo: 'Toque retal e anuscopia sempre; colonoscopia em > 45 anos ou com anemia/alteração do hábito.', detalhe: 'Sangramento retal não é hemorroida até o cólon ser visto.' },
    ],
    mecanismo: 'As almofadas anais (plexo hemorroidário superior com tecido conjuntivo e músculo liso de Treitz) perdem a sustentação com esforço evacuatório crônico, constipação, gestação e idade; deslizam distalmente, ingurgitam e sangram (sangue arterial vivo); no prolapso irredutível, o esfíncter estrangula e tromboza.',
    significado: 'Graus I e II tratam-se com fibra e ligadura elástica; III e IV com cirurgia (hemorroidectomia, grampeamento, desarterização). Grau IV encarcerado e trombosado é urgência. O sangramento hemorroidário nunca dispensa investigar o cólon na faixa etária de risco.',
    armadilhas: ['Prolapso retal completo: anéis concêntricos, grande, com sulco circunferencial.', 'Câncer de reto baixo ou anal palpável ao toque — que foi omitido "porque era hemorroida".', 'Condiloma e papila anal hipertrófica.'],
    causas: [
      { titulo: 'Deslizamento das almofadas anais', mecanismo: 'Esforço e perda de suporte.', itens: ['Constipação e esforço evacuatório', 'Gestação e parto', 'Idade', 'Diarreia crônica, tempo prolongado no vaso', 'Hipertensão portal (varizes anorretais — diferente)'] },
    ],
    referencias: ['Davis BR et al. The ASCRS Clinical Practice Guidelines for the Management of Hemorrhoids. Dis Colon Rectum, 2018.'],
  },
]
