import type { Sinal } from './esquemas'

/**
 * Síndromes genéticas, parte 2 — craniofaciais, hematológicas, metabólicas e
 * de membros: 15 fenótipos que o pediatra e o clínico reconhecem no exame.
 */
export const SINAIS_GENETICAS_2: Sinal[] = [
  {
    slug: 'sindrome-de-holt-oram',
    nome: 'Síndrome de Holt-Oram — mão e coração',
    sinonimos: ['Síndrome mão-coração', 'Polegar trifalângico', 'TBX5'],
    sistema: 'genetico',
    resumo: 'Polegar com três falanges, que parece um dedo, hipoplásico ou ausente, com ombros estreitos e caídos e antebraço curto — e uma comunicação interatrial ou um bloqueio de condução no ECG. Mão alterada pede ausculta.',
    definicao: 'Síndrome autossômica dominante (TBX5) com anomalias dos membros superiores sempre presentes, frequentemente assimétricas e mais à esquerda: polegar trifalângico, hipoplásico ou ausente, sindactilia, hipoplasia do rádio, focomelia nos casos graves, ombros estreitos e caídos, clavículas curtas, limitação da supinação; cardiopatia em 75% (comunicação interatrial tipo ostium secundum, comunicação interventricular) e distúrbios de condução (bloqueio AV, bradicardia).',
    comoProcurar: [
      { passo: 'Examine os polegares: número de falanges (pregas), oposição, tamanho.', detalhe: 'O polegar trifalângico fica no plano dos outros dedos e não opõe.' },
      { passo: 'Avalie ombros, clavículas e a supinação dos antebraços.', detalhe: 'Radiografia dos membros superiores e das mãos.' },
      { passo: 'Ausculte (desdobramento fixo de B2 da CIA) e faça ECG.', detalhe: 'Ecocardiograma em todo paciente e parente com anomalia de polegar.' },
    ],
    mecanismo: 'O fator de transcrição TBX5 comanda tanto a formação do membro superior quanto a septação dos átrios e o sistema de condução; a haploinsuficiência afeta os dois — por isso a mão e o coração andam juntos.',
    significado: 'A anomalia visível do polegar é o que leva ao ecocardiograma que encontra a CIA e ao ECG que encontra o bloqueio. Orienta cirurgia de polegar (policização) e aconselhamento (50% de transmissão).',
    armadilhas: ['Anemia de Fanconi: polegar hipoplásico com manchas café com leite, baixa estatura e falência medular.', 'VACTERL: anomalias radiais com vértebras, ânus, traqueia e rins.', 'TAR (trombocitopenia com ausência de rádio): polegares presentes.'],
    causas: [
      { titulo: 'TBX5', mecanismo: 'Desenvolvimento do membro superior e do coração.', itens: ['Mutação herdada (autossômica dominante)', 'Mutação de novo'] },
    ],
    referencias: ['McDermott DA et al. TBX5 genetic testing validates strict clinical criteria for Holt-Oram syndrome. Pediatr Res, 2005.'],
  },
  {
    slug: 'facies-de-hurler',
    nome: 'Fácies grosseira das mucopolissacaridoses',
    sinonimos: ['Síndrome de Hurler', 'Síndrome de Hunter', 'Gargulismo', 'MPS'],
    sistema: 'genetico',
    resumo: 'Criança que era normal ao nascer e ficou com traços grosseiros — lábios e língua grossos, nariz largo, sobrancelhas espessas, cabelos ásperos —, com giba lombar, articulações rígidas em garra, fígado e baço grandes, hérnias e córnea turva.',
    definicao: 'Fenótipo das mucopolissacaridoses (deficiências de enzimas lisossômicas com acúmulo de glicosaminoglicanos): face grosseira progressiva (bossa frontal, ponte nasal baixa e larga, narinas antevertidas, lábios espessos, macroglossia, hipertrofia gengival, dentes espaçados, sobrancelhas espessas, hirsutismo); macrocefalia; opacidade de córnea (Hurler; ausente no Hunter); hepatoesplenomegalia, hérnias umbilical e inguinal; disostose múltipla (giba toracolombar por vértebras em bico, costelas em remo), rigidez articular com mãos em garra, baixa estatura; surdez, rinorreia e otites crônicas, apneia obstrutiva, valvopatia; deficiência intelectual nas formas graves. Hunter (MPS II) é ligada ao X e tem lesões em seixo nas escápulas.',
    comoProcurar: [
      { passo: 'Compare fotos da criança com meses de vida: a face ficou grosseira com o tempo.', detalhe: 'Pergunte por otites, roncos e rinorreia persistente.' },
      { passo: 'Palpe fígado e baço, procure hérnias, examine a coluna (giba) e a amplitude articular.', detalhe: 'Mãos em garra sem artrite inflamatória.' },
      { passo: 'Examine a córnea com lanterna e ausculte o coração.', detalhe: 'Glicosaminoglicanos urinários e dosagem enzimática confirmam.' },
    ],
    mecanismo: 'As enzimas lisossômicas que degradam dermatam e heparam sulfato faltam; os glicosaminoglicanos se acumulam em todos os tecidos conjuntivos, ossos, vísceras, valvas, córnea e, nas formas neuronopáticas, no cérebro — a infiltração progressiva produz a grosseria dos traços e das articulações.',
    significado: 'O diagnóstico precoce muda o prognóstico: transplante de células-tronco hematopoéticas antes dos 2 anos na Hurler preserva a cognição, e a reposição enzimática melhora vísceras e mobilidade. As otites e hérnias de repetição costumam vir antes do diagnóstico.',
    armadilhas: ['Hipotireoidismo congênito: face infiltrada e macroglossia, sem giba e com TSH alto.', 'Mucolipidoses e fucosidose: fenótipo parecido, outras enzimas.', 'Síndrome de Down: face plana, hipotonia, sem piora progressiva nem hepatoesplenomegalia.'],
    causas: [
      { titulo: 'Deficiência de enzimas lisossômicas', mecanismo: 'Acúmulo de glicosaminoglicanos.', itens: ['MPS I Hurler (alfa-L-iduronidase)', 'MPS II Hunter (iduronato sulfatase, ligada ao X)', 'MPS III Sanfilippo (neurológica)', 'MPS IV Morquio, MPS VI Maroteaux-Lamy'] },
    ],
    referencias: ['Muenzer J. Overview of the mucopolysaccharidoses. Rheumatology, 2011.'],
  },
  {
    slug: 'dactilite-falciforme',
    nome: 'Dactilite falciforme (síndrome mão-pé)',
    sinonimos: ['Síndrome mão-pé', 'Dactilite da anemia falciforme', 'Crise vaso-oclusiva do lactente'],
    sistema: 'genetico',
    resumo: 'Lactente de 6 meses a 2 anos que chora com as mãos e os pés inchados, quentes e dolorosos, simetricamente, sem trauma — muitas vezes a primeira manifestação da anemia falciforme.',
    definicao: 'Crise vaso-oclusiva dos pequenos ossos das mãos e pés (metacarpos, metatarsos, falanges) na anemia falciforme (HbSS e HbSβ0) entre 6 meses e 3 anos, quando a medula ativa ainda ocupa esses ossos: edema dorsal difuso, doloroso, quente, uni ou bilateral, com irritabilidade, recusa de apoio ou de pegar objetos e febre baixa; radiografia normal no início e, após 2 semanas, reação periosteal e lesões líticas. Outros sinais da doença no exame: palidez, icterícia escleral, esplenomegalia no lactente (depois autoesplenectomia), úlceras maleolares no adolescente, priapismo, retardo puberal.',
    comoProcurar: [
      { passo: 'Observe o dorso das mãos e dos pés: edema em salsicha dos dedos ou do dorso inteiro.', detalhe: 'Palpe o calor e a dor sobre os metacarpos.' },
      { passo: 'Procure palidez, icterícia e baço; pergunte pelo teste do pezinho.', detalhe: 'Eletroforese de hemoglobina se não houver diagnóstico.' },
      { passo: 'Diferencie de osteomielite: febre alta, toxemia, dor localizada em um osso.', detalhe: 'Osteomielite por Salmonella é mais comum no falciforme.' },
    ],
    mecanismo: 'As hemácias com HbS polimerizam em desoxigenação e ficam rígidas; nos ossos pequenos com medula hematopoética ativa e circulação terminal, ocluem capilares e causam infarto medular — edema, dor e, depois, reação periosteal de reparo.',
    significado: 'É frequentemente o sinal que revela a doença em quem não teve triagem neonatal, e marca maior gravidade futura. Hidratação, analgesia e início de penicilina profilática, vacinas e hidroxiureia.',
    armadilhas: ['Osteomielite: febre alta, um osso só, marcadores muito altos — pode coexistir.', 'Artrite idiopática juvenil: rara nessa idade, com rigidez matinal e sinovite articular.', 'Maus-tratos: lesões assimétricas, fraturas em idades diferentes.'],
    causas: [
      { titulo: 'Doença falciforme', mecanismo: 'Vaso-oclusão em ossos com medula ativa.', itens: ['HbSS', 'HbSβ0-talassemia', 'HbSC e HbSβ+ (menos frequente)'] },
    ],
    referencias: ['Kato GJ et al. Sickle cell disease. Nat Rev Dis Primers, 2018.'],
  },
  {
    slug: 'facies-talassemica',
    nome: 'Fácies talassêmica',
    sinonimos: ['Fácies em esquilo', 'Talassemia beta maior', 'Crânio em escova'],
    sistema: 'genetico',
    resumo: 'Criança pálida e ictérica com bochechas e maxila proeminentes, dentes superiores projetados para a frente, ponte nasal deprimida e bossa frontal — o osso da face expandido pela medula que tenta, sem conseguir, produzir hemácias.',
    definicao: 'Deformidade craniofacial da talassemia beta maior (ou intermédia) mal transfundida: hipertrofia maxilar com protrusão dos incisivos superiores e má oclusão, malar proeminente, ponte nasal achatada, bossa frontal e parietal, hipertelorismo aparente; palidez, icterícia, hepatoesplenomegalia volumosa, baixa estatura e retardo puberal; radiografia do crânio com espessamento da díploe e trabéculas perpendiculares (crânio "em escova" ou "cabelo em pé"); com sobrecarga de ferro por transfusões, pigmentação cinza-bronzeada da pele.',
    comoProcurar: [
      { passo: 'Observe a face de perfil: maxila projetada, malar alto, nariz achatado.', detalhe: 'Examine a oclusão dentária.' },
      { passo: 'Palpe fígado e baço; olhe a esclera e a palidez.', detalhe: 'Pergunte pela origem (Mediterrâneo, Oriente Médio, Sudeste Asiático) e consanguinidade.' },
      { passo: 'Pergunte sobre transfusões e quelação.', detalhe: 'Hemograma com microcitose grave, eletroforese com HbF e HbA2 altas.' },
    ],
    mecanismo: 'Sem cadeias beta, as alfa em excesso precipitam e destroem os eritroblastos na medula (eritropoese ineficaz); a anemia estimula eritropoetina, e a medula se expande dentro dos ossos da face e do crânio, alargando-os, e fora deles (hepatoesplenomegalia e massas paravertebrais).',
    significado: 'A fácies é o retrato de uma talassemia sem transfusão adequada; o regime transfusional regular desde cedo previne a deformidade, e a quelação de ferro previne a morte por cardiomiopatia. Transplante e terapia gênica são curativos.',
    armadilhas: ['Anemia ferropriva grave: microcitose sem esplenomegalia volumosa nem deformidade óssea.', 'Anemia falciforme: pode ter bossas, mas com crises vaso-oclusivas e HbS.', 'Hidrocefalia: macrocrania sem hipertrofia maxilar.'],
    causas: [
      { titulo: 'Talassemia beta', mecanismo: 'Eritropoese ineficaz e expansão medular.', itens: ['Talassemia beta maior (β0/β0)', 'Talassemia intermédia', 'Hemoglobina E/β-talassemia'] },
    ],
    referencias: ['Taher AT et al. Thalassaemia. Lancet, 2018.'],
  },
  {
    slug: 'sindrome-de-digeorge',
    nome: 'Síndrome de DiGeorge (deleção 22q11.2)',
    sinonimos: ['Síndrome velocardiofacial', 'CATCH22', 'Deleção 22q11.2'],
    sistema: 'genetico',
    resumo: 'Recém-nascido com cardiopatia conotruncal, convulsão por cálcio baixo e infecções de repetição — e uma face discreta: fendas palpebrais estreitas, nariz tubular com ponta bulbosa, boca pequena, orelhas pequenas e com hélix dobrada. Fala anasalada vem depois.',
    definicao: 'Síndrome da microdeleção 22q11.2 (a mais comum das microdeleções): cardiopatia conotruncal (tetralogia de Fallot, interrupção do arco aórtico tipo B, truncus arteriosus, CIV); hipocalcemia neonatal por hipoplasia de paratireoides; imunodeficiência de células T por hipoplasia tímica (infecções, raramente grave); insuficiência velofaríngea e fenda palatina submucosa (voz anasalada, regurgitação nasal); dismorfias leves — face alongada, fendas palpebrais curtas, nariz com raiz alta e ponta bulbosa, asas hipoplásicas, filtro curto, boca pequena, micrognatia, orelhas pequenas e de implantação baixa com hélix sobredobrada, dedos longos e afilados; dificuldade de aprendizagem e alto risco de transtornos psiquiátricos na adolescência.',
    comoProcurar: [
      { passo: 'Em todo recém-nascido com cardiopatia conotruncal, dose o cálcio e peça contagem de linfócitos T.', detalhe: 'Timo ausente na radiografia ou na cirurgia é pista.' },
      { passo: 'Observe nariz, fendas palpebrais, boca e orelhas.', detalhe: 'A face é sutil — raramente diagnóstica sozinha.' },
      { passo: 'Na criança maior, escute a fala (anasalada) e examine o palato (úvula bífida, fenda submucosa).', detalhe: 'Microarranjo ou FISH para 22q11.2 confirmam.' },
    ],
    mecanismo: 'A deleção inclui o TBX1, que comanda o desenvolvimento das 3ª e 4ª bolsas faríngeas e das células da crista neural cardíaca — daí o timo, as paratireoides, a via de saída do coração, o palato e a face afetados juntos.',
    significado: 'Diagnóstico que muda o cuidado cirúrgico (sangue irradiado, sem vacinas vivas até avaliar imunidade), o controle do cálcio, a fonoterapia e o acompanhamento psiquiátrico; risco de 50% de transmissão.',
    armadilhas: ['Tetralogia de Fallot isolada: todo Fallot merece teste para 22q11.2.', 'Hipocalcemia neonatal por outras causas: mãe diabética, prematuridade.', 'CHARGE: coloboma, atresia de coanas e orelhas malformadas.'],
    causas: [
      { titulo: 'Microdeleção 22q11.2', mecanismo: 'Haploinsuficiência do TBX1 e genes vizinhos.', itens: ['Deleção de 3 Mb (maioria, de novo)', 'Deleções atípicas menores', 'Herança autossômica dominante em 10%'] },
    ],
    referencias: ['McDonald-McGinn DM et al. 22q11.2 deletion syndrome. Nat Rev Dis Primers, 2015.'],
  },
  {
    slug: 'sindrome-de-treacher-collins',
    nome: 'Síndrome de Treacher Collins',
    sinonimos: ['Disostose mandibulofacial', 'TCOF1'],
    sistema: 'genetico',
    resumo: 'Face com as fendas palpebrais inclinadas para baixo, falha na pálpebra inferior, malares e mandíbula pequenos, orelhas malformadas ou ausentes e surdez de condução — numa criança de inteligência normal.',
    definicao: 'Disostose mandibulofacial autossômica dominante (TCOF1, POLR1C/D) com envolvimento simétrico dos derivados do 1º e 2º arcos faríngeos: fendas palpebrais oblíquas para baixo, coloboma (entalhe) do terço lateral da pálpebra inferior com ausência de cílios medialmente a ele, hipoplasia dos zigomáticos (face "de ave"), micrognatia e retrognatia, microtia ou orelhas malformadas, atresia do conduto auditivo com surdez de condução, fenda palatina, macrostomia, projeção de cabelos na bochecha; inteligência normal; risco de obstrução de via aérea no recém-nascido.',
    comoProcurar: [
      { passo: 'Observe a inclinação das fendas palpebrais e o terço lateral da pálpebra inferior.', detalhe: 'Conte os cílios: ausentes medialmente ao entalhe.' },
      { passo: 'Palpe os malares e o mento; examine orelhas e condutos.', detalhe: 'Simetria dos achados distingue de microssomia hemifacial.' },
      { passo: 'Teste a audição precocemente e avalie a via aérea e a alimentação.', detalhe: 'Pesquisa genética do TCOF1.' },
    ],
    mecanismo: 'A proteína treacle é necessária para a biogênese de ribossomos nas células da crista neural que formam os ossos da face; sem ela, essas células morrem por apoptose durante a migração, e os derivados do 1º e 2º arcos ficam hipoplásicos de forma simétrica.',
    significado: 'A inteligência normal com surdez de condução exige aparelho auditivo precoce (de condução óssea) para que a criança não seja rotulada com deficiência intelectual; a via aérea pode exigir traqueostomia; cirurgias craniofaciais reconstroem malar e mandíbula.',
    armadilhas: ['Microssomia hemifacial (Goldenhar): assimétrica, com dermoides epibulbares.', 'Sequência de Pierre Robin isolada: micrognatia sem malares hipoplásicos e sem coloboma palpebral.', 'Síndrome de Nager: com anomalias radiais dos polegares.'],
    causas: [
      { titulo: 'Biogênese ribossômica na crista neural', mecanismo: 'Apoptose de células da crista neural.', itens: ['TCOF1 (autossômica dominante, 80%)', 'POLR1D (dominante), POLR1C (recessiva)', 'Mutações de novo em 60%'] },
    ],
    referencias: ['Trainor PA et al. Treacher Collins syndrome: etiology, pathogenesis and prevention. Eur J Hum Genet, 2009.'],
  },
  {
    slug: 'craniossinostose-sindromica',
    nome: 'Craniossinostose de Crouzon e Apert',
    sinonimos: ['Síndrome de Crouzon', 'Síndrome de Apert', 'Acrocefalossindactilia', 'FGFR2'],
    sistema: 'genetico',
    resumo: 'Crânio alto e curto, olhos saltados por órbitas rasas, terço médio da face afundado e mandíbula que parece prognata — Crouzon; tudo isso com dedos das mãos e dos pés fundidos em luva — Apert.',
    definicao: 'Craniossinostoses sindrômicas por mutações ativadoras do FGFR2 (autossômicas dominantes): fechamento prematuro das suturas coronais com braquicefalia ou turricefalia, proptose por órbitas rasas (risco de exposição corneana e luxação do globo), hipertelorismo, estrabismo, hipoplasia do terço médio da face com pseudoprognatismo, nariz em bico, palato ogival; hipertensão intracraniana (papiledema), obstrução de via aérea superior. Apert acrescenta sindactilia complexa simétrica de mãos e pés (fusão óssea do 2º ao 4º dedos, "mão em luva ou colher"), polegar e hálux largos e desviados, acne intensa, e mais frequentemente deficiência intelectual. Pfeiffer tem polegares e háluces largos; Saethre-Chotzen, ptose e implantação baixa dos cabelos.',
    comoProcurar: [
      { passo: 'Olhe o crânio de lado e de cima (braquicefalia, turricefalia) e palpe as suturas.', detalhe: 'Crista óssea sobre a sutura fechada.' },
      { passo: 'Observe proptose, hipertelorismo, terço médio e oclusão.', detalhe: 'Fundo de olho para papiledema.' },
      { passo: 'Examine mãos e pés: sindactilia em luva (Apert) ou polegares largos (Pfeiffer).', detalhe: 'TC com reconstrução 3D e teste genético.' },
    ],
    mecanismo: 'O FGFR2 ativado acelera a diferenciação de osteoblastos nas suturas, que fecham antes do tempo; o crânio cresce para onde ainda pode (para cima ou para os lados) e a base, curta, não acompanha — órbitas rasas e face média hipoplásica. Na mão, a mesma via impede a apoptose interdigital.',
    significado: 'Exige equipe craniofacial: descompressão e remodelamento craniano precoces para evitar hipertensão intracraniana e dano visual, proteção da córnea, manejo da via aérea e cirurgias de mão. A face é o diagnóstico.',
    armadilhas: ['Plagiocefalia posicional: crânio em paralelogramo com suturas abertas.', 'Craniossinostose isolada (sagital, metópica): sem proptose nem alterações de membros.', 'Proptose por hipertireoidismo: adquirida, com retração palpebral.'],
    causas: [
      { titulo: 'Mutações ativadoras de FGFR', mecanismo: 'Fechamento prematuro das suturas.', itens: ['Crouzon (FGFR2)', 'Apert (FGFR2 S252W/P253R)', 'Pfeiffer (FGFR1/FGFR2)', 'Saethre-Chotzen (TWIST1)', 'Muenke (FGFR3)'] },
    ],
    referencias: ['Johnson D, Wilkie AO. Craniosynostosis. Eur J Hum Genet, 2011.'],
  },
  {
    slug: 'sequencia-de-pierre-robin',
    nome: 'Sequência de Pierre Robin',
    sinonimos: ['Micrognatia com glossoptose', 'Robin', 'Fenda palatina em U'],
    sistema: 'pediatrico',
    resumo: 'Recém-nascido com o queixo muito pequeno e recuado, língua caída para trás, fenda no palato em forma de U e respiração ruidosa que piora de barriga para cima — até cianose e dificuldade para mamar.',
    definicao: 'Sequência (cascata de eventos a partir de uma anomalia inicial) com a tríade micrognatia/retrognatia, glossoptose (a língua cai posteriormente e obstrui a hipofaringe) e fenda palatina em U, larga, sem fenda labial; obstrução de via aérea superior de gravidade variável (estridor inspiratório, retrações, apneias, cianose) pior em decúbito dorsal, dificuldade alimentar e baixo ganho de peso; isolada ou associada a síndromes (Stickler em até 1/3 — miopia alta, descolamento de retina, artropatia; deleção 22q11.2; Treacher Collins).',
    comoProcurar: [
      { passo: 'Observe o perfil: queixo recuado muito atrás do lábio superior.', detalhe: 'Examine o palato com lanterna: fenda em U.' },
      { passo: 'Observe a respiração em decúbito dorsal e ventral: melhora de bruços.', detalhe: 'Saturação durante sono e mamadas; polissonografia.' },
      { passo: 'Procure sinais de síndrome: miopia, articulações, face (Stickler, 22q11.2).', detalhe: 'Avaliação oftalmológica precoce em todo Robin.' },
    ],
    mecanismo: 'A mandíbula pequena no início da gestação mantém a língua alta entre as lâminas palatinas, impedindo que elas se fechem na linha média (fenda em U); após o nascimento, a mandíbula curta deixa a base da língua cair sobre a faringe e obstruir a via aérea.',
    significado: 'Emergência de via aérea neonatal com tratamento escalonado (posição prona, cânula nasofaríngea, distração mandibular, traqueostomia) e alimentação assistida; o crescimento da mandíbula nos primeiros anos melhora a obstrução. Rastrear Stickler previne cegueira.',
    armadilhas: ['Laringomalácia: estridor que também muda com posição, mas com mandíbula e palato normais.', 'Fenda palatina isolada sem micrognatia: via aérea normal.', 'Atresia de coanas: cianose que melhora com o choro.'],
    causas: [
      { titulo: 'Mandíbula pequena primária', mecanismo: 'Cascata micrognatia → glossoptose → fenda.', itens: ['Isolada', 'Síndrome de Stickler (COL2A1, COL11A1)', 'Deleção 22q11.2', 'Treacher Collins, restrição mecânica intraútero'] },
    ],
    referencias: ['Côté A et al. Pierre Robin sequence: review of diagnostic and treatment challenges. Int J Pediatr Otorhinolaryngol, 2015.'],
  },
  {
    slug: 'sindrome-de-beckwith-wiedemann',
    nome: 'Síndrome de Beckwith-Wiedemann',
    sinonimos: ['Macroglossia com onfalocele', 'Supercrescimento 11p15', 'Hemi-hipertrofia'],
    sistema: 'genetico',
    resumo: 'Recém-nascido grande para a idade com língua enorme que fica para fora da boca, onfalocele ou hérnia umbilical, sulcos nos lóbulos das orelhas, hipoglicemia nas primeiras horas e, às vezes, um lado do corpo maior que o outro.',
    definicao: 'Síndrome de supercrescimento por alterações epigenéticas ou genéticas da região 11p15.5 (IGF2, CDKN1C, H19): macrossomia pré e pós-natal, macroglossia (dificuldade de alimentação e respiração, protrusão lingual), defeitos da parede abdominal (onfalocele, hérnia umbilical, diástase de retos), hemi-hipertrofia (lateralização do crescimento), sulcos lineares nos lóbulos e depressões na hélix posterior das orelhas, nevus flammeus na glabela, visceromegalia (fígado, rins, adrenais), hipoglicemia neonatal por hiperinsulinismo; risco aumentado de tumores embrionários (tumor de Wilms, hepatoblastoma) nos primeiros 8 anos.',
    comoProcurar: [
      { passo: 'Observe a língua, os lóbulos das orelhas (sulcos) e a glabela.', detalhe: 'Compare comprimento e circunferência de membros dos dois lados.' },
      { passo: 'Examine o abdome: umbigo, diástase, fígado e rins palpáveis.', detalhe: 'Glicemia seriada nas primeiras 72 horas.' },
      { passo: 'Pergunte por fertilização assistida (mais frequente).', detalhe: 'Teste de metilação 11p15; ultrassom abdominal a cada 3 meses e alfafetoproteína até os 4 a 8 anos.' },
    ],
    mecanismo: 'Na região 11p15 há genes com imprinting que equilibram o crescimento: o IGF2 (paterno, promove) e o CDKN1C (materno, freia). Perda da metilação materna ou dissomia uniparental paterna desequilibram a balança para o crescimento excessivo — e para tumores embrionários.',
    significado: 'A macroglossia e a onfalocele levam ao diagnóstico, que exige manejo da hipoglicemia, correção da parede e da língua e, sobretudo, rastreamento de Wilms e hepatoblastoma, que detecta tumores em estágio curável.',
    armadilhas: ['Hipotireoidismo congênito: macroglossia com hipotonia, icterícia prolongada e TSH alto.', 'Mucopolissacaridose: macroglossia progressiva, não neonatal.', 'Trissomia 21: língua protrusa por boca pequena e hipotonia, não macroglossia verdadeira.'],
    causas: [
      { titulo: 'Desregulação do imprinting 11p15', mecanismo: 'Desequilíbrio IGF2/CDKN1C.', itens: ['Perda de metilação em KCNQ1OT1 (IC2, 50%)', 'Dissomia uniparental paterna 11p15 (20%)', 'Ganho de metilação em H19 (IC1)', 'Mutação do CDKN1C'] },
    ],
    referencias: ['Brioude F et al. Expert consensus document: clinical and molecular diagnosis, screening and management of Beckwith-Wiedemann syndrome. Nat Rev Endocrinol, 2018.'],
  },
  {
    slug: 'sindrome-de-cornelia-de-lange',
    nome: 'Síndrome de Cornelia de Lange',
    sinonimos: ['Sinofre com cílios longos', 'NIPBL', 'Síndrome de Brachmann-de Lange'],
    sistema: 'genetico',
    resumo: 'Criança pequena com sobrancelhas grossas e unidas, cílios longuíssimos, nariz curto com narinas para cima, filtro longo, boca em "carpa" com lábio superior fino e comissuras caídas, mãos e pés pequenos — às vezes com braços muito encurtados.',
    definicao: 'Síndrome das coesinopatias (NIPBL, SMC1A, SMC3, RAD21, HDAC8): sinofre com sobrancelhas arqueadas e bem definidas, cílios longos, ponte nasal deprimida com narinas antevertidas, filtro longo e liso, lábio superior fino com comissuras voltadas para baixo, micrognatia, orelhas de implantação baixa; restrição de crescimento pré e pós-natal, microcefalia; mãos e pés pequenos, clinodactilia do 5º dedo, polegares de implantação proximal, até deficiências graves dos membros superiores (oligodactilia, ausência de antebraço); hirsutismo, cutis marmorata; refluxo gastroesofágico grave, deficiência intelectual de grau variável, autoagressão.',
    comoProcurar: [
      { passo: 'Observe sobrancelhas, cílios, nariz, filtro e lábios.', detalhe: 'A combinação sinofre + filtro longo + lábio fino é muito sugestiva.' },
      { passo: 'Meça altura, peso e perímetro cefálico e examine mãos, polegares e antebraços.', detalhe: 'Radiografia dos membros superiores nas formas com redução.' },
      { passo: 'Pergunte por vômitos, irritabilidade e sono (refluxo grave).', detalhe: 'Painel genético das coesinopatias.' },
    ],
    mecanismo: 'O complexo coesina e seus reguladores organizam a cromatina e controlam a expressão de genes do desenvolvimento; a disfunção altera a transcrição de múltiplos genes durante a embriogênese — crescimento, face, membros e cérebro afetados juntos.',
    significado: 'O reconhecimento facial orienta o diagnóstico em uma doença com necessidades específicas: tratamento agressivo do refluxo (causa de irritabilidade e autoagressão), audição, visão, cardiopatia e suporte ao desenvolvimento.',
    armadilhas: ['Síndrome alcoólica fetal: filtro liso e lábio fino, mas sem sinofre e cílios longos.', 'Sinofre isolada familiar: sem outras alterações.', 'Síndrome de Coffin-Siris: hipertricose com hipoplasia da falange do 5º dedo.'],
    causas: [
      { titulo: 'Coesinopatias', mecanismo: 'Regulação da cromatina durante o desenvolvimento.', itens: ['NIPBL (60%, formas mais graves)', 'SMC1A e HDAC8 (ligadas ao X)', 'SMC3, RAD21'] },
    ],
    referencias: ['Kline AD et al. Diagnosis and management of Cornelia de Lange syndrome: first international consensus statement. Nat Rev Genet, 2018.'],
  },
  {
    slug: 'sindrome-de-poland',
    nome: 'Síndrome de Poland',
    sinonimos: ['Agenesia do peitoral maior', 'Sequência de Poland'],
    sistema: 'genetico',
    resumo: 'Um lado do tórax achatado, sem a prega axilar anterior, com o mamilo menor e mais alto, e a mão do mesmo lado pequena com dedos curtos e unidos — a interrupção de fluxo da artéria subclávia no embrião.',
    definicao: 'Anomalia congênita esporádica, unilateral (mais à direita, mais em homens): ausência da porção esternocostal do peitoral maior (perda da prega axilar anterior e achatamento do hemitórax), às vezes do peitoral menor, serrátil e outros músculos; hipoplasia ou ausência da mama e do mamilo, elevação do mamilo, escassez de gordura e pelos axilares; anomalias de costelas (ausência, depressão da parede, hérnia pulmonar); braquissindactilia ipsilateral (dedos médios curtos e unidos), hipoplasia da mão e do antebraço. Associação com Möbius (paralisia facial) em alguns casos.',
    comoProcurar: [
      { passo: 'Peça para colocar as mãos na cintura e empurrar: a prega peitoral some de um lado.', detalhe: 'Compare mamilos, mamas e pelos axilares.' },
      { passo: 'Palpe a parede torácica: costelas ausentes ou deprimidas, movimento paradoxal.', detalhe: 'Radiografia e TC de tórax nas formas com defeito ósseo.' },
      { passo: 'Examine a mão do mesmo lado: dedos curtos e sindactilia.', detalhe: 'Examine a face (Möbius).' },
    ],
    mecanismo: 'A hipótese mais aceita é a interrupção do suprimento sanguíneo da artéria subclávia ou de seus ramos (torácica interna, vertebral) por volta da 6ª semana, quando o membro superior e a parede torácica se formam — os territórios hipoperfundidos ficam hipoplásicos do mesmo lado.',
    significado: 'Majoritariamente estético-funcional, mas a hipoplasia mamária na adolescente e os defeitos costais exigem reconstrução; a mão pode precisar de cirurgia para função. Reconhecer evita investigações desnecessárias.',
    armadilhas: ['Assimetria mamária da puberdade: músculo peitoral normal.', 'Sequela de cirurgia ou radioterapia torácica na infância.', 'Escoliose com assimetria de tórax: peitoral presente.'],
    causas: [
      { titulo: 'Disrupção vascular embrionária', mecanismo: 'Hipoperfusão da subclávia.', itens: ['Esporádica (maioria)', 'Associação com Möbius', 'Raros casos familiares'] },
    ],
    referencias: ['Fokin AA, Robicsek F. Poland\'s syndrome revisited. Ann Thorac Surg, 2002.'],
  },
  {
    slug: 'incontinentia-pigmenti',
    nome: 'Incontinentia pigmenti',
    sinonimos: ['Síndrome de Bloch-Sulzberger', 'Linhas de Blaschko', 'IKBKG/NEMO'],
    sistema: 'genetico',
    resumo: 'Menina recém-nascida com vesículas em faixas lineares que seguem trajetos curvos e em S nos membros e no tronco, que viram verrugas, depois manchas marrons em redemoinho e, no adulto, faixas pálidas sem pelos — as linhas de Blaschko contando o mosaicismo.',
    definicao: 'Genodermatose dominante ligada ao X (IKBKG/NEMO), letal na maioria dos fetos masculinos: lesões cutâneas em quatro estágios que seguem as linhas de Blaschko — (1) vesiculobolhoso, nas primeiras semanas, com eosinofilia; (2) verrucoso, lesões hiperceratósicas lineares, meses; (3) hiperpigmentado, faixas e redemoinhos castanho-acinzentados no tronco, anos; (4) atrófico-hipopigmentado, faixas pálidas sem pelos e sem suor nas pernas do adulto; alopecia cicatricial do vértice, unhas distróficas, dentes cônicos e ausentes (hipodontia), retinopatia vascular (descolamento, cegueira) e alterações neurológicas (convulsões neonatais, AVC).',
    comoProcurar: [
      { passo: 'Observe o padrão: faixas lineares curvas, em S e em V no tronco, que não seguem dermátomos.', detalhe: 'O padrão de Blaschko é a pista de mosaicismo.' },
      { passo: 'Examine dentes (cônicos, ausentes), unhas e couro cabeludo; pergunte pela mãe e pelas avós.', detalhe: 'Mães afetadas podem ter apenas dentes alterados e faixas pálidas nas pernas.' },
      { passo: 'Fundo de olho precoce e seriado e avaliação neurológica.', detalhe: 'A retinopatia é tratável com laser se detectada cedo.' },
    ],
    mecanismo: 'O NEMO ativa o NF-κB, que protege as células da apoptose induzida por TNF; em mulheres, a inativação aleatória do X cria dois clones de células — as que expressam o X mutado sofrem apoptose e inflamação ao longo dos trajetos de migração embrionária (as linhas de Blaschko), depois são substituídas.',
    significado: 'O padrão cutâneo neonatal é o sinal que leva ao exame de retina e ao acompanhamento neurológico — os determinantes do prognóstico. Também explica abortos masculinos de repetição na família.',
    armadilhas: ['Herpes neonatal e impetigo bolhoso: vesículas agrupadas, não lineares — mas excluir herpes é obrigatório.', 'Nevo epidérmico linear: verrucoso desde o nascimento, sem evolução em estágios.', 'Hipomelanose de Ito: faixas claras em Blaschko, sem fases inflamatórias.'],
    causas: [
      { titulo: 'IKBKG/NEMO', mecanismo: 'Mosaicismo funcional por inativação do X.', itens: ['Deleção recorrente dos éxons 4 a 10 (80%)', 'Herança dominante ligada ao X'] },
    ],
    referencias: ['Fusco F et al. Clinical diagnosis of incontinentia pigmenti in a cohort of male and female patients. J Am Acad Dermatol, 2014.'],
  },
  {
    slug: 'sindrome-do-miado-do-gato',
    nome: 'Síndrome do miado do gato (cri-du-chat)',
    sinonimos: ['Deleção 5p', 'Cri-du-chat', 'Síndrome de Lejeune'],
    sistema: 'genetico',
    resumo: 'Recém-nascido pequeno com choro agudo e fino como o miado de um gato, face arredondada, olhos afastados com epicanto e fendas oblíquas para baixo, e microcefalia — o choro é o diagnóstico ao lado do berço.',
    definicao: 'Síndrome da deleção terminal do braço curto do cromossomo 5 (5p15): choro monocórdio agudo semelhante a miado nas primeiras semanas (por hipoplasia e malformação da laringe), baixo peso, microcefalia, face redonda (lua) no lactente que se alonga com a idade, hipertelorismo, epicanto, fendas palpebrais oblíquas para baixo, ponte nasal larga, micrognatia, orelhas de implantação baixa, prega palmar única; hipotonia, deficiência intelectual grave com atraso de fala, comportamentos repetitivos e hiperatividade; cardiopatias em parte dos casos.',
    comoProcurar: [
      { passo: 'Ouça o choro do recém-nascido: agudo, fino, contínuo.', detalhe: 'Tende a desaparecer após o primeiro ano.' },
      { passo: 'Observe a face, meça o perímetro cefálico e o peso.', detalhe: 'Examine palmas (prega única) e tônus.' },
      { passo: 'Cariótipo ou microarranjo confirmam; cariótipo dos pais quando há translocação.', detalhe: 'Ecocardiograma.' },
    ],
    mecanismo: 'A perda de genes da região 5p15.2 (CTNND2 relacionado a cognição, TERT) causa o fenótipo neurológico e facial; a região 5p15.3 contém genes relacionados ao desenvolvimento laríngeo que explicam o choro característico.',
    significado: 'O choro permite um diagnóstico clínico precoce, orienta intervenção de linguagem e desenvolvimento e o aconselhamento — em 10 a 15% há translocação balanceada em um dos pais, com risco real de recorrência.',
    armadilhas: ['Laringomalácia: estridor, não choro miado, com desenvolvimento normal.', 'Choro fraco da hipotonia (Prader-Willi, SMA): fraco, não agudo.', 'Trissomia 21: hipotonia com face plana, sem choro característico.'],
    causas: [
      { titulo: 'Deleção 5p', mecanismo: 'Haploinsuficiência de genes de 5p15.', itens: ['Deleção terminal de novo (80 a 90%)', 'Translocação desbalanceada de genitor portador'] },
    ],
    referencias: ['Cerruti Mainardi P. Cri du chat syndrome. Orphanet J Rare Dis, 2006.'],
  },
  {
    slug: 'esplenomegalia-de-gaucher',
    nome: 'Esplenomegalia maciça de Gaucher',
    sinonimos: ['Doença de Gaucher', 'Deficiência de glicocerebrosidase', 'Fêmur em frasco de Erlenmeyer'],
    sistema: 'genetico',
    resumo: 'Baço que ultrapassa a cicatriz umbilical e chega à fossa ilíaca, fígado grande, criança ou adulto jovem pálido, com equimoses fáceis, dor óssea em crises e fraturas — sem febre, sem linfonodos e sem hipertensão portal.',
    definicao: 'Doença lisossômica autossômica recessiva (GBA1, deficiência de glicocerebrosidase) com acúmulo de glicocerebrosídeo nos macrófagos (células de Gaucher): esplenomegalia maciça (às vezes > 20 vezes o normal), hepatomegalia, pancitopenia (anemia, plaquetopenia com equimoses e sangramentos), doença óssea (dor, crises ósseas com febre e dor intensa, necrose avascular da cabeça femoral, fraturas patológicas, deformidade em frasco de Erlenmeyer do fêmur distal), retardo de crescimento; formas neuronopáticas (tipos 2 e 3) com paralisia do olhar horizontal e convulsões. Mais comum em judeus asquenazes; associação com parkinsonismo em portadores.',
    comoProcurar: [
      { passo: 'Palpe o baço partindo da fossa ilíaca direita em direção ao hipocôndrio esquerdo.', detalhe: 'Palpar do rebordo para baixo deixa passar o polo inferior de um baço gigante.' },
      { passo: 'Procure palidez, equimoses, dor óssea e limitação dos quadris.', detalhe: 'Movimentos oculares sacádicos horizontais nas formas neuronopáticas.' },
      { passo: 'Pergunte pela origem étnica e família.', detalhe: 'Dosagem da atividade da glicocerebrosidase e quitotriosidase.' },
    ],
    mecanismo: 'Os macrófagos fagocitam membranas de células senescentes e, sem a enzima, acumulam glicocerebrosídeo; tornam-se células de Gaucher que infiltram baço, fígado e medula óssea, produzem citocinas e substituem a medula — hiperesplenismo, citopenias e osteonecrose.',
    significado: 'Uma esplenomegalia gigante afebril sem hipertensão portal nem linfonodos, com citopenias, deve lembrar Gaucher antes de leucemia; a reposição enzimática ou a redução de substrato reverte vísceras e citopenias e previne a doença óssea.',
    armadilhas: ['Leucemia mieloide crônica e mielofibrose: esplenomegalia maciça com leucocitose ou dacriócitos.', 'Esquistossomose hepatoesplênica: baço grande com hipertensão portal e varizes.', 'Calazar: febre, emagrecimento e pancitopenia em área endêmica.'],
    causas: [
      { titulo: 'Deficiência de glicocerebrosidase', mecanismo: 'Acúmulo em macrófagos.', itens: ['Tipo 1 (não neuronopática, mais comum)', 'Tipo 2 (neuronopática aguda infantil)', 'Tipo 3 (neuronopática crônica)'] },
    ],
    referencias: ['Stirnemann J et al. A review of Gaucher disease pathophysiology, clinical presentation and treatments. Int J Mol Sci, 2017.'],
  },
  {
    slug: 'ectopia-lentis-homocistinuria',
    nome: 'Ectopia do cristalino da homocistinúria',
    sinonimos: ['Homocistinúria clássica', 'Deficiência de cistationina beta-sintase', 'Luxação do cristalino para baixo'],
    sistema: 'genetico',
    resumo: 'Jovem alto e marfanoide, com cristalino deslocado para baixo e íris que treme, deficiência intelectual, osteoporose e uma trombose venosa ou AVC antes dos 30 anos — o "Marfan" que coagula.',
    definicao: 'Erro inato do metabolismo da metionina (CBS, autossômica recessiva) com homocisteína plasmática muito elevada: ectopia do cristalino inferonasal (em Marfan é superotemporal) com iridodonese e miopia alta, habitus marfanoide com escoliose e pectus, osteoporose precoce, deficiência intelectual e alterações psiquiátricas em parte dos casos, pele clara, rubor malar, livedo; tromboembolismo venoso e arterial (TVP, TEP, trombose de seios venosos, AVC, infarto) em jovens, com risco anestésico e pós-operatório alto.',
    comoProcurar: [
      { passo: 'Observe a íris ao mover o olho (iridodonese) e peça lâmpada de fenda para a direção do deslocamento.', detalhe: 'Para baixo e medial = homocistinúria; para cima e lateral = Marfan.' },
      { passo: 'Avalie hábito, coluna e cognição; pergunte por tromboses pessoais e familiares.', detalhe: 'Trombose em jovem sem causa merece homocisteína.' },
      { passo: 'Dose a homocisteína total e aminoácidos plasmáticos.', detalhe: 'Parte responde à piridoxina (vitamina B6).' },
    ],
    mecanismo: 'Sem cistationina beta-sintase, a homocisteína se acumula: interfere nas ligações cruzadas do colágeno e da fibrilina (ligamento do cristalino frágil, ossos e hábito marfanoide) e lesa o endotélio, ativando a coagulação — trombose arterial e venosa.',
    significado: 'Diferenciar de Marfan muda tudo: aqui o risco é trombose, e o tratamento (piridoxina, dieta restrita em metionina, betaína, folato e B12) previne complicações. A triagem neonatal detecta parte dos casos.',
    armadilhas: ['Síndrome de Marfan: ectopia para cima, inteligência normal, aorta dilatada, sem trombose.', 'Hiper-homocisteinemia leve adquirida (B12, folato, insuficiência renal): sem ectopia.', 'Luxação traumática do cristalino: unilateral, com história de trauma.'],
    causas: [
      { titulo: 'Metabolismo da metionina', mecanismo: 'Acúmulo de homocisteína.', itens: ['Deficiência de CBS (clássica)', 'Defeitos da remetilação (MTHFR grave, cobalamina C)'] },
    ],
    referencias: ['Morris AA et al. Guidelines for the diagnosis and management of cystathionine beta-synthase deficiency. J Inherit Metab Dis, 2017.'],
  },
]
