import type { Sinal } from './esquemas'

/**
 * Síndromes genéticas, parte 1 — o que o exame físico enxerga antes do
 * cariótipo: fácies, hábito, pele, olhos e mãos de 15 doenças hereditárias.
 */
export const SINAIS_GENETICAS_1: Sinal[] = [
  {
    slug: 'habito-marfanoide',
    nome: 'Hábito marfanoide',
    sinonimos: ['Síndrome de Marfan', 'Aracnodactilia', 'Sinal do punho (Walker-Murdoch)', 'Sinal do polegar (Steinberg)'],
    sistema: 'genetico',
    resumo: 'Alto, magro, com braços e dedos longos demais, peito escavado ou em quilha, pés planos e cristalino deslocado para cima — e uma aorta que dilata em silêncio. Os sinais do punho e do polegar transformam a impressão em exame.',
    definicao: 'Conjunto de achados da síndrome de Marfan (fibrilina-1, FBN1, autossômica dominante): estatura alta com envergadura maior que a altura (razão > 1,05) e segmento inferior longo, aracnodactilia com sinal do punho (polegar e mínimo se sobrepõem ao envolver o punho oposto) e do polegar (a falange distal do polegar ultrapassa a borda ulnar da mão fechada), pectus excavatum ou carinatum, escoliose, pé plano, hipermobilidade articular, estrias atróficas sem ganho de peso, palato ogival com dentes apinhados, ectopia do cristalino superotemporal (iridodonese), miopia alta; dilatação da raiz da aorta e prolapso mitral. Critérios de Ghent revisados combinam aorta, ectopia do cristalino, história familiar e escore sistêmico.',
    comoProcurar: [
      { passo: 'Peça para envolver o punho oposto com o polegar e o mínimo, e para fechar a mão sobre o polegar.', detalhe: 'Os dois sinais positivos juntos têm alta especificidade para aracnodactilia.' },
      { passo: 'Meça envergadura e altura; olhe o tórax, a coluna em flexão (Adams), os pés e a boca.', detalhe: 'Some o escore sistêmico de Ghent.' },
      { passo: 'Procure iridodonese (a íris treme ao mover o olho) e ausculte o sopro de prolapso mitral ou de insuficiência aórtica.', detalhe: 'Ecocardiograma com medida da raiz da aorta e exame de lâmpada de fenda em todo suspeito.' },
    ],
    mecanismo: 'A fibrilina-1 é o arcabouço das microfibrilas elásticas e sequestra o TGF-β na matriz; mutada, deixa o tecido conjuntivo frouxo e o TGF-β livre sinalizando em excesso — o crescimento longitudinal dos ossos, a frouxidão ligamentar, a dilatação progressiva da aorta e a fragilidade do ligamento suspensor do cristalino vêm do mesmo defeito.',
    significado: 'Reconhecer o hábito salva vidas: a dissecção da aorta é a causa de morte, e é prevenível com betabloqueador ou losartana, seguimento ecocardiográfico e cirurgia eletiva da raiz aórtica. Um atleta alto de dedos longos com sopro diastólico não é só alto.',
    armadilhas: ['Homocistinúria: marfanoide com ectopia do cristalino para baixo, deficiência intelectual e trombose.', 'Síndrome de Loeys-Dietz: aorta que disseca mais cedo, com úvula bífida e hipertelorismo.', 'Pessoas altas e magras saudáveis: sinais do punho e do polegar podem ser positivos isoladamente — o que define é o conjunto e a aorta.'],
    causas: [
      { titulo: 'Fibrilinopatias e afins', mecanismo: 'Tecido conjuntivo frouxo e TGF-β em excesso.', itens: ['Síndrome de Marfan (FBN1)', 'Loeys-Dietz (TGFBR1/2)', 'Homocistinúria clássica (CBS)', 'Ehlers-Danlos vascular (diferencial)'] },
    ],
    referencias: ['Loeys BL et al. The revised Ghent nosology for the Marfan syndrome. J Med Genet, 2010.'],
  },
  {
    slug: 'facies-de-williams',
    nome: 'Fácies de Williams (fácies de elfo)',
    sinonimos: ['Síndrome de Williams-Beuren', 'Deleção 7q11.23', 'Fácies de duende'],
    sistema: 'genetico',
    resumo: 'Fronte larga, edema periorbitário, íris com padrão estrelado, nariz curto de ponta arrebitada, filtro longo, lábios cheios e boca larga — numa criança extremamente sociável, com hipercalcemia e sopro de estenose aórtica supravalvar.',
    definicao: 'Fenótipo da síndrome de Williams-Beuren (microdeleção 7q11.23 que inclui o gene da elastina): fronte larga com estreitamento bitemporal, plenitude periorbitária, íris estrelada (padrão rendilhado branco na íris azul), ponte nasal baixa com nariz curto e antevertido, bochechas cheias, filtro longo, lábios grossos, boca larga, dentes pequenos e espaçados; baixa estatura, voz rouca; estenose aórtica supravalvar e estenose de artérias pulmonares; hipercalcemia na infância; deficiência intelectual leve a moderada com personalidade hipersociável, loquaz e empática, e boa habilidade musical.',
    comoProcurar: [
      { passo: 'Olhe a face de perto: periorbitário cheio, nariz curto antevertido, filtro longo, lábios grossos.', detalhe: 'A íris estrelada aparece melhor em olhos claros com lanterna oblíqua.' },
      { passo: 'Ausculte o foco aórtico e a base: sopro sistólico supravalvar e sopros pulmonares periféricos.', detalhe: 'Meça a pressão nos quatro membros — hipertensão por estenose de artérias renais.' },
      { passo: 'Converse com a criança: loquacidade, familiaridade excessiva com estranhos.', detalhe: 'FISH ou microarranjo confirmam; cálcio sérico e ecocardiograma.' },
    ],
    mecanismo: 'A haploinsuficiência da elastina explica a arteriopatia (espessamento da média com estenoses, sobretudo supravalvar aórtica), a voz rouca e o envelhecimento precoce da pele; os outros genes contíguos da deleção (LIMK1, GTF2I) influenciam cognição visuoespacial e comportamento social.',
    significado: 'O diagnóstico clínico pela face permite rastrear a estenose supravalvar, a hipercalcemia (evitar suplementos de vitamina D) e a hipertensão, e orienta a família sobre o perfil cognitivo — fraqueza visuoespacial com linguagem relativamente preservada.',
    armadilhas: ['Síndrome alcoólica fetal: filtro liso e lábio superior fino — o oposto do filtro longo e lábios cheios.', 'Noonan: hipertelorismo, ptose e estenose valvar pulmonar.', 'Íris estrelada é sutil em olhos escuros — não descarte pela ausência.'],
    causas: [
      { titulo: 'Microdeleção cromossômica', mecanismo: 'Perda de genes contíguos incluindo ELN.', itens: ['Deleção 7q11.23 de novo (maioria)', 'Herança autossômica dominante quando o genitor é afetado'] },
    ],
    referencias: ['Pober BR. Williams-Beuren syndrome. N Engl J Med, 2010.'],
  },
  {
    slug: 'sindrome-do-x-fragil',
    nome: 'Síndrome do X frágil',
    sinonimos: ['Síndrome de Martin-Bell', 'FMR1', 'Macro-orquidismo'],
    sistema: 'genetico',
    resumo: 'Menino com atraso de linguagem e comportamento autista, face alongada, fronte e mandíbula proeminentes, orelhas grandes e em abano, articulações frouxas e, após a puberdade, testículos grandes — a causa herdada mais comum de deficiência intelectual.',
    definicao: 'Fenótipo da expansão de trincas CGG (> 200) no gene FMR1 (Xq27.3): nos meninos, deficiência intelectual moderada, atraso de fala, hiperatividade, contato visual pobre, estereotipias de mãos (morder, abanar), timidez social; face alongada e estreita, fronte ampla, mandíbula proeminente, orelhas grandes, proeminentes ou em abano, palato alto, hiperextensibilidade das metacarpofalangianas, pele macia, pés planos, prolapso mitral; macro-orquidismo pós-puberal (volume > 25 mL). Meninas têm fenótipo mais leve e variável. Pré-mutação (55 a 200 repetições) causa insuficiência ovariana precoce e síndrome de tremor-ataxia no idoso (FXTAS).',
    comoProcurar: [
      { passo: 'Observe face, orelhas e mandíbula; palpe as MCF (hiperextensão) e a textura da pele.', detalhe: 'Em pré-púberes a face pode ser pouco característica — o comportamento pesa mais.' },
      { passo: 'Após a puberdade, meça os testículos com orquidômetro.', detalhe: 'Macro-orquidismo com deficiência intelectual é quase patognomônico.' },
      { passo: 'Pergunte pela família: tios maternos com deficiência, menopausa precoce, avô com tremor e ataxia.', detalhe: 'O teste molecular do FMR1 faz parte da investigação de todo autismo e deficiência intelectual sem causa.' },
    ],
    mecanismo: 'A expansão CGG metila e silencia o FMR1; sem a proteína FMRP, que regula a tradução local nas sinapses, a plasticidade sináptica e a poda dendrítica falham (espinhas longas e imaturas). A instabilidade da repetição explica a antecipação ao passar pela mãe.',
    significado: 'Diagnóstico com impacto familiar enorme: identificar portadoras de pré-mutação (risco de ter filhos afetados, insuficiência ovariana) e avôs com FXTAS. Muda o aconselhamento reprodutivo e dá acesso a intervenções educacionais precoces.',
    armadilhas: ['Autismo idiopático: sem orelhas grandes, sem macro-orquidismo — mas o teste do FMR1 é indicado de qualquer modo.', 'Sotos: macrocefalia e crescimento excessivo, sem macro-orquidismo.', 'Cariótipo convencional não detecta — é preciso teste molecular específico.'],
    causas: [
      { titulo: 'Expansão de trincas', mecanismo: 'Silenciamento do FMR1.', itens: ['Mutação completa (> 200 CGG)', 'Mosaicismo de tamanho ou de metilação', 'Pré-mutação (55 a 200) — FXTAS e insuficiência ovariana'] },
    ],
    referencias: ['Hagerman RJ et al. Fragile X syndrome. Nat Rev Dis Primers, 2017.'],
  },
  {
    slug: 'sindrome-de-angelman',
    nome: 'Síndrome de Angelman',
    sinonimos: ['Fantoche feliz', 'UBE3A', 'Deleção materna 15q11-q13'],
    sistema: 'genetico',
    resumo: 'Criança com atraso grave, ausência de fala, riso frequente e fácil com excitabilidade, marcha atáxica com braços erguidos e dobrados, microcefalia adquirida e crises epilépticas — o polo materno do imprinting do cromossomo 15.',
    definicao: 'Fenótipo da perda da expressão materna do UBE3A (deleção materna 15q11-q13, dissomia uniparental paterna, defeito de imprinting ou mutação do UBE3A): atraso grave do desenvolvimento, fala ausente ou mínima com compreensão melhor que a expressão, comportamento alegre com riso paroxístico, excitabilidade, bater de mãos, fascínio por água; ataxia de marcha com base alargada e braços elevados e fletidos (marcha de marionete), tremor; microcefalia adquirida até os 2 anos, occipício achatado, boca larga com língua protrusa, prognatismo, dentes espaçados, sialorreia, hipopigmentação na deleção; epilepsia em 80% com EEG característico.',
    comoProcurar: [
      { passo: 'Observe o comportamento: riso fácil e fora de contexto, alegria constante, mãos que abanam.', detalhe: 'A fala ausente contrasta com a boa interação.' },
      { passo: 'Observe a marcha: rígida, atáxica, com braços erguidos e cotovelos fletidos.', detalhe: 'Meça o perímetro cefálico e compare com a curva.' },
      { passo: 'Pergunte por crises e por distúrbio do sono.', detalhe: 'Teste de metilação do 15q11-q13 detecta 80%; se normal, sequenciamento do UBE3A.' },
    ],
    mecanismo: 'No neurônio, só o alelo materno do UBE3A é expresso (o paterno é silenciado por imprinting); sem ele, falta uma ubiquitina-ligase que regula proteínas sinápticas, e a maturação dos circuitos corticais e cerebelares falha.',
    significado: 'Diagnóstico que explica uma epilepsia de difícil controle e um atraso grave; orienta o risco de recorrência (quase nulo na deleção de novo, até 50% na mutação materna herdada) e o manejo do sono, das crises e da comunicação alternativa.',
    armadilhas: ['Prader-Willi: mesma região, alelo paterno ausente — hipotonia neonatal e hiperfagia, não riso e ataxia.', 'Síndrome de Rett: menina com regressão e estereotipia de lavar as mãos.', 'Paralisia cerebral atáxica: sem o comportamento alegre característico.'],
    causas: [
      { titulo: 'Perda do UBE3A materno', mecanismo: 'Imprinting genômico.', itens: ['Deleção materna 15q11-q13 (70%)', 'Dissomia uniparental paterna', 'Defeito do centro de imprinting', 'Mutação do UBE3A'] },
    ],
    referencias: ['Buiting K et al. Angelman syndrome — insights into a rare neurogenetic disorder. Nat Rev Neurol, 2016.'],
  },
  {
    slug: 'sindrome-de-rett',
    nome: 'Síndrome de Rett — as mãos que lavam',
    sinonimos: ['MECP2', 'Regressão com estereotipias manuais'],
    sistema: 'genetico',
    resumo: 'Menina que se desenvolveu normalmente até os 6 a 18 meses e então perdeu a fala e o uso das mãos, que passam a se torcer, bater ou "lavar" sem parar diante do corpo — com desaceleração do crescimento da cabeça e episódios de hiperventilação.',
    definicao: 'Doença do neurodesenvolvimento ligada ao X (mutações do MECP2), quase exclusiva de meninas: período de desenvolvimento aparentemente normal, depois regressão entre 6 e 18 meses com perda da fala adquirida e do uso funcional das mãos, estereotipias manuais na linha média (torcer, lavar, bater palmas, levar à boca), marcha dispráxica ou ausente, desaceleração do perímetro cefálico, bruxismo, alterações respiratórias em vigília (hiperventilação, apneias), escoliose, mãos e pés frios e pequenos, epilepsia, e depois estabilização com melhora do contato visual ("olhar intenso").',
    comoProcurar: [
      { passo: 'Observe as mãos em repouso: movimento repetitivo na linha média, sem uso funcional.', detalhe: 'Peça para pegar um objeto: ela não consegue, apesar de olhar para ele.' },
      { passo: 'Reconstrua a curva do desenvolvimento e do perímetro cefálico com a família.', detalhe: 'O marco é a perda — ela já falou palavras e pegou objetos.' },
      { passo: 'Observe a respiração em vigília, a coluna e as extremidades.', detalhe: 'Sequenciamento do MECP2 confirma.' },
    ],
    mecanismo: 'A proteína MeCP2 regula a expressão de genes neuronais ligando-se ao DNA metilado; sem ela, os neurônios não mantêm a maturação sináptica após o primeiro ano, quando a demanda por refinamento dos circuitos aumenta — daí o desenvolvimento inicial normal seguido de regressão.',
    significado: 'O diagnóstico explica a regressão e evita investigações desnecessárias; exige vigilância de QT longo, escoliose, epilepsia e nutrição. O trofinetide é o primeiro tratamento aprovado.',
    armadilhas: ['Autismo com regressão: sem perda do uso das mãos nem desaceleração do perímetro cefálico.', 'Angelman: riso fácil, ataxia e ausência de período normal.', 'Meninos com MECP2: encefalopatia neonatal grave — o fenótipo clássico é feminino.'],
    causas: [
      { titulo: 'MECP2', mecanismo: 'Desregulação da expressão gênica neuronal.', itens: ['Mutação de novo do MECP2 (> 95%)', 'Formas atípicas: CDKL5 (início precoce com epilepsia), FOXG1 (congênita)'] },
    ],
    referencias: ['Neul JL et al. Rett syndrome: revised diagnostic criteria and nomenclature. Ann Neurol, 2010.'],
  },
  {
    slug: 'telangiectasia-hemorragica-hereditaria',
    nome: 'Telangiectasias de Osler-Weber-Rendu',
    sinonimos: ['Telangiectasia hemorrágica hereditária', 'Doença de Rendu-Osler-Weber', 'THH'],
    sistema: 'genetico',
    resumo: 'Pontos vermelho-violáceos que empalidecem à pressão nos lábios, na língua, na face e nas pontas dos dedos, num adulto com epistaxes de repetição desde a infância e anemia ferropriva — e um pai ou mãe com a mesma história.',
    definicao: 'Doença vascular autossômica dominante (ENG, ACVRL1, SMAD4) com malformações de pequenos e grandes vasos: telangiectasias múltiplas de 1 a 3 mm, puntiformes ou aracneiformes, na mucosa labial, língua, palato, face, orelhas e polpas digitais, que empalidecem à vitropressão e aumentam com a idade; epistaxes espontâneas e recorrentes (o primeiro sintoma, na infância); sangramento digestivo crônico; malformações arteriovenosas pulmonares (cianose, baqueteamento, AVC e abscesso cerebral por embolia paradoxal), cerebrais e hepáticas. Critérios de Curaçao: epistaxes, telangiectasias, lesão visceral, parente de primeiro grau.',
    comoProcurar: [
      { passo: 'Examine lábios, língua (bordas e ponta), palato e polpas dos dedos com boa luz.', detalhe: 'Vitropressão: empalidecem, ao contrário de petéquias.' },
      { passo: 'Pergunte por epistaxes desde a infância, melena, anemia e história familiar.', detalhe: 'Três de quatro critérios de Curaçao = diagnóstico definitivo.' },
      { passo: 'Procure cianose, baqueteamento e sopro pulmonar (MAV), e ausculte o fígado.', detalhe: 'Ecocardiograma com microbolhas rastreia MAV pulmonar em todos.' },
    ],
    mecanismo: 'As mutações comprometem a sinalização do TGF-β/BMP9 no endotélio; os vasos formam conexões diretas arteríola-vênula sem capilar interposto, com paredes frágeis que sangram ao menor trauma — nas mucosas, telangiectasias; nos órgãos, MAV maiores.',
    significado: 'As telangiectasias visíveis são a porta para rastrear o que mata: MAV pulmonar (embolização previne AVC e abscesso cerebral) e cerebral. O tratamento da anemia e das epistaxes (laser, bevacizumabe) transforma a qualidade de vida.',
    armadilhas: ['Síndrome CREST: telangiectasias em placa nas mãos e face com esclerodactilia e calcinose.', 'Angiomas rubi e aranhas vasculares da cirrose: não acometem mucosas labial e lingual.', 'Peutz-Jeghers: máculas pigmentadas, que não empalidecem.'],
    causas: [
      { titulo: 'Genes da via TGF-β/BMP9', mecanismo: 'Angiogênese anômala.', itens: ['THH tipo 1 (ENG) — mais MAV pulmonar e cerebral', 'THH tipo 2 (ACVRL1) — mais MAV hepática', 'SMAD4 — THH com polipose juvenil'] },
    ],
    referencias: ['Faughnan ME et al. Second international guidelines for the diagnosis and management of hereditary hemorrhagic telangiectasia. Ann Intern Med, 2020.'],
  },
  {
    slug: 'maculas-de-peutz-jeghers',
    nome: 'Máculas de Peutz-Jeghers',
    sinonimos: ['Síndrome de Peutz-Jeghers', 'Lentiginose periorificial', 'STK11'],
    sistema: 'genetico',
    resumo: 'Manchas castanho-escuras de 1 a 5 mm nos lábios — sobretudo o inferior —, na mucosa jugal, ao redor da boca e dos olhos e nos dedos, surgidas na infância, num jovem com cólicas por intussuscepção de pólipos hamartomatosos.',
    definicao: 'Síndrome autossômica dominante (STK11/LKB1) com máculas melanóticas mucocutâneas — castanho-escuras a azuladas, de 1 a 5 mm, nos lábios (especialmente o inferior), mucosa oral e gengiva, região perioral, perinasal e periorbitária, palmas, plantas e dedos — que aparecem na infância e podem esmaecer na pele (persistem na mucosa jugal); pólipos hamartomatosos em todo o trato gastrointestinal (sobretudo delgado), com intussuscepção, sangramento e anemia; risco elevado de câncer gastrointestinal, pancreático, mamário, ovariano (tumor de cordão sexual), testicular e cervical.',
    comoProcurar: [
      { passo: 'Examine lábios, mucosa jugal (onde persistem na idade adulta), palmas e dedos.', detalhe: 'Efélides não aparecem na mucosa oral — a mucosa é a pista.' },
      { passo: 'Pergunte por dor abdominal em cólica, obstrução, sangramento digestivo e cirurgias na infância.', detalhe: 'Intussuscepção de repetição em criança é Peutz-Jeghers até prova contrária.' },
      { passo: 'Pergunte por história familiar de pólipos e cânceres precoces.', detalhe: 'Teste do STK11 e programa de rastreamento (endoscopia, cápsula, mama, pâncreas, gônadas).' },
    ],
    mecanismo: 'A perda do STK11, um supressor tumoral que regula o mTOR e a polaridade celular, causa hamartomas com arborização de músculo liso no intestino e acúmulo de melanina nos melanócitos basais das mucosas; o mesmo defeito eleva o risco de carcinoma em múltiplos órgãos.',
    significado: 'As máculas labiais são um sinal visível de uma síndrome de predisposição ao câncer: o diagnóstico inicia o rastreamento endoscópico desde a infância (polipectomia preventiva) e oncológico ao longo da vida, e o aconselhamento familiar.',
    armadilhas: ['Efélides e lentigos solares: não acometem a mucosa oral.', 'Doença de Addison: hiperpigmentação difusa de mucosa, sem máculas discretas.', 'Síndrome de Laugier-Hunziker: máculas orais e ungueais sem pólipos.'],
    causas: [
      { titulo: 'STK11/LKB1', mecanismo: 'Supressor tumoral e polaridade celular.', itens: ['Mutação germinativa herdada (autossômica dominante)', 'Mutação de novo (até metade dos casos)'] },
    ],
    referencias: ['Beggs AD et al. Peutz-Jeghers syndrome: a systematic review and recommendations for management. Gut, 2010.'],
  },
  {
    slug: 'albinismo-oculocutaneo',
    nome: 'Albinismo oculocutâneo',
    sinonimos: ['Albinismo', 'Hipopigmentação congênita', 'TYR'],
    sistema: 'genetico',
    resumo: 'Pele muito clara que não bronzeia e queima, cabelos brancos ou louro-palha, íris translúcidas acinzentadas que deixam passar a luz, nistagmo e fotofobia — e, no adulto sem proteção, ceratoses e carcinomas nas áreas expostas.',
    definicao: 'Grupo de doenças autossômicas recessivas da síntese de melanina (TYR, OCA2, TYRP1, SLC45A2): hipopigmentação difusa da pele (branca ou rosada, sem bronzear, com queimaduras fáceis, efélides e lentigos), cabelos e pelos brancos, amarelados ou castanho-claros, íris azul-acinzentada translúcida à transiluminação; hipoplasia foveal, nistagmo congênito, estrabismo, fotofobia, baixa acuidade visual e decussação anômala das fibras ópticas; na pele exposta ao sol, ceratoses actínicas e carcinomas espinocelulares precoces. No Brasil e na África subsaariana, grande impacto social e dermatológico.',
    comoProcurar: [
      { passo: 'Observe pele, cabelos e sobrancelhas; examine os olhos com lanterna — a íris transilumina.', detalhe: 'Nistagmo e fotofobia desde os primeiros meses.' },
      { passo: 'Inspecione as áreas fotoexpostas: face, orelhas, ombros, dorso das mãos.', detalhe: 'Placas descamativas e úlceras que não cicatrizam são carcinoma até biópsia.' },
      { passo: 'Pergunte por sangramentos e infecções de repetição.', detalhe: 'Hermansky-Pudlak (sangramento, fibrose pulmonar) e Chédiak-Higashi (infecções) têm albinismo associado.' },
    ],
    mecanismo: 'A tirosinase e as proteínas associadas convertem tirosina em melanina nos melanossomos; com a via bloqueada, os melanócitos existem mas não pigmentam — a pele perde proteção UV, e a falta de melanina no epitélio pigmentar da retina desorganiza o desenvolvimento da fóvea e das vias ópticas.',
    significado: 'Exige fotoproteção rigorosa desde o nascimento e vigilância dermatológica (o carcinoma cutâneo é a principal causa de morte evitável), correção visual precoce e apoio escolar. As formas sindrômicas precisam ser excluídas.',
    armadilhas: ['Vitiligo: manchas despigmentadas adquiridas e localizadas, olhos normais.', 'Piebaldismo: mecha branca e placas despigmentadas congênitas e estáveis, sem alterações oculares.', 'Fenilcetonúria não tratada: hipopigmentação com deficiência intelectual e odor característico.'],
    causas: [
      { titulo: 'Síntese de melanina', mecanismo: 'Melanócitos presentes, sem pigmento.', itens: ['OCA1 (TYR)', 'OCA2 (P — mais comum na África)', 'OCA3 (TYRP1), OCA4 (SLC45A2)', 'Sindrômicos: Hermansky-Pudlak, Chédiak-Higashi'] },
    ],
    referencias: ['Grønskov K et al. Oculocutaneous albinism. Orphanet J Rare Dis, 2007.'],
  },
  {
    slug: 'sindrome-de-waardenburg',
    nome: 'Síndrome de Waardenburg',
    sinonimos: ['Mecha branca frontal', 'Distopia cantorum', 'Heterocromia com surdez'],
    sistema: 'genetico',
    resumo: 'Mecha de cabelo branco na fronte, olhos de cores diferentes ou azuis muito vívidos, cantos internos dos olhos afastados com raiz nasal larga e surdez neurossensorial congênita — a combinação que diz "crista neural".',
    definicao: 'Grupo de síndromes autossômicas dominantes (PAX3, MITF, SOX10, EDNRB) de migração anômala de melanócitos: mecha branca frontal (poliose), encanecimento precoce, heterocromia de íris completa ou setorial ou íris azul brilhante, placas despigmentadas na pele, distopia cantorum (deslocamento lateral dos cantos internos, índice W > 1,95 no tipo 1), raiz nasal alta e larga, sinofre; surdez neurossensorial congênita uni ou bilateral. Tipo 1 com distopia; tipo 2 sem distopia (mais surdez); tipo 3 com anomalias dos membros superiores; tipo 4 com doença de Hirschsprung.',
    comoProcurar: [
      { passo: 'Observe cabelos (mecha frontal), sobrancelhas e íris com boa luz.', detalhe: 'Heterocromia setorial pode passar despercebida.' },
      { passo: 'Meça as distâncias intercantal interna, interpupilar e intercantal externa e calcule o índice W.', detalhe: 'Distopia cantorum imita hipertelorismo — as pupilas estão em posição normal.' },
      { passo: 'Pergunte pela audição e teste; pergunte por constipação grave desde o nascimento.', detalhe: 'Todo recém-nascido com mecha branca ou heterocromia deve ter a audição avaliada.' },
    ],
    mecanismo: 'Os melanócitos derivam da crista neural e precisam migrar para a pele, a íris e a estria vascular da cóclea; os fatores de transcrição PAX3, MITF e SOX10 comandam essa migração — sem eles faltam melanócitos na mecha, na íris e no ouvido interno, onde são necessários para manter o potencial endococlear.',
    significado: 'Os sinais cutâneos e oculares são a pista para diagnosticar precocemente uma surdez que precisa de aparelho ou implante coclear na janela de linguagem, e para investigar Hirschsprung no tipo 4.',
    armadilhas: ['Piebaldismo: mecha branca e placas, sem surdez nem heterocromia.', 'Vitiligo com poliose: adquirido.', 'Heterocromia isolada (benigna ou por Horner congênito) sem outros sinais.'],
    causas: [
      { titulo: 'Migração de melanócitos da crista neural', mecanismo: 'Fatores de transcrição e sinalização.', itens: ['Tipos 1 e 3 (PAX3)', 'Tipo 2 (MITF, SOX10)', 'Tipo 4 (EDNRB, EDN3, SOX10) com Hirschsprung'] },
    ],
    referencias: ['Pingault V et al. Review and update of mutations causing Waardenburg syndrome. Hum Mutat, 2010.'],
  },
  {
    slug: 'hemocromatose-sinais',
    nome: 'Hemocromatose — pele de bronze e mão de ferro',
    sinonimos: ['Hemocromatose hereditária', 'HFE C282Y', 'Diabetes bronzeado'],
    sistema: 'genetico',
    resumo: 'Homem de meia-idade com pele cinza-bronzeada, fígado aumentado, diabetes, impotência e dor nas articulações do segundo e terceiro dedos — o aperto de mão doloroso da artropatia por ferro.',
    definicao: 'Sinais da sobrecarga de ferro na hemocromatose hereditária (HFE C282Y homozigota, autossômica recessiva): hiperpigmentação cinza-bronzeada difusa, mais nas áreas expostas, genitais e cicatrizes; hepatomegalia, eritema palmar e aranhas quando cirrose; artropatia das 2ª e 3ª metacarpofalangianas com osteófitos em gancho e condrocalcinose (dor ao aperto de mão — sinal do "aperto de ferro"); diabetes, hipogonadismo (atrofia testicular, perda de libido, rarefação de pelos), cardiomiopatia com arritmias. Ferritina alta e saturação de transferrina > 45%.',
    comoProcurar: [
      { passo: 'Compare a cor da pele com a de familiares e procure pigmentação em cicatrizes e genitais.', detalhe: 'O tom é cinza-metálico, não o bronzeado dourado do sol.' },
      { passo: 'Palpe as 2ª e 3ª MCF (edema ósseo, dor) e aperte a mão.', detalhe: 'Radiografia: osteófitos em gancho e condrocalcinose.' },
      { passo: 'Palpe o fígado; pergunte por libido, diabetes e palpitações.', detalhe: 'Saturação de transferrina e ferritina; genotipagem do HFE.' },
    ],
    mecanismo: 'A deficiência de hepcidina deixa a ferroportina abrir sem freio: o intestino absorve ferro em excesso por décadas; o ferro livre gera radicais que lesam hepatócitos, células beta, gonadotrofos e miócitos, e estimula melanócitos — daí a tríade clássica de cirrose, diabetes e pele bronzeada.',
    significado: 'Diagnosticada antes da cirrose, a flebotomia normaliza a expectativa de vida; depois dela, o risco de hepatocarcinoma persiste. A artropatia das MCF 2-3 num homem de 40 anos é frequentemente o primeiro sinal — e o que o reumatologista pode pegar.',
    armadilhas: ['Artrite reumatoide: sinovite mole e simétrica das MCF, sem osteófitos em gancho.', 'Doença de Addison: hiperpigmentação com hipotensão e mucosas pigmentadas.', 'Ferritina alta por inflamação, álcool ou síndrome metabólica com saturação normal.'],
    causas: [
      { titulo: 'Deficiência de hepcidina', mecanismo: 'Absorção intestinal de ferro desregulada.', itens: ['HFE C282Y homozigota (tipo 1)', 'Hemojuvelina e hepcidina (tipo 2, juvenil)', 'Receptor 2 da transferrina (tipo 3)', 'Ferroportina (tipo 4)'] },
    ],
    referencias: ['Adams PC, Barton JC. Haemochromatosis. Lancet, 2007.'],
  },
  {
    slug: 'angioqueratomas-de-fabry',
    nome: 'Angioqueratomas de Fabry',
    sinonimos: ['Doença de Fabry', 'Angioqueratoma corporis diffusum', 'Deficiência de alfa-galactosidase A'],
    sistema: 'genetico',
    resumo: 'Pápulas puntiformes vermelho-escuras que não empalidecem, agrupadas entre o umbigo e os joelhos — a "zona da cueca" —, num jovem com crises de dor em queimação nas mãos e nos pés, intolerância ao calor, suor ausente e proteinúria.',
    definicao: 'Doença lisossômica ligada ao X (GLA, deficiência de alfa-galactosidase A) com acúmulo de globotriaosilceramida: angioqueratomas — pápulas de 1 a 3 mm, vermelho-escuras a violáceas, discretamente ceratósicas, que não empalidecem à pressão — em distribuição de calção (abdome inferior, nádegas, genitais, raiz das coxas), também em lábios e umbigo; acroparestesias em queimação desde a infância, desencadeadas por febre, calor e exercício; hipo ou anidrose com intolerância ao calor; córnea verticilata (opacidades em redemoinho) à lâmpada de fenda; proteinúria e doença renal progressiva, hipertrofia ventricular esquerda e arritmias, AVC em jovem. Mulheres heterozigotas podem ser afetadas.',
    comoProcurar: [
      { passo: 'Examine a pele do umbigo aos joelhos, incluindo genitais e nádegas, e os lábios.', detalhe: 'Vitropressão: não empalidecem.' },
      { passo: 'Pergunte por dor em queimação nas extremidades com febre, calor ou exercício, e por não suar.', detalhe: 'A dor começa na infância e é frequentemente rotulada como "dor do crescimento".' },
      { passo: 'Peça lâmpada de fenda (córnea verticilata), urina (proteinúria) e ECG.', detalhe: 'Atividade da alfa-galactosidase nos homens; genética nas mulheres.' },
    ],
    mecanismo: 'Sem a enzima, o glicoesfingolipídeo se acumula no endotélio, nos podócitos, nos cardiomiócitos e nos neurônios dos gânglios da raiz dorsal: capilares dérmicos dilatam (angioqueratomas), fibras finas degeneram (dor e anidrose), e rim, coração e cérebro sofrem por vasculopatia e acúmulo.',
    significado: 'Reconhecer os angioqueratomas e a dor neuropática da infância permite tratar com reposição enzimática ou chaperona antes do dano renal e cardíaco irreversível — e rastrear a família. É causa subdiagnosticada de AVC, hipertrofia ventricular e doença renal em jovens.',
    armadilhas: ['Angiomas rubi: maiores, lisos, no tronco superior, em adultos mais velhos.', 'Angioqueratomas de Fordyce no escroto do idoso: isolados, sem outros sinais.', 'Petéquias e vasculite: empalidecem ou são palpáveis e inflamadas.'],
    causas: [
      { titulo: 'Deficiência de alfa-galactosidase A', mecanismo: 'Acúmulo lisossômico de Gb3.', itens: ['Fenótipo clássico (homens, atividade quase nula)', 'Variantes tardias cardíacas ou renais', 'Mulheres heterozigotas com expressão variável'] },
    ],
    referencias: ['Ortiz A et al. Fabry disease revisited: management and treatment recommendations for adult patients. Mol Genet Metab, 2018.'],
  },
  {
    slug: 'ocronose-alcaptonuria',
    nome: 'Ocronose da alcaptonúria',
    sinonimos: ['Alcaptonúria', 'Pigmentação ocronótica', 'Urina que escurece'],
    sistema: 'genetico',
    resumo: 'Manchas cinza-azuladas na esclera entre a córnea e os cantos, orelhas azuladas e endurecidas, suor que mancha a roupa e urina que escurece em repouso — num adulto com artrose precoce da coluna e dos grandes joelhos.',
    definicao: 'Doença autossômica recessiva (HGD, deficiência de homogentisato dioxigenase) com acúmulo de ácido homogentísico: urina que escurece ao ar ou alcalinizada (desde a fralda); pigmentação ocronótica — manchas cinza-azuladas a pretas na esclera, nas regiões interpalpebrais, pigmentação azulada e espessamento da cartilagem das orelhas, pigmentação da pele de axilas, mãos e face e do suor; artropatia degenerativa precoce da coluna (discos calcificados, anquilose) e dos grandes joelhos e quadris, ruptura de tendões, calcificação valvar aórtica, cálculos renais e prostáticos.',
    comoProcurar: [
      { passo: 'Afaste as pálpebras e olhe a esclera nas posições de 3 e 9 horas; palpe e olhe as orelhas contra a luz.', detalhe: 'Pigmento e cartilagem rígida.' },
      { passo: 'Pergunte se a urina escurece quando fica parada, se o suor mancha roupas brancas.', detalhe: 'Deixe uma amostra ao ar ou alcalinize — ela escurece.' },
      { passo: 'Examine a coluna (rigidez) e os joelhos em paciente de 30 a 40 anos.', detalhe: 'Radiografia: discos calcificados em vários níveis.' },
    ],
    mecanismo: 'O ácido homogentísico, intermediário da degradação da tirosina, não é metabolizado; oxida-se em polímeros semelhantes à melanina que se ligam ao colágeno das cartilagens e tendões, tornando-os rígidos, pigmentados e quebradiços — daí a artropatia e as rupturas.',
    significado: 'Diagnóstico simples (urina, ácido homogentísico urinário) que explica a artrose precoce e as complicações cardíacas; a nitisinona reduz a produção do ácido e retarda a progressão.',
    armadilhas: ['Espondilite anquilosante: sacroileíte e sindesmófitos, sem discos calcificados e pigmento.', 'Ocronose exógena por hidroquinona: pigmentação facial sem urina escura.', 'Pigmentação escleral por minociclina e argiria.'],
    causas: [
      { titulo: 'Deficiência de homogentisato dioxigenase', mecanismo: 'Acúmulo e deposição de polímeros pigmentados.', itens: ['Alcaptonúria (HGD, autossômica recessiva)'] },
    ],
    referencias: ['Ranganath LR et al. Nitisinone arrests ochronosis and decreases rate of progression of alkaptonuria. Lancet Diabetes Endocrinol, 2020.'],
  },
  {
    slug: 'xeroderma-pigmentoso',
    nome: 'Xeroderma pigmentoso',
    sinonimos: ['XP', 'Defeito de reparo por excisão de nucleotídeos', 'Crianças da lua'],
    sistema: 'genetico',
    resumo: 'Criança com queimadura solar desproporcional desde os primeiros meses, depois pele seca e sarapintada de efélides e manchas claras nas áreas expostas, olhos vermelhos e fotofóbicos — e carcinomas cutâneos antes dos 10 anos.',
    definicao: 'Doença autossômica recessiva do reparo do DNA por excisão de nucleotídeos (genes XPA a XPG e XPV): queimadura solar grave e prolongada após exposição mínima (em metade), efélides precoces e profusas nas áreas expostas, xerose, poiquilodermia (hiper e hipopigmentação com telangiectasias e atrofia), ceratoses actínicas, carcinomas basocelulares, espinocelulares e melanomas com mediana de idade abaixo de 10 anos; fotofobia, conjuntivite, ceratite e tumores da superfície ocular; degeneração neurológica progressiva em alguns grupos (XPA, XPD).',
    comoProcurar: [
      { passo: 'Compare pele exposta (face, pescoço, antebraços) com a coberta (nádegas).', detalhe: 'A diferença é a marca da fotodermatose.' },
      { passo: 'Pergunte pela primeira exposição solar e a reação — bolhas após minutos de sol.', detalhe: 'Consanguinidade é frequente.' },
      { passo: 'Examine olhos e pálpebras; faça exame neurológico (surdez, ataxia, perda cognitiva).', detalhe: 'Teste de reparo do DNA em fibroblastos e painel genético confirmam.' },
    ],
    mecanismo: 'A luz ultravioleta cria dímeros de pirimidina no DNA, normalmente removidos pelo reparo por excisão de nucleotídeos; sem ele, as lesões se acumulam em queratinócitos e melanócitos e se convertem em mutações — risco de câncer de pele mil vezes maior.',
    significado: 'O diagnóstico impõe proteção UV total (roupas, filtros, películas nas janelas) desde cedo, vigilância dermatológica e oftalmológica frequente e retirada precoce de lesões; muda radicalmente a sobrevida.',
    armadilhas: ['Protoporfiria eritropoiética: dor e ardor imediatos ao sol, sem efélides nem câncer precoce.', 'Efélides comuns: sem queimadura desproporcional nem poiquilodermia.', 'Síndrome de Cockayne: fotossensibilidade com nanismo e envelhecimento, sem câncer.'],
    causas: [
      { titulo: 'Reparo por excisão de nucleotídeos', mecanismo: 'Dímeros de pirimidina não reparados.', itens: ['Grupos XPA a XPG', 'XP variante (polimerase eta)', 'Consanguinidade como fator'] },
    ],
    referencias: ['Lehmann AR et al. Xeroderma pigmentosum. Orphanet J Rare Dis, 2011.'],
  },
  {
    slug: 'epidermolise-bolhosa',
    nome: 'Epidermólise bolhosa',
    sinonimos: ['Pele de borboleta', 'EB simples, juncional e distrófica'],
    sistema: 'genetico',
    resumo: 'Bolhas e erosões que surgem ao menor atrito — onde a fralda aperta, onde a criança engatinha, nos dedos — desde o nascimento, com unhas distróficas, cicatrizes, mílios e, nas formas distróficas, dedos fundidos em luva.',
    definicao: 'Grupo de genodermatoses da adesão dermoepidérmica com bolhas induzidas por trauma mínimo: simples (queratinas 5/14; bolhas intraepidérmicas, em mãos e pés, que pioram no calor, cicatrizam sem cicatriz), juncional (laminina 332, colágeno XVII; bolhas generalizadas, tecido de granulação periorificial, hipoplasia do esmalte; forma grave letal na infância), distrófica (colágeno VII; bolhas que cicatrizam com cicatrizes, mílios, perda de unhas, pseudossindactilia em luva, microstomia, estenose esofágica, carcinoma espinocelular agressivo no adulto) e Kindler. Presente ao nascimento ou nos primeiros meses.',
    comoProcurar: [
      { passo: 'Localize as bolhas: áreas de atrito (mãos, pés, joelhos, fralda) e mucosas.', detalhe: 'Sinal de Nikolsky pode ser positivo pela fragilidade — cuidado ao examinar.' },
      { passo: 'Procure unhas distróficas, mílios em cicatrizes, dentes com esmalte fino, pseudossindactilia.', detalhe: 'Cicatriz e mílios apontam para a forma distrófica.' },
      { passo: 'Pergunte por história familiar e consanguinidade; avalie nutrição e deglutição.', detalhe: 'Biópsia com imunomapeamento e painel genético definem o tipo.' },
    ],
    mecanismo: 'A pele resiste ao cisalhamento graças a âncoras moleculares em série — queratinas no citoesqueleto, hemidesmossomos, filamentos de ancoragem (laminina 332) e fibrilas de ancoragem (colágeno VII); a falta de qualquer elo faz a pele se separar naquele nível, e a profundidade da clivagem define cicatriz, mucosa e prognóstico.',
    significado: 'Diagnóstico precoce muda o manejo do recém-nascido (manipulação, curativos não aderentes, nutrição), evita traumas iatrogênicos e prepara vigilância de estenose esofágica, anemia e carcinoma. A terapia gênica tópica (beremagene) abriu tratamento para a distrófica.',
    armadilhas: ['Impetigo bolhoso e síndrome da pele escaldada: bolhas infecciosas, agudas, com febre.', 'Epidermólise bolhosa adquirida: autoimune, em adultos.', 'Maus-tratos: lesões em padrão, sem bolhas espontâneas no atrito mínimo.'],
    causas: [
      { titulo: 'Proteínas de adesão da pele', mecanismo: 'Clivagem no nível da proteína defeituosa.', itens: ['EB simples (KRT5, KRT14)', 'EB juncional (LAMA3/B3/C2, COL17A1)', 'EB distrófica (COL7A1)', 'Síndrome de Kindler (FERMT1)'] },
    ],
    referencias: ['Has C et al. Consensus reclassification of inherited epidermolysis bullosa. Br J Dermatol, 2020.'],
  },
  {
    slug: 'sindrome-de-gorlin',
    nome: 'Síndrome de Gorlin',
    sinonimos: ['Síndrome do nevo basocelular', 'PTCH1', 'Pits palmares'],
    sistema: 'genetico',
    resumo: 'Dezenas de carcinomas basocelulares começando na adolescência, pequenas depressões puntiformes nas palmas e plantas, macrocefalia com fronte proeminente e cistos na mandíbula — a via hedgehog desligada do freio.',
    definicao: 'Síndrome autossômica dominante (PTCH1, SUFU) com carcinomas basocelulares múltiplos de início precoce (antes dos 20 a 30 anos), inclusive em pele não exposta; pits palmares e plantares (depressões de 1 a 3 mm, rosadas, puntiformes), queratocistos odontogênicos da mandíbula (dor, tumefação, deslocamento dentário, a partir da segunda década), macrocefalia com bossa frontal, hipertelorismo, costelas bífidas, calcificação da foice cerebral, meduloblastoma na infância e fibromas ovarianos e cardíacos.',
    comoProcurar: [
      { passo: 'Examine as palmas e plantas com luz oblíqua: pits puntiformes.', detalhe: 'Ficam mais visíveis após imersão em água.' },
      { passo: 'Conte lesões perláceas na pele (face, tronco, dorso) e pergunte por cirurgias de pele já feitas.', detalhe: 'Basocelular em jovem ou múltiplo pede investigação.' },
      { passo: 'Meça o perímetro cefálico e pergunte por cistos na mandíbula e familiares.', detalhe: 'Radiografia panorâmica, calcificação da foice; evitar radioterapia (induz basocelulares).' },
    ],
    mecanismo: 'O PTCH1 é o receptor que mantém a via hedgehog desligada; sem ele, a via fica ativa e estimula a proliferação de células basais da epiderme, do epitélio odontogênico e dos precursores cerebelares — basocelulares, queratocistos e meduloblastoma.',
    significado: 'O diagnóstico orienta vigilância dermatológica frequente, tratamento de lesões pequenas, fotoproteção e evitar radiação ionizante; vismodegibe e sonidegibe (inibidores de hedgehog) tratam os casos múltiplos.',
    armadilhas: ['Basocelular esporádico no idoso fotoexposto: único, tardio.', 'Pits palmares confundidos com ceratólise ou verrugas planas.', 'Macrocefalia benigna familiar sem outros sinais.'],
    causas: [
      { titulo: 'Via hedgehog', mecanismo: 'Perda do freio PTCH1.', itens: ['PTCH1 (maioria)', 'SUFU (maior risco de meduloblastoma)', 'PTCH2 (raro)'] },
    ],
    referencias: ['Bree AF et al. Consensus statement from the first international colloquium on basal cell nevus syndrome. Am J Med Genet A, 2011.'],
  },
]
