import type { CenaClinica } from './esquemas'

/**
 * Cenas adicionais de pulmão e pericárdio — segunda leva do acervo.
 *
 * Nenhuma tem esquema paramétrico: são achados que só existem em movimento
 * (o ponto pulmonar, a água-viva, o colapso diastólico) ou cuja textura o
 * desenho não reproduz. O caso real do The POCUS Atlas é a figura; a ficha
 * faz o resto.
 */
export const CENAS_PULMAO: CenaClinica[] = [
  {
    id: 'ponto-pulmonar',
    titulo: 'Ponto pulmonar — a borda do pneumotórax',
    estado: 'alterado',
    diagnostico: 'Pneumotórax: o ponto onde o pulmão colapsado ainda toca a parede.',
    achado: 'Na mesma imagem, metade da linha pleural **desliza** e a outra metade fica parada, e a fronteira entre as duas vai e volta com a respiração. No modo M alternam praia e código de barras no mesmo traçado.',
    leitura: ['Ache uma região sem deslizamento e deslize a sonda lateralmente, devagar.', 'Pare quando o deslizamento aparecer de um lado da tela só.', 'Registre em modo M: praia e código de barras alternando fecham o diagnóstico.'],
    diferencaDoNormal: 'No pulmão normal a pleura desliza inteira. Aqui o ar separa os folhetos em parte do campo, e a borda do colapso passa pela janela a cada ciclo. É o único achado de ultrassom **patognomônico** de pneumotórax — especificidade próxima de 100%.',
    conduta: 'Confirma o pneumotórax; a posição do ponto estima o tamanho (quanto mais lateral e posterior, maior). Instável, drena sem esperar radiografia. Pequeno e estável, observação com controle.',
    diferencial: ['Bolha enfisematosa (borda fixa, não respiratória)', 'Aderência pleural parcial', 'Borda do coração ou do diafragma imitando o ponto'],
  },
  {
    id: 'codigo-de-barras',
    titulo: 'Código de barras no modo M',
    estado: 'alterado',
    diagnostico: 'Ausência de deslizamento pleural — pneumotórax até prova em contrário.',
    achado: 'Modo M com linhas horizontais paralelas do topo ao fundo da tela, sem o granulado abaixo da pleura. É o "sinal da estratosfera".',
    leitura: ['Ponha o cursor do modo M sobre a linha pleural.', 'Compare com o lado oposto: praia de um lado, barras do outro.', 'Confirme no modo B que não há linhas B nem pulso pulmonar.'],
    diferencaDoNormal: 'Na praia, tudo abaixo da pleura é granulado porque o pulmão se move. No código de barras nada se move — o ar entre os folhetos apagou o movimento, e a imagem vira uma pilha de linhas fixas.',
    conduta: 'Sozinho não fecha pneumotórax (apneia, intubação seletiva e aderência também apagam o deslizamento). Procure o ponto pulmonar; no trauma instável com clínica compatível, descomprima.',
    diferencial: ['Intubação seletiva', 'Apneia ou parada', 'Aderência pleural', 'Pleurodese prévia'],
  },
  {
    id: 'sinal-da-praia',
    titulo: 'Sinal da praia — modo M normal',
    estado: 'alterado',
    diagnostico: 'Pleura deslizando — o registro que afasta pneumotórax naquele ponto.',
    achado: 'Acima da linha pleural, linhas horizontais fixas (a parede parada — o "mar"); abaixo, granulado homogêneo (o pulmão em movimento — a "areia").',
    leitura: ['Cursor sobre a linha pleural, congelando alguns ciclos.', 'Veja a transição nítida de linhas para granulado exatamente na pleura.', 'Guarde a imagem como referência do lado oposto.'],
    diferencaDoNormal: 'É o normal registrado em traçado. Está aqui para ser comparado com o código de barras: a diferença entre os dois é o que se procura no trauma.',
    conduta: 'Afasta pneumotórax naquele ponto com sensibilidade alta. Um ponto normal não exclui pneumotórax lateral ou pequeno — examine ao menos dois pontos anteriores e um lateral.',
    diferencial: [],
  },
  {
    id: 'linhas-b-confluentes',
    titulo: 'Linhas B confluentes — pulmão branco',
    estado: 'alterado',
    diagnostico: 'Síndrome intersticial grave: edema alveolar ou SDRA.',
    achado: 'As linhas B se fundem numa faixa branca que ocupa o campo inteiro abaixo da pleura, sem espaço preto entre elas. É o "feixe de luz" no extremo.',
    leitura: ['Confirme que a faixa parte da pleura e vai ao fundo.', 'Mapeie os campos: bilateral e homogêneo, ou com áreas poupadas?', 'Olhe a pleura: lisa sugere congestão, irregular sugere pneumonia ou SDRA.'],
    diferencaDoNormal: 'Do padrão A às linhas B contadas, e destas ao pulmão branco: é a mesma física, com cada vez mais água nos septos até o alvéolo inundar. A imagem deixa de mostrar linhas porque já não há ar suficiente para separá-las.',
    conduta: 'Edema alveolar: em congestão, diurético e ventilação não invasiva; em SDRA, ventilação protetora. A pleura irregular e as áreas poupadas apontam para SDRA e mudam a estratégia.',
    diferencial: ['Edema cardiogênico', 'SDRA', 'Pneumonia extensa', 'Fibrose com exacerbação'],
  },
  {
    id: 'pleura-irregular',
    titulo: 'Pleura irregular com linhas B — pneumonite viral',
    estado: 'alterado',
    diagnostico: 'Pneumonia intersticial viral (COVID-19 é o protótipo).',
    achado: 'Linha pleural espessada e serrilhada, linhas B em focos separados por áreas normais, pequenas consolidações subpleurais. Distribuição posterior e basal, assimétrica.',
    leitura: ['Percorra os campos posteriores — é onde começa.', 'Note a alternância: campo de B, campo normal, campo de B.', 'Procure as consolidações subpleurais milimétricas.'],
    diferencaDoNormal: 'No edema cardiogênico a pleura é lisa e as B são homogêneas e gravitacionais. Aqui a pleura está doente — irregular — e as B vêm em ilhas, porque a inflamação é focal e não hidrostática.',
    conduta: 'Sugere pneumonite viral; graduar a extensão por campos ajuda a prever necessidade de oxigênio. Não substitui o teste etiológico.',
    diferencial: ['SDRA de outra causa', 'Pneumonia bacteriana multifocal', 'Fibrose pulmonar', 'Pneumonite por aspiração'],
  },
  {
    id: 'broncograma-dinamico',
    titulo: 'Broncograma aéreo dinâmico — pneumonia',
    estado: 'alterado',
    diagnostico: 'Consolidação com brônquios pérvios — pneumonia, não atelectasia obstrutiva.',
    achado: 'Dentro do pulmão hepatizado, pontos e traços brilhantes que **se movem** com a respiração: ar entrando e saindo dos brônquios.',
    leitura: ['Fixe a sonda sobre a consolidação por vários ciclos.', 'Observe se os pontos brancos deslocam-se centrifugamente na inspiração.', 'Se ficam parados, é broncograma estático — outra história.'],
    diferencaDoNormal: 'O pulmão normal não mostra brônquios porque o ar ao redor apaga tudo. Na consolidação, o parênquima virou líquido e o ar que ainda entra nos brônquios fica visível — e o fato de ele se mover prova que a via aérea está aberta.',
    conduta: 'Pneumonia: antibiótico conforme gravidade. Broncograma dinâmico afasta atelectasia obstrutiva com alta especificidade e dispensa broncoscopia diagnóstica.',
    diferencial: ['Atelectasia obstrutiva (broncograma estático)', 'Contusão pulmonar', 'Infarto pulmonar'],
  },
  {
    id: 'sinal-do-fragmento',
    titulo: 'Sinal do fragmento (shred) — consolidação subpleural',
    estado: 'alterado',
    diagnostico: 'Consolidação que não alcança a pleura inteira — pneumonia, infarto ou contusão.',
    achado: 'Borda profunda da consolidação irregular, "rasgada", onde encontra pulmão aerado. Diferente da borda lisa e regular do derrame.',
    leitura: ['Identifique o tecido hipoecoico subpleural.', 'Olhe a margem profunda: irregular e brilhante é o fragmento.', 'Some linhas B ao redor, comuns na borda da consolidação.'],
    diferencaDoNormal: 'A pleura normal é uma linha limpa. A consolidação subpleural a substitui por tecido com ecos, e a fronteira com o ar residual fica irregular — o ar não recua de forma uniforme.',
    conduta: 'Consolidação periférica; o contexto decide entre pneumonia (febre, tosse), embolia (dor pleurítica, hipoxemia, TVP) e contusão (trauma). Procure múltiplos focos em cunha se pensar em embolia.',
    diferencial: ['Pneumonia', 'Infarto pulmonar', 'Contusão', 'Metástase pleural'],
  },
  {
    id: 'hepatizacao',
    titulo: 'Hepatização pulmonar',
    estado: 'alterado',
    diagnostico: 'Consolidação lobar — pneumonia bacteriana típica.',
    achado: 'O pulmão adquire textura de fígado: parênquima homogêneo com ecos, broncogramas aéreos dentro, às vezes vasos ao Doppler. A base do lobo é vista como se fosse órgão sólido.',
    leitura: ['Procure na base posterior, onde o lobo inferior encosta no diafragma.', 'Compare com o fígado ou o baço do mesmo lado: a textura é parecida.', 'Diferencie de derrame: derrame é anecoico; hepatização tem ecos e broncogramas.'],
    diferencaDoNormal: 'Todo o ar do lobo foi substituído por exsudato. O que era barreira acústica virou janela, e o pulmão passa a ser visto por dentro.',
    conduta: 'Pneumonia lobar: antibiótico. Volume de consolidação e derrame parapneumônico associado orientam a gravidade.',
    diferencial: ['Atelectasia completa', 'Massa pulmonar', 'Derrame complexo'],
  },
  {
    id: 'infarto-pulmonar',
    titulo: 'Infarto pulmonar periférico — embolia',
    estado: 'alterado',
    diagnostico: 'Embolia pulmonar com infarto subpleural.',
    achado: 'Lesão hipoecoica subpleural em **cunha** ou triângulo, base na pleura, sem broncograma, com uma linha B na borda. Frequentemente múltiplas e posteriores.',
    leitura: ['Explore os campos posteriores e laterais do lado da dor.', 'Meça: a maioria tem 1 a 3 cm.', 'Conte: duas ou mais cunhas em paciente com suspeita clínica aumentam muito a probabilidade.'],
    diferencaDoNormal: 'O infarto é o segmento que o êmbolo deixou sem sangue: o tecido enche de sangue e necrosa, e o ar some da periferia. A forma em cunha é a forma do território arterial.',
    conduta: 'Achado que apoia embolia mas não a substitui: peça angiotomografia ou trate empiricamente se instável. Combine com ecocardiograma (sobrecarga de VD) e Doppler venoso.',
    diferencial: ['Pneumonia subpleural', 'Contusão', 'Metástase', 'Vasculite'],
  },
  {
    id: 'contusao-pulmonar',
    titulo: 'Contusão pulmonar',
    estado: 'alterado',
    diagnostico: 'Contusão pulmonar após trauma torácico fechado.',
    achado: 'Linhas B focais e consolidação subpleural irregular, do lado do impacto, sem derrame no início. A pleura pode estar irregular, e a fratura de costela costuma estar ao lado.',
    leitura: ['Examine a área do impacto e o campo oposto.', 'Procure fratura de costela adjacente.', 'Repita em 6 a 12 horas: a contusão piora antes de melhorar.'],
    diferencaDoNormal: 'É sangue nos alvéolos, não infecção nem água hidrostática. Por isso é focal, assimétrica, unilateral e ligada ao ponto do golpe.',
    conduta: 'Oxigênio, analgesia e vigilância; a contusão extensa evolui para SDRA. Evite hiper-hidratação. Avalie pneumotórax e hemotórax associados.',
    diferencial: ['Pneumonia por aspiração', 'Atelectasia', 'Pneumotórax oculto'],
  },
  {
    id: 'enfisema-subcutaneo',
    titulo: 'Enfisema subcutâneo — E-lines',
    estado: 'alterado',
    diagnostico: 'Ar no subcutâneo: pneumotórax, fratura de costela ou lesão de via aérea.',
    achado: 'Artefatos verticais brilhantes que partem **acima** da linha pleural, do tecido subcutâneo, e apagam tudo abaixo. A pleura e as costelas ficam invisíveis.',
    leitura: ['Note que as linhas nascem acima de onde a pleura deveria estar.', 'Procure o sinal do morcego: não há.', 'Palpe: a crepitação confirma.'],
    diferencaDoNormal: 'O ar sob a pele reflete tudo antes de o som chegar à pleura. Não é sinal pulmonar; é o motivo de o pulmão não poder ser visto naquele ponto.',
    conduta: 'Mude a sonda para um ponto sem enfisema. Procure a origem: pneumotórax (drene), fratura, lesão traqueobrônquica ou esofágica.',
    diferencial: ['Linhas B verdadeiras (nascem na pleura)', 'Artefato de gel ou de contato'],
  },
  {
    id: 'cavitacao',
    titulo: 'Lesão cavitária — abscesso e tuberculose',
    estado: 'alterado',
    diagnostico: 'Cavidade pulmonar periférica: abscesso, tuberculose ou neoplasia escavada.',
    achado: 'Dentro de uma consolidação, área anecoica ou com nível hidroaéreo e parede espessa e irregular. Na tuberculose miliar, múltiplos micronódulos subpleurais com pleura irregular.',
    leitura: ['Só se vê o que toca a pleura — a cavidade central escapa.', 'Procure nível líquido-ar e parede irregular.', 'Correlacione com radiografia ou tomografia.'],
    diferencaDoNormal: 'Necrose dentro da consolidação: o tecido liquefeito é anecoico e o ar que entra faz o nível. O ultrassom vê só a parte periférica, mas essa parte já muda a conduta.',
    conduta: 'Abscesso: antibiótico prolongado, drenagem se não responder. Tuberculose: isolamento respiratório e escarro. Neoplasia: biópsia.',
    diferencial: ['Empiema com fístula broncopleural', 'Pneumatocele', 'Cisto hidático roto'],
  },
  {
    id: 'sinal-da-coluna',
    titulo: 'Sinal da coluna — derrame pleural',
    estado: 'alterado',
    diagnostico: 'Derrame pleural: líquido permite ver a coluna acima do diafragma.',
    achado: 'A coluna vertebral, que normalmente termina no diafragma, continua visível **cranialmente** através do líquido. O pulmão flutua dentro.',
    leitura: ['Janela posterolateral, sonda longitudinal, ache o diafragma.', 'Siga a coluna: para abaixo do diafragma é normal; acima, há derrame.', 'Meça a lâmina de líquido para estimar o volume.'],
    diferencaDoNormal: 'O ar do pulmão normal apaga tudo além da pleura, inclusive a coluna. O líquido é janela: o som atravessa, bate no osso e o mostra onde não deveria aparecer.',
    conduta: 'Confirma derrame com alta especificidade. Toracocentese guiada se dispneia ou etiologia incerta. Lâmina > 1 cm na expiração é puncionável com segurança.',
    diferencial: ['Consolidação (também mostra coluna, mas com ecos e broncogramas)', 'Ascite alta (abaixo do diafragma)'],
  },
  {
    id: 'sinal-da-agua-viva',
    titulo: 'Sinal da água-viva — pulmão flutuando',
    estado: 'alterado',
    diagnostico: 'Derrame pleural volumoso com atelectasia compressiva.',
    achado: 'Lobo inferior colapsado ondula dentro do líquido a cada batimento e respiração, como uma água-viva. Bordas lisas, movimento livre.',
    leitura: ['Ache o derrame e espere alguns ciclos.', 'Observe o pulmão pendular; se não se move, pense em aderências ou tumor.', 'Meça a distância pulmão-parede: > 5 cm costuma ser > 1 litro.'],
    diferencaDoNormal: 'O pulmão normal enche o tórax e não tem espaço para oscilar. Aqui o líquido o afasta da parede e ele vira uma estrutura pendurada — livre de movimento porque perdeu o ar e a fixação.',
    conduta: 'Derrame grande: toracocentese ou dreno, conforme a causa. Movimento livre prediz reexpansão após drenagem.',
    diferencial: ['Massa pleural (fixa)', 'Derrame septado (movimento restrito)'],
  },
  {
    id: 'empiema',
    titulo: 'Empiema — derrame com plâncton',
    estado: 'alterado',
    diagnostico: 'Derrame parapneumônico complicado ou empiema.',
    achado: 'Líquido com ecos finos flutuantes que rodopiam ("plâncton"), septos, espessamento pleural. Consolidação adjacente.',
    leitura: ['Aumente o ganho: ecos móveis no líquido.', 'Procure septos e lojas.', 'Meça a espessura da pleura: > 3 mm sugere empiema organizado.'],
    diferencaDoNormal: 'Transudato é água limpa: anecoico e homogêneo. Pus e fibrina espalham o som e criam pontos móveis; a fibrina organiza septos. A imagem conta a composição do líquido.',
    conduta: 'Dreno torácico (não só punção) e antibiótico; septado, fibrinolítico intrapleural ou cirurgia. O plâncton prediz que a punção simples não resolve.',
    diferencial: ['Hemotórax', 'Derrame maligno', 'Quilotórax'],
  },
  {
    id: 'hemotorax',
    titulo: 'Hemotórax',
    estado: 'alterado',
    diagnostico: 'Sangue no espaço pleural após trauma.',
    achado: 'Líquido acima do diafragma, com ecos móveis ou coágulos, do lado da lesão. Frequentemente com fratura de costela ou contusão adjacente.',
    leitura: ['No EFAST, estenda a janela do quadrante superior para cima do diafragma.', 'Procure ecos e coágulos aderidos.', 'Reavalie após dreno: volume residual e pulmão reexpandido.'],
    diferencaDoNormal: 'Igual ao derrame, mas no trauma e com ecos. Sangue fresco pode ser anecoico; coagula em minutos e passa a ter textura.',
    conduta: 'Dreno torácico calibroso; > 1.500 mL iniciais ou > 200 mL/h por 3 horas indicam toracotomia. Reponha volume e monitore.',
    diferencial: ['Derrame prévio', 'Ruptura diafragmática com vísceras (procure peristalse)'],
  },
  {
    id: 'derrame-septado',
    titulo: 'Derrame septado',
    estado: 'alterado',
    diagnostico: 'Derrame pleural organizado — exsudato complicado.',
    achado: 'Traves de fibrina cruzando o líquido, formando lojas de tamanhos diferentes. O pulmão não flutua livremente.',
    leitura: ['Varra várias janelas: os septos não aparecem em todas.', 'Conte as lojas e veja se comunicam.', 'Verifique se há loja acessível para o dreno.'],
    diferencaDoNormal: 'A fibrina que o exsudato deposita vira rede. O derrame deixa de ser um espaço e vira vários; a drenagem de um não esvazia os outros.',
    conduta: 'Dreno guiado na loja maior; fibrinolítico intrapleural ou cirurgia videoassistida. Tomografia subestima septos — o ultrassom é melhor aqui.',
    diferencial: ['Empiema', 'Hemotórax organizado', 'Derrame maligno'],
  },
  {
    id: 'derrame-maligno',
    titulo: 'Derrame maligno com massa pleural',
    estado: 'alterado',
    diagnostico: 'Derrame neoplásico: nódulos pleurais ou espessamento irregular.',
    achado: 'Derrame com nódulos na pleura parietal ou diafragmática, espessamento pleural > 1 cm, pulmão com massa. Líquido pode ser límpido ou com ecos.',
    leitura: ['Percorra a pleura parietal e o diafragma: nodularidade é o achado.', 'Meça o espessamento.', 'Escolha o sítio de punção longe dos nódulos.'],
    diferencaDoNormal: 'O derrame comum tem pleura lisa. Aqui a pleura tem implantes — protuberâncias que a tornam irregular. É a assinatura da neoplasia.',
    conduta: 'Toracocentese com citologia; biópsia pleural guiada se negativa. Pleurodese ou cateter tunelizado para derrame recorrente sintomático.',
    diferencial: ['Empiema crônico', 'Tuberculose pleural', 'Mesotelioma'],
  },
  {
    id: 'cortina-pulmonar',
    titulo: 'Sinal da cortina — base normal',
    estado: 'alterado',
    diagnostico: 'Base pulmonar aerada, sem derrame.',
    achado: 'Na inspiração, o pulmão desce e "puxa uma cortina" de ar que apaga o fígado ou o baço no alto da imagem; na expiração, o órgão reaparece.',
    leitura: ['Sonda na linha axilar posterior, sobre o diafragma.', 'Observe a borda do ar descendo e subindo.', 'Cortina presente afasta derrame de qualquer volume relevante.'],
    diferencaDoNormal: 'É a normalidade da base, e existe como cena porque é o que falta no derrame: quando há líquido, o ar não desce até ali e a cortina não aparece.',
    conduta: 'Nenhuma. É o critério que encerra a busca por derrame naquele hemitórax.',
    diferencial: [],
  },
  {
    id: 'contracao-diafragmatica',
    titulo: 'Contração diafragmática',
    estado: 'alterado',
    diagnostico: 'Avaliação da função diafragmática: excursão e espessamento.',
    achado: 'Sonda subcostal: o diafragma desce na inspiração (excursão normal > 1 cm em respiração tranquila, > 5 cm em inspiração profunda). Sonda linear na zona de aposição: o músculo engrossa ≥ 20% ao inspirar.',
    leitura: ['Modo M sobre o diafragma posterior: meça a excursão.', 'Linear no 8º–10º espaço, linha axilar média: meça a espessura no fim da expiração e da inspiração.', 'Compare os lados.'],
    diferencaDoNormal: 'A cena é o normal em funcionamento. Paralisia: sem excursão ou movimento paradoxal (sobe ao inspirar) e espessamento < 20%.',
    conduta: 'Prediz sucesso de desmame ventilatório e diagnostica paralisia frênica (pós-cirurgia cardíaca, neuropatia). Excursão < 1 cm ou paradoxal: falha de desmame provável.',
    diferencial: ['Paralisia diafragmática', 'Fraqueza neuromuscular', 'Hiperinsuflação no DPOC (excursão reduzida com músculo normal)'],
  },
  {
    id: 'reexpansao',
    titulo: 'Reexpansão após dreno',
    estado: 'alterado',
    diagnostico: 'Pneumotórax drenado — pulmão reexpandido.',
    achado: 'Deslizamento pleural que volta onde estava ausente, com o dreno em pigtail visível. Linhas B esparsas pela reexpansão.',
    leitura: ['Compare com a imagem pré-dreno.', 'Procure o ponto pulmonar residual: se sumiu, o pulmão encostou.', 'Pulso pulmonar sem deslizamento sugere pulmão encostado mas não ventilando.'],
    diferencaDoNormal: 'Reverte o código de barras: o ar saiu, os folhetos se tocam e o deslizamento retorna. O ultrassom acompanha o dreno sem radiografia seriada.',
    conduta: 'Dreno funcionando; retirar quando o deslizamento persiste com o dreno clampado. Recidiva do código de barras após clampeamento: mantenha.',
    diferencial: ['Pneumotórax residual loculado', 'Dreno mal posicionado'],
  },
  {
    id: 'intubacao-esofagica',
    titulo: 'Intubação esofágica',
    estado: 'alterado',
    diagnostico: 'Tubo no esôfago — o "duplo trato".',
    achado: 'Sonda linear transversa no pescoço: além da traqueia com sua sombra, um segundo anel com sombra posterior à esquerda — o esôfago distendido pelo tubo. Sem deslizamento pleural bilateral ao ventilar.',
    leitura: ['Sonda sobre a fúrcula, transversal, durante a laringoscopia.', 'Um trato com ar: traqueia. Dois: o segundo é o esôfago com tubo.', 'Confirme com deslizamento pleural bilateral e capnografia.'],
    diferencaDoNormal: 'O esôfago normal é colabado e invisível atrás da traqueia. O tubo o abre e cria uma segunda coluna de ar, com sua própria sombra.',
    conduta: 'Retire o tubo e reintube. Sensibilidade e especificidade acima de 95% em mãos treinadas, antes mesmo da primeira ventilação.',
    diferencial: ['Divertículo de Zenker', 'Ar esofágico por ventilação com máscara'],
  },
  {
    id: 'intubacao-traqueal',
    titulo: 'Confirmação de intubação — sinal da nevasca',
    estado: 'alterado',
    diagnostico: 'Tubo passando pela traqueia.',
    achado: 'No instante em que o tubo atravessa, uma chuva de ecos brilhantes ("nevasca") dentro da traqueia. Depois, deslizamento pleural bilateral ao ventilar.',
    leitura: ['Mantenha a sonda na traqueia enquanto o tubo desce.', 'Veja a nevasca — dura um segundo.', 'Confirme a bilateralidade do deslizamento: só de um lado sugere seletiva.'],
    diferencaDoNormal: 'Cena de procedimento: a traqueia vazia ganha ecos com o tubo passando. Serve para descartar o esôfago em tempo real.',
    conduta: 'Prossiga a ventilação; confirme com capnografia. Deslizamento unilateral: recue o tubo até bilateralizar.',
    diferencial: ['Intubação seletiva à direita'],
  },
  {
    id: 'fratura-de-costela',
    titulo: 'Fratura de costela',
    estado: 'alterado',
    diagnostico: 'Fratura de arco costal.',
    achado: 'Descontinuidade ou degrau na cortical brilhante da costela, com hematoma hipoecoico sobre ela. Dor ao apoiar a sonda no ponto exato.',
    leitura: ['Sonda linear longitudinal sobre o ponto doloroso.', 'Siga a cortical: o degrau é a fratura.', 'Examine pleura abaixo: pneumotórax e hemotórax associados.'],
    diferencaDoNormal: 'A cortical normal é uma linha contínua e lisa. A fratura a interrompe; o hematoma marca o lugar.',
    conduta: 'Analgesia (bloqueio serrátil ou paravertebral no idoso ou em múltiplas fraturas), fisioterapia respiratória. Três ou mais fraturas no idoso: internação.',
    diferencial: ['Contusão sem fratura', 'Fratura de cartilagem costal'],
  },
  {
    id: 'bronquiolite',
    titulo: 'Bronquiolite — lactente',
    estado: 'alterado',
    diagnostico: 'Bronquiolite viral aguda.',
    achado: 'Linhas B em focos bilaterais, pequenas consolidações subpleurais e irregularidade pleural, distribuição em retalhos. Sem derrame.',
    leitura: ['Sonda linear, campos posteriores primeiro.', 'Conte áreas de B e consolidações < 1 cm.', 'Grade a extensão: mais campos, mais gravidade.'],
    diferencaDoNormal: 'O lactente normal tem padrão A limpo. Aqui as vias aéreas pequenas obstruídas produzem atelectasias e edema focais — daí o padrão em retalhos, e não homogêneo.',
    conduta: 'Suporte: oxigênio, hidratação, higiene nasal. Extensão ao ultrassom correlaciona com necessidade de oxigênio e internação.',
    diferencial: ['Pneumonia bacteriana (consolidação maior com broncograma)', 'Insuficiência cardíaca (B homogêneas)'],
  },
]

export const CENAS_PERICARDIO: CenaClinica[] = [
  {
    id: 'tamponamento',
    titulo: 'Tamponamento — colapso diastólico do VD',
    estado: 'alterado',
    diagnostico: 'Tamponamento cardíaco.',
    achado: 'Derrame circunferencial e, na diástole, a parede livre do ventrículo direito **afunda** para dentro — o coração não consegue encher. Átrio direito colapsa na sístole. Cava pletórica sem variação.',
    leitura: ['Ache o derrame e observe o VD ao longo de vários ciclos.', 'Identifique a diástole (valva mitral aberta) e veja a parede livre invaginar.', 'Confirme com a cava dilatada e fixa.'],
    diferencaDoNormal: 'No derrame sem tamponamento, o VD enche normalmente apesar do líquido. Quando a pressão pericárdica supera a pressão diastólica do VD, a parede cede: é o momento em que o derrame virou tamponamento — um diagnóstico de fisiologia, não de volume.',
    conduta: 'Emergência: pericardiocentese guiada ou drenagem cirúrgica. Volume e vasopressor como ponte. Não espere a tríade de Beck.',
    diferencial: ['Derrame volumoso sem tamponamento', 'Pericardite constritiva', 'Hipovolemia com VD pequeno'],
  },
  {
    id: 'tamponamento-modo-m',
    titulo: 'Colapso do VD no modo M',
    estado: 'alterado',
    diagnostico: 'Tamponamento documentado em modo M.',
    achado: 'Cursor pela parede livre do VD e pela valva mitral: a parede do VD mergulha exatamente quando a mitral está aberta (diástole). O registro fixa a fase.',
    leitura: ['Alinhe o cursor no eixo longo paraesternal cruzando VD, septo e mitral.', 'Relacione o mergulho da parede à abertura mitral.', 'Guarde a imagem: é o documento do diagnóstico.'],
    diferencaDoNormal: 'O modo M resolve o que o olho às vezes não separa: colapso na sístole (átrio, precoce e menos específico) do colapso na diástole (ventrículo, específico de tamponamento).',
    conduta: 'Drenagem. O traçado serve para convencer quem não estava ao lado do aparelho.',
    diferencial: ['Movimento normal da parede em derrame sem tamponamento'],
  },
  {
    id: 'variacao-do-fluxo-mitral',
    titulo: 'Variação respiratória do fluxo mitral',
    estado: 'alterado',
    diagnostico: 'Tamponamento: pulso paradoxal visto ao Doppler.',
    achado: 'Doppler pulsado na ponta dos folhetos mitrais: a onda E cai mais de 25 a 30% na inspiração e sobe na expiração. No fluxo tricúspide o oposto, com variação > 40%.',
    leitura: ['Amostra na mitral, apical 4 câmaras, respiração espontânea.', 'Compare a maior e a menor onda E entre os ciclos.', 'Repita na tricúspide.'],
    diferencaDoNormal: 'O fluxo mitral normal varia menos de 15% com a respiração. No tamponamento os ventrículos disputam um espaço fixo: o que o direito enche na inspiração o esquerdo perde — é a interdependência ventricular, e é o pulso paradoxal desenhado.',
    conduta: 'Confirma tamponamento fisiológico mesmo quando o colapso de câmara é duvidoso. Drenagem.',
    diferencial: ['DPOC e asma grave (variação por pressão pleural)', 'Pericardite constritiva'],
  },
  {
    id: 'coracao-oscilante',
    titulo: 'Coração oscilante — derrame volumoso',
    estado: 'alterado',
    diagnostico: 'Derrame pericárdico volumoso com coração pendular.',
    achado: 'O coração inteiro balança dentro de um lago de líquido, mudando de posição a cada batimento. No eletrocardiograma, alternância elétrica.',
    leitura: ['Subxifoide ou apical: veja o órgão inteiro se deslocar.', 'Estime o volume: > 2 cm de lâmina na diástole é grande.', 'Procure sinais de tamponamento.'],
    diferencaDoNormal: 'Preso ao pericárdio, o coração normal não se desloca. Solto no líquido, ele oscila — e a alternância do QRS no traçado é esse movimento visto pelos eletrodos.',
    conduta: 'Drenagem programada ou urgente conforme repercussão hemodinâmica. Investigue a causa: neoplasia, tuberculose, uremia, hipotireoidismo.',
    diferencial: ['Derrame pleural esquerdo volumoso (o coração não balança)'],
  },
  {
    id: 'derrame-com-fibrina',
    titulo: 'Derrame pericárdico com fibrina',
    estado: 'alterado',
    diagnostico: 'Derrame exsudativo: pericardite infecciosa, urêmica ou neoplásica.',
    achado: 'Traves e ecos finos dentro do líquido pericárdico, aderidos ao epicárdio, que oscilam com o batimento. Espessamento pericárdico.',
    leitura: ['Aumente o ganho: fibrina aparece como fios.', 'Veja se as traves limitam o movimento do coração.', 'Meça a lâmina e procure loculações.'],
    diferencaDoNormal: 'Transudato é preto e limpo. Fibrina e proteína espalham o som: o derrame ganha textura, e isso já diz que é inflamatório.',
    conduta: 'Investigar a causa (tuberculose em área endêmica, uremia, neoplasia, purulento). Fibrina prediz evolução para constrição — acompanhar.',
    diferencial: ['Hemopericárdio organizado', 'Gordura epicárdica'],
  },
  {
    id: 'hemopericardio',
    titulo: 'Hemopericárdio traumático',
    estado: 'alterado',
    diagnostico: 'Sangue no pericárdio após trauma penetrante.',
    achado: 'Derrame com ecos ou coágulo aderido, frequentemente pequeno, em paciente com ferida precordial. Tamponamento pode ocorrer com 100 mL.',
    leitura: ['Subxifoide é a janela do EFAST; se ruim, paraesternal.', 'Qualquer líquido pericárdico em trauma penetrante é positivo.', 'Cuidado com hemotórax esquerdo drenando o pericárdio: janela falsamente negativa.'],
    diferencaDoNormal: 'Sangue arterial entra rápido num pericárdio que não teve tempo de se distender: pouco volume, muita pressão. Por isso a lâmina é pequena e o paciente está chocado.',
    conduta: 'Cirurgia (toracotomia ou esternotomia). Pericardiocentese só como ponte se a cirurgia não for imediata — coágulo entope a agulha.',
    diferencial: ['Derrame prévio', 'Gordura epicárdica'],
  },
  {
    id: 'gordura-epicardica',
    titulo: 'Gordura epicárdica — o que imita derrame',
    estado: 'alterado',
    diagnostico: 'Coxim adiposo epicárdico, não derrame.',
    achado: 'Faixa hipoecoica com ecos finos, **anterior** ao VD, que se move junto com o coração e não aparece posteriormente. Não muda com a posição.',
    leitura: ['Localize: anterior apenas? Gordura. Circunferencial ou posterior? Derrame.', 'Textura: gordura tem ecos; derrame simples é preto.', 'Movimento: gordura acompanha o miocárdio; líquido fica e o coração se move dentro.'],
    diferencaDoNormal: 'É uma variante do normal, comum em obesos e idosos. Foi confundida com derrame em muitas pericardiocenteses desnecessárias.',
    conduta: 'Nenhuma. Se a dúvida persiste, olhe o sulco atrioventricular posterior: derrame o preenche, gordura não.',
    diferencial: ['Derrame pericárdico anterior loculado', 'Derrame pleural'],
  },
  {
    id: 'pericardite-constritiva',
    titulo: 'Pericardite constritiva',
    estado: 'alterado',
    diagnostico: 'Pericárdio espessado e rígido que impede o enchimento.',
    achado: 'Pericárdio espesso e brilhante, septo que "salta" no início da diástole (septal bounce), cava pletórica, veias hepáticas com reversão expiratória, variação respiratória do fluxo mitral.',
    leitura: ['Note o pericárdio: espessado, às vezes calcificado.', 'Veja o septo balançar na diástole precoce.', 'Doppler: variação mitral > 25% com átrios grandes e ventrículos pequenos.'],
    diferencaDoNormal: 'O pericárdio normal é uma linha fina. Rígido, ele vira caixa fechada: o coração enche até o limite e para, e os ventrículos passam a competir pelo espaço — o mesmo mecanismo do tamponamento, mas crônico e sem líquido.',
    conduta: 'Diagnóstico difícil e frequentemente tardio. Confirmar com ressonância e cateterismo; pericardiectomia é o tratamento definitivo.',
    diferencial: ['Cardiomiopatia restritiva', 'Tamponamento', 'Insuficiência tricúspide grave'],
  },
  {
    id: 'pericardiocentese',
    titulo: 'Pericardiocentese guiada',
    estado: 'alterado',
    diagnostico: 'Drenagem do derrame sob visão direta.',
    achado: 'Agulha ou cateter dentro do espaço pericárdico; injeção de soro agitado confirma a posição ("bolhas" no pericárdio, não no ventrículo). Depois, a lâmina diminui e o VD volta a encher.',
    leitura: ['Escolha a janela onde a lâmina é maior e mais próxima da pele — muitas vezes apical, não subxifoide.', 'Veja a ponta da agulha entrar no líquido.', 'Confirme com soro agitado antes de aspirar volume.'],
    diferencaDoNormal: 'Cena de procedimento: a diferença que importa é antes/depois — o colapso do VD desaparece com os primeiros 50 mL.',
    conduta: 'Retire o que for necessário para reverter o tamponamento; deixe cateter se recidivante. Envie líquido para análise.',
    diferencial: [],
  },
  {
    id: 'derrame-com-ascite',
    titulo: 'Derrame pericárdico, pleural e ascite',
    estado: 'alterado',
    diagnostico: 'Poliserosite: derrames em três cavidades.',
    achado: 'Na mesma janela subxifoide, líquido no pericárdio, líquido pleural esquerdo atrás da aorta descendente e ascite ao redor do fígado. Cada um em seu compartimento.',
    leitura: ['Pericárdio: o líquido fica anterior à aorta descendente.', 'Pleural: posterior à aorta descendente.', 'Ascite: sob o diafragma, ao redor do fígado.'],
    diferencaDoNormal: 'A anatomia separa os três: a aorta descendente é a fronteira entre pericárdio e pleura, e o diafragma entre tórax e abdome. Saber isso evita drenar o compartimento errado.',
    conduta: 'Procure causa sistêmica: insuficiência cardíaca, cirrose, nefrose, lúpus, hipotireoidismo, neoplasia.',
    diferencial: ['Derrame pleural isolado confundido com pericárdico'],
  },
]
