import type { CenaClinica, JanelaUltrassom } from './esquemas'

/**
 * Cenas adicionais de pelve e obstetrícia, partes moles e sistema
 * musculoesquelético — e a janela nova do olho.
 */
export const CENAS_OBSTETRICO: CenaClinica[] = [
  {
    id: 'batimentos-fetais',
    titulo: 'Batimentos fetais no modo M',
    estado: 'alterado',
    diagnostico: 'Gestação viável — atividade cardíaca fetal documentada.',
    achado: 'Cursor do modo M sobre o coração do embrião: traçado ondulado regular; a frequência se mede entre dois picos (normal 110 a 160 bpm; < 100 bpm antes de 7 semanas prediz perda).',
    leitura: ['Ache o polo embrionário e o ponto que pisca.', 'Modo M, não Doppler: menos energia sobre o embrião.', 'Meça a frequência entre dois batimentos.'],
    diferencaDoNormal: 'É o normal registrado — e o que separa aborto retido de gestação viável. Batimento presente com sangramento é ameaça de aborto, não aborto.',
    conduta: 'Viável: tranquilizar, acompanhar. Bradicardia < 100 bpm: repetir em uma semana.',
    diferencial: ['Pulsação materna transmitida (frequência igual ao pulso da mãe)'],
  },
  {
    id: 'gestacao-anembrionada',
    titulo: 'Gestação anembrionada',
    estado: 'alterado',
    diagnostico: 'Saco gestacional sem embrião — ovo anembrionado.',
    achado: 'Saco gestacional intrauterino com diâmetro médio ≥ 25 mm sem embrião nem vesícula vitelina, ou saco menor que não desenvolve embrião em duas semanas.',
    leitura: ['Meça o diâmetro médio do saco nos três eixos.', '≥ 25 mm sem embrião (transvaginal): diagnóstico.', '< 25 mm: repita em 7 a 14 dias antes de concluir.'],
    diferencaDoNormal: 'Com 25 mm de saco, o embrião já deveria ter 5 a 6 semanas e batimento. Saco grande e vazio é gestação que parou no início.',
    conduta: 'Confirmado: conduta expectante, misoprostol ou aspiração. Nunca conclua num exame só quando o saco é pequeno.',
    diferencial: ['Gestação muito inicial', 'Pseudossaco da ectópica (central, sem anel duplo)'],
  },
  {
    id: 'aborto-espontaneo',
    titulo: 'Aborto espontâneo',
    estado: 'alterado',
    diagnostico: 'Aborto retido ou em curso.',
    achado: 'Embrião com comprimento cabeça-nádega ≥ 7 mm **sem batimento** (retido); ou material heterogêneo no útero com colo aberto e saco deformado (em curso); ou útero vazio com endométrio espesso após sangramento (completo).',
    leitura: ['Meça o embrião e procure batimento por 30 segundos.', '≥ 7 mm sem batimento: retido.', 'Colo aberto e material saindo: em curso.'],
    diferencaDoNormal: 'A gestação normal tem embrião com batimento proporcional ao tamanho. A ausência, uma vez confirmada com os critérios, é definitiva — e critérios frouxos já interromperam gestações viáveis.',
    conduta: 'Retido: expectante, medicamentoso ou cirúrgico. Em curso com sangramento intenso: aspiração. Imunoglobulina anti-D se Rh negativo.',
    diferencial: ['Gestação viável muito inicial', 'Ectópica com endométrio decidual'],
  },
  {
    id: 'mola',
    titulo: 'Mola hidatiforme',
    estado: 'alterado',
    diagnostico: 'Doença trofoblástica gestacional.',
    achado: 'Útero aumentado cheio de material heterogêneo com múltiplos cistos pequenos — "tempestade de neve" ou "cacho de uvas" — sem embrião (mola completa). Cistos tecaluteínicos nos ovários. Beta-hCG muito alto.',
    leitura: ['Útero maior que a idade gestacional.', 'Veja os cistos e a ausência de feto.', 'Olhe os ovários.'],
    diferencaDoNormal: 'O trofoblasto prolifera sem embrião e vira vesículas. Beta-hCG desproporcional, hiperêmese, sangramento com vesículas — e risco de coriocarcinoma.',
    conduta: 'Aspiração e seguimento de beta-hCG até negativar; contracepção durante o seguimento. Quimioterapia se persistência.',
    diferencial: ['Aborto retido com degeneração', 'Mioma degenerado'],
  },
  {
    id: 'ectopica-rota',
    titulo: 'Ectópica rota com FAST positivo',
    estado: 'alterado',
    diagnostico: 'Gravidez ectópica rota com hemoperitônio.',
    achado: 'Útero vazio, massa anexial e líquido livre com ecos na pelve e no espaço de Morison. Beta-hCG positivo. Paciente com dor e choque.',
    leitura: ['Beta-hCG positivo sem gestação intrauterina: procure líquido.', 'Líquido no Morison em ectópica = hemoperitônio volumoso.', 'Não perca tempo procurando a massa: o líquido decide.'],
    diferencaDoNormal: 'A ectópica íntegra dá massa anexial e pouco líquido. Rota, o sangue enche a pelve e sobe. Líquido no Morison prediz necessidade de cirurgia com alta especificidade.',
    conduta: 'Laparoscopia ou laparotomia imediata; sangue e reposição.',
    diferencial: ['Cisto ovariano roto', 'Corpo lúteo hemorrágico'],
  },
  {
    id: 'gemelar',
    titulo: 'Gestação gemelar',
    estado: 'alterado',
    diagnostico: 'Gestação múltipla — corionicidade.',
    achado: 'Dois sacos gestacionais separados por membrana espessa com sinal do lambda (dicoriônica) ou um saco com dois embriões e membrana fina em T (monocoriônica diamniótica).',
    leitura: ['Conte os sacos e os embriões.', 'Olhe a membrana e a sua inserção na placenta: lambda ou T.', 'Documente antes de 14 semanas — depois fica difícil.'],
    diferencaDoNormal: 'A corionicidade define o risco: monocoriônicas compartilham placenta e podem ter transfusão feto-fetal. É o dado mais importante do primeiro trimestre gemelar.',
    conduta: 'Encaminhar para pré-natal de alto risco; monocoriônicas com controle a cada 2 semanas a partir de 16 semanas.',
    diferencial: ['Saco com hematoma subcoriônico imitando segundo saco'],
  },
  {
    id: 'diu',
    titulo: 'DIU — posição',
    estado: 'alterado',
    diagnostico: 'Dispositivo intrauterino: posição correta ou deslocado.',
    achado: 'Haste ecogênica linear com sombra, no fundo da cavidade endometrial, sagital e transversal. Deslocado: no colo, no miométrio (perfuração parcial) ou ausente (expulso ou na cavidade abdominal).',
    leitura: ['Sagital: haste do fundo ao istmo.', 'Transversal: os braços.', 'Não achou: radiografia de abdome — pode estar no peritônio.'],
    diferencaDoNormal: 'Posição correta é no fundo, envolvido pelo endométrio. Baixo ou no miométrio, falha e machuca. Ausente com fio invisível não é expulsão até provar.',
    conduta: 'Bem posicionado: nada. Baixo: retirar e reinserir. Perfuração: retirada laparoscópica.',
    diferencial: ['Calcificação endometrial', 'Sinéquias'],
  },
  {
    id: 'cisto-ovariano',
    titulo: 'Cisto ovariano',
    estado: 'alterado',
    diagnostico: 'Cisto ovariano simples ou hemorrágico.',
    achado: 'Simples: anecoico, parede fina, reforço posterior. Hemorrágico: conteúdo em rede de fibrina ("teia"), coágulo retrátil, sem fluxo interno. Corpo lúteo: parede espessa com anel vascular ("anel de fogo" ovariano).',
    leitura: ['Classifique: simples, hemorrágico, complexo.', 'Doppler: fluxo interno é suspeito; fluxo só na parede é corpo lúteo.', 'Meça: < 5 cm simples resolve sozinho.'],
    diferencaDoNormal: 'O folículo normal tem até 2,5 cm. Além disso é cisto — a maioria funcional e transitória. O padrão em rede do hemorrágico é característico e não precisa de cirurgia.',
    conduta: 'Simples < 5 cm: repetir em 6 a 12 semanas. Hemorrágico com dor: analgesia. Complexo com componente sólido ou fluxo interno: investigar neoplasia.',
    diferencial: ['Ectópica', 'Endometrioma (vidro fosco)', 'Teratoma', 'Abscesso tubo-ovariano'],
  },
  {
    id: 'torcao-ovariana',
    titulo: 'Torção ovariana',
    estado: 'alterado',
    diagnostico: 'Torção anexial — emergência cirúrgica.',
    achado: 'Ovário aumentado, edemaciado, com folículos periféricos ("colar de pérolas"), frequentemente com cisto ou teratoma de base; fluxo venoso ausente e arterial reduzido ao Doppler; pedículo torcido em redemoinho; líquido livre.',
    leitura: ['Compare o volume com o ovário contralateral.', 'Doppler: ausência de fluxo venoso é o achado mais confiável — o arterial pode persistir.', 'Fluxo presente não afasta torção: a clínica manda.'],
    diferencaDoNormal: 'O ovário normal tem fluxo arterial e venoso. Torcido, a veia oclui primeiro, o ovário incha, e a artéria pode ainda pulsar — a armadilha clássica.',
    conduta: 'Laparoscopia com destorção; não espere o Doppler "confirmar". Dor súbita com ovário grande é torção até prova em contrário.',
    diferencial: ['Cisto hemorrágico', 'Apendicite', 'Ectópica'],
  },
  {
    id: 'teratoma',
    titulo: 'Teratoma ovariano',
    estado: 'alterado',
    diagnostico: 'Cisto dermoide.',
    achado: 'Massa anexial com componente muito ecogênico e sombra ("ponta do iceberg"), níveis gordura-líquido, focos calcificados (dente), linhas e pontos de cabelo ("dermoid mesh").',
    leitura: ['Note a heterogeneidade e a sombra.', 'Nível gordura-líquido é característico.', 'Meça: > 5 cm tem risco de torção.'],
    diferencaDoNormal: 'Tecido de várias linhagens dentro do ovário — gordura, cabelo, dente. Nenhum outro cisto tem gordura com sombra.',
    conduta: 'Cistectomia eletiva; urgente se torção.',
    diferencial: ['Alça intestinal com gás', 'Endometrioma', 'Cisto hemorrágico'],
  },
  {
    id: 'miomas',
    titulo: 'Útero com miomas',
    estado: 'alterado',
    diagnostico: 'Leiomiomas uterinos.',
    achado: 'Nódulos miometriais bem delimitados, hipoecoicos e heterogêneos, com sombra em leque e vascularização periférica; útero aumentado e de contorno lobulado. Submucosos deformam a cavidade.',
    leitura: ['Conte, meça e localize: subseroso, intramural, submucoso.', 'Veja a relação com a cavidade — submucoso sangra.', 'Degeneração: áreas císticas ou calcificação.'],
    diferencaDoNormal: 'O miométrio é homogêneo. O mioma é um nódulo de músculo liso encapsulado — o tumor benigno mais comum da mulher.',
    conduta: 'Assintomático: nada. Sangramento ou volume: tratamento medicamentoso, embolização ou cirurgia.',
    diferencial: ['Adenomiose (difusa, sem cápsula)', 'Sarcoma (raro, crescimento rápido)', 'Massa ovariana'],
  },
  {
    id: 'comprimento-cabeca-nadega',
    titulo: 'Comprimento cabeça-nádega — datação',
    estado: 'alterado',
    diagnostico: 'Datação da gestação no primeiro trimestre.',
    achado: 'Embrião medido da cabeça à nádega, em posição neutra, excluindo a vesícula vitelina e os membros. Idade gestacional ≈ CCN (mm) + 42 dias. É a medida mais precisa (± 5 dias).',
    leitura: ['Maior eixo do embrião, sem incluir a vesícula.', 'Três medidas, use a média.', 'Compare com a data da última menstruação: > 7 dias de diferença, a idade ecográfica prevalece.'],
    diferencaDoNormal: 'Cena de referência: a datação correta é o que faz todos os outros marcos (viabilidade, termo, crescimento) fazerem sentido.',
    conduta: 'Definir a idade gestacional no primeiro exame.',
    diferencial: [],
  },
  {
    id: 'saco-e-vesicula-vitelina',
    titulo: 'Saco gestacional e vesícula vitelina',
    estado: 'alterado',
    diagnostico: 'Gestação intrauterina inicial — os primeiros marcos.',
    achado: 'Saco gestacional excêntrico no endométrio com anel duplo (decídua) a partir de 5 semanas; vesícula vitelina como anel brilhante dentro dele a partir de 5,5 semanas; polo embrionário a partir de 6.',
    leitura: ['Saco excêntrico com anel duplo: gestação intrauterina.', 'Vesícula vitelina: confirma — o pseudossaco da ectópica não tem.', 'Vesícula > 6 mm ou saco sem vesícula com 20 mm: mau prognóstico.'],
    diferencaDoNormal: 'Cena de referência: a vesícula vitelina é o primeiro achado que **prova** gestação intrauterina — e afasta ectópica com útero de pseudossaco.',
    conduta: 'Gestação intrauterina confirmada: pré-natal. Repetir em 1 a 2 semanas se só há saco.',
    diferencial: ['Pseudossaco da ectópica', 'Cisto endometrial'],
  },
  {
    id: 'diametro-biparietal',
    titulo: 'Diâmetro biparietal — 2º trimestre',
    estado: 'alterado',
    diagnostico: 'Biometria fetal no segundo trimestre.',
    achado: 'Corte transversal da cabeça no nível dos tálamos e do cavo do septo pelúcido, com a foice da mesma linha; mede-se da tábua externa proximal à interna distal. Tabela dá a idade e o percentil.',
    leitura: ['Ache o plano: tálamos, cavo do septo, sem cerebelo.', 'Meça externa-interna.', 'Some fêmur e circunferência abdominal para o peso.'],
    diferencaDoNormal: 'Cena de referência da biometria. No pronto-socorro serve para estimar a idade quando não há pré-natal — e para decidir a viabilidade num parto iminente.',
    conduta: 'Estimar a idade e o peso; encaminhar.',
    diferencial: [],
  },
  {
    id: 'colo-dilatado',
    titulo: 'Colo dilatado com bolsa protrusa',
    estado: 'alterado',
    diagnostico: 'Insuficiência cervical ou trabalho de parto prematuro.',
    achado: 'Colo curto (< 25 mm) ou apagado, com as membranas abaulando pelo orifício interno em funil ou protruindo para a vagina.',
    leitura: ['Transvaginal, bexiga vazia: meça o colo do orifício interno ao externo.', 'Veja o funil.', 'Bolsa protruindo: não toque.'],
    diferencaDoNormal: 'O colo normal no segundo trimestre tem > 30 mm e orifício interno fechado. Curto com funil é risco de prematuridade; bolsa protrusa é emergência.',
    conduta: 'Colo curto: progesterona ou cerclagem conforme história. Bolsa protrusa: cerclagem de emergência ou conduta expectante em decúbito, conforme idade gestacional e infecção.',
    diferencial: ['Segmento inferior mal distendido imitando funil', 'Contração'],
  },
  {
    id: 'abscesso-de-bartholin',
    titulo: 'Abscesso de Bartholin',
    estado: 'alterado',
    diagnostico: 'Abscesso da glândula de Bartholin.',
    achado: 'Coleção hipoecoica com ecos e parede espessa e hiperemiada no terço posterior do grande lábio; tecido ao redor edemaciado.',
    leitura: ['Sonda linear sobre a tumoração vulvar.', 'Coleção com conteúdo: abscesso; anecoica sem hiperemia: cisto.', 'Marque o ponto de drenagem.'],
    diferencaDoNormal: 'A glândula não se vê. Obstruída, vira cisto; infectada, abscesso — quente e doloroso.',
    conduta: 'Drenagem com cateter de Word ou marsupialização; antibiótico se celulite.',
    diferencial: ['Cisto de Bartholin', 'Hérnia vulvar', 'Hematoma'],
  },
]

export const CENAS_PARTES_MOLES: CenaClinica[] = [
  {
    id: 'celulite',
    titulo: 'Celulite — paralelepípedo',
    estado: 'alterado',
    diagnostico: 'Celulite sem abscesso.',
    achado: 'Subcutâneo espessado e hiperecoico, com traves anecoicas de edema separando lóbulos de gordura — o padrão em "paralelepípedo" (cobblestoning). Sem coleção.',
    leitura: ['Compare com a pele sã contralateral.', 'Note as traves de líquido entre a gordura.', 'Comprima: sem coleção que se mova — não há abscesso.'],
    diferencaDoNormal: 'O subcutâneo normal é homogêneo. O edema inflamatório o infiltra e o divide em pedras de calçamento. É celulite; o que o exame procura é se já virou abscesso.',
    conduta: 'Antibiótico oral ou venoso; sem drenagem. Reexaminar se não melhorar em 48 h — abscesso pode surgir.',
    diferencial: ['Edema de estase (bilateral, sem dor)', 'Linfedema', 'TVP'],
  },
  {
    id: 'fasciite-necrosante',
    titulo: 'Fasciíte necrosante — gás na fáscia',
    estado: 'alterado',
    diagnostico: 'Infecção necrosante de partes moles.',
    achado: 'Fáscia espessada e irregular com líquido anecoico ao longo dela (> 4 mm), e focos de **gás** — ecos brilhantes com sombra suja e reverberação — dissecando os planos. Subcutâneo com celulite.',
    leitura: ['Procure líquido ao longo da fáscia profunda.', 'Gás: brilho com sombra suja que muda de lugar.', 'Dor desproporcional com este achado: não espere a tomografia.'],
    diferencaDoNormal: 'A celulite fica no subcutâneo. A fasciíte segue a fáscia, acumula líquido nela e produz gás — e avança centímetros por hora.',
    conduta: 'Desbridamento cirúrgico imediato e antibiótico de amplo espectro. Sensibilidade do ultrassom ~90% para o líquido fascial.',
    diferencial: ['Celulite grave', 'Piomiosite', 'Gangrena gasosa'],
  },
  {
    id: 'corpo-estranho',
    titulo: 'Corpo estranho — madeira e vidro',
    estado: 'alterado',
    diagnostico: 'Corpo estranho radiotransparente em partes moles.',
    achado: 'Foco linear hiperecoico com sombra acústica (madeira, espinho) ou reverberação (vidro, metal); após dias, halo hipoecoico de reação inflamatória ao redor.',
    leitura: ['Sonda linear, bastante gel ou imersão em água para objetos superficiais.', 'Dois planos: o objeto é linear em um e pontual no outro.', 'Meça a profundidade e marque a pele para a retirada.'],
    diferencaDoNormal: 'Madeira e plástico não aparecem na radiografia. O ultrassom os vê, e o halo inflamatório os denuncia mesmo quando pequenos.',
    conduta: 'Retirada guiada; antibiótico se madeira ou vegetal (infecta sempre). Vacinar contra tétano.',
    diferencial: ['Calcificação', 'Gás após ferida', 'Tendão em corte transversal'],
  },
  {
    id: 'linfadenite',
    titulo: 'Linfadenite',
    estado: 'alterado',
    diagnostico: 'Linfonodo reativo ou supurado.',
    achado: 'Linfonodo aumentado, oval, com hilo ecogênico preservado e fluxo hilar ao Doppler (reativo); supurado: centro hipoecoico sem fluxo, parede espessa. Suspeito de malignidade: redondo, sem hilo, fluxo periférico.',
    leitura: ['Forma: oval é reativo; redondo é suspeito.', 'Hilo: preservado é benigno.', 'Doppler: hilar é benigno; periférico ou caótico é suspeito.'],
    diferencaDoNormal: 'O linfonodo normal é pequeno, oval, com hilo. Inflamado cresce mas mantém a arquitetura; infiltrado por tumor perde o hilo e arredonda.',
    conduta: 'Reativo: tratar a causa. Supurado: drenagem. Suspeito: biópsia.',
    diferencial: ['Abscesso', 'Cisto branquial', 'Metástase', 'Linfoma'],
  },
  {
    id: 'cisto-epidermoide',
    titulo: 'Cisto epidermoide',
    estado: 'alterado',
    diagnostico: 'Cisto epidérmico de inclusão.',
    achado: 'Nódulo bem delimitado no subcutâneo, hipoecoico com ecos internos finos ("pseudotesticular"), reforço posterior, sem fluxo interno; conectado à derme por um trato. Roto: bordas irregulares e hiperemia.',
    leitura: ['Nódulo oval com conteúdo homogêneo e reforço.', 'Sem fluxo dentro.', 'Roto e inflamado: parece abscesso.'],
    diferencaDoNormal: 'Queratina encapsulada: parece sólido mas é cisto — o reforço posterior denuncia. Não drenar como abscesso.',
    conduta: 'Excisão eletiva com a cápsula; inflamado: antibiótico e depois excisão.',
    diferencial: ['Lipoma', 'Abscesso', 'Nódulo sólido'],
  },
  {
    id: 'abscesso-periamigdaliano',
    titulo: 'Abscesso periamigdaliano',
    estado: 'alterado',
    diagnostico: 'Abscesso peritonsilar.',
    achado: 'Sonda endocavitária ou linear pequena na boca, sobre a amígdala: coleção hipoecoica com ecos e parede irregular entre a amígdala e o constritor, com a carótida interna alguns milímetros posterior.',
    leitura: ['Anestesie a garganta; sonda endocavitária coberta.', 'Coleção atrás da amígdala.', 'Marque a carótida antes de puncionar.'],
    diferencaDoNormal: 'Celulite peritonsilar não tem coleção; abscesso tem. A diferença é uma agulha — e a carótida está a 1 cm dela.',
    conduta: 'Aspiração ou incisão guiada; antibiótico. Sem coleção: antibiótico e reavaliar.',
    diferencial: ['Celulite peritonsilar', 'Abscesso parafaríngeo', 'Tumor'],
  },
  {
    id: 'epiglotite',
    titulo: 'Epiglotite',
    estado: 'alterado',
    diagnostico: 'Epiglotite aguda.',
    achado: 'Sonda linear longitudinal sobre a membrana tireo-hióidea: epiglote espessada (> 5 mm em adulto), hipoecoica, em "P" ou "polegar" — o sinal da letra P. Espaço pré-epiglótico aumentado.',
    leitura: ['Paciente sentado, sonda na linha média entre hioide e tireoide.', 'Meça a epiglote.', 'Não deite o paciente para o exame.'],
    diferencaDoNormal: 'A epiglote normal é fina (~2 a 3 mm). Inflamada, engrossa e ameaça a via aérea — e o ultrassom a vê sem abrir a boca de quem pode fechar a glote.',
    conduta: 'Via aérea garantida por quem sabe intubar difícil; antibiótico venoso. Não manipular a orofaringe.',
    diferencial: ['Abscesso retrofaríngeo', 'Angioedema', 'Laringite'],
  },
  {
    id: 'tireoide',
    titulo: 'Tireoide — lobo normal e inferno',
    estado: 'alterado',
    diagnostico: 'Tireoide normal e tireoide hipervascular (Graves ou tempestade).',
    achado: 'Lobo normal homogêneo, um pouco mais ecogênico que o músculo, ao lado da carótida. Na doença de Graves, glândula aumentada, hipoecoica, com fluxo intenso ao Doppler — o "inferno tireoidiano".',
    leitura: ['Transversal: istmo e dois lobos.', 'Textura: homogênea é normal; hipoecoica e heterogênea é tireoidite ou Graves.', 'Doppler: o inferno é diagnóstico em contexto de hipertireoidismo.'],
    diferencaDoNormal: 'A glândula normal tem pouco fluxo visível. Estimulada pelos anticorpos, dilata os vasos até parecer que pega fogo.',
    conduta: 'Hipertireoidismo com inferno: Graves — antitireoidiano, betabloqueador. Tempestade: emergência.',
    diferencial: ['Tireoidite de Hashimoto (fluxo variável)', 'Tireoidite subaguda (fluxo baixo)', 'Nódulo tóxico'],
  },
  {
    id: 'sialolitiase',
    titulo: 'Sialolitíase e sialadenite',
    estado: 'alterado',
    diagnostico: 'Cálculo salivar com glândula inflamada.',
    achado: 'Foco ecogênico com sombra no ducto ou dentro da glândula submandibular; ducto dilatado a montante; glândula aumentada, hipoecoica e hiperemiada. Abscesso como coleção.',
    leitura: ['Sonda linear sob a mandíbula.', 'Siga o ducto até o cálculo.', 'Glândula inchada e com fluxo: sialadenite.'],
    diferencaDoNormal: 'A glândula normal é homogênea, ducto invisível. Cálculo obstrui, o ducto dilata e a glândula infecta — dor que piora ao comer.',
    conduta: 'Hidratação, sialogogos, massagem, antibiótico; remoção do cálculo se não sair.',
    diferencial: ['Linfadenite submandibular', 'Abscesso dentário', 'Tumor'],
  },
  {
    id: 'piomiosite',
    titulo: 'Piomiosite e abscesso intramuscular',
    estado: 'alterado',
    diagnostico: 'Infecção bacteriana do músculo.',
    achado: 'Músculo aumentado e heterogêneo com perda do padrão fibrilar; coleção hipoecoica com ecos dentro dele (abscesso intramuscular), hiperemia ao redor. Comum em imunossuprimidos, diabéticos e usuários de drogas injetáveis.',
    leitura: ['Compare com o músculo contralateral.', 'Coleção dentro do músculo, não no subcutâneo.', 'Comprima: o pus se move.'],
    diferencaDoNormal: 'A celulite fica acima da fáscia. Aqui a infecção está no músculo — mais profunda, mais febre, e a drenagem precisa alcançá-la.',
    conduta: 'Antibiótico anti-estafilocócico e drenagem guiada ou cirúrgica.',
    diferencial: ['Hematoma', 'Fasciíte', 'Tumor'],
  },
  {
    id: 'tenossinovite',
    titulo: 'Tenossinovite dos flexores',
    estado: 'alterado',
    diagnostico: 'Tenossinovite infecciosa da bainha flexora.',
    achado: 'Líquido anecoico ou com ecos distendendo a bainha ao redor do tendão flexor, em todo o trajeto do dedo; tendão espessado; hiperemia da bainha ao Doppler.',
    leitura: ['Sonda linear pequena, longitudinal e transversal no dedo; imersão em água ajuda.', 'Halo de líquido em volta do tendão.', 'Compare com o dedo vizinho.'],
    diferencaDoNormal: 'A bainha normal é virtual. Infectada, enche de pus e comprime o tendão — os quatro sinais de Kanavel são a clínica desta imagem.',
    conduta: 'Cirurgia urgente (irrigação da bainha) e antibiótico. Atraso destrói o tendão.',
    diferencial: ['Tenossinovite inflamatória', 'Celulite do dedo', 'Panarício'],
  },
  {
    id: 'felon',
    titulo: 'Panarício (felon)',
    estado: 'alterado',
    diagnostico: 'Abscesso da polpa digital.',
    achado: 'Coleção hipoecoica na polpa do dedo, entre os septos fibrosos, com hiperemia ao redor; osso subjacente íntegro ou com irregularidade se osteomielite.',
    leitura: ['Imersão em água, sonda sobre a polpa.', 'Coleção sob pressão nos compartimentos.', 'Olhe a cortical da falange.'],
    diferencaDoNormal: 'A polpa é compartimentada por septos; o pus fica preso sob pressão e necrosa — daí a dor intensa e a urgência.',
    conduta: 'Incisão e drenagem; antibiótico. Não confundir com paroníquia (ao redor da unha).',
    diferencial: ['Paroníquia', 'Panarício herpético (não drenar)', 'Osteomielite'],
  },
  {
    id: 'ruptura-de-aquiles',
    titulo: 'Ruptura do tendão de Aquiles',
    estado: 'alterado',
    diagnostico: 'Ruptura completa do Aquiles.',
    achado: 'Descontinuidade das fibras com hematoma entre os cotos, 2 a 6 cm acima da inserção; na flexão plantar passiva os cotos não se aproximam. Tendão normal: fibrilar, contínuo, 5 a 6 mm.',
    leitura: ['Decúbito ventral, longitudinal sobre o tendão.', 'Siga as fibras: o gap com líquido é a ruptura.', 'Mova o pé: cotos que não se movem juntos confirmam ruptura completa.'],
    diferencaDoNormal: 'O tendão é uma faixa de fibras paralelas. Rompido, as fibras se retraem e o espaço enche de sangue — e o teste de Thompson é esta imagem em movimento.',
    conduta: 'Ortopedia: cirurgia ou imobilização em equino conforme o gap e o paciente.',
    diferencial: ['Ruptura parcial', 'Tendinopatia', 'Ruptura do plantar delgado'],
  },
  {
    id: 'ruptura-patelar',
    titulo: 'Ruptura do tendão patelar',
    estado: 'alterado',
    diagnostico: 'Ruptura do tendão patelar ou do quadríceps.',
    achado: 'Descontinuidade do tendão abaixo (patelar) ou acima (quadríceps) da patela, com hematoma; patela deslocada para cima (patelar) ou para baixo (quadríceps). Incapaz de estender o joelho.',
    leitura: ['Longitudinal sobre o tendão com o joelho levemente fletido.', 'Gap com líquido e fibras retraídas.', 'Veja a posição da patela.'],
    diferencaDoNormal: 'O tendão contínuo transmite a força do quadríceps; rompido, o joelho não estende. A radiografia mostra só a patela fora do lugar; o ultrassom mostra o tendão.',
    conduta: 'Reparo cirúrgico precoce.',
    diferencial: ['Fratura de patela', 'Ruptura parcial', 'Bursite'],
  },
  {
    id: 'derrame-de-joelho',
    titulo: 'Derrame articular do joelho',
    estado: 'alterado',
    diagnostico: 'Derrame no recesso suprapatelar.',
    achado: 'Líquido anecoico no recesso suprapatelar, entre o tendão do quadríceps e o fêmur, que se desloca com a compressão; ecos ou septos se hemorrágico ou infectado. Sinovite: parede espessa e hiperemiada.',
    leitura: ['Joelho em 30° de flexão, sonda longitudinal acima da patela.', 'Meça a lâmina: > 2 mm é derrame.', 'Marque o ponto de punção lateral.'],
    diferencaDoNormal: 'O recesso normal é virtual. Cheio, é derrame — e o ultrassom diz onde puncionar e se o líquido é limpo.',
    conduta: 'Artrocentese guiada para análise (cristais, cultura); tratar a causa. Nunca puncione sem excluir celulite no trajeto.',
    diferencial: ['Bursite pré-patelar (superficial à patela)', 'Cisto de Baker'],
  },
  {
    id: 'artrite-septica',
    titulo: 'Artrite séptica',
    estado: 'alterado',
    diagnostico: 'Infecção articular — joelho, cotovelo.',
    achado: 'Derrame com ecos e sinóvia espessa e hiperemiada; cartilagem e osso podem estar irregulares se avançado. Nada no ultrassom distingue séptico de inflamatório com certeza — a punção decide.',
    leitura: ['Confirme o derrame e caracterize.', 'Doppler: sinóvia vascularizada.', 'Puncione: leucócitos > 50.000 e cultura.'],
    diferencaDoNormal: 'Derrame com sinovite é artrite. Febre, uma articulação e dor intensa: séptica até a punção dizer o contrário.',
    conduta: 'Punção imediata; antibiótico após a coleta; drenagem cirúrgica ou artroscópica.',
    diferencial: ['Gota', 'Artrite reativa', 'Hemartrose'],
  },
  {
    id: 'derrame-de-quadril',
    titulo: 'Derrame de quadril — sinovite transitória',
    estado: 'alterado',
    diagnostico: 'Derrame coxofemoral na criança que manca.',
    achado: 'Sonda linear longitudinal sobre o colo femoral: a cápsula anterior distendida por líquido (> 5 mm de distância osso-cápsula, ou > 2 mm de diferença entre os lados).',
    leitura: ['Compare sempre com o outro lado.', 'Meça a distância cápsula-colo.', 'Febre e leucocitose com derrame: puncione — artrite séptica.'],
    diferencaDoNormal: 'A cápsula normal encosta no colo. Distendida, há líquido; e a criança que manca com derrame de quadril precisa da distinção séptica × transitória em horas.',
    conduta: 'Sinovite transitória: repouso e anti-inflamatório. Critérios de Kocher altos: punção e cirurgia.',
    diferencial: ['Artrite séptica', 'Legg-Calvé-Perthes', 'Epifisiólise'],
  },
  {
    id: 'luxacao-de-ombro',
    titulo: 'Luxação anterior do ombro',
    estado: 'alterado',
    diagnostico: 'Luxação glenoumeral anterior.',
    achado: 'Sonda posterior sobre a glenoide: a cabeça umeral não está na cavidade — aparece **anterior** e mais profunda (longe da sonda). Na posterior, mais próxima. Fratura de Hill-Sachs como degrau na cabeça.',
    leitura: ['Sonda linear posterior, transversal, abaixo da espinha da escápula.', 'Ache a glenoide e procure a cabeça umeral: fora do lugar.', 'Após a redução, repita: a cabeça volta à cavidade.'],
    diferencaDoNormal: 'No ombro normal a cabeça encaixa na glenoide na mesma imagem. Luxada, some do encaixe — e o ultrassom confirma a luxação e a redução sem radiografia.',
    conduta: 'Redução após analgesia ou bloqueio guiado; confirmar com a mesma janela.',
    diferencial: ['Luxação posterior', 'Fratura do colo umeral'],
  },
  {
    id: 'reducao-de-ombro',
    titulo: 'Redução do ombro em tempo real',
    estado: 'alterado',
    diagnostico: 'Confirmação imediata da redução.',
    achado: 'Com a sonda posterior durante a manobra, a cabeça umeral desliza de volta para a glenoide; o alinhamento se restabelece e a rotação passiva mostra a cabeça girando no lugar.',
    leitura: ['Mantenha a sonda posterior durante a tração.', 'Veja a cabeça entrar.', 'Gire o braço: a cabeça roda dentro da cavidade.'],
    diferencaDoNormal: 'Cena de procedimento: substitui a radiografia pós-redução e encurta a permanência no pronto-socorro.',
    conduta: 'Reduzido: imobilização. Não reduzido: repetir a manobra.',
    diferencial: [],
  },
  {
    id: 'fratura-de-radio',
    titulo: 'Fratura de rádio distal',
    estado: 'alterado',
    diagnostico: 'Fratura do rádio distal — inclusive a fratura em torus da criança.',
    achado: 'Degrau, angulação ou descontinuidade na cortical brilhante do rádio, com hematoma; na criança, abaulamento da cortical sem descontinuidade (torus). Após redução, alinhamento restabelecido.',
    leitura: ['Sonda linear longitudinal nas quatro faces do rádio distal.', 'Siga a cortical: qualquer quebra é fratura.', 'Meça a angulação antes e depois da redução.'],
    diferencaDoNormal: 'A cortical é uma linha lisa e contínua. Quebrada, faz degrau. O ultrassom acha a fratura e guia a redução sem repetir radiografias.',
    conduta: 'Redução guiada e imobilização; ortopedia se articular ou instável.',
    diferencial: ['Fisiodesloca­mento (Salter-Harris)', 'Contusão'],
  },
  {
    id: 'fratura-de-cranio',
    titulo: 'Fratura de crânio',
    estado: 'alterado',
    diagnostico: 'Fratura de calota no lactente com hematoma subgaleal.',
    achado: 'Sob o hematoma do couro cabeludo, descontinuidade da cortical do osso, com ou sem afundamento; suturas normais são regulares e simétricas.',
    leitura: ['Sonda linear sobre o hematoma, em dois planos.', 'Quebra da cortical: fratura. Afundamento: cirurgia?', 'Não confunda com sutura: compare o lado oposto.'],
    diferencaDoNormal: 'O crânio é uma linha brilhante contínua entre as suturas. A fratura a interrompe onde não há sutura.',
    conduta: 'Fratura: tomografia para lesão intracraniana. Afundada: neurocirurgia.',
    diferencial: ['Sutura', 'Fontanela'],
  },
  {
    id: 'fratura-de-clavicula',
    titulo: 'Fratura de clavícula',
    estado: 'alterado',
    diagnostico: 'Fratura do terço médio da clavícula.',
    achado: 'Descontinuidade ou cavalgamento dos fragmentos na cortical clavicular, com hematoma; na criança, angulação sem desvio (galho verde). No recém-nascido, fratura obstétrica.',
    leitura: ['Longitudinal ao longo da clavícula.', 'Ache o degrau e meça o desvio.', 'Veja o pulmão abaixo: pneumotórax raro.'],
    diferencaDoNormal: 'Linha cortical interrompida. A clavícula é superficial e o ultrassom a vê inteira — mais sensível que a radiografia no recém-nascido.',
    conduta: 'Tipoia; cirurgia se desvio grande ou encurtamento.',
    diferencial: ['Luxação acromioclavicular', 'Contusão'],
  },
  {
    id: 'lipohemartrose',
    titulo: 'Lipohemartrose — fratura intra-articular',
    estado: 'alterado',
    diagnostico: 'Gordura e sangue na articulação — fratura oculta.',
    achado: 'No recesso suprapatelar, o derrame se separa em camadas: gordura ecogênica flutuando por cima, sangue por baixo, com nível nítido entre elas. Só a gordura da medula produz esse nível.',
    leitura: ['Joelho em repouso alguns minutos.', 'Veja o nível gordura-sangue.', 'Radiografia negativa com este achado: tomografia.'],
    diferencaDoNormal: 'Derrame simples é homogêneo. O nível de gordura prova que o osso quebrou até a medula — mesmo que a radiografia não mostre.',
    conduta: 'Tratar como fratura intra-articular: imobilizar, tomografia.',
    diferencial: ['Hemartrose sem fratura', 'Derrame séptico com debris'],
  },
  {
    id: 'pronacao-dolorosa',
    titulo: 'Pronação dolorosa',
    estado: 'alterado',
    diagnostico: 'Subluxação da cabeça do rádio (cotovelo de babá).',
    achado: 'Sonda linear sobre a cabeça do rádio: o ligamento anular deslocado e o músculo supinador interposto entre a cabeça do rádio e o capítulo ("sinal do J" ou espessamento do supinador). Após a redução, anatomia normal.',
    leitura: ['Compare com o outro braço.', 'Veja o tecido interposto na articulação radiocapitular.', 'Reduza e confirme.'],
    diferencaDoNormal: 'A tração puxa a cabeça do rádio para fora do ligamento anular; a criança para de usar o braço. A redução devolve tudo ao lugar em segundos.',
    conduta: 'Redução por hiperpronação ou supinação-flexão; não precisa de radiografia se a história é típica.',
    diferencial: ['Fratura supracondiliana', 'Fratura do colo do rádio'],
  },
  {
    id: 'fascite-plantar',
    titulo: 'Fascite plantar',
    estado: 'alterado',
    diagnostico: 'Fasciopatia plantar na inserção calcânea.',
    achado: 'Fáscia plantar espessada (> 4 mm) e hipoecoica na inserção no calcâneo, com perda do padrão fibrilar; às vezes esporão e líquido perifascial.',
    leitura: ['Longitudinal na planta, na origem calcânea.', 'Meça a espessura e compare com o outro pé.', 'Ruptura: descontinuidade.'],
    diferencaDoNormal: 'A fáscia normal tem ~3 mm e fibras nítidas. Degenerada, engrossa e escurece — e o ultrassom exclui ruptura e guia a infiltração.',
    conduta: 'Alongamento, palmilha, fisioterapia; infiltração guiada em casos refratários.',
    diferencial: ['Ruptura da fáscia', 'Fratura de estresse do calcâneo', 'Neuropatia de Baxter'],
  },
  {
    id: 'hematoma-do-reto',
    titulo: 'Hematoma do reto abdominal',
    estado: 'alterado',
    diagnostico: 'Hematoma da bainha do reto — anticoagulado, tosse, esforço.',
    achado: 'Massa heterogênea, fusiforme, dentro do músculo reto abdominal, que não cruza a linha média (acima da linha arqueada) e não muda com a contração; sem fluxo. Fibras rompidas ao redor.',
    leitura: ['Sonda linear sobre a massa dolorosa da parede.', 'Massa dentro do músculo, sem peristalse.', 'Doppler: sem fluxo; extravasamento ativo é raro mas grave.'],
    diferencaDoNormal: 'O músculo é fibrilar e homogêneo. O hematoma é a bolsa de sangue que o substitui — dor de parede que imita abdome agudo, sobretudo no anticoagulado.',
    conduta: 'Conservador na maioria; reverter anticoagulação se grande; embolização se ativo.',
    diferencial: ['Hérnia', 'Tumor de parede', 'Abscesso', 'Apendicite (o hematoma do lado direito engana)'],
  },
  {
    id: 'gota',
    titulo: 'Gota — cristais de urato',
    estado: 'alterado',
    diagnostico: 'Artropatia por cristais de urato.',
    achado: 'Linha hiperecoica sobre a cartilagem hialina, paralela ao osso — o **duplo contorno**; tofos como agregados heterogêneos com sombra; erosões ósseas com bordas salientes; derrame com pontos brilhantes ("tempestade").',
    leitura: ['Joelho ou primeira metatarsofalângica: procure o duplo contorno.', 'Veja tofos e erosões.', 'Puncione o derrame: cristais confirmam.'],
    diferencaDoNormal: 'A cartilagem é uma faixa escura sobre o osso branco. O urato se deposita na superfície dela e cria uma segunda linha branca — específico de gota.',
    conduta: 'Crise: anti-inflamatório ou colchicina. Crônica: hipouricemiante até ácido úrico < 6 mg/dL.',
    diferencial: ['Pseudogota (calcificação dentro da cartilagem)', 'Artrite séptica'],
  },
]

/**
 * O olho — a janela nova.
 *
 * O ultrassom ocular entra na semiologia porque responde, em dois minutos e
 * sem dilatar, à pergunta que o fundo de olho às vezes não consegue: a retina
 * está no lugar? o nervo óptico está inchado? Numa perda visual aguda ou
 * num trauma com pálpebra fechada por edema, é o único exame possível ali.
 */
export const JANELA_OLHO: JanelaUltrassom = {
  slug: 'olho',
  nome: 'Ultrassom ocular',
  protocolo: 'Ocular POCUS',
  transdutor: 'linear',
  posicao:
    'Pálpebra fechada, gel abundante (sem tocar o olho), sonda linear transversal sobre a pálpebra superior apoiada na órbita — não no globo. Marcador para a direita do paciente.',
  pergunta: 'A retina está descolada? A bainha do nervo óptico está dilatada? Há hemorragia ou corpo estranho?',
  profundidade: '4 a 5 cm, ganho baixo para o vítreo e alto para membranas finas.',
  comoFazer: [
    { passo: 'Apoie a mão na face do paciente e a sonda na órbita, nunca no globo.', detalhe: 'Pressão sobre o olho dói, distorce e, com globo roto, expulsa o conteúdo. A mão apoiada garante que o peso não cai no olho.' },
    { passo: 'Percorra o globo em transversal e sagital.', detalhe: 'O olho é uma esfera: um plano não vê tudo. Membranas finas aparecem num plano e somem no outro.' },
    { passo: 'Peça para o paciente mover os olhos com as pálpebras fechadas.', detalhe: 'Movimento ("cinemática") é o que separa descolamento de retina (membrana rígida presa ao disco) de descolamento de vítreo (membrana fina que flutua livre).' },
    { passo: 'Meça a bainha do nervo óptico 3 mm atrás do globo.', detalhe: 'É onde a bainha é mais distensível. > 5 mm sugere pressão intracraniana elevada. Meça nos dois olhos.' },
    { passo: 'Aumente o ganho para ver hemorragia vítrea.', detalhe: 'Sangue no vítreo é sutil no ganho baixo. Subindo o ganho, os ecos aparecem e se movem com o olho — a máquina de lavar.' },
  ],
  estruturas: [],
  cenas: [
    {
      id: 'olho-normal',
      titulo: 'Olho normal',
      estado: 'normal',
      diagnostico: 'Globo ocular sem alterações.',
      achado: 'Câmara anterior anecoica, íris e cristalino (lente biconvexa com bordas brilhantes), vítreo **anecoico e homogêneo**, retina aderida à parede (invisível), nervo óptico como faixa hipoecoica saindo posteriormente com bainha < 5 mm.',
      leitura: ['Câmara anterior, cristalino e vítreo, da frente para trás.', 'Vítreo preto e limpo — nada flutuando.', 'Nervo óptico reto atrás do globo.'],
      diferencaDoNormal: 'É a referência.',
      conduta: 'Nenhuma.',
      diferencial: [],
    },
    {
      id: 'bainha-do-nervo-optico',
      titulo: 'Bainha do nervo óptico — hipertensão intracraniana',
      estado: 'alterado',
      diagnostico: 'Pressão intracraniana elevada estimada pela bainha.',
      achado: 'Bainha do nervo óptico medida 3 mm atrás do globo com diâmetro > 5 mm (> 5,5 a 6 mm é mais específico); às vezes papila protruindo para o vítreo (papiledema ecográfico) e sinal do crescente.',
      leitura: ['Localize o nervo saindo do polo posterior.', 'Marque 3 mm atrás da retina e meça a largura da bainha (borda externa a externa).', 'Média dos dois olhos; > 5 mm em cefaleia, trauma ou coma sugere hipertensão intracraniana.'],
      diferencaDoNormal: 'A bainha é contínua com o espaço subaracnóideo: quando a pressão sobe, o líquor a infla. É o único ponto do crânio onde a pressão intracraniana pode ser vista de fora.',
      conduta: 'Tomografia urgente; medidas para pressão intracraniana conforme a causa. Sensibilidade ~90% para PIC > 20 mmHg; útil onde não há monitor invasivo.',
      diferencial: ['Neurite óptica', 'Variação anatômica', 'Medida inclinada'],
    },
    {
      id: 'bainha-normal',
      titulo: 'Bainha do nervo óptico normal',
      estado: 'alterado',
      diagnostico: 'Bainha < 5 mm — pressão intracraniana provavelmente normal.',
      achado: 'Nervo óptico com bainha de 3 a 4,5 mm a 3 mm do globo, papila plana.',
      leitura: ['Mesma técnica.', '< 5 mm: pressão provavelmente normal.', 'Guarde para comparar com medições seriadas.'],
      diferencaDoNormal: 'É a medida normal registrada — o par da cena anterior.',
      conduta: 'Bainha normal em paciente de baixo risco reduz a probabilidade de hipertensão intracraniana; não substitui a tomografia quando há déficit.',
      diferencial: [],
    },
    {
      id: 'papiledema',
      titulo: 'Papiledema',
      estado: 'alterado',
      diagnostico: 'Edema de papila visto pelo ultrassom.',
      achado: 'Papila elevada > 0,6 mm protruindo para o vítreo, com bainha do nervo dilatada. Bilateral na hipertensão intracraniana.',
      leitura: ['Ganho médio, olhe o ponto de entrada do nervo.', 'Elevação da papila em direção ao vítreo.', 'Meça a bainha: costuma estar > 5 mm.'],
      diferencaDoNormal: 'A papila normal é plana com a retina. O edema a empurra para dentro do olho — o mesmo abaulamento que o oftalmoscópio vê, agora sem dilatar.',
      conduta: 'Como hipertensão intracraniana: imagem cerebral urgente.',
      diferencial: ['Drusas do disco (brilhantes, com sombra)', 'Neurite óptica'],
    },
    {
      id: 'descolamento-de-retina',
      titulo: 'Descolamento de retina',
      estado: 'alterado',
      diagnostico: 'Descolamento regmatogênico ou tracional da retina.',
      achado: 'Membrana **espessa, brilhante e rígida** flutuando no vítreo, presa posteriormente ao disco óptico (não cruza o nervo) e anteriormente à ora serrata; forma de V ou funil quando total. Ondula pouco com o movimento ocular.',
      leitura: ['Ganho baixo: a retina descolada aparece mesmo assim (é espessa).', 'Siga a membrana até o nervo: presa ao disco é retina.', 'Mova o olho: movimento limitado, "pesado".'],
      diferencaDoNormal: 'A retina aderida é invisível. Descolada, vira uma membrana que sai da parede e continua presa só no disco — a inserção no nervo é a assinatura.',
      conduta: 'Oftalmologia de urgência: mácula ainda aderida é cirurgia em 24 horas. Não deitar o paciente de bruços.',
      diferencial: ['Descolamento de vítreo (fina, cruza o nervo, muito móvel)', 'Hemorragia vítrea organizada', 'Descolamento de coroide (espesso, lobulado)'],
    },
    {
      id: 'hemorragia-vitrea',
      titulo: 'Hemorragia vítrea — máquina de lavar',
      estado: 'alterado',
      diagnostico: 'Sangue no vítreo.',
      achado: 'Ecos finos e móveis no vítreo que rodopiam com o movimento do olho e continuam a se mover depois que o olho para ("máquina de lavar"); mais visíveis com ganho alto. Sem membrana presa ao disco.',
      leitura: ['Suba o ganho: os ecos aparecem.', 'Peça movimento: rodopio que persiste após o olho parar.', 'Baixe o ganho e procure retina descolada por baixo.'],
      diferencaDoNormal: 'O vítreo é gel transparente e anecoico. Sangue dentro dele espalha o som e cria a nuvem que gira. Sempre procure a causa: retinopatia diabética, descolamento, trauma.',
      conduta: 'Oftalmologia; repouso com cabeceira elevada; vitrectomia se não clarear ou se há descolamento.',
      diferencial: ['Hialose asteroide (ecos brilhantes, sem doença)', 'Vitreíte', 'Descolamento de vítreo'],
    },
    {
      id: 'descolamento-de-vitreo',
      titulo: 'Descolamento de vítreo',
      estado: 'alterado',
      diagnostico: 'Descolamento posterior do vítreo — o que imita descolamento de retina.',
      achado: 'Membrana **fina, pouco ecogênica, muito móvel**, que flutua livremente e **cruza** o nervo óptico sem se prender a ele; só aparece com ganho alto.',
      leitura: ['Ganho alto para vê-la; some no ganho baixo (a retina não some).', 'Não se prende ao disco.', 'Movimento amplo, "leve", que continua após o olho parar.'],
      diferencaDoNormal: 'O vítreo se solta da retina com a idade e sua face posterior vira uma membrana fina. Diferente da retina, é mole e não tem inserção no disco — e não é urgência.',
      conduta: 'Oftalmologia eletiva para procurar rotura retiniana associada (10% dos casos).',
      diferencial: ['Descolamento de retina', 'Hemorragia vítrea em cortina'],
    },
    {
      id: 'luxacao-de-cristalino',
      titulo: 'Luxação do cristalino',
      estado: 'alterado',
      diagnostico: 'Deslocamento do cristalino — trauma ou Marfan.',
      achado: 'A lente biconvexa fora da posição atrás da íris: no vítreo (luxação posterior), inclinada (subluxação) ou na câmara anterior. Espaço vazio onde deveria estar.',
      leitura: ['Localize o cristalino atrás da íris.', 'Não está: procure no vítreo.', 'Móvel com o olho: luxado.'],
      diferencaDoNormal: 'O cristalino fica preso pelas zônulas atrás da íris. Rompidas, ele cai — e o ultrassom o acha sem dilatar.',
      conduta: 'Oftalmologia: cirurgia conforme sintomas e pressão intraocular.',
      diferencial: ['Afacia cirúrgica', 'Lente intraocular deslocada'],
    },
    {
      id: 'oclusao-da-arteria-central',
      titulo: 'Oclusão da artéria central da retina',
      estado: 'alterado',
      diagnostico: 'Isquemia retiniana aguda — o AVC do olho.',
      achado: 'Doppler colorido e espectral na artéria central da retina (dentro do nervo óptico, ao lado da veia): fluxo ausente ou muito reduzido, comparado ao olho contralateral. Às vezes um êmbolo ecogênico ("spot sign") no nervo.',
      leitura: ['Doppler no nervo óptico, escala baixa.', 'Artéria: fluxo pulsátil; veia: contínuo. Compare os lados.', 'Procure o ponto brilhante do êmbolo.'],
      diferencaDoNormal: 'O olho normal mostra artéria e veia pulsando dentro do nervo. Ocluída, a artéria silencia — e a perda visual súbita e indolor tem causa vista.',
      conduta: 'Emergência: janela de horas; discutir trombólise; investigar fonte embólica (carótida, coração) e arterite de células gigantes.',
      diferencial: ['Oclusão de veia central', 'Neuropatia óptica isquêmica'],
    },
    {
      id: 'corpo-estranho-orbitario',
      titulo: 'Corpo estranho orbitário',
      estado: 'alterado',
      diagnostico: 'Corpo estranho intraocular ou orbitário.',
      achado: 'Foco muito ecogênico com sombra ou reverberação dentro do globo ou nos tecidos da órbita; hemorragia vítrea associada; se metálico, cauda de cometa.',
      leitura: ['Sem pressão no olho — pode estar roto.', 'Foco brilhante fora do lugar.', 'Tomografia para localizar e planejar a retirada.'],
      diferencaDoNormal: 'Nada dentro do olho reflete como metal ou vidro. O foco com sombra é o corpo estranho; e um globo com corpo estranho está roto.',
      conduta: 'Oftalmologia urgente; protetor rígido; antibiótico; tomografia (não ressonância se metálico).',
      diferencial: ['Calcificação', 'Hialose asteroide'],
    },
    {
      id: 'hematoma-retrobulbar',
      titulo: 'Hematoma retrobulbar',
      estado: 'alterado',
      diagnostico: 'Síndrome compartimental da órbita.',
      achado: 'Coleção hipoecoica atrás do globo, deslocando-o para a frente (proptose), com achatamento do polo posterior e às vezes sinal do guitar-pick (globo deformado em ponta). Bainha do nervo esticada.',
      leitura: ['Trauma com proptose e pressão ocular alta: olhe atrás do globo.', 'Coleção retrobulbar.', 'Polo posterior achatado: pressão crítica.'],
      diferencaDoNormal: 'A gordura orbitária é homogênea e ecogênica. Sangue atrás do globo o empurra para fora e estrangula o nervo — cegueira em 60 a 90 minutos.',
      conduta: 'Cantotomia lateral e cantólise imediatas — sem esperar imagem se a clínica é clara.',
      diferencial: ['Celulite orbitária', 'Enfisema orbitário'],
    },
    {
      id: 'ruptura-do-globo',
      titulo: 'Ruptura do globo',
      estado: 'alterado',
      diagnostico: 'Globo ocular aberto.',
      achado: 'Globo com perda do contorno esférico, câmara anterior rasa ou colapsada, hemorragia vítrea e do segmento anterior, conteúdo extravasado. Exame com pressão zero e muito gel — ou nenhum exame.',
      leitura: ['Suspeita clara: proteja e não examine.', 'Se examinar, sonda flutuando no gel sem tocar.', 'Contorno irregular, câmara rasa.'],
      diferencaDoNormal: 'O olho é uma esfera sob pressão. Roto, perde a forma. O risco do ultrassom é apertar e expulsar o que sobrou — a imagem não vale isso.',
      conduta: 'Protetor rígido sem pressão, antibiótico, antiemético, jejum, oftalmologia para reparo. Tomografia.',
      diferencial: ['Ruptura antiga (phthisis bulbi)'],
    },
    {
      id: 'endoftalmite',
      titulo: 'Endoftalmite',
      estado: 'alterado',
      diagnostico: 'Infecção intraocular.',
      achado: 'Vítreo cheio de ecos densos e opacidades, membranas, espessamento das camadas do globo; câmara anterior com hipópio ecogênico. Pós-cirurgia, trauma ou endógena.',
      leitura: ['Vítreo turvo com ganho baixo já visível.', 'Espessamento coroide-retina.', 'Contexto: cirurgia recente, sepse, usuário de drogas.'],
      diferencaDoNormal: 'Hemorragia vítrea é sangue que se mexe; endoftalmite é pus com membranas. Ambos turvam o vítreo; a clínica (dor, olho vermelho, febre) e as membranas separam.',
      conduta: 'Emergência: antibiótico intravítreo; vitrectomia. Endógena: hemoculturas e antibiótico sistêmico.',
      diferencial: ['Hemorragia vítrea', 'Uveíte', 'Retinoblastoma na criança'],
    },
    {
      id: 'abscesso-orbitario',
      titulo: 'Abscesso orbitário',
      estado: 'alterado',
      diagnostico: 'Celulite orbitária com coleção.',
      achado: 'Coleção hipoecoica na gordura orbitária ou subperiosteal ao longo da parede medial, deslocando o globo; tecidos ao redor edemaciados e hiperemiados.',
      leitura: ['Olho vermelho, proptose, dor ao mover: olhe a órbita.', 'Coleção: abscesso.', 'Tomografia confirma a extensão e o seio de origem.'],
      diferencaDoNormal: 'A celulite orbitária infiltra a gordura; o abscesso a substitui por uma coleção. O primeiro é antibiótico; o segundo, drenagem.',
      conduta: 'Antibiótico venoso; drenagem cirúrgica se abscesso, déficit visual ou não melhora em 48 h.',
      diferencial: ['Celulite pré-septal', 'Hematoma', 'Tumor'],
    },
    {
      id: 'reflexo-consensual',
      titulo: 'Reflexo consensual',
      estado: 'alterado',
      diagnostico: 'Reflexo pupilar avaliado pelo ultrassom em olho fechado.',
      achado: 'Sonda transversal na pálpebra fechada, no plano da íris: ao iluminar o outro olho, a pupila (o espaço entre as bordas da íris) se estreita. Ausência com a pupila fixa: lesão do arco.',
      leitura: ['Plano da íris, pupila como intervalo escuro.', 'Luz no olho contralateral: a pupila diminui.', 'Útil no edema palpebral que impede abrir o olho.'],
      diferencaDoNormal: 'Cena de técnica: permite o exame pupilar no trauma facial com olho fechado por edema.',
      conduta: 'Pupila fixa e dilatada com trauma: hipertensão intracraniana ou lesão do III nervo — tomografia.',
      diferencial: ['Midríase farmacológica', 'Trauma da íris'],
    },
    {
      id: 'retinoblastoma',
      titulo: 'Retinoblastoma',
      estado: 'alterado',
      diagnostico: 'Tumor retiniano da criança.',
      achado: 'Massa sólida intraocular partindo da retina, com **calcificações** (focos brilhantes com sombra), às vezes com descolamento de retina associado. Leucocoria na criança.',
      leitura: ['Leucocoria: ultrassom antes de qualquer coisa.', 'Massa com calcificação é o achado-chave.', 'Bilateral em 30%: examine os dois.'],
      diferencaDoNormal: 'A retina é invisível. Uma massa que sai dela com cálcio dentro, numa criança pequena, é retinoblastoma até prova em contrário — e o cálcio o separa dos outros.',
      conduta: 'Oncologia ocular urgente; ressonância para extensão; não biopsiar.',
      diferencial: ['Doença de Coats', 'Persistência do vítreo primário', 'Catarata'],
    },
    {
      id: 'hialose-asteroide',
      titulo: 'Hialose asteroide — o que imita hemorragia',
      estado: 'alterado',
      diagnostico: 'Depósitos de cálcio-fosfolipídio no vítreo — benigno.',
      achado: 'Múltiplos pontos muito brilhantes e uniformes no vítreo, visíveis mesmo com ganho baixo, que se movem com o olho e voltam à posição; sem membrana, sem sintomas.',
      leitura: ['Ecos brilhantes com ganho baixo (hemorragia exige ganho alto).', 'Uniformes e sem sombra.', 'Paciente sem perda visual.'],
      diferencaDoNormal: 'A hemorragia vítrea tem ecos finos, só no ganho alto, com perda visual. A hialose tem ecos brilhantes, no ganho baixo, sem sintoma — achado incidental que engana quem não a conhece.',
      conduta: 'Nenhuma.',
      diferencial: ['Hemorragia vítrea', 'Vitreíte'],
    },
  ],
  armadilhas: [
    'Pressionar o globo: dói, distorce e é perigoso em ruptura. A sonda se apoia na órbita e flutua no gel.',
    'Membrana fina que cruza o nervo é vítreo, não retina. A inserção no disco é o critério — não a presença de membrana.',
    'Bainha do nervo óptico medida inclinada ou muito perto do globo dá valor falso. São 3 mm atrás da retina, perpendicular ao nervo.',
    'Ganho baixo esconde a hemorragia vítrea; ganho alto cria membranas falsas. Faça as duas coisas e leia cada uma no ganho certo.',
    'Não use Doppler prolongado sobre o cristalino nem em gestantes: energia acústica desnecessária.',
  ],
  ondeVerFoto: [
    { titulo: 'The POCUS Atlas — Ocular', url: 'https://www.thepocusatlas.com/ocular', oQueProcurar: 'Descolamento de retina, hemorragia vítrea, bainha do nervo óptico e corpos estranhos, com clipes em movimento.', licenciada: 'pocus-atlas' },
  ],
  referencias: [
    'Blaivas M et al. A study of bedside ocular ultrasonography in the emergency department. Acad Emerg Med, 2002.',
    'Dubourg J et al. Ultrasonography of optic nerve sheath diameter for detection of raised intracranial pressure: a systematic review and meta-analysis. Intensive Care Med, 2011.',
    'Lahham S et al. Point-of-care ultrasonography in the diagnosis of retinal detachment, vitreous hemorrhage, and vitreous detachment in the emergency department. JAMA Netw Open, 2019.',
  ],
}
