import type { CenaClinica, Vista } from './esquemas'

/**
 * Quarta leva de vistas — três instrumentos que não são endoscópio nem sonda,
 * mas moram na beira do leito de quem os conhece: o microscópio do
 * laboratório de plantão, o capilaroscópio (ou o dermatoscópio apontado para a
 * cutícula) e a luz de Wood. As cenas são fotografia pura; o Commons e o CDC
 * têm acervo de domínio público para quase todas.
 */

const CENAS_MICROSCOPIA: CenaClinica[] = [
  {
    id: 'sedimento-normal',
    titulo: 'Sedimento urinário normal',
    estado: 'normal',
    diagnostico: 'Urina centrifugada sem elementos patológicos.',
    achado: 'Campo em 400× quase vazio: raras células epiteliais escamosas grandes e poligonais, até 2 hemácias e 5 leucócitos por campo, eventual cilindro hialino (transparente, bordas retas, quase invisível), sem cristais relevantes ou muco escasso.',
    leitura: ['Baixe o condensador: os elementos são transparentes.', 'Conte hemácias e leucócitos em 10 campos e faça a média.', 'Cilindro hialino isolado é normal — após exercício, desidratação, diurético.'],
    diferencaDoNormal: 'É a referência.',
    conduta: 'Nenhuma.',
    diferencial: [],
  },
  {
    id: 'cilindros-hematicos',
    titulo: 'Cilindros hemáticos e hematúria dismórfica',
    estado: 'alterado',
    diagnostico: 'Hematúria de origem glomerular — glomerulonefrite.',
    achado: 'Cilindro cilíndrico com **hemácias embutidas** numa matriz de proteína de Tamm-Horsfall, de cor laranja-avermelhada; hemácias **dismórficas** (> 40% com formas irregulares) e **acantócitos** (anel com protrusões em "orelha de Mickey", > 5%) no sedimento; proteinúria associada.',
    leitura: ['Cilindro com células vermelhas dentro: glomerular, não urológico.', 'Contraste de fase para acantócitos.', 'Combine com proteinúria e creatinina: síndrome nefrítica.'],
    diferencaDoNormal: 'Hemácia que passou pelo glomérulo inflamado sai deformada; hemácia que sangrou da bexiga sai redonda (isomórfica).',
    conduta: 'Cilindro hemático é glomerulonefrite até prova em contrário: nefrologia, complemento, ANCA, anti-MBG, biópsia.',
    diferencial: ['Hematúria isomórfica (litíase, tumor, infecção)', 'Cilindro granuloso pigmentado (mioglobinúria)', 'Contaminação menstrual'],
  },
  {
    id: 'cilindros-granulosos',
    titulo: 'Cilindros granulosos e de células epiteliais',
    estado: 'alterado',
    diagnostico: 'Necrose tubular aguda.',
    achado: 'Cilindros com grânulos grosseiros **castanho-escuros ("lamacentos")** e cilindros com células epiteliais tubulares renais (cúbicas, núcleo grande) descamadas, em quantidade; células tubulares livres; ausência de hemácias dismórficas. Escore de sedimento ≥ 2 (cilindros granulosos + células tubulares por campo) prediz NTA.',
    leitura: ['Cilindro marrom e granular grosseiro em paciente com IRA: o túbulo está descamando.', 'Diferente do granuloso fino, que pode ser normal.', 'Conte por campo de baixo aumento.'],
    diferencaDoNormal: 'O sedimento pré-renal é limpo (cilindros hialinos); o da NTA é sujo — a diferença que separa "dar volume" de "esperar recuperar".',
    conduta: 'Suporte, evitar nefrotóxicos, prever oligúria de dias a semanas.',
    diferencial: ['Cilindro céreo (IRC avançada, largo e refringente)', 'Cilindro leucocitário (nefrite intersticial, pielonefrite)'],
  },
  {
    id: 'cristais-urinarios',
    titulo: 'Cristais urinários — oxalato, urato, estruvita',
    estado: 'alterado',
    diagnostico: 'Cristalúria com valor diagnóstico.',
    achado: 'Oxalato de cálcio di-hidratado: **envelopes** (octaedros com cruz); mono-hidratado: halteres ou "grãos de café" (intoxicação por etilenoglicol quando em massa); ácido úrico: rombos e rosetas amarelo-acastanhados em urina ácida; estruvita: **tampas de caixão** (prismas retangulares) em urina alcalina com infecção por urease (Proteus); cistina: hexágonos incolores (cistinúria); fosfato de cálcio: agulhas.',
    leitura: ['pH da urina primeiro: ácido pede urato e cistina; alcalino, estruvita e fosfato.', 'Forma decide: envelope, rombo, tampa de caixão, hexágono.', 'Cristais em urina fresca e quente valem; em urina fria, precipitam sem doença.'],
    diferencaDoNormal: 'Cristais isolados em urina refrigerada são artefato; cristais abundantes em urina fresca com clínica são litíase, intoxicação ou erro inato.',
    conduta: 'Cistina: sempre patológico. Oxalato mono-hidratado em massa com acidose: etilenoglicol. Estruvita: infecção e cálculo coraliforme.',
    diferencial: ['Cristais de medicamentos (sulfa, aciclovir, indinavir — feixes e agulhas)'],
  },
  {
    id: 'gram-diplococos',
    titulo: 'Gram — diplococos e bacilos',
    estado: 'alterado',
    diagnostico: 'Coloração de Gram de líquor, secreção ou urina com bactéria identificável.',
    achado: '**Diplococos gram-negativos intracelulares** em neutrófilos (Neisseria — gonorreia em uretra, meningococo em líquor); **diplococos gram-positivos lanceolados** (pneumococo) em escarro ou líquor; bacilos gram-negativos (enterobactérias) em urina; cocos gram-positivos em cachos (estafilococo) ou em cadeia (estreptococo); bacilos gram-positivos em paliçada.',
    leitura: ['Cor: roxo = positivo, rosa = negativo.', 'Forma e arranjo: coco/bacilo, pares, cadeias, cachos.', 'Dentro do neutrófilo = fagocitado = agente real, não contaminante.'],
    diferencaDoNormal: 'Líquor e sangue não têm bactéria; escarro tem flora oral misturada — o predomínio de um morfotipo com leucócitos é o que vale.',
    conduta: 'Líquor com diplococos gram-negativos: ceftriaxona já; gram-positivos lanceolados: cobrir pneumococo resistente. O Gram guia horas antes da cultura.',
    diferencial: ['Contaminação de flora (morfotipos múltiplos sem leucócitos)', 'Artefato de coloração (Gram-variável)'],
  },
  {
    id: 'koh-hifas',
    titulo: 'Exame direto com KOH — hifas',
    estado: 'alterado',
    diagnostico: 'Dermatofitose ou candidíase no raspado de pele, unha ou mucosa.',
    achado: 'Após KOH 10 a 20% dissolver a queratina: **hifas septadas, ramificadas, refringentes**, atravessando os limites das células epidérmicas (dermatófito); **pseudo-hifas com blastoconídios em brotamento** (Candida); hifas curtas e esporos redondos agrupados ("espaguete com almôndegas") na pitiríase versicolor.',
    leitura: ['Condensador baixo, luz reduzida: hifas são transparentes.', 'Hifa cruza a célula — fibra de roupa e borda celular não.', 'Espaguete com almôndegas = versicolor, sem cultura.'],
    diferencaDoNormal: 'Raspado normal mostra só células epiteliais poligonais anucleadas.',
    conduta: 'Positivo confirma o antifúngico; negativo não exclui (raspar a borda ativa, sem creme prévio).',
    diferencial: ['Artefato em mosaico (bordas celulares)', 'Fibras têxteis (não septadas, irregulares)', 'Gotículas de gordura'],
  },
  {
    id: 'exame-a-fresco-vaginal',
    titulo: 'Exame a fresco do conteúdo vaginal',
    estado: 'alterado',
    diagnostico: 'Vaginose bacteriana, tricomoníase ou candidíase.',
    achado: '**Clue cells**: células epiteliais com bordas apagadas cobertas por cocobacilos (vaginose, com pH > 4,5 e teste das aminas positivo); **Trichomonas vaginalis**: protozoário piriforme móvel, do tamanho de um leucócito, com flagelos, junto a muitos neutrófilos; **Candida**: pseudo-hifas e leveduras com KOH, pH normal.',
    leitura: ['Gota de soro, lamínula, 400×, sem corar — e rápido: o Trichomonas para de se mover em minutos.', 'Clue cell: borda pontilhada, não lisa.', 'Leucócitos abundantes: tricomoníase ou cervicite, não vaginose.'],
    diferencaDoNormal: 'Conteúdo normal: células epiteliais limpas, lactobacilos (bacilos longos) e raros leucócitos.',
    conduta: 'Critérios de Amsel para vaginose; tricomoníase trata o parceiro; candidíase recorrente pede glicemia e HIV.',
    diferencial: ['Vaginite atrófica (células parabasais, leucócitos)', 'Vaginite inflamatória descamativa'],
  },
  {
    id: 'gota-espessa-malaria',
    titulo: 'Gota espessa — Plasmodium falciparum e vivax',
    estado: 'alterado',
    diagnostico: 'Malária diagnosticada por microscopia.',
    achado: 'Gota espessa (hemácias lisadas, concentra parasitas): trofozoítos em anel com cromatina puntiforme. Esfregaço fino identifica a espécie: **P. falciparum** — anéis pequenos, múltiplos por hemácia, com dois pontos de cromatina, formas em "fone de ouvido" na borda (appliqué), **gametócitos em banana**, hemácias de tamanho normal, sem esquizontes no sangue periférico; **P. vivax** — hemácias aumentadas com pontilhado de Schüffner, trofozoítos ameboides, esquizontes com 12 a 24 merozoítos, gametócitos redondos.',
    leitura: ['Gota espessa para achar; fino para tipar.', 'Banana = falciparum. Hemácia grande pontilhada = vivax.', 'Conte a parasitemia (%) no falciparum: > 5% é grave.'],
    diferencaDoNormal: 'Hemácias normais são discos homogêneos sem inclusões.',
    conduta: 'Falciparum: artemisinina, avaliar gravidade e internar se parasitemia alta ou disfunção; vivax: cloroquina + primaquina (G6PD antes).',
    diferencial: ['Babesia (tétrades em cruz de Malta, sem pigmento)', 'Plaquetas sobre hemácias', 'Corpúsculos de Howell-Jolly'],
  },
  {
    id: 'leishmania-aspirado',
    titulo: 'Leishmania em aspirado de medula ou lesão',
    estado: 'alterado',
    diagnostico: 'Leishmaniose visceral ou tegumentar confirmada por amastigotas.',
    achado: 'Giemsa: **amastigotas** (corpúsculos de Leishman-Donovan) — corpos ovais de 2 a 4 µm, com núcleo e **cinetoplasto em bastonete** ao lado (a marca que distingue de Histoplasma), dentro de macrófagos ou livres, em aspirado de medula, baço ou borda de úlcera cutânea.',
    leitura: ['Procure dentro dos macrófagos em 1.000×.', 'Núcleo + cinetoplasto: é Leishmania. Só núcleo com halo: Histoplasma.', 'Medula tem sensibilidade 60-85%; baço 95% (com risco).'],
    diferencaDoNormal: 'Macrófagos normais não carregam corpúsculos com cinetoplasto.',
    conduta: 'Visceral: anfotericina lipossomal; tegumentar: antimonial ou miltefosina; rastreie HIV.',
    diferencial: ['Histoplasma capsulatum (sem cinetoplasto, PAS+)', 'Toxoplasma (crescentes, extracelulares)', 'Trypanosoma cruzi (amastigotas em tecido, morfologicamente idênticos — a clínica separa)'],
  },
  {
    id: 'esfregaco-drepanocitos-esquizocitos',
    titulo: 'Esfregaço — drepanócitos e esquizócitos',
    estado: 'alterado',
    diagnostico: 'Anemia falciforme em crise ou anemia hemolítica microangiopática.',
    achado: '**Drepanócitos**: hemácias em foice ou meia-lua, alongadas, com pontas afiladas, junto a células em alvo e corpúsculos de Howell-Jolly (asplenia funcional). **Esquizócitos**: fragmentos de hemácia em capacete, triângulo ou meia-lua com bordas cortantes, > 1% dos eritrócitos, com plaquetopenia e policromasia — PTT, SHU, CIVD, HELLP.',
    leitura: ['Foice com pontas: falciforme. Fragmento com bordas retas: esquizócito.', 'Esquizócitos > 1% + plaquetas baixas + LDH alta: microangiopatia — emergência.', 'Howell-Jolly no falcêmico: o baço já não funciona.'],
    diferencaDoNormal: 'Hemácias normais são discos bicôncavos uniformes, sem fragmentos nem formas em foice.',
    conduta: 'Esquizócitos com plaquetopenia e sem outra explicação: PTT até prova contrária — plasmaférese no mesmo dia. Falciforme em crise: hidratação, analgesia, oxigênio se hipoxemia.',
    diferencial: ['Eliptócitos (ovais, sem pontas — eliptocitose hereditária)', 'Células em lágrima (mielofibrose)', 'Artefato de esfregaço mal feito (fragmentos na cauda)'],
  },
]

const CENAS_CAPILAROSCOPIA: CenaClinica[] = [
  {
    id: 'capilares-normais',
    titulo: 'Capilaroscopia periungueal normal',
    estado: 'normal',
    diagnostico: 'Leito capilar periungueal sem alterações.',
    achado: 'Alças capilares em **grampo de cabelo (hairpin)**, finas, uniformes, paralelas, dispostas em fileira regular na borda da cutícula, com **densidade de 7 a 12 alças por milímetro**, sem dilatação (< 20 µm), sem hemorragias, sem áreas avasculares; fluxo homogêneo.',
    leitura: ['Fileira regular de grampos.', 'Conte por milímetro: 7 a 12.', 'Alças tortuosas leves e cruzadas são variantes normais.'],
    diferencaDoNormal: 'É a referência.',
    conduta: 'Nenhuma. Raynaud com capilaroscopia normal e autoanticorpos negativos é primário — tranquilize.',
    diferencial: [],
  },
  {
    id: 'padrao-esclerodermico-precoce',
    titulo: 'Padrão esclerodérmico precoce',
    estado: 'alterado',
    diagnostico: 'Esclerose sistêmica em fase inicial — Raynaud secundário.',
    achado: 'Poucos **capilares gigantes** (> 50 µm, alças ectásicas homogêneas) e **microhemorragias** puntiformes ao redor, com densidade ainda preservada e arquitetura relativamente conservada; sem áreas avasculares significativas.',
    leitura: ['Um capilar gigante já é anormal — não existe gigante fisiológico.', 'Hemorragias em torno das alças dilatadas.', 'Arquitetura ainda ordenada.'],
    diferencaDoNormal: 'Onde deveria haver grampos finos uniformes, alguns viraram balões com sangue ao redor.',
    conduta: 'Raynaud + capilar gigante + autoanticorpo específico (centrômero, Scl-70) = esclerose sistêmica muito precoce (critérios VEDOSS) — antes de qualquer espessamento de pele.',
    diferencial: ['Dermatomiosite e doença mista (padrão semelhante, com mais ramificação)', 'Trauma da cutícula (hemorragia isolada sem dilatação)'],
  },
  {
    id: 'padrao-esclerodermico-ativo',
    titulo: 'Padrão esclerodérmico ativo',
    estado: 'alterado',
    diagnostico: 'Esclerose sistêmica em atividade microvascular.',
    achado: '**Numerosos capilares gigantes** e hemorragias, **perda moderada de capilares (20 a 30%)** com áreas avasculares iniciais, desorganização moderada da arquitetura, poucos ou nenhum capilar ramificado.',
    leitura: ['Gigantes por todo lado, hemorragias frequentes.', 'Buracos começam a aparecer na fileira.', 'Densidade caindo para 4 a 6 por milímetro.'],
    diferencaDoNormal: 'A fileira regular virou um campo de balões e lacunas.',
    conduta: 'Correlaciona com atividade da doença e risco de úlcera digital e envolvimento pulmonar — avaliar prova de função pulmonar e ecocardiograma.',
    diferencial: ['Dermatomiosite ativa', 'Overlap'],
  },
  {
    id: 'padrao-esclerodermico-tardio',
    titulo: 'Padrão esclerodérmico tardio',
    estado: 'alterado',
    diagnostico: 'Esclerose sistêmica de longa evolução — rarefação e neoangiogênese.',
    achado: '**Perda grave de capilares (> 50%)** com extensas áreas avasculares ("desertos"), raros ou nenhum gigante, poucas hemorragias, e **capilares ramificados, arborizados ou em arbusto** (neoangiogênese desordenada); arquitetura totalmente desorganizada.',
    leitura: ['Mais deserto que capilar.', 'Os que restam são arbustos irregulares.', 'Gigantes e hemorragias praticamente desapareceram.'],
    diferencaDoNormal: 'Pouco resta da fileira; o que cresceu de novo cresceu errado.',
    conduta: 'Associado a doença de longa duração, úlceras digitais recorrentes e hipertensão pulmonar; o padrão tardio prediz mau prognóstico vascular.',
    diferencial: ['Padrão tardio da dermatomiosite', 'Alterações inespecíficas em diabetes e hipertensão (sem desertos nem arbustos)'],
  },
]

const CENAS_LUZ_DE_WOOD: CenaClinica[] = [
  {
    id: 'pele-normal-wood',
    titulo: 'Pele normal à luz de Wood',
    estado: 'normal',
    diagnostico: 'Sem fluorescência patológica.',
    achado: 'Sob a lâmpada de Wood (UV-A 365 nm) em sala escura, a pele normal aparece **azul-violácea homogênea e fosca**; cosméticos, fibras de roupa, sabão e pomadas fluorescem branco ou azul-brilhante (artefatos); cabelos e unhas normais não fluorescem; máculas hipocrômicas discretas não se acentuam.',
    leitura: ['Sala totalmente escura e 1 minuto de adaptação.', 'Lave e seque a área: creme e sabão brilham.', 'Compare com pele sã adjacente.'],
    diferencaDoNormal: 'É a referência.',
    conduta: 'Nenhuma.',
    diferencial: [],
  },
  {
    id: 'pitiriase-versicolor-wood',
    titulo: 'Pitiríase versicolor',
    estado: 'alterado',
    diagnostico: 'Malassezia produzindo fluorescência amarelo-dourada.',
    achado: 'Máculas que à luz comum eram discretas e finamente descamativas aparecem com **fluorescência amarelo-dourada ou amarelo-esverdeada**, revelando extensão muito maior que a visível no tronco, ombros e pescoço; o KOH confirma (espaguete com almôndegas).',
    leitura: ['Amarelo-ouro nas manchas.', 'A extensão real aparece — trate tudo o que brilha.', 'Fluorescência some após banho recente (falso-negativo).'],
    diferencaDoNormal: 'O que era mancha pálida vira mapa dourado.',
    conduta: 'Antifúngico tópico ou oral conforme a extensão que a lâmpada mostrou; recorrência é a regra.',
    diferencial: ['Eritrasma (vermelho-coral, nas dobras)', 'Vitiligo (branco-azulado, sem descamação)'],
  },
  {
    id: 'eritrasma-wood',
    titulo: 'Eritrasma',
    estado: 'alterado',
    diagnostico: 'Corynebacterium minutissimum nas dobras — fluorescência vermelho-coral.',
    achado: 'Placas acastanhadas, finamente descamativas, bem delimitadas, nas virilhas, axilas ou espaços interdigitais, que sob a luz de Wood emitem **fluorescência vermelho-coral** (porfirinas bacterianas); KOH negativo para hifas.',
    leitura: ['Coral nas dobras = eritrasma, não tinha.', 'Banho recente remove as porfirinas: falso-negativo.', 'Interdigital dos pés: eritrasma imita tinha do pé.'],
    diferencaDoNormal: 'Placa que parecia intertrigo fúngico brilha vermelho — é bactéria.',
    conduta: 'Eritromicina tópica ou oral, ácido fusídico; antifúngico não resolve.',
    diferencial: ['Tinha cruris (sem fluorescência ou leve verde)', 'Candidíase intertriginosa (satélites, sem fluorescência)', 'Intertrigo simples'],
  },
  {
    id: 'vitiligo-wood',
    titulo: 'Vitiligo',
    estado: 'alterado',
    diagnostico: 'Despigmentação completa acentuada pela luz de Wood.',
    achado: 'Máculas acrômicas que sob a luz de Wood aparecem **branco-azuladas brilhantes, com bordas nítidas**, contrastando fortemente com a pele ao redor, revelando lesões invisíveis à luz comum em pele clara; lesões hipocrômicas (não acrômicas) — pitiríase alba, nevo acrômico, hipopigmentação pós-inflamatória — acentuam-se muito menos.',
    leitura: ['Branco brilhante com borda cortante = acromia.', 'Hipocromia fica só um pouco mais clara.', 'Mapeie a extensão para acompanhar resposta ao tratamento.'],
    diferencaDoNormal: 'A pele sem melanina reflete o UV sem absorver — brilha.',
    conduta: 'Confirma vitiligo em pele clara; separa de pitiríase alba e nevo acrômico; documenta extensão.',
    diferencial: ['Esclerose tuberosa (manchas hipomelanóticas em folha de freixo — também acentuam)', 'Hanseníase indeterminada (hipocromia com hipoestesia)', 'Líquen escleroso'],
  },
  {
    id: 'tinha-do-couro-cabeludo-wood',
    titulo: 'Tinha do couro cabeludo',
    estado: 'alterado',
    diagnostico: 'Tinea capitis por Microsporum — fluorescência verde dos cabelos.',
    achado: 'Cabelos parasitados por **Microsporum canis ou audouinii** (ectotrix) emitem **fluorescência verde-brilhante** ao longo da haste, na placa de alopecia descamativa; **Trichophyton tonsurans** (endotrix, a causa mais comum no Brasil) **não fluoresce** — luz de Wood negativa não exclui tinha do couro cabeludo.',
    leitura: ['Verde nos fios quebrados: Microsporum — pergunte por gato ou cão.', 'Sem fluorescência com placa descamativa e pontos pretos: Trichophyton — KOH e cultura.', 'Não confunda com fluorescência azul de escamas e pomadas.'],
    diferencaDoNormal: 'Fio normal não brilha; fio com Microsporum brilha verde.',
    conduta: 'Antifúngico sistêmico (griseofulvina ou terbinafina); tópico não penetra o folículo. Examine contactantes e o animal.',
    diferencial: ['Dermatite seborreica (escamas sem fluorescência dos fios)', 'Alopecia areata (sem descamação, fios em ponto de exclamação)', 'Tricotilomania'],
  },
]

export const VISTAS_LEVA_4: Vista[] = [
  {
    slug: 'microscopia',
    nome: 'Microscopia à beira do leito',
    instrumento: 'microscopio',
    resumo: 'O sedimento urinário, o Gram, o KOH, o a fresco e a gota espessa — cinco exames que o plantão faz em minutos e que decidem antes da cultura.',
    paraQue: 'A cultura demora dois dias; o microscópio responde em dez minutos: é glomerular ou urológica? É meningite bacteriana e de qual morfologia? É fungo ou eczema? É malária e de que espécie? A microscopia à beira do leito é a semiologia estendida — o exame físico do líquido.',
    comoFazer: [
      { passo: 'Sedimento: 10 mL de urina fresca centrifugados a 1.500 rpm por 5 minutos; despreze o sobrenadante, ressuspenda o botão, uma gota na lâmina com lamínula.', detalhe: 'Urina de mais de 2 horas lisa hemácias e dissolve cilindros — fresca ou nada.' },
      { passo: 'Condensador baixo e luz reduzida para elementos transparentes; 100× para cilindros, 400× para células e cristais.', detalhe: 'Com o condensador aberto, hialinos e hifas somem.' },
      { passo: 'Gram: esfregaço fino, fixado ao calor, cristal violeta, lugol, descoloração com álcool-acetona (o passo que erra), safranina.', detalhe: 'Descolorar demais faz gram-positivo virar negativo; de menos, o contrário. Controle com a flora da boca.' },
      { passo: 'KOH: raspado da borda ativa, KOH 10-20%, aquecimento leve ou 15 minutos de espera.', detalhe: 'DMSO no KOH acelera a clarificação sem aquecer.' },
      { passo: 'Gota espessa: gota grande espalhada em círculo de 1 cm, seca sem fixar, Giemsa; esfregaço fino ao lado para a espécie.', detalhe: 'Fixar a gota espessa impede a lise das hemácias e esconde os parasitas.' },
    ],
    qualidade: ['Amostra fresca e identificada.', 'Aumento e condensador adequados ao elemento procurado.', 'Achado registrado com foto do campo.'],
    estruturas: [],
    cenas: CENAS_MICROSCOPIA,
    armadilhas: [
      'Cristais em urina refrigerada não são doença.',
      'Gram de escarro sem leucócitos e com células escamosas é saliva — não interprete.',
      'KOH negativo após creme antifúngico não exclui.',
      'Esfregaço fino negativo não exclui malária — a gota espessa concentra 20 vezes mais.',
    ],
    ondeVerFoto: [
      { titulo: 'CDC Public Health Image Library', url: 'https://phil.cdc.gov', oQueProcurar: 'Gram, KOH, Plasmodium, Leishmania, Trichomonas — domínio público.', nota: 'Imagens do CDC são de domínio público nos EUA.' },
      { titulo: 'Wikimedia Commons', url: 'https://commons.wikimedia.org/wiki/Category:Urinary_sediment', oQueProcurar: 'Cilindros, cristais, hemácias dismórficas.', licenciada: 'wikimedia-commons' },
    ],
    referencias: ['Perazella MA et al. Diagnostic value of urine microscopy for differential diagnosis of acute kidney injury in hospitalized patients. Clin J Am Soc Nephrol, 2008.', 'WHO. Basic malaria microscopy, 2ª ed., 2010.'],
  },
  {
    slug: 'capilaroscopia',
    nome: 'Capilaroscopia periungueal',
    instrumento: 'capilaroscopio',
    resumo: 'A microcirculação vista na cutícula — o exame que separa o Raynaud benigno da esclerose sistêmica anos antes da pele endurecer.',
    paraQue: 'Um em cada dez adultos tem Raynaud; um em cada cem deles vai desenvolver esclerose sistêmica. A capilaroscopia é o único exame que responde qual — e responde na fase em que ainda não há esclerodactilia, quando o tratamento vascular muda o curso das úlceras digitais.',
    comoFazer: [
      { passo: 'Paciente sentado 15 minutos em sala a 20-22 °C, sem esmalte, sem trauma recente nas cutículas.', detalhe: 'Frio contrai os capilares e simula rarefação.' },
      { passo: 'Gota de óleo de imersão na cutícula do 2º ao 5º dedos das duas mãos; capilaroscópio (200×) ou dermatoscópio (10×) apoiado sem pressão.', detalhe: 'Polegar tem cutícula espessa e vê pior; o 4º dedo costuma ser o melhor.' },
      { passo: 'Avalie em cada dedo: arquitetura, densidade por milímetro, calibre (gigantes > 50 µm), hemorragias, áreas avasculares, ramificações.', detalhe: 'Um dedo com gigante basta para ser anormal.' },
      { passo: 'Classifique: normal, inespecífico, esclerodérmico precoce/ativo/tardio.', detalhe: 'Fotografe e repita anualmente no Raynaud com anticorpo positivo.' },
    ],
    qualidade: ['Oito dedos examinados.', 'Densidade contada por milímetro.', 'Fotografia do pior campo.'],
    estruturas: [],
    cenas: CENAS_CAPILAROSCOPIA,
    armadilhas: [
      'Hemorragia isolada em quem rói unhas ou trabalha com as mãos é trauma.',
      'Tortuosidade e cruzamento de alças são normais; dilatação homogênea não.',
      'Diabetes e hipertensão dão alterações inespecíficas — sem gigantes nem desertos.',
    ],
    ondeVerFoto: [{ titulo: 'Wikimedia Commons', url: 'https://commons.wikimedia.org/wiki/Category:Capillaroscopy', oQueProcurar: 'Capilaroscopia normal e padrões esclerodérmicos.', licenciada: 'wikimedia-commons' }],
    referencias: ['Cutolo M et al. Nailfold videocapillaroscopy assessment of microvascular damage in systemic sclerosis. J Rheumatol, 2000.', 'Smith V et al. Standardisation of nailfold capillaroscopy for the assessment of patients with Raynaud\'s phenomenon and systemic sclerosis. Autoimmun Rev, 2020.'],
  },
  {
    slug: 'luz-de-wood',
    nome: 'Luz de Wood',
    instrumento: 'lampada-de-wood',
    resumo: 'Ultravioleta A numa sala escura: a Malassezia brilha dourada, o eritrasma vermelho-coral, o Microsporum verde, e o vitiligo mostra o que a luz comum escondia.',
    paraQue: 'Três perguntas que a lâmpada de 20 dólares responde em 30 segundos: essa mancha da virilha é fungo ou bactéria? essa mancha branca é vitiligo ou hipocromia? até onde vai a versicolor? — e uma quarta, na porfiria, em que a urina brilha rosa.',
    comoFazer: [
      { passo: 'Sala completamente escura; lâmpada acesa por 1 minuto para estabilizar; olhos adaptados.', detalhe: 'Qualquer luz ambiente apaga a fluorescência fraca.' },
      { passo: 'Pele limpa e seca — sem creme, sabão, cosmético ou fibra de roupa.', detalhe: 'Todos fluorescem e produzem falsos positivos brilhantes.' },
      { passo: 'Lâmpada a 10 a 15 cm da pele, varrendo lentamente; compare com pele sã.', detalhe: 'Banho recente remove as porfirinas do eritrasma e da versicolor — falso-negativo.' },
      { passo: 'Interprete pela cor: amarelo-ouro (versicolor), vermelho-coral (eritrasma), verde (Microsporum), branco-azulado nítido (vitiligo), rosa (urina na porfiria).', detalhe: 'Pseudomonas em ferida fluoresce verde-amarelado.' },
    ],
    qualidade: ['Escuro total.', 'Pele limpa.', 'Cor da fluorescência registrada.'],
    estruturas: [],
    cenas: CENAS_LUZ_DE_WOOD,
    armadilhas: [
      'Trichophyton tonsurans, a tinha de couro cabeludo mais comum, não fluoresce — negativo não exclui.',
      'Versicolor após banho: sem brilho.',
      'Fluorescência azul-branca de cosmético confundida com vitiligo.',
    ],
    ondeVerFoto: [{ titulo: 'Wikimedia Commons', url: 'https://commons.wikimedia.org/wiki/Category:Wood%27s_lamp', oQueProcurar: 'Versicolor, eritrasma, vitiligo e tinha capitis sob luz de Wood.', licenciada: 'wikimedia-commons' }],
    referencias: ['Asawanonda P, Taylor CR. Wood\'s light in dermatology. Int J Dermatol, 1999.', 'Klatte JL et al. 100 years of Wood\'s lamp revised. J Eur Acad Dermatol Venereol, 2015.'],
  },
]
