import sys; sys.path.insert(0, str(__import__('pathlib').Path(__file__).resolve().parents[1]))
from leeds import *

salvar('adenocarcinoma-colorretal-1', [
    pat('glandulas-tumorais', 'glandulas-neoplasicas-complexas', seta(0.539, 0.241, 45),
        rotulo='Glândulas neoplásicas irregulares e ramificadas',
        vista=(0.50, 0.20, 0.58, 0.28)),
    pat('transicao', 'transicao-abrupta-para-mucosa-normal', seta(0.598, 0.20, 0),
        rotulo='Transição: tumor à esquerda, criptas normais à direita',
        nota='À esquerda da seta, glândulas neoplásicas escuras e desorganizadas; à direita, criptas normais cortadas transversalmente, redondas e cheias de células caliciformes.',
        vista=(0.55, 0.16, 0.66, 0.26)),
    pat('atipia', 'atipia-citologica', seta(0.5299, 0.2285, 0),
        rotulo='Núcleos grandes, alongados e estratificados',
        nota='Os núcleos ocupam toda a altura do epitélio (estratificação), são alongados ou vesiculosos, com nucléolos. Compare com os núcleos pequenos e basais das criptas normais.',
        vista=(0.524, 0.2235, 0.536, 0.2355)),
    pat('necrose-suja', 'necrose-suja', seta(0.4051, 0.2075, 315),
        rotulo='"Necrose suja" na luz glandular',
        nota='Restos necróticos eosinofílicos com fragmentos nucleares dentro da luz de uma glândula tumoral.',
        vista=(0.398, 0.199, 0.413, 0.214)),
    pat('invasao-muscular', 'infiltracao-da-muscular-propria', seta(0.3149, 0.1453, 45),
        rotulo='Glândulas tumorais entre os feixes da muscular própria',
        nota='Glândulas atípicas dissecando os feixes de músculo liso da muscular própria: a invasão ultrapassou a submucosa.',
        vista=(0.295, 0.12, 0.345, 0.17)),
    pat('frente-invasiva', 'invasao-estromal', seta(0.1335, 0.036, 0),
        rotulo='Frente de invasão profunda',
        nota='Na parte mais profunda do tumor, glândulas pequenas, cordões e ninhos infiltram um estroma fibroso, longe da mucosa de origem, e chegam a encostar em adipócitos.',
        vista=(0.095, 0.010, 0.165, 0.080)),
    pat('desmoplasia', 'reacao-desmoplasica', seta(0.1385, 0.0215, 0),
        rotulo='Estroma desmoplásico entre os ninhos tumorais',
        nota='Estroma pálido e fibroso, com fibroblastos fusiformes ativados, envolvendo os ninhos de carcinoma.',
        vista=(0.128, 0.010, 0.162, 0.044)),
    est('criptas-normais', 'cripta-de-lieberkuhn', seta(0.641, 0.176, 45), rotulo='Criptas normais do cólon',
        vista=(0.625, 0.16, 0.665, 0.20)),
    est('caliciformes', 'celula-caliciforme', seta(0.6505, 0.1865, 225), rotulo='Células caliciformes na mucosa normal',
        vista=(0.638, 0.178, 0.658, 0.198)),
    est('muscular-propria', 'muscular-externa', seta(0.78, 0.125, 0), rotulo='Muscular própria (sem tumor neste setor)',
        vista=(0.70, 0.05, 0.86, 0.20)),
], achados=[
    achado('glandulas-neoplasicas-complexas', 'presente', ['glandulas-tumorais'],
           'Toda a metade esquerda do corte é tumor: glândulas alongadas, ramificadas e fundidas, sem células caliciformes.'),
    achado('invasao-estromal', 'presente', ['frente-invasiva'],
           'O tumor atravessa a submucosa e infiltra as camadas profundas da parede em estroma desmoplásico.'),
    achado('infiltracao-da-muscular-propria', 'presente', ['invasao-muscular'],
           'Glândulas neoplásicas entre os feixes da muscular própria.'),
    achado('necrose-suja', 'presente', ['necrose-suja'], 'Frequente na luz das glândulas maiores.'),
    achado('transicao-abrupta-para-mucosa-normal', 'presente', ['transicao'],
           'Transição nítida entre tumor e mucosa colônica normal no meio do corte.'),
    achado('mucina-extracelular', 'ausente', [], 'Não há lagos de muco neste corte: é um adenocarcinoma usual (não mucinoso).'),
    achado('celulas-em-anel-de-sinete', 'ausente', [], 'O tumor forma glândulas; não há células isoladas em anel de sinete.'),
    achado('adenoma-residual', 'nao-avaliavel', [],
           'Não se reconhece com segurança um componente adenomatoso residual: o tumor ocupa toda a espessura da mucosa neste setor.'),
    achado('atipia-citologica', 'presente', ['atipia'], 'Atipia acentuada, com estratificação nuclear e nucléolos evidentes.'),
    achado('reacao-desmoplasica', 'presente', ['desmoplasia'], 'Estroma fibroso ativado em torno das glândulas invasivas, mais evidente na frente profunda.'),
    achado('invasao-angiolinfatica', 'nao-avaliavel', [],
           'Nenhum êmbolo tumoral inequívoco foi identificado neste corte; a pesquisa de invasão vascular exige exame sistemático e, às vezes, colorações especiais.'),
    achado('ulceracao-da-mucosa', 'ausente', [],
           'Nos setores examinados, as próprias glândulas neoplásicas formam a superfície voltada para a luz, sem úlcera recoberta por fibrina e neutrófilos.'),
], conferencias=3, resumo='Parede de cólon com adenocarcinoma moderadamente diferenciado (metade esquerda) ao lado de mucosa colônica normal (direita). O tumor forma glândulas complexas com "necrose suja", infiltra a muscular própria e forma uma frente de invasão profunda em estroma desmoplásico.')
print('ok')
