import sys; sys.path.insert(0, str(__import__('pathlib').Path(__file__).resolve().parents[1]))
from leeds import *

salvar('colite-ulcerativa-1', [
    pat('abscesso-cripta', 'abscesso-de-cripta', seta(0.3645, 0.0667, 45),
        rotulo='Abscesso de cripta: neutrófilos na luz',
        nota='A luz desta cripta, que deveria conter muco claro, está cheia de neutrófilos e restos celulares.',
        vista=(0.357, 0.059, 0.371, 0.073)),
    pat('distorcao', 'distorcao-arquitetural-das-criptas', seta(0.3715, 0.0765, 45),
        rotulo='Criptas distorcidas, ramificadas e irregulares',
        nota='As criptas têm tamanhos, formas e orientações diferentes, algumas ramificadas, e não formam as fileiras paralelas do cólon normal.',
        vista=(0.355, 0.052, 0.395, 0.085)),
    pat('linfoplasmocitario', 'infiltrado-linfoplasmocitario', seta(0.3755, 0.0787, 225),
        rotulo='Lâmina própria cheia de linfócitos e plasmócitos',
        vista=(0.370, 0.074, 0.384, 0.088)),
    pat('ulcera', 'ulceracao-da-mucosa', seta(0.240, 0.2112, 90),
        rotulo='Úlcera: sem epitélio, fundo de granulação coberto por fibrina',
        nota='Neste setor a mucosa desapareceu inteira: a superfície é tecido de granulação coberto por uma fina camada de fibrina.',
        vista=(0.222, 0.195, 0.258, 0.231)),
    pat('granulacao', 'tecido-de-granulacao', seta(0.2455, 0.2175, 135),
        rotulo='Tecido de granulação no fundo da úlcera',
        vista=(0.228, 0.205, 0.258, 0.235)),
    pat('pseudopolipo', 'pseudopolipo-inflamatorio', seta(0.2335, 0.160, 0),
        rotulo='Pseudopólipo: ilha de mucosa entre úlceras',
        nota='Uma ilha de mucosa inflamada fica em relevo, enquanto à direita e embaixo o fundo é ulcerado, sem criptas.',
        vista=(0.17, 0.10, 0.33, 0.26)),
    pat('congestao', 'hiperemia-e-congestao', seta(0.4195, 0.1045, 45),
        rotulo='Submucosa inflamada e congesta',
        nota='A inflamação e a congestão ultrapassam a mucosa e tomam a submucosa: sinal de colite grave (esta peça veio de colectomia).',
        vista=(0.38, 0.09, 0.44, 0.13)),
    est('muscular-propria', 'muscular-externa', seta(0.300, 0.2285, 0), rotulo='Muscular própria',
        vista=(0.25, 0.19, 0.35, 0.26)),
], achados=[
    achado('distorcao-arquitetural-das-criptas', 'presente', ['distorcao'],
           'Criptas irregulares e ramificadas em toda a mucosa preservada — sinal de doença crônica.'),
    achado('infiltrado-linfoplasmocitario', 'presente', ['linfoplasmocitario'],
           'Lâmina própria densamente expandida por linfócitos e plasmócitos, até a base das criptas.'),
    achado('abscesso-de-cripta', 'presente', ['abscesso-cripta'], 'Abscessos e criptite: a colite está em atividade.'),
    achado('pseudopolipo-inflamatorio', 'presente', ['pseudopolipo'], 'Ilhas de mucosa em relevo entre áreas ulceradas.'),
    achado('ulceracao-da-mucosa', 'presente', ['ulcera'], 'Úlceras largas, com perda de toda a mucosa, em vários pontos do corte.'),
    achado('infiltrado-neutrofilico', 'presente', ['abscesso-cripta'],
           'Neutrófilos nas criptas, na lâmina própria e no fundo das úlceras.'),
    achado('tecido-de-granulacao', 'presente', ['granulacao'], 'Fundo das úlceras com capilares neoformados e dilatados.'),
    achado('hiperemia-e-congestao', 'presente', ['congestao'], 'Vasos congestos na mucosa e, sobretudo, na submucosa.'),
], conferencias=3, resumo='Parede de cólon de colectomia com colite ulcerativa grave e ativa: mucosa com criptas distorcidas, lâmina própria abarrotada de linfócitos e plasmócitos, abscessos de cripta, úlceras largas com fundo de granulação e pseudopólipos; inflamação e congestão chegam à submucosa. Não há granulomas nem fissuras neste corte.')
print('ok')
