import { d, p, r, type ConteudoCaso } from './casos-imagem-tipos'

/** Segunda leva de TC — trauma (órgãos sólidos, bacia, membros e coluna). Pacientes fictícios. */
export const CASOS_TC_L2_TRAUMA: Record<string, ConteudoCaso> = {
  'lesao-renal-traumatica': {
    tema: 'Órgãos sólidos',
    titulo: 'Lesão renal traumática grau III com pseudoaneurisma',
    resumo: 'Lacerações lineares e em cunha no polo superior do rim direito sem atingir o sistema coletor, pequeno pseudoaneurisma, hematoma adrenal, fraturas costais, coágulo vesical e contusão pulmonar.',
    protocolo: 'TC de abdome com contraste, fase portal, axial e sagital',
    series: ['Axial', 'Sagital'],
    rotulos: {
      Consolidation: r('Consolidação na base direita', 'Consolidação com broncograma aéreo no lobo inferior direito.',
        'No trauma, uma consolidação na base pulmonar logo abaixo de costelas fraturadas é contusão pulmonar: sangue e edema dentro dos alvéolos pelo impacto. Ela aparece nas primeiras horas, piora em um a dois dias e melhora em uma semana, ao contrário da pneumonia, que surge depois.',
        'Contusão pulmonar extensa aumenta o risco de insuficiência respiratória: monitore a oxigenação.'),
      Hematoma: r('Hematoma adrenal direito', 'Lesão oval e hipodensa na adrenal direita.',
        'A adrenal direita, presa entre o fígado, o rim e a coluna, sangra no trauma do flanco direito. Hematoma adrenal isolado costuma ter tratamento conservador. Quando os dois lados sangram, a insuficiência adrenal aguda passa a ser uma preocupação real.'),
      defects: r('Lacerações lineares', 'Faixas sem realce atravessando o parênquima do polo superior.',
        'Laceração é uma fenda no rim que aparece como linha escura porque ali o parênquima não realça. A escala da AAST classifica a lesão pela profundidade: até 1 cm é grau II, mais de 1 cm sem atingir o sistema coletor é grau III, e com o sistema coletor rompido passa a ser grau IV.',
        'Na suspeita de lesão do sistema coletor, peça uma fase excretora para ver se a urina extravasa.'),
      'wedge-shaped': r('Defeito em cunha', 'Área triangular sem realce no polo superior.',
        'Uma área em cunha com a base na cápsula pode ser laceração profunda ou infarto segmentar por lesão de um ramo arterial. Distinguir os dois importa, porque o infarto pode indicar dissecção da artéria renal. Aqui ela faz parte das lacerações do polo superior.'),
      'arterial aneurysm': r('Pseudoaneurisma intrarrenal', 'Pequeno foco muito denso no polo superior, como contraste no vaso.',
        'O pseudoaneurisma é uma ruptura da parede arterial contida pelos tecidos em volta. Ele não sangra hoje, mas pode romper dias depois e causar hemorragia tardia. Por isso, mesmo em paciente estável, a presença de pseudoaneurisma costuma indicar embolização por arteriografia.',
        'Hematúria maciça dias após trauma renal tratado de forma conservadora sugere pseudoaneurisma roto.'),
      fractures: r('Fraturas das costelas 10 e 11', 'Fraturas pouco desviadas das costelas baixas direitas.',
        'Fraturas das costelas 10, 11 e 12 indicam impacto sobre o rim, o fígado e o baço. Toda vez que aparecem, a TC de abdome deve procurar lesões desses órgãos com cuidado, mesmo com o paciente estável e o abdome pouco doloroso.'),
      clot: r('Coágulo na bexiga', 'Material denso na parte de baixo da bexiga, sem fluxo.',
        'Sangue vindo do rim desce pelo ureter e coagula na bexiga. O coágulo fica na parte mais baixa e não realça nem tem fluxo ao Doppler, o que o separa de tumor. Coágulos grandes podem obstruir a sonda e exigir lavagem vesical.'),
      "Foley's bulb": r('Balão da sonda vesical', 'O balão da sonda de Foley dentro da bexiga.',
        'Identificar o balão evita confundi-lo com lesão e confirma a posição da sonda. A sonda permite medir a diurese e acompanhar a hematúria, que deve clarear nas horas seguintes se o rim parar de sangrar.'),
    },
    achados: [
      'Lacerações lineares e em cunha no polo superior do rim direito, com mais de 1 cm, sem atingir o sistema coletor e sem hematoma perirrenal — grau III.',
      'Pequeno foco hiperdenso no polo superior, compatível com pseudoaneurisma; hidroureteronefrose direita.',
      'Coágulo na parte pendente da bexiga com sonda de Foley.',
      'Hematoma adrenal direito, fraturas das costelas 10 e 11 direitas e contusão no lobo inferior direito.',
    ],
    armadilhas: [
      'Sem fase excretora, lesão do sistema coletor pode passar despercebida.',
      'Hematúria não se correlaciona com a gravidade: lesão do pedículo pode não ter hematúria.',
      'Coágulo vesical pode imitar tumor; Doppler ou controle resolvem.',
    ],
    conduta: 'Tratamento conservador com repouso, controle de hemoglobina e diurese, arteriografia com embolização do pseudoaneurisma e TC de controle com fase excretora.',
    vinheta: {
      cenario: 'Sala de trauma',
      identificacao: 'Homem de 27 anos, jogador de rúgbi amador.',
      queixa: 'Dor forte no lado direito das costas e urina com sangue depois de uma pancada no jogo.',
      historia: 'Durante uma partida levou uma joelhada no flanco direito. Sentiu dor intensa que piora ao respirar e, ao urinar no vestiário, a urina saiu vermelha com coágulos. Chegou ao hospital consciente e caminhando, duas horas depois.',
      antecedentes: [
        'Pessoais: sem doenças renais conhecidas',
        'Pessoais: sem uso de anticoagulantes',
        'Familiares: sem doenças relevantes',
        'Hábitos: não fuma, bebe aos fins de semana',
      ],
      vitais: { pa: '122 × 76 mmHg', fc: '104 bpm', fr: '22 irpm', satO2: '95% em ar ambiente', temp: '36,6 °C' },
      exame: [
        'Equimose e dor no flanco direito',
        'Dor à palpação das costelas baixas direitas',
        'Hematúria macroscópica pela sonda vesical',
        'Hemoglobina de 12,4 g/dL',
      ],
      pedido: 'Trauma fechado no flanco com hematúria macroscópica e paciente estável: a pergunta é o grau da lesão renal e se há lesão vascular.',
      pergunta: 'TC de abdome com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Lesão renal com pseudoaneurisma',
      veredito: 'Lesão renal direita grau III com pseudoaneurisma intrarrenal, hematoma adrenal e fraturas costais',
      correlacao: 'A joelhada no flanco direito fraturou as costelas 10 e 11 e lacerou o polo superior do rim, que fica logo abaixo delas. A hematúria com coágulos vem do rim lacerado. As lacerações passam de 1 cm sem atingir o sistema coletor, por isso são grau III, e o pseudoaneurisma explica o risco de sangramento tardio, que justifica a embolização mesmo com o paciente estável.',
      distratores: [
        d('Lesão do sistema coletor grau IV', 'Haveria urina extravasando para fora do rim na fase excretora e laceração alcançando o sistema coletor, o que não aparece neste exame.'),
        d('Avulsão do pedículo renal', 'O rim inteiro ficaria sem realce, com hematoma volumoso e instabilidade, quadro de grau V que exige cirurgia imediata. Este paciente está estável e o rim realça.'),
        d('Contusão renal isolada', 'Mostraria área mal definida de realce reduzido sem fendas no parênquima e sem pseudoaneurisma, o que corresponde ao grau I. Ela não deixa pseudoaneurisma.'),
      ],
    },
  },

  'fratura-de-acetabulo-com-luxacao-central': {
    tema: 'Bacia e membros',
    titulo: 'Fratura de acetábulo das duas colunas com luxação central do quadril',
    resumo: 'Fratura cominutiva do acetábulo direito acometendo as duas colunas com a cabeça femoral protruindo para a pelve, fraturas dos ramos púbicos, derrame articular e hematoma extraperitoneal.',
    protocolo: 'TC de pelve sem contraste, janelas óssea e de partes moles',
    series: ['Janela óssea', 'Partes moles'],
    rotulos: {
      'complex fracture': r('Fratura das duas colunas do acetábulo', 'Fratura cominutiva separando as colunas anterior e posterior.',
        'O acetábulo é sustentado por duas colunas ósseas, uma anterior e uma posterior, como um Y invertido. Na fratura das duas colunas, nenhum fragmento da superfície articular fica preso ao osso ilíaco íntegro. A TC é indispensável para ver o desvio dos fragmentos e planejar a fixação.',
        'Use reconstruções 3D e o corte axial juntos para classificar pela classificação de Letournel.'),
      'central right hip dislocation': r('Luxação central do quadril', 'A cabeça femoral empurrada para dentro da pelve.',
        'Quando a força chega pelo trocânter maior, num impacto lateral, a cabeça do fêmur é empurrada contra o fundo do acetábulo, quebra a parede medial e entra na pelve. A redução precisa ser rápida para proteger a cartilagem e a irrigação da cabeça.'),
      'iliopubic ramus': r('Fratura do ramo iliopúbico', 'Fratura do ramo superior do púbis.',
        'Fraturas dos ramos púbicos acompanham as fraturas do acetábulo e mostram que o anel pélvico também foi lesado. Elas podem lesar a bexiga e a uretra, que ficam logo atrás do púbis, por isso a sondagem deve ser cuidadosa.'),
      'ischiopubic ramus': r('Fratura do ramo isquiopúbico', 'Fratura do ramo inferior do púbis.',
        'A fratura dos dois ramos do mesmo lado indica instabilidade do arco anterior da pelve. Junto com a fratura acetabular, o conjunto aumenta o sangramento e a dor e define a estratégia de fixação.'),
      'extraperitoneal space': r('Hematoma extraperitoneal', 'Líquido denso no espaço pré-vesical, compatível com sangue.',
        'Fraturas da pelve sangram dos vasos e do osso esponjoso para o espaço extraperitoneal. O sangue fica contido, mas o volume pode ser grande e levar ao choque. Líquido denso ali também pode indicar lesão de bexiga, que deve ser investigada com cistografia.',
        'Instabilidade com fratura pélvica: pense em tamponamento pré-peritoneal ou arteriografia com embolização.'),
      'joint effusion': r('Derrame articular do quadril', 'Líquido denso dentro da articulação do quadril.',
        'Sangue dentro da articulação, a hemartrose, acompanha toda fratura que entra na articulação. Ele distende a cápsula e aumenta a dor. Fragmentos soltos dentro da articulação precisam ser retirados na cirurgia.'),
    },
    achados: [
      'Fratura cominutiva do acetábulo direito acometendo as colunas anterior e posterior, com luxação central da cabeça femoral para a pelve.',
      'Fraturas dos ramos iliopúbico e isquiopúbico direitos.',
      'Derrame articular do quadril direito.',
      'Coleção de alta densidade no espaço extraperitoneal da pelve, compatível com hematoma.',
    ],
    armadilhas: [
      'A radiografia simples subestima o número de fragmentos e o desvio.',
      'Hematoma extraperitoneal grande pode esconder lesão de bexiga.',
      'Lesão do nervo ciático deve ser pesquisada antes e depois da redução.',
    ],
    conduta: 'Estabilização hemodinâmica, tração esquelética para reduzir a luxação, cistografia se houver suspeita de lesão vesical e fixação cirúrgica do acetábulo nos primeiros dias.',
    vinheta: {
      cenario: 'Sala de trauma',
      identificacao: 'Homem de 45 anos, motorista de caminhão.',
      queixa: 'Dor forte no quadril direito e impossibilidade de mexer a perna depois de capotamento.',
      historia: 'O caminhão capotou e ele foi lançado contra a porta do lado direito. Chegou consciente, com dor intensa no quadril direito, sem conseguir mover a perna. Recebeu dois litros de cristaloide no transporte.',
      antecedentes: [
        'Pessoais: hipertensão',
        'Pessoais: obesidade',
        'Familiares: sem doenças relevantes',
        'Hábitos: tabagista de 20 maços-ano',
      ],
      vitais: { pa: '98 × 62 mmHg', fc: '118 bpm', fr: '22 irpm', satO2: '96% em ar ambiente', temp: '36,2 °C' },
      exame: [
        'Membro inferior direito encurtado, sem rotação evidente',
        'Equimose no trocânter maior direito',
        'Dor à compressão da pelve',
        'Pulsos distais presentes e sensibilidade preservada',
      ],
      pedido: 'Impacto lateral no quadril com membro encurtado e sinais de sangramento: a pergunta é o tipo de lesão acetabular e se há sangramento pélvico.',
      pergunta: 'TC de pelve. Qual é o achado que responde à pergunta clínica?',
      achado: 'Luxação central com fratura acetabular',
      veredito: 'Fratura das duas colunas do acetábulo direito com luxação central e hematoma extraperitoneal',
      correlacao: 'O impacto lateral contra a porta chegou pelo trocânter maior e empurrou a cabeça do fêmur contra o fundo do acetábulo, que se partiu nas duas colunas e deixou a cabeça entrar na pelve. Por isso a perna encurtou sem rotação. O sangue das fraturas no espaço extraperitoneal explica a taquicardia e a pressão baixa.',
      distratores: [
        d('Luxação posterior do quadril', 'Ocorre no impacto do joelho contra o painel, com a perna fletida, aduzida e rodada para dentro, e a cabeça fica atrás do acetábulo.'),
        d('Fratura do colo do fêmur desviada', 'Encurta e roda a perna para fora, típica de idoso com queda da própria altura, com o acetábulo e a cabeça no lugar. Também não produz hematoma extraperitoneal volumoso.'),
        d('Fratura isolada dos ramos púbicos', 'Dói na virilha e ao andar, mas a cabeça femoral fica no acetábulo e o membro não encurta nem perde o movimento. O sangramento costuma ser menor.'),
      ],
    },
  },

  'fratura-de-odontoide-e-jefferson': {
    tema: 'Coluna',
    titulo: 'Fratura de Jefferson com fratura do odontoide tipo III',
    resumo: 'Fratura dos arcos anterior e posterior do atlas com ligamento transverso íntegro e fratura do odontoide estendendo-se ao corpo de C2, em coluna espondilótica; lesão calcificada no forame magno.',
    protocolo: 'TC de coluna cervical sem contraste, janela óssea, axial e coronal',
    series: ['Axial', 'Coronal'],
    rotulos: {
      'anterior arch fracture': r('Fratura do arco anterior de C1', 'Traço de fratura no arco anterior do atlas.',
        'O atlas é um anel sem corpo vertebral, com dois arcos e duas massas laterais. Uma carga axial sobre a cabeça empurra os côndilos occipitais contra as massas laterais e abre o anel em vários pontos. Essa é a fratura de Jefferson, que costuma ocorrer em mergulho em água rasa ou queda de cabeça.'),
      'calcified extra-axial lesion': r('Lesão calcificada no forame magno', 'Pequena lesão calcificada junto ao forame magno, incidental.',
        'Uma lesão calcificada fora do cérebro, junto à dura-máter, pode ser meningioma calcificado ou outras lesões calcificadas benignas raras. Não tem relação com o trauma, mas deve ser relatada e investigada depois com ressonância.'),
      'posterior arches fractures': r('Fraturas dos arcos posteriores', 'Traços nos dois lados do arco posterior de C1.',
        'Fraturas em quatro pontos do anel, dois anteriores e dois posteriores, caracterizam a Jefferson clássica. O canal medular costuma ficar largo, porque os fragmentos se afastam para fora, por isso os déficits neurológicos são raros.'),
      'body of C2 vertebra fracture': r('Fratura do odontoide tipo III', 'Traço que desce da base do dente para o corpo de C2.',
        'Anderson e D’Alonzo dividem as fraturas do odontoide em três tipos: tipo I na ponta, tipo II na base do dente e tipo III entrando no corpo de C2. O tipo III tem osso esponjoso com boa irrigação e costuma consolidar com imobilização. O tipo II consolida mal e frequentemente precisa de cirurgia.',
        'Em idosos com coluna rígida, quedas simples causam fraturas de C1 e C2: tenha limiar baixo para pedir TC.'),
    },
    achados: [
      'Fratura do arco anterior e dos arcos posteriores do atlas — fratura de Jefferson.',
      'Intervalo atlantodental normal, sugerindo ligamento transverso íntegro.',
      'Fratura do odontoide estendendo-se ao corpo de C2 — tipo III de Anderson e D’Alonzo.',
      'Espondilose cervical difusa com redução do espaço C5-C6; lesão calcificada de 1,2 cm junto ao forame magno.',
    ],
    armadilhas: [
      'Fratura de C1 vem com outra fratura cervical em até metade dos casos: examine toda a coluna.',
      'Soma do desvio das massas laterais acima de 7 mm sugere ruptura do ligamento transverso e instabilidade.',
      'Coluna espondilótica e rígida fratura com traumas leves e pode não mostrar desvio na radiografia.',
    ],
    conduta: 'Imobilização cervical rígida, ressonância para o ligamento transverso e a medula, e tratamento com órtese ou halo; cirurgia se houver instabilidade ou falha de consolidação.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Homem de 72 anos, aposentado.',
      queixa: 'Dor forte na nuca depois de cair da escada.',
      historia: 'Escorregou na escada de casa e bateu o alto da cabeça no chão. Não perdeu a consciência. Tem dor intensa na nuca e não consegue virar a cabeça. Nega formigamento ou fraqueza nos braços e pernas.',
      antecedentes: [
        'Pessoais: artrose cervical com dor crônica',
        'Pessoais: hipertensão e fibrilação atrial em uso de anticoagulante',
        'Familiares: sem doenças relevantes',
        'Hábitos: sedentário, mora sozinho',
      ],
      vitais: { pa: '146 × 88 mmHg', fc: '88 bpm', fr: '18 irpm', satO2: '96% em ar ambiente', temp: '36,4 °C' },
      exame: [
        'Escoriação no vértice do crânio',
        'Dor à palpação da região occipital e cervical alta',
        'Força e sensibilidade normais nos quatro membros',
        'Colar cervical colocado pelo resgate',
      ],
      pedido: 'Idoso com carga axial no crânio e dor cervical alta, sem déficit: a pergunta é se há fratura da junção craniocervical.',
      pergunta: 'TC de coluna cervical. Qual é o achado que responde à pergunta clínica?',
      achado: 'Fraturas de C1 e do odontoide',
      veredito: 'Fratura de Jefferson combinada com fratura do odontoide tipo III',
      correlacao: 'O golpe no alto da cabeça transmitiu uma carga axial que abriu o anel do atlas em vários pontos e partiu a base do odontoide até o corpo de C2. A coluna rígida pela artrose deixa a junção craniocervical mais frágil, por isso uma queda simples bastou. O canal alargado pela fratura explica a ausência de déficit.',
      distratores: [
        d('Fratura do enforcado de C2', 'Fratura as partes interarticulares de C2 por hiperextensão, com o odontoide e o atlas preservados, e não por carga axial. O atlas fica íntegro.'),
        d('Luxação atlantoaxial rotatória', 'Fixa a cabeça girada, típica de criança após infecção ou trauma leve, sem traços de fratura no atlas ou no áxis. A TC dinâmica mostra a rotação fixa entre C1 e C2.'),
        d('Espondilose cervical dolorosa agudizada', 'Explica a dor crônica do paciente, mas não abre o anel do atlas nem produz traço de fratura no corpo de C2. Também não explica a dor nova e intensa após a queda.'),
      ],
    },
  },

  'fratura-de-jefferson': {
    tema: 'Coluna',
    titulo: 'Fratura de Jefferson em dois pontos',
    resumo: 'Fratura do anel de C1 no arco anterior esquerdo e no arco posterior direito, com intervalo atlantoaxial normal e edema pré-vertebral leve.',
    protocolo: 'TC de coluna cervical sem contraste, janela óssea, sagital e axial',
    series: ['Sagital', 'Axial'],
    rotulos: {
      'atlantoaxial interval': r('Intervalo atlantodental', 'Distância normal entre o arco anterior de C1 e o dente.',
        'O ligamento transverso segura o dente do áxis contra o arco anterior do atlas. Se ele se rompe, o atlas desliza para a frente e o intervalo aumenta, acima de 3 mm no adulto. Intervalo normal sugere ligamento íntegro e, portanto, fratura estável, tratável com imobilização.',
        'A ressonância confirma a integridade do ligamento transverso quando a TC deixa dúvida.'),
      'soft tissue swelling': r('Edema pré-vertebral', 'Partes moles aumentadas na frente de C1 e C2.',
        'Na frente das vértebras cervicais altas, as partes moles devem medir até cerca de 7 mm. Aumento depois de trauma indica hematoma ou edema por fratura ou lesão ligamentar. Às vezes é o único sinal de uma fratura difícil de ver na radiografia.'),
      '# anterior arch on the left': r('Fratura do arco anterior esquerdo', 'Traço com afastamento no arco anterior do atlas, à esquerda.',
        'O anel de C1, como todo anel, tende a quebrar em pelo menos dois pontos. Aqui o traço anterior está à esquerda e se abriu, com afastamento dos fragmentos. A abertura mostra que a carga empurrou as massas laterais para fora.'),
      '# posterior arch on the right': r('Fratura do arco posterior direito', 'Segundo traço no arco posterior do atlas, à direita.',
        'O segundo ponto de fratura, no lado oposto, fecha o anel partido em duas metades. As massas laterais se deslocam pouco em relação a C2. Desvio total acima de 7 mm sugeriria ruptura do ligamento transverso e instabilidade.'),
    },
    achados: [
      'Fratura do anel de C1 em dois pontos: arco anterior esquerdo, com diástase, e arco posterior direito, com leve desvio lateral.',
      'Discreto desalinhamento das massas laterais de C1 sobre C2.',
      'Intervalo atlantoaxial normal, sem avulsão na inserção do ligamento transverso.',
      'Edema pré-vertebral leve.',
    ],
    armadilhas: [
      'Variantes congênitas com falha de fusão do arco posterior de C1 imitam fratura: têm bordas lisas e corticalizadas.',
      'A radiografia transoral pode mostrar o desvio das massas laterais, mas a TC é o exame de escolha.',
      'Procure fratura associada de C2 e dos côndilos occipitais.',
    ],
    conduta: 'Imobilização cervical rígida por 8 a 12 semanas com controle por imagem; ressonância se houver dúvida sobre o ligamento transverso.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Mulher de 22 anos, estudante.',
      queixa: 'Dor forte na nuca depois de mergulhar numa piscina rasa.',
      historia: 'Mergulhou de cabeça na parte rasa de uma piscina numa festa e bateu o alto da cabeça no fundo. Saiu da água sozinha, com dor intensa na nuca. Nega formigamento, fraqueza ou perda de consciência. Bebeu algumas cervejas antes.',
      antecedentes: [
        'Pessoais: sem doenças',
        'Pessoais: sem cirurgias',
        'Familiares: sem doenças relevantes',
        'Hábitos: etilismo social',
      ],
      vitais: { pa: '118 × 74 mmHg', fc: '92 bpm', fr: '16 irpm', satO2: '99% em ar ambiente', temp: '36,5 °C' },
      exame: [
        'Escoriação no couro cabeludo do vértice',
        'Dor à palpação da região occipital e cervical alta',
        'Rigidez cervical por dor',
        'Exame neurológico normal',
      ],
      pedido: 'Mergulho em água rasa com dor cervical alta e exame neurológico normal: a pergunta é se há fratura e se ela é estável.',
      pergunta: 'TC de coluna cervical. Qual é o achado que responde à pergunta clínica?',
      achado: 'Fratura do anel do atlas',
      veredito: 'Fratura de Jefferson em dois pontos com ligamento transverso provavelmente íntegro',
      correlacao: 'O mergulho em água rasa é o mecanismo clássico de carga axial: o crânio empurra as massas laterais do atlas para fora e o anel quebra em dois pontos opostos. Como os fragmentos se afastam, o canal fica mais largo e a medula é poupada, por isso o exame neurológico é normal. O intervalo atlantodental normal indica fratura estável.',
      distratores: [
        d('Falha congênita do arco de C1', 'Também interrompe o anel, mas tem bordas lisas e arredondadas com cortical, sem edema pré-vertebral nem dor após trauma. Costuma ser achado incidental.'),
        d('Entorse cervical por hiperextensão', 'Causa dor e rigidez cervical, mas a TC não mostra traço de fratura nem edema pré-vertebral localizado em C1. O mecanismo também é outro, sem carga axial.'),
        d('Fratura em explosão de C5', 'Mergulho também pode causar essa lesão, mas na coluna cervical baixa, com fragmento no canal e frequente déficit. O atlas estaria íntegro.'),
      ],
    },
  },

  'fratura-do-enforcado': {
    tema: 'Coluna',
    titulo: 'Fratura do enforcado com anterolistese de C2',
    resumo: 'Fratura bilateral das partes interarticulares de C2 com anterolistese grau 1 de C2 sobre C3 e forames transversos preservados.',
    protocolo: 'TC de coluna cervical sem contraste, janela óssea, axial',
    rotulos: {
      'bilateral pars interarticulari': r('Fratura bilateral das partes interarticulares de C2', 'Traços nos dois lados, separando o corpo de C2 do arco posterior.',
        'A espondilolistese traumática de C2 recebeu o nome de fratura do enforcado porque era a lesão causada pela forca, com hiperextensão e tração. Hoje ocorre em acidentes de carro, quando o queixo bate no painel e a cabeça é jogada para trás. O corpo de C2 desliza para a frente sobre C3 enquanto o arco posterior fica para trás, o que alarga o canal e explica por que muitos pacientes não têm déficit.',
        'Confira os forames transversos: traço que os atravessa pode lesar a artéria vertebral e exige angiotomografia.'),
    },
    apontamentosProprios: [
      { ...p(0, 0.61, 0.41, -45, 'Forame transverso preservado', 'Orifício por onde passa a artéria vertebral, sem traço de fratura.',
        'A artéria vertebral sobe pelos forames transversos de C6 a C1. Na fratura do enforcado, o traço pode atravessar o forame e lesar a artéria, com risco de AVC de circulação posterior. Forames íntegros, como aqui, tornam a lesão vascular menos provável, mas a dúvida pede angiotomografia.'), corte: 15 },
      { ...p(0, 0.50, 0.54, 90, 'Canal vertebral amplo', 'O canal fica largo porque o arco se separa do corpo de C2.',
        'Na fratura do enforcado, o corpo de C2 desliza para a frente e o arco posterior fica para trás. Em vez de estreitar, o canal se alarga, o que explica por que a maioria dos pacientes não tem déficit neurológico. É o oposto da fratura em explosão, em que o fragmento invade o canal.'), corte: 15 },
    ],
    achados: [
      'Fratura bilateral das partes interarticulares de C2.',
      'Anterolistese grau 1 de C2 sobre C3.',
      'Forames transversos preservados.',
      'Sem fragmentos no canal vertebral.',
    ],
    armadilhas: [
      'A classificação de Levine e Edwards depende do desvio e da angulação, que mudam o tratamento.',
      'O tipo IIa, com grande angulação, piora com tração e não deve ser tracionado.',
      'Lesão da artéria vertebral pode causar AVC de circulação posterior horas depois.',
    ],
    conduta: 'Imobilização cervical rígida ou halo conforme o desvio, angiotomografia se houver traço nos forames transversos, e cirurgia nos tipos instáveis.',
    vinheta: {
      cenario: 'Sala de trauma',
      identificacao: 'Homem de 31 anos, representante comercial.',
      queixa: 'Dor no pescoço depois de batida de carro.',
      historia: 'Dirigia sem cinto e bateu de frente em outro carro. O rosto bateu no volante e a cabeça foi jogada para trás. Chegou consciente, com dor no pescoço alto e no queixo, sem formigamento nem fraqueza.',
      antecedentes: [
        'Pessoais: sem doenças',
        'Pessoais: fratura de clavícula na adolescência',
        'Familiares: sem doenças relevantes',
        'Hábitos: dirige muitas horas por dia',
      ],
      vitais: { pa: '132 × 82 mmHg', fc: '96 bpm', fr: '18 irpm', satO2: '98% em ar ambiente', temp: '36,6 °C' },
      exame: [
        'Laceração no queixo',
        'Dor à palpação da coluna cervical alta',
        'Força e sensibilidade normais',
        'Sem sinais de lesão vascular cervical',
      ],
      pedido: 'Hiperextensão cervical com golpe no queixo e dor cervical alta: a pergunta é se há fratura de C2.',
      pergunta: 'TC de coluna cervical. Qual é o achado que responde à pergunta clínica?',
      achado: 'Fratura do enforcado de C2',
      veredito: 'Espondilolistese traumática de C2 com fratura bilateral das partes interarticulares',
      correlacao: 'A laceração no queixo marca o ponto de impacto: o volante empurrou o queixo e jogou a cabeça em hiperextensão, que partiu as duas partes interarticulares de C2. O corpo deslizou para a frente e o arco ficou para trás, o que alarga o canal e explica a ausência de déficit.',
      distratores: [
        d('Fratura do odontoide tipo II', 'Também é fratura de C2, mas atravessa a base do dente, e não as partes interarticulares do arco, e costuma surgir em quedas de idosos.'),
        d('Fratura de Jefferson do atlas', 'Quebra o anel de C1 por carga axial no alto da cabeça, sem traço em C2 nem deslizamento de C2 sobre C3. Nesse caso o golpe teria sido no alto da cabeça.'),
        d('Pseudossubluxação fisiológica de C2', 'É deslizamento normal de C2 sobre C3 em crianças, sem fratura e com a linha espinolaminar alinhada. Em adulto com trauma, deslizamento de C2 deve ser tratado como fratura até prova em contrário.'),
      ],
    },
  },

  'fratura-de-chance': {
    tema: 'Coluna',
    titulo: 'Fratura de L1 com fragmento retropulsado e rotação',
    resumo: 'Fratura cominutiva em cunha anterior de L1 com perda de altura, fragmento retropulsado comprimindo o saco dural e rotação no nível da fratura; pâncreas e baço preservados.',
    protocolo: 'TC de coluna toracolombar sem contraste, axial e sagital',
    series: ['Axial', 'Sagital'],
    rotulos: {
      pancreas: r('Pâncreas sem lesão', 'Pâncreas íntegro na frente da coluna.',
        'O cinto de segurança abdominal comprime o abdome contra a coluna. Por isso as fraturas por flexão-distração da transição toracolombar vêm com lesões do pâncreas, do duodeno e do intestino em até metade dos casos. Ver o pâncreas íntegro é parte do laudo.',
        'Equimose em faixa no abdome após acidente com cinto: procure lesão de alça e de coluna.'),
      spleen: r('Baço sem lesão', 'Baço íntegro, sem laceração nem hematoma.',
        'No trauma de alta energia, o baço é o órgão sólido mais lesado. A ausência de líquido livre e de laceração permite tratar a coluna sem preocupação imediata com sangramento abdominal. Isso também orienta a analgesia.'),
      fragment: r('Fragmento retropulsado', 'Pedaço da parede posterior do corpo de L1 empurrado para o canal.',
        'Quando a parede posterior do corpo vertebral quebra, um fragmento pode ser empurrado para trás, para dentro do canal. Ele comprime o saco dural e o cone medular, que fica em L1, e ameaça a função das pernas, da bexiga e do intestino. A porcentagem do canal ocupada orienta a descompressão.'),
      'wedge fracture': r('Fratura em cunha de L1', 'Corpo de L1 achatado na frente, com perda de altura.',
        'A flexão comprime a parte anterior do corpo vertebral, que fica em forma de cunha. Se a parede posterior também quebra, como aqui, é uma fratura em explosão, mais instável. A transição toracolombar, entre T11 e L2, é o ponto mais lesado porque é onde a coluna torácica rígida encontra a lombar móvel.'),
      rotation: r('Rotação no nível da fratura', 'Processos espinhosos em planos diferentes acima e abaixo.',
        'Rotação entre os segmentos acima e abaixo da fratura indica que o complexo ligamentar posterior se rompeu. Isso transforma a lesão em instável, com risco de piora neurológica, e geralmente indica fixação cirúrgica.'),
    },
    achados: [
      'Fratura cominutiva em cunha anterior do corpo de L1 com perda de altura, alcançando os platôs e o processo transverso direito.',
      'Fragmento retropulsado comprimindo o saco dural, com apagamento dos planos de gordura.',
      'Rotação no nível da fratura, com processos espinhosos em planos diferentes acima e abaixo; perda da lordose lombar.',
      'Pâncreas, baço e demais vísceras sem lesão; atelectasias posteriores.',
    ],
    armadilhas: [
      'A verdadeira fratura de Chance é horizontal, atravessando corpo, pedículos e processo espinhoso; aqui a lesão predomina em compressão com rotação.',
      'Fratura em explosão com retropulsão pode passar como cunha simples na radiografia.',
      'Lesões de alça intestinal podem não aparecer na primeira TC.',
    ],
    conduta: 'Imobilização em bloco, exame neurológico seriado, ressonância para o complexo ligamentar e o cone medular, e fixação cirúrgica com descompressão se houver instabilidade ou déficit.',
    vinheta: {
      cenario: 'Sala de trauma',
      identificacao: 'Mulher de 29 anos, nutricionista.',
      queixa: 'Dor forte nas costas depois de acidente de carro.',
      historia: 'Estava no banco de trás com cinto de dois pontos quando o carro bateu de frente. O corpo dobrou para a frente sobre o cinto. Sente dor intensa na transição entre as costas e a lombar e um pouco de dormência nas coxas.',
      antecedentes: [
        'Pessoais: sem doenças',
        'Gestacionais: nuligesta',
        'Familiares: sem doenças relevantes',
        'Hábitos: pratica corrida',
      ],
      vitais: { pa: '116 × 72 mmHg', fc: '100 bpm', fr: '20 irpm', satO2: '97% em ar ambiente', temp: '36,4 °C' },
      exame: [
        'Equimose em faixa na parte baixa do abdome',
        'Degrau doloroso à palpação da coluna em L1',
        'Hipoestesia discreta nas coxas, força preservada',
        'Abdome doloroso, sem defesa',
      ],
      pedido: 'Flexão violenta sobre o cinto com dor toracolombar e alteração sensitiva: a pergunta é o tipo de fratura e o risco para o canal.',
      pergunta: 'TC de coluna toracolombar. Qual é o achado que responde à pergunta clínica?',
      achado: 'Fratura instável de L1 com retropulsão',
      veredito: 'Fratura cominutiva em cunha de L1 com fragmento retropulsado e rotação',
      correlacao: 'O corpo dobrou sobre o cinto e a carga em flexão esmagou a frente de L1 e partiu a parede posterior, que empurrou um fragmento para o canal — por isso a dormência nas coxas. A rotação entre os segmentos mostra que os ligamentos posteriores romperam, o que torna a lesão instável. A equimose em faixa lembra que alças e pâncreas precisam ser examinados.',
      distratores: [
        d('Fratura osteoporótica por compressão', 'Achata o corpo vertebral em cunha em idosos com trauma mínimo, sem fragmento no canal nem rotação entre os segmentos. A paciente é jovem.'),
        d('Fratura isolada de processo transverso', 'Dói muito, mas é estável e não alcança o corpo vertebral nem o canal, portanto não explica a alteração sensitiva. Ela não exige cirurgia.'),
        d('Hérnia de disco traumática em L1', 'Comprimiria o saco dural, mas sem fratura do corpo vertebral nem perda de altura em cunha. Hérnia discal traumática isolada na transição toracolombar é rara e não explica o achatamento do corpo vertebral.'),
      ],
    },
  },

  'fratura-de-calcaneo': {
    tema: 'Bacia e membros',
    titulo: 'Fratura cominutiva intra-articular do calcâneo',
    resumo: 'Fratura do calcâneo direito com mais de três traços primários, desvio dos fragmentos, perda da congruência da articulação subtalar e espessamento de partes moles.',
    protocolo: 'TC de tornozelo e pé sem contraste, janela óssea e de partes moles',
    series: ['Janela óssea', 'Partes moles'],
    rotulos: {
      displaced: r('Fragmentos desviados', 'Fragmentos afastados e degrau na superfície articular.',
        'A faceta posterior do calcâneo articula com o tálus na articulação subtalar, responsável pela inversão e eversão do pé. Degrau ou afastamento nessa superfície leva a artrose dolorosa. A classificação de Sanders conta quantos fragmentos a faceta posterior tem no corte coronal: quatro ou mais é tipo IV, de pior prognóstico.',
        'Queda de altura com fratura de calcâneo: examine a coluna lombar, lesada junto em muitos casos.'),
      fracture: r('Traços de fratura múltiplos', 'Vários traços atravessando o corpo do calcâneo.',
        'Na queda de pé, o tálus funciona como uma cunha e é empurrado para dentro do calcâneo, que explode em vários fragmentos. O calcâneo perde altura e alarga, o que muda a forma do retropé, dificulta o uso de calçados e comprime os tendões fibulares.'),
      'soft tissue thickening': r('Edema de partes moles', 'Partes moles espessadas em volta do calcâneo.',
        'O retropé tem pele fina e pouca gordura, e o edema após a fratura é intenso. Cirurgia feita com edema tem alto risco de necrose da pele e infecção. Por isso espera-se o sinal da ruga, quando a pele volta a enrugar, antes de operar.'),
    },
    achados: [
      'Fratura cominutiva, intra-articular e desviada do calcâneo direito com mais de três traços primários.',
      'Perda da congruência da articulação subtalar.',
      'Espessamento de partes moles adjacente.',
    ],
    armadilhas: [
      'A radiografia lateral subestima a cominuição; o ângulo de Böhler reduzido é uma pista.',
      'Fratura bilateral do calcâneo e da coluna são comuns no mesmo mecanismo.',
      'Síndrome compartimental do pé pode ocorrer e exige fasciotomia.',
    ],
    conduta: 'Elevação, gelo, imobilização e controle do edema; cirurgia com redução e fixação ou artrodese primária conforme o tipo de Sanders, depois da melhora das partes moles.',
    vinheta: {
      cenario: 'Pronto-socorro de ortopedia',
      identificacao: 'Homem de 38 anos, pedreiro.',
      queixa: 'Dor forte no calcanhar direito, sem conseguir pisar, depois de cair do andaime.',
      historia: 'Caiu de um andaime de cerca de quatro metros e aterrissou de pé, com o peso no pé direito. Não consegue apoiar o pé e o calcanhar inchou muito em poucas horas. Também sente dor na parte baixa das costas.',
      antecedentes: [
        'Pessoais: sem doenças',
        'Pessoais: sem cirurgias prévias',
        'Familiares: sem doenças relevantes',
        'Hábitos: tabagista de 15 maços-ano',
      ],
      vitais: { pa: '134 × 84 mmHg', fc: '92 bpm', fr: '18 irpm', satO2: '98% em ar ambiente', temp: '36,5 °C' },
      exame: [
        'Retropé direito alargado e edemaciado',
        'Equimose na planta do pé',
        'Dor à palpação da coluna lombar',
        'Pulsos e sensibilidade do pé preservados',
      ],
      pedido: 'Queda de altura sobre o pé com retropé alargado: a pergunta é o padrão da fratura e se a articulação foi atingida.',
      pergunta: 'TC de tornozelo e pé. Qual é o achado que responde à pergunta clínica?',
      achado: 'Fratura intra-articular do calcâneo',
      veredito: 'Fratura cominutiva intra-articular desviada do calcâneo direito, Sanders tipo IV',
      correlacao: 'A queda de quatro metros sobre o pé empurrou o tálus como uma cunha para dentro do calcâneo, que explodiu em muitos fragmentos, entrou na articulação subtalar e alargou o retropé. A equimose na planta é típica. A dor lombar lembra que o mesmo mecanismo fratura a coluna e precisa ser investigado.',
      distratores: [
        d('Ruptura do tendão de Aquiles', 'Dói atrás do tornozelo com falha palpável no tendão e teste de Thompson positivo, sem alargamento do retropé nem fratura. Ocorre em arrancada esportiva.'),
        d('Fratura por avulsão da tuberosidade', 'É fratura extra-articular do calcâneo pelo puxão do tendão de Aquiles, em idoso com osteoporose, sem atingir a subtalar. O retropé não alarga.'),
        d('Fratura do pilão tibial distal', 'Também ocorre por carga axial, mas atinge a superfície articular da tíbia no tornozelo, não o calcâneo. A TC mostraria a tíbia partida e o calcâneo íntegro.'),
      ],
    },
  },

  'lesao-esplenica-traumatica': {
    tema: 'Órgãos sólidos',
    titulo: 'Lesão esplênica traumática em evolução com hematoma subcapsular',
    resumo: 'Lacerações lineares no baço, hematoma subcapsular crônico, calcificação capsular e líquido na goteira parietocólica esquerda até o fundo de saco.',
    protocolo: 'TC de abdome sem contraste e fase tardia',
    series: ['Fase tardia', 'Sem contraste'],
    rotulos: {
      'chronic calcification': r('Calcificação capsular crônica', 'Linha densa na cápsula que não muda entre as fases.',
        'Uma linha densa no baço pode ser contraste saindo de um vaso, que é sangramento ativo, ou calcificação antiga. A diferença é que o sangramento ativo aparece só depois do contraste e cresce na fase tardia, enquanto a calcificação já está lá antes do contraste e não muda. Comparar as fases evita uma embolização desnecessária.',
        'Sempre compare a fase sem contraste antes de chamar uma área densa de extravasamento.'),
      'hypodense linear areas': r('Lacerações esplênicas', 'Linhas hipodensas atravessando o parênquima.',
        'As lacerações são fendas no baço que não realçam e aparecem escuras. A classificação da AAST gradua a lesão pela profundidade das lacerações e pelo tamanho do hematoma. Lacerações que chegam ao hilo e lesão vascular aumentam o grau e o risco de falha do tratamento conservador.'),
      'paracolic gutter fluid': r('Líquido na goteira parietocólica', 'Líquido na goteira esquerda descendo até o fundo de saco.',
        'O sangue do baço escorre pela goteira parietocólica esquerda até a pelve. A quantidade de líquido e sua densidade ajudam a estimar o volume perdido. Sangue que chega ao fundo de saco indica hemoperitônio moderado.'),
      'mildly hyperdense fluid': r('Líquido levemente denso', 'Líquido com densidade um pouco maior que a água.',
        'Sangue fresco mede de 30 a 45 UH, coágulo de 45 a 70 UH. Líquido levemente denso longe do baço é sangue que já se diluiu ou foi parcialmente reabsorvido. Perto do baço, o coágulo mais denso, o sinal do coágulo sentinela, aponta o órgão que sangrou.'),
      'calcific line': r('Linha calcificada no sem contraste', 'A mesma linha densa já visível antes do contraste.',
        'Ver a linha densa na fase sem contraste confirma que é calcificação e não extravasamento. É o raciocínio de comparar fases que separa achado antigo de sangramento que precisa de tratamento imediato.'),
      'fluid collection': r('Hematoma subcapsular', 'Coleção em crescente junto à cápsula do baço.',
        'O sangue que fica preso embaixo da cápsula forma uma coleção em crescente que achata o contorno do baço. Com o tempo, o hematoma fica menos denso. Hematoma subcapsular grande pode romper a cápsula dias depois do trauma, causando a ruptura esplênica tardia.'),
      lacerations: r('Lacerações no sem contraste', 'As fendas vistas também na fase sem contraste.',
        'Na fase sem contraste, as lacerações são mais difíceis de ver porque baço e sangue têm densidades parecidas. Por isso o contraste é indispensável no trauma, e a fase sem contraste serve sobretudo para comparar áreas densas.'),
    },
    achados: [
      'Múltiplas lacerações lineares hipodensas no baço.',
      'Coleção subcapsular curvilínea hipodensa, compatível com hematoma em fase crônica.',
      'Linha capsular hiperdensa já presente sem contraste e constante em todas as fases — calcificação, não extravasamento ativo.',
      'Líquido na goteira parietocólica esquerda, levemente denso, estendendo-se ao fundo de saco; atelectasia no lobo inferior esquerdo e artéria subclávia direita aberrante.',
    ],
    armadilhas: [
      'Extravasamento ativo cresce e muda de forma entre as fases; calcificação não.',
      'Baço com fendas congênitas lisas pode imitar laceração.',
      'Ruptura tardia de hematoma subcapsular pode ocorrer dias após o trauma.',
    ],
    conduta: 'Tratamento conservador em paciente estável com observação, hemoglobina seriada e repouso; arteriografia com embolização se houver extravasamento ou pseudoaneurisma; esplenectomia se instável.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Homem de 24 anos, ciclista de montanha.',
      queixa: 'Dor no lado esquerdo da barriga e no ombro esquerdo há quatro dias, que piorou hoje.',
      historia: 'Há quatro dias caiu da bicicleta numa trilha e bateu o lado esquerdo do tórax numa pedra. Teve dor, mas melhorou com analgésico. Hoje a dor no lado esquerdo da barriga aumentou, ficou tonto ao levantar e sente dor no ombro esquerdo.',
      antecedentes: [
        'Pessoais: mononucleose há dois meses',
        'Pessoais: sem cirurgias',
        'Familiares: sem doenças relevantes',
        'Hábitos: atleta, não fuma',
      ],
      vitais: { pa: '108 × 66 mmHg', fc: '106 bpm', fr: '20 irpm', satO2: '97% em ar ambiente', temp: '36,8 °C' },
      exame: [
        'Dor à palpação do hipocôndrio esquerdo',
        'Dor referida no ombro esquerdo, sinal de Kehr',
        'Equimose nas costelas baixas esquerdas',
        'Hemoglobina de 11,2 g/dL, era 14 há quatro dias',
      ],
      pedido: 'Trauma no flanco esquerdo há dias com piora da dor, sinal de Kehr e queda da hemoglobina: a pergunta é se há lesão esplênica e se está sangrando ativamente.',
      pergunta: 'TC de abdome sem contraste e em fase tardia. Qual é o achado que responde à pergunta clínica?',
      achado: 'Lacerações esplênicas com hematoma',
      veredito: 'Lesão esplênica com lacerações, hematoma subcapsular e hemoperitônio, sem extravasamento ativo',
      correlacao: 'A pancada no flanco esquerdo lacerou o baço, que estava aumentado e frágil pela mononucleose recente. O sangue preso sob a cápsula formou o hematoma, e o que escapou desceu pela goteira esquerda até a pelve. A dor no ombro esquerdo é o sangue irritando o diafragma. A linha densa na cápsula é calcificação, não sangramento ativo.',
      distratores: [
        d('Extravasamento ativo de contraste esplênico', 'Apareceria só após o contraste e cresceria na fase tardia; aqui a linha densa já existe sem contraste e não muda. Esse é o motivo de comparar as fases antes de indicar embolização.'),
        d('Fratura de costela isolada sem lesão', 'Explicaria a dor costal, mas não a queda de hemoglobina, o sinal de Kehr nem o líquido livre na pelve. A TC mostra lacerações no baço que a fratura sozinha não explica.'),
        d('Infarto esplênico por mononucleose', 'Causa áreas em cunha sem realce no baço, mas sem fendas lineares, hematoma subcapsular nem sangue na cavidade. Também não explicaria a queda da hemoglobina depois do trauma.'),
      ],
    },
  },
}
