import { d, type ConteudoCasoTC } from './casos-tc-tipos'

/** Casos de TC de face, órbita e pescoço. Pacientes das vinhetas são fictícios. */
export const CASOS_TC_CABECA_PESCOCO: Record<string, ConteudoCasoTC> = {
  'fratura-blowout-da-orbita': {
    titulo: 'Fratura em blowout do assoalho da órbita',
    resumo: 'Defeito amplo no assoalho orbitário esquerdo com herniação do reto inferior e da gordura para o seio maxilar.',
    protocolo: 'TC de face sem contraste, reconstrução coronal, janela óssea',
    rotulos: {
      Defect: ['Defeito no assoalho da órbita', 'Falha óssea por onde o conteúdo orbitário desce para o seio maxilar.'],
      'Fracture fragment': ['Fragmento da fratura', 'Lasca do assoalho deslocada para dentro do seio, como um alçapão.'],
      'Left inferior rectus muscle': ['Músculo reto inferior esquerdo', 'O músculo herniou pelo defeito e está preso: explica a limitação do olhar para cima.'],
    },
    achados: [
      'Fratura do assoalho da órbita esquerda com defeito amplo.',
      'Fragmento ósseo deslocado para o seio maxilar.',
      'Herniação do músculo reto inferior e da gordura orbitária pelo defeito.',
      'Rebordo orbitário preservado, o que caracteriza o blowout puro.',
    ],
    armadilhas: [
      'O plano coronal é o que mostra o assoalho e o músculo; no axial a fratura pode passar despercebida.',
      'Em crianças a fratura em alçapão pode prender o músculo com pouco achado na imagem e reflexo oculocardíaco grave — urgência cirúrgica.',
      'Sangue no seio maxilar após trauma orbitário é pista indireta de fratura do assoalho.',
    ],
    conduta: 'Avaliação oftalmológica para acuidade e motilidade, orientação para não assoar o nariz, antibiótico conforme protocolo. Encarceramento muscular, enoftalmia significativa ou diplopia persistente indicam reconstrução do assoalho.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Homem de 24 anos, estudante universitário.',
      queixa: 'Visão dupla ao olhar para cima depois de levar uma bolada no olho esquerdo.',
      historia: 'Jogava squash quando a bola o atingiu diretamente no olho esquerdo. O olho inchou em minutos. Ao assoar o nariz, a pálpebra inchou ainda mais e ficou crepitante. Desde então vê duas imagens quando olha para cima e sente formigamento na bochecha e no lábio superior esquerdos.',
      antecedentes: [
        'Pessoais: miopia leve, usa lentes de contato',
        'Pessoais: sem cirurgias oculares',
        'Familiares: sem doenças oculares hereditárias',
        'Hábitos: atleta amador, não usava óculos de proteção',
      ],
      vitais: { pa: '124 × 76 mmHg', fc: '78 bpm', fr: '14 irpm', satO2: '99% em ar ambiente', temp: '36,6 °C' },
      exame: [
        'Edema e equimose periorbitária esquerda com enfisema subcutâneo palpebral',
        'Limitação da elevação do olho esquerdo com diplopia vertical',
        'Hipoestesia no território do nervo infraorbitário',
        'Acuidade visual preservada, sem hifema',
      ],
      pedido: 'Trauma direto na órbita com diplopia vertical e hipoestesia infraorbitária: a pergunta é se o assoalho quebrou e se há músculo preso.',
      pergunta: 'TC de face com reconstrução coronal. Qual é o achado que responde à pergunta clínica?',
      achado: 'Fratura blowout do assoalho orbitário',
      veredito: 'Fratura em blowout do assoalho da órbita esquerda com herniação do reto inferior',
      correlacao: 'Um objeto maior que a abertura da órbita aumenta a pressão intraorbitária e o osso mais fino cede: o assoalho. O nervo infraorbitário corre ali, daí a hipoestesia; o reto inferior hernia pelo defeito e fica preso, daí a diplopia ao olhar para cima. O enfisema palpebral ao assoar confirma comunicação com o seio. O coronal mostra tudo: defeito, fragmento e músculo descido.',
      distratores: [
        d('Fratura do complexo zigomático', 'Também dá hipoestesia infraorbitária, mas rompe o arco, a parede lateral e o rebordo, com afundamento malar. Aqui o rebordo está íntegro e só o assoalho cedeu.'),
        d('Paralisia traumática do nervo troclear', 'Causa diplopia vertical pior ao olhar para baixo e para dentro, sem enfisema nem hipoestesia. A limitação deste paciente é na elevação e há músculo herniado na imagem.'),
        d('Hematoma retrobulbar com proptose', 'Empurra o olho para frente, eleva a pressão intraocular e ameaça a visão. Este olho não está protruso, a acuidade está normal e há um defeito ósseo, não uma coleção.'),
      ],
    },
  },

  'abscesso-subperiosteal-da-orbita': {
    titulo: 'Abscesso subperiosteal da órbita',
    resumo: 'Pansinusite à direita com rarefação da lâmina papirácea e coleção subperiosteal extraconal medial.',
    protocolo: 'TC de órbitas e seios da face com contraste, janela de partes moles',
    rotulos: {
      'maxillary sinusitis': ['Sinusite maxilar', 'Seio maxilar direito preenchido por material inflamatório.'],
      'ethmoidal sinusitis': ['Sinusite etmoidal', 'Células etmoidais opacificadas, vizinhas diretas da órbita.'],
      'frontal sinusitis': ['Sinusite frontal', 'Seio frontal direito velado.'],
      'the lamina papyracea': ['Lâmina papirácea rarefeita', 'A parede medial da órbita, finíssima, perde definição: por ali a infecção passa.'],
      'inter-ethmoidal septae': ['Septos interetmoidais', 'Septos das células etmoidais com erosão, sinal de infecção agressiva.'],
    },
    achados: [
      'Opacificação dos seios maxilar, etmoidal e frontal à direita.',
      'Rarefação da lâmina papirácea direita.',
      'Coleção extraconal subperiosteal junto à parede medial da órbita, deslocando o reto medial.',
      'Proptose e borramento da gordura orbitária.',
    ],
    armadilhas: [
      'Celulite pré-septal fica na frente do septo orbitário e não limita os movimentos oculares; dor à movimentação, proptose ou queda da visão significam doença pós-septal.',
      'A classificação de Chandler vai da celulite pré-septal ao abscesso subperiosteal, abscesso orbitário e trombose do seio cavernoso.',
      'Em crianças o etmoide é a fonte clássica, pela lâmina papirácea fina e deiscente.',
    ],
    conduta: 'Internação, antibiótico venoso de amplo espectro, avaliação oftalmológica seriada e drenagem endoscópica ou externa se o abscesso for grande, se a visão piorar ou se não houver resposta em 24 a 48 horas.',
    vinheta: {
      cenario: 'Pronto-socorro pediátrico',
      identificacao: 'Menino de 9 anos, trazido pela mãe.',
      queixa: 'Olho direito inchado, vermelho e doendo para mexer há dois dias.',
      historia: 'Há uma semana está resfriado, com coriza amarelada e obstrução nasal. Há dois dias as pálpebras do olho direito incharam e hoje ele reclama de dor ao olhar para os lados e de ver dobrado. Teve febre de 39 °C esta madrugada. Recebeu amoxicilina de um posto há três dias sem melhora.',
      antecedentes: [
        'Pessoais: rinite alérgica, sinusites de repetição',
        'Gestacionais: nascido a termo, parto normal, sem intercorrências neonatais',
        'Familiares: pai asmático',
        'Vacinação completa para a idade',
      ],
      vitais: { pa: '104 × 64 mmHg', fc: '118 bpm', fr: '22 irpm', satO2: '98% em ar ambiente', temp: '38,9 °C' },
      exame: [
        'Edema e eritema palpebral direito',
        'Proptose com desvio lateral do globo',
        'Dor e limitação à adução e à elevação do olho direito',
        'Acuidade visual preservada e reflexos pupilares normais',
      ],
      pedido: 'Celulite periorbitária com dor à movimentação ocular, proptose e febre após sinusite: a pergunta é se a infecção é pós-septal e se há coleção a drenar.',
      pergunta: 'TC de órbitas e seios com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Abscesso subperiosteal medial da órbita',
      veredito: 'Abscesso subperiosteal medial da órbita direita secundário a etmoidite, com rarefação da lâmina papirácea',
      correlacao: 'Sinusite que não responde, febre alta e dor à movimentação ocular tiram o quadro da celulite pré-septal. A etmoidite atravessou a lâmina papirácea e formou uma coleção entre o periósteo e o osso da parede medial, empurrando o globo para fora e o reto medial. A TC mostra os seios velados, a lâmina rarefeita e a coleção extraconal.',
      distratores: [
        d('Celulite pré-septal simples', 'Inflama só as pálpebras, na frente do septo orbitário, sem dor à movimentação nem proptose. Este menino tem limitação da motilidade e uma coleção atrás do septo.'),
        d('Trombose do seio cavernoso', 'É o último estágio, com oftalmoplegia bilateral, quemose e acometimento de pares cranianos; na TC o seio cavernoso fica abaulado e sem contraste. Aqui o processo é unilateral e a coleção é medial.'),
        d('Dacriocistite aguda com celulite', 'A inflamação fica sobre o saco lacrimal, no canto medial abaixo do tendão, com refluxo purulento pelo ponto lacrimal. Esta criança tem sinusite e coleção dentro da órbita, atrás da lâmina papirácea.'),
      ],
    },
  },

  'tumor-de-pott': {
    titulo: 'Tumor de Pott',
    resumo: 'Sinusite frontal complicada com abscesso subgaleal na fronte e abscesso cerebral frontal.',
    protocolo: 'TC de crânio e seios com contraste',
    rotulos: {
      'frontal sinuses': ['Seios frontais', 'Seios frontais opacificados, origem da infecção.'],
      'Mucosal enhancement': ['Realce mucoso', 'Mucosa espessada e realçada dos seios, sinal de inflamação ativa.'],
      'subgaleal soft tissue swelling': ['Abscesso subgaleal frontal', 'Tumefação sob o couro cabeludo da fronte: o tumor de Pott propriamente dito.'],
    },
    achados: [
      'Opacificação dos seios frontais, etmoidais e maxilar direito com realce mucoso.',
      'Tumefação subgaleal frontal com coleção, por osteomielite da tábua anterior.',
      'Lesão frontal direita com realce anelar e edema vasogênico: abscesso cerebral.',
      'Osteomielite do osso frontal com erosão das tábuas.',
    ],
    armadilhas: [
      'A tumefação da testa em adolescente com sinusite não é celulite superficial: é osteomielite frontal até prova em contrário.',
      'A mesma infecção atravessa a tábua posterior pelas veias diploicas: procure empiema epidural, subdural e abscesso cerebral.',
      'Adolescentes do sexo masculino são o grupo típico, pela vascularização diploica exuberante.',
    ],
    conduta: 'Antibiótico venoso prolongado e drenagem cirúrgica do seio, do abscesso subgaleal e, quando indicado, do abscesso intracraniano, com equipe de otorrinolaringologia e neurocirurgia.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Adolescente de 15 anos, sexo masculino, trazido pelo pai.',
      queixa: 'Inchaço mole na testa e dor de cabeça intensa há cinco dias.',
      historia: 'Há três semanas teve sinusite, tratada por dois dias com antibiótico que abandonou quando melhorou. Há cinco dias surgiu um inchaço mole e dolorido no meio da testa, que foi crescendo. Hoje vomitou, está sonolento e teve febre de 39,5 °C. O pai notou que ele está confundindo palavras.',
      antecedentes: [
        'Pessoais: rinite alérgica sem tratamento regular',
        'Gestacionais: prematuro de 35 semanas, sem complicações',
        'Familiares: sem imunodeficiências conhecidas',
        'Hábitos: pratica natação três vezes por semana',
      ],
      vitais: { pa: '118 × 70 mmHg', fc: '112 bpm', fr: '20 irpm', satO2: '98% em ar ambiente', temp: '39,4 °C' },
      exame: [
        'Tumefação flutuante e dolorosa na região frontal mediana',
        'Glasgow 14, com parafasias',
        'Rinorreia purulenta à rinoscopia',
        'Rigidez de nuca discreta',
      ],
      pedido: 'Tumefação frontal após sinusite mal tratada, com febre e alteração neurológica: a pergunta é a extensão óssea e intracraniana da infecção.',
      pergunta: 'TC de crânio e seios com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Tumor de Pott com abscesso cerebral',
      veredito: 'Tumor de Pott: osteomielite frontal com abscesso subgaleal e abscesso cerebral frontal',
      correlacao: 'A sinusite frontal mal tratada infectou o osso frontal: pela tábua anterior formou o abscesso sob o couro cabeludo que o pai viu crescer; pela posterior chegou ao cérebro, e as parafasias e a sonolência são o abscesso frontal com edema. A TC mostra os três andares da mesma infecção.',
      distratores: [
        d('Celulite do couro cabeludo frontal', 'Seria inflamação superficial, sem coleção sob a gálea nem destruição óssea, e não explicaria a alteração de linguagem. Aqui há osso acometido e lesão intracraniana.'),
        d('Meningite bacteriana com sinusite', 'Pode complicar a sinusite, com rigidez de nuca e febre, mas não forma tumefação frontal nem lesão com anel e edema no parênquima.'),
        d('Cisto dermoide frontal infectado', 'É lesão congênita da linha média, lentamente progressiva, com gordura na TC. Este paciente tem quadro agudo pós-sinusite e seios opacificados.'),
      ],
    },
  },

  'abscesso-peritonsilar': {
    titulo: 'Abscesso periamigdaliano',
    resumo: 'Amígdalas aumentadas que se tocam na linha média e coleção com realce periférico junto à amígdala direita.',
    protocolo: 'TC de pescoço com contraste, janela de partes moles',
    rotulos: {
      'Palatine tonsils': ['Amígdalas palatinas', 'Amígdalas aumentadas que se tocam na linha média: amígdalas em beijo.'],
      'Peritonsillar abscess': ['Abscesso periamigdaliano', 'Coleção hipodensa com realce periférico ao lado da amígdala direita.'],
      Hypopharyngeal: ['Hipofaringe', 'Via aérea da hipofaringe estreitada pelo edema.'],
      'Right vallecula': ['Valécula direita', 'Espaço entre a base da língua e a epiglote, reduzido pelo processo inflamatório.'],
      'internal laryngocele': ['Laringocele interna', 'Dilatação aérea do ventrículo laríngeo, achado associado.'],
      'Right pyriform sinus': ['Seio piriforme direito', 'Recesso da hipofaringe, assimétrico pelo edema.'],
    },
    achados: [
      'Amígdalas palatinas aumentadas, tocando-se na linha média.',
      'Coleção hipodensa com realce periférico adjacente à amígdala direita.',
      'Estreitamento da via aérea orofaríngea e hipofaríngea.',
      'Laringocele interna incidental.',
    ],
    armadilhas: [
      'O diagnóstico é clínico; a TC entra quando há dúvida entre celulite e abscesso, suspeita de extensão profunda ou trismo que impede o exame.',
      'Flegmão realça de forma difusa; abscesso tem centro hipodenso com anel periférico.',
      'Desvio da úvula e voz de batata quente são as pistas clínicas mais úteis.',
    ],
    conduta: 'Drenagem por punção ou incisão, antibiótico com cobertura para estreptococos e anaeróbios, analgesia e hidratação. Amigdalectomia considerada em episódios recorrentes.',
    vinheta: {
      cenario: 'Pronto-socorro de otorrinolaringologia',
      identificacao: 'Mulher de 22 anos, estudante de enfermagem.',
      queixa: 'Dor de garganta muito forte à direita, não consegue abrir a boca nem engolir.',
      historia: 'Há seis dias começou com dor de garganta e febre, tratada com anti-inflamatório por conta própria. Melhorou por dois dias e piorou muito do lado direito, com dor irradiada para o ouvido. Hoje não consegue engolir a própria saliva, a voz ficou abafada e a boca abre só dois dedos.',
      antecedentes: [
        'Pessoais: amigdalites de repetição, três no último ano',
        'Gestacionais: nuligesta, usa anticoncepcional oral',
        'Familiares: sem doenças relevantes',
        'Hábitos: tabagista de 10 cigarros por dia',
      ],
      vitais: { pa: '116 × 72 mmHg', fc: '108 bpm', fr: '18 irpm', satO2: '98% em ar ambiente', temp: '38,7 °C' },
      exame: [
        'Trismo com abertura oral de dois centímetros',
        'Abaulamento do pilar amigdaliano anterior direito',
        'Úvula desviada para a esquerda',
        'Voz de batata quente e sialorreia',
      ],
      pedido: 'Faringoamigdalite com trismo, desvio da úvula e voz abafada: a pergunta é se há coleção periamigdaliana e se ela se estende aos espaços profundos.',
      pergunta: 'TC de pescoço com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Abscesso periamigdaliano direito',
      veredito: 'Abscesso periamigdaliano direito com amígdalas em beijo, sem extensão aos espaços profundos',
      correlacao: 'A amigdalite parcialmente tratada evoluiu para coleção entre a cápsula da amígdala e o músculo constritor. O pus empurra o pilar e a úvula, irrita o pterigóideo medial e causa trismo. A TC mostra a coleção com anel periférico ao lado da amígdala direita e as amígdalas se tocando na linha média.',
      distratores: [
        d('Celulite periamigdaliana sem coleção', 'Dá dor e edema do pilar, mas sem trismo importante e com realce difuso, sem centro hipodenso. Aqui há anel periférico em torno de conteúdo líquido.'),
        d('Epiglotite aguda do adulto', 'Causa odinofagia intensa e voz abafada, mas a orofaringe parece pouco alterada e a epiglote fica espessada, com risco de obstrução. A alteração desta paciente é na loja amigdaliana, com úvula desviada.'),
        d('Mononucleose com hipertrofia amigdaliana', 'Aumenta as duas amígdalas de forma simétrica, com adenomegalia cervical posterior e esplenomegalia, sem trismo nem coleção. Aqui o processo é unilateral e há pus.'),
      ],
    },
  },

  'abscesso-retrofaringeo': {
    titulo: 'Abscesso periamigdaliano com extensão retrofaríngea',
    resumo: 'Coleção com gás e debris a partir da amígdala esquerda, cruzando o espaço mucoso faríngeo posterior até os espaços retrofaríngeo e visceral.',
    protocolo: 'TC de pescoço com contraste, janela de partes moles',
    rotulos: {
      'peritonsillar abscess': ['Abscesso periamigdaliano', 'Coleção com gás junto à amígdala palatina esquerda, ponto de partida.'],
      retropharyngeal: ['Extensão retrofaríngea', 'O pus desce pelo espaço retrofaríngeo, atrás da faringe e à frente da fáscia pré-vertebral.'],
      'visceral space': ['Espaço visceral', 'A coleção alcança o espaço que envolve faringe, esôfago e traqueia.'],
    },
    achados: [
      'Coleção com gás e debris partindo da amígdala palatina esquerda.',
      'Extensão pelo espaço mucoso faríngeo posterior e retrofaríngeo.',
      'Acometimento do espaço visceral, com estreitamento da via aérea.',
      'Sem extensão mediastinal nos cortes disponíveis.',
    ],
    armadilhas: [
      'O espaço retrofaríngeo é uma avenida para o mediastino: sempre inclua o tórax superior no exame.',
      'Gás na coleção sugere anaeróbios ou fístula e aumenta a gravidade.',
      'Espessamento pré-vertebral na radiografia lateral é a pista inicial; a TC define se é coleção drenável.',
    ],
    conduta: 'Proteção da via aérea, antibiótico venoso de amplo espectro com cobertura anaeróbia e drenagem cirúrgica. Vigiar mediastinite descendente.',
    vinheta: {
      cenario: 'Sala de emergência',
      identificacao: 'Homem de 44 anos, motorista de aplicativo.',
      queixa: 'Dor de garganta, dificuldade para engolir e pescoço duro há quatro dias.',
      historia: 'Começou com dor de garganta à esquerda há uma semana. Há quatro dias não consegue engolir sólidos, tem dor ao mexer o pescoço e hoje sente falta de ar ao deitar. Teve calafrios e a voz ficou rouca. Tomou dipirona e um antibiótico que sobrou em casa por dois dias.',
      antecedentes: [
        'Pessoais: diabetes tipo 2 sem acompanhamento',
        'Pessoais: dentes em mau estado, sem ida ao dentista há anos',
        'Familiares: mãe diabética',
        'Hábitos: etilismo diário, tabagista de 30 maços-ano',
      ],
      vitais: { pa: '104 × 62 mmHg', fc: '124 bpm', fr: '26 irpm', satO2: '93% em ar ambiente', temp: '39,2 °C' },
      exame: [
        'Estridor inspiratório leve na posição deitada',
        'Abaulamento da parede posterior da orofaringe e do pilar esquerdo',
        'Rigidez cervical com dor à extensão do pescoço',
        'Glicemia capilar de 382 mg/dL',
      ],
      pedido: 'Infecção faríngea com disfagia, rigidez cervical, estridor e instabilidade em diabético: a pergunta é a extensão da coleção nos espaços profundos.',
      pergunta: 'TC de pescoço com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Abscesso cervical com extensão retrofaríngea',
      veredito: 'Abscesso periamigdaliano esquerdo com gás, estendendo-se aos espaços retrofaríngeo e visceral',
      correlacao: 'A infecção amigdaliana num diabético descompensado não se limitou à loja: o pus desceu pelo espaço retrofaríngeo e chegou ao espaço visceral. A rigidez cervical e a dor à extensão vêm do espaço retrofaríngeo inflamado; o estridor, da compressão da via aérea. O gás na coleção sinaliza anaeróbios e gravidade.',
      distratores: [
        d('Abscesso periamigdaliano sem extensão', 'Daria trismo e desvio da úvula, mas sem rigidez cervical, estridor ou abaulamento da parede posterior. A coleção deste paciente atravessa para trás da faringe.'),
        d('Angina de Ludwig submandibular', 'É celulite do assoalho da boca, com língua elevada e endurecimento submandibular bilateral de origem dentária. A coleção aqui nasce na amígdala e desce por trás da faringe.'),
        d('Tendinite calcificada do longo do pescoço', 'Causa dor cervical e odinofagia com edema pré-vertebral, mas afebril e com calcificação anterior a C1 e C2, sem coleção com gás.'),
      ],
    },
  },

  'sindrome-de-lemierre': {
    titulo: 'Síndrome de Lemierre',
    resumo: 'Trombose séptica da veia jugular após abscesso periamigdaliano, com êmbolos sépticos pulmonares.',
    protocolo: 'TC de pescoço e tórax com contraste',
    rotulos: {
      thrombosis: ['Trombose da veia jugular interna', 'Falha de enchimento na jugular interna direita, com parede espessada e realçada.'],
      'peritonsillar abscess,': ['Abscesso periamigdaliano residual', 'Coleção remanescente após a drenagem, junto à amígdala direita.'],
      'Post-procedural gas foci': ['Gás pós-procedimento', 'Focos de ar no trajeto da drenagem recente.'],
      'reactive lymph nodes': ['Linfonodos reativos', 'Linfonodos cervicais aumentados pelo processo inflamatório.'],
      'septic pulmonary nodules': ['Nódulos pulmonares sépticos', 'Nódulos periféricos, alguns escavados, semeados pela veia infectada.'],
    },
    achados: [
      'Inflamação persistente da amígdala direita e do espaço parafaríngeo após drenagem.',
      'Trombose da veia jugular interna direita.',
      'Linfonodomegalias cervicais reativas.',
      'Nódulos pulmonares periféricos múltiplos, compatíveis com êmbolos sépticos.',
    ],
    armadilhas: [
      'Febre persistente e dor cervical lateral após faringite em jovem: pense em Lemierre e peça contraste venoso.',
      'Nódulos pulmonares periféricos com vaso nutridor e cavitação são êmbolos sépticos até prova contrária.',
      'O agente clássico é o Fusobacterium necrophorum, anaeróbio que as hemoculturas de rotina podem não mostrar se não forem incubadas de forma adequada.',
    ],
    conduta: 'Antibiótico venoso prolongado com cobertura anaeróbia, drenagem de coleções e discussão individualizada sobre anticoagulação.',
    vinheta: {
      cenario: 'Enfermaria de clínica médica',
      identificacao: 'Mulher de 19 anos, estudante.',
      queixa: 'Febre persistente e dor no lado direito do pescoço, agora com dor ao respirar.',
      historia: 'Há dez dias teve abscesso periamigdaliano direito drenado no pronto-socorro e recebeu antibiótico oral. A dor de garganta melhorou, mas a febre com calafrios continuou e surgiu dor e inchaço na lateral direita do pescoço. Há dois dias sente dor em pontada no tórax ao respirar e tosse com escarro com raias de sangue.',
      antecedentes: [
        'Pessoais: previamente hígida',
        'Gestacionais: nuligesta, sem uso de anticoncepcional',
        'Familiares: sem trombofilias conhecidas',
        'Hábitos: nega drogas injetáveis, etilismo social',
      ],
      vitais: { pa: '98 × 58 mmHg', fc: '126 bpm', fr: '28 irpm', satO2: '91% em ar ambiente', temp: '39,6 °C' },
      exame: [
        'Empastamento doloroso ao longo do esternocleidomastóideo direito',
        'Linfonodos cervicais dolorosos',
        'Estertores crepitantes esparsos em ambos os hemitórax',
        'Sem sopros cardíacos',
      ],
      pedido: 'Sepse após infecção orofaríngea com dor cervical lateral e sintomas pulmonares novos: a pergunta é se há complicação vascular e disseminação embólica.',
      pergunta: 'TC de pescoço e tórax com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Tromboflebite séptica da jugular interna',
      veredito: 'Síndrome de Lemierre: tromboflebite séptica da jugular interna direita com êmbolos sépticos pulmonares',
      correlacao: 'A infecção periamigdaliana se estendeu ao espaço parafaríngeo e infectou a parede da jugular interna, que trombosou. A dor ao longo do esternocleidomastóideo é a veia inflamada; os fragmentos do trombo infectado viajam aos pulmões e explicam a dor pleurítica, a hemoptise e os nódulos periféricos.',
      distratores: [
        d('Endocardite tricúspide com êmbolos sépticos', 'Também semeia nódulos pulmonares escavados, mas em usuários de drogas injetáveis ou portadores de cateter, com sopro tricúspide. Esta paciente não tem fator de risco e a fonte é a jugular trombosada.'),
        d('Pneumonia bacteriana adquirida na comunidade', 'Daria consolidação lobar ou segmentar, não múltiplos nódulos periféricos, e não explicaria a dor e o empastamento cervical lateral.'),
        d('Tromboembolismo pulmonar por trombofilia', 'Causa dor pleurítica e hemoptise com falhas de enchimento nas artérias pulmonares, sem febre séptica nem nódulos escavados. Aqui os êmbolos são infectados e partem da jugular.'),
      ],
    },
  },
}
