import { d, p, r, type ConteudoCaso } from './casos-imagem-tipos'

/** Raio-X com apontamentos — fraturas do membro superior. Pacientes fictícios. */
export const CASOS_RX_OSSO: Record<string, ConteudoCaso> = {
  'fratura-de-smith': {
    tema: 'Fraturas e luxações',
    titulo: 'Fratura de Smith instável fixada com placa volar',
    resumo: 'Fratura cominutiva da metáfise distal do rádio com desvio volar do fragmento distal e esporão cortical instável; controle após placa volar com comprimento, inclinação e inclinação volar restaurados.',
    protocolo: 'Radiografias de punho em perfil, perfil pós-operatório e frontal pós-operatório',
    series: ['Perfil inicial', 'Perfil pós-operatório', 'Frontal pós-operatório'],
    rotulos: {
      'dominant distal fragment': r('Fragmento distal desviado para a frente', 'O fragmento distal do rádio deslocado no sentido volar.',
        'A fratura de Smith é o contrário da de Colles: o fragmento distal do rádio vai para a frente, em direção à palma. Por isso é chamada de Colles invertida. Ela ocorre em quedas sobre o punho dobrado ou com golpe no dorso da mão. O desvio volar é instável porque os músculos flexores puxam o fragmento.',
        'No perfil, compare a superfície articular do rádio: normal é inclinada cerca de 11 graus para a palma.'),
      'cortical strut': r('Esporão cortical volar', 'Fragmento da cortical anterior girado quase 90 graus.',
        'Um fragmento da cortical anterior girado e solto impede que a fratura fique estável depois da redução fechada. Ele é sinal de instabilidade e explica por que a manipulação não manteve o alinhamento. Nesses casos, a fixação interna com placa é o tratamento.'),
      'volar plate and screw fixation': r('Placa volar com parafusos', 'Placa na face anterior do rádio, fixando os fragmentos.',
        'A placa volar é colocada na face anterior do rádio e funciona como um apoio que impede o fragmento de escorregar para a frente. Os parafusos distais seguram a superfície articular. Ela permite mexer o punho cedo e é o tratamento padrão das fraturas de Smith instáveis.'),
      'Neutral tilt': r('Inclinação volar neutra', 'Superfície articular sem inclinação dorsal residual.',
        'Depois da cirurgia, a superfície articular deve ter inclinação neutra ou volar. Inclinação dorsal residual sobrecarrega o carpo e limita a flexão do punho. A radiografia de controle confere esses parâmetros.'),
      'Anatomic radial length and inc': r('Comprimento e inclinação radial restaurados', 'No frontal, rádio com comprimento e inclinação normais.',
        'No frontal, o rádio deve ficar cerca de 11 mm mais longo que a ulna e com inclinação de cerca de 22 graus. Encurtamento do rádio desloca a carga para a ulna e causa dor no lado ulnar do punho. Restaurar esses valores melhora a função final.'),
    },
    achados: [
      'Fratura cominutiva da metáfise distal do rádio com translação volar do fragmento distal e leve inclinação volar — fratura de Smith.',
      'Fragmento cortical volar girado quase 90 graus, instável após tentativa de redução fechada.',
      'Pós-operatório com placa volar e parafusos, traços em consolidação, comprimento e inclinação radial anatômicos e inclinação articular neutra.',
    ],
    armadilhas: [
      'Não confunda com Barton volar: na Smith o traço não entra na articulação pela borda volar.',
      'Verifique o escafoide: fraturas associadas mudam o tratamento.',
      'Parafusos longos podem irritar os tendões extensores no dorso.',
    ],
    conduta: 'Fixação interna com placa volar nas fraturas instáveis, mobilização precoce dos dedos e do punho, fisioterapia e avaliação de osteoporose em pacientes mais velhos.',
    vinheta: {
      cenario: 'Pronto-socorro de ortopedia',
      identificacao: 'Homem de 34 anos, ciclista de estrada.',
      queixa: 'Dor e deformidade no punho direito depois de queda da bicicleta.',
      historia: 'Caiu da bicicleta em velocidade e o punho direito bateu dobrado para dentro contra o asfalto. O punho ficou com um degrau para a frente. Uma tentativa de redução no pronto-socorro não segurou: o desvio voltou no gesso.',
      antecedentes: [
        'Pessoais: sem fraturas anteriores',
        'Pessoais: sem doenças',
        'Familiares: sem osteoporose conhecida',
        'Hábitos: pedala 300 km por semana',
      ],
      vitais: { pa: '126 × 78 mmHg', fc: '88 bpm', fr: '16 irpm', satO2: '99% em ar ambiente', temp: '36,5 °C' },
      exame: [
        'Deformidade em pá de jardineiro, com o punho desviado para a palma',
        'Edema e dor no rádio distal',
        'Sensibilidade do nervo mediano preservada',
        'Pulso radial presente',
      ],
      pedido: 'Queda sobre o punho fletido com deformidade volar que não se manteve reduzida: a pergunta é o tipo de fratura e por que é instável.',
      pergunta: 'Radiografias do punho. Qual é o achado que responde à pergunta clínica?',
      achado: 'Fratura de Smith instável',
      veredito: 'Fratura de Smith cominutiva com esporão cortical volar instável, tratada com placa volar',
      correlacao: 'O impacto com o punho dobrado para dentro empurrou o fragmento distal do rádio para a frente: é a fratura de Smith, com a deformidade em pá de jardineiro. O esporão cortical volar girado deixa a fratura sem apoio anterior, e os flexores puxam o fragmento, por isso a redução fechada não segurou e foi preciso operar.',
      distratores: [
        d('Fratura de Colles com desvio dorsal', 'Tem o fragmento distal deslocado para o dorso, com deformidade em dorso de garfo, após queda sobre a mão espalmada. Aqui o desvio é volar.'),
        d('Fratura de Barton volar intra-articular', 'Também desvia para a frente, mas o traço sai na borda volar da superfície articular, levando o carpo junto. Aqui o traço é metafisário.'),
        d('Luxação do semilunar', 'Desloca o semilunar para a frente, com o rádio íntegro e compressão do nervo mediano, sem fratura metafisária. Aqui o rádio está quebrado.'),
      ],
    },
  },

  'fratura-de-barton-volar': {
    tema: 'Fraturas e luxações',
    titulo: 'Fratura de Barton volar com subluxação radiocárpica',
    resumo: 'Fratura oblíqua da borda volar do rádio distal entrando na articulação, com o carpo subluxado para a frente junto com o fragmento.',
    protocolo: 'Radiografias de punho AP e perfil',
    rotulos: {
      'distal radius fracture': r('Fratura do rádio distal', 'No frontal, traço discreto com leve desvio do fragmento.',
        'No frontal, a fratura de Barton costuma ser sutil, porque o fragmento é a borda anterior do rádio e se sobrepõe ao resto do osso. Por isso o perfil é obrigatório em todo trauma de punho. Uma radiografia frontal quase normal não exclui fratura articular.'),
      'intra-articular extension': r('Extensão para a articulação', 'No perfil, traço oblíquo saindo na borda volar da superfície articular.',
        'A fratura de Barton é uma fratura-luxação: um fragmento da borda do rádio quebra e o carpo vai junto com ele. Na forma volar, a borda anterior quebra e o carpo escorrega para a frente. Como envolve a articulação e o carpo, é muito instável e quase sempre precisa de placa volar de apoio.',
        'Fratura que leva o carpo junto é fratura-luxação: gesso sozinho não segura.'),
    },
    apontamentosProprios: [
      p(1, 0.66, 0.44, 0, 'Carpo deslocado para a frente', 'O carpo acompanha o fragmento da borda volar e escorrega para a palma.',
        'O que define a fratura de Barton é o carpo sair do lugar junto com o fragmento do rádio. No perfil, o semilunar e o capitato deixam de se apoiar no centro da superfície do rádio e escorregam para a frente. Por isso a lesão é uma fratura-luxação, instável, que pede placa volar de apoio.'),
    ],
    achados: [
      'Fratura oblíqua da borda volar do rádio distal com extensão intra-articular, mais clara no perfil.',
      'Subluxação volar da articulação radiocárpica, com o carpo acompanhando o fragmento.',
      'Desvio volar discreto no frontal, sem degrau articular evidente nessa incidência.',
    ],
    armadilhas: [
      'O frontal pode parecer quase normal: sempre analise o perfil.',
      'A TC ajuda a medir o degrau articular e planejar a fixação.',
      'Procure lesão associada do escafoide e dos ligamentos do carpo.',
    ],
    conduta: 'Redução aberta e fixação com placa volar de apoio, mobilização precoce e fisioterapia.',
    vinheta: {
      cenario: 'Pronto-socorro de ortopedia',
      identificacao: 'Mulher de 41 anos, enfermeira.',
      queixa: 'Dor forte no punho esquerdo depois de escorregar no hospital.',
      historia: 'Escorregou no piso molhado e caiu com o punho esquerdo dobrado para a frente. Sentiu dor intensa e o punho inchou rápido. Não consegue dobrar nem esticar o punho.',
      antecedentes: [
        'Pessoais: sem fraturas anteriores',
        'Pessoais: hipotireoidismo tratado',
        'Familiares: mãe com osteoporose',
        'Hábitos: sedentária',
      ],
      vitais: { pa: '122 × 74 mmHg', fc: '86 bpm', fr: '16 irpm', satO2: '99% em ar ambiente', temp: '36,4 °C' },
      exame: [
        'Edema volar do punho esquerdo',
        'Dor à palpação da borda anterior do rádio',
        'Formigamento leve no polegar e no indicador',
        'Pulso radial presente',
      ],
      pedido: 'Queda com o punho fletido, edema volar e dor na borda anterior do rádio: a pergunta é se a fratura entra na articulação.',
      pergunta: 'Radiografias do punho. Qual é o achado que responde à pergunta clínica?',
      achado: 'Fratura de Barton volar',
      veredito: 'Fratura de Barton volar com subluxação radiocárpica',
      correlacao: 'A queda com o punho fletido empurrou o carpo contra a borda anterior do rádio, que se partiu e levou o carpo junto para a frente. O frontal engana, mas o perfil mostra o traço entrando na articulação. O edema volar comprime o nervo mediano e explica o formigamento no polegar e no indicador.',
      distratores: [
        d('Fratura de Smith extra-articular', 'Também desvia para a frente, mas o traço fica na metáfise sem entrar na articulação, e o carpo não sai do lugar em relação ao rádio.'),
        d('Fratura do escafoide', 'Dói na tabaqueira anatômica com o rádio íntegro e pode ter radiografia inicial normal, sem subluxação do carpo. O perfil aqui mostra o rádio quebrado.'),
        d('Fratura do estiloide radial', 'É a fratura de Chauffeur, com traço que sai na lateral do rádio, sem pegar a borda anterior nem deslocar o carpo para a frente.'),
      ],
    },
  },

  'fratura-de-rolando': {
    tema: 'Fraturas e luxações',
    titulo: 'Fratura de Rolando da base do primeiro metacarpo',
    resumo: 'Fratura cominutiva intra-articular da base do primeiro metacarpo com leve subluxação carpometacarpal.',
    protocolo: 'Radiografia da mão oblíqua',
    rotulos: {
      'comminuted fracture': r('Fratura cominutiva da base do primeiro metacarpo', 'Vários fragmentos na base do metacarpo do polegar, entrando na articulação.',
        'A base do primeiro metacarpo articula com o trapézio na articulação em sela, que permite a oposição do polegar. A fratura de Bennett tem dois fragmentos, um pequeno que fica preso pelo ligamento e o resto do metacarpo, que é puxado pelo abdutor longo do polegar. A fratura de Rolando é a versão cominutiva, com três ou mais fragmentos em forma de Y ou T, e tem pior prognóstico pela maior lesão da superfície articular.',
        'Fratura articular da base do polegar mal reduzida leva a artrose dolorosa e perda da pinça.'),
    },
    apontamentosProprios: [
      p(0, 0.47, 0.74, 45, 'Articulação trapeziometacarpal', 'Articulação entre o trapézio e a base do metacarpo, levemente subluxada.',
        'A articulação entre o trapézio e o primeiro metacarpo tem forma de sela e permite a oposição do polegar. Quando a base do metacarpo quebra em vários pedaços e perde o encaixe, a pinça perde força e a articulação evolui para artrose. Restaurar a congruência é o objetivo do tratamento.'),
    ],
    achados: [
      'Fratura cominutiva da base do primeiro metacarpo direito com extensão intra-articular.',
      'Leve subluxação da articulação carpometacarpal do polegar.',
      'Trapézio e demais ossos do carpo sem fratura.',
    ],
    armadilhas: [
      'Incidências específicas do polegar mostram melhor a superfície articular.',
      'Bennett e Rolando são articulares; fraturas extra-articulares da base têm melhor prognóstico.',
      'A TC ajuda a planejar a fixação dos fragmentos.',
    ],
    conduta: 'Redução e fixação com fios, parafusos ou placa, ou fixador externo quando a cominuição é grande, seguida de reabilitação da pinça.',
    vinheta: {
      cenario: 'Pronto-socorro de ortopedia',
      identificacao: 'Homem de 27 anos, lutador amador de boxe.',
      queixa: 'Dor e inchaço na base do polegar direito depois de um soco.',
      historia: 'Deu um soco com o polegar dobrado durante o treino e sentiu um estalo na base do polegar. Desde então o local está muito inchado e roxo e ele não consegue fazer pinça para segurar objetos.',
      antecedentes: [
        'Pessoais: fratura do quinto metacarpo há três anos',
        'Pessoais: sem doenças',
        'Familiares: sem doenças ósseas',
        'Hábitos: treina boxe cinco vezes por semana',
      ],
      vitais: { pa: '124 × 76 mmHg', fc: '78 bpm', fr: '14 irpm', satO2: '99% em ar ambiente', temp: '36,5 °C' },
      exame: [
        'Edema e equimose na eminência tenar',
        'Dor intensa à palpação da base do primeiro metacarpo',
        'Pinça entre polegar e indicador impossível',
        'Sensibilidade normal',
      ],
      pedido: 'Carga axial sobre o polegar fletido com dor na base e perda da pinça: a pergunta é o tipo de fratura.',
      pergunta: 'Radiografia da mão. Qual é o achado que responde à pergunta clínica?',
      achado: 'Fratura de Rolando',
      veredito: 'Fratura cominutiva intra-articular da base do primeiro metacarpo',
      correlacao: 'O soco com o polegar dobrado transmitiu a força pelo eixo do metacarpo até a base, que se partiu em vários fragmentos contra o trapézio. Por ser articular e cominutiva, a fratura de Rolando compromete a articulação em sela que permite a pinça e precisa de redução cuidadosa para evitar artrose.',
      distratores: [
        d('Fratura de Bennett do polegar', 'Também é articular na base do primeiro metacarpo, mas tem só dois fragmentos, com o pequeno fragmento volar preso pelo ligamento.'),
        d('Polegar do esquiador', 'É a lesão do ligamento colateral ulnar da articulação metacarpofalângica, mais distal, sem fratura da base do metacarpo. A pinça falha por instabilidade.'),
        d('Fratura do boxeador', 'Quebra o colo do quinto metacarpo ao socar com o punho fechado, e não a base do polegar. Ela atinge o colo do quinto metacarpo, longe da articulação do polegar.'),
      ],
    },
  },

  'fratura-da-cabeca-do-radio': {
    tema: 'Fraturas e luxações',
    titulo: 'Fratura desviada da cabeça do rádio',
    resumo: 'Fratura da cabeça do rádio com fragmento desviado e girado 90 graus, perda do contato com o capítulo, possível subluxação posterior do olécrano e edema lateral de partes moles.',
    protocolo: 'Radiografias de cotovelo AP e perfil',
    rotulos: {
      'displacement and rotation': r('Fragmento desviado e girado', 'Fragmento da cabeça do rádio girado 90 graus, fora do contato com o capítulo.',
        'A cabeça do rádio é a fratura mais comum do cotovelo no adulto. Ela ocorre em queda sobre a mão espalmada com o braço estendido, quando a cabeça bate contra o capítulo do úmero. Fragmentos pequenos sem desvio são tratados com movimento precoce. Fragmento girado e desviado bloqueia a rotação do antebraço e indica cirurgia.',
        'Peça ao paciente para girar o antebraço: bloqueio mecânico da rotação indica fixação ou prótese.'),
      'swelling of the soft tissue': r('Edema lateral de partes moles', 'Partes moles aumentadas no lado de fora do cotovelo.',
        'O edema no lado lateral do cotovelo marca o ponto de impacto e de lesão. Ele acompanha a fratura e, junto com dor no ligamento colateral medial, sugere uma lesão mais complexa que só a cabeça do rádio.'),
      'fracture of the radial head': r('Fratura da cabeça do rádio', 'Traço na cabeça do rádio no perfil.',
        'No perfil, a fratura pode ser sutil. O sinal do coxim gorduroso ajuda: o derrame articular empurra a gordura para fora da fossa do olécrano, e ela aparece como uma vela no lado posterior. Em adulto, coxim posterior visível após trauma significa fratura até prova em contrário, mais frequentemente da cabeça do rádio.'),
      'posterior subluxation': r('Possível subluxação posterior do olécrano', 'Leve incongruência da articulação entre a ulna e o úmero.',
        'Se a ulna também saiu do lugar, a lesão deixa de ser uma fratura isolada. A tríade terrível do cotovelo é luxação, fratura da cabeça do rádio e fratura do processo coronoide, uma lesão muito instável que exige cirurgia.'),
    },
    achados: [
      'Fratura da cabeça do rádio com fragmento desviado e girado 90 graus, sem contato com a superfície articular do capítulo.',
      'Leve incongruência da articulação umeroulnar, com possível subluxação posterior do olécrano.',
      'Edema acentuado de partes moles na face lateral do cotovelo.',
    ],
    armadilhas: [
      'Radiografia aparentemente normal com coxim gorduroso posterior: trate como fratura.',
      'Procure fratura do coronoide e lesão ligamentar: muda o tratamento.',
      'Dor no punho junto com fratura da cabeça do rádio sugere lesão de Essex-Lopresti.',
    ],
    conduta: 'TC do cotovelo, redução aberta e fixação ou prótese da cabeça do rádio para fragmento desviado com bloqueio, reparo ligamentar se instável e mobilização precoce.',
    vinheta: {
      cenario: 'Pronto-socorro de ortopedia',
      identificacao: 'Mulher de 38 anos, professora de dança.',
      queixa: 'Dor no cotovelo direito e incapacidade de girar o antebraço depois de uma queda.',
      historia: 'Caiu de costas durante uma apresentação e apoiou a mão direita espalmada com o braço esticado. Sentiu dor forte no cotovelo. Não consegue virar a palma para cima nem para baixo, e o cotovelo não estica totalmente.',
      antecedentes: [
        'Pessoais: sem fraturas anteriores',
        'Pessoais: sem doenças',
        'Familiares: sem doenças ósseas',
        'Hábitos: dança profissional',
      ],
      vitais: { pa: '118 × 74 mmHg', fc: '90 bpm', fr: '16 irpm', satO2: '99% em ar ambiente', temp: '36,5 °C' },
      exame: [
        'Edema e dor na face lateral do cotovelo',
        'Rotação do antebraço bloqueada',
        'Punho sem dor',
        'Sensibilidade e pulsos normais',
      ],
      pedido: 'Queda sobre a mão espalmada com dor lateral no cotovelo e bloqueio da rotação: a pergunta é a lesão óssea e se há instabilidade.',
      pergunta: 'Radiografias do cotovelo. Qual é o achado que responde à pergunta clínica?',
      achado: 'Fratura desviada da cabeça do rádio',
      veredito: 'Fratura desviada da cabeça do rádio com possível subluxação posterior do cotovelo',
      correlacao: 'A queda com o braço esticado empurrou a cabeça do rádio contra o capítulo, que a quebrou. O fragmento girou e ficou fora do lugar, travando a rotação do antebraço. A leve incongruência entre a ulna e o úmero sugere instabilidade e lesão ligamentar, o que pede TC e cirurgia.',
      distratores: [
        d('Fratura supracondiliana do úmero', 'É a fratura típica da criança, acima dos côndilos, com desvio posterior do fragmento distal e risco à artéria braquial. É rara no adulto.'),
        d('Fratura do olécrano por queda', 'Ocorre em queda sobre o cotovelo dobrado, com perda da extensão ativa, e não sobre a mão espalmada. A dor seria posterior e não lateral.'),
        d('Pronação dolorosa do cotovelo', 'É a subluxação da cabeça do rádio em crianças pequenas puxadas pela mão, com radiografia normal. A paciente é adulta e houve queda com o braço estendido.'),
      ],
    },
  },

  'luxacao-acromioclavicular': {
    tema: 'Fraturas e luxações',
    titulo: 'Fratura do coracoide com luxação acromioclavicular tipo III',
    resumo: 'Fratura desviada da base do processo coracoide, com a clavícula lateral subindo acima do acrômio, ruptura da articulação acromioclavicular e edema local.',
    protocolo: 'Radiografias do ombro AP e incidência de Zanca',
    series: ['Ombro AP', 'Acromioclavicular'],
    rotulos: {
      'Coracoid process fracture': r('Fratura do processo coracoide', 'Traço na base do coracoide, com desvio.',
        'Os ligamentos coracoclaviculares prendem a clavícula ao coracoide e são os que mais seguram a clavícula no lugar. Na luxação acromioclavicular, eles costumam romper. Às vezes, em vez de romperem, arrancam a base do coracoide, que se fratura. O resultado funcional é o mesmo: a clavícula fica solta.'),
      'Superiorly displaced clavicle': r('Clavícula elevada', 'Ponta lateral da clavícula acima da borda superior do acrômio.',
        'Na verdade, a clavícula não sobe: o braço e a escápula caem pelo peso, e a clavícula fica acima. A classificação de Rockwood gradua essa distância: no tipo III, o desvio é de 25 a 100% da largura da clavícula, com ruptura dos ligamentos acromioclaviculares e coracoclaviculares.',
        'Compare com o lado oposto: a distância coracoclavicular aumentada confirma o grau.'),
      'Disruption of AC joint': r('Ruptura da articulação acromioclavicular', 'Perda do alinhamento entre a clavícula e o acrômio.',
        'Normalmente a borda inferior da clavícula se alinha com a borda inferior do acrômio. Quando os ligamentos se rompem, esse alinhamento se perde e aparece o degrau visível e palpável no ombro, o sinal da tecla.'),
      'Soft tissue swelling': r('Edema de partes moles', 'Partes moles aumentadas sobre a articulação acromioclavicular.',
        'O edema sobre a articulação reflete o hematoma e a lesão dos ligamentos. Ele aparece mesmo nas lesões leves, tipo I e II, em que o alinhamento ainda está preservado. Ele também ajuda a localizar a lesão no exame físico.'),
      base: r('Base do coracoide', 'O traço da fratura na base do processo coracoide.',
        'A fratura na base do coracoide fica abaixo da inserção dos ligamentos coracoclaviculares. Por isso, o fragmento sobe junto com a clavícula. Fraturas da base com luxação acromioclavicular costumam ser tratadas com fixação cirúrgica.'),
    },
    achados: [
      'Fratura desviada da base do processo coracoide.',
      'Ruptura da articulação acromioclavicular com a clavícula lateral acima da borda superior do acrômio — tipo III.',
      'Articulação glenoumeral alinhada.',
      'Edema de partes moles sobre a articulação acromioclavicular.',
    ],
    armadilhas: [
      'Fratura do coracoide passa despercebida no AP: a incidência axilar ou a TC ajudam.',
      'Distância coracoclavicular normal com luxação sugere fratura do coracoide.',
      'Graus IV a VI desviam a clavícula para trás, para baixo ou muito para cima e precisam de cirurgia.',
    ],
    conduta: 'TC do ombro, fixação cirúrgica da fratura do coracoide e da articulação acromioclavicular em pacientes ativos, ou tratamento conservador com tipoia e reabilitação.',
    vinheta: {
      cenario: 'Pronto-socorro de ortopedia',
      identificacao: 'Homem de 29 anos, jogador de rúgbi.',
      queixa: 'Dor e um degrau no alto do ombro esquerdo depois de uma queda no jogo.',
      historia: 'Caiu diretamente sobre a ponta do ombro esquerdo durante uma disputa de bola. Sentiu dor intensa e notou um caroço no alto do ombro. Não consegue levantar o braço.',
      antecedentes: [
        'Pessoais: luxação do ombro direito há dois anos',
        'Pessoais: sem doenças',
        'Familiares: sem doenças ósseas',
        'Hábitos: joga rúgbi semanalmente',
      ],
      vitais: { pa: '128 × 78 mmHg', fc: '84 bpm', fr: '16 irpm', satO2: '99% em ar ambiente', temp: '36,4 °C' },
      exame: [
        'Proeminência da clavícula lateral esquerda',
        'Sinal da tecla positivo',
        'Dor à palpação do coracoide',
        'Pulsos e sensibilidade do braço normais',
      ],
      pedido: 'Queda sobre a ponta do ombro com degrau acromioclavicular e dor no coracoide: a pergunta é a lesão da articulação e se há fratura associada.',
      pergunta: 'Radiografias do ombro. Qual é o achado que responde à pergunta clínica?',
      achado: 'Luxação acromioclavicular tipo III',
      veredito: 'Luxação acromioclavicular tipo III com fratura da base do coracoide',
      correlacao: 'A queda sobre a ponta do ombro empurrou o acrômio para baixo. Os ligamentos acromioclaviculares romperam e, em vez de romper os coracoclaviculares, a força arrancou a base do coracoide. O braço caiu e a clavícula ficou proeminente, com o sinal da tecla.',
      distratores: [
        d('Fratura da clavícula no terço médio', 'É a fratura mais comum da clavícula, com deformidade no meio do osso, e não na articulação com o acrômio. O coracoide fica íntegro.'),
        d('Luxação anterior glenoumeral', 'Tira a cabeça do úmero da glenoide, com ombro em dragona e acrômio proeminente, e não a clavícula do acrômio. A glenoumeral está alinhada.'),
        d('Luxação acromioclavicular tipo I', 'É só um estiramento dos ligamentos, com dor local e radiografia alinhada, sem degrau nem fratura do coracoide. Aqui o desvio é grande.'),
      ],
    },
  },
}
