import { d, r, type ConteudoCaso } from './casos-imagem-tipos'

/** Segunda leva de TC — abdome, parte 5 (perfuração, hérnia, fígado, rim, adrenal, períneo). Pacientes fictícios. */
export const CASOS_TC_L2_ABDOME_5: Record<string, ConteudoCaso> = {
  'ulcera-peptica-perfurada': {
    tema: 'Obstrução e perfuração',
    titulo: 'Úlcera péptica perfurada do antro gástrico',
    resumo: 'Gás livre peri-hepático, perigástrico e periportal com defeito focal na parede do antro, edema parietal, densificação da gordura e pouco líquido livre.',
    protocolo: 'TC de abdome com contraste, fases arterial e portal',
    series: ['Fase arterial', 'Fase portal'],
    rotulos: {
      perihepatic: r('Gás livre peri-hepático', 'Bolhas de ar entre o fígado e a parede abdominal.',
        'Ar fora das alças é pneumoperitônio, e em paciente sem cirurgia recente significa perfuração de víscera oca até prova em contrário. Com o paciente deitado, o ar sobe para a frente do fígado, que é o ponto mais alto do abdome. A janela de pulmão facilita ver pequenas bolhas.',
        'Na radiografia, peça tórax em pé: ar sob a cúpula diafragmática aparece com volumes pequenos.'),
      'minimal free fluid': r('Pouco líquido livre', 'Lâmina de líquido em volta do estômago.',
        'O conteúdo gástrico que vaza e a reação peritoneal formam líquido junto à perfuração. Pouco líquido indica perfuração recente ou tamponada; muito líquido sugere peritonite estabelecida. Ele também ajuda a localizar a perfuração.'),
      'perigastric fat stranding.': r('Densificação da gordura perigástrica', 'Gordura borrada em volta do antro.',
        'A inflamação em volta da úlcera e o suco gástrico que extravasou irritam a gordura vizinha. Densificação localizada aponta o local da perfuração quando o defeito na parede é pequeno. Ela não aparece em úlcera sem perfuração.'),
      perforation: r('Defeito na parede gástrica', 'Interrupção focal da parede do antro distal.',
        'A úlcera péptica aprofunda até atravessar toda a parede e abre o estômago para o peritônio. Ver o defeito confirma a origem gástrica do ar. As úlceras perfuradas costumam ficar na parede anterior do antro ou do bulbo duodenal, porque a parede posterior está protegida pelo pâncreas.',
        'Úlcera gástrica perfurada deve ser biopsiada: parte delas é câncer.'),
      periportal: r('Gás periportal', 'Bolhas de ar junto ao hilo hepático.',
        'Gás livre que migra para o ligamento hepatoduodenal, perto da veia porta, é típico de perfuração do estômago ou do duodeno. Não confundir com gás dentro da veia porta, que fica na periferia do fígado e indica isquemia intestinal.'),
      'hepatic cysts': r('Cistos hepáticos simples', 'Pequenos cistos de água no fígado, incidentais.',
        'Cistos simples têm densidade de água, paredes imperceptíveis e não realçam. São comuns, benignos e não precisam de seguimento. Aqui são incidentais e não têm relação com a dor. Relatar e não valorizar é o comportamento correto, para não desviar o foco da urgência cirúrgica.'),
      'mural oedema': r('Edema da parede gástrica', 'Parede do antro espessada e menos densa.',
        'A úlcera é cercada por inflamação que deixa a parede espessa e edemaciada. Espessamento muito grande, assimétrico e com linfonodos levantaria suspeita de tumor. Por isso a biópsia é obrigatória depois da fase aguda.'),
      perigastric: r('Gás perigástrico', 'Ar livre colado ao estômago.',
        'O ar concentrado em volta do antro, mais que em outros pontos, ajuda a localizar a perfuração. Gás livre no retroperitônio apontaria para o duodeno retroperitoneal ou o cólon. A distribuição do ar orienta o cirurgião.'),
    },
    achados: [
      'Gás livre perigástrico, peri-hepático e periportal.',
      'Defeito focal na parede do antro distal com edema parietal, densificação da gordura perigástrica e pouco líquido em volta — perfuração.',
      'Sonda nasogástrica com a ponta no duodeno.',
      'Pequenos cistos hepáticos simples.',
    ],
    armadilhas: [
      'Ausência de ar livre não exclui perfuração tamponada.',
      'Corticoide e analgesia mascaram a peritonite em idosos.',
      'Gás na veia porta e gás livre periportal têm significados diferentes.',
    ],
    conduta: 'Jejum, sonda nasogástrica, inibidor de bomba de prótons venoso, antibiótico e cirurgia com rafia e epiploplastia, com pesquisa e tratamento de Helicobacter pylori.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Homem de 52 anos, motorista de ônibus.',
      queixa: 'Dor súbita e muito forte na parte alta da barriga há quatro horas.',
      historia: 'Há quatro horas sentiu uma dor em facada no epigástrio, de início súbito, que se espalhou para toda a barriga e piora ao respirar e ao se mexer. Há meses tem queimação no estômago que melhora ao comer. Tomou anti-inflamatório toda a semana por dor nas costas.',
      antecedentes: [
        'Pessoais: dispepsia não investigada',
        'Pessoais: lombalgia em uso de diclofenaco',
        'Familiares: pai com úlcera operada',
        'Hábitos: tabagista e etilista social',
      ],
      vitais: { pa: '104 × 64 mmHg', fc: '116 bpm', fr: '24 irpm', satO2: '96% em ar ambiente', temp: '37,8 °C' },
      exame: [
        'Abdome em tábua, sem movimentos respiratórios',
        'Descompressão brusca dolorosa difusa',
        'Perda da macicez hepática à percussão',
        'Leucocitose de 16.000',
      ],
      pedido: 'Dor epigástrica súbita com abdome em tábua em usuário de anti-inflamatório com dispepsia: a pergunta é se há perfuração e de onde.',
      pergunta: 'TC de abdome com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Perfuração de úlcera gástrica',
      veredito: 'Úlcera péptica perfurada no antro gástrico com pneumoperitônio',
      correlacao: 'O anti-inflamatório tira a proteção da mucosa, o tabagismo e provavelmente o Helicobacter completam o risco, e a queimação de meses era a úlcera. A perfuração derrama suco ácido no peritônio, o que dá a dor em facada e o abdome em tábua. O ar livre sobe para a frente do fígado, por isso some a macicez hepática.',
      distratores: [
        d('Pancreatite aguda edematosa', 'Também dói no epigástrio e irradia, mas com amilase alta, pâncreas aumentado e sem ar livre na cavidade. Ela não causa abdome em tábua de início súbito.'),
        d('Colecistite aguda calculosa', 'Dói no hipocôndrio direito após comida gordurosa, com vesícula espessada e cálculos, sem ar livre nem abdome em tábua. A dor é progressiva e não súbita.'),
        d('Infarto agudo de parede inferior', 'Pode se apresentar com dor epigástrica e vômitos, mas o abdome é flácido e o eletrocardiograma mostra o supradesnível. Sem ar livre.'),
      ],
    },
  },

  'hernia-femoral-encarcerada': {
    tema: 'Obstrução e perfuração',
    titulo: 'Hérnia femoral estrangulada com obstrução de delgado',
    resumo: 'Alça de delgado no canal femoral direito, medial à veia femoral comprimida, com espessamento parietal, estreitamento no colo e líquido no saco, e dilatação das alças a montante.',
    protocolo: 'TC de abdome e pelve com contraste, fase portal, axial e coronal',
    series: ['Axial', 'Coronal'],
    rotulos: {
      'Mild free intraperitoneal flui': r('Líquido livre intraperitoneal', 'Pouco líquido livre entre as alças.',
        'Líquido livre na obstrução intestinal pode ser apenas transudato pela congestão das alças, mas aumenta quando há sofrimento isquêmico. Junto com os outros sinais, reforça a suspeita de estrangulamento.'),
      'renal cystic lesion': r('Cisto renal complexo', 'Pequeno cisto renal direito com nódulo na parede.',
        'Cisto com nódulo mural que pode realçar não é cisto simples: entra na classificação de Bosniak como lesão que pode ser carcinoma. É incidental aqui, mas precisa de ressonância ou seguimento depois da urgência.'),
      'surrounding fat stranding.': r('Densificação em volta do saco', 'Gordura borrada em torno da hérnia.',
        'Edema e inflamação em volta do saco herniário indicam que o conteúdo está sofrendo. Na hérnia apenas redutível, a gordura em volta é limpa. Ela é um dos sinais mais úteis para indicar cirurgia de urgência.'),
      'hernia neck': r('Colo da hérnia', 'Abaixo dos vasos epigástricos e medial à veia femoral.',
        'A posição do colo define o tipo de hérnia. A femoral passa abaixo do ligamento inguinal, medial à veia femoral. A inguinal fica acima do ligamento; a direta é medial e a indireta lateral aos vasos epigástricos. O colo femoral é estreito e rígido, por isso a hérnia femoral encarcera e estrangula muito mais que a inguinal.',
        'Mulher idosa com obstrução de delgado sem cirurgia prévia: procure hérnia femoral.'),
      'common femoral vein': r('Veia femoral comum', 'A referência lateral do canal femoral.',
        'O canal femoral fica logo medial à veia femoral comum. Identificar a veia e ver o saco medial a ela é a forma mais confiável de diagnosticar hérnia femoral na TC. A artéria fica lateral a ela, e o ligamento inguinal acima.'),
      'compressed cfv': r('Veia femoral comprimida', 'O saco herniário achata a veia.',
        'A compressão da veia pela hérnia é sinal característico de hérnia femoral, porque o saco ocupa o canal ao lado da veia. A compressão pode inchar a perna e predispor a trombose. Esse achado não ocorre na hérnia inguinal.'),
      'right femoral hernia': r('Hérnia femoral direita', 'Alça de delgado dentro do saco no canal femoral.',
        'A alça presa no canal estreito é estrangulada pelo colo, primeiro na drenagem venosa e depois na chegada arterial. Sem cirurgia, ela necrosa e perfura. Por isso toda hérnia femoral deve ser operada, mesmo sem sintomas.'),
      'localized free fluid': r('Líquido dentro do saco', 'Líquido em volta da alça herniada.',
        'Líquido no saco herniário é sinal de congestão venosa da alça encarcerada e é um dos indicadores de estrangulamento. Ele aparece porque o sangue entra pela artéria, mas não consegue sair pela veia comprimida. Quanto mais líquido, maior a chance de a alça já estar sofrendo.'),
      'wall thickening,': r('Espessamento da alça herniada', 'Parede da alça presa espessada.',
        'A parede incha quando a drenagem venosa é bloqueada. Espessamento com realce reduzido ou ausente indica isquemia avançada e risco de necrose. Isso indica que a ressecção pode ser necessária.'),
      'narrowing at the neck of the h': r('Estreitamento no colo', 'A alça afunila onde passa pelo colo.',
        'O afunilamento mostra o ponto de transição da obstrução. Alças dilatadas antes e colabadas depois localizam o problema na hérnia. Ele mostra que o colo rígido é o que estrangula a alça e explica por que a redução manual é arriscada.'),
    },
    achados: [
      'Hérnia femoral direita contendo alça de delgado, com colo abaixo dos vasos epigástricos inferiores e medial à veia femoral comum, que está comprimida.',
      'Alça herniada com espessamento parietal, estreitamento no colo, líquido no saco e densificação da gordura — sinais de estrangulamento.',
      'Dilatação das alças de delgado a montante e alças distais colabadas — obstrução mecânica.',
      'Pouco líquido livre; cistos hepáticos e renais; pequeno cisto renal direito com nódulo mural indeterminado.',
    ],
    armadilhas: [
      'A hérnia femoral pequena pode não ser palpável em pacientes obesas.',
      'Hérnia femoral é confundida com inguinal no exame físico; a TC mostra a relação com a veia femoral.',
      'A redução manual de hérnia estrangulada pode devolver alça necrótica ao abdome.',
    ],
    conduta: 'Cirurgia de urgência com redução, avaliação da viabilidade da alça, ressecção se necrótica e correção do defeito; investigar o cisto renal complexo depois.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Mulher de 78 anos, aposentada.',
      queixa: 'Vômitos, barriga inchada e sem evacuar há dois dias.',
      historia: 'Há dois dias tem dor em cólica na barriga, vômitos que ficaram esverdeados e depois com cheiro de fezes, distensão e parada de gases e fezes. Há meses notava um caroço na virilha direita, que hoje está duro e dolorido. Nunca operou o abdome.',
      antecedentes: [
        'Pessoais: tosse crônica por DPOC',
        'Pessoais: constipação crônica',
        'Gestacionais: cinco partos normais',
        'Familiares: sem doenças relevantes',
      ],
      vitais: { pa: '102 × 60 mmHg', fc: '112 bpm', fr: '22 irpm', satO2: '93% em ar ambiente', temp: '37,9 °C' },
      exame: [
        'Abdome distendido e timpânico',
        'Ruídos hidroaéreos metálicos',
        'Abaulamento endurecido e doloroso abaixo do ligamento inguinal direito, irredutível',
        'Lactato de 3,4 mmol/L',
      ],
      pedido: 'Obstrução intestinal em idosa sem cirurgia prévia, com abaulamento doloroso na raiz da coxa: a pergunta é a causa e se há sofrimento da alça.',
      pergunta: 'TC de abdome e pelve. Qual é o achado que responde à pergunta clínica?',
      achado: 'Hérnia femoral estrangulada',
      veredito: 'Hérnia femoral direita estrangulada com obstrução de delgado',
      correlacao: 'Mulher idosa, multípara, com tosse crônica e constipação: tudo aumenta a pressão abdominal e alarga o canal femoral. A alça entrou no canal estreito e ficou presa, o que obstruiu o delgado — vômitos fecaloides e parada de eliminação. Febre, lactato alto e abaulamento duro e doloroso mostram estrangulamento, confirmado pelos sinais de isquemia na TC.',
      distratores: [
        d('Hérnia inguinal indireta encarcerada', 'Fica acima do ligamento inguinal e lateral aos vasos epigástricos, descendo para o canal inguinal, sem comprimir a veia femoral.'),
        d('Brida pós-operatória com obstrução', 'É a principal causa de obstrução de delgado, mas exige cirurgia abdominal prévia, que esta paciente nunca fez. Sem cirurgia prévia, procure hérnias.'),
        d('Linfonodo inguinal aumentado e doloroso', 'Forma um nódulo na virilha, mas é sólido, oval e sem alça intestinal nem obstrução associada. Costuma vir com uma lesão de pele no membro ou no períneo que explica a infecção.'),
      ],
    },
  },

  'cisto-hidatico-hepatico': {
    tema: 'Fígado e vias biliares',
    titulo: 'Hidatidose hepática com cistos-filhos',
    resumo: 'Dois grandes cistos multiloculados de paredes espessas nos lobos direito e esquerdo com cistos-filhos, calcificação parietal e compressão das veias hepáticas e porta.',
    protocolo: 'TC de abdome com contraste, fase portal, coronal e axial',
    series: ['Coronal', 'Axial'],
    rotulos: {
      'hydatid cysts': r('Cistos hidáticos', 'Dois grandes cistos de paredes espessas, um em cada lobo.',
        'O Echinococcus granulosus vive no intestino do cão; o homem ingere os ovos em contato com cães ou água contaminada. A larva atravessa a parede intestinal, chega ao fígado pela veia porta e forma um cisto que cresce lentamente por anos. Por isso o paciente pode ficar sem sintomas até o cisto ficar enorme.',
        'Cão alimentado com vísceras de ovelha em área rural é a pista epidemiológica clássica.'),
      'multiple daughter cysts': r('Cistos-filhos', 'Cistos menores dentro do cisto-mãe — aspecto em favo.',
        'A membrana interna do cisto gera cistos-filhos que ficam dentro do cisto principal, como um favo ou uma roseta. Esse aspecto é patognomônico de hidatidose e corresponde ao tipo CE2 da classificação da OMS, um cisto ativo.'),
      'right hepatic vein': r('Veia hepática direita comprimida', 'Deslocada e parcialmente comprimida pelo cisto.',
        'Cistos grandes comprimem as veias que drenam o fígado. Compressão importante pode causar síndrome de Budd-Chiari, com ascite e fígado aumentado. Esse dado é essencial para planejar a cirurgia.'),
      'middle hepatic vein': r('Veia hepática média comprimida', 'Também deslocada pelo cisto.',
        'A relação dos cistos com as veias hepáticas define quais segmentos podem ser ressecados com segurança e se a cirurgia conservadora é preferível. Ela drena os segmentos centrais do fígado.'),
      'Hydatid cyst in lesser sac': r('Cisto projetado na bolsa omental', 'Componente exofítico entrando na bolsa omental.',
        'O cisto do lobo esquerdo cresce para fora do fígado e entra na bolsa omental, atrás do estômago. Cistos exofíticos têm maior risco de romper para o peritônio, o que pode causar anafilaxia e disseminação de cistos.'),
      'lesser curvature': r('Pequena curvatura gástrica', 'O estômago empurrado pelo cisto.',
        'O efeito de massa sobre o estômago explica a saciedade precoce e o desconforto pós-prandial que muitos desses pacientes relatam. Ela também mostra o risco de ruptura para a bolsa omental e orienta a via de acesso cirúrgico.'),
      'main portal vein': r('Veia porta principal deslocada', 'Empurrada para trás e parcialmente comprimida.',
        'A compressão da porta pode causar hipertensão portal. Saber a posição da porta é obrigatório antes de qualquer cirurgia ou punção. Lesar a porta é a complicação mais grave da cirurgia desses cistos.'),
    },
    achados: [
      'Dois grandes cistos multiloculados de paredes espessas, de cerca de 10 e 11 cm, no lobo direito, segmentos VII e VIII, e em todo o lobo esquerdo.',
      'Múltiplos cistos-filhos no interior; calcificação focal na parede anterior.',
      'Componente exofítico projetando-se para a bolsa omental com efeito de massa sobre a pequena curvatura gástrica e o pâncreas.',
      'Deslocamento e compressão parcial das veias hepáticas direita e média e da veia porta; hepatomegalia.',
    ],
    armadilhas: [
      'Puncionar cisto hidático sem preparo pode causar anafilaxia e disseminação.',
      'O cisto univesicular inicial imita cisto simples; procure a parede dupla.',
      'Comunicação com a via biliar causa colangite e icterícia.',
    ],
    conduta: 'Sorologia para equinococo, albendazol antes e depois do tratamento, e cirurgia ou drenagem percutânea com técnica PAIR conforme o estágio, a localização e a relação com vasos e vias biliares.',
    vinheta: {
      cenario: 'Ambulatório de cirurgia do aparelho digestivo',
      identificacao: 'Homem de 41 anos, criador de ovelhas no interior.',
      queixa: 'Peso e aumento do volume na parte alta da barriga há um ano.',
      historia: 'Há um ano sente o lado direito e o meio da barriga mais pesados e nota que ela cresceu. Fica cheio com pouca comida. Nega febre, icterícia e emagrecimento importante. Cria ovelhas e tem cães que comem vísceras dos animais abatidos.',
      antecedentes: [
        'Pessoais: sem doenças crônicas',
        'Pessoais: nunca operou',
        'Familiares: irmão operado de cisto no fígado',
        'Hábitos: bebe água de poço, contato diário com cães da fazenda',
      ],
      vitais: { pa: '124 × 78 mmHg', fc: '72 bpm', fr: '14 irpm', satO2: '98% em ar ambiente', temp: '36,6 °C' },
      exame: [
        'Hepatomegalia volumosa, lisa e indolor',
        'Abaulamento no epigástrio',
        'Sem icterícia nem ascite',
        'Eosinofilia leve',
      ],
      pedido: 'Hepatomegalia lentamente progressiva com eosinofilia em criador de ovelhas que alimenta cães com vísceras: a pergunta é a natureza das lesões hepáticas.',
      pergunta: 'TC de abdome com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Cistos hidáticos hepáticos',
      veredito: 'Hidatidose hepática com cistos multiloculados e cistos-filhos',
      correlacao: 'O ciclo do Echinococcus passa do cão que come vísceras de ovelha para o homem que ingere os ovos — o criador e o irmão vivem no mesmo ambiente. Os cistos crescem devagar por anos, por isso a hepatomegalia é lenta e sem febre. A eosinofilia reflete o parasita, e os cistos-filhos no interior são patognomônicos.',
      distratores: [
        d('Abscesso hepático piogênico multiloculado', 'Pode ter septos, mas surge em dias com febre alta e calafrios, sem cistos-filhos nem crescimento lento por um ano. Responde a drenagem e antibiótico.'),
        d('Cistoadenoma biliar mucinoso hepático', 'É cisto septado do fígado, mas em mulheres de meia-idade, com septos finos e sem cistos-filhos nem exposição a cães e ovelhas.'),
        d('Doença hepática policística isolada', 'Forma muitos cistos simples espalhados de paredes finas, sem cistos-filhos dentro de grandes cistos de parede espessa. Os cistos não têm membranas soltas nem calcificação parietal.'),
      ],
    },
  },

  'sindrome-de-wunderlich': {
    tema: 'Rim e adrenal',
    titulo: 'Síndrome de Wunderlich por angiomiolipoma roto',
    resumo: 'Grande lesão renal direita com gordura e sangue no interior, contínua com hematoma perirrenal e retroperitoneal; achados incidentais de cálculo renal e colelitíase.',
    protocolo: 'TC de abdome sem contraste e fase arterial',
    series: ['Fase arterial', 'Sem contraste'],
    rotulos: {
      'retroperitoneal haemorrhage': r('Hemorragia retroperitoneal', 'Sangue espalhado no retroperitônio direito.',
        'A síndrome de Wunderlich é o sangramento renal espontâneo, sem trauma, para o espaço perirrenal e o retroperitônio. A tríade de Lenk é dor lombar súbita, massa no flanco e choque. O sangue fica contido pelas fáscias renais, mas a perda pode ser grande.',
        'Hematoma perirrenal espontâneo: procure angiomiolipoma, carcinoma renal e vasculite.'),
      'perirenal haematoma': r('Hematoma perirrenal', 'Coleção de sangue de 8 cm em volta do rim direito.',
        'O hematoma perirrenal fica dentro da fáscia de Gerota. Medir o tamanho e procurar extravasamento ativo de contraste na fase arterial define se é preciso embolizar com urgência. Ele também pode empurrar e comprimir o rim.'),
      'renal fat-containing lesion': r('Angiomiolipoma com sangue', 'Lesão renal de 7 cm com gordura e sangue.',
        'Gordura macroscópica dentro de uma lesão renal identifica o angiomiolipoma. Os vasos do tumor têm paredes anormais e formam aneurismas que se rompem. O risco aumenta acima de 4 cm, na gravidez e na esclerose tuberosa.'),
      stone: r('Cálculo renal esquerdo', 'Cálculo no polo inferior do rim esquerdo, incidental.',
        'Na TC sem contraste, os cálculos aparecem muito densos. Este não está obstruindo e não explica o quadro, mas entra no laudo. Deve ser descrito, mas sem desviar o foco da emergência. Ele não muda a conduta agora.'),
      'gallbladder stones': r('Cálculos na vesícula', 'Dois cálculos densos na vesícula, incidentais.',
        'Colelitíase incidental é comum e só precisa de tratamento se causar sintomas. Achados incidentais devem ser relatados sem desviar o foco da urgência. Aqui não causam sintomas. Devem ser relatados para seguimento ambulatorial.'),
    },
    achados: [
      'Lesão renal direita de 7 × 5,5 × 7,7 cm com gordura macroscópica e componente com densidade de sangue — angiomiolipoma roto.',
      'Hematoma perirrenal direito de 7,9 cm contínuo com hemorragia retroperitoneal.',
      'Cálculo no polo inferior e cisto no polo superior do rim esquerdo.',
      'Dois cálculos densos na vesícula.',
    ],
    armadilhas: [
      'Hematoma volumoso pode esconder a gordura do tumor; repita a imagem depois da reabsorção.',
      'Na ausência de gordura, carcinoma renal é a principal causa de Wunderlich.',
      'Extravasamento ativo na fase arterial indica embolização imediata.',
    ],
    conduta: 'Reposição volêmica, angiotomografia ou arteriografia com embolização seletiva do angiomiolipoma e, se instável sem acesso a embolização, nefrectomia; investigar esclerose tuberosa.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Mulher de 36 anos, enfermeira.',
      queixa: 'Dor súbita e muito forte no lado direito das costas, com tontura.',
      historia: 'Há três horas, sem trauma, sentiu dor lancinante no flanco direito, que irradia para a barriga. Ficou pálida e quase desmaiou ao levantar. Nega febre e ardência ao urinar. Fez ultrassom há três anos que mostrou um nódulo no rim, sem seguimento.',
      antecedentes: [
        'Pessoais: nódulo renal direito visto em ultrassom há três anos',
        'Gestacionais: dois partos, último há quatro anos',
        'Familiares: sem doenças renais conhecidas',
        'Hábitos: não fuma, sem uso de anticoagulantes',
      ],
      vitais: { pa: '88 × 54 mmHg', fc: '124 bpm', fr: '22 irpm', satO2: '98% em ar ambiente', temp: '36,7 °C' },
      exame: [
        'Massa dolorosa no flanco direito',
        'Palidez e sudorese',
        'Hemoglobina de 8,1 g/dL, era 13 há um mês',
        'Urina com hematúria microscópica',
      ],
      pedido: 'Dor lombar súbita com massa no flanco e choque em jovem com nódulo renal não seguido: a pergunta é a origem do sangramento.',
      pergunta: 'TC de abdome sem contraste e em fase arterial. Qual é o achado que responde à pergunta clínica?',
      achado: 'Angiomiolipoma renal roto',
      veredito: 'Síndrome de Wunderlich por ruptura de angiomiolipoma renal direito',
      correlacao: 'A dor súbita no flanco, a massa palpável e o choque formam a tríade de Lenk. O nódulo visto há três anos cresceu e seus vasos frágeis se romperam, sangrando para dentro da fáscia de Gerota. A gordura dentro da lesão na TC identifica o angiomiolipoma como causa.',
      distratores: [
        d('Cólica renal por cálculo obstrutivo', 'Dói muito no flanco, mas não derruba a hemoglobina nem causa choque, e mostra cálculo com dilatação a montante. Sem choque. Nem massa.'),
        d('Carcinoma de células claras roto', 'Também causa Wunderlich e é a principal causa sem gordura, mas a lesão não teria gordura macroscópica. Por isso, sem gordura, o carcinoma deve ser procurado após o sangramento.'),
        d('Ruptura de aneurisma da aorta abdominal', 'Causa dor lombar e choque com hematoma retroperitoneal, mas em idoso, com aorta dilatada e sem lesão renal com gordura. A aorta aqui é normal.'),
      ],
    },
  },

  'hematoma-adrenal-traumatico': {
    tema: 'Rim e adrenal',
    titulo: 'Hematoma adrenal direito traumático',
    resumo: 'Expansão ovoide da adrenal direita com densidade de partes moles, densificação da gordura perirrenal, pouco sangue e espessamento da fáscia, com fraturas das costelas 8 e 9.',
    protocolo: 'TC de abdome com contraste, fases portal e arterial',
    series: ['Fase portal', 'Fase arterial'],
    rotulos: {
      'right adrenal': r('Adrenal direita aumentada', 'Glândula com expansão ovoide e densidade de sangue.',
        'A adrenal normal tem forma de Y ou de V invertido, com braços finos. No trauma, ela se transforma numa massa oval porque sangrou dentro dela. A direita é mais lesada, porque fica presa entre o fígado e a coluna e drena direto na veia cava, que transmite o pico de pressão do impacto.',
        'Hematoma adrenal no trauma costuma vir com lesões vizinhas: fígado, rim direito e costelas baixas.'),
      'fat stranding': r('Densificação da gordura', 'Gordura borrada junto à adrenal e às costelas fraturadas.',
        'Densificação da gordura mostra sangue e edema em volta da lesão. Em volta da adrenal, é o sinal mais sensível de hematoma; junto aos músculos intercostais, acompanha as fraturas. Ela também ajuda a separar hematoma de adenoma.'),
      haemorrhage: r('Sangue no espaço perirrenal', 'Pequena quantidade de líquido denso entre a fáscia e o fígado.',
        'Sangue recente mede de 40 a 70 UH, mais que água. Pouca quantidade em volta da adrenal confirma que o sangramento saiu da glândula. Grande volume de sangue indica lesão de outro órgão, como o rim, e precisa ser procurado com cuidado.'),
      'thickened perirenal fascia': r('Fáscia perirrenal espessada', 'A fáscia lateral direita mais grossa.',
        'O sangue e o edema que se espalham no espaço perirrenal espessam a fáscia. É um sinal indireto de lesão dentro desse compartimento. Ela reforça que a origem é a adrenal e não o fígado, porque fica dentro do compartimento perirrenal.'),
      'fractured 8th rib': r('Fratura da 8ª costela', 'Fratura da costela 8 direita.',
        'Fraturas das costelas baixas direitas indicam energia sobre o fígado, o rim e a adrenal. Sempre que estão presentes, as vísceras do andar superior devem ser examinadas com cuidado. É o mecanismo.'),
      'fracture 9th rib': r('Fratura da 9ª costela', 'Fratura da costela 9 direita.',
        'Duas costelas fraturadas aumentam a dor e o risco de pneumonia por respiração superficial. A analgesia adequada faz parte do tratamento. Três ou mais costelas fraturadas aumentariam ainda mais esse risco, sobretudo em idosos.'),
    },
    achados: [
      'Expansão ovoide da adrenal direita com densidade de partes moles e densificação da gordura em volta, estendendo-se ao espaço perirrenal superior.',
      'Pequena quantidade de líquido de alta densidade entre a fáscia perirrenal e a área nua do fígado; espessamento da fáscia perirrenal lateral direita.',
      'Fraturas das costelas 8 e 9 direitas com densificação junto aos intercostais; atelectasia na base direita.',
      'Fígado e rim direito sem lesão.',
    ],
    armadilhas: [
      'Hematoma adrenal pode ser confundido com nódulo; controle por imagem confirma a resolução.',
      'Hematoma adrenal bilateral pode levar à insuficiência adrenal aguda.',
      'Hemorragia adrenal sem trauma sugere sepse, anticoagulação ou tumor subjacente.',
    ],
    conduta: 'Tratamento conservador com observação, controle de hemoglobina, analgesia para as fraturas, vigilância de insuficiência adrenal se houver lesão bilateral e TC de controle para confirmar resolução.',
    vinheta: {
      cenario: 'Sala de trauma',
      identificacao: 'Homem de 34 anos, motoboy.',
      queixa: 'Dor no lado direito do tórax e das costas após queda de moto.',
      historia: 'Caiu de moto a 60 km/h e bateu o lado direito do tórax no meio-fio. Chegou consciente, com dor forte no lado direito, que piora ao respirar. Nega perda de consciência. Estava de capacete.',
      antecedentes: [
        'Pessoais: sem doenças crônicas',
        'Pessoais: sem uso de anticoagulantes',
        'Familiares: sem doenças relevantes',
        'Hábitos: etilista social, não fuma',
      ],
      vitais: { pa: '128 × 80 mmHg', fc: '98 bpm', fr: '22 irpm', satO2: '95% em ar ambiente', temp: '36,5 °C' },
      exame: [
        'Dor à palpação dos arcos costais 8 e 9 à direita',
        'Escoriações no flanco direito',
        'Murmúrio vesicular reduzido na base direita',
        'Hemoglobina estável e urina sem sangue',
      ],
      pedido: 'Trauma fechado no flanco direito com dor costal, estável: a pergunta é se há lesão de órgão sólido do andar superior.',
      pergunta: 'TC de abdome com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Hematoma adrenal direito',
      veredito: 'Hematoma adrenal direito traumático com fraturas das costelas 8 e 9',
      correlacao: 'O impacto no flanco direito fraturou as costelas baixas e comprimiu a adrenal entre o fígado e a coluna. A glândula sangrou para dentro e ficou oval. O fígado e o rim estão íntegros, a urina sem sangue confirma o rim, e o paciente estável permite tratamento conservador.',
      distratores: [
        d('Laceração hepática do segmento posterior', 'É a lesão mais esperada nesse impacto, mas a TC mostraria linha hipodensa no fígado, que aqui está íntegro. Também haveria sangue em volta do fígado.'),
        d('Lesão renal direita com hematoma', 'Daria sangue em volta do rim, com laceração no parênquima e hematúria, mas o rim está íntegro e a urina limpa. A fáscia estaria muito mais distendida.'),
        d('Adenoma adrenal incidental antigo', 'É nódulo bem definido de baixa densidade pela gordura, sem densificação em volta nem sangue após trauma. Não haveria trauma. Nem dor.'),
      ],
    },
  },

  'gangrena-de-fournier': {
    tema: 'Pelve',
    titulo: 'Gangrena de Fournier de origem retal',
    resumo: 'Abscesso perirretal com nível hidroaéreo e defeito na parede retal, com gás dissecando o subcutâneo do períneo, glúteos, escroto e parede abdominal esquerda.',
    protocolo: 'TC de abdome e pelve com contraste, fase portal, axial e coronal',
    series: ['Axial', 'Coronal'],
    rotulos: {
      'air-fluid mirror': r('Nível hidroaéreo', 'Ar sobre líquido dentro da coleção perirretal.',
        'O nível hidroaéreo dentro de uma coleção indica pus com gás produzido por bactérias ou ar vindo de uma víscera. Aqui o ar vem do reto perfurado e das bactérias anaeróbias. Ele confirma infecção grave.'),
      'Large abscess-suspicious circu': r('Abscesso perirretal circunferencial', 'Coleção de 9,6 cm envolvendo o reto.',
        'O abscesso perirretal é o ponto de partida mais comum da gangrena de Fournier. A infecção se espalha pelos planos das fáscias do períneo, que se comunicam com o escroto e a parede abdominal.'),
      rectum: r('Reto', 'O reto no centro da coleção.',
        'Identificar o reto no meio do abscesso mostra a origem anorretal. Ela muda o tratamento, porque pode ser preciso desviar as fezes com colostomia. Ela também orienta a necessidade de exame proctológico e de biópsia se houver suspeita de tumor.'),
      'defect in the rectal wall': r('Defeito na parede retal', 'Comunicação entre a luz do reto e o abscesso.',
        'A perfuração do reto alimenta a infecção com fezes e bactérias continuamente. Esse dado indica colostomia derivativa para controlar o foco. Sem desviar as fezes, a ferida perineal não cicatriza e a infecção se renova.'),
      'subcutaneous and intramuscular': r('Gás subcutâneo e intramuscular', 'Ar dissecando o subcutâneo e os músculos do períneo.',
        'A gangrena de Fournier é uma fasciite necrotizante do períneo: bactérias aeróbias e anaeróbias produzem gás e trombosam os pequenos vasos, o que necrosa a fáscia. O gás nos tecidos é o achado mais característico. A TC mostra a extensão real, que é muito maior do que a pele sugere.',
        'Crepitação à palpação do períneo ou do escroto é Fournier até prova em contrário.'),
      'air bubbles dissect ventrally': r('Gás dissecando para a frente', 'Bolhas avançando do períneo em direção anterior.',
        'As fáscias do períneo continuam com as do escroto, do pênis e da parede abdominal. O gás segue esses planos e mostra para onde a necrose está avançando. Seguir o gás em todos os cortes mostra a extensão real da necrose.'),
      'left abdominal wall/flank': r('Gás na parede abdominal esquerda', 'Ar subcutâneo subindo até o flanco esquerdo.',
        'A extensão até a parede abdominal define até onde o desbridamento precisa ir. Infecção que sobe para a parede aumenta a mortalidade. Ela também mostra que o desbridamento terá de incluir a parede abdominal.'),
      'left scrotum': r('Gás no escroto esquerdo', 'Ar no escroto, a área clássica do Fournier.',
        'O escroto tem pele fina e fáscias que se comunicam com o períneo, por isso é acometido cedo. Os testículos costumam ser poupados porque têm irrigação própria, vinda do abdome. Por isso a orquiectomia raramente é necessária.'),
      'the left inguinal region': r('Gás na região inguinal esquerda', 'Ar subindo pelo canal inguinal esquerdo.',
        'A região inguinal é a passagem do gás do escroto para a parede abdominal, ao longo do cordão espermático. Ela é o caminho pelo qual a infecção sai da pelve e chega à parede abdominal. Por isso o cirurgião precisa abrir também esse trajeto.'),
      'rectum is wall thickened': r('Parede retal espessada', 'Reto com parede espessa e realce.',
        'O espessamento e o realce da parede retal mostram inflamação acompanhando a perfuração. Câncer retal perfurado também pode causar Fournier e deve ser excluído. Por isso o reto precisa ser examinado depois.'),
      'gluteal regions': r('Gás nas regiões glúteas', 'Ar dissecando os dois glúteos, mais à esquerda.',
        'A extensão para os glúteos amplia a área de desbridamento e o risco de choque séptico. A TC mapeia tudo que o cirurgião precisa abrir. Ela também prolonga a internação. Também exige curativos extensos.'),
    },
    achados: [
      'Abscesso circunferencial em volta do reto de 9,6 × 8,6 × 6,7 cm com nível hidroaéreo.',
      'Reto com parede espessada e realce, com suspeita de defeito parietal comunicando a luz com o abscesso.',
      'Gás subcutâneo e intramuscular extenso no períneo, nas regiões glúteas, mais à esquerda, no escroto esquerdo, na região inguinal e na parede abdominal e flanco esquerdos — fasciite necrotizante.',
    ],
    armadilhas: [
      'A pele pode parecer pouco alterada enquanto a necrose profunda avança.',
      'Não adie a cirurgia para fazer imagem em paciente instável.',
      'Diabetes, etilismo e imunossupressão são os grandes fatores de risco.',
    ],
    conduta: 'Ressuscitação, antibiótico de amplo espectro imediato e desbridamento cirúrgico extenso de urgência, com novas revisões, colostomia derivativa pela perfuração retal e controle glicêmico.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Homem de 61 anos, comerciante.',
      queixa: 'Dor muito forte no ânus e no saco escrotal, febre e inchaço há três dias.',
      historia: 'Há uma semana teve dor perto do ânus que piorou. Há três dias o escroto inchou, ficou vermelho e com dor desproporcional ao que se vê. Hoje a pele do períneo escureceu e tem cheiro forte. Está confuso desde a manhã, segundo a esposa.',
      antecedentes: [
        'Pessoais: diabetes mal controlado, hemoglobina glicada de 11%',
        'Pessoais: obesidade',
        'Familiares: sem doenças relevantes',
        'Hábitos: etilista de destilados diariamente',
      ],
      vitais: { pa: '86 × 50 mmHg', fc: '128 bpm', fr: '26 irpm', satO2: '93% em ar ambiente', temp: '39,4 °C' },
      exame: [
        'Escroto e períneo edemaciados, com áreas escuras e bolhas',
        'Crepitação à palpação do períneo e do flanco esquerdo',
        'Leucocitose de 28.000 e glicemia de 420 mg/dL',
        'Lactato de 5,2 mmol/L',
      ],
      pedido: 'Infecção perineal com crepitação, dor desproporcional e choque em diabético: a pergunta é a extensão e a origem.',
      pergunta: 'TC de abdome e pelve com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Fasciite necrotizante perineal',
      veredito: 'Gangrena de Fournier de origem retal com extensão à parede abdominal',
      correlacao: 'Diabetes descontrolado e etilismo tiram a defesa. O abscesso perirretal, alimentado pelo reto perfurado, abriu caminho pelas fáscias do períneo. A mistura de bactérias produz gás e trombosa os vasos, por isso a crepitação, a pele escura e a dor desproporcional. O choque séptico exige cirurgia imediata, e a TC mostra até onde desbridar.',
      distratores: [
        d('Abscesso perianal simples localizado', 'Dói perto do ânus com febre, mas fica restrito a uma coleção, sem gás dissecando o escroto e a parede abdominal nem choque. Resolve com drenagem.'),
        d('Celulite escrotal sem necrose', 'Deixa o escroto vermelho e inchado, mas sem crepitação, sem gás nos tecidos e sem dor desproporcional. Responde a antibiótico sem cirurgia.'),
        d('Hérnia inguinal escrotal encarcerada', 'Também dá aumento doloroso do escroto, mas com alça intestinal no saco e gás dentro da alça, não nos tecidos. Não causa choque séptico em três dias.'),
      ],
    },
  },
}
