import { d, r, type ConteudoCaso } from './casos-imagem-tipos'

/** Segunda leva de TC — face, órbita e pescoço. Pacientes das vinhetas são fictícios. */
export const CASOS_TC_L2_CABECA_PESCOCO: Record<string, ConteudoCaso> = {
  'abscesso-orbitario-sinusite-fungica': {
    tema: 'Órbita e seios',
    titulo: 'Abscesso orbitário com sinusite fúngica invasiva',
    resumo: 'Densificação da gordura retro-orbitária com coleção intraconal, músculos reto medial e inferior espessados, erosão óssea do assoalho da órbita e do septo nasal.',
    protocolo: 'TC de órbitas com contraste, fase portal, e janela óssea',
    series: ['Coronal com contraste', 'Janela óssea'],
    rotulos: {
      'right orbital floor': r('Assoalho da órbita direita', 'Limite entre a órbita e o seio maxilar, atravessado pela infecção.',
        'O assoalho da órbita é o teto do seio maxilar. Na sinusite fúngica invasiva, o fungo cresce pelos vasos e atravessa o osso sem precisar de grandes destruições, chegando à gordura da órbita. A gordura densificada logo acima do assoalho mostra por onde a infecção entrou.',
        'Densificação da gordura periantral e orbitária com pouca destruição óssea, em imunodeprimido, é sinal precoce de fungo invasivo.'),
      'medial rectus muscle': r('Reto medial espessado', 'O músculo reto medial direito maior que o esquerdo, inflamado.',
        'Músculos extraoculares inflamados aumentam de volume e perdem a definição de suas bordas. A comparação com o lado oposto é a melhor régua. Músculo espessado com dor e limitação da movimentação é miosite infecciosa, parte da celulite orbitária pós-septal.'),
      'inferior rectus muscle': r('Reto inferior espessado', 'O reto inferior, junto ao assoalho, também inflamado.',
        'O reto inferior corre sobre o assoalho da órbita, a porta de entrada da infecção vinda do seio maxilar. Seu aumento traduz a extensão da inflamação para o cone muscular e explica a dor ao olhar para baixo.'),
      'bony resorption': r('Reabsorção óssea', 'Osso afinado e corroído nas paredes do seio.',
        'Fungos invasivos, como Mucor e Aspergillus, invadem vasos e causam necrose do osso e da mucosa. Na TC, as paredes do seio ficam finas, interrompidas ou desaparecem. Erosão óssea em sinusite muda o diagnóstico de infecção comum para doença agressiva.'),
      'bone erosion of nasal septum.': r('Erosão do septo nasal', 'O septo ósseo nasal corroído pela infecção.',
        'A necrose do septo e dos cornetos é marca da mucormicose em diabéticos descompensados. Ao exame, a mucosa fica preta ou pálida, sem sangrar — sinal que pede biópsia imediata. Essa necrose sem sangramento é um sinal de gravidade que exige desbridamento cirúrgico precoce.'),
      'bony remodelling': r('Remodelação óssea', 'Osso expandido e afinado, sinal de doença de longa duração.',
        'A remodelação, com osso expandido e liso, sugere processo crônico, como a bola fúngica ou a sinusite fúngica alérgica, que coexistem ou precedem a forma invasiva. Distinguir remodelação de erosão ajuda a datar a doença.'),
    },
    achados: [
      'Densificação extensa da gordura retro-orbitária direita junto ao ápice, com pequena coleção intraconal de realce periférico.',
      'Espessamento dos músculos reto medial e inferior direitos e veia oftálmica superior proeminente.',
      'Reabsorção e erosão óssea do seio maxilar e do septo nasal, com remodelação.',
      'Leve abaulamento posterior do globo, sem extensão intracraniana.',
    ],
    armadilhas: [
      'Sinusite fúngica invasiva pode ter pouca destruição óssea visível; a densificação da gordura além do seio é o sinal precoce.',
      'Celulite orbitária em diabético descompensado ou neutropênico é fungo até prova em contrário.',
      'Veia oftálmica superior dilatada e proptose pedem avaliação do seio cavernoso.',
    ],
    conduta: 'Controle da cetoacidose ou da imunossupressão, anfotericina B lipossomal, desbridamento cirúrgico extenso urgente, biópsia com cultura e ressonância para avaliar extensão ao seio cavernoso e ao crânio.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Homem de 58 anos, agricultor, diabético.',
      queixa: 'Olho direito inchado, dor na face e visão embaçada há cinco dias.',
      historia: 'Há duas semanas tem obstrução nasal à direita e dor na bochecha. Há cinco dias o olho direito inchou, ficou dolorido para mexer e a visão embaçou. Notou uma crosta escura dentro do nariz. Está com muita sede e urinando muito.',
      antecedentes: [
        'Pessoais: diabetes tipo 2 mal controlado, sem insulina',
        'Pessoais: uso de corticoide oral há um mês por crise de asma',
        'Familiares: pai e irmã diabéticos',
        'Hábitos: trabalha com silagem e solo úmido',
      ],
      vitais: { pa: '108 × 64 mmHg', fc: '112 bpm', fr: '26 irpm, respiração de Kussmaul', satO2: '97% em ar ambiente', temp: '38,2 °C' },
      exame: [
        'Edema palpebral e proptose à direita com limitação da movimentação ocular',
        'Crosta negra na mucosa do corneto inferior direito',
        'Acuidade visual reduzida à direita',
        'Glicemia de 486 mg/dL e cetonúria',
      ],
      pedido: 'Celulite orbitária com escara nasal em diabético em cetoacidose usando corticoide: a pergunta é a extensão da infecção e se há destruição óssea.',
      pergunta: 'TC de órbitas com contraste e janela óssea. Qual é o achado que responde à pergunta clínica?',
      achado: 'Sinusite fúngica invasiva com abscesso orbitário',
      veredito: 'Sinusite fúngica invasiva com erosão óssea e abscesso orbitário intraconal à direita',
      correlacao: 'Cetoacidose e corticoide criam o ambiente ideal para fungos angioinvasivos como o Mucor. A escara negra na mucosa é necrose por invasão vascular. O fungo atravessou o assoalho da órbita, inflamou os músculos e formou uma coleção dentro do cone. A TC mostra a gordura densificada, os músculos espessados e o osso corroído.',
      distratores: [
        d('Celulite orbitária bacteriana por etmoidite', 'Ocorre sobretudo em crianças, a partir das células etmoidais, com abscesso subperiosteal medial e sem necrose da mucosa nasal nem erosão do septo.'),
        d('Oftalmopatia tireoidiana com músculos espessados', 'Espessa os músculos extraoculares de forma bilateral, poupando os tendões, sem febre, coleção ou destruição óssea. O paciente também teria sinais de hipertireoidismo e exoftalmia de instalação lenta.'),
        d('Pseudotumor inflamatório orbitário', 'Causa dor, proptose e músculos inflamados, mas sem sinusite, sem erosão óssea e com resposta rápida ao corticoide. É diagnóstico de exclusão, depois de afastar infecção e tumor.'),
      ],
    },
  },

  'hemorragia-retrobulbar': {
    tema: 'Órbita e seios',
    titulo: 'Hemorragia retrobulbar com fraturas da base anterior do crânio',
    resumo: 'Hematomas extraconais superomediais nas duas órbitas com proptose e enfisema, fratura transesfenoidal da base e contusões cerebrais.',
    protocolo: 'TC de crânio e órbitas sem contraste, janelas óssea e de partes moles',
    series: ['Janela óssea', 'Partes moles'],
    rotulos: {
      'mastoid part fracture': r('Fratura da porção mastoide', 'Segundo componente da fratura, posterior, pelo mastoide.',
        'A fratura da base pode ter mais de um traço. A extensão ao mastoide ameaça a orelha média e o nervo facial, e explica a equimose retroauricular, o sinal de Battle. Ela pode estender-se ao canal do nervo facial e à orelha média, e a função do facial deve ser registrada logo na admissão.'),
      'planum sphenoidale': r('Fratura do plano esfenoidal', 'Traço no assoalho da fossa anterior, à frente da sela.',
        'O plano esfenoidal separa a fossa craniana anterior do seio esfenoidal. Fraturá-lo comunica o crânio com o seio e pode causar fístula liquórica e pneumoencéfalo. Rinorreia clara após o trauma, com o teste do duplo halo, sugere essa fístula.'),
      'orbital roofs': r('Fratura dos tetos das órbitas', 'Traço nos dois tetos orbitários, finos como papel.',
        'Os tetos das órbitas são o assoalho da fossa anterior. Fraturados, sangram para dentro da órbita, por cima do globo, formando hematomas extraconais superiores que empurram o olho para frente e para baixo.'),
      'zygomaticosphenoid suture': r('Sutura zigomaticoesfenoidal', 'Diástase na junção entre o zigomático e o esfenoide.',
        'Na parede lateral da órbita, a sutura entre o zigomático e a asa maior do esfenoide pode se abrir no trauma. Ela faz parte da parede lateral, e sua lesão indica fratura da órbita lateral.'),
      'greater wing of sphenoid': r('Asa maior do esfenoide', 'Traço na asa maior, parede lateral da órbita e assoalho da fossa média.',
        'A fratura que atravessa as asas maiores do esfenoide de um lado ao outro é transesfenoidal, de alta energia. Ela pode atingir a fissura orbitária superior e o canal óptico, com risco de neuropatia óptica traumática.',
        'Fratura próxima ao canal óptico com perda visual pede avaliação imediata da via óptica.'),
      'squamous temporal bone': r('Escama temporal', 'Ponto de origem lateral da fratura.',
        'A fratura começa na escama temporal direita, ponto do impacto, e cruza a base de um lado ao outro. Seguir o traço de osso em osso é o que permite descrever o padrão da fratura da base. Ela é o ponto mais fino da calota e frequentemente o local do impacto inicial.'),
      Proptosis: r('Proptose', 'Globo ocular empurrado para frente pelo hematoma atrás dele.',
        'A órbita é uma caixa óssea fechada atrás e limitada à frente pelo septo orbitário. Sangue acumulado atrás do globo aumenta a pressão dentro dela e empurra o olho para frente. A pressão comprime a artéria central da retina e o nervo óptico: é a síndrome compartimental da órbita.',
        'Proptose dura com perda visual e pupila aferente após trauma é emergência: cantotomia lateral à beira do leito, antes de qualquer exame.'),
      emphysema: r('Enfisema orbitário', 'Bolhas de ar na gordura da órbita.',
        'Ar na órbita indica comunicação com um seio paranasal por fratura. Ele também aumenta o volume dentro da órbita e pode piorar a compressão do nervo óptico. Ele também ajuda a localizar a fratura, porque o ar entra pelo ponto mais próximo do seio rompido.'),
      Haematoma: r('Hematoma extraconal superomedial', 'Coleção de sangue acima e medial ao globo.',
        'O sangue que sai da fratura do teto fica entre o osso e o periósteo ou na gordura extraconal, em forma de lente acima do globo. Com até 12 mm de espessura, já empurra o olho e estira o nervo óptico.'),
      hematomas: r('Hematoma na órbita contralateral', 'Coleção semelhante na outra órbita.',
        'A bilateralidade mostra que a fratura atravessa as duas órbitas. As duas precisam ser avaliadas clinicamente, mesmo que a queixa seja de um olho só. O olho que parece melhor também pode estar sob pressão e precisa de exame da acuidade e dos reflexos pupilares.'),
      'parenchymal contusion': r('Contusão cerebral', 'Focos hemorrágicos no lobo temporal e frontal.',
        'O mesmo impacto que fraturou a base contundiu o cérebro contra as superfícies irregulares das fossas anterior e média. As contusões ficam nos polos e nas faces inferiores dos lobos frontal e temporal.'),
    },
    achados: [
      'Fratura transversa transesfenoidal da base anterior: escama temporal direita, asas maiores do esfenoide, sutura zigomaticoesfenoidal, tetos das órbitas e plano esfenoidal, com componente pelo mastoide.',
      'Hematomas extraconais superomediais nas duas órbitas, com proptose.',
      'Enfisema orbitário bilateral.',
      'Contusões hemorrágicas temporal esquerda e frontal direita.',
    ],
    armadilhas: [
      'A hemorragia retrobulbar é diagnóstico clínico de urgência: não se espera a TC para descomprimir um olho que está perdendo a visão.',
      'Fraturas do teto da órbita podem levar a encefalocele e fístula liquórica.',
      'Procure o canal óptico em toda fratura da asa do esfenoide.',
    ],
    conduta: 'Cantotomia lateral com cantólise urgente se houver perda visual com proptose tensa, avaliação oftalmológica, antibiótico pela fratura exposta da base, observação neurocirúrgica e vigilância de fístula liquórica.',
    vinheta: {
      cenario: 'Trauma, sala vermelha',
      identificacao: 'Homem de 33 anos, motociclista.',
      queixa: 'Bateu a cabeça em acidente de moto e não enxerga bem com o olho direito.',
      historia: 'Perdeu o controle da moto e bateu o lado direito da cabeça e a testa num muro. Chegou acordado, com dor intensa nos olhos, olhos inchados e saltados, e disse que a visão do olho direito escureceu na última hora.',
      antecedentes: [
        'Pessoais: previamente hígido',
        'Pessoais: sem uso de anticoagulantes',
        'Familiares: sem coagulopatias',
        'Hábitos: estava sem capacete e alcoolizado',
      ],
      vitais: { pa: '146 × 88 mmHg', fc: '104 bpm', fr: '20 irpm', satO2: '97% em ar ambiente', temp: '36,4 °C' },
      exame: [
        'Glasgow 14',
        'Proptose bilateral, pior à direita, com pálpebras tensas',
        'Defeito pupilar aferente à direita e acuidade reduzida a vultos',
        'Rinorreia clara e equimose retroauricular direita',
      ],
      pedido: 'Trauma facial e craniano com proptose tensa, perda visual e defeito pupilar aferente: a pergunta é se há hemorragia retrobulbar e fratura da base.',
      pergunta: 'TC de crânio e órbitas. Qual é o achado que responde à pergunta clínica?',
      achado: 'Hemorragia retrobulbar com fratura da base',
      veredito: 'Hemorragia retrobulbar bilateral com proptose, enfisema orbitário e fratura transesfenoidal da base anterior',
      correlacao: 'A fratura atravessou os tetos das órbitas e sangrou para dentro delas. A órbita é uma caixa fechada: o sangue elevou a pressão, empurrou os olhos e comprimiu o nervo óptico direito, daí a perda visual e o defeito pupilar aferente. A rinorreia clara e o sinal de Battle apontam fratura da base com fístula liquórica.',
      distratores: [
        d('Fratura em blowout do assoalho orbitário', 'Faz o olho afundar, com diplopia vertical e hipoestesia infraorbitária, sem proptose tensa nem perda visual. Aqui o olho está saltado e o nervo óptico sofre.'),
        d('Neuropatia óptica traumática isolada', 'Causa perda visual e defeito aferente sem proptose, por lesão direta do nervo no canal óptico. Este paciente tem hematoma retrobulbar com proptose tensa.'),
        d('Fístula carotídeo-cavernosa traumática', 'Dá proptose pulsátil com sopro e quemose, dias a semanas após o trauma, por shunt arteriovenoso, e não hematoma retrobulbar imediato.'),
      ],
    },
  },

  'fratura-do-complexo-zigomaticomaxilar': {
    tema: 'Fraturas da face',
    titulo: 'Corpo estranho intraoral após reparo de fratura zigomaticomaxilar',
    resumo: 'Pós-operatório de fraturas do complexo zigomaticomaxilar com placa, material hemostático no seio e corpo estranho com gás no sulco gengivobucal.',
    protocolo: 'TC de face sem contraste, janela óssea axial e coronal',
    series: ['Axial, janela óssea', 'Coronal'],
    rotulos: {
      'ovoid density': r('Corpo estranho ovoide no sulco gengivobucal', 'Objeto denso e ovalado com bolhas de gás, dentro da boca.',
        'Uma densidade ovoide no sulco entre a gengiva e a bochecha, com gás dentro e ao redor, não faz parte do material cirúrgico: é um corpo estranho que o paciente colocou na boca — aqui, algo mastigável. Corpos estranhos na via aérea superior e no sulco precisam ser reconhecidos porque podem ser aspirados.',
        'No pós-operatório, compare cada estrutura densa com a descrição cirúrgica: o que não foi colocado pela equipe é corpo estranho.'),
      'plate and microscrews': r('Placa e microparafusos', 'Material de osteossíntese fixando a fratura.',
        'Placas e parafusos de titânio estabilizam os fragmentos do complexo zigomaticomaxilar. Na TC aparecem muito densos, com artefato em estrias. A posição e o alinhamento dos fragmentos ao redor mostram se a redução foi adequada.'),
      'hemostatic/ surgical filler ma': r('Material hemostático no seio maxilar', 'Material radiopaco preenchendo o seio, com artefato metálico.',
        'Após cirurgias de face, o seio maxilar pode ser preenchido com material hemostático ou de tamponamento, que aparece denso na TC. Reconhecê-lo evita confundir com sangue organizado, tumor ou corpo estranho.'),
      'superficial drain in situ': r('Dreno superficial', 'Dreno no subcutâneo do couro cabeludo.',
        'Drenos superficiais são deixados após cirurgias extensas para evitar acúmulo de sangue. Sua ponta deve estar no local da dissecção, e não em cavidades profundas. Dreno com débito alto ou com sangue vivo sugere sangramento na ferida operatória e deve ser avaliado.'),
      'post-traumatic contusion': r('Contusão frontal em resolução', 'Área frontal hipodensa, contusão antiga.',
        'A contusão evolui de foco hemorrágico denso para área hipodensa à medida que o sangue é reabsorvido. Em trauma facial grave, a contusão cerebral associada é frequente e deve ser acompanhada.'),
    },
    achados: [
      'Fraturas extensas do complexo zigomaticomaxilar e da órbita esquerda, parcialmente fixadas com placa e microparafusos.',
      'Material hemostático radiopaco no seio maxilar esquerdo e tela no assoalho da órbita.',
      'Corpo estranho ovoide com gás no sulco gengivobucal direito.',
      'Contusão frontal esquerda em resolução e dreno superficial no couro cabeludo.',
    ],
    armadilhas: [
      'Material cirúrgico, hemostáticos e próteses podem simular sangue, tumor ou corpo estranho; leia com a descrição da cirurgia.',
      'Corpo estranho na cavidade oral de paciente com rebaixamento pode ser aspirado.',
      'O artefato metálico esconde estruturas próximas; ajuste a janela.',
    ],
    conduta: 'Remoção do corpo estranho oral, cuidados de via aérea, seguimento da reconstrução orbitária e facial programada e avaliação oftalmológica.',
    vinheta: {
      cenario: 'Enfermaria de cirurgia bucomaxilofacial',
      identificacao: 'Homem de 27 anos, operário, segunda semana de pós-operatório.',
      queixa: 'Dor e inchaço na bochecha direita desde ontem.',
      historia: 'Sofreu esmagamento da face esquerda numa prensa industrial e está em reconstrução por etapas. Ontem passou a sentir dor no lado direito da boca, oposto às fraturas. A enfermagem viu que ele mastiga goma escondido, apesar da orientação de dieta líquida.',
      antecedentes: [
        'Pessoais: previamente hígido',
        'Pessoais: cirurgia de face há dez dias com fixação parcial',
        'Familiares: sem doenças relevantes',
        'Hábitos: tabagista de 10 cigarros por dia',
      ],
      vitais: { pa: '124 × 76 mmHg', fc: '84 bpm', fr: '16 irpm', satO2: '98% em ar ambiente', temp: '37,4 °C' },
      exame: [
        'Edema na bochecha direita',
        'Abaulamento no sulco gengivobucal direito',
        'Ferida operatória da face esquerda limpa',
        'Dreno no couro cabeludo com pouco débito',
      ],
      pedido: 'Dor e abaulamento intraoral do lado oposto às fraturas em paciente em reconstrução facial: a pergunta é a causa do abaulamento e o estado da reconstrução.',
      pergunta: 'TC de face. Qual é o achado que responde à pergunta clínica?',
      achado: 'Corpo estranho no sulco gengivobucal',
      veredito: 'Corpo estranho ovoide com gás no sulco gengivobucal direito em pós-operatório de fraturas zigomaticomaxilares',
      correlacao: 'O abaulamento doloroso está do lado oposto às fraturas, longe do material cirúrgico. A TC mostra uma densidade ovoide com gás dentro e ao redor no sulco gengivobucal direito — um objeto mastigável que ficou retido, com inflamação em volta. Todo o resto de denso na imagem é material da cirurgia: placa, parafusos, tela e hemostático.',
      distratores: [
        d('Abscesso odontogênico do lado direito', 'Formaria coleção com realce periférico ligada à raiz de um dente doente, com reabsorção óssea periapical. O que está no sulco é uma densidade ovoide sem origem dentária.'),
        d('Falha da fixação com fragmento solto', 'Mostraria fragmento ósseo ou placa deslocados no lado operado. A reconstrução à esquerda está estável e o achado novo é do lado oposto.'),
        d('Hematoma pós-operatório da bochecha', 'Seria coleção de sangue nas partes moles junto às fraturas operadas, sem gás interno nem forma ovoide definida. O hematoma também ficaria do lado operado, à esquerda, e não do lado oposto.'),
      ],
    },
  },

  'fratura-de-le-fort': {
    tema: 'Fraturas da face',
    titulo: 'Fraturas das paredes do seio maxilar com enfisema profundo',
    resumo: 'Fraturas das paredes lateral e anterior do seio maxilar direito, hemossinus e ar dissecando os espaços profundos da face.',
    protocolo: 'TC de face sem contraste, janelas óssea e de partes moles',
    series: ['Janela óssea', 'Partes moles'],
    rotulos: {
      'Air pockets': r('Bolhas de ar nos espaços profundos', 'Ar nos espaços retromaxilozigomático, mastigatório e parafaríngeo.',
        'Quando a parede do seio maxilar quebra, o ar do seio escapa para os tecidos moles. Ele disseca os planos profundos da face — atrás da maxila, no espaço mastigatório e até o parafaríngeo. Assoar o nariz piora o enfisema.',
        'Oriente o paciente a não assoar o nariz: a pressão empurra ar e bactérias do seio para os tecidos e para a órbita.'),
      Fractures: r('Fraturas das paredes do seio maxilar', 'Parede lateral desviada para dentro e anterior abaulada para fora.',
        'O seio maxilar é uma caixa de paredes finas. O impacto lateral empurra a parede lateral para dentro e a anterior se dobra para fora. Fraturas que envolvem os pilares de sustentação da face — a parede lateral é parte do pilar zigomaticomaxilar — podem exigir fixação para restaurar a altura e a projeção da face.'),
      haemosinus: r('Hemossinus', 'Seio maxilar parcialmente preenchido por sangue hiperdenso.',
        'Sangue dentro do seio após trauma tem densidade maior que a secreção comum e muitas vezes forma nível. Hemossinus em seio com paredes íntegras sugere fratura que não aparece; por isso é sinal indireto valioso.'),
    },
    achados: [
      'Fratura da parede lateral do seio maxilar direito com desvio medial.',
      'Fratura da parede anterior com abaulamento externo.',
      'Hemossinus maxilar direito.',
      'Enfisema nos espaços retromaxilozigomático, mastigatório e parafaríngeo lateral.',
    ],
    armadilhas: [
      'As fraturas de Le Fort exigem separação entre a maxila e a base do crânio, com acometimento das lâminas pterigoides; fraturas isoladas das paredes do seio não são Le Fort.',
      'Procure sempre as lâminas pterigoides: se estiverem íntegras, Le Fort fica afastado.',
      'Enfisema extenso pode chegar à órbita e ao mediastino.',
    ],
    conduta: 'Analgesia, antibiótico conforme protocolo, orientação para não assoar o nariz e avaliação bucomaxilofacial para decidir fixação conforme desvio e oclusão.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Homem de 35 anos, segurança.',
      queixa: 'Levou um soco forte na bochecha direita e o rosto inchou ao assoar o nariz.',
      historia: 'Foi agredido durante o trabalho com socos no lado direito do rosto. Sentiu dor e sangrou pelo nariz. Ao assoar o nariz, a bochecha e as pálpebras incharam de repente, com sensação de crepitação. Refere dormência na bochecha e nos dentes de cima à direita.',
      antecedentes: [
        'Pessoais: previamente hígido',
        'Pessoais: sem uso de anticoagulantes',
        'Familiares: sem coagulopatias',
        'Hábitos: pratica lutas, tabagista social',
      ],
      vitais: { pa: '136 × 84 mmHg', fc: '92 bpm', fr: '16 irpm', satO2: '99% em ar ambiente', temp: '36,6 °C' },
      exame: [
        'Edema e crepitação na bochecha e na pálpebra inferior direitas',
        'Dor à palpação da parede anterior da maxila',
        'Hipoestesia no território do nervo infraorbitário',
        'Oclusão dentária preservada',
      ],
      pedido: 'Trauma facial com enfisema após assoar o nariz e hipoestesia infraorbitária: a pergunta é a extensão da fratura e se há instabilidade da face média.',
      pergunta: 'TC de face. Qual é o achado que responde à pergunta clínica?',
      achado: 'Fratura das paredes do seio maxilar',
      veredito: 'Fraturas das paredes lateral e anterior do seio maxilar direito com hemossinus e enfisema dos espaços profundos',
      correlacao: 'O soco quebrou as paredes finas do seio maxilar. O sangue se acumulou no seio, e, ao assoar o nariz, o ar foi empurrado do seio para os planos profundos da face, causando crepitação. A hipoestesia vem do nervo infraorbitário, que corre na parede anterior. A oclusão preservada e a face estável afastam fratura de Le Fort.',
      distratores: [
        d('Fratura de Le Fort tipo I', 'Separa todo o palato e o arco dentário do resto da face, com mobilidade da maxila e alteração da oclusão, acometendo as lâminas pterigoides.'),
        d('Fratura isolada do arco zigomático', 'Afunda o arco e limita a abertura da boca por compressão do músculo temporal, sem fraturar as paredes do seio nem causar hemossinus.'),
        d('Fratura em blowout do assoalho orbitário', 'Também pode causar hipoestesia infraorbitária e enfisema, mas o defeito está no assoalho da órbita, com diplopia vertical e limitação do olhar para cima.'),
      ],
    },
  },

  'fratura-de-mandibula': {
    tema: 'Fraturas da face',
    titulo: 'Fratura do ângulo da mandíbula com lesão do canal do nervo alveolar inferior',
    resumo: 'Fratura oblíqua do ângulo esquerdo da mandíbula, atravessando o alvéolo de um terceiro molar incluso e interrompendo o canal do nervo alveolar inferior.',
    protocolo: 'TC de face sem contraste, janela óssea sagital e axial',
    series: ['Sagital, janela óssea', 'Axial'],
    rotulos: {
      socket: r('Alvéolo do terceiro molar incluso', 'A fratura passa pelo alvéolo do dente do siso não erupcionado.',
        'O terceiro molar incluso ocupa espaço no osso do ângulo da mandíbula e o enfraquece. Por isso o ângulo é um local frequente de fratura em jovens com siso incluso. Dente na linha de fratura pode precisar ser extraído para evitar infecção e pseudoartrose.'),
      'inferior alveolar nerve canal': r('Canal do nervo alveolar inferior interrompido', 'A fratura atravessa o canal por onde corre o nervo.',
        'O nervo alveolar inferior corre dentro de um canal no corpo da mandíbula e dá sensibilidade aos dentes de baixo, ao lábio inferior e ao queixo. Fratura que interrompe o canal explica dormência no lábio e no queixo — o sinal de Vincent — e pode deixar sequela sensitiva.',
        'Pergunte sempre pela dormência do lábio inferior e documente antes da cirurgia.'),
      'Left frontal sinus fluid': r('Líquido no seio frontal', 'Conteúdo denso no seio frontal esquerdo, sem fratura da parede.',
        'Líquido denso no seio após trauma pode ser sangue, mesmo sem fratura visível, ou secreção de sinusite. Aqui as paredes estão íntegras, o que favorece sinusite ou sangue vindo de outro ponto.'),
    },
    achados: [
      'Fratura oblíqua com leve desvio do ângulo esquerdo da mandíbula.',
      'Traço atravessando o alvéolo de um terceiro molar incluso.',
      'Interrupção do canal do nervo alveolar inferior esquerdo.',
      'Conteúdo denso no seio frontal esquerdo sem fratura de parede.',
    ],
    armadilhas: [
      'A mandíbula funciona como um anel: uma fratura muitas vezes vem acompanhada de outra, geralmente no côndilo ou na sínfise do lado oposto.',
      'A radiografia panorâmica pode não mostrar fraturas condilares; a TC é superior.',
      'Fratura que se comunica com o alvéolo é considerada exposta e pede antibiótico.',
    ],
    conduta: 'Antibiótico, analgesia, avaliação bucomaxilofacial para redução e fixação interna, extração do dente na linha de fratura quando indicado e registro da sensibilidade do lábio.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Homem de 22 anos, estudante.',
      queixa: 'Dor no queixo e a boca não fecha direito após levar uma joelhada.',
      historia: 'Durante uma partida de futebol levou uma joelhada no lado esquerdo do rosto. Desde então dói para mastigar, sente que os dentes não se encaixam e o lábio de baixo e o queixo do lado esquerdo estão dormentes.',
      antecedentes: [
        'Pessoais: sisos inclusos sem extração',
        'Pessoais: sinusites frequentes',
        'Familiares: sem doenças relevantes',
        'Hábitos: pratica futebol sem protetor bucal',
      ],
      vitais: { pa: '122 × 76 mmHg', fc: '86 bpm', fr: '14 irpm', satO2: '99% em ar ambiente', temp: '36,7 °C' },
      exame: [
        'Edema e dor no ângulo esquerdo da mandíbula',
        'Má oclusão dentária com degrau entre os dentes posteriores',
        'Hipoestesia do lábio inferior e do queixo à esquerda',
        'Limitação da abertura bucal',
      ],
      pedido: 'Trauma mandibular com má oclusão e dormência do lábio inferior: a pergunta é a localização da fratura e o comprometimento do nervo alveolar inferior.',
      pergunta: 'TC de face. Qual é o achado que responde à pergunta clínica?',
      achado: 'Fratura do ângulo mandibular',
      veredito: 'Fratura do ângulo esquerdo da mandíbula atravessando o alvéolo do siso e o canal do nervo alveolar inferior',
      correlacao: 'O siso incluso enfraquece o ângulo da mandíbula, ponto em que o impacto lateral concentra a força. A fratura alterou a oclusão e atravessou o canal do nervo alveolar inferior, que corre por dentro do osso: daí a dormência no lábio e no queixo.',
      distratores: [
        d('Fratura do côndilo mandibular', 'Também causa má oclusão, mas com dor e desvio junto ao ouvido, perto da articulação temporomandibular, sem dormência do lábio.'),
        d('Luxação da articulação temporomandibular', 'Deixa a boca travada aberta, com o côndilo à frente da eminência articular, sem fratura nem lesão do nervo alveolar. A redução é feita com manobra manual, sem cirurgia.'),
        d('Pericoronarite do terceiro molar', 'Dá dor e limitação da abertura em torno do siso inflamado, sem trauma, sem má oclusão e sem traço de fratura. O tratamento é local, com limpeza e antibiótico, e não fixação.'),
      ],
    },
  },

  'fratura-do-osso-temporal': {
    tema: 'Fraturas da face',
    titulo: 'Fratura longitudinal do osso temporal com disjunção da cadeia ossicular',
    resumo: 'Fratura longitudinal do temporal direito até a orelha média com separação entre bigorna e martelo, comparada à articulação normal do lado esquerdo.',
    protocolo: 'TC de ossos temporais, janela óssea de alta resolução',
    rotulos: {
      'Normal joint': r('Articulação incudomaleolar normal', 'Do lado sadio, martelo e bigorna encaixados como uma casquinha de sorvete.',
        'No corte axial, a cabeça do martelo e o corpo da bigorna formam a imagem de uma casquinha de sorvete: a bola é a cabeça do martelo, o cone é a bigorna. Comparar com o lado sadio é a melhor forma de reconhecer a disjunção.',
        'A comparação com o lado oposto é a régua da TC de osso temporal.'),
      'Left incus': r('Bigorna esquerda', 'Bigorna normal do lado esquerdo.',
        'A bigorna é o ossículo do meio da cadeia, entre o martelo e o estribo. Do lado esquerdo está alinhada ao martelo, servindo de referência. Seu corpo forma o cone da casquinha de sorvete, e seu ramo longo desce até o estribo.'),
      'Left malleus': r('Martelo esquerdo', 'Martelo normal, preso à membrana timpânica.',
        'O martelo se prende à membrana timpânica e articula com a bigorna. Do lado esquerdo, a relação entre os dois está preservada. Sua cabeça forma a bola da casquinha de sorvete vista no corte axial.'),
      Fracture: r('Traço de fratura longitudinal', 'Fratura paralela ao eixo maior do rochedo, chegando à orelha média.',
        'A fratura longitudinal corre paralela ao eixo da porção petrosa e costuma atravessar a orelha média, lesando a cadeia ossicular e a membrana timpânica. Causa perda auditiva de condução. A transversa, perpendicular, atravessa a cápsula ótica e lesa o nervo facial e a cóclea com mais frequência.',
        'A classificação atual divide as fraturas em que poupam e que violam a cápsula ótica — o que mais importa para o prognóstico.'),
      'Incudomalleolar disruption': r('Disjunção incudomaleolar', 'A bigorna separou-se do martelo à direita.',
        'O sorvete caiu da casquinha: o martelo e a bigorna perderam o contato. A cadeia ossicular interrompida não transmite a vibração da membrana para a orelha interna, causando perda auditiva de condução que pode exigir reconstrução cirúrgica.'),
      'Right incus': r('Bigorna direita deslocada', 'Bigorna fora do lugar do lado fraturado.',
        'A bigorna é o ossículo mais frequentemente deslocado, porque é presa por ligamentos mais frágeis. Seu deslocamento é a principal causa de perda condutiva persistente após trauma. Na TC, o cone da casquinha aparece afastado ou rodado em relação à bola.'),
      'Right malleus': r('Martelo direito', 'Martelo do lado fraturado, separado da bigorna.',
        'O martelo permanece preso à membrana timpânica, enquanto a bigorna se desloca. Ver a cabeça do martelo isolada, sem o cone da bigorna, confirma a disjunção. A membrana íntegra ao exame não exclui essa lesão, que só a TC de alta resolução mostra.'),
      'Left temporal bone fracture': r('Fratura temporal esquerda', 'Fratura sem desvio também do lado esquerdo.',
        'Fraturas bilaterais do osso temporal indicam trauma de energia muito alta. Mesmo sem desvio, a do lado esquerdo precisa de avaliação auditiva. Fraturas bilaterais aumentam o risco de perda auditiva nos dois ouvidos e de fístula liquórica.'),
    },
    achados: [
      'Fratura longitudinal do osso temporal direito estendendo-se à orelha média.',
      'Disjunção incudomaleolar à direita, comparada com a articulação normal à esquerda.',
      'Fratura sem desvio do osso temporal esquerdo.',
    ],
    armadilhas: [
      'Hemotímpano e perda auditiva após trauma pedem TC de osso temporal; a TC de crânio comum não tem resolução suficiente.',
      'Perda auditiva de condução persistente depois que o sangue da orelha média reabsorve sugere disjunção ossicular.',
      'Paralisia facial imediata após fratura do temporal pode ser indicação de descompressão cirúrgica.',
    ],
    conduta: 'Audiometria, avaliação do nervo facial, observação da fístula liquórica, antibiótico conforme protocolo e reconstrução ossicular eletiva se a perda condutiva persistir.',
    vinheta: {
      cenario: 'Ambulatório de otorrinolaringologia',
      identificacao: 'Mulher de 41 anos, professora.',
      queixa: 'Escuta mal do ouvido direito desde um acidente há quatro semanas.',
      historia: 'Há quatro semanas bateu o lado direito da cabeça em acidente de carro. Teve sangramento pelo ouvido direito, que parou em dois dias. Desde então escuta abafado e tem um zumbido baixo à direita. Nega tontura e fraqueza na face.',
      antecedentes: [
        'Pessoais: sem doenças otológicas prévias',
        'Gestacionais: dois partos normais',
        'Familiares: sem surdez hereditária',
        'Hábitos: nega exposição a ruído ocupacional',
      ],
      vitais: { pa: '118 × 76 mmHg', fc: '72 bpm', fr: '14 irpm', satO2: '99% em ar ambiente', temp: '36,4 °C' },
      exame: [
        'Membrana timpânica direita íntegra, sem sangue atrás dela',
        'Weber lateralizado para a direita',
        'Rinne negativo à direita',
        'Função do nervo facial preservada',
      ],
      pedido: 'Perda auditiva de condução persistente após trauma temporal, com membrana timpânica íntegra: a pergunta é se há lesão da cadeia ossicular.',
      pergunta: 'TC de ossos temporais. Qual é o achado que responde à pergunta clínica?',
      achado: 'Disjunção incudomaleolar traumática',
      veredito: 'Fratura longitudinal do temporal direito com disjunção incudomaleolar',
      correlacao: 'Weber para o lado afetado e Rinne negativo indicam perda de condução. O sangue da orelha média já foi reabsorvido e a membrana está íntegra, mas a perda persiste: a vibração não chega à orelha interna porque a bigorna se soltou do martelo. A fratura longitudinal atravessou a orelha média, o trajeto típico desse padrão.',
      distratores: [
        d('Perda auditiva neurossensorial por concussão coclear', 'Também ocorre após trauma, mas o Weber lateraliza para o ouvido sadio e o Rinne é positivo, sem desarranjo ossicular. A TC não mostraria desarranjo da cadeia.'),
        d('Hemotímpano persistente sem fratura', 'Daria sangue atrás da membrana na otoscopia e reabsorve em semanas. A membrana desta paciente está normal e a cadeia, desarticulada.'),
        d('Fratura transversa com lesão da cápsula ótica', 'Atravessa a cóclea e o labirinto, com perda neurossensorial e vertigem e frequente paralisia facial, e não perda condutiva isolada.'),
      ],
    },
  },
}
