import { d, r, type ConteudoCaso } from './casos-imagem-tipos'

/** Terceira leva de TC — trauma abdominal e pélvico. Pacientes fictícios. */
export const CASOS_TC_L3_TRAUMA: Record<string, ConteudoCaso> = {
  'ruptura-de-bexiga': {
    tema: 'Órgãos sólidos',
    titulo: 'Ruptura extraperitoneal da bexiga com fraturas pélvicas',
    resumo: 'Contraste da cistotomografia extravasando para o espaço de Retzius e o espaço extraperitoneal da pelve, sinal do dente molar, defeitos nas paredes anterior e lateral direita da bexiga e fraturas dos ramos púbicos.',
    protocolo: 'TC com cistografia por sonda, fase tardia e janela óssea',
    series: ['Cistotomografia', 'Janela óssea'],
    rotulos: {
      'Contrast in retroperitoneum': r('Contraste no retroperitônio', 'Contraste subindo para o espaço pararrenal anterior direito.',
        'O contraste que sai da bexiga rompida fora do peritônio se espalha pelos planos de gordura extraperitoneais e pode subir até o retroperitônio, atrás do cólon. Isso mostra a extensão do vazamento, mas não muda o fato de a ruptura ser extraperitoneal.'),
      'contrast in the bladder': r('Contraste na bexiga', 'Bexiga cheia com o contraste instilado pela sonda.',
        'Na cistotomografia, o contraste é colocado pela sonda até encher a bexiga, com pelo menos 300 a 350 mL. A distensão é necessária: com a bexiga vazia, pequenas rupturas não vazam e passam despercebidas.',
        'Cistografia só por excreção do contraste venoso não basta: encha a bexiga pela sonda.'),
      'space of Retzius': r('Contraste no espaço de Retzius', 'Contraste no espaço pré-vesical, atrás do púbis.',
        'O espaço de Retzius fica entre o púbis e a bexiga, fora do peritônio. Contraste ali, sem contraste entre as alças, define a ruptura extraperitoneal, quase sempre causada por fratura pélvica ou por um fragmento de osso que perfura a bexiga.'),
      '"molar tooth sign"': r('Sinal do dente molar', 'Contraste em volta da bexiga desenhando a forma de um dente molar.',
        'O contraste extraperitoneal preenche o espaço pré-vesical e os lados da bexiga, desenhando uma forma com raízes, como um dente molar. É a imagem clássica da ruptura extraperitoneal na cistografia.'),
      'right bladder wall defect': r('Defeito na parede lateral direita', 'Falha na parede anterolateral direita da bexiga.',
        'Ver o local exato da ruptura ajuda a planejar o tratamento. Rupturas extraperitoneais simples costumam cicatrizar com sonda vesical por cerca de duas semanas, sem cirurgia. A cistografia de controle confirma o fechamento antes de retirar a sonda.'),
      'Anterior bladder wall defect': r('Defeito na parede anterior', 'Falha na parede anterior da bexiga.',
        'A parede anterior fica logo atrás do púbis. Fragmentos ósseos da fratura do ramo púbico ou da sínfise podem perfurá-la. Quando o osso continua dentro da bexiga ou a ruptura envolve o colo vesical, a correção cirúrgica é indicada.'),
      'pubic symphysis': r('Contraste pela sínfise púbica', 'Contraste atravessando a sínfise.',
        'O contraste que atravessa a sínfise mostra que os ligamentos e o osso em volta foram rompidos. A lesão da sínfise faz parte do trauma do anel pélvico e aumenta a instabilidade. Ela pode exigir fixação.'),
      'left adductor muscles': r('Contraste nos adutores esquerdos', 'Contraste infiltrando os músculos adutores da coxa esquerda.',
        'Rupturas extensas deixam a urina e o contraste escaparem para a raiz da coxa e o períneo. Isso indica ruptura complexa e grande vazamento, o que pode exigir reparo cirúrgico em vez de só sonda.'),
      'superior pubic ramus fracture': r('Fratura do ramo púbico superior', 'Traço no ramo púbico superior.',
        'Fraturas dos ramos púbicos são as que mais se associam a lesão da bexiga, porque o osso fica colado à parede anterior. Fraturas pélvicas com sangue na urina pedem sempre cistografia. É o caso aqui.'),
      'inferior pubic ramus fracture': r('Fratura do ramo púbico inferior', 'Traço no ramo púbico inferior.',
        'Fraturas dos dois ramos indicam lesão do arco anterior da pelve. Elas também podem lesar a uretra, embora isso seja muito mais comum em homens. Na mulher, a uretra curta é raramente lesada, ao contrário do homem, em que a uretra posterior sofre com fraturas do anel.'),
    },
    achados: [
      'Contraste extraperitoneal na pelve dos dois lados, incluindo o espaço de Retzius — sinal do dente molar; sem contraste intraperitoneal.',
      'Defeitos na parede anterior e anterolateral direita da bexiga.',
      'Contraste atravessando a sínfise púbica até os músculos adutores esquerdos e subindo ao espaço pararrenal anterior direito.',
      'Fraturas dos ramos púbicos superior e inferior.',
    ],
    armadilhas: [
      'Ruptura intraperitoneal mostra contraste entre as alças e em volta do fígado e exige cirurgia.',
      'Sangue no meato uretral contraindica a sondagem antes da uretrografia.',
      'Bexiga pouco distendida esconde pequenas rupturas.',
    ],
    conduta: 'Sonda vesical de demora por 10 a 14 dias com cistografia de controle, antibiótico, fixação das fraturas pélvicas e reparo cirúrgico se houver fragmento ósseo na bexiga, lesão do colo ou vazamento extenso.',
    vinheta: {
      cenario: 'Sala de trauma',
      identificacao: 'Mulher de 36 anos, professora.',
      queixa: 'Dor forte na bacia e urina com sangue depois de atropelamento.',
      historia: 'Foi atropelada por um carro ao atravessar a rua e bateu a bacia no chão. Chegou com dor intensa no púbis, sem conseguir andar. Ao ser sondada, a urina saiu com sangue vivo. Usa DIU há três anos.',
      antecedentes: [
        'Pessoais: sem doenças',
        'Gestacionais: dois partos normais; DIU de cobre',
        'Familiares: sem doenças relevantes',
        'Hábitos: não fuma',
      ],
      vitais: { pa: '104 × 64 mmHg', fc: '112 bpm', fr: '22 irpm', satO2: '97% em ar ambiente', temp: '36,4 °C' },
      exame: [
        'Dor à compressão da pelve',
        'Equimose suprapúbica e na raiz da coxa esquerda',
        'Hematúria macroscópica pela sonda',
        'Sem sangue no meato uretral',
      ],
      pedido: 'Fratura pélvica com hematúria macroscópica após atropelamento: a pergunta é se há ruptura da bexiga e de que tipo.',
      pergunta: 'TC com cistografia. Qual é o achado que responde à pergunta clínica?',
      achado: 'Ruptura extraperitoneal da bexiga',
      veredito: 'Ruptura extraperitoneal da bexiga com fraturas dos ramos púbicos',
      correlacao: 'O impacto fraturou os ramos púbicos, e fragmentos e a força de cisalhamento rasgaram a parede anterior da bexiga, colada ao púbis. Como a ruptura está abaixo do peritônio, a urina e o contraste vazaram para o espaço de Retzius e os planos da pelve, formando o dente molar, e desceram para a coxa, onde há equimose.',
      distratores: [
        d('Ruptura intraperitoneal da bexiga', 'Ocorre com a bexiga cheia em trauma direto no abdome, e o contraste vai para entre as alças e as goteiras, exigindo cirurgia. Aqui não há contraste entre as alças.'),
        d('Lesão da uretra posterior', 'É típica de homens com fratura pélvica, com sangue no meato e próstata elevada, e a bexiga fica íntegra. Aqui a paciente é mulher e não há sangue no meato.'),
        d('Contusão da bexiga sem ruptura', 'Causa hematúria após trauma, mas a cistografia não mostra contraste fora da bexiga. A hematúria costuma ser leve e a bexiga fica íntegra na imagem, sem defeitos na parede nem sinal do dente molar.'),
      ],
    },
  },

  'ruptura-diafragmatica': {
    tema: 'Órgãos sólidos',
    titulo: 'Hérnia diafragmática traumática tardia com estômago no tórax',
    resumo: 'Defeito persistente no hemidiafragma esquerdo com herniação do estômago, sinal do colar no ponto em que o estômago atravessa o defeito e gordura mesentérica herniada.',
    protocolo: 'TC de tórax e abdome com contraste, sagital e coronal',
    series: ['Sagital', 'Coronal'],
    rotulos: {
      Defect: r('Defeito no diafragma esquerdo', 'Falha na continuidade do hemidiafragma esquerdo.',
        'O diafragma esquerdo rompe mais que o direito, porque o fígado protege o lado direito. No trauma fechado, o aumento brusco da pressão abdominal rasga o músculo. A ruptura pode passar despercebida no início, principalmente em pacientes ventilados, e as vísceras sobem para o tórax meses ou anos depois, como aqui.',
        'Toda ferida penetrante abaixo do quinto espaço intercostal pode ter lesão de diafragma.'),
      Stomach: r('Estômago no tórax', 'O estômago passou pelo defeito e ocupa a base do hemitórax esquerdo.',
        'O abdome tem pressão positiva e o tórax, negativa. Por isso, uma vez aberto o diafragma, as vísceras são sugadas para cima, e o defeito tende a aumentar com o tempo. O estômago no tórax pode se torcer e estrangular, uma emergência cirúrgica.'),
      'Fat herniating': r('Gordura herniada', 'Gordura do mesentério e do omento passando pelo defeito.',
        'Antes das vísceras, a gordura costuma subir pelo defeito. Ver gordura abdominal acima do diafragma, junto com a falha muscular, ajuda a confirmar a lesão em casos sutis. Pode ser o único sinal.'),
    },
    achados: [
      'Defeito persistente no hemidiafragma esquerdo.',
      'Herniação do estômago para o tórax pelo defeito, com sinal do colar, em que o estômago é estrangulado pelas bordas do diafragma.',
      'Gordura mesentérica herniando pelo defeito.',
    ],
    armadilhas: [
      'Eventração diafragmática eleva o diafragma, mas ele fica contínuo, sem colar.',
      'Sonda nasogástrica acima do diafragma na radiografia é pista importante.',
      'Não drene o tórax antes de saber se é estômago: pode furar a víscera.',
    ],
    conduta: 'Sonda nasogástrica para descomprimir, cirurgia com redução do estômago e fechamento do defeito, de urgência se houver sinais de estrangulamento.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Homem de 44 anos, caminhoneiro.',
      queixa: 'Dor no peito do lado esquerdo e vômitos depois de comer, há dois dias.',
      historia: 'Há dois anos sofreu um acidente de caminhão com fraturas de costelas, tratado em outro hospital. Desde então sente estufamento e falta de ar depois de comer muito. Há dois dias, após um almoço grande, teve dor forte no lado esquerdo do peito e vômitos, e agora não consegue vomitar apesar da ânsia.',
      antecedentes: [
        'Pessoais: trauma toracoabdominal fechado há dois anos',
        'Pessoais: fraturas de costelas esquerdas',
        'Familiares: sem doenças relevantes',
        'Hábitos: refeições volumosas e irregulares',
      ],
      vitais: { pa: '138 × 86 mmHg', fc: '112 bpm', fr: '24 irpm', satO2: '93% em ar ambiente', temp: '37,3 °C' },
      exame: [
        'Murmúrio vesicular ausente na base esquerda',
        'Ruídos hidroaéreos audíveis no hemitórax esquerdo',
        'Sonda nasogástrica não progride',
        'Abdome escavado',
      ],
      pedido: 'Dor torácica com vômitos, ruídos intestinais no tórax e sonda que não passa anos após trauma fechado: a pergunta é se há víscera abdominal no tórax.',
      pergunta: 'TC de tórax e abdome. Qual é o achado que responde à pergunta clínica?',
      achado: 'Hérnia diafragmática traumática',
      veredito: 'Herniação tardia do estômago por ruptura traumática do hemidiafragma esquerdo',
      correlacao: 'O acidente rasgou o diafragma esquerdo, e a lesão passou despercebida. A pressão negativa do tórax foi puxando o omento e depois o estômago para cima, o que explica o estufamento após as refeições. Agora o estômago ficou preso no colar do defeito, por isso a dor, a ânsia sem vômito e a sonda que não passa: risco de estrangulamento.',
      distratores: [
        d('Eventração do diafragma esquerdo', 'Eleva o diafragma inteiro, que fica fino mas contínuo, sem defeito nem colar estrangulando o estômago. Costuma ser congênita e sem sintomas.'),
        d('Hérnia de hiato paraesofágica', 'Leva o estômago para o tórax pelo hiato esofágico, no centro, e não por um defeito na parte lateral do diafragma após trauma. Não tem relação com trauma.'),
        d('Derrame pleural loculado esquerdo', 'Ocupa a base do hemitórax com líquido, sem ruídos intestinais, sem estômago acima do diafragma e sem defeito muscular. A sonda gástrica passaria normalmente.'),
      ],
    },
  },

  'lesao-de-alca-e-mesenterio': {
    tema: 'Órgãos sólidos',
    titulo: 'Lesão traumática do mesentério e do intestino delgado',
    resumo: 'Contusão mesentérica com densificação e pequenos hematomas, hemoperitônio na pelve, no espaço perirrenal e no recesso de Morison, alça ileal espessada com conteúdo denso, sinal das fezes no delgado e alças proximais dilatadas.',
    protocolo: 'TC de abdome e pelve com contraste, fase portal, axial e coronal',
    series: ['Axial', 'Coronal'],
    rotulos: {
      'dilated stomach': r('Estômago distendido', 'Estômago cheio de líquido.',
        'O estômago distendido acompanha o íleo, a parada do trânsito intestinal causada pelo trauma e pela irritação do peritônio. A sonda nasogástrica alivia e reduz o risco de aspiração. Ele também ajuda a monitorar sangramento digestivo.'),
      'Morison pouch free fluid': r('Líquido no recesso de Morison', 'Líquido entre o fígado e o rim direito.',
        'O recesso de Morison é o ponto mais baixo do abdome superior com o paciente deitado, onde o líquido livre se acumula primeiro. É o local olhado no FAST. Líquido livre sem lesão de órgão sólido levanta a suspeita de lesão de alça ou de mesentério.',
        'Líquido livre sem lesão de fígado ou baço: procure lesão de alça e mesentério.'),
      'small hematomas': r('Pequenos hematomas mesentéricos', 'Coleções densas pequenas no mesentério.',
        'O cinto de segurança e os impactos no abdome rasgam os vasos do mesentério, formando hematomas. Hematomas que crescem ou extravasamento de contraste indicam sangramento ativo e cirurgia ou embolização.'),
      'mesenteric contusion': r('Contusão mesentérica', 'Gordura do mesentério borrada e densificada.',
        'A contusão do mesentério aparece como borramento da gordura em volta dos vasos. Ela pode comprometer o fluxo de sangue para a alça vizinha, que fica isquêmica e pode perfurar dias depois.'),
      'hyperdense fluid': r('Hemoperitônio', 'Líquido livre denso na pelve.',
        'Líquido com densidade acima de 30 UH após trauma é sangue. A quantidade e o local orientam a busca da fonte. O sangue que se acumula perto de uma alça ou do mesentério aponta a origem. Mais denso perto da fonte.'),
      'ileal loop': r('Alça ileal lesada', 'Alça com parede espessada e conteúdo mais denso.',
        'A alça vizinha à contusão tem parede espessada e luz com conteúdo mais denso, sinal de sangue dentro da alça por contusão ou isquemia. Parede sem realce, gás livre ou contraste fora da alça indicariam perfuração e cirurgia imediata.'),
      'dilated small bowel loops': r('Alças de delgado dilatadas', 'Alças proximais cheias de líquido.',
        'As alças antes da lesão se dilatam por íleo ou por uma obstrução em evolução. Esse dado, junto com a dor que piora, pesa a favor da laparotomia exploradora. Elas também podem esconder perfuração, por isso a reavaliação clínica e a TC de controle são importantes.'),
      'small bowel faeces sig': r('Sinal das fezes no delgado', 'Conteúdo com bolhas de gás no delgado, como fezes.',
        'Quando o trânsito fica lento, o conteúdo do delgado se desidrata e fica parecido com fezes, com bolhas de gás. O sinal costuma aparecer logo antes do ponto de obstrução ou de lentidão e ajuda a localizá-lo.'),
    },
    achados: [
      'Contusão mesentérica mal definida na linha média do abdome inferior e da pelve, com densificação da gordura e pequenos hematomas.',
      'Líquido livre hiperdenso na pelve, no espaço perirrenal direito e no recesso de Morison — hemoperitônio.',
      'Alça ileal adjacente com espessamento parietal e conteúdo luminal mais denso, por contusão ou isquemia.',
      'Sinal das fezes no delgado distal; alças proximais dilatadas e cheias de líquido; estômago distendido.',
    ],
    armadilhas: [
      'A TC inicial pode subestimar lesões de alça; repita se a dor piorar.',
      'Ar livre pode ser mínimo ou ausente na perfuração do delgado.',
      'Equimose do cinto de segurança no abdome aumenta muito o risco de lesão de alça.',
    ],
    conduta: 'Observação com exames seriados e reavaliação cirúrgica frequente, sonda nasogástrica e laparotomia se houver peritonite, sangramento ativo, ar livre ou piora clínica.',
    vinheta: {
      cenario: 'Sala de trauma',
      identificacao: 'Mulher de 29 anos, recepcionista.',
      queixa: 'Dor na barriga depois de acidente de carro com cinto.',
      historia: 'Era passageira com cinto de segurança quando o carro bateu de frente. Chegou com dor na parte baixa da barriga, que está piorando, e náuseas. Tem uma marca roxa em faixa no abdome, na altura do cinto.',
      antecedentes: [
        'Pessoais: sem doenças',
        'Gestacionais: nuligesta; beta-hCG negativo',
        'Familiares: sem doenças relevantes',
        'Hábitos: não fuma',
      ],
      vitais: { pa: '108 × 68 mmHg', fc: '108 bpm', fr: '20 irpm', satO2: '98% em ar ambiente', temp: '36,8 °C' },
      exame: [
        'Equimose em faixa no abdome inferior, o sinal do cinto',
        'Dor difusa, maior no hipogástrio, com defesa leve',
        'FAST com líquido no recesso de Morison',
        'Fígado e baço sem lesão aparente no FAST',
      ],
      pedido: 'Sinal do cinto, dor abdominal progressiva e líquido livre sem lesão de órgão sólido: a pergunta é se há lesão de alça ou de mesentério.',
      pergunta: 'TC de abdome com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Lesão traumática de mesentério e alça',
      veredito: 'Contusão mesentérica com hematomas, hemoperitônio e lesão de alça ileal',
      correlacao: 'Na desaceleração, o cinto comprimiu o abdome contra a coluna e rasgou os vasos do mesentério, formando os hematomas e o sangue livre. A alça ileal vizinha ficou contundida e mal irrigada, e o trânsito parou, o que dilata as alças antes dela. A dor que piora e a defesa indicam risco de perfuração.',
      distratores: [
        d('Laceração esplênica com hemoperitônio', 'Causa sangue livre após trauma, mas com laceração no baço e coágulo sentinela junto a ele, e não contusão mesentérica. Aqui o baço está íntegro.'),
        d('Hematoma da bainha do reto', 'Fica na parede abdominal, dentro do músculo reto, sem líquido livre na cavidade nem lesão de alça. Costuma ocorrer em anticoagulados ou após tosse intensa.'),
        d('Íleo adinâmico pós-traumático', 'Dilata as alças após trauma, mas sem hematomas mesentéricos, hemoperitônio nem alça espessada. Ele também melhora em poucos dias sem cirurgia.'),
      ],
    },
  },
}
