import { d, p, r, type ConteudoCaso } from './casos-imagem-tipos'

/** Terceira leva de TC — crânio e tórax. Pacientes fictícios. */
export const CASOS_TC_L3_NEURO_TORAX: Record<string, ConteudoCaso> = {
  'schwannoma-vestibular': {
    tema: 'Tumores',
    titulo: 'Schwannoma vestibular com conduto auditivo alargado',
    resumo: 'Massa lobulada no ângulo pontocerebelar esquerdo com áreas císticas e realce periférico, entrando no conduto auditivo interno alargado em trompete; anomalia venosa do desenvolvimento cerebelar incidental.',
    protocolo: 'TC de crânio sem contraste e com contraste, fase arterial',
    series: ['Com contraste', 'Sem contraste'],
    rotulos: {
      'cystic areas': r('Áreas císticas', 'Regiões sem realce dentro da massa.',
        'Schwannomas maiores degeneram e formam cistos ou áreas de necrose no interior, que não realçam com contraste. Tumores com muitos cistos podem crescer mais rápido e de forma menos previsível, o que pesa na decisão entre observar, operar ou irradiar.'),
      'caput medusae': r('Cabeça de medusa', 'Veias finas convergindo para uma veia coletora no cerebelo.',
        'A anomalia venosa do desenvolvimento é um conjunto de pequenas veias medulares que convergem, como os cabelos da medusa, para uma veia coletora maior. É uma variação benigna, achado incidental, que não deve ser operada, porque drena tecido cerebral normal.',
        'Anomalia venosa nunca deve ser ressecada: sua retirada causa infarto venoso.'),
      'normal contralateral': r('Conduto auditivo direito normal', 'O conduto oposto serve de comparação.',
        'O conduto auditivo interno leva os nervos facial e vestibulococlear do tronco até a orelha interna. Comparar os dois lados mostra a assimetria: o normal tem paredes paralelas e calibre de poucos milímetros, enquanto o do lado do tumor fica alargado.'),
      'trumpeted IAM': r('Conduto auditivo em trompete', 'Abertura do conduto esquerdo alargada como a boca de um trompete.',
        'O schwannoma vestibular nasce dentro do conduto e cresce para fora, para o ângulo pontocerebelar. Ao crescer lentamente, remodela e alarga a abertura do conduto, o poro acústico, que fica em forma de trompete. Esse sinal ajuda a diferenciar do meningioma, que costuma ficar fora do conduto e tem base larga na dura.'),
      'peripheral enhancement': r('Realce periférico', 'A parte sólida realça na periferia da massa.',
        'O schwannoma é formado por células de Schwann e realça intensamente com contraste na parte sólida. Realce heterogêneo com cistos é típico de tumores maiores. A ressonância é o exame de escolha para detectar e acompanhar esses tumores.'),
      'middle cerebellar peduncle': r('Pedúnculo cerebelar médio', 'A massa encosta no pedúnculo que liga a ponte ao cerebelo.',
        'Tumores grandes comprimem o pedúnculo cerebelar médio e o tronco, o que pode causar ataxia e, ao deformar o quarto ventrículo, hidrocefalia. O contato com o tronco define o estágio do tumor e torna a cirurgia mais complexa.'),
      DVA: r('Anomalia venosa no cerebelo', 'Foco denso no hemisfério cerebelar esquerdo, sem contraste.',
        'Sem contraste, a anomalia venosa pode aparecer como um foco discretamente denso. Com contraste, revela o padrão em cabeça de medusa. É importante não confundi-la com sangramento ou tumor.'),
      'left CPA mass': r('Massa no ângulo pontocerebelar', 'Massa hipodensa lobulada entre a ponte, o cerebelo e o osso temporal.',
        'O ângulo pontocerebelar é o espaço entre a ponte, o cerebelo e a face posterior do osso temporal. O schwannoma vestibular é o tumor mais comum desse local, seguido pelo meningioma. Ele nasce do nervo vestibular e por isso começa com perda auditiva e zumbido de um lado.'),
    },
    achados: [
      'Massa lobulada hipoatenuante no ângulo pontocerebelar esquerdo com realce periférico heterogêneo e áreas císticas sem realce.',
      'Extensão para o conduto auditivo interno esquerdo, cujo poro está alargado em trompete em relação ao lado direito.',
      'Contato com o pedúnculo cerebelar médio.',
      'Anomalia venosa do desenvolvimento no hemisfério cerebelar esquerdo, incidental.',
    ],
    armadilhas: [
      'TC sem contraste pode não mostrar tumores pequenos dentro do conduto: a ressonância é o exame de escolha.',
      'Meningioma do ângulo tem base larga na dura, calcificações e não costuma alargar o conduto.',
      'Schwannoma vestibular bilateral sugere neurofibromatose tipo 2.',
    ],
    conduta: 'Ressonância com gadolínio, audiometria e decisão compartilhada entre observação com imagens seriadas, radiocirurgia ou microcirurgia conforme tamanho, crescimento e audição.',
    vinheta: {
      cenario: 'Ambulatório de otorrinolaringologia',
      identificacao: 'Mulher de 52 anos, professora de música.',
      queixa: 'Perda de audição no ouvido esquerdo e zumbido há dois anos.',
      historia: 'Há dois anos percebeu que não ouve bem o telefone no ouvido esquerdo e tem zumbido contínuo desse lado. Nos últimos meses tem desequilíbrio ao andar no escuro e sente a face esquerda formigando às vezes. Nega dor de ouvido e secreção.',
      antecedentes: [
        'Pessoais: hipertensão controlada',
        'Pessoais: sem cirurgias otológicas',
        'Familiares: sem tumores cerebrais conhecidos',
        'Hábitos: não fuma',
      ],
      vitais: { pa: '132 × 82 mmHg', fc: '74 bpm', fr: '14 irpm', satO2: '98% em ar ambiente', temp: '36,5 °C' },
      exame: [
        'Teste de Weber lateralizado para a direita',
        'Rinne positivo bilateral',
        'Reflexo corneano diminuído à esquerda',
        'Marcha com base levemente alargada',
      ],
      pedido: 'Perda auditiva neurossensorial unilateral progressiva com zumbido e reflexo corneano reduzido: a pergunta é se há lesão no ângulo pontocerebelar.',
      pergunta: 'TC de crânio com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Schwannoma vestibular esquerdo',
      veredito: 'Schwannoma vestibular esquerdo com alargamento do conduto auditivo interno',
      correlacao: 'Perda auditiva neurossensorial unilateral e progressiva com zumbido é schwannoma vestibular até prova em contrário. O tumor nasceu no nervo vestibular, dentro do conduto, alargou-o e cresceu para o ângulo, onde passou a tocar o nervo trigêmeo, por isso a face formiga e o reflexo corneano caiu, e o pedúnculo cerebelar, o que explica o desequilíbrio.',
      distratores: [
        d('Meningioma do ângulo pontocerebelar', 'Também ocupa o ângulo, mas tem base larga na dura, calcificações frequentes e cauda dural, e não costuma alargar o conduto em trompete.'),
        d('Doença de Ménière unilateral', 'Causa perda auditiva flutuante com crises de vertigem rotatória de horas e plenitude auricular, com TC normal. A audiometria flutua entre as crises, ao contrário da perda progressiva do schwannoma.'),
        d('Cisto epidermoide do ângulo', 'Ocupa o ângulo e se insinua entre os nervos, mas tem densidade de líquor, sem realce, e não alarga o conduto. A ressonância mostra restrição à difusão, que o separa do cisto aracnoide e do schwannoma.'),
      ],
    },
  },

  'trombose-da-basilar': {
    tema: 'Vascular',
    titulo: 'Oclusão da artéria basilar com infartos da circulação posterior',
    resumo: 'Artéria basilar hiperdensa por trombo, com infartos na ponte, nos hemisférios cerebelares, no lobo temporal medial esquerdo e no lobo occipital direito.',
    protocolo: 'TC de crânio sem contraste em dois momentos',
    series: ['Controle', 'Admissão'],
    rotulos: {
      'pons infarct': r('Infarto na ponte', 'Área hipodensa na ponte direita.',
        'A ponte recebe ramos perfurantes da artéria basilar. Quando a basilar fecha, a ponte sofre infarto, e o paciente pode ter tetraparesia, alteração dos movimentos oculares e, nos casos mais graves, síndrome do encarceramento, em que fica acordado mas só consegue mexer os olhos.'),
      'right cerebellar infarct': r('Infarto cerebelar direito', 'Hipodensidade no hemisfério cerebelar superior direito.',
        'A artéria cerebelar superior nasce do topo da basilar e irriga a parte de cima do cerebelo. Seu infarto causa ataxia do mesmo lado, vertigem e fala arrastada. Infartos cerebelares grandes incham e podem comprimir o quarto ventrículo.'),
      'left cerebellar infarct': r('Infarto cerebelar esquerdo', 'Hipodensidade também no cerebelo superior esquerdo.',
        'Infartos nos dois hemisférios cerebelares, ao mesmo tempo, apontam para a basilar, a artéria que alimenta os dois lados. Um infarto de um lado só sugeriria oclusão de uma vertebral ou de um ramo isolado.'),
      'left temporal infarct': r('Infarto temporal medial esquerdo', 'Hipodensidade na face medial do lobo temporal esquerdo.',
        'As artérias cerebrais posteriores nascem do topo da basilar e irrigam o lobo occipital e a face medial do temporal, incluindo o hipocampo. O infarto temporal medial pode causar perda de memória recente.'),
      'right occipital infarct': r('Infarto occipital direito', 'Hipodensidade no lobo occipital direito.',
        'O lobo occipital é o córtex visual. Seu infarto causa perda do campo visual do lado oposto, a hemianopsia. Infartos em vários territórios da circulação posterior, ao mesmo tempo, são a assinatura da síndrome do topo da basilar.'),
      'Hyperdense basilar artery': r('Artéria basilar hiperdensa', 'A basilar aparece mais branca que o normal na TC sem contraste.',
        'Sangue coagulado é mais denso que o sangue que corre. Por isso, um trombo dentro da artéria deixa o vaso mais branco na TC sem contraste. É o equivalente, na circulação posterior, do sinal da artéria cerebral média hiperdensa. Na admissão, o trombo aparece antes de qualquer infarto estabelecido.',
        'Coma ou tetraparesia súbitos com basilar densa: angiotomografia imediata e trombectomia.'),
    },
    achados: [
      'Na admissão, artéria basilar hiperdensa, sugerindo trombose, ainda sem infarto estabelecido na circulação posterior.',
      'No controle, infartos na ponte direita, nos hemisférios cerebelares superiores e no lobo temporal medial esquerdo e occipital direito.',
      'Oclusão da artéria cerebelar superior direita.',
      'Sem transformação hemorrágica.',
    ],
    armadilhas: [
      'Hematócrito alto e calcificação da parede também deixam a basilar densa: compare com outros vasos.',
      'Sintomas flutuantes, como tontura e diplopia, precedem a oclusão completa e são desvalorizados.',
      'A TC inicial costuma ser normal no parênquima: o diagnóstico é vascular.',
    ],
    conduta: 'Angiotomografia imediata, trombólise venosa dentro da janela e trombectomia mecânica, que na basilar pode ser feita em janela mais longa; cuidados intensivos e prevenção secundária conforme a causa.',
    vinheta: {
      cenario: 'Sala de emergência',
      identificacao: 'Homem de 67 anos, aposentado.',
      queixa: 'Tontura, visão dupla e fala enrolada que começaram há três horas e pioraram.',
      historia: 'Há três horas sentiu tontura intensa e passou a ver dobrado. Em seguida, a fala ficou enrolada e as pernas fraquejaram. Ontem teve um episódio de tontura que passou em minutos. A família notou que ele está cada vez mais sonolento.',
      antecedentes: [
        'Pessoais: hipertensão, diabetes e fibrilação atrial sem anticoagulação',
        'Pessoais: dislipidemia',
        'Familiares: pai com AVC aos 70 anos',
        'Hábitos: ex-tabagista',
      ],
      vitais: { pa: '186 × 98 mmHg', fc: '112 bpm irregular', fr: '18 irpm', satO2: '95% em ar ambiente', temp: '36,7 °C' },
      exame: [
        'Sonolento, desperta ao chamado',
        'Oftalmoparesia internuclear e nistagmo vertical',
        'Disartria e ataxia dos quatro membros',
        'Glicemia de 168 mg/dL',
      ],
      pedido: 'Déficits de tronco e cerebelo súbitos e progressivos com rebaixamento em paciente com fibrilação atrial sem anticoagulação: a pergunta é se há oclusão na circulação posterior.',
      pergunta: 'TC de crânio sem contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Trombose da artéria basilar',
      veredito: 'Oclusão da artéria basilar com infartos do tronco, do cerebelo e dos territórios posteriores',
      correlacao: 'A fibrilação atrial sem anticoagulação formou um trombo no coração que embolizou para a basilar. A tontura de ontem foi um aviso. Com a basilar fechada, sofrem a ponte, o cerebelo e os territórios das cerebrais posteriores, o que explica a diplopia, a disartria, a ataxia e o rebaixamento.',
      distratores: [
        d('Hemorragia pontina hipertensiva', 'Também causa déficits de tronco e coma, mas aparece como sangue branco na ponte na TC, e não como artéria densa com infartos escuros.'),
        d('Neurite vestibular aguda', 'Causa vertigem intensa com nistagmo horizontal, mas sem diplopia, disartria nem fraqueza, com exame neurológico e TC normais.'),
        d('Infarto lacunar talâmico', 'É um infarto pequeno de uma perfurante, com déficit sensitivo puro, sem envolver ponte, cerebelo e lobos posteriores ao mesmo tempo.'),
      ],
    },
  },

  'cisto-aracnoide': {
    tema: 'Líquor e hidrocefalia',
    titulo: 'Cisto aracnoide temporal roto com higroma e hematomas subdurais',
    resumo: 'Grande cisto aracnoide temporal esquerdo com higroma subdural do mesmo lado, pequenos hematomas subdurais agudos frontal e parietal à direita, desvio da linha média e afilamento da díploe.',
    protocolo: 'TC de crânio sem contraste, janelas de parênquima e óssea',
    series: ['Parênquima', 'Janela óssea'],
    rotulos: {
      'small frontal subdural hematom': r('Hematoma subdural frontal direito', 'Pequena coleção densa em crescente na região frontal direita.',
        'Hematoma subdural agudo é sangue entre a dura e a aracnoide, por ruptura de veias ponte. Ele aparece denso e em crescente, cruzando as suturas. Aqui está do lado oposto ao cisto, o que sugere um trauma em contragolpe ou uma mudança brusca de pressão quando o cisto se rompeu.'),
      'large arachnoid cyst': r('Grande cisto aracnoide', 'Coleção com densidade de líquor na fossa média esquerda.',
        'O cisto aracnoide é uma bolsa de líquor envolvida por aracnoide, congênita, mais comum na fossa média, junto ao lobo temporal. Costuma ser assintomático e achado de exame. Cistos grandes podem remodelar o osso e, raramente, se romper com traumas leves.',
        'Cisto aracnoide em jovem com cefaleia após trauma leve: procure higroma ou hematoma associado.'),
      'ispilateral subdural hygroma': r('Higroma subdural do mesmo lado', 'Coleção de líquor no espaço subdural sobre o hemisfério esquerdo.',
        'Higroma é líquor acumulado no espaço subdural. Quando o cisto aracnoide se rompe, o líquor sai para esse espaço e forma o higroma. A coleção tem densidade de água e pode comprimir o cérebro e desviar a linha média.'),
      'small parietal subdural hemato': r('Hematoma subdural parietal direito', 'Outra pequena coleção densa, parietal à direita.',
        'Dois focos de sangue subdural do lado oposto mostram que o trauma ou a mudança de pressão rompeu veias ponte em mais de um ponto. Hematomas pequenos costumam ser tratados de forma conservadora, com TC de controle.'),
      'diploe thinning': r('Afilamento da díploe', 'Osso temporal fino e abaulado sobre o cisto.',
        'A díploe é o osso esponjoso entre as duas tábuas do crânio. A pressão de um cisto que existe desde a infância remodela o osso, que fica fino e abaulado. Esse sinal indica que o cisto é antigo e de crescimento lento.'),
    },
    achados: [
      'Grande cisto aracnoide na fossa média esquerda.',
      'Higroma subdural esquerdo, sugerindo ruptura do cisto.',
      'Pequenos hematomas subdurais agudos frontal e parietal à direita.',
      'Leve desvio da linha média para a direita; afilamento da díploe temporal esquerda.',
    ],
    armadilhas: [
      'Cisto aracnoide não realça nem tem restrição à difusão; cisto epidermoide restringe.',
      'Higroma crônico pode ser confundido com hematoma subdural crônico hipodenso.',
      'Atrofia com espaço liquórico alargado não desloca o cérebro, ao contrário do higroma.',
    ],
    conduta: 'Observação neurológica, TC de controle, tratamento cirúrgico se houver piora do higroma ou do hematoma com efeito de massa, e orientação sobre esportes de contato.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Rapaz de 17 anos, jogador de futebol.',
      queixa: 'Dor de cabeça forte há quatro dias depois de uma cabeçada no jogo.',
      historia: 'Há quatro dias deu uma cabeçada em um adversário durante uma partida, sem perder a consciência. Desde então tem dor de cabeça que piora ao deitar e ao fazer esforço, com náuseas. Hoje vomitou duas vezes e está mais sonolento.',
      antecedentes: [
        'Pessoais: sem doenças',
        'Pessoais: nunca fez exame de imagem do crânio',
        'Familiares: sem doenças neurológicas',
        'Hábitos: treina futebol diariamente',
      ],
      vitais: { pa: '128 × 76 mmHg', fc: '64 bpm', fr: '16 irpm', satO2: '99% em ar ambiente', temp: '36,6 °C' },
      exame: [
        'Sonolento, desperta e conversa',
        'Papiledema discreto ao fundo de olho',
        'Sem déficit motor',
        'Coagulação normal',
      ],
      pedido: 'Cefaleia progressiva com vômitos e sonolência dias após trauma craniano leve em adolescente: a pergunta é se há coleção intracraniana.',
      pergunta: 'TC de crânio sem contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Cisto aracnoide roto com higroma',
      veredito: 'Ruptura de cisto aracnoide temporal com higroma subdural e pequenos hematomas subdurais contralaterais',
      correlacao: 'O cisto aracnoide existia desde a infância, sem sintomas, e afinou o osso. A cabeçada rompeu sua parede, e o líquor saiu para o espaço subdural, formando o higroma que comprime o hemisfério, e veias ponte do outro lado sangraram. O aumento de pressão explica a cefaleia ao deitar, os vômitos e o papiledema.',
      distratores: [
        d('Hematoma extradural temporal', 'Também ocorre após trauma, mas é sangue denso em forma de lente biconvexa, por lesão da artéria meníngea, geralmente com fratura.'),
        d('Concussão cerebral sem lesão estrutural', 'Causa cefaleia e náuseas após trauma, mas a TC é normal e os sintomas não pioram com papiledema dias depois. Aqui a TC mostra coleções e desvio da linha média.'),
        d('Cisto epidermoide da fossa média', 'Tem densidade parecida com líquor, mas se insinua entre estruturas, restringe à difusão e não se rompe formando higroma. Também não explica o higroma subdural.'),
      ],
    },
  },

  'empiema-subdural': {
    tema: 'Infecção',
    titulo: 'Empiema subdural da fossa posterior por mastoidite',
    resumo: 'Coleções subdurais entre o cerebelo e o tentório, cruzando a linha média, com opacificação da mastoide e da orelha média esquerdas e defeito ósseo para a fossa posterior.',
    protocolo: 'TC de crânio sem contraste, axial e coronal',
    series: ['Axial', 'Coronal'],
    rotulos: {
      'subdural collections': r('Coleções subdurais na fossa posterior', 'Coleções finas junto à superfície do cerebelo.',
        'O empiema subdural é pus no espaço entre a dura e a aracnoide. Na fossa posterior, ele vem quase sempre de infecção da orelha média e da mastoide, que fica colada à fossa posterior. O pus se espalha rápido pelo espaço subdural, que não tem barreiras, e pode causar trombose venosa, cerebelite e hidrocefalia. É uma emergência neurocirúrgica.',
        'Otite crônica com febre, cefaleia e sinais cerebelares: pense em complicação intracraniana.'),
      collections: r('Coleções sob o tentório', 'No coronal, coleções entre o cerebelo e o tentório, cruzando a linha média.',
        'O plano coronal mostra que as coleções ficam no espaço subdural, entre o cerebelo e o tentório, e cruzam a linha média, o que as separa do abscesso cerebelar, que fica dentro do tecido. A ressonância com difusão confirma o pus pela restrição à difusão.'),
    },
    apontamentosProprios: [
      { ...p(0, 0.80, 0.55, 0, 'Mastoide esquerda opacificada', 'Células da mastoide esquerda cheias, sem ar.',
        'As células da mastoide normalmente são cheias de ar e aparecem pretas na TC. Na mastoidite, elas se enchem de pus e tecido inflamatório e ficam opacas. A mastoide é separada da fossa posterior por uma placa fina de osso, que a infecção pode erodir, abrindo caminho para o espaço subdural.',
        'Mastoide opaca de um lado com coleção na fossa posterior do mesmo lado: a fonte é a orelha.'), corte: 27 },
      { ...p(0, 0.15, 0.55, 180, 'Mastoide direita aerada', 'As células da mastoide direita, cheias de ar, servem de comparação.',
        'Comparar os dois lados é o modo mais rápido de perceber a mastoide doente. Do lado normal, as células ficam pretas e separadas por septos finos; do lado da infecção, desaparecem na opacidade.'), corte: 27 },
    ],
    achados: [
      'Opacificação parcial da orelha média e da mastoide esquerdas, com defeito ósseo para a fossa posterior.',
      'Coleções subdurais entre o cerebelo e o tentório, cruzando a linha média e envolvendo a superfície dorsal do cerebelo, com extensão ao forame magno.',
      'Pouco realce perceptível; sem pneumoencéfalo.',
      'Redução volumétrica difusa leve; seios paranasais anteriores parcialmente opacificados.',
    ],
    armadilhas: [
      'Coleções subdurais pequenas podem passar despercebidas na TC: a ressonância com difusão é mais sensível.',
      'Procure trombose do seio sigmoide, complicação frequente da mastoidite.',
      'Antibiótico prévio pode mascarar a febre.',
    ],
    conduta: 'Ressonância com difusão e venografia, antibiótico venoso de amplo espectro com boa penetração no sistema nervoso, drenagem neurocirúrgica e mastoidectomia para tratar o foco.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Homem de 71 anos, aposentado.',
      queixa: 'Dor de cabeça forte, febre e desequilíbrio há cinco dias.',
      historia: 'Tem secreção no ouvido esquerdo há meses, tratada com gotas. Há cinco dias começou com dor de cabeça na nuca, febre e vômitos. Hoje não consegue andar sem apoio e está confuso, segundo a filha.',
      antecedentes: [
        'Pessoais: otite média crônica à esquerda',
        'Pessoais: diabetes tipo 2',
        'Familiares: sem doenças relevantes',
        'Hábitos: ex-etilista',
      ],
      vitais: { pa: '146 × 84 mmHg', fc: '108 bpm', fr: '20 irpm', satO2: '96% em ar ambiente', temp: '38,9 °C' },
      exame: [
        'Otorreia purulenta à esquerda',
        'Rigidez de nuca',
        'Dismetria e ataxia de marcha',
        'Leucocitose de 19.000 e PCR elevada',
      ],
      pedido: 'Febre, cefaleia, sinais cerebelares e confusão em idoso com otite crônica: a pergunta é se há complicação intracraniana.',
      pergunta: 'TC de crânio sem contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Empiema subdural da fossa posterior',
      veredito: 'Empiemas subdurais da fossa posterior por mastoidite com erosão óssea',
      correlacao: 'A otite crônica estendeu a infecção à mastoide, que erodiu o osso e abriu caminho para a fossa posterior. O pus se espalhou no espaço subdural sob o tentório, irritando as meninges e o cerebelo, o que explica a rigidez de nuca, a ataxia e a confusão. O diabetes favorece a infecção grave.',
      distratores: [
        d('Abscesso cerebelar', 'Também vem da mastoidite, mas é uma cavidade dentro do cerebelo com cápsula que realça, e não coleção no espaço subdural cruzando a linha média.'),
        d('Meningite bacteriana sem coleção', 'Dá febre, cefaleia e rigidez de nuca, mas a TC não mostra coleções e não há sinais cerebelares focais. A punção lombar seria o próximo passo, mas está contraindicada quando há coleção com efeito de massa.'),
        d('Infarto cerebelar com edema', 'Causa ataxia e vômitos súbitos, sem febre nem otorreia, com área hipodensa dentro do cerebelo. Também não haveria mastoidite nem defeito ósseo na fossa posterior.'),
      ],
    },
  },

  'abscesso-pulmonar': {
    tema: 'Infecção',
    titulo: 'Abscesso pulmonar no lobo superior direito',
    resumo: 'Grande consolidação no segmento anterior do lobo superior direito com escavação central, líquido pendente e ar, vidro fosco multifocal, linfonodos e consolidação subsegmentar à esquerda.',
    protocolo: 'TC de tórax com contraste, janelas de mediastino e pulmão',
    series: ['Mediastino', 'Pulmão'],
    rotulos: {
      'large area of consolidation w': r('Consolidação com escavação central', 'Consolidação grande com centro necrótico, líquido embaixo e ar em cima.',
        'O abscesso pulmonar é a necrose do pulmão infectado formando uma cavidade cheia de pus. Quando ele se comunica com um brônquio, parte do pus sai pela tosse e entra ar: forma-se um nível líquido. As bactérias anaeróbias da boca, aspiradas durante perda de consciência, são as principais causas. Parede espessa e irregular, com consolidação em volta, sugere abscesso; parede fina, empiema ou cisto infectado.',
        'Nível hidroaéreo que encosta na parede torácica em ângulo agudo é abscesso; em ângulo obtuso, empiema.'),
      'lateral basal segment of left': r('Consolidação basal lateral esquerda', 'Pequena consolidação subsegmentar no lobo inferior esquerdo.',
        'Focos pequenos em outros segmentos indicam que houve aspiração ou disseminação brônquica para mais de uma área. Eles devem ser acompanhados, porque também podem evoluir para necrose se o tratamento não for eficaz.'),
    },
    achados: [
      'Consolidação extensa no segmento anterior do lobo superior direito com escavação central, líquido pendente e ar não pendente — abscesso pulmonar.',
      'Opacidades em vidro fosco multifocais no lobo superior e no lobo inferior direitos.',
      'Consolidação subsegmentar no segmento basal lateral do lobo inferior esquerdo.',
      'Linfonodos hilares e paratraqueais direitos aumentados; pequeno derrame bilateral; hérnia de hiato.',
    ],
    armadilhas: [
      'Carcinoma escavado imita abscesso: parede muito espessa e nodular, ou falta de resposta, pedem broncoscopia.',
      'Tuberculose cavitária prefere segmentos apicais e posteriores, com nódulos em árvore em brotamento.',
      'Empiema com fístula broncopleural também forma nível hidroaéreo, mas na pleura.',
    ],
    conduta: 'Antibiótico com cobertura para anaeróbios por semanas, fisioterapia e drenagem postural, investigação de tuberculose e de câncer, e drenagem percutânea ou cirurgia se não houver resposta.',
    vinheta: {
      cenario: 'Enfermaria de clínica médica',
      identificacao: 'Homem de 54 anos, pedreiro.',
      queixa: 'Tosse com catarro fétido e febre há três semanas.',
      historia: 'Há três semanas começou com febre, calafrios e tosse que passou a trazer grande quantidade de catarro com cheiro muito ruim. Perdeu 5 kg. Bebe muito e há um mês acordou no chão depois de uma bebedeira, sem lembrar do que aconteceu.',
      antecedentes: [
        'Pessoais: etilismo pesado',
        'Pessoais: dentes em mau estado, sem acompanhamento',
        'Familiares: sem tuberculose conhecida',
        'Hábitos: tabagista de 30 maços-ano',
      ],
      vitais: { pa: '118 × 72 mmHg', fc: '104 bpm', fr: '24 irpm', satO2: '93% em ar ambiente', temp: '38,6 °C' },
      exame: [
        'Hálito fétido e gengivite',
        'Macicez e sopro anfórico no terço superior direito',
        'Baqueteamento digital discreto',
        'Pesquisa de BAAR no escarro negativa',
      ],
      pedido: 'Tosse com escarro pútrido, febre e perda de peso em etilista com perda de consciência e má dentição: a pergunta é se há cavitação.',
      pergunta: 'TC de tórax com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Abscesso pulmonar escavado',
      veredito: 'Abscesso pulmonar do lobo superior direito com nível hidroaéreo',
      correlacao: 'Durante a perda de consciência pelo álcool, ele aspirou secreção da boca cheia de bactérias anaeróbias por causa dos dentes ruins. O pulmão infectado necrosou e formou uma cavidade de pus, que drena para os brônquios e explica o catarro fétido em grande volume. O nível líquido dentro da consolidação é a marca do abscesso.',
      distratores: [
        d('Tuberculose pulmonar cavitária', 'Também cava e dá febre com emagrecimento, mas prefere segmentos apicais e posteriores, com nódulos em árvore em brotamento e BAAR positivo.'),
        d('Carcinoma epidermoide escavado', 'Forma cavidade de parede grossa e irregular em fumante, mas sem febre alta nem escarro pútrido, e não responde a antibiótico. A broncoscopia separa.'),
        d('Empiema pleural loculado', 'É pus na pleura, em forma de lente encostada na parede, com o pulmão comprimido, e não uma cavidade dentro do pulmão. O ângulo com a parede é obtuso e as pleuras se afastam, formando o sinal da pleura dividida.'),
      ],
    },
  },

  'fistula-esofagopericardica': {
    tema: 'Pleura e mediastino',
    titulo: 'Fístula esofagopericárdica por câncer de esôfago',
    resumo: 'Defeito na parede anterior do esôfago distal comunicando com o pericárdio, com ar no pericárdio, derrame pericárdico com realce e massa esofágica distal.',
    protocolo: 'TC de tórax com contraste, protocolo de embolia e fase arterial',
    series: ['Angiotomografia', 'Fase arterial'],
    rotulos: {
      'Pericardial enhancement': r('Realce do pericárdio', 'Pericárdio espessado e realçado em volta do derrame.',
        'O pericárdio inflamado ou invadido por tumor realça com contraste. Junto com o derrame, o realce indica pericardite, aqui por infecção e invasão tumoral. Derrame volumoso pode comprimir o coração e levar ao tamponamento.'),
      'Esophageal defect': r('Defeito na parede do esôfago', 'Falha na parede anterior do esôfago distal.',
        'O câncer de esôfago cresce através da parede e invade estruturas vizinhas. Quando necrosa ou após radioterapia, abre uma comunicação, a fístula. A face anterior do esôfago distal encosta no pericárdio e no átrio esquerdo, por isso a fístula pode chegar ao pericárdio.'),
      'Pericardial air': r('Ar no pericárdio', 'Bolhas de gás dentro do saco pericárdico.',
        'Ar no pericárdio sem cirurgia ou trauma recente prova que há comunicação com uma víscera que contém ar. É o sinal que confirma a fístula. A contaminação pela flora do esôfago causa pericardite purulenta, de altíssima mortalidade.',
        'Pneumopericárdio espontâneo em paciente com câncer de esôfago: fístula até prova em contrário.'),
      'Soft tissue mass': r('Massa do esôfago distal', 'Massa irregular no esôfago distal até a junção com o estômago.',
        'O adenocarcinoma do esôfago distal se associa a refluxo crônico e esôfago de Barrett. Ele espessa a parede de forma assimétrica e estreita a luz, o que causa disfagia progressiva, primeiro para sólidos e depois para líquidos.'),
      'Wall thickening': r('Espessamento da parede esofágica', 'Parede do esôfago espessada em 10 cm.',
        'A parede normal do esôfago tem até 3 a 5 mm. Espessamento longo e irregular com perda dos planos de gordura em volta sugere tumor invadindo o mediastino. A TC estadia o tumor mostrando invasão de estruturas e metástases.'),
    },
    achados: [
      'Defeito novo na face anterior do esôfago torácico distal comunicando com o espaço pericárdico, com ar no pericárdio — fístula esofagopericárdica.',
      'Derrame pericárdico moderado a volumoso com realce pericárdico leve, compatível com derrame maligno e infectado.',
      'Massa de partes moles irregular e espessamento parietal dos 10 cm distais do esôfago até a transição esofagogástrica.',
    ],
    armadilhas: [
      'O pneumopericárdio pode ser confundido com pneumomediastino: o ar no pericárdio contorna o coração e para nas grandes artérias.',
      'Fístula com o átrio esquerdo causa embolia gasosa e hemorragia maciça.',
      'Não dê contraste baritado na suspeita de fístula.',
    ],
    conduta: 'Jejum, antibiótico de amplo espectro, drenagem pericárdica, prótese esofágica coberta para selar a fístula e discussão de cuidados paliativos conforme o estado do tumor.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Homem de 63 anos, motorista aposentado.',
      queixa: 'Dor no peito que piora ao deitar, febre e falta de ar há dois dias.',
      historia: 'Está em tratamento de câncer de esôfago com quimioterapia e radioterapia. Há dois dias começou com dor no peito que melhora ao sentar para a frente, febre e falta de ar. A dor piora ao engolir.',
      antecedentes: [
        'Pessoais: adenocarcinoma de esôfago distal em quimiorradioterapia',
        'Pessoais: refluxo de longa data e esôfago de Barrett',
        'Familiares: pai com câncer de estômago',
        'Hábitos: ex-tabagista e obeso',
      ],
      vitais: { pa: '94 × 62 mmHg', fc: '128 bpm', fr: '28 irpm', satO2: '90% em ar ambiente', temp: '39,0 °C' },
      exame: [
        'Bulhas abafadas',
        'Atrito pericárdico com som metálico',
        'Turgência jugular e pulso paradoxal',
        'Leucocitose de 22.000',
      ],
      pedido: 'Dor pleurítica que melhora sentado, febre, bulhas abafadas e sinais de tamponamento em paciente com câncer de esôfago irradiado: a pergunta é a causa da pericardite.',
      pergunta: 'TC de tórax com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Fístula do esôfago para o pericárdio',
      veredito: 'Fístula esofagopericárdica por câncer de esôfago com pneumopericárdio e pericardite',
      correlacao: 'O tumor do esôfago distal, encostado no pericárdio e enfraquecido pela radioterapia, necrosou e abriu uma passagem para o saco pericárdico. Ar e bactérias da boca entraram no pericárdio, o que causou a pericardite purulenta com febre e o derrame que abafa as bulhas e ameaça tamponar o coração. O som metálico do atrito vem do ar.',
      distratores: [
        d('Pericardite viral aguda', 'Também dói melhorando ao sentar, com atrito e derrame, mas em pessoa sem câncer, sem ar no pericárdio e sem febre tão alta. Ela também não forma ar no pericárdio.'),
        d('Perfuração esofágica para o mediastino', 'Deixa ar e líquido no mediastino, mas o ar fica entre as estruturas do mediastino, e não dentro do pericárdio em volta do coração.'),
        d('Derrame pericárdico maligno sem fístula', 'Também pode tamponar o coração em paciente com câncer, mas não traz ar ao pericárdio nem defeito na parede do esôfago. Também não explicaria a febre alta e a sepse.'),
      ],
    },
  },

  'sindrome-da-veia-cava-superior': {
    tema: 'Vascular',
    titulo: 'Síndrome da veia cava superior por linfoma mediastinal',
    resumo: 'Grande massa no mediastino superior comprimindo a veia cava superior até a ázigo, refluxo de contraste para a jugular esquerda e a subclávia direita, jugular direita sem contraste e pequeno derrame direito.',
    protocolo: 'TC de tórax com contraste, fase arterial, janelas de mediastino e pulmão',
    series: ['Mediastino', 'Pulmão'],
    rotulos: {
      'unopacified right IJV': r('Jugular interna direita sem contraste', 'A jugular direita não recebe contraste por causa da obstrução.',
        'Com a veia cava superior obstruída, o sangue da cabeça não consegue descer e o fluxo fica lento ou parado em algumas veias. A jugular sem contraste pode estar trombosada ou só com fluxo estagnado, e isso precisa ser esclarecido antes de puncionar acessos venosos.'),
      'opacified left IJV': r('Refluxo para a jugular esquerda', 'O contraste injetado no braço sobe pela jugular esquerda.',
        'Normalmente o contraste injetado no braço desce direto para a cava. Quando ela está fechada, o contraste reflui para as veias do pescoço, buscando outro caminho. Esse refluxo é um sinal indireto de obstrução venosa central.'),
      'right subclavian vein': r('Refluxo para a subclávia direita', 'Contraste voltando pela veia subclávia direita.',
        'O refluxo para várias veias do pescoço e do braço mostra que o sangue procura colaterais. Com o tempo, abrem-se veias na parede do tórax, visíveis na pele como uma rede de vasos dilatados.'),
      'large soft tissue mass': r('Grande massa no mediastino superior', 'Massa de 5,8 cm envolvendo os vasos do mediastino.',
        'Os linfomas e o câncer de pulmão de pequenas células são as principais causas malignas de síndrome da veia cava superior. Massa grande e homogênea no mediastino anterior e superior de um adulto jovem sugere linfoma, que costuma envolver os vasos sem invadi-los profundamente e responde muito bem ao tratamento.',
        'Faça a biópsia antes do corticoide: ele pode desfazer o linfoma e impedir o diagnóstico.'),
      SVC: r('Veia cava superior comprimida', 'A cava aparece estreitada, quase sem contraste.',
        'A veia cava superior tem parede fina e pressão baixa, por isso é facilmente comprimida por massas do mediastino. A obstrução causa inchaço do rosto, do pescoço e dos braços, pior ao deitar, e dilatação das veias do pescoço.'),
      'azygous vein': r('Extensão para a ázigo', 'A obstrução se estende da cava para a veia ázigo.',
        'A veia ázigo é a principal via colateral quando a cava superior fecha acima de sua entrada. Se a obstrução atinge também a ázigo, o sangue precisa de caminhos mais longos, como as veias da parede torácica e as veias do abdome, e os sintomas ficam mais intensos.'),
      'small right pleural effusion': r('Pequeno derrame pleural direito', 'Derrame pequeno com atelectasia adjacente.',
        'O derrame pode resultar do aumento da pressão venosa e da obstrução linfática pela massa. Ele contribui para a falta de ar e, se crescer, pode ser puncionado e analisado. Ele também pode ser usado para o diagnóstico citológico.'),
    },
    achados: [
      'Grande massa de partes moles no mediastino superior, de 5,8 × 3,6 × 4,3 cm.',
      'Compressão e obstrução quase completa da veia cava superior, estendendo-se à veia ázigo; efeito de massa sobre a carina.',
      'Refluxo de contraste para a jugular interna esquerda e a subclávia direita; jugular interna direita sem contraste.',
      'Edema subcutâneo no pescoço; pequeno derrame pleural direito com atelectasia.',
    ],
    armadilhas: [
      'Refluxo de contraste para veias do pescoço também ocorre com manobra de Valsalva; confirme a estenose.',
      'Estridor e edema cerebral indicam síndrome grave, que exige tratamento urgente.',
      'Cateteres e marca-passos também causam trombose da cava.',
    ],
    conduta: 'Cabeceira elevada, biópsia da massa antes de corticoide, tratamento específico do linfoma e stent venoso nos casos graves ou refratários.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Mulher de 28 anos, designer.',
      queixa: 'Rosto e pescoço inchados e falta de ar ao deitar há duas semanas.',
      historia: 'Há dois meses tem suores à noite, coceira no corpo e perdeu 7 kg. Há duas semanas o rosto e o pescoço incharam, principalmente pela manhã, e ela sente a cabeça pesada ao se abaixar. Não consegue dormir deitada por falta de ar.',
      antecedentes: [
        'Pessoais: sem doenças',
        'Gestacionais: nuligesta',
        'Familiares: sem câncer conhecido',
        'Hábitos: não fuma',
      ],
      vitais: { pa: '124 × 78 mmHg', fc: '104 bpm', fr: '24 irpm', satO2: '95% em ar ambiente', temp: '37,8 °C' },
      exame: [
        'Edema de face, pescoço e braço direito',
        'Veias dilatadas na parede anterior do tórax',
        'Linfonodo supraclavicular direito endurecido',
        'Sem estridor',
      ],
      pedido: 'Edema de face e pescoço com circulação colateral no tórax e sintomas B em jovem: a pergunta é a causa da obstrução venosa.',
      pergunta: 'TC de tórax com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Compressão da cava por massa',
      veredito: 'Síndrome da veia cava superior por massa mediastinal, provável linfoma',
      correlacao: 'Febre baixa, suores noturnos, prurido e emagrecimento são sintomas B de linfoma. A massa no mediastino superior comprimiu a veia cava, por isso o sangue da cabeça e dos braços não desce: o rosto e o pescoço incham, pior ao deitar, e abrem-se veias colaterais na parede do tórax.',
      distratores: [
        d('Trombose venosa por cateter central', 'Também obstrui a cava, mas em paciente com cateter ou marca-passo, sem massa no mediastino nem sintomas B. O ultrassom com Doppler das veias do braço e do pescoço é o primeiro exame nesses casos.'),
        d('Insuficiência cardíaca direita', 'Dilata as jugulares e incha as pernas e o fígado, mas não incha o rosto de forma isolada nem forma colaterais na parede do tórax.'),
        d('Angioedema por medicamento', 'Incha a face e os lábios em horas, com coceira ou após remédio, sem colaterais venosas nem massa no mediastino. Responde a anti-histamínico, corticoide ou adrenalina e some em horas a dias.'),
      ],
    },
  },

  'histiocitose-de-langerhans': {
    tema: 'Parênquima e vias aéreas',
    titulo: 'Histiocitose pulmonar de células de Langerhans',
    resumo: 'Inúmeros cistos pulmonares de formas bizarras com predomínio nos lobos superiores, poupando os seios costofrênicos, bolhas apicais e, na MinIP, cistos centrolobulares em arranjo linear e ramificado com preservação subpleural.',
    protocolo: 'TC de tórax de alta resolução, coronal em MinIP e axial em janela de pulmão',
    series: ['Coronal MinIP', 'Axial'],
    rotulos: {
      branching: r('Cistos em padrão ramificado', 'Cistos alinhados como galhos, seguindo as vias aéreas.',
        'Na histiocitose de Langerhans, células inflamatórias se acumulam em volta dos bronquíolos e formam nódulos, que escavam e viram cistos. Como nascem nos bronquíolos, os cistos acompanham a árvore brônquica e às vezes se arranjam em ramos. A MinIP, que mostra o ar mais escuro, destaca esse padrão.'),
      linear: r('Cistos em arranjo linear', 'Cistos enfileirados ao longo de pequenas vias aéreas.',
        'O alinhamento dos cistos ao longo das vias aéreas mostra a origem bronquiolar da doença. É diferente da linfangioleiomiomatose, em que os cistos são redondos, regulares e espalhados de forma uniforme por todo o pulmão.'),
      'subpleural sparing': r('Preservação subpleural', 'Faixa de pulmão sem cistos junto à pleura.',
        'Como a doença começa no centro dos lóbulos, em volta dos bronquíolos, a periferia junto à pleura fica relativamente poupada. Esse detalhe ajuda a separar dos cistos do enfisema paraseptal, que ficam justamente na periferia.'),
      bullae: r('Bolhas apicais', 'Espaços aéreos grandes nos ápices.',
        'Cistos que se juntam formam bolhas, principalmente nos ápices. Elas podem se romper e causar pneumotórax, uma complicação frequente da doença. Todo pneumotórax espontâneo em fumante jovem merece olhar os pulmões na TC.'),
      cysts: r('Cistos de formas bizarras', 'Cistos de tamanhos e formas variados, alguns lobulados e confluentes.',
        'Cistos irregulares, de formas bizarras, com paredes de espessura variável e predomínio nos lobos superiores, poupando as bases e os seios costofrênicos, são a assinatura da histiocitose de Langerhans. A doença ocorre quase só em fumantes jovens, e parar de fumar pode estabilizá-la ou até fazê-la regredir.',
        'Cistos bizarros nos lobos superiores com bases poupadas em fumante jovem: histiocitose de Langerhans.'),
    },
    achados: [
      'Inúmeros cistos pulmonares de tamanhos e formas variados, alguns com estruturas internas, com predomínio nos lobos superiores e poupando os seios costofrênicos.',
      'Bolhas apicais.',
      'Na MinIP, cistos centrolobulares em arranjo linear e por vezes ramificado, com preservação subpleural.',
    ],
    armadilhas: [
      'Na fase inicial predominam nódulos, alguns escavados, e não cistos.',
      'Linfangioleiomiomatose tem cistos redondos difusos, inclusive nas bases, em mulheres.',
      'Enfisema centrolobular não tem paredes visíveis em volta das áreas escuras.',
    ],
    conduta: 'Cessação completa do tabagismo, prova de função pulmonar, ecocardiograma para hipertensão pulmonar, orientação sobre pneumotórax e corticoide ou quimioterapia nas formas progressivas.',
    vinheta: {
      cenario: 'Ambulatório de pneumologia',
      identificacao: 'Homem de 34 anos, publicitário.',
      queixa: 'Tosse seca e cansaço aos esforços há oito meses.',
      historia: 'Há oito meses tem tosse seca e cansa ao subir escadas, o que antes não acontecia. Há um ano teve um pneumotórax espontâneo à direita, drenado no pronto-socorro. Fuma um maço por dia desde os 16 anos.',
      antecedentes: [
        'Pessoais: pneumotórax espontâneo há um ano',
        'Pessoais: sede excessiva e urina em grande volume há meses',
        'Familiares: sem doenças pulmonares',
        'Hábitos: tabagista de 18 maços-ano',
      ],
      vitais: { pa: '118 × 74 mmHg', fc: '84 bpm', fr: '18 irpm', satO2: '95% em ar ambiente', temp: '36,5 °C' },
      exame: [
        'Murmúrio vesicular reduzido nos ápices',
        'Sem baqueteamento',
        'Difusão de monóxido de carbono reduzida',
        'Densidade urinária baixa',
      ],
      pedido: 'Dispneia, tosse e pneumotórax prévio em fumante jovem com poliúria: a pergunta é o padrão pulmonar.',
      pergunta: 'TC de tórax de alta resolução. Qual é o achado que responde à pergunta clínica?',
      achado: 'Histiocitose de células de Langerhans',
      veredito: 'Histiocitose pulmonar de células de Langerhans com cistos bizarros nos lobos superiores',
      correlacao: 'A fumaça do cigarro atrai células de Langerhans para os bronquíolos, onde formam nódulos que escavam e viram cistos bizarros, mais nos lobos superiores. As bolhas apicais explicam o pneumotórax, e a perda de área de troca reduz a difusão e causa cansaço. A sede e a poliúria sugerem diabetes insípido por infiltração da hipófise, outra manifestação da doença.',
      distratores: [
        d('Linfangioleiomiomatose pulmonar', 'Também forma cistos, mas em mulheres, com cistos redondos e regulares espalhados por todo o pulmão, inclusive nas bases. Também pode haver angiomiolipomas renais.'),
        d('Enfisema centrolobular do fumante', 'Forma áreas escuras nos lobos superiores sem parede visível, com uma artéria no centro, e não cistos de paredes definidas e formas bizarras.'),
        d('Pneumonia intersticial linfocítica', 'Forma cistos esparsos em volta de vasos nas bases, associada a Sjögren ou HIV, e não cistos bizarros nos ápices de fumantes. Ela também não tem relação com o tabagismo.'),
      ],
    },
  },

  pneumocistose: {
    tema: 'Infecção',
    titulo: 'Pneumocistose com cistos e pneumomediastino',
    resumo: 'Vidro fosco bilateral difuso com pavimentação em mosaico, consolidações nas bases, cistos de paredes finas nos lobos superiores, pneumomediastino com enfisema subcutâneo e linfonodos mediastinais e hilares.',
    protocolo: 'TC de tórax, janela de pulmão e fase tardia com contraste',
    series: ['Pulmão', 'Mediastino'],
    rotulos: {
      'subcutaneous emphysema': r('Enfisema subcutâneo', 'Ar sob a pele do pescoço e da parede do tórax.',
        'O ar que escapa dos alvéolos rompidos segue as bainhas dos vasos até o mediastino e, daí, sobe para o pescoço e a parede do tórax, onde fica sob a pele. Na palpação, o paciente tem crepitação, como se apertasse papel celofane.'),
      'lung cysts': r('Cistos pulmonares', 'Cistos de paredes finas, mais nos lobos superiores.',
        'A pneumonia por Pneumocystis destrói as paredes dos alvéolos e forma cistos, as pneumatoceles, em até um terço dos pacientes. Os cistos se rompem com facilidade e causam pneumotórax e pneumomediastino, complicações que pioram muito o prognóstico.'),
      Pneumomediastinum: r('Pneumomediastino', 'Ar em volta das estruturas do mediastino.',
        'O pneumomediastino aqui é espontâneo: os alvéolos frágeis se rompem e o ar segue pelas bainhas dos vasos e brônquios até o mediastino, o efeito Macklin. Em paciente com pneumocistose, ele indica pulmão muito doente e pode ser seguido de pneumotórax.'),
      'crazy-paving pattern': r('Pavimentação em mosaico', 'Vidro fosco com septos espessados por cima, como pedras de calçamento.',
        'O vidro fosco é o pulmão parcialmente preenchido por líquido e células, e os septos interlobulares espessados desenham linhas por cima, formando o padrão de pavimentação em mosaico. Ele aparece em pneumocistose, proteinose alveolar, edema, hemorragia e pneumonias virais.'),
      consolidation: r('Consolidações nas bases', 'Áreas de pulmão totalmente preenchidas, mais nos lobos inferiores.',
        'Na pneumocistose avançada, o vidro fosco evolui para consolidações, quando os alvéolos ficam completamente cheios de exsudato espumoso com os fungos. Isso se acompanha de hipoxemia intensa e pode exigir ventilação.'),
      mediastinal: r('Linfonodos mediastinais', 'Linfonodos aumentados no mediastino.',
        'Linfonodos aumentados não são típicos da pneumocistose isolada. Em paciente com HIV, eles levantam a suspeita de outra doença associada, como tuberculose, micobactérias atípicas, linfoma ou sarcoma de Kaposi, que deve ser investigada.'),
      'hilar lymph nodes': r('Linfonodos hilares', 'Linfonodos aumentados nos dois hilos.',
        'Linfonodos hilares bilaterais em paciente imunodeprimido ampliam o diagnóstico diferencial. A combinação de achados pulmonares típicos de pneumocistose com linfonodos exige procurar uma segunda infecção ou tumor oportunista.'),
    },
    achados: [
      'Opacidades em vidro fosco bilaterais e difusas com consolidações multifocais nos lobos inferiores e espessamento septal sobreposto — pavimentação em mosaico.',
      'Múltiplos cistos de paredes finas e tamanhos variados com predomínio nos lobos superiores.',
      'Pneumomediastino com enfisema subcutâneo no pescoço e na parede torácica superior.',
      'Linfonodos mediastinais e hilares bilaterais aumentados; colelitíase incidental.',
    ],
    armadilhas: [
      'A radiografia pode ser normal no início, mesmo com hipoxemia.',
      'Pneumotórax em paciente com pneumocistose tem alta mortalidade.',
      'Linfonodos e derrame não são típicos: procure outra doença associada.',
    ],
    conduta: 'Sulfametoxazol-trimetoprima em dose alta, corticoide se a pressão de oxigênio estiver baixa, teste de HIV e contagem de CD4, investigação de coinfecções e início da terapia antirretroviral nas semanas seguintes.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Homem de 36 anos, garçom.',
      queixa: 'Falta de ar que piora há três semanas e tosse seca.',
      historia: 'Há três semanas tem tosse seca e falta de ar que vem piorando, agora até para tomar banho. Tem febre baixa e perdeu 10 kg em três meses. Hoje sentiu dor no peito e o pescoço ficou estalando ao toque. Nunca fez teste de HIV.',
      antecedentes: [
        'Pessoais: candidíase oral de repetição',
        'Pessoais: herpes-zóster há um ano',
        'Familiares: sem doenças relevantes',
        'Hábitos: múltiplas parcerias sem preservativo',
      ],
      vitais: { pa: '112 × 70 mmHg', fc: '116 bpm', fr: '32 irpm', satO2: '84% em ar ambiente', temp: '38,1 °C' },
      exame: [
        'Candidíase oral',
        'Crepitação subcutânea no pescoço e na parede do tórax',
        'Ausculta pulmonar quase normal',
        'DHL elevada e teste rápido de HIV positivo',
      ],
      pedido: 'Dispneia subaguda com hipoxemia grave, ausculta pobre e DHL alta em paciente com HIV recém-diagnosticado e enfisema subcutâneo: a pergunta é o padrão pulmonar.',
      pergunta: 'TC de tórax. Qual é o achado que responde à pergunta clínica?',
      achado: 'Pneumocistose com pneumomediastino',
      veredito: 'Pneumonia por Pneumocystis jirovecii com cistos, pneumomediastino e enfisema subcutâneo',
      correlacao: 'Com o HIV sem tratamento e a imunidade baixa, mostrada pela candidíase e pelo zóster, o fungo Pneumocystis encheu os alvéolos de exsudato espumoso, o que dá o vidro fosco e a hipoxemia desproporcional à ausculta. Os alvéolos destruídos formaram cistos que se romperam e mandaram ar para o mediastino e o pescoço, por isso a dor e a crepitação.',
      distratores: [
        d('Tuberculose pulmonar miliar', 'Também ocorre com HIV e dá febre e dispneia, mas forma micronódulos de 1 a 3 mm espalhados por todo o pulmão, e não vidro fosco com cistos.'),
        d('Pneumonia bacteriana lobar', 'Começa em dias com febre alta e escarro purulento, com consolidação em um lobo e ausculta com estertores e sopro. Também não forma cistos nem pneumomediastino.'),
        d('Sarcoma de Kaposi pulmonar', 'Também ocorre com HIV avançado, mas forma nódulos em chama em volta dos brônquios, com lesões violáceas na pele. Costuma vir com derrame pleural e linfonodos.'),
      ],
    },
  },

  timoma: {
    tema: 'Tumores',
    titulo: 'Timoma com paralisia do nervo frênico',
    resumo: 'Massa no mediastino anterossuperior estendendo-se ao espaço pleural anterior direito, com calcificações e áreas císticas ou necróticas, e elevação do hemidiafragma direito por paralisia frênica.',
    protocolo: 'TC de tórax com contraste, fase arterial, axial e coronal',
    series: ['Axial', 'Coronal'],
    rotulos: {
      mass: r('Massa no mediastino anterior', 'Massa lobulada no mediastino anterossuperior, avançando para a pleura direita.',
        'O mediastino anterior abriga o timo, e as massas dessa região seguem a regra dos quatro T: timoma, teratoma, linfoma, chamado de terrível linfoma, e tireoide mergulhante. Em adultos acima de 40 anos, o timoma é o mais comum. Massa que invade a pleura ou estruturas vizinhas sugere timoma invasivo.'),
      'cystic/necrotic changes': r('Áreas císticas ou necróticas', 'Regiões sem realce dentro da massa.',
        'Timomas grandes podem ter áreas de degeneração cística e necrose. Necrose extensa e invasão de gordura sugerem tumor mais agressivo, como o carcinoma tímico, e influenciam o estadiamento de Masaoka.'),
      calcifications: r('Calcificações', 'Focos calcificados dentro da massa.',
        'Calcificações na periferia ou dentro da massa ocorrem em timomas e teratomas. No linfoma não tratado, calcificação é rara. Esse detalhe ajuda a estreitar o diferencial das massas do mediastino anterior.'),
      'elevated right diaphragm': r('Hemidiafragma direito elevado', 'Cúpula diafragmática direita alta, com o pilar atrofiado.',
        'O nervo frênico desce pelos lados do mediastino, junto ao pericárdio. Uma massa que o invade paralisa o diafragma daquele lado, que sobe e fica fino. Paralisia frênica é sinal de invasão e muda o estadiamento e a cirurgia.',
        'Diafragma elevado com massa mediastinal: suspeite de invasão do nervo frênico.'),
    },
    achados: [
      'Massa no mediastino anterossuperior estendendo-se ao espaço pleural anterior direito.',
      'Calcificações e áreas císticas ou necróticas no interior.',
      'Hemidiafragma direito elevado com atrofia do pilar diafragmático, indicando paralisia do nervo frênico.',
    ],
    armadilhas: [
      'Timo normal em jovens e hiperplasia tímica têm forma de pirâmide e gordura entremeada.',
      'Implantes pleurais, as metástases em gota, devem ser procurados em toda a pleura.',
      'Miastenia gravis ocorre em parte dos pacientes com timoma: cuidado com a anestesia.',
    ],
    conduta: 'Dosar anticorpos contra receptor de acetilcolina, biópsia quando o tumor não for ressecável de início, timectomia com ressecção completa e radioterapia ou quimioterapia conforme o estadiamento.',
    vinheta: {
      cenario: 'Ambulatório de neurologia',
      identificacao: 'Mulher de 49 anos, contadora.',
      queixa: 'Pálpebras caindo e visão dupla no fim do dia há quatro meses.',
      historia: 'Há quatro meses as pálpebras caem no fim do dia e ela vê dobrado ao dirigir à noite. Cansa ao mastigar carne e ao pentear o cabelo, melhorando com repouso. Há um mês sente falta de ar ao deitar de barriga para cima.',
      antecedentes: [
        'Pessoais: hipotireoidismo',
        'Gestacionais: duas gestações',
        'Familiares: sem doenças neuromusculares',
        'Hábitos: não fuma',
      ],
      vitais: { pa: '126 × 80 mmHg', fc: '82 bpm', fr: '18 irpm', satO2: '96% em ar ambiente', temp: '36,4 °C' },
      exame: [
        'Ptose bilateral que piora com olhar sustentado para cima',
        'Fraqueza proximal que piora com repetição',
        'Teste do gelo positivo',
        'Anticorpo antirreceptor de acetilcolina positivo',
      ],
      pedido: 'Fraqueza flutuante com ptose e diplopia e anticorpo positivo: a pergunta é se há tumor do timo associado.',
      pergunta: 'TC de tórax com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Timoma invasivo do mediastino',
      veredito: 'Timoma do mediastino anterior com extensão pleural e paralisia frênica direita',
      correlacao: 'O timo produz linfócitos que aprendem a não atacar o próprio corpo; o timoma desregula esse processo e gera anticorpos contra o receptor de acetilcolina, causando a miastenia gravis, com fraqueza que piora com o uso. A massa invadiu o nervo frênico direito e paralisou o diafragma, o que explica a falta de ar ao deitar.',
      distratores: [
        d('Linfoma de Hodgkin mediastinal', 'Também ocupa o mediastino anterior, mas em jovens com sintomas B e linfonodos em outras cadeias, sem calcificação e sem miastenia.'),
        d('Teratoma maduro do mediastino', 'Ocupa o mediastino anterior com gordura, calcificação e líquido, em adultos jovens, sem miastenia associada. Pode romper para o pulmão ou a pleura.'),
        d('Bócio mergulhante', 'Desce do pescoço para o mediastino em continuidade com a tireoide, com calcificações e realce intenso, e não se associa a miastenia.'),
      ],
    },
  },

  'torax-instavel': {
    tema: 'Trauma',
    titulo: 'Fraturas de costelas com contusão pulmonar e pneumotórax',
    resumo: 'Fraturas dos arcos posteriores das costelas 6 e 7 esquerdas com pequeno desvio, contusão no segmento basal posterior esquerdo e pequeno derrame com pneumotórax à esquerda.',
    protocolo: 'TC de tórax, janelas de mediastino e pulmão',
    series: ['Mediastino', 'Pulmão'],
    rotulos: {
      'fracture lines': r('Fraturas das costelas 6 e 7', 'Traços nos arcos posteriores das costelas esquerdas, pouco desviados.',
        'As costelas fraturam no ponto que recebe a força ou onde se curvam mais. Fraturas de três ou mais costelas seguidas, em dois pontos cada, formam o tórax instável, em que um segmento da parede se move ao contrário durante a respiração. Mesmo sem isso, fraturas de costelas doem muito, fazem o paciente respirar superficial e aumentam o risco de pneumonia, sobretudo em idosos.',
        'Conte as costelas fraturadas: três ou mais em idoso aumentam muito a mortalidade.'),
      'pleural effusion': r('Derrame com pneumotórax', 'Lâmina de líquido e ar na pleura esquerda.',
        'A costela quebrada pode furar a pleura e o pulmão, deixando entrar ar e sangue no espaço pleural. Sangue na pleura após trauma é hemotórax até prova em contrário. Pequenos volumes são observados, grandes volumes são drenados.'),
      'ground glass opacity and septa': r('Contusão pulmonar', 'Consolidação periférica com vidro fosco e septos espessados.',
        'A contusão é sangue e edema dentro do pulmão, no ponto atingido pelo trauma. Aparece em horas, em áreas que não respeitam os limites dos segmentos, perto das costelas fraturadas. Piora nas primeiras 24 a 48 horas e regride em cerca de uma semana. Contusões extensas podem levar à insuficiência respiratória.'),
    },
    achados: [
      'Fraturas dos arcos posteriores das costelas 6 e 7 esquerdas com pequeno desvio.',
      'Consolidação periférica com vidro fosco e espessamento septal no segmento basal posterior esquerdo — contusão pulmonar.',
      'Pequeno derrame pleural esquerdo com pneumotórax.',
    ],
    armadilhas: [
      'Pneumotórax pequeno visto só na TC pode crescer com ventilação mecânica.',
      'Fraturas de costelas baixas pedem procurar lesão de baço, fígado e rim.',
      'Contusão que aparece dias depois sugere pneumonia ou aspiração, não trauma.',
    ],
    conduta: 'Analgesia potente, inclusive com bloqueios regionais, fisioterapia respiratória, observação do pneumotórax com radiografias e drenagem se aumentar ou se o paciente for ventilado.',
    vinheta: {
      cenario: 'Sala de trauma',
      identificacao: 'Homem de 41 anos, entregador.',
      queixa: 'Dor forte nas costas do lado esquerdo depois de cair da moto.',
      historia: 'Caiu da moto e bateu as costas do lado esquerdo contra o meio-fio. Sente dor muito forte ao respirar fundo e ao tossir, e escarrou um pouco de sangue. Está consciente e lembra de tudo.',
      antecedentes: [
        'Pessoais: sem doenças',
        'Pessoais: sem uso de anticoagulantes',
        'Familiares: sem doenças relevantes',
        'Hábitos: tabagista',
      ],
      vitais: { pa: '134 × 82 mmHg', fc: '102 bpm', fr: '26 irpm', satO2: '93% em ar ambiente', temp: '36,6 °C' },
      exame: [
        'Dor e crepitação óssea nas costelas posteriores esquerdas',
        'Murmúrio vesicular reduzido na base esquerda',
        'Respiração superficial pela dor',
        'Sem movimento paradoxal da parede',
      ],
      pedido: 'Trauma fechado no dorso com dor costal, hemoptise e murmúrio reduzido: a pergunta é a lesão da parede e do pulmão.',
      pergunta: 'TC de tórax. Qual é o achado que responde à pergunta clínica?',
      achado: 'Fraturas costais com contusão pulmonar',
      veredito: 'Fraturas das costelas 6 e 7 esquerdas com contusão pulmonar, pequeno derrame e pneumotórax',
      correlacao: 'O impacto no meio-fio quebrou os arcos posteriores das costelas 6 e 7, o que explica a dor e a crepitação. A mesma força contundiu o pulmão logo abaixo, com sangue nos alvéolos, daí a hemoptise. A costela feriu a pleura, deixando entrar ar e um pouco de sangue, o que reduz o murmúrio na base.',
      distratores: [
        d('Tórax instável com segmento paradoxal', 'Exige três ou mais costelas seguidas quebradas em dois pontos, com um segmento da parede que afunda na inspiração, o que este paciente não tem.'),
        d('Pneumonia aspirativa do lobo inferior', 'Também consolida a base, mas surge dias depois de uma aspiração, com febre e escarro purulento, sem fraturas. O contexto de trauma direto aponta para contusão.'),
        d('Hemotórax maciço pós-traumático', 'Enche o hemitórax de sangue, com choque e mais de 1,5 litro na drenagem, e não só uma lâmina de líquido. Ele exige toracotomia de urgência.'),
      ],
    },
  },

  'malformacao-arteriovenosa-pulmonar': {
    tema: 'Vascular',
    titulo: 'Malformação arteriovenosa pulmonar simples',
    resumo: 'Lesão bem definida no ápice esquerdo com realce como os vasos, artéria nutridora e veia de drenagem segmentares, com átrio direito e tronco pulmonar aumentados, derrame pericárdico, veia cava inferior dilatada e ascite.',
    protocolo: 'TC de tórax com contraste, fase arterial e angiotomografia pulmonar',
    series: ['Fase arterial', 'Angiotomografia'],
    rotulos: {
      'postcontrast enhancement': r('Realce como os vasos', 'A lesão realça de forma homogênea, igual às artérias.',
        'A malformação arteriovenosa pulmonar é uma comunicação direta entre uma artéria e uma veia, sem capilares no meio. Como é feita de sangue em movimento, realça junto com os vasos. Nódulos que realçam exatamente como a artéria pulmonar sugerem lesão vascular, e não tumor.'),
      'feeding artery': r('Artéria nutridora', 'Ramo arterial segmentar tortuoso e dilatado chegando à lesão.',
        'Na malformação simples, uma única artéria segmentar alimenta o saco. O diâmetro da artéria nutridora orienta o tratamento: acima de 2 a 3 mm, indica-se embolização, porque o risco de embolia paradoxal e abscesso cerebral aumenta.',
        'Artéria nutridora acima de 3 mm: embolize, mesmo sem sintomas.'),
      'draining vein': r('Veia de drenagem', 'Veia segmentar que sai da lesão em direção ao átrio esquerdo.',
        'A veia de drenagem leva o sangue não oxigenado da malformação direto para o átrio esquerdo e daí para o corpo. Esse desvio explica a hipoxemia e a cianose. Coágulos e bactérias que normalmente seriam filtrados pelos capilares do pulmão podem chegar ao cérebro.'),
      'enlarged main pulmonary artery': r('Tronco pulmonar aumentado', 'Tronco da artéria pulmonar dilatado.',
        'O tronco pulmonar dilatado sugere aumento de fluxo ou de pressão no circuito pulmonar. Aqui ele acompanha o coração direito aumentado, o que pode indicar sobrecarga crônica ou outra doença cardíaca associada, que precisa ser avaliada por ecocardiograma.'),
      'enlarged right atrium': r('Átrio direito aumentado', 'Átrio direito grande, sem aumento proporcional do ventrículo.',
        'O átrio direito dilatado com congestão do fígado e da cava inferior indica pressão venosa sistêmica alta. Essa combinação não é causada pela malformação simples e sugere doença cardíaca associada, como insuficiência tricúspide.'),
      'pericardial effusion': r('Derrame pericárdico pequeno', 'Lâmina de líquido em volta do coração.',
        'Pequeno derrame pericárdico pode acompanhar a congestão venosa sistêmica. Ele faz parte do quadro de sobrecarga do coração direito e deve ser acompanhado no ecocardiograma. Ele raramente causa sintomas.'),
      'dilated IVC': r('Veia cava inferior dilatada', 'Cava inferior larga, com refluxo e congestão hepática.',
        'A cava inferior dilatada, com contraste refluindo para as veias do fígado, mostra que a pressão no átrio direito está alta. É um sinal de congestão do lado direito do coração, que causa fígado aumentado e ascite.'),
      ascites: r('Ascite leve', 'Pouco líquido livre no abdome.',
        'A ascite completa o quadro de congestão sistêmica. Ela também pode ter outras causas, como doença do fígado, que devem ser lembradas no laudo. Ela não precisa de punção diagnóstica se a causa já é clara, mas deve ser acompanhada.'),
      'well-defined lesion': r('Lesão bem definida no ápice esquerdo', 'Nódulo de contornos nítidos no ápice, ligado a vasos.',
        'Na angiotomografia, a lesão aparece como um nódulo bem definido conectado a uma artéria e a uma veia, como uma bola com dois fios. Reconstruções em vários planos mostram essa conexão e permitem planejar a embolização com molas ou plugues.'),
    },
    achados: [
      'Lesão bem definida no ápice esquerdo com realce homogêneo, nutrida por ramo arterial segmentar tortuoso e dilatado do lobo superior e drenada por veia segmentar — malformação arteriovenosa pulmonar simples.',
      'Tronco pulmonar aumentado; átrio direito muito aumentado sem aumento proporcional do ventrículo direito; câmaras esquerdas pequenas.',
      'Veia cava inferior dilatada com congestão hepática passiva, pequeno derrame pericárdico e ascite leve.',
    ],
    armadilhas: [
      'Malformações múltiplas sugerem telangiectasia hemorrágica hereditária: examine nariz, pele e fígado.',
      'Ar em acessos venosos é perigoso nesses pacientes: use filtros.',
      'Nódulo pulmonar com vaso grande entrando e saindo não deve ser biopsiado.',
    ],
    conduta: 'Embolização da artéria nutridora, ecocardiograma para avaliar a sobrecarga direita, rastreio de telangiectasia hemorrágica hereditária e antibioticoprofilaxia em procedimentos dentários.',
    vinheta: {
      cenario: 'Ambulatório de pneumologia',
      identificacao: 'Mulher de 38 anos, bancária.',
      queixa: 'Falta de ar aos esforços e lábios arroxeados há anos.',
      historia: 'Há anos cansa mais que as amigas e percebe os lábios roxos quando faz exercício. Tem sangramentos nasais frequentes desde a adolescência. Há seis meses teve um AVC pequeno sem causa definida, do qual se recuperou. Nos últimos meses as pernas e a barriga incharam.',
      antecedentes: [
        'Pessoais: epistaxes de repetição',
        'Pessoais: AVC isquêmico há seis meses sem causa definida',
        'Familiares: mãe com sangramentos nasais e manchas vermelhas na boca',
        'Hábitos: não fuma',
      ],
      vitais: { pa: '116 × 72 mmHg', fc: '92 bpm', fr: '20 irpm', satO2: '88% em ar ambiente', temp: '36,4 °C' },
      exame: [
        'Telangiectasias nos lábios e na língua',
        'Sopro contínuo no ápice esquerdo do tórax',
        'Baqueteamento digital',
        'Turgência jugular, hepatomegalia e edema de membros',
      ],
      pedido: 'Hipoxemia com baqueteamento, sopro torácico contínuo, AVC sem causa e epistaxes familiares: a pergunta é se há shunt pulmonar.',
      pergunta: 'TC de tórax com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Malformação arteriovenosa pulmonar',
      veredito: 'Malformação arteriovenosa pulmonar simples no ápice esquerdo com sinais de sobrecarga direita',
      correlacao: 'Epistaxes, telangiectasias e mãe com o mesmo quadro sugerem telangiectasia hemorrágica hereditária, que forma comunicações diretas entre artérias e veias. No pulmão, o sangue passa sem oxigenar, por isso a cianose, o baqueteamento e o sopro contínuo. Sem o filtro dos capilares, um coágulo chegou ao cérebro e causou o AVC. A congestão venosa indica doença cardíaca associada.',
      distratores: [
        d('Nódulo pulmonar maligno', 'Também é nódulo no ápice, mas não tem artéria e veia ligadas a ele, não realça como os vasos e não causa cianose nem sopro. Biopsiar uma malformação pode causar sangramento grave.'),
        d('Síndrome hepatopulmonar', 'Causa hipoxemia por dilatação dos vasos pulmonares em pacientes com cirrose, sem nódulo vascular focal no ápice. Aqui não há doença do fígado que a explique.'),
        d('Forame oval patente com shunt', 'Também permite embolia paradoxal e AVC, mas o desvio é no coração, e o pulmão não mostra lesão vascular. O ecocardiograma com microbolhas mostra a passagem em poucos batimentos, mais cedo que no shunt pulmonar.'),
      ],
    },
  },
}
