import { d, r, type ConteudoCaso } from './casos-imagem-tipos'

/** Raio-X com apontamentos — doenças metabólicas, tumores ósseos e coluna. Pacientes fictícios. */
export const CASOS_RX_OSSO_4: Record<string, ConteudoCaso> = {
  'hiperparatireoidismo-secundario': {
    tema: 'Doenças metabólicas',
    titulo: 'Hiperparatireoidismo secundário com fratura patológica',
    resumo: 'Vértebras torácicas levemente achatadas, esterno heterogêneo, costelas deformadas e alargadas, múltiplas lesões líticas e fratura patológica imobilizada.',
    protocolo: 'Radiografias da coluna torácica em perfil, do tórax e do membro',
    series: ['Coluna torácica', 'Tórax', 'Membro'],
    rotulos: {
      heterogeneous: r('Esterno heterogêneo', 'Estrutura do esterno irregular, com áreas claras e densas.',
        'O excesso de paratormônio acelera a reabsorção e a formação do osso de forma desorganizada. O osso perde a textura normal e fica com áreas claras e densas misturadas, um aspecto em sal e pimenta, que é muito visível no crânio e também aparece no esterno e nas costelas.'),
      'mildly flattened': r('Vértebras achatadas', 'Corpos vertebrais torácicos com leve perda de altura.',
        'O osso enfraquecido pelo paratormônio cede ao peso e os corpos vertebrais se achatam. No hiperparatireoidismo secundário da doença renal, também pode aparecer a coluna em camisa de rúgbi, com faixas densas nos platôs e clara no meio das vértebras.'),
      'pathologic fracture': r('Fratura patológica', 'Fratura em osso enfraquecido por lesão, com trauma mínimo.',
        'Fratura patológica é a que acontece em osso já doente, com trauma que não quebraria um osso normal. No hiperparatireoidismo, os tumores marrons, lesões líticas cheias de tecido fibroso e sangue antigo, deixam pontos fracos no osso. Toda fratura com trauma pequeno deve fazer o médico procurar a doença de base.',
        'Lesões líticas múltiplas com fratura em paciente renal crônico: dose PTH antes de pensar em metástase.'),
      'multiple lytic bone lesions': r('Lesões líticas múltiplas', 'Várias áreas de osso destruído — tumores marrons.',
        'Os tumores marrons não são tumores verdadeiros, mas áreas de reabsorção intensa de osso pelos osteoclastos, cheias de tecido fibroso e hemossiderina, que dá a cor marrom. Eles regridem quando o paratormônio é controlado. Na imagem, podem imitar metástases ou mieloma, por isso o contexto clínico e o PTH são essenciais.'),
    },
    achados: [
      'Corpos vertebrais torácicos levemente achatados.',
      'Esterno de estrutura heterogênea; costelas deformadas e alargadas com contorno irregular.',
      'Múltiplas lesões líticas — tumores marrons — com fratura patológica imobilizada em gesso.',
    ],
    armadilhas: [
      'Tumores marrons imitam metástases e mieloma.',
      'Reabsorção subperiosteal na borda radial das falanges médias é o sinal mais específico.',
      'No hiperparatireoidismo terciário, o PTH continua alto mesmo após corrigir o fósforo.',
    ],
    conduta: 'Dosar cálcio, fósforo, PTH e vitamina D; controlar o fósforo, repor vitamina D ativa, usar calcimimético e indicar paratireoidectomia nos casos refratários; tratar a fratura.',
    vinheta: {
      cenario: 'Ambulatório de nefrologia',
      identificacao: 'Homem de 49 anos, em hemodiálise há nove anos.',
      queixa: 'Dor no braço depois de esbarrar na porta e dores ósseas difusas.',
      historia: 'Faz hemodiálise três vezes por semana há nove anos e não toma regularmente os quelantes de fósforo. Há meses tem dores nos ossos e coceira. Ao bater o braço numa porta, sentiu um estalo e o braço deformou. Também ficou mais baixo nos últimos anos.',
      antecedentes: [
        'Pessoais: doença renal crônica por nefropatia diabética',
        'Pessoais: baixa adesão aos quelantes de fósforo',
        'Familiares: sem doenças ósseas',
        'Hábitos: dieta rica em laticínios e refrigerantes',
      ],
      vitais: { pa: '152 × 88 mmHg', fc: '82 bpm', fr: '16 irpm', satO2: '97% em ar ambiente', temp: '36,5 °C' },
      exame: [
        'Deformidade e dor no antebraço após trauma mínimo',
        'Dor à palpação das costelas',
        'Prurido com escoriações',
        'PTH de 2.100 pg/mL e fósforo de 8,2 mg/dL',
      ],
      pedido: 'Fratura com trauma mínimo, dores ósseas e PTH muito alto em paciente em diálise: a pergunta é o padrão ósseo.',
      pergunta: 'Radiografias da coluna, do tórax e do membro. Qual é o achado que responde à pergunta clínica?',
      achado: 'Tumores marrons com fratura patológica',
      veredito: 'Hiperparatireoidismo secundário com tumores marrons, deformidades e fratura patológica',
      correlacao: 'O rim doente não elimina fósforo nem ativa a vitamina D, e o cálcio cai. As paratireoides respondem produzindo PTH sem parar, e o PTH retira cálcio do osso. Sem os quelantes, o fósforo ficou alto e o estímulo continuou por anos. O osso ficou cheio de tumores marrons e quebrou com um esbarrão.',
      distratores: [
        d('Mieloma múltiplo com lesões líticas', 'Também dá lesões líticas e fraturas, mas com pico monoclonal, anemia e cálcio alto, sem o PTH muito elevado do renal crônico. O PTH aqui explica.'),
        d('Metástases ósseas líticas', 'Destroem o osso em múltiplos pontos em paciente com câncer conhecido, e não regridem com o controle do PTH. Aqui não há câncer conhecido.'),
        d('Osteoporose com fraturas vertebrais', 'Achata vértebras e causa fraturas por fragilidade, mas sem lesões líticas, costelas alargadas nem PTH muito alto. Aqui há lesões líticas.'),
      ],
    },
  },

  'tumor-de-celulas-gigantes': {
    tema: 'Tumores ósseos',
    titulo: 'Tumor de células gigantes da tíbia distal',
    resumo: 'Lesão lítica excêntrica na tíbia distal com septos, margem bem definida sem halo esclerótico, afilamento e expansão da cortical, chegando ao osso subcondral; controle com enxerto, cimento e placa.',
    protocolo: 'Radiografias da perna AP antes e após a cirurgia',
    series: ['Pré-operatório', 'Pós-operatório'],
    rotulos: {
      'thinning of the cortical bone': r('Afilamento da cortical', 'Cortical fina e expandida junto à lesão.',
        'A lesão cresce dentro do osso e empurra a cortical para fora, que fica fina e abaulada. Se a cortical se romper, o tumor pode invadir as partes moles e o risco de fratura aumenta. O grau de destruição cortical entra na classificação de Campanacci, que orienta o tratamento.'),
      'soft tissue edema': r('Edema de partes moles', 'Partes moles inchadas junto à lesão.',
        'O edema em volta da lesão pode ser reação à expansão do osso. Uma massa verdadeira de partes moles, e não só edema, indicaria ruptura da cortical e doença mais agressiva. Aqui não há massa.'),
      septations: r('Septos internos', 'Finas traves dentro da lesão, aspecto em bolhas de sabão.',
        'Os septos são restos de cortical e trabéculas que sobram enquanto o tumor cresce. Dão o aspecto em bolhas de sabão, que também aparece em outros tumores e no cisto ósseo aneurismático. Eles sozinhos não indicam malignidade.'),
      'osteolytic lesion': r('Lesão lítica excêntrica', 'Lesão clara, excêntrica, chegando ao osso sob a cartilagem.',
        'O tumor de células gigantes aparece em adultos jovens, de 20 a 40 anos, com as placas de crescimento já fechadas. Ele nasce na metáfise e cresce até o osso logo abaixo da cartilagem articular, de forma excêntrica. A margem é bem definida, mas sem o halo esclerótico das lesões de crescimento lento. Esses quatro dados, idade, localização, excentricidade e ausência de esclerose, sugerem fortemente o diagnóstico.',
        'Lesão lítica que chega até a superfície articular em adulto com placa fechada: tumor de células gigantes.'),
      'bone graft material and cement': r('Enxerto e cimento ósseo', 'O espaço do tumor preenchido após a curetagem.',
        'O tratamento usual é curetar o tumor e preencher a cavidade com enxerto ósseo ou cimento. O cimento produz calor que ajuda a destruir células tumorais restantes e permite ver recidivas como áreas claras na borda. A recidiva local é a principal preocupação nos primeiros anos.'),
      'plate and screws': r('Placa e parafusos', 'Placa na tíbia distal para reforçar o osso.',
        'A placa sustenta o osso enfraquecido depois da curetagem e evita fratura. As radiografias de seguimento procuram reabsorção em volta do cimento, que pode indicar recidiva. Ela também permite carga mais cedo.'),
    },
    achados: [
      'Lesão lítica excêntrica na tíbia distal com septos internos e margens bem definidas, zona de transição estreita, sem halo esclerótico.',
      'Afilamento e expansão da cortical; extensão ao osso subcondral, sem cruzar a superfície articular.',
      'Edema de partes moles; sem reação periosteal, fratura ou matriz mineralizada.',
      'Controle de 4 meses com a cavidade preenchida por enxerto e cimento e fixação com placa e parafusos.',
    ],
    armadilhas: [
      'Em paciente com placa aberta, lesão parecida sugere outros diagnósticos, como cisto ósseo aneurismático.',
      'Tumor de células gigantes raramente dá metástase pulmonar: faça TC de tórax no estadiamento.',
      'O hiperparatireoidismo com tumor marrom pode imitar o tumor de células gigantes.',
    ],
    conduta: 'Biópsia, ressonância e TC de tórax; curetagem ampliada com adjuvantes e preenchimento com cimento ou enxerto; denosumabe nos casos irressecáveis; seguimento por anos para recidiva.',
    vinheta: {
      cenario: 'Ambulatório de ortopedia oncológica',
      identificacao: 'Mulher de 28 anos, professora de educação física.',
      queixa: 'Dor no tornozelo direito há seis meses, pior com atividade.',
      historia: 'Há seis meses tem dor no tornozelo direito que piora ao correr e, nas últimas semanas, também em repouso. Notou um inchaço na parte de dentro do tornozelo. Nega trauma, febre e emagrecimento.',
      antecedentes: [
        'Pessoais: sem doenças',
        'Gestacionais: uma gestação há dois anos',
        'Familiares: sem câncer ósseo',
        'Hábitos: pratica corrida',
      ],
      vitais: { pa: '114 × 70 mmHg', fc: '70 bpm', fr: '14 irpm', satO2: '99% em ar ambiente', temp: '36,4 °C' },
      exame: [
        'Abaulamento doloroso na tíbia distal',
        'Leve limitação do movimento do tornozelo',
        'Sem sinais inflamatórios',
        'Cálcio e PTH normais',
      ],
      pedido: 'Dor e abaulamento na tíbia distal em adulta jovem, sem trauma nem febre: a pergunta é a natureza da lesão óssea.',
      pergunta: 'Radiografias da perna. Qual é o achado que responde à pergunta clínica?',
      achado: 'Tumor de células gigantes',
      veredito: 'Tumor de células gigantes da tíbia distal tratado com curetagem, cimento e placa',
      correlacao: 'Adulta jovem, com placas de crescimento fechadas, e lesão lítica excêntrica que vai da metáfise até o osso sob a cartilagem, sem halo esclerótico: é o perfil típico. O tumor afinou e abaulou a cortical, o que explica o inchaço e a dor, e trazia risco de fratura. Cálcio e PTH normais afastam tumor marrom.',
      distratores: [
        d('Cisto ósseo aneurismático', 'Também é expansivo e septado, mas ocorre antes dos 20 anos com placa aberta e mostra níveis líquidos na ressonância. Aqui a placa está fechada.'),
        d('Condrossarcoma de baixo grau', 'Ocorre em adultos mais velhos, com matriz condroide em anéis e arcos e escavação endosteal, e não é excêntrico até o subcondral.'),
        d('Defeito fibroso cortical', 'É lesão pequena e excêntrica na cortical da metáfise de crianças, com halo esclerótico, e some sozinha. Aqui a paciente é adulta.'),
      ],
    },
  },

  'cisto-osseo-simples': {
    tema: 'Tumores ósseos',
    titulo: 'Cisto ósseo simples com fratura e sinal do fragmento caído',
    resumo: 'Lesão lítica expansiva central na metáfise proximal do úmero com margem esclerótica fina, fratura patológica e fragmento ósseo caído dentro do cisto.',
    protocolo: 'Radiografia do úmero AP',
    rotulos: {
      'Expansile lytic lesion': r('Lesão lítica expansiva', 'Lesão clara central na metáfise do úmero, com margem fina.',
        'O cisto ósseo simples, ou unicameral, é uma cavidade cheia de líquido que aparece em crianças e adolescentes, sobretudo no úmero e no fêmur proximais. Ele fica no centro da metáfise, junto à placa de crescimento, e se afasta dela com o crescimento. Tem margem fina e bem definida, sem matriz. Muitas vezes é descoberto quando fratura.'),
      'fallen fragment sign': r('Sinal do fragmento caído', 'Pedaço de cortical solto no fundo do cisto.',
        'Quando o cisto fratura, um fragmento da cortical se solta e afunda no líquido até a parte mais baixa da cavidade. Esse sinal prova que a lesão é cheia de líquido e não de tecido sólido, porque num tumor sólido o fragmento não teria para onde cair. É praticamente patognomônico de cisto ósseo simples.',
        'Fragmento de osso solto na parte pendente de uma lesão lítica: cisto ósseo simples.'),
    },
    achados: [
      'Lesão lítica expansiva de 72 × 24 mm na metáfise proximal do úmero, com margem esclerótica fina e zona de transição estreita.',
      'Fratura patológica com fragmento ósseo dentro da lesão — sinal do fragmento caído.',
      'Reação periosteal lisa e focal; sem massa de partes moles nem matriz calcificada.',
    ],
    armadilhas: [
      'Cisto ósseo aneurismático é excêntrico e mais expansivo, com níveis líquidos.',
      'A fratura pode estimular a cicatrização do cisto, mas muitos recidivam.',
      'Cistos ativos, encostados na placa, têm mais risco de recidiva.',
    ],
    conduta: 'Tratar a fratura com imobilização e aguardar consolidação; depois, injeção de corticoide ou medula óssea, ou curetagem com enxerto se o cisto persistir com risco de nova fratura.',
    vinheta: {
      cenario: 'Pronto-socorro de ortopedia pediátrica',
      identificacao: 'Menino de 10 anos.',
      queixa: 'Dor no braço direito depois de arremessar uma bola.',
      historia: 'Durante uma partida de queimada, ao arremessar a bola, sentiu um estalo e dor forte no braço direito. Não caiu nem bateu. Nunca tinha sentido dor no braço antes.',
      antecedentes: [
        'Pessoais: sem fraturas anteriores',
        'Pessoais: sem doenças',
        'Familiares: sem doenças ósseas',
        'Hábitos: ativo, pratica esportes',
      ],
      vitais: { pa: '102 × 64 mmHg', fc: '98 bpm', fr: '20 irpm', satO2: '99% em ar ambiente', temp: '36,6 °C' },
      exame: [
        'Dor e edema no terço proximal do braço direito',
        'Mobilidade anormal no úmero proximal',
        'Pulsos e sensibilidade normais',
        'Sem febre nem emagrecimento',
      ],
      pedido: 'Fratura do úmero com trauma mínimo em criança sem doenças: a pergunta é se havia lesão óssea prévia.',
      pergunta: 'Radiografia do úmero. Qual é o achado que responde à pergunta clínica?',
      achado: 'Cisto ósseo simples fraturado',
      veredito: 'Cisto ósseo simples do úmero proximal com fratura patológica e sinal do fragmento caído',
      correlacao: 'O cisto cresceu sem sintomas na metáfise do úmero e afinou a cortical. Um simples arremesso bastou para quebrar o osso fraco: é uma fratura patológica. O fragmento de cortical que afundou no líquido mostra que a lesão é um cisto, e não um tumor sólido.',
      distratores: [
        d('Cisto ósseo aneurismático', 'É mais expansivo e excêntrico, com septos e níveis líquidos de sangue na ressonância, e pode crescer rápido. Não deixa fragmento caído.'),
        d('Displasia fibrosa monostótica', 'Tem aspecto em vidro fosco, com matriz levemente densa, e deforma o osso, sem fragmento caído no interior. Aqui a lesão é clara e não fosca.'),
        d('Granuloma eosinofílico ósseo', 'É lesão lítica em saca-bocado com bordas biseladas, em criança, que pode ter reação periosteal e dor sem fratura. Aqui há fragmento caído.'),
      ],
    },
  },

  'osteoma-osteoide': {
    tema: 'Tumores ósseos',
    titulo: 'Osteoma osteoide da diáfise do rádio',
    resumo: 'Diáfise do rádio deformada, com cortical espessa e esclerótica, reação periosteal, canal estreitado e nicho radiotransparente; controle com o defeito da ressecção.',
    protocolo: 'Radiografias do antebraço AP, perfil e controle após ressecção',
    series: ['Frontal', 'Perfil', 'Pós-operatório'],
    rotulos: {
      'thick and sclerotic': r('Cortical espessa e esclerótica', 'Cortical muito engrossada e densa ao longo da diáfise.',
        'O osteoma osteoide é um tumor benigno pequeno, menor que 1,5 cm, que produz prostaglandinas. Elas causam inflamação intensa e o osso em volta reage formando muita esclerose. A esclerose pode ser tão grande que esconde o tumor, e o osso fica engrossado e deformado.'),
      'Periosteal reaction': r('Reação periosteal', 'Osso novo formado pelo periósteo em volta da lesão.',
        'A reação periosteal sólida e lisa mostra um processo de crescimento lento, que dá tempo ao periósteo de formar osso bem organizado. Reação em camadas ou espiculada indicaria processo agressivo.'),
      nidus: r('Nicho', 'Pequena área clara no meio da esclerose.',
        'O nicho é o tumor propriamente dito: uma pequena área clara, às vezes com um ponto calcificado no centro, cercada por esclerose. Ele precisa ser encontrado e retirado por inteiro, senão a dor volta. A TC é o melhor exame para localizar o nicho.',
        'Dor noturna que melhora com aspirina ou anti-inflamatório em jovem: procure o nicho na TC.'),
      'projection area of the resecti': r('Área da ressecção', 'Defeito na cortical onde o nicho foi retirado.',
        'O controle mostra o defeito da cortical onde o tumor foi removido. Hoje, muitos são tratados com ablação por radiofrequência guiada por TC, que destrói o nicho sem abrir o osso. O sucesso é confirmado pelo fim da dor noturna.'),
    },
    achados: [
      'Deformidade dos terços médio e distal da diáfise do rádio com aumento do diâmetro transverso.',
      'Cortical espessa e esclerótica, reação periosteal e estreitamento do canal medular.',
      'Nicho radiotransparente na face anterior.',
      'Controle com defeito cortical na área da ressecção.',
    ],
    armadilhas: [
      'A esclerose pode esconder o nicho na radiografia: peça TC.',
      'Osteoma osteoide intra-articular causa sinovite e pouca esclerose.',
      'Fratura por estresse e osteomielite crônica podem imitar a lesão.',
    ],
    conduta: 'TC para localizar o nicho, anti-inflamatório para a dor e ablação por radiofrequência guiada por TC ou ressecção cirúrgica do nicho.',
    vinheta: {
      cenario: 'Ambulatório de ortopedia',
      identificacao: 'Rapaz de 17 anos, estudante.',
      queixa: 'Dor no antebraço direito que acorda à noite há oito meses.',
      historia: 'Há oito meses tem dor no antebraço direito, pior à noite, que chega a acordá-lo. A dor passa em meia hora com ibuprofeno. Notou que o antebraço engrossou. Nega trauma e febre.',
      antecedentes: [
        'Pessoais: sem doenças',
        'Pessoais: sem fraturas',
        'Familiares: sem doenças ósseas',
        'Hábitos: joga vôlei',
      ],
      vitais: { pa: '118 × 72 mmHg', fc: '70 bpm', fr: '14 irpm', satO2: '99% em ar ambiente', temp: '36,5 °C' },
      exame: [
        'Espessamento duro e doloroso na diáfise do rádio',
        'Sem calor nem vermelhidão',
        'Movimentos do punho e do cotovelo normais',
        'Hemograma e marcadores inflamatórios normais',
      ],
      pedido: 'Dor noturna que melhora com anti-inflamatório e espessamento do rádio em adolescente: a pergunta é a natureza da lesão.',
      pergunta: 'Radiografias do antebraço. Qual é o achado que responde à pergunta clínica?',
      achado: 'Osteoma osteoide com nicho',
      veredito: 'Osteoma osteoide da diáfise do rádio com nicho e esclerose cortical',
      correlacao: 'O pequeno nicho produz prostaglandinas, que causam dor pior à noite e explicam o alívio rápido com ibuprofeno, que as bloqueia. A inflamação em volta fez o osso reagir com muita esclerose e espessamento da cortical. Marcadores inflamatórios normais e ausência de febre afastam osteomielite.',
      distratores: [
        d('Osteomielite crônica com sequestro', 'Também espessa o osso, mas com febre, fístula e um fragmento denso de osso morto no centro, não um nicho claro. Aqui não há febre.'),
        d('Fratura por estresse do rádio', 'Tem linha esclerótica transversa e calo após esforço repetido, sem nicho e com dor ao esforço, não noturna. Aqui há nicho claro na cortical.'),
        d('Osteossarcoma da diáfise', 'Destrói o osso com reação periosteal agressiva em raios de sol e massa de partes moles, e a dor não melhora com anti-inflamatório.'),
      ],
    },
  },

  'espondilolise-com-listese': {
    tema: 'Coluna',
    titulo: 'Espondiloptose de L5 com sinal do chapéu de Napoleão invertido',
    resumo: 'Defeito bilateral das partes interarticulares de L5 com escorregamento completo de L5 à frente do sacro e sinal do chapéu de Napoleão invertido no frontal.',
    protocolo: 'Radiografias da coluna lombossacra perfil e AP',
    rotulos: {
      spondyloptosis: r('Espondiloptose', 'L5 escorregou inteira à frente do sacro.',
        'A espondilolistese é o escorregamento de uma vértebra sobre a de baixo. A classificação de Meyerding divide o platô do sacro em quatro partes: grau I até 25%, grau II até 50%, grau III até 75% e grau IV até 100%. Acima de 100%, a vértebra cai totalmente à frente do sacro, e chama-se espondiloptose. As raízes nervosas ficam esticadas e o paciente pode ter dor ciática e alteração da marcha.',
        'Escorregamento alto em adolescente: peça ressonância para avaliar as raízes de L5 e S1.'),
      'pars interarticularis defect': r('Defeito da parte interarticular', 'Falha no istmo de L5, o pescoço do cachorrinho.',
        'A parte interarticular é a ponte de osso entre as facetas articulares de cima e de baixo. Movimentos repetidos de extensão, como em ginastas e jogadores de futebol americano, causam fratura por estresse nessa ponte: a espondilólise. Na incidência oblíqua, aparece como uma coleira no pescoço do cachorrinho escocês. Com os dois lados quebrados, a vértebra pode escorregar.'),
      'inverted Napoleon hat sign': r('Sinal do chapéu de Napoleão invertido', 'No frontal, L5 aparece como um chapéu de bicorne de cabeça para baixo.',
        'Quando L5 escorrega muito para a frente e se inclina, no frontal vemos o corpo vertebral de frente e de cima ao mesmo tempo. Ele se sobrepõe ao sacro com a forma de um chapéu de Napoleão de cabeça para baixo. O sinal indica espondilolistese de alto grau de L5 sobre S1.'),
    },
    achados: [
      'Defeito bilateral das partes interarticulares de L5.',
      'Escorregamento completo de L5 à frente do sacro — espondiloptose.',
      'Sinal do chapéu de Napoleão invertido no frontal.',
    ],
    armadilhas: [
      'A espondilólise pode não aparecer no perfil: a TC ou as oblíquas mostram o defeito.',
      'Espondilolistese degenerativa ocorre em L4-L5 em idosos, sem defeito na pars.',
      'Adolescentes podem progredir rápido durante o estirão de crescimento.',
    ],
    conduta: 'Ressonância para avaliar as raízes, e artrodese lombossacra com redução parcial e descompressão nos escorregamentos de alto grau.',
    vinheta: {
      cenario: 'Ambulatório de ortopedia',
      identificacao: 'Menina de 15 anos, ginasta.',
      queixa: 'Dor lombar há um ano e dor que desce pelas pernas.',
      historia: 'Treina ginástica artística há oito anos. Há um ano sente dor lombar que piora ao arquear as costas para trás. Há três meses a dor desce pelas duas pernas e ela tem andado com os joelhos dobrados. Os pais notaram que a barriga ficou mais saliente.',
      antecedentes: [
        'Pessoais: sem doenças',
        'Pessoais: estirão de crescimento no último ano',
        'Familiares: pai com espondilólise',
        'Hábitos: treina 20 horas por semana',
      ],
      vitais: { pa: '108 × 66 mmHg', fc: '68 bpm', fr: '14 irpm', satO2: '99% em ar ambiente', temp: '36,5 °C' },
      exame: [
        'Degrau palpável na transição lombossacra',
        'Isquiotibiais muito encurtados',
        'Marcha com joelhos e quadris fletidos',
        'Tronco encurtado com abdome protruso',
      ],
      pedido: 'Ginasta adolescente com dor lombar em extensão, degrau lombossacro e marcha com joelhos fletidos: a pergunta é o grau do escorregamento.',
      pergunta: 'Radiografias da coluna lombossacra. Qual é o achado que responde à pergunta clínica?',
      achado: 'Espondiloptose de L5 sobre o sacro',
      veredito: 'Espondilólise bilateral de L5 com espondiloptose e sinal do chapéu de Napoleão invertido',
      correlacao: 'Anos de extensão repetida da coluna na ginástica quebraram as duas partes interarticulares de L5. Sem essa trava, e com o estirão de crescimento, L5 escorregou inteira à frente do sacro. O degrau palpável, o tronco encurtado e a barriga saliente vêm do escorregamento. As raízes esticadas encurtam os isquiotibiais e causam a marcha típica.',
      distratores: [
        d('Espondilolistese degenerativa de L4', 'Ocorre em idosos com artrose das facetas, sem defeito na parte interarticular, e o escorregamento é pequeno. Aqui a paciente é adolescente.'),
        d('Hérnia de disco lombar L5-S1', 'Causa ciática por compressão da raiz, mas sem escorregamento da vértebra nem degrau palpável. Aqui há degrau e escorregamento total.'),
        d('Espondilólise sem escorregamento', 'Tem o defeito na parte interarticular, mas a vértebra fica no lugar, sem degrau nem sinal no frontal. Aqui L5 caiu à frente do sacro.'),
      ],
    },
  },

  'hiperostose-esqueletica-difusa': {
    tema: 'Coluna',
    titulo: 'Hiperostose esquelética idiopática difusa cervical',
    resumo: 'Ossificação em ponte do ligamento longitudinal anterior de C2 a C6 com discos preservados e artrose facetária e uncovertebral inicial.',
    protocolo: 'Radiografias da coluna cervical perfil e AP',
    rotulos: {
      'anterior longitudinal ligament': r('Ossificação do ligamento longitudinal anterior', 'Faixa óssea grossa e ondulada na frente das vértebras, em ponte.',
        'Na hiperostose esquelética idiopática difusa, conhecida como DISH, o ligamento longitudinal anterior e as inserções de tendões se ossificam. O critério clássico exige ponte óssea em pelo menos quatro vértebras seguidas, com os discos relativamente preservados. Ela é mais comum em homens idosos, obesos e diabéticos. Na coluna cervical, a ossificação volumosa pode comprimir o esôfago e causar dificuldade para engolir.',
        'Coluna rígida por DISH fratura com trauma leve, como uma barra: tenha limiar baixo para TC.'),
      facet: r('Artrose das facetas', 'Facetas articulares com sinais iniciais de desgaste.',
        'As facetas são as articulações posteriores da coluna. A artrose delas é comum com a idade e causa dor no pescoço. Na DISH, ela costuma ser discreta, ao contrário da espondilose comum, em que o desgaste dos discos e das facetas domina.'),
      uncovertebral: r('Artrose uncovertebral', 'Pequenos osteófitos nas articulações uncovertebrais, no frontal.',
        'As articulações uncovertebrais, de Luschka, ficam nas bordas laterais dos corpos vertebrais cervicais. Osteófitos nelas podem estreitar os forames por onde saem as raízes e causar dor que irradia para o braço.'),
    },
    achados: [
      'Ossificação do ligamento longitudinal anterior de C2 a C6 em ponte — hiperostose esquelética idiopática difusa.',
      'Espaços discais sem redução significativa.',
      'Artrose facetária e uncovertebral inicial.',
    ],
    armadilhas: [
      'Espondilite anquilosante forma pontes finas, os sindesmófitos, e acomete as sacroilíacas, que na DISH são normais.',
      'Espondilose degenerativa tem discos reduzidos e osteófitos horizontais.',
      'Fraturas em coluna rígida podem ser instáveis mesmo com trauma leve.',
    ],
    conduta: 'Analgesia e fisioterapia, investigação de disfagia com esofagograma se houver sintoma, cirurgia dos osteófitos em disfagia grave e controle de diabetes, obesidade e dislipidemia.',
    vinheta: {
      cenario: 'Ambulatório de clínica médica',
      identificacao: 'Homem de 69 anos, aposentado.',
      queixa: 'Pescoço duro e dificuldade para engolir comprimidos.',
      historia: 'Há anos tem o pescoço rígido, sem muita dor. Nos últimos meses sente que comprimidos grandes e pedaços de carne parecem parar na garganta. Nega emagrecimento e dor ao engolir.',
      antecedentes: [
        'Pessoais: diabetes tipo 2 e obesidade',
        'Pessoais: dislipidemia e gota',
        'Familiares: sem doenças reumáticas',
        'Hábitos: sedentário',
      ],
      vitais: { pa: '142 × 86 mmHg', fc: '76 bpm', fr: '16 irpm', satO2: '97% em ar ambiente', temp: '36,5 °C' },
      exame: [
        'Movimentos do pescoço limitados, pouco dolorosos',
        'Esporões palpáveis no calcanhar',
        'Sacroilíacas indolores',
        'Marcadores inflamatórios normais e HLA-B27 negativo',
      ],
      pedido: 'Rigidez cervical e disfagia em idoso obeso e diabético, com sacroilíacas normais: a pergunta é o padrão da coluna.',
      pergunta: 'Radiografias da coluna cervical. Qual é o achado que responde à pergunta clínica?',
      achado: 'Hiperostose esquelética idiopática difusa',
      veredito: 'Hiperostose esquelética idiopática difusa com ossificação do ligamento longitudinal anterior de C2 a C6',
      correlacao: 'Obesidade, diabetes e dislipidemia favorecem a ossificação dos ligamentos e das inserções de tendões, o que explica também os esporões no calcanhar. A faixa óssea na frente das vértebras deixou o pescoço rígido e, volumosa, empurra o esôfago, o que dá a sensação de comida parando. Sacroilíacas normais e HLA-B27 negativo afastam espondilite.',
      distratores: [
        d('Espondilite anquilosante cervical', 'Forma pontes finas e verticais em homens jovens com dor lombar inflamatória, sacroileíte e HLA-B27 positivo. Aqui o HLA-B27 é negativo.'),
        d('Espondilose cervical degenerativa', 'Reduz os espaços dos discos com osteófitos horizontais, sem a faixa ondulada contínua na frente de quatro vértebras. Aqui os discos estão preservados.'),
        d('Ossificação do ligamento longitudinal posterior', 'Forma faixa óssea atrás dos corpos vertebrais, dentro do canal, e pode comprimir a medula, e não o esôfago. Aqui a ossificação é anterior.'),
      ],
    },
  },
}
