import { d, p, r, type ConteudoCaso } from './casos-imagem-tipos'

/** Raio-X com apontamentos — fraturas do membro inferior e da bacia. Pacientes fictícios. */
export const CASOS_RX_OSSO_2: Record<string, ConteudoCaso> = {
  'fratura-de-segond': {
    tema: 'Fraturas e luxações',
    titulo: 'Fratura de Segond com lipo-hemartrose',
    resumo: 'Pequeno fragmento avulsionado da borda lateral do platô tibial, fratura da região intercondilar anterior e nível de gordura sobre sangue no recesso suprapatelar.',
    protocolo: 'Radiografias do joelho AP e perfil com raio horizontal',
    rotulos: {
      'displaced fracture': r('Avulsão lateral do platô tibial', 'Pequeno fragmento ósseo junto à borda lateral da tíbia.',
        'A fratura de Segond é o arranque de um pequeno fragmento da borda lateral do platô tibial pela cápsula e pelo ligamento anterolateral, quando o joelho gira para dentro com o pé fixo. O fragmento é pequeno, mas o significado é grande: em cerca de 75% dos casos há ruptura do ligamento cruzado anterior, e muitas vezes lesão de menisco.',
        'Fragmento pequeno na borda lateral da tíbia: peça ressonância para o cruzado anterior.'),
      lipohaemarthrosis: r('Lipo-hemartrose', 'Nível líquido-líquido no recesso suprapatelar: gordura sobre sangue.',
        'Quando uma fratura entra na articulação, a gordura da medula óssea escapa junto com o sangue. Na radiografia em perfil com raio horizontal, a gordura, mais leve, flutua sobre o sangue e forma um nível reto. Esse sinal prova que há uma fratura intra-articular, mesmo quando o traço não é visível.'),
    },
    achados: [
      'Fragmento avulsionado da borda lateral do côndilo tibial — fratura de Segond.',
      'Fratura desviada da região intercondilar anterior.',
      'Lipo-hemartrose no recesso suprapatelar.',
    ],
    armadilhas: [
      'O fragmento é pequeno e passa despercebido; procure-o em todo trauma torcional do joelho.',
      'Segond reversa, na borda medial, associa-se a lesão do cruzado posterior.',
      'Lipo-hemartrose só aparece com raio horizontal.',
    ],
    conduta: 'Imobilização provisória, ressonância magnética do joelho e reconstrução do ligamento cruzado anterior com tratamento das lesões associadas.',
    vinheta: {
      cenario: 'Pronto-socorro de ortopedia',
      identificacao: 'Mulher de 23 anos, jogadora de handebol.',
      queixa: 'Joelho direito inchado e instável depois de uma torção no jogo.',
      historia: 'Ao mudar de direção com o pé apoiado, o joelho direito girou para dentro e ela ouviu um estalo. Caiu e não conseguiu continuar. Em duas horas o joelho inchou muito. Sente que o joelho falha ao apoiar.',
      antecedentes: [
        'Pessoais: entorse de tornozelo há um ano',
        'Pessoais: sem doenças',
        'Familiares: sem doenças ósseas',
        'Hábitos: treina cinco vezes por semana',
      ],
      vitais: { pa: '116 × 72 mmHg', fc: '88 bpm', fr: '16 irpm', satO2: '99% em ar ambiente', temp: '36,5 °C' },
      exame: [
        'Derrame articular volumoso de instalação rápida',
        'Teste de Lachman positivo',
        'Dor na borda lateral da tíbia proximal',
        'Punção articular com sangue e gotas de gordura',
      ],
      pedido: 'Torção do joelho com estalo, derrame rápido e Lachman positivo: a pergunta é se a radiografia mostra sinal indireto de lesão ligamentar.',
      pergunta: 'Radiografias do joelho. Qual é o achado que responde à pergunta clínica?',
      achado: 'Fratura de Segond da tíbia',
      veredito: 'Fratura de Segond com lipo-hemartrose, sugerindo lesão do cruzado anterior',
      correlacao: 'O giro do joelho para dentro com o pé fixo esticou a cápsula lateral, que arrancou um fragmento da tíbia, e rompeu o cruzado anterior, o que dá o estalo, o derrame rápido de sangue e o Lachman positivo. As gotas de gordura na punção e o nível na radiografia provam a fratura dentro da articulação.',
      distratores: [
        d('Lesão isolada do menisco medial', 'Causa dor e bloqueio, com derrame que se forma em horas a dias, sem fragmento ósseo nem lipo-hemartrose. O Lachman seria negativo.'),
        d('Luxação da patela', 'Desloca a patela para o lado de fora, com fragmento osteocondral da patela, e não da borda lateral da tíbia. O mecanismo também envolve rotação, mas a patela fica fora do lugar.'),
        d('Fratura de Segond reversa', 'Arranca um fragmento da borda medial da tíbia e se associa a lesão do ligamento cruzado posterior, não do anterior. Aqui o fragmento é lateral.'),
      ],
    },
  },

  'fratura-do-amante': {
    tema: 'Fraturas e luxações',
    titulo: 'Fratura do calcâneo após queda de altura',
    resumo: 'Fratura fragmentada do calcâneo direito com desvio mínimo, traço visível na incidência axial e edema de partes moles.',
    protocolo: 'Radiografias do calcâneo em perfil e axial',
    rotulos: {
      'Soft tissue swelling': r('Edema do retropé', 'Partes moles aumentadas em volta do calcanhar.',
        'O calcâneo tem pouca cobertura de partes moles, e o edema após a fratura é rápido e intenso. A pele pode formar bolhas, e a cirurgia costuma esperar o edema diminuir. A elevação do membro é parte importante do tratamento inicial.'),
      fracture: r('Fratura do calcâneo', 'Traços no corpo do calcâneo no perfil.',
        'A fratura do amante recebeu esse nome pelas quedas de quem pulava a janela para fugir do marido traído. A queda de pé empurra o tálus contra o calcâneo. No perfil, o ângulo de Böhler, entre a tuberosidade e a faceta posterior, normalmente de 20 a 40 graus, diminui quando o calcâneo afunda.',
        'Fratura de calcâneo por queda: procure fratura da coluna lombar e do outro calcâneo.'),
      'fracture line': r('Traço na incidência axial', 'Traço atravessando o calcâneo na incidência de Harris.',
        'A incidência axial, ou de Harris, mostra o calcâneo de baixo para cima e revela traços que no perfil se sobrepõem. Ela mostra também o alargamento do calcâneo e o desvio em varo ou valgo. A TC completa a avaliação da articulação subtalar.'),
    },
    apontamentosProprios: [
      p(0, 0.55, 0.38, -60, 'Faceta posterior do calcâneo', 'Superfície que articula com o tálus, referência do ângulo de Böhler.',
        'O ângulo de Böhler é formado por duas linhas no perfil: uma do ponto mais alto da tuberosidade ao ponto mais alto da faceta posterior, e outra deste ponto ao processo anterior. O normal fica entre 20 e 40 graus. Quando a faceta posterior afunda, o ângulo diminui, sinal de fratura articular.'),
      p(0, 0.78, 0.45, -30, 'Tuberosidade do calcâneo', 'Parte posterior do calcâneo, onde se insere o tendão de Aquiles.',
        'A tuberosidade é o ponto de apoio do calcanhar e de inserção do Aquiles. Fraturas que a separam do corpo do calcâneo podem ser puxadas pelo tendão e ameaçar a pele de trás do calcanhar, uma urgência ortopédica.'),
    ],
    achados: [
      'Fratura fragmentada do calcâneo direito com desvio mínimo dos fragmentos.',
      'Traço de fratura evidente na incidência axial.',
      'Edema de partes moles.',
    ],
    armadilhas: [
      'Fratura sem desvio pode ser sutil no perfil: peça a axial.',
      'Ângulo de Böhler reduzido indica afundamento da faceta posterior.',
      'Até 10% têm fratura de coluna associada.',
    ],
    conduta: 'Elevação, gelo e imobilização; TC para avaliar a articulação subtalar e tratamento conservador sem carga nas fraturas sem desvio, cirurgia nas desviadas.',
    vinheta: {
      cenario: 'Pronto-socorro de ortopedia',
      identificacao: 'Homem de 35 anos, vendedor.',
      queixa: 'Dor forte no calcanhar direito depois de pular de um muro.',
      historia: 'Pulou de um muro de cerca de três metros ao fugir de um cachorro e caiu de pé sobre o calcanhar direito. Não consegue apoiar o pé. O calcanhar inchou e ficou roxo na planta.',
      antecedentes: [
        'Pessoais: sem fraturas anteriores',
        'Pessoais: sem doenças',
        'Familiares: sem doenças ósseas',
        'Hábitos: sedentário',
      ],
      vitais: { pa: '132 × 82 mmHg', fc: '92 bpm', fr: '16 irpm', satO2: '99% em ar ambiente', temp: '36,5 °C' },
      exame: [
        'Edema e equimose plantar no calcanhar direito',
        'Dor à compressão lateral do calcâneo',
        'Coluna lombar sem dor',
        'Pulsos pediosos presentes',
      ],
      pedido: 'Queda de altura sobre o calcanhar com dor à compressão do calcâneo: a pergunta é se há fratura e quanto ela desviou.',
      pergunta: 'Radiografias do calcâneo. Qual é o achado que responde à pergunta clínica?',
      achado: 'Fratura do calcâneo',
      veredito: 'Fratura fragmentada do calcâneo direito com desvio mínimo',
      correlacao: 'A queda de três metros sobre o calcanhar empurrou o tálus contra o calcâneo, que se partiu em fragmentos. A equimose plantar e a dor à compressão lateral são típicas. O desvio mínimo favorece tratamento conservador, mas a TC deve confirmar se a articulação subtalar foi atingida.',
      distratores: [
        d('Fasciite plantar aguda', 'Dói na planta ao dar os primeiros passos pela manhã, sem trauma de alta energia, equimose nem traço de fratura. A radiografia é normal.'),
        d('Ruptura do tendão de Aquiles', 'Dói atrás do tornozelo com falha palpável e teste de Thompson positivo, com o calcâneo íntegro. Ocorre em arrancadas e não em quedas de altura.'),
        d('Fratura do tálus', 'Também ocorre em quedas, mas atinge o osso acima do calcâneo, com risco de necrose do corpo do tálus. A dor seria no tornozelo e não no calcanhar.'),
      ],
    },
  },

  'fratura-do-plato-tibial': {
    tema: 'Fraturas e luxações',
    titulo: 'Fratura do platô tibial lateral Schatzker II',
    resumo: 'Fratura com afundamento e cominuição do platô tibial lateral estendendo-se à eminência intercondilar, traço vertical para a metáfise e derrame articular.',
    protocolo: 'Radiografias do joelho AP e perfil',
    rotulos: {
      'Intercondylar eminence': r('Eminência intercondilar', 'O traço chega à eminência entre os platôs.',
        'A eminência intercondilar é onde se inserem os ligamentos cruzados. Fratura que chega a ela pode afrouxar esses ligamentos. Isso indica que a lesão é mais extensa que um simples afundamento lateral e deve ser avaliada por TC.'),
      'Depressed comminuted fracture': r('Afundamento do platô lateral', 'Superfície articular lateral afundada e fragmentada.',
        'O platô lateral é o mais atingido, porque recebe o impacto do côndilo femoral quando o joelho é forçado em valgo, como num para-choque batendo no lado de fora do joelho. A classificação de Schatzker separa os tipos: o I é só a cunha, o II é cunha com afundamento e o III é só afundamento. Afundamento articular maior que 2 a 3 mm costuma indicar cirurgia.',
        'Fratura do platô em paciente com dor intensa na perna: monitore a síndrome compartimental.'),
      'vertical lucency': r('Traço vertical para a metáfise', 'Linha clara descendo do platô lateral para a metáfise.',
        'O traço vertical separa uma cunha lateral do resto da tíbia, característica do tipo II. A cunha precisa ser reduzida e sustentada com placa lateral para que a superfície articular elevada não volte a afundar.'),
      'joint effusion': r('Derrame articular', 'Líquido no recesso suprapatelar no perfil.',
        'Toda fratura que entra na articulação sangra para dentro dela. Um derrame grande depois de trauma, com radiografia aparentemente normal, deve levantar suspeita de fratura oculta do platô, que a TC mostra.'),
    },
    achados: [
      'Fratura com afundamento e cominuição do platô tibial lateral estendendo-se à eminência intercondilar.',
      'Traço vertical do platô lateral para a metáfise e em direção à diáfise — Schatzker II.',
      'Platô medial, côndilos femorais e patela normais.',
      'Derrame articular.',
    ],
    armadilhas: [
      'O afundamento é subestimado na radiografia: a TC mede o degrau.',
      'Lesão do menisco lateral é comum e pode ficar presa na fratura.',
      'Fraturas do platô medial, tipo IV, associam-se a lesões vasculares e luxação do joelho.',
    ],
    conduta: 'TC do joelho, redução com elevação do fragmento afundado, enxerto ósseo e placa lateral de sustentação, sem carga por algumas semanas.',
    vinheta: {
      cenario: 'Sala de trauma',
      identificacao: 'Mulher de 52 anos, comerciante.',
      queixa: 'Dor forte no joelho esquerdo depois de ser atropelada.',
      historia: 'Atravessava a rua quando o para-choque de um carro em baixa velocidade bateu no lado de fora do joelho esquerdo. Caiu e não conseguiu se levantar. O joelho inchou muito em pouco tempo.',
      antecedentes: [
        'Pessoais: menopausa há três anos',
        'Pessoais: sem fraturas anteriores',
        'Familiares: mãe com osteoporose',
        'Hábitos: sedentária',
      ],
      vitais: { pa: '138 × 84 mmHg', fc: '94 bpm', fr: '18 irpm', satO2: '98% em ar ambiente', temp: '36,5 °C' },
      exame: [
        'Joelho esquerdo com derrame volumoso',
        'Escoriação na face lateral do joelho',
        'Dor à palpação do platô lateral',
        'Compartimentos da perna macios e pulsos presentes',
      ],
      pedido: 'Impacto lateral no joelho com derrame e dor no platô lateral: a pergunta é se há fratura articular e qual o padrão.',
      pergunta: 'Radiografias do joelho. Qual é o achado que responde à pergunta clínica?',
      achado: 'Fratura do platô tibial lateral',
      veredito: 'Fratura do platô tibial lateral Schatzker II com afundamento e derrame',
      correlacao: 'O para-choque forçou o joelho em valgo e o côndilo femoral lateral bateu como um martelo no platô lateral, que afundou e abriu em cunha. A osteopenia da menopausa favorece o afundamento. O sangue da fratura dentro da articulação causa o derrame volumoso.',
      distratores: [
        d('Fratura do platô tibial medial', 'Ocorre por força em varo, é menos comum e associa-se a luxação do joelho e lesão vascular, com o platô lateral íntegro. Aqui o lado é lateral.'),
        d('Lesão do ligamento colateral medial', 'Também ocorre por valgo e dói no lado de dentro, mas a radiografia não mostra afundamento nem traço no platô. Aqui há afundamento ósseo.'),
        d('Fratura da cabeça da fíbula', 'Pode acompanhar o trauma lateral do joelho, mas atinge a fíbula e ameaça o nervo fibular, sem afundar a superfície da tíbia. Aqui o platô afundou.'),
      ],
    },
  },

  'fratura-de-maisonneuve': {
    tema: 'Fraturas e luxações',
    titulo: 'Fratura de Maisonneuve com instabilidade do tornozelo',
    resumo: 'Fraturas sem desvio dos maléolos medial e posterior, alargamento do encaixe do tornozelo com desvio lateral do tálus e fratura espiral da fíbula proximal.',
    protocolo: 'Radiografias do tornozelo AP e perfil e da perna',
    series: ['Tornozelo AP', 'Tornozelo perfil', 'Perna'],
    rotulos: {
      'soft tissue swelling': r('Edema periarticular', 'Partes moles aumentadas em volta do tornozelo.',
        'O edema em volta do tornozelo é inespecífico, mas mostra onde estão as lesões. Edema medial com dor, sem fratura visível da fíbula distal, deve fazer o médico palpar e radiografar a perna inteira.'),
      'Widening of the ankle mortise': r('Encaixe do tornozelo alargado', 'Espaço medial entre o tálus e o maléolo medial aumentado.',
        'O encaixe é formado pela tíbia, pela fíbula e pelo tálus, mantidos juntos pela sindesmose, os ligamentos entre a tíbia e a fíbula. Espaço medial maior que 4 mm, ou maior que o superior, indica que o tálus escorregou para fora e o tornozelo está instável.',
        'Espaço medial alargado sem fratura da fíbula distal: radiografe a fíbula inteira.'),
      'Tiny avulsion fracture': r('Pequena avulsão do maléolo medial', 'Pequeno fragmento na ponta do maléolo medial.',
        'O ligamento deltoide, no lado medial, pode romper ou arrancar a ponta do maléolo medial. A lesão medial é a primeira etapa do mecanismo de rotação externa que termina na fratura alta da fíbula.'),
      'medial malleolus fracture': r('Fratura do maléolo medial', 'Traço sem desvio no maléolo medial.',
        'A fratura do maléolo medial no tornozelo com encaixe alargado indica lesão de mais de um lado do anel do tornozelo. O tornozelo funciona como um anel: quando ele quebra em dois lugares, fica instável e geralmente precisa de fixação.'),
      'posterior malleolus fracture': r('Fratura do maléolo posterior', 'Traço sem desvio na borda posterior da tíbia, no perfil.',
        'O maléolo posterior é a borda de trás da tíbia distal, onde se prende um dos ligamentos da sindesmose. Sua fratura faz parte do mesmo mecanismo de rotação e reforça a instabilidade da sindesmose.'),
      'Achilles enthesopathy': r('Entesopatia calcificada do Aquiles', 'Calcificação na inserção do tendão no calcâneo.',
        'Calcificação na inserção do Aquiles é achado degenerativo comum e antigo. Não tem relação com o trauma, mas deve ser descrita e pode causar dor crônica no calcanhar. É um achado de longa data.'),
      'spiral fracture of fibula': r('Fratura espiral da fíbula proximal', 'Traço em espiral na fíbula alta, perto do joelho.',
        'A fratura de Maisonneuve é a fratura alta da fíbula com lesão da sindesmose e do lado medial do tornozelo. A rotação externa do pé rompe o deltoide, sobe rasgando a membrana entre a tíbia e a fíbula e sai quebrando a fíbula perto do joelho. Se o médico radiografa só o tornozelo, a lesão passa despercebida.'),
    },
    achados: [
      'Fraturas sem desvio dos maléolos medial e posterior, com pequena avulsão na ponta do maléolo medial.',
      'Alargamento do encaixe do tornozelo com desvio lateral do tálus — instabilidade.',
      'Fratura espiral da diáfise proximal da fíbula — fratura de Maisonneuve.',
      'Edema periarticular e entesopatia calcificada do tendão de Aquiles.',
    ],
    armadilhas: [
      'Sempre palpe a fíbula inteira no trauma de tornozelo.',
      'O nervo fibular passa perto da fratura alta e pode ser lesado.',
      'Lesão da sindesmose não tratada leva a artrose precoce do tornozelo.',
    ],
    conduta: 'Fixação cirúrgica da sindesmose com parafusos ou botões de sutura, redução do tálus no encaixe e fixação dos maléolos quando indicado.',
    vinheta: {
      cenario: 'Pronto-socorro de ortopedia',
      identificacao: 'Homem de 44 anos, jogador de futebol amador.',
      queixa: 'Tornozelo direito inchado e dor na parte alta da perna depois de torção.',
      historia: 'Durante uma partida, o pé direito ficou preso no gramado e o corpo girou por cima. Sentiu dor no tornozelo e, depois, na parte de cima da perna, perto do joelho. Não consegue apoiar.',
      antecedentes: [
        'Pessoais: entorses de tornozelo anteriores',
        'Pessoais: dor crônica no calcanhar',
        'Familiares: sem doenças ósseas',
        'Hábitos: joga futebol aos fins de semana',
      ],
      vitais: { pa: '128 × 80 mmHg', fc: '86 bpm', fr: '16 irpm', satO2: '99% em ar ambiente', temp: '36,5 °C' },
      exame: [
        'Edema e dor no maléolo medial',
        'Dor à palpação da fíbula proximal',
        'Teste de compressão da perna positivo',
        'Sensibilidade do dorso do pé normal',
      ],
      pedido: 'Torção em rotação externa com dor medial no tornozelo e na fíbula proximal: a pergunta é a extensão da lesão.',
      pergunta: 'Radiografias do tornozelo e da perna. Qual é o achado que responde à pergunta clínica?',
      achado: 'Fratura de Maisonneuve da fíbula',
      veredito: 'Fratura de Maisonneuve com lesão da sindesmose e alargamento do encaixe',
      correlacao: 'O corpo girou sobre o pé preso e a rotação externa rompeu o lado medial do tornozelo, rasgou a sindesmose para cima e saiu quebrando a fíbula perto do joelho. Por isso a dor alta na perna e o teste de compressão positivo. O tálus escorregou para fora e o encaixe alargou, o que torna a lesão instável.',
      distratores: [
        d('Entorse lateral do tornozelo', 'É a lesão mais comum, com dor no ligamento talofibular anterior, sem alargamento do encaixe nem fratura alta da fíbula. Aqui o lado medial está lesado e a fíbula alta dói.'),
        d('Fratura bimaleolar da fíbula distal', 'Quebra os maléolos medial e lateral perto do tornozelo, com a fíbula proximal íntegra. Aqui a fratura da fíbula fica perto do joelho, longe do tornozelo.'),
        d('Fratura isolada do maléolo medial', 'Pode acontecer com o encaixe estável e sem lesão da sindesmose, e não explica a dor na fíbula alta. Aqui o encaixe está alargado e o tálus desviado para fora.'),
      ],
    },
  },

  'fratura-por-estresse': {
    tema: 'Fraturas e luxações',
    titulo: 'Fratura por estresse do terceiro metatarso',
    resumo: 'Linha esclerótica na diáfise do terceiro metatarso direito sem destruição cortical nem calo, com cistos subcondrais na cabeça do primeiro metatarso e calcificação na perna.',
    protocolo: 'Radiografias do pé oblíqua e AP',
    rotulos: {
      'soft tissue calcification': r('Calcificação de partes moles', 'Calcificação na face medial da perna distal, incidental.',
        'Calcificações de partes moles na perna podem ser vasculares, flebólitos ou sequela de trauma antigo. Esta não tem relação com a dor no pé, mas deve ser descrita. Achados incidentais precisam ser relatados sem desviar o foco do problema principal.'),
      'sclerotic line': r('Linha esclerótica na diáfise do terceiro metatarso', 'Faixa densa transversa na diáfise, sem traço nem calo.',
        'A fratura por estresse acontece quando o osso recebe cargas repetidas maiores do que consegue reparar, como em corredores e recrutas militares. No início, a radiografia é normal. Depois de duas a três semanas, aparece uma linha densa, que é osso novo tentando consertar microfraturas, e depois o calo periosteal. A ressonância mostra o edema ósseo desde o início.',
        'Dor no antepé que aumenta com o exercício e melhora com repouso: pense em fratura de marcha.'),
      'subchondral cysts': r('Cistos subcondrais no primeiro metatarso', 'Pequenos cistos na cabeça do primeiro metatarso.',
        'Cistos subcondrais na cabeça do primeiro metatarso são comuns em degeneração da articulação do hálux, como no hálux rígido, ou em gota. Aqui são achado associado e não explicam a dor no meio do pé.'),
    },
    achados: [
      'Linha esclerótica na diáfise do terceiro metatarso direito, sem destruição cortical, reação periosteal ou calo — fratura por estresse.',
      'Cistos subcondrais na cabeça do primeiro metatarso.',
      'Calcificação de partes moles na face medial da perna distal.',
      'Espaços articulares preservados.',
    ],
    armadilhas: [
      'Radiografia normal nas primeiras semanas não exclui fratura por estresse.',
      'Fratura por estresse em atleta mulher pede investigar a tríade da atleta: pouca energia, alteração menstrual e baixa massa óssea.',
      'Fratura do quinto metatarso na junção metafisodiafisária consolida mal.',
    ],
    conduta: 'Repouso relativo com calçado rígido ou bota por quatro a seis semanas, retorno gradual à atividade e investigação de fatores de risco como baixa massa óssea e erros de treino.',
    vinheta: {
      cenario: 'Ambulatório de medicina esportiva',
      identificacao: 'Mulher de 29 anos, corredora amadora.',
      queixa: 'Dor no meio do pé direito há quatro semanas que piora ao correr.',
      historia: 'Está treinando para uma maratona e aumentou a distância semanal de 30 para 70 km em um mês. Há quatro semanas tem dor no dorso do pé direito que começa durante a corrida e melhora com repouso. Agora dói até ao caminhar. Trocou o tênis há pouco.',
      antecedentes: [
        'Pessoais: menstruação irregular nos últimos meses',
        'Pessoais: dieta restrita para perder peso',
        'Familiares: mãe com osteoporose',
        'Hábitos: corre seis vezes por semana',
      ],
      vitais: { pa: '104 × 64 mmHg', fc: '56 bpm', fr: '14 irpm', satO2: '99% em ar ambiente', temp: '36,4 °C' },
      exame: [
        'Dor localizada à palpação da diáfise do terceiro metatarso',
        'Edema discreto no dorso do pé',
        'Teste do diapasão doloroso',
        'Índice de massa corporal de 18',
      ],
      pedido: 'Dor no antepé que piora com o exercício após aumento rápido de carga em corredora com dieta restrita: a pergunta é se há fratura por estresse.',
      pergunta: 'Radiografias do pé. Qual é o achado que responde à pergunta clínica?',
      achado: 'Fratura de estresse do metatarso',
      veredito: 'Fratura por estresse da diáfise do terceiro metatarso',
      correlacao: 'O aumento rápido de 30 para 70 km por semana sobrecarregou o metatarso, e a dieta restrita com menstruação irregular sugere pouca energia e osso frágil. As microfraturas se acumularam e, depois de semanas, o osso reagiu formando a linha esclerótica. A dor localizada e o teste do diapasão confirmam o ponto.',
      distratores: [
        d('Neuroma de Morton', 'Dói entre o terceiro e o quarto dedo com choque ao apertar o antepé, sem dor na diáfise nem linha esclerótica. A dor é neuropática.'),
        d('Metatarsalgia mecânica', 'Dói na planta, sob as cabeças dos metatarsos, pela pisada, e a radiografia não mostra alteração na diáfise. Não há ponto doloroso na diáfise.'),
        d('Osteoma osteoide do metatarso', 'Causa dor noturna que melhora com anti-inflamatório, com nicho claro cercado de esclerose espessa, e não linha transversa. É raro no pé.'),
      ],
    },
  },

  'fratura-do-anel-pelvico': {
    tema: 'Fraturas e luxações',
    titulo: 'Lesão em livro aberto da pelve',
    resumo: 'Diástase da sínfise púbica de 5 cm com alargamento da articulação sacroilíaca esquerda, sem fraturas.',
    protocolo: 'Radiografia de bacia AP na sala de trauma',
    rotulos: {
      'left sacroiliac joint.': r('Sacroilíaca esquerda alargada', 'Espaço da articulação sacroilíaca esquerda aumentado.',
        'A pelve é um anel: se abre na frente, tem de abrir atrás também. Na compressão anteroposterior, a pelve se abre como um livro. No estágio III de Young e Burgess, os ligamentos sacroilíacos anteriores e posteriores rompem, e a hemipelve fica instável em rotação e na vertical.',
        'Lesão em livro aberto com choque: amarre um lençol ou cinta pélvica na altura dos trocânteres.'),
      'symphysis pubis': r('Diástase da sínfise púbica', 'Sínfise púbica aberta em 5 cm.',
        'A sínfise normal tem menos de 5 mm. Acima de 2,5 cm, os ligamentos do assoalho pélvico e os sacroilíacos anteriores também romperam. O volume da pelve aumenta muito e os plexos venosos atrás dela sangram para um espaço maior, o que pode levar ao choque. A bexiga e a uretra, logo atrás do púbis, também correm risco.'),
    },
    achados: [
      'Alargamento da sínfise púbica de 5 cm.',
      'Alargamento da articulação sacroilíaca esquerda.',
      'Sem fraturas visíveis — lesão por compressão anteroposterior estágio III.',
    ],
    armadilhas: [
      'Cinta pélvica bem colocada pode fechar a sínfise e esconder a lesão na radiografia.',
      'Sangue no meato uretral contraindica a sonda vesical antes da uretrografia.',
      'A TC mostra melhor a parte posterior do anel.',
    ],
    conduta: 'Cinta pélvica, reposição volêmica com sangue, tamponamento pré-peritoneal ou embolização se instável, avaliação da uretra e da bexiga e fixação da sínfise e da sacroilíaca.',
    vinheta: {
      cenario: 'Sala de trauma',
      identificacao: 'Homem de 38 anos, motociclista.',
      queixa: 'Dor intensa na bacia depois de colisão frontal de moto.',
      historia: 'Bateu de frente com a moto contra um carro e o tanque atingiu a região da bacia. Chegou consciente, com dor intensa no púbis e na bacia, sem conseguir mexer as pernas pela dor.',
      antecedentes: [
        'Pessoais: sem doenças',
        'Pessoais: sem cirurgias',
        'Familiares: sem doenças relevantes',
        'Hábitos: etilista social',
      ],
      vitais: { pa: '86 × 52 mmHg', fc: '132 bpm', fr: '26 irpm', satO2: '96% em ar ambiente', temp: '35,9 °C' },
      exame: [
        'Membros inferiores em rotação externa',
        'Equimose perineal e escrotal',
        'Sangue no meato uretral',
        'FAST sem líquido livre no abdome',
      ],
      pedido: 'Trauma de alta energia com choque, pernas rodadas para fora e sangue no meato: a pergunta é a lesão do anel pélvico.',
      pergunta: 'Radiografia de bacia. Qual é o achado que responde à pergunta clínica?',
      achado: 'Lesão pélvica em livro aberto',
      veredito: 'Lesão por compressão anteroposterior estágio III com diástase púbica e sacroilíaca',
      correlacao: 'O tanque da moto empurrou as asas ilíacas para fora e a pelve se abriu como um livro: a sínfise afastou 5 cm e a sacroilíaca esquerda abriu. As veias atrás da pelve sangram num espaço maior, e o FAST negativo indica que o sangue está na pelve. O sangue no meato aponta para lesão de uretra.',
      distratores: [
        d('Fratura dos ramos por compressão lateral', 'Ocorre em impacto lateral, com fraturas horizontais dos ramos e pelve fechada, sem diástase da sínfise. As pernas rodariam para dentro, e a pelve fecharia em vez de abrir.'),
        d('Lesão por cisalhamento vertical', 'Sobe uma hemipelve em relação à outra, após queda de pé de grande altura, com desvio vertical e não abertura. Aqui não há desvio vertical.'),
        d('Fratura isolada do acetábulo', 'Atinge a articulação do quadril, com a sínfise e a sacroilíaca íntegras. Aqui a sínfise abriu 5 cm e a sacroilíaca esquerda alargou, sem traço no acetábulo.'),
      ],
    },
  },
}
