import { d, p, r, type ConteudoCaso } from './casos-imagem-tipos'

/** Raio-X com apontamentos — artropatias. Pacientes fictícios. */
export const CASOS_RX_OSSO_3: Record<string, ConteudoCaso> = {
  'tendinite-calcarea': {
    tema: 'Artropatias',
    titulo: 'Tendinite calcária do infraespinal',
    resumo: 'Calcificação amorfa projetada na inserção do tendão infraespinal na grande tuberosidade do úmero, em paciente com marca-passo.',
    protocolo: 'Radiografia do ombro AP',
    rotulos: {
      pacemaker: r('Marca-passo', 'Gerador e eletrodo projetados no tórax superior.',
        'Dispositivos implantados devem ser descritos em todo laudo. Marca-passo é uma contraindicação relativa à ressonância, o que importa se for preciso investigar o ombro com mais detalhe. Muitos modelos atuais são compatíveis, mas isso precisa ser verificado antes do exame.'),
      opacity: r('Calcificação no infraespinal', 'Depósito calcificado amorfo junto à grande tuberosidade.',
        'Na tendinite calcária, cristais de hidroxiapatita de cálcio se depositam dentro dos tendões do manguito rotador, mais no supraespinal e depois no infraespinal. O depósito pode ficar quieto por anos. Na fase de reabsorção, ele fica mais mole e mal definido, e a inflamação causa dor aguda muito intensa. Depósitos densos e bem definidos tendem a estar na fase de formação.',
        'Rodar o úmero na radiografia separa o supraespinal, em cima, do infraespinal, atrás.'),
    },
    apontamentosProprios: [
      p(0, 0.36, 0.32, -60, 'Espaço subacromial preservado', 'Distância normal entre o acrômio e a cabeça do úmero.',
        'Entre o acrômio e a cabeça do úmero passam o tendão supraespinal e a bolsa subacromial. Espaço menor que 7 mm sugere ruptura extensa do manguito, porque a cabeça sobe sem o tendão para segurá-la. Aqui o espaço está preservado, o que combina com tendinite e não com ruptura.'),
      p(0, 0.805, 0.62, 0, 'Eletrodos do marca-passo', 'Fios que descem do gerador para o coração.',
        'Os eletrodos saem do gerador, entram pela veia subclávia e descem até as câmaras direitas. Ao descrever uma radiografia de ombro em portador de marca-passo, vale conferir se os fios estão contínuos, sem dobras ou fraturas, porque a lesão do fio pode deixar o paciente sem estímulo.'),
    ],
    achados: [
      'Pequena calcificação amorfa projetada na inserção do tendão infraespinal na grande tuberosidade do úmero.',
      'Marca-passo cardíaco.',
      'Articulação glenoumeral sem alterações.',
    ],
    armadilhas: [
      'Calcificação mole e mal definida com dor aguda indica fase de reabsorção.',
      'Calcificação que migra para a bursa pode causar bursite aguda.',
      'Artropatia por cristais de pirofosfato calcifica cartilagem, não tendões.',
    ],
    conduta: 'Analgesia, anti-inflamatório e fisioterapia; nos casos persistentes, lavagem guiada por ultrassom, ondas de choque ou cirurgia.',
    vinheta: {
      cenario: 'Ambulatório de ortopedia',
      identificacao: 'Mulher de 58 anos, costureira.',
      queixa: 'Dor intensa no ombro direito há cinco dias, pior à noite.',
      historia: 'Há cinco dias acordou com dor muito forte no ombro direito, sem trauma. A dor piora à noite e ao levantar e girar o braço para fora. Já teve dores menores no mesmo ombro há um ano, que passaram sozinhas.',
      antecedentes: [
        'Pessoais: bloqueio atrioventricular com marca-passo há três anos',
        'Pessoais: diabetes',
        'Familiares: sem doenças reumáticas',
        'Hábitos: trabalho repetitivo com os braços',
      ],
      vitais: { pa: '132 × 80 mmHg', fc: '70 bpm', fr: '16 irpm', satO2: '98% em ar ambiente', temp: '36,8 °C' },
      exame: [
        'Dor à palpação da grande tuberosidade posterior',
        'Rotação externa resistida muito dolorosa',
        'Amplitude passiva preservada',
        'Sem sinais de infecção',
      ],
      pedido: 'Dor aguda no ombro sem trauma, com rotação externa resistida dolorosa: a pergunta é se há depósito de cálcio no manguito.',
      pergunta: 'Radiografia do ombro. Qual é o achado que responde à pergunta clínica?',
      achado: 'Tendinite calcária do infraespinal',
      veredito: 'Tendinite calcária do infraespinal em provável fase de reabsorção',
      correlacao: 'O depósito de hidroxiapatita ficou quieto por um tempo e agora começou a ser reabsorvido, o que provoca inflamação intensa e a dor aguda à noite. O infraespinal faz a rotação externa, por isso o movimento resistido dói. O marca-passo limita a ressonância, mas a radiografia já mostra o depósito.',
      distratores: [
        d('Ruptura completa do supraespinal', 'Causa fraqueza para elevar o braço e queda do braço, com a radiografia muitas vezes normal ou com subida da cabeça do úmero. Aqui há calcificação.'),
        d('Capsulite adesiva do ombro', 'Limita o movimento passivo em todas as direções, com rigidez progressiva por meses, e a radiografia é normal. Aqui o movimento passivo é livre.'),
        d('Artrite séptica glenoumeral', 'Dá febre, ombro quente e dor a qualquer movimento, com derrame articular e marcadores inflamatórios altos. Aqui não há febre nem derrame.'),
      ],
    },
  },

  'artrite-reumatoide-das-maos': {
    tema: 'Artropatias',
    titulo: 'Artrite reumatoide avançada das mãos',
    resumo: 'Anquilose do carpo e das carpometacarpais, reabsorção do estiloide ulnar, cistos subcondrais, erosões e subluxações metacarpofalângicas e deformidade em botoeira, nas duas mãos.',
    protocolo: 'Radiografias das mãos PA',
    series: ['Mão direita', 'Mão esquerda'],
    rotulos: {
      'ankylosis of the carpus and 2n': r('Anquilose do carpo', 'Ossos do carpo e bases dos metacarpos fundidos.',
        'Na artrite reumatoide, a sinóvia inflamada, o pannus, destrói a cartilagem e o osso. Com anos de doença, os ossos do carpo perdem os espaços entre si e se fundem num bloco. A anquilose do carpo é sinal de doença antiga e grave, e limita muito o movimento do punho.'),
      'Multiple subchondral cysts see': r('Cistos subcondrais no rádio', 'Pequenas áreas claras sob a superfície articular do rádio.',
        'O pannus invade o osso logo abaixo da cartilagem e forma cistos. Junto com as erosões, os cistos mostram que a inflamação está destruindo o osso de dentro para fora. Eles enfraquecem o osso.'),
      'Positive ulnar variance': r('Variância ulnar positiva', 'Ulna mais longa que o rádio no punho.',
        'Quando a ulna fica mais longa que o rádio, ela bate no carpo e pode causar dor e lesão da fibrocartilagem triangular. Na artrite reumatoide, o colapso do carpo e a destruição da articulação radioulnar distal mudam essas relações.'),
      'Partial ankylosis with subluxa': r('Erosões e subluxações metacarpofalângicas', 'Articulações dos dedos com erosões, desvio e fusão parcial.',
        'As metacarpofalângicas são alvos clássicos da artrite reumatoide. A sinovite destrói as cápsulas e os ligamentos, e os dedos escorregam para o lado ulnar e para baixo, a deformidade em ventania. As erosões começam nas margens das articulações, nas áreas sem cartilagem, chamadas áreas nuas.',
        'Na artrite reumatoide as interfalângicas distais costumam ser poupadas; se acometidas, pense em psoríase ou artrose.'),
      'boutonniere deformity': r('Deformidade em botoeira', 'Interfalângica proximal fletida e distal estendida.',
        'Na botoeira, a sinovite da interfalângica proximal rompe a banda central do tendão extensor, e a articulação passa por entre as bandas laterais como um botão por uma casa. O dedo fica com a proximal dobrada e a distal esticada. É uma deformidade típica da artrite reumatoide avançada.'),
      'resorption of the ulnar styloi': r('Reabsorção do estiloide ulnar', 'A ponta da ulna desapareceu por erosão.',
        'O estiloide ulnar é um dos primeiros locais de erosão na artrite reumatoide, porque fica coberto por uma sinóvia muito inflamada. A reabsorção completa mostra doença de longa data. Junto com a destruição da radioulnar distal, pode levar à ruptura dos tendões extensores dos dedos.'),
      'Subchondral cyst formation wit': r('Cistos e erosões na mão esquerda', 'Cistos subcondrais com erosões nas articulações da mão esquerda.',
        'O acometimento simétrico, com alterações parecidas nas duas mãos, é uma das características que separam a artrite reumatoide de outras artrites. A comparação entre os lados ajuda a reconhecer o padrão.'),
      'Marked loss of joint space wit': r('Perda acentuada do espaço articular', 'Espaços articulares muito reduzidos de forma uniforme.',
        'Na artrite inflamatória, a cartilagem é destruída de forma uniforme, e o espaço diminui por igual em toda a articulação. Na artrose, a perda é desigual, concentrada na área de mais carga, com osteófitos. Esse detalhe ajuda a separar as duas doenças.'),
    },
    achados: [
      'Anquilose do carpo e das articulações carpometacarpais nas duas mãos.',
      'Reabsorção do estiloide ulnar, completa à esquerda; cistos subcondrais no rádio distal; variância ulnar positiva.',
      'Erosões, subluxações e anquilose parcial das metacarpofalângicas; deformidade em botoeira do indicador.',
      'Perda difusa e uniforme do espaço articular — artrite reumatoide avançada.',
    ],
    armadilhas: [
      'Osteopenia periarticular e edema são os primeiros sinais; erosões aparecem depois.',
      'Ultrassom e ressonância detectam sinovite e erosões antes da radiografia.',
      'Instabilidade atlantoaxial é comum na doença avançada: cuidado na intubação.',
    ],
    conduta: 'Acompanhamento reumatológico com metotrexato e terapias biológicas para controlar a inflamação, terapia ocupacional, órteses e cirurgia da mão quando há perda funcional.',
    vinheta: {
      cenario: 'Ambulatório de reumatologia',
      identificacao: 'Mulher de 61 anos, aposentada.',
      queixa: 'Mãos deformadas e sem força, com rigidez pela manhã.',
      historia: 'Tem dor e inchaço nas mãos e nos punhos há vinte anos, com rigidez de duas horas pela manhã. Usou corticoide por conta própria por anos e abandonou o tratamento reumatológico. Hoje não consegue abotoar roupas nem abrir potes.',
      antecedentes: [
        'Pessoais: artrite reumatoide há vinte anos, sem seguimento',
        'Pessoais: osteoporose por uso de corticoide',
        'Familiares: irmã com artrite reumatoide',
        'Hábitos: ex-tabagista',
      ],
      vitais: { pa: '128 × 78 mmHg', fc: '80 bpm', fr: '16 irpm', satO2: '98% em ar ambiente', temp: '36,6 °C' },
      exame: [
        'Desvio ulnar dos dedos e deformidade em botoeira no indicador',
        'Punhos rígidos, sem movimento',
        'Nódulos reumatoides nos cotovelos',
        'Fator reumatoide e anti-CCP muito positivos',
      ],
      pedido: 'Poliartrite simétrica das mãos de vinte anos com deformidades e anticorpos positivos: a pergunta é o grau de destruição articular.',
      pergunta: 'Radiografias das mãos. Qual é o achado que responde à pergunta clínica?',
      achado: 'Artrite reumatoide avançada',
      veredito: 'Artrite reumatoide avançada com anquilose do carpo, erosões e deformidades',
      correlacao: 'Vinte anos de sinovite sem tratamento adequado destruíram a cartilagem e o osso das duas mãos de forma simétrica. O carpo se fundiu num bloco, o estiloide ulnar foi reabsorvido e os dedos desviaram. A rigidez matinal longa, os nódulos e o anti-CCP positivo confirmam a artrite reumatoide.',
      distratores: [
        d('Osteoartrite erosiva das mãos', 'Acomete as interfalângicas distais e proximais com erosões centrais em asa de gaivota, poupando o carpo e as metacarpofalângicas.'),
        d('Artrite psoriásica mutilante', 'Prefere as interfalângicas distais, com lápis na xícara e proliferação óssea, e é assimétrica, com psoríase na pele e nas unhas.'),
        d('Artrite gotosa tofácea crônica', 'Forma erosões em saca-bocado com bordas salientes e tofos nas partes moles, assimétricas, com espaços preservados por muito tempo.'),
      ],
    },
  },

  'condrocalcinose-do-joelho': {
    tema: 'Artropatias',
    titulo: 'Doença por deposição de pirofosfato de cálcio no joelho',
    resumo: 'Condrocalcinose dos meniscos medial e lateral, redução desproporcional do espaço femoropatelar, escavação da cortical anterior do fêmur e calcificação no tendão do gastrocnêmio.',
    protocolo: 'Radiografias do joelho AP e perfil',
    series: ['Visão geral', 'Detalhe dos meniscos'],
    rotulos: {
      'patellofemoral joint space': r('Espaço femoropatelar muito reduzido', 'Redução maior entre a patela e o fêmur que entre o fêmur e a tíbia.',
        'Na artrose comum, o compartimento mais afetado é o femorotibial medial. Quando o femoropatelar está muito mais desgastado que os outros, a distribuição é atípica e sugere artropatia por pirofosfato. Esse padrão incomum é uma pista importante para o diagnóstico.'),
      'mild scalloping': r('Escavação da cortical anterior do fêmur', 'Leve erosão em concha da frente do fêmur, acima da patela.',
        'A escavação da cortical anterior do fêmur distal acontece quando a sinóvia inflamada ou a patela desgastada pressionam o osso. Ela também é descrita na artropatia por pirofosfato com doença femoropatelar grave.'),
      'proximal gastrocnemius tendon': r('Calcificação no tendão do gastrocnêmio', 'Linhas finas calcificadas na origem do gastrocnêmio.',
        'Os cristais de pirofosfato não se depositam só na cartilagem: também calcificam tendões, ligamentos e cápsulas. Calcificações lineares em tendões em volta do joelho reforçam o diagnóstico.'),
      'lateral meniscal': r('Condrocalcinose do menisco lateral', 'Calcificação triangular dentro do menisco lateral.',
        'A condrocalcinose é a calcificação da cartilagem. Nos meniscos, que são fibrocartilagem em forma de cunha, ela aparece como triângulo branco dentro do espaço articular. É o sinal mais característico da doença por deposição de pirofosfato de cálcio.',
        'Procure condrocalcinose também no punho, na fibrocartilagem triangular, e na sínfise púbica.'),
      medial: r('Condrocalcinose do menisco medial', 'Calcificação também no menisco medial.',
        'O acometimento dos dois meniscos e de outras articulações mostra que é uma doença sistêmica. A pseudogota, crise aguda de inflamação causada pelos cristais, é a forma mais conhecida, mas a doença também causa artropatia crônica.'),
    },
    achados: [
      'Condrocalcinose dos meniscos medial e lateral.',
      'Redução do espaço femoropatelar desproporcional ao femorotibial.',
      'Leve escavação da cortical anterior do fêmur; calcificações lineares no tendão proximal do gastrocnêmio.',
      'Osteopenia difusa e derrame suprapatelar.',
    ],
    armadilhas: [
      'Condrocalcinose em paciente jovem pede investigar hemocromatose, hiperparatireoidismo e hipomagnesemia.',
      'A crise de pseudogota imita artrite séptica: a punção mostra os cristais.',
      'Condrocalcinose pode ser achado sem sintomas em idosos.',
    ],
    conduta: 'Na crise, punção com análise de cristais, anti-inflamatório, colchicina ou corticoide intra-articular; dosar cálcio, PTH, ferritina e magnésio; tratamento da artropatia crônica como na artrose.',
    vinheta: {
      cenario: 'Ambulatório de reumatologia',
      identificacao: 'Mulher de 74 anos, aposentada.',
      queixa: 'Joelho esquerdo inchado e doloroso, com crises de piora.',
      historia: 'Há anos tem dor no joelho esquerdo ao subir escadas e levantar da cadeira. Nos últimos meses teve duas crises em que o joelho ficou quente, vermelho e muito inchado de repente, que passaram em uma semana. Também sente dor no punho direito.',
      antecedentes: [
        'Pessoais: hipotireoidismo',
        'Pessoais: crises recorrentes de artrite no joelho',
        'Familiares: sem doenças reumáticas',
        'Hábitos: sedentária',
      ],
      vitais: { pa: '138 × 82 mmHg', fc: '76 bpm', fr: '16 irpm', satO2: '97% em ar ambiente', temp: '37,2 °C' },
      exame: [
        'Derrame articular no joelho esquerdo',
        'Crepitação e dor na compressão da patela',
        'Punção com cristais romboides de birrefringência fraca positiva',
        'Cultura do líquido negativa',
      ],
      pedido: 'Crises de artrite aguda do joelho em idosa com artropatia femoropatelar e cristais na punção: a pergunta é o padrão radiográfico.',
      pergunta: 'Radiografias do joelho. Qual é o achado que responde à pergunta clínica?',
      achado: 'Condrocalcinose meniscal',
      veredito: 'Doença por deposição de pirofosfato de cálcio com condrocalcinose e artropatia femoropatelar',
      correlacao: 'Os cristais de pirofosfato se depositam na cartilagem dos meniscos com a idade, o que aparece como condrocalcinose. Quando se soltam, causam as crises de pseudogota, com o joelho quente e inchado. A destruição desproporcional da articulação entre a patela e o fêmur é o padrão típico da artropatia por pirofosfato.',
      distratores: [
        d('Gota com crise no joelho', 'Também causa crise aguda, mas os cristais são agulhas de birrefringência negativa e não há calcificação dos meniscos. Os cristais aqui são romboides.'),
        d('Artrose primária do joelho', 'Desgasta mais o compartimento medial, com osteófitos, sem condrocalcinose nem crises inflamatórias com cristais. Aqui o femoropatelar domina.'),
        d('Artrite séptica do joelho', 'Dá febre e joelho quente com líquido purulento e cultura positiva, e não melhora sozinha em uma semana. A cultura aqui é negativa.'),
      ],
    },
  },

  'lesao-de-pellegrini-stieda': {
    tema: 'Artropatias',
    titulo: 'Lesão de Pellegrini-Stieda com condrocalcinose',
    resumo: 'Calcificação junto ao côndilo femoral medial por lesão antiga do ligamento colateral medial, condrocalcinose, artrose femoropatelar e calcificações vasculares.',
    protocolo: 'Radiografias do joelho AP e perfil',
    rotulos: {
      'Pellegrini-stieda lesion': r('Lesão de Pellegrini-Stieda', 'Calcificação alongada junto ao côndilo femoral medial.',
        'A lesão de Pellegrini-Stieda é a calcificação ou ossificação da origem do ligamento colateral medial no fêmur, depois de uma lesão antiga desse ligamento. O hematoma no local da lesão calcifica com o tempo. Ela indica que o joelho sofreu uma entorse em valgo no passado e geralmente não precisa de tratamento.',
        'Calcificação na face medial do côndilo femoral: pergunte por entorse antiga do joelho.'),
      chondrocalcinosis: r('Condrocalcinose', 'Calcificação da cartilagem dentro do joelho.',
        'A condrocalcinose indica deposição de cristais de pirofosfato de cálcio na cartilagem. Em idosos, é comum e pode ser silenciosa, mas também pode causar crises de pseudogota e piorar a artrose.'),
      'subchondral sclerosis': r('Esclerose subcondral', 'Osso mais denso sob o platô tibial medial.',
        'Quando a cartilagem se desgasta, o osso logo abaixo recebe mais carga e fica mais denso. A esclerose subcondral é um dos sinais clássicos da artrose, junto com a redução do espaço, os osteófitos e os cistos.'),
      'vascular calcification': r('Calcificação vascular', 'Artérias femoral e poplítea calcificadas.',
        'Calcificações em trilho nas artérias da perna indicam aterosclerose ou calcificação da camada média, comum em diabetes e doença renal crônica. Não tem relação com o joelho, mas é um marcador de risco cardiovascular e deve constar no laudo.'),
      'Tendon mineralization': r('Mineralização do tendão do quadríceps', 'Pequena calcificação na inserção do quadríceps na patela.',
        'Calcificações nas inserções de tendões, as entesopatias, são comuns com a idade. Elas costumam ser assintomáticas e fazem parte do envelhecimento das estruturas em volta do joelho. Não muda a conduta.'),
      'Loss of joint space': r('Perda do espaço femoropatelar', 'Espaço entre a patela e o fêmur muito reduzido.',
        'A redução marcada do espaço femoropatelar com osteófitos indica artrose avançada nesse compartimento. Ela explica a dor ao subir escadas e ao levantar de uma cadeira. Com condrocalcinose, esse padrão é ainda mais característico.'),
    },
    achados: [
      'Calcificação junto à face medial do côndilo femoral medial — lesão de Pellegrini-Stieda.',
      'Condrocalcinose difusa do joelho; corpo livre sobre a espinha tibial lateral.',
      'Perda marcada do espaço femoropatelar com osteófitos; leve perda do espaço medial com esclerose subcondral.',
      'Mineralização na inserção do tendão do quadríceps e calcificação acentuada das artérias femoral e poplítea.',
    ],
    armadilhas: [
      'Não confunda com fratura avulsão aguda: a lesão de Pellegrini-Stieda tem contorno corticalizado e é antiga.',
      'Na fase aguda, a calcificação ainda não existe.',
      'Corpo livre pode travar o joelho.',
    ],
    conduta: 'Tratamento sintomático da artrose com exercício, perda de peso e analgesia; não é preciso tratar a lesão de Pellegrini-Stieda, salvo se dolorosa; controle dos fatores de risco cardiovascular.',
    vinheta: {
      cenario: 'Ambulatório de ortopedia',
      identificacao: 'Homem de 70 anos, aposentado, ex-jogador de futebol.',
      queixa: 'Dor no joelho direito ao subir escadas e levantar da cadeira.',
      historia: 'Tem dor no joelho direito há anos, pior ao subir escadas, agachar e levantar da cadeira. Às vezes o joelho trava. Na juventude, jogando futebol, torceu o joelho para dentro e ficou semanas com dor na face interna.',
      antecedentes: [
        'Pessoais: diabetes e doença renal crônica',
        'Pessoais: entorse grave do joelho direito aos 25 anos',
        'Familiares: sem doenças reumáticas',
        'Hábitos: ex-tabagista',
      ],
      vitais: { pa: '144 × 84 mmHg', fc: '74 bpm', fr: '16 irpm', satO2: '97% em ar ambiente', temp: '36,5 °C' },
      exame: [
        'Crepitação femoropatelar',
        'Espessamento indolor na face medial do côndilo femoral',
        'Ligamento colateral medial estável',
        'Pulsos pediosos diminuídos',
      ],
      pedido: 'Dor femoropatelar em idoso com entorse medial antiga e espessamento no côndilo medial: a pergunta é o que a radiografia mostra.',
      pergunta: 'Radiografias do joelho. Qual é o achado que responde à pergunta clínica?',
      achado: 'Lesão de Pellegrini-Stieda',
      veredito: 'Lesão de Pellegrini-Stieda com condrocalcinose e artrose femoropatelar',
      correlacao: 'A entorse em valgo da juventude lesou o ligamento colateral medial, e o hematoma no local calcificou ao longo dos anos, formando o espessamento palpável. A dor ao subir escadas vem da artrose femoropatelar, e a condrocalcinose sugere doença por pirofosfato. As artérias calcificadas combinam com o diabetes e a doença renal.',
      distratores: [
        d('Fratura avulsão recente do côndilo', 'Teria fragmento com bordas agudas e sem cortical, com dor aguda e trauma recente, e não um espessamento antigo indolor. Aqui a lesão é antiga.'),
        d('Osteocondroma do fêmur distal', 'É uma projeção óssea com cortical e medular contínuas com o fêmur, apontando para longe da articulação. Surge na infância e para de crescer com o fim do crescimento.'),
        d('Corpo livre intra-articular isolado', 'Aparece dentro da articulação e causa travamento, mas não fica colado na origem do ligamento colateral medial. Aqui também existe um corpo livre, mas ele não explica a calcificação medial.'),
      ],
    },
  },

  'osteoartrose-de-quadril': {
    tema: 'Artropatias',
    titulo: 'Osteoartrose avançada do quadril esquerdo',
    resumo: 'Perda superior grave do espaço do quadril esquerdo com achatamento da cabeça, grandes cistos subcondrais, esclerose, osteófitos em colar e alterações degenerativas lombares.',
    protocolo: 'Radiografias da bacia AP e do quadril em perfil',
    rotulos: {
      widening: r('Alargamento medial do espaço', 'Espaço articular medial aumentado.',
        'Na artrose do quadril, a cabeça femoral costuma migrar para cima e para fora, onde a carga é maior. Com isso, o espaço medial alarga, enquanto o superior some. A direção da migração ajuda a separar a artrose da artrite inflamatória, em que a cabeça migra para dentro.'),
      flattening: r('Achatamento da cabeça femoral', 'Contorno superolateral da cabeça achatado.',
        'Com a perda da cartilagem, o osso da cabeça passa a receber carga diretamente e se deforma. O achatamento piora a congruência da articulação e acelera o desgaste. Achatamento com fragmentação faria pensar em necrose avascular.'),
      'intervertebral disc space': r('Discos lombares degenerados', 'Espaços discais lombares baixos reduzidos, com osteófitos.',
        'A coluna lombar baixa aparece na radiografia da bacia. Discos degenerados com osteófitos e fenômeno de vácuo, gás dentro do disco, são sinais de degeneração avançada. Dor na coluna pode irradiar para a nádega e confundir com dor do quadril.'),
      'Enthesophyte formation': r('Entesófitos no trocânter maior', 'Pequenas projeções ósseas na inserção dos tendões.',
        'Entesófitos são calcificações nas inserções dos tendões, aqui dos glúteos no trocânter maior. São comuns com a idade e podem se associar a dor lateral do quadril, a tendinopatia glútea. São muito comuns após os 60 anos.'),
      superiorly: r('Perda superior do espaço', 'Espaço articular superior quase ausente.',
        'A parte superior do quadril é a que mais recebe carga ao andar, e é onde a cartilagem se desgasta primeiro. A perda grave do espaço indica que a cartilagem praticamente sumiu e que o osso encosta no osso, o que causa dor ao andar.',
        'Na artrose, os quatro sinais são redução do espaço, osteófitos, esclerose e cistos subcondrais.'),
      'subchondral cyst': r('Cisto subcondral', 'Grande cisto na cabeça femoral.',
        'Sem cartilagem, o líquido articular é empurrado para dentro do osso por pequenas fissuras e forma cistos, também chamados geodos. Cistos grandes enfraquecem a cabeça e podem levar ao colapso.'),
      'patchy areas of sclerosis': r('Esclerose em placas', 'Áreas densas irregulares na cabeça femoral, no perfil.',
        'A esclerose é o osso que reage à carga excessiva ficando mais denso. Em placas, junto com cistos, mostra osso sob estresse intenso, típico da artrose avançada. Ela aparece melhor no perfil.'),
    },
    achados: [
      'Perda grave do espaço articular superior do quadril esquerdo com alargamento da porção medial.',
      'Achatamento superolateral da cabeça femoral com grande cisto subcondral e áreas de esclerose em placas.',
      'Osteófitos em colar em volta do acetábulo esquerdo; artrose leve à direita.',
      'Degeneração discal lombar baixa com osteófitos e fenômeno de vácuo; entesófitos nos trocânteres maiores.',
    ],
    armadilhas: [
      'Dor no joelho pode vir do quadril: examine o quadril em idosos com dor no joelho.',
      'Cabeça achatada com fragmentação e espaço preservado sugere necrose avascular.',
      'Dor lombar irradiada para a nádega imita dor do quadril.',
    ],
    conduta: 'Exercícios, perda de peso, analgesia e bengala na mão oposta; artroplastia total do quadril quando a dor e a limitação são incapacitantes.',
    vinheta: {
      cenario: 'Ambulatório de ortopedia',
      identificacao: 'Homem de 67 anos, agricultor aposentado.',
      queixa: 'Dor na virilha esquerda ao andar e dificuldade para calçar as meias.',
      historia: 'Há quatro anos sente dor na virilha esquerda que piora ao andar e melhora com repouso. Hoje caminha só duas quadras. Tem rigidez de poucos minutos pela manhã e dificuldade para cortar as unhas do pé e calçar as meias. Também tem dor lombar antiga.',
      antecedentes: [
        'Pessoais: lombalgia crônica',
        'Pessoais: sobrepeso',
        'Familiares: pai com prótese de quadril',
        'Hábitos: trabalhou carregando peso por quarenta anos',
      ],
      vitais: { pa: '136 × 82 mmHg', fc: '72 bpm', fr: '16 irpm', satO2: '97% em ar ambiente', temp: '36,5 °C' },
      exame: [
        'Marcha claudicante à esquerda',
        'Rotação interna do quadril esquerdo muito limitada e dolorosa',
        'Encurtamento leve do membro inferior esquerdo',
        'Marcadores inflamatórios normais',
      ],
      pedido: 'Dor inguinal mecânica com rotação interna limitada em idoso que carregou peso a vida toda: a pergunta é o padrão do quadril.',
      pergunta: 'Radiografias da bacia e do quadril. Qual é o achado que responde à pergunta clínica?',
      achado: 'Osteoartrose avançada do quadril',
      veredito: 'Osteoartrose avançada do quadril esquerdo com cistos, esclerose e osteófitos',
      correlacao: 'Décadas carregando peso e o sobrepeso desgastaram a cartilagem do quadril, começando pela região superior, que recebe mais carga. O osso passou a encostar no osso, formou cistos, esclerose e osteófitos, e a cabeça achatou. A perda de rotação interna é o primeiro movimento a sumir na artrose do quadril e explica a dificuldade para calçar meias.',
      distratores: [
        d('Necrose avascular da cabeça femoral', 'Achata e fragmenta a cabeça com linha clara sob a superfície, mas o espaço articular se mantém até o colapso. Aqui o espaço sumiu.'),
        d('Artrite reumatoide do quadril', 'Reduz o espaço de forma uniforme e empurra a cabeça para dentro do acetábulo, com poucos osteófitos e rigidez matinal longa. Aqui há osteófitos.'),
        d('Tendinopatia glútea do trocânter', 'Dói na face lateral do quadril ao deitar sobre o lado, com rotação preservada e espaço articular normal. Aqui a rotação interna está limitada.'),
      ],
    },
  },
}
