import { d, type ConteudoCasoTC } from './casos-tc-tipos'

/** Casos de TC de crânio. Pacientes das vinhetas são fictícios. */
export const CASOS_TC_NEURO: Record<string, ConteudoCasoTC> = {
  'avc-isquemico-acm': {
    titulo: 'AVC isquêmico no território da ACM esquerda',
    resumo: 'Infarto extenso da artéria cerebral média esquerda com o sinal da artéria hiperdensa: o trombo aparece antes do parênquima escurecer.',
    protocolo: 'TC de crânio sem contraste, janela de parênquima',
    rotulos: {
      hyperattenuating: ['ACM esquerda hiperdensa', 'O trombo recente dentro da artéria cerebral média é mais denso que o sangue circulante: é o sinal da ACM hiperdensa.'],
      hypoattenuation: ['Hipoatenuação do território', 'O edema citotóxico baixa a densidade do tecido infartado, que fica mais escuro que o hemisfério contralateral.'],
      'gray-white matter': ['Perda da diferenciação córtico-subcortical', 'O córtex infartado incha e perde o brilho que o separa da substância branca — a fita insular e os núcleos da base se apagam.'],
    },
    achados: [
      'Hiperdensidade linear no segmento M1 da artéria cerebral média esquerda, compatível com trombo.',
      'Hipoatenuação córtico-subcortical frontotemporoparietal esquerda, respeitando o território da ACM.',
      'Apagamento da fita insular, dos núcleos da base e dos sulcos do lado acometido.',
      'Sem hiperdensidade parenquimatosa que sugira transformação hemorrágica.',
    ],
    armadilhas: [
      'Nas primeiras horas a TC pode ser normal; o sinal da artéria hiperdensa costuma ser o primeiro achado, e compará-lo com a ACM do outro lado evita o falso positivo do hematócrito alto.',
      'Hipoatenuação franca em mais de um terço do território da ACM indica infarto já estabelecido e aumenta o risco de sangramento com trombólise.',
      'O escore ASPECTS quantifica o que se vê: dez regiões, perde-se um ponto por região hipodensa.',
    ],
    conduta: 'Protocolo de AVC: horário do último momento visto bem, glicemia, TC sem contraste para excluir sangramento e angiotomografia para localizar a oclusão. Oclusão proximal de ACM é candidata a trombectomia mecânica; trombólise venosa se dentro da janela e sem contraindicação.',
    vinheta: {
      cenario: 'Sala de emergência, protocolo de AVC',
      identificacao: 'Homem de 71 anos, aposentado, destro, trazido pela esposa.',
      queixa: 'Não consegue falar nem mexer o lado direito desde que acordou.',
      historia: 'A esposa conta que ele foi deitar às 23 h conversando normalmente. Às 6 h acordou tentando falar sem conseguir, com o braço direito caído e a boca torta. Não houve queda, convulsão ou cefaleia referida. Há duas semanas teve um episódio de 10 minutos de fraqueza na mão direita que passou sozinho e não procurou atendimento.',
      antecedentes: [
        'Pessoais: fibrilação atrial há 3 anos, suspendeu a varfarina por conta própria há 4 meses',
        'Pessoais: hipertensão e dislipidemia em tratamento irregular',
        'Familiares: pai faleceu de AVC aos 68 anos',
        'Hábitos: ex-tabagista de 40 maços-ano, parou há 5 anos',
      ],
      vitais: { pa: '182 × 98 mmHg', fc: '112 bpm, irregular', fr: '18 irpm', satO2: '95% em ar ambiente', temp: '36,6 °C' },
      exame: [
        'Afasia global: não nomeia, não repete, não obedece a comandos',
        'Desvio conjugado do olhar para a esquerda',
        'Hemiplegia direita de predomínio braquiofacial',
        'Glicemia capilar de 128 mg/dL; NIHSS 20',
      ],
      pedido: 'Déficit neurológico agudo com afasia e desvio do olhar em paciente com fibrilação atrial sem anticoagulação: a pergunta é o que a TC mostra além de excluir sangramento.',
      pergunta: 'TC de crânio sem contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Infarto em território da ACM',
      veredito: 'Infarto agudo da ACM esquerda com artéria hiperdensa e perda da diferenciação córtico-subcortical',
      correlacao: 'Afasia, desvio do olhar para o lado da lesão e hemiplegia braquiofacial direita localizam o evento no hemisfério esquerdo, no território da artéria cerebral média. A fibrilação atrial sem anticoagulação fornece o êmbolo. A TC mostra o trombo como uma artéria mais branca que a contralateral e um território já hipoatenuante, com perda da fita insular — o relógio começou antes do despertar.',
      distratores: [
        d('Hemorragia intraparenquimatosa hipertensiva', 'Explicaria o déficit súbito em hipertenso, mas o sangue agudo é hiperdenso no parênquima, com efeito de massa arredondado. Aqui o parênquima está mais escuro e a única estrutura branca é a luz da própria artéria.'),
        d('Paralisia de Todd pós-ictal', 'Déficit que se segue a uma crise e regride em horas, com TC normal. Não houve crise testemunhada e a TC já mostra hipoatenuação de um território arterial inteiro, o que não acontece após convulsão.'),
        d('Glioma de alto grau frontotemporal', 'Pode ser hipodenso, mas cresce em semanas e causa déficit progressivo, com edema digitiforme e efeito de massa desproporcional. Aqui o início foi súbito e a hipodensidade tem os limites exatos de um território arterial.'),
      ],
    },
  },

  'hemorragia-intraparenquimatosa': {
    titulo: 'Hemorragia intraparenquimatosa talamocapsular',
    resumo: 'Hematoma na região tálamo-cápsula-putâmen com edema, efeito de massa e desvio da linha média; neste paciente, o sangramento vinha de um glioma de alto grau.',
    protocolo: 'TC de crânio sem contraste, janela de parênquima',
    rotulos: {
      'Intracerebral hemorrhage': ['Hematoma intraparenquimatoso', 'Coleção hiperdensa, de 60 a 80 UH, na região do tálamo, cápsula interna e putâmen direitos.'],
      'cerebral edema': ['Edema perilesional', 'Halo hipodenso ao redor do hematoma, que cresce nos primeiros dias e responde por parte do efeito de massa.'],
      compression: ['Compressão do terceiro ventrículo', 'O volume do hematoma e do edema empurra e colapsa o terceiro ventrículo.'],
      'Mild dilation': ['Dilatação ventricular leve', 'Os cornos temporais começam a dilatar: sinal precoce de obstrução ao fluxo liquórico.'],
      'hyperdense mass': ['Massa hiperdensa', 'Componente sólido denso junto ao sangue — o que levantou a suspeita de lesão subjacente.'],
    },
    achados: [
      'Hematoma hiperdenso na topografia do tálamo, cápsula interna e putâmen à direita.',
      'Edema vasogênico perilesional e compressão do terceiro ventrículo.',
      'Desvio discreto da linha média para a esquerda.',
      'Dilatação inicial do sistema ventricular a montante.',
    ],
    armadilhas: [
      'A topografia talâmica e putaminal é a clássica da hemorragia hipertensiva, mas não a garante: hematoma em paciente sem hipertensão, com edema desproporcional ao tempo de evolução ou com componente nodular pede contraste ou ressonância.',
      'Hemorragia com componente sólido pode esconder tumor — glioblastoma, metástases de melanoma, rim e tireoide sangram com frequência.',
      'Extensão intraventricular e hidrocefalia mudam o prognóstico e podem exigir derivação.',
    ],
    conduta: 'Controle pressórico, reversão de anticoagulação se houver, cabeceira elevada e avaliação neurocirúrgica. O escore ICH (volume, Glasgow, idade, sangue intraventricular, localização infratentorial) estima mortalidade. Diante de achados atípicos, ressonância com contraste para buscar causa secundária.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Mulher de 58 anos, professora, trazida pelo marido.',
      queixa: 'Fraqueza súbita no lado esquerdo e dor de cabeça forte há 3 horas.',
      historia: 'Estava corrigindo provas quando derrubou a caneta e não conseguiu pegá-la com a mão esquerda. Em minutos a perna esquerda cedeu e surgiu cefaleia intensa com um vômito. O marido refere que há cerca de seis semanas ela vinha com dor de cabeça matinal, esquecimentos e uma dificuldade nova para se vestir, que atribuíram ao cansaço.',
      antecedentes: [
        'Pessoais: nega hipertensão; aferições recentes normais',
        'Pessoais: nega uso de anticoagulantes ou antiagregantes',
        'Gestacionais: três gestações a termo, sem pré-eclâmpsia',
        'Familiares: sem história de aneurisma ou AVC precoce',
      ],
      vitais: { pa: '164 × 92 mmHg', fc: '64 bpm', fr: '16 irpm', satO2: '97% em ar ambiente', temp: '36,4 °C' },
      exame: [
        'Glasgow 13, sonolenta mas desperta ao chamado',
        'Hemiparesia esquerda proporcionada, grau 2',
        'Hemi-hipoestesia esquerda',
        'Papiledema bilateral à fundoscopia',
      ],
      pedido: 'Déficit súbito com cefaleia e vômito sobre um quadro subagudo de semanas: a pergunta é se há sangramento e se ele tem aspecto de hemorragia primária.',
      pergunta: 'TC de crânio sem contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Hematoma talamocapsular direito',
      veredito: 'Hematoma intraparenquimatoso talamocapsular direito com edema, efeito de massa e componente nodular suspeito',
      correlacao: 'O déficit sensitivo e motor proporcionado do lado esquerdo aponta para o tálamo e a cápsula interna direitos, e a TC mostra ali o sangue hiperdenso. O que não fecha é o contexto: paciente sem hipertensão, com semanas de cefaleia matinal e papiledema, e um hematoma com edema maior que o esperado para três horas. Sangramento em topografia típica com história atípica pede busca de lesão subjacente — aqui, um glioma de alto grau.',
      distratores: [
        d('Infarto lacunar da cápsula interna', 'Também causa hemiparesia proporcionada, mas a lacuna é pequena e hipodensa, frequentemente invisível nas primeiras horas. Aqui a lesão é volumosa, branca e empurra a linha média.'),
        d('Abscesso cerebral nos núcleos da base', 'Forma lesão hipodensa com anel de realce após contraste e costuma vir com febre. A lesão desta paciente é hiperdensa sem contraste, o que traduz sangue e não pus.'),
        d('Hemorragia subaracnoidea aneurismática', 'A cefaleia em trovoada cabe, mas o sangue ocupa as cisternas e os sulcos, desenhando o espaço liquórico. Aqui o sangue está dentro do parênquima profundo e as cisternas estão livres.'),
      ],
    },
  },

  'hemorragia-pontina': {
    titulo: 'Hemorragia pontina hipertensiva',
    resumo: 'Hematoma no tronco encefálico estendendo-se ao mesencéfalo e ao tálamo direito, com sequela antiga nos núcleos da base.',
    protocolo: 'TC de crânio sem contraste, janela de parênquima',
    rotulos: {
      'Pontine haemorrhage': ['Hemorragia pontina', 'Hiperdensidade central na ponte: território das artérias perfurantes paramedianas da basilar.'],
      'right thalamus extension': ['Extensão ao tálamo direito', 'O hematoma sobe pelo mesencéfalo até o tálamo — quanto mais se estende, pior o prognóstico.'],
      'focal encephalomalacia': ['Encefalomalácia focal', 'Área hipodensa com densidade de líquor nos núcleos da base: sequela de infarto antigo, outro sinal de doença de pequenos vasos.'],
    },
    achados: [
      'Hematoma hiperdenso na ponte, com extensão ao mesencéfalo e ao tálamo direito.',
      'Apagamento da cisterna pré-pontina e do quarto ventrículo.',
      'Encefalomalácia focal nos núcleos da base à direita, sequelar.',
      'Leucoaraiose periventricular, marca de microangiopatia hipertensiva.',
    ],
    armadilhas: [
      'O tronco é mal avaliado na TC pelos artefatos de endurecimento de feixe entre os rochedos; hemorragias pequenas podem se perder nas faixas escuras.',
      'Pupilas puntiformes, coma e tetraparesia de instalação súbita sugerem ponte antes mesmo da imagem.',
      'Hemorragia pontina em jovem normotenso deve levantar cavernoma ou malformação vascular.',
    ],
    conduta: 'Suporte avançado de via aérea, controle pressórico e avaliação neurocirúrgica, embora a drenagem raramente seja indicada. Prognóstico reservado quando o hematoma é extenso e há extensão mesencefálica ou talâmica.',
    vinheta: {
      cenario: 'Sala vermelha',
      identificacao: 'Homem de 62 anos, motorista de caminhão, trazido pelo SAMU.',
      queixa: 'Encontrado caído e sem responder no pátio de uma transportadora.',
      historia: 'Colegas o viram queixar-se de tontura e visão dupla, cambalear e cair em seguida, sem trauma craniano aparente. Em minutos deixou de responder. Houve vômito no trajeto. Ele havia contado a um colega que estava sem os remédios da pressão há dois meses.',
      antecedentes: [
        'Pessoais: hipertensão há 15 anos, sem tratamento há 2 meses',
        'Pessoais: AVC isquêmico há 4 anos, sem sequelas motoras',
        'Familiares: mãe e dois irmãos hipertensos',
        'Hábitos: etilismo de 6 latas de cerveja por dia e tabagismo ativo',
      ],
      vitais: { pa: '230 × 128 mmHg', fc: '58 bpm', fr: '10 irpm, irregular', satO2: '88% em ar ambiente', temp: '37,8 °C' },
      exame: [
        'Glasgow 5, sem abertura ocular',
        'Pupilas puntiformes e fotorreagentes',
        'Ausência de movimentos oculares horizontais ao reflexo oculocefálico',
        'Tetraparesia com postura em extensão ao estímulo',
      ],
      pedido: 'Coma súbito com pupilas puntiformes, perda do olhar horizontal e hipertensão grave: a pergunta é a topografia e a natureza da lesão.',
      pergunta: 'TC de crânio sem contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Hemorragia pontina com extensão talâmica',
      veredito: 'Hemorragia pontina hipertensiva com extensão ao mesencéfalo e ao tálamo direito',
      correlacao: 'Pupilas puntiformes vêm da destruição das vias simpáticas descendentes na ponte, e a perda do olhar horizontal indica lesão dos centros pontinos da mirada. Hipertensão grave sem tratamento, AVC prévio e leucoaraiose completam o perfil de doença de pequenos vasos. A TC mostra o hematoma central na ponte subindo até o tálamo.',
      distratores: [
        d('Trombose da artéria basilar', 'Também produz coma e pupilas pequenas, mas na TC sem contraste aparece como basilar hiperdensa com parênquima inicialmente preservado. Aqui o sangue está no próprio tronco, e não na luz arterial.'),
        d('Intoxicação por opioides', 'Explica miose e rebaixamento com bradipneia, mas não a tetraparesia em extensão nem a perda do olhar horizontal. E a TC seria normal, não com hiperdensidade central na ponte.'),
        d('Hemorragia cerebelar hemisférica', 'Dá vertigem, vômito e ataxia com rebaixamento por compressão do tronco. O hematoma, porém, fica lateral no hemisfério cerebelar; o deste paciente é central e paramediano, dentro da ponte.'),
      ],
    },
  },

  'hematoma-extradural': {
    titulo: 'Hematoma extradural subagudo após derivação',
    resumo: 'Coleção biconvexa de densidade mista após derivação ventricular para hidrocefalia por cisto coloide: o hematoma apareceu depois que o cérebro colapsou.',
    protocolo: 'TC de crânio sem contraste, janela de parênquima',
    rotulos: {
      hyperdensity: ['Componente hiperdenso', 'Sangue mais recente e coagulado no hematoma extradural.'],
      'isodense component': ['Componente isodenso', 'Sangue em degradação, com densidade próxima à do córtex: é o que define o hematoma como subagudo.'],
      'air bubbles': ['Bolhas de ar no trajeto do cateter', 'Gás residual do procedimento, ao longo do cateter ventricular.'],
      'Y-shaped branched VP shunt': ['Derivação ventriculoperitoneal em Y', 'Cateter ventricular bifurcado, colocado para drenar os dois ventrículos laterais.'],
      'colloid cyst': ['Cisto coloide', 'Nódulo hiperdenso no forame de Monro, causa da hidrocefalia que motivou a derivação.'],
    },
    achados: [
      'Coleção extra-axial biconvexa, de limites nítidos, com componentes hiperdenso e isodenso.',
      'A coleção não cruza as suturas, o que a situa entre a dura e a tábua interna.',
      'Derivação ventriculoperitoneal bifurcada com bolhas de ar no trajeto.',
      'Cisto coloide no forame de Monro e ventrículos já descomprimidos.',
    ],
    armadilhas: [
      'A densidade mista confunde a idade: isodenso não é normal, é sangue de dias — janelas estreitas e comparação com o córtex evitam que o hematoma passe despercebido.',
      'A descompressão rápida de ventrículos muito dilatados descola a dura da tábua interna e rompe vasos meníngeos e emissárias: é complicação conhecida da derivação.',
      'Forma biconvexa que não cruza suturas é extradural; forma em crescente que cruza suturas e respeita a foice é subdural.',
    ],
    conduta: 'Avaliação neurocirúrgica imediata. Hematoma extradural com efeito de massa ou piora neurológica é drenado; revisar a válvula da derivação para evitar hiperdrenagem.',
    vinheta: {
      cenario: 'Enfermaria de neurocirurgia',
      identificacao: 'Homem de 34 anos, analista de sistemas, no quinto dia de pós-operatório.',
      queixa: 'Dor de cabeça que voltou e está piorando desde ontem.',
      historia: 'Foi internado há uma semana com cefaleia intensa, vômitos e visão borrada; a investigação mostrou hidrocefalia obstrutiva por um cisto no forame de Monro e ele recebeu derivação ventriculoperitoneal com cateter bifurcado. Acordou bem da cirurgia, sem cefaleia. Ontem à noite a dor voltou do lado direito, e hoje a enfermagem o achou sonolento e com dificuldade de segurar o copo com a mão esquerda.',
      antecedentes: [
        'Pessoais: previamente hígido até a internação atual',
        'Pessoais: sem uso de anticoagulantes; coagulograma pré-operatório normal',
        'Familiares: sem doenças neurológicas conhecidas',
        'Hábitos: sedentário, nega tabagismo e drogas',
      ],
      vitais: { pa: '152 × 88 mmHg', fc: '60 bpm', fr: '14 irpm', satO2: '97% em ar ambiente', temp: '36,9 °C' },
      exame: [
        'Glasgow 13, desorientado no tempo',
        'Pupila direita discretamente maior que a esquerda, ambas fotorreagentes',
        'Paresia leve em membro superior esquerdo',
        'Ferida operatória limpa, válvula palpável e depressível',
      ],
      pedido: 'Piora neurológica focal dias após uma derivação ventricular: a pergunta é se houve complicação hemorrágica ou falha da drenagem.',
      pergunta: 'TC de crânio sem contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Hematoma extradural subagudo',
      veredito: 'Hematoma extradural subagudo biconvexo de densidade mista após descompressão ventricular',
      correlacao: 'O paciente melhorou com a derivação e voltou a piorar dias depois, com sinais focais contralaterais e anisocoria discreta. A drenagem rápida de ventrículos dilatados deixa a dura sem apoio e favorece o descolamento com sangramento. A coleção é biconvexa, limitada pelas suturas, e mistura sangue hiperdenso com componente isodenso — hematoma extradural de alguns dias.',
      distratores: [
        d('Hiperdrenagem com ventrículos em fenda', 'Causa cefaleia postural com ventrículos colapsados, mas sem coleção extra-axial nem sinais focais. Aqui há uma coleção biconvexa comprimindo o hemisfério, que explica a paresia.'),
        d('Obstrução do cateter com hidrocefalia', 'Traria de volta os ventrículos dilatados e a transudação periventricular. Os ventrículos estão descomprimidos; o que ocupa espaço é sangue fora do cérebro.'),
        d('Hematoma subdural crônico bilateral', 'É outra complicação da hiperdrenagem, mas tem forma de crescente, cruza as suturas e é hipodenso. A coleção deste paciente é lenticular, para nas suturas e tem sangue hiperdenso.'),
      ],
    },
  },

  'hematoma-subdural-agudo-sobre-cronico': {
    titulo: 'Hematoma subdural agudo sobre crônico',
    resumo: 'Coleção subdural extensa na convexidade esquerda com níveis de hematócrito, herniação subfalcina e aprisionamento ventricular.',
    protocolo: 'TC de crânio sem contraste, janela de parênquima',
    rotulos: {
      'acute subdural haematoma': ['Hematoma subdural agudo', 'Crescente hiperdenso que acompanha a convexidade e cruza as suturas.'],
      'acute component': ['Componente agudo', 'Sangue novo, mais denso, que se deposita na porção pendente da coleção.'],
      'chronic component': ['Componente crônico', 'Sangue antigo liquefeito, hipodenso, que sobrenada na parte superior.'],
      'two separate hematocrit levels': ['Dois níveis de hematócrito', 'Interfaces horizontais entre sangue novo e antigo: a coleção sangrou mais de uma vez.'],
      'falcine subdural': ['Hematoma subdural junto à foice', 'Sangue ao longo da foice do cérebro, que o subdural respeita sem cruzar a linha média.'],
      'subfalcine herniation': ['Herniação subfalcina', 'O giro do cíngulo passa por baixo da foice para o lado oposto.'],
      'compression lateral ventricle': ['Compressão do ventrículo lateral', 'O ventrículo esquerdo colapsa sob a coleção.'],
      'trapping and dilatation': ['Aprisionamento do ventrículo contralateral', 'O forame de Monro obstruído pelo desvio faz o ventrículo direito dilatar.'],
      'sulcal effacement': ['Apagamento dos sulcos', 'Os sulcos somem sob a compressão: sinal de hipertensão intracraniana.'],
      infarcts: ['Infartos por herniação', 'Áreas hipodensas em território de artéria comprimida contra a borda da foice ou do tentório.'],
    },
    achados: [
      'Coleção subdural em crescente na convexidade esquerda, de densidade mista.',
      'Componente agudo hiperdenso pendente e componente crônico hipodenso superior, com dois níveis de hematócrito.',
      'Extensão ao longo da foice, herniação subfalcina e compressão do ventrículo esquerdo.',
      'Aprisionamento e dilatação do ventrículo contralateral e infartos secundários.',
    ],
    armadilhas: [
      'O subdural isodenso da fase subaguda pode parecer apenas apagamento dos sulcos; procure o córtex afastado da tábua interna.',
      'Idosos com atrofia, etilistas e anticoagulados sangram com trauma mínimo, que muitas vezes nem é lembrado.',
      'Nível de hematócrito também aparece em coagulopatia; revise o coagulograma antes de concluir ressangramento.',
    ],
    conduta: 'Reversão de anticoagulação, avaliação neurocirúrgica imediata. Desvio de linha média acima de 5 mm, espessura acima de 10 mm ou piora do Glasgow indicam craniotomia; componente crônico isolado pode ser drenado por trepanação ou tratado com embolização da artéria meníngea média.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Homem de 79 anos, viúvo, mora sozinho, trazido pela filha.',
      queixa: 'Confusão progressiva nas últimas três semanas e sonolência intensa hoje.',
      historia: 'A filha notou que ele começou a esquecer compromissos e a repetir perguntas há cerca de três semanas. Há dez dias passou a arrastar a perna direita. Hoje não conseguiu levantar da cama e responde pouco. Ele comentou ter batido a cabeça na porta do armário no mês passado, sem desmaio, e não procurou atendimento.',
      antecedentes: [
        'Pessoais: fibrilação atrial em uso de rivaroxabana',
        'Pessoais: quedas frequentes no último ano',
        'Familiares: sem demência na família',
        'Hábitos: etilismo de duas doses de destilado ao dia por décadas',
      ],
      vitais: { pa: '168 × 86 mmHg', fc: '54 bpm, irregular', fr: '12 irpm', satO2: '95% em ar ambiente', temp: '36,2 °C' },
      exame: [
        'Glasgow 10, abre os olhos à dor',
        'Pupila esquerda maior e lentamente reativa',
        'Hemiparesia direita grau 3',
        'Equimose antiga em região frontal',
      ],
      pedido: 'Declínio cognitivo subagudo com piora focal em idoso anticoagulado e etilista após trauma trivial: a pergunta é se há coleção e se ela exige cirurgia agora.',
      pergunta: 'TC de crânio sem contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Hematoma subdural agudo sobre crônico',
      veredito: 'Hematoma subdural agudo sobre crônico à esquerda com herniação subfalcina e dois níveis de hematócrito',
      correlacao: 'Idoso atrófico, etilista e anticoagulado sofreu um trauma banal que rompeu veias ponte. O sangue antigo liquefez e explicou as semanas de confusão; o ressangramento recente trouxe a piora rápida, a anisocoria e a hemiparesia contralateral. A TC mostra exatamente as duas idades: sangue novo pendente, sangue velho em cima, e o hemisfério empurrado por baixo da foice.',
      distratores: [
        d('Demência vascular com infartos lacunares', 'Explicaria esquecimento em hipertenso idoso, mas evolui em meses, sem anisocoria nem rebaixamento. E não formaria uma coleção em crescente desviando a linha média.'),
        d('Hematoma extradural temporal agudo', 'É biconvexo, não cruza suturas e costuma vir com intervalo lúcido de horas após trauma forte. Esta coleção tem forma de crescente ao longo de toda a convexidade e mistura sangue de semanas.'),
        d('Higroma subdural por atrofia cerebral', 'É líquor no espaço subdural, homogêneo e com densidade de água, sem efeito de massa relevante. Aqui há componente hiperdenso, níveis de hematócrito e herniação.'),
      ],
    },
  },

  'hemorragia-subaracnoidea': {
    titulo: 'Hemorragia subaracnoidea traumática',
    resumo: 'Sangue nos sulcos da convexidade após impacto de projétil de alta energia retido no osso parietal, sem penetração na dura.',
    protocolo: 'TC de crânio sem contraste, janelas de parênquima e óssea',
    rotulos: {
      'subarachnoid hemorrhage': ['Hemorragia subaracnoidea', 'Sangue hiperdenso desenhando os sulcos da convexidade, junto ao ponto de impacto.'],
    },
    achados: [
      'Corpo estranho metálico hiperdenso incrustado na tábua externa parietal esquerda, com artefato em raios.',
      'Hematoma subgaleal com fragmentos e gás no subcutâneo.',
      'Hiperdensidade nos sulcos da convexidade adjacente: hemorragia subaracnoidea traumática.',
      'Sem coleção extra-axial significativa nem desvio da linha média.',
    ],
    armadilhas: [
      'A hemorragia subaracnoidea traumática é a mais comum de todas e fica nos sulcos da convexidade, perto do impacto; sangue nas cisternas da base sem trauma sugere aneurisma.',
      'Artefato metálico cria faixas brancas e escuras que simulam ou escondem sangue; janelas mais largas e cortes adjacentes ajudam.',
      'Projétil que não penetra a dura ainda transfere energia suficiente para contusão e hemorragia.',
    ],
    conduta: 'Avaliação neurocirúrgica, controle da dor e pressão arterial, profilaxia antitetânica e antibiótica conforme a ferida, TC de controle em 6 a 24 horas para detectar progressão.',
    vinheta: {
      cenario: 'Trauma, sala de emergência',
      identificacao: 'Homem de 27 anos, entregador, trazido pelo resgate.',
      queixa: 'Atingido na cabeça por bala perdida enquanto pilotava a moto.',
      historia: 'Sentiu uma pancada forte do lado esquerdo da cabeça durante um tiroteio próximo, conseguiu parar a moto e perdeu a consciência por cerca de um minuto. Ao acordar tinha sangramento no couro cabeludo, dor de cabeça intensa e vomitou duas vezes. O capacete aberto tinha um amassado na lateral.',
      antecedentes: [
        'Pessoais: previamente hígido',
        'Pessoais: vacinação antitetânica desconhecida',
        'Familiares: sem doenças conhecidas',
        'Hábitos: tabagista social, nega drogas ilícitas',
      ],
      vitais: { pa: '138 × 84 mmHg', fc: '98 bpm', fr: '18 irpm', satO2: '98% em ar ambiente', temp: '36,5 °C' },
      exame: [
        'Glasgow 14, confuso quanto à data',
        'Ferida contusa parietal esquerda com projétil palpável sob o couro cabeludo',
        'Pupilas isocóricas e fotorreagentes',
        'Rigidez de nuca leve, sem déficit motor',
      ],
      pedido: 'Trauma craniano por projétil com perda de consciência e vômitos: a pergunta é se houve penetração e que sangramento intracraniano existe.',
      pergunta: 'TC de crânio sem contraste. Qual é o achado intracraniano que responde à pergunta clínica?',
      achado: 'Hemorragia subaracnoidea traumática',
      veredito: 'Hemorragia subaracnoidea traumática na convexidade sob projétil retido na tábua externa',
      correlacao: 'O projétil ficou preso no osso parietal, sem atravessar a dura, mas a energia do impacto rompeu pequenos vasos corticais. O resultado é sangue nos sulcos da convexidade logo abaixo do ponto atingido — hemorragia subaracnoidea traumática, que explica a cefaleia, os vômitos e a leve rigidez de nuca, sem desvio da linha média.',
      distratores: [
        d('Hematoma extradural sob a fratura', 'É a coleção esperada em impacto sobre o osso temporal com lesão da meníngea média: lente biconvexa hiperdensa. Aqui o sangue não forma coleção, ele preenche os sulcos corticais.'),
        d('Hemorragia subaracnoidea aneurismática', 'O sangue predomina nas cisternas da base e na fissura sylviana, sem relação com trauma. Neste paciente ele está na convexidade, colado ao ponto de impacto do projétil.'),
        d('Lesão axonal difusa com petéquias', 'Resulta de aceleração rotacional, com pequenos focos hemorrágicos no corpo caloso e na junção córtico-subcortical e coma desproporcional à TC. O paciente está com Glasgow 14 e o sangue está nos sulcos.'),
      ],
    },
  },

  'contusoes-cerebrais': {
    titulo: 'Contusões cerebrais e múltiplas hemorragias traumáticas',
    resumo: 'Trauma craniano grave com contusões bifrontais e temporal, subdural, subaracnoidea, intraventricular e fratura da calota.',
    protocolo: 'TC de crânio sem contraste, janelas de parênquima e óssea',
    rotulos: {
      Contusion: ['Contusão cerebral', 'Focos hemorrágicos corticais nas regiões que batem contra o osso: polos frontais e temporais.'],
      'Subarachnoid haemorrhage': ['Hemorragia subaracnoidea', 'Sangue nos sulcos frontais direitos.'],
      'Intraventricular haemorrhage': ['Hemorragia intraventricular', 'Sangue dentro do sistema ventricular.'],
      'CSF/blood level': ['Nível líquor-sangue', 'O sangue se deposita no corno occipital, em posição pendente.'],
      'Subdural haematoma': ['Hematoma subdural', 'Crescente hiperdenso na convexidade direita.'],
      'Calvarial fracture': ['Fratura da calota craniana', 'Traço de fratura na janela óssea, no ponto de impacto.'],
    },
    achados: [
      'Contusões hemorrágicas bifrontais e temporal esquerda.',
      'Hematoma subdural na convexidade direita.',
      'Hemorragia subaracnoidea frontal direita e hemorragia intraventricular com nível no corno occipital.',
      'Fratura da calota craniana.',
    ],
    armadilhas: [
      'Contusões são dinâmicas: podem crescer e coalescer nas primeiras 24 a 72 horas, por isso a TC de controle é rotina.',
      'Golpe e contragolpe: a contusão mais grave costuma estar do lado oposto ao impacto.',
      'Polos frontais e temporais anteriores ficam junto a artefatos ósseos da base; olhe os cortes altos e baixos com atenção.',
    ],
    conduta: 'Via aérea definitiva se Glasgow igual ou menor que 8, evitar hipotensão e hipóxia, avaliação neurocirúrgica, monitorização de pressão intracraniana conforme o caso e TC de controle precoce.',
    vinheta: {
      cenario: 'Trauma, sala vermelha',
      identificacao: 'Mulher de 45 anos, ciclista, trazida pelo SAMU.',
      queixa: 'Atropelada por carro enquanto pedalava, sem capacete.',
      historia: 'Foi atingida lateralmente em cruzamento e arremessada contra o meio-fio, batendo a cabeça do lado direito. Testemunhas relatam que ficou inconsciente no local e teve movimentos tônicos breves. No transporte apresentou vômito e piora do nível de consciência.',
      antecedentes: [
        'Pessoais: hipotireoidismo em uso de levotiroxina',
        'Gestacionais: duas gestações, uma cesárea',
        'Familiares: sem coagulopatias conhecidas',
        'Hábitos: nega álcool; exame toxicológico em andamento',
      ],
      vitais: { pa: '150 × 90 mmHg', fc: '62 bpm', fr: '12 irpm', satO2: '93% com máscara', temp: '36,0 °C' },
      exame: [
        'Glasgow 8: abertura ocular à dor, sons incompreensíveis, localiza a dor',
        'Hematoma e crepitação em região parietal direita',
        'Pupilas isocóricas e lentamente reativas',
        'Otorragia à direita',
      ],
      pedido: 'Trauma craniano grave com Glasgow 8 após impacto de alta energia: a pergunta é quais lesões hemorrágicas existem e se alguma é cirúrgica agora.',
      pergunta: 'TC de crânio sem contraste. Qual é o conjunto de achados que responde à pergunta clínica?',
      achado: 'Contusões com hemorragias em vários compartimentos',
      veredito: 'Contusões bifrontais e temporal, subdural direito, hemorragia subaracnoidea e intraventricular com fratura da calota',
      correlacao: 'Impacto lateral de alta energia contra o meio-fio produziu fratura no ponto de impacto, subdural na convexidade e contusões nos polos frontais e temporal esquerdo pelo contragolpe. O sangue ainda alcançou os sulcos e os ventrículos. A soma explica o Glasgow 8 e impõe via aérea definitiva e TC de controle.',
      distratores: [
        d('Lesão axonal difusa isolada', 'Explica coma desproporcional após aceleração, mas a TC costuma ser quase normal, com petéquias no corpo caloso. Aqui as lesões são macroscópicas e em vários compartimentos.'),
        d('Hemorragia subaracnoidea aneurismática com queda', 'Um aneurisma roto pode causar a queda, mas o sangue ficaria nas cisternas da base e não haveria fratura nem contusões polares de contragolpe.'),
        d('Hematoma extradural com intervalo lúcido', 'É lente biconvexa sob fratura temporal, com paciente que desperta antes de piorar. Esta paciente não teve intervalo lúcido e a coleção extra-axial tem forma de crescente.'),
      ],
    },
  },

  'hidrocefalia-cisto-coloide': {
    titulo: 'Hidrocefalia obstrutiva por cisto coloide',
    resumo: 'Cisto no forame de Monro dilata os ventrículos laterais e empurra o septo, com transudação liquórica periventricular.',
    protocolo: 'TC de crânio sem contraste, janela de parênquima',
    rotulos: {
      dilatation: ['Dilatação dos ventrículos laterais', 'Os ventrículos laterais crescem porque o líquor não sai pelo forame de Monro.'],
      'leftward bowing': ['Abaulamento do septo para a esquerda', 'O septo pelúcido é empurrado pela assimetria de pressão entre os ventrículos.'],
      'CSF permeation': ['Transudação liquórica periventricular', 'Hipodensidade em torno dos cornos: líquor forçado para o parênquima sob pressão — hidrocefalia aguda.'],
      'cerebral edema': ['Edema cerebral difuso', 'Apagamento dos sulcos por hipertensão intracraniana.'],
    },
    achados: [
      'Lesão arredondada hiperdensa no teto do terceiro ventrículo, no forame de Monro.',
      'Dilatação acentuada dos ventrículos laterais com terceiro e quarto ventrículos normais.',
      'Abaulamento do septo pelúcido para a esquerda.',
      'Hipodensidade periventricular por transudação liquórica e apagamento de sulcos.',
    ],
    armadilhas: [
      'Ventrículos laterais dilatados com terceiro e quarto normais localizam a obstrução no forame de Monro.',
      'O cisto coloide pode ser isodenso e passar despercebido; procure-o sempre que os laterais estiverem grandes e o terceiro pequeno.',
      'Cefaleia posicional com perda súbita de consciência é alerta: a obstrução intermitente pode matar.',
    ],
    conduta: 'Emergência neurocirúrgica: derivação ventricular externa ou definitiva e ressecção do cisto por via endoscópica ou microcirúrgica.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Mulher de 31 anos, advogada, trazida pelo marido.',
      queixa: 'Dor de cabeça fortíssima e vômitos desde a madrugada.',
      historia: 'Há três meses tem crises de cefaleia frontal que pioram ao abaixar a cabeça e melhoram quando deita de lado. Numa delas chegou a perder a força nas pernas e cair, recuperando-se em segundos. Hoje acordou com a pior dor da vida, vômitos em jato e visão embaçada, e ficou muito sonolenta no caminho.',
      antecedentes: [
        'Pessoais: enxaqueca diagnosticada na adolescência',
        'Gestacionais: gestação única há dois anos, sem intercorrências',
        'Familiares: mãe com enxaqueca',
        'Hábitos: anticoncepcional oral, nega tabagismo',
      ],
      vitais: { pa: '158 × 96 mmHg', fc: '52 bpm', fr: '12 irpm', satO2: '97% em ar ambiente', temp: '36,5 °C' },
      exame: [
        'Glasgow 12, sonolenta',
        'Papiledema bilateral',
        'Paralisia do sexto nervo à esquerda',
        'Sem déficit motor ou sinais meníngeos',
      ],
      pedido: 'Cefaleia posicional recorrente evoluindo com hipertensão intracraniana e tríade de Cushing parcial: a pergunta é a causa e o nível da obstrução.',
      pergunta: 'TC de crânio sem contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Hidrocefalia por cisto coloide',
      veredito: 'Hidrocefalia obstrutiva aguda por cisto coloide no forame de Monro com transudação periventricular',
      correlacao: 'A cefaleia que muda com a posição da cabeça e o episódio de queda súbita são típicos de uma lesão móvel que tampa o forame de Monro. Hoje a obstrução se manteve: hipertensão, bradicardia, papiledema e paralisia do sexto nervo. A TC mostra o nódulo denso no forame, os laterais dilatados e o terceiro e quarto ventrículos normais — o bloqueio está exatamente ali.',
      distratores: [
        d('Hipertensão intracraniana idiopática', 'Dá cefaleia, papiledema e sexto nervo em mulher jovem, mas os ventrículos são normais ou pequenos. Aqui os laterais estão muito dilatados com transudação.'),
        d('Estenose do aqueduto cerebral', 'Também obstrui o fluxo, mas dilata os laterais e o terceiro ventrículo, poupando só o quarto. Neste caso o terceiro ventrículo está normal, o que sobe o bloqueio para o forame de Monro.'),
        d('Trombose venosa cerebral', 'Anticoncepcional e cefaleia cabem, porém a TC mostra seio venoso hiperdenso, infartos venosos ou hemorragia, e não dilatação ventricular obstrutiva.'),
      ],
    },
  },

  'abscesso-cerebral': {
    titulo: 'Abscesso cerebral nos núcleos da base',
    resumo: 'Lesão hipodensa de limites definidos no putâmen, globo pálido e cápsula interna direitos, com edema e efeito de massa.',
    protocolo: 'TC de crânio sem contraste, janela de parênquima',
    rotulos: {
      mass: ['Lesão expansiva hipodensa', 'Coleção de conteúdo homogêneo e bordas razoavelmente definidas nos núcleos da base direitos.'],
      'mass effect': ['Efeito de massa', 'Compressão do ventrículo lateral e desvio das estruturas da linha média.'],
      'cerebral edema': ['Edema vasogênico', 'Hipodensidade digitiforme na substância branca em torno da lesão.'],
    },
    achados: [
      'Lesão hipodensa no putâmen, globo pálido e ramo posterior da cápsula interna à direita.',
      'Edema vasogênico perilesional digitiforme.',
      'Efeito de massa sobre o ventrículo lateral direito.',
      'Após contraste, realce anelar fino e regular é o esperado para abscesso.',
    ],
    armadilhas: [
      'Anel fino, liso e mais delgado do lado ventricular favorece abscesso; anel grosso e irregular favorece glioblastoma ou metástase.',
      'A ressonância com difusão resolve: o pus restringe a difusão, a necrose tumoral em geral não.',
      'Febre está ausente em boa parte dos abscessos; a tríade febre, cefaleia e déficit focal completa aparece na minoria.',
    ],
    conduta: 'Ressonância com difusão, hemoculturas, busca da fonte (dentes, seios, ouvido, coração), antibioticoterapia empírica de amplo espectro com boa penetração no sistema nervoso e aspiração estereotáxica para lesões grandes ou sem resposta.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Homem de 49 anos, pedreiro.',
      queixa: 'Dor de cabeça há duas semanas e fraqueza no lado esquerdo há quatro dias.',
      historia: 'A cefaleia começou gradualmente, holocraniana, pior de manhã, sem resposta a analgésicos comuns. Há quatro dias começou a tropeçar com o pé esquerdo e a deixar cair objetos da mão esquerda. Teve febre baixa em dois dias da semana passada. Há um mês extraiu um molar infectado e não completou o antibiótico.',
      antecedentes: [
        'Pessoais: diabetes tipo 2 mal controlado, última hemoglobina glicada de 10,8%',
        'Pessoais: periodontite crônica',
        'Familiares: pai diabético com amputação',
        'Hábitos: tabagista de 20 cigarros por dia e etilista de fim de semana',
      ],
      vitais: { pa: '146 × 88 mmHg', fc: '94 bpm', fr: '16 irpm', satO2: '97% em ar ambiente', temp: '37,9 °C' },
      exame: [
        'Glasgow 15, bradipsíquico',
        'Hemiparesia esquerda grau 4 com Babinski à esquerda',
        'Sem rigidez de nuca',
        'Dentição em mau estado com gengivite',
      ],
      pedido: 'Déficit focal subagudo com cefaleia progressiva, febre baixa e foco dentário recente em diabético: a pergunta é se há lesão expansiva e qual o seu aspecto.',
      pergunta: 'TC de crânio sem contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Abscesso cerebral nos núcleos da base',
      veredito: 'Abscesso cerebral nos núcleos da base direitos com edema vasogênico e efeito de massa',
      correlacao: 'Diabético com extração dentária infectada e antibiótico incompleto desenvolveu cefaleia progressiva, febre baixa e déficit motor contralateral. A TC mostra lesão hipodensa bem delimitada nos núcleos da base e cápsula interna direitos, com edema e efeito de massa — lesão expansiva infecciosa até prova em contrário, a ser confirmada pelo realce anelar fino e pela restrição à difusão.',
      distratores: [
        d('Infarto lacunar na cápsula interna', 'Explicaria a hemiparesia em diabético tabagista, mas a instalação seria súbita e a lesão pequena, sem edema nem efeito de massa. Esta lesão empurra o ventrículo e cresceu em dias.'),
        d('Glioblastoma dos núcleos da base', 'É o diferencial real de lesão com edema e efeito de massa, mas costuma ter paredes grossas e irregulares com necrose central heterogênea. A história de foco dentário e febre, e o conteúdo homogêneo, apontam para pus.'),
        d('Toxoplasmose cerebral em imunodeprimido', 'Forma lesões múltiplas com realce anelar nos núcleos da base, mas em paciente com HIV avançado. Este paciente tem lesão única, foco dentário e nenhuma imunodeficiência conhecida.'),
      ],
    },
  },

  glioblastoma: {
    titulo: 'Glioblastoma frontal',
    resumo: 'Massa córtico-subcortical frontal esquerda com centro necrótico, borda irregular com focos hemorrágicos e edema extenso.',
    protocolo: 'TC de crânio sem contraste, janela de parênquima',
    rotulos: {
      'cortico-subcortical mass': ['Massa córtico-subcortical', 'Lesão frontal esquerda, predominantemente hipodensa, que ocupa córtex e substância branca.'],
      'peripheral rim': ['Borda periférica irregular', 'Anel iso a hiperdenso, espesso e irregular: tumor viável em torno do centro necrótico.'],
      'hyperattenuating foci': ['Focos hiperdensos', 'Pequenos focos de sangramento ou calcificação na parede tumoral.'],
      'white matter hypoattenuation': ['Edema da substância branca', 'Hipodensidade digitiforme que se espalha pela substância branca, poupando o córtex.'],
    },
    achados: [
      'Massa córtico-subcortical frontal esquerda com centro hipodenso necrótico.',
      'Borda espessa e irregular, iso a hiperdensa, com focos hemorrágicos.',
      'Edema vasogênico extenso na substância branca.',
      'Efeito de massa com compressão do corno frontal.',
    ],
    armadilhas: [
      'Glioblastoma pode cruzar o corpo caloso e acometer os dois hemisférios — o padrão em borboleta é quase específico.',
      'A área que realça não é o limite do tumor: células infiltram o edema além da borda visível.',
      'Lesão única com anel irregular em adulto é glioblastoma ou metástase; procure primário antes de concluir.',
    ],
    conduta: 'Corticoide para o edema, ressonância com perfusão e espectroscopia, ressecção máxima segura seguida de radioterapia com temozolomida.',
    vinheta: {
      cenario: 'Ambulatório de neurologia',
      identificacao: 'Homem de 63 anos, engenheiro aposentado, trazido pela esposa.',
      queixa: 'Mudança de comportamento e dor de cabeça há dois meses.',
      historia: 'A esposa conta que ele ficou apático, deixou de cuidar das finanças e passou a fazer comentários inadequados em público, o que nunca fazia. Há três semanas tem cefaleia matinal que melhora durante o dia. Na semana passada teve uma crise com abalos no braço direito que durou um minuto. Nega febre ou perda de peso importante.',
      antecedentes: [
        'Pessoais: hipertensão controlada com anlodipino',
        'Pessoais: sem neoplasias prévias; colonoscopia normal há dois anos',
        'Familiares: sem doenças neurológicas ou síndromes de câncer',
        'Hábitos: nunca fumou, etilismo social',
      ],
      vitais: { pa: '138 × 82 mmHg', fc: '70 bpm', fr: '14 irpm', satO2: '98% em ar ambiente', temp: '36,4 °C' },
      exame: [
        'Desinibição e apatia, com reflexo de preensão palmar',
        'Afasia não fluente leve',
        'Paresia facial central direita',
        'Papiledema incipiente',
      ],
      pedido: 'Síndrome frontal progressiva com crise focal e hipertensão intracraniana em idoso: a pergunta é se há lesão expansiva e qual o seu aspecto.',
      pergunta: 'TC de crânio sem contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Glioma de alto grau frontal',
      veredito: 'Glioblastoma frontal esquerdo com necrose central, borda irregular e edema vasogênico extenso',
      correlacao: 'Desinibição, apatia e preensão palmar são o lobo frontal falando; a crise focal e a cefaleia matinal indicam lesão que cresce e irrita o córtex. A TC mostra massa frontal esquerda com centro necrótico, parede espessa e irregular com focos de sangue e edema que se espalha pela substância branca — o retrato do glioblastoma.',
      distratores: [
        d('Doença de Alzheimer de início tardio', 'Começa com perda de memória recente e evolui em anos, sem crises focais nem papiledema. A TC mostraria atrofia hipocampal, e não uma massa com edema.'),
        d('Meningioma da convexidade frontal', 'Também causa síndrome frontal, mas é extra-axial, hiperdenso e homogêneo, com base dural e às vezes hiperostose. Esta lesão nasce dentro do parênquima e tem centro necrótico.'),
        d('Abscesso cerebral frontal', 'Forma anel, mas fino e regular, com conteúdo que restringe difusão e geralmente foco infeccioso. O anel deste paciente é espesso, irregular e com hemorragia, sem febre nem fonte.'),
      ],
    },
  },

  'metastases-cerebrais': {
    titulo: 'Metástases cerebrais múltiplas',
    resumo: 'Lesões múltiplas supra e infratentoriais com realce anelar e edema vasogênico desproporcional ao tamanho, incluindo uma de base dural.',
    protocolo: 'TC de crânio sem e com contraste',
    rotulos: {
      'ring enhancement': ['Realce anelar', 'Lesão com anel que capta contraste em torno de centro necrótico.'],
      'vasogenic edema': ['Edema vasogênico', 'Edema digitiforme muito maior que a própria lesão, típico de metástase.'],
      'dural-based': ['Lesão de base dural', 'Implante junto à dura, que pode simular meningioma.'],
    },
    achados: [
      'Múltiplas lesões nos hemisférios cerebrais e cerebelares, de tamanhos variados.',
      'Realce anelar periférico após contraste.',
      'Edema vasogênico desproporcional ao tamanho das lesões.',
      'Implante de base dural associado.',
    ],
    armadilhas: [
      'Lesões múltiplas na junção córtico-subcortical, em territórios diferentes, sugerem disseminação hematogênica.',
      'Pulmão, mama, melanoma, rim e cólon são os primários mais frequentes; melanoma, rim e tireoide sangram.',
      'Lesões pequenas só aparecem com contraste; a ressonância detecta mais do que a TC.',
    ],
    conduta: 'Corticoide para o edema, estadiamento do primário, ressonância com contraste e discussão entre radiocirurgia, radioterapia de crânio total e ressecção conforme número, tamanho e performance.',
    vinheta: {
      cenario: 'Pronto-socorro oncológico',
      identificacao: 'Mulher de 56 anos, comerciante.',
      queixa: 'Tontura, desequilíbrio e dor de cabeça há três semanas.',
      historia: 'Refere cefaleia progressiva, pior pela manhã, e desequilíbrio que a faz cair para a direita ao andar. Nos últimos dias vomita ao levantar. Emagreceu 8 kg em quatro meses e tem tosse seca persistente que atribuiu ao cigarro.',
      antecedentes: [
        'Pessoais: DPOC leve, sem acompanhamento',
        'Gestacionais: quatro gestações, amamentou todos os filhos',
        'Familiares: pai faleceu de câncer de pulmão',
        'Hábitos: tabagista de 45 maços-ano, ativa',
      ],
      vitais: { pa: '142 × 86 mmHg', fc: '84 bpm', fr: '18 irpm', satO2: '93% em ar ambiente', temp: '36,6 °C' },
      exame: [
        'Ataxia apendicular direita e marcha de base alargada',
        'Nistagmo horizontal ao olhar para a direita',
        'Paresia leve em membro superior esquerdo',
        'Baqueteamento digital',
      ],
      pedido: 'Sinais cerebelares e piramidais em lados diferentes, com perda de peso e tabagismo pesado: a pergunta é se há lesões múltiplas e de que natureza.',
      pergunta: 'TC de crânio com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Metástases cerebrais múltiplas',
      veredito: 'Metástases cerebrais múltiplas supra e infratentoriais com realce anelar e edema desproporcional',
      correlacao: 'Um único lugar não explica ataxia direita e paresia esquerda ao mesmo tempo: são lesões em mais de um território. Tabagismo pesado, emagrecimento, tosse e baqueteamento apontam para câncer de pulmão. A TC mostra várias lesões com anel e edema muito maior que elas próprias, no cerebelo e nos hemisférios — disseminação hematogênica.',
      distratores: [
        d('Abscessos cerebrais múltiplos', 'Também dão anéis múltiplos, mas o anel é fino e regular, o conteúdo restringe difusão e há febre ou fonte embólica. Aqui o quadro é consumptivo, sem febre, em tabagista com baqueteamento.'),
        d('Esclerose múltipla tumefativa', 'Pode realçar em anel incompleto aberto para o córtex, com pouco edema, em adultos jovens. Esta paciente tem 56 anos, lesões com anel completo e edema desproporcional.'),
        d('Infartos embólicos cardioembólicos', 'Múltiplos territórios cabem, mas o início é súbito e as lesões são cunhas corticais hipodensas sem anel. Esta evolução é de semanas e as lesões captam contraste na periferia.'),
      ],
    },
  },

  pneumoencefalo: {
    titulo: 'Pneumoencéfalo',
    resumo: 'Ar nos espaços subaracnoideos da convexidade e nas cisternas da base, predominante à esquerda, com foco hiperdenso associado.',
    protocolo: 'TC de crânio sem contraste, janelas de parênquima e óssea',
    rotulos: {
      gas: ['Gás intracraniano', 'Densidade negativa, igual à do ar, dentro da caixa craniana.'],
      'air in the subarachnoid spaces': ['Ar no espaço subaracnoideo', 'Bolhas pretas desenhando sulcos e cisternas, fora dos vasos.'],
      'A small hyperdense focus': ['Pequeno foco hiperdenso', 'Foco denso associado: sangue ou fragmento ósseo.'],
    },
    achados: [
      'Gás nos espaços subaracnoideos das convexidades, predominante à esquerda.',
      'Gás nas cisternas da base.',
      'Pequeno foco hiperdenso associado.',
      'Sem sinal do monte Fuji, que indicaria pneumoencéfalo hipertensivo.',
    ],
    armadilhas: [
      'Pneumoencéfalo após trauma significa comunicação com seio paranasal, mastoide ou pele: procure a fratura na janela óssea.',
      'Ar bifrontal separando os polos frontais com aspecto de montanha (sinal do monte Fuji) indica ar sob tensão e é emergência.',
      'Ar intracraniano após cirurgia ou punção lombar é esperado e reabsorve em dias.',
    ],
    conduta: 'Tratar a causa: fístula por fratura de base pede observação e, se persistir liquorreia, reparo cirúrgico. Oxigênio a 100% acelera a reabsorção; pneumoencéfalo hipertensivo exige descompressão.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Homem de 38 anos, operador de máquinas.',
      queixa: 'Dor de cabeça e líquido claro escorrendo pelo nariz desde ontem.',
      historia: 'Há dois dias caiu de uma escada de três metros e bateu a testa e o lado esquerdo do rosto, sem perda de consciência prolongada. Ontem notou que, ao se inclinar para a frente, escorre um líquido transparente e salgado pela narina esquerda. Hoje a cefaleia piorou e ouviu um barulho de líquido dentro da cabeça ao virar.',
      antecedentes: [
        'Pessoais: previamente hígido',
        'Pessoais: sinusite crônica sem tratamento',
        'Familiares: sem doenças relevantes',
        'Hábitos: nega álcool e tabagismo; não usava equipamento de proteção',
      ],
      vitais: { pa: '132 × 80 mmHg', fc: '80 bpm', fr: '16 irpm', satO2: '98% em ar ambiente', temp: '36,8 °C' },
      exame: [
        'Glasgow 15',
        'Equimose periorbitária esquerda',
        'Rinorreia clara com sinal do duplo halo positivo',
        'Sem sinais meníngeos nem déficits focais',
      ],
      pedido: 'Trauma frontofacial com rinorreia clara e cefaleia progressiva: a pergunta é se há comunicação entre o espaço intracraniano e as vias aéreas.',
      pergunta: 'TC de crânio sem contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Pneumoencéfalo subaracnoideo traumático',
      veredito: 'Pneumoencéfalo subaracnoideo em convexidades e cisternas por fístula traumática',
      correlacao: 'A rinorreia clara com duplo halo é líquor saindo por uma fratura da base anterior; pelo mesmo caminho o ar entra. A TC mostra gás preto desenhando sulcos e cisternas, predominante à esquerda — a prova de que o espaço subaracnoideo comunica com o exterior.',
      distratores: [
        d('Rinossinusite aguda com secreção', 'A secreção nasal seria purulenta e não aumentaria ao inclinar a cabeça; o duplo halo não aparece e a TC mostraria seios opacificados sem gás intracraniano.'),
        d('Meningite bacteriana pós-traumática', 'É o risco dessa fístula, com febre, rigidez de nuca e rebaixamento. O paciente está afebril, sem sinais meníngeos, e o achado é ar, não realce meníngeo.'),
        d('Hematoma subdural agudo frontal', 'Seria um crescente hiperdenso sobre a convexidade após o trauma. O que se vê aqui é densidade negativa, de ar, e não sangue hiperdenso.'),
      ],
    },
  },
}
