import { d, type ConteudoCasoTC } from './casos-tc-tipos'

/** Casos de TC no trauma. Pacientes das vinhetas são fictícios. */
export const CASOS_TC_TRAUMA: Record<string, ConteudoCasoTC> = {
  'trauma-hepatico-grau-v': {
    titulo: 'Lesão hepática contusa grau V',
    resumo: 'Laceração estrelada atravessando mais de 75% do lobo direito, com extravasamento arterial ativo de ramo da artéria hepática direita.',
    protocolo: 'TC de abdome com contraste, fases arterial e portal',
    rotulos: {
      'active arterial extravasation': ['Extravasamento arterial ativo', 'Contraste com densidade de artéria escapando para o parênquima: sangramento em curso.'],
      'right hepatic artery.': ['Artéria hepática direita', 'Ramo de onde parte o sangramento, alvo da embolização.'],
    },
    achados: [
      'Ruptura parenquimatosa extensa dos segmentos 5, 6, 7 e 8.',
      'Laceração estrelada em mais de 75% do lobo direito.',
      'Extravasamento arterial ativo a partir de ramos da artéria hepática direita.',
      'Hemoperitônio.',
    ],
    armadilhas: [
      'O grau AAST orienta, mas quem decide a cirurgia é a hemodinâmica: lesões grau V em paciente estável podem ser tratadas com embolização.',
      'Extravasamento ativo aparece como contraste que cresce e muda de forma entre a fase arterial e a portal.',
      'Lesão das veias hepáticas ou da cava retro-hepática é a mais letal e difícil de controlar.',
    ],
    conduta: 'Paciente estável: angioembolização e tratamento não operatório em unidade intensiva. Instável: laparotomia com controle de danos e tamponamento hepático.',
    vinheta: {
      cenario: 'Trauma, sala vermelha',
      identificacao: 'Homem de 23 anos, motoboy.',
      queixa: 'Dor forte no lado direito da barriga e do tórax após colisão com carro.',
      historia: 'Colidiu frontalmente com um carro a cerca de 60 km/h e bateu o lado direito do tórax e do abdome no guidão. Estava de capacete. Refere dor no hipocôndrio direito que irradia para o ombro direito e falta de ar leve. Recebeu dois litros de cristaloide no atendimento pré-hospitalar e respondeu.',
      antecedentes: [
        'Pessoais: previamente hígido',
        'Pessoais: sem uso de anticoagulantes',
        'Familiares: sem coagulopatias',
        'Hábitos: etilismo social, ingeriu cerveja antes do acidente',
      ],
      vitais: { pa: '104 × 66 mmHg após reposição', fc: '112 bpm', fr: '24 irpm', satO2: '96% com máscara', temp: '36,1 °C' },
      exame: [
        'Escoriação do guidão no hipocôndrio direito',
        'Dor e defesa no quadrante superior direito',
        'FAST com líquido no espaço hepatorrenal',
        'Fraturas de costelas inferiores direitas à palpação',
      ],
      pedido: 'Trauma abdominal fechado com FAST positivo em paciente que respondeu à reposição: a pergunta é a lesão de órgão sólido e se há sangramento ativo.',
      pergunta: 'TC de abdome com contraste em fases arterial e portal. Qual é o achado que responde à pergunta clínica?',
      achado: 'Lesão hepática grau V com sangramento',
      veredito: 'Lesão hepática contusa grau V com laceração do lobo direito e extravasamento arterial ativo',
      correlacao: 'O guidão comprimiu o fígado contra as costelas e a coluna e o partiu em estrela. A dor no ombro direito é o sangue irritando o diafragma (sinal de Kehr), e o FAST mostrou o líquido no espaço hepatorrenal. A TC define a extensão — mais de 75% do lobo direito — e o contraste escapando de ramo da artéria hepática: sangramento ativo que pede embolização imediata enquanto ele estiver respondendo.',
      distratores: [
        d('Laceração hepática superficial grau II', 'Ferida de até 3 cm de profundidade, sem extravasamento, que costuma parar sozinha. Esta laceração atravessa quase todo o lobo e sangra ativamente.'),
        d('Lesão renal direita com urinoma', 'Daria coleção perirrenal, com extravasamento na fase excretora e hematúria. A lesão aqui está no parênquima hepático, e o sangue vem da artéria hepática.'),
        d('Hematoma subcapsular hepático isolado', 'Coleção em crescente sob a cápsula que comprime o parênquima, sem ruptura estrelada. Este fígado está partido em vários segmentos.'),
      ],
    },
  },

  'ruptura-esplenica-hemoperitonio': {
    titulo: 'Laceração esplênica com hemoperitônio após colonoscopia',
    resumo: 'Líquido com densidade de sangue em torno do baço, na goteira parietocólica esquerda e em grande volume na pelve.',
    protocolo: 'TC de abdome com contraste venoso, fase portal',
    rotulos: {
      'Free fluid surrounding the spl': ['Líquido periesplênico', 'Sangue em volta do baço, com densidade de 40 a 70 UH.'],
      'left pericolic gutter': ['Goteira parietocólica esquerda', 'O sangue desce do baço pela goteira esquerda.'],
      blood: ['Hemoperitônio pélvico', 'Grande volume de sangue acumulado na pelve, o ponto mais baixo.'],
    },
    achados: [
      'Líquido livre em torno do baço e na goteira parietocólica esquerda.',
      'Grande volume de líquido na pelve.',
      'Densidade do líquido entre 40 e 70 UH, compatível com hemoperitônio.',
      'Sem extravasamento ativo de contraste.',
    ],
    armadilhas: [
      'Coágulo sentinela: o sangue mais denso fica junto ao órgão que sangra e aponta a origem.',
      'Lesão esplênica após colonoscopia é rara e ocorre pela tração do ligamento esplenocólico na flexura esplênica.',
      'Líquido com densidade de água sugere ascite; acima de 30 a 40 UH, sangue.',
    ],
    conduta: 'Estável e sem extravasamento: observação em unidade intensiva com hemoglobina seriada. Extravasamento ou instabilidade: embolização ou esplenectomia.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Mulher de 66 anos, aposentada.',
      queixa: 'Dor no lado esquerdo da barriga e no ombro esquerdo, horas após uma colonoscopia.',
      historia: 'Fez colonoscopia de rastreio pela manhã, descrita como difícil na flexura esplênica, com retirada de um pólipo. À tarde começou dor no hipocôndrio esquerdo que irradia para o ombro esquerdo e piora ao deitar. Sentiu tontura ao levantar e desmaiou no banheiro.',
      antecedentes: [
        'Pessoais: fibrilação atrial em uso de apixabana, suspensa dois dias antes do exame',
        'Pessoais: cirurgia abdominal prévia com aderências',
        'Gestacionais: duas gestações',
        'Familiares: pai com câncer de cólon',
      ],
      vitais: { pa: '94 × 58 mmHg', fc: '116 bpm', fr: '22 irpm', satO2: '97% em ar ambiente', temp: '36,4 °C' },
      exame: [
        'Dor no hipocôndrio esquerdo com defesa',
        'Sinal de Kehr presente',
        'Abdome levemente distendido, sem gás livre ao exame',
        'Hemoglobina caiu de 13,0 para 9,1 g/dL',
      ],
      pedido: 'Dor em hipocôndrio esquerdo com irradiação para o ombro e queda da hemoglobina após colonoscopia difícil: a pergunta é se há perfuração ou sangramento intra-abdominal.',
      pergunta: 'TC de abdome com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Hemoperitônio por lesão esplênica',
      veredito: 'Laceração esplênica pós-colonoscopia com hemoperitônio periesplênico, na goteira esquerda e na pelve',
      correlacao: 'A tração do colonoscópio na flexura esplênica puxa o ligamento esplenocólico, especialmente quando há aderências, e rasga a cápsula do baço. O sangue irrita o diafragma — dor no ombro esquerdo — e desce pela goteira até a pelve. A queda da hemoglobina e a síncope combinam. A TC mostra sangue em torno do baço, na goteira e na pelve, sem gás livre.',
      distratores: [
        d('Perfuração colônica pós-colonoscopia', 'É a complicação mais temida, com gás livre ou retroperitoneal e peritonite, sem queda tão grande da hemoglobina. Não há gás livre e o líquido tem densidade de sangue.'),
        d('Síndrome pós-polipectomia', 'Dor localizada e febre por queimadura transmural no local do pólipo, sem perfuração nem hemoperitônio. Aqui há sangue livre e anemia aguda.'),
        d('Hematoma da bainha do reto', 'Massa na parede abdominal anterior em anticoagulados, sem líquido livre intraperitoneal. O sangue desta paciente está dentro da cavidade, ao redor do baço.'),
      ],
    },
  },

  'politrauma-abdominal': {
    titulo: 'Politrauma abdominal',
    resumo: 'Hemoperitônio volumoso com laceração hepática no segmento 6, sangramento arterial ativo, lesão de delgado, fratura de processo transverso e cinta pélvica.',
    protocolo: 'TC de corpo inteiro no trauma, fases arterial e portal',
    rotulos: {
      'liver laceration': ['Laceração hepática', 'Área hipoatenuante de 15 × 32 mm no segmento 6, com líquido em volta.'],
      'free fluid': ['Líquido livre', 'Sangue em volta do fígado e do baço, entre as alças e na pelve.'],
      'arterial blush': ['Blush arterial', 'Foco de contraste com densidade de artéria fora do vaso: sangramento ativo.'],
      'Active bleeding': ['Sangramento ativo', 'O contraste aumenta entre as fases: o sangramento continua.'],
      'small bowel mural thickening': ['Espessamento da parede do delgado', 'Parede de alça espessa por contusão ou lesão mesentérica.'],
      'transverse pocess fracture': ['Fratura de processo transverso', 'Traço no processo transverso lombar, marca de energia alta no flanco.'],
      'pelvic binder': ['Cinta pélvica', 'Dispositivo de estabilização pélvica colocado no atendimento.'],
    },
    achados: [
      'Hemoperitônio volumoso em torno do fígado, baço, entre alças e na pelve.',
      'Laceração hepática no segmento 6.',
      'Foco de sangramento arterial ativo.',
      'Espessamento da parede do delgado, fratura de processo transverso lombar e cinta pélvica posicionada.',
    ],
    armadilhas: [
      'Espessamento parietal de delgado com líquido livre sem lesão de órgão sólido sugere lesão de víscera oca ou mesentério, que exige laparotomia.',
      'Fratura de processo transverso lombar é marcador de trauma de alta energia e se associa a lesões viscerais e renais.',
      'A cinta pélvica pode reduzir uma fratura e escondê-la na TC; avaliar a pelve depois de retirá-la com segurança.',
    ],
    conduta: 'Controle de danos: angioembolização ou laparotomia conforme a hemodinâmica, transfusão balanceada e ácido tranexâmico precoce.',
    vinheta: {
      cenario: 'Trauma, sala vermelha',
      identificacao: 'Mulher de 34 anos, passageira do banco da frente.',
      queixa: 'Dor abdominal difusa após capotamento de carro em rodovia.',
      historia: 'O carro capotou a cerca de 100 km/h. Estava com cinto de segurança de três pontos, com marca evidente no abdome. Foi retirada das ferragens após 30 minutos. A equipe colocou cinta pélvica por dor no quadril e iniciou reposição com resposta transitória.',
      antecedentes: [
        'Pessoais: previamente hígida',
        'Gestacionais: teste de gravidez negativo na admissão; duas gestações prévias',
        'Familiares: sem coagulopatias',
        'Hábitos: nega álcool e drogas',
      ],
      vitais: { pa: '88 × 54 mmHg após dois litros', fc: '128 bpm', fr: '28 irpm', satO2: '95% com máscara', temp: '35,6 °C' },
      exame: [
        'Sinal do cinto de segurança no abdome inferior',
        'Abdome distendido e doloroso difusamente',
        'Dor no flanco direito e hematúria microscópica',
        'FAST positivo em vários quadrantes',
      ],
      pedido: 'Trauma de alta energia com sinal do cinto, FAST positivo e resposta transitória à reposição: a pergunta é a fonte do sangramento e se há lesão de víscera oca.',
      pergunta: 'TC de corpo inteiro no trauma. Qual é o conjunto de achados que responde à pergunta clínica?',
      achado: 'Hemoperitônio com sangramento ativo',
      veredito: 'Hemoperitônio volumoso com laceração hepática, sangramento arterial ativo e lesão de delgado',
      correlacao: 'Capotamento a alta velocidade com cinto abdominal: o cinto comprime as vísceras contra a coluna, lesando fígado, mesentério e delgado, e o mesmo mecanismo fratura processos transversos. A resposta transitória à reposição já sugeria sangramento contínuo. A TC mostra o sangue em todos os recessos, a laceração do segmento 6, o contraste escapando e a alça com parede espessa.',
      distratores: [
        d('Lesão esplênica grau I isolada', 'Hematoma subcapsular pequeno com pouco líquido periesplênico, compatível com observação. Esta paciente tem hemoperitônio em todos os recessos e sangramento ativo.'),
        d('Fratura pélvica com hematoma isolado', 'A cinta pélvica sugere, mas o sangue ficaria retroperitoneal na pelve, sem hemoperitônio em torno do fígado e do baço. Aqui o sangue é intraperitoneal e há laceração hepática.'),
        d('Ruptura diafragmática esquerda', 'Levaria estômago ou cólon para o tórax, com sinal do colar e elevação da cúpula. O diafragma desta paciente está íntegro e o problema é abdominal.'),
      ],
    },
  },

  'fratura-de-plato-tibial-com-lesao-arterial': {
    titulo: 'Fratura do platô tibial Schatzker VI com lesão da artéria poplítea',
    resumo: 'Fratura cominutiva intra-articular do platô com dissociação metáfise-diáfise e oclusão da artéria poplítea com reconstituição distal.',
    protocolo: 'Angiotomografia do membro inferior, fase arterial',
    rotulos: {
      'Popliteal artery occlusion': ['Oclusão da artéria poplítea', 'Interrupção abrupta do contraste na poplítea, no nível da fratura.'],
      'Muscular arterial branches': ['Ramos musculares colaterais', 'Pequenas artérias que contornam a oclusão.'],
      'Reconstituted arterial flow': ['Reconstituição do fluxo', 'O contraste reaparece distal à oclusão pelas colaterais.'],
    },
    achados: [
      'Fratura cominutiva e desviada intra-articular do platô tibial lateral junto à área intercondilar.',
      'Fratura transversa impactada na transição metáfise-diáfise: Schatzker VI.',
      'Oclusão da artéria poplítea no nível da fratura.',
      'Ramos musculares colaterais e reconstituição do fluxo distal.',
    ],
    armadilhas: [
      'Fraturas bicondilares e luxações do joelho têm alto risco de lesão poplítea: índice tornozelo-braquial abaixo de 0,9 pede angiotomografia.',
      'Pulso pedioso presente não exclui lesão arterial; colaterais podem mantê-lo palpável.',
      'Síndrome compartimental acompanha as fraturas de alta energia da perna: dor à extensão passiva é o sinal precoce.',
    ],
    conduta: 'Estabilização provisória com fixador externo, revascularização urgente com derivação ou enxerto, fasciotomia profilática e fixação definitiva quando as partes moles permitirem.',
    vinheta: {
      cenario: 'Trauma, pronto-socorro',
      identificacao: 'Homem de 45 anos, motociclista.',
      queixa: 'Dor intensa e deformidade no joelho esquerdo após queda de moto.',
      historia: 'Caiu de moto em alta velocidade e o joelho esquerdo bateu de frente no meio-fio. Não consegue mexer a perna, que está deformada e muito inchada. Sente o pé esquerdo frio e formigando desde o acidente.',
      antecedentes: [
        'Pessoais: previamente hígido',
        'Pessoais: sem doença arterial periférica',
        'Familiares: sem doenças relevantes',
        'Hábitos: tabagista de 20 cigarros por dia',
      ],
      vitais: { pa: '132 × 82 mmHg', fc: '104 bpm', fr: '20 irpm', satO2: '98% em ar ambiente', temp: '36,4 °C' },
      exame: [
        'Deformidade e edema volumoso no joelho esquerdo',
        'Pé esquerdo pálido e frio com enchimento capilar lento',
        'Pulsos pedioso e tibial posterior esquerdos fracos',
        'Índice tornozelo-braquial de 0,6 à esquerda',
      ],
      pedido: 'Fratura de alta energia do joelho com pé frio e índice tornozelo-braquial reduzido: a pergunta é o padrão da fratura e se há lesão arterial.',
      pergunta: 'Angiotomografia do membro inferior. Qual é o achado que responde à pergunta clínica?',
      achado: 'Oclusão traumática da artéria poplítea',
      veredito: 'Fratura do platô tibial Schatzker VI com oclusão da artéria poplítea e reconstituição distal por colaterais',
      correlacao: 'A artéria poplítea fica presa entre o hiato dos adutores e o arco do sóleo; quando o platô e a metáfise se deslocam, ela é estirada e a íntima rompe, trombosando. O pé frio, pálido e com índice tornozelo-braquial de 0,6 já dizia isso. A angiotomografia mostra a interrupção da poplítea no nível da fratura e o fluxo voltando por colaterais — isquemia que conta em horas.',
      distratores: [
        d('Espasmo arterial transitório pós-trauma', 'Reduz o calibre de forma difusa e reverte com reaquecimento e redução da fratura, sem interrupção abrupta do contraste. Aqui há oclusão completa no nível da fratura.'),
        d('Trombose venosa profunda poplítea', 'Causa edema e dor, mas o pé fica quente e avermelhado, com pulsos normais. Este pé está frio e pálido, e a falha é na artéria.'),
        d('Síndrome compartimental aguda da perna', 'Dá dor desproporcional e à extensão passiva com compartimentos tensos, e os pulsos costumam estar presentes até tarde. A angiotomografia mostra uma oclusão arterial, que é outra coisa.'),
      ],
    },
  },

  'fratura-vertebral-em-explosao': {
    titulo: 'Fratura em explosão de L2',
    resumo: 'Fratura cominutiva do corpo vertebral de L2 com retropulsão de fragmento para o canal e estenose, com elementos posteriores preservados.',
    protocolo: 'TC de coluna lombar sem contraste, reconstrução sagital, janela óssea',
    rotulos: {
      'L2 vertebral body': ['Corpo vertebral de L2', 'Corpo achatado e fragmentado, com muro posterior empurrado para dentro do canal.'],
    },
    achados: [
      'Fratura em explosão do corpo vertebral de L2.',
      'Retropulsão de fragmento do muro posterior para o canal vertebral.',
      'Estenose do canal vertebral.',
      'Elementos posteriores aparentemente íntegros.',
    ],
    armadilhas: [
      'O que separa explosão de compressão simples é o muro posterior: se ele foi acometido, a coluna média falhou.',
      'Na transição toracolombar, fraturas por queda de altura se associam a fraturas do calcâneo: examine os pés.',
      'Elementos posteriores lesados ou ligamento posterior rompido tornam a fratura instável; a ressonância avalia o complexo ligamentar.',
    ],
    conduta: 'Imobilização e avaliação neurológica seriada; sem déficit e com complexo ligamentar íntegro, órtese; com déficit ou instabilidade, descompressão e fixação.',
    vinheta: {
      cenario: 'Trauma, pronto-socorro',
      identificacao: 'Homem de 31 anos, montador de andaimes.',
      queixa: 'Dor intensa nas costas após queda de quatro metros.',
      historia: 'Caiu de pé de um andaime de quatro metros e sentiu dor imediata e muito forte na região lombar alta. Não perdeu a consciência. Refere formigamento nas coxas e dificuldade para urinar desde a queda. Também sente dor no calcanhar direito.',
      antecedentes: [
        'Pessoais: previamente hígido',
        'Pessoais: sem osteoporose ou uso de corticoide',
        'Familiares: sem doenças ósseas',
        'Hábitos: não usava cinto de segurança no trabalho em altura',
      ],
      vitais: { pa: '134 × 80 mmHg', fc: '96 bpm', fr: '18 irpm', satO2: '98% em ar ambiente', temp: '36,6 °C' },
      exame: [
        'Dor à palpação dos processos espinhosos da transição toracolombar',
        'Força preservada nos membros inferiores',
        'Hipoestesia discreta nas faces anteriores das coxas',
        'Edema e dor no calcâneo direito',
      ],
      pedido: 'Queda de altura com carga axial, dor toracolombar e sintomas neurológicos leves: a pergunta é o tipo de fratura e se há comprometimento do canal.',
      pergunta: 'TC de coluna lombar com reconstrução sagital. Qual é o achado que responde à pergunta clínica?',
      achado: 'Fratura em explosão com retropulsão',
      veredito: 'Fratura em explosão do corpo de L2 com retropulsão para o canal e estenose',
      correlacao: 'A queda de pé transmite carga axial pela coluna até a transição toracolombar, ponto de maior tensão. O corpo vertebral explode e o muro posterior é empurrado para o canal, explicando a hipoestesia e a dificuldade urinária. A dor no calcanhar lembra o padrão de queda com carga axial. A TC sagital mostra o corpo de L2 fragmentado e o fragmento dentro do canal.',
      distratores: [
        d('Fratura por compressão em cunha', 'Acomete só a coluna anterior, com muro posterior íntegro e sem fragmento no canal, em geral estável. Este corpo explodiu e invadiu o canal.'),
        d('Fratura de Chance por flexão-distração', 'Rompe horizontalmente o corpo e os elementos posteriores, típica do cinto abdominal em colisões. Aqui os elementos posteriores estão íntegros e o mecanismo foi axial.'),
        d('Hérnia discal traumática L1 L2', 'Comprimiria o canal com material discal, sem fragmentação óssea do corpo. O que ocupa o canal deste paciente é osso do muro posterior.'),
      ],
    },
  },
}
