import { d, type ConteudoCasoTC } from './casos-tc-tipos'

/** Casos de TC de tórax. Pacientes das vinhetas são fictícios. */
export const CASOS_TC_TORAX: Record<string, ConteudoCasoTC> = {
  'tep-a-cavaleiro': {
    titulo: 'Tromboembolismo pulmonar a cavaleiro',
    resumo: 'Trombo em sela na bifurcação do tronco pulmonar, estendendo-se às artérias lobares, segmentares e subsegmentares, com sobrecarga do ventrículo direito.',
    protocolo: 'Angiotomografia de artérias pulmonares, janela de mediastino',
    rotulos: {
      right: ['Artéria pulmonar direita', 'Falha de enchimento na artéria pulmonar principal direita, continuação do trombo em sela.'],
      left: ['Artéria pulmonar esquerda', 'O trombo cavalga a bifurcação e ocupa também a artéria principal esquerda.'],
      'left upper': ['Artéria do lobo superior esquerdo', 'Falha de enchimento no ramo lobar superior esquerdo.'],
      upper: ['Segmentar do lobo superior direito', 'Trombo nos ramos segmentares do lobo superior direito.'],
      middle: ['Segmentar do lobo médio', 'Trombo no ramo segmentar do lobo médio.'],
      subsegmental: ['Ramo subsegmentar', 'Falha de enchimento em ramo subsegmentar periférico.'],
      'left subsegmental': ['Subsegmentar esquerdo', 'Trombo em ramo subsegmentar do pulmão esquerdo.'],
      'right ventricle': ['Ventrículo direito dilatado', 'O ventrículo direito fica maior que o esquerdo: sobrecarga aguda de pressão.'],
      flattening: ['Retificação do septo interventricular', 'O septo perde a curvatura e se aplana em direção ao ventrículo esquerdo.'],
    },
    achados: [
      'Falha de enchimento em sela na bifurcação do tronco pulmonar, estendendo-se às duas artérias principais.',
      'Trombos lobares, segmentares e subsegmentares bilaterais.',
      'Ventrículo direito dilatado, com relação VD/VE acima de 1.',
      'Retificação do septo interventricular.',
    ],
    armadilhas: [
      'O tamanho do trombo não define a gravidade: quem define é o ventrículo direito e o estado hemodinâmico.',
      'Artefato de fluxo por contraste mal cronometrado simula falha de enchimento; o trombo verdadeiro persiste em cortes consecutivos e forma ângulo agudo com a parede.',
      'Refluxo de contraste para a veia cava inferior e as veias hepáticas é outro sinal de disfunção do ventrículo direito.',
    ],
    conduta: 'Estratificação por hemodinâmica, troponina, BNP e relação VD/VE. Anticoagulação plena imediata; trombólise sistêmica se houver instabilidade hemodinâmica; trombectomia ou trombólise dirigida por cateter em casos selecionados.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Mulher de 52 anos, contadora.',
      queixa: 'Falta de ar súbita e desmaio em casa há duas horas.',
      historia: 'Operou o joelho direito há dezesseis dias e ficou com a perna imobilizada, levantando pouco da cama. Hoje, ao ir ao banheiro, sentiu falta de ar súbita, palpitação e desmaiou por alguns segundos. Desde então não consegue falar frases inteiras. A panturrilha direita está inchada há cinco dias, o que atribuiu à cirurgia.',
      antecedentes: [
        'Pessoais: obesidade grau 2 e varizes de membros inferiores',
        'Pessoais: terapia hormonal da menopausa há dois anos',
        'Gestacionais: três gestações, uma trombose venosa no puerpério',
        'Familiares: mãe com embolia pulmonar aos 60 anos',
      ],
      vitais: { pa: '96 × 64 mmHg', fc: '124 bpm', fr: '30 irpm', satO2: '86% em ar ambiente', temp: '37,2 °C' },
      exame: [
        'Turgência jugular a 45 graus',
        'Hiperfonese de segunda bulha em foco pulmonar',
        'Pulmões limpos à ausculta',
        'Edema e empastamento da panturrilha direita',
      ],
      pedido: 'Dispneia súbita com síncope, hipoxemia e sinais de trombose venosa após cirurgia ortopédica: a pergunta é se há embolia pulmonar e qual o impacto no ventrículo direito.',
      pergunta: 'Angiotomografia de artérias pulmonares. Qual é o achado que responde à pergunta clínica?',
      achado: 'Tromboembolismo pulmonar maciço em sela',
      veredito: 'Tromboembolismo pulmonar a cavaleiro com trombos bilaterais e sobrecarga do ventrículo direito',
      correlacao: 'Pós-operatório ortopédico, imobilização, estrogênio, obesidade, trombose prévia e história familiar: a trombose da panturrilha embolizou. A síncope, a turgência jugular e a segunda bulha hiperfonética são o ventrículo direito sofrendo. A angiotomografia mostra o trombo em sela na bifurcação, ramos bilaterais ocluídos e o ventrículo direito maior que o esquerdo com septo retificado.',
      distratores: [
        d('Dissecção aguda da aorta ascendente', 'Pode causar síncope e hipotensão, mas com dor torácica lancinante, assimetria de pulsos e flap intimal na aorta. As artérias pulmonares seriam normais; aqui elas estão ocupadas por trombo.'),
        d('Infarto agudo do ventrículo direito', 'Dá hipotensão com turgência jugular e pulmões limpos, mas em contexto de infarto inferior com supradesnivelamento. Não haveria falhas de enchimento nas artérias pulmonares.'),
        d('Tamponamento cardíaco por derrame', 'Também une hipotensão, turgência jugular e pulmões limpos, mas com bulhas abafadas e pulso paradoxal. A TC mostraria líquido pericárdico, não trombo pulmonar.'),
      ],
    },
  },

  'disseccao-de-aorta-tipo-a': {
    titulo: 'Dissecção aguda da aorta tipo A de Stanford',
    resumo: 'Flap intimal da raiz da aorta ascendente ao arco, à aorta descendente e às artérias viscerais, com luz verdadeira e falsa.',
    protocolo: 'Angiotomografia de aorta, fase arterial',
    rotulos: {
      'intimal flap': ['Flap intimal', 'Linha hipodensa e ondulada dentro da aorta: a íntima descolada que separa as duas luzes.'],
      'true lumen': ['Luz verdadeira', 'Geralmente menor e mais densa, contínua com a raiz; nutre os ramos principais.'],
      'false lumen': ['Luz falsa', 'Maior, com fluxo mais lento e às vezes trombo parcial.'],
      'coeliac trunk': ['Tronco celíaco', 'A dissecção se estende ao tronco celíaco.'],
      SMA: ['Artéria mesentérica superior', 'O flap alcança a mesentérica superior: risco de isquemia intestinal.'],
      'left renal artery': ['Artéria renal esquerda', 'Ramo acometido pela dissecção, com risco de isquemia renal.'],
      'intraluminal filling defects': ['Falhas de enchimento intraluminais', 'Trombo parcial dentro da luz falsa.'],
    },
    achados: [
      'Flap intimal ondulado na raiz da aorta ascendente, estendendo-se pelo arco à aorta descendente e abdominal.',
      'Luz verdadeira menor e luz falsa maior, com trombo parcial.',
      'Extensão ao tronco celíaco, à mesentérica superior e à renal esquerda.',
      'Avaliar derrame pericárdico e acometimento coronário e dos troncos supra-aórticos.',
    ],
    armadilhas: [
      'Stanford A é qualquer dissecção que envolva a aorta ascendente, mesmo que comece distal: é cirúrgica.',
      'Artefato de movimento na raiz simula flap; o flap verdadeiro aparece em vários cortes e em outras reconstruções.',
      'Pulsos assimétricos e déficit neurológico com dor torácica devem lembrar dissecção antes da trombólise.',
    ],
    conduta: 'Controle agressivo de frequência e pressão com betabloqueador venoso, analgesia e cirurgia de emergência. Não anticoagular nem trombolisar.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Homem de 61 anos, dono de restaurante.',
      queixa: 'Dor no peito súbita, rasgando, que irradia para as costas há uma hora.',
      historia: 'Carregava caixas pesadas quando sentiu dor súbita e máxima desde o início no peito, irradiando para entre as escápulas e depois para o abdome. Sentiu fraqueza na perna esquerda por alguns minutos. Nunca teve dor semelhante. Não toma os remédios da pressão há meses.',
      antecedentes: [
        'Pessoais: hipertensão grave mal controlada',
        'Pessoais: valva aórtica bicúspide diagnosticada na juventude',
        'Familiares: irmão faleceu subitamente aos 55 anos',
        'Hábitos: tabagista de 35 maços-ano e uso ocasional de cocaína',
      ],
      vitais: { pa: '188 × 104 mmHg no braço direito e 142 × 80 mmHg no esquerdo', fc: '104 bpm', fr: '22 irpm', satO2: '95% em ar ambiente', temp: '36,5 °C' },
      exame: [
        'Pulso radial esquerdo diminuído',
        'Sopro diastólico aspirativo em foco aórtico',
        'Pulso femoral esquerdo reduzido',
        'Abdome doloroso difusamente, sem peritonismo',
      ],
      pedido: 'Dor torácica lancinante irradiada para o dorso com diferença de pressão entre os braços e sopro de insuficiência aórtica: a pergunta é se há dissecção e se ela envolve a ascendente.',
      pergunta: 'Angiotomografia de aorta. Qual é o achado que responde à pergunta clínica?',
      achado: 'Dissecção aguda de aorta Stanford A',
      veredito: 'Dissecção aguda da aorta Stanford A, da raiz às artérias viscerais e renal esquerda',
      correlacao: 'Hipertensão grave, valva bicúspide, cocaína e esforço: a íntima rasgou na aorta ascendente. A dor migrou do tórax ao dorso e ao abdome seguindo o flap; a diferença de pressão e os pulsos reduzidos vêm de ramos comprometidos, e o sopro diastólico é a raiz dilatada. A angiotomografia mostra o flap desde a raiz, o que a classifica como tipo A e cirúrgica.',
      distratores: [
        d('Infarto agudo com supra de ST', 'A dor é constritiva e crescente, sem diferença de pulsos, e o eletrocardiograma define. A dissecção pode ocluir a coronária direita, mas o achado primário aqui é o flap na aorta.'),
        d('Dissecção de aorta tipo B', 'Começa depois da subclávia esquerda, poupando a ascendente, e é tratada clinicamente na forma não complicada. Neste paciente o flap está na raiz, com insuficiência aórtica.'),
        d('Hematoma intramural da aorta', 'Espessa a parede em crescente sem flap nem luz falsa com fluxo. Aqui há duas luzes com contraste separadas por uma íntima ondulada.'),
      ],
    },
  },

  'aneurisma-de-aorta-toracica': {
    titulo: 'Aneurisma da aorta torácica descendente',
    resumo: 'Aneurisma tortuoso da aorta descendente com trombo mural excêntrico, suspeitado na radiografia pelo sinal da sobreposição hilar.',
    protocolo: 'TC de tórax com contraste, janela de mediastino',
    rotulos: {
      'thoracic aortic aneurysm': ['Aneurisma da aorta torácica', 'Dilatação da aorta descendente muito acima do calibre normal.'],
      'eccentric luminal thrombus': ['Trombo mural excêntrico', 'Trombo em crescente ocupando parte da parede, com a luz contrastada deslocada.'],
    },
    achados: [
      'Aorta torácica descendente tortuosa e aneurismática.',
      'Trombo mural excêntrico com luz residual contrastada.',
      'Sem sinais de ruptura, como hematoma periaórtico ou derrame pleural hemorrágico.',
      'Na radiografia, os vasos hilares eram vistos através da massa: sinal da sobreposição hilar, que a localiza fora do hilo.',
    ],
    armadilhas: [
      'O sinal da sobreposição hilar ensina que a massa está à frente ou atrás do hilo, e não nele.',
      'Crescente hiperdenso dentro do trombo na TC sem contraste é sinal de ruptura iminente.',
      'Medir perpendicularmente ao eixo do vaso evita superestimar aneurismas tortuosos.',
    ],
    conduta: 'Controle pressórico, cessação do tabagismo e seguimento seriado. Reparo endovascular ou aberto quando o diâmetro ultrapassa cerca de 5,5 a 6 cm, cresce rápido ou há sintomas.',
    vinheta: {
      cenario: 'Ambulatório de clínica médica',
      identificacao: 'Homem de 74 anos, agricultor aposentado.',
      queixa: 'Rouquidão e dor surda nas costas há três meses.',
      historia: 'A voz foi ficando rouca aos poucos, sem gripe, e há dois meses sente uma dor surda e constante entre as escápulas que não melhora com repouso. Nega febre. Uma radiografia pedida pelo posto mostrou um alargamento do mediastino, e ele foi encaminhado.',
      antecedentes: [
        'Pessoais: hipertensão e doença arterial coronariana com angioplastia',
        'Pessoais: DPOC moderada',
        'Familiares: irmão operado de aneurisma de aorta abdominal',
        'Hábitos: tabagista de 60 maços-ano, parou há um ano',
      ],
      vitais: { pa: '162 × 84 mmHg', fc: '76 bpm', fr: '16 irpm', satO2: '94% em ar ambiente', temp: '36,3 °C' },
      exame: [
        'Rouquidão com paralisia da prega vocal esquerda à laringoscopia',
        'Pulsos periféricos simétricos',
        'Sem sopros abdominais',
        'Murmúrio vesicular reduzido difusamente',
      ],
      pedido: 'Mediastino alargado na radiografia com rouquidão e dor dorsal em tabagista vasculopata: a pergunta é a natureza da massa mediastinal posterior.',
      pergunta: 'TC de tórax com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Aneurisma da aorta descendente',
      veredito: 'Aneurisma tortuoso da aorta torácica descendente com trombo mural excêntrico',
      correlacao: 'O nervo laríngeo recorrente esquerdo contorna o arco aórtico; uma aorta dilatada o estira e paralisa a prega vocal esquerda. A dor dorsal surda é a parede aneurismática. O tabagismo, a aterosclerose e o irmão com aneurisma completam o perfil. A TC mostra a aorta descendente dilatada, tortuosa e com trombo em crescente.',
      distratores: [
        d('Linfonodomegalia hilar por carcinoma', 'Também causa rouquidão pela invasão do recorrente, mas a massa estaria no hilo, apagando os vasos. A radiografia mostrava os vasos hilares através da massa e a TC mostra que ela é a própria aorta.'),
        d('Dissecção crônica da aorta descendente', 'Mostraria flap intimal separando duas luzes com contraste, em paciente com dor torácica prévia. Aqui existe uma luz só, com trombo mural aderido e excêntrico.'),
        d('Schwannoma do mediastino posterior', 'É massa paravertebral de partes moles que alarga forames, sem realce igual ao do sangue. A lesão deste paciente tem luz contrastada contínua com a aorta.'),
      ],
    },
  },

  'enfisema-centrolobular': {
    titulo: 'Enfisema centrolobular e destrutivo',
    resumo: 'Pulmões hiperinsuflados com lucências centrolobulares sem parede e áreas de destruição avançada do parênquima.',
    protocolo: 'TC de tórax sem contraste, janela de pulmão',
    rotulos: {
      centrilobular: ['Enfisema centrolobular', 'Lucências arredondadas sem parede no centro do lóbulo, com a artéria centrolobular visível como um ponto.'],
      'destructive emphysema': ['Enfisema destrutivo', 'Áreas extensas sem arquitetura pulmonar, com vasos rarefeitos.'],
    },
    achados: [
      'Pulmões de grande volume com retificação diafragmática.',
      'Lucências centrolobulares sem parede, predominando nos lobos superiores.',
      'Áreas confluentes de destruição do parênquima com rarefação vascular.',
      'Sem consolidações nem nódulos suspeitos nos cortes analisados.',
    ],
    armadilhas: [
      'Centrolobular predomina nos lobos superiores e se associa ao tabagismo; panlobular predomina nas bases e sugere deficiência de alfa-1 antitripsina.',
      'Cistos têm parede fina; o enfisema não tem parede.',
      'Bolhas grandes podem simular pneumotórax: a linha pleural do pneumotórax é paralela à parede e não há vasos além dela.',
    ],
    conduta: 'Cessação do tabagismo, espirometria, broncodilatadores de longa ação, vacinação e reabilitação. Rastreamento de câncer de pulmão com TC de baixa dose conforme critérios.',
    vinheta: {
      cenario: 'Ambulatório de pneumologia',
      identificacao: 'Homem de 66 anos, ex-metalúrgico.',
      queixa: 'Falta de ar progressiva há cinco anos, agora ao tomar banho.',
      historia: 'A dispneia começou ao subir ladeiras e hoje aparece ao se vestir e ao tomar banho. Tem tosse com pouca secreção pela manhã e duas internações por crise no último ano. Emagreceu nos últimos anos e se cansa ao comer.',
      antecedentes: [
        'Pessoais: DPOC diagnosticada há seis anos, uso irregular de inaladores',
        'Pessoais: hipertensão controlada',
        'Familiares: pai com enfisema, sem deficiência de alfa-1 antitripsina conhecida',
        'Hábitos: tabagista de 70 maços-ano, ainda fuma dez cigarros por dia',
      ],
      vitais: { pa: '132 × 78 mmHg', fc: '92 bpm', fr: '24 irpm', satO2: '89% em ar ambiente', temp: '36,4 °C' },
      exame: [
        'Tórax em tonel com uso de musculatura acessória',
        'Expiração prolongada com lábios semicerrados',
        'Murmúrio vesicular muito reduzido e hipersonoridade à percussão',
        'Sinal de Hoover presente',
      ],
      pedido: 'Dispneia progressiva em grande tabagista com hiperinsuflação ao exame: a pergunta é o padrão e a distribuição da doença pulmonar.',
      pergunta: 'TC de tórax em janela de pulmão. Qual é o achado que responde à pergunta clínica?',
      achado: 'Enfisema centrolobular avançado',
      veredito: 'Enfisema centrolobular com áreas de destruição avançada e hiperinsuflação',
      correlacao: 'A fumaça inalada destrói primeiro o centro do lóbulo, em torno do bronquíolo respiratório, e com mais intensidade nos lobos superiores. A perda do recolhimento elástico prende o ar: tórax em tonel, hipersonoridade e diafragmas planos. A TC mostra buracos sem parede com a artéria centrolobular no meio e zonas onde a arquitetura sumiu.',
      distratores: [
        d('Enfisema panlobular por alfa-1 antitripsina', 'Destrói o lóbulo inteiro de forma homogênea e predomina nas bases, em pacientes mais jovens. Este paciente é grande tabagista e a destruição predomina nos ápices com padrão centrolobular.'),
        d('Linfangioleiomiomatose pulmonar difusa', 'Forma cistos de parede fina, redondos e difusos, em mulheres jovens. As lucências deste paciente não têm parede e há um ponto vascular no centro.'),
        d('Histiocitose de células de Langerhans', 'Afeta tabagistas jovens com nódulos que cavitam e cistos bizarros nos lobos superiores, poupando os seios costofrênicos. Aqui não há nódulos nem cistos com parede, e o paciente tem 66 anos.'),
      ],
    },
  },

  'bronquiectasias-cisticas': {
    titulo: 'Bronquiectasias varicosas e císticas',
    resumo: 'Brônquios dilatados em colar de pérolas e em cacho de uva, com espessamento parietal e níveis hidroaéreos, predominando nos lobos inferiores e médio.',
    protocolo: 'TC de tórax sem contraste, janela de pulmão',
    rotulos: {
      'signet-ring sign': ['Sinal do anel de sinete', 'Brônquio cortado em corte transversal maior que a artéria que o acompanha.'],
      'string of pearls sign': ['Sinal do colar de pérolas', 'Brônquio com dilatações e estreitamentos alternados: bronquiectasia varicosa.'],
      'bunch of grapes sign': ['Sinal do cacho de uva', 'Aglomerado de brônquios císticos em uma mesma região.'],
      'cystic bronchiectasis': ['Bronquiectasia cística', 'Brônquios saculares, arredondados, que terminam em fundo cego.'],
      'varicose bronchiectasis': ['Bronquiectasia varicosa', 'Brônquio irregular, com calibre variável ao longo do trajeto.'],
      'air–fluid levels': ['Níveis hidroaéreos', 'Secreção retida dentro das bronquiectasias císticas.'],
      'diffuse bronchial wall thicke': ['Espessamento difuso das paredes brônquicas', 'Paredes brônquicas espessas por inflamação crônica.'],
    },
    achados: [
      'Bronquiectasias varicosas e císticas difusas, predominando nos lobos inferiores e médio.',
      'Sinal do anel de sinete, colar de pérolas e cacho de uva.',
      'Níveis hidroaéreos em bronquiectasias císticas.',
      'Espessamento difuso das paredes brônquicas.',
    ],
    armadilhas: [
      'Relação broncoarterial acima de 1, ausência de afilamento e brônquio visível a 1 cm da pleura são os critérios.',
      'Bronquiectasias de lobos superiores sugerem fibrose cística ou tuberculose; centrais sugerem aspergilose broncopulmonar alérgica; inferiores sugerem pós-infecciosas, imunodeficiência ou aspiração.',
      'Durante infecção aguda os brônquios podem parecer dilatados de forma reversível; confirme fora da crise.',
    ],
    conduta: 'Investigar a causa (imunoglobulinas, fibrose cística, discinesia ciliar, micobactérias, aspergilose), fisioterapia respiratória diária, tratamento das exacerbações guiado por cultura e vacinação.',
    vinheta: {
      cenario: 'Ambulatório de pneumologia',
      identificacao: 'Mulher de 41 anos, cabeleireira.',
      queixa: 'Tosse com catarro abundante todos os dias desde a adolescência.',
      historia: 'Tosse com expectoração amarelo-esverdeada diária, mais de meio copo por dia, pior ao acordar e ao deitar de lado. Tem pneumonias de repetição desde a infância e hemoptise leve algumas vezes por ano. Na infância teve coqueluche grave e sarampo com internação.',
      antecedentes: [
        'Pessoais: sinusites crônicas, nega infertilidade ou situs inversus',
        'Gestacionais: duas gestações sem intercorrências',
        'Familiares: sem fibrose cística na família',
        'Hábitos: nunca fumou, exposição a produtos químicos no trabalho',
      ],
      vitais: { pa: '118 × 74 mmHg', fc: '88 bpm', fr: '20 irpm', satO2: '93% em ar ambiente', temp: '36,8 °C' },
      exame: [
        'Baqueteamento digital',
        'Estertores grossos nas bases que mudam após a tosse',
        'Roncos esparsos',
        'Halitose',
      ],
      pedido: 'Broncorreia crônica volumosa com infecções de repetição e baqueteamento após infecções graves na infância: a pergunta é se há dilatação brônquica e qual o padrão.',
      pergunta: 'TC de tórax em janela de pulmão. Qual é o achado que responde à pergunta clínica?',
      achado: 'Bronquiectasias varicosas e císticas',
      veredito: 'Bronquiectasias varicosas e císticas difusas com níveis hidroaéreos e espessamento parietal',
      correlacao: 'Coqueluche e sarampo graves na infância lesaram as paredes brônquicas; o ciclo de infecção, inflamação e dano dilatou os brônquios de forma permanente. O muco retido explica a tosse produtiva volumosa e pior ao mudar de decúbito. A TC mostra brônquios maiores que as artérias, em colar de pérolas e em cachos císticos com secreção.',
      distratores: [
        d('Bronquite crônica tabágica', 'Tosse produtiva em pelo menos três meses por dois anos, em fumantes, com brônquios de calibre normal na TC. Esta paciente nunca fumou e os brônquios estão dilatados.'),
        d('Pneumonia necrosante com cavitações', 'Forma cavidades agudas dentro de uma consolidação, com febre alta e quadro de dias. Aqui a doença é de décadas e as lucências seguem a árvore brônquica.'),
        d('Linfangioleiomiomatose com cistos difusos', 'Os cistos são redondos, de parede fina, sem relação com brônquios e sem secreção, em mulheres com pneumotórax de repetição. Esta paciente tem broncorreia e cistos em cacho ao longo dos brônquios.'),
      ],
    },
  },

  'fibrose-pulmonar-uip': {
    titulo: 'Fibrose pulmonar com padrão de pneumonia intersticial usual',
    resumo: 'Faveolamento micro e macrocístico subpleural e basal com volumes pulmonares reduzidos.',
    protocolo: 'TC de tórax de alta resolução, janela de pulmão',
    rotulos: {
      honeycombing: ['Faveolamento', 'Cistos aéreos agrupados em camadas, de paredes espessas, compartilhando paredes: fibrose terminal.'],
      subpleural: ['Distribuição subpleural', 'A fibrose começa na periferia, colada à pleura.'],
      basal: ['Predomínio basal', 'O gradiente é ápico-basal: as bases são as mais acometidas.'],
    },
    achados: [
      'Redução dos volumes pulmonares.',
      'Reticulação e faveolamento subpleural com predomínio basal.',
      'Bronquiectasias de tração.',
      'Ausência de vidro fosco extenso, nódulos ou aprisionamento aéreo que sugeririam outro diagnóstico.',
    ],
    armadilhas: [
      'Faveolamento subpleural basal é o marco do padrão UIP; sem ele, o padrão é provável ou indeterminado.',
      'Enfisema parasseptal pode imitar faveolamento: os cistos do enfisema ficam em uma única camada e não se acompanham de reticulação.',
      'UIP não é sinônimo de fibrose pulmonar idiopática: descarte colagenoses, exposições e drogas.',
    ],
    conduta: 'Investigar exposições, colagenoses e medicações, discussão multidisciplinar, antifibróticos como nintedanibe ou pirfenidona, oxigênio conforme necessidade e encaminhamento precoce para avaliação de transplante.',
    vinheta: {
      cenario: 'Ambulatório de pneumologia',
      identificacao: 'Homem de 70 anos, marceneiro aposentado.',
      queixa: 'Tosse seca e cansaço aos esforços há dois anos, piorando.',
      historia: 'Há dois anos tem tosse seca persistente e dispneia que evoluiu de subir escadas para caminhar no plano. Nega febre, dor articular, lesões de pele ou fraqueza muscular. Tratou várias vezes como bronquite sem melhora.',
      antecedentes: [
        'Pessoais: refluxo gastroesofágico',
        'Pessoais: sem uso de amiodarona, nitrofurantoína ou metotrexato',
        'Familiares: irmão com doença pulmonar fibrosante',
        'Hábitos: ex-tabagista de 30 maços-ano, exposição a pó de madeira; sem aves em casa',
      ],
      vitais: { pa: '128 × 76 mmHg', fc: '88 bpm', fr: '22 irpm', satO2: '90% em ar ambiente, 82% ao caminhar', temp: '36,5 °C' },
      exame: [
        'Estertores finos em velcro nas bases, bilaterais',
        'Baqueteamento digital',
        'Sem sinais de colagenose ao exame articular e cutâneo',
        'Sem edema periférico',
      ],
      pedido: 'Tosse seca e dispneia progressiva com estertores em velcro e baqueteamento em idoso: a pergunta é o padrão da doença intersticial.',
      pergunta: 'TC de tórax de alta resolução. Qual é o achado que responde à pergunta clínica?',
      achado: 'Padrão de pneumonia intersticial usual',
      veredito: 'Padrão UIP: faveolamento subpleural e basal com reticulação e bronquiectasias de tração',
      correlacao: 'Idoso, ex-tabagista, com refluxo e irmão com fibrose: o perfil da fibrose pulmonar idiopática. Os estertores em velcro são os alvéolos fibrosados abrindo na inspiração, e a dessaturação ao esforço traduz a perda da troca gasosa. A TC mostra o padrão UIP: faveolamento em camadas na periferia das bases, com volumes reduzidos.',
      distratores: [
        d('Pneumonia intersticial não específica', 'Predomina o vidro fosco basal com reticulação fina e poupa a região subpleural imediata, com pouco ou nenhum faveolamento, geralmente associada a colagenose. Aqui o faveolamento subpleural domina.'),
        d('Pneumonite de hipersensibilidade crônica', 'Tem distribuição peribroncovascular e superior, com nódulos centrolobulares e aprisionamento aéreo em mosaico, ligada a aves ou mofo. Este paciente tem gradiente basal sem aprisionamento.'),
        d('Insuficiência cardíaca com edema intersticial', 'Dá estertores basais e linhas septais, mas com vidro fosco, derrames e cardiomegalia, e melhora com diurético. Não formaria cistos em favo de mel.'),
      ],
    },
  },

  'tuberculose-cavitaria': {
    titulo: 'Tuberculose pulmonar cavitária',
    resumo: 'Cavidades de parede espessa no lobo superior esquerdo com consolidação e disseminação broncogênica em árvore em brotamento.',
    protocolo: 'TC de tórax sem contraste, janela de pulmão',
    rotulos: {
      cavities: ['Cavidades', 'Cavidades de parede espessa no segmento anteromedial e na língula.'],
      consolidation: ['Consolidação', 'Parênquima preenchido em torno das cavidades.'],
      'tree in bud nodules': ['Árvore em brotamento', 'Micronódulos centrolobulares ramificados: bronquíolos cheios de material caseoso — disseminação broncogênica.'],
    },
    achados: [
      'Duas cavidades de parede espessa no lobo superior esquerdo com consolidação ao redor.',
      'Nódulos centrolobulares em árvore em brotamento no mesmo pulmão e no contralateral.',
      'Sem derrame pleural significativo.',
      'Cavidade já visível no topograma.',
    ],
    armadilhas: [
      'Árvore em brotamento ao lado de cavidade indica doença ativa e contagiosa.',
      'Tuberculose de reativação prefere os segmentos apicais e posteriores dos lobos superiores e o superior dos inferiores.',
      'Em imunodeprimidos a apresentação pode ser atípica, sem cavidade e com adenopatias.',
    ],
    conduta: 'Isolamento respiratório, baciloscopia, teste rápido molecular e cultura do escarro, teste para HIV e esquema RIPE conforme protocolo, com notificação e investigação de contatos.',
    vinheta: {
      cenario: 'Unidade de pronto atendimento',
      identificacao: 'Homem de 35 anos, pedreiro, morador de região com alta incidência de tuberculose.',
      queixa: 'Tosse com catarro há dois meses e escarro com sangue esta semana.',
      historia: 'Tosse produtiva há dois meses, febre vespertina, suores noturnos que molham o lençol e perda de 9 kg. Nesta semana escarrou sangue vivo em pequena quantidade. O irmão, com quem divide o quarto, tratou tuberculose no ano passado e abandonou o tratamento.',
      antecedentes: [
        'Pessoais: sorologia para HIV nunca realizada',
        'Pessoais: diabetes recém-diagnosticado',
        'Familiares: irmão com tuberculose não tratada',
        'Hábitos: etilismo diário, tabagismo de 15 maços-ano, esteve preso por dois anos',
      ],
      vitais: { pa: '112 × 70 mmHg', fc: '102 bpm', fr: '22 irpm', satO2: '94% em ar ambiente', temp: '38,1 °C' },
      exame: [
        'Emagrecido, com perda de massa muscular',
        'Estertores e sopro anfórico no terço superior do hemitórax esquerdo',
        'Linfonodos cervicais não palpáveis',
        'Sem baqueteamento',
      ],
      pedido: 'Tosse crônica com febre vespertina, sudorese noturna, emagrecimento e hemoptise com contato domiciliar bacilífero: a pergunta é se há doença cavitária ativa.',
      pergunta: 'TC de tórax em janela de pulmão. Qual é o achado que responde à pergunta clínica?',
      achado: 'Tuberculose cavitária ativa',
      veredito: 'Tuberculose pulmonar cavitária no lobo superior esquerdo com disseminação broncogênica',
      correlacao: 'Contato com bacilífero, prisão, etilismo e diabetes: o risco é enorme, e a clínica é clássica de tuberculose pulmonar. A TC mostra cavidades de parede espessa no lobo superior e, o mais importante, árvore em brotamento — o material caseoso escorrendo pelos brônquios, sinal de atividade e de alta transmissibilidade.',
      distratores: [
        d('Carcinoma epidermoide cavitado', 'Forma cavidade única de parede espessa e irregular em tabagistas mais velhos, sem disseminação broncogênica. Este paciente tem febre, sudorese, contato bacilífero e árvore em brotamento.'),
        d('Abscesso pulmonar por aspiração', 'Cavidade única com nível hidroaéreo nos segmentos posteriores ou basais, em etilistas com dentes ruins e escarro pútrido. Aqui há duas cavidades apicais e disseminação em árvore em brotamento.'),
        d('Aspergiloma em cavidade antiga', 'É bola fúngica móvel dentro de cavidade prévia, com sinal do crescente aéreo e pouca febre. As cavidades deste paciente não têm massa interna e há doença ativa ao redor.'),
      ],
    },
  },

  'empiema-pleura-dividida': {
    titulo: 'Empiema pleural com sinal da pleura dividida',
    resumo: 'Coleção pleural lenticular com pleura visceral e parietal espessadas e realçadas, separadas pelo líquido.',
    protocolo: 'TC de tórax com contraste, janela de mediastino',
    rotulos: {
      'pleural fluid accumulation': ['Coleção pleural lenticular', 'Líquido com forma de lente e bordas obtusas, loculado, entre as pleuras realçadas.'],
      atelectasis: ['Atelectasia compressiva', 'Pulmão adjacente colapsado pela coleção.'],
    },
    achados: [
      'Coleção pleural lenticular com bordas obtusas e densidade líquida.',
      'Pleuras visceral e parietal espessadas e realçadas, separadas pelo líquido: sinal da pleura dividida.',
      'Atelectasia compressiva do pulmão adjacente.',
      'Sem gás na coleção.',
    ],
    armadilhas: [
      'Empiema tem forma lenticular e ângulos obtusos com a parede; abscesso pulmonar é redondo, forma ângulo agudo e destrói o parênquima.',
      'O sinal da pleura dividida é sensível mas não exclusivo; o diagnóstico se confirma pela toracocentese.',
      'Derrame parapneumônico com pH abaixo de 7,2, glicose baixa ou pus exige drenagem.',
    ],
    conduta: 'Drenagem torácica, antibiótico com cobertura anaeróbia e, se houver loculação, fibrinolítico intrapleural com DNase ou videotoracoscopia.',
    vinheta: {
      cenario: 'Enfermaria de clínica médica',
      identificacao: 'Homem de 57 anos, porteiro.',
      queixa: 'Febre que não passa depois de uma pneumonia tratada há duas semanas.',
      historia: 'Internou há duas semanas por pneumonia à direita, recebeu antibiótico venoso e teve alta ao ficar afebril. Há cinco dias voltou a ter febre de 38,8 °C, dor torácica à direita que piora na inspiração e falta de ar crescente. Perdeu o apetite.',
      antecedentes: [
        'Pessoais: diabetes tipo 2 e etilismo',
        'Pessoais: dentes em mau estado, episódios de engasgo quando bebe',
        'Familiares: sem doenças pulmonares',
        'Hábitos: tabagista de 25 maços-ano',
      ],
      vitais: { pa: '118 × 72 mmHg', fc: '108 bpm', fr: '26 irpm', satO2: '92% em ar ambiente', temp: '38,7 °C' },
      exame: [
        'Macicez à percussão no terço inferior do hemitórax direito',
        'Murmúrio vesicular abolido na base direita',
        'Frêmito toracovocal abolido na mesma área',
        'Egofonia no limite superior da macicez',
      ],
      pedido: 'Febre recorrente após pneumonia com sinais de derrame à direita: a pergunta é se o derrame complicou e se precisa de drenagem.',
      pergunta: 'TC de tórax com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Empiema com pleura dividida',
      veredito: 'Empiema pleural loculado com sinal da pleura dividida e atelectasia compressiva',
      correlacao: 'A pneumonia de um diabético etilista com risco de aspiração evoluiu para infecção do espaço pleural. A febre voltou porque o pus ficou fora do alcance do antibiótico. A TC mostra a coleção em lente, com ângulos obtusos, envolvida pelas duas pleuras espessadas e realçadas que o líquido afasta — o sinal da pleura dividida.',
      distratores: [
        d('Abscesso pulmonar periférico', 'Tem forma redonda, ângulos agudos com a parede torácica e destrói o parênquima, sem separar as pleuras. Esta coleção é lenticular, com ângulos obtusos, e está entre as pleuras.'),
        d('Derrame parapneumônico não complicado', 'Seria livre, com menisco, sem espessamento nem realce pleural, e melhoraria com antibiótico. Aqui a coleção é loculada e as pleuras estão realçadas.'),
        d('Mesotelioma pleural maligno', 'Espessa a pleura de forma nodular e circunferencial, acima de 1 cm, envolvendo a mediastinal, em expostos ao amianto. Este espessamento é liso e acompanha uma coleção infecciosa aguda.'),
      ],
    },
  },

  piopneumotorax: {
    titulo: 'Piopneumotórax',
    resumo: 'Coleção pleural multiloculada com nível hidroaéreo, espessamento pleural e colapso parcial do pulmão.',
    protocolo: 'TC de tórax sem contraste, janelas de mediastino e pulmão',
    rotulos: {
      'air-fluid level': ['Nível hidroaéreo pleural', 'Interface reta entre ar e líquido dentro do espaço pleural.'],
      multilobed: ['Coleção multiloculada', 'Septos dividem a coleção em lojas.'],
      'partial collapse': ['Colapso parcial do pulmão', 'O parênquima adjacente foi comprimido pela coleção.'],
    },
    achados: [
      'Coleção pleural direita multiloculada com nível hidroaéreo.',
      'Espessamento pleural.',
      'Colapso parcial do parênquima adjacente.',
      'Nível hidroaéreo que se estende ao longo da parede, com comprimento semelhante nas incidências.',
    ],
    armadilhas: [
      'Nível hidroaéreo pleural tem comprimento diferente na radiografia frontal e lateral e encosta na parede; o do abscesso pulmonar tem comprimento igual nas duas.',
      'Ar no espaço pleural sem punção prévia indica fístula broncopleural ou germe produtor de gás.',
      'Em pós-operatório de pneumonectomia, o nível que desce é sinal de fístula.',
    ],
    conduta: 'Drenagem torácica, antibiótico com cobertura anaeróbia, investigação de fístula broncopleural e, se necessário, videotoracoscopia ou decorticação.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Mulher de 48 anos, diarista.',
      queixa: 'Dor forte no lado direito do peito e falta de ar súbita há um dia, após semanas de tosse.',
      historia: 'Há três semanas tem tosse com escarro amarelado e fétido e febre. Ontem, após um acesso de tosse, sentiu dor pontiaguda no lado direito e piora súbita da falta de ar. Hoje está expectorando grande quantidade de secreção purulenta.',
      antecedentes: [
        'Pessoais: epilepsia com crises frequentes, a última há um mês',
        'Gestacionais: cinco gestações, uma perda gestacional',
        'Familiares: sem doenças pulmonares',
        'Hábitos: etilista, dentes em péssimo estado',
      ],
      vitais: { pa: '102 × 64 mmHg', fc: '118 bpm', fr: '30 irpm', satO2: '88% em ar ambiente', temp: '38,9 °C' },
      exame: [
        'Hipersonoridade no terço superior e macicez no terço inferior do hemitórax direito',
        'Murmúrio abolido à direita',
        'Sucussão hipocrática audível ao balançar o tórax',
        'Halitose e dentes com cáries extensas',
      ],
      pedido: 'Pneumonia aspirativa com piora súbita, hipersonoridade superior, macicez inferior e sucussão: a pergunta é o que ocupa o espaço pleural.',
      pergunta: 'TC de tórax. Qual é o achado que responde à pergunta clínica?',
      achado: 'Piopneumotórax multiloculado',
      veredito: 'Piopneumotórax direito multiloculado com nível hidroaéreo e colapso parcial',
      correlacao: 'Aspiração durante crises, etilismo e dentes ruins criaram uma pneumonia por anaeróbios que necrosou e rompeu para a pleura: o acesso de tosse com dor súbita marca a fístula. Ar em cima e pus embaixo explicam a hipersonoridade superior, a macicez inferior e a sucussão. A TC mostra o nível hidroaéreo pleural, as lojas e o pulmão comprimido.',
      distratores: [
        d('Abscesso pulmonar com nível hidroaéreo', 'O nível fica dentro de uma cavidade arredondada no parênquima, com ângulos agudos com a parede. Aqui o nível está no espaço pleural e o pulmão foi empurrado.'),
        d('Hidropneumotórax pós-toracocentese', 'Ar e líquido entram após uma punção, sem infecção e sem septos. Esta paciente não foi puncionada e a coleção é purulenta e loculada.'),
        d('Hérnia diafragmática com alça intestinal', 'Levaria estômago ou cólon com nível para o tórax, geralmente à esquerda e após trauma, com haustrações ou pregas. Esta coleção é pleural direita com espessamento infeccioso.'),
      ],
    },
  },

  'cancer-de-pulmao-espiculado': {
    titulo: 'Câncer de pulmão espiculado com implantes pleurais',
    resumo: 'Massa espiculada no segmento posterior do lobo superior direito em pulmão enfisematoso, com nódulo associado e depósitos pleurais.',
    protocolo: 'TC de baixa dose do PET-CT, sem contraste',
    rotulos: {
      'Spiculated mass': ['Massa espiculada', 'Lesão de contornos em raios, que tracionam o parênquima: comportamento infiltrativo.'],
      nodule: ['Nódulo associado', 'Nódulo adicional que pede estadiamento: satélite ou metástase.'],
      emphysema: ['Enfisema', 'Pulmão de fundo enfisematoso, pista do tabagismo.'],
      'high attenuation': ['Implante pleural', 'Foco pleural que, no PET, captava glicose marcada: depósito neoplásico.'],
    },
    achados: [
      'Massa espiculada no segmento posterior do lobo superior direito.',
      'Nódulo pulmonar adicional.',
      'Espessamentos e depósitos pleurais, hipermetabólicos no PET.',
      'Enfisema centrolobular de fundo.',
    ],
    armadilhas: [
      'Espículas, retração pleural e broncograma dentro do nódulo aumentam a probabilidade de malignidade.',
      'Implante pleural muda o estadiamento para M1a e retira a possibilidade de cirurgia curativa.',
      'Consolidação redonda infecciosa pode ter contorno irregular; o seguimento curto ajuda.',
    ],
    conduta: 'Estadiamento com PET-CT e ressonância de crânio, biópsia da lesão mais acessível que estadie mais alto, pesquisa de mutações e PD-L1 e tratamento sistêmico conforme o estádio.',
    vinheta: {
      cenario: 'Ambulatório de oncologia torácica',
      identificacao: 'Mulher de 67 anos, costureira aposentada.',
      queixa: 'Tosse persistente e dor no ombro direito há quatro meses.',
      historia: 'A tosse mudou de característica, ficou diária e seca. Há dois meses sente dor no dorso e no ombro direito, pior à noite, e percebeu escarro com raias de sangue duas vezes. Perdeu 7 kg sem dieta. Um raio-X mostrou uma opacidade no ápice direito.',
      antecedentes: [
        'Pessoais: DPOC com enfisema',
        'Gestacionais: duas gestações, menopausa aos 50 anos',
        'Familiares: irmã com câncer de mama',
        'Hábitos: tabagista de 50 maços-ano, ativa; marido fumante',
      ],
      vitais: { pa: '134 × 80 mmHg', fc: '86 bpm', fr: '20 irpm', satO2: '93% em ar ambiente', temp: '36,6 °C' },
      exame: [
        'Emagrecida',
        'Murmúrio reduzido no ápice direito',
        'Sem linfonodos supraclaviculares palpáveis',
        'Baqueteamento digital',
      ],
      pedido: 'Opacidade apical em grande tabagista com hemoptise, dor e emagrecimento: a pergunta é o aspecto da lesão e se há doença além dela.',
      pergunta: 'TC do PET-CT. Qual é o achado que responde à pergunta clínica?',
      achado: 'Carcinoma pulmonar espiculado com implantes',
      veredito: 'Massa espiculada no lobo superior direito com nódulo associado e implantes pleurais hipermetabólicos',
      correlacao: 'Tabagismo intenso, emagrecimento, hemoptise e baqueteamento em mulher de 67 anos: a massa apical é neoplasia até prova em contrário. As espículas traduzem infiltração do parênquima; o nódulo associado e os depósitos pleurais, captantes no PET, mostram doença disseminada, o que muda o tratamento de cirúrgico para sistêmico.',
      distratores: [
        d('Tuberculose apical com fibrose', 'Prefere os ápices e causa hemoptise, mas com cavidades, árvore em brotamento ou estrias fibróticas e calcificações, sem massa espiculada sólida. Os implantes pleurais hipercaptantes não cabem.'),
        d('Hamartoma pulmonar calcificado', 'É nódulo bem delimitado, liso, com gordura e calcificação em pipoca, estável por anos. Esta lesão é espiculada e acompanhada de implantes.'),
        d('Pneumonia redonda do lobo superior', 'Consolidação arredondada aguda com febre e broncograma, que regride com antibiótico. Esta paciente não tem febre e a evolução é de meses com emagrecimento.'),
      ],
    },
  },

  'trauma-toracico-contuso': {
    titulo: 'Trauma torácico contuso em evolução',
    resumo: 'TC de controle após trauma: contusões pulmonares em regressão, laceração com pneumatocele, pneumotórax e enfisema subcutâneo à direita.',
    protocolo: 'TC de tórax de controle, janela de pulmão',
    rotulos: {
      'receding pulmonary contusions': ['Contusões pulmonares em regressão', 'Opacidades em vidro fosco e consolidação que diminuem em dias: sangue alveolar sendo absorvido.'],
      'pulmonary laceration': ['Laceração pulmonar', 'Cavidade de ar ou ar e sangue dentro do parênquima rompido.'],
      pneumothorax: ['Pneumotórax', 'Ar entre a pleura e o pulmão, sem desvio do mediastino.'],
      'subcutaneous emphysema': ['Enfisema subcutâneo', 'Ar dissecando as partes moles da parede torácica.'],
    },
    achados: [
      'Pneumotórax direito sem desvio do mediastino.',
      'Contusões pulmonares com atenuação menor que no exame inicial.',
      'Lacerações pulmonares estáveis, com aspecto de pneumatocele.',
      'Pequeno derrame pleural direito e enfisema subcutâneo.',
    ],
    armadilhas: [
      'Contusão aparece em horas e regride em dias; opacidade que piora após 72 horas sugere pneumonia ou síndrome do desconforto respiratório.',
      'Laceração forma cavidade que pode confundir com abscesso; o contexto de trauma e a evolução decidem.',
      'Pneumotórax oculto na radiografia em supino é comum; a TC mostra o ar anterior.',
    ],
    conduta: 'Analgesia eficaz, fisioterapia respiratória, drenagem se o pneumotórax for significativo ou houver ventilação com pressão positiva, e vigilância de infecção.',
    vinheta: {
      cenario: 'Unidade de terapia intensiva de trauma',
      identificacao: 'Homem de 32 anos, motociclista, terceiro dia de internação.',
      queixa: 'Dor ao respirar e piora da falta de ar ao sentar.',
      historia: 'Colidiu de moto contra um carro há três dias, com impacto do tórax direito no guidão. Fraturou três costelas à direita. A radiografia inicial mostrou opacidades pulmonares à direita. Hoje refere piora da dor e sensação de crepitação sob a pele do tórax.',
      antecedentes: [
        'Pessoais: previamente hígido',
        'Pessoais: sem doenças pulmonares',
        'Familiares: sem doenças relevantes',
        'Hábitos: tabagista social',
      ],
      vitais: { pa: '128 × 78 mmHg', fc: '98 bpm', fr: '24 irpm', satO2: '93% com cateter nasal', temp: '37,4 °C' },
      exame: [
        'Crepitação subcutânea na parede torácica direita',
        'Murmúrio reduzido no ápice direito',
        'Dor à palpação dos arcos costais direitos',
        'Traqueia centrada',
      ],
      pedido: 'Trauma torácico contuso em evolução com crepitação subcutânea e murmúrio reduzido: a pergunta é o que evoluiu desde a admissão.',
      pergunta: 'TC de tórax de controle. Qual é o conjunto de achados que responde à pergunta clínica?',
      achado: 'Pneumotórax com contusões em regressão',
      veredito: 'Pneumotórax direito com contusões em regressão, lacerações pulmonares e enfisema subcutâneo',
      correlacao: 'O impacto no guidão contundiu e lacerou o pulmão direito e quebrou costelas. Em três dias o sangue alveolar das contusões começou a ser absorvido, mas o ar de uma laceração ou de fratura costal passou para a pleura e para o subcutâneo: daí a crepitação e o murmúrio reduzido no ápice, com traqueia centrada.',
      distratores: [
        d('Pneumonia aspirativa do lobo inferior', 'Seria consolidação nova e crescente em segmento pendente, com febre e secreção. As opacidades deste paciente estão diminuindo e o achado novo é ar.'),
        d('Pneumotórax hipertensivo com desvio mediastinal', 'Daria hipotensão, desvio da traqueia e desvio do mediastino. Este paciente está estável, com traqueia centrada e sem desvio na TC.'),
        d('Síndrome do desconforto respiratório agudo', 'Causa opacidades bilaterais crescentes com hipoxemia grave após o terceiro dia. Aqui as opacidades são unilaterais e em regressão.'),
      ],
    },
  },

  'pericardite-purulenta': {
    titulo: 'Pericardite purulenta',
    resumo: 'Derrame pericárdico volumoso com realce do pericárdio e derrames pleurais bilaterais.',
    protocolo: 'TC de tórax com contraste, janela de mediastino',
    rotulos: {
      'Rim-enhancing effusion': ['Derrame pericárdico com realce periférico', 'Líquido pericárdico volumoso envolvido por pericárdio espessado que capta contraste.'],
    },
    achados: [
      'Derrame pericárdico volumoso.',
      'Espessamento e realce do pericárdio.',
      'Sem gás nem septações pericárdicas.',
      'Derrames pleurais bilaterais.',
    ],
    armadilhas: [
      'Realce do pericárdio sugere inflamação ou infecção, mas não diferencia purulento de outras causas: quem decide é a pericardiocentese.',
      'A TC não é o exame para tamponamento; ecocardiograma avalia colapso de câmaras.',
      'Gás no pericárdio sem procedimento prévio indica fístula ou germe produtor de gás.',
    ],
    conduta: 'Drenagem pericárdica urgente, culturas e antibiótico venoso de amplo espectro; considerar pericardiectomia se houver loculação ou constrição.',
    vinheta: {
      cenario: 'Unidade de terapia intensiva',
      identificacao: 'Homem de 59 anos, caminhoneiro.',
      queixa: 'Febre alta, falta de ar e dor no peito há cinco dias.',
      historia: 'Há duas semanas teve pneumonia à esquerda tratada em casa com antibiótico oral. Há cinco dias voltou a ter febre alta, dor retroesternal que melhora ao inclinar o tronco para a frente e falta de ar progressiva. Hoje ficou tonto ao levantar.',
      antecedentes: [
        'Pessoais: diabetes tipo 2 e doença renal crônica estágio 3',
        'Pessoais: sem cirurgia cardíaca prévia',
        'Familiares: sem doenças cardíacas precoces',
        'Hábitos: etilismo moderado, ex-tabagista',
      ],
      vitais: { pa: '92 × 70 mmHg, queda de 14 mmHg na inspiração', fc: '128 bpm', fr: '28 irpm', satO2: '92% em ar ambiente', temp: '39,3 °C' },
      exame: [
        'Turgência jugular com sinal de Kussmaul',
        'Bulhas cardíacas abafadas',
        'Atrito pericárdico fugaz',
        'Macicez nas bases pulmonares',
      ],
      pedido: 'Sepse após pneumonia com dor pleuropericárdica, bulhas abafadas, pulso paradoxal e turgência jugular: a pergunta é o que envolve o coração.',
      pergunta: 'TC de tórax com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Derrame pericárdico com realce',
      veredito: 'Derrame pericárdico volumoso com espessamento e realce do pericárdio compatível com pericardite purulenta',
      correlacao: 'A pneumonia mal tratada num diabético nefropata contaminou o pericárdio por contiguidade. A dor que melhora ao inclinar o tronco é pericárdica; bulhas abafadas, pulso paradoxal e turgência jugular indicam que o líquido já compromete o enchimento. A TC mostra o derrame volumoso cercado por pericárdio espessado que realça.',
      distratores: [
        d('Pericardite viral com derrame pequeno', 'Tem dor pericárdica e atrito, mas o derrame é pequeno, o pericárdio realça pouco e não há sepse nem tamponamento. Este derrame é volumoso e o paciente está séptico e hipotenso.'),
        d('Insuficiência cardíaca com derrames', 'Causa derrames pleurais e pericárdico pequeno com cardiomegalia e congestão, sem febre alta nem realce pericárdico. Aqui o pericárdio está espessado e realçado em quadro infeccioso.'),
        d('Derrame pericárdico urêmico', 'Aparece na doença renal avançada com ureia muito alta, geralmente sem febre séptica. Este paciente tem nefropatia moderada e o quadro seguiu uma pneumonia.'),
      ],
    },
  },

  'fibrose-cistica': {
    titulo: 'Fibrose cística',
    resumo: 'Bronquiectasias difusas com padrão de árvore em brotamento e substituição gordurosa do pâncreas.',
    protocolo: 'TC de tórax e abdome superior, janelas de pulmão e partes moles',
    rotulos: {
      bronchiectases: ['Bronquiectasias', 'Brônquios dilatados e espessados, com predomínio nos lobos superiores.'],
      'tree-in-bud': ['Árvore em brotamento', 'Bronquíolos preenchidos por muco infectado.'],
    },
    achados: [
      'Bronquiectasias difusas, predominando nos lobos superiores.',
      'Nódulos centrolobulares em árvore em brotamento e tampões mucosos.',
      'Espessamento das paredes brônquicas.',
      'Substituição gordurosa do pâncreas nos cortes do abdome superior.',
    ],
    armadilhas: [
      'Bronquiectasias de lobos superiores em jovem: pense em fibrose cística antes de tuberculose.',
      'Pâncreas substituído por gordura explica a insuficiência exócrina e a esteatorreia.',
      'O diagnóstico se confirma pelo teste do suor e pela genética, não pela imagem.',
    ],
    conduta: 'Acompanhamento em centro de referência: fisioterapia respiratória, mucolíticos, antibióticos inalatórios, moduladores do CFTR conforme mutação, enzimas pancreáticas e suporte nutricional.',
    vinheta: {
      cenario: 'Ambulatório de pneumologia pediátrica de transição',
      identificacao: 'Mulher de 19 anos, estudante universitária.',
      queixa: 'Tosse com catarro espesso e cansaço há anos, piorando no último ano.',
      historia: 'Desde criança tem tosse produtiva, pneumonias de repetição e baixo ganho de peso. Evacua fezes volumosas, gordurosas e malcheirosas várias vezes ao dia. Nunca teve diagnóstico definido. A mãe conta que a pele dela era salgada ao beijar quando bebê. No último ano, as culturas de escarro cresceram Pseudomonas.',
      antecedentes: [
        'Pessoais: pólipos nasais operados aos 14 anos',
        'Gestacionais: íleo meconial ao nascer, operado no período neonatal',
        'Familiares: pais primos em segundo grau; irmão falecido aos 6 anos por pneumonia',
        'Hábitos: nunca fumou',
      ],
      vitais: { pa: '104 × 66 mmHg', fc: '96 bpm', fr: '22 irpm', satO2: '92% em ar ambiente', temp: '36,9 °C' },
      exame: [
        'IMC de 16,8 kg/m²',
        'Baqueteamento digital',
        'Estertores grossos difusos, predominando nos ápices',
        'Pólipos nasais recidivados',
      ],
      pedido: 'Doença supurativa crônica desde a infância com má absorção, íleo meconial e consanguinidade: a pergunta é o padrão pulmonar e se há pista pancreática.',
      pergunta: 'TC de tórax e abdome superior. Qual é o conjunto de achados que responde à pergunta clínica?',
      achado: 'Bronquiectasias com lipossubstituição pancreática',
      veredito: 'Fibrose cística: bronquiectasias difusas com árvore em brotamento e substituição gordurosa do pâncreas',
      correlacao: 'Pais consanguíneos, irmão morto por pneumonia, íleo meconial, pele salgada, pólipos e esteatorreia: herança autossômica recessiva do CFTR. O muco espesso obstrui brônquios e ductos pancreáticos. A TC mostra as duas faces da mesma doença: bronquiectasias com árvore em brotamento nos pulmões e o pâncreas trocado por gordura.',
      distratores: [
        d('Discinesia ciliar primária com situs', 'Dá bronquiectasias, sinusite e otites desde a infância, predominando no lobo médio e nas bases, às vezes com situs inversus, mas sem insuficiência pancreática nem íleo meconial.'),
        d('Imunodeficiência comum variável', 'Causa infecções de repetição e bronquiectasias basais em adultos jovens com imunoglobulinas baixas, sem pólipos nasais precoces, esteatorreia ou íleo meconial.'),
        d('Aspergilose broncopulmonar alérgica isolada', 'Forma bronquiectasias centrais com muco hiperdenso em asmáticos, com eosinofilia e IgE alta. Esta paciente não é asmática e tem doença pancreática.'),
      ],
    },
  },
}
