import { d, p, r, type ConteudoCaso } from './casos-imagem-tipos'

/** Raio-X com apontamentos — pediatria. Pacientes fictícios. */
export const CASOS_RX_PEDIATRICO: Record<string, ConteudoCaso> = {
  'doenca-de-hirschsprung': {
    tema: 'Abdome do lactente',
    titulo: 'Doença de Hirschsprung com cólon sigmoide dilatado',
    resumo: 'Cólon sigmoide muito dilatado e sem haustrações, com índice retossigmoide menor que 1 no enema contrastado.',
    protocolo: 'Radiografia de abdome e enema opaco',
    series: ['Radiografia simples', 'Enema opaco'],
    rotulos: {
      'loss of haustration': r('Perda das haustrações', 'Cólon distendido com a parede lisa, sem as pregas habituais.',
        'As haustrações são as saculações normais do cólon. Quando ele fica muito distendido por muito tempo, a parede se estica e elas desaparecem. Na doença de Hirschsprung, o cólon acima do segmento doente se dilata cada vez mais porque as fezes não conseguem passar.'),
      dilated: r('Cólon sigmoide dilatado no enema', 'O sigmoide maior que o reto, com zona de transição.',
        'Na doença de Hirschsprung, faltam as células nervosas, os gânglios, na parede do reto e de um trecho variável do cólon. Sem elas, o segmento fica contraído e não deixa as fezes passarem. No enema, o reto doente fica estreito e o cólon normal acima dele se dilata. O reto deveria ser a parte mais larga: quando o índice retossigmoide é menor que 1, o padrão é sugestivo.',
        'A biópsia retal por sucção sem células ganglionares confirma o diagnóstico.'),
    },
    apontamentosProprios: [
      p(1, 0.55, 0.76, 0, 'Reto de calibre menor', 'O reto contrastado é mais estreito que o sigmoide acima dele.',
        'Normalmente o reto é a parte mais larga do intestino grosso no enema. Na doença de Hirschsprung, o reto sem gânglios fica contraído e estreito, enquanto o sigmoide normal acima dele se dilata para vencer a obstrução. Comparar os dois calibres é o modo de calcular o índice retossigmoide.',
        'Índice retossigmoide menor que 1: reto mais estreito que o sigmoide.'),
      p(1, 0.50, 0.90, 0, 'Sonda retal do enema', 'Sonda por onde entra o contraste, sem balão insuflado.',
        'Na suspeita de Hirschsprung, o enema é feito sem insuflar o balão da sonda e sem preparo intestinal, porque o balão distende o reto e o preparo esvazia o cólon, e os dois apagam a diferença de calibre que define a zona de transição.'),
    ],
    achados: [
      'Cólon sigmoide muito dilatado e sem haustrações.',
      'Índice retossigmoide menor que 1 no enema, com reto relativamente estreito.',
      'Zona de transição entre o reto estreito e o sigmoide dilatado.',
    ],
    armadilhas: [
      'Não faça preparo intestinal antes do enema: ele apaga a zona de transição.',
      'Enterocolite de Hirschsprung é a complicação mais grave e pode ser fatal.',
      'Na doença de segmento ultracurto, o enema pode ser quase normal.',
    ],
    conduta: 'Biópsia retal por sucção, irrigações retais para descomprimir e cirurgia de abaixamento do cólon com ressecção do segmento sem gânglios.',
    vinheta: {
      cenario: 'Ambulatório de cirurgia pediátrica',
      identificacao: 'Menina de 2 anos.',
      queixa: 'Prisão de ventre desde o nascimento e barriga muito grande.',
      historia: 'Eliminou o mecônio só no terceiro dia de vida. Desde então evacua a cada cinco a sete dias, apenas com supositório. A barriga é muito distendida e ela come pouco. Teve um episódio de diarreia com febre e vômitos aos 8 meses, com internação.',
      antecedentes: [
        'Pessoais: atraso na eliminação de mecônio',
        'Pessoais: baixo ganho de peso',
        'Familiares: primo com cirurgia intestinal na infância',
        'Hábitos: dieta rica em fibras sem melhora',
      ],
      vitais: { pa: '90 × 56 mmHg', fc: '112 bpm', fr: '26 irpm', satO2: '99% em ar ambiente', temp: '36,7 °C' },
      exame: [
        'Abdome muito distendido e timpânico',
        'Ampola retal vazia ao toque',
        'Saída explosiva de fezes e gases após o toque',
        'Peso abaixo do percentil 3',
      ],
      pedido: 'Constipação desde o nascimento, mecônio atrasado e reto vazio com saída explosiva ao toque: a pergunta é o padrão do cólon.',
      pergunta: 'Radiografia e enema opaco. Qual é o achado que responde à pergunta clínica?',
      achado: 'Aganglionose do reto e do sigmoide',
      veredito: 'Doença de Hirschsprung com cólon sigmoide dilatado e índice retossigmoide invertido',
      correlacao: 'As células nervosas não migraram até o reto durante a gestação, e o segmento sem gânglios ficou contraído. Por isso o mecônio atrasou e as fezes se acumulam no sigmoide, que dilata. O reto estreito fica vazio, e o toque desfaz por um momento a obstrução, com a saída explosiva. A internação aos 8 meses foi provavelmente uma enterocolite.',
      distratores: [
        d('Constipação funcional da infância', 'Começa depois do desfralde, com reto cheio de fezes ao toque e escapes fecais, sem atraso do mecônio nem reto estreito no enema.'),
        d('Íleo meconial por fibrose cística', 'Obstrui o íleo do recém-nascido com mecônio espesso e microcólon no enema, e não um sigmoide dilatado aos 2 anos. Apareceria logo ao nascer.'),
        d('Hipotireoidismo congênito com constipação', 'Deixa o intestino lento, mas com icterícia prolongada, hipotonia e macroglossia, e o teste do pezinho alterado. O enema seria normal.'),
      ],
    },
  },

  'atresia-de-esofago-vacterl': {
    tema: 'Abdome do lactente',
    titulo: 'Atresia de esôfago na associação VACTERL',
    resumo: 'Sonda enrolada no coto esofágico superior, ausência de gás no abdome e hemivértebras múltiplas; após a correção, continuidade restabelecida com pequeno vazamento na anastomose.',
    protocolo: 'Radiografias toracoabdominais e estudos contrastados seriados',
    series: ['Ao nascer', 'Após a correção', 'Contraste pela sonda'],
    rotulos: {
      'multiple hemivertebrae': r('Hemivértebras múltiplas', 'Vértebras formadas pela metade, causando escoliose.',
        'A hemivértebra é uma vértebra em que só um lado se formou, em forma de cunha. Várias delas entortam a coluna. Anomalias vertebrais são o V da associação VACTERL, que reúne defeitos vertebrais, anorretais, cardíacos, traqueoesofágicos, renais e dos membros. Achar um componente obriga a procurar os outros.'),
      'absence of distal bowel gas': r('Ausência de gás no abdome', 'Abdome sem gás nas alças.',
        'O ar só chega ao estômago pela traqueia se houver uma fístula entre a traqueia e o esôfago distal. Abdome sem gás com atresia de esôfago indica atresia pura, sem fístula distal, o que significa que os cotos costumam estar distantes e a correção é mais difícil.',
        'Atresia com gás no abdome indica fístula distal, a forma mais comum.'),
      'nasogastric tube coiled': r('Sonda enrolada no coto superior', 'A sonda para no meio do tórax e se dobra.',
        'O sinal mais simples da atresia de esôfago é a sonda que não desce até o estômago e se enrola no coto esofágico superior, que termina em fundo cego. O recém-nascido tem salivação excessiva e engasga na primeira mamada. Toda criança com polidrâmnio na gestação deve ter a passagem da sonda testada.'),
      'Restored esophageal continuity': r('Continuidade esofágica restabelecida', 'Contraste passando do esôfago ao estômago após a cirurgia.',
        'Depois da anastomose entre os dois cotos, o contraste deve passar livremente até o estômago. O exame também procura estreitamento da anastomose, que é a complicação tardia mais comum e causa dificuldade para engolir.'),
      'small focal contrast leak': r('Pequeno vazamento na anastomose', 'Contraste saindo do esôfago no ponto da sutura.',
        'O vazamento da anastomose acontece porque os cotos ficam sob tensão. Vazamentos pequenos e contidos costumam fechar com jejum, drenagem e antibiótico. Vazamentos grandes podem causar mediastinite e exigir nova cirurgia.'),
      'blind esophageal pouch': r('Coto esofágico cego', 'O contraste enche o coto superior, que termina em fundo cego.',
        'O contraste hidrossolúvel injetado pela sonda mostra o coto superior dilatado terminando em fundo cego. O exame confirma a atresia e mede o comprimento do coto, mas deve usar pouco contraste, porque ele pode ser aspirado para os pulmões.'),
    },
    achados: [
      'Sonda nasogástrica enrolada no esôfago torácico médio, sem progredir ao estômago; coto esofágico superior cego no estudo contrastado.',
      'Distensão abdominal sem gás distal nas alças.',
      'Hemivértebras múltiplas com escoliose toracolombar.',
      'Após a correção: continuidade esofágica com passagem de contraste ao estômago e pequeno vazamento na anastomose.',
    ],
    armadilhas: [
      'Use pouco contraste hidrossolúvel no coto superior pelo risco de aspiração.',
      'Procure cardiopatia com ecocardiograma antes da cirurgia: muda o lado do acesso.',
      'Fístula em H, sem atresia, aparece mais tarde com tosse às mamadas.',
    ],
    conduta: 'Sonda de aspiração contínua no coto, cabeceira elevada, rastreio dos componentes VACTERL com ecocardiograma, ultrassom renal e exame anorretal, e correção cirúrgica, por etapas se a distância entre os cotos for longa.',
    vinheta: {
      cenario: 'Unidade neonatal',
      identificacao: 'Recém-nascido do sexo masculino, 6 horas de vida.',
      queixa: 'Muita saliva espumosa e engasgo na primeira mamada.',
      historia: 'Nasceu de parto cesáreo a termo. A gestação teve excesso de líquido amniótico. Desde o nascimento baba muito, com saliva espumosa saindo pela boca e pelo nariz. Na primeira mamada tossiu, engasgou e ficou roxo. A sonda gástrica não passou.',
      antecedentes: [
        'Pessoais: polidrâmnio na gestação',
        'Pessoais: peso de nascimento de 2.600 g',
        'Familiares: sem malformações conhecidas',
        'Gestacionais: pré-natal com seis consultas',
      ],
      vitais: { pa: '62 × 38 mmHg', fc: '152 bpm', fr: '58 irpm', satO2: '92% em ar ambiente', temp: '36,6 °C' },
      exame: [
        'Sialorreia espumosa',
        'Sonda trava a cerca de 10 cm da narina',
        'Abdome escavado no início e depois distendido',
        'Sopro sistólico e assimetria no dorso',
      ],
      pedido: 'Recém-nascido com polidrâmnio, sialorreia e sonda que não progride: a pergunta é a anatomia do esôfago e se há malformações associadas.',
      pergunta: 'Radiografias seriadas. Qual é o achado que responde à pergunta clínica?',
      achado: 'Atresia de esôfago com hemivértebras',
      veredito: 'Atresia de esôfago sem fístula distal na associação VACTERL, corrigida com pequeno vazamento anastomótico',
      correlacao: 'O feto não engole o líquido amniótico quando o esôfago termina em fundo cego, por isso houve polidrâmnio. Depois do nascimento, a saliva se acumula no coto e reflui. As hemivértebras e o sopro sugerem a associação VACTERL, que exige procurar defeitos renais, anorretais e dos membros.',
      distratores: [
        d('Fístula traqueoesofágica em H isolada', 'Não tem atresia, a sonda desce ao estômago e os sintomas são tosse e pneumonia nas mamadas ao longo de semanas. O esôfago seria contínuo.'),
        d('Refluxo gastroesofágico do recém-nascido', 'Causa regurgitação depois das mamadas com a sonda passando livremente ao estômago e sem sialorreia desde o nascimento. O abdome teria gás.'),
        d('Atresia duodenal com dupla bolha', 'Também tem polidrâmnio, mas mostra estômago e duodeno cheios de ar, com vômitos biliosos e sonda que desce sem problemas. Associa-se a síndrome de Down.'),
      ],
    },
  },

  raquitismo: {
    tema: 'Osso em crescimento',
    titulo: 'Raquitismo com metáfises em taça e tíbias em sabre',
    resumo: 'Metáfises alargadas, desorganizadas e em taça com bordas esgarçadas, e arqueamento das tíbias e fêmures.',
    protocolo: 'Radiografia de membros inferiores AP com carga',
    rotulos: {
      fraying: r('Metáfise esgarçada e em taça', 'Borda da metáfise irregular, alargada e côncava.',
        'Na placa de crescimento, a cartilagem precisa calcificar para virar osso. Sem vitamina D, cálcio ou fosfato suficientes, ela continua crescendo sem calcificar. A metáfise fica larga, côncava como uma taça e com a borda desfiada como um pincel. Os sinais aparecem primeiro onde o osso cresce mais rápido: punhos, joelhos e junções costocondrais.',
        'Radiografia do punho é a mais útil para diagnosticar e acompanhar a resposta ao tratamento.'),
      'saber shin': r('Tíbia arqueada', 'Tíbias e fêmures curvados pelo peso.',
        'O osso pouco mineralizado é mole e se deforma com o peso do corpo. Quando a criança começa a andar, as pernas se arqueiam em varo, com os joelhos afastados. Com tratamento precoce, boa parte da deformidade se corrige com o crescimento; na doença antiga, pode exigir cirurgia.'),
    },
    achados: [
      'Metáfises do fêmur distal e da tíbia proximal alargadas, desorganizadas e irregulares, em taça e com bordas esgarçadas.',
      'Arqueamento diafisário medial das tíbias e dos fêmures.',
      'Alterações mais marcadas nas incidências com carga, compatíveis com raquitismo de longa data.',
    ],
    armadilhas: [
      'Arqueamento fisiológico em varo até os 2 anos é normal e simétrico, com metáfises normais.',
      'Raquitismo hipofosfatêmico ligado ao X não responde à vitamina D comum.',
      'Doença de Blount deforma só a tíbia proximal medial.',
    ],
    conduta: 'Dosar cálcio, fósforo, fosfatase alcalina, PTH e 25-hidroxivitamina D; repor vitamina D e cálcio no carencial, fosfato e calcitriol ou burosumabe no hipofosfatêmico, e acompanhar com radiografia do punho.',
    vinheta: {
      cenario: 'Ambulatório de pediatria',
      identificacao: 'Menino de 3 anos.',
      queixa: 'Pernas tortas que estão piorando e atraso para andar.',
      historia: 'Começou a andar com 20 meses e as pernas foram ficando cada vez mais arqueadas. Cansa ao caminhar e às vezes reclama de dor nas pernas. Foi amamentado exclusivamente até os 2 anos, com pouca comida sólida. Mora num apartamento e quase não sai ao sol. A mãe usa véu e também toma pouco sol.',
      antecedentes: [
        'Pessoais: aleitamento prolongado sem suplemento de vitamina D',
        'Pessoais: dentição atrasada',
        'Familiares: mãe com dores ósseas e pouca exposição solar',
        'Hábitos: pouca atividade ao ar livre',
      ],
      vitais: { pa: '92 × 56 mmHg', fc: '104 bpm', fr: '24 irpm', satO2: '99% em ar ambiente', temp: '36,5 °C' },
      exame: [
        'Pernas arqueadas em varo com joelhos afastados',
        'Punhos alargados',
        'Rosário raquítico nas junções costocondrais',
        'Fosfatase alcalina muito elevada e 25-hidroxivitamina D baixa',
      ],
      pedido: 'Arqueamento progressivo das pernas, punhos alargados e rosário raquítico em criança sem sol e sem suplemento: a pergunta é o padrão ósseo.',
      pergunta: 'Radiografia de membros inferiores. Qual é o achado que responde à pergunta clínica?',
      achado: 'Raquitismo por falta de vitamina D',
      veredito: 'Raquitismo com metáfises em taça e esgarçadas e arqueamento de tíbias e fêmures',
      correlacao: 'Sem sol e sem suplemento, a criança e a mãe não produziram vitamina D, e o leite materno sozinho não supre a necessidade. Sem vitamina D, o intestino não absorve cálcio, e a cartilagem de crescimento não calcifica: as metáfises alargam em taça e os punhos e as costelas engrossam. O osso mole se curva com o peso.',
      distratores: [
        d('Arqueamento fisiológico do lactente', 'É simétrico, melhora espontâneo até os 2 a 3 anos e as metáfises são normais na radiografia, sem rosário nem punhos alargados.'),
        d('Doença de Blount infantil', 'Deforma a parte medial da tíbia proximal com bico metafisário, sem alteração das outras metáfises nem fosfatase muito alta. É unilateral muitas vezes.'),
        d('Displasia metafisária de Schmid', 'Também deixa metáfises irregulares e pernas arqueadas, mas é genética, com vitamina D e fosfatase alcalina normais. Não há rosário raquítico.'),
      ],
    },
  },

  escorbuto: {
    tema: 'Osso em crescimento',
    titulo: 'Escorbuto com linha de Frankel e esporão de Pelkan',
    resumo: 'Linha densa de calcificação provisória nas metáfises, fratura metafisária com esporão e reação periosteal marcada nos joelhos e nos punhos.',
    protocolo: 'Radiografias de joelhos e punhos AP',
    series: ['Joelhos', 'Punhos'],
    rotulos: {
      'Frankel line': r('Linha de Frankel', 'Faixa branca e densa na borda da metáfise.',
        'A vitamina C é necessária para formar colágeno. Sem ela, os osteoblastos não produzem a matriz do osso, mas a cartilagem da placa continua calcificando. Forma-se então uma faixa muito densa de cartilagem calcificada na borda da metáfise, a linha de Frankel, com uma zona clara e frágil logo abaixo, a zona de Trümmerfeld.'),
      'Pelken cpur': r('Esporão de Pelkan', 'Pequena projeção óssea na borda da metáfise, por fratura.',
        'A zona clara abaixo da linha de Frankel é fraca e quebra com pequenos traumas. A borda da metáfise se projeta para fora como um esporão. É um sinal característico de escorbuto e mostra fraturas metafisárias por fragilidade.',
        'Fraturas metafisárias em criança pequena também sugerem maus-tratos: o contexto separa as duas causas.'),
      'periosteal reaction': r('Reação periosteal extensa', 'Periósteo descolado e calcificado ao longo dos ossos dos punhos.',
        'O colágeno defeituoso deixa os vasos frágeis, e o sangue se acumula embaixo do periósteo, descolando-o. Quando o tratamento começa, esse hematoma calcifica e aparece como uma reação periosteal larga. Essa hemorragia subperiosteal explica a dor intensa ao mexer as pernas.'),
    },
    apontamentosProprios: [
      p(0, 0.76, 0.635, 0, 'Linha de Frankel na tíbia', 'A mesma faixa densa na metáfise proximal da tíbia esquerda.',
        'As alterações do escorbuto são simétricas e aparecem em todas as metáfises de crescimento rápido: fêmur distal, tíbia proximal, punhos e junções costocondrais. Encontrar o mesmo sinal em vários ossos ajuda a separar uma doença sistêmica de um trauma localizado.'),
      p(0, 0.84, 0.52, 0, 'Anel de Wimberger', 'Epífise com borda densa e centro claro.',
        'Na epífise, a falta de osso novo deixa o centro rarefeito, enquanto a borda de cartilagem calcificada fica densa: a epífise parece um anel desenhado a lápis. O anel de Wimberger é um sinal clássico de escorbuto, diferente do sinal de Wimberger da sífilis congênita, que é uma erosão na tíbia.'),
      p(0, 0.76, 0.25, 0, 'Osteopenia difusa', 'Diáfises com cortical fina e osso mais transparente, aspecto em vidro fosco.',
        'Sem vitamina C, os osteoblastos não formam a matriz de colágeno, e o osso fica pobre e transparente. A cortical se afina como um traço a lápis. A osteopenia difusa junto com metáfises densas é a combinação típica do escorbuto.'),
    ],
    achados: [
      'Linha densa de calcificação provisória nas metáfises dos joelhos — linha de Frankel.',
      'Fratura metafisária com esporão — esporão de Pelkan.',
      'Reação periosteal marcada nos joelhos e nos dois punhos.',
    ],
    armadilhas: [
      'Escorbuto em criança com dieta restrita ou autismo é subdiagnosticado.',
      'Dor e recusa a andar podem ser confundidas com artrite ou leucemia.',
      'O anel de Wimberger, borda densa nas epífises, é outro sinal.',
    ],
    conduta: 'Reposição de vitamina C, que melhora a dor em dias, avaliação nutricional, investigação de restrição alimentar e acompanhamento da resolução das alterações.',
    vinheta: {
      cenario: 'Ambulatório de pediatria',
      identificacao: 'Menino de 5 anos com transtorno do espectro autista.',
      queixa: 'Não quer mais andar e chora quando mexem nas pernas.',
      historia: 'Há dois meses passou a mancar e agora se recusa a andar. Chora ao ser trocado e ao mexerem nas pernas. Há um ano só aceita biscoito de polvilho, macarrão e leite. As gengivas sangram ao escovar os dentes e apareceram manchas roxas nas pernas.',
      antecedentes: [
        'Pessoais: transtorno do espectro autista com seletividade alimentar intensa',
        'Pessoais: sem frutas nem verduras há um ano',
        'Familiares: sem doenças hematológicas',
        'Hábitos: dieta restrita a três alimentos',
      ],
      vitais: { pa: '94 × 58 mmHg', fc: '112 bpm', fr: '22 irpm', satO2: '99% em ar ambiente', temp: '37,2 °C' },
      exame: [
        'Gengivas edemaciadas e sangrantes',
        'Petéquias perifoliculares e equimoses nas pernas',
        'Dor intensa à mobilização dos joelhos',
        'Hemograma sem blastos',
      ],
      pedido: 'Recusa a andar, dor óssea, gengivas sangrando e petéquias em criança com dieta sem frutas e verduras: a pergunta é o padrão ósseo.',
      pergunta: 'Radiografias de joelhos e punhos. Qual é o achado que responde à pergunta clínica?',
      achado: 'Escorbuto com hemorragia subperiosteal',
      veredito: 'Escorbuto com linha de Frankel, esporão de Pelkan e reação periosteal',
      correlacao: 'Um ano sem frutas e verduras esgotou a vitamina C. Sem ela, o colágeno é defeituoso: os vasos sangram nas gengivas, na pele e embaixo do periósteo, o que dá a dor ao mexer as pernas. O osso novo não se forma, e a cartilagem calcificada se acumula na linha de Frankel, com fratura e esporão logo abaixo.',
      distratores: [
        d('Leucemia linfoide aguda com dor óssea', 'Também dá dor óssea, petéquias e recusa a andar, mas com faixas claras nas metáfises e alterações no hemograma, que aqui está normal.'),
        d('Lesões metafisárias por maus-tratos', 'Causam fraturas metafisárias em canto, mas sem gengivas sangrando, sem linha de Frankel e sem a história alimentar restrita. Exige avaliação social.'),
        d('Osteomielite hematogênica aguda', 'Dói em um osso só, com febre alta e marcadores inflamatórios altos, e não deixa alterações simétricas nos joelhos e punhos. Não há gengivas sangrando.'),
      ],
    },
  },

  'fratura-de-salter-harris-ii': {
    tema: 'Osso em crescimento',
    titulo: 'Fratura de Salter-Harris II do rádio distal',
    resumo: 'Fratura desviada pela placa de crescimento do rádio distal com fragmento metafisário, fratura angulada da ulna distal e redução adequada no gesso.',
    protocolo: 'Radiografias de punho AP, oblíqua e controle após redução',
    series: ['Frontal', 'Oblíqua', 'Controle no gesso'],
    rotulos: {
      'Fracture with angulation': r('Fratura angulada da ulna distal', 'Diáfise distal da ulna quebrada com angulação.',
        'A queda com a mão espalmada transmite a força pelo rádio e pela ulna. Fraturas associadas da ulna são comuns e influenciam a estabilidade da redução. A angulação precisa ser corrigida junto com a do rádio para não limitar a rotação do antebraço.'),
      'fractured bone fragment': r('Fragmento metafisário', 'Triângulo de osso da metáfise que acompanha a epífise.',
        'A classificação de Salter-Harris descreve fraturas que passam pela placa de crescimento. O tipo II é o mais comum: o traço corre pela placa e sai pela metáfise, levando um fragmento triangular de metáfise junto com a epífise, chamado fragmento de Thurston-Holland. Como a camada germinativa da placa fica com a epífise, o prognóstico de crescimento costuma ser bom.',
        'Mnemônico SALTR: tipo I separa, II acima, III abaixo, IV atravessa e V esmaga a placa.'),
      'Displaced physeal fracture': r('Fratura desviada pela placa de crescimento', 'A epífise do rádio deslocada em relação à metáfise.',
        'A placa de crescimento é a parte mais fraca do osso da criança, mais fraca que os ligamentos. Por isso, o mesmo trauma que no adulto causa entorse, na criança separa a placa. O desvio precisa ser reduzido com delicadeza e cedo, porque manipulações repetidas podem lesar a placa.'),
      'distal radius epiphysis': r('Epífise do rádio reduzida', 'Epífise de volta ao lugar no controle com gesso.',
        'Na radiografia de controle, a epífise deve estar alinhada com a metáfise. Em crianças pequenas, pequenas angulações residuais remodelam com o crescimento. O acompanhamento procura parada de crescimento, que se manifesta como encurtamento ou desvio do punho meses depois.'),
    },
    achados: [
      'Fratura desviada pela placa de crescimento do rádio distal com fragmento metafisário — Salter-Harris tipo II.',
      'Fratura angulada da diáfise distal da ulna.',
      'Controle com redução adequada da epífise do rádio e imobilização gessada.',
    ],
    armadilhas: [
      'Salter-Harris I sem desvio pode ter radiografia normal; dor na placa sugere fratura.',
      'Tipos III e IV atingem a articulação e costumam precisar de redução anatômica.',
      'Tipo V é muitas vezes reconhecido só quando o osso para de crescer.',
    ],
    conduta: 'Redução fechada sob analgesia, gesso, radiografias de controle em uma a duas semanas e seguimento do crescimento por meses.',
    vinheta: {
      cenario: 'Pronto-socorro de ortopedia pediátrica',
      identificacao: 'Menino de 11 anos, estudante.',
      queixa: 'Dor e deformidade no punho esquerdo depois de cair de skate.',
      historia: 'Caiu de skate apoiando a mão esquerda espalmada no chão. Sentiu dor forte e o punho ficou torto e inchado. Não consegue mexer a mão. Nega dormência nos dedos. É destro e está no meio do estirão de crescimento.',
      antecedentes: [
        'Pessoais: sem fraturas anteriores',
        'Pessoais: sem doenças',
        'Familiares: sem doenças ósseas',
        'Hábitos: anda de skate sem protetor de punho',
      ],
      vitais: { pa: '108 × 66 mmHg', fc: '104 bpm', fr: '20 irpm', satO2: '99% em ar ambiente', temp: '36,6 °C' },
      exame: [
        'Deformidade em dorso de garfo no punho esquerdo',
        'Dor à palpação do rádio e da ulna distais',
        'Perfusão e sensibilidade dos dedos normais',
        'Pele íntegra',
      ],
      pedido: 'Queda com a mão espalmada e deformidade do punho em criança: a pergunta é o tipo de fratura e se atinge a placa de crescimento.',
      pergunta: 'Radiografias do punho. Qual é o achado que responde à pergunta clínica?',
      achado: 'Fratura fisária Salter-Harris II',
      veredito: 'Fratura de Salter-Harris tipo II do rádio distal com fratura da ulna',
      correlacao: 'Na criança, a placa de crescimento é mais fraca que os ligamentos, e a queda sobre a mão espalmada separou a epífise do rádio pela placa, levando um triângulo de metáfise. O desvio dorsal deu a deformidade em dorso de garfo. Por ser tipo II, a redução precoce tem bom prognóstico de crescimento.',
      distratores: [
        d('Fratura em galho verde do rádio', 'Quebra uma só cortical da diáfise, que se dobra como um galho novo, sem passar pela placa de crescimento. Aqui o traço corre pela placa.'),
        d('Fratura de Salter-Harris tipo IV', 'Atravessa a epífise, a placa e a metáfise em um só traço vertical, entra na articulação e tem pior prognóstico. Precisa de redução anatômica.'),
        d('Fratura de Colles do adulto', 'Tem o mesmo desvio dorsal, mas ocorre em idosos com osteoporose, sem placa de crescimento aberta. Este paciente tem 11 anos e placas de crescimento abertas.'),
      ],
    },
  },

  'fratura-em-toro': {
    tema: 'Osso em crescimento',
    titulo: 'Fratura em toro do rádio distal',
    resumo: 'Linha densa de impactação transversa na metáfise distal do rádio com abaulamento sutil da cortical dorsal, sem traço que atravesse a cortical.',
    protocolo: 'Radiografias de punho AP, perfil e controle',
    series: ['Frontal', 'Perfil', 'Controle'],
    rotulos: {
      'impaction line': r('Linha de impactação', 'Faixa densa transversa na metáfise do rádio.',
        'O osso da criança é mais elástico e poroso que o do adulto. Uma queda com a mão espalmada comprime a metáfise, que se dobra para dentro em vez de quebrar. As trabéculas se compactam e aparecem como uma linha mais densa atravessando a metáfise.'),
      'cortical buckling,': r('Abaulamento da cortical', 'A cortical dorsal faz uma pequena dobra, sem romper.',
        'Toro, em latim, é a moldura saliente na base de uma coluna. Na fratura em toro, a cortical se dobra para fora como essa moldura, mas não se rompe. O sinal pode ser muito sutil, e o perfil é a incidência que melhor mostra a dobra na cortical dorsal.',
        'Siga a cortical com os olhos: qualquer degrau ou dobra na metáfise de uma criança que caiu é fratura.'),
      'sclerotic line': r('Linha esclerótica no controle', 'Faixa densa de consolidação semanas depois.',
        'Na radiografia de controle, a área impactada aparece mais densa por causa do osso novo formado na consolidação. A fratura em toro é estável e consolida em três a quatro semanas, sem necessidade de gesso fechado na maioria das crianças.'),
    },
    achados: [
      'Linha densa de impactação transversa na metáfise distal do rádio.',
      'Abaulamento sutil da cortical, mais evidente na cortical dorsal no perfil, sem ruptura cortical, desvio ou angulação.',
      'Placa de crescimento preservada e ulna distal íntegra; linha esclerótica de consolidação no controle.',
    ],
    armadilhas: [
      'O sinal é sutil: compare com o lado oposto ou com o perfil.',
      'Se a cortical está rompida de um lado, é galho verde, que é menos estável.',
      'Dor na tabaqueira anatômica pede pesquisa de fratura do escafoide.',
    ],
    conduta: 'Imobilização com tala removível por três semanas, analgesia e retorno às atividades conforme a dor, sem necessidade de radiografia de controle na maioria dos casos.',
    vinheta: {
      cenario: 'Pronto atendimento pediátrico',
      identificacao: 'Menina de 7 anos.',
      queixa: 'Dor no punho direito depois de cair do patinete.',
      historia: 'Caiu do patinete no parque e apoiou a mão direita no chão. Chorou de dor, mas continuou brincando. À noite o punho inchou um pouco e ela não quer apoiar a mão para se levantar.',
      antecedentes: [
        'Pessoais: sem fraturas anteriores',
        'Pessoais: sem doenças',
        'Familiares: sem doenças ósseas',
        'Hábitos: muito ativa, faz ginástica',
      ],
      vitais: { pa: '98 × 60 mmHg', fc: '96 bpm', fr: '20 irpm', satO2: '99% em ar ambiente', temp: '36,5 °C' },
      exame: [
        'Edema discreto no dorso do punho direito',
        'Dor à palpação do rádio distal, sem deformidade',
        'Movimentos dos dedos preservados',
        'Sem dor na tabaqueira anatômica',
      ],
      pedido: 'Queda com a mão espalmada e dor no rádio distal sem deformidade: a pergunta é se há fratura e de que tipo.',
      pergunta: 'Radiografias do punho. Qual é o achado que responde à pergunta clínica?',
      achado: 'Fratura em toro do rádio',
      veredito: 'Fratura em toro sem desvio do rádio distal',
      correlacao: 'O osso poroso e elástico da criança absorveu a compressão da queda dobrando a cortical da metáfise, sem rompê-la. Por isso há dor e um pouco de inchaço, sem deformidade, e a menina continuou brincando. A fratura é estável e consolida com uma tala simples.',
      distratores: [
        d('Fratura em galho verde do rádio', 'Rompe a cortical de um lado e dobra a do outro, com angulação visível, sendo menos estável que a fratura em toro. Aqui as corticais estão inteiras.'),
        d('Entorse do punho sem fratura', 'Dói nos ligamentos e não no rádio, e a radiografia não mostra linha de impactação nem dobra na cortical. É rara em criança pequena.'),
        d('Fratura de Salter-Harris tipo I', 'Separa a epífise pela placa de crescimento, com dor sobre a placa e às vezes alargamento dela, e não dobra a metáfise. Aqui a placa está preservada.'),
      ],
    },
  },

  'displasia-do-quadril': {
    tema: 'Quadril',
    titulo: 'Displasia do desenvolvimento do quadril com luxação tardia',
    resumo: 'Cabeça femoral esquerda luxada de um acetábulo raso, núcleo de ossificação pequeno, linha de Shenton rompida e metáfise acima de Hilgenreiner e lateral a Perkins; quadril direito normal.',
    protocolo: 'Radiografia de bacia AP',
    rotulos: {
      "Shenton's line": r('Linha de Shenton', 'Arco que une a borda do forame obturado ao colo femoral.',
        'A linha de Shenton é um arco contínuo entre a borda superior do forame obturado e a borda medial do colo do fêmur. Se a cabeça femoral sobe e sai do acetábulo, o arco se rompe e forma um degrau. À direita ela é contínua, à esquerda está quebrada.'),
      'right femoral head is enlocate': r('Quadril direito no lugar', 'Cabeça femoral direita dentro de um acetábulo profundo.',
        'O lado normal serve de comparação. A cabeça direita está centrada, o acetábulo é profundo e as linhas de referência estão normais. A comparação lado a lado é o modo mais confiável de perceber a displasia unilateral.'),
      'femoral head': r('Cabeça femoral direita', 'O núcleo de ossificação normal do lado direito.',
        'O núcleo de ossificação da cabeça femoral aparece entre 3 e 6 meses de vida. No quadril luxado, ele aparece mais tarde e fica menor, porque a cabeça fora do lugar recebe menos estímulo para crescer. Comparar o tamanho dos dois núcleos é um sinal útil.'),
      "Hilgenreiner's line": r('Linha de Hilgenreiner', 'Linha horizontal que passa pelas cartilagens trirradiadas.',
        'A linha de Hilgenreiner é desenhada na horizontal, ligando as duas cartilagens trirradiadas, no fundo dos acetábulos. A metáfise do fêmur normal fica abaixo dela. Se fica acima, a cabeça subiu e saiu do acetábulo.'),
      'shallow left acetabulum': r('Acetábulo esquerdo raso', 'Teto acetabular inclinado e pouco profundo.',
        'O acetábulo se aprofunda porque a cabeça femoral o pressiona durante o crescimento. Sem a cabeça dentro, ele fica raso e inclinado. O índice acetabular mede essa inclinação, e valores acima de 30 graus no lactente indicam displasia.'),
      'proximal femoral epiphysis': r('Núcleo de ossificação esquerdo pequeno', 'Núcleo da cabeça femoral esquerda menor que o direito.',
        'O núcleo menor do lado luxado mostra que a displasia já é antiga. Além do diagnóstico, isso indica risco de necrose da cabeça femoral durante o tratamento, que deve ser feito com cuidado.'),
      'centre point of the left proxi': r('Metáfise esquerda fora do quadrante', 'O ponto central da metáfise acima de Hilgenreiner e lateral a Perkins.',
        'As linhas de Hilgenreiner e Perkins dividem o quadril em quatro quadrantes. A metáfise normal fica no quadrante inferior e medial. A classificação IHDI usa a posição do ponto central da metáfise: acima da linha de Hilgenreiner é grau IV, a luxação mais alta.',
        'Na criança abaixo de 6 meses, o ultrassom é o exame de escolha, porque a cabeça ainda é cartilagem.'),
      "Perkin's line": r('Linha de Perkins', 'Linha vertical pela borda lateral do teto acetabular.',
        'A linha de Perkins é traçada perpendicular à de Hilgenreiner, na borda lateral do acetábulo. A cabeça ou a metáfise normal fica medial a ela. Se fica lateral, o quadril está deslocado para fora.'),
    },
    achados: [
      'Cabeça femoral esquerda luxada de um acetábulo raso.',
      'Núcleo de ossificação da cabeça femoral esquerda pequeno; linha de Shenton rompida à esquerda.',
      'Ponto central da metáfise femoral esquerda acima da linha de Hilgenreiner e lateral à de Perkins — luxação IHDI grau IV.',
      'Quadril direito centrado, com acetábulo profundo e linha de Shenton contínua.',
    ],
    armadilhas: [
      'As manobras de Ortolani e Barlow ficam negativas depois dos 3 meses, quando o quadril luxado fica preso.',
      'Displasia bilateral não tem assimetria, o que dificulta o diagnóstico clínico.',
      'Rotação da pelve na radiografia distorce as linhas de referência.',
    ],
    conduta: 'Encaminhar à ortopedia pediátrica; no diagnóstico tardio, redução fechada ou aberta sob anestesia com gesso pelvipodálico, e osteotomias quando necessário.',
    vinheta: {
      cenario: 'Ambulatório de ortopedia pediátrica',
      identificacao: 'Menina de 20 meses, primeira filha.',
      queixa: 'Manca desde que começou a andar.',
      historia: 'Começou a andar aos 15 meses e desde então manca da perna esquerda, com o tronco balançando para o lado. A mãe notou que a perna esquerda parece mais curta e as dobras das coxas são diferentes. Nasceu de parto cesáreo, em apresentação pélvica. Não fez ultrassom do quadril.',
      antecedentes: [
        'Pessoais: apresentação pélvica ao nascer',
        'Pessoais: primeira gestação, oligoidrâmnio',
        'Familiares: tia materna com displasia do quadril',
        'Hábitos: usava cueiro apertado com pernas esticadas',
      ],
      vitais: { pa: '88 × 52 mmHg', fc: '118 bpm', fr: '26 irpm', satO2: '99% em ar ambiente', temp: '36,5 °C' },
      exame: [
        'Membro inferior esquerdo mais curto, sinal de Galeazzi positivo',
        'Abdução do quadril esquerdo limitada',
        'Pregas cutâneas da coxa assimétricas',
        'Marcha com sinal de Trendelenburg à esquerda',
      ],
      pedido: 'Menina primogênita, nascida pélvica, com história familiar, encurtamento e abdução limitada: a pergunta é a posição da cabeça femoral.',
      pergunta: 'Radiografia de bacia. Qual é o achado que responde à pergunta clínica?',
      achado: 'Luxação congênita do quadril esquerdo',
      veredito: 'Displasia do desenvolvimento do quadril esquerdo com luxação IHDI grau IV',
      correlacao: 'Menina, primogênita, pélvica, com oligoidrâmnio, tia afetada e cueiro com pernas esticadas: todos os fatores de risco juntos. Sem diagnóstico precoce, a cabeça saiu do acetábulo, que ficou raso. A perna encurtou e a marcha passou a mancar com o tronco balançando, porque os abdutores trabalham sem o fulcro da cabeça.',
      distratores: [
        d('Doença de Legg-Calvé-Perthes', 'É necrose da cabeça femoral entre 4 e 8 anos, com cabeça achatada e fragmentada, mas dentro do acetábulo. A idade aqui é menor.'),
        d('Artrite séptica do quadril', 'Causa dor aguda, febre e recusa a mexer a perna, com derrame articular, e não um mancar indolor desde o início da marcha. Aqui não há febre.'),
        d('Coxa vara congênita do fêmur', 'Diminui o ângulo do colo femoral com defeito triangular no colo, mas a cabeça fica dentro de um acetábulo normal. A linha de Shenton fica contínua.'),
      ],
    },
  },

  'malformacao-adenomatoide-cistica': {
    tema: 'Tórax',
    titulo: 'Malformação congênita das vias aéreas pulmonares tipo 1',
    resumo: 'Grande lesão cística no pulmão direito com efeito de massa, atelectasias, cateteres umbilicais e tubo traqueal no recém-nascido; depois, dreno torácico e, no seguimento, opacidade homogênea residual.',
    protocolo: 'Radiografias de tórax AP seriadas no recém-nascido',
    series: ['Primeiro dia', 'Após drenagem', 'Seguimento'],
    rotulos: {
      'Endotracheal tube': r('Tubo traqueal', 'Tubo com a ponta acima da carina.',
        'No recém-nascido, a ponta do tubo traqueal deve ficar entre a primeira e a segunda vértebra torácica, acima da carina. Tubo baixo entra no brônquio direito e ventila só um pulmão; tubo alto pode sair da traqueia com o movimento da cabeça.'),
      'Umbilical artery catheter': r('Cateter de artéria umbilical', 'Cateter com a ponta em posição alta, entre T6 e T10.',
        'O cateter da artéria umbilical desce primeiro para a pelve e depois sobe pela aorta. A posição alta ideal é entre T6 e T10, acima das artérias do abdome. Posições entre T11 e L2 ficam perto das artérias renais e mesentéricas e podem causar tromboses.'),
      Atelectasis: r('Atelectasia', 'Pulmão colapsado em volta do cisto.',
        'O cisto grande ocupa espaço e comprime o pulmão vizinho, que colapsa e fica opaco. Também pode comprimir o outro pulmão. Atelectasias extensas pioram a troca de gases e explicam a necessidade de ventilação mecânica.'),
      'Umbilical vein catheter': r('Cateter de veia umbilical', 'Cateter com a ponta na veia porta esquerda.',
        'O cateter da veia umbilical deve passar pelo ducto venoso até a junção da veia cava inferior com o átrio direito. Se fica no fígado, como aqui na veia porta esquerda, pode causar trombose portal ou lesão hepática se usado para infusões irritantes.'),
      'Minimal aerated lung': r('Pequena área de pulmão aerado', 'Pouco pulmão normal acima e abaixo do cisto.',
        'O pouco pulmão que sobra aerado mostra quanto o cisto domina o hemitórax. Na malformação tipo 1, o problema não é só o cisto, mas o pulmão normal que não consegue se expandir. Ela é o que sustenta a troca de gases.'),
      'Large cystic lesion': r('Grande lesão cística', 'Cisto com ar ocupando quase todo o pulmão direito.',
        'A malformação congênita das vias aéreas pulmonares é um crescimento anormal de bronquíolos durante a gestação. O tipo 1 tem um ou poucos cistos grandes, maiores que 2 cm, cheios de ar depois do nascimento. Quando os cistos aprisionam ar, crescem, empurram o mediastino e comprimem o pulmão saudável, causando dificuldade respiratória grave.',
        'Diagnóstico diferencial principal: hérnia diafragmática congênita; confira se há alças no tórax e gás no abdome.'),
      Opacity: r('Líquido no interior do cisto', 'Opacidade na parte de baixo do cisto.',
        'Logo após o nascimento, o cisto ainda tem líquido pulmonar fetal, que vai sendo substituído por ar. Opacidade na parte pendente do cisto representa esse líquido. Com o tempo o cisto pode encher de ar e crescer, ou infectar.'),
      'umbilical artery catheter': r('Cateter arterial umbilical no controle', 'Ponta em T5, um pouco mais alta.',
        'Nas radiografias de controle, a posição dos cateteres deve ser revista sempre. Aqui a ponta subiu para T5, acima do ideal, e deve ser recuada para evitar que fique perto dos vasos do arco aórtico.'),
      'Endotracheal tube tip': r('Ponta do tubo traqueal em C7', 'Tubo um pouco alto, na altura de C7.',
        'Com a ponta em C7, o tubo está alto e corre risco de extubação acidental. A posição do pescoço muda a posição da ponta: flexão desce o tubo e extensão sobe. Deve ser ajustado para T1 ou T2.'),
      'ill-defined opacity': r('Lesão mal definida com gás', 'Área de gás mal delimitada nos campos médio e inferior direitos.',
        'Depois da drenagem, o cisto se esvaziou em parte e restou uma área de gás mal definida. Essa evolução mostra que o cisto pode ser descomprimido, mas a malformação continua presente e precisa ser retirada.'),
      'Chest tube': r('Dreno torácico', 'Dreno projetado no hemitórax superior direito.',
        'O dreno foi colocado para descomprimir o cisto ou um pneumotórax associado em um recém-nascido com insuficiência respiratória. É uma medida de estabilização antes da cirurgia definitiva.'),
      'Minimal air': r('Pouco ar residual', 'Pequena quantidade de ar na área do cisto.',
        'O ar residual mostra o cisto parcialmente descomprimido. As radiografias seriadas acompanham se ele volta a encher, o que indicaria cirurgia mais rápida. Também ajudam a ver se o dreno está funcionando.'),
      'homogenous opacity': r('Opacidade homogênea residual', 'Opacidade uniforme no hemitórax direito no seguimento.',
        'No seguimento, a área da malformação aparece como opacidade homogênea, que pode ser pulmão operado, espessamento ou líquido. A TC define se resta malformação e orienta o seguimento. Ela pode persistir meses.'),
      'apical pleural thickening': r('Espessamento pleural apical', 'Pleura espessada no ápice direito.',
        'Espessamento pleural depois de drenos e cirurgia torácica é sequela comum. Ele deve ser acompanhado, mas não costuma causar sintomas. Deve ser comparado em exames futuros para garantir que está estável e não esconde uma coleção.'),
    },
    achados: [
      'Grande lesão cística no pulmão direito com efeito de massa sobre o mediastino e o pulmão esquerdo, com líquido na parte pendente e pouco pulmão aerado acima e abaixo.',
      'Atelectasias em volta do cisto e dos lobos superior e inferior esquerdos.',
      'Tubo traqueal acima da carina, cateter de veia umbilical na veia porta esquerda e cateter arterial umbilical em posição alta.',
      'Após drenagem, lesão com gás mal definida e pouco ar residual; no seguimento, opacidade homogênea e espessamento pleural apical.',
    ],
    armadilhas: [
      'Hérnia diafragmática também mostra cistos no tórax: procure o estômago e a sonda.',
      'Cateteres mal posicionados são frequentes e devem ser descritos em toda radiografia neonatal.',
      'Malformações tipo 1 têm pequeno risco de tumor no futuro, o que favorece a ressecção.',
    ],
    conduta: 'Suporte ventilatório, TC de tórax e lobectomia, de urgência se houver insuficiência respiratória ou eletiva nos primeiros meses se estável.',
    vinheta: {
      cenario: 'Unidade de terapia intensiva neonatal',
      identificacao: 'Recém-nascida de 2 horas de vida.',
      queixa: 'Desconforto respiratório grave logo após o nascimento.',
      historia: 'O ultrassom morfológico do segundo trimestre mostrou uma lesão no pulmão direito do feto. Nasceu a termo de parto cesáreo e logo apresentou gemência, tiragem e cianose, sendo intubada na sala de parto. Foram colocados cateteres umbilicais.',
      antecedentes: [
        'Gestacionais: lesão pulmonar fetal vista no ultrassom de 22 semanas',
        'Gestacionais: polidrâmnio leve',
        'Familiares: sem malformações conhecidas',
        'Pessoais: Apgar 5 e 7',
      ],
      vitais: { pa: '58 × 34 mmHg', fc: '168 bpm', fr: '72 irpm', satO2: '86% com oxigênio a 60%', temp: '36,4 °C' },
      exame: [
        'Tórax direito abaulado',
        'Murmúrio vesicular ausente à direita',
        'Bulhas deslocadas para a esquerda',
        'Abdome normal, com bolha gástrica no lugar',
      ],
      pedido: 'Recém-nascida com lesão pulmonar fetal, desconforto grave e tórax direito abaulado: a pergunta é a natureza da lesão e a posição dos dispositivos.',
      pergunta: 'Radiografias de tórax seriadas. Qual é o achado que responde à pergunta clínica?',
      achado: 'Malformação congênita cística pulmonar',
      veredito: 'Malformação congênita das vias aéreas pulmonares tipo 1 do pulmão direito',
      correlacao: 'O pulmão direito formou bronquíolos anormais durante a gestação, o que o ultrassom fetal já mostrou. Depois do nascimento, o cisto encheu de ar, comprimiu o pulmão saudável e empurrou o coração, por isso o desconforto grave e as bulhas deslocadas. O estômago no lugar afasta a hérnia diafragmática.',
      distratores: [
        d('Hérnia diafragmática congênita esquerda', 'Põe alças intestinais no tórax, geralmente à esquerda, com abdome escavado e a sonda gástrica subindo para o tórax. Aqui o estômago está no abdome.'),
        d('Enfisema lobar congênito', 'Hiperinsufla um lobo, quase sempre o superior esquerdo, sem cistos com paredes e sem líquido no interior. O lobo fica escuro e não cístico.'),
        d('Pneumotórax hipertensivo neonatal', 'Também desloca o mediastino, mas é ar livre na pleura sem paredes de cisto e com o pulmão colapsado no hilo. O ar contorna o pulmão inteiro.'),
      ],
    },
  },
}
