import { d, r, type ConteudoCaso } from './casos-imagem-tipos'

/** Segunda leva de TC — pescoço, parte 2. Pacientes das vinhetas são fictícios. */
export const CASOS_TC_L2_CABECA_PESCOCO_2: Record<string, ConteudoCaso> = {
  'bocio-mergulhante': {
    tema: 'Tireoide',
    titulo: 'Bócio multinodular gigante mergulhante',
    resumo: 'Massas tireoidianas heterogêneas que descem ao mediastino anterior, com calcificações, comprimindo e desviando a traqueia e afastando os grandes vasos.',
    protocolo: 'TC de pescoço e tórax com contraste, fase arterial',
    series: ['Coronal', 'Axial'],
    rotulos: {
      connected: r('Conexão com a tireoide cervical', 'O componente mediastinal continua o cervical por um segmento curto.',
        'O que define o bócio mergulhante é a continuidade com a tireoide do pescoço: o tecido desce pela abertura torácica superior para o mediastino. Ver essa conexão separa o bócio de outras massas do mediastino anterior, como timoma, linfoma e teratoma.',
        'Massa do mediastino anterior que se conecta à tireoide e realça intensamente é bócio até prova contrária.'),
      'mediastinal masses': r('Massas no mediastino anterior', 'Grandes componentes heterogêneos, com calcificações e áreas de necrose.',
        'O tecido tireoidiano contém iodo e por isso é mais denso que os músculos mesmo sem contraste, e realça intensamente. Bócios antigos são heterogêneos, com nódulos, cistos, hemorragias e calcificações grosseiras.'),
      brachiocephalic: r('Tronco braquiocefálico afastado', 'A artéria é empurrada pela massa, sem ser invadida.',
        'O bócio empurra os vasos em vez de invadi-los, como faz uma massa benigna de crescimento lento. Vasos afastados, mas com calibre e contorno preservados, falam a favor de benignidade. O cirurgião precisa saber dessa relação para dissecar a massa com segurança.'),
      'left carotid artery': r('Carótida comum esquerda afastada', 'A carótida esquerda deslocada pela massa.',
        'O afastamento das carótidas mostra o volume do bócio. O planejamento cirúrgico considera essa relação: bócios que descem muito abaixo do arco aórtico podem exigir esternotomia. A massa empurra a artéria, mas a luz e a parede continuam normais, sem sinais de invasão.'),
      'marked narrowing': r('Estreitamento acentuado da traqueia', 'A traqueia comprimida pela massa, com luz reduzida.',
        'A compressão traqueal causa dispneia que piora deitado e estridor. Redução importante da luz traqueal aumenta o risco na intubação e é indicação de cirurgia. Traqueomalácia, a traqueia amolecida pela compressão crônica, pode aparecer depois da cirurgia.',
        'Bócio com compressão traqueal exige planejamento da via aérea antes de qualquer sedação.'),
      'Mass effect on the trachea': r('Desvio da traqueia', 'Traqueia empurrada para a direita.',
        'O efeito de massa desloca a traqueia para o lado oposto ao maior componente. Desvio e compressão juntos explicam os sintomas respiratórios e a disfagia. Na radiografia, esse desvio aparece como traqueia curva, empurrada para o lado oposto ao bócio.'),
    },
    achados: [
      'Duas grandes massas heterogêneas do mediastino anterior conectadas à tireoide, a maior com 14 cm, com calcificações e possível necrose.',
      'Desvio da traqueia para a direita com estreitamento acentuado da luz.',
      'Afastamento do tronco braquiocefálico e da carótida comum esquerda, sem invasão.',
    ],
    armadilhas: [
      'Elevar os braços pode piorar a compressão da veia cava superior — sinal de Pemberton.',
      'Contraste iodado em bócio pode precipitar hipertireoidismo em áreas autônomas.',
      'Crescimento rápido, invasão de estruturas ou linfonodos pedem investigação de carcinoma.',
    ],
    conduta: 'Função tireoidiana, avaliação da via aérea e tireoidectomia total, cervical ou com esternotomia, conforme a extensão mediastinal.',
    vinheta: {
      cenario: 'Ambulatório de cirurgia de cabeça e pescoço',
      identificacao: 'Mulher de 67 anos, aposentada, vinda do interior.',
      queixa: 'Falta de ar ao deitar e dificuldade para engolir comprimidos.',
      historia: 'Tem papo no pescoço há mais de 20 anos, que nunca tratou. Nos últimos dois anos sente falta de ar quando deita de costas e chiado ao dormir, e precisa de três travesseiros. Engole sólidos com dificuldade. Ao levantar os braços para estender roupa, o rosto fica vermelho e a cabeça pesa.',
      antecedentes: [
        'Pessoais: sem tratamento prévio da tireoide',
        'Gestacionais: cinco gestações',
        'Familiares: mãe e irmã com papo',
        'Hábitos: morou a vida toda em região montanhosa, com pouco acesso a sal iodado na infância',
      ],
      vitais: { pa: '138 × 82 mmHg', fc: '78 bpm', fr: '20 irpm', satO2: '95% em ar ambiente', temp: '36,3 °C' },
      exame: [
        'Bócio multinodular volumoso cujo polo inferior não é palpável',
        'Estridor leve em decúbito',
        'Sinal de Pemberton positivo',
        'TSH normal',
      ],
      pedido: 'Bócio de longa data com polo inferior não palpável, dispneia ortostática e sinal de Pemberton: a pergunta é a extensão mediastinal e o grau de compressão.',
      pergunta: 'TC de pescoço e tórax com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Bócio multinodular mergulhante',
      veredito: 'Bócio multinodular gigante mergulhante com compressão e desvio da traqueia',
      correlacao: 'A deficiência de iodo na infância e a história familiar explicam o bócio multinodular que cresceu por décadas. Sem espaço no pescoço, ele desceu pela abertura torácica para o mediastino anterior, onde comprime a traqueia e os vasos. Ao deitar ou levantar os braços, a abertura torácica se estreita e a compressão piora — o sinal de Pemberton.',
      distratores: [
        d('Timoma do mediastino anterior', 'Também ocupa o mediastino anterior, mas não tem continuidade com a tireoide e costuma ser mais homogêneo e menos calcificado, às vezes com miastenia.'),
        d('Linfoma mediastinal volumoso', 'Forma massa de linfonodos confluentes que envolvem os vasos, em paciente mais jovem, com sintomas B, sem relação com a tireoide.'),
        d('Carcinoma anaplásico da tireoide', 'Cresce em semanas, invade traqueia, vasos e esôfago e causa rouquidão e dor, em vez de crescimento lento ao longo de décadas. Ele também se acompanha de linfonodos e metástases precoces.'),
      ],
    },
  },

  'angina-de-ludwig': {
    tema: 'Espaços profundos do pescoço',
    titulo: 'Angina de Ludwig com extensão aos espaços profundos',
    resumo: 'Coleção multiloculada no espaço sublingual estendendo-se aos espaços submandibular, mastigatório, parafaríngeo, mucoso faríngeo e retrofaríngeo, com desvio da via aérea.',
    protocolo: 'TC de pescoço com contraste, fase portal',
    series: ['Axial', 'Coronal'],
    rotulos: {
      nasopharynx: r('Nasofaringe desviada', 'A coluna de ar da nasofaringe estreitada e desviada.',
        'O edema que sobe pelos espaços parafaríngeo e retrofaríngeo empurra a parede da nasofaringe. É sinal de extensão alta do processo, longe do assoalho da boca onde ele começou. Quanto mais alto o edema chega, maior o risco de perda da via aérea durante a manipulação.'),
      oropharynx: r('Orofaringe comprimida', 'A via aérea na altura da orofaringe reduzida e desviada.',
        'Na angina de Ludwig, a língua é empurrada para cima e para trás pelo edema do assoalho da boca, e a orofaringe se fecha. A morte vem da obstrução da via aérea, não da infecção em si. A luz residual medida na TC ajuda a planejar a via aérea.',
        'O risco de perda da via aérea dita a conduta: intubação acordada com fibroscópio ou traqueostomia com anestesia local.'),
      parapharyngeal: r('Espaço parafaríngeo', 'Edema invadindo o espaço lateral à faringe.',
        'O espaço parafaríngeo liga o assoalho da boca aos espaços profundos do pescoço e ao mediastino. Infecção que chega a ele pode descer e causar mediastinite. Ele contém a artéria carótida e a veia jugular, que podem ser envolvidas pela infecção.'),
      'left masticator': r('Espaço mastigatório esquerdo', 'A coleção alcança o espaço dos músculos da mastigação.',
        'O espaço mastigatório contém os músculos pterigoides e o masseter. Inflamação ali causa trismo, que dificulta abrir a boca e intubar pela via oral. Esse é o motivo pelo qual a intubação deve ser planejada com fibroscópio, com o paciente acordado.'),
      'phayrngeal mucosal': r('Espaço mucoso faríngeo', 'Edema da mucosa da faringe.',
        'O edema da mucosa faríngea reduz ainda mais a luz da via aérea e causa dor para engolir e voz abafada. Esse espaço é a camada mais interna da faringe, e o edema ali é o que o paciente sente como bola na garganta. Com os outros espaços acometidos, a via aérea fica cercada de todos os lados.'),
      submandibular: r('Espaço submandibular', 'Coleção e densificação abaixo da mandíbula.',
        'A angina de Ludwig é uma celulite bilateral dos espaços submandibular e sublingual, geralmente a partir de um molar inferior infectado, cujas raízes ficam abaixo da inserção do músculo milo-hióideo. O pus passa direto para o espaço submandibular.'),
      retropharyngeal: r('Espaço retrofaríngeo', 'Edema atrás da faringe.',
        'O espaço retrofaríngeo é a avenida para o mediastino. Edema ou coleção ali é sinal de alerta e exige avaliação do tórax. Coleção nesse espaço exige incluir o mediastino superior no exame e vigilância de dor torácica e febre persistente.'),
      'lymph nodes': r('Linfonodos cervicais', 'Linfonodos aumentados, reativos.',
        'Linfonodos cervicais reativos acompanham a infecção. Centro hipodenso indicaria necrose e abscesso ganglionar. Eles drenam o assoalho da boca e o espaço submandibular e diminuem com o tratamento da infecção.'),
    },
    achados: [
      'Coleção multiloculada no espaço sublingual com extensão aos espaços submandibular e mastigatório esquerdo.',
      'Edema invadindo os espaços parafaríngeo, mucoso faríngeo e retrofaríngeo esquerdos.',
      'Desvio e estreitamento da orofaringe e da nasofaringe.',
      'Densificação extensa da gordura submandibular e submentoniana e linfonodos reativos, sem gás.',
    ],
    armadilhas: [
      'A ausência de coleção não exclui a doença: a angina de Ludwig é celulite e pode matar antes de formar pus.',
      'Não mande paciente com estridor sozinho para o tomógrafo: a via aérea vem primeiro.',
      'Gás nos tecidos sugere anaeróbios e infecção necrosante.',
    ],
    conduta: 'Garantir a via aérea, antibiótico venoso de amplo espectro com cobertura anaeróbia, drenagem cirúrgica das coleções, extração do dente causador e vigilância de mediastinite.',
    vinheta: {
      cenario: 'Sala de emergência',
      identificacao: 'Homem de 45 anos, mecânico.',
      queixa: 'Pescoço muito inchado, não consegue engolir e a língua está levantada.',
      historia: 'Há uma semana tem dor no dente de trás do lado esquerdo, embaixo. Há três dias o queixo e o pescoço incharam dos dois lados e ficaram duros. Hoje não consegue engolir a saliva, a voz está abafada e sente falta de ar quando deita.',
      antecedentes: [
        'Pessoais: diabetes tipo 2 sem acompanhamento',
        'Pessoais: dentes cariados, sem ida ao dentista há anos',
        'Familiares: sem doenças relevantes',
        'Hábitos: etilista e tabagista',
      ],
      vitais: { pa: '102 × 62 mmHg', fc: '124 bpm', fr: '28 irpm', satO2: '93% em ar ambiente', temp: '39,4 °C' },
      exame: [
        'Edema endurecido, lenhoso, submandibular e submentoniano bilateral',
        'Língua elevada e protrusa, assoalho da boca abaulado',
        'Trismo e sialorreia',
        'Estridor inspiratório leve, prefere ficar sentado',
      ],
      pedido: 'Infecção dentária com edema lenhoso do assoalho da boca, língua elevada e estridor: depois de garantida a via aérea, a pergunta é a extensão aos espaços profundos.',
      pergunta: 'TC de pescoço com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Angina de Ludwig com coleção multiloculada',
      veredito: 'Angina de Ludwig com coleção sublingual multiloculada e extensão aos espaços profundos e retrofaríngeo',
      correlacao: 'A infecção do molar inferior desceu pelas raízes, abaixo do músculo milo-hióideo, para os espaços sublingual e submandibular dos dois lados. O edema lenhoso eleva a língua e fecha a orofaringe, o que explica o estridor e a voz abafada. A TC mostra a coleção multiloculada e a extensão para os espaços profundos, que ameaça o mediastino.',
      distratores: [
        d('Abscesso periamigdaliano unilateral', 'Desvia a úvula e causa trismo, mas a coleção fica junto à amígdala, sem o edema bilateral do assoalho da boca e sem elevação da língua.'),
        d('Angioedema hereditário de assoalho', 'Incha a língua e o assoalho da boca em horas, sem febre, sem dente doente e sem coleções, com edema mole e não lenhoso. Há história de crises semelhantes e não há febre.'),
        d('Sialadenite submandibular obstrutiva', 'Aumenta uma glândula submandibular com dor ao comer, por cálculo no ducto, sem acometimento bilateral nem extensão aos espaços profundos.'),
      ],
    },
  },

  'abscesso-periapical': {
    tema: 'Espaços profundos do pescoço',
    titulo: 'Abscesso periapical da maxila com celulite facial',
    resumo: 'Lesão osteolítica envolvendo as raízes dos incisivos com cortical afinada e interrompida, edema do lábio e da bochecha e linfonodos submandibulares.',
    protocolo: 'TC de face, janela óssea axial e coronal',
    series: ['Axial', 'Coronal'],
    rotulos: {
      'defective osseous margin': r('Cortical interrompida', 'A parede óssea da maxila afinada e com falha sobre a lesão.',
        'O pus acumulado no ápice do dente reabsorve o osso ao redor. Quando a cortical se rompe, o pus sai para as partes moles, formando abscesso subperiosteal ou celulite. A falha na cortical mostra por onde a infecção escapou.'),
      'submandibular lymph nodes': r('Linfonodos submandibulares', 'Linfonodos aumentados que drenam a região da face.',
        'A drenagem linfática dos dentes e do lábio vai para os linfonodos submandibulares, que aumentam de forma reativa. Eles ajudam a localizar a origem da infecção. Eles regridem com o tratamento; aumento persistente após a cura pede investigação de outras causas.'),
      'Small lucency': r('Pequena lucência periapical', 'Halo escuro em volta da raiz de um dente supranumerário quebrado.',
        'Lucências ao redor do ápice da raiz indicam reabsorção óssea por inflamação crônica — granuloma ou cisto periapical. São lesões silenciosas que podem agudizar. Ela pode crescer e infectar se o dente não for tratado.'),
      'bone cystic lesion': r('Lesão cística periapical', 'Lesão bem definida envolvendo as raízes dos incisivos.',
        'A necrose da polpa dentária leva bactérias até o ápice da raiz, onde se forma um granuloma que pode virar cisto. Infectado, vira abscesso. Na TC, aparece como lucência arredondada envolvendo a raiz, com o espaço do ligamento periodontal alargado.',
        'Procure sempre o dente causador: tratar a celulite sem tratar o dente leva à recidiva.'),
    },
    achados: [
      'Lesão cística bem definida envolvendo as raízes dos incisivos superiores direitos.',
      'Afilamento e interrupção da cortical óssea sobre a lesão.',
      'Edema do lábio superior e da bochecha direita.',
      'Pequena lucência periapical em dente supranumerário e linfonodos submandibulares reativos.',
    ],
    armadilhas: [
      'Abscessos dos dentes superiores podem drenar para o seio maxilar e para a órbita.',
      'Edema facial com febre alta e trismo pede avaliação de espaços profundos.',
      'Cisto periapical e queratocisto podem ser parecidos; a relação com o ápice de dente não vital favorece o periapical.',
    ],
    conduta: 'Drenagem do abscesso, tratamento endodôntico ou extração do dente causador e antibiótico se houver celulite ou sinais sistêmicos.',
    vinheta: {
      cenario: 'Pronto-socorro odontológico',
      identificacao: 'Menino de 12 anos, trazido pela mãe.',
      queixa: 'Lábio de cima e bochecha inchados com dor no dente da frente.',
      historia: 'Há dois anos bateu os dentes da frente numa queda de bicicleta, e um deles ficou escurecido. Há três dias começou dor latejante nesse dente, e ontem o lábio superior e a bochecha direita incharam. Teve febre de 38 °C.',
      antecedentes: [
        'Pessoais: dente supranumerário diagnosticado e não tratado',
        'Gestacionais: nascido a termo, sem intercorrências',
        'Familiares: sem doenças relevantes',
        'Hábitos: escovação irregular, consumo frequente de doces',
      ],
      vitais: { pa: '108 × 66 mmHg', fc: '102 bpm', fr: '18 irpm', satO2: '99% em ar ambiente', temp: '38,1 °C' },
      exame: [
        'Edema do lábio superior e da bochecha direita',
        'Incisivo central superior escurecido, doloroso à percussão',
        'Abaulamento flutuante no vestíbulo acima do dente',
        'Linfonodo submandibular direito doloroso',
      ],
      pedido: 'Celulite facial a partir de um incisivo traumatizado e escurecido: a pergunta é a origem óssea e a extensão da infecção.',
      pergunta: 'TC de face. Qual é o achado que responde à pergunta clínica?',
      achado: 'Abscesso periapical com cortical rompida',
      veredito: 'Abscesso periapical dos incisivos superiores com cortical interrompida e celulite facial',
      correlacao: 'O trauma antigo matou a polpa do incisivo, que escureceu. Bactérias chegaram ao ápice da raiz e formaram uma lesão que reabsorveu o osso. Quando a cortical se rompeu, a infecção alcançou o lábio e a bochecha. O dente doloroso à percussão e o abaulamento no vestíbulo apontam a origem.',
      distratores: [
        d('Celulite facial de origem cutânea', 'Começa numa lesão da pele, como uma picada ou foliculite, sem dente doente e sem lesão óssea periapical. O tratamento seria só antibiótico, sem procedimento no dente.'),
        d('Sinusite maxilar aguda complicada', 'Causa dor e edema na bochecha com secreção nasal, a partir do seio velado, e não de lesão em torno da raiz dos incisivos. O seio desta criança está apenas com espessamento mucoso.'),
        d('Queratocisto odontogênico infectado', 'É uma lesão cística expansiva da mandíbula ou da maxila, geralmente posterior e sem relação com dente sem vitalidade. Ele também tende a recidivar após a remoção.'),
      ],
    },
  },
}
