import { d, r, type ConteudoCaso } from './casos-imagem-tipos'

/** Segunda leva de TC — abdome, parte 2 (vias biliares, fígado, pâncreas, baço). Pacientes fictícios. */
export const CASOS_TC_L2_ABDOME_2: Record<string, ConteudoCaso> = {
  'perfuracao-da-vesicula': {
    tema: 'Abdome agudo inflamatório',
    titulo: 'Perfuração da vesícula biliar',
    resumo: 'Vesícula distendida com defeitos em várias paredes, coleção pericolecística, densificação extensa e cálculo fora da vesícula na goteira direita.',
    protocolo: 'TC de abdome com contraste, fase portal',
    rotulos: {
      'pericholecystic collection': r('Coleção pericolecística', 'Pequena coleção ao lado da vesícula, descendo para baixo.',
        'Quando a parede da vesícula necrosa e se rompe, a bile e o pus saem e ficam bloqueados pelo omento e pelas alças vizinhas, formando uma coleção junto à vesícula. É a perfuração bloqueada, o tipo mais comum.'),
      'anterior wall defect': r('Defeito da parede anterior', 'Falha na parede anterior da vesícula.',
        'O defeito na parede aparece como interrupção do contorno que realça, às vezes com o conteúdo vazando por ali. É o sinal mais específico de perfuração, mas nem sempre é visível. Seguir a parede em vários cortes é o que permite ver a falha com segurança.',
        'O defeito parietal visível na TC é o achado mais específico de perfuração; a ultrassonografia o mostra como o sinal do buraco.'),
      'focal bulge': r('Abaulamento focal da parede', 'A parede faz uma bolsa para fora no ponto mais fraco.',
        'Antes de romper, a parede necrosada cede e se abaula. O abaulamento junto a um defeito mostra por onde o conteúdo está saindo. Esse abaulamento costuma estar junto do ponto em que a parede necrosou e cedeu. Encontrá-lo orienta onde procurar o defeito e onde o cirurgião deve esperar a perfuração.'),
      'posteromedial mural defect': r('Defeito posteromedial', 'Falha na parede posteromedial, junto ao fígado.',
        'A perfuração que se volta para o fígado pode formar abscesso hepático; a que se volta para a cavidade livre causa peritonite. A direção do defeito muda a conduta. Defeitos múltiplos indicam necrose mais extensa da parede.'),
      'posterolateral mural defect': r('Defeito posterolateral', 'Outra falha, na parede posterolateral.',
        'Múltiplos defeitos indicam necrose extensa da parede, comum em idosos, diabéticos e pacientes com doença vascular, nos quais a colecistite gangrena com mais facilidade. Cada falha é uma porta para a bile e o pus saírem da vesícula.'),
      'mural defects': r('Defeitos parietais múltiplos', 'Várias falhas na parede da vesícula.',
        'A vesícula com vários defeitos, distendida e sem cálculos densos visíveis, mostra uma parede que perdeu a viabilidade em vários pontos. É a evolução da colecistite gangrenosa para perfuração.'),
      'extraluminal gallstone': r('Cálculo fora da vesícula', 'Foco calcificado na goteira direita, com inflamação em volta.',
        'Um cálculo que saiu da vesícula pela perfuração e caiu na goteira parietocólica é prova de que a parede rompeu. Cálculos perdidos na cavidade podem formar abscessos tardios se não forem retirados.'),
      'fat stranding': r('Densificação inflamatória da gordura', 'Gordura inflamada do hipocôndrio à fossa ilíaca direita.',
        'A inflamação desce pela goteira direita até a fossa ilíaca, o que pode imitar apendicite. Seguir a densificação de cima para baixo mostra que a fonte é a vesícula. Quanto mais extensa, mais avançada costuma estar a inflamação.'),
      'serous inclusion cyst': r('Cisto de inclusão peritoneal', 'Coleção cística de líquido seroso, achado associado.',
        'Cistos de inclusão peritoneal são coleções de líquido aprisionadas por aderências, comuns em pacientes com inflamação ou cirurgia prévia. Têm paredes finas e conteúdo de água e não exigem tratamento por si.'),
    },
    achados: [
      'Vesícula distendida com defeitos parietais posteromedial, posterolateral e anterior, com abaulamentos focais.',
      'Pequena coleção pericolecística descendo inferiormente.',
      'Densificação inflamatória do hipocôndrio direito à fossa ilíaca direita, com cálculo extraluminal na goteira.',
      'Colédoco dilatado a 11 mm; cisto de inclusão peritoneal.',
    ],
    armadilhas: [
      'Idosos e diabéticos podem ter poucos sintomas mesmo com vesícula gangrenada.',
      'Inflamação que desce pela goteira direita imita apendicite.',
      'Cálculo fora da vesícula é sinal quase definitivo de perfuração.',
    ],
    conduta: 'Antibiótico, ressuscitação, colecistectomia de urgência ou colecistostomia percutânea em paciente de alto risco, drenagem das coleções e retirada de cálculos perdidos.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Homem de 76 anos, aposentado, diabético.',
      queixa: 'Dor no lado direito da barriga há seis dias, agora espalhada até embaixo.',
      historia: 'Há seis dias tem dor no hipocôndrio direito com febre, que tratou em casa com analgésicos. Há dois dias a dor ficou menos localizada e passou a descer pelo lado direito do abdome. Hoje está prostrado e com febre alta.',
      antecedentes: [
        'Pessoais: diabetes tipo 2 com neuropatia e doença arterial periférica',
        'Pessoais: insuficiência renal crônica leve',
        'Familiares: sem doenças relevantes',
        'Hábitos: ex-tabagista de 40 maços-ano',
      ],
      vitais: { pa: '98 × 58 mmHg', fc: '116 bpm', fr: '24 irpm', satO2: '95% em ar ambiente', temp: '38,9 °C' },
      exame: [
        'Dor e defesa no hipocôndrio e flanco direitos até a fossa ilíaca',
        'Sinal de Murphy pouco evidente',
        'Bilirrubina discretamente elevada',
        'Leucocitose de 21.000',
      ],
      pedido: 'Colecistite tratada tardiamente em idoso diabético e vasculopata, com dor que se espalhou e sepse: a pergunta é se houve complicação da vesícula.',
      pergunta: 'TC de abdome com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Perfuração bloqueada da vesícula',
      veredito: 'Perfuração da vesícula biliar com defeitos parietais múltiplos, coleção pericolecística e cálculo extraluminal',
      correlacao: 'Colecistite não tratada num idoso diabético com doença vascular: a parede isquemiou, necrosou e rompeu em vários pontos. A dor que deixou de ser localizada e desceu pelo flanco acompanha a bile e o pus escorrendo pela goteira, junto com um cálculo que saiu da vesícula. O Murphy pouco evidente é típico quando a parede já está necrótica.',
      distratores: [
        d('Apendicite aguda retrocecal', 'Daria dor no flanco e na fossa ilíaca direita com apêndice dilatado e inflamado. Aqui o apêndice é normal e a inflamação parte da vesícula.'),
        d('Colecistite aguda não complicada', 'Tem parede espessa com realce preservado e Murphy evidente, sem defeitos na parede nem cálculo fora da vesícula. Não haveria defeito na parede nem coleção em volta da vesícula.'),
        d('Abscesso hepático piogênico', 'Seria coleção dentro do parênquima do fígado, com parede que realça, sem defeitos na parede da vesícula. A vesícula estaria íntegra e o foco ficaria dentro do parênquima hepático, não junto à parede da vesícula.'),
      ],
    },
  },

  coledocolitiase: {
    tema: 'Fígado e vias biliares',
    titulo: 'Coledocolitíase com dilatação das vias biliares',
    resumo: 'Cálculo no colédoco intrapancreático com dilatação das vias biliares; cistos renais e hérnia umbilical incidentais.',
    protocolo: 'TC de abdome sem e com contraste, fase portal',
    series: ['Com contraste', 'Sem contraste'],
    rotulos: {
      'biliary duct dilatation': r('Dilatação das vias biliares', 'Colédoco e vias intra-hepáticas dilatados acima do cálculo.',
        'O colédoco normal mede até 6 a 7 mm, um pouco mais em idosos e colecistectomizados. Acima de um cálculo impactado, a bile não escoa e as vias dilatam de baixo para cima: primeiro o colédoco, depois as vias dentro do fígado, que aparecem como canais escuros ao lado dos ramos portais.',
        'Dilatação das vias com o ducto pancreático também dilatado (sinal do duplo ducto) sugere obstrução na papila, por cálculo ou tumor.'),
      'renal cysts': r('Cistos renais', 'Cistos simples nos rins, achado incidental.',
        'Cistos renais simples têm conteúdo de água, paredes finas e não realçam. São muito comuns após os 50 anos e não precisam de seguimento quando preenchem esses critérios (Bosniak I). Não exigem seguimento quando têm parede fina e conteúdo homogêneo de água.'),
      'umbilical hernia': r('Hérnia umbilical', 'Pequeno defeito na parede com gordura herniada.',
        'Achado incidental comum em obesos e multíparas. Merece menção porque pode encarcerar, sobretudo quando contém alças. Hérnias da parede são achados comuns na TC e entram no laudo porque podem encarcerar. Quando contêm alça intestinal com sinais de sofrimento, passam a ser a urgência.'),
      stone: r('Cálculo no colédoco intrapancreático', 'Foco denso dentro do colédoco, na porção que atravessa a cabeça do pâncreas.',
        'O cálculo desce da vesícula e para na porção distal do colédoco, a mais estreita, dentro da cabeça do pâncreas. Na TC sem contraste ele é mais fácil de ver como foco denso cercado pela bile mais escura — o sinal do alvo. Muitos cálculos, porém, são isodensos à bile e só a colangiorressonância ou a ecoendoscopia mostram.',
        'Cálculo isodenso pode ser invisível; dilatação das vias sem causa aparente pede colangiorressonância.'),
    },
    achados: [
      'Cálculo no colédoco intrapancreático.',
      'Dilatação do colédoco e das vias biliares intra-hepáticas.',
      'Cistos renais simples e hérnia umbilical incidentais.',
    ],
    armadilhas: [
      'A TC tem sensibilidade limitada para cálculos biliares; a colangiorressonância e a ecoendoscopia são melhores.',
      'Febre, icterícia e dor indicam colangite e drenagem urgente.',
      'Colédoco discretamente dilatado em idoso ou colecistectomizado pode ser normal.',
    ],
    conduta: 'Colangiopancreatografia retrógrada endoscópica com papilotomia e retirada do cálculo, antibiótico se houver colangite e colecistectomia posterior.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Mulher de 58 anos, costureira.',
      queixa: 'Pele e olhos amarelos, urina escura e dor no lado direito alto da barriga.',
      historia: 'Há três dias tem dor em cólica no hipocôndrio direito e epigástrio, irradiada para as costas, seguida de olhos amarelos, urina cor de coca-cola e fezes claras. Tem coceira no corpo. Nega perda de peso e febre alta.',
      antecedentes: [
        'Pessoais: colelitíase conhecida há cinco anos, sem cirurgia',
        'Gestacionais: três gestações',
        'Familiares: mãe operada da vesícula',
        'Hábitos: obesidade e sedentarismo',
      ],
      vitais: { pa: '132 × 82 mmHg', fc: '88 bpm', fr: '16 irpm', satO2: '98% em ar ambiente', temp: '37,4 °C' },
      exame: [
        'Icterícia de pele e mucosas',
        'Dor leve à palpação do hipocôndrio direito',
        'Bilirrubina direta e fosfatase alcalina elevadas',
        'Vesícula não palpável',
      ],
      pedido: 'Icterícia obstrutiva com cólica biliar em paciente com colelitíase: a pergunta é o local e a causa da obstrução.',
      pergunta: 'TC de abdome. Qual é o achado que responde à pergunta clínica?',
      achado: 'Cálculo no colédoco distal',
      veredito: 'Coledocolitíase no colédoco intrapancreático com dilatação das vias biliares',
      correlacao: 'Um cálculo saiu da vesícula, desceu pelo cístico e ficou preso na parte mais estreita do colédoco, dentro da cabeça do pâncreas. A bile parou de chegar ao intestino — fezes claras — e voltou para o sangue — icterícia, urina escura e coceira. A cólica com vesícula não palpável favorece cálculo, ao contrário do tumor, que dá icterícia indolor e vesícula palpável.',
      distratores: [
        d('Adenocarcinoma da cabeça do pâncreas', 'Também obstrui o colédoco distal, mas com icterícia indolor, emagrecimento e vesícula palpável, e mostra massa hipoatenuante na cabeça do pâncreas.'),
        d('Colangiocarcinoma hilar', 'Dilata só as vias intra-hepáticas, com colédoco normal, porque a obstrução fica na confluência dos ductos hepáticos. A dilatação pararia no hilo, sem cálculo no colédoco distal.'),
        d('Hepatite aguda viral', 'Causa icterícia com transaminases muito altas, sem dilatação das vias biliares e sem cálculo no colédoco. As vias biliares ficariam finas, e o padrão laboratorial seria de transaminases muito altas.'),
      ],
    },
  },

  'metastases-hepaticas': {
    tema: 'Fígado e vias biliares',
    titulo: 'Câncer de cólon perfurado com metástases hepáticas',
    resumo: 'Massa anular do cólon descendente com coleção pericólica, dilatação do cólon a montante, linfonodos mesentéricos e lesões hepáticas hipoatenuantes.',
    protocolo: 'TC de abdome com contraste, fases portal e tardia',
    series: ['Fase portal', 'Fase tardia'],
    rotulos: {
      'hepatic hypoenhancing lesions': r('Metástases hepáticas', 'Várias lesões no fígado que realçam menos que o parênquima.',
        'O fígado recebe o sangue do intestino pela veia porta, e é para lá que as células do câncer colorretal vão primeiro. As metástases realçam menos que o fígado na fase portal e aparecem como lesões escuras, às vezes com halo periférico. São o fator que mais pesa no prognóstico do câncer colorretal.',
        'Metástases colorretais restritas ao fígado podem ser ressecadas com intenção curativa; descreva número, tamanho e segmentos.'),
      'splaying of the portal vein': r('Ramo portal afastado', 'Um ramo da veia porta direita afastado por uma metástase.',
        'Lesões grandes deslocam os vasos sem invadi-los. A relação das metástases com os ramos portais e as veias hepáticas define se elas podem ser ressecadas mantendo fígado suficiente. Isso ajuda a separar tumor de outras lesões que infiltram os vasos.'),
      'proximal colonic dilatation': r('Cólon dilatado a montante', 'Cólon antes do tumor dilatado até 7,5 cm.',
        'O tumor anular estreita a luz e o cólon antes dele dilata. O ceco, com parede mais fina, é o que mais sofre: acima de 10 a 12 cm, o risco de perfuração aumenta. A dilatação antes do tumor indica que a luz está quase fechada e que o paciente pode obstruir a qualquer momento.'),
      'irregular annular mass': r('Massa anular do cólon descendente', 'Espessamento irregular e assimétrico que estreita a luz — a lesão em maçã mordida.',
        'O adenocarcinoma de cólon cresce em volta da parede e estreita a luz como um anel, com bordas irregulares em ombro. Do lado esquerdo, onde as fezes são mais sólidas, causa obstrução e alteração do hábito intestinal.'),
      'pericolic collection': r('Coleção pericólica', 'Coleção multiloculada ao lado do tumor — perfuração.',
        'O tumor pode perfurar no ponto da lesão, por necrose, formando uma coleção junto ao cólon. Perfuração tumoral piora o prognóstico e muda a cirurgia. Coleção junto ao tumor sugere perfuração contida, que muda o estadiamento e pode exigir drenagem antes da cirurgia.'),
      'mesenteric lymph nodes': r('Linfonodos mesentéricos', 'Linfonodos aumentados no mesentério do cólon.',
        'Linfonodos ao longo dos vasos que drenam o segmento do tumor indicam disseminação linfática e fazem parte do estadiamento. Linfonodos no trajeto da drenagem do tumor sugerem disseminação regional. O número de linfonodos acometidos define o estádio e a indicação de quimioterapia depois da cirurgia.'),
    },
    achados: [
      'Massa anular irregular do cólon descendente com espessamento assimétrico e estreitamento da luz.',
      'Coleção pericólica multiloculada adjacente, indicando perfuração tumoral.',
      'Dilatação do cólon a montante até 7,5 cm e linfonodos mesentéricos aumentados.',
      'Múltiplas lesões hepáticas hipoatenuantes — metástases — afastando ramo da veia porta direita.',
    ],
    armadilhas: [
      'Diverticulite perfurada também causa espessamento do sigmoide com coleção; espessamento curto, assimétrico e com linfonodos favorece tumor.',
      'Metástases pequenas podem ser vistas só na ressonância com contraste hepatoespecífico.',
      'Cistos e hemangiomas são comuns no fígado e não devem ser confundidos com metástases.',
    ],
    conduta: 'Ressuscitação, cirurgia de urgência pela perfuração e obstrução, colonoscopia quando possível, CEA, estadiamento torácico e discussão multidisciplinar para quimioterapia e ressecção hepática.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Homem de 66 anos, motorista aposentado.',
      queixa: 'Barriga inchada, sem evacuar há quatro dias e dor no lado esquerdo.',
      historia: 'Há seis meses as fezes ficaram mais finas e alterna prisão de ventre com diarreia. Notou sangue escuro nas fezes algumas vezes e perdeu 10 kg. Há quatro dias não evacua nem solta gases, e hoje surgiu dor forte e contínua no flanco esquerdo com febre.',
      antecedentes: [
        'Pessoais: nunca fez colonoscopia',
        'Pessoais: anemia ferropriva em exame recente',
        'Familiares: irmão com pólipos no cólon',
        'Hábitos: dieta rica em carne vermelha e embutidos, etilismo moderado',
      ],
      vitais: { pa: '108 × 66 mmHg', fc: '112 bpm', fr: '22 irpm', satO2: '96% em ar ambiente', temp: '38,3 °C' },
      exame: [
        'Abdome distendido e timpânico',
        'Dor e defesa no flanco esquerdo',
        'Fígado palpável e endurecido, com bordas irregulares',
        'CEA muito elevado',
      ],
      pedido: 'Obstrução colônica com dor localizada e febre em idoso com alteração do hábito intestinal, sangramento e emagrecimento: a pergunta é a causa e a extensão da doença.',
      pergunta: 'TC de abdome com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Câncer de cólon com metástases hepáticas',
      veredito: 'Adenocarcinoma do cólon descendente perfurado com coleção pericólica e metástases hepáticas',
      correlacao: 'Fezes finas, alteração do hábito, sangramento, anemia e emagrecimento num idoso sem colonoscopia apontam para câncer do cólon esquerdo. O tumor anular obstruiu a luz e perfurou, formando a coleção que explica a dor localizada e a febre. O fígado irregular e o CEA alto já sugeriam metástases, que a TC mostra.',
      distratores: [
        d('Diverticulite complicada com abscesso', 'Também forma coleção junto ao cólon com febre, mas o espessamento é mais longo e simétrico, com divertículos, sem massa anular, emagrecimento nem lesões hepáticas.'),
        d('Volvo do sigmoide com alça fechada', 'Dilata muito o sigmoide com redemoinho mesentérico e dois pontos de transição, sem massa na parede nem metástases no fígado. Não explicaria as metástases hepáticas.'),
        d('Colite isquêmica do cólon esquerdo', 'Espessa a parede do cólon em segmento, com dor súbita e diarreia com sangue em idoso vasculopata, sem massa anular nem lesões hepáticas.'),
      ],
    },
  },

  'adenocarcinoma-de-pancreas': {
    tema: 'Pâncreas',
    titulo: 'Adenocarcinoma da cabeça do pâncreas',
    resumo: 'Massa hipoatenuante mal definida na cabeça e no processo uncinado com dilatação do ducto pancreático e do colédoco, envolvimento da confluência portoesplênica e infiltração junto às artérias.',
    protocolo: 'TC de abdome com contraste, fase portal, axial e coronal',
    series: ['Axial', 'Coronal'],
    rotulos: {
      nodes: r('Linfonodos peripancreáticos', 'Linfonodos limítrofes acima da massa, até o hilo hepático.',
        'Linfonodos que acompanham a drenagem do pâncreas entram no estadiamento. Mesmo de tamanho limítrofe, podem conter tumor, e sua ressecção faz parte da cirurgia. Linfonodos à distância contam como metástase e contraindicam a cirurgia.'),
      pancreas: r('Ducto pancreático dilatado', 'O ducto de Wirsung dilatado no corpo e na cauda.',
        'O tumor na cabeça obstrui o ducto pancreático, que dilata a montante, e o parênquima do corpo e da cauda atrofia. Ducto dilatado com corte abrupto numa massa é sinal forte de adenocarcinoma.'),
      'common bile duct': r('Colédoco dilatado', 'O colédoco também dilatado até a massa — o sinal do duplo ducto.',
        'O colédoco atravessa a cabeça do pâncreas antes de chegar à papila. A massa o comprime, e os dois ductos dilatados convergindo para o mesmo ponto formam o duplo ducto, que sugere tumor da cabeça do pâncreas ou da papila.',
        'O duplo ducto também ocorre em cálculo impactado na papila; a massa hipoatenuante faz a diferença.'),
      'Narrowing/distortion': r('Confluência portoesplênica estreitada', 'A união das veias esplênica e mesentérica superior estreitada e deformada.',
        'O tumor que envolve e deforma a veia mesentérica superior e a confluência com a porta pode exigir ressecção venosa junto com o pâncreas. O grau de contato com os vasos define se o tumor é ressecável, limítrofe ou irressecável.'),
      haziness: r('Infiltração em volta da artéria mesentérica', 'Densificação da gordura em volta da mesentérica superior.',
        'A gordura em volta da artéria mesentérica superior deve ser limpa. Densificação ou tecido envolvendo mais de 180 graus da artéria indica invasão e torna o tumor irressecável. O pâncreas é um tumor que se espalha pelos nervos em volta dos vasos.'),
      mass: r('Massa hipoatenuante na cabeça', 'Lesão mal definida, escura em relação ao pâncreas que realça.',
        'O adenocarcinoma de pâncreas é muito fibroso e pouco vascularizado, por isso realça menos que o pâncreas normal e aparece escuro na fase pancreática e portal. As bordas são mal definidas porque o tumor infiltra a gordura em volta.'),
      'common hepatic haziness': r('Infiltração junto à artéria hepática comum', 'Densificação em volta da artéria hepática comum.',
        'A extensão do tumor para a artéria hepática comum também pesa na ressecabilidade. A descrição de cada artéria — mesentérica superior, tronco celíaco e hepática comum — é obrigatória no laudo.'),
    },
    achados: [
      'Massa hipoatenuante mal definida na cabeça do pâncreas e no processo uncinado.',
      'Dilatação do ducto pancreático e do colédoco convergindo para a massa — duplo ducto.',
      'Estreitamento e deformação da confluência portoesplênica e da veia mesentérica superior.',
      'Densificação em volta da mesentérica superior e da hepática comum e linfonodos limítrofes até o hilo hepático.',
    ],
    armadilhas: [
      'Cerca de 10% dos adenocarcinomas são isoatenuantes; dilatação do ducto com corte abrupto sem massa visível deve ser investigada.',
      'Pancreatite focal pode imitar tumor; o sinal do ducto penetrante favorece pancreatite.',
      'Leia os vasos um a um: o contato arterial é o que decide a ressecção.',
    ],
    conduta: 'Estadiamento com TC de tórax, CA 19-9, ecoendoscopia com biópsia, drenagem biliar se necessário e discussão multidisciplinar entre cirurgia de Whipple e quimioterapia neoadjuvante conforme a ressecabilidade.',
    vinheta: {
      cenario: 'Ambulatório de gastroenterologia',
      identificacao: 'Homem de 68 anos, contador aposentado.',
      queixa: 'Ficou amarelo sem dor e emagreceu muito nos últimos dois meses.',
      historia: 'Há um mês a esposa notou os olhos amarelos. Ele não sente cólica, mas tem coceira intensa, urina escura e fezes esbranquiçadas. Perdeu 12 kg em dois meses, tem dor surda nas costas que piora deitado e foi diagnosticado com diabetes há três meses.',
      antecedentes: [
        'Pessoais: diabetes de início recente, sem obesidade',
        'Pessoais: pancreatite crônica não conhecida',
        'Familiares: irmão com câncer de pâncreas',
        'Hábitos: tabagista de 40 maços-ano',
      ],
      vitais: { pa: '124 × 76 mmHg', fc: '84 bpm', fr: '16 irpm', satO2: '97% em ar ambiente', temp: '36,6 °C' },
      exame: [
        'Icterícia intensa com escoriações por coceira',
        'Vesícula palpável e indolor — sinal de Courvoisier',
        'Emagrecimento evidente',
        'CA 19-9 muito elevado',
      ],
      pedido: 'Icterícia indolor progressiva com vesícula palpável, emagrecimento e diabetes de início recente em tabagista: a pergunta é a causa da obstrução e se o tumor é ressecável.',
      pergunta: 'TC de abdome com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Adenocarcinoma da cabeça do pâncreas',
      veredito: 'Adenocarcinoma da cabeça do pâncreas com duplo ducto e envolvimento venoso e arterial',
      correlacao: 'Icterícia indolor com vesícula palpável é o sinal de Courvoisier: obstrução lenta do colédoco por tumor, e não por cálculo, que causa dor e vesícula fibrosada. Diabetes de início recente, emagrecimento, dor nas costas, tabagismo e irmão com a doença completam o quadro. A TC mostra a massa escura na cabeça, os dois ductos dilatados e o envolvimento vascular que define a ressecabilidade.',
      distratores: [
        d('Coledocolitíase com icterícia obstrutiva', 'Dá icterícia com cólica biliar e cálculo visível no colédoco, sem massa na cabeça do pâncreas nem emagrecimento importante. Não haveria massa na cabeça do pâncreas.'),
        d('Pancreatite autoimune focal', 'Também aumenta a cabeça do pâncreas e causa icterícia, mas com halo hipodenso, IgG4 elevada e resposta ao corticoide. Responderia a corticoide, com IgG4 elevada e sem invasão vascular.'),
        d('Ampuloma da papila duodenal', 'Causa duplo ducto e icterícia, mas a lesão está na papila, dentro do duodeno, e não na cabeça do pâncreas com envolvimento vascular.'),
      ],
    },
  },
}
