import type { DistratorClinico, VinhetaClinica } from './casos-clinicos'

const d = (nome: string, porQue: string): DistratorClinico => ({ nome, porQue })

/** Vinhetas da segunda leva — trauma, UTI e pediatria. Pacientes fictícios. */
export const VINHETAS_LEVA_2_TRAUMA_PEDIATRIA: Record<string, VinhetaClinica> = {
  'fraturas-de-costelas': {
    cenario: 'Sala de trauma',
    identificacao: 'Homem de 58 anos, pedreiro, trazido pelo SAMU após queda de andaime de 3 metros.',
    queixa: 'Dor intensa no lado direito do tórax, que piora ao respirar e ao tossir.',
    historia: 'Caiu de lado sobre uma viga de madeira há uma hora. Não perdeu a consciência. Desde então sente dor em pontada na lateral direita do tórax, respira curto para não doer e não consegue tossir. Nega dor abdominal ou cervical. Não usa anticoagulante.',
    antecedentes: ['Hipertensão em uso de hidroclorotiazida', 'Tabagismo de 30 maços-ano', 'Etilismo social', 'Sem cirurgias prévias'],
    vitais: { pa: '138 × 86 mmHg', fc: '106 bpm', fr: '26 irpm', satO2: '93% em ar ambiente', temp: '36,4 °C' },
    exame: ['Escoriação e hematoma na face lateral do hemitórax direito', 'Crepitação óssea à palpação do 5º ao 8º arcos na linha axilar média', 'Murmúrio discretamente reduzido na base direita', 'Sem movimento paradoxal visível da parede'],
    pedido: 'Trauma torácico contuso com crepitação costal: a pergunta é quantas costelas quebraram e se há pneumotórax ou hemotórax associado.',
    pergunta: 'Radiografia de tórax em PA. Qual é o achado que responde à pergunta clínica?',
    achado: 'Fraturas costais em série',
    veredito: 'Fraturas de costelas consecutivas na linha axilar, com pequeno hemotórax associado',
    correlacao: 'Queda lateral sobre uma viga, dor pleurítica localizada e crepitação sob os dedos contam a fratura antes do filme. A radiografia mostra os degraus na cortical de arcos consecutivos na curva lateral — o ponto de maior tensão do arco — e o velamento basal do sangue que desceu para a pleura. O que decide a conduta é o que está em volta: pneumotórax, hemotórax e o número de traços por costela.',
    distratores: [
      d('Contusão pulmonar isolada', 'A contusão aparece como opacidade mal definida no parênquima sob o impacto, sem interrupção da cortical. Aqui os arcos têm degraus nítidos em sequência — o osso quebrou —, e a opacidade basal é pleural. A contusão pode coexistir, mas não explica a crepitação óssea.'),
      d('Pneumotórax traumático', 'Faria linha pleural visceral com ausência de trama vascular além dela e hipertimpanismo. O paciente tem murmúrio apenas reduzido na base e o filme não mostra linha pleural: há fraturas e sangue, não ar. Um pneumotórax pequeno precisa ser procurado no ápice, mas não é o achado dominante.'),
      d('Tórax instável com respiração paradoxal', 'Exige três ou mais costelas com dois traços cada, liberando um segmento que afunda na inspiração. As fraturas deste caso têm um traço por arco e a parede não se move paradoxalmente ao exame. São fraturas em série, não um segmento livre — a analgesia muda, a indicação cirúrgica não.'),
    ],
  },
  'contusao-pulmonar': {
    cenario: 'Pronto-socorro',
    identificacao: 'Mulher de 24 anos, motorista, vítima de colisão frontal há 3 horas com airbag acionado.',
    queixa: 'Dor no peito do lado esquerdo e tosse com raias de sangue.',
    historia: 'Batia a 70 km/h num poste; o airbag abriu e o cinto a segurou. Levou uma pancada no hemitórax esquerdo contra a porta. Nas últimas duas horas surgiu tosse com raias de sangue e a falta de ar aumentou um pouco. Nega perda de consciência, dor abdominal ou cervical.',
    antecedentes: ['Asma leve na infância', 'Sem medicamentos contínuos', 'Nega alergias', 'Gestação descartada por beta-hCG negativo'],
    vitais: { pa: '118 × 72 mmHg', fc: '112 bpm', fr: '24 irpm', satO2: '91% em ar ambiente', temp: '36,6 °C' },
    exame: ['Marca do cinto de segurança no tórax', 'Dor à palpação dos arcos costais esquerdos', 'Estertores crepitantes no terço médio do hemitórax esquerdo', 'Sem enfisema subcutâneo'],
    pedido: 'Trauma de alta energia com hipoxemia e hemoptise: a pergunta é se há lesão parenquimatosa sob o ponto de impacto.',
    pergunta: 'Radiografia de tórax em AP. Qual é o achado que responde à pergunta clínica?',
    achado: 'Contusão pulmonar',
    veredito: 'Contusão pulmonar — opacidade não segmentar sob o impacto, surgida nas primeiras horas',
    correlacao: 'A energia da colisão atravessou a parede e rompeu capilares alveolares: o sangue e o edema encheram os alvéolos exatamente onde o tórax bateu na porta. O filme mostra a opacidade mal definida, que não respeita fissuras nem segmentos, surgida em poucas horas. A hemoptise e a hipoxemia são o mesmo sangue visto por outra janela; em 3 a 10 dias ela deve clarear.',
    distratores: [
      d('Pneumonia aspirativa pós-trauma', 'Ocupa segmentos dependentes e surge em 24 a 48 horas, geralmente em quem rebaixou a consciência. A paciente está lúcida, a opacidade está sob o ponto do impacto e apareceu em três horas — o tempo e a topografia são de contusão, não de aspiração.'),
      d('Hemotórax traumático', 'O sangue pleural faz menisco em pé ou véu homogêneo em decúbito, com vasos visíveis através e sem estertores. Aqui a opacidade é parenquimatosa, heterogênea, apaga os vasos dentro dela e vem com estertores e hemoptise — está no pulmão, não na pleura.'),
      d('Laceração com hematoma pulmonar', 'A laceração forma uma cavidade ou um nódulo redondo e denso, cheio de sangue, às vezes com nível, e demora semanas para sumir. A opacidade deste caso é mal definida e difusa, sem contorno redondo — é contusão. A TC separa as duas quando a radiografia não basta.'),
    ],
  },
  'ruptura-diafragmatica': {
    cenario: 'Sala de trauma',
    identificacao: 'Homem de 31 anos, motociclista, vítima de colisão com caminhão há 2 horas.',
    queixa: 'Falta de ar progressiva e dor no abdome superior esquerdo.',
    historia: 'Foi prensado entre a moto e o para-choque do caminhão, com impacto na região toracoabdominal esquerda. Chegou consciente, queixando-se de falta de ar crescente. Foi intubado por queda da saturação e passada sonda nasogástrica antes da radiografia.',
    antecedentes: ['Sem comorbidades', 'Apendicectomia na infância', 'Tabagismo social', 'Sem alergias'],
    vitais: { pa: '102 × 64 mmHg', fc: '118 bpm', fr: '28 irpm', satO2: '90% com FiO2 0,6', temp: '36,1 °C' },
    exame: ['Murmúrio abolido na metade inferior do hemitórax esquerdo', 'Ruídos hidroaéreos audíveis no hemitórax esquerdo', 'Abdome escavado e doloroso no hipocôndrio esquerdo', 'Bulhas deslocadas para a direita'],
    pedido: 'Trauma toracoabdominal esquerdo com ruídos intestinais no tórax: a pergunta é se o diafragma rompeu e se há vísceras no hemitórax.',
    pergunta: 'Radiografia de tórax em AP no leito. Qual é o achado que responde à pergunta clínica?',
    achado: 'Ruptura diafragmática esquerda',
    veredito: 'Ruptura do hemidiafragma esquerdo — estômago e alças no tórax com sonda gástrica acima do diafragma',
    correlacao: 'A compressão abdominal brusca rasgou o hemidiafragma esquerdo e a pressão negativa do tórax aspirou as vísceras: ruídos intestinais no tórax, abdome escavado e bulhas desviadas contam isso ao estetoscópio. O filme mostra o estômago com gás e nível no hemitórax inferior, o contorno diafragmático perdido e a sonda nasogástrica enrolada acima de onde deveria estar a cúpula.',
    distratores: [
      d('Hemotórax maciço à esquerda', 'Opacifica o hemitórax e desvia o mediastino, mas é homogêneo, sem bolhas de gás, e a sonda gástrica fica no abdome. Aqui há gás com nível acima do diafragma e a sonda está no tórax — não é líquido, é estômago.'),
      d('Pneumotórax hipertensivo', 'Desvia o mediastino e aboliria o murmúrio, mas o hemitórax fica hiperlucente e sem trama, com o diafragma rebaixado e visível. O filme deste caso mostra estruturas com parede e nível — vísceras ocas —, não ar pleural livre; drenar ali perfuraria o estômago.'),
      d('Eventração diafragmática congênita', 'Eleva a cúpula, mas o diafragma continua como uma linha curva contínua, a sonda fica abaixo dela e não há história de trauma. Aqui o contorno diafragmático desapareceu após um trauma de alta energia, e a sonda sobe para o tórax.'),
    ],
  },
  'lesao-aortica-traumatica': {
    cenario: 'Sala de trauma',
    identificacao: 'Mulher de 45 anos, passageira de carro em colisão frontal a 100 km/h.',
    queixa: 'Dor torácica retroesternal e dor interescapular.',
    historia: 'O carro bateu de frente num muro na rodovia; ela estava de cinto. Chegou consciente, com dor no meio do peito que irradia para as costas entre as escápulas. O motorista morreu no local. Nega doenças prévias.',
    antecedentes: ['Hipotireoidismo em uso de levotiroxina', 'Sem cirurgias', 'Nega tabagismo', 'Sem alergias'],
    vitais: { pa: '148 × 90 mmHg no braço direito e 124 × 80 no esquerdo', fc: '104 bpm', fr: '22 irpm', satO2: '95% em ar ambiente', temp: '36,3 °C' },
    exame: ['Marca do cinto no tórax', 'Pulsos femorais presentes, mais fracos que os radiais', 'Sopro sistólico interescapular discreto', 'Ausculta pulmonar simétrica'],
    pedido: 'Desaceleração de alta energia com dor interescapular e diferença de pressão entre os braços: a pergunta é se o mediastino tem sinais de hematoma.',
    pergunta: 'Radiografia de tórax em AP. Qual é o achado que responde à pergunta clínica?',
    achado: 'Mediastino alargado pós-trauma',
    veredito: 'Mediastino superior alargado com botão aórtico apagado e traqueia desviada — suspeita de lesão aórtica traumática',
    correlacao: 'Desaceleração brusca a 100 km/h, dor interescapular, assimetria de pressão entre os braços e pulsos femorais fracos: a aorta rasgou no istmo e o sangue está contido na adventícia. O filme mostra o hematoma que isso produz — mediastino superior largo, botão aórtico sem contorno e traqueia empurrada para a direita. Nenhum sinal é definitivo; todos juntos mandam a paciente para a angiotomografia agora.',
    distratores: [
      d('Magnificação pela técnica AP', 'O filme AP em decúbito alarga o mediastino em qualquer pessoa, e é a explicação mais comum. Mas a técnica não apaga o botão aórtico nem desvia a traqueia, e não explica a diferença de pressão entre os braços. Com esse mecanismo e esses sinais, atribuir à técnica é o erro que mata.'),
      d('Hematoma por fratura esternal', 'A fratura do esterno sangra para o mediastino anterior e alarga a silhueta, mas preserva o botão aórtico e não desvia a traqueia nem assimetriza pulsos. Aqui há sinais que apontam para a aorta — a TC separa os dois, e ambos podem coexistir.'),
      d('Timo residual ou bócio mergulhante', 'Massas mediastinais anteriores antigas alargam a sombra superior, mas estão lá antes do trauma, têm bordas nítidas e não explicam dor interescapular com assimetria de pressão. O contexto agudo é de sangramento, não de massa.'),
    ],
  },
  'sinal-do-sulco-profundo': {
    cenario: 'Unidade de terapia intensiva',
    identificacao: 'Homem de 67 anos, em ventilação mecânica por pneumonia grave, com DPOC.',
    queixa: 'Queda súbita da saturação e aumento da pressão de pico no ventilador.',
    historia: 'Intubado há quatro dias por pneumonia com PEEP de 12. Há 30 minutos, após passagem de cateter subclávio esquerdo, a saturação caiu de 94% para 85% e a pressão de pico subiu de 28 para 38 cmH2O. O filme é feito no leito, em decúbito dorsal.',
    antecedentes: ['DPOC com enfisema', 'Pneumonia comunitária grave', 'Passagem de cateter subclávio esquerdo há 30 minutos', 'Hipertensão'],
    vitais: { pa: '96 × 58 mmHg', fc: '124 bpm', fr: '22 irpm (ventilação mecânica)', satO2: '85% com FiO2 0,6', temp: '37,8 °C' },
    exame: ['Murmúrio reduzido no hemitórax esquerdo', 'Hipertimpanismo à percussão anterior esquerda', 'Enfisema subcutâneo discreto na região infraclavicular esquerda', 'Traqueia centrada'],
    pedido: 'Piora súbita após punção subclávia em paciente ventilado: a pergunta é se há pneumotórax no filme em decúbito, onde o ar não vai para o ápice.',
    pergunta: 'Radiografia de tórax em AP em decúbito dorsal. Qual é o achado que responde à pergunta clínica?',
    achado: 'Pneumotórax com sulco profundo',
    veredito: 'Pneumotórax em decúbito — sinal do sulco profundo com hemidiafragma nítido',
    correlacao: 'Punção subclávia, enfisema subcutâneo, hipertimpanismo anterior e piora súbita no ventilador: a pleura foi perfurada. Deitado, o ar sobe para a frente e para baixo, e o filme mostra o seio costofrênico esquerdo profundo e escuro, com o hemidiafragma mais nítido que o direito — não há linha no ápice porque o ápice não é o ponto mais alto. Com pressão positiva, esse pneumotórax cresce: drenagem agora.',
    distratores: [
      d('Hiperinsuflação do enfisema', 'O enfisema escurece os dois pulmões e achata as duas cúpulas de forma simétrica. Aqui a lucência é unilateral, concentrada no seio costofrênico esquerdo, e surgiu após a punção com enfisema subcutâneo — assimetria aguda é pneumotórax até prova contrária.'),
      d('Intubação seletiva à direita', 'O tubo no brônquio direito colapsa o pulmão esquerdo, que fica branco, e aumenta a pressão de pico. O hemitórax esquerdo deste caso está mais escuro, não mais branco, e há hipertimpanismo — o oposto da atelectasia.'),
      d('Bolha enfisematosa gigante', 'A bolha é uma área sem vasos delimitada por parede côncava fina, geralmente apical e antiga. O achado deste caso é o recesso costofrênico anormalmente profundo, surgido agora, em decúbito, após punção. Comparar com o filme anterior resolve a dúvida.'),
    ],
  },
  'sonda-nasogastrica-mal-posicionada': {
    cenario: 'Enfermaria de neurologia',
    identificacao: 'Mulher de 79 anos, pós-AVC isquêmico extenso há 5 dias, com disfagia grave.',
    queixa: 'Radiografia de controle após passagem de sonda para dieta enteral.',
    historia: 'Internada por AVC de artéria cerebral média esquerda, com afasia e disfagia. A fonoaudiologia contraindicou dieta oral. A enfermagem passou sonda nasoenteral há uma hora; a paciente tossiu durante a passagem, mas se acalmou. Nenhuma dieta foi iniciada ainda.',
    antecedentes: ['AVC isquêmico há 5 dias', 'Fibrilação atrial anticoagulada', 'Diabetes tipo 2', 'Reflexo de tosse diminuído'],
    vitais: { pa: '142 × 84 mmHg', fc: '88 bpm irregular', fr: '20 irpm', satO2: '94% em ar ambiente', temp: '36,8 °C' },
    exame: ['Hemiparesia direita e afasia', 'Sonda fixada na narina direita a 55 cm', 'Estertores discretos na base direita', 'Ausculta epigástrica ao injetar ar considerada duvidosa pela enfermagem'],
    pedido: 'Confirmação da posição da sonda antes de iniciar a dieta: a pergunta é onde está a ponta e se o trajeto é esofágico.',
    pergunta: 'Radiografia de tórax e abdome superior em AP. Qual é o achado que responde à pergunta clínica?',
    achado: 'Sonda em trajeto brônquico',
    veredito: 'Sonda nasogástrica no brônquio, com a ponta projetada sobre o parênquima pulmonar',
    correlacao: 'Paciente sem reflexo de tosse eficaz, passagem às cegas, tosse durante o procedimento e ausculta epigástrica duvidosa: a sonda pode ter ido para a traqueia sem que ninguém percebesse. O filme mostra o trajeto que denuncia — a sonda deixa a linha média na altura da carina, segue um brônquio principal e termina sobre o pulmão, sem nunca cruzar o diafragma. Dieta ali seria pneumonia.',
    distratores: [
      d('Sonda enrolada no esôfago', 'A sonda que enrola no esôfago fica na linha média, forma alças sobre o mediastino e não cruza o diafragma, mas nunca se desvia lateralmente para o campo pulmonar. Aqui ela sai da linha média na carina e segue o brônquio — está na via aérea.'),
      d('Ponta no fundo gástrico', 'Seria a posição correta: sonda mediana que cruza o diafragma e vira para a esquerda sob a cúpula. A ponta deste caso está acima do diafragma, lateralizada, sobre o parênquima — não há curva gástrica.'),
      d('Sonda na hérnia hiatal', 'Uma hérnia hiatal leva o estômago para trás do coração, e a ponta fica retrocardíaca acima do diafragma — mas na linha média, com bolha gástrica ao redor. O trajeto deste caso se desvia na carina e acompanha o brônquio, sem bolha: não é estômago.'),
    ],
  },
  'cateter-central-mal-posicionado': {
    cenario: 'Unidade de terapia intensiva',
    identificacao: 'Homem de 63 anos, em choque séptico de foco abdominal, pós-operatório de colectomia.',
    queixa: 'Radiografia de controle após passagem de cateter venoso central.',
    historia: 'Precisou de noradrenalina em dose crescente e o residente passou cateter venoso central pela subclávia direita, sem ultrassom, com fluxo sanguíneo adequado nas três vias. Antes de iniciar a noradrenalina pelo cateter, foi pedida radiografia. O paciente refere dor no pescoço à direita ao infundir soro pela via distal.',
    antecedentes: ['Perfuração de sigmoide com peritonite', 'Colectomia há 1 dia', 'Diabetes tipo 2', 'Doença renal crônica estágio 3'],
    vitais: { pa: '88 × 52 mmHg em noradrenalina periférica', fc: '118 bpm', fr: '24 irpm', satO2: '95% com cateter nasal', temp: '38,4 °C' },
    exame: ['Cateter subclávio direito fixado', 'Dor e sensação de "frio" no pescoço direito ao infundir', 'Ausculta pulmonar simétrica', 'Sem enfisema subcutâneo'],
    pedido: 'Controle de cateter central antes de infundir vasopressor: a pergunta é onde está a ponta e se houve complicação da punção.',
    pergunta: 'Radiografia de tórax em AP. Qual é o achado que responde à pergunta clínica?',
    achado: 'Cateter com ponta fora da cava',
    veredito: 'Cateter venoso central mal posicionado, com a ponta fora da veia cava superior',
    correlacao: 'Fluxo sanguíneo nas vias não prova posição; a dor e o frio no pescoço ao infundir diziam que o líquido ia para cima. O filme mostra o cateter tomando um trajeto anômalo em vez de descer pela cava superior até a altura da carina. Vasopressor infundido fora da cava pode extravasar ou chegar em concentração errada — o cateter deve ser reposicionado antes de qualquer droga.',
    distratores: [
      d('Ponta na junção cavoatrial', 'É a posição ideal ou aceitável: a ponta desce paralela à borda direita do mediastino até a altura da carina ou pouco abaixo. O cateter deste caso não segue esse trajeto, e a dor cervical ao infundir não aconteceria com a ponta na cava.'),
      d('Pneumotórax pós-punção', 'É a complicação mecânica que a radiografia de controle procura primeiro, mas a ausculta é simétrica, não há enfisema subcutâneo e o filme não mostra linha pleural. O problema deste cateter é onde a ponta foi parar, não o que a agulha perfurou.'),
      d('Punção arterial inadvertida', 'O cateter na subclávia arterial segue a aorta e a ponta fica à esquerda da coluna, com sangue pulsátil e vermelho-vivo. Aqui o fluxo era venoso e o trajeto anômalo segue uma veia — a gasometria da via e a curva de pressão confirmam.'),
    ],
  },
  'atelectasia-por-rolha-de-muco': {
    cenario: 'Unidade de terapia intensiva',
    identificacao: 'Mulher de 55 anos, em ventilação mecânica após cirurgia abdominal extensa.',
    queixa: 'Dessaturação súbita e hemitórax esquerdo branco na radiografia da manhã.',
    historia: 'Segundo dia de pós-operatório de gastrectomia, ainda intubada por instabilidade. A enfermagem relata secreção muito espessa, difícil de aspirar. Na última hora a saturação caiu de 96% para 86%, sem febre nova. Não houve mudança no ventilador nem manipulação do tubo.',
    antecedentes: ['Gastrectomia total por adenocarcinoma', 'Tabagismo de 25 maços-ano', 'Hipotireoidismo', 'Sedação contínua'],
    vitais: { pa: '124 × 76 mmHg', fc: '108 bpm', fr: '18 irpm (ventilação mecânica)', satO2: '86% com FiO2 0,5', temp: '37,3 °C' },
    exame: ['Murmúrio abolido em todo o hemitórax esquerdo', 'Macicez à esquerda', 'Traqueia desviada para a esquerda à palpação', 'Tubo endotraqueal fixado a 22 cm da rima labial'],
    pedido: 'Hemitórax esquerdo opaco com murmúrio abolido em paciente com secreção espessa: a pergunta é se é colapso pulmonar ou derrame, e para que lado vai o mediastino.',
    pergunta: 'Radiografia de tórax em AP no leito. Qual é o achado que responde à pergunta clínica?',
    achado: 'Atelectasia do pulmão esquerdo',
    veredito: 'Atelectasia total do pulmão esquerdo por rolha de muco — mediastino puxado para o lado da opacidade',
    correlacao: 'Secreção espessa, queda súbita da saturação e traqueia desviada para a esquerda formam o quadro da rolha que fechou o brônquio principal: o ar distal foi absorvido e o pulmão colapsou. O filme mostra o hemitórax esquerdo branco com a traqueia, o coração e o hemidiafragma puxados para ele — perda de volume. A aspiração ou a broncoscopia devem reexpandi-lo em minutos.',
    distratores: [
      d('Derrame pleural maciço à esquerda', 'Opacifica o hemitórax com a mesma densidade, mas empurra o mediastino para o lado oposto, porque ocupa espaço. Aqui a traqueia e o coração foram puxados para a esquerda — o lado branco perdeu volume. O sentido do desvio é o diagnóstico.'),
      d('Pneumonia do lobo inferior esquerdo', 'Consolida um lobo, com broncograma e sem perda de volume importante, e costuma vir com febre. O hemitórax inteiro está opaco, sem broncograma, com desvio mediastinal ipsilateral e sem febre nova — é colapso, não consolidação.'),
      d('Intubação seletiva no brônquio direito', 'Também colapsa o pulmão esquerdo inteiro com desvio ipsilateral, e é a primeira coisa a conferir. Mas o tubo está a 22 cm da rima, não houve manipulação, e há secreção espessa difícil de aspirar — se a ponta estiver acima da carina no filme, a causa é a rolha.'),
    ],
  },
  bronquiolite: {
    cenario: 'Pronto-socorro pediátrico',
    identificacao: 'Lactente de 4 meses, sexo masculino, nascido a termo, em aleitamento materno.',
    queixa: 'Coriza há 3 dias, tosse e cansaço para mamar desde ontem.',
    historia: 'Começou com coriza e espirros; o irmão de 3 anos, que vai à creche, está resfriado. Desde ontem tosse muito, respira rápido e cansa durante as mamadas, mamando menos da metade do habitual. Febre de 37,9 °C. Nega engasgos ou episódios de apneia.',
    antecedentes: ['Parto vaginal a termo, 3.200 g, sem intercorrências', 'Vacinação em dia', 'Irmão frequenta creche', 'Pais não fumantes'],
    vitais: { pa: 'não aferida', fc: '156 bpm', fr: '58 irpm', satO2: '92% em ar ambiente', temp: '37,9 °C' },
    exame: ['Tiragem subcostal e batimento de asa nasal', 'Sibilos e estertores finos difusos bilaterais', 'Expiração prolongada', 'Fígado palpável a 2 cm do rebordo por rebaixamento diafragmático'],
    pedido: 'O quadro é típico e a radiografia não é rotina; foi pedida porque a saturação caiu e havia dúvida sobre pneumonia associada.',
    pergunta: 'Radiografia de tórax em AP. Qual é o achado que responde à pergunta clínica?',
    achado: 'Bronquiolite viral aguda',
    veredito: 'Bronquiolite — hiperinsuflação com espessamento peribrônquico e atelectasias lineares',
    correlacao: 'Lactente de 4 meses, irmão resfriado, pródromo de coriza e depois sibilos, estertores e esforço respiratório: o vírus inflamou os bronquíolos. O filme mostra o ar aprisionado — cúpulas baixas, pulmões grandes — com paredes brônquicas espessas ao redor dos hilos e pequenas atelectasias lineares que migram. Não há consolidação lobar, e o antibiótico não entra.',
    distratores: [
      d('Pneumonia bacteriana lobar', 'Faria consolidação densa de um lobo, febre alta e toxemia. As opacidades deste filme são lineares e subsegmentares — rolhas de muco que colapsam pequenas áreas —, sobre um pulmão hiperinsuflado. Chamar atelectasia de pneumonia é o erro que expõe o lactente a antibiótico sem indicação.'),
      d('Corpo estranho aspirado', 'Produz hiperinsuflação unilateral que não esvazia na expiração, com desvio do mediastino. A hiperinsuflação deste caso é bilateral e simétrica, com pródromo viral e contato doméstico — e um lactente de 4 meses raramente pega objetos.'),
      d('Asma na primeira crise', 'Sibilância com hiperinsuflação também ocorre na asma, mas não aos 4 meses de vida e não com pródromo de coriza e estertores finos difusos. Abaixo de 2 anos, o primeiro episódio de sibilância viral é bronquiolite.'),
    ],
  },
  'corpo-estranho-aspirado': {
    cenario: 'Pronto-socorro pediátrico',
    identificacao: 'Menino de 2 anos, trazido pela mãe após episódio de engasgo em festa.',
    queixa: 'Tosse persistente e chiado desde que se engasgou comendo amendoim há 6 horas.',
    historia: 'Estava comendo amendoim na festa de aniversário quando teve um acesso súbito de tosse, ficou vermelho e sem ar por alguns segundos. A tosse melhorou, mas persiste em crises e a mãe ouve um chiado que ele nunca teve. Nega febre ou resfriado nos últimos dias.',
    antecedentes: ['Previamente hígido', 'Sem asma ou sibilância prévia', 'Vacinação em dia', 'Sem internações'],
    vitais: { pa: 'não aferida', fc: '128 bpm', fr: '34 irpm', satO2: '95% em ar ambiente', temp: '36,7 °C' },
    exame: ['Murmúrio reduzido no hemitórax direito', 'Sibilo localizado à direita, monofônico', 'Hemitórax esquerdo com ausculta normal', 'Sem esforço respiratório importante'],
    pedido: 'Engasgo testemunhado com sibilo unilateral: a pergunta é se há sinais indiretos de obstrução brônquica — ou um objeto radiopaco.',
    pergunta: 'Radiografia de tórax em inspiração e expiração. Qual é o achado que responde à pergunta clínica?',
    achado: 'Corpo estranho brônquico',
    veredito: 'Corpo estranho brônquico — aprisionamento aéreo ou objeto radiopaco na via aérea',
    correlacao: 'Engasgo testemunhado com amendoim, tosse súbita e agora um sibilo monofônico só de um lado: a história é o diagnóstico, e a broncoscopia está indicada mesmo com filme normal. A radiografia pode mostrar o objeto, quando radiopaco, ou o efeito dele — um pulmão que não esvazia na expiração e empurra o mediastino. Nunca espere a pneumonia obstrutiva para confirmar.',
    distratores: [
      d('Bronquiolite com sibilância', 'A sibilância viral é difusa, bilateral, com pródromo de coriza e febre, e a hiperinsuflação é simétrica. O sibilo deste caso é localizado e monofônico, começou num engasgo testemunhado e não há quadro viral — é obstrução focal.'),
      d('Primeira crise de asma', 'A asma faz sibilos polifônicos bilaterais que respondem ao broncodilatador, com hiperinsuflação simétrica. Sibilo unilateral e fixo, após engasgo com amendoim, não é asma — e tratar como asma atrasa a broncoscopia.'),
      d('Pneumonia do lobo médio', 'Consolidaria com febre, estertores e opacidade no filme. A criança está afebril, a ausculta mostra murmúrio reduzido com sibilo, e o evento foi agudo há 6 horas. A pneumonia vem depois, se o objeto ficar lá.'),
    ],
  },
  epiglotite: {
    cenario: 'Pronto-socorro',
    identificacao: 'Homem de 44 anos, professor, sem vacinação conhecida na infância.',
    queixa: 'Dor de garganta intensa, dificuldade para engolir a saliva e voz abafada há 12 horas.',
    historia: 'Começou com dor de garganta que piorou rapidamente; hoje não consegue engolir nem a saliva, que escorre da boca, e a voz ficou "de batata quente". Sente-se febril e prefere ficar sentado inclinado para a frente. Nega tosse. A orofaringe, vista pelo plantonista, parecia pouco alterada.',
    antecedentes: ['Diabetes tipo 2', 'Vacinação na infância desconhecida', 'Sem alergias', 'Tabagismo'],
    vitais: { pa: '134 × 84 mmHg', fc: '116 bpm', fr: '24 irpm', satO2: '94% em ar ambiente', temp: '39,1 °C' },
    exame: ['Sialorreia e voz abafada', 'Posição em tripé', 'Orofaringe com hiperemia discreta, desproporcional à dor', 'Dor intensa à palpação do osso hioide'],
    pedido: 'Odinofagia desproporcional à orofaringe com sialorreia e voz abafada: a pergunta é se há edema supraglótico, e a radiografia só é feita porque o paciente está estável e sentado.',
    pergunta: 'Radiografia lateral de pescoço. Qual é o achado que responde à pergunta clínica?',
    achado: 'Epiglotite aguda',
    veredito: 'Epiglotite — epiglote edemaciada em polegar com pregas ariepiglóticas espessadas',
    correlacao: 'Dor de garganta que não combina com a orofaringe quase normal, saliva escorrendo, voz de batata quente e posição em tripé: a doença está abaixo do que o abaixador de língua alcança. O perfil do pescoço mostra a epiglote inchada e arredondada, o polegar, estreitando a via aérea supraglótica. A via aérea é garantida antes de qualquer outra coisa.',
    distratores: [
      d('Abscesso retrofaríngeo', 'Alarga o espaço pré-vertebral, que no perfil fica mais espesso que metade do corpo vertebral em C2, e pode ter gás. A epiglote fica fina. Aqui o espaço pré-vertebral é normal e é a própria epiglote que está arredondada.'),
      d('Abscesso periamigdaliano', 'Causa trismo, voz abafada e dor intensa, mas a orofaringe mostra o abaulamento do pilar e o desvio da úvula. A orofaringe deste paciente está quase normal — o problema está mais abaixo, na supraglote.'),
      d('Angioedema de via aérea', 'Incha lábios, língua e laringe em minutos, sem febre, frequentemente com IECA ou alergia. O paciente tem febre alta, evolução de 12 horas e toxemia — infecção, não angioedema.'),
    ],
  },
  crupe: {
    cenario: 'Pronto-socorro pediátrico',
    identificacao: 'Menina de 18 meses, levada de madrugada pelos pais.',
    queixa: 'Tosse "de cachorro" e barulho ao respirar que começaram à noite.',
    historia: 'Estava resfriada há dois dias, com coriza e febre baixa. Acordou às 2 horas com uma tosse rouca, metálica, "como latido", e um ruído agudo ao puxar o ar. Chora com voz rouca. Nega engasgo, e bebe líquidos normalmente, sem babar.',
    antecedentes: ['Parto a termo sem intercorrências', 'Vacinação em dia', 'Episódio semelhante mais leve aos 12 meses', 'Frequenta creche'],
    vitais: { pa: 'não aferida', fc: '142 bpm', fr: '40 irpm', satO2: '96% em ar ambiente', temp: '38,0 °C' },
    exame: ['Estridor inspiratório em repouso, que piora ao chorar', 'Tosse ladrante e rouquidão', 'Tiragem supraesternal leve', 'Bom estado geral, sem sialorreia'],
    pedido: 'Estridor com tosse ladrante; a radiografia foi feita porque era o segundo episódio e havia dúvida sobre estenose subglótica.',
    pergunta: 'Radiografia frontal e lateral de pescoço. Qual é o achado que responde à pergunta clínica?',
    achado: 'Laringotraqueíte viral aguda',
    veredito: 'Crupe — estreitamento subglótico simétrico em torre, com epiglote normal',
    correlacao: 'Resfriado, tosse de cachorro, rouquidão e estridor noturno numa criança de 18 meses que não baba: é a subglote edemaciada, o ponto mais estreito da via aérea infantil. A incidência frontal mostra a coluna de ar perdendo os ombros e afilando como uma torre logo abaixo das cordas vocais; a epiglote no perfil é fina. Dexametasona e, se necessário, adrenalina nebulizada.',
    distratores: [
      d('Epiglotite bacteriana', 'Criança toxemiada, com febre alta, sialorreia, posição em tripé e voz abafada, sem tosse ladrante. No perfil, a epiglote é um polegar. Esta menina está em bom estado, tosse como cachorro e bebe líquidos — e a epiglote é normal.'),
      d('Estenose subglótica congênita', 'Também estreita a subglote, mas de forma fixa, com estridor que persiste entre infecções, desde os primeiros meses. O estreitamento deste caso surgiu com um resfriado e deve desaparecer em dias — se o estridor persistir, aí a endoscopia.'),
      d('Corpo estranho laríngeo', 'Estridor súbito após engasgo, sem pródromo viral, frequentemente com afonia e sem febre. A história aqui é de resfriado há dois dias e febre, e o estreitamento é simétrico — viral.'),
    ],
  },
  'timo-normal': {
    cenario: 'Ambulatório de pediatria',
    identificacao: 'Menino de 5 meses, levado para consulta de puericultura.',
    queixa: 'Radiografia feita em outro serviço por tosse, com laudo de "alargamento mediastinal".',
    historia: 'Teve um resfriado há duas semanas e fez radiografia num pronto-atendimento, cujo laudo sugeria "massa mediastinal a esclarecer". Os pais estão assustados. A tosse já passou, a criança mama bem, ganha peso e não tem estridor, chiado ou febre.',
    antecedentes: ['Nascido a termo, 3.450 g', 'Aleitamento materno exclusivo', 'Vacinação em dia', 'Sem internações'],
    vitais: { pa: 'não aferida', fc: '128 bpm', fr: '36 irpm', satO2: '99% em ar ambiente', temp: '36,6 °C' },
    exame: ['Bom estado geral, ganho ponderal adequado', 'Ausculta pulmonar normal', 'Sem estridor ou desconforto', 'Sem adenomegalias ou visceromegalias'],
    pedido: 'Alargamento mediastinal superior em lactente assintomático: a pergunta é se a imagem tem as características do timo normal.',
    pergunta: 'Radiografia de tórax em AP. Qual é o achado que responde à pergunta clínica?',
    achado: 'Timo normal do lactente',
    veredito: 'Timo normal — sinal da vela, sem efeito de massa',
    correlacao: 'Um lactente de 5 meses que mama, ganha peso e respira sem esforço não tem uma massa mediastinal comprimindo nada. O filme mostra o timo, proporcionalmente enorme nessa idade: borda inferior reta e nítida apoiada na fissura menor — a vela — e contorno lateral ondulado pelas costelas, com a traqueia no meio. É anatomia, e a investigação para aqui.',
    distratores: [
      d('Linfoma mediastinal anterior', 'Linfoma no lactente é raríssimo; quando há massa mediastinal verdadeira, ela desloca ou comprime a traqueia, tem contorno lobulado e vem com sintomas. Aqui a traqueia está central, a borda é nítida em vela e a criança está assintomática.'),
      d('Teratoma do mediastino', 'Massa anterior que pode ter gordura, calcificação ou dentes, com efeito de massa e crescimento. A sombra deste caso é homogênea, sem calcificação, moldada pelas costelas e sem compressão — o timo tem exatamente esse comportamento mole.'),
      d('Pneumonia do lobo superior', 'Consolidação do lobo superior direito também opacifica o campo superior e tem limite inferior na fissura menor. Mas teria broncograma, febre e estertores; a criança está bem e a borda lateral mostra a ondulação costal que só um órgão mole faz.'),
    ],
  },
  'hernia-diafragmatica-congenita': {
    cenario: 'Sala de parto',
    identificacao: 'Recém-nascido de 38 semanas, sexo feminino, 2.900 g, sem pré-natal adequado.',
    queixa: 'Desconforto respiratório grave e cianose logo após o nascimento.',
    historia: 'Mãe de 19 anos com apenas duas consultas de pré-natal e nenhum ultrassom morfológico. Parto vaginal; a criança chorou fracamente e em minutos evoluiu com cianose, gemência e retração intensa. Foi ventilada com máscara e piorou. Intubada e passada sonda gástrica.',
    antecedentes: ['Pré-natal incompleto', 'Polidrâmnio relatado no único ultrassom', 'Sem consanguinidade', 'Apgar 4 e 6'],
    vitais: { pa: 'não aferida', fc: '172 bpm', fr: '70 irpm antes da intubação', satO2: '72% pré-ductal', temp: '36,2 °C' },
    exame: ['Abdome escavado', 'Murmúrio abolido no hemitórax esquerdo', 'Bulhas mais audíveis à direita do esterno', 'Ruídos hidroaéreos no hemitórax esquerdo'],
    pedido: 'Recém-nascido cianótico com abdome escavado e bulhas à direita: a pergunta é se há vísceras abdominais no tórax.',
    pergunta: 'Radiografia toracoabdominal em AP. Qual é o achado que responde à pergunta clínica?',
    achado: 'Hérnia diafragmática congênita',
    veredito: 'Hérnia diafragmática congênita à esquerda — alças com gás no hemitórax e mediastino desviado',
    correlacao: 'Polidrâmnio, desconforto grave ao nascer, abdome escavado, bulhas à direita e ruídos intestinais no tórax contam que as vísceras estão acima do diafragma. O filme mostra o hemitórax esquerdo cheio de bolhas de gás intestinal, o mediastino empurrado e o abdome sem gás. A ventilação com máscara piorou tudo porque encheu de ar o intestino no tórax — intubar, descomprimir e estabilizar antes da cirurgia.',
    distratores: [
      d('Malformação adenomatoide cística', 'Também produz cistos com ar no hemitórax e desvio mediastinal, mas o diafragma está íntegro, o abdome tem alças com gás e não é escavado, e a sonda gástrica fica no abdome. Aqui o abdome está vazio e há ruídos intestinais no tórax.'),
      d('Pneumotórax neonatal hipertensivo', 'Deixa o hemitórax hiperlucente, sem trama e sem bolhas com parede, e o abdome continua normal. As bolhas deste caso são alças com parede — drenar pensando em pneumotórax perfuraria o intestino.'),
      d('Síndrome de aspiração de mecônio', 'Recém-nascido a termo com desconforto grave e opacidades grosseiras bilaterais, hiperinsuflação e líquido meconial. Não há mecônio relatado, o abdome é escavado e as imagens são bolhas de gás intestinal no tórax.'),
    ],
  },
  'doenca-da-membrana-hialina': {
    cenario: 'Unidade de terapia intensiva neonatal',
    identificacao: 'Recém-nascido de 29 semanas, sexo masculino, 1.180 g.',
    queixa: 'Gemência e desconforto respiratório progressivo desde a primeira hora de vida.',
    historia: 'Parto cesáreo por pré-eclâmpsia grave materna; a mãe recebeu apenas uma dose de corticoide antenatal. Nasceu com esforço respiratório, que piorou nas primeiras horas: gemência, batimento de asa nasal e retrações. Está em CPAP com FiO2 de 0,5.',
    antecedentes: ['Prematuridade extrema', 'Corticoide antenatal incompleto', 'Pré-eclâmpsia grave materna', 'Bolsa rota há menos de 1 hora'],
    vitais: { pa: 'média de 30 mmHg', fc: '164 bpm', fr: '72 irpm', satO2: '88% com FiO2 0,5', temp: '36,4 °C' },
    exame: ['Gemência expiratória', 'Retrações intercostais e subcostais', 'Murmúrio diminuído globalmente', 'Sem sopros cardíacos'],
    pedido: 'Prematuro de 29 semanas com desconforto crescente: a pergunta é se há o padrão da deficiência de surfactante que indica surfactante exógeno.',
    pergunta: 'Radiografia de tórax em AP. Qual é o achado que responde à pergunta clínica?',
    achado: 'Deficiência de surfactante',
    veredito: 'Síndrome do desconforto respiratório neonatal — padrão granular difuso com broncogramas e volumes reduzidos',
    correlacao: 'Vinte e nove semanas, corticoide antenatal incompleto e gemência desde a primeira hora: o pulmão não tem surfactante e os alvéolos colapsam a cada expiração. O filme mostra milhões de microatelectasias como um vidro granular homogêneo, broncogramas chegando à periferia e cúpulas altas. O surfactante exógeno está indicado.',
    distratores: [
      d('Taquipneia transitória do recém-nascido', 'Acomete o termo nascido de cesárea, com estrias peri-hilares, líquido nas fissuras e pulmões normais ou hiperinsuflados, e melhora em 48 horas. Aqui o recém-nascido é prematuro extremo, com granulação difusa e volumes baixos.'),
      d('Pneumonia por estreptococo do grupo B', 'O filme pode ser idêntico, e por isso o antibiótico empírico entra até a cultura sair. Mas a bolsa rompeu há menos de 1 hora, sem febre materna, e a prematuridade com corticoide incompleto explica sozinha o quadro.'),
      d('Síndrome de aspiração de mecônio', 'É do termo ou pós-termo, com líquido meconial, opacidades grosseiras e assimétricas e hiperinsuflação. O prematuro de 29 semanas raramente elimina mecônio, e o padrão aqui é fino, simétrico e com volumes baixos.'),
    ],
  },
  'taquipneia-transitoria': {
    cenario: 'Alojamento conjunto',
    identificacao: 'Recém-nascido de 38 semanas, sexo feminino, 3.300 g, nascido de cesárea eletiva.',
    queixa: 'Respiração rápida desde o nascimento, sem piora.',
    historia: 'Cesárea eletiva sem trabalho de parto por cesárea anterior. Chorou ao nascer, Apgar 8 e 9. Desde a primeira hora respira rápido, com leve retração, mas mama e está corada. Nas primeiras 6 horas, a frequência respiratória permaneceu entre 70 e 80, com necessidade de oxigênio por pouco tempo.',
    antecedentes: ['Cesárea eletiva sem trabalho de parto', 'Mãe diabética gestacional em dieta', 'Bolsa íntegra até o parto', 'Líquido amniótico claro'],
    vitais: { pa: 'não aferida', fc: '150 bpm', fr: '76 irpm', satO2: '94% em ar ambiente', temp: '36,8 °C' },
    exame: ['Taquipneia com retração subcostal leve', 'Sem gemência', 'Murmúrio presente bilateral, estertores finos discretos', 'Sem sopros cardíacos'],
    pedido: 'Recém-nascido a termo de cesárea com taquipneia isolada: a pergunta é se o padrão é de líquido pulmonar retido.',
    pergunta: 'Radiografia de tórax em AP. Qual é o achado que responde à pergunta clínica?',
    achado: 'Taquipneia transitória neonatal',
    veredito: 'Taquipneia transitória do recém-nascido — estrias peri-hilares e líquido nas fissuras',
    correlacao: 'Cesárea sem trabalho de parto significa que o pulmão fetal não foi espremido nem recebeu o estímulo hormonal para reabsorver o líquido. O filme mostra esse líquido: estrias radiadas a partir dos hilos, a fissura menor desenhada como faixa branca e volumes preservados. O bebê melhora sozinho em 24 a 72 horas.',
    distratores: [
      d('Deficiência de surfactante neonatal', 'É do prematuro, com granulação fina difusa, broncogramas periféricos e volumes baixos, e piora nas primeiras horas. Este recém-nascido é a termo, com volumes normais e estrias peri-hilares — outro mecanismo.'),
      d('Cardiopatia congênita com hiperfluxo', 'Também produz estrias e congestão, mas com cardiomegalia, sopro e piora progressiva após o fechamento do canal. O coração é normal e o bebê tende a melhorar; se não melhorar em 72 horas, o ecocardiograma entra.'),
      d('Pneumonia neonatal precoce', 'Pode imitar qualquer padrão, mas vem com fatores de risco infecciosos — bolsa rota prolongada, febre materna, colonização por estreptococo B. Não há nenhum deles aqui, e a evolução é de melhora.'),
    ],
  },
  'pneumonia-redonda': {
    cenario: 'Pronto-socorro pediátrico',
    identificacao: 'Menino de 4 anos, previamente hígido.',
    queixa: 'Febre alta há 3 dias e dor abdominal.',
    historia: 'Febre de 39,5 °C há três dias, que cede com antitérmico e volta. Tosse pouca. Queixou-se de dor na barriga e vomitou uma vez, e a mãe achou que era virose intestinal. Hoje está mais abatido e respirando um pouco rápido.',
    antecedentes: ['Sem doenças prévias', 'Vacinação em dia, incluindo pneumocócica', 'Frequenta escola', 'Sem viagens recentes'],
    vitais: { pa: '98 × 60 mmHg', fc: '132 bpm', fr: '32 irpm', satO2: '95% em ar ambiente', temp: '39,4 °C' },
    exame: ['Prostrado, mas hidratado', 'Estertores finos localizados na base direita posterior', 'Abdome doloroso difusamente, sem sinais de peritonite', 'Orofaringe sem alterações'],
    pedido: 'Febre alta com dor abdominal e estertores localizados em criança: a pergunta é se há foco pulmonar que explique o quadro.',
    pergunta: 'Radiografia de tórax em PA. Qual é o achado que responde à pergunta clínica?',
    achado: 'Pneumonia redonda',
    veredito: 'Pneumonia redonda — opacidade esférica bem delimitada em criança febril',
    correlacao: 'Criança pequena com febre alta, estertores localizados e dor abdominal referida da base pulmonar: o foco é o pulmão. O filme mostra uma opacidade esférica, bem delimitada, que parece massa — mas na criança os canais colaterais entre alvéolos são imaturos e a consolidação pneumocócica fica contida como bola. Trate e repita em 2 a 3 semanas; ela desaparece.',
    distratores: [
      d('Massa pulmonar primária', 'Tumor pulmonar em criança de 4 anos é raríssimo, e não vem com febre de 39 °C há três dias. Uma "massa" em criança febril é pneumonia até prova contrária — biopsiar antes de tratar seria o erro.'),
      d('Cisto broncogênico infectado', 'É uma lesão congênita, geralmente mediastinal ou peri-hilar, de parede lisa, que pode infectar e ganhar nível. A opacidade deste caso é periférica, homogênea, sem nível, surgida com o quadro febril — e deve sumir com antibiótico.'),
      d('Sequestro pulmonar infectado', 'Localiza-se no segmento basal posterior, geralmente à esquerda, com pneumonias recorrentes no mesmo lugar e vaso anômalo da aorta. É o primeiro episódio desta criança; se a opacidade persistir ou recorrer, a angiotomografia procura o sequestro.'),
    ],
  },
  'aspiracao-de-meconio': {
    cenario: 'Unidade de terapia intensiva neonatal',
    identificacao: 'Recém-nascido de 42 semanas, sexo masculino, 3.900 g.',
    queixa: 'Desconforto respiratório grave logo após o parto com líquido meconial espesso.',
    historia: 'Gestação pós-termo, trabalho de parto prolongado com desacelerações tardias na cardiotocografia. Líquido amniótico espesso, "em purê de ervilha". Nasceu deprimido, foi aspirado e ventilado, e evoluiu com desconforto grave, cianose e necessidade de intubação.',
    antecedentes: ['Gestação de 42 semanas', 'Sofrimento fetal na cardiotocografia', 'Líquido meconial espesso', 'Apgar 3 e 6'],
    vitais: { pa: 'média de 38 mmHg', fc: '168 bpm', fr: 'ventilação mecânica', satO2: '84% pré-ductal e 74% pós-ductal', temp: '36,9 °C' },
    exame: ['Pele e unhas impregnadas de mecônio', 'Tórax hiperinsuflado, em barril', 'Estertores grossos bilaterais', 'Diferença de saturação pré e pós-ductal'],
    pedido: 'Recém-nascido pós-termo com líquido meconial e hipoxemia grave: a pergunta é o padrão pulmonar e se há ar extra-alveolar.',
    pergunta: 'Radiografia de tórax em AP. Qual é o achado que responde à pergunta clínica?',
    achado: 'Síndrome de aspiração meconial',
    veredito: 'Síndrome de aspiração de mecônio — opacidades grosseiras assimétricas com hiperinsuflação',
    correlacao: 'Pós-termo, sofrimento fetal, líquido em purê de ervilha e pele impregnada: o feto hipóxico eliminou e aspirou mecônio. O filme mostra o que ele faz no pulmão — áreas de hiperinsuflação alternando com opacidades grosseiras e irregulares, obstrução parcial e total ao mesmo tempo. A diferença de saturação pré e pós-ductal denuncia a hipertensão pulmonar que acompanha.',
    distratores: [
      d('Deficiência de surfactante neonatal', 'Acomete o prematuro, com granulação fina, simétrica e volumes baixos. Este é um pós-termo de 42 semanas com volumes grandes e opacidades grosseiras e assimétricas — o oposto.'),
      d('Taquipneia transitória do recém-nascido', 'Termo de cesárea, com estrias peri-hilares e evolução benigna em 48 horas. Este recém-nascido nasceu deprimido, com líquido meconial, e precisa de ventilação mecânica — não é líquido pulmonar retido.'),
      d('Hérnia diafragmática congênita', 'Faz bolhas de gás intestinal no tórax, abdome escavado e desvio mediastinal. Aqui o abdome é normal, as opacidades são parenquimatosas e bilaterais, e há mecônio na pele — outra doença.'),
    ],
  },
  'fraturas-de-maus-tratos': {
    cenario: 'Pronto-socorro pediátrico',
    identificacao: 'Lactente de 3 meses, sexo feminino, trazida pelo padrasto.',
    queixa: 'Irritabilidade e choro ao mexer a perna esquerda há 2 dias.',
    historia: 'O padrasto relata que a criança "prendeu a perna na grade do berço" há dois dias; a mãe, que chegou depois, diz que não sabia de nenhum acidente. A bebê chora ao trocar a fralda e não mexe a perna esquerda. Há seis semanas foi atendida por "choro inconsolável" e liberada.',
    antecedentes: ['Parto a termo sem intercorrências', 'Atendimento prévio por choro inconsolável', 'Pais separados; mora com a mãe e o padrasto', 'Vacinação atrasada'],
    vitais: { pa: 'não aferida', fc: '148 bpm', fr: '38 irpm', satO2: '98% em ar ambiente', temp: '36,7 °C' },
    exame: ['Edema e dor à mobilização do joelho esquerdo', 'Equimoses de idades diferentes no tronco', 'Fontanela normotensa', 'Sem outras deformidades evidentes'],
    pedido: 'Lactente que não anda com fratura provável e história inconsistente: a pergunta é se há padrões de fratura específicos de trauma não acidental.',
    pergunta: 'Radiografia do joelho e série esquelética. Qual é o achado que responde à pergunta clínica?',
    achado: 'Lesão metafisária clássica',
    veredito: 'Fraturas de maus-tratos — lesão metafisária clássica e fraturas em diferentes estágios',
    correlacao: 'Uma lactente que não anda, uma história que muda conforme quem conta, equimoses de idades diferentes e uma visita anterior por choro inconsolável: a clínica já exige a investigação. O filme mostra a lesão metafisária em canto — o fragmento arrancado da metáfise por torção e tração do membro, quase exclusivo de trauma infligido. A série esquelética, o fundo de olho e a notificação são obrigatórios.',
    distratores: [
      d('Fratura acidental em galho verde', 'A fratura incompleta da diáfise ocorre em criança que já anda e cai sobre a mão, com história coerente. Esta bebê de 3 meses não se move sozinha, e a lesão é na metáfise, por torção — não por queda.'),
      d('Osteogênese imperfeita', 'Deixa ossos frágeis com fraturas múltiplas, mas vem com esclera azulada, ossos wormianos, osteopenia difusa e história familiar. Excluí-la faz parte da avaliação, não da desculpa; a lesão metafisária em canto não é o padrão dela.'),
      d('Osteomielite metafisária', 'Também acomete a metáfise do lactente, com dor e edema, mas com febre, rarefação mal definida e reação periosteal — não um fragmento cortical nítido em canto. A bebê está afebril, e há equimoses em outros locais.'),
    ],
  },
}
