import { d, r, type ConteudoCaso } from './casos-imagem-tipos'

/** Segunda leva de TC — crânio. Pacientes das vinhetas são fictícios. */
export const CASOS_TC_L2_NEURO: Record<string, ConteudoCaso> = {
  'hematoma-extradural-agudo': {
    tema: 'Trauma',
    titulo: 'Hematoma extradural agudo com sinal do redemoinho e herniações',
    resumo: 'Hematoma extradural temporal direito com sangramento ativo, contusão de contragolpe, herniação subfalcina e uncal e fraturas da base e da face.',
    protocolo: 'TC de crânio sem contraste, janelas óssea e de parênquima',
    series: ['Janela óssea', 'Parênquima'],
    rotulos: {
      'right lateral mass of C1': r('Massa lateral direita de C1', 'Fratura que alcança a massa lateral do atlas, no limite inferior do exame.',
        'O exame de crânio no trauma grave sempre inclui a transição craniocervical, porque impacto de alta energia na cabeça transmite força para o atlas e o áxis. Uma linha de fratura na massa lateral de C1 muda a manipulação do paciente: o colar cervical fica até a coluna ser avaliada por inteiro.',
        'Trauma craniano grave é trauma de coluna cervical até prova contrária; a TC de coluna faz parte do protocolo.'),
      'right zygomatic fracture': r('Fratura do arco zigomático direito', 'Traço no arco zigomático do mesmo lado do hematoma.',
        'O arco zigomático é uma ponte óssea fina entre a face e o osso temporal. Fratura nele, do mesmo lado do hematoma, ajuda a reconstruir o ponto de impacto: o golpe veio pela lateral direita da cabeça, na região temporal, onde corre a artéria meníngea média.'),
      'clivus fracture': r('Fratura do clivo', 'Traço no clivo, osso da base do crânio à frente do tronco.',
        'O clivo é a rampa óssea que sustenta a ponte e o bulbo. Fraturá-lo exige energia muito alta e põe em risco a artéria basilar, os nervos cranianos baixos e o sexto nervo. Fraturas da base costumam se acompanhar de sangue nos seios esfenoidais.',
        'Fratura do clivo pede angiotomografia: lesão da artéria basilar ou das carótidas pode passar despercebida na TC sem contraste.'),
      haemosinus: r('Hemossinus', 'Sangue com nível líquido dentro de um seio paranasal.',
        'Nível líquido no seio esfenoidal após trauma é sangue, e sangue no seio esfenoidal é sinal indireto de fratura da base do crânio, mesmo quando o traço não aparece. Também abre caminho para fístula liquórica e para ar intracraniano.'),
      'squamous temporal fracture': r('Fratura da escama temporal', 'Traço na parte fina e lateral do osso temporal.',
        'A escama temporal é o osso mais fino da calota e fica bem sobre o sulco da artéria meníngea média. É por isso que fraturas temporais são a causa clássica do hematoma extradural arterial: o osso quebrado rasga a artéria, e o sangue sob pressão descola a dura da tábua interna.',
        'Fratura que cruza o sulco da meníngea média com coleção logo abaixo fecha a origem do hematoma.'),
      'widening of coronal suture': r('Diástase da sutura coronal', 'Sutura coronal afastada além do normal pelo impacto.',
        'Em adultos, as suturas cranianas são linhas finas e simétricas. Uma sutura mais larga que a do outro lado, ou que a esperada, significa que o impacto a separou — é a diástase traumática, que conta como fratura e tem o mesmo significado de energia.'),
      'uncal herniation': r('Herniação uncal', 'O úncus do lobo temporal desce pela incisura do tentório e comprime o mesencéfalo.',
        'O úncus é a porção mais medial do lobo temporal. Quando um hematoma temporal empurra o lobo para dentro, o úncus passa pela incisura do tentório e esmaga o terceiro nervo e o mesencéfalo. Clinicamente aparece a pupila dilatada do mesmo lado; na TC, a cisterna suprasselar e a ambiens ficam apagadas.',
        'Anisocoria com rebaixamento no trauma é herniação uncal até prova em contrário — sala de cirurgia, não nova imagem.'),
      'left temporal lobe contusion': r('Contusão temporal esquerda — contragolpe', 'Foco hemorrágico no lobo temporal oposto ao impacto.',
        'Quando a cabeça para bruscamente, o cérebro continua o movimento e bate do outro lado do crânio. A contusão de contragolpe aparece no lado oposto ao impacto, aqui o temporal esquerdo, contra a asa do esfenoide. Ela pode crescer nas primeiras horas e piorar o efeito de massa.'),
      'subfalcine herniation': r('Herniação subfalcina', 'O hemisfério direito passa por baixo da foice para a esquerda.',
        'O giro do cíngulo é empurrado sob a borda livre da foice. A linha média, medida no septo pelúcido, sai do lugar, e o ventrículo do lado do hematoma é comprimido enquanto o do outro lado se dilata por aprisionamento. Desvio acima de 5 mm com sintomas é indicação cirúrgica.'),
      'swirl sign': r('Sinal do redemoinho', 'Áreas escuras misturadas ao sangue branco dentro do hematoma.',
        'Sangue coagulado é branco; sangue fresco, ainda líquido e saindo da artéria, é mais escuro. Dentro de um hematoma agudo, áreas hipodensas em redemoinho indicam que ele ainda está sendo alimentado — sangramento ativo. É sinal de mau prognóstico e de expansão iminente.',
        'Não confunda com hematoma subagudo heterogêneo: o redemoinho aparece em coleções de poucas horas, com bordas muito densas.'),
    },
    achados: [
      'Coleção extra-axial biconvexa temporal direita, hiperdensa, com áreas hipodensas centrais em redemoinho — sangramento ativo.',
      'Herniação subfalcina e uncal, com compressão do ventrículo direito e dilatação do esquerdo por aprisionamento.',
      'Contusão temporal esquerda por contragolpe.',
      'Fraturas da escama temporal direita, do arco zigomático, do clivo e da massa lateral de C1, com hemossinus e diástase da sutura coronal.',
    ],
    armadilhas: [
      'O intervalo lúcido existe em parte dos casos: o paciente fala e piora horas depois, quando o hematoma cresce.',
      'Hematoma extradural é limitado pelas suturas porque a dura está presa a elas; quando cruza suturas, pense em subdural ou em origem venosa.',
      'A TC de crânio no trauma de alta energia deve ser lida também na janela óssea e na transição craniocervical.',
    ],
    conduta: 'Craniotomia de emergência para drenagem do hematoma e ligadura do vaso, proteção da coluna cervical, controle da pressão intracraniana e correção de coagulopatia; avaliação de lesão vascular pela fratura da base.',
    vinheta: {
      cenario: 'Trauma, sala vermelha',
      identificacao: 'Homem de 24 anos, entregador de moto, trazido pelo SAMU.',
      queixa: 'Bateu a cabeça em colisão de moto e piorou no trajeto.',
      historia: 'Colidiu a moto contra um poste, com capacete aberto, e bateu o lado direito da cabeça. No local estava confuso, mas falava e reconhecia os socorristas. Durante os 30 minutos de transporte ficou cada vez mais sonolento, vomitou duas vezes e passou a não abrir os olhos ao chamado.',
      antecedentes: [
        'Pessoais: previamente hígido, sem uso de anticoagulantes',
        'Pessoais: sem cirurgias prévias',
        'Familiares: sem coagulopatias conhecidas',
        'Hábitos: etilismo social, bebeu duas cervejas antes do acidente',
      ],
      vitais: { pa: '172 × 94 mmHg', fc: '56 bpm', fr: '10 irpm, irregular', satO2: '93% com máscara', temp: '36,1 °C' },
      exame: [
        'Glasgow 7: abertura ocular ausente, palavras inapropriadas, flexão anormal à dor',
        'Pupila direita dilatada e pouco reativa',
        'Hematoma e escoriação na região temporal direita',
        'Equimose periorbitária bilateral e otorragia à direita',
      ],
      pedido: 'Trauma craniano com intervalo lúcido, piora rápida, anisocoria e tríade de Cushing: a pergunta é qual lesão cirúrgica existe e se há herniação.',
      pergunta: 'TC de crânio sem contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Hematoma extradural agudo com herniação',
      veredito: 'Hematoma extradural temporal direito com sangramento ativo, herniação subfalcina e uncal e fraturas da base do crânio',
      correlacao: 'O impacto temporal fraturou a escama, o osso mais fino da calota, e rompeu a artéria meníngea média que corre logo abaixo. O sangue arterial descolou a dura e formou a lente biconvexa. O paciente falava no local — o intervalo lúcido — e piorou à medida que o hematoma crescia, alimentado por sangue ainda líquido, o redemoinho. Pupila direita dilatada, bradicardia e hipertensão mostram a herniação uncal que a TC confirma.',
      distratores: [
        d('Hematoma subdural agudo hemisférico', 'Também comprime o hemisfério e causa herniação, mas tem forma de crescente, cruza as suturas e vem de veias ponte, geralmente sem intervalo lúcido. A coleção deste paciente é biconvexa e limitada às suturas, sob uma fratura temporal.'),
        d('Lesão axonal difusa grave', 'Explica coma após trauma de alta energia, mas o paciente fica em coma desde o impacto, sem intervalo lúcido, e a TC mostra poucas petéquias, sem coleção nem desvio da linha média.'),
        d('Contusões frontotemporais hemorrágicas', 'Este paciente tem uma contusão de contragolpe, mas ela é pequena e não explica a herniação. O que comprime o cérebro é a coleção extra-axial temporal direita.'),
      ],
    },
  },

  'trombose-venosa-cerebral': {
    tema: 'Vascular',
    titulo: 'Trombose venosa cerebral com infarto venoso hemorrágico',
    resumo: 'Seio sagital superior e veia cortical hiperdensos, falha de enchimento na fase venosa e focos de hemorragia parietal com hemorragia subaracnoidea de sulco.',
    protocolo: 'TC de crânio sem contraste e venografia por TC',
    series: ['Sem contraste', 'Fase venosa'],
    rotulos: {
      'subarachnoiid haemorrhage': r('Hemorragia subaracnoidea de sulco', 'Sangue em poucos sulcos da convexidade, junto ao infarto venoso.',
        'A veia cortical trombosada fica sob pressão e se rompe para o espaço subaracnoideo, deixando sangue em um ou dois sulcos da convexidade. Hemorragia subaracnoidea restrita à convexidade, sem sangue nas cisternas da base, é padrão que lembra trombose venosa, vasculopatia reversível ou angiopatia amiloide — não aneurisma.'),
      'intracerebral haemorrhage': r('Hematomas do infarto venoso', 'Focos arredondados de sangue no lobo parietal direito, com edema.',
        'Quando a drenagem venosa é bloqueada, o sangue continua chegando pelas artérias e não tem por onde sair: a pressão capilar sobe, o tecido incha e os capilares rompem. O infarto venoso costuma ser hemorrágico, subcortical, não respeita território arterial e pode ser múltiplo e bilateral.',
        'Hemorragia lobar em mulher jovem, sem hipertensão, com cefaleia de dias: pense em trombose venosa antes de qualquer outra coisa.'),
      hyperattenuation: r('Seio sagital superior hiperdenso', 'O seio aparece mais branco que o normal por trombo recente.',
        'O trombo fresco tem hemácias concentradas e mede de 60 a 80 UH, contra cerca de 40 UH do sangue circulante. Na TC sem contraste, o seio trombosado fica mais branco que as artérias do mesmo corte — o sinal do delta denso, quando o seio é cortado em triângulo.',
        'Hematócrito alto e desidratação deixam todos os seios mais densos; o sinal vale quando é desproporcional e assimétrico.'),
      'cortical vein': r('Veia cortical trombosada', 'Veia superficial hiperdensa em cordão, drenando para o seio — o sinal da corda.',
        'As veias corticais drenam a superfície do cérebro para os seios durais. Trombosada, a veia aparece como um cordão branco sobre a convexidade. É ela que, ao se ocluir, causa o infarto venoso e a hemorragia logo abaixo.'),
      'filling defect': r('Falha de enchimento — sinal do delta vazio', 'Na fase venosa, o seio realça na periferia e fica escuro no centro.',
        'Com contraste, as paredes do seio e as veias colaterais na dura realçam, mas o trombo no centro não: forma-se um triângulo branco com centro escuro, o delta vazio. É a confirmação direta da trombose, e a venografia por TC mostra até onde o trombo se estende.',
        'Granulações aracnoides também criam falhas arredondadas e pequenas no seio; elas são focais, bem delimitadas e têm densidade de líquor.'),
    },
    achados: [
      'Hiperdensidade do seio sagital superior e de uma veia cortical parietal direita na TC sem contraste.',
      'Falha de enchimento do seio sagital superior na fase venosa — sinal do delta vazio.',
      'Focos arredondados de hemorragia parietal direita com edema vasogênico e apagamento de sulcos.',
      'Hemorragia subaracnoidea em sulcos da convexidade adjacentes.',
    ],
    armadilhas: [
      'A TC sem contraste pode ser normal ou mostrar só edema; a suspeita clínica é que manda pedir a venografia.',
      'O infarto venoso não respeita território arterial e muitas vezes é bilateral junto à linha média, por trombose do sagital superior.',
      'A hemorragia não contraindica a anticoagulação na trombose venosa: ela é o tratamento.',
    ],
    conduta: 'Anticoagulação plena mesmo com hemorragia, tratamento de convulsões, controle da hipertensão intracraniana, investigação de trombofilia e causas locais; trombectomia venosa em quem piora apesar do tratamento.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Mulher de 29 anos, publicitária, puérpera de três semanas.',
      queixa: 'Dor de cabeça que piora há cinco dias e uma convulsão hoje.',
      historia: 'Teve parto cesáreo há três semanas. Há cinco dias começou cefaleia holocraniana progressiva, pior ao deitar e ao tossir, sem melhora com analgésicos. Hoje o marido a viu ter abalos no braço esquerdo que se generalizaram, com perda de consciência por dois minutos. Desde então tem fraqueza na mão esquerda.',
      antecedentes: [
        'Pessoais: enxaqueca sem aura desde a adolescência',
        'Gestacionais: primeira gestação, cesárea por parada de progressão, puerpério com desidratação por amamentação difícil',
        'Familiares: mãe com trombose venosa profunda após cirurgia',
        'Hábitos: usava anticoncepcional oral antes da gestação; nega tabagismo',
      ],
      vitais: { pa: '134 × 86 mmHg', fc: '96 bpm', fr: '18 irpm', satO2: '98% em ar ambiente', temp: '37,2 °C' },
      exame: [
        'Sonolenta, orientada após o período pós-ictal',
        'Paresia leve em mão e antebraço esquerdos',
        'Papiledema bilateral',
        'Sem rigidez de nuca',
      ],
      pedido: 'Cefaleia progressiva com crise focal e papiledema no puerpério: a pergunta é se há trombose venosa e lesão cerebral associada.',
      pergunta: 'TC sem contraste e venografia por TC. Qual é o achado que responde à pergunta clínica?',
      achado: 'Trombose venosa cerebral com hemorragia',
      veredito: 'Trombose do seio sagital superior e de veia cortical com infarto venoso hemorrágico parietal direito',
      correlacao: 'O puerpério é estado de hipercoagulabilidade, piorado pela desidratação, e a mãe teve trombose: o terreno da trombose venosa cerebral. A obstrução do seio sagital superior eleva a pressão intracraniana, daí a cefaleia que piora deitada e o papiledema. A veia cortical trombosada causou o infarto hemorrágico parietal direito, que explica a crise focal e a paresia da mão esquerda.',
      distratores: [
        d('Hemorragia por aneurisma roto', 'Daria cefaleia súbita e máxima desde o início, com sangue nas cisternas da base e na fissura sylviana. Esta cefaleia foi progressiva em dias, e o sangue está em poucos sulcos da convexidade junto a um infarto venoso.'),
        d('Eclâmpsia pós-parto com PRES', 'Também ocorre no puerpério com cefaleia e convulsão, mas com hipertensão e edema vasogênico simétrico posterior, sem seio hiperdenso nem falha de enchimento venosa.'),
        d('Malformação arteriovenosa rota', 'Sangra em jovens, mas na TC aparecem vasos serpiginosos realçados e calcificações junto ao hematoma, sem trombo nos seios venosos.'),
      ],
    },
  },

  'hemorragia-subaracnoidea-aneurismatica': {
    tema: 'Vascular',
    titulo: 'Hemorragia subaracnoidea aneurismática com síndrome de Terson',
    resumo: 'Sangue difuso nas cisternas da base, fissuras sylvianas e inter-hemisférica com inundação ventricular, hemorragia intraocular e embolização do aneurisma no controle.',
    protocolo: 'TC de crânio sem contraste na admissão e no controle após embolização',
    series: ['Admissão', 'Controle após embolização'],
    rotulos: {
      'maxillary sinusopathy': r('Sinusopatia maxilar', 'Espessamento mucoso do seio maxilar, achado incidental.',
        'O espessamento da mucosa do seio maxilar é muito comum em pacientes internados e intubados, pela posição deitada e pela sonda. Não tem relação com a hemorragia e não deve ser confundido com sangue no seio, que aconteceria em fratura da base.'),
      fourth: r('Quarto ventrículo com sangue', 'Sangue dentro do quarto ventrículo, na fossa posterior.',
        'O sangue que entra no sistema ventricular desce com o líquor e chega ao quarto ventrículo. Coágulo ali pode bloquear a saída do líquor pelos forames de Luschka e Magendie e causar hidrocefalia aguda, uma das complicações precoces da hemorragia subaracnoidea.'),
      'intraocular hemorrhage': r('Hemorragia intraocular — síndrome de Terson', 'Sangue no vítreo, visível como densidade dentro do globo ocular.',
        'A subida brusca da pressão intracraniana se transmite pela bainha do nervo óptico e rompe vasos da retina, levando sangue para o vítreo. É a síndrome de Terson, presente em parte das hemorragias subaracnoideas graves e associada a pior prognóstico. Na TC aparece como uma área mais densa no globo ocular.',
        'Peça avaliação oftalmológica: a hemorragia vítrea pode exigir vitrectomia se não reabsorver.'),
      'basal cisterns': r('Cisternas da base preenchidas', 'Sangue desenhando a cisterna suprasselar e as cisternas perimesencefálicas.',
        'Os aneurismas saccularess nascem no polígono de Willis, que fica justamente nas cisternas da base. Quando rompem, o sangue preenche primeiro essas cisternas, formando a estrela branca da cisterna suprasselar. É o padrão que diferencia a hemorragia aneurismática da traumática, que fica na convexidade.',
        'Na escala de Fisher modificada, sangue espesso nas cisternas e nos ventrículos indica maior risco de vasoespasmo.'),
      lateral: r('Sangue nos ventrículos laterais', 'Coágulo nos cornos occipitais, mais à esquerda.',
        'O sangue intraventricular se deposita nos cornos occipitais pela gravidade, com o paciente deitado. Hemorragia intraventricular aumenta a chance de hidrocefalia e piora o prognóstico da hemorragia subaracnoidea.'),
      'bilateral Sylvian fissures': r('Fissuras sylvianas', 'Sangue nas duas fissuras sylvianas, onde correm as artérias cerebrais médias.',
        'As fissuras sylvianas separam os lobos frontal e temporal e contêm as artérias cerebrais médias. Sangue nelas, bilateral e simétrico, é típico de aneurisma da comunicante anterior ou da artéria basilar; quando muito assimétrico, aponta para aneurisma da cerebral média do lado mais cheio.'),
      third: r('Terceiro ventrículo com sangue', 'Sangue preenchendo a fenda do terceiro ventrículo.',
        'O terceiro ventrículo recebe o sangue dos laterais pelos forames de Monro. Preenchido por coágulo, pode bloquear a passagem pelo aqueduto e contribuir para a hidrocefalia. Aneurismas da comunicante anterior podem romper diretamente para ele através da lâmina terminal.'),
      'subcortical sulci': r('Sangue nos sulcos', 'Sulcos da convexidade desenhados em branco.',
        'Em hemorragias volumosas, o sangue sobe das cisternas e chega aos sulcos da convexidade. O quanto ele se espalha é um indicador do volume do sangramento e do risco de complicações. Na escala de Fisher modificada, a espessura do sangue e a presença de sangue intraventricular graduam o risco de vasoespasmo.'),
      'interhemispheric fissure': r('Fissura inter-hemisférica', 'Sangue na fenda entre os hemisférios, à frente.',
        'Sangue concentrado na fissura inter-hemisférica anterior e no giro reto sugere aneurisma da artéria comunicante anterior, o local mais comum de aneurisma intracraniano. O sangue pode ainda romper para o giro reto e formar um hematoma frontal basal, outra pista da comunicante anterior.'),
      'hemorrhagic focus': r('Foco hemorrágico residual', 'Sangue remanescente no controle, já em reabsorção.',
        'Na TC de controle, parte do sangue ainda está presente, mas menos denso e em menor quantidade. O sangue subaracnoideo é lavado pelo líquor em dias, enquanto coágulos maiores e intraparenquimatosos demoram mais.'),
      'partial resorption': r('Reabsorção parcial', 'O sangue das cisternas diminuiu em relação à admissão.',
        'Comparar com o exame inicial mostra a evolução: o sangue some das cisternas progressivamente. Sangue novo no controle sugeriria ressangramento, a complicação mais temida antes do tratamento do aneurisma.'),
      'Metallic coil': r('Molas da embolização', 'Material metálico muito denso no local do aneurisma, com artefato em estrias.',
        'O aneurisma foi tratado por via endovascular: molas de platina preenchem o saco e promovem trombose, excluindo-o da circulação. Na TC, aparecem como foco metálico com artefato em raios que pode esconder estruturas próximas.',
        'O artefato metálico das molas simula ou esconde sangue nas proximidades; compare com cortes vizinhos.'),
    },
    achados: [
      'Hemorragia subaracnoidea extensa nas cisternas da base, nas fissuras sylvianas e inter-hemisférica e nos sulcos.',
      'Inundação ventricular com sangue nos ventrículos laterais, terceiro e quarto ventrículos — Fisher modificado 4.',
      'Hemorragia intraocular, compatível com síndrome de Terson.',
      'Controle após embolização: molas no local do aneurisma e reabsorção parcial do sangue.',
    ],
    armadilhas: [
      'A sensibilidade da TC cai depois de 6 horas; cefaleia em trovoada com TC normal pede punção lombar ou angiotomografia.',
      'Hidrocefalia aguda é precoce e pode exigir derivação ventricular nas primeiras horas.',
      'Vasoespasmo aparece entre o quarto e o décimo quarto dia; piora neurológica nesse período é isquemia até prova em contrário.',
    ],
    conduta: 'Unidade de terapia intensiva, controle pressórico, nimodipino, tratamento precoce do aneurisma por embolização ou clipagem, derivação ventricular para hidrocefalia, vigilância de vasoespasmo e avaliação oftalmológica.',
    vinheta: {
      cenario: 'Sala de emergência',
      identificacao: 'Mulher de 52 anos, contadora, trazida pelo marido.',
      queixa: 'A pior dor de cabeça da vida, súbita, seguida de desmaio.',
      historia: 'Estava fazendo exercício na academia quando sentiu uma dor de cabeça explosiva na nuca, máxima em segundos, e caiu. Recuperou a consciência em minutos, vomitou várias vezes e queixa-se de dor no pescoço e de visão embaçada no olho direito. Há duas semanas teve uma dor de cabeça forte e súbita que passou em um dia.',
      antecedentes: [
        'Pessoais: hipertensão mal controlada',
        'Pessoais: tabagista de 25 maços-ano',
        'Familiares: irmã com aneurisma cerebral operado aos 48 anos',
        'Hábitos: consumo de duas doses de destilado por dia',
      ],
      vitais: { pa: '196 × 108 mmHg', fc: '64 bpm', fr: '18 irpm', satO2: '96% em ar ambiente', temp: '37,0 °C' },
      exame: [
        'Glasgow 13, sonolenta e confusa',
        'Rigidez de nuca acentuada',
        'Hemorragia retiniana no olho direito à fundoscopia',
        'Sem déficit motor focal',
      ],
      pedido: 'Cefaleia em trovoada com perda de consciência, meningismo e cefaleia sentinela em paciente com irmã com aneurisma: a pergunta é se há hemorragia subaracnoidea e qual o seu padrão.',
      pergunta: 'TC de crânio sem contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Hemorragia subaracnoidea aneurismática difusa',
      veredito: 'Hemorragia subaracnoidea aneurismática difusa com inundação ventricular e síndrome de Terson',
      correlacao: 'Cefaleia máxima em segundos durante esforço, desmaio, vômitos e rigidez de nuca: um aneurisma rompeu. A cefaleia de duas semanas atrás foi provavelmente o sangramento sentinela. Hipertensão, tabagismo e irmã com aneurisma completam o risco. O sangue preenche as cisternas da base, onde fica o polígono de Willis, e invade os ventrículos; a visão embaçada é a hemorragia vítrea da síndrome de Terson, que a TC também mostra.',
      distratores: [
        d('Hemorragia subaracnoidea perimesencefálica benigna', 'Também causa cefaleia em trovoada, mas o sangue fica restrito à frente do mesencéfalo e da ponte, sem invadir as fissuras sylvianas nem os ventrículos, e a angiografia é normal.'),
        d('Síndrome de vasoconstrição reversível', 'Dá cefaleias em trovoada repetidas e pode deixar pouco sangue em sulcos da convexidade, mas sem preenchimento maciço das cisternas da base nem inundação ventricular.'),
        d('Meningite bacteriana aguda grave', 'Explica rigidez de nuca e rebaixamento, mas com febre e instalação em horas, não em segundos, e sem sangue hiperdenso nas cisternas.'),
      ],
    },
  },

  'aneurisma-roto-da-acm': {
    tema: 'Vascular',
    titulo: 'Ruptura de aneurisma da artéria cerebral média',
    resumo: 'Hematoma na fissura sylviana esquerda com componentes subaracnoideo, subdural e intraparenquimatoso, desvio da linha média e dois aneurismas saculares na angiotomografia.',
    protocolo: 'TC de crânio sem contraste e angiotomografia arterial',
    series: ['Sem contraste', 'Angiotomografia'],
    rotulos: {
      'Subarachnoid haemorrhage': r('Hematoma na fissura sylviana', 'Coleção de sangue que ocupa e alarga a fissura sylviana esquerda.',
        'Aneurismas da bifurcação da artéria cerebral média ficam dentro da fissura sylviana. Quando rompem, o jato de sangue forma um coágulo que ocupa a fissura e empurra os lobos frontal e temporal — um hematoma subaracnoideo com efeito de massa, mais localizado e assimétrico que o padrão difuso das cisternas.',
        'Sangue concentrado numa fissura sylviana aponta o aneurisma da cerebral média daquele lado.'),
      'Intraparenchymal haemorrhage': r('Hemorragia intraparenquimatosa', 'Pequeno hematoma no núcleo lentiforme esquerdo, ligado ao sangue da fissura.',
        'O jato do aneurisma pode romper a superfície do cérebro e entrar no parênquima, formando um hematoma em continuidade com o sangue da fissura. Hematoma intraparenquimatoso perto da fissura sylviana em paciente sem hipertensão sugere aneurisma, e não hemorragia hipertensiva.'),
      'Subdural haemorrhage': r('Hemorragia subdural associada', 'Fina lâmina de sangue em crescente sobre o lobo frontal esquerdo.',
        'O aneurisma às vezes rompe também através da aracnoide para o espaço subdural, formando um hematoma subdural sem trauma. Os três sangramentos se comunicam por trajetos finos. Subdural espontâneo, sem trauma e sem anticoagulação, deve levantar a hipótese de aneurisma.'),
      'Sacullar aneurysm 1st': r('Aneurisma sacular — o primeiro', 'Dilatação arredondada da artéria cerebral média na angiotomografia.',
        'Aneurisma sacular é uma bolsa que se forma no ponto fraco de uma bifurcação arterial, onde a camada média falha. Na angiotomografia aparece como saco realçado ligado ao vaso pelo colo. Tamanho, forma irregular e lóbulos sugerem qual rompeu quando há mais de um.',
        'Com aneurismas múltiplos, o que rompeu costuma ser o maior, o mais irregular e o que está junto ao maior volume de sangue.'),
      'ACA aneurysm': r('Aneurisma da artéria cerebral anterior', 'Segunda bolsa, na circulação anterior, sem relação com o sangramento.',
        'Aneurismas múltiplos ocorrem em parte dos pacientes, sobretudo em mulheres, fumantes e hipertensos. Um aneurisma da cerebral anterior longe do coágulo provavelmente não é o que rompeu, mas entra no planejamento do tratamento.'),
      'Sacullar aneurysm 2nd': r('Aneurisma sacular — o segundo', 'Outra bolsa na angiotomografia, que também precisa de tratamento.',
        'A angiotomografia deve ser lida inteira, mesmo depois de encontrado o primeiro aneurisma: perder um segundo aneurisma significa deixar um risco de nova hemorragia sem tratamento. O tratamento costuma ser planejado em etapas, começando pelo roto e programando os outros.'),
    },
    achados: [
      'Hematoma na fissura sylviana esquerda, com efeito de massa sobre os lobos frontal e temporal.',
      'Hemorragia subdural frontal esquerda e pequeno hematoma no núcleo lentiforme, comunicando-se com o sangue da fissura.',
      'Desvio da linha média para a direita, compressão do ventrículo lateral esquerdo e herniação subfalcina inicial.',
      'Angiotomografia com dois aneurismas saculares da artéria cerebral média e um da cerebral anterior.',
    ],
    armadilhas: [
      'Hematoma frontotemporal em paciente sem trauma e sem hipertensão é aneurisma até prova em contrário: peça a angiotomografia.',
      'O sangue sylviano com efeito de massa pode exigir drenagem do hematoma junto com a clipagem.',
      'Leia toda a angiotomografia: aneurismas múltiplos são comuns.',
    ],
    conduta: 'Controle pressórico e da pressão intracraniana, tratamento urgente do aneurisma roto — muitas vezes clipagem com drenagem do hematoma —, nimodipino e vigilância de vasoespasmo; planejamento dos aneurismas não rotos.',
    vinheta: {
      cenario: 'Sala de emergência',
      identificacao: 'Mulher de 58 anos, costureira, trazida pela filha.',
      queixa: 'Dor de cabeça súbita, fala enrolada e fraqueza no braço direito.',
      historia: 'Estava costurando quando gritou de dor de cabeça e deixou cair a tesoura. Em minutos a fala ficou confusa, trocando palavras, e o braço direito ficou fraco. Vomitou duas vezes. A filha conta que ela tinha cefaleias frequentes nos últimos meses, que tratava com analgésicos.',
      antecedentes: [
        'Pessoais: hipertensão em uso de losartana',
        'Pessoais: tabagista de 35 maços-ano',
        'Familiares: mãe morreu subitamente aos 60 anos com hemorragia cerebral',
        'Hábitos: sedentária, nega álcool e drogas',
      ],
      vitais: { pa: '188 × 102 mmHg', fc: '68 bpm', fr: '18 irpm', satO2: '96% em ar ambiente', temp: '36,8 °C' },
      exame: [
        'Glasgow 12, com afasia mista',
        'Hemiparesia direita de predomínio braquial',
        'Rigidez de nuca leve',
        'Pupilas isocóricas',
      ],
      pedido: 'Cefaleia súbita com afasia e hemiparesia direita em hipertensa tabagista com história familiar de hemorragia: a pergunta é a causa e a localização do sangramento.',
      pergunta: 'TC sem contraste e angiotomografia. Qual é o achado que responde à pergunta clínica?',
      achado: 'Aneurisma roto da cerebral média',
      veredito: 'Ruptura de aneurisma da artéria cerebral média esquerda com hematoma sylviano, subdural e intraparenquimatoso',
      correlacao: 'A cefaleia súbita com vômitos e rigidez de nuca anuncia sangue no espaço subaracnoideo; a afasia e a hemiparesia direita localizam o problema no hemisfério esquerdo. O aneurisma da cerebral média, dentro da fissura sylviana, rompeu formando um coágulo que comprime as áreas da linguagem e se estendeu ao subdural e ao parênquima. Mãe com hemorragia cerebral, hipertensão e tabagismo explicam os aneurismas múltiplos.',
      distratores: [
        d('Hemorragia hipertensiva dos núcleos da base', 'Também causa hemiparesia em hipertensa, mas o hematoma nasce no putâmen e não se acompanha de sangue na fissura sylviana, no subdural e nas cisternas, nem de aneurisma na angiotomografia.'),
        d('Hematoma subdural agudo espontâneo', 'Há um componente subdural, mas ele é fino; a maior parte do sangue está na fissura sylviana, e a angiotomografia mostra a fonte arterial.'),
        d('Transformação hemorrágica de infarto', 'Ocorre dias após um AVC isquêmico no território já infartado, com hipodensidade prévia. Aqui o início foi súbito com cefaleia e o sangue é subaracnoideo.'),
      ],
    },
  },

  'infarto-cerebelar': {
    tema: 'Vascular',
    titulo: 'Infarto cerebelar bilateral com hidrocefalia e herniação ascendente',
    resumo: 'Hipodensidade e edema dos dois hemisférios cerebelares, compressão do quarto ventrículo e do tronco, hidrocefalia e herniação transtentorial ascendente.',
    protocolo: 'TC de crânio sem contraste, reconstruções axial e sagital',
    series: ['Axial', 'Sagital'],
    rotulos: {
      'obstructed outflow': r('Quarto ventrículo comprimido', 'O cerebelo inchado apaga o quarto ventrículo e bloqueia a saída do líquor.',
        'O quarto ventrículo fica entre o cerebelo e a ponte. Quando os hemisférios cerebelares incham, ele é espremido até virar uma fenda ou desaparecer, e o líquor dos ventrículos de cima não consegue sair. O resultado é hidrocefalia aguda obstrutiva, que pode matar em horas.',
        'Infarto cerebelar com quarto ventrículo apagado pede neurocirurgia de sobreaviso: derivação ou craniectomia suboccipital.'),
      'Prominent hypodensity': r('Hipodensidade dos hemisférios cerebelares', 'Os dois hemisférios cerebelares estão escuros e inchados.',
        'O tecido cerebelar infartado acumula água e perde densidade, com apagamento das folhas cerebelares. O acometimento bilateral sugere oclusão na circulação posterior — artéria basilar ou as duas vertebrais —, já que cada cerebelar inferior posterior nutre um lado.'),
      'spinning top appearance': r('Mesencéfalo em pião', 'O mesencéfalo comprimido de cima para baixo ganha forma de pião no sagital.',
        'Com o cerebelo empurrando para cima pela incisura do tentório, o mesencéfalo é comprimido e deformado. Na reconstrução sagital, o tronco perde a forma normal e lembra um pião. É sinal de herniação transtentorial ascendente avançada.'),
      'effaced quadrigeminal cistern': r('Cisterna quadrigeminal apagada', 'A cisterna atrás do mesencéfalo desaparece pela compressão.',
        'A cisterna quadrigeminal é um espaço de líquor atrás do mesencéfalo, logo acima do cerebelo. Quando o cerebelo sobe, ele ocupa esse espaço, que deixa de aparecer. Cisternas apagadas significam fossa posterior sem reserva de espaço.'),
      'upward herniation': r('Herniação ascendente', 'O vérmis cerebelar sobe pela incisura do tentório.',
        'Na fossa posterior não há para onde o tecido inchado ir: ele sobe pela incisura do tentório ou desce pelo forame magno. A herniação ascendente comprime o mesencéfalo e o aqueduto; a descendente, das tonsilas, comprime o bulbo e causa parada respiratória.',
        'Drenar só os ventrículos de cima numa fossa posterior apertada pode agravar a herniação ascendente; a descompressão suboccipital resolve a causa.'),
      compression: r('Compressão da ponte e do mesencéfalo', 'O tronco encefálico achatado contra o clivo.',
        'O tronco fica entre o clivo à frente e o cerebelo atrás. O cerebelo edemaciado o empurra contra o osso, comprimindo núcleos e vias vitais. Rebaixamento de consciência em infarto cerebelar indica essa compressão e é indicação de cirurgia.'),
    },
    achados: [
      'Hipodensidade e edema dos dois hemisférios cerebelares, com apagamento das folhas e perda da diferenciação córtico-subcortical.',
      'Apagamento do quarto ventrículo com hidrocefalia obstrutiva.',
      'Herniação transtentorial ascendente com cisterna quadrigeminal apagada e mesencéfalo em pião.',
      'Compressão da ponte e do mesencéfalo contra o clivo.',
    ],
    armadilhas: [
      'O infarto cerebelar se apresenta como vertigem e vômitos e é confundido com labirintite; o exame HINTS e a marcha ajudam.',
      'A TC é pouco sensível para isquemia da fossa posterior nas primeiras horas; a ressonância com difusão é superior.',
      'O edema máximo ocorre entre o segundo e o quarto dia: o paciente que chegou bem pode piorar.',
    ],
    conduta: 'Internação em unidade neurológica, vigilância do nível de consciência, derivação ventricular para hidrocefalia e craniectomia suboccipital descompressiva se houver compressão do tronco; investigação da circulação posterior.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Homem de 66 anos, motorista aposentado.',
      queixa: 'Tontura intensa, vômitos e incapacidade de ficar em pé há dois dias, agora sonolento.',
      historia: 'Há dois dias acordou com tontura giratória, vômitos e desequilíbrio, sem conseguir andar. Foi a uma UPA, recebeu antiemético e o diagnóstico de labirintite. Hoje a família o encontrou muito sonolento, com fala arrastada e dor na nuca.',
      antecedentes: [
        'Pessoais: fibrilação atrial sem anticoagulação, diabetes e hipertensão',
        'Pessoais: AIT com visão dupla há seis meses',
        'Familiares: pai com AVC aos 70 anos',
        'Hábitos: tabagista ativo de 40 maços-ano',
      ],
      vitais: { pa: '176 × 98 mmHg', fc: '108 bpm, irregular', fr: '14 irpm', satO2: '94% em ar ambiente', temp: '36,7 °C' },
      exame: [
        'Glasgow 11, sonolento',
        'Ataxia de tronco e dismetria bilateral',
        'Nistagmo vertical',
        'Disartria e paresia do olhar para cima',
      ],
      pedido: 'Síndrome vertiginosa aguda diagnosticada como labirintite, evoluindo com rebaixamento em paciente com fibrilação atrial: a pergunta é se há lesão da fossa posterior e se ela comprime o tronco.',
      pergunta: 'TC de crânio sem contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Infarto cerebelar bilateral com herniação',
      veredito: 'Infarto cerebelar bilateral com hidrocefalia obstrutiva e herniação transtentorial ascendente',
      correlacao: 'Vertigem com incapacidade de andar, nistagmo vertical e fibrilação atrial não anticoagulada: um êmbolo ocluiu a circulação posterior e infartou os dois hemisférios cerebelares. O edema, que atinge o máximo entre o segundo e o quarto dia, apagou o quarto ventrículo — hidrocefalia — e empurrou o cerebelo para cima pela incisura do tentório, comprimindo o mesencéfalo: a sonolência e a paresia do olhar vertical.',
      distratores: [
        d('Neurite vestibular aguda', 'Dá vertigem e vômitos intensos, mas o paciente anda com ajuda, o nistagmo é horizontal e unidirecional, o teste do impulso cefálico é alterado e a TC é normal.'),
        d('Hemorragia cerebelar hipertensiva', 'Também comprime o quarto ventrículo e o tronco, mas aparece como coleção hiperdensa em um hemisfério, não como hipodensidade bilateral simétrica.'),
        d('Metástases cerebelares com edema', 'Formam lesões nodulares com edema e realce anelar, de evolução em semanas, em paciente com câncer conhecido. Seriam lesões nodulares com edema ao redor e realce anelar, em pessoa com câncer conhecido, crescendo em semanas e não de um dia para o outro.'),
      ],
    },
  },
}
