import { d, r, type ConteudoCaso } from './casos-imagem-tipos'

/** Segunda leva de TC — abdome, parte 3 (pâncreas, baço, rim, pelve). Pacientes fictícios. */
export const CASOS_TC_L2_ABDOME_3: Record<string, ConteudoCaso> = {
  'pancreatite-cronica': {
    tema: 'Pâncreas',
    titulo: 'Pancreatite crônica calcificante com pseudocisto calcificado',
    resumo: 'Pâncreas volumoso com calcificações parenquimatosas e intraductais extensas, ducto principal dilatado, áreas sem realce e pseudocisto calcificado na cauda.',
    protocolo: 'TC de abdome sem e com contraste, fase portal',
    series: ['Com contraste', 'Sem contraste'],
    rotulos: {
      'indistinct and irregular margi': r('Contornos irregulares e mal definidos', 'O pâncreas perdeu o contorno lobulado normal e tem bordas borradas.',
        'A inflamação repetida substitui o tecido glandular por fibrose, deixando o contorno irregular e mal definido. Áreas que deixam de realçar indicam parênquima destruído ou um surto agudo sobre a doença crônica. Essa perda de tecido explica a insuficiência exócrina e endócrina.'),
      'Intraductal calcifications are': r('Cálculos dentro do ducto', 'Calcificações no ducto pancreático principal.',
        'Proteínas precipitadas no suco pancreático formam tampões que calcificam dentro dos ductos. Os cálculos obstruem o fluxo, o ducto dilata a montante e a pressão alta causa a dor crônica. Cálculos no ducto principal podem ser retirados por endoscopia ou litotripsia.',
        'Calcificações pancreáticas na radiografia simples, sobre a coluna lombar alta, já sugerem pancreatite crônica.'),
      'pancreas is bulky': r('Pâncreas volumoso', 'Cabeça e corpo aumentados, com inflamação ativa.',
        'Na pancreatite crônica avançada o pâncreas costuma atrofiar, mas pode estar aumentado durante uma agudização ou quando há massa inflamatória. Massa na cabeça em pancreatite crônica exige afastar adenocarcinoma, cujo risco é maior nesses pacientes.'),
      'calcified pancreatic pseudocys': r('Pseudocisto calcificado na cauda', 'Coleção arredondada com parede calcificada na cauda do pâncreas.',
        'Pseudocistos são coleções de suco pancreático envoltas por parede fibrosa, sem epitélio, formadas após episódios de pancreatite. Os antigos podem calcificar a parede. Podem comprimir o estômago, infectar ou romper vasos e formar pseudoaneurismas.'),
      'Intraductal calcifications': r('Cálculos ductais no corte sem contraste', 'Os mesmos cálculos, bem visíveis sem contraste.',
        'Sem contraste, as calcificações aparecem com mais nitidez, porque não competem com o realce do parênquima. Por isso a fase sem contraste é útil na pancreatite crônica e para diferenciar calcificação de contraste em vasos.'),
      'Extensive calcifications': r('Calcificações parenquimatosas difusas', 'Calcificações espalhadas por todo o pâncreas.',
        'Calcificações difusas são o marco da pancreatite crônica de longa data, sobretudo a alcoólica e a tropical. Elas indicam glândula muito destruída, com risco alto de diabetes e esteatorreia.'),
    },
    achados: [
      'Pâncreas volumoso com contornos irregulares e áreas de cabeça, colo e corpo sem realce.',
      'Calcificações difusas no parênquima e cálculos no ducto pancreático principal, que está dilatado.',
      'Cauda com áreas de realce preservado e pseudocisto de parede calcificada.',
    ],
    armadilhas: [
      'Pancreatite crônica aumenta o risco de adenocarcinoma; massa focal ou estenose de ducto merecem investigação.',
      'Pseudocistos podem erodir artérias e formar pseudoaneurismas que sangram.',
      'A TC pode ser normal nas fases iniciais; a ressonância e a ecoendoscopia são mais sensíveis.',
    ],
    conduta: 'Suspensão do álcool e do tabaco, analgesia, reposição de enzimas pancreáticas, rastreio de diabetes e tratamento endoscópico ou cirúrgico dos cálculos e do pseudocisto sintomático.',
    vinheta: {
      cenario: 'Ambulatório de gastroenterologia',
      identificacao: 'Homem de 49 anos, pedreiro.',
      queixa: 'Dor na barriga que vai para as costas há anos e fezes gordurosas.',
      historia: 'Há cinco anos tem dor epigástrica que irradia em faixa para o dorso, pior depois de comer e de beber, e que melhora inclinado para frente. Teve quatro internações por pancreatite. Há um ano as fezes ficaram volumosas, claras, gordurosas, que boiam, e emagreceu 9 kg. Há seis meses descobriu diabetes.',
      antecedentes: [
        'Pessoais: quatro episódios de pancreatite aguda',
        'Pessoais: diabetes recente em uso de insulina',
        'Familiares: pai etilista falecido por cirrose',
        'Hábitos: etilismo de meio litro de cachaça por dia há 25 anos, tabagista',
      ],
      vitais: { pa: '128 × 78 mmHg', fc: '82 bpm', fr: '16 irpm', satO2: '98% em ar ambiente', temp: '36,5 °C' },
      exame: [
        'Emagrecido',
        'Dor à palpação epigástrica',
        'Massa endurecida mal definida no hipocôndrio esquerdo',
        'Elastase fecal muito baixa',
      ],
      pedido: 'Dor abdominal crônica, esteatorreia e diabetes em etilista pesado com pancreatites de repetição: a pergunta é o estado do pâncreas.',
      pergunta: 'TC de abdome. Qual é o achado que responde à pergunta clínica?',
      achado: 'Pancreatite crônica calcificante',
      veredito: 'Pancreatite crônica calcificante com cálculos ductais, ducto dilatado e pseudocisto calcificado',
      correlacao: 'Décadas de álcool e episódios repetidos de pancreatite trocaram o tecido glandular por fibrose e calcificações. A perda de tecido exócrino explica a esteatorreia e a elastase baixa; a perda de ilhotas, o diabetes. Os cálculos que obstruem o ducto mantêm a dor, e o pseudocisto calcificado na cauda é a massa palpável.',
      distratores: [
        d('Adenocarcinoma de pâncreas com metástases', 'Também causa dor nas costas, emagrecimento e diabetes, mas forma massa hipoatenuante focal com ducto cortado abruptamente, sem calcificações difusas.'),
        d('Pancreatite aguda edematosa recorrente', 'Cada surto aumenta o pâncreas com densificação da gordura, mas sem calcificações nem cálculos ductais, e sem insuficiência exócrina permanente.'),
        d('Doença celíaca com má absorção', 'Causa esteatorreia e emagrecimento por lesão da mucosa do delgado, com pâncreas normal e anticorpos antitransglutaminase positivos.'),
      ],
    },
  },

  'pseudoaneurisma-visceral': {
    tema: 'Vascular',
    titulo: 'Pseudoaneurisma visceral com hematoma epigástrico',
    resumo: 'Hematoma epigástrico volumoso com pseudoaneurisma central de ramo da mesentérica superior, pseudocisto pancreático e dilatação das vias biliares e do ducto pancreático.',
    protocolo: 'TC de abdome sem contraste e angiotomografia arterial',
    series: ['Fase arterial', 'Sem contraste'],
    rotulos: {
      'moderate biliary dilatation': r('Dilatação biliar por compressão', 'Vias biliares dilatadas pela compressão do colédoco pelo hematoma.',
        'O hematoma volumoso no epigástrio comprime o hilo hepático e o colédoco, e a bile para de escoar. A icterícia nesse cenário não vem de cálculo nem de tumor, mas do efeito de massa do sangue, e tende a melhorar quando o hematoma é reabsorvido ou drenado.'),
      'pancreatic duct dilatation': r('Ducto pancreático dilatado', 'Ducto de Wirsung dilatado até 4,2 mm.',
        'Dilatação do ducto pancreático com cabeça não visualizada sugere pancreatite crônica ou sequela de trauma do pâncreas. É a doença pancreática de base que corroeu a artéria e formou o pseudoaneurisma.'),
      'pancreatic pseudocyst': r('Pseudocisto pancreático', 'Coleção cística logo abaixo do hematoma.',
        'O suco pancreático do pseudocisto é rico em enzimas que digerem a parede das artérias vizinhas. A artéria enfraquecida rompe e forma um pseudoaneurisma: uma cavidade de sangue contida só por tecido fibroso, sem as camadas da parede arterial, que pode romper a qualquer momento.',
        'Pseudocisto que aumenta de tamanho ou fica denso pode ter sangrado dentro: procure pseudoaneurisma.'),
      'epigastric haematoma': r('Hematoma epigástrico', 'Coleção densa na TC sem contraste, com o pseudoaneurisma no centro.',
        'Sangue recente é hiperdenso na TC sem contraste. Na fase arterial, o pseudoaneurisma aparece como foco que realça igual à aorta dentro do hematoma. A ausência de extravasamento ativo indica que, por ora, o sangramento está contido, mas o risco de ruptura é alto.'),
    },
    achados: [
      'Hematoma epigástrico volumoso, hiperdenso na TC sem contraste.',
      'Pseudoaneurisma central, provavelmente de ramo da artéria mesentérica superior, sem extravasamento ativo.',
      'Pseudocisto pancreático e dilatação do ducto pancreático, com cabeça do pâncreas não identificada.',
      'Dilatação biliar por compressão do colédoco.',
    ],
    armadilhas: [
      'Pseudoaneurisma não tratado pode romper com hemorragia maciça; não espere sangrar de novo.',
      'Sangramento digestivo em paciente com pancreatite pode vir de pseudoaneurisma que rompe para o ducto — hemossucus pancreaticus.',
      'Na TC sem contraste o pseudoaneurisma passa despercebido dentro do hematoma; a fase arterial é obrigatória.',
    ],
    conduta: 'Arteriografia com embolização do pseudoaneurisma como primeira escolha, cirurgia se falhar ou houver instabilidade, drenagem biliar se necessário e tratamento da doença pancreática.',
    vinheta: {
      cenario: 'Pronto-socorro',
      identificacao: 'Homem de 51 anos, motorista de ônibus.',
      queixa: 'Dor forte no alto da barriga, tontura e olhos amarelados.',
      historia: 'Teve pancreatite grave há oito meses, com uma coleção que não foi drenada. Há três dias sente dor epigástrica intensa e contínua, e ontem desmaiou ao levantar. Hoje notou os olhos amarelos e a urina escura.',
      antecedentes: [
        'Pessoais: pancreatite aguda grave alcoólica há oito meses',
        'Pessoais: trauma abdominal fechado em acidente de moto há dois anos',
        'Familiares: sem coagulopatias',
        'Hábitos: etilismo, reduzido após a internação',
      ],
      vitais: { pa: '96 × 60 mmHg', fc: '118 bpm', fr: '22 irpm', satO2: '97% em ar ambiente', temp: '37,2 °C' },
      exame: [
        'Massa epigástrica dolorosa e pulsátil',
        'Icterícia leve',
        'Palidez',
        'Hemoglobina caiu de 12 para 8,6 g/dL',
      ],
      pedido: 'Dor epigástrica com queda da hemoglobina, síncope e massa pulsátil em paciente com pancreatite e coleção prévias: a pergunta é a origem do sangramento.',
      pergunta: 'TC de abdome sem contraste e fase arterial. Qual é o achado que responde à pergunta clínica?',
      achado: 'Pseudoaneurisma com hematoma epigástrico',
      veredito: 'Pseudoaneurisma de ramo da mesentérica superior com hematoma epigástrico, secundário a pancreatite',
      correlacao: 'As enzimas da coleção pancreática não drenada corroeram a parede de uma artéria vizinha, que rompeu e formou um pseudoaneurisma contido por tecido fibroso. O sangramento formou o hematoma epigástrico — massa pulsátil, queda da hemoglobina e síncope — e o hematoma comprimiu o colédoco, causando a icterícia.',
      distratores: [
        d('Pseudocisto pancreático não complicado', 'Seria coleção de densidade líquida e parede fina, sem sangue denso na fase sem contraste e sem foco que realça como artéria no centro.'),
        d('Úlcera duodenal com sangramento', 'Causaria hematêmese ou melena com sangue na luz do duodeno, sem hematoma epigástrico pulsátil nem compressão do colédoco. Não haveria saco vascular realçado junto à artéria.'),
        d('Aneurisma verdadeiro da artéria esplênica', 'Tem parede arterial completa, muitas vezes calcificada, em mulheres e grávidas, sem hematoma em volta e sem pancreatite. Não teria relação com pancreatite prévia nem com coleção em volta.'),
      ],
    },
  },

  'pancreatite-necrotizante': {
    tema: 'Pâncreas',
    titulo: 'Pancreatite aguda necrosante com trombose esplênica',
    resumo: 'Cabeça e corpo do pâncreas sem realce com processo uncinado preservado, densificação e líquido peripancreáticos, ascite e trombos não oclusivos nas veias esplênica e mesentérica.',
    protocolo: 'TC de abdome com contraste, fase portal, axial e coronal',
    series: ['Axial', 'Coronal'],
    rotulos: {
      Hypoenhancement: r('Necrose da cabeça e do corpo', 'Parte do pâncreas não realça — tecido sem circulação.',
        'O pâncreas viável realça de forma homogênea na fase portal. Áreas que ficam escuras são tecido morto: a necrose. A extensão da necrose, em menos ou mais de 30% ou 50% da glândula, entra no índice de gravidade tomográfico e prevê infecção e mortalidade.',
        'Necrose costuma ficar visível só depois de 72 horas; uma TC precoce pode subestimar a gravidade.'),
      'small clot': r('Pequeno trombo venoso', 'Falha de enchimento na veia esplênica.',
        'A veia esplênica passa por trás do pâncreas e é banhada pela inflamação. A agressão à parede e a estase favorecem a trombose, uma complicação frequente da pancreatite grave. Por isso a anticoagulação é discutida caso a caso.'),
      'peripancreatic stranding': r('Densificação peripancreática extensa', 'Gordura em volta do pâncreas inflamada e borrada.',
        'As enzimas que extravasam digerem a gordura em volta e causam inflamação intensa. A densificação extensa traduz a gravidade do processo inflamatório e acompanha a necrose. Ela não é necrose, mas indica gravidade.'),
      'nonocclusive clot': r('Trombo não oclusivo', 'Trombo parcial na veia esplênica e provavelmente na veia porta.',
        'Trombo que não obstrui toda a luz pode crescer ou ser reabsorvido. A trombose esplênica crônica causa hipertensão portal segmentar, com varizes gástricas isoladas — um diagnóstico a lembrar no seguimento.'),
      fluid: r('Coleção líquida peripancreática', 'Líquido junto ao pâncreas.',
        'Na pancreatite necrosante, as coleções agudas contêm líquido e restos de tecido morto — coleções necróticas agudas. Depois de quatro semanas ganham parede e passam a se chamar necrose encapsulada, que pode precisar de drenagem.'),
      necrosis: r('Necrose em evolução', 'Área do pâncreas que não realça no coronal.',
        'No corte coronal, a extensão da necrose ao longo da glândula fica mais clara. Necrose infectada, com gás ou piora clínica, é indicação de drenagem por via endoscópica ou percutânea, de preferência depois de quatro semanas.'),
      'Uncinate enhances': r('Processo uncinado preservado', 'A parte inferior da cabeça realça normalmente.',
        'Comparar com a parte que ainda realça ajuda a ter certeza de que o restante é necrose, e não apenas edema ou atraso do contraste. Preservar parte da glândula permite que a função pancreática seja mantida em parte depois da recuperação. Esse dado também orienta onde não há necrose a drenar.'),
      ascites: r('Ascite', 'Pequena quantidade de líquido livre na cavidade.',
        'Ascite na pancreatite resulta da inflamação peritoneal e, às vezes, de vazamento do ducto pancreático. Em grande volume, rica em amilase, sugere ruptura ductal — a ascite pancreática. Ascite é marcador de gravidade.'),
    },
    achados: [
      'Ausência de realce da cabeça e do corpo proximal do pâncreas, com processo uncinado preservado — necrose.',
      'Densificação peripancreática extensa com coleções líquidas e pequena ascite.',
      'Trombo não oclusivo na veia esplênica e provavelmente na veia porta.',
    ],
    armadilhas: [
      'A TC antes de 72 horas subestima a necrose; peça quando o diagnóstico é duvidoso ou o paciente não melhora.',
      'Gás dentro de coleção necrótica indica infecção, mas pode também vir de fístula com o intestino.',
      'Trombose esplênica leva a varizes gástricas isoladas; considere no paciente que sangra depois.',
    ],
    conduta: 'Suporte intensivo, hidratação guiada, nutrição enteral, anticoagulação discutida caso a caso para a trombose, antibiótico só para necrose infectada e drenagem escalonada, de preferência após quatro semanas.',
    vinheta: {
      cenario: 'Unidade de terapia intensiva',
      identificacao: 'Homem de 44 anos, metalúrgico, quinto dia de internação.',
      queixa: 'A dor da pancreatite não melhora e a falta de ar piorou.',
      historia: 'Internou com dor epigástrica intensa em faixa após uma bebedeira, com lipase 12 vezes o normal. Recebeu hidratação, mas no quinto dia continua com febre, distensão abdominal, falta de ar e diurese baixa.',
      antecedentes: [
        'Pessoais: obesidade e hipertrigliceridemia',
        'Pessoais: episódio de pancreatite leve há dois anos',
        'Familiares: pai com triglicerídeos muito altos',
        'Hábitos: etilismo de fim de semana pesado',
      ],
      vitais: { pa: '98 × 62 mmHg', fc: '122 bpm', fr: '30 irpm', satO2: '90% com cateter nasal', temp: '38,3 °C' },
      exame: [
        'Abdome distendido e doloroso',
        'Ruídos hidroaéreos ausentes',
        'Diurese de 20 mL por hora e creatinina subindo',
        'Proteína C reativa de 280 mg/L',
      ],
      pedido: 'Pancreatite aguda com falência de órgãos persistente no quinto dia: a pergunta é se há necrose e complicações vasculares.',
      pergunta: 'TC de abdome com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Pancreatite necrosante com trombose venosa',
      veredito: 'Pancreatite aguda necrosante da cabeça e do corpo com coleções e trombose da veia esplênica',
      correlacao: 'Álcool e triglicerídeos altos desencadearam uma pancreatite que, no quinto dia, mantém falência respiratória e renal: sinal de forma grave. A TC agora mostra o que não aparecia no início — áreas do pâncreas sem realce, a necrose — e a inflamação que trombosou a veia esplênica, que corre colada atrás da glândula.',
      distratores: [
        d('Pancreatite aguda intersticial edematosa', 'Aumenta o pâncreas e densifica a gordura, mas a glândula realça por inteiro, sem áreas de necrose, e costuma melhorar em poucos dias.'),
        d('Adenocarcinoma de pâncreas com obstrução', 'Forma massa hipoatenuante focal com ducto dilatado e corte abrupto, em paciente mais velho, sem quadro agudo com falência de órgãos.'),
        d('Isquemia mesentérica aguda venosa', 'Também pode ter trombose venosa e dor intensa, mas a alteração está nas alças, com parede espessa e realce reduzido, e o pâncreas realça.'),
      ],
    },
  },

  'infarto-esplenico': {
    tema: 'Vascular',
    titulo: 'Infarto esplênico global após embolização da artéria esplênica',
    resumo: 'Baço sem realce e liquefeito após embolização com molas da artéria esplênica, vaso atravessando o infarto, fígado cirrótico e líquido peri-hepático.',
    protocolo: 'TC de abdome com contraste, fase portal, axial e sagital',
    series: ['Axial', 'Sagital'],
    rotulos: {
      'cirrhotic pattern': r('Fígado cirrótico', 'Fígado de contornos nodulares e lobo caudado aumentado.',
        'A cirrose deixa o fígado com contorno serrilhado, caudado hipertrofiado e segmentos mediais atrofiados. Em cirróticos com hiperesplenismo — plaquetas muito baixas pelo baço grande —, a embolização da artéria esplênica é usada para reduzir a destruição de plaquetas.'),
      'traversing vessel': r('Vaso atravessando o infarto', 'Um vaso ainda contrastado passa pelo baço infartado.',
        'Vasos que atravessam a área sem realce sem desvio mostram que o tecido é infarto, e não abscesso. Abscessos empurram e afastam os vasos; o infarto deixa os vasos no lugar, porque não ocupa espaço como uma coleção.',
        'Ausência de gás e vasos atravessando a área ajudam a separar infarto liquefeito de abscesso esplênico.'),
      'splenic artery coiling': r('Molas na artéria esplênica', 'Material metálico denso no trajeto da artéria esplênica.',
        'As molas foram colocadas por cateterismo para ocluir a artéria. O metal gera artefato em estrias. A oclusão proximal da artéria esplênica reduz o fluxo; a embolização mais distal causa infartos, aqui de quase todo o baço.'),
      'splenic infarction': r('Infarto esplênico', 'Áreas do baço sem realce, em cunha ou difusas.',
        'O baço infartado não recebe contraste e aparece escuro. Infartos pequenos têm forma de cunha com a base na cápsula; infarto global deixa o órgão todo sem realce, com uma fina borda periférica que ainda realça pelos vasos da cápsula — o sinal da borda.'),
      'Rim of fluid': r('Líquido peri-hepático', 'Fina lâmina de líquido junto à ponta do fígado.',
        'Pequena quantidade de líquido livre em cirrótico pode ser ascite inicial ou reação ao infarto esplênico. Não exige drenagem, mas deve ser acompanhada. Esse líquido reacional costuma desaparecer quando a causa é tratada, e não precisa de punção.'),
      'peritoneal fat stranding': r('Densificação da gordura peritoneal', 'Gordura inflamada perto do fígado e do baço.',
        'A necrose do baço causa inflamação do peritônio vizinho, explicando a dor e a febre que costumam seguir a embolização — a síndrome pós-embolização. Ela também explica por que a dor do infarto pode ser difusa e não apenas no hipocôndrio esquerdo, confundindo o diagnóstico inicial.'),
      'splenic artery coiling. T': r('Molas no corte sagital', 'O material de embolização visto no plano sagital.',
        'O corte sagital mostra a posição das molas em relação ao hilo esplênico, confirmando que a oclusão foi distal o suficiente para infartar o órgão. O plano sagital mostra onde as molas foram colocadas em relação ao baço e quais territórios podem ter ficado sem sangue.'),
    },
    achados: [
      'Ausência de realce de quase todo o baço com liquefação — infarto global.',
      'Molas na artéria esplênica e vasos atravessando a área infartada.',
      'Sem gás no baço, o que fala contra abscesso.',
      'Fígado cirrótico, lâmina de líquido peri-hepático e densificação peritoneal.',
    ],
    armadilhas: [
      'Infarto liquefeito pode virar abscesso; gás ou parede que realça mudam o diagnóstico.',
      'Infarto esplênico espontâneo pede busca de fonte embólica cardíaca, trombofilia ou doença hematológica.',
      'O baço infartado não funciona: o paciente precisa das vacinas de asplênico.',
    ],
    conduta: 'Analgesia e observação da síndrome pós-embolização, antibiótico se houver suspeita de abscesso e vacinação contra germes encapsulados.',
    vinheta: {
      cenario: 'Enfermaria de hepatologia',
      identificacao: 'Homem de 57 anos, cirrótico, quarto dia após embolização esplênica.',
      queixa: 'Dor forte no lado esquerdo da barriga e febre.',
      historia: 'Tem cirrose por hepatite C com baço muito grande e plaquetas abaixo de 30 mil, e foi submetido a embolização da artéria esplênica para melhorar as plaquetas antes de uma cirurgia. Desde o segundo dia sente dor intensa no hipocôndrio esquerdo, que piora ao respirar, e febre baixa.',
      antecedentes: [
        'Pessoais: cirrose por hepatite C com derivação portossistêmica intra-hepática',
        'Pessoais: varizes esofágicas tratadas',
        'Familiares: sem doenças hematológicas',
        'Hábitos: abstinente de álcool há cinco anos',
      ],
      vitais: { pa: '112 × 68 mmHg', fc: '102 bpm', fr: '22 irpm', satO2: '95% em ar ambiente', temp: '38,0 °C' },
      exame: [
        'Dor à palpação do hipocôndrio esquerdo',
        'Murmúrio reduzido na base esquerda',
        'Plaquetas subiram para 90 mil',
        'Hemoculturas negativas',
      ],
      pedido: 'Dor no hipocôndrio esquerdo e febre após embolização esplênica: a pergunta é a extensão do infarto e se há abscesso.',
      pergunta: 'TC de abdome com contraste. Qual é o achado que responde à pergunta clínica?',
      achado: 'Infarto esplênico global',
      veredito: 'Infarto esplênico global e liquefeito após embolização, sem sinais de abscesso',
      correlacao: 'A embolização foi feita para reduzir a destruição de plaquetas pelo baço grande da cirrose — e funcionou, as plaquetas subiram. O preço é o infarto: dor, febre baixa e reação pleural, a síndrome pós-embolização. A TC mostra o baço todo sem realce, mas sem gás e com vasos atravessando a área, o que favorece infarto liquefeito e não abscesso.',
      distratores: [
        d('Abscesso esplênico pós-embolização', 'É a complicação temida, mas teria gás ou coleção com parede que realça e afasta os vasos, hemoculturas positivas e piora clínica.'),
        d('Ruptura esplênica com hemoperitônio', 'Daria líquido livre denso em volta do baço e na pelve com queda da hemoglobina, e não baço sem realce com vasos atravessando. Haveria choque com queda de hemoglobina.'),
        d('Trombose da veia esplênica isolada', 'Causa falha na veia e varizes gástricas, mas o baço continua realçando porque o fluxo arterial é mantido. O baço estaria congesto, sem áreas em cunha sem realce, e haveria varizes gástricas.'),
      ],
    },
  },
}
