import type { SubsecaoTC } from '../tipos'

export const abdomeSistemaVenosoCaval: SubsecaoTC = {
  id: 'sistema-venoso-caval',
  titulo: 'Sistema venoso caval',
  subtitulo: 'Veias hepáticas, cava inferior e veias renais — a via de retorno do abdome',
  secaoId: 'abdome',
  pasta: '/TC_ABDOME/TB_ABDOME_SISTEMA_VENOSO_CAVAL',
  ext: 'JPG',
  totalCortes: 36,
  orientacao: 'cranio-caudal',
  icone: 'branch',
  cor: 'azul',
  janelaPadrao: 'mediastinal',
  protocolo:
    'TC de abdome com contraste iodado endovenoso em fase venosa portal (60–80 s após a injeção), quando as veias hepáticas, a cava e as renais já estão homogeneamente opacificadas. A fase arterial (25–35 s) NÃO serve para avaliar o sistema caval — nela as veias ainda estão pouco opacificadas e a mistura de sangue contrastado com não contrastado produz falhas de enchimento que imitam trombo. Para suspeita de trombose crônica ou de invasão tumoral, acrescenta-se fase tardia (3 min).',
  introducao:
    'O sistema caval é a via final do retorno venoso de tudo o que está abaixo do diafragma, e a TC é o melhor exame para segui-lo do início ao fim. A lógica anatômica é simples e vale a pena fixá-la antes de olhar qualquer corte: a veia cava inferior nasce da junção das ilíacas comuns na altura de L5, sobe pelo retroperitônio SEMPRE à direita da aorta, recebe as renais no meio do caminho e, no segmento final, recebe as três veias hepáticas antes de atravessar o diafragma e desembocar no átrio direito. Duas assimetrias precisam ser decoradas porque explicam quase toda a patologia da região: a veia renal ESQUERDA é longa e passa entre a aorta e a artéria mesentérica superior (pinça aortomesentérica — origem da síndrome de quebra-nozes), enquanto a direita é curta e direta. E as veias hepáticas convergem para a cava como as três nervuras de um leque, dividindo o fígado em setores — é por elas que se define a anatomia segmentar de Couinaud, base de toda a cirurgia hepática. Percorrer esta série de cima para baixo é ver esse leque se formar, a cava crescer, as renais chegarem e o conjunto se bifurcar nas ilíacas.',
  roteiro: [
    { passo: '1. Confirme a fase', detalhe: 'Veias homogeneamente opacificadas = fase portal. Se a aorta está muito mais densa que a cava, você está na fase arterial e não deve laudar trombo.' },
    { passo: '2. Ache a cava à direita da aorta', detalhe: 'Em todos os cortes abdominais, aorta à esquerda da coluna e cava à direita. Essa dupla é a bússola do retroperitônio.' },
    { passo: '3. Suba até a confluência hepática', detalhe: 'No corte mais alto, procure as três veias hepáticas convergindo para a cava — o "sinal do Mercedes" ou leque hepático.' },
    { passo: '4. Desça e encontre as renais', detalhe: 'A esquerda cruza a linha média por baixo da mesentérica superior; a direita entra quase perpendicular. Ambas no nível de L1-L2.' },
    { passo: '5. Avalie o calibre e o contorno', detalhe: 'Cava colabada em fenda = hipovolemia. Cava distendida = sobrecarga direita. Falha de enchimento persistente = trombo.' },
    { passo: '6. Termine na bifurcação', detalhe: 'Nos cortes baixos, veja a cava se dividir nas ilíacas comuns, ao nível de L5.' },
  ],
  perolas: [
    'Regra de ouro do retroperitônio: aorta à ESQUERDA, cava à DIREITA. Se parecer o contrário, pense em situs inversus ou em cava esquerda (variante em 0,2–0,5%).',
    'A veia renal esquerda passa ENTRE a aorta e a mesentérica superior. A direita não passa por lugar nenhum — é curta e direta.',
    'Cava inferior "em fenda", achatada, com aorta de calibre normal: pense em hipovolemia grave (sinal da cava plana), muito relevante no politraumatizado.',
    'Trombo tumoral realça (tem neovascularização); trombo bland não realça. Essa é a diferença que separa carcinoma renal invasivo de trombose simples.',
    'As veias hepáticas não têm válvulas e correm ENTRE os segmentos; as veias portais correm DENTRO deles. É assim que se distingue uma da outra no parênquima.',
  ],
  estruturas: [
    {
      id: 'veia-hepatica-direita',
      nome: 'Veia hepática direita',
      categoria: 'veia',
      resumo: 'A maior das três veias hepáticas; corre no plano que separa os setores anterior e posterior do lobo direito.',
      morfologia: 'Percorre a fissura portal direita, no plano coronal oblíquo entre os segmentos VIII/V (anteriores) e VII/VI (posteriores). Costuma drenar diretamente na cava inferior, isolada das outras duas. Calibre de 6–10 mm perto da desembocadura.',
      funcao: 'Drena o setor posterior e parte do anterior do lobo direito, devolvendo à circulação sistêmica o sangue que chegou pela porta e pela artéria hepática. As veias hepáticas não possuem válvulas, o que faz delas um manômetro direto da pressão do átrio direito — motivo de refluírem contraste na insuficiência tricúspide.',
      densidade: 'Fase portal: 120–180 UH, homogênea. Sem contraste, são hipodensas em relação ao parênquima hepático (que é mais denso). Na esteatose, essa relação se inverte e as veias parecem hiperdensas contra um fígado escuro.',
      janela: 'Partes moles / hepática estreita.',
      comoIdentificar: 'Nos cortes mais altos do fígado, procure as três veias convergindo para a cava como as nervuras de um leque. A direita é a mais lateral e a que corre mais horizontalmente para a direita.',
      reparos: ['Veia cava inferior (destino comum)', 'Veia hepática média (medialmente)', 'Cúpula diafragmática (acima)'],
      clinica: 'A anatomia venosa hepática é o que define a ressecabilidade em cirurgia do fígado: as veias hepáticas delimitam os setores de Couinaud, e preservar a drenagem do remanescente é tão importante quanto preservar a irrigação. Uma hepatectomia direita, por exemplo, sacrifica a veia hepática direita — o que só é tolerável se a média e a esquerda estiverem íntegras.',
      alteracoes: [
        { nome: 'Síndrome de Budd-Chiari', achado: 'Não visualização ou afilamento das veias hepáticas, realce heterogêneo "em mosaico" do fígado, hipertrofia do lobo caudado (que drena direto na cava) e ascite.' },
        { nome: 'Invasão por hepatocarcinoma', achado: 'Trombo dentro da veia que REALÇA na fase arterial — sinal de trombo tumoral, não de trombose simples.' },
        { nome: 'Congestão passiva', achado: 'Veias hepáticas e cava dilatadas com refluxo precoce de contraste, realce hepático heterogêneo "em noz-moscada" — insuficiência cardíaca direita.' },
        { nome: 'Variante anatômica', achado: 'Veias hepáticas acessórias inferiores drenando direto na cava (presentes em até 30%), relevantes em transplante e ressecção.' },
      ],
      armadilhas: ['Na esteatose, veias hepáticas hiperdensas em relação ao parênquima podem simular contraste onde não há — cheque se o exame tem mesmo contraste.'],
    },
    {
      id: 'veia-hepatica-media',
      nome: 'Veia hepática média',
      categoria: 'veia',
      resumo: 'Corre na fissura portal principal — o plano que separa o lobo direito do esquerdo (linha de Cantlie).',
      morfologia: 'Situa-se no plano que vai da fossa da vesícula biliar à cava inferior. Em 60–85% das pessoas, une-se à veia hepática esquerda formando um tronco comum antes de entrar na cava.',
      funcao: 'Drena os segmentos IV, V e VIII — ou seja, territórios dos DOIS lobos. Essa drenagem compartilhada é o que torna a veia hepática média a estrutura mais delicada da cirurgia hepática e do transplante com doador vivo.',
      densidade: 'Fase portal: 120–180 UH.',
      janela: 'Partes moles / hepática.',
      comoIdentificar: 'É a veia central do leque, a que aponta na direção da vesícula biliar. Se você traçar uma linha da cava até a fossa vesicular, você desenhou o plano da veia hepática média — a divisão funcional do fígado.',
      reparos: ['Fossa da vesícula biliar (o plano da veia aponta para ela)', 'Veia cava inferior', 'Veia hepática esquerda (tronco comum frequente)'],
      clinica: 'No transplante com doador vivo, decidir se a veia hepática média vai com o enxerto ou fica com o doador é uma das decisões mais críticas do planejamento: sem ela, o segmento V/VIII do receptor pode congestionar; com ela, o doador é que fica em risco. A TC pré-operatória com reconstrução venosa existe basicamente para responder a essa pergunta.',
      alteracoes: [
        { nome: 'Trombose', achado: 'Falha de enchimento persistente; no contexto de Budd-Chiari, pode acometer as três veias.' },
        { nome: 'Compressão/deslocamento por massa', achado: 'Desvio do trajeto por tumor; a distância entre a lesão e a veia determina a margem cirúrgica possível.' },
        { nome: 'Tronco comum com a esquerda', achado: 'Variante presente na maioria; deve ser descrita no laudo pré-operatório.' },
      ],
    },
    {
      id: 'veia-hepatica-esquerda',
      nome: 'Veia hepática esquerda',
      categoria: 'veia',
      resumo: 'Menor das três; drena os segmentos II e III, correndo na fissura portal esquerda.',
      morfologia: 'Percorre o plano entre os segmentos II e III (setor lateral esquerdo). Une-se à média em tronco comum na maioria das pessoas. Recebe a veia da fissura do ligamento venoso.',
      funcao: 'Drena o lobo esquerdo anatômico (segmentos II e III). O segmento I (lobo caudado) é a exceção da regra: ele drena por veias curtas e independentes diretamente na cava — razão de hipertrofiar na síndrome de Budd-Chiari, quando é o único território com drenagem preservada.',
      densidade: 'Fase portal: 120–180 UH.',
      janela: 'Partes moles / hepática.',
      comoIdentificar: 'É a veia mais medial e mais à esquerda do leque, drenando o território à esquerda do ligamento falciforme.',
      reparos: ['Fissura do ligamento venoso', 'Veia hepática média (tronco comum)', 'Lobo caudado (posteroinferior)'],
      clinica: 'A hipertrofia do lobo caudado com atrofia dos demais setores, num fígado com veias hepáticas não visíveis, é praticamente diagnóstica de Budd-Chiari — e a explicação está na drenagem independente do caudado direto para a cava.',
      alteracoes: [
        { nome: 'Budd-Chiari', achado: 'Ausência de opacificação das veias hepáticas, hipertrofia do caudado, realce em mosaico e ascite.' },
        { nome: 'Trombo tumoral', achado: 'Trombo com realce arterial, expansivo, no contexto de hepatocarcinoma do lobo esquerdo.' },
      ],
    },
    {
      id: 'veia-cava-inferior',
      nome: 'Veia cava inferior',
      sinonimos: ['VCI'],
      categoria: 'veia',
      resumo: 'Maior veia do corpo; conduz ao átrio direito todo o retorno venoso abaixo do diafragma.',
      morfologia: 'Nasce em L5 da junção das ilíacas comuns, sobe no retroperitônio à DIREITA da aorta, percorre um sulco na face posterior do fígado e atravessa o diafragma pelo forame da veia cava (T8). Calibre variável — 15 a 25 mm — e seção que muda com a respiração e a volemia, indo do oval ao completamente achatado.',
      funcao: 'Retorno de dois terços do débito cardíaco. Sistema de baixa pressão e altíssima complacência: sua forma é um marcador direto do estado volêmico, e é exatamente essa colapsabilidade que a torna útil como termômetro hemodinâmico na TC de trauma.',
      densidade: 'Fase portal: 120–180 UH, homogênea. Na fase arterial, é comum ver-se heterogeneidade por mistura de contraste com sangue não opacificado das renais e das ilíacas — pseudotrombo.',
      janela: 'Partes moles.',
      comoIdentificar: 'Em qualquer corte abdominal, é a estrutura vascular à DIREITA da aorta, à frente e à direita dos corpos vertebrais. Rolando os cortes de baixo para cima, você vê as ilíacas se juntarem, o vaso engrossar, receber as renais e finalmente as hepáticas.',
      reparos: ['Aorta abdominal (à esquerda dela)', 'Corpos vertebrais (posteriores)', 'Lobo caudado do fígado (anterior, no segmento hepático)', 'Pilar diafragmático direito (posterolateral)'],
      clinica: 'A cava concentra achados de altíssimo valor. O "sinal da cava plana" — cava achatada em fenda no politraumatizado — indica hipovolemia grave e precede o colapso hemodinâmico. Do lado oposto, cava distendida com refluxo de contraste indica sobrecarga de câmaras direitas. E é aqui que carcinoma renal e hepatocarcinoma crescem para dentro do lúmen, formando trombo tumoral cujo nível craniano define a estratégia cirúrgica (infra-hepático, retro-hepático ou supradiafragmático).',
      alteracoes: [
        { nome: 'Trombose de cava (bland)', achado: 'Falha de enchimento que NÃO realça, com dilatação do vaso e realce da parede; colaterais lombares e ázigos dilatadas.' },
        { nome: 'Trombo tumoral', achado: 'Falha de enchimento que REALÇA na fase arterial (neovascularização), contínua com o tumor primário (rim, fígado, adrenal). O nível superior do trombo define a abordagem cirúrgica.' },
        { nome: 'Sinal da cava plana', achado: 'Cava achatada em fenda com aorta normal — hipovolemia grave. Em trauma, prediz necessidade de transfusão.' },
        { nome: 'Cava distendida', achado: 'Calibre aumentado com refluxo precoce de contraste e veias hepáticas dilatadas — insuficiência cardíaca direita, tamponamento, hipertensão pulmonar.' },
        { nome: 'Duplicação de cava', achado: 'Duas cavas abaixo das renais (variante em ~0,3%); relevante antes de colocar filtro de cava, que precisaria ser bilateral.' },
        { nome: 'Cava inferior esquerda', achado: 'Cava à esquerda da aorta abaixo das renais, cruzando para a direita no nível renal; variante rara mas armadilha cirúrgica.' },
        { nome: 'Continuação ázigos', achado: 'Ausência do segmento hepático da cava com ázigos muito dilatada no tórax; associada a poliesplenia e cardiopatias.' },
      ],
      armadilhas: [
        'Nunca diagnosticar trombo de cava na fase arterial: a mistura de sangue opacificado (renais) com não opacificado (ilíacas) cria falhas de enchimento em camadas que somem na fase portal.',
        'A cava pode estar quase virtual em pessoas magras e desidratadas sem que isso signifique doença — interprete junto ao contexto clínico.',
      ],
      medidas: [{ rotulo: 'Calibre habitual', valor: '15–25 mm' }],
    },
    {
      id: 'veia-renal-direita',
      nome: 'Veia renal direita',
      categoria: 'veia',
      resumo: 'Veia curta que liga diretamente o hilo renal direito à cava inferior.',
      morfologia: 'Mede apenas 2–4 cm, é praticamente horizontal e entra na cava quase perpendicularmente. Em geral não recebe tributárias importantes — ao contrário da esquerda. Situa-se anteriormente à artéria renal direita.',
      funcao: 'Drenagem do rim direito. Sua brevidade tem consequência prática direta: em transplante renal, o enxerto do rim direito tem pedículo venoso curto, o que dificulta a anastomose — motivo pela qual se prefere retirar o rim esquerdo do doador vivo.',
      densidade: 'Fase portal/nefrográfica: 120–180 UH.',
      janela: 'Partes moles.',
      comoIdentificar: 'No nível de L1-L2, é o vaso curto que sai do hilo renal direito e entra imediatamente na cava. "Curta e direta" é a descrição que a distingue da esquerda.',
      reparos: ['Hilo renal direito', 'Veia cava inferior (destino imediato)', 'Artéria renal direita (posterior a ela)', 'Segunda porção duodenal (anterior)'],
      clinica: 'Trombose de veia renal no adulto tem três grandes causas: síndrome nefrótica (sobretudo nefropatia membranosa), neoplasia renal e estados de hipercoagulabilidade. Na criança, desidratação grave. A TC mostra o rim aumentado, com nefrograma retardado e estriado, e falha de enchimento na veia.',
      alteracoes: [
        { nome: 'Trombose de veia renal', achado: 'Falha de enchimento com rim aumentado, nefrograma tardio e estriado, e edema perirrenal.' },
        { nome: 'Trombo tumoral de carcinoma renal', achado: 'Trombo que realça, contínuo com a massa renal, estendendo-se para a cava.' },
        { nome: 'Veias renais múltiplas', achado: 'Duas ou mais veias à direita, presentes em ~15%; informação obrigatória antes de nefrectomia de doador.' },
      ],
    },
    {
      id: 'veia-renal-esquerda',
      nome: 'Veia renal esquerda',
      categoria: 'veia',
      resumo: 'Veia longa que atravessa a linha média entre a aorta e a artéria mesentérica superior para alcançar a cava.',
      morfologia: 'Mede 6–10 cm — o triplo da direita. Cruza a linha média passando pela "pinça aortomesentérica": o ângulo entre a aorta (atrás) e a artéria mesentérica superior (à frente). Recebe a veia adrenal esquerda (acima), a veia gonadal esquerda (abaixo) e veias lombares.',
      funcao: 'Drena o rim esquerdo e, ao contrário da direita, funciona como coletor de outros territórios (adrenal e gonadal esquerdos). É por isso que a varicocele é preferencialmente esquerda: a veia gonadal esquerda drena em ângulo reto na renal, com coluna hidrostática maior, e sofre com qualquer aumento de pressão na renal.',
      densidade: 'Fase portal: 120–180 UH.',
      janela: 'Partes moles.',
      comoIdentificar: 'Procure o corte em que um vaso atravessa horizontalmente a linha média, passando entre a aorta e a artéria mesentérica superior. Esse "sanduíche" é inconfundível — nenhuma outra estrutura abdominal ocupa esse espaço.',
      reparos: ['Aorta (posterior)', 'Artéria mesentérica superior (anterior)', 'Cava inferior (destino)', 'Hilo renal esquerdo (origem)'],
      clinica: 'A síndrome de quebra-nozes (nutcracker) resulta da compressão da veia renal esquerda na pinça aortomesentérica, com hipertensão venosa renal e suas consequências: hematúria, dor no flanco esquerdo e varicocele. Na TC, mede-se a razão entre o calibre da veia no hilo e no ponto comprimido (razão > 4,9 sugere o diagnóstico) e o ângulo aortomesentérico (< 35° é estreito). A variante retroaórtica — em que a veia passa ATRÁS da aorta — é outra armadilha cirúrgica clássica.',
      alteracoes: [
        { nome: 'Síndrome de quebra-nozes', achado: 'Estreitamento na pinça aortomesentérica com dilatação a montante; razão de calibre > 4,9 e ângulo aortomesentérico < 35°; veia gonadal esquerda dilatada.' },
        { nome: 'Veia renal esquerda retroaórtica', achado: 'A veia passa ATRÁS da aorta em vez de à frente; variante em ~2%, com risco de lesão em cirurgia aórtica.' },
        { nome: 'Veia renal esquerda circumaórtica', achado: 'Um ramo passa à frente e outro atrás da aorta, formando um anel; variante em ~5%.' },
        { nome: 'Trombose', achado: 'Falha de enchimento; procurar síndrome nefrótica e neoplasia como causa.' },
      ],
      armadilhas: ['O estreitamento fisiológico da veia renal esquerda na pinça é comum em pessoas magras e assintomáticas — o diagnóstico de quebra-nozes é clínico-radiológico, nunca só radiológico.'],
      medidas: [{ rotulo: 'Comprimento', valor: '6–10 cm' }, { rotulo: 'Ângulo aortomesentérico normal', valor: '38°–65°' }],
    },
  ],
  quiz: [
    {
      pergunta: 'Qual estrutura passa entre a aorta e a artéria mesentérica superior?',
      alternativas: ['Veia renal direita', 'Veia renal esquerda', 'Veia cava inferior', 'Ducto torácico'],
      correta: 1,
      explicacao: 'A veia renal esquerda cruza a linha média pela pinça aortomesentérica. Sua compressão nesse ponto produz a síndrome de quebra-nozes, com hematúria, dor em flanco e varicocele à esquerda.',
    },
    {
      pergunta: 'Trombo dentro da veia cava inferior que REALÇA na fase arterial indica:',
      alternativas: ['Trombose bland (simples)', 'Trombo tumoral com neovascularização', 'Artefato de mistura de contraste', 'Filtro de cava'],
      correta: 1,
      explicacao: 'O trombo tumoral tem vascularização própria e realça; o trombo bland não. Essa distinção muda o estadiamento e a cirurgia no carcinoma de células renais e no hepatocarcinoma.',
    },
    {
      pergunta: 'Por que o lobo caudado hipertrofia na síndrome de Budd-Chiari?',
      alternativas: [
        'Porque recebe mais fluxo arterial',
        'Porque drena por veias curtas diretamente na cava, escapando da obstrução das veias hepáticas',
        'Porque é o segmento mais próximo do diafragma',
        'Por regeneração compensatória inespecífica',
      ],
      correta: 1,
      explicacao: 'O segmento I (caudado) tem drenagem venosa independente, por veias curtas que vão direto à cava. Quando as veias hepáticas se ocluem, ele é o único território com drenagem preservada e hipertrofia — enquanto o resto do fígado atrofia.',
    },
    {
      pergunta: 'Uma veia cava inferior achatada "em fenda" num politraumatizado sugere:',
      alternativas: ['Sobrecarga de volume', 'Hipovolemia grave', 'Trombose de cava', 'Compressão tumoral'],
      correta: 1,
      explicacao: 'É o sinal da cava plana. A cava tem alta complacência e colaba quando a volemia cai — o achado prediz necessidade de transfusão e precede o colapso hemodinâmico.',
    },
    {
      pergunta: 'Em qual fase de contraste deve-se avaliar o sistema venoso caval?',
      alternativas: ['Sem contraste', 'Arterial (25–35 s)', 'Venosa portal (60–80 s)', 'Qualquer fase serve'],
      correta: 2,
      explicacao: 'Só na fase portal as veias estão homogeneamente opacificadas. Na fase arterial, a mistura de sangue contrastado e não contrastado gera falhas de enchimento em camadas que imitam trombo — a maior fonte de falso-positivo da região.',
    },
  ],
}
