import type { SubsecaoTC } from '../tipos'

export const abdomeSistemaArterial: SubsecaoTC = {
  id: 'sistema-arterial',
  titulo: 'Sistema arterial',
  subtitulo: 'Aorta abdominal, tronco celíaco, mesentéricas, renais e ilíacas',
  secaoId: 'abdome',
  pasta: '/TC_ABDOME/TC_ABDOME_SISTEMA_ARTERIAL',
  ext: 'JPG',
  totalCortes: 54,
  orientacao: 'cranio-caudal',
  icone: 'heart',
  cor: 'vermelho',
  janelaPadrao: 'angio',
  protocolo:
    'Angio-TC de aorta abdominal: aquisição na fase arterial pura (25–35 s, disparada por rastreamento de bolus na aorta com limiar de ~150 UH), cortes submilimétricos, injeção rápida (4–5 mL/s) e reconstruções MIP e VR. A fase arterial é indispensável: na fase portal os ramos viscerais já perderam contraste e a origem do tronco celíaco e da mesentérica superior fica indistinguível da gordura vizinha. Para aneurisma, acrescenta-se série sem contraste (procurar hematoma mural) e tardia (endoleak).',
  introducao:
    'A árvore arterial abdominal é o roteiro anatômico mais previsível do corpo — e por isso o mais fácil de aprender, desde que se decore a ordem de saída dos ramos da aorta. Descendo do diafragma, a sequência é sempre a mesma: tronco celíaco (T12), artéria mesentérica superior (L1), artérias renais (L1-L2), artéria mesentérica inferior (L3) e bifurcação nas ilíacas comuns (L4). Fixar esses cinco níveis é o que permite dizer, com um único corte na tela, em que altura do abdome se está. A segunda ideia central é a das anastomoses: os territórios do celíaco, da mesentérica superior e da mesentérica inferior conversam entre si por arcadas — as pancreaticoduodenais ligam celíaco e mesentérica superior; a artéria marginal de Drummond e o arco de Riolan ligam mesentérica superior e inferior. Essas conexões explicam por que uma oclusão crônica lenta pode ser assintomática (dá tempo de colateralizar) enquanto uma embolia aguda infarta o intestino em horas. Percorrer esta série é acompanhar cada um desses ramos se desprender da aorta e ganhar seu órgão.',
  roteiro: [
    { passo: '1. Confirme a fase arterial', detalhe: 'Aorta muito densa, veias ainda escuras. Sem isso, os ramos viscerais somem.' },
    { passo: '2. Siga a aorta de cima para baixo', detalhe: 'Ela está sempre à esquerda da coluna e à esquerda da cava. Note o calibre em cada nível.' },
    { passo: '3. Marque os cinco níveis', detalhe: 'Celíaco (T12), mesentérica superior (L1), renais (L1-L2), mesentérica inferior (L3), bifurcação (L4).' },
    { passo: '4. Abra o tronco celíaco', detalhe: 'Procure o "tripé de Haller": gástrica esquerda (para cima), esplênica (para a esquerda) e hepática comum (para a direita).' },
    { passo: '5. Cheque as renais', detalhe: 'Uma de cada lado é o padrão, mas artérias renais múltiplas ocorrem em 25–30%. Conte sempre — muda a cirurgia e o transplante.' },
    { passo: '6. Termine nas ilíacas', detalhe: 'Bifurcação em L4, seguida da divisão em ilíaca interna e externa na altura da articulação sacroilíaca.' },
  ],
  perolas: [
    'Ordem de saída da aorta, decorada: TC-AMS-Renais-AMI-Bifurcação (T12, L1, L1-L2, L3, L4).',
    'Aneurisma de aorta abdominal: diâmetro ≥ 3 cm. Risco de ruptura sobe muito acima de 5,5 cm no homem e 5,0 cm na mulher.',
    'Artéria hepática direita substituída saindo da mesentérica superior é a variante mais importante do abdome: presente em ~15% e passa POSTERIOR à veia porta.',
    'Artérias renais múltiplas em 25–30% das pessoas. Se você "só achou uma", volte e procure a outra antes de laudar.',
    'Calcificação de aorta é o mapa da doença aterosclerótica: sua presença em paciente jovem obriga a investigar dislipidemia e tabagismo.',
  ],
  estruturas: [
    {
      id: 'aorta-abdominal',
      nome: 'Aorta abdominal',
      categoria: 'arteria',
      resumo: 'Continuação da aorta torácica abaixo do diafragma; irriga todas as vísceras abdominais e os membros inferiores.',
      morfologia: 'Entra pelo hiato aórtico (T12) e desce à esquerda da linha média, à frente dos corpos vertebrais, até se bifurcar em L4. Calibre normal de 2,0–2,5 cm no início e 1,5–2,0 cm perto da bifurcação — ela AFINA progressivamente à medida que cede ramos.',
      funcao: 'Distribuição do débito sistêmico ao abdome, à pelve e aos membros inferiores. Sua parede tem três camadas cuja integridade determina toda a patologia aórtica: a íntima (que rompe na dissecção), a média (que se degenera no aneurisma) e a adventícia (última barreira antes da ruptura livre).',
      densidade: 'Fase arterial: 250–450 UH. Sem contraste: 40–50 UH, com calcificações murais frequentes (> 300 UH).',
      janela: 'Angio para a luz; sem contraste em janela mediastinal para hematoma mural.',
      comoIdentificar: 'Estrutura circular, muito densa na fase arterial, à ESQUERDA da coluna e à esquerda da cava. Presente em todos os cortes abdominais — é o ponto de referência mais estável do exame.',
      reparos: ['Veia cava inferior (à direita)', 'Corpos vertebrais (posteriores)', 'Pilares diafragmáticos (laterais, no início)', 'Pâncreas e veia renal esquerda (anteriores, no nível de L1)'],
      clinica: 'O aneurisma de aorta abdominal é o achado que mais justifica a existência desta série. Definido por diâmetro ≥ 3 cm, é geralmente assintomático até romper, com mortalidade global de 80–90%. A TC mede o diâmetro máximo (de parede externa a parede externa, perpendicular ao eixo), o colo proximal, a extensão às ilíacas e a relação com as renais — dados que decidem entre cirurgia aberta e endoprótese. Sinais de ruptura iminente incluem crescimento rápido (> 5 mm em 6 meses), o "sinal do crescente hiperdenso" (hematoma na parede do trombo) e a descontinuidade da calcificação intimal.',
      alteracoes: [
        { nome: 'Aneurisma de aorta abdominal', achado: 'Dilatação ≥ 3 cm, geralmente fusiforme e infrarrenal, com trombo mural laminado e calcificação intimal deslocada para dentro.' },
        { nome: 'Ruptura de aneurisma', achado: 'Hematoma retroperitoneal com extravasamento de contraste; sinal do "crescente hiperdenso" na parede indica ruptura iminente.' },
        { nome: 'Dissecção tipo B com extensão abdominal', achado: 'Flap intimal dividindo luz verdadeira (menor, mais opacificada) e falsa; avaliar se os ramos viscerais nascem da luz verdadeira ou falsa — isso define a má perfusão.' },
        { nome: 'Aneurisma inflamatório', achado: 'Espessamento parietal com realce e fibrose periaórtica que engloba os ureteres, causando hidronefrose.' },
        { nome: 'Aortite infecciosa (micótica)', achado: 'Aneurisma sacular de crescimento rápido, contorno lobulado, gás na parede e coleção periaórtica.' },
        { nome: 'Doença oclusiva aortoilíaca (síndrome de Leriche)', achado: 'Oclusão da aorta distal e das ilíacas, com claudicação, impotência e ausência de pulsos femorais; colaterais lombares e epigástricas hipertrofiadas.' },
      ],
      armadilhas: ['Medir a aorta no plano axial quando ela é tortuosa superestima o diâmetro em até 20% — a medida válida é perpendicular ao eixo do vaso.'],
      medidas: [{ rotulo: 'Calibre normal proximal', valor: '2,0–2,5 cm' }, { rotulo: 'Aneurisma', valor: '≥ 3,0 cm' }, { rotulo: 'Limiar cirúrgico', valor: '5,5 cm (homem) / 5,0 cm (mulher)' }],
    },
    {
      id: 'arteria-gastrica-esquerda',
      nome: 'Artéria gástrica esquerda',
      sinonimos: ['artéria coronária estomáquica'],
      categoria: 'arteria',
      resumo: 'Menor ramo do tronco celíaco; sobe para a cárdia e desce pela pequena curvatura do estômago.',
      morfologia: 'Ramo mais fino e mais superior do tronco celíaco. Sobe e à esquerda até a junção esofagogástrica, depois curva-se e desce ao longo da pequena curvatura, anastomosando-se com a gástrica direita. Emite ramos esofágicos.',
      funcao: 'Irriga a pequena curvatura, a cárdia e o esôfago distal. Suas tributárias esofágicas são as veias que se transformam em varizes esofágicas na hipertensão portal — a mesma região, do lado venoso.',
      densidade: 'Fase arterial: 250–400 UH; vaso fino, exige cortes finos e MIP.',
      janela: 'Angio.',
      comoIdentificar: 'Do tronco celíaco, é o ramo que sobe. Se você identificou o tripé e viu um ramo indo para CIMA e para a esquerda, é a gástrica esquerda.',
      reparos: ['Tronco celíaco (origem)', 'Junção esofagogástrica (destino inicial)', 'Pequena curvatura gástrica'],
      clinica: 'É a artéria embolizada no tratamento endovascular de sangramento gástrico alto refratário. Também é a origem de uma variante importantíssima: a artéria hepática esquerda substituída ou acessória, presente em 10–15% das pessoas, que corre no ligamento gastro-hepático — e pode ser inadvertidamente seccionada em gastrectomia ou fundoplicatura, causando isquemia hepática esquerda.',
      alteracoes: [
        { nome: 'Artéria hepática esquerda substituída', achado: 'Ramo saindo da gástrica esquerda e correndo no ligamento gastro-hepático até a fissura do ligamento venoso; presente em 10–15%.' },
        { nome: 'Sangramento gástrico ativo', achado: 'Extravasamento de contraste na luz gástrica na fase arterial, com aumento na fase tardia.' },
        { nome: 'Pseudoaneurisma', achado: 'Dilatação sacular após pancreatite ou úlcera penetrante.' },
      ],
    },
    {
      id: 'arteria-esplenica',
      nome: 'Artéria esplênica',
      categoria: 'arteria',
      resumo: 'Maior ramo do tronco celíaco; percorre a borda superior do pâncreas em trajeto tortuoso até o baço.',
      morfologia: 'Segue para a esquerda, acima da veia esplênica, ao longo da borda superior do corpo e da cauda do pâncreas. Torna-se progressivamente mais tortuosa com a idade — "serpentina" é a descrição clássica. Emite ramos pancreáticos, gástricas curtas e a gastroepiploica esquerda.',
      funcao: 'Irriga o baço, boa parte do pâncreas e o fundo gástrico. É uma artéria terminal para o baço: sua oclusão causa infarto esplênico, ao contrário do fígado, protegido pela dupla irrigação.',
      densidade: 'Fase arterial: 250–400 UH; calcificação mural é comum em idosos.',
      janela: 'Angio; reconstrução coronal ou MIP para ver a tortuosidade inteira.',
      comoIdentificar: 'É o ramo que sai do tripé e segue para a ESQUERDA, acima e mais tortuoso que a veia esplênica. Em cortes axiais, ela aparece como vários pontinhos densos em sequência ao longo do pâncreas — isso é a serpentina cortada em vários pontos.',
      reparos: ['Tronco celíaco (origem)', 'Borda superior do pâncreas (trajeto)', 'Veia esplênica (abaixo dela)', 'Hilo esplênico (destino)'],
      clinica: 'É o sítio mais comum de aneurisma visceral (60% de todos), com predileção por mulheres multíparas e portadoras de hipertensão portal. Aneurismas > 2 cm, em gestantes ou em candidatas a transplante hepático têm indicação de tratamento pelo risco de ruptura, que é catastrófica. Pseudoaneurismas da esplênica são complicação clássica de pancreatite, por digestão enzimática da parede.',
      alteracoes: [
        { nome: 'Aneurisma de artéria esplênica', achado: 'Dilatação sacular, muitas vezes calcificada em anel; o mais comum dos aneurismas viscerais. Tratar se > 2 cm, gestante ou pré-transplante.' },
        { nome: 'Pseudoaneurisma pós-pancreatite', achado: 'Coleção com realce arterial em continuidade com a artéria, dentro ou junto a um pseudocisto — risco alto de sangramento.' },
        { nome: 'Infarto esplênico', achado: 'Área hipodensa em cunha, de base capsular e vértice hilar, sem realce.' },
        { nome: 'Envolvimento por neoplasia de corpo/cauda pancreática', achado: 'Contato circunferencial; ao contrário da mesentérica superior, o envolvimento esplênico não impede a ressecção (pancreatectomia distal com esplenectomia).' },
      ],
    },
    {
      id: 'tronco-celiaco',
      nome: 'Tronco celíaco',
      sinonimos: ['tripé de Haller', 'artéria celíaca'],
      categoria: 'arteria',
      resumo: 'Primeiro ramo visceral da aorta abdominal; divide-se em gástrica esquerda, esplênica e hepática comum.',
      morfologia: 'Tronco curto — 1 a 2 cm apenas — que sai da face ANTERIOR da aorta ao nível de T12, imediatamente abaixo do hiato aórtico. Divide-se no clássico tripé de Haller. Irriga o intestino anterior embrionário (foregut): esôfago distal, estômago, duodeno proximal, fígado, pâncreas e baço.',
      funcao: 'Aporte arterial de todo o andar supramesocólico. Suas anastomoses com a mesentérica superior pelas arcadas pancreaticoduodenais permitem que a oclusão lenta de um dos dois seja compensada pelo outro.',
      densidade: 'Fase arterial: 250–450 UH.',
      janela: 'Angio; a reconstrução SAGITAL é indispensável — a origem sai para a frente e o corte axial mostra só um ponto.',
      comoIdentificar: 'No primeiro corte abaixo do diafragma em que você vê um vaso saindo da FRENTE da aorta, esse é o tronco celíaco. Um ou dois cortes adiante, ele se abre no tripé — e a imagem em "asa de gaivota" (esplênica para a esquerda, hepática comum para a direita) é inconfundível.',
      reparos: ['Aorta (origem anterior, T12)', 'Pilares diafragmáticos e ligamento arqueado mediano (acima)', 'Corpo do pâncreas (abaixo)', 'Lobo caudado do fígado (à direita)'],
      clinica: 'A síndrome do ligamento arqueado mediano (Dunbar) é a compressão extrínseca do tronco celíaco pelas fibras dos pilares diafragmáticos, produzindo dor abdominal pós-prandial, perda de peso e sopro epigástrico em pacientes jovens. Na TC sagital, o achado é uma indentação em "gancho" na face SUPERIOR do tronco, que acentua na EXPIRAÇÃO e melhora na inspiração — a variação respiratória é o que diferencia essa compressão externa de uma placa aterosclerótica, que é fixa e afeta a face inferior/ostial.',
      alteracoes: [
        { nome: 'Síndrome do ligamento arqueado mediano', achado: 'Indentação em gancho na face superior, dilatação pós-estenótica e piora na expiração. Diagnóstico feito no plano sagital.' },
        { nome: 'Estenose aterosclerótica', achado: 'Placa calcificada ostial com estreitamento fixo; isquemia mesentérica crônica exige acometimento de pelo menos dois dos três troncos viscerais.' },
        { nome: 'Tronco celiacomesentérico', achado: 'Variante rara em que celíaco e mesentérica superior nascem juntos — a oclusão desse tronco único é catastrófica.' },
        { nome: 'Dissecção isolada', achado: 'Flap no tronco celíaco, geralmente espontânea em homens de meia-idade.' },
      ],
      armadilhas: ['Não avaliar o tronco celíaco só no axial: a origem é anterior e o plano sagital é o único que mostra a compressão em gancho.'],
    },
    {
      id: 'arteria-hepatica-comum',
      nome: 'Artéria hepática comum',
      categoria: 'arteria',
      resumo: 'Ramo direito do tronco celíaco; dá origem à gastroduodenal e continua como hepática própria.',
      morfologia: 'Segue para a DIREITA a partir do tronco celíaco, ao longo da borda superior do pâncreas, até o ligamento hepatoduodenal. Ali emite a artéria gastroduodenal (que desce) e continua como hepática própria (que sobe).',
      funcao: 'Aporte arterial ao fígado (25% do fluxo, mas 50% do oxigênio), ao estômago, ao duodeno e à cabeça do pâncreas.',
      densidade: 'Fase arterial: 250–400 UH.',
      janela: 'Angio.',
      comoIdentificar: 'A partir do tripé, é o ramo que segue para a DIREITA. Siga-o e você chegará ao ponto em que ele se divide em gastroduodenal (para baixo) e hepática própria (para cima).',
      reparos: ['Tronco celíaco (origem)', 'Borda superior do pâncreas', 'Veia porta (posterior)', 'Bifurcação em gastroduodenal e hepática própria'],
      clinica: 'Antes de qualquer cirurgia hepatobiliopancreática, o mapeamento arterial é obrigatório porque as variantes são a regra, não a exceção: a artéria hepática direita substituída, saindo da mesentérica superior, ocorre em ~15% e passa POSTERIOR à veia porta e lateralmente ao colédoco — ela é lesada com facilidade na duodenopancreatectomia se não for identificada. A hepática esquerda substituída, saindo da gástrica esquerda, ocorre em 10–15%.',
      alteracoes: [
        { nome: 'Artéria hepática direita substituída', achado: 'Vaso saindo da mesentérica superior e subindo POSTERIOR à porta até o fígado direito; a variante mais importante da cirurgia abdominal.' },
        { nome: 'Estenose ostial', achado: 'Placa calcificada com estreitamento; relevante após transplante hepático, quando causa isquemia biliar.' },
        { nome: 'Pseudoaneurisma pós-cirúrgico', achado: 'Após duodenopancreatectomia, na topografia do coto da gastroduodenal — causa de hemorragia tardia grave.' },
      ],
    },
    {
      id: 'arteria-hepatica-propria',
      nome: 'Artéria hepática própria',
      categoria: 'arteria',
      resumo: 'Continuação da hepática comum após a saída da gastroduodenal; sobe no ligamento hepatoduodenal até o hilo.',
      morfologia: 'Sobe no ligamento hepatoduodenal, à esquerda do colédoco e à frente da veia porta, e se divide em ramos hepáticos direito e esquerdo. O ramo direito costuma cruzar POSTERIOR ao ducto hepático comum. Emite a artéria cística.',
      funcao: 'Único aporte arterial das vias biliares — fato de consequência clínica direta: a árvore biliar depende exclusivamente da artéria, sem suprimento portal. Por isso, trombose da artéria hepática após transplante causa necrose biliar isquêmica, e não apenas infarto do parênquima.',
      densidade: 'Fase arterial: 250–400 UH.',
      janela: 'Angio.',
      comoIdentificar: 'No hilo hepático, é a "orelha esquerda" do Mickey Mouse — anterior à porta e à esquerda do colédoco.',
      reparos: ['Veia porta (posterior)', 'Colédoco (à direita)', 'Ligamento hepatoduodenal (contém os três)'],
      clinica: 'A trombose da artéria hepática é a complicação vascular mais temida do transplante hepático: leva a necrose isquêmica das vias biliares, abscessos e perda do enxerto. A TC no pós-operatório procura ativamente o realce da artéria e a perviedade da anastomose. Já a artéria cística, seu ramo, é a estrutura seccionada na colecistectomia — e sua variação anatômica, junto com a do ducto cístico, explica boa parte das lesões biliares iatrogênicas.',
      alteracoes: [
        { nome: 'Trombose pós-transplante', achado: 'Ausência de opacificação arterial com áreas de infarto hepático e necrose biliar (bilomas centrais).' },
        { nome: 'Estenose da anastomose', achado: 'Estreitamento focal com fluxo distal reduzido; tratável por angioplastia.' },
        { nome: 'Aneurisma de artéria hepática', achado: 'Segundo aneurisma visceral mais comum; risco de fístula biliar (hemobilia).' },
      ],
    },
    {
      id: 'arteria-gastroduodenal',
      nome: 'Artéria gastroduodenal',
      sinonimos: ['AGD'],
      categoria: 'arteria',
      resumo: 'Ramo da hepática comum que desce atrás da primeira porção duodenal e forma as arcadas pancreaticoduodenais.',
      morfologia: 'Desce posteriormente ao bulbo duodenal e à frente da cabeça do pâncreas. Divide-se nas artérias pancreaticoduodenais superiores (anterior e posterior) e na gastroepiploica direita. As pancreaticoduodenais superiores anastomosam-se com as inferiores, ramos da mesentérica superior.',
      funcao: 'Irriga o duodeno, a cabeça do pâncreas e a grande curvatura gástrica. Fecha a anastomose entre os territórios celíaco e mesentérico superior — a via de salvamento quando um dos dois oclui lentamente.',
      densidade: 'Fase arterial: 250–400 UH.',
      janela: 'Angio.',
      comoIdentificar: 'A partir da hepática comum, é o ramo que DESCE, passando atrás do bulbo duodenal e à frente da cabeça do pâncreas.',
      reparos: ['Bulbo duodenal (anterior a ela)', 'Cabeça do pâncreas (posterior)', 'Colédoco distal (medial)'],
      clinica: 'A parede posterior do bulbo duodenal é o local clássico da úlcera péptica que sangra maciçamente — e ela sangra porque a artéria gastroduodenal está imediatamente atrás. Uma úlcera que penetra a parede posterior erode a artéria e produz hemorragia digestiva alta de grande volume, que a angio-TC mostra como extravasamento ativo de contraste na luz duodenal e que se trata por embolização.',
      alteracoes: [
        { nome: 'Sangramento por úlcera péptica posterior', achado: 'Extravasamento de contraste na luz duodenal na fase arterial, com aumento na fase venosa; a AGD é o vaso culpado.' },
        { nome: 'Pseudoaneurisma pós-pancreatite ou pós-Whipple', achado: 'Dilatação sacular na topografia do coto arterial; complicação hemorrágica tardia de alta letalidade.' },
        { nome: 'Colateralização', achado: 'AGD e arcadas hipertrofiadas na oclusão crônica do tronco celíaco ou da mesentérica superior.' },
      ],
    },
    {
      id: 'arteria-mesenterica-superior',
      nome: 'Artéria mesentérica superior',
      sinonimos: ['AMS'],
      categoria: 'arteria',
      resumo: 'Segundo ramo visceral da aorta; irriga todo o intestino médio, do duodeno distal ao cólon transverso.',
      morfologia: 'Sai da face anterior da aorta em L1, cerca de 1 cm abaixo do tronco celíaco, e desce quase paralela à aorta, envolta por gordura mesentérica. Cruza à frente da veia renal esquerda e da terceira porção duodenal. Emite as pancreaticoduodenais inferiores, jejunais, ileais, ileocólica, cólica direita e cólica média.',
      funcao: 'Irriga o intestino delgado inteiro (exceto o duodeno proximal), o ceco, o apêndice, o cólon ascendente e os dois terços proximais do transverso — o território do intestino médio embrionário.',
      densidade: 'Fase arterial: 250–450 UH. A gordura que a envolve é o que a torna reconhecível: um ponto denso num halo escuro.',
      janela: 'Angio; sagital para a origem.',
      comoIdentificar: 'Logo abaixo do tronco celíaco, é o vaso que sai da frente da aorta e DESCE verticalmente, cercado por gordura. A veia mesentérica superior está sempre à sua direita.',
      reparos: ['Aorta (origem anterior, L1)', 'Veia renal esquerda (passa atrás da AMS)', 'Terceira porção duodenal (passa atrás da AMS)', 'Veia mesentérica superior (à direita)', 'Processo uncinado (à direita e atrás)'],
      clinica: 'A isquemia mesentérica aguda por embolia da AMS é uma das emergências de maior mortalidade da medicina, justamente porque o quadro inicial é de dor desproporcional ao exame físico e a suspeita costuma vir tarde. Na TC, o achado direto é a falha de enchimento na artéria; os indiretos — que aparecem mais tarde e indicam necrose — são parede intestinal afinada e sem realce, pneumatose intestinal e gás portal. A síndrome da artéria mesentérica superior, por outro lado, é a compressão da terceira porção duodenal na pinça entre AMS e aorta, em pacientes muito emagrecidos.',
      alteracoes: [
        { nome: 'Embolia da AMS', achado: 'Falha de enchimento abrupta, tipicamente 3–10 cm da origem (poupando as jejunais proximais); alças com parede fina e sem realce.' },
        { nome: 'Trombose aterosclerótica', achado: 'Oclusão ostial em vaso com aterosclerose difusa; costuma haver colaterais, sinal de que o processo foi lento.' },
        { nome: 'Isquemia mesentérica não oclusiva', achado: 'Vasos pérvios mas afilados, com alças espessadas — baixo débito, típico de choque e uso de vasoconstritor.' },
        { nome: 'Síndrome da AMS (pinça aortomesentérica)', achado: 'Ângulo aortomesentérico < 22° e distância < 8 mm, com dilatação gástrica e duodenal a montante em paciente emagrecido.' },
        { nome: 'Dissecção isolada da AMS', achado: 'Flap intimal com luz falsa; pode ser assintomática ou causar isquemia.' },
        { nome: 'Envolvimento por neoplasia pancreática', achado: 'Contato > 180° com a AMS classifica o tumor como localmente avançado/irressecável.' },
      ],
      armadilhas: ['Alça isquêmica pode ter parede FINA (isquemia arterial) ou ESPESSA (isquemia venosa ou reperfusão) — a ausência de espessamento não exclui isquemia.'],
      medidas: [{ rotulo: 'Ângulo aortomesentérico normal', valor: '38°–65°' }, { rotulo: 'Síndrome da AMS', valor: 'ângulo < 22°' }],
    },
    {
      id: 'arteria-renal-direita',
      nome: 'Artéria renal direita',
      categoria: 'arteria',
      resumo: 'Ramo lateral da aorta que irriga o rim direito; mais longa que a esquerda porque passa atrás da cava.',
      morfologia: 'Nasce da face lateral direita da aorta em L1-L2, ligeiramente abaixo da esquerda, e segue POSTERIOR à veia cava inferior até o hilo renal direito. Divide-se em ramos segmentares (apical, anterossuperior, anteroinferior, inferior e posterior), que são artérias TERMINAIS, sem anastomoses.',
      funcao: 'Conduz cerca de 10% do débito cardíaco a cada rim. Emite a artéria adrenal inferior e ramos capsulares e ureterais. Como os ramos segmentares são terminais, sua oclusão causa infarto renal com necrose — não há circulação colateral que salve o território.',
      densidade: 'Fase arterial: 250–450 UH.',
      janela: 'Angio.',
      comoIdentificar: 'No corte em que aparecem os dois rins, procure o vaso que sai lateralmente da aorta e passa ATRÁS da cava a caminho do rim direito. O trajeto retrocaval é sua marca.',
      reparos: ['Aorta (origem lateral)', 'Veia cava inferior (a artéria passa atrás dela)', 'Veia renal direita (anterior à artéria)', 'Hilo renal direito'],
      clinica: 'A estenose de artéria renal é causa tratável de hipertensão arterial: aterosclerótica (ostial, em idosos, com fatores de risco) ou por displasia fibromuscular (em mulheres jovens, no terço médio-distal, com aspecto em "colar de contas"). O achado indireto mais valioso é a assimetria renal — um rim menor que o outro em mais de 1,5 cm. E, antes de nefrectomia de doador vivo, contar as artérias é obrigatório: 25–30% das pessoas têm artérias renais múltiplas.',
      alteracoes: [
        { nome: 'Estenose aterosclerótica', achado: 'Placa calcificada ostial ou nos primeiros 2 cm, com dilatação pós-estenótica e rim ipsilateral atrófico.' },
        { nome: 'Displasia fibromuscular', achado: 'Aspecto em "colar de contas" no terço médio-distal, em mulher jovem hipertensa.' },
        { nome: 'Infarto renal', achado: 'Área hipodensa em cunha, sem realce, de base capsular; o "sinal do halo cortical" (fina camada cortical preservada pela irrigação capsular) é típico.' },
        { nome: 'Artérias renais múltiplas', achado: 'Duas ou mais artérias em 25–30% das pessoas; obrigatoriamente descritas antes de transplante e de endoprótese aórtica.' },
        { nome: 'Dissecção', achado: 'Flap com má perfusão renal; pode ser extensão da dissecção aórtica ou isolada.' },
      ],
    },
    {
      id: 'arteria-renal-esquerda',
      nome: 'Artéria renal esquerda',
      categoria: 'arteria',
      resumo: 'Ramo lateral esquerdo da aorta; mais curta e mais alta que a direita.',
      morfologia: 'Nasce em L1-L2, tipicamente um pouco acima da direita, e segue lateralmente e um pouco para trás até o hilo renal esquerdo. Situa-se POSTERIOR à veia renal esquerda.',
      funcao: 'Irrigação do rim esquerdo e da adrenal esquerda por ramo inferior.',
      densidade: 'Fase arterial: 250–450 UH.',
      janela: 'Angio.',
      comoIdentificar: 'Vaso que sai lateralmente da aorta à esquerda, atrás da veia renal esquerda. Como a veia é grande e anterior, a artéria fica "escondida" atrás dela.',
      reparos: ['Aorta', 'Veia renal esquerda (anterior à artéria)', 'Hilo renal esquerdo', 'Pilar diafragmático esquerdo (posterior)'],
      clinica: 'A regra "artéria atrás, veia à frente" no hilo renal é o que evita confundir as duas em uma TC de fase indeterminada. Em transplante de doador vivo, prefere-se o rim ESQUERDO porque a veia renal esquerda é longa (facilita a anastomose), apesar de a artéria ser curta.',
      alteracoes: [
        { nome: 'Estenose', achado: 'Mesmo espectro do lado direito — aterosclerose ostial ou displasia fibromuscular.' },
        { nome: 'Artéria polar acessória', achado: 'Ramo adicional para o polo superior ou inferior; a polar inferior pode cruzar e comprimir a junção ureteropélvica, causando hidronefrose.' },
      ],
    },
    {
      id: 'arteria-mesenterica-inferior',
      nome: 'Artéria mesentérica inferior',
      sinonimos: ['AMI'],
      categoria: 'arteria',
      resumo: 'Terceiro e menor ramo visceral da aorta; irriga o cólon esquerdo, o sigmoide e o reto superior.',
      morfologia: 'Sai da face anterolateral esquerda da aorta em L3, cerca de 3–4 cm acima da bifurcação. É fina (2–3 mm) e frequentemente pouco visível. Emite a cólica esquerda, as sigmoideias e a retal superior.',
      funcao: 'Irrigação do intestino posterior embrionário (hindgut): terço distal do transverso, cólon descendente, sigmoide e reto proximal. Conecta-se à mesentérica superior pela artéria marginal de Drummond e pelo arco de Riolan.',
      densidade: 'Fase arterial: 250–400 UH; vaso fino, exige cortes finos.',
      janela: 'Angio.',
      comoIdentificar: 'Alguns centímetros acima da bifurcação aórtica, procure um vaso fino saindo da face anterolateral ESQUERDA da aorta e seguindo para baixo e para a esquerda. É pequeno — role devagar.',
      reparos: ['Aorta (origem em L3)', 'Bifurcação aórtica (3–4 cm abaixo)', 'Cólon descendente (à esquerda)', 'Ângulo duodenojejunal (acima e medialmente)'],
      clinica: 'A colite isquêmica do cólon esquerdo é a doença desta artéria, e ela tem localização característica: o ângulo esplênico e a junção retossigmoide são "zonas divisoras de águas" (pontos de Griffiths e de Sudeck), onde a circulação colateral é mais frágil. Na cirurgia de aneurisma aórtico, a ligadura da AMI sem colateral adequada causa isquemia colônica — complicação grave que a TC pré-operatória ajuda a antecipar ao mostrar a qualidade do arco de Riolan.',
      alteracoes: [
        { nome: 'Colite isquêmica', achado: 'Espessamento parietal segmentar do cólon esquerdo, com realce em camadas, densificação da gordura e distribuição respeitando as zonas divisoras de águas.' },
        { nome: 'Oclusão crônica com arco de Riolan hipertrofiado', achado: 'AMI ocluída com colateral calibrosa conectando as cólicas média e esquerda — "artéria serpenteante de Moskowitz". Indica boa compensação.' },
        { nome: 'Isquemia colônica pós-cirurgia aórtica', achado: 'Espessamento e pneumatose do sigmoide após ligadura da AMI.' },
      ],
    },
    {
      id: 'arteria-iliaca-comum-direita',
      nome: 'Artéria ilíaca comum direita',
      categoria: 'arteria',
      resumo: 'Ramo terminal direito da aorta; divide-se em ilíaca interna e externa.',
      morfologia: 'Nasce da bifurcação aórtica em L4, mede 4–6 cm e desce anterolateralmente até a articulação sacroilíaca, onde se divide. É ligeiramente mais longa que a esquerda. Calibre normal até 1,5 cm.',
      funcao: 'Distribui sangue à pelve (pela ilíaca interna) e ao membro inferior direito (pela externa).',
      densidade: 'Fase arterial: 250–450 UH.',
      janela: 'Angio.',
      comoIdentificar: 'Nos cortes abaixo do umbigo, é o vaso à direita que se separa da aorta e se afasta lateralmente. Segui-lo para baixo mostra a divisão em interna (posteromedial) e externa (anterolateral).',
      reparos: ['Bifurcação aórtica (L4)', 'Veia ilíaca comum direita (posterior e medial)', 'Ureter direito (cruza à frente da bifurcação)', 'Articulação sacroilíaca (nível da divisão)'],
      clinica: 'Aneurisma de ilíaca comum (> 1,8–2,0 cm) muda o planejamento da endoprótese aórtica, porque exige zona de ancoragem distal na ilíaca externa e frequentemente embolização da interna. O ureter cruza à frente da bifurcação ilíaca — referência anatômica que salva ureteres em cirurgia pélvica.',
      alteracoes: [
        { nome: 'Aneurisma de ilíaca comum', achado: 'Dilatação ≥ 1,8 cm, geralmente associada a aneurisma aórtico; complica o planejamento endovascular.' },
        { nome: 'Doença oclusiva', achado: 'Estenose ou oclusão com colaterais lombares e da ilíaca interna; causa claudicação de nádega e coxa.' },
        { nome: 'Síndrome de May-Thurner (do lado venoso)', achado: 'A ilíaca comum direita comprime a veia ilíaca comum esquerda contra a coluna, causando trombose venosa profunda à esquerda em mulheres jovens.' },
      ],
    },
    {
      id: 'arteria-iliaca-comum-esquerda',
      nome: 'Artéria ilíaca comum esquerda',
      categoria: 'arteria',
      resumo: 'Ramo terminal esquerdo da aorta; espelho da direita, ligeiramente mais curta.',
      morfologia: 'Também nasce em L4, com 4–5 cm de extensão. Passa à frente da veia ilíaca comum ESQUERDA, que é comprimida contra o corpo de L5.',
      funcao: 'Irrigação da pelve esquerda e do membro inferior esquerdo.',
      densidade: 'Fase arterial: 250–450 UH.',
      janela: 'Angio.',
      comoIdentificar: 'Espelho da direita, do lado esquerdo. A relação com a veia ilíaca esquerda por baixo é o detalhe a memorizar.',
      reparos: ['Bifurcação aórtica', 'Veia ilíaca comum esquerda (comprimida sob a artéria ilíaca comum direita)', 'Cólon sigmoide (anterior)', 'Ureter esquerdo (cruza à frente)'],
      clinica: 'A síndrome de May-Thurner (ou de Cockett) é a compressão da VEIA ilíaca comum esquerda entre a ARTÉRIA ilíaca comum direita (à frente) e o corpo de L5 (atrás). Explica por que a trombose venosa profunda iliofemoral é muito mais frequente à esquerda, sobretudo em mulheres jovens usando contraceptivo. A TC mostra o achatamento da veia no ponto de cruzamento e colaterais pélvicas.',
      alteracoes: [
        { nome: 'Compressão de May-Thurner', achado: 'Achatamento da veia ilíaca comum esquerda no cruzamento com a artéria direita, com colaterais e, muitas vezes, trombo.' },
        { nome: 'Aneurisma', achado: 'Dilatação ≥ 1,8 cm; frequentemente bilateral e associada a aneurisma aórtico.' },
        { nome: 'Oclusão aterosclerótica', achado: 'Placa calcificada com estenose; contribui para a síndrome de Leriche quando bilateral.' },
      ],
    },
  ],
  quiz: [
    {
      pergunta: 'Qual a ordem correta dos ramos viscerais da aorta abdominal, de cima para baixo?',
      alternativas: [
        'Renais, tronco celíaco, mesentérica superior, mesentérica inferior',
        'Tronco celíaco, mesentérica superior, renais, mesentérica inferior',
        'Mesentérica superior, tronco celíaco, mesentérica inferior, renais',
        'Tronco celíaco, renais, mesentérica superior, mesentérica inferior',
      ],
      correta: 1,
      explicacao: 'A sequência é tronco celíaco (T12), mesentérica superior (L1), renais (L1-L2), mesentérica inferior (L3) e bifurcação (L4). Decorar essa ordem permite localizar o nível do corte instantaneamente.',
    },
    {
      pergunta: 'Uma indentação em "gancho" na face superior do tronco celíaco, que piora na expiração, indica:',
      alternativas: [
        'Placa aterosclerótica ostial',
        'Síndrome do ligamento arqueado mediano',
        'Dissecção do tronco celíaco',
        'Aneurisma sacular',
      ],
      correta: 1,
      explicacao: 'A compressão pelos pilares diafragmáticos atinge a face SUPERIOR do tronco e varia com a respiração — piora na expiração. A placa aterosclerótica é fixa e ostial. O diagnóstico se faz no plano sagital, não no axial.',
    },
    {
      pergunta: 'Qual a variante arterial hepática mais relevante para a cirurgia pancreática?',
      alternativas: [
        'Artéria hepática esquerda saindo da gástrica esquerda',
        'Artéria hepática direita substituída saindo da mesentérica superior, com trajeto posterior à veia porta',
        'Tronco celiacomesentérico',
        'Artéria cística dupla',
      ],
      correta: 1,
      explicacao: 'Presente em ~15%, essa artéria sobe POSTERIOR à veia porta e lateral ao colédoco, atravessando o campo da duodenopancreatectomia. Não reconhecê-la na TC pré-operatória é causa clássica de lesão arterial e isquemia hepática.',
    },
    {
      pergunta: 'Uma úlcera na parede posterior do bulbo duodenal sangra maciçamente porque erode qual artéria?',
      alternativas: ['Artéria gástrica esquerda', 'Artéria gastroduodenal', 'Artéria esplênica', 'Artéria hepática própria'],
      correta: 1,
      explicacao: 'A artéria gastroduodenal desce imediatamente atrás do bulbo duodenal. Uma úlcera que penetra a parede posterior a atinge, produzindo hemorragia digestiva alta de grande volume, tratada por embolização.',
    },
    {
      pergunta: 'Colite isquêmica do cólon esquerdo tem predileção pelo ângulo esplênico porque:',
      alternativas: [
        'É a região com maior carga bacteriana',
        'É uma zona divisora de águas entre os territórios das mesentéricas superior e inferior',
        'A parede é mais fina nessa região',
        'O trânsito é mais lento ali',
      ],
      correta: 1,
      explicacao: 'O ponto de Griffiths, no ângulo esplênico, é a fronteira entre os territórios da mesentérica superior e da inferior, com colateralização mais frágil. A junção retossigmoide (ponto de Sudeck) é a outra zona divisora clássica.',
    },
    {
      pergunta: 'Em qual porcentagem da população existem artérias renais múltiplas?',
      alternativas: ['Menos de 5%', '25–30%', '50–60%', 'Mais de 70%'],
      correta: 1,
      explicacao: 'Artérias renais múltiplas ocorrem em cerca de um quarto a um terço das pessoas. Contá-las é obrigatório antes de nefrectomia de doador vivo, transplante e endoprótese aórtica.',
    },
  ],
}
