import type { SubsecaoTC } from '../tipos'

export const abdomeTratoUrinario: SubsecaoTC = {
  id: 'trato-urinario',
  titulo: 'Trato urinário',
  subtitulo: 'Cálices, pelve renal, ureteres e bexiga — o caminho da urina na urotomografia',
  secaoId: 'abdome',
  pasta: '/TC_ABDOME/TC_ABDOME_TRATO_URINARIO',
  ext: 'JPG',
  totalCortes: 48,
  orientacao: 'cranio-caudal',
  icone: 'droplets',
  cor: 'esmeralda',
  janelaPadrao: 'mediastinal',
  protocolo:
    'Urotomografia em três tempos: (1) fase SEM contraste — indispensável, porque cálculo é hiperdenso e desaparece quando o sistema coletor se enche de contraste; (2) fase nefrográfica (90–100 s), em que o parênquima realça de forma homogênea e as massas se destacam; (3) fase EXCRETORA (7–10 min), em que o contraste opacifica cálices, pelve, ureteres e bexiga, revelando falhas de enchimento e extravasamentos. Para cólica renal simples, faz-se TC de baixa dose SEM contraste — ela tem sensibilidade próxima de 100% para cálculo e evita radiação e contraste desnecessários.',
  introducao:
    'O trato urinário é um sistema de tubos, e ler tubos exige uma lógica diferente da de ler órgãos sólidos: interessa a continuidade, o calibre e o conteúdo. A urina é produzida nos néfrons, coletada nos cálices menores, reunida nos maiores, canalizada na pelve renal, transportada pelo ureter e armazenada na bexiga. Qualquer obstáculo nesse caminho dilata o que está a montante e nada muda a jusante — e é justamente essa dissociação, o "ponto de transição" entre o dilatado e o normal, que a TC procura. O ureter tem três estreitamentos fisiológicos onde os cálculos param: a junção ureteropélvica, o cruzamento com os vasos ilíacos e a junção ureterovesical. Saber onde eles ficam é saber onde olhar. A segunda ideia importante é a das fases: cálculo só é confiável na fase sem contraste, massa renal só é caracterizável na fase nefrográfica, e falha de enchimento urotelial só existe na fase excretora. Pedir ou ler a fase errada é o erro mais comum desta região.',
  roteiro: [
    { passo: '1. Comece pela fase sem contraste', detalhe: 'É onde o cálculo aparece. Depois do contraste, ele fica indistinguível da urina opacificada.' },
    { passo: '2. Compare os dois rins', detalhe: 'Tamanho, contorno, espessura cortical e grau de realce. Assimetria é sempre um achado.' },
    { passo: '3. Procure dilatação', detalhe: 'Cálices arredondados (perda da concavidade normal), pelve alargada, ureter proeminente.' },
    { passo: '4. Encontre o ponto de transição', detalhe: 'Siga o ureter dilatado para baixo até onde ele volta ao normal. Ali está a causa.' },
    { passo: '5. Avalie a gordura perirrenal', detalhe: 'Densificação e estriações indicam obstrução aguda, pielonefrite ou ruptura de fórnice.' },
    { passo: '6. Termine na bexiga', detalhe: 'Parede, conteúdo, trabeculação, divertículos e as duas junções ureterovesicais.' },
  ],
  perolas: [
    'Cálculo só na fase SEM contraste. Se o exame só tem fase com contraste, você não pode excluir litíase.',
    'Praticamente todos os cálculos urinários são visíveis na TC — exceto os de indinavir (medicamento antirretroviral), que são radiotransparentes até na TC.',
    'Três estreitamentos onde o cálculo encrava: junção ureteropélvica, cruzamento dos vasos ilíacos e junção ureterovesical.',
    'O "sinal do halo/anel de partes moles" ao redor de um foco denso na pelve confirma que ele é um cálculo ureteral impactado, e não um flebólito.',
    'Flebólito tem centro lucente e é arredondado; cálculo é irregular e tem o anel de partes moles. Essa distinção resolve a maior dúvida da TC de cólica renal.',
  ],
  estruturas: [
    {
      id: 'calices-renais-superiores',
      nome: 'Cálices renais superiores',
      categoria: 'urinario',
      resumo: 'Primeiras câmaras coletoras do rim, no polo superior; recebem urina das papilas.',
      morfologia: 'Cada cálice menor abraça uma papila renal, que projeta-se para dentro dele. Vários cálices menores confluem em um cálice maior. A concavidade normal do cálice (forma de "taça") é dada pela papila que o preenche — quando a papila atrofia ou o sistema dilata, o cálice fica arredondado ou em "baqueta".',
      funcao: 'Coleta da urina definitiva que sai dos ductos coletores nas papilas. A musculatura lisa calicial inicia a peristalse que empurra a urina para a pelve.',
      densidade: 'Urina sem contraste: 0–15 UH. Na fase excretora, opacificada intensamente (> 300 UH). Cálculo na fase sem contraste: > 200 UH, frequentemente > 500 UH.',
      janela: 'Partes moles; para cálculos pequenos, janela óssea ajuda a separar da urina densa.',
      comoIdentificar: 'Nos cortes do polo superior renal, são as pequenas estruturas de densidade líquida (ou muito densas na fase excretora) dentro do seio renal, cercadas pela gordura sinusal.',
      reparos: ['Papilas renais (projetam-se para dentro deles)', 'Seio renal (gordura ao redor)', 'Pelve renal (para onde convergem)'],
      clinica: 'A morfologia calicial conta histórias. Cálices em "baqueta" (arredondados, com perda da concavidade) indicam necrose de papila — que ocorre em diabetes, anemia falciforme, uso crônico de analgésicos e pielonefrite. Já a dilatação calicial associada a atrofia cortical focal, com cicatriz, é a marca da nefropatia de refluxo, tipicamente nos polos, onde as papilas compostas permitem refluxo intrarrenal.',
      alteracoes: [
        { nome: 'Necrose de papila', achado: 'Cálice em baqueta, cavidade na papila, defeito de enchimento por papila descamada; diabetes, falciforme, abuso de analgésicos.' },
        { nome: 'Cálculo calicial', achado: 'Foco hiperdenso na fase sem contraste dentro do cálice; frequentemente assintomático quando não obstrui.' },
        { nome: 'Divertículo calicial', achado: 'Cavidade que comunica com o cálice por colo estreito, enche tardiamente na fase excretora; pode conter cálculos e "leite de cálcio".' },
        { nome: 'Cicatriz de nefropatia de refluxo', achado: 'Afilamento cortical polar sobre cálice dilatado, com contorno renal irregular.' },
      ],
    },
    {
      id: 'calices-renais-medios',
      nome: 'Cálices renais médios',
      categoria: 'urinario',
      resumo: 'Cálices da porção interpolar do rim.',
      morfologia: 'Mesma estrutura dos superiores, drenando as pirâmides da região média. Os cálices médios costumam ser os mais numerosos e apontam mais lateralmente.',
      funcao: 'Coleta e condução da urina da região interpolar.',
      densidade: 'Igual aos superiores.',
      janela: 'Partes moles.',
      comoIdentificar: 'No corte que passa pelo hilo renal, são as estruturas coletoras que apontam lateralmente a partir da pelve.',
      reparos: ['Pelve renal (medialmente)', 'Vasos do hilo (anteriores)', 'Pirâmides medulares'],
      clinica: 'O carcinoma urotelial pode se originar em qualquer ponto do urotélio, inclusive nos cálices. Na fase excretora, ele aparece como falha de enchimento fixa dentro do contraste — diferentemente do coágulo, que muda de posição, e do cálculo, que é hiperdenso na fase sem contraste. Falha de enchimento no sistema coletor de um fumante idoso é urotelioma até prova em contrário, e obriga a avaliar todo o urotélio, dos cálices à uretra.',
      alteracoes: [
        { nome: 'Carcinoma urotelial', achado: 'Falha de enchimento fixa na fase excretora, com realce próprio na fase nefrográfica; obriga a avaliar todo o urotélio.' },
        { nome: 'Coágulo', achado: 'Falha de enchimento que muda de posição entre as fases e não realça.' },
        { nome: 'Pielonefrite', achado: 'Nefrograma estriado (faixas hipodensas radiadas) com espessamento urotelial e densificação perirrenal.' },
      ],
    },
    {
      id: 'calices-renais-inferiores',
      nome: 'Cálices renais inferiores',
      categoria: 'urinario',
      resumo: 'Cálices do polo inferior, onde a drenagem é mais dependente da gravidade.',
      morfologia: 'Cálices do terço inferior, que apontam para baixo. A geometria do cálice inferior — o ângulo infundibulopélvico e o comprimento do infundíbulo — determina a facilidade de drenagem de fragmentos.',
      funcao: 'Coleta da urina do polo inferior. É o cálice de pior clearance espontâneo, porque a urina precisa subir contra a gravidade para alcançar a pelve na posição ereta.',
      densidade: 'Igual aos demais.',
      janela: 'Partes moles.',
      comoIdentificar: 'Nos cortes do polo inferior renal, apontando inferiormente a partir da pelve.',
      reparos: ['Pelve renal', 'Polo inferior do rim', 'Ureter proximal (abaixo)'],
      clinica: 'A localização de um cálculo no cálice inferior tem consequência terapêutica direta: fragmentos gerados por litotripsia extracorpórea nessa posição têm baixa taxa de eliminação espontânea, sobretudo quando o ângulo infundibulopélvico é agudo e o infundíbulo é longo e estreito. Por isso, cálculos de polo inferior maiores que 1 cm costumam ser tratados por ureteroscopia flexível ou nefrolitotripsia percutânea em vez de litotripsia.',
      alteracoes: [
        { nome: 'Cálculo de polo inferior', achado: 'Foco hiperdenso no cálice inferior; medir o maior diâmetro e a densidade em UH (acima de 1000 UH sugere resistência à litotripsia).' },
        { nome: 'Hidrocalicose localizada', achado: 'Dilatação isolada de um grupo calicial por estenose infundibular.' },
      ],
    },
    {
      id: 'pelve-renal-direita',
      nome: 'Pelve renal direita',
      categoria: 'urinario',
      resumo: 'Reservatório em forma de funil que reúne os cálices maiores e se continua no ureter.',
      morfologia: 'Estrutura triangular no seio renal, que pode ser intrarrenal (contida no seio) ou extrarrenal (projetando-se além do hilo) — variação anatômica normal e importante, porque a pelve extrarrenal parece dilatada sem estar. Capacidade de 3–10 mL.',
      funcao: 'Reservatório temporário e propulsor: sua contração peristáltica empurra a urina para o ureter, em ondas de 2 a 6 por minuto.',
      densidade: 'Urina 0–15 UH sem contraste; > 300 UH na fase excretora.',
      janela: 'Partes moles.',
      comoIdentificar: 'No hilo renal direito, é a estrutura de densidade líquida entre os vasos, dentro da gordura do seio.',
      reparos: ['Hilo renal direito', 'Artéria e veia renais (anteriores à pelve — de frente para trás: veia, artéria, pelve)', 'Segunda porção duodenal (anterior)'],
      clinica: 'A obstrução da junção ureteropélvica é a causa mais comum de hidronefrose congênita: a pelve dilata muito e o ureter permanece de calibre normal — a chave é justamente a ausência de dilatação ureteral. Em adultos, pode ser causada por um vaso polar inferior cruzando e comprimindo a junção, achado que a angio-TC identifica e que muda a cirurgia. Vale também memorizar a ordem das estruturas no hilo: de anterior para posterior, veia, artéria e pelve.',
      alteracoes: [
        { nome: 'Obstrução da junção ureteropélvica', achado: 'Pelve muito dilatada com ureter de calibre normal; procurar vaso polar cruzante.' },
        { nome: 'Pelve extrarrenal', achado: 'Pelve proeminente projetada além do hilo, sem dilatação calicial — variante normal, não é hidronefrose.' },
        { nome: 'Carcinoma urotelial de pelve', achado: 'Falha de enchimento com realce; obriga avaliar todo o trato urinário.' },
        { nome: 'Cálculo coraliforme', achado: 'Cálculo que molda a pelve e os cálices ("chifre de veado"); tipicamente de estruvita, associado a infecção por germes produtores de urease.' },
      ],
      armadilhas: ['Pelve extrarrenal é rotineiramente confundida com hidronefrose — o critério é a ausência de dilatação dos cálices.'],
    },
    {
      id: 'pelve-renal-esquerda',
      nome: 'Pelve renal esquerda',
      categoria: 'urinario',
      resumo: 'Contraparte esquerda do reservatório piélico.',
      morfologia: 'Idêntica à direita.',
      funcao: 'Coleta e propulsão da urina.',
      densidade: 'Igual à direita.',
      janela: 'Partes moles.',
      comoIdentificar: 'Hilo renal esquerdo, entre os vasos, dentro da gordura sinusal.',
      reparos: ['Hilo renal esquerdo', 'Veia e artéria renais esquerdas', 'Cauda do pâncreas e cólon descendente (anteriores)'],
      clinica: 'A comparação entre as duas pelves é o método: dilatação unilateral aponta obstrução do lado dilatado; dilatação bilateral aponta obstrução baixa (bexiga, próstata, uretra) ou refluxo. Essa simples bifurcação do raciocínio direciona toda a investigação.',
      alteracoes: [
        { nome: 'Hidronefrose unilateral', achado: 'Dilatação de um lado só; procurar o ponto de transição no ureter ipsilateral.' },
        { nome: 'Hidronefrose bilateral', achado: 'Dilatação dos dois lados; pensar em obstrução infravesical (HPB, tumor de bexiga, estenose de uretra) ou compressão pélvica.' },
      ],
    },
    {
      id: 'ureter-direito',
      nome: 'Ureter direito',
      categoria: 'urinario',
      resumo: 'Tubo muscular de 25–30 cm que conduz a urina do rim à bexiga.',
      morfologia: 'Desce no retroperitônio sobre a face anterior do músculo psoas, cruza os vasos ilíacos na altura da bifurcação e entra na pelve, seguindo pela parede lateral até desembocar na bexiga em trajeto oblíquo intramural — que funciona como válvula antirrefluxo. Calibre normal de 3–4 mm, com três estreitamentos fisiológicos.',
      funcao: 'Transporte ativo da urina por peristalse, independente da gravidade. O trajeto oblíquo na parede vesical é o que impede o refluxo: quando a bexiga enche, ela comprime esse segmento e o fecha.',
      densidade: 'Não opacificado, aparece como pequeno ponto de partes moles sobre o psoas. Na fase excretora, torna-se uma linha densa e facilmente seguível.',
      janela: 'Partes moles.',
      comoIdentificar: 'Role a série de cima para baixo e siga um pontinho de partes moles caminhando sobre a face anterior do psoas. Ele desce, cruza os vasos ilíacos e entra na pelve. Rolar é essencial: em um corte isolado o ureter é indistinguível de um vaso ou de um linfonodo pequeno.',
      reparos: ['Músculo psoas (o ureter corre sobre ele)', 'Vasos ilíacos (cruzados na bifurcação)', 'Veia cava inferior (medial, no trajeto alto)', 'Bexiga (destino)'],
      clinica: 'A cólica renal é a apresentação clássica, e a TC sem contraste de baixa dose resolve o caso em minutos: encontra-se o cálculo, mede-se seu tamanho (< 5 mm elimina espontaneamente em 70–80% dos casos; > 10 mm quase nunca) e sua densidade, e avaliam-se os sinais secundários — hidronefrose, hidroureter, densificação da gordura perirrenal e periureteral, e assimetria do nefrograma. O grande diagnóstico diferencial de um foco denso na pelve é o flebólito, e a distinção se faz por dois sinais: o cálculo tem o "anel de partes moles" ao redor (a parede ureteral edemaciada) e é irregular; o flebólito é redondo e frequentemente tem centro lucente.',
      alteracoes: [
        { nome: 'Cálculo ureteral obstrutivo', achado: 'Foco hiperdenso com anel de partes moles, hidroureteronefrose a montante, densificação perirrenal e nefrograma retardado.' },
        { nome: 'Estenose ureteral', achado: 'Afilamento com dilatação a montante; causas pós-cirúrgicas, pós-radioterapia, tuberculose e neoplasia.' },
        { nome: 'Ureter retrocaval', achado: 'Ureter direito passando ATRÁS da cava e depois cruzando medialmente ("sinal do S invertido"); variante que causa obstrução.' },
        { nome: 'Fibrose retroperitoneal', achado: 'Placa de partes moles periaórtica que traciona os ureteres MEDIALMENTE, causando hidronefrose bilateral.' },
        { nome: 'Carcinoma urotelial ureteral', achado: 'Falha de enchimento fixa com espessamento parietal e realce.' },
        { nome: 'Lesão iatrogênica', achado: 'Extravasamento de contraste na fase excretora após cirurgia pélvica ou ginecológica; urinoma no retroperitônio.' },
      ],
      armadilhas: [
        'Flebólito x cálculo: o anel de partes moles e a irregularidade favorecem cálculo; o centro lucente e a forma redonda favorecem flebólito.',
        'Sem a fase sem contraste, um cálculo dentro do ureter opacificado desaparece completamente.',
      ],
      medidas: [{ rotulo: 'Calibre normal', valor: '3–4 mm' }, { rotulo: 'Eliminação espontânea provável', valor: 'cálculo < 5 mm' }],
    },
    {
      id: 'ureter-esquerdo',
      nome: 'Ureter esquerdo',
      categoria: 'urinario',
      resumo: 'Contraparte esquerda; mesmo trajeto e mesmos estreitamentos.',
      morfologia: 'Idêntica ao direito, sobre o psoas esquerdo. Na pelve, tem relação íntima com o mesossigmoide e, na mulher, cruza sob a artéria uterina.',
      funcao: 'Transporte da urina do rim esquerdo à bexiga.',
      densidade: 'Igual ao direito.',
      janela: 'Partes moles.',
      comoIdentificar: 'Mesma técnica: siga o pontinho sobre o psoas esquerdo, rolando os cortes.',
      reparos: ['Psoas esquerdo', 'Vasos ilíacos esquerdos', 'Artéria uterina (na mulher, cruza por cima do ureter)', 'Mesossigmoide (anterior, na pelve)'],
      clinica: 'A relação do ureter distal com a artéria uterina — "água por baixo da ponte" — é a anatomia que explica a lesão ureteral em histerectomia, complicação que a TC diagnostica no pós-operatório pelo urinoma e pelo extravasamento na fase excretora. Nos homens, a relação com o ducto deferente é análoga.',
      alteracoes: [
        { nome: 'Lesão pós-histerectomia', achado: 'Extravasamento de contraste na fase excretora com urinoma pélvico; hidronefrose a montante.' },
        { nome: 'Compressão por massa pélvica', achado: 'Estreitamento com hidronefrose; frequente em neoplasias ginecológicas e colorretais avançadas.' },
        { nome: 'Ureterocele', achado: 'Dilatação cística da porção intramural distal, com aspecto de "cabeça de cobra" na fase excretora.' },
      ],
    },
    {
      id: 'bexiga',
      nome: 'Bexiga',
      categoria: 'urinario',
      resumo: 'Reservatório muscular extraperitoneal que armazena a urina até a micção.',
      morfologia: 'Órgão oco de parede muscular (detrusor) situado no espaço extraperitoneal retropúbico. Sua forma muda com o enchimento: piramidal quando vazia, ovoide quando cheia. Capacidade normal de 400–500 mL. Parede de até 3 mm quando distendida (parede "espessa" numa bexiga vazia é normal). O trígono, entre os dois óstios ureterais e o colo vesical, é a única região de mucosa lisa e aderida.',
      funcao: 'Armazenamento de urina em baixa pressão (complacência) e esvaziamento coordenado. O detrusor relaxa passivamente durante o enchimento e contrai na micção, sincronizado com o relaxamento do esfíncter — coordenação mediada pelo centro pontino da micção.',
      densidade: 'Urina 0–15 UH sem contraste; na fase excretora, o contraste denso decanta e forma nível líquido-líquido — achado NORMAL, frequentemente confundido com hemorragia. Parede realça discretamente.',
      janela: 'Partes moles.',
      comoIdentificar: 'Estrutura de densidade líquida na pelve anterior, atrás da sínfise púbica. Nos cortes mais baixos, encontra a próstata (no homem) ou o útero e a vagina (na mulher).',
      reparos: ['Sínfise púbica (anterior)', 'Espaço de Retzius (entre púbis e bexiga)', 'Próstata ou útero (posterior/inferior)', 'Reto (posterior)', 'Óstios ureterais (trígono)'],
      clinica: 'A TC da bexiga tem três grandes usos. No trauma, a cistografia por TC distingue a ruptura extraperitoneal (extravasamento no espaço de Retzius, com padrão em "chama", associada a fratura de ramos púbicos, geralmente tratada com sonda) da intraperitoneal (contraste contornando alças e no fundo de saco, por trauma com bexiga cheia, tratamento cirúrgico). Na oncologia, o carcinoma urotelial vesical é a neoplasia mais comum do trato urinário e aparece como massa polipoide ou espessamento parietal focal, melhor visto quando a bexiga está bem distendida. E na urologia funcional, a bexiga de esforço — trabeculada e com divertículos — conta a história de anos de obstrução prostática.',
      alteracoes: [
        { nome: 'Carcinoma urotelial de bexiga', achado: 'Massa polipoide ou espessamento parietal focal com realce; avaliar invasão da gordura perivesical (T3) e de órgãos vizinhos (T4).' },
        { nome: 'Ruptura vesical extraperitoneal', achado: 'Contraste no espaço de Retzius em padrão de chama, com fratura de ramos púbicos; sonda vesical costuma resolver.' },
        { nome: 'Ruptura vesical intraperitoneal', achado: 'Contraste contornando alças intestinais e no fundo de saco; exige cirurgia.' },
        { nome: 'Bexiga de esforço', achado: 'Parede trabeculada com divertículos e resíduo; consequência de obstrução crônica.' },
        { nome: 'Cistite enfisematosa', achado: 'Gás na parede vesical, tipicamente em diabéticos; emergência infecciosa.' },
        { nome: 'Divertículo vesical', achado: 'Herniação da mucosa através da parede; risco de estase, cálculo e neoplasia dentro dele.' },
        { nome: 'Fístula vesicoentérica', achado: 'Gás dentro da bexiga sem instrumentação prévia, com espessamento parietal focal; causas: diverticulite, doença de Crohn, neoplasia.' },
      ],
      armadilhas: [
        'Nível líquido-líquido na bexiga na fase excretora é o contraste decantando — não é hemorragia.',
        'Bexiga pouco distendida tem parede aparentemente espessa; nunca laudar espessamento em bexiga vazia.',
        'Gás na bexiga após sondagem é esperado; sem instrumentação, pense em fístula ou cistite enfisematosa.',
      ],
      medidas: [{ rotulo: 'Capacidade normal', valor: '400–500 mL' }, { rotulo: 'Espessura da parede distendida', valor: '≤ 3 mm' }],
    },
  ],
  quiz: [
    {
      pergunta: 'Por que a fase SEM contraste é indispensável na investigação de cólica renal?',
      alternativas: [
        'Porque mostra melhor a anatomia vascular',
        'Porque o cálculo é hiperdenso e fica invisível quando o sistema coletor se enche de contraste',
        'Porque reduz a dose de radiação',
        'Porque evita alergia ao iodo',
      ],
      correta: 1,
      explicacao: 'Um cálculo de 500 UH desaparece dentro de urina opacificada a 300–800 UH. A TC de baixa dose sem contraste tem sensibilidade próxima de 100% para litíase e é o exame de escolha na cólica renal.',
    },
    {
      pergunta: 'Qual sinal ajuda a diferenciar cálculo ureteral distal de flebólito pélvico?',
      alternativas: [
        'Densidade em UH',
        'Anel de partes moles ao redor do foco denso (parede ureteral edemaciada)',
        'Localização anterior',
        'Presença de gás',
      ],
      correta: 1,
      explicacao: 'O "soft tissue rim sign" indica que o foco está dentro do ureter, cuja parede está edemaciada. O flebólito, por estar dentro de uma veia, não tem esse anel, é arredondado e costuma ter centro lucente.',
    },
    {
      pergunta: 'Hidronefrose BILATERAL em homem idoso deve levar a investigar primeiro:',
      alternativas: [
        'Cálculos bilaterais simultâneos',
        'Obstrução infravesical (hiperplasia prostática, tumor de bexiga)',
        'Trombose de veias renais',
        'Nefropatia diabética',
      ],
      correta: 1,
      explicacao: 'Obstrução bilateral simultânea acima da bexiga é improvável; o raciocínio deve ir para um obstáculo único e baixo — próstata, colo vesical, uretra — ou compressão pélvica. Dilatação unilateral, ao contrário, aponta para o ureter daquele lado.',
    },
    {
      pergunta: 'Nível líquido-líquido dentro da bexiga na fase excretora corresponde a:',
      alternativas: ['Hemorragia vesical', 'Contraste iodado decantando na urina — achado normal', 'Piúria', 'Fístula vesicoentérica'],
      correta: 1,
      explicacao: 'O contraste é mais denso que a urina e se deposita na porção dependente, formando um nível. É um achado fisiológico da fase excretora, rotineiramente confundido com sangue por quem não conhece.',
    },
    {
      pergunta: 'Uma placa de partes moles periaórtica que traciona os ureteres MEDIALMENTE, com hidronefrose bilateral, sugere:',
      alternativas: ['Linfoma retroperitoneal', 'Fibrose retroperitoneal', 'Aneurisma de aorta', 'Metástases linfonodais'],
      correta: 1,
      explicacao: 'O desvio MEDIAL dos ureteres é característico da fibrose retroperitoneal (doença de Ormond). Massas linfonodais e linfoma tendem a deslocar os ureteres lateralmente e a elevar a aorta da coluna, o que a fibrose não faz.',
    },
  ],
}
