import type { SubsecaoTC } from '../tipos'

export const abdomeOssos: SubsecaoTC = {
  id: 'ossos',
  titulo: 'Ossos do abdome e da pelve',
  subtitulo: 'Últimos arcos costais, coluna lombar, anel pélvico e fêmur proximal',
  secaoId: 'abdome',
  pasta: '/TC_ABDOME/TC_ABDOME_OSSOS',
  ext: 'JPG',
  totalCortes: 32,
  orientacao: 'cranio-caudal',
  icone: 'bone',
  cor: 'ambar',
  janelaPadrao: 'ossea',
  protocolo:
    'Reconstrução com filtro ósseo da mesma aquisição da TC de abdome e pelve, lida em janela óssea (WW 2000 / WL 400). Em trauma pélvico, reconstruções coronal, sagital e volumétrica 3D são obrigatórias — o anel pélvico é uma estrutura tridimensional e traços no plano axial podem ser invisíveis. Em suspeita de metástase, complementa-se com janela de partes moles para avaliar o componente extraósseo e o canal medular.',
  introducao:
    'A pelve óssea é o exemplo mais didático de um princípio da traumatologia: é um ANEL, e anéis não se rompem em um só lugar. Se você encontrar uma fratura no anel pélvico, existe quase obrigatoriamente uma segunda lesão — outra fratura ou uma disjunção ligamentar na sínfise ou na sacroilíaca. Procurar essa segunda lesão é a diferença entre um laudo correto e um laudo que subestima a instabilidade. A segunda ideia importante é a de que o esqueleto axial é o principal destino das metástases ósseas — coluna lombar, sacro e bacia concentram a maior parte da doença metastática esquelética, porque abrigam medula vermelha bem vascularizada em adultos. Uma TC de abdome feita por qualquer motivo carrega, portanto, um rastreamento ósseo embutido, desde que o leitor troque a janela e olhe. Percorrendo esta série de cima para baixo, você atravessa os últimos arcos costais, desce pelas vértebras lombares, alcança o anel pélvico e termina no fêmur proximal — o percurso completo do esqueleto do tronco inferior.',
  roteiro: [
    { passo: '1. Janela óssea, sempre', detalhe: 'Em janela de partes moles, fratura sem desvio e lesão lítica sutil simplesmente não existem.' },
    { passo: '2. Conte as costelas inferiores', detalhe: '11ª e 12ª são flutuantes e curtas; fratura aqui aponta para lesão de fígado, baço ou rim.' },
    { passo: '3. Percorra as vértebras lombares', detalhe: 'Avalie altura dos corpos, integridade do muro posterior, pedículos e processos. Pedículo ausente é sinal clássico de metástase.' },
    { passo: '4. Feche o anel pélvico', detalhe: 'Sacro, sacroilíacas, ilíacos, ramos púbicos, sínfise, ísquios. Achou uma fratura? Procure a segunda.' },
    { passo: '5. Avalie os acetábulos', detalhe: 'Colunas anterior e posterior, teto acetabular e a congruência com a cabeça femoral.' },
    { passo: '6. Termine no fêmur proximal', detalhe: 'Cabeça, colo, trocanteres e diáfise proximal — sede das fraturas do idoso e da osteonecrose.' },
  ],
  perolas: [
    'A pelve é um anel: uma fratura isolada é rara. Sempre procure a segunda lesão, que pode ser ligamentar (disjunção da sínfise ou da sacroilíaca).',
    'Sinal do pedículo ausente ("coruja piscando") na vértebra lombar: metástase até prova em contrário.',
    'Fratura da 11ª ou 12ª costela à direita → olhe o fígado e o rim direito. À esquerda → baço e rim esquerdo.',
    'Fratura de colo femoral no idoso pode ser oculta na radiografia. A TC vê o traço, mas a ressonância continua sendo o padrão-ouro para fratura oculta.',
    'Coluna lombar: o muro posterior íntegro separa uma fratura estável (por compressão) de uma instável (por explosão, com risco de fragmento no canal).',
  ],
  estruturas: [
    {
      id: 'decimo-primeiro-arco-costal-esquerdo',
      nome: '11º arco costal esquerdo',
      categoria: 'osso',
      resumo: 'Costela flutuante superior esquerda, sem articulação anterior.',
      morfologia: 'Curta, pontiaguda, articula-se apenas com o corpo de T11 posteriormente e termina livremente na musculatura da parede abdominal, sem cartilagem que alcance o esterno ou o rebordo costal.',
      funcao: 'Protege o polo superior do rim esquerdo e o baço, e serve de inserção para o diafragma e para os músculos da parede abdominal posterior.',
      densidade: 'Cortical densa (> 700 UH) com medular gordurosa.',
      janela: 'Óssea.',
      comoIdentificar: 'Nos primeiros cortes da série, é o arco ósseo posterolateral esquerdo que não alcança a frente. Como é curto, aparece em poucos cortes.',
      reparos: ['Baço (medialmente e anteriormente)', 'Polo superior do rim esquerdo', 'T11 (articulação posterior)', 'Diafragma (inserção)'],
      clinica: 'A fratura das costelas flutuantes é dolorosa e costuma ser tratada conservadoramente, mas sua importância está no que ela indica: energia transmitida ao flanco. À esquerda, obriga a examinar o baço e o rim esquerdo com atenção. É também aqui que se procura o traço quando o paciente refere dor persistente em flanco após trauma e a radiografia é normal.',
      alteracoes: [
        { nome: 'Fratura com lesão esplênica', achado: 'Traço costal com laceração esplênica, hematoma perisplênico e líquido livre no espaço esplenorrenal.' },
        { nome: 'Fratura com lesão renal', achado: 'Traço costal com contusão ou laceração renal, hematoma perirrenal e, nos casos graves, extravasamento urinário na fase excretora.' },
        { nome: 'Metástase costal', achado: 'Lesão lítica ou blástica com destruição cortical e massa de partes moles.' },
      ],
    },
    {
      id: 'decimo-segundo-arco-costal-direito',
      nome: '12º arco costal direito',
      categoria: 'osso',
      resumo: 'Costela flutuante mais inferior à direita; a mais curta de todas.',
      morfologia: 'Muito curta e variável — pode ser rudimentar ou até ausente. Articula-se apenas com T12. Serve de referência para a numeração vertebral.',
      funcao: 'Inserção do quadrado lombar e do diafragma; proteção do polo superior do rim direito.',
      densidade: 'Cortical densa.',
      janela: 'Óssea.',
      comoIdentificar: 'É o último arco costal, o mais curto e o mais posterior. Encontrá-lo estabelece o nível T12 — e a partir dele conta-se L1, L2 e assim por diante.',
      reparos: ['T12 (articulação)', 'Polo superior do rim direito', 'Fígado (anterolateral)', 'Quadrado lombar (inserção)'],
      clinica: 'A 12ª costela é a referência para a contagem vertebral, e essa contagem é clinicamente crítica: variações como costela lombar em L1 ou 11 pares de costelas mudam a numeração e podem levar a cirurgia no nível errado. Sempre que houver dúvida, conta-se de C2 para baixo em reconstrução sagital.',
      alteracoes: [
        { nome: 'Costela lombar supranumerária', achado: 'Costela adicional em L1; presente em ~8% e causa clássica de erro de numeração vertebral.' },
        { nome: 'Fratura com lesão renal', achado: 'Traço com hematoma perirrenal; obriga a fase excretora para excluir lesão do sistema coletor.' },
        { nome: 'Agenesia ou hipoplasia da 12ª costela', achado: 'Variante que também confunde a contagem.' },
      ],
    },
    {
      id: 'decimo-segundo-arco-costal-esquerdo',
      nome: '12º arco costal esquerdo',
      categoria: 'osso',
      resumo: 'Última costela flutuante à esquerda.',
      morfologia: 'Igual à direita: curta, articulada apenas com T12, terminando livre na musculatura.',
      funcao: 'Proteção do rim esquerdo e inserção muscular.',
      densidade: 'Cortical densa.',
      janela: 'Óssea.',
      comoIdentificar: 'Espelho da direita. As duas juntas marcam o nível T12.',
      reparos: ['T12', 'Rim esquerdo', 'Baço (mais acima)', 'Cauda do pâncreas (anteromedial)'],
      clinica: 'O ângulo costovertebral esquerdo, entre a 12ª costela e a coluna, é o ponto de percussão de Giordano no exame físico — e é exatamente ali que a TC mostra o rim esquerdo e a gordura perirrenal, onde se buscam pielonefrite, abscesso e cálculo.',
      alteracoes: [
        { nome: 'Fratura', achado: 'Traço costal; correlacionar com lesão renal e esplênica.' },
        { nome: 'Lesão lítica', achado: 'Destruição cortical; mieloma e metástases são as causas mais frequentes no adulto.' },
      ],
    },
    {
      id: 'vertebras-lombares',
      nome: 'Vértebras lombares',
      categoria: 'osso',
      resumo: 'Cinco vértebras de corpos volumosos que suportam a maior carga axial da coluna.',
      morfologia: 'Corpos grandes e reniformes, pedículos curtos e espessos, processos transversos finos e processo espinhoso quadrangular e horizontal. As facetas articulares são orientadas no plano sagital, o que permite bastante flexão e extensão mas limita a rotação. O canal vertebral é triangular; abaixo de L1-L2 contém a cauda equina, não a medula.',
      funcao: 'Suporte do peso corporal, mobilidade em flexão/extensão e proteção da cauda equina. Os corpos vertebrais lombares contêm medula óssea vermelha ativa por toda a vida adulta — o que faz deles o principal sítio de metástase óssea e de mieloma.',
      densidade: 'Osso trabecular do corpo: 100–200 UH no adulto jovem, caindo com a idade. Densidade < 100 UH no corpo de L1 sugere osteoporose (um rastreamento oportunista que qualquer TC permite fazer, sem custo adicional).',
      janela: 'Óssea para o osso; partes moles para o canal e para componentes extraósseos.',
      comoIdentificar: 'Corpos vertebrais grandes na linha média posterior, presentes em todos os cortes abdominais. Numere a partir de T12 (última costela) ou de S1 (primeira vértebra do sacro).',
      reparos: ['12ª costela (marca T12, acima de L1)', 'Aorta e cava (anteriores)', 'Psoas (anterolateral)', 'Cristas ilíacas (a linha entre elas cruza tipicamente L4-L5)'],
      clinica: 'Duas leituras importam aqui. A primeira é a fratura: distinguir a fratura por compressão (perda de altura anterior, muro posterior íntegro, estável) da fratura em explosão (muro posterior recuado, fragmento no canal, instável e potencialmente neurológica) muda completamente a conduta. A segunda é a lesão metastática: o "pedículo ausente" — quando um pedículo desaparece no corte axial — é um dos sinais mais confiáveis de metástase, porque o tumor destrói o osso cortical do pedículo antes de dar sintomas. Vale também lembrar do rastreamento oportunista de osteoporose: medir a densidade do corpo de L1 em qualquer TC leva segundos e identifica pacientes que precisam de densitometria.',
      alteracoes: [
        { nome: 'Fratura por compressão osteoporótica', achado: 'Perda de altura do corpo, tipicamente anterior, com muro posterior preservado e sem massa de partes moles.' },
        { nome: 'Fratura em explosão (burst)', achado: 'Cominuição do corpo com recuo do muro posterior e fragmento no canal vertebral; instável.' },
        { nome: 'Metástase lítica', achado: 'Destruição trabecular com pedículo ausente e, muitas vezes, componente epidural comprimindo a cauda equina.' },
        { nome: 'Metástase blástica', achado: 'Vértebra hiperdensa ("vértebra de marfim"); típica de próstata e mama.' },
        { nome: 'Espondilodiscite', achado: 'Destruição dos platôs de duas vértebras adjacentes com perda do disco entre elas e abscesso paravertebral — o padrão que diferencia infecção (ataca o disco) de tumor (poupa o disco).' },
        { nome: 'Espondilolistese', achado: 'Escorregamento de um corpo sobre o outro; melhor avaliada em reconstrução sagital.' },
        { nome: 'Nódulo de Schmorl', achado: 'Herniação do disco para dentro do platô vertebral, com borda esclerótica; achado degenerativo comum e benigno.' },
      ],
      armadilhas: ['Vértebra de transição (lombarização de S1 ou sacralização de L5) ocorre em ~15% e é a maior fonte de erro de numeração — que já causou cirurgias no nível errado.'],
      medidas: [{ rotulo: 'Densidade trabecular em L1', valor: '< 100 UH sugere osteoporose' }],
    },
    {
      id: 'osso-iliaco-direito',
      nome: 'Osso ilíaco direito',
      sinonimos: ['ílio direito', 'osso do quadril direito'],
      categoria: 'osso',
      resumo: 'Maior componente do osso do quadril; forma a asa da pelve e a parte superior do acetábulo.',
      morfologia: 'Formado pela asa (lâmina larga e fina) e pelo corpo, que participa do acetábulo. A crista ilíaca é sua borda superior; as espinhas ilíacas anterossuperior e anteroinferior são referências de superfície. Articula-se com o sacro pela articulação sacroilíaca, uma sindesmose reforçada por ligamentos muito potentes.',
      funcao: 'Transmite a carga do tronco aos membros inferiores e serve de inserção para a musculatura abdominal e glútea. A asa ilíaca contém medula óssea vermelha, sendo local clássico de punção e biópsia medular.',
      densidade: 'Cortical densa; a asa é fina e pode simular descontinuidade por volume parcial.',
      janela: 'Óssea.',
      comoIdentificar: 'Ao entrar na pelve, é a grande lâmina óssea curva que forma a parede lateral, com o músculo ilíaco forrando sua face interna.',
      reparos: ['Sacro (articulação sacroilíaca, medialmente)', 'Músculo ilíaco (face interna)', 'Glúteos (face externa)', 'Acetábulo (inferior)'],
      clinica: 'A fratura da asa ilíaca isolada (fratura de Duverney) é estável, porque não interrompe o anel pélvico que sustenta a carga. Já a disjunção sacroilíaca é instável e frequentemente acompanha ruptura da sínfise púbica — a chamada lesão em "livro aberto", que abre a pelve, aumenta o volume pélvico e permite sangramento retroperitoneal maciço. Reconhecer esse padrão na TC muda a conduta imediata: cinta pélvica, embolização, fixação externa.',
      alteracoes: [
        { nome: 'Fratura da asa ilíaca (Duverney)', achado: 'Traço isolado na asa, sem envolvimento do anel de carga; estável.' },
        { nome: 'Disjunção sacroilíaca', achado: 'Alargamento assimétrico da articulação (> 5 mm de diferença entre os lados); componente instável da lesão em livro aberto.' },
        { nome: 'Metástase', achado: 'Lesão lítica ou blástica na asa; sítio muito frequente por conter medula vermelha.' },
        { nome: 'Sacroileíte', achado: 'Erosões, esclerose subcondral e, na fase tardia, anquilose; espondiloartrites.' },
      ],
    },
    {
      id: 'osso-iliaco-esquerdo',
      nome: 'Osso ilíaco esquerdo',
      categoria: 'osso',
      resumo: 'Contraparte esquerda; simétrico ao direito.',
      morfologia: 'Idêntica ao direito.',
      funcao: 'Transmissão de carga e inserção muscular.',
      densidade: 'Cortical densa.',
      janela: 'Óssea.',
      comoIdentificar: 'Espelho do direito. A simetria é a chave: qualquer assimetria de posição das sacroilíacas ou do contorno indica lesão.',
      reparos: ['Sacro', 'Músculo ilíaco esquerdo', 'Sigmoide (anteromedial)'],
      clinica: 'A comparação lado a lado das articulações sacroilíacas é o modo mais rápido de detectar disjunção em trauma e sacroileíte em doenças inflamatórias. Nas espondiloartrites, o acometimento costuma ser bilateral e simétrico na espondilite anquilosante, e assimétrico nas artrites reativa e psoriásica.',
      alteracoes: [
        { nome: 'Sacroileíte bilateral simétrica', achado: 'Erosões e esclerose nos dois lados; espondilite anquilosante.' },
        { nome: 'Disjunção traumática', achado: 'Alargamento assimétrico com hematoma adjacente; procurar lesão no anel anterior.' },
      ],
    },
    {
      id: 'sacro',
      nome: 'Sacro',
      categoria: 'osso',
      resumo: 'Osso triangular formado pela fusão de cinco vértebras; fecha o anel pélvico posteriormente.',
      morfologia: 'Cinco vértebras fundidas, com quatro pares de forames sacrais anteriores e posteriores por onde passam as raízes sacrais. Articula-se com L5 acima, com os ilíacos lateralmente e com o cóccix abaixo. O promontório sacral é sua borda anterossuperior proeminente.',
      funcao: 'Transmite todo o peso do tronco para os ilíacos e abriga as raízes sacrais que inervam períneo, bexiga, reto e esfíncteres. É o elemento posterior do anel pélvico.',
      densidade: 'Osso esponjoso; a cortical dos forames é fina e as linhas arqueadas devem estar íntegras e simétricas.',
      janela: 'Óssea; a reconstrução coronal é essencial — no axial, os traços verticais do sacro são quase invisíveis.',
      comoIdentificar: 'Osso triangular na linha média posterior da pelve, entre os dois ilíacos, logo abaixo de L5.',
      reparos: ['L5 (acima)', 'Articulações sacroilíacas (laterais)', 'Cóccix (abaixo)', 'Reto (anterior)'],
      clinica: 'A fratura do sacro é a lesão mais subdiagnosticada do trauma pélvico, porque os traços costumam ser verticais e o corte axial os corta longitudinalmente. A classificação de Denis divide o sacro em três zonas: zona I (lateral aos forames, 6% de lesão neurológica), zona II (transforaminal, 28%) e zona III (medial ao canal, 57% — com risco de disfunção esfincteriana). Também é sítio frequente de fratura por insuficiência em idosas osteoporóticas, com o padrão em "H" que aparece na cintilografia como sinal de Honda.',
      alteracoes: [
        { nome: 'Fratura vertical do sacro', achado: 'Traço na zona I, II ou III; melhor visto em reconstrução coronal. Sempre procurar a lesão do anel anterior associada.' },
        { nome: 'Fratura por insuficiência', achado: 'Traços bilaterais nas asas sacrais em idosa osteoporótica, com esclerose linear; padrão em H.' },
        { nome: 'Metástase / cordoma', achado: 'Lesão lítica destrutiva; o cordoma é característico da linha média sacrococcígea, com massa volumosa e calcificações.' },
        { nome: 'Cisto de Tarlov', achado: 'Cisto perineural que alarga o forame sacral; achado incidental habitualmente assintomático.' },
      ],
      armadilhas: ['Fratura sacral vertical passa despercebida no axial puro — sem reconstrução coronal, a taxa de erro é alta.'],
    },
    {
      id: 'coccix',
      nome: 'Cóccix',
      categoria: 'osso',
      resumo: 'Segmento terminal da coluna, formado por três a cinco vértebras rudimentares fundidas.',
      morfologia: 'Pequeno osso triangular articulado ao ápice do sacro pela articulação sacrococcígea. Número de segmentos e angulação são muito variáveis.',
      funcao: 'Inserção de músculos do assoalho pélvico (levantador do ânus, coccígeo) e do ligamento anococcígeo; ponto de apoio na posição sentada reclinada.',
      densidade: 'Osso pequeno, frequentemente com aspecto irregular por variação anatômica.',
      janela: 'Óssea; sagital é o único plano que o mostra bem.',
      comoIdentificar: 'Última estrutura óssea na linha média posterior, abaixo do sacro. No axial aparece como pequenos fragmentos ósseos — daí a importância do sagital.',
      reparos: ['Ápice do sacro (acima)', 'Reto (anterior)', 'Assoalho pélvico'],
      clinica: 'A coccidínia é dor local frequentemente pós-traumática ou pós-parto. O grande cuidado é não superdiagnosticar fratura: a articulação sacrococcígea e as intercoccígeas podem permanecer não fundidas e ter angulações que imitam traços de fratura. A comparação com exames antigos e a correlação clínica são indispensáveis.',
      alteracoes: [
        { nome: 'Fratura/luxação coccígea', achado: 'Angulação anormal ou degrau na articulação, em geral pós-queda sentada.' },
        { nome: 'Cisto pilonidal / abscesso', achado: 'Coleção nas partes moles na topografia sacrococcígea, com trajeto fistuloso à pele.' },
        { nome: 'Cordoma', achado: 'Massa destrutiva de linha média com componente de partes moles e calcificações.' },
      ],
      armadilhas: ['Segmentos coccígeos não fundidos são normais e imitam fratura — o achado isolado, sem trauma, não deve ser laudado como fratura.'],
    },
    {
      id: 'acetabulo-direito',
      nome: 'Acetábulo direito',
      categoria: 'osso',
      resumo: 'Cavidade articular do quadril, formada pela fusão de ílio, ísquio e púbis.',
      morfologia: 'Cavidade hemisférica com teto (formado pelo ílio), coluna anterior (ílio + púbis) e coluna posterior (ílio + ísquio). A fossa acetabular central é não articular; a superfície de carga é a porção superior, em forma de ferradura.',
      funcao: 'Recebe a cabeça femoral e transmite a carga do tronco ao membro inferior. A congruência entre acetábulo e cabeça é o que preserva a cartilagem — perdê-la leva à artrose precoce.',
      densidade: 'Cortical densa; o teto é a região mais espessa.',
      janela: 'Óssea; reconstruções 3D e obliquidades (Judet) definem as colunas.',
      comoIdentificar: 'Cavidade côncava lateral que abraça a cabeça femoral, na parte inferior do osso ilíaco.',
      reparos: ['Cabeça femoral (dentro dele)', 'Colunas anterior e posterior', 'Forame obturado (abaixo e medialmente)'],
      clinica: 'A classificação das fraturas acetabulares de Judet e Letournel — baseada em quais colunas e paredes estão comprometidas — é integralmente feita por TC, e determina a via de acesso cirúrgico. Duas coisas mudam a conduta: o degrau na superfície de carga (> 2 mm indica redução cirúrgica) e a presença de fragmento intra-articular, que precisa ser removido para evitar artrose rápida. Fratura da parede posterior é a mais comum e associa-se a luxação posterior do quadril, típica do trauma "painel de carro".',
      alteracoes: [
        { nome: 'Fratura da parede posterior', achado: 'Fragmento posterior com luxação posterior da cabeça femoral; procurar fragmentos intra-articulares e lesão do nervo isquiático.' },
        { nome: 'Fratura das duas colunas', achado: 'Dissociação completa da superfície articular do esqueleto axial; o "sinal do esporão" na obliquidade obturadora é diagnóstico.' },
        { nome: 'Protrusão acetabular', achado: 'Cabeça femoral migrando medialmente além da linha ilioisquiática; artrite reumatoide, doença de Paget, osteomalácia.' },
        { nome: 'Impacto femoroacetabular (pincer)', achado: 'Cobertura acetabular excessiva com sinal do cruzamento; causa de dor no quadril em adulto jovem.' },
      ],
    },
    {
      id: 'acetabulo-esquerdo',
      nome: 'Acetábulo esquerdo',
      categoria: 'osso',
      resumo: 'Contraparte esquerda da cavidade do quadril.',
      morfologia: 'Idêntica à direita.',
      funcao: 'Articulação com a cabeça femoral esquerda.',
      densidade: 'Cortical densa.',
      janela: 'Óssea.',
      comoIdentificar: 'Espelho do direito; comparar simetria de cobertura e de espaço articular.',
      reparos: ['Cabeça femoral esquerda', 'Forame obturado esquerdo'],
      clinica: 'A comparação bilateral do espaço articular detecta coxartrose incipiente (redução assimétrica) e displasia (cobertura reduzida). São achados incidentais frequentes na TC de abdome e pelve que explicam a queixa do paciente.',
      alteracoes: [
        { nome: 'Coxartrose', achado: 'Redução do espaço articular superior, osteófitos, esclerose subcondral e cistos.' },
        { nome: 'Displasia acetabular', achado: 'Cobertura insuficiente da cabeça femoral; causa de artrose precoce em adulto jovem.' },
      ],
    },
    {
      id: 'cabeca-do-femur-direito',
      nome: 'Cabeça do fêmur direito',
      categoria: 'osso',
      resumo: 'Extremidade esférica do fêmur que se articula com o acetábulo.',
      morfologia: 'Esfera que corresponde a cerca de dois terços de uma esfera completa, revestida de cartilagem exceto na fóvea, onde se insere o ligamento redondo. Sua vascularização depende principalmente dos vasos retinaculares, ramos da artéria circunflexa femoral medial, que sobem pelo colo — uma irrigação retrógrada e frágil.',
      funcao: 'Permite movimento em três eixos com estabilidade, graças à profundidade do acetábulo e ao lábrum. Suporta forças de até várias vezes o peso corporal na marcha.',
      densidade: 'Osso esponjoso com trabeculado orientado nas linhas de força; cortical fina.',
      janela: 'Óssea; partes moles para derrame articular.',
      comoIdentificar: 'Esfera óssea dentro do acetábulo, nos cortes pélvicos baixos.',
      reparos: ['Acetábulo (ao redor)', 'Colo femoral (abaixo e lateralmente)', 'Fóvea (depressão medial)'],
      clinica: 'A osteonecrose da cabeça femoral é consequência direta daquela vascularização retrógrada e frágil: fratura de colo, corticoterapia, alcoolismo, doença falciforme e mergulho (doença descompressiva) interrompem o fluxo e matam o osso subcondral. Na TC, o achado precoce é a esclerose serpiginosa; o tardio é o "sinal do crescente" (fratura subcondral) e o colapso da esfera. A ressonância detecta antes, mas a TC costuma ser o exame que está disponível.',
      alteracoes: [
        { nome: 'Osteonecrose', achado: 'Esclerose serpiginosa subcondral, depois sinal do crescente (linha radiolucente subcondral) e, por fim, colapso e achatamento da cabeça.' },
        { nome: 'Fratura da cabeça (Pipkin)', achado: 'Fragmento cefálico após luxação posterior; classificação depende da relação com a fóvea.' },
        { nome: 'Impacto femoroacetabular tipo cam', achado: 'Perda da esfericidade na transição cabeça-colo, com aumento do ângulo alfa.' },
        { nome: 'Derrame articular do quadril', achado: 'Distensão capsular com densidade líquida; em criança febril, obriga a excluir artrite séptica.' },
      ],
    },
    {
      id: 'cabeca-do-femur-esquerdo',
      nome: 'Cabeça do fêmur esquerdo',
      categoria: 'osso',
      resumo: 'Contraparte esquerda.',
      morfologia: 'Idêntica à direita.',
      funcao: 'Articulação do quadril esquerdo.',
      densidade: 'Osso esponjoso.',
      janela: 'Óssea.',
      comoIdentificar: 'Esfera dentro do acetábulo esquerdo; comparar esfericidade e densidade com o lado direito.',
      reparos: ['Acetábulo esquerdo', 'Colo femoral esquerdo'],
      clinica: 'A osteonecrose é bilateral em mais da metade dos casos, embora frequentemente assimétrica no tempo. Encontrar necrose de um lado obriga a examinar o outro com atenção redobrada.',
      alteracoes: [
        { nome: 'Osteonecrose bilateral', achado: 'Alterações simultâneas nos dois lados, em estágios diferentes; típico de corticoterapia e falciforme.' },
      ],
    },
    {
      id: 'colo-do-femur-direito',
      nome: 'Colo do fêmur direito',
      categoria: 'osso',
      resumo: 'Segmento entre a cabeça e os trocanteres; sede das fraturas do idoso.',
      morfologia: 'Forma ângulo cervicodiafisário de 125°–135° com a diáfise e anteversão de 10°–15°. É intracapsular — coberto pela cápsula articular —, o que tem consequência direta: uma fratura aqui não forma calo periosteal e compromete a irrigação da cabeça.',
      funcao: 'Braço de alavanca que transmite carga da cabeça à diáfise. O trabeculado interno se organiza em sistemas de compressão e tração; entre eles fica o triângulo de Ward, área de menor densidade e ponto fraco.',
      densidade: 'Osso esponjoso com trabeculado orientado; rarefação do triângulo de Ward é marcador de osteoporose.',
      janela: 'Óssea.',
      comoIdentificar: 'Segmento estreitado entre a esfera da cabeça e o volume dos trocanteres.',
      reparos: ['Cabeça femoral (acima e medialmente)', 'Trocanter maior (lateral)', 'Trocanter menor (posteromedial)', 'Cápsula articular (envolve o colo)'],
      clinica: 'A fratura do colo femoral é uma das grandes causas de morbimortalidade no idoso: mortalidade de 20–30% no primeiro ano. Por ser intracapsular, ela interrompe os vasos retinaculares e leva à osteonecrose em 15–35% dos casos com desvio — razão pela qual fraturas desviadas em idosos costumam ser tratadas com artroplastia em vez de osteossíntese. A fratura oculta, com radiografia normal e dor persistente, é uma armadilha clássica: a TC pode mostrar o traço, mas a ressonância continua sendo o padrão-ouro.',
      alteracoes: [
        { nome: 'Fratura de colo femoral', achado: 'Traço intracapsular com angulação em varo e encurtamento; classificação de Garden pelo grau de desvio orienta o tratamento.' },
        { nome: 'Fratura oculta', achado: 'Traço sutil ou apenas irregularidade trabecular; se a TC for negativa e a suspeita persistir, indicar ressonância.' },
        { nome: 'Osteonecrose pós-fratura', achado: 'Esclerose e colapso da cabeça meses após a fratura, por lesão dos vasos retinaculares.' },
        { nome: 'Fratura atípica por bisfosfonato', achado: 'Traço transverso na cortical lateral subtrocantérica com espessamento cortical local; não é no colo, mas entra no diferencial.' },
      ],
      medidas: [{ rotulo: 'Ângulo cervicodiafisário', valor: '125°–135°' }],
    },
    {
      id: 'colo-do-femur-esquerdo',
      nome: 'Colo do fêmur esquerdo',
      categoria: 'osso',
      resumo: 'Contraparte esquerda do colo femoral.',
      morfologia: 'Idêntica à direita.',
      funcao: 'Transmissão de carga.',
      densidade: 'Osso esponjoso.',
      janela: 'Óssea.',
      comoIdentificar: 'Segmento estreito entre cabeça e trocanteres do lado esquerdo.',
      reparos: ['Cabeça femoral esquerda', 'Trocanteres esquerdos'],
      clinica: 'A comparação de ângulos cervicodiafisários entre os lados detecta coxa vara e coxa valga, e a assimetria de trabeculado sugere fratura oculta no lado sintomático.',
      alteracoes: [
        { nome: 'Coxa vara / valga', achado: 'Ângulo cervicodiafisário reduzido (< 120°) ou aumentado (> 140°); altera a biomecânica e predispõe a fratura e artrose.' },
      ],
    },
    {
      id: 'ramo-pubico-superior-direito',
      nome: 'Ramo púbico superior direito',
      categoria: 'osso',
      resumo: 'Parte do púbis que se dirige do acetábulo à sínfise; componente anterior do anel pélvico.',
      morfologia: 'Vai do corpo do púbis até o acetábulo, formando a borda superior do forame obturado. Junto com o ramo inferior, delimita esse forame.',
      funcao: 'Fecha o anel pélvico anteriormente e serve de inserção para adutores e para o ligamento inguinal.',
      densidade: 'Cortical densa.',
      janela: 'Óssea.',
      comoIdentificar: 'Nos cortes pélvicos baixos, é o segmento ósseo que segue da região do acetábulo em direção à linha média anterior.',
      reparos: ['Sínfise púbica (medialmente)', 'Acetábulo (lateralmente)', 'Forame obturado (abaixo)', 'Bexiga (posterior)', 'Corona mortis (anastomose vascular na face posterior)'],
      clinica: 'A fratura de ramo púbico é a fratura pélvica mais comum, e em idosos costuma ser por queda de baixa energia. Duas cautelas importantes: primeiro, mesmo uma fratura "simples" de ramo púbico deve levar à procura de fratura sacral associada, porque o anel raramente se quebra em um só ponto; segundo, a corona mortis — uma anastomose entre os sistemas obturatório e ilíaco externo que corre na face posterior do ramo superior — pode sangrar de forma significativa e é uma armadilha em cirurgia e em trauma.',
      alteracoes: [
        { nome: 'Fratura de ramo púbico', achado: 'Traço com ou sem desvio; procurar sempre a lesão posterior associada (sacro ou sacroilíaca).' },
        { nome: 'Sangramento por corona mortis', achado: 'Extravasamento de contraste na face posterior do ramo, com hematoma pélvico.' },
        { nome: 'Fratura por insuficiência', achado: 'Traços com esclerose em idosos osteoporóticos e após radioterapia pélvica.' },
        { nome: 'Osteíte púbica', achado: 'Erosões e esclerose nos bordos da sínfise, em atletas e no pós-parto.' },
      ],
    },
    {
      id: 'ramo-pubico-superior-esquerdo',
      nome: 'Ramo púbico superior esquerdo',
      categoria: 'osso',
      resumo: 'Contraparte esquerda do ramo púbico superior.',
      morfologia: 'Idêntica à direita.',
      funcao: 'Fecha o anel anterior; inserção muscular.',
      densidade: 'Cortical densa.',
      janela: 'Óssea.',
      comoIdentificar: 'Espelho do direito, à esquerda da sínfise.',
      reparos: ['Sínfise púbica', 'Acetábulo esquerdo', 'Forame obturado esquerdo'],
      clinica: 'Fraturas bilaterais dos ramos púbicos, superior e inferior, configuram a fratura "em borboleta" — segmento anterior livre, que costuma indicar instabilidade e acompanhar lesão posterior.',
      alteracoes: [
        { nome: 'Fratura em borboleta', achado: 'Fraturas bilaterais dos quatro ramos, com segmento anterior livre; instável.' },
      ],
    },
    {
      id: 'pubis-direito',
      nome: 'Púbis direito',
      categoria: 'osso',
      resumo: 'Porção anterior do osso do quadril, que se articula com o contralateral na sínfise púbica.',
      morfologia: 'Corpo achatado com ramos superior e inferior. Os dois corpos púbicos se unem na linha média por um disco fibrocartilaginoso — a sínfise púbica, cuja largura normal é de 4 a 5 mm no adulto.',
      funcao: 'Fecha o anel pélvico anteriormente e é inserção dos adutores e do músculo reto abdominal. Na gestação, a sínfise amolece pela ação da relaxina e alarga alguns milímetros.',
      densidade: 'Cortical densa; a sínfise é fibrocartilaginosa e aparece como espaço de partes moles.',
      janela: 'Óssea.',
      comoIdentificar: 'Nos cortes mais baixos, é o osso na linha média anterior, imediatamente à frente da bexiga.',
      reparos: ['Sínfise púbica (linha média)', 'Bexiga (posterior)', 'Espaço de Retzius (entre púbis e bexiga)'],
      clinica: 'A diástase da sínfise púbica além de 25 mm indica ruptura dos ligamentos sacroilíacos anteriores e caracteriza a lesão em livro aberto, instável e com alto risco de sangramento — indicação imediata de cinta pélvica. Além disso, o espaço de Retzius, entre púbis e bexiga, é onde se acumula o hematoma pélvico e para onde extravasa a urina na ruptura vesical extraperitoneal, frequentemente associada a fratura de ramos púbicos.',
      alteracoes: [
        { nome: 'Diástase da sínfise', achado: 'Alargamento > 10 mm é anormal; > 25 mm indica lesão instável em livro aberto.' },
        { nome: 'Ruptura vesical extraperitoneal', achado: 'Extravasamento de contraste no espaço de Retzius na cistografia por TC, associado a fratura de ramos púbicos.' },
        { nome: 'Osteíte púbica', achado: 'Esclerose e erosões simétricas nos bordos da sínfise.' },
      ],
    },
    {
      id: 'pubis-esquerdo',
      nome: 'Púbis esquerdo',
      categoria: 'osso',
      resumo: 'Contraparte esquerda do púbis.',
      morfologia: 'Idêntica à direita.',
      funcao: 'Fechamento anterior do anel pélvico.',
      densidade: 'Cortical densa.',
      janela: 'Óssea.',
      comoIdentificar: 'À esquerda da sínfise, na linha média anterior.',
      reparos: ['Sínfise púbica', 'Bexiga', 'Adutores (inserção)'],
      clinica: 'A avaliação da sínfise deve ser feita comparando a altura dos dois corpos púbicos: um degrau vertical indica lesão de cisalhamento vertical (padrão de Malgaigne), a forma mais instável de lesão pélvica.',
      alteracoes: [
        { nome: 'Lesão de cisalhamento vertical (Malgaigne)', achado: 'Degrau vertical na sínfise com fratura ou disjunção posterior no mesmo lado; máxima instabilidade.' },
      ],
    },
    {
      id: 'isquio-direito',
      nome: 'Ísquio direito',
      categoria: 'osso',
      resumo: 'Porção posteroinferior do osso do quadril; sua tuberosidade suporta o peso na posição sentada.',
      morfologia: 'Corpo que participa do acetábulo e da parede posterior, mais o ramo isquiático que se une ao ramo púbico inferior. A tuberosidade isquiática é sua proeminência posteroinferior; a espinha isquiática separa as incisuras ciáticas maior e menor.',
      funcao: 'Suporte na posição sentada e inserção dos isquiotibiais e do ligamento sacrotuberal. A espinha isquiática é referência obstétrica clássica para avaliar a descida fetal.',
      densidade: 'Cortical densa.',
      janela: 'Óssea.',
      comoIdentificar: 'Nos cortes pélvicos baixos, é o osso posteroinferior, que se torna a tuberosidade — a proeminência sobre a qual se senta.',
      reparos: ['Acetábulo (acima)', 'Ramo púbico inferior (anteriormente)', 'Forame obturado (medialmente)', 'Nervo isquiático (posterior à espinha)'],
      clinica: 'A avulsão da tuberosidade isquiática é lesão típica de adolescente atleta, por contração violenta dos isquiotibiais — e ela pode ser confundida com tumor na fase de consolidação, quando forma osso exuberante. Em adultos acamados, a tuberosidade é sítio de úlcera de pressão e de osteomielite subjacente.',
      alteracoes: [
        { nome: 'Avulsão da tuberosidade isquiática', achado: 'Fragmento ósseo deslocado em adolescente; na consolidação, exuberância óssea que imita tumor.' },
        { nome: 'Osteomielite por úlcera de pressão', achado: 'Erosão cortical com realce medular sob úlcera isquiática.' },
        { nome: 'Metástase', achado: 'Lesão lítica com destruição cortical.' },
      ],
    },
    {
      id: 'isquio-esquerdo',
      nome: 'Ísquio esquerdo',
      categoria: 'osso',
      resumo: 'Contraparte esquerda do ísquio.',
      morfologia: 'Idêntica à direita.',
      funcao: 'Suporte sentado e inserção dos isquiotibiais.',
      densidade: 'Cortical densa.',
      janela: 'Óssea.',
      comoIdentificar: 'Espelho do direito.',
      reparos: ['Acetábulo esquerdo', 'Forame obturado esquerdo', 'Tuberosidade isquiática esquerda'],
      clinica: 'Em pacientes acamados, comparar as duas tuberosidades detecta assimetria de partes moles e osteomielite precoce.',
      alteracoes: [
        { nome: 'Bursite isquiática', achado: 'Coleção junto à tuberosidade; a "doença do alfaiate", por pressão prolongada.' },
      ],
    },
    {
      id: 'diafise-proximal-do-femur-direito',
      nome: 'Diáfise proximal do fêmur direito',
      categoria: 'osso',
      resumo: 'Segmento tubular do fêmur logo abaixo dos trocanteres.',
      morfologia: 'Cortical espessa envolvendo canal medular amplo com gordura. A região subtrocantérica, nos 5 cm abaixo do trocanter menor, é submetida às maiores forças compressivas do esqueleto.',
      funcao: 'Transmissão de carga ao joelho e inserção da musculatura da coxa. O canal medular contém medula amarela no adulto.',
      densidade: 'Cortical > 1000 UH; canal medular gorduroso (−30 a −100 UH).',
      janela: 'Óssea; partes moles para avaliar componente extraósseo.',
      comoIdentificar: 'Nos últimos cortes da série, são os dois tubos ósseos com cortical espessa e centro gorduroso.',
      reparos: ['Trocanter menor (acima)', 'Musculatura da coxa (ao redor)', 'Vasos femorais (anteromediais)'],
      clinica: 'A região subtrocantérica é sede da fratura atípica associada ao uso prolongado de bisfosfonatos: traço transverso na cortical LATERAL, com espessamento cortical focal ("bico"), muitas vezes bilateral e precedido de dor na coxa. Reconhecê-la muda a conduta — suspende-se o bisfosfonato e avalia-se fixação profilática do lado contralateral. A diáfise femoral também é sítio frequente de metástase, e lesão lítica ocupando mais de 50% da cortical indica fixação profilática antes que ocorra fratura patológica.',
      alteracoes: [
        { nome: 'Fratura atípica por bisfosfonato', achado: 'Traço transverso na cortical lateral subtrocantérica com espessamento cortical local; frequentemente bilateral.' },
        { nome: 'Metástase com risco de fratura patológica', achado: 'Lesão lítica > 50% da cortical ou > 2,5 cm; indicação de fixação profilática.' },
        { nome: 'Osteomielite crônica', achado: 'Espessamento cortical, sequestro ósseo e trajeto fistuloso.' },
      ],
    },
    {
      id: 'diafise-proximal-do-femur-esquerdo',
      nome: 'Diáfise proximal do fêmur esquerdo',
      categoria: 'osso',
      resumo: 'Contraparte esquerda da diáfise proximal.',
      morfologia: 'Idêntica à direita.',
      funcao: 'Transmissão de carga.',
      densidade: 'Cortical densa com canal medular gorduroso.',
      janela: 'Óssea.',
      comoIdentificar: 'Espelho da direita; comparar espessura cortical e conteúdo medular.',
      reparos: ['Trocanter menor esquerdo', 'Musculatura da coxa esquerda'],
      clinica: 'Nas fraturas atípicas por bisfosfonato, o achado contralateral é a regra: encontrar espessamento cortical lateral de um lado obriga a examinar o outro, porque a fixação profilática bilateral costuma ser indicada.',
      alteracoes: [
        { nome: 'Reação cortical contralateral', achado: 'Espessamento cortical lateral assintomático no fêmur oposto ao da fratura atípica.' },
      ],
    },
  ],
  quiz: [
    {
      pergunta: 'Ao encontrar uma fratura isolada de ramo púbico na TC, qual é a conduta de leitura obrigatória?',
      alternativas: [
        'Concluir que a lesão é isolada e estável',
        'Procurar ativamente uma segunda lesão no anel posterior (sacro ou sacroilíaca)',
        'Solicitar ressonância imediatamente',
        'Repetir a TC em 24 horas',
      ],
      correta: 1,
      explicacao: 'A pelve é um anel: uma única fratura é biomecanicamente improvável. A segunda lesão pode ser óssea (sacro) ou ligamentar (disjunção sacroilíaca ou da sínfise), e é ela que define a instabilidade.',
    },
    {
      pergunta: 'O "sinal do pedículo ausente" em vértebra lombar sugere:',
      alternativas: ['Espondilodiscite', 'Metástase', 'Fratura por compressão osteoporótica', 'Nódulo de Schmorl'],
      correta: 1,
      explicacao: 'A destruição do pedículo (que na radiografia dá o aspecto de "coruja piscando") é sinal clássico de metástase. Espondilodiscite ataca preferencialmente o disco e os platôs adjacentes; a fratura osteoporótica reduz a altura do corpo sem destruir o pedículo.',
    },
    {
      pergunta: 'Por que a fratura do colo femoral com desvio frequentemente evolui para osteonecrose?',
      alternativas: [
        'Porque o osso é muito denso',
        'Porque é intracapsular e rompe os vasos retinaculares que sobem pelo colo até a cabeça',
        'Porque não forma calo periosteal',
        'Por infecção secundária',
      ],
      correta: 1,
      explicacao: 'A cabeça femoral recebe sangue de forma retrógrada, pelos vasos retinaculares que sobem ao longo do colo (ramos da circunflexa femoral medial). Uma fratura deslocada nesse ponto interrompe o suprimento, e a osteonecrose ocorre em 15–35% dos casos.',
    },
    {
      pergunta: 'Fratura vertical do sacro é frequentemente subdiagnosticada porque:',
      alternativas: [
        'O sacro é radiotransparente',
        'O traço é vertical e o corte axial o secciona longitudinalmente — só o plano coronal o revela bem',
        'A janela óssea não mostra o sacro',
        'A fratura só aparece após 48 horas',
      ],
      correta: 1,
      explicacao: 'Traços verticais correm paralelos ao eixo do corte axial e podem ser quase invisíveis nele. A reconstrução coronal é obrigatória no trauma pélvico — e a classificação de Denis em zonas I, II e III prediz o risco neurológico.',
    },
    {
      pergunta: 'Um traço transverso na cortical lateral da região subtrocantérica, com espessamento cortical focal, em paciente em uso prolongado de bisfosfonato, corresponde a:',
      alternativas: ['Metástase', 'Fratura atípica do fêmur', 'Osteomielite', 'Fratura de estresse comum'],
      correta: 1,
      explicacao: 'É a fratura atípica associada a bisfosfonatos — transversa, na cortical lateral, com espessamento cortical em "bico", frequentemente bilateral e precedida de dor na coxa. Exige suspender a droga e avaliar fixação profilática contralateral.',
    },
  ],
}
