import type { SubsecaoTC } from '../tipos'

export const abdomePelveFeminina: SubsecaoTC = {
  id: 'pelve-feminina',
  titulo: 'Pelve feminina',
  subtitulo: 'Útero e ovários — anatomia, ciclo e as urgências ginecológicas na TC',
  secaoId: 'abdome',
  pasta: '/TC_ABDOME/TC_ABDOME_PELVE_FEMININA',
  ext: 'JPG',
  totalCortes: 24,
  orientacao: 'cranio-caudal',
  icone: 'venus',
  cor: 'rosa',
  janelaPadrao: 'mediastinal',
  protocolo:
    'TC de abdome e pelve com contraste endovenoso em fase venosa (70–90 s) — o útero é um órgão de realce lento e progressivo, e na fase arterial o miométrio aparece heterogêneo de forma fisiológica, o que já foi laudado como lesão inúmeras vezes. Bexiga moderadamente cheia melhora a definição do fundo uterino e dos anexos. Vale lembrar que a TC NÃO é o exame de escolha para a pelve feminina: a ultrassonografia transvaginal e a ressonância caracterizam muito melhor útero e ovários. A TC entra quando a pergunta é abdome agudo, estadiamento oncológico ou trauma.',
  introducao:
    'A pelve feminina é a região em que a TC mais precisa de humildade e mais precisa de contexto. Humildade porque o contraste de tecidos moles é insuficiente para separar endométrio, junctional zone e miométrio — coisas que a ressonância mostra com naturalidade. E contexto porque a aparência normal muda radicalmente com idade, fase do ciclo, paridade e uso de hormônios: um ovário com folículos de 2 cm é normal numa mulher de 25 anos e é suspeito numa de 70. Dito isso, a TC tem papéis insubstituíveis. Ela é o exame que a paciente com dor abdominal aguda vai fazer no pronto-socorro, e é ali que aparecem torção anexial, cisto roto com hemoperitônio, doença inflamatória pélvica e abscesso tubo-ovariano. Ela é também o exame de estadiamento do câncer de ovário, capaz de mapear implantes peritoneais, ascite e doença no omento. Percorrer esta série é aprender a reconhecer as três estruturas centrais — útero na linha média, ovários nas fossas anexiais — e a saber quando o que se vê é fisiológico e quando merece um exame melhor.',
  roteiro: [
    { passo: '1. Ache o útero na linha média', detalhe: 'Estrutura de partes moles entre a bexiga (à frente) e o reto (atrás). O realce miometrial intenso o distingue de tudo ao redor.' },
    { passo: '2. Determine a versão e a flexão', detalhe: 'Anteversoflexão é o mais comum; o útero retrovertido é variante normal, mas muda a aparência em todos os cortes.' },
    { passo: '3. Siga os ligamentos largos até os anexos', detalhe: 'Os ovários ficam lateralmente, tipicamente junto aos vasos ilíacos internos, na fossa ovárica.' },
    { passo: '4. Caracterize os ovários pela idade', detalhe: 'Folículos são normais na menacme. Na pós-menopausa, o ovário é pequeno e homogêneo — qualquer cisto merece atenção.' },
    { passo: '5. Olhe o fundo de saco', detalhe: 'Pequena quantidade de líquido no fundo de saco de Douglas é fisiológica na menacme; líquido de alta densidade é sangue.' },
    { passo: '6. Termine pelo peritônio e o omento', detalhe: 'No estadiamento de câncer de ovário, os implantes peritoneais e o "bolo omental" definem a doença.' },
  ],
  perolas: [
    'Líquido livre pélvico de baixa densidade (0–15 UH) em mulher na menacme costuma ser fisiológico. Densidade > 30 UH é sangue e muda tudo.',
    'Ovário na pós-menopausa deve ser pequeno e sem folículos. Cisto > 3 cm nessa faixa exige avaliação complementar.',
    'Torção ovariana: ovário aumentado, deslocado para a linha média, com folículos periféricos ("colar de pérolas") e o "sinal do redemoinho" no pedículo vascular.',
    'Dispositivo intrauterino fora da cavidade é achado que muda a conduta — o DIU migrado pode perfurar e alojar-se na cavidade peritoneal.',
    'Miomas calcificados são achados incidentais extremamente comuns na TC de abdome e não precisam de investigação adicional quando típicos.',
  ],
  estruturas: [
    {
      id: 'utero',
      nome: 'Útero',
      categoria: 'genital',
      resumo: 'Órgão muscular oco na linha média pélvica, entre a bexiga e o reto; sede da gestação.',
      morfologia: 'Formado por fundo, corpo, istmo e colo. Mede aproximadamente 7–9 cm de comprimento na nulípara e cresce com a paridade. Parede em três camadas: endométrio (interno), miométrio (muscular, espesso) e serosa. Na maioria das mulheres está em anteversoflexão — inclinado para a frente sobre a bexiga. É sustentado pelos ligamentos largos, redondos e uterossacros.',
      funcao: 'Recebe o embrião, abriga a gestação e gera as contrações do parto. O endométrio prolifera e descama ciclicamente sob comando hormonal; o miométrio é o músculo liso mais potente do corpo, capaz de gerar as pressões do trabalho de parto e de fazer a hemostasia pós-parto por contração ("ligaduras vivas de Pinard").',
      densidade: 'Miométrio sem contraste: 40–60 UH. Com contraste na fase venosa, realce intenso e homogêneo (100–150 UH) — costuma ser a estrutura pélvica que mais realça. O endométrio realça menos e aparece como faixa central hipodensa. Na fase arterial, o miométrio realça de forma HETEROGÊNEA de modo fisiológico.',
      janela: 'Partes moles.',
      comoIdentificar: 'Estrutura de partes moles em forma de pera na linha média, entre a bexiga (anterior) e o reto (posterior), com realce marcadamente mais intenso que os tecidos vizinhos. Nos cortes mais baixos aparece o colo, mais denso e fibroso.',
      reparos: ['Bexiga (anterior)', 'Reto (posterior)', 'Fundo de saco de Douglas (entre útero e reto)', 'Ligamentos largos e ovários (laterais)', 'Ureteres (cruzam sob as artérias uterinas, ~2 cm lateral ao colo)'],
      clinica: 'A relação entre o ureter e a artéria uterina — "água por baixo da ponte", com o ureter passando sob a artéria a cerca de 2 cm do colo — é uma das anatomias cirúrgicas mais importantes da medicina: é ali que o ureter é lesado em histerectomia. Na oncologia, a TC estadia o câncer de endométrio e de colo procurando invasão de parametrio, bexiga e reto, hidronefrose (que já classifica o câncer de colo como estádio IIIB) e linfonodomegalia. E em emergência, o útero gravídico e a retenção de restos placentários são diagnósticos que aparecem em TCs feitas por outros motivos.',
      alteracoes: [
        { nome: 'Leiomioma (mioma)', achado: 'Massa miometrial bem definida, isodensa ou hipodensa, frequentemente com calcificações grosseiras em "pipoca"; deforma o contorno uterino. Achado incidental muito comum.' },
        { nome: 'Adenomiose', achado: 'Espessamento miometrial difuso e assimétrico com contorno preservado; a TC é ruim para esse diagnóstico — a ressonância é o exame.' },
        { nome: 'Câncer de endométrio', achado: 'Espessamento endometrial com massa hipodensa realçando menos que o miométrio; avaliar invasão miometrial e linfonodos.' },
        { nome: 'Câncer de colo uterino', achado: 'Massa cervical hipodensa com perda dos planos parametriais; hidronefrose indica pelo menos estádio IIIB.' },
        { nome: 'Piométrio / hematométrio', achado: 'Cavidade uterina distendida por conteúdo líquido ou com nível; obstrução cervical em idosa exige excluir neoplasia.' },
        { nome: 'DIU malposicionado ou migrado', achado: 'Dispositivo hiperdenso fora da cavidade, no miométrio ou na cavidade peritoneal.' },
        { nome: 'Gestação', achado: 'Útero aumentado com saco gestacional; se identificado inadvertidamente, interromper a aquisição e registrar.' },
      ],
      armadilhas: [
        'O realce miometrial heterogêneo na fase arterial é fisiológico e já foi laudado como massa incontáveis vezes — reavalie na fase venosa.',
        'Um útero muito anteflectido pode aparecer em cortes axiais como duas estruturas separadas (corpo e colo), simulando massa anexial.',
      ],
      medidas: [{ rotulo: 'Comprimento (nulípara)', valor: '7–8 cm' }, { rotulo: 'Comprimento (multípara)', valor: 'até 9–10 cm' }],
    },
    {
      id: 'ovario-direito',
      nome: 'Ovário direito',
      categoria: 'genital',
      resumo: 'Gônada feminina situada na fossa ovárica, lateralmente ao útero; produz óvulos e hormônios sexuais.',
      morfologia: 'Amêndoa de 3 × 2 × 1 cm na menacme, com volume de até 10 mL. Situa-se na fossa ovárica, delimitada pelos vasos ilíacos externos (à frente) e pelos ilíacos internos e ureter (atrás). Preso ao útero pelo ligamento útero-ovárico e à parede pélvica pelo ligamento suspensor (infundibulopélvico), que carrega os vasos gonadais. Na pós-menopausa atrofia para 1–2 cm e perde os folículos.',
      funcao: 'Produção de ovócitos e de estrogênio, progesterona e androgênios. É o único órgão intraperitoneal sem revestimento peritoneal completo — o ovócito é liberado diretamente na cavidade, fato que explica por que o câncer de ovário dissemina tão precocemente pelo peritônio.',
      densidade: 'Estroma: 40–50 UH, com realce moderado. Folículos: densidade líquida (0–15 UH). Corpo lúteo: cisto de paredes realçantes, muitas vezes com conteúdo hemorrágico (30–60 UH) — achado fisiológico frequentemente confundido com abscesso ou lesão.',
      janela: 'Partes moles.',
      comoIdentificar: 'Procure a fossa ovárica: siga os vasos ilíacos internos e olhe imediatamente à frente e medialmente. Em mulheres na menacme, os folículos (pequenos cistos) tornam o ovário fácil de reconhecer; na pós-menopausa ele é pequeno e pode ser praticamente invisível na TC.',
      reparos: ['Vasos ilíacos internos (posteriores à fossa ovárica)', 'Ureter (posterior)', 'Útero (medial, ligado pelo ligamento útero-ovárico)', 'Vasos gonadais (no ligamento suspensor, seguindo em direção cranial)'],
      clinica: 'Duas emergências definem a importância deste órgão na TC. A torção anexial ocorre quando o ovário roda sobre o pedículo vascular, e o achado mais específico é o "sinal do redemoinho" — os vasos do pedículo enrolados — junto com ovário aumentado, deslocado medialmente e com os folículos empurrados para a periferia ("colar de pérolas"). Como a drenagem venosa cessa antes da arterial, o ovário incha muito antes de infartar, e há janela para salvá-lo. A segunda é o cisto hemorrágico roto, com líquido de alta densidade no fundo de saco e, nos casos graves, hemoperitônio significativo. Vale lembrar que a torção acomete mais o lado DIREITO, provavelmente porque o sigmoide limita a mobilidade do anexo esquerdo.',
      alteracoes: [
        { nome: 'Torção anexial', achado: 'Ovário aumentado (> 5 cm) e deslocado para a linha média, folículos periféricos em "colar de pérolas", sinal do redemoinho no pedículo, líquido livre e ausência ou redução de realce.' },
        { nome: 'Cisto funcional', achado: 'Lesão de densidade líquida, parede fina, sem componente sólido; até 3 cm na menacme é folículo normal.' },
        { nome: 'Cisto hemorrágico', achado: 'Conteúdo denso (30–60 UH) com parede realçante; pode romper e produzir hemoperitônio.' },
        { nome: 'Endometrioma', achado: 'Cisto de conteúdo denso e homogêneo, frequentemente múltiplo e aderente; a ressonância é o exame de escolha.' },
        { nome: 'Teratoma maduro (cisto dermoide)', achado: 'Lesão com gordura (densidade negativa), calcificação/dente e nível gordura-líquido — praticamente patognomônico na TC.' },
        { nome: 'Carcinoma de ovário', achado: 'Massa cística com componentes sólidos e septos espessos realçantes, ascite, implantes peritoneais e "bolo omental".' },
        { nome: 'Abscesso tubo-ovariano', achado: 'Massa anexial complexa com realce periférico espesso, gás e densificação da gordura, no contexto de doença inflamatória pélvica.' },
      ],
      armadilhas: [
        'O corpo lúteo normal tem parede espessa e realçante e é rotineiramente confundido com abscesso ou com lesão neoplásica — a correlação com a fase do ciclo resolve.',
        'Ovários podem estar em posição alta (pós-histerectomia) ou pélvica profunda, dificultando a identificação.',
      ],
      medidas: [{ rotulo: 'Volume na menacme', valor: 'até 10 mL' }, { rotulo: 'Volume na pós-menopausa', valor: 'até 6 mL' }],
    },
    {
      id: 'ovario-esquerdo',
      nome: 'Ovário esquerdo',
      categoria: 'genital',
      resumo: 'Gônada esquerda, na fossa ovárica esquerda; funcionalmente idêntica à direita.',
      morfologia: 'Mesmas dimensões e estrutura do direito. Sua drenagem venosa é diferente: a veia gonadal esquerda drena na VEIA RENAL ESQUERDA (em ângulo reto), enquanto a direita drena diretamente na cava. Essa assimetria tem consequência clínica.',
      funcao: 'Ovulação e produção hormonal, alternando-se irregularmente com o direito.',
      densidade: 'Igual ao direito.',
      janela: 'Partes moles.',
      comoIdentificar: 'Fossa ovárica esquerda, à frente dos vasos ilíacos internos esquerdos. O sigmoide costuma estar próximo e pode dificultar a identificação — uma alça com conteúdo pode ser confundida com massa anexial.',
      reparos: ['Vasos ilíacos internos esquerdos', 'Sigmoide (anteromedial — fonte de confusão)', 'Útero (medial)', 'Veia gonadal esquerda (drena na veia renal esquerda)'],
      clinica: 'A drenagem da veia gonadal esquerda na veia renal esquerda explica a síndrome de congestão pélvica ser mais comum à esquerda: qualquer aumento de pressão na renal esquerda (inclusive a compressão na pinça aortomesentérica, na síndrome de quebra-nozes) se transmite retrogradamente às veias pélvicas, que se dilatam e causam dor pélvica crônica, pior em pé e no fim do dia. Na TC, veem-se veias parauterinas dilatadas e tortuosas, com refluxo gonadal.',
      alteracoes: [
        { nome: 'Síndrome de congestão pélvica', achado: 'Veias parauterinas e gonadais dilatadas (> 5 mm) e tortuosas, com refluxo; associação com quebra-nozes.' },
        { nome: 'Torção anexial esquerda', achado: 'Menos frequente que à direita; mesmos sinais (redemoinho, colar de pérolas, deslocamento medial).' },
        { nome: 'Massa anexial esquerda x alça sigmoide', achado: 'Diferenciar exige seguir a estrutura em cortes contíguos; a alça é tubular e contínua, a massa é focal.' },
      ],
      armadilhas: ['O sigmoide preenchido por fezes é a pseudomassa anexial esquerda mais frequente da TC.'],
    },
  ],
  quiz: [
    {
      pergunta: 'Qual achado é MAIS específico de torção anexial na TC?',
      alternativas: [
        'Líquido livre no fundo de saco',
        'Sinal do redemoinho no pedículo vascular',
        'Ovário com folículos',
        'Espessamento do endométrio',
      ],
      correta: 1,
      explicacao: 'O "whirlpool sign" — vasos do pedículo enrolados — é o achado mais específico. Acompanha ovário aumentado, deslocado para a linha média e com folículos periféricos em colar de pérolas. Líquido livre é inespecífico.',
    },
    {
      pergunta: 'Uma lesão anexial contendo gordura, calcificação semelhante a dente e nível gordura-líquido corresponde a:',
      alternativas: ['Endometrioma', 'Teratoma maduro (cisto dermoide)', 'Cistoadenoma seroso', 'Abscesso tubo-ovariano'],
      correta: 1,
      explicacao: 'A combinação de gordura macroscópica (densidade negativa), calcificação/dente e nível gordura-líquido é praticamente patognomônica de teratoma maduro — um dos poucos diagnósticos ginecológicos que a TC faz com segurança.',
    },
    {
      pergunta: 'Por que o ureter é lesado em histerectomia?',
      alternativas: [
        'Porque passa dentro do miométrio',
        'Porque cruza SOB a artéria uterina, cerca de 2 cm lateralmente ao colo',
        'Porque adere ao ovário',
        'Porque passa à frente da bexiga',
      ],
      correta: 1,
      explicacao: 'A regra mnemônica é "água por baixo da ponte": o ureter (água) passa sob a artéria uterina (ponte), a aproximadamente 2 cm do colo. É exatamente onde a artéria é ligada, e por isso o ponto de lesão ureteral iatrogênica clássico.',
    },
    {
      pergunta: 'Realce miometrial heterogêneo na fase ARTERIAL de uma TC pélvica deve ser interpretado como:',
      alternativas: [
        'Massa uterina',
        'Achado fisiológico — reavaliar na fase venosa',
        'Adenomiose',
        'Necrose miometrial',
      ],
      correta: 1,
      explicacao: 'O miométrio realça de forma progressiva e desigual na fase arterial; só na fase venosa ele se homogeneíza. É uma pseudolesão clássica que já gerou muitos laudos equivocados.',
    },
    {
      pergunta: 'Por que a síndrome de congestão pélvica é mais frequente à esquerda?',
      alternativas: [
        'Porque o ovário esquerdo é maior',
        'Porque a veia gonadal esquerda drena em ângulo reto na veia renal esquerda, transmitindo pressão retrogradamente',
        'Porque o sigmoide comprime o anexo',
        'Porque a artéria uterina esquerda é mais calibrosa',
      ],
      correta: 1,
      explicacao: 'A veia gonadal esquerda drena na renal esquerda (a direita vai direto à cava). Qualquer aumento de pressão na renal esquerda — incluindo a compressão aortomesentérica — reflete-se nas veias pélvicas, que se dilatam e causam dor crônica.',
    },
  ],
}
