import type { SubsecaoTC } from '../tipos'

export const cranioViasLiquoricas: SubsecaoTC = {
  id: 'vias-liquoricas',
  titulo: 'Vias de circulação liquórica',
  subtitulo: 'Ventrículos, aqueduto, cisternas e sulcos — o caminho do líquor',
  secaoId: 'cranio',
  pasta: '/TC_CRANIO/TC_CRANIO_VIAS_DE_CIRCULAÇÃO_LIQUÓRICA',
  ext: 'PNG',
  totalCortes: 16,
  orientacao: 'caudo-cranial',
  icone: 'waves',
  cor: 'ciano',
  janelaPadrao: 'cerebral',
  protocolo:
    'TC de crânio sem contraste, janela cerebral. Como o líquor tem densidade próxima da água (0–15 UH) e o parênquima está entre 25 e 45 UH, o contraste natural é excelente e a TC é o exame de escolha para avaliar tamanho ventricular e para o seguimento de hidrocefalia e de válvulas de derivação. Para fístula liquórica, faz-se cisternotomografia com contraste intratecal; para estudar o fluxo, a ressonância com sequências de fluxo é superior.',
  introducao:
    'O líquor é produzido nos plexos coroides, sobretudo dos ventrículos laterais, num ritmo de cerca de 500 mL por dia — o que significa que o volume total, de 150 mL, é renovado três a quatro vezes ao dia. O caminho é fixo e vale memorizá-lo, porque é ele que explica todas as hidrocefalias: dos ventrículos laterais o líquor passa pelos forames de Monro ao terceiro ventrículo, desce pelo aqueduto de Sylvius ao quarto ventrículo, sai pelos forames de Luschka (laterais) e Magendie (mediano) para as cisternas da base, circula pelo espaço subaracnóideo e é reabsorvido nas granulações aracnoides dos seios durais. Qualquer estreitamento nesse trajeto produz hidrocefalia OBSTRUTIVA (não comunicante), com dilatação a montante e normalidade a jusante — e localizar o ponto de obstrução é exatamente ler onde a dilatação para. Quando o problema é na reabsorção, e não no trânsito, a hidrocefalia é COMUNICANTE e todo o sistema dilata. A segunda função dos espaços liquóricos é servir de reserva: são eles que absorvem o aumento de volume intracraniano, e seu apagamento progressivo — sulcos, depois cisternas — é a maneira como a TC anuncia a hipertensão intracraniana antes de qualquer herniação.',
  roteiro: [
    { passo: '1. Avalie os ventrículos laterais', detalhe: 'Tamanho, simetria e configuração dos cornos frontais, occipitais e temporais.' },
    { passo: '2. Siga o caminho do líquor', detalhe: 'Monro, terceiro ventrículo, aqueduto, quarto ventrículo. Onde a dilatação para, está a obstrução.' },
    { passo: '3. Examine as cisternas da base', detalhe: 'Devem ser escuras e simétricas. Sangue nelas é hemorragia subaracnóidea; apagamento é hipertensão intracraniana.' },
    { passo: '4. Olhe as fissuras de Sylvius', detalhe: 'Simétricas e abertas. Assimetria pode ser efeito de massa; conteúdo denso é sangue.' },
    { passo: '5. Percorra os sulcos até o vértice', detalhe: 'Apagamento difuso = edema; alargamento = atrofia. Compare com a idade do paciente.' },
    { passo: '6. Calcule o índice de Evans quando houver dúvida', detalhe: 'Maior largura dos cornos frontais dividida pelo maior diâmetro biparietal interno; acima de 0,30 indica ventriculomegalia.' },
  ],
  perolas: [
    'Índice de Evans > 0,30 define ventriculomegalia. É a medida mais usada e mais simples do exame.',
    'Hidrocefalia obstrutiva: dilata acima do obstáculo e não abaixo. Aqueduto estenosado dilata laterais e terceiro, poupando o quarto.',
    'Atrofia x hidrocefalia: na atrofia, os sulcos estão alargados junto com os ventrículos; na hidrocefalia, os ventrículos dilatam e os sulcos ficam apagados.',
    'Hemorragia subaracnóidea: sangue hiperdenso preenchendo cisternas e fissuras que deveriam ser escuras. Distribuição perimesencefálica pura tem prognóstico melhor.',
    'Sinal do transudato transependimário: halo hipodenso ao redor dos cornos frontais indica hidrocefalia AGUDA, com líquor sendo forçado através do epêndima.',
    'Apagamento das cisternas da base é o alarme final: significa que a reserva de espaço acabou e a herniação é iminente.',
  ],
  estruturas: [
    {
      id: 'cisternas-da-base',
      nome: 'Cisternas da base',
      categoria: 'liquor',
      resumo: 'Dilatações do espaço subaracnóideo na base do crânio, onde o líquor circula ao redor do tronco e dos vasos.',
      morfologia: 'Conjunto de espaços comunicantes: cisterna supra-selar (em estrela de cinco pontas, ao redor do polígono de Willis), interpeduncular, pré-pontina, ambiens (contornando o mesencéfalo), quadrigeminal e magna. Contêm os grandes vasos e os nervos cranianos.',
      funcao: 'Amortecimento hidráulico do encéfalo, circulação do líquor da fossa posterior para a convexidade, e alojamento de artérias e nervos cranianos. Funcionam como o espaço de reserva do compartimento intracraniano.',
      densidade: 'Líquor 0–15 UH — devem aparecer escuras e simétricas. Sangue subaracnóideo agudo: 50–70 UH, tornando as cisternas brancas.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Nos cortes da base do crânio, são os espaços escuros ao redor do mesencéfalo e da ponte. A cisterna supra-selar, em forma de estrela de cinco pontas, é a mais reconhecível.',
      reparos: ['Mesencéfalo (cercado pelas cisternas perimesencefálicas)', 'Polígono de Willis (dentro da supra-selar)', 'Ponte (à frente, pela pré-pontina)', 'Cerebelo (atrás, pela magna)'],
      clinica: 'As cisternas da base concentram dois dos achados mais urgentes de toda a TC de crânio. O primeiro é a hemorragia subaracnóidea: sangue hiperdenso preenchendo cisternas que deveriam ser escuras, quase sempre por ruptura de aneurisma, e cuja distribuição sugere a origem — sangue predominante na cisterna inter-hemisférica aponta comunicante anterior, na fissura de Sylvius aponta cerebral média. A escala de Fisher, baseada na quantidade e distribuição do sangue, prediz o risco de vasoespasmo. Uma exceção importante é a hemorragia perimesencefálica pura, restrita às cisternas ao redor do mesencéfalo, geralmente não aneurismática e de prognóstico bem melhor. O segundo achado é o apagamento cisternal: quando as cisternas somem, o espaço de reserva acabou e a herniação transtentorial é iminente — é um sinal que exige ação imediata.',
      alteracoes: [
        { nome: 'Hemorragia subaracnóidea', achado: 'Cisternas preenchidas por material hiperdenso (50–70 UH); a distribuição sugere o aneurisma de origem. Escala de Fisher prediz vasoespasmo.' },
        { nome: 'Apagamento das cisternas', achado: 'Perda dos espaços escuros perimesencefálicos; hipertensão intracraniana grave com herniação iminente.' },
        { nome: 'Hemorragia perimesencefálica não aneurismática', achado: 'Sangue restrito às cisternas ao redor do mesencéfalo, sem extensão às fissuras; angiografia negativa em ~95% e prognóstico favorável.' },
        { nome: 'Meningite / carcinomatose meníngea', achado: 'Realce anormal das cisternas após contraste, com apagamento parcial.' },
        { nome: 'Cisto aracnoide', achado: 'Coleção de densidade liquórica que expande e remodela o osso adjacente; benigno, mas pode causar efeito de massa.' },
      ],
      armadilhas: ['Pseudo-hemorragia subaracnóidea: em edema cerebral difuso grave, o parênquima fica tão hipodenso que os vasos e a dura normais parecem hiperdensos, simulando sangue nas cisternas.'],
    },
    {
      id: 'fissura-de-sylvius-direita',
      nome: 'Fissura de Sylvius direita',
      sinonimos: ['sulco lateral direito', 'fissura lateral direita'],
      categoria: 'liquor',
      resumo: 'Profunda fissura que separa o lobo temporal dos lobos frontal e parietal e aloja a artéria cerebral média.',
      morfologia: 'Fenda profunda que se estende da base do crânio, lateralmente, contendo a artéria cerebral média e seus ramos e, no seu fundo, a ínsula. Divide-se em ramos anterior, ascendente e posterior.',
      funcao: 'Espaço subaracnóideo de passagem para a cerebral média e suas divisões; contém o córtex insular em sua profundidade.',
      densidade: 'Líquor 0–15 UH — deve aparecer como fenda escura e simétrica. Sangue: hiperdenso.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Fenda escura que se dirige lateralmente a partir da região da cisterna supra-selar, com a artéria cerebral média correndo dentro dela.',
      reparos: ['Lobo temporal (abaixo)', 'Lobo frontal e parietal (acima)', 'Ínsula (no fundo)', 'Artéria cerebral média (dentro da fissura)'],
      clinica: 'A fissura de Sylvius é uma estrutura de leitura rica. Sangue dentro dela sugere aneurisma de bifurcação da cerebral média, quando é subaracnóideo, ou contusão temporal, quando é parenquimatoso adjacente. O apagamento assimétrico da fissura é um dos sinais mais precoces de AVC de cerebral média, aparecendo junto com a perda da diferenciação entre a ínsula e a cápsula externa — a chamada "perda da fita insular", que é um dos itens do escore ASPECTS. Já a assimetria de alargamento, com uma fissura muito mais aberta que a outra, pode indicar atrofia focal ou, em criança, cisto aracnoide da fossa média.',
      alteracoes: [
        { nome: 'Perda da fita insular', achado: 'Apagamento da diferenciação entre ínsula e cápsula externa; sinal precoce de infarto de cerebral média e item do ASPECTS.' },
        { nome: 'Hemorragia subaracnóidea silviana', achado: 'Sangue hiperdenso na fissura; sugere aneurisma de bifurcação da cerebral média.' },
        { nome: 'Cisto aracnoide da fossa média', achado: 'Coleção liquórica que alarga a fissura e remodela a asa do esfenoide; o tipo mais comum de cisto aracnoide.' },
        { nome: 'Apagamento por edema', achado: 'Fissura assimetricamente estreitada; efeito de massa ipsilateral.' },
      ],
    },
    {
      id: 'fissura-de-sylvius-esquerda',
      nome: 'Fissura de Sylvius esquerda',
      categoria: 'liquor',
      resumo: 'Contraparte esquerda; a comparação entre as duas é o método.',
      morfologia: 'Idêntica à direita. Uma assimetria fisiológica é conhecida: o plano temporal é habitualmente maior à esquerda, ligado à dominância da linguagem.',
      funcao: 'Passagem da cerebral média esquerda e alojamento da ínsula esquerda.',
      densidade: 'Líquor 0–15 UH.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Fenda escura lateral esquerda; comparar abertura e conteúdo com a direita no mesmo corte.',
      reparos: ['Lobo temporal esquerdo', 'Ínsula esquerda', 'Artéria cerebral média esquerda'],
      clinica: 'A comparação lado a lado das duas fissuras é uma das rotinas mais produtivas da TC de crânio: o apagamento unilateral pode ser o único achado nas primeiras horas de um infarto extenso de cerebral média, num exame que à primeira vista parece normal. Treinar esse olhar comparativo vale mais do que memorizar densidades.',
      alteracoes: [
        { nome: 'Apagamento unilateral precoce', achado: 'Único achado em muitas TCs feitas nas primeiras horas de AVC de cerebral média.' },
        { nome: 'Alargamento por atrofia focal', achado: 'Fissura ampla com sulcos temporais alargados; sequela de infarto antigo ou atrofia lobar.' },
      ],
    },
    {
      id: 'quarto-ventriculo',
      nome: 'Quarto ventrículo',
      categoria: 'liquor',
      resumo: 'Cavidade em forma de tenda entre o tronco encefálico e o cerebelo.',
      morfologia: 'Losango achatado, com assoalho formado pela face posterior da ponte e do bulbo e teto pelo véu medular e pelo cerebelo. Comunica-se acima com o aqueduto de Sylvius e abaixo com o canal central da medula, além de se abrir para as cisternas pelos forames de Luschka (dois laterais) e Magendie (um mediano).',
      funcao: 'Passagem do líquor do sistema ventricular para o espaço subaracnóideo. Seu assoalho contém os núcleos de vários nervos cranianos e a área postrema, o centro do vômito, sem barreira hematoencefálica — o que explica os vômitos da hipertensão intracraniana.',
      densidade: 'Líquor 0–15 UH.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Nos cortes da fossa posterior, é a cavidade escura em forma de tenda ou losango entre a ponte (à frente) e o cerebelo (atrás).',
      reparos: ['Ponte (assoalho anterior)', 'Cerebelo e vermis (teto posterior)', 'Aqueduto de Sylvius (acima)', 'Forames de Luschka e Magendie (saídas)'],
      clinica: 'O quarto ventrículo é uma das estruturas mais sensíveis da TC de crânio, porque qualquer efeito de massa na fossa posterior o comprime e o desloca — e, como ele é a via de saída do líquor, sua compressão produz hidrocefalia obstrutiva aguda. Por isso, num hematoma ou infarto cerebelar, o estado do quarto ventrículo é o que define a urgência cirúrgica, mais do que o tamanho da lesão em si. Do ponto de vista topográfico, o quarto ventrículo também localiza a obstrução: se ele está DILATADO junto com os demais, o obstáculo está nas saídas ou na reabsorção; se está NORMAL enquanto os outros dilatam, o obstáculo está no aqueduto.',
      alteracoes: [
        { nome: 'Compressão por massa de fossa posterior', achado: 'Quarto ventrículo achatado e desviado, com hidrocefalia obstrutiva a montante; define urgência cirúrgica.' },
        { nome: 'Hemorragia intraventricular', achado: 'Sangue hiperdenso preenchendo a cavidade; pode ocluir as saídas e causar hidrocefalia aguda.' },
        { nome: 'Malformação de Dandy-Walker', achado: 'Dilatação cística do quarto ventrículo com agenesia do vermis e fossa posterior aumentada.' },
        { nome: 'Ependimoma / meduloblastoma', achado: 'Massa intraventricular na criança, com hidrocefalia; o ependimoma tende a se insinuar pelos forames ("tumor plástico").' },
      ],
    },
    {
      id: 'aqueduto-de-sylvius',
      nome: 'Aqueduto de Sylvius',
      sinonimos: ['aqueduto cerebral', 'aqueduto mesencefálico'],
      categoria: 'liquor',
      resumo: 'Canal estreito que atravessa o mesencéfalo unindo o terceiro ao quarto ventrículo.',
      morfologia: 'Canal de apenas 1–2 mm de diâmetro e cerca de 15 mm de comprimento, no tegmento mesencefálico, entre os colículos (dorsalmente) e o tegmento (ventralmente). É o ponto mais estreito de todo o sistema ventricular.',
      funcao: 'Passagem obrigatória do líquor produzido nos ventrículos laterais e terceiro rumo ao quarto ventrículo. Seu calibre mínimo o torna o gargalo hidráulico do encéfalo.',
      densidade: 'Líquor 0–15 UH; frequentemente no limite da resolução da TC.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Pequeno ponto escuro na porção posterior do mesencéfalo, no corte em que o mesencéfalo tem forma de coração. É pequeno — procure com atenção.',
      reparos: ['Mesencéfalo (o aqueduto o atravessa)', 'Colículos / lâmina quadrigêmea (dorsalmente)', 'Terceiro ventrículo (acima)', 'Quarto ventrículo (abaixo)'],
      clinica: 'A estenose do aqueduto é a causa mais comum de hidrocefalia obstrutiva congênita, e produz um padrão de imagem inconfundível: ventrículos laterais e terceiro ventrículo dilatados, com quarto ventrículo de tamanho NORMAL. Reconhecer esse padrão localiza a obstrução sem necessidade de mais nada. As causas adquiridas incluem tumores da região pineal e do tegmento, hemorragia com aderências e infecção. O tratamento moderno preferencial é a terceiroventriculostomia endoscópica, que cria uma comunicação entre o terceiro ventrículo e as cisternas, desviando o obstáculo sem implantar válvula — e a TC pré-operatória avalia a anatomia do assoalho do terceiro ventrículo e a distância às artérias basilares.',
      alteracoes: [
        { nome: 'Estenose do aqueduto', achado: 'Ventrículos laterais e terceiro dilatados com quarto ventrículo NORMAL; padrão que localiza a obstrução.' },
        { nome: 'Tumor da região pineal comprimindo o aqueduto', achado: 'Massa pineal com hidrocefalia triventricular; associada à síndrome de Parinaud (paralisia do olhar vertical).' },
        { nome: 'Obstrução por hemorragia intraventricular', achado: 'Sangue no terceiro e quarto ventrículos com hidrocefalia aguda.' },
      ],
    },
    {
      id: 'ventriculo-lateral-direito',
      nome: 'Ventrículo lateral direito',
      categoria: 'liquor',
      resumo: 'Maior cavidade ventricular; tem forma de "C" acompanhando a curvatura do hemisfério.',
      morfologia: 'Composto por corno frontal, corpo, átrio (trígono), corno occipital e corno temporal. Contém o plexo coroide, que produz a maior parte do líquor e frequentemente calcifica no átrio em adultos. Comunica-se com o terceiro ventrículo pelo forame de Monro.',
      funcao: 'Produção e armazenamento de líquor. Seu tamanho é o principal parâmetro de acompanhamento em hidrocefalia e em derivações ventriculoperitoneais.',
      densidade: 'Líquor 0–15 UH; plexo coroide calcificado > 100 UH (achado normal em adultos).',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Cavidades escuras pareadas na profundidade dos hemisférios; nos cortes altos aparecem os corpos, nos médios os cornos frontais e os átrios.',
      reparos: ['Núcleo caudado (parede lateral do corno frontal)', 'Septo pelúcido (medial, entre os dois ventrículos)', 'Tálamo (assoalho do corpo)', 'Forame de Monro (comunicação com o terceiro)'],
      clinica: 'O índice de Evans — maior largura dos cornos frontais dividida pelo maior diâmetro interno do crânio no mesmo corte — é a medida mais usada da neurorradiologia: acima de 0,30 há ventriculomegalia. A distinção clinicamente decisiva é entre hidrocefalia e atrofia: na hidrocefalia, os ventrículos dilatam e os sulcos ficam apagados ou normais, os cornos temporais se dilatam precocemente e há halo de transudato periventricular na forma aguda; na atrofia, ventrículos e sulcos alargam juntos, de forma proporcional. Na hidrocefalia de pressão normal, a tríade clínica de apraxia de marcha, incontinência e demência acompanha ventriculomegalia desproporcional ao grau de atrofia, com sulcos da convexidade alta apertados — um padrão chamado DESH que ajuda a selecionar candidatos à derivação.',
      alteracoes: [
        { nome: 'Hidrocefalia', achado: 'Índice de Evans > 0,30, cornos temporais dilatados, ângulo caloso reduzido e halo de transudato periventricular na forma aguda.' },
        { nome: 'Atrofia (hidrocefalia ex vacuo)', achado: 'Ventrículos e sulcos alargados proporcionalmente; não há transudato nem apagamento de sulcos.' },
        { nome: 'Hemorragia intraventricular', achado: 'Sangue hiperdenso com nível líquido-líquido nas porções dependentes; risco de hidrocefalia por obstrução.' },
        { nome: 'Ventriculite', achado: 'Realce ependimário, debris com nível e hidrocefalia; complicação de derivação e de meningite.' },
        { nome: 'Colpocefalia', achado: 'Dilatação desproporcional dos cornos occipitais; associada a agenesia do corpo caloso.' },
      ],
      armadilhas: ['A calcificação do plexo coroide no átrio é fisiológica em adultos e não deve ser confundida com hemorragia ou tumor.'],
      medidas: [{ rotulo: 'Índice de Evans normal', valor: '< 0,30' }],
    },
    {
      id: 'ventriculo-lateral-esquerdo',
      nome: 'Ventrículo lateral esquerdo',
      categoria: 'liquor',
      resumo: 'Contraparte esquerda; leve assimetria entre os dois é comum e normal.',
      morfologia: 'Idêntica ao direito. Assimetria discreta de tamanho ocorre em cerca de 40% das pessoas sem significado patológico.',
      funcao: 'Produção e circulação de líquor.',
      densidade: 'Líquor 0–15 UH.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Cavidade escura em C no hemisfério esquerdo; comparar com o direito.',
      reparos: ['Caudado esquerdo', 'Septo pelúcido', 'Tálamo esquerdo'],
      clinica: 'Assimetria ventricular é comum e benigna, mas exige uma verificação: assimetria com DESVIO da linha média ou apagamento de sulcos do lado do ventrículo menor indica efeito de massa, não variação anatômica. Já a dilatação isolada de um ventrículo (hidrocefalia unilateral) aponta obstrução do forame de Monro daquele lado — por cisto coloide, tumor ou aderência pós-hemorrágica.',
      alteracoes: [
        { nome: 'Assimetria fisiológica', achado: 'Diferença de tamanho sem desvio de linha média nem apagamento de sulcos; presente em ~40%.' },
        { nome: 'Hidrocefalia unilateral', achado: 'Dilatação de um único ventrículo por obstrução do forame de Monro ipsilateral; procurar cisto coloide ou tumor.' },
        { nome: 'Colapso ventricular por hiperdrenagem', achado: 'Ventrículos em fenda em portador de derivação; síndrome do ventrículo em fenda.' },
      ],
    },
    {
      id: 'terceiro-ventriculo',
      nome: 'Terceiro ventrículo',
      categoria: 'liquor',
      resumo: 'Cavidade mediana estreita entre os dois tálamos, no diencéfalo.',
      morfologia: 'Fenda vertical na linha média, com paredes laterais formadas pelos tálamos e hipotálamo. Comunica-se com os ventrículos laterais pelos dois forames de Monro e com o quarto pelo aqueduto. Apresenta recessos característicos: supra-óptico, infundibular (que aponta para a hipófise) e pineal.',
      funcao: 'Passagem do líquor e relação anatômica íntima com o hipotálamo e a hipófise, o que o torna referência em cirurgia da região selar e do terceiro ventrículo.',
      densidade: 'Líquor 0–15 UH. Largura normal de até 10 mm no adulto, aumentando com a idade.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Fenda escura estreita exatamente na linha média, entre os dois tálamos, no corte dos núcleos da base.',
      reparos: ['Tálamos (paredes laterais)', 'Forames de Monro (comunicação anterior superior)', 'Hipófise e quiasma óptico (abaixo e à frente)', 'Glândula pineal (atrás)'],
      clinica: 'O cisto coloide do terceiro ventrículo é um pequeno tumor benigno com uma característica temível: alojado no teto anterior, junto aos forames de Monro, ele pode obstruí-los de forma intermitente e posicional, causando cefaleia súbita e intensa que muda com a posição da cabeça, e podendo levar a hidrocefalia aguda e morte súbita. Na TC, aparece como um nódulo hiperdenso (em 2/3 dos casos) e bem definido na topografia dos Monro, com dilatação dos ventrículos laterais e terceiro ventrículo poupado. É um dos diagnósticos que mais recompensa quem olha a região com atenção.',
      alteracoes: [
        { nome: 'Cisto coloide', achado: 'Nódulo hiperdenso e bem definido no teto anterior do terceiro ventrículo, obstruindo os forames de Monro; hidrocefalia biventricular com terceiro poupado.' },
        { nome: 'Dilatação em hidrocefalia comunicante', achado: 'Terceiro ventrículo arredondado, com recessos abaulados e assoalho rebaixado.' },
        { nome: 'Sela vazia', achado: 'Herniação do recesso infundibular para dentro da sela turca; associada a hipertensão intracraniana idiopática.' },
        { nome: 'Craniofaringioma', achado: 'Massa supra-selar com calcificações e componente cístico, deslocando ou invadindo o terceiro ventrículo.' },
      ],
      medidas: [{ rotulo: 'Largura normal', valor: '≤ 10 mm' }],
    },
    {
      id: 'sulco-central-direito',
      nome: 'Sulco central direito',
      sinonimos: ['sulco de Rolando direito'],
      categoria: 'liquor',
      resumo: 'Sulco que separa o lobo frontal do parietal e delimita os córtices motor e sensitivo.',
      morfologia: 'Sulco profundo e oblíquo que corre de posteromedial para anterolateral na convexidade. À sua frente está o giro pré-central (motor primário); atrás, o giro pós-central (sensitivo primário). O "sinal do ômega" ou "hand knob" — uma dobra em ômega invertido na parede do giro pré-central — marca a área da mão.',
      funcao: 'Marco anatômico que separa as funções motoras das sensitivas. Sua identificação é essencial no planejamento neurocirúrgico, para preservar o córtex eloquente.',
      densidade: 'Líquor 0–15 UH dentro do sulco.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Nos cortes altos, é o sulco mais proeminente que corre obliquamente na convexidade. O truque prático é achar o "hand knob": a dobra em ômega no giro imediatamente anterior ao sulco central marca a representação da mão.',
      reparos: ['Giro pré-central (à frente — motor)', 'Giro pós-central (atrás — sensitivo)', 'Sulco pré-central e pós-central (paralelos)', 'Hand knob (ômega no pré-central)'],
      clinica: 'Localizar o sulco central é a habilidade que permite dizer se uma lesão está em córtex eloquente — informação que muda a indicação e a técnica cirúrgica, podendo exigir mapeamento intraoperatório com paciente acordado. Também é o que permite prever o déficit: uma lesão logo à frente do sulco causa déficit motor; logo atrás, sensitivo. E o apagamento assimétrico dos sulcos nessa região é frequentemente o primeiro sinal de um infarto de cerebral média em evolução.',
      alteracoes: [
        { nome: 'Lesão em córtex eloquente', achado: 'Massa adjacente ao sulco central; exige mapeamento funcional pré e intraoperatório.' },
        { nome: 'Apagamento sulcal assimétrico', achado: 'Edema por infarto, contusão ou massa; comparar sistematicamente com o lado oposto.' },
        { nome: 'Hemorragia subaracnóidea da convexidade', achado: 'Sangue nos sulcos da convexidade, poupando as cisternas; em idoso, sugere angiopatia amiloide; em jovem, síndrome de vasoconstrição cerebral reversível.' },
      ],
    },
    {
      id: 'sulco-central-esquerdo',
      nome: 'Sulco central esquerdo',
      categoria: 'liquor',
      resumo: 'Contraparte esquerda do sulco de Rolando.',
      morfologia: 'Idêntica ao direito.',
      funcao: 'Divisão entre córtex motor e sensitivo do hemisfério esquerdo.',
      densidade: 'Líquor 0–15 UH.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Mesmo método: procurar o hand knob em ômega no giro pré-central esquerdo.',
      reparos: ['Giro pré-central esquerdo', 'Giro pós-central esquerdo', 'Fissura de Sylvius (inferiormente)'],
      clinica: 'À esquerda, a proximidade entre o córtex motor da face e a área de Broca (imediatamente à frente e abaixo) explica por que lesões nessa região combinam disartria, paresia facial e afasia de expressão. O planejamento cirúrgico ali é particularmente delicado, e a avaliação de dominância hemisférica por ressonância funcional costuma ser exigida.',
      alteracoes: [
        { nome: 'Lesão perirrolândica esquerda', achado: 'Combinação de déficit motor braquiofacial e afasia; região de altíssimo risco cirúrgico.' },
        { nome: 'Alargamento sulcal por atrofia focal', achado: 'Sulcos amplos com perda de volume giral; sequela ou degeneração lobar.' },
      ],
    },
  ],
  quiz: [
    {
      pergunta: 'Ventrículos laterais e terceiro ventrículo dilatados, com quarto ventrículo de tamanho NORMAL, localizam a obstrução em:',
      alternativas: [
        'Forames de Luschka e Magendie',
        'Aqueduto de Sylvius',
        'Granulações aracnoides',
        'Forame de Monro',
      ],
      correta: 1,
      explicacao: 'A dilatação para exatamente antes do obstáculo. Se o quarto ventrículo está normal e tudo acima dele está dilatado, o gargalo é o aqueduto — a causa mais comum de hidrocefalia obstrutiva congênita.',
    },
    {
      pergunta: 'Como diferenciar hidrocefalia de atrofia cerebral na TC?',
      alternativas: [
        'Pelo tamanho absoluto dos ventrículos',
        'Na hidrocefalia os ventrículos dilatam com sulcos apagados ou normais; na atrofia ventrículos e sulcos alargam proporcionalmente',
        'Pela densidade do líquor',
        'Pela idade do paciente apenas',
      ],
      correta: 1,
      explicacao: 'A hidrocefalia é um aumento de pressão que expande os ventrículos e comprime os sulcos; a atrofia é perda de tecido, que alarga tudo de forma proporcional. O halo de transudato periventricular e a dilatação precoce dos cornos temporais reforçam a hidrocefalia.',
    },
    {
      pergunta: 'Um nódulo hiperdenso e bem definido no teto anterior do terceiro ventrículo, com hidrocefalia biventricular, corresponde a:',
      alternativas: ['Craniofaringioma', 'Cisto coloide', 'Ependimoma', 'Cisto aracnoide'],
      correta: 1,
      explicacao: 'O cisto coloide se aloja junto aos forames de Monro e os obstrui de forma intermitente e posicional, dilatando os ventrículos laterais e poupando o terceiro. Apesar de benigno, pode causar hidrocefalia aguda e morte súbita.',
    },
    {
      pergunta: 'O apagamento das cisternas da base significa:',
      alternativas: [
        'Atrofia cerebral avançada',
        'Que o espaço de reserva intracraniano acabou e a herniação é iminente',
        'Hidrocefalia comunicante',
        'Artefato técnico',
      ],
      correta: 1,
      explicacao: 'As cisternas são o volume de reserva do crânio. Enquanto existem, o encéfalo ainda tem para onde se deslocar; quando somem, qualquer aumento adicional de volume força a herniação transtentorial. É um dos achados mais urgentes da TC de crânio.',
    },
    {
      pergunta: 'O índice de Evans é calculado como:',
      alternativas: [
        'Área ventricular dividida pela área craniana',
        'Maior largura dos cornos frontais dividida pelo maior diâmetro biparietal interno; > 0,30 indica ventriculomegalia',
        'Largura do terceiro ventrículo dividida pela do quarto',
        'Volume liquórico total dividido pelo volume craniano',
      ],
      correta: 1,
      explicacao: 'É uma razão simples medida num único corte axial, e por isso amplamente usada. Acima de 0,30 configura ventriculomegalia — mas a distinção entre hidrocefalia e atrofia depende de olhar os sulcos, não só o índice.',
    },
    {
      pergunta: 'Hemorragia subaracnóidea restrita às cisternas perimesencefálicas, sem extensão às fissuras, caracteriza:',
      alternativas: [
        'Ruptura de aneurisma de comunicante anterior',
        'Hemorragia perimesencefálica não aneurismática, com angiografia negativa em ~95% e bom prognóstico',
        'Trauma craniano grave',
        'Malformação arteriovenosa rota',
      ],
      correta: 1,
      explicacao: 'Esse padrão de distribuição, restrito e centrado no mesencéfalo, corresponde a um sangramento provavelmente venoso, com angiografia negativa na grande maioria dos casos e evolução muito mais favorável que a da hemorragia aneurismática.',
    },
  ],
}
