import type { SubsecaoTC } from '../tipos'

export const cranioParenquimaEncefalico: SubsecaoTC = {
  id: 'parenquima-encefalico',
  titulo: 'Parênquima encefálico',
  subtitulo: 'Tronco, cerebelo, lobos, núcleos da base e cápsula interna',
  secaoId: 'cranio',
  pasta: '/TC_CRANIO/TC_CRANIO_PARENQUIMA_ENCEFALICO',
  ext: 'PNG',
  totalCortes: 19,
  orientacao: 'caudo-cranial',
  icone: 'brain',
  cor: 'violeta',
  janelaPadrao: 'cerebral',
  protocolo:
    'TC de crânio SEM contraste, cortes de 5 mm na fossa posterior e supratentorial (ou volumétricos com reconstrução), lida obrigatoriamente em janela cerebral estreita (WW 80 / WL 40) — em janela de partes moles convencional, a diferença de 10 UH entre substância branca e cinzenta simplesmente não é visível. Muitos serviços usam ainda uma janela "de AVC" ainda mais estreita (WW 30–40) para detectar o apagamento precoce da diferenciação corticossubcortical. O contraste só entra quando a suspeita é tumor, abscesso ou doença inflamatória; no AVC agudo, a TC sem contraste é o exame inicial, seguida de angio-TC e perfusão.',
  introducao:
    'A TC de crânio é o exame mais pedido do mundo e, paradoxalmente, um dos mais difíceis de ler bem — porque tudo o que interessa está separado por poucas unidades Hounsfield. A substância cinzenta tem 35–45 UH e a branca 25–35 UH: uma diferença de apenas dez unidades, invisível em qualquer janela larga. Toda a leitura do parênquima depende de aceitar isso e trabalhar em janela estreita. A segunda ideia é a de que a TC de crânio é lida por SIMETRIA: o cérebro é um órgão par, e a comparação sistemática de um lado com o outro detecta lesões que a inspeção isolada perde. A terceira é a das densidades absolutas, que resolvem quase toda a emergência: sangue agudo tem 50–80 UH (branco), isquemia aguda tem densidade reduzida (escuro), edema é escuro, calcificação é muito branca, e ar é preto. Percorrendo esta série de baixo para cima, você atravessa a transição bulbomedular, a ponte e o cerebelo, o mesencéfalo com as cisternas ao redor, depois o nível dos núcleos da base e da cápsula interna — o corte mais importante de toda a TC de crânio — e por fim a convexidade e os ventrículos laterais.',
  roteiro: [
    { passo: '1. Ajuste a janela', detalhe: 'Janela cerebral estreita. Se você consegue ver a diferença entre córtex e substância branca, a janela está certa.' },
    { passo: '2. Comece pela fossa posterior', detalhe: 'Bulbo, ponte, cerebelo e quarto ventrículo. Região de muito artefato de endurecimento do feixe — olhe com atenção redobrada.' },
    { passo: '3. Suba ao mesencéfalo', detalhe: 'Formato de "Mickey Mouse" ou de coração, cercado pelas cisternas peri-mesencefálicas. Cisternas apagadas = herniação.' },
    { passo: '4. Chegue ao corte dos núcleos da base', detalhe: 'Caudado, lentiforme, cápsula interna e tálamo. É o corte mais informativo do exame.' },
    { passo: '5. Compare os dois lados sistematicamente', detalhe: 'Sulcos, cisternas, ventrículos, córtex e núcleos. Assimetria é sempre um achado até prova em contrário.' },
    { passo: '6. Termine na convexidade', detalhe: 'Sulcos corticais e espaços extra-axiais até o vértice — onde hematomas subdurais finos se escondem.' },
  ],
  perolas: [
    'Substância cinzenta 35–45 UH, branca 25–35 UH. Dez unidades de diferença: só a janela estreita mostra.',
    'Sangue agudo: 50–80 UH. Vai perdendo densidade ~1,5 UH/dia e fica isodenso ao parênquima em 1–3 semanas — o subdural subagudo isodenso é o grande armadilha.',
    'Perda da diferenciação corticossubcortical e apagamento dos sulcos são os sinais MAIS PRECOCES de AVC isquêmico na TC.',
    'ASPECTS: escore de 10 pontos no território da cerebral média, subtraindo 1 por região comprometida. Guia a decisão de trombectomia.',
    'Hemorragia hipertensiva tem endereço: putame (mais comum), tálamo, ponte e cerebelo. Hemorragia lobar em idoso sugere angiopatia amiloide.',
    'Cerebelo e tronco sofrem com artefato de endurecimento do feixe entre os rochedos — lesões pequenas na ponte passam despercebidas na TC; a ressonância é o exame.',
  ],
  estruturas: [
    {
      id: 'medula-espinhal',
      nome: 'Medula espinhal',
      categoria: 'nervoso',
      resumo: 'Porção do sistema nervoso central que se continua com o bulbo através do forame magno.',
      morfologia: 'No nível do forame magno, a medula cervical alta aparece como estrutura oval de partes moles no centro do canal, cercada por líquor. Tem cerca de 1 cm de diâmetro nesse nível.',
      funcao: 'Condução das vias motoras descendentes (corticoespinhal) e sensitivas ascendentes (cordão posterior, espinotalâmico), além dos circuitos reflexos segmentares. A junção bulbomedular concentra vias vitais — a lesão aqui é imediatamente fatal por parada respiratória.',
      densidade: 'Partes moles, 30–40 UH, cercada por líquor (0–15 UH). A TC mostra mal o parênquima medular; a ressonância é o exame de escolha.',
      janela: 'Cerebral estreita; janela óssea para o canal.',
      comoIdentificar: 'Nos primeiros cortes da série (os mais baixos), é a estrutura oval central dentro do anel ósseo do forame magno e do canal cervical.',
      reparos: ['Forame magno (ao redor)', 'Côndilos occipitais (laterais)', 'Clivo (anterior)', 'Cisterna magna (posterior)'],
      clinica: 'A TC avalia mal a medula, mas avalia muito bem o continente: no trauma cervical, ela mostra fraturas, luxações e fragmentos no canal — e é o estreitamento do canal que produz a lesão medular. A malformação de Chiari tipo I, com tonsilas cerebelares descendo pelo forame magno, também comprime a junção bulbomedular e é reconhecível na TC, embora a ressonância a defina melhor.',
      alteracoes: [
        { nome: 'Compressão por fragmento ósseo', achado: 'Estreitamento do canal por fragmento retropulsado; a TC define a geometria, a ressonância define o dano medular.' },
        { nome: 'Malformação de Chiari I', achado: 'Tonsilas cerebelares abaixo do forame magno, apinhamento da junção bulbomedular; pode associar-se a siringomielia.' },
        { nome: 'Hematoma epidural espinhal', achado: 'Coleção hiperdensa no canal comprimindo a medula; emergência neurocirúrgica.' },
      ],
    },
    {
      id: 'bulbo',
      nome: 'Bulbo',
      sinonimos: ['medula oblonga', 'bulbo raquidiano'],
      categoria: 'nervoso',
      resumo: 'Porção mais inferior do tronco encefálico, entre a medula e a ponte; abriga os centros vitais.',
      morfologia: 'Cone truncado à frente do cerebelo e atrás do clivo. Contém as pirâmides bulbares anteriormente (onde ocorre a decussação das vias corticoespinhais), as olivas lateralmente e os núcleos dos nervos cranianos IX a XII.',
      funcao: 'Centros respiratório e vasomotor — as funções que definem a vida. Também sedia os reflexos de tosse, vômito, deglutição e o barorreflexo. A decussação das pirâmides, em sua porção inferior, é a razão anatômica de o hemisfério esquerdo comandar o lado direito do corpo.',
      densidade: '30–40 UH, homogêneo. Muito sujeito a artefato de endurecimento do feixe pelos rochedos.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Estrutura de partes moles à frente do cerebelo e atrás do clivo, nos cortes baixos da fossa posterior. Cercada pela cisterna pré-bulbar.',
      reparos: ['Clivo (anterior)', 'Cerebelo (posterior)', 'Quarto ventrículo (posterior, mais acima)', 'Forame magno (abaixo)'],
      clinica: 'A síndrome de Wallenberg (bulbar lateral), por oclusão da artéria cerebelar posteroinferior ou da vertebral, produz um dos quadros mais reconhecíveis da neurologia: dor e perda térmica na hemiface ipsilateral e no hemicorpo contralateral, ataxia, síndrome de Horner, disfagia e rouquidão. A TC frequentemente é normal nesse cenário — o artefato de fossa posterior mascara o infarto —, e a ressonância com difusão é obrigatória quando a suspeita clínica existe. Esse descompasso entre a clínica eloquente e a TC normal é uma das lições mais importantes desta região.',
      alteracoes: [
        { nome: 'Infarto bulbar lateral (Wallenberg)', achado: 'TC frequentemente normal; a ressonância com difusão mostra a lesão. Não descartar AVC de fossa posterior por TC normal.' },
        { nome: 'Hemorragia bulbar', achado: 'Foco hiperdenso; rara e geralmente catastrófica.' },
        { nome: 'Compressão por lesão do forame magno', achado: 'Meningioma ou cordoma clival deslocando o bulbo.' },
      ],
      armadilhas: ['TC normal NÃO exclui AVC de fossa posterior — a sensibilidade da TC ali é baixíssima nas primeiras horas.'],
    },
    {
      id: 'ponte',
      nome: 'Ponte',
      categoria: 'nervoso',
      resumo: 'Porção média e mais volumosa do tronco encefálico, entre bulbo e mesencéfalo.',
      morfologia: 'Protuberância arredondada anterior, ligada ao cerebelo pelos pedúnculos cerebelares médios. Contém núcleos pontinos, fibras corticoespinhais descendentes e os núcleos dos nervos cranianos V a VIII. Sua face posterior forma o assoalho do quarto ventrículo.',
      funcao: 'Relé entre córtex cerebral e cerebelo (via núcleos pontinos e pedúnculos), controle respiratório fino (centros pneumotáxico e apnêustico), e sede dos núcleos do trigêmeo, abducente, facial e vestibulococlear.',
      densidade: '30–40 UH; região de máximo artefato de endurecimento do feixe entre os dois rochedos.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'É a estrutura mais volumosa e arredondada da fossa posterior anterior, à frente do quarto ventrículo e atrás do clivo. Vista nos cortes médios da série.',
      reparos: ['Clivo (anterior)', 'Quarto ventrículo (posterior)', 'Pedúnculos cerebelares médios (laterais)', 'Cisterna pré-pontina (anterior)', 'Ângulo pontocerebelar (lateral)'],
      clinica: 'A hemorragia pontina hipertensiva é uma das formas mais graves de AVC hemorrágico: produz coma súbito, pupilas puntiformes reativas, tetraplegia e postura de descerebração, com prognóstico sombrio. Já a oclusão da artéria basilar pode produzir a síndrome do encarceramento (locked-in), em que o paciente está consciente mas só consegue mover os olhos verticalmente — um quadro que se confunde com coma se o examinador não testar o olhar vertical. O ângulo pontocerebelar, na face lateral da ponte, é o local do schwannoma vestibular, tumor mais comum da região.',
      alteracoes: [
        { nome: 'Hemorragia pontina', achado: 'Foco hiperdenso central na ponte; hipertensiva na maioria dos casos, com prognóstico grave.' },
        { nome: 'Infarto pontino', achado: 'Frequentemente invisível na TC por artefato; a ressonância com difusão é necessária.' },
        { nome: 'Schwannoma vestibular', achado: 'Massa no ângulo pontocerebelar alargando o conduto auditivo interno; a TC mostra o alargamento ósseo, a ressonância mostra o tumor.' },
        { nome: 'Mielinólise pontina central', achado: 'Área hipodensa central na ponte, poupando a periferia; complicação da correção rápida de hiponatremia.' },
      ],
    },
    {
      id: 'mesencefalo',
      nome: 'Mesencéfalo',
      categoria: 'nervoso',
      resumo: 'Porção mais alta do tronco encefálico; conecta a ponte ao diencéfalo e contém o aqueduto de Sylvius.',
      morfologia: 'Formato característico em coração ou "Mickey Mouse" no corte axial, com os pedúnculos cerebrais anteriormente (as "orelhas"), o tegmento no meio e a lâmina quadrigêmea (colículos superiores e inferiores) posteriormente. O aqueduto de Sylvius o atravessa. É circundado pelas cisternas perimesencefálicas.',
      funcao: 'Conduz as vias motoras descendentes pelos pedúnculos; abriga os núcleos do oculomotor (III) e do troclear (IV), a substância negra (dopaminérgica, degenerada no Parkinson) e os colículos, centros reflexos visuais e auditivos.',
      densidade: '30–40 UH; a substância negra pode aparecer discretamente mais densa.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Procure o corte em que a estrutura central tem forma de coração ou de Mickey Mouse, cercada por cisternas líquóricas escuras. Esse é o corte mesencefálico — um dos marcos da TC de crânio.',
      reparos: ['Cisternas perimesencefálicas (ao redor)', 'Aqueduto de Sylvius (central, posterior)', 'Lobos temporais (laterais, através da incisura tentorial)', 'Tálamos (acima)'],
      clinica: 'As cisternas perimesencefálicas são o marcador mais importante de hipertensão intracraniana na TC: seu apagamento indica herniação transtentorial iminente. Na herniação uncal, o úncus do lobo temporal se insinua pela incisura e comprime o mesencéfalo lateralmente, produzindo midríase ipsilateral (compressão do III nervo) e hemiparesia contralateral — ou, quando o pedúnculo contralateral é comprimido contra a borda tentorial, hemiparesia IPSILATERAL, o falso sinal localizatório de Kernohan. Reconhecer o apagamento cisternal é uma das leituras que salvam vidas.',
      alteracoes: [
        { nome: 'Apagamento das cisternas perimesencefálicas', achado: 'Sinal de hipertensão intracraniana grave e herniação iminente; exige ação imediata.' },
        { nome: 'Herniação uncal', achado: 'Úncus temporal deslocado medialmente comprimindo o mesencéfalo; cisterna ambiens apagada assimetricamente.' },
        { nome: 'Hemorragia de Duret', achado: 'Foco hemorrágico no tronco por herniação descendente com estiramento das perfurantes; sinal de irreversibilidade.' },
        { nome: 'Hidrocefalia obstrutiva por estenose do aqueduto', achado: 'Dilatação dos ventrículos laterais e terceiro, com quarto ventrículo normal.' },
      ],
    },
    {
      id: 'tonsila-cerebelar-direita',
      nome: 'Tonsila cerebelar direita',
      categoria: 'nervoso',
      resumo: 'Lóbulo cerebelar mais inferior e medial, adjacente ao forame magno.',
      morfologia: 'Pequena estrutura arredondada na face inferomedial de cada hemisfério cerebelar, situada logo acima do forame magno, ao lado da medula oblonga.',
      funcao: 'Parte do vestibulocerebelo/espinocerebelo, envolvida em coordenação axial e equilíbrio. Sua importância clínica, porém, é sobretudo topográfica: é a estrutura que hernia pelo forame magno.',
      densidade: '30–40 UH.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Nos cortes mais baixos da fossa posterior, são as duas estruturas arredondadas de cada lado da medula, imediatamente acima ou ao nível do forame magno.',
      reparos: ['Forame magno (abaixo)', 'Bulbo (medialmente)', 'Cisterna magna (posterior)'],
      clinica: 'A herniação tonsilar (cone de pressão) é a via final comum da hipertensão intracraniana: as tonsilas descem pelo forame magno e comprimem o bulbo, causando parada respiratória e morte. Na TC, o achado é o apagamento da cisterna magna e o "apinhamento" da junção bulbomedular. É por isso que a punção lombar é contraindicada sem imagem prévia em pacientes com sinais de hipertensão intracraniana: retirar líquor abaixo cria um gradiente que precipita a herniação.',
      alteracoes: [
        { nome: 'Herniação tonsilar', achado: 'Tonsilas abaixo do forame magno com apagamento da cisterna magna; compressão bulbar — emergência.' },
        { nome: 'Malformação de Chiari I', achado: 'Descida tonsilar > 5 mm de forma crônica, com tonsilas afiladas em "cunha"; pode ser assintomática ou causar cefaleia tussígena e siringomielia.' },
      ],
    },
    {
      id: 'tonsila-cerebelar-esquerda',
      nome: 'Tonsila cerebelar esquerda',
      categoria: 'nervoso',
      resumo: 'Contraparte esquerda; a simetria entre as duas é o que se avalia.',
      morfologia: 'Idêntica à direita.',
      funcao: 'Coordenação axial e equilíbrio.',
      densidade: '30–40 UH.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Espelho da direita, ao lado esquerdo do bulbo.',
      reparos: ['Forame magno', 'Bulbo', 'Cisterna magna'],
      clinica: 'A assimetria de descida tonsilar sugere efeito de massa unilateral na fossa posterior. Como o compartimento infratentorial é pequeno e rígido, lesões pequenas ali descompensam rapidamente — um hematoma cerebelar de 3 cm já pode ser cirúrgico, enquanto o mesmo volume supratentorial seria observado.',
      alteracoes: [
        { nome: 'Descida assimétrica', achado: 'Efeito de massa unilateral na fossa posterior; procurar hematoma, infarto edemaciado ou tumor.' },
      ],
    },
    {
      id: 'hemisferio-cerebelar-direito',
      nome: 'Hemisfério cerebelar direito',
      categoria: 'nervoso',
      resumo: 'Metade direita do cerebelo, na fossa posterior, abaixo do tentório.',
      morfologia: 'Superfície com folhas cerebelares finas e paralelas; substância branca central ramificada (árvore da vida) e núcleos profundos, dos quais o denteado é o maior. Conecta-se ao tronco pelos três pares de pedúnculos cerebelares.',
      funcao: 'Coordenação motora, planejamento e ajuste fino do movimento, tônus e equilíbrio. Regra fundamental: o cerebelo controla o lado IPSILATERAL do corpo — porque suas vias cruzam duas vezes. Lesão cerebelar direita causa ataxia à direita.',
      densidade: '30–40 UH; frequentemente degradado por artefato entre os rochedos.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Grande massa de parênquima na fossa posterior, atrás e lateralmente à ponte, abaixo do tentório.',
      reparos: ['Tentório (acima)', 'Osso occipital (posterior)', 'Quarto ventrículo (medial)', 'Rochedos temporais (anterolaterais)'],
      clinica: 'O infarto e o hematoma cerebelares são emergências de comportamento peculiar: o edema em um compartimento pequeno e rígido comprime o quarto ventrículo, causa hidrocefalia obstrutiva aguda e herniação tonsilar. Um paciente pode estar lúcido e deteriorar em horas. Por isso, hematoma cerebelar maior que 3 cm ou com compressão do quarto ventrículo tem indicação cirúrgica precoce, mesmo em paciente ainda consciente — critério bem mais agressivo do que o usado no compartimento supratentorial.',
      alteracoes: [
        { nome: 'Hematoma cerebelar', achado: 'Foco hiperdenso com compressão do quarto ventrículo e hidrocefalia; > 3 cm indica cirurgia.' },
        { nome: 'Infarto cerebelar', achado: 'Área hipodensa em território vascular (PICA, AICA ou SCA); o edema tardio (24–72 h) é o que ameaça a vida.' },
        { nome: 'Metástase cerebelar', achado: 'Lesão com edema desproporcional e realce em anel; o cerebelo é sítio comum de metástase no adulto.' },
        { nome: 'Meduloblastoma / astrocitoma pilocítico', achado: 'Tumores de fossa posterior da infância, geralmente na linha média (vermis) ou hemisféricos com componente cístico.' },
      ],
      armadilhas: ['O artefato de endurecimento do feixe entre os rochedos cria faixas hipodensas que imitam infarto — compare os dois lados e desconfie de "lesões" simétricas ou lineares.'],
    },
    {
      id: 'hemisferio-cerebelar-esquerdo',
      nome: 'Hemisfério cerebelar esquerdo',
      categoria: 'nervoso',
      resumo: 'Contraparte esquerda do cerebelo.',
      morfologia: 'Idêntica ao direito.',
      funcao: 'Coordenação ipsilateral (esquerda).',
      densidade: '30–40 UH.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Espelho do direito; comparar densidade, volume e simetria dos sulcos cerebelares.',
      reparos: ['Tentório', 'Quarto ventrículo', 'Osso occipital'],
      clinica: 'Como o cerebelo é ipsilateral, um paciente com ataxia de membro esquerdo e dismetria à esquerda tem lesão cerebelar ESQUERDA — o oposto da lógica hemisférica cerebral. Confundir isso é um erro clássico de raciocínio topográfico.',
      alteracoes: [
        { nome: 'Infarto de território da SCA/PICA', achado: 'Hipodensidade delimitada por território vascular; correlacionar com ataxia ipsilateral.' },
        { nome: 'Atrofia cerebelar', achado: 'Sulcos cerebelares alargados; alcoolismo crônico, degenerações espinocerebelares e uso de fenitoína.' },
      ],
    },
    {
      id: 'lobo-frontal-direito',
      nome: 'Lobo frontal direito',
      categoria: 'nervoso',
      resumo: 'Maior lobo cerebral; sede do planejamento, do comportamento e do córtex motor primário.',
      morfologia: 'Ocupa a porção anterior do hemisfério, limitado atrás pelo sulco central e abaixo pelo sulco lateral (de Sylvius). Contém o giro pré-central (córtex motor primário), as áreas pré-motora e motora suplementar, e o córtex pré-frontal.',
      funcao: 'Função executiva, planejamento, inibição comportamental, memória de trabalho e controle motor voluntário do hemicorpo contralateral. À direita, participa da atenção espacial e do processamento da prosódia emocional.',
      densidade: 'Córtex 35–45 UH, substância branca 25–35 UH.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Porção anterior do hemisfério direito, à frente do sulco central. Nos cortes altos, é tudo o que está à frente da linha do sulco central.',
      reparos: ['Sulco central (limite posterior)', 'Fissura de Sylvius (limite inferior)', 'Foice do cérebro (medial)', 'Osso frontal e seio frontal (anteriores)'],
      clinica: 'A base do lobo frontal apoia-se sobre o teto orbitário, que é irregular — e é por isso que o lobo frontal é, junto com o temporal, o principal sítio de contusão cerebral no trauma, especialmente no mecanismo de golpe e contragolpe. Já os infartos de artéria cerebral anterior atingem a face medial do lobo frontal e produzem paresia predominante do membro INFERIOR contralateral, além de abulia e incontinência — um padrão bem diferente do infarto de cerebral média.',
      alteracoes: [
        { nome: 'Contusão frontal', achado: 'Focos hiperdensos puntiformes com edema ao redor na base frontal, tipicamente bilaterais no trauma; podem crescer nas primeiras 24 h.' },
        { nome: 'Infarto de cerebral anterior', achado: 'Hipodensidade na face medial frontal, com paresia crural contralateral.' },
        { nome: 'Meningioma da foice', achado: 'Massa extra-axial de base dural, hiperdensa espontaneamente, com realce homogêneo intenso e possível hiperostose adjacente.' },
        { nome: 'Glioblastoma', achado: 'Massa infiltrativa com necrose central, realce irregular em anel e edema vasogênico extenso.' },
      ],
    },
    {
      id: 'lobo-frontal-esquerdo',
      nome: 'Lobo frontal esquerdo',
      categoria: 'nervoso',
      resumo: 'Lobo frontal do hemisfério dominante na maioria das pessoas; contém a área de Broca.',
      morfologia: 'Idêntica ao direito, com a peculiaridade de conter, na porção inferior (giro frontal inferior, áreas 44 e 45), a área de Broca.',
      funcao: 'Além das funções frontais gerais, produção da linguagem. Lesão da área de Broca causa afasia de expressão: fala não fluente, com esforço, mas compreensão preservada — e o paciente tem consciência do próprio déficit, o que gera frustração intensa.',
      densidade: 'Igual ao direito.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Porção anterior do hemisfério esquerdo. A área de Broca fica na porção inferior, junto à fissura de Sylvius.',
      reparos: ['Fissura de Sylvius (a área de Broca fica em sua margem superior anterior)', 'Sulco central', 'Foice do cérebro'],
      clinica: 'A lateralização da linguagem no hemisfério esquerdo em 95% dos destros e em cerca de 70% dos canhotos é uma das assimetrias funcionais mais importantes do cérebro. Um infarto de ramo superior da cerebral média esquerda produz afasia de Broca com hemiparesia braquiofacial direita; um infarto do ramo inferior produz afasia de Wernicke sem hemiparesia significativa. Reconhecer o território na TC permite prever e explicar o déficit.',
      alteracoes: [
        { nome: 'Infarto do ramo superior da cerebral média esquerda', achado: 'Hipodensidade frontal opercular com afasia de Broca e hemiparesia braquiofacial direita.' },
        { nome: 'Contusão frontal esquerda', achado: 'Focos hemorrágicos na base frontal com edema; pode causar alteração de comportamento tardia.' },
      ],
    },
    {
      id: 'lobo-temporal-direito',
      nome: 'Lobo temporal direito',
      categoria: 'nervoso',
      resumo: 'Lobo inferior e lateral, abaixo da fissura de Sylvius; contém o hipocampo e o córtex auditivo.',
      morfologia: 'Separado do frontal e do parietal pela fissura de Sylvius. Sua face medial contém o úncus, a amígdala e o hipocampo, alojados no compartimento medial junto à incisura tentorial. O corno temporal do ventrículo lateral o percorre.',
      funcao: 'Audição (giro temporal transverso de Heschl), memória declarativa (hipocampo), processamento emocional (amígdala) e reconhecimento visual complexo. À direita, participa do processamento de música, de faces e da memória não verbal.',
      densidade: 'Córtex 35–45 UH; substância branca 25–35 UH.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Lobo situado abaixo da fissura de Sylvius, lateralmente ao mesencéfalo, apoiado no assoalho da fossa média.',
      reparos: ['Fissura de Sylvius (acima)', 'Osso temporal e asa do esfenoide (lateral e anterior)', 'Úncus e mesencéfalo (medial)', 'Corno temporal do ventrículo lateral (interno)'],
      clinica: 'O lobo temporal é, com o frontal, o principal sítio de contusão traumática, por atritar contra a asa maior do esfenoide e o rochedo. Sua porção medial é a que hernia pela incisura tentorial — a herniação uncal —, comprimindo o III nervo e o mesencéfalo. E a encefalite herpética tem predileção quase específica pelos lobos temporais mediais e pelo sistema límbico, aparecendo como hipodensidade e edema temporomedial, muitas vezes assimétrica e com hemorragia — um diagnóstico que exige aciclovir imediato.',
      alteracoes: [
        { nome: 'Contusão temporal', achado: 'Focos hemorrágicos com edema no polo temporal; risco de crescimento e de herniação.' },
        { nome: 'Herniação uncal', achado: 'Úncus deslocado medialmente com apagamento da cisterna ambiens; midríase ipsilateral.' },
        { nome: 'Encefalite herpética', achado: 'Hipodensidade e edema temporomedial e insular, frequentemente assimétricos, poupando os núcleos da base — emergência infecciosa.' },
        { nome: 'Esclerose mesial temporal', achado: 'Atrofia hipocampal; a TC é insensível, o exame é a ressonância. Causa mais comum de epilepsia refratária do adulto.' },
      ],
    },
    {
      id: 'lobo-temporal-esquerdo',
      nome: 'Lobo temporal esquerdo',
      categoria: 'nervoso',
      resumo: 'Contém a área de Wernicke no hemisfério dominante.',
      morfologia: 'Idêntica ao direito; a área de Wernicke ocupa a porção posterior do giro temporal superior (área 22).',
      funcao: 'Compreensão da linguagem. Lesão da área de Wernicke produz afasia de compreensão: fala fluente porém sem sentido (jargonofasia), com compreensão gravemente comprometida — e o paciente não percebe o próprio déficit (anosognosia), o que frequentemente leva à confusão com quadro psiquiátrico.',
      densidade: 'Igual ao direito.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Lobo temporal esquerdo; a área de Wernicke fica em sua porção posterossuperior, junto ao final da fissura de Sylvius.',
      reparos: ['Fissura de Sylvius', 'Lobo parietal (acima e atrás)', 'Corno temporal esquerdo'],
      clinica: 'A afasia de Wernicke é um dos quadros mais mal interpretados da emergência: o paciente fala muito, de forma fluente e incompreensível, não obedece comandos e parece agitado — e é frequentemente rotulado como "confuso" ou "psiquiátrico". Reconhecer que se trata de um AVC de ramo inferior da cerebral média esquerda muda completamente a conduta e o tempo de resposta.',
      alteracoes: [
        { nome: 'Infarto do ramo inferior da cerebral média esquerda', achado: 'Hipodensidade temporal posterior com afasia de Wernicke, sem hemiparesia proeminente.' },
        { nome: 'Encefalite herpética', achado: 'Acometimento temporomedial esquerdo com afasia e crises convulsivas.' },
      ],
    },
    {
      id: 'lobo-parietal-direito',
      nome: 'Lobo parietal direito',
      categoria: 'nervoso',
      resumo: 'Lobo entre o sulco central e o occipital; sede do córtex somatossensorial e da integração espacial.',
      morfologia: 'Limitado à frente pelo sulco central, abaixo pela fissura de Sylvius e atrás pelo sulco parietoccipital. Contém o giro pós-central (córtex somatossensorial primário) e os lóbulos parietais superior e inferior.',
      funcao: 'Processamento somatossensorial contralateral, integração multissensorial e representação espacial. O parietal DIREITO é dominante para atenção espacial — o que explica a heminegligência.',
      densidade: 'Córtex 35–45 UH.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Nos cortes altos, é a região entre o sulco central (à frente) e o sulco parietoccipital (atrás).',
      reparos: ['Sulco central (anterior)', 'Sulco parietoccipital (posterior)', 'Fissura de Sylvius (inferior)', 'Osso parietal'],
      clinica: 'A lesão do parietal direito produz a síndrome de heminegligência: o paciente ignora todo o hemiespaço esquerdo — não come a metade esquerda do prato, não se barbeia do lado esquerdo, não reconhece o próprio braço esquerdo (assomatognosia). Como o parietal esquerdo não é dominante para atenção espacial, lesões dele raramente causam negligência à direita. Essa assimetria funcional é uma das mais elegantes demonstrações de que os hemisférios não são espelhos.',
      alteracoes: [
        { nome: 'Infarto parietal direito', achado: 'Hipodensidade com perda da diferenciação corticossubcortical; heminegligência esquerda e anosognosia.' },
        { nome: 'Hematoma subdural sobre a convexidade', achado: 'Coleção em crescente que cruza suturas; nos cortes altos pode ser fina e passar despercebida.' },
      ],
    },
    {
      id: 'lobo-parietal-esquerdo',
      nome: 'Lobo parietal esquerdo',
      categoria: 'nervoso',
      resumo: 'Lobo parietal dominante; envolvido em cálculo, leitura e praxia.',
      morfologia: 'Idêntica ao direito, com o giro angular e o supramarginal na porção inferior.',
      funcao: 'Somatossensorial contralateral, além de funções simbólicas: cálculo, leitura, escrita e praxia. Lesão do giro angular esquerdo produz a síndrome de Gerstmann — agrafia, acalculia, agnosia digital e desorientação direita-esquerda.',
      densidade: 'Igual ao direito.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Região homóloga no hemisfério esquerdo.',
      reparos: ['Sulco central', 'Giro angular e supramarginal (porção inferior)'],
      clinica: 'A síndrome de Gerstmann é um dos poucos conjuntos de sinais que localizam uma lesão com precisão quase cirúrgica — o giro angular esquerdo. Sua presença numa TC com hipodensidade parietal esquerda fecha a correlação anatomoclínica de forma exemplar.',
      alteracoes: [
        { nome: 'Infarto do giro angular esquerdo', achado: 'Hipodensidade parietal inferior com síndrome de Gerstmann.' },
        { nome: 'Metástase parietal', achado: 'Lesão com realce em anel e edema desproporcional na junção corticossubcortical, sítio preferencial das metástases.' },
      ],
    },
    {
      id: 'lobo-occipital-direito',
      nome: 'Lobo occipital direito',
      categoria: 'nervoso',
      resumo: 'Lobo posterior do cérebro; contém o córtex visual primário.',
      morfologia: 'Situa-se atrás do sulco parietoccipital, acima do tentório. Sua face medial abriga o sulco calcarino, ao redor do qual está o córtex visual primário (área 17). Irrigado pela artéria cerebral posterior.',
      funcao: 'Processamento visual primário do campo visual CONTRALATERAL. As fibras da metade inferior da retina projetam-se abaixo do sulco calcarino e vice-versa, o que produz déficits em quadrantes quando a lesão é parcial.',
      densidade: 'Córtex 35–45 UH.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Porção mais posterior do hemisfério, atrás do sulco parietoccipital, acima do tentório.',
      reparos: ['Sulco parietoccipital (anterior)', 'Tentório (inferior)', 'Foice do cérebro (medial)', 'Osso occipital (posterior)'],
      clinica: 'O infarto occipital por oclusão da cerebral posterior produz hemianopsia homônima contralateral com "poupança macular" — a mácula tem irrigação dupla, da cerebral posterior e da média. A síndrome de encefalopatia posterior reversível (PRES), por sua vez, produz edema vasogênico bilateral e predominantemente posterior, associada a hipertensão grave, pré-eclâmpsia e imunossupressores — e, apesar do nome, nem sempre é reversível se não tratada.',
      alteracoes: [
        { nome: 'Infarto de cerebral posterior', achado: 'Hipodensidade occipital com hemianopsia homônima contralateral e poupança macular.' },
        { nome: 'PRES', achado: 'Edema vasogênico bilateral e simétrico na substância branca occipital e parietal posterior; associado a hipertensão grave e imunossupressores.' },
        { nome: 'Trombose de seio sagital com infarto venoso', achado: 'Áreas hipodensas que não respeitam territórios arteriais, frequentemente com hemorragia.' },
      ],
    },
    {
      id: 'lobo-occipital-esquerdo',
      nome: 'Lobo occipital esquerdo',
      categoria: 'nervoso',
      resumo: 'Contraparte esquerda do córtex visual.',
      morfologia: 'Idêntica ao direito.',
      funcao: 'Processamento visual do campo visual direito.',
      densidade: 'Igual ao direito.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Região posterior do hemisfério esquerdo.',
      reparos: ['Sulco parietoccipital', 'Esplênio do corpo caloso (medial e anterior)'],
      clinica: 'A alexia sem agrafia é uma das síndromes de desconexão mais fascinantes da neurologia: uma lesão do occipital ESQUERDO somada ao esplênio do corpo caloso deixa o paciente capaz de escrever mas incapaz de ler o que escreveu — porque a informação visual, agora processada apenas à direita, não consegue alcançar as áreas de linguagem à esquerda.',
      alteracoes: [
        { nome: 'Alexia sem agrafia', achado: 'Infarto occipital esquerdo com envolvimento do esplênio do corpo caloso; território da cerebral posterior esquerda.' },
        { nome: 'Cegueira cortical (síndrome de Anton)', achado: 'Infarto occipital bilateral; o paciente não enxerga mas nega a cegueira.' },
      ],
    },
    {
      id: 'nucleo-caudado-direito',
      nome: 'Núcleo caudado direito',
      categoria: 'nervoso',
      resumo: 'Núcleo da base em forma de "C" que acompanha o ventrículo lateral; sua cabeça faz saliência no corno frontal.',
      morfologia: 'Composto por cabeça, corpo e cauda, curvando-se ao redor do tálamo acompanhando o ventrículo lateral. A cabeça abaula a parede lateral do corno frontal — é ali que ele é visto na TC axial.',
      funcao: 'Componente do estriado, integra os circuitos de gânglios da base ligados a comportamento, cognição e controle do movimento. Sua degeneração seletiva é a lesão da doença de Huntington.',
      densidade: 'Substância cinzenta, 35–45 UH — discretamente mais denso que a substância branca vizinha. Pode calcificar fisiologicamente em idosos.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'No corte dos núcleos da base, é a estrutura levemente mais densa que faz saliência na parede LATERAL do corno frontal do ventrículo lateral.',
      reparos: ['Corno frontal do ventrículo lateral (medialmente)', 'Braço anterior da cápsula interna (lateralmente)', 'Núcleo lentiforme (lateral, além da cápsula)'],
      clinica: 'A atrofia da cabeça do caudado, com alargamento dos cornos frontais que ganham aspecto "em caixa", é o achado de imagem clássico da doença de Huntington. O caudado também é território das artérias lentículo-estriadas, sendo sede de infartos lacunares e de hemorragias hipertensivas. Calcificações dos núcleos da base são achado comum em idosos e geralmente fisiológicas — mas quando extensas e em paciente jovem, sugerem doença de Fahr, hipoparatireoidismo ou infecções congênitas.',
      alteracoes: [
        { nome: 'Atrofia na doença de Huntington', achado: 'Perda da convexidade da cabeça do caudado, com cornos frontais alargados em "caixa".' },
        { nome: 'Infarto lacunar', achado: 'Pequena área hipodensa < 15 mm; território das lentículo-estriadas.' },
        { nome: 'Calcificação dos núcleos da base', achado: 'Focos hiperdensos simétricos; fisiológica em idosos, patológica quando extensa em jovem (Fahr, hipoparatireoidismo).' },
      ],
    },
    {
      id: 'nucleo-caudado-esquerdo',
      nome: 'Núcleo caudado esquerdo',
      categoria: 'nervoso',
      resumo: 'Contraparte esquerda do caudado.',
      morfologia: 'Idêntica ao direito.',
      funcao: 'Circuitos de gânglios da base.',
      densidade: '35–45 UH.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Espelho do direito, no corno frontal esquerdo.',
      reparos: ['Corno frontal esquerdo', 'Cápsula interna esquerda'],
      clinica: 'A comparação de densidade e volume entre os dois caudados é parte do escore ASPECTS, usado para quantificar a extensão do infarto de cerebral média e decidir sobre trombectomia. Cada região comprometida subtrai um ponto de dez.',
      alteracoes: [
        { nome: 'Hipodensidade precoce no ASPECTS', achado: 'Perda de definição do caudado esquerdo em AVC de cerebral média; subtrai 1 ponto do escore.' },
      ],
    },
    {
      id: 'nucleo-lentiforme-direito',
      nome: 'Núcleo lentiforme direito',
      categoria: 'nervoso',
      resumo: 'Conjunto do putame e do globo pálido, lateral à cápsula interna.',
      morfologia: 'Formato de lente ou cunha em corte axial, com o putame lateral (mais escuro) e o globo pálido medial (frequentemente calcificado em idosos). Situa-se entre a cápsula interna (medialmente) e a cápsula externa (lateralmente).',
      funcao: 'Núcleo motor dos gânglios da base: o putame integra o circuito motor e o globo pálido é a via de saída para o tálamo. Disfunções produzem distúrbios do movimento — parkinsonismo, distonia, coreia.',
      densidade: 'Putame 35–45 UH; globo pálido pode ser mais denso por depósito de ferro e calcificação.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'No corte dos núcleos da base, é a estrutura em forma de lente lateral à cápsula interna. A cápsula interna, mais hipodensa, o separa do caudado e do tálamo.',
      reparos: ['Cápsula interna (medial)', 'Cápsula externa e ínsula (lateral)', 'Núcleo caudado (anteromedial)', 'Tálamo (posteromedial)'],
      clinica: 'O putame é o sítio MAIS COMUM da hemorragia intraparenquimatosa hipertensiva — cerca de 35% dos casos —, porque as artérias lentículo-estriadas saem em ângulo reto da cerebral média e recebem toda a pressão sistêmica sem amortecimento. Na TC, aparece como hematoma ovalado hiperdenso no putame, que pode dissecar para o ventrículo. Na isquemia, o "sinal do núcleo lentiforme obscurecido" — perda da definição de suas bordas — é um dos achados mais precoces de AVC de cerebral média, aparecendo antes mesmo da hipodensidade franca.',
      alteracoes: [
        { nome: 'Hemorragia putaminal hipertensiva', achado: 'Hematoma ovalado hiperdenso (50–80 UH) no putame; a mais comum das hemorragias hipertensivas.' },
        { nome: 'Sinal do núcleo lentiforme obscurecido', achado: 'Perda de definição das bordas nas primeiras horas do AVC de cerebral média; achado precoce e sutil.' },
        { nome: 'Necrose bilateral dos gânglios da base', achado: 'Hipodensidade simétrica; intoxicação por monóxido de carbono, hipóxia global, metanol.' },
        { nome: 'Calcificação do globo pálido', achado: 'Focos hiperdensos simétricos; fisiológica em idosos.' },
      ],
    },
    {
      id: 'nucleo-lentiforme-esquerdo',
      nome: 'Núcleo lentiforme esquerdo',
      categoria: 'nervoso',
      resumo: 'Contraparte esquerda do putame e do globo pálido.',
      morfologia: 'Idêntica ao direito.',
      funcao: 'Circuito motor dos gânglios da base.',
      densidade: '35–45 UH.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Estrutura em lente lateral à cápsula interna esquerda.',
      reparos: ['Cápsula interna esquerda', 'Ínsula esquerda'],
      clinica: 'A hemorragia putaminal esquerda produz hemiparesia direita e, quando volumosa, afasia — porque comprime as vias e as áreas de linguagem adjacentes. O volume do hematoma, estimado pela fórmula ABC/2, é um dos principais preditores de mortalidade: acima de 30 mL, o prognóstico piora acentuadamente.',
      alteracoes: [
        { nome: 'Hemorragia putaminal esquerda', achado: 'Hematoma hiperdenso com hemiparesia direita; medir volume por ABC/2.' },
      ],
    },
    {
      id: 'capsula-interna-direita',
      nome: 'Cápsula interna direita',
      categoria: 'nervoso',
      resumo: 'Feixe compacto de substância branca entre os núcleos da base; conduz quase todas as vias motoras e sensitivas.',
      morfologia: 'Em corte axial tem forma de "V" aberto lateralmente, com braço anterior (entre caudado e lentiforme), joelho e braço posterior (entre tálamo e lentiforme). O braço posterior é o mais importante: nele passa o trato corticoespinhal, com somatotopia — face mais anterior, perna mais posterior.',
      funcao: 'Autoestrada de fibras: leva as vias motoras do córtex ao tronco e à medula, e traz as vias sensitivas do tálamo ao córtex. Por concentrar tantas fibras num espaço tão pequeno, uma lesão minúscula aqui produz déficit desproporcionalmente grande.',
      densidade: 'Substância branca, 25–35 UH — mais hipodensa que os núcleos vizinhos, o que a torna visível como uma faixa escura entre eles.',
      janela: 'Cerebral estreita — sem ela, a cápsula não se distingue dos núcleos.',
      comoIdentificar: 'No corte dos núcleos da base, é a faixa mais ESCURA em "V" entre o caudado/tálamo (medial) e o lentiforme (lateral).',
      reparos: ['Núcleo caudado (medial, anteriormente)', 'Tálamo (medial, posteriormente)', 'Núcleo lentiforme (lateral)', 'Joelho da cápsula (vértice do V)'],
      clinica: 'A cápsula interna é o exemplo perfeito de que o tamanho da lesão não prediz o tamanho do déficit: um infarto lacunar de 5 mm no braço posterior produz hemiplegia motora pura completa e desproporcional — braço, perna e face contralaterais —, enquanto um infarto cortical dez vezes maior pode causar um déficit muito mais restrito. As lacunas resultam de lipo-hialinose das artérias perfurantes, doença de pequenos vasos ligada a hipertensão e diabetes.',
      alteracoes: [
        { nome: 'Infarto lacunar capsular', achado: 'Lesão hipodensa < 15 mm no braço posterior; hemiplegia motora pura desproporcional ao tamanho.' },
        { nome: 'Hemorragia capsuloputaminal', achado: 'Hematoma que se estende do putame para a cápsula, com déficit motor denso.' },
        { nome: 'Degeneração walleriana', achado: 'Atrofia e hipodensidade do trato corticoespinhal descendente meses após um infarto cortical extenso.' },
      ],
    },
    {
      id: 'capsula-interna-esquerda',
      nome: 'Cápsula interna esquerda',
      categoria: 'nervoso',
      resumo: 'Contraparte esquerda da cápsula interna.',
      morfologia: 'Idêntica à direita.',
      funcao: 'Condução de vias motoras e sensitivas para o hemicorpo direito.',
      densidade: '25–35 UH.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Faixa hipodensa em "V" entre os núcleos, no hemisfério esquerdo.',
      reparos: ['Caudado e tálamo esquerdos', 'Lentiforme esquerdo'],
      clinica: 'A cápsula interna entra no escore ASPECTS como uma das dez regiões avaliadas. Além disso, a somatotopia do braço posterior — face anterior, membro superior no meio, membro inferior posterior — permite prever, a partir da posição exata da lacuna, qual segmento corporal será mais afetado.',
      alteracoes: [
        { nome: 'Lacuna do braço posterior', achado: 'Hemiparesia direita motora pura; a posição da lacuna prediz o predomínio braquial ou crural.' },
      ],
    },
    {
      id: 'talamo-direito',
      nome: 'Tálamo direito',
      categoria: 'nervoso',
      resumo: 'Núcleo diencefálico ovoide que funciona como estação de retransmissão de quase toda a informação sensorial ao córtex.',
      morfologia: 'Massa ovoide de substância cinzenta de cada lado do terceiro ventrículo, medial à cápsula interna e posterior ao forame de Monro. Contém dezenas de núcleos com projeções específicas.',
      funcao: 'Retransmite ao córtex toda a informação sensorial (exceto o olfato), participa do controle motor pelos circuitos dos gânglios da base e do cerebelo, e regula a consciência e o ciclo sono-vigília pelos núcleos intralaminares. É irrigado por perfurantes da artéria cerebral posterior e da comunicante posterior.',
      densidade: 'Substância cinzenta, 35–45 UH.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'No corte dos núcleos da base, são as duas massas ovais que flanqueiam o terceiro ventrículo, atrás dos núcleos lentiformes e mediais à cápsula interna.',
      reparos: ['Terceiro ventrículo (medial)', 'Cápsula interna, braço posterior (lateral)', 'Corpo pineal (posterior)', 'Mesencéfalo (abaixo)'],
      clinica: 'A hemorragia talâmica é a segunda mais comum entre as hipertensivas e tem uma assinatura clínica peculiar: além da hemiparesia e da hemianestesia contralaterais, produz alterações oculares características — desvio dos olhos para BAIXO e para dentro ("olhando para o próprio nariz"), por compressão do teto mesencefálico. Pela proximidade com o terceiro ventrículo, frequentemente rompe para o sistema ventricular, causando hidrocefalia aguda. Já a síndrome de Déjerine-Roussy é a dor talâmica central que surge semanas após o infarto, uma dor neuropática intensa e refratária no hemicorpo previamente insensível.',
      alteracoes: [
        { nome: 'Hemorragia talâmica', achado: 'Hematoma hiperdenso medial, frequentemente com inundação ventricular e hidrocefalia; desvio ocular para baixo e para dentro.' },
        { nome: 'Infarto talâmico', achado: 'Hipodensidade em território de perfurantes; pode causar síndrome sensitiva pura ou alteração de consciência quando bilateral.' },
        { nome: 'Infarto de artéria de Percheron', achado: 'Infarto talâmico BILATERAL simétrico, com ou sem mesencéfalo; variante em que uma única perfurante irriga os dois tálamos. Causa coma súbito inexplicado.' },
        { nome: 'Trombose venosa profunda cerebral', achado: 'Hipodensidade talâmica bilateral por infarto venoso; procurar hiperdensidade da veia de Galeno e do seio reto.' },
      ],
    },
    {
      id: 'talamo-esquerdo',
      nome: 'Tálamo esquerdo',
      categoria: 'nervoso',
      resumo: 'Contraparte esquerda do tálamo.',
      morfologia: 'Idêntica ao direito.',
      funcao: 'Retransmissão sensorial e regulação da consciência.',
      densidade: '35–45 UH.',
      janela: 'Cerebral estreita.',
      comoIdentificar: 'Massa oval à esquerda do terceiro ventrículo.',
      reparos: ['Terceiro ventrículo', 'Cápsula interna esquerda'],
      clinica: 'Lesões talâmicas esquerdas podem produzir afasia talâmica — fala fluente com parafasias e anomia, com repetição preservada —, um quadro que demonstra que a linguagem depende de redes subcorticais e não apenas do córtex. Hipodensidade talâmica BILATERAL é um alerta importante: sugere infarto de artéria de Percheron ou trombose venosa profunda, dois diagnósticos facilmente perdidos.',
      alteracoes: [
        { nome: 'Afasia talâmica', achado: 'Lesão talâmica esquerda com fala fluente, parafasias e repetição preservada.' },
        { nome: 'Hipodensidade talâmica bilateral', achado: 'Percheron ou trombose venosa profunda — procurar sinais venosos e considerar angio-TC venosa.' },
      ],
    },
  ],
  quiz: [
    {
      pergunta: 'Por que a TC de crânio deve ser lida em janela estreita (WW 80 / WL 40)?',
      alternativas: [
        'Para reduzir a dose de radiação',
        'Porque a diferença entre substância cinzenta (35–45 UH) e branca (25–35 UH) é de apenas ~10 UH e desaparece em janelas largas',
        'Para melhorar a visualização do osso',
        'Para reduzir artefatos de movimento',
      ],
      correta: 1,
      explicacao: 'A janela estreita amplifica visualmente uma diferença de dez unidades Hounsfield. Sem ela, a perda da diferenciação corticossubcortical — o sinal mais precoce do AVC isquêmico — é literalmente invisível.',
    },
    {
      pergunta: 'Qual é o local MAIS COMUM de hemorragia intraparenquimatosa hipertensiva?',
      alternativas: ['Lobo frontal', 'Putame', 'Cerebelo', 'Ponte'],
      correta: 1,
      explicacao: 'O putame responde por cerca de 35% das hemorragias hipertensivas, seguido de tálamo, ponte e cerebelo. A causa é a lipo-hialinose das artérias lentículo-estriadas, que saem em ângulo reto da cerebral média e recebem a pressão sistêmica sem amortecimento.',
    },
    {
      pergunta: 'Por que um infarto lacunar de 5 mm no braço posterior da cápsula interna causa hemiplegia completa?',
      alternativas: [
        'Porque causa edema extenso',
        'Porque a cápsula interna concentra, num espaço mínimo, todas as fibras motoras do hemicorpo contralateral',
        'Porque compromete o tálamo adjacente',
        'Porque sempre se acompanha de hemorragia',
      ],
      correta: 1,
      explicacao: 'A cápsula interna é uma autoestrada compacta: o trato corticoespinhal inteiro passa pelo braço posterior. Uma lesão milimétrica ali produz déficit desproporcional — muito maior que o de um infarto cortical dez vezes mais extenso.',
    },
    {
      pergunta: 'Uma TC de crânio NORMAL em paciente com vertigem, ataxia e disfagia agudas permite excluir AVC?',
      alternativas: [
        'Sim, TC normal exclui AVC',
        'Não — a TC tem baixíssima sensibilidade para infartos de fossa posterior; a ressonância com difusão é necessária',
        'Sim, se feita nas primeiras 3 horas',
        'Somente se houver contraste',
      ],
      correta: 1,
      explicacao: 'O artefato de endurecimento do feixe entre os rochedos mascara lesões do tronco e do cerebelo. A síndrome de Wallenberg, por exemplo, é frequentemente invisível na TC. Diante de síndrome de fossa posterior, a ressonância com difusão é obrigatória.',
    },
    {
      pergunta: 'Hipodensidade talâmica BILATERAL e simétrica deve levantar suspeita de:',
      alternativas: [
        'Doença de Alzheimer',
        'Infarto de artéria de Percheron ou trombose venosa cerebral profunda',
        'Esclerose múltipla',
        'Hidrocefalia',
      ],
      correta: 1,
      explicacao: 'A artéria de Percheron é uma variante em que uma única perfurante irriga os dois tálamos — sua oclusão causa infarto talâmico bilateral e coma súbito inexplicado. A trombose venosa profunda produz o mesmo padrão por infarto venoso; procure hiperdensidade da veia de Galeno e do seio reto.',
    },
    {
      pergunta: 'O apagamento das cisternas perimesencefálicas na TC indica:',
      alternativas: [
        'Atrofia cerebral',
        'Hipertensão intracraniana com risco de herniação transtentorial',
        'Hidrocefalia comunicante',
        'Artefato de movimento',
      ],
      correta: 1,
      explicacao: 'As cisternas ao redor do mesencéfalo são o espaço de reserva do compartimento supratentorial. Seu apagamento significa que esse espaço acabou e que a herniação é iminente — é um dos achados mais urgentes de toda a TC de crânio.',
    },
  ],
}
