import type { SubsecaoTC } from '../tipos'

export const cranioPartesMoles: SubsecaoTC = {
  id: 'partes-moles-do-cranio',
  titulo: 'Partes moles do crânio',
  subtitulo: 'Órbitas, pavilhões auriculares e condutos auditivos externos',
  secaoId: 'cranio',
  pasta: '/TC_CRANIO/TC_CRANIO_PARTES_MOLES',
  ext: 'PNG',
  totalCortes: 17,
  orientacao: 'caudo-cranial',
  icone: 'eye',
  cor: 'ardosia',
  janelaPadrao: 'mediastinal',
  protocolo:
    'Cortes finos com reconstrução de partes moles, lidos em janela de partes moles (WW 350 / WL 50) e conferidos em janela óssea para as paredes orbitárias. Para órbita, reconstruções coronal e sagital são indispensáveis: o assoalho e o teto orbitários são horizontais e praticamente invisíveis no plano axial. O contraste entra quando a suspeita é celulite orbitária, massa ou trombose de seio cavernoso.',
  introducao:
    'Esta é a seção que a maioria dos leitores de TC de crânio ignora — e é a que mais devolve achados em pronto-socorro. A órbita é um cone de gordura contendo o globo, os músculos extrínsecos, o nervo óptico e vasos, tudo empacotado num espaço ósseo rígido de cerca de 30 mL. Essa rigidez é a chave da sua patologia: qualquer coisa que aumente de volume — sangue, pus, ar, tumor — empurra o globo para a frente (proptose) e pode comprimir o nervo óptico, uma emergência com janela de horas para preservar a visão. Já os pavilhões auriculares e os condutos auditivos externos são estruturas superficiais que a TC mostra bem e que carregam achados discretos porém decisivos: gás nos tecidos moles periauriculares, coleções e erosões ósseas que denunciam a otite externa maligna do diabético. Percorrer esta série é treinar o olhar para o que está fora do parênquima — a periferia da imagem, onde o olho cansado deixa de olhar.',
  roteiro: [
    { passo: '1. Compare as órbitas', detalhe: 'Posição do globo, espessura dos músculos, densidade da gordura e calibre do nervo óptico, sempre lado a lado.' },
    { passo: '2. Meça a proptose', detalhe: 'Trace uma linha entre as bordas laterais das órbitas; mais de 21 mm de globo à frente dela é proptose.' },
    { passo: '3. Confira as paredes orbitárias em janela óssea', detalhe: 'Assoalho e parede medial (lâmina papirácea) são os pontos frágeis; use coronal.' },
    { passo: '4. Avalie o conteúdo intraconal', detalhe: 'Gordura homogênea, nervo óptico central, músculos simétricos. Densificação da gordura é sinal precoce de inflamação.' },
    { passo: '5. Olhe os pavilhões auriculares', detalhe: 'Simetria, espessamento, coleções e gás nas partes moles.' },
    { passo: '6. Siga os condutos auditivos externos', detalhe: 'Devem estar aerados e simétricos; conteúdo de partes moles com erosão óssea é bandeira vermelha.' },
  ],
  perolas: [
    'Proptose = mais de 21 mm do globo anterior à linha interzigomática, ou diferença > 2 mm entre os lados.',
    'Celulite PRÉ-septal (à frente do septo orbitário) é tratada com antibiótico oral; PÓS-septal exige internação, antibiótico venoso e vigilância da visão. O septo é a fronteira que a TC define.',
    'Espessamento dos ventres musculares POUPANDO os tendões é a assinatura da orbitopatia de Graves. Se o tendão está espesso, pense em miosite inflamatória.',
    'Gás na órbita após trauma indica fratura comunicando com um seio paranasal — mesmo que você não veja o traço.',
    'Otite externa maligna: tecido de partes moles no conduto com erosão óssea da base do crânio, em diabético idoso. É osteomielite, não otite banal.',
  ],
  estruturas: [
    {
      id: 'orbita-direita',
      nome: 'Órbita direita',
      categoria: 'partes-moles',
      resumo: 'Cavidade óssea piramidal que aloja o globo ocular, os músculos extrínsecos, o nervo óptico e a gordura orbitária.',
      morfologia: 'Pirâmide de quatro paredes com o ápice posteromedial, onde ficam o canal óptico e a fissura orbitária superior. Volume de cerca de 30 mL, dos quais o globo ocupa apenas 7 mL — o restante é gordura, músculos, vasos e nervos. O septo orbitário, uma lâmina fibrosa que vai da borda óssea às pálpebras, divide o compartimento pré-septal do pós-septal. Os quatro músculos retos e o oblíquo superior delimitam o espaço intraconal.',
      funcao: 'Proteger e posicionar o globo, permitir a motilidade ocular e dar passagem ao nervo óptico e à vascularização. A gordura orbitária funciona como coxim hidráulico que permite o movimento sem atrito.',
      densidade: 'Gordura orbitária −80 a −100 UH; músculos 40–60 UH; nervo óptico 30–40 UH; globo com humor vítreo em torno de 10–20 UH e cristalino mais denso (~70 UH).',
      janela: 'Partes moles para o conteúdo; óssea para as paredes. Coronal é obrigatório para assoalho e teto.',
      comoIdentificar: 'Nos cortes baixos da série, são as duas cavidades cheias de gordura escura contendo o globo ocular anteriormente e o nervo óptico se dirigindo posteromedialmente ao ápice.',
      reparos: ['Seio maxilar (abaixo — o assoalho orbitário é o teto do seio)', 'Seio etmoidal (medial, pela lâmina papirácea)', 'Seio frontal e fossa anterior (acima)', 'Fissura orbitária superior e canal óptico (ápice)', 'Músculos retos (delimitam o cone)'],
      clinica: 'A grande decisão que a TC toma aqui é pré-septal versus pós-septal. A celulite pré-septal envolve apenas as pálpebras, à frente do septo orbitário, e se resolve com antibiótico oral; a pós-septal invade o cone, causa proptose, oftalmoplegia e dor à movimentação ocular, e exige internação, antibiótico venoso e reavaliação frequente da acuidade visual — porque pode evoluir para abscesso subperiosteal, perda visual e trombose de seio cavernoso. A segunda decisão é a síndrome compartimental orbitária: hematoma retrobulbar após trauma ou cirurgia, com proptose tensa e estiramento do nervo óptico, é uma emergência com janela de 60 a 120 minutos para cantotomia lateral. A terceira grande entidade é a orbitopatia de Graves, cujo padrão de espessamento muscular — ventres espessos e tendões poupados, acometendo preferencialmente o reto inferior e o medial — é praticamente diagnóstico.',
      alteracoes: [
        { nome: 'Celulite pós-septal com abscesso subperiosteal', achado: 'Coleção lenticular na parede medial, adjacente a etmoide opacificado, deslocando o reto medial; proptose e densificação da gordura.' },
        { nome: 'Hematoma retrobulbar', achado: 'Coleção hiperdensa intraconal com proptose, estiramento do nervo óptico e ápice "cheio" — emergência para cantotomia.' },
        { nome: 'Orbitopatia de Graves', achado: 'Espessamento fusiforme dos ventres musculares poupando os tendões (reto inferior e medial primeiro), com aumento da gordura e proptose bilateral.' },
        { nome: 'Fratura blow-out do assoalho', achado: 'Descontinuidade com herniação de gordura/músculo para o seio maxilar; encarceramento do reto inferior causa diplopia e pede cirurgia.' },
        { nome: 'Pseudotumor inflamatório orbitário', achado: 'Espessamento muscular COM envolvimento do tendão, unilateral e doloroso — o oposto de Graves.' },
        { nome: 'Corpo estranho intraorbitário', achado: 'Material hiperdenso (metal, vidro) ou hipodenso (madeira, que pode simular ar); a TC é o exame de escolha antes de qualquer ressonância.' },
      ],
      armadilhas: ['Corpo estranho de madeira tem densidade próxima à do ar e é confundido com pneumo-órbita — a história do trauma resolve, e a ressonância é contraindicada até excluir metal.'],
      medidas: [{ rotulo: 'Proptose', valor: '> 21 mm à frente da linha interzigomática' }, { rotulo: 'Espessura muscular normal', valor: '≤ 4–5 mm' }],
    },
    {
      id: 'orbita-esquerda',
      nome: 'Órbita esquerda',
      categoria: 'partes-moles',
      resumo: 'Contraparte esquerda; a comparação entre as duas é o método central de leitura.',
      morfologia: 'Idêntica à direita.',
      funcao: 'Idêntica à direita.',
      densidade: 'Igual à direita.',
      janela: 'Partes moles e óssea.',
      comoIdentificar: 'Cavidade orbitária esquerda; medir e comparar a projeção do globo e a espessura dos músculos no mesmo corte.',
      reparos: ['Seio maxilar esquerdo', 'Seio etmoidal esquerdo', 'Canal óptico esquerdo'],
      clinica: 'Proptose UNILATERAL tem diagnóstico diferencial diferente da bilateral. A unilateral sugere massa (hemangioma cavernoso, linfoma, metástase), inflamação (pseudotumor, celulite) ou fístula carótido-cavernosa — esta última com o sinal quase específico da dilatação da veia oftálmica superior. A bilateral aponta sobretudo para orbitopatia de Graves, a causa mais comum de proptose no adulto.',
      alteracoes: [
        { nome: 'Fístula carótido-cavernosa', achado: 'Veia oftálmica superior dilatada, seio cavernoso alargado com realce precoce, proptose pulsátil e quemose.' },
        { nome: 'Hemangioma cavernoso orbitário', achado: 'Massa intraconal bem delimitada com realce progressivo; tumor orbitário benigno mais comum do adulto.' },
        { nome: 'Linfoma orbitário', achado: 'Massa que se molda às estruturas sem destruí-las, homogênea, frequentemente na glândula lacrimal.' },
      ],
    },
    {
      id: 'pavilhao-auricular-direito',
      nome: 'Pavilhão auricular direito',
      sinonimos: ['orelha externa direita', 'aurícula direita'],
      categoria: 'partes-moles',
      resumo: 'Estrutura cartilaginosa externa que capta e direciona o som ao conduto auditivo.',
      morfologia: 'Lâmina de cartilagem elástica recoberta por pele fina e firmemente aderida, com pericôndrio como única fonte de nutrição — a cartilagem é avascular. Suas subunidades (hélice, anti-hélice, concha, trago, lóbulo) dão o relevo característico.',
      funcao: 'Captação e amplificação seletiva de frequências, e localização espacial do som pelas diferenças de tempo e intensidade entre as duas orelhas.',
      densidade: 'Partes moles e cartilagem, 40–70 UH; a cartilagem pode calcificar com a idade ou após trauma.',
      janela: 'Partes moles.',
      comoIdentificar: 'Estrutura de partes moles projetando-se lateralmente da cabeça, ao lado do conduto auditivo externo.',
      reparos: ['Conduto auditivo externo (medial)', 'Mastoide (posterior)', 'Articulação temporomandibular (anterior)', 'Glândula parótida (anteroinferior)'],
      clinica: 'A dependência exclusiva do pericôndrio para nutrir a cartilagem explica duas condições. O hematoma auricular do lutador descola o pericôndrio da cartilagem, que necrosa e cicatriza de forma desorganizada — a "orelha em couve-flor"; por isso a drenagem precoce é essencial. E a pericondrite, frequentemente após piercing na porção cartilaginosa, pode destruir a cartilagem e deformar permanentemente a orelha. Na TC, procura-se espessamento, coleções e, sobretudo, gás nos tecidos moles, sinal de infecção por anaeróbios.',
      alteracoes: [
        { nome: 'Hematoma auricular', achado: 'Coleção entre o pericôndrio e a cartilagem; sem drenagem, evolui para deformidade em couve-flor.' },
        { nome: 'Pericondrite', achado: 'Espessamento difuso com realce e densificação; risco de necrose cartilaginosa.' },
        { nome: 'Neoplasia cutânea (carcinoma espinocelular)', achado: 'Massa com invasão da cartilagem e possível extensão ao conduto e à parótida.' },
      ],
    },
    {
      id: 'pavilhao-auricular-esquerdo',
      nome: 'Pavilhão auricular esquerdo',
      categoria: 'partes-moles',
      resumo: 'Contraparte esquerda da orelha externa.',
      morfologia: 'Idêntica à direita.',
      funcao: 'Captação sonora e localização espacial.',
      densidade: 'Igual à direita.',
      janela: 'Partes moles.',
      comoIdentificar: 'Espelho da direita; comparar espessura e contorno.',
      reparos: ['Conduto auditivo externo esquerdo', 'Mastoide esquerda', 'Parótida esquerda'],
      clinica: 'Assimetria de partes moles periauriculares, com densificação e gás, num diabético idoso com otalgia intensa e desproporcional ao exame, é o quadro da otite externa maligna — que na verdade é uma osteomielite da base do crânio por Pseudomonas aeruginosa, com mortalidade significativa.',
      alteracoes: [
        { nome: 'Extensão de otite externa maligna', achado: 'Densificação das partes moles periauriculares e do espaço parafaríngeo, com erosão óssea da base do crânio.' },
        { nome: 'Abscesso periauricular', achado: 'Coleção com realce periférico; procurar origem no conduto ou na parótida.' },
      ],
    },
    {
      id: 'conduto-auditivo-externo-direito',
      nome: 'Conduto auditivo externo direito',
      sinonimos: ['meato acústico externo direito'],
      categoria: 'partes-moles',
      resumo: 'Canal de 2,5 cm que conduz o som do pavilhão à membrana timpânica.',
      morfologia: 'Terço externo cartilaginoso (com folículos pilosos e glândulas ceruminosas) e dois terços internos ósseos, escavados no osso temporal. Tem trajeto em "S" e termina na membrana timpânica, que o separa da orelha média. Na junção osteocartilaginosa existem as fissuras de Santorini, por onde a infecção pode escapar para os tecidos profundos.',
      funcao: 'Condução e ressonância do som (amplifica cerca de 10–15 dB nas frequências da fala). O cerume e os pelos protegem contra corpos estranhos e infecções; o pH ácido inibe o crescimento bacteriano.',
      densidade: 'Ar (−1000 UH) quando normal, com paredes ósseas densas na porção interna.',
      janela: 'Partes moles e óssea.',
      comoIdentificar: 'Canal aéreo que vai do pavilhão auricular em direção medial até a membrana timpânica, dentro do osso temporal.',
      reparos: ['Membrana timpânica (extremidade medial)', 'Articulação temporomandibular (anterior)', 'Mastoide (posterior)', 'Fissuras de Santorini (junção osteocartilaginosa)'],
      clinica: 'A otite externa maligna (necrosante) é o diagnóstico que justifica examinar essa estrutura com atenção: em diabéticos e imunossuprimidos idosos, a infecção por Pseudomonas escapa pelas fissuras de Santorini e se transforma em osteomielite da base do crânio. Na TC, o achado é tecido de partes moles no conduto associado a EROSÃO ÓSSEA e densificação dos planos profundos — e é a erosão óssea, não o tecido mole, que faz o diagnóstico. A doença pode acometer nervos cranianos baixos e o canal facial, e exige antibioticoterapia prolongada.',
      alteracoes: [
        { nome: 'Otite externa maligna', achado: 'Tecido de partes moles com erosão óssea da parede do conduto e da base do crânio, densificação do espaço parafaríngeo; diabético idoso com otalgia intensa.' },
        { nome: 'Exostose / osteoma do conduto', achado: 'Crescimento ósseo estreitando o canal; a exostose é bilateral e de base larga ("orelha do surfista"), o osteoma é único e pediculado.' },
        { nome: 'Colesteatoma de conduto externo', achado: 'Erosão focal da parede óssea com conteúdo de partes moles.' },
        { nome: 'Atresia congênita', achado: 'Ausência do canal com placa atrésica óssea; avaliar cadeia ossicular e trajeto do nervo facial antes de cirurgia.' },
      ],
    },
    {
      id: 'conduto-auditivo-externo-esquerdo',
      nome: 'Conduto auditivo externo esquerdo',
      categoria: 'partes-moles',
      resumo: 'Contraparte esquerda do canal auditivo externo.',
      morfologia: 'Idêntica ao direito.',
      funcao: 'Condução e amplificação sonora.',
      densidade: 'Ar quando normal.',
      janela: 'Partes moles e óssea.',
      comoIdentificar: 'Canal aéreo do lado esquerdo; comparar aeração e calibre com o direito.',
      reparos: ['Membrana timpânica esquerda', 'ATM esquerda', 'Mastoide esquerda'],
      clinica: 'Opacificação unilateral do conduto tem diferencial amplo — cerume impactado, otite externa, corpo estranho, neoplasia — e a chave para separá-los está no OSSO: se há erosão, o problema é grave (otite maligna ou neoplasia); se o osso está íntegro, o mais provável é conteúdo banal.',
      alteracoes: [
        { nome: 'Cerume impactado', achado: 'Conteúdo de partes moles sem erosão óssea nem realce; achado banal.' },
        { nome: 'Carcinoma do conduto', achado: 'Massa com destruição óssea e extensão à parótida ou à orelha média; raro e agressivo.' },
      ],
    },
  ],
  quiz: [
    {
      pergunta: 'Qual estrutura separa a celulite pré-septal da pós-septal, e por que a distinção importa?',
      alternativas: [
        'A cápsula de Tenon; muda o antibiótico',
        'O septo orbitário; a pré-septal é tratada por via oral e a pós-septal exige internação e vigilância da visão',
        'A conjuntiva; muda apenas o prognóstico estético',
        'A periórbita; não muda a conduta',
      ],
      correta: 1,
      explicacao: 'O septo orbitário é a lâmina fibrosa entre a borda óssea e as pálpebras. Infecção à frente dele é palpebral e benigna; atrás dele invade o cone, causa proptose e oftalmoplegia e pode levar a abscesso, perda visual e trombose de seio cavernoso.',
    },
    {
      pergunta: 'Espessamento dos ventres musculares extraoculares POUPANDO os tendões é típico de:',
      alternativas: ['Pseudotumor inflamatório', 'Orbitopatia de Graves', 'Celulite orbitária', 'Linfoma'],
      correta: 1,
      explicacao: 'Na orbitopatia de Graves o processo é infiltrativo do ventre muscular, poupando as inserções tendíneas — reto inferior e medial primeiro. O pseudotumor inflamatório, ao contrário, envolve o tendão e costuma ser unilateral e doloroso.',
    },
    {
      pergunta: 'Hematoma retrobulbar com proptose tensa após trauma é uma emergência porque:',
      alternativas: [
        'Pode causar infecção',
        'Produz síndrome compartimental orbitária com isquemia do nervo óptico, com janela de 60–120 minutos para cantotomia',
        'Pode romper o globo ocular',
        'Sempre evolui para fístula carótido-cavernosa',
      ],
      correta: 1,
      explicacao: 'A órbita é um compartimento rígido de ~30 mL. O aumento agudo de volume eleva a pressão, estira o nervo óptico e compromete sua perfusão. A cantotomia lateral descomprime e precisa ser feita em pouco mais de uma hora para preservar a visão.',
    },
    {
      pergunta: 'Tecido de partes moles no conduto auditivo externo COM erosão óssea da base do crânio, em diabético idoso, indica:',
      alternativas: ['Cerume impactado', 'Otite externa maligna (osteomielite de base de crânio)', 'Exostose', 'Otite média serosa'],
      correta: 1,
      explicacao: 'A erosão óssea é o que transforma o quadro de otite externa banal em osteomielite da base do crânio por Pseudomonas. Exige antibioticoterapia prolongada e vigilância de nervos cranianos; a mortalidade é significativa.',
    },
  ],
}
