import type { SubsecaoTC } from '../tipos'

export const cranioOssos: SubsecaoTC = {
  id: 'ossos-do-cranio',
  titulo: 'Ossos do crânio',
  subtitulo: 'Calota, base, seios paranasais, mastoides e suturas',
  secaoId: 'cranio',
  pasta: '/TC_CRANIO/TC_CRANIO_OSSOS',
  ext: 'PNG',
  totalCortes: 20,
  orientacao: 'caudo-cranial',
  icone: 'bone',
  cor: 'ambar',
  janelaPadrao: 'ossea',
  protocolo:
    'Reconstrução com filtro ósseo da mesma aquisição da TC de crânio, lida em janela óssea (WW 2000 / WL 400). Para trauma, reconstruções coronal e sagital são obrigatórias: fraturas horizontais da base do crânio são invisíveis no plano axial. Para seios paranasais e ouvido, cortes finos (0,6–1 mm) e reconstruções nos três planos; o osso temporal exige um protocolo dedicado de altíssima resolução.',
  introducao:
    'O crânio ósseo é onde a janela deixa de ser preferência e passa a ser um interruptor: em janela cerebral, o osso é uma massa branca uniforme e uma fratura simplesmente não existe; em janela óssea, o parênquima some e o osso revela sua arquitetura. Aprender a alternar deliberadamente entre as duas é a primeira habilidade desta seção. A segunda é entender que o crânio tem duas partes com lógicas diferentes: a calota, formada por ossos chatos com duas tábuas corticais e díploe entre elas, feita para proteger por resistência; e a base, um mosaico complexo de forames e canais por onde passam nervos e vasos, onde uma fratura de milímetros pode significar fístula liquórica, lesão de carótida ou paralisia facial. A terceira habilidade é distinguir o normal do patológico entre estruturas que se parecem: suturas e canais vasculares imitam fraturas o tempo todo, e é a familiaridade com o trajeto e a morfologia deles que evita o falso-positivo. Percorrendo esta série de baixo para cima, você atravessa a base, os seios paranasais, os rochedos temporais e chega à calota — o percurso natural da leitura óssea.',
  roteiro: [
    { passo: '1. Troque para janela óssea', detalhe: 'Nenhuma fratura sem desvio é visível fora dela.' },
    { passo: '2. Percorra os seios paranasais', detalhe: 'Frontais, etmoidais, esfenoidais e maxilares — todos devem ser aerados. Nível líquido em trauma é sinal indireto de fratura.' },
    { passo: '3. Examine os rochedos e mastoides', detalhe: 'Células mastóideas aeradas, conduto auditivo interno simétrico, cadeia ossicular íntegra.' },
    { passo: '4. Siga a base do crânio', detalhe: 'Fossa anterior, média e posterior. Procure descontinuidades, gás intracraniano e assimetrias de forames.' },
    { passo: '5. Suba pela calota', detalhe: 'Frontal, parietais, temporais e occipital. Compare os dois lados e siga a cortical de forma contínua.' },
    { passo: '6. Identifique as suturas', detalhe: 'Coronal, sagital e lambdóide são bordas serrilhadas e simétricas — não são fraturas.' },
  ],
  perolas: [
    'Fratura x sutura: a fratura é retilínea, tem bordas nítidas e não é simétrica; a sutura é serrilhada, tem bordas escleróticas e tem par do outro lado.',
    'Pneumoencéfalo (ar dentro do crânio) prova que existe uma comunicação com o exterior ou com um seio — mesmo se você não achar a fratura.',
    'Nível hidroaéreo no seio esfenoidal em politraumatizado = fratura de base de crânio até prova em contrário.',
    'Sinal de Battle (equimose retroauricular) e olhos de guaxinim correspondem a fraturas de base — mas aparecem horas depois. A TC vem antes.',
    'Fratura de osso temporal: a longitudinal (paralela ao eixo do rochedo) atinge a cadeia ossicular e causa perda condutiva; a transversal atinge a cóclea e o nervo facial, com perda neurossensorial e paralisia facial.',
  ],
  estruturas: [
    {
      id: 'seio-maxilar-direito',
      nome: 'Seio maxilar direito',
      sinonimos: ['antro de Highmore'],
      categoria: 'seio-paranasal',
      resumo: 'Maior dos seios paranasais, dentro do corpo da maxila, abaixo da órbita.',
      morfologia: 'Cavidade piramidal com base voltada para a cavidade nasal e ápice para o processo zigomático. Seu teto é o assoalho da órbita; seu assoalho relaciona-se com as raízes dos dentes pré-molares e molares. Drena por um óstio localizado ALTO na parede medial — uma configuração hidraulicamente ruim, que exige transporte mucociliar ativo contra a gravidade.',
      funcao: 'Aquecimento e umidificação do ar, aligeiramento do crânio e ressonância vocal. O epitélio ciliado varre o muco em direção ao óstio; quando o transporte falha ou o óstio obstrui, instala-se a sinusite.',
      densidade: 'Ar (−1000 UH) quando normal. Conteúdo inflamatório: 10–30 UH. Secreção espessa crônica ou fúngica: pode chegar a 100 UH ou mais, com calcificações.',
      janela: 'Óssea para as paredes; partes moles para o conteúdo e para lesões expansivas.',
      comoIdentificar: 'Nos cortes baixos, é a grande cavidade aérea de cada lado do nariz, abaixo das órbitas.',
      reparos: ['Órbita (acima — o teto do seio é o assoalho orbitário)', 'Cavidade nasal (medial)', 'Fossa pterigopalatina (posterior)', 'Raízes dentárias (abaixo)'],
      clinica: 'A fratura do assoalho orbitário ("blow-out") faz o conteúdo da órbita herniar para dentro do seio maxilar, produzindo o clássico "sinal da gota pendente". Quando o músculo reto inferior é encarcerado, surge diplopia à supraversão, e a cirurgia se torna urgente. Do lado infeccioso, a sinusite maxilar de origem dentária é responsável por até 40% dos casos unilaterais — sempre vale olhar as raízes dos molares. E qualquer opacificação unilateral com destruição óssea em adulto exige excluir neoplasia, não apenas sinusite.',
      alteracoes: [
        { nome: 'Fratura blow-out do assoalho orbitário', achado: 'Descontinuidade do assoalho com herniação de gordura/músculo para o seio ("gota pendente") e enfisema orbitário.' },
        { nome: 'Sinusite aguda', achado: 'Nível hidroaéreo ou espessamento mucoso com aeração parcial.' },
        { nome: 'Sinusite odontogênica', achado: 'Opacificação unilateral com lesão periapical dentária subjacente; procurar sempre a raiz do molar.' },
        { nome: 'Bola fúngica', achado: 'Conteúdo hiperdenso com calcificações puntiformes, em seio único, com esclerose das paredes.' },
        { nome: 'Neoplasia sinonasal', achado: 'Massa de partes moles com destruição óssea — o achado que separa tumor de inflamação.' },
        { nome: 'Cisto de retenção', achado: 'Lesão em cúpula, de base larga no assoalho, com densidade líquida; achado incidental banal.' },
      ],
      armadilhas: ['Espessamento mucoso leve é achado incidental em até 40% das TCs de crânio de pessoas assintomáticas — não se diagnostica sinusite por imagem isolada.'],
    },
    {
      id: 'seio-maxilar-esquerdo',
      nome: 'Seio maxilar esquerdo',
      categoria: 'seio-paranasal',
      resumo: 'Contraparte esquerda do maior seio paranasal.',
      morfologia: 'Idêntica ao direito; assimetrias de volume entre os dois lados são comuns e normais.',
      funcao: 'Idêntica ao direito.',
      densidade: 'Ar quando normal.',
      janela: 'Óssea / partes moles.',
      comoIdentificar: 'Cavidade aérea à esquerda do nariz, abaixo da órbita esquerda.',
      reparos: ['Órbita esquerda', 'Cavidade nasal', 'Processo zigomático'],
      clinica: 'A comparação bilateral é o método: opacificação UNILATERAL em adulto merece muito mais atenção do que a bilateral, porque a bilateral costuma ser inflamatória e a unilateral levanta a hipótese de causa odontogênica, corpo estranho, bola fúngica ou neoplasia.',
      alteracoes: [
        { nome: 'Opacificação unilateral', achado: 'Investigar causa dentária, fúngica ou neoplásica; procurar destruição óssea.' },
        { nome: 'Hipoplasia do seio maxilar', achado: 'Seio pequeno com paredes espessas; variante que pode acompanhar a síndrome do seio silencioso, com enoftalmia progressiva.' },
      ],
    },
    {
      id: 'seio-etmoidal-direito',
      nome: 'Seio etmoidal direito',
      categoria: 'seio-paranasal',
      resumo: 'Labirinto de células aéreas entre a órbita e a cavidade nasal.',
      morfologia: 'Conjunto de 3 a 18 células aéreas separadas por septos finíssimos, dividido em grupos anterior, médio e posterior. Sua parede lateral é a lâmina papirácea — uma lâmina óssea de espessura de papel que separa o etmoide da órbita.',
      funcao: 'Condicionamento do ar e proteção da órbita. A lâmina papirácea é a fronteira mais frágil da face.',
      densidade: 'Ar quando normal; septos finos e hiperdensos.',
      janela: 'Óssea, com cortes finos.',
      comoIdentificar: 'Entre a órbita direita e a cavidade nasal, um "favo" de pequenas células aéreas.',
      reparos: ['Órbita (lateral, através da lâmina papirácea)', 'Cavidade nasal (medial)', 'Lâmina cribriforme (acima)', 'Seio esfenoidal (posterior)'],
      clinica: 'A etmoidite é a causa mais comum de celulite orbitária em crianças, justamente porque a lâmina papirácea é fina e permeável — a infecção atravessa e se instala na órbita. Na TC, procura-se o abscesso subperiosteal, uma coleção lenticular na parede medial da órbita, cuja presença muda o tratamento de antibiótico para drenagem. Acima, a lâmina cribriforme é o outro ponto de fragilidade: fraturas ali produzem fístula liquórica nasal (rinorreia) e risco de meningite.',
      alteracoes: [
        { nome: 'Celulite orbitária com abscesso subperiosteal', achado: 'Coleção lenticular na parede medial da órbita, adjacente a etmoide opacificado, com desvio do reto medial.' },
        { nome: 'Fratura da lâmina papirácea', achado: 'Descontinuidade com enfisema orbitário; comum no trauma facial.' },
        { nome: 'Fístula liquórica pela lâmina cribriforme', achado: 'Defeito ósseo com pneumoencéfalo ou herniação meníngea; rinorreia liquórica.' },
        { nome: 'Polipose nasossinusal', achado: 'Opacificação difusa com alargamento das cavidades e remodelamento ósseo.' },
      ],
    },
    {
      id: 'seio-etmoidal-esquerdo',
      nome: 'Seio etmoidal esquerdo',
      categoria: 'seio-paranasal',
      resumo: 'Labirinto etmoidal esquerdo.',
      morfologia: 'Idêntica ao direito.',
      funcao: 'Condicionamento do ar; fronteira com a órbita.',
      densidade: 'Ar quando normal.',
      janela: 'Óssea.',
      comoIdentificar: 'Favo de células aéreas entre a órbita esquerda e o nariz.',
      reparos: ['Órbita esquerda', 'Lâmina papirácea esquerda', 'Cavidade nasal'],
      clinica: 'Antes de cirurgia endoscópica nasossinusal, a TC define variantes anatômicas de risco: célula de Onodi (célula etmoidal posterior que se estende sobre o canal óptico, expondo o nervo óptico), célula de Haller (na órbita, estreitando o complexo ostiomeatal) e a altura da lâmina cribriforme pela classificação de Keros — quanto mais profunda, maior o risco de fístula liquórica iatrogênica.',
      alteracoes: [
        { nome: 'Célula de Onodi', achado: 'Célula etmoidal posterior pneumatizando sobre o canal óptico; risco de lesão do nervo óptico em cirurgia.' },
        { nome: 'Classificação de Keros', achado: 'Profundidade da fossa olfatória; Keros III (7–16 mm) é o de maior risco de fístula liquórica cirúrgica.' },
      ],
    },
    {
      id: 'seio-esfenoidal-direito',
      nome: 'Seio esfenoidal direito',
      categoria: 'seio-paranasal',
      resumo: 'Cavidade aérea dentro do corpo do esfenoide, no centro da base do crânio.',
      morfologia: 'Ocupa o corpo do osso esfenoide, abaixo da sela turca. Seu teto é o assoalho selar; suas paredes laterais relacionam-se com o seio cavernoso, a artéria carótida interna e o nervo óptico — que podem fazer relevos dentro da cavidade ou até estar deiscentes.',
      funcao: 'Aligeiramento do crânio; é também o corredor cirúrgico para a hipófise — a cirurgia transesfenoidal atravessa o nariz e esse seio para alcançar a sela.',
      densidade: 'Ar quando normal.',
      janela: 'Óssea; partes moles para conteúdo e sela.',
      comoIdentificar: 'Cavidade aérea central na base do crânio, atrás do etmoide e abaixo da sela turca.',
      reparos: ['Sela turca e hipófise (acima)', 'Seio cavernoso e carótida interna (laterais)', 'Nervo óptico (súpero-lateral)', 'Clivo (posterior)'],
      clinica: 'Duas aplicações se destacam. Na cirurgia transesfenoidal de adenoma hipofisário, a TC mapeia o grau de pneumatização, a posição dos septos (que às vezes se inserem sobre a carótida — armadilha grave) e a deiscência óssea sobre carótida e nervo óptico. No trauma, o nível hidroaéreo no seio esfenoidal em politraumatizado é um dos sinais indiretos mais confiáveis de fratura de base de crânio, e obriga a procurar o traço com cortes finos.',
      alteracoes: [
        { nome: 'Nível hidroaéreo pós-traumático', achado: 'Sinal indireto de fratura da base do crânio; procurar o traço com cortes finos e reconstruções.' },
        { nome: 'Deiscência óssea sobre a carótida', achado: 'Ausência de cortical entre o seio e a artéria; risco catastrófico em cirurgia endoscópica.' },
        { nome: 'Sinusite esfenoidal', achado: 'Opacificação com espessamento; pode complicar com trombose de seio cavernoso e meningite.' },
        { nome: 'Mucocele', achado: 'Cavidade expandida com conteúdo homogêneo e afinamento das paredes; pode comprimir o nervo óptico.' },
      ],
    },
    {
      id: 'seio-esfenoidal-esquerdo',
      nome: 'Seio esfenoidal esquerdo',
      categoria: 'seio-paranasal',
      resumo: 'Compartimento esquerdo do seio esfenoidal, separado por um septo frequentemente assimétrico.',
      morfologia: 'O septo intersfenoidal raramente é mediano — sua assimetria é a regra, e sua inserção lateral pode coincidir com a parede da carótida.',
      funcao: 'Idêntica ao direito.',
      densidade: 'Ar quando normal.',
      janela: 'Óssea.',
      comoIdentificar: 'Compartimento à esquerda do septo intersfenoidal.',
      reparos: ['Sela turca', 'Carótida interna esquerda', 'Clivo'],
      clinica: 'A localização exata do septo intersfenoidal é uma das informações mais importantes que a TC entrega ao neurocirurgião: um septo que se insere sobre a protuberância carotídea pode ser fraturado durante a abordagem e lacerar a carótida — uma das complicações mais temidas da cirurgia transesfenoidal.',
      alteracoes: [
        { nome: 'Septo inserido sobre a carótida', achado: 'Septo intersfenoidal ancorado no relevo carotídeo; risco de lesão vascular na cirurgia.' },
        { nome: 'Pneumatização variável', achado: 'Tipos conchal, pré-selar e selar; a pneumatização conchal dificulta a via transesfenoidal.' },
      ],
    },
    {
      id: 'seio-frontal-direito',
      nome: 'Seio frontal direito',
      categoria: 'seio-paranasal',
      resumo: 'Cavidade aérea no osso frontal, acima da órbita.',
      morfologia: 'Muito variável em tamanho e forma — pode ser ausente em 5% das pessoas. Drena pelo recesso frontonasal até o meato médio. Sua parede posterior separa o seio da fossa craniana anterior e do lobo frontal.',
      funcao: 'Condicionamento do ar e absorção de impacto frontal. Como a pneumatização é individual e assimétrica, o padrão do seio frontal é usado em identificação forense — é praticamente uma impressão digital.',
      densidade: 'Ar quando normal.',
      janela: 'Óssea.',
      comoIdentificar: 'Cavidades aéreas na porção anterior do osso frontal, acima das órbitas, nos cortes altos.',
      reparos: ['Órbita (abaixo)', 'Fossa craniana anterior e lobo frontal (atrás da parede posterior)', 'Recesso frontonasal (drenagem inferior)'],
      clinica: 'A fratura do seio frontal se divide em duas situações com condutas opostas. Se apenas a parede ANTERIOR está fraturada, o problema é estético e o tratamento pode ser conservador. Se a parede POSTERIOR está envolvida, existe comunicação com a dura-máter e o risco de fístula liquórica, pneumoencéfalo, meningite e abscesso — o que muda a abordagem para cirúrgica. Portanto, diante de fratura frontal, a pergunta obrigatória é: a parede posterior está íntegra?',
      alteracoes: [
        { nome: 'Fratura da parede anterior isolada', achado: 'Descontinuidade anterior com afundamento; problema sobretudo estético.' },
        { nome: 'Fratura da parede posterior', achado: 'Descontinuidade posterior com pneumoencéfalo; risco de fístula liquórica e meningite — abordagem cirúrgica.' },
        { nome: 'Mucocele frontal', achado: 'Cavidade expandida com conteúdo homogêneo e erosão das paredes; pode deslocar o globo ocular.' },
        { nome: 'Tumor de Pott (Pott puffy tumor)', achado: 'Osteomielite do frontal com abscesso subperiosteal e tumefação da fronte; frequentemente com empiema epidural associado.' },
      ],
    },
    {
      id: 'seio-frontal-esquerdo',
      nome: 'Seio frontal esquerdo',
      categoria: 'seio-paranasal',
      resumo: 'Compartimento esquerdo do seio frontal.',
      morfologia: 'Separado do direito por um septo intersinusal habitualmente assimétrico.',
      funcao: 'Idêntica ao direito.',
      densidade: 'Ar quando normal.',
      janela: 'Óssea.',
      comoIdentificar: 'Cavidade aérea frontal à esquerda do septo intersinusal.',
      reparos: ['Órbita esquerda', 'Fossa craniana anterior'],
      clinica: 'A grande assimetria entre os seios frontais é normal e não deve ser interpretada como patologia. Sua unicidade anatômica é usada em identificação forense por comparação com radiografias antigas.',
      alteracoes: [
        { nome: 'Agenesia ou hipoplasia', achado: 'Seio ausente ou muito pequeno; variante presente em ~5%, sem significado clínico.' },
        { nome: 'Sinusite frontal com complicação intracraniana', achado: 'Opacificação com empiema epidural ou subdural adjacente; emergência neurocirúrgica.' },
      ],
    },
    {
      id: 'osso-frontal',
      nome: 'Osso frontal',
      categoria: 'osso',
      resumo: 'Osso da fronte; forma a parede anterior do crânio e o teto das órbitas.',
      morfologia: 'Osso chato com duas tábuas corticais e díploe entre elas. Forma a escama frontal (fronte), os tetos orbitários e a porção anterior da fossa craniana anterior. Contém os seios frontais.',
      funcao: 'Proteção dos lobos frontais e do conteúdo orbitário. A díploe entre as tábuas absorve energia e contém medula óssea hematopoiética.',
      densidade: 'Cortical > 1000 UH; díploe menos densa, com trabéculas.',
      janela: 'Óssea.',
      comoIdentificar: 'Osso da porção anterior do crânio, presente nos cortes altos e médios, formando a fronte.',
      reparos: ['Órbitas (abaixo)', 'Sutura coronal (posterior, com os parietais)', 'Seios frontais (dentro dele)', 'Etmoide (inferomedial)'],
      clinica: 'A fratura com afundamento é definida quando a tábua interna se desloca além da espessura total do crânio — critério que costuma indicar elevação cirúrgica pelo risco de laceração dural, contusão subjacente e epilepsia pós-traumática. Fraturas abertas com afundamento têm risco infeccioso e indicação cirúrgica mais clara. Vale notar que, na criança, a "fratura em galho verde" e a fratura em crescimento (que alarga com o tempo por herniação de meninges) são particularidades importantes.',
      alteracoes: [
        { nome: 'Fratura com afundamento', achado: 'Fragmento deslocado além da espessura da calota; avaliar contusão subjacente e integridade dural.' },
        { nome: 'Hiperostose frontal interna', achado: 'Espessamento nodular simétrico da tábua interna em mulheres idosas; benigno e sem significado.' },
        { nome: 'Lesão lítica', achado: 'Destruição da díploe; mieloma, metástase, granuloma eosinofílico e cisto epidermoide entram no diferencial.' },
        { nome: 'Doença de Paget', achado: 'Espessamento com aspecto de "algodão" e alargamento da díploe.' },
      ],
    },
    {
      id: 'osso-esfenoide',
      nome: 'Osso esfenoide',
      categoria: 'osso',
      resumo: 'Osso ímpar em forma de morcego no centro da base do crânio; articula-se com todos os outros ossos cranianos.',
      morfologia: 'Formado pelo corpo (que contém o seio esfenoidal e a sela turca), asas menores, asas maiores e processos pterigoides. Contém os principais forames da base: redondo (V2), oval (V3), espinhoso (artéria meníngea média), o canal óptico e a fissura orbitária superior.',
      funcao: 'Chave arquitetônica da base do crânio — é o osso que articula e estabiliza todos os demais. Também abriga a sela turca, onde repousa a hipófise, e delimita passagens para nervos cranianos e vasos.',
      densidade: 'Cortical densa com estrutura complexa.',
      janela: 'Óssea, com cortes finos.',
      comoIdentificar: 'Osso central da base do crânio, com o seio esfenoidal em seu corpo e as asas se estendendo lateralmente como as de um morcego.',
      reparos: ['Sela turca (no corpo)', 'Seio esfenoidal (dentro do corpo)', 'Fissura orbitária superior (entre as asas)', 'Forame oval e espinhoso (na asa maior)', 'Clivo (posterior)'],
      clinica: 'A fratura da asa maior do esfenoide pode lacerar a artéria meníngea média, que corre em um sulco na face interna — é o mecanismo clássico do hematoma epidural temporal, cuja evolução em "intervalo lúcido" é uma das apresentações mais características da neurocirurgia. Já as fraturas que atravessam o canal carotídeo exigem angio-TC para excluir dissecção ou pseudoaneurisma. E o forame espinhoso, por onde a meníngea média entra, é uma referência confiável para localizar o vaso.',
      alteracoes: [
        { nome: 'Fratura com lesão da meníngea média', achado: 'Traço na asa maior cruzando o sulco arterial, com hematoma epidural biconvexo adjacente.' },
        { nome: 'Fratura do canal carotídeo', achado: 'Traço atravessando o canal; indicação de angio-TC para excluir dissecção e pseudoaneurisma.' },
        { nome: 'Displasia da asa do esfenoide', achado: 'Ausência ou hipoplasia da asa maior com herniação do lobo temporal na órbita; marcador de neurofibromatose tipo 1.' },
        { nome: 'Meningioma da asa do esfenoide', achado: 'Massa com base dural, hiperostose e realce intenso.' },
      ],
    },
    {
      id: 'osso-temporal-direito',
      nome: 'Osso temporal direito',
      categoria: 'osso',
      resumo: 'Osso que aloja os órgãos da audição e do equilíbrio; o mais complexo do crânio.',
      morfologia: 'Composto por escama (parte plana lateral), porção petrosa ou rochedo (a mais densa do corpo humano, contendo cóclea, vestíbulo e canais semicirculares), porção mastóidea (com as células aéreas), porção timpânica e processo estiloide. Contém o canal do nervo facial e o canal carotídeo.',
      funcao: 'Proteção do labirinto membranoso e da orelha média; transmissão do som. Sua densidade extrema protege estruturas de dimensões submilimétricas, mas é também a origem do artefato de endurecimento do feixe que atrapalha a leitura da fossa posterior.',
      densidade: 'A cortical do rochedo é o osso mais denso do organismo, ultrapassando 2000 UH; as células mastóideas são aeradas.',
      janela: 'Óssea de altíssima resolução, com cortes submilimétricos e reconstruções dedicadas.',
      comoIdentificar: 'Nos cortes da base, é o osso muito denso e triangular que aponta medialmente, entre a fossa média e a posterior, contendo estruturas aéreas.',
      reparos: ['Conduto auditivo interno (medial)', 'Células mastóideas (posterolaterais)', 'Canal carotídeo (anterior)', 'Articulação temporomandibular (anterolateral)', 'Seio sigmoide (posterior)'],
      clinica: 'A fratura do osso temporal se classifica pelo eixo em relação ao rochedo, e essa classificação prediz o dano funcional. A fratura LONGITUDINAL (80%), paralela ao eixo do rochedo, atravessa a orelha média, disloca a cadeia ossicular e rompe a membrana timpânica, produzindo perda auditiva CONDUTIVA e otorragia; a paralisia facial é rara e geralmente tardia. A fratura TRANSVERSAL (20%), perpendicular ao eixo, atravessa a cápsula ótica e o canal facial, produzindo perda NEUROSSENSORIAL, vertigem e paralisia facial imediata em até 50% dos casos. Uma classificação moderna, mais preditiva, divide as fraturas em "com" e "sem" violação da cápsula ótica.',
      alteracoes: [
        { nome: 'Fratura longitudinal', achado: 'Traço paralelo ao rochedo atravessando a orelha média; luxação ossicular, perda condutiva, otorragia.' },
        { nome: 'Fratura transversal', achado: 'Traço perpendicular atravessando a cápsula ótica e o canal facial; perda neurossensorial, vertigem e paralisia facial imediata.' },
        { nome: 'Colesteatoma', achado: 'Massa de partes moles na orelha média com erosão ossicular e do esporão (scutum); tipicamente no espaço de Prussak.' },
        { nome: 'Otosclerose', achado: 'Foco de desmineralização na janela oval (fissula ante fenestram); perda condutiva progressiva em adulto jovem.' },
        { nome: 'Mastoidite coalescente', achado: 'Opacificação das células com destruição dos septos ósseos; risco de abscesso e trombose de seio sigmoide.' },
      ],
    },
    {
      id: 'osso-temporal-esquerdo',
      nome: 'Osso temporal esquerdo',
      categoria: 'osso',
      resumo: 'Contraparte esquerda; a comparação bilateral é essencial na leitura.',
      morfologia: 'Idêntica ao direito.',
      funcao: 'Audição e equilíbrio.',
      densidade: 'Rochedo extremamente denso.',
      janela: 'Óssea de alta resolução.',
      comoIdentificar: 'Espelho do direito; avaliar simetria de aeração mastóidea e do conduto auditivo interno.',
      reparos: ['Conduto auditivo interno esquerdo', 'Mastoide esquerda', 'Canal carotídeo esquerdo'],
      clinica: 'A leitura do osso temporal é feita necessariamente em comparação: as estruturas são submilimétricas e a assimetria é o que denuncia a doença. Opacificação mastóidea unilateral, alargamento assimétrico do conduto auditivo interno e erosão ossicular só se tornam evidentes quando se olha os dois lados no mesmo corte.',
      alteracoes: [
        { nome: 'Alargamento assimétrico do conduto auditivo interno', achado: 'Sugere schwannoma vestibular; confirmar com ressonância.' },
        { nome: 'Opacificação mastóidea unilateral', achado: 'Mastoidite, otite média crônica ou obstrução; correlacionar com clínica.' },
      ],
    },
    {
      id: 'osso-occipital',
      nome: 'Osso occipital',
      categoria: 'osso',
      resumo: 'Osso posterior e inferior do crânio; contém o forame magno.',
      morfologia: 'Formado pela escama (posterior), pelas partes laterais com os côndilos occipitais (que se articulam com o atlas) e pela porção basilar, que forma o clivo com o esfenoide. O forame magno é sua abertura central. Sua face interna apresenta sulcos para os seios transversos e para a confluência dos seios.',
      funcao: 'Proteção do cerebelo e do tronco encefálico; articulação com a coluna cervical. Os côndilos occipitais transmitem todo o peso da cabeça para o atlas.',
      densidade: 'Cortical densa com díploe.',
      janela: 'Óssea.',
      comoIdentificar: 'Osso posterior do crânio, presente em todos os cortes da fossa posterior; nos cortes baixos, contém o forame magno.',
      reparos: ['Forame magno (central)', 'Côndilos occipitais (laterais ao forame)', 'Clivo (anterior)', 'Protuberância occipital interna e confluência dos seios (posterior)'],
      clinica: 'Fratura de côndilo occipital indica trauma cervical de altíssima energia e pode causar instabilidade craniocervical e lesão de nervos cranianos baixos (IX a XII), que saem pelo forame jugular e pelo canal do hipoglosso adjacentes. Fraturas da escama occipital que cruzam os sulcos dos seios venosos são particularmente perigosas: podem causar trombose de seio ou hematoma epidural da fossa posterior, este último de evolução rápida e catastrófica pelo espaço limitado do compartimento.',
      alteracoes: [
        { nome: 'Fratura de côndilo occipital', achado: 'Traço no côndilo; classificação de Anderson-Montesano orienta a estabilidade; procurar lesão de nervos baixos.' },
        { nome: 'Fratura cruzando sulco de seio venoso', achado: 'Traço sobre o sulco do transverso ou sigmoide; risco de trombose venosa e de hematoma epidural de fossa posterior.' },
        { nome: 'Impressão basilar / invaginação basilar', achado: 'Odontoide projetando-se acima da linha de Chamberlain; pode comprimir o bulbo.' },
      ],
    },
    {
      id: 'osso-parietal-direito',
      nome: 'Osso parietal direito',
      categoria: 'osso',
      resumo: 'Osso chato que forma grande parte da abóbada craniana lateral e superior.',
      morfologia: 'Quadrilátero, com duas tábuas corticais e díploe. Sua face interna apresenta o sulco da artéria meníngea média, que se ramifica como um traçado arboriforme.',
      funcao: 'Proteção dos lobos parietais. A díploe contém medula óssea hematopoiética ativa.',
      densidade: 'Cortical densa com díploe intermediária.',
      janela: 'Óssea.',
      comoIdentificar: 'Nos cortes altos, forma a maior parte da parede lateral e do teto do crânio.',
      reparos: ['Sutura coronal (anterior)', 'Sutura sagital (medial)', 'Sutura lambdóide (posterior)', 'Sutura escamosa (inferior, com o temporal)', 'Sulco da meníngea média (face interna)'],
      clinica: 'A região temporoparietal é o local mais frequente do hematoma epidural, porque ali o osso é fino e a artéria meníngea média corre num sulco imediatamente sob a tábua interna. Uma fratura linear que cruza esse sulco é o achado que antecipa o hematoma. Na TC, o epidural é biconvexo (lenticular), NÃO cruza suturas — porque a dura está aderida a elas — mas pode cruzar a linha média. O subdural é o oposto: em crescente, cruza suturas, mas não cruza a foice.',
      alteracoes: [
        { nome: 'Fratura linear cruzando o sulco da meníngea média', achado: 'Traço parietotemporal; procurar ativamente hematoma epidural.' },
        { nome: 'Hematoma epidural', achado: 'Coleção biconvexa hiperdensa que não cruza suturas; o "sinal do redemoinho" (áreas hipodensas dentro) indica sangramento ativo.' },
        { nome: 'Lesão lítica da díploe', achado: 'Metástase, mieloma, hemangioma (com trabeculado em "raios de sol") ou granuloma eosinofílico.' },
      ],
    },
    {
      id: 'osso-parietal-esquerdo',
      nome: 'Osso parietal esquerdo',
      categoria: 'osso',
      resumo: 'Contraparte esquerda do parietal.',
      morfologia: 'Idêntica ao direito, unido a ele pela sutura sagital.',
      funcao: 'Proteção dos lobos parietais.',
      densidade: 'Cortical densa com díploe.',
      janela: 'Óssea.',
      comoIdentificar: 'Metade esquerda do teto e da parede lateral superior do crânio.',
      reparos: ['Sutura sagital (medial)', 'Sutura coronal', 'Sutura lambdóide'],
      clinica: 'A comparação da espessura e da densidade das duas calotas ajuda a detectar lesões líticas sutis e o afinamento por hiperostose contralateral. Nos cortes mais altos, hematomas subdurais finos junto ao vértice são um ponto cego clássico — é preciso rolar até o último corte para não perdê-los.',
      alteracoes: [
        { nome: 'Hematoma subdural do vértice', achado: 'Coleção fina em crescente junto ao vértice; ponto cego se a série não for percorrida até o fim.' },
        { nome: 'Hemangioma da calota', achado: 'Lesão lítica expansiva com trabeculado radiado ("raios de sol"); benigno.' },
      ],
    },
    {
      id: 'mandibula',
      nome: 'Mandíbula',
      categoria: 'osso',
      resumo: 'Único osso móvel do crânio; articula-se com o temporal na articulação temporomandibular.',
      morfologia: 'Osso em forma de ferradura, com corpo, ângulo, ramo, processo coronoide e côndilo. Contém o canal mandibular, por onde correm o nervo alveolar inferior e seus vasos.',
      funcao: 'Mastigação, fonação e sustentação da arcada dentária inferior. É um anel ósseo — e, como todo anel, tende a fraturar em dois pontos.',
      densidade: 'Cortical densa com canal mandibular visível.',
      janela: 'Óssea.',
      comoIdentificar: 'Nos cortes baixos, é o osso em U que forma o contorno inferior da face; os côndilos aparecem mais acima, articulados ao temporal.',
      reparos: ['Articulação temporomandibular (côndilo)', 'Canal mandibular (com o nervo alveolar inferior)', 'Arcada dentária inferior', 'Músculos masseter e pterigóideos (inserções)'],
      clinica: 'Como estrutura em anel, a mandíbula raramente fratura em um só ponto — encontrar uma fratura obriga a procurar a segunda, frequentemente do lado oposto (por exemplo, fratura de parassínfise à direita com fratura de côndilo à esquerda). A fratura de côndilo é a mais comum e pode passar despercebida; sua consequência tardia é a anquilose e o desvio da abertura bucal. Lesão do nervo alveolar inferior produz parestesia do lábio inferior, achado que se correlaciona com traço atravessando o canal mandibular.',
      alteracoes: [
        { nome: 'Fratura mandibular dupla', achado: 'Dois traços no anel — procurar sempre o segundo depois de encontrar o primeiro.' },
        { nome: 'Fratura de côndilo', achado: 'Traço com deslocamento medial do côndilo; risco de anquilose e má oclusão.' },
        { nome: 'Luxação da ATM', achado: 'Côndilo anterior à eminência articular, com boca travada aberta.' },
        { nome: 'Osteonecrose por bisfosfonato', achado: 'Osso esclerótico com sequestro, fístula e ausência de cicatrização após extração dentária.' },
      ],
    },
    {
      id: 'mastoide-direita',
      nome: 'Mastoide direita',
      categoria: 'osso',
      resumo: 'Processo do osso temporal preenchido por células aéreas comunicantes com a orelha média.',
      morfologia: 'Sistema de células aéreas separadas por finos septos ósseos, comunicando-se com o antro mastóideo e, por ele, com a orelha média através do ádito. O grau de pneumatização varia muito entre indivíduos.',
      funcao: 'Reservatório de ar que amortece variações de pressão na orelha média. A comunicação direta com a caixa timpânica explica por que a otite média se estende à mastoide.',
      densidade: 'Ar (−1000 UH) nas células, com septos ósseos finos hiperdensos.',
      janela: 'Óssea.',
      comoIdentificar: 'Atrás do conduto auditivo, área com aspecto de "favo de mel" ou esponja, com múltiplas cavidades aéreas.',
      reparos: ['Orelha média (comunicação pelo ádito)', 'Seio sigmoide (posteromedial)', 'Fossa craniana média (acima, pelo tegmen)', 'Nervo facial (medialmente)'],
      clinica: 'A opacificação mastóidea isolada não significa mastoidite: é frequente em otite média serosa e em pacientes intubados. O que caracteriza a MASTOIDITE COALESCENTE — a forma cirúrgica — é a destruição dos septos ósseos entre as células, transformando o favo numa cavidade única. As complicações a procurar são o abscesso subperiosteal, a trombose do seio sigmoide, o empiema epidural e o abscesso cerebelar. Cada uma delas muda a conduta radicalmente.',
      alteracoes: [
        { nome: 'Mastoidite coalescente', achado: 'Opacificação com DESTRUIÇÃO dos septos ósseos; forma cirúrgica.' },
        { nome: 'Trombose do seio sigmoide', achado: 'Falha de enchimento no seio adjacente à mastoide opacificada; complicação clássica.' },
        { nome: 'Abscesso de Bezold', achado: 'Extensão da infecção para o pescoço através da ponta da mastoide.' },
        { nome: 'Opacificação simples', achado: 'Sem destruição de septos; otite serosa, intubação, obstrução tubária — não é mastoidite cirúrgica.' },
      ],
    },
    {
      id: 'mastoide-esquerda',
      nome: 'Mastoide esquerda',
      categoria: 'osso',
      resumo: 'Contraparte esquerda do sistema de células mastóideas.',
      morfologia: 'Idêntica à direita; o grau de pneumatização costuma ser simétrico no mesmo indivíduo.',
      funcao: 'Amortecimento de pressão e comunicação com a orelha média.',
      densidade: 'Ar com septos.',
      janela: 'Óssea.',
      comoIdentificar: 'Espelho da direita; comparar aeração e integridade dos septos.',
      reparos: ['Orelha média esquerda', 'Seio sigmoide esquerdo', 'Tegmen mastoideum'],
      clinica: 'A esclerose e a hipopneumatização mastóidea unilateral são marcas de otite média crônica na infância — o osso deixa de pneumatizar normalmente. É um achado retrospectivo que conta a história otológica do paciente.',
      alteracoes: [
        { nome: 'Hipopneumatização com esclerose', achado: 'Mastoide pequena e densa; sequela de otite média crônica na infância.' },
        { nome: 'Colesteatoma com erosão mastóidea', achado: 'Massa de partes moles erodindo septos e a parede do canal facial.' },
      ],
    },
    {
      id: 'conduto-auditivo-interno-direito',
      nome: 'Conduto auditivo interno direito',
      sinonimos: ['meato acústico interno direito'],
      categoria: 'osso',
      resumo: 'Canal ósseo no rochedo por onde passam os nervos facial e vestibulococlear.',
      morfologia: 'Canal de 8–10 mm de comprimento e 4–6 mm de diâmetro, dividido internamente pela crista falciforme. Conduz o nervo facial (VII), o nervo vestibulococlear (VIII) com suas divisões coclear e vestibulares, o nervo intermédio e a artéria labiríntica.',
      funcao: 'Passagem protegida dos nervos da audição, do equilíbrio e da mímica facial, do tronco encefálico até o labirinto e o canal facial.',
      densidade: 'Cavidade preenchida por líquor e nervos; paredes ósseas densas.',
      janela: 'Óssea de alta resolução; a ressonância é o exame para o conteúdo.',
      comoIdentificar: 'Canal que se dirige medialmente a partir do rochedo em direção ao ângulo pontocerebelar. Compare o calibre com o lado oposto.',
      reparos: ['Ângulo pontocerebelar (abertura medial)', 'Cóclea (anterolateral)', 'Vestíbulo e canais semicirculares (posterolateral)', 'Canal do nervo facial (continuação)'],
      clinica: 'O alargamento assimétrico do conduto auditivo interno é o principal sinal indireto de schwannoma vestibular na TC — mas o exame de escolha para o tumor é a ressonância com contraste, que mostra a lesão mesmo quando ela é intracanalicular e não alarga o osso. A regra prática: perda auditiva neurossensorial UNILATERAL e progressiva em adulto exige investigar o ângulo pontocerebelar, e uma TC "normal" não encerra a investigação.',
      alteracoes: [
        { nome: 'Alargamento por schwannoma vestibular', achado: 'Assimetria de calibre com erosão em funil; confirmar com ressonância.' },
        { nome: 'Fratura transversal atravessando o conduto', achado: 'Traço com perda neurossensorial e paralisia facial.' },
        { nome: 'Neurofibromatose tipo 2', achado: 'Schwannomas vestibulares BILATERAIS; achado praticamente diagnóstico da síndrome.' },
      ],
    },
    {
      id: 'conduto-auditivo-interno-esquerdo',
      nome: 'Conduto auditivo interno esquerdo',
      categoria: 'osso',
      resumo: 'Contraparte esquerda; a comparação de calibre é o método de leitura.',
      morfologia: 'Idêntica ao direito.',
      funcao: 'Passagem dos nervos VII e VIII.',
      densidade: 'Cavidade com líquor e nervos.',
      janela: 'Óssea de alta resolução.',
      comoIdentificar: 'Espelho do direito; medir e comparar os dois diâmetros no mesmo corte.',
      reparos: ['Ângulo pontocerebelar esquerdo', 'Cóclea esquerda'],
      clinica: 'Diferença de mais de 2 mm entre os dois condutos é considerada significativa e deve levar à ressonância. Vale lembrar que schwannomas bilaterais definem a neurofibromatose tipo 2, doença autossômica dominante com implicações familiares.',
      alteracoes: [
        { nome: 'Assimetria > 2 mm', achado: 'Indicação de ressonância com contraste para excluir schwannoma.' },
      ],
    },
    {
      id: 'sutura-coronal',
      nome: 'Sutura coronal',
      categoria: 'osso',
      resumo: 'Sutura transversal entre o osso frontal e os dois parietais.',
      morfologia: 'Linha serrilhada que cruza o crânio de uma articulação escamosa à outra, no plano coronal. Suas bordas são interdigitadas e escleróticas.',
      funcao: 'Articulação fibrosa que permite o crescimento do crânio perpendicularmente a si mesma durante a infância e absorve impacto no adulto. Fecha funcionalmente por volta dos 24 anos.',
      densidade: 'Linha de baixa densidade com bordas escleróticas e serrilhadas.',
      janela: 'Óssea.',
      comoIdentificar: 'Nos cortes altos, é a linha serrilhada transversal na porção anterior do crânio, separando o frontal dos parietais. Sempre simétrica.',
      reparos: ['Osso frontal (anterior)', 'Ossos parietais (posteriores)', 'Bregma (encontro com a sutura sagital)'],
      clinica: 'A distinção entre sutura e fratura é uma das habilidades básicas: a sutura é serrilhada, tem bordas escleróticas, ocupa localização anatômica conhecida e é simétrica; a fratura é retilínea ou anguiforme, tem bordas nítidas e não escleróticas, é mais lucente e não tem par contralateral. Na criança, o fechamento precoce da coronal (craniossinostose) produz braquicefalia se bilateral e plagiocefalia anterior se unilateral, com o "sinal do olho de arlequim" na órbita ipsilateral.',
      alteracoes: [
        { nome: 'Craniossinostose coronal', achado: 'Fusão precoce com esclerose da sutura; braquicefalia (bilateral) ou plagiocefalia anterior com olho de arlequim (unilateral).' },
        { nome: 'Diástase de sutura', achado: 'Alargamento > 2 mm; hipertensão intracraniana na criança ou extensão de fratura no trauma.' },
      ],
      armadilhas: ['Sutura metópica persistente (na linha média frontal, presente em ~10% dos adultos) é a pseudofratura mais clássica do crânio.'],
    },
    {
      id: 'sutura-lambdoide',
      nome: 'Sutura lambdóide',
      categoria: 'osso',
      resumo: 'Sutura entre os parietais e o occipital, na porção posterior do crânio.',
      morfologia: 'Linha serrilhada em forma de "lambda" (Λ) invertido. Frequentemente contém ossos wormianos — pequenos ossos supranumerários dentro da sutura.',
      funcao: 'Crescimento e absorção de impacto na região posterior.',
      densidade: 'Linha lucente com bordas serrilhadas.',
      janela: 'Óssea.',
      comoIdentificar: 'Nos cortes altos posteriores, é a linha serrilhada que separa os parietais do occipital, formando um V invertido.',
      reparos: ['Ossos parietais (anteriores)', 'Osso occipital (posterior)', 'Lâmbda (encontro com a sagital)'],
      clinica: 'Ossos wormianos numerosos na sutura lambdóide não são achado banal: quando abundantes, associam-se a osteogênese imperfeita, disostose cleidocraniana, hipotireoidismo e picnodisostose. A regra mnemônica clássica em inglês, "PORKCHOPS", lista essas causas. Isoladamente, porém, um ou dois ossos wormianos são variação normal.',
      alteracoes: [
        { nome: 'Ossos wormianos múltiplos', achado: 'Numerosos ossículos na sutura; investigar osteogênese imperfeita e disostose cleidocraniana.' },
        { nome: 'Craniossinostose lambdóide', achado: 'Fusão precoce com plagiocefalia posterior; rara e deve ser diferenciada da plagiocefalia posicional.' },
      ],
    },
    {
      id: 'sutura-sagital',
      nome: 'Sutura sagital',
      categoria: 'osso',
      resumo: 'Sutura da linha média entre os dois ossos parietais.',
      morfologia: 'Linha serrilhada mediana que vai do bregma ao lambda. É a sutura mais longa da abóbada.',
      funcao: 'Permite o crescimento transversal do crânio na infância. Sua fusão precoce impede o crescimento lateral, e o crânio compensa crescendo no sentido anteroposterior.',
      densidade: 'Linha lucente mediana com bordas escleróticas.',
      janela: 'Óssea.',
      comoIdentificar: 'Nos cortes mais altos, é a linha serrilhada exatamente na linha média, separando os dois parietais.',
      reparos: ['Ossos parietais (de cada lado)', 'Bregma (anterior)', 'Lâmbda (posterior)', 'Seio sagital superior (imediatamente abaixo, na face interna)'],
      clinica: 'A craniossinostose sagital é a mais comum de todas (cerca de 50% dos casos) e produz a escafocefalia: crânio longo e estreito, "em barco". Além disso, imediatamente sob a sutura corre o seio sagital superior — uma fratura que a cruze pode lacerar o seio e produzir hematoma epidural venoso ou trombose, complicações que devem ser ativamente procuradas.',
      alteracoes: [
        { nome: 'Craniossinostose sagital (escafocefalia)', achado: 'Fusão precoce com crânio alongado no eixo anteroposterior e estreito lateralmente; a mais comum das craniossinostoses.' },
        { nome: 'Fratura cruzando a sutura sagital', achado: 'Risco de lesão do seio sagital superior; procurar hematoma epidural venoso e trombose.' },
      ],
    },
  ],
  quiz: [
    {
      pergunta: 'Como diferenciar uma sutura craniana de uma fratura na TC?',
      alternativas: [
        'Pela densidade da linha',
        'A sutura é serrilhada, com bordas escleróticas, em localização anatômica conhecida e simétrica; a fratura é retilínea, de bordas nítidas e sem par contralateral',
        'Pela espessura',
        'Suturas só aparecem em crianças',
      ],
      correta: 1,
      explicacao: 'Serrilhamento, esclerose das bordas, localização típica e simetria definem a sutura. A fratura é mais lucente, retilínea ou anguiforme, com bordas nítidas e sem correspondente do outro lado.',
    },
    {
      pergunta: 'Numa fratura do seio frontal, qual achado muda a conduta para cirúrgica?',
      alternativas: [
        'Afundamento da parede anterior',
        'Envolvimento da parede POSTERIOR, com risco de fístula liquórica e meningite',
        'Nível hidroaéreo no seio',
        'Enfisema subcutâneo',
      ],
      correta: 1,
      explicacao: 'A parede posterior separa o seio da dura-máter e do lobo frontal. Seu comprometimento cria comunicação intracraniana, com risco de fístula liquórica, pneumoencéfalo, meningite e abscesso — enquanto a fratura da parede anterior isolada é sobretudo um problema estético.',
    },
    {
      pergunta: 'Uma fratura TRANSVERSAL do osso temporal caracteristicamente causa:',
      alternativas: [
        'Perda auditiva condutiva e otorragia',
        'Perda auditiva neurossensorial, vertigem e paralisia facial imediata',
        'Apenas dor local',
        'Rinorreia liquórica isolada',
      ],
      correta: 1,
      explicacao: 'A fratura transversal cruza a cápsula ótica e o canal facial, danificando cóclea, vestíbulo e nervo facial. A longitudinal, mais comum, atravessa a orelha média e produz perda condutiva por lesão ossicular, com otorragia.',
    },
    {
      pergunta: 'Um hematoma epidural na região temporoparietal decorre tipicamente da lesão de:',
      alternativas: ['Veias-ponte', 'Artéria meníngea média', 'Seio sagital superior', 'Artéria cerebral média'],
      correta: 1,
      explicacao: 'A artéria meníngea média corre num sulco da face interna do osso, onde a calota é fina. Uma fratura que cruze esse sulco a lacera. O epidural resultante é biconvexo e não cruza suturas; o subdural, de veias-ponte, é em crescente e cruza suturas.',
    },
    {
      pergunta: 'Nível hidroaéreo no seio esfenoidal em politraumatizado deve ser interpretado como:',
      alternativas: [
        'Sinusite aguda casual',
        'Sinal indireto de fratura da base do crânio',
        'Artefato de posicionamento',
        'Achado sem significado',
      ],
      correta: 1,
      explicacao: 'Sangue no seio esfenoidal em contexto de trauma indica comunicação com uma fratura de base, mesmo quando o traço não é imediatamente visível. Obriga a procurar a fratura com cortes finos e reconstruções, e a avaliar o canal carotídeo.',
    },
  ],
}
