import type { SubsecaoTC } from '../tipos'

export const toraxPartesMolesOssos: SubsecaoTC = {
  id: 'partes-moles-e-ossos',
  titulo: 'Partes moles e ossos do tórax',
  subtitulo: 'Arcabouço ósseo, cintura escapular, mamas, tireoide e a transição toracoabdominal',
  secaoId: 'torax',
  pasta: '/TC_TORAX/TC_TORAX_PARTES_MOLES_E_OSSOS',
  ext: 'png',
  totalCortes: 45,
  orientacao: 'cranio-caudal',
  icone: 'bone',
  cor: 'ambar',
  janelaPadrao: 'ossea',
  protocolo:
    'A mesma aquisição da TC de tórax serve para osso e partes moles — o que muda é a reconstrução. Para osso, reconstrói-se com filtro de alta frequência ("bone kernel") e lê-se em janela óssea (WW 2000 / WL 400); para partes moles, filtro suave e janela mediastinal. Em trauma, reconstruções coronal e sagital e, quando possível, volumétricas 3D são indispensáveis: fraturas de arcos costais em plano axial passam despercebidas porque o traço é perpendicular ao corte.',
  introducao:
    'Esta é a seção que quase todo mundo pula — e é justamente onde estão os achados que mudam conduta no pronto-socorro. Ossos e partes moles do tórax formam um invólucro que a TC atravessa em fatias, e o desafio é mental: uma costela é uma estrutura longa e curva, e o corte axial mostra apenas um pedacinho dela de cada vez. Reconhecer que os "pontos brancos" ao redor do pulmão são cortes transversais de costelas diferentes, e que essas costelas se ordenam de cima para baixo à medida que você rola a série, é o salto conceitual que transforma a leitura. Este é também o único conjunto do manual em que a janela é decisiva de forma binária: em janela mediastinal, uma fratura sem desvio simplesmente não existe na imagem; em janela óssea, ela salta aos olhos. Por fim, os cortes mais baixos desta série já mostram fígado, baço, estômago e pilares diafragmáticos — a transição toracoabdominal, região em que a TC de tórax vira TC de abdome e onde achados abdominais inesperados são encontrados com frequência.',
  roteiro: [
    { passo: '1. Troque para janela óssea', detalhe: 'Nada de esqueleto é confiável em janela de partes moles. Fratura sem desvio é invisível fora da janela óssea.' },
    { passo: '2. Conte as costelas de cima para baixo', detalhe: 'A primeira costela é a mais alta e curta, articulada com o manúbrio. A partir dela, conte descendo — a numeração é o que permite localizar a fratura.' },
    { passo: '3. Percorra o esterno', detalhe: 'Manúbrio, corpo e apêndice xifoide, na linha média anterior. Fratura de esterno indica trauma de alta energia e obriga a procurar lesão cardíaca e aórtica.' },
    { passo: '4. Avalie a cintura escapular', detalhe: 'Clavícula, escápula e úmero proximal. Fratura de escápula também é marcador de alta energia.' },
    { passo: '5. Volte à janela de partes moles', detalhe: 'Agora avalie tireoide, mamas, musculatura da parede e planos de gordura. Enfisema subcutâneo e hematomas moram aqui.' },
    { passo: '6. Termine na transição toracoabdominal', detalhe: 'Nos últimos cortes, identifique fígado, baço, estômago e os pilares diafragmáticos — e não deixe de olhá-los só porque "é uma TC de tórax".' },
  ],
  perolas: [
    'Fratura da 1ª ou 2ª costela = trauma de altíssima energia. Procure lesão de vasos subclávios, plexo braquial e aorta.',
    'Fratura das últimas costelas (9ª a 12ª) = procure lesão de fígado (à direita), baço (à esquerda) e rins.',
    'Três ou mais costelas consecutivas fraturadas em dois pontos cada = tórax instável (flail chest), com risco de insuficiência respiratória.',
    'A tireoide é naturalmente hiperdensa (70–100 UH) sem contraste, por causa do iodo — não confunda com contraste ou calcificação.',
    'Pilares diafragmáticos são bandas verticais que descem à frente da coluna; iniciantes os confundem com linfonodos retrocrurais ou com a aorta.',
  ],
  estruturas: [
    {
      id: 'tireoide',
      nome: 'Tireoide',
      categoria: 'glandula',
      resumo: 'Glândula endócrina em forma de borboleta que abraça a traqueia na base do pescoço.',
      morfologia: 'Dois lobos laterais unidos por um istmo que cruza à frente do 2º ao 4º anel traqueal; cada lobo mede cerca de 4–6 cm de altura e 1,5–2 cm de espessura. Em 40% das pessoas há um lobo piramidal que sobe do istmo. Fica encapsulada, aderida à traqueia pelo ligamento de Berry — motivo pelo qual sobe com a deglutição.',
      funcao: 'Produz T3 e T4, que regulam metabolismo basal, termogênese, desenvolvimento neurológico e sensibilidade adrenérgica. Concentra iodo ativamente pelo simportador sódio-iodeto — e é justamente esse iodo acumulado que a torna espontaneamente densa na TC.',
      densidade: '70–100 UH SEM contraste (bem acima das partes moles, que ficam em 40–60 UH), pelo conteúdo de iodo. Realça intensa e homogeneamente, chegando a 150–200 UH. Um nódulo é sempre HIPOdenso em relação ao parênquima normal.',
      janela: 'Mediastinal / partes moles.',
      comoIdentificar: 'Nos primeiros cortes da série, é o tecido claramente mais BRANCO ao redor da traqueia, na base do pescoço. Aquele "colar" hiperdenso abraçando a traqueia é a tireoide — nenhuma outra estrutura da região tem essa densidade espontânea.',
      reparos: ['Traqueia (envolvida pelo istmo e pelos lobos)', 'Artérias carótidas comuns (posterolaterais)', 'Veias jugulares internas (laterais)', 'Esôfago (posterior, geralmente à esquerda)'],
      clinica: 'O grande achado torácico é o bócio mergulhante: extensão da tireoide para dentro do mediastino superior, que comprime e desvia a traqueia. Na TC, ele é reconhecido pela continuidade com a glândula cervical e pela densidade elevada sem contraste. Uma advertência prática importante: administrar contraste iodado a um paciente com nódulo tireoidiano autônomo pode desencadear tireotoxicose (fenômeno de Jod-Basedow) e também bloqueia a captação de iodo radioativo por semanas, atrapalhando cintilografia e tratamento.',
      alteracoes: [
        { nome: 'Bócio multinodular mergulhante', achado: 'Glândula aumentada, heterogênea, com nódulos hipodensos e calcificações grosseiras, estendendo-se ao mediastino superior e desviando a traqueia.' },
        { nome: 'Nódulo tireoidiano', achado: 'Área hipodensa em relação ao parênquima normal; a TC não caracteriza malignidade — o exame de escolha é a ultrassonografia.' },
        { nome: 'Carcinoma de tireoide', achado: 'Massa infiltrativa com perda do plano de clivagem, microcalcificações e linfonodomegalia cervical; invasão traqueal muda a cirurgia.' },
        { nome: 'Tireoidite', achado: 'Glândula aumentada, difusamente hipodensa e heterogênea.' },
        { nome: 'Agenesia de lobo / tireoide ectópica', achado: 'Ausência de um lobo ou tecido tireoidiano fora do leito (lingual, mediastinal).' },
      ],
      armadilhas: ['A densidade alta espontânea da tireoide é regularmente confundida com contraste residual ou com calcificação por quem não conhece o achado.'],
      medidas: [{ rotulo: 'Densidade sem contraste', valor: '70–100 UH' }, { rotulo: 'Espessura do istmo', valor: '≤ 4 mm' }],
    },
    {
      id: 'clavicula',
      nome: 'Clavícula',
      categoria: 'osso',
      resumo: 'Osso longo em "S" que liga o esterno à escápula, único elo ósseo entre o membro superior e o esqueleto axial.',
      morfologia: 'Curvatura em "S" itálico, com convexidade anterior medialmente e posterior lateralmente. Articula-se com o manúbrio (articulação esternoclavicular, a única verdadeira articulação entre membro superior e tronco) e com o acrômio. É o primeiro osso do corpo a ossificar e o último a fechar a placa epifisária (aos 25 anos).',
      funcao: 'Funciona como escora que mantém o ombro afastado do tórax, permitindo a amplitude do membro superior. Também protege o plexo braquial e os vasos subclávios, que passam logo abaixo dela.',
      densidade: 'Cortical > 700 UH; medular 100–300 UH com gordura.',
      janela: 'Óssea, obrigatoriamente.',
      comoIdentificar: 'Nos cortes mais altos da série, é o osso alongado e curvo que atravessa a região anterior, da linha média (junto ao manúbrio) para fora, em direção ao ombro. Por ser curva, aparece em vários cortes seguidos com formatos diferentes.',
      reparos: ['Manúbrio esternal (medialmente)', 'Acrômio da escápula (lateralmente)', 'Vasos subclávios e plexo braquial (imediatamente abaixo)', '1ª costela (abaixo)'],
      clinica: 'A fratura de clavícula é uma das mais comuns do corpo, tipicamente no terço médio. O risco relevante não é a fratura em si, mas o que está embaixo: fragmentos deslocados podem lesar a artéria e a veia subclávias e o plexo braquial. Na TC, é obrigatório checar esses elementos quando há desvio importante. A luxação esternoclavicular posterior é rara mas grave, podendo comprimir traqueia e grandes vasos — e é praticamente indiagnosticável sem TC.',
      alteracoes: [
        { nome: 'Fratura do terço médio', achado: 'Traço no ponto de transição das curvaturas, com desvio superior do fragmento medial (tracionado pelo esternocleidomastóideo).' },
        { nome: 'Luxação esternoclavicular posterior', achado: 'Extremidade medial deslocada para trás do manúbrio, comprimindo estruturas mediastinais. Emergência.' },
        { nome: 'Lesão lítica/metastática', achado: 'Destruição cortical com massa de partes moles; mieloma e metástases são as causas usuais.' },
        { nome: 'Osteíte condensante', achado: 'Esclerose da extremidade medial em mulheres, benigna e sem erosão.' },
      ],
    },
    {
      id: 'umero',
      nome: 'Úmero',
      categoria: 'osso',
      resumo: 'Osso do braço; sua extremidade proximal aparece nos cortes altos da TC de tórax.',
      morfologia: 'Cabeça esférica que se articula com a glenoide da escápula, seguida do colo anatômico, dos tubérculos maior e menor (separados pelo sulco intertubercular, por onde corre o tendão da cabeça longa do bíceps) e do colo cirúrgico.',
      funcao: 'Sustentação e mobilidade do membro superior. A articulação glenoumeral troca estabilidade por amplitude — é a mais móvel e a mais luxável do corpo.',
      densidade: 'Cortical densa, medular gordurosa.',
      janela: 'Óssea.',
      comoIdentificar: 'Nos primeiros cortes, é a estrutura óssea arredondada e volumosa nas extremidades laterais da imagem, fora da caixa torácica, articulada com a escápula.',
      reparos: ['Glenoide da escápula (medialmente)', 'Acrômio (acima)', 'Parede torácica lateral'],
      clinica: 'Fraturas do colo cirúrgico do úmero são frequentes em idosos após queda da própria altura e podem lesar o nervo axilar. Em TC de tórax feita por outro motivo, uma lesão lítica no úmero proximal é um achado incidental relevante — é sítio comum de metástase e de mieloma.',
      alteracoes: [
        { nome: 'Fratura do colo cirúrgico', achado: 'Traço transversal abaixo dos tubérculos, com angulação; classificação de Neer conta os fragmentos.' },
        { nome: 'Luxação glenoumeral anterior', achado: 'Cabeça deslocada anteroinferiormente; procurar lesão de Hill-Sachs (impactação posterolateral da cabeça) e de Bankart (borda glenoidal).' },
        { nome: 'Lesão lítica', achado: 'Área de destruição óssea; o úmero proximal é sítio clássico de metástase, mieloma e cisto ósseo simples.' },
      ],
    },
    {
      id: 'escapula',
      nome: 'Escápula',
      categoria: 'osso',
      resumo: 'Osso triangular e plano que desliza sobre a parede torácica posterior, conectando o úmero ao tronco.',
      morfologia: 'Lâmina triangular com espinha proeminente na face posterior, que termina no acrômio. Tem processo coracoide anteriormente e cavidade glenoidal lateralmente. Não se articula diretamente com a coluna — flutua sobre o gradil costal, presa apenas por músculos.',
      funcao: 'Base móvel do ombro: sua rotação acompanha a elevação do braço na proporção de 2:1 (ritmo escapuloumeral). Serve de inserção a 17 músculos.',
      densidade: 'Cortical fina com centro medular; a lâmina é tão fina que pode parecer descontínua no corte axial.',
      janela: 'Óssea.',
      comoIdentificar: 'Nos cortes médios, é a lâmina óssea fina e alongada situada POSTERIORMENTE às costelas, deslizando sobre elas. Ela é o osso "de fora" da caixa torácica, atrás.',
      reparos: ['Costelas posteriores (a escápula desliza sobre elas)', 'Úmero (articulação glenoumeral)', 'Músculos do manguito rotador'],
      clinica: 'A escápula é protegida por musculatura espessa; fraturá-la exige energia muito alta. Por isso, fratura de escápula é um marcador de gravidade: obriga a procurar lesão pulmonar, de arcos costais, de plexo braquial e de aorta. Na TC axial, a lâmina fina pode dar falsa impressão de descontinuidade — só se afirma fratura confirmando em reconstruções.',
      alteracoes: [
        { nome: 'Fratura de corpo escapular', achado: 'Traço na lâmina, frequentemente com hematoma adjacente; marcador de trauma de alta energia.' },
        { nome: 'Fratura de glenoide', achado: 'Traço articular; o degrau articular determina a indicação cirúrgica.' },
        { nome: 'Escápula alada', achado: 'Afastamento da escápula da parede torácica por lesão do nervo torácico longo (serrátil anterior).' },
      ],
      armadilhas: ['A lâmina escapular é tão fina que o volume parcial simula fratura — sempre confirmar em outro plano.'],
    },
    {
      id: 'vertebra-cervical-c7',
      nome: 'Vértebra cervical C7',
      sinonimos: ['vértebra proeminente'],
      categoria: 'osso',
      resumo: 'Última vértebra cervical, com processo espinhoso longo e não bifurcado — o mais palpável da nuca.',
      morfologia: 'Corpo pequeno, forames transversos que geralmente NÃO contêm a artéria vertebral (ela costuma entrar em C6), e processo espinhoso longo, horizontal e único.',
      funcao: 'Transição entre a coluna cervical móvel e a torácica rígida. Zonas de transição concentram estresse mecânico e, por isso, fraturas.',
      densidade: 'Osso cortical e trabecular normais.',
      janela: 'Óssea.',
      comoIdentificar: 'É a última vértebra antes da primeira que se articula com uma costela. Se você vê uma costela articulada ao corpo vertebral, já está em T1 — o corte imediatamente acima é C7.',
      reparos: ['1ª costela (articula-se com T1, logo abaixo)', 'Traqueia (anterior)', 'Ápices pulmonares (laterais)'],
      clinica: 'A junção cervicotorácica é um ponto cego clássico da radiografia — os ombros escondem C7-T1. Muitas fraturas nessa altura só aparecem na TC, o que justifica estender a TC de coluna cervical até T1 em todo trauma. Costela cervical (em C7) é a causa óssea mais comum de síndrome do desfiladeiro torácico.',
      alteracoes: [
        { nome: 'Fratura da junção cervicotorácica', achado: 'Traço em C7-T1, muitas vezes invisível na radiografia; sempre estender a TC até T1.' },
        { nome: 'Costela cervical', achado: 'Costela extra articulada em C7, presente em ~0,5% da população; comprime plexo braquial e artéria subclávia.' },
        { nome: 'Lesão metastática', achado: 'Destruição do corpo com colapso; procurar componente epidural comprimindo a medula.' },
      ],
    },
    {
      id: 'vertebra-toracica-t1',
      nome: 'Vértebra torácica T1',
      categoria: 'osso',
      resumo: 'Primeira vértebra torácica; primeira a articular-se com uma costela.',
      morfologia: 'Corpo com face articular costal completa para a 1ª costela e uma hemifaceta inferior para a 2ª. Processo espinhoso longo, quase tão proeminente quanto o de C7.',
      funcao: 'Início da caixa torácica rígida; ancora a primeira costela e, com ela, o desfiladeiro torácico superior.',
      densidade: 'Normal.',
      janela: 'Óssea.',
      comoIdentificar: 'É a primeira vértebra, descendo, que tem uma costela articulada. Encontrar T1 é o passo obrigatório para numerar corretamente todas as costelas e vértebras abaixo.',
      reparos: ['1ª costela', 'Ápices pulmonares', 'Traqueia e esôfago (anteriores)'],
      clinica: 'A contagem vertebral a partir de T1 é o que permite localizar corretamente uma fratura ou uma metástase — errar em um nível é errar o nível operado. Em tumores do sulco superior (Pancoast), a invasão do corpo de T1 e do forame neural define irressecabilidade.',
      alteracoes: [
        { nome: 'Invasão por tumor de Pancoast', achado: 'Destruição do corpo vertebral e extensão ao forame neural; T4 no estadiamento.' },
        { nome: 'Fratura por compressão', achado: 'Perda de altura do corpo com linha de condensação; avaliar recuo do muro posterior.' },
      ],
    },
    {
      id: 'primeiro-arco-costal',
      nome: '1º arco costal',
      categoria: 'osso',
      resumo: 'Costela mais alta, curta, larga e horizontalizada; forma o assoalho do desfiladeiro torácico.',
      morfologia: 'A mais curta e mais curva das costelas. Achatada de cima para baixo (e não lateralmente, como as demais). Apresenta o tubérculo do escaleno anterior, que separa os sulcos da veia subclávia (à frente) e da artéria subclávia (atrás). Articula-se apenas com T1.',
      funcao: 'Além da proteção, é a peça que define o desfiladeiro torácico: o espaço entre a primeira costela e a clavícula, por onde passam plexo braquial e vasos subclávios.',
      densidade: 'Cortical densa; frequentemente calcifica a cartilagem costal precocemente.',
      janela: 'Óssea.',
      comoIdentificar: 'É a primeira estrutura óssea em forma de arco que aparece descendo dos ápices, envolvendo o ápice pulmonar. Como é quase horizontal, ela aparece quase inteira num único corte — as costelas seguintes, mais oblíquas, aparecem em pedaços.',
      reparos: ['Clavícula (acima)', 'Vasos subclávios (correm sobre ela)', 'T1 (articulação posterior)', 'Ápice pulmonar (abaixo)'],
      clinica: 'Fratura da primeira costela é sinal de trauma de energia extrema, porque ela é curta, espessa e protegida pela clavícula e pela musculatura do pescoço. Quando presente, a probabilidade de lesão de grandes vasos, plexo braquial e aorta sobe muito — é um dos poucos achados ósseos que, sozinho, justifica angio-TC.',
      alteracoes: [
        { nome: 'Fratura da 1ª costela', achado: 'Marcador de alta energia; obriga a procurar lesão subclávia, do plexo e aórtica.' },
        { nome: 'Costela cervical / banda fibrosa', achado: 'Estrutura supranumerária que estreita o desfiladeiro; causa de síndrome neurogênica ou vascular do desfiladeiro torácico.' },
        { nome: 'Síndrome de Paget-Schroetter', achado: 'Trombose da veia subclávia por compressão no desfiladeiro costoclavicular, em atletas de arremesso.' },
      ],
    },
    {
      id: 'segundo-arco-costal',
      nome: '2º arco costal',
      categoria: 'osso',
      resumo: 'Costela que se articula com o ângulo esternal (ângulo de Louis), referência de contagem.',
      morfologia: 'Mais longa e mais fina que a primeira, com curvatura mais típica. Articula-se anteriormente com o ângulo esternal, ponto onde o manúbrio encontra o corpo do esterno.',
      funcao: 'Estrutura da caixa torácica e referência anatômica de superfície: o ângulo esternal, palpável, corresponde à segunda costela, à carina, ao arco aórtico e ao disco T4-T5.',
      densidade: 'Normal.',
      janela: 'Óssea.',
      comoIdentificar: 'Descendo da primeira costela, é o segundo arco. Anteriormente, ela chega ao esterno exatamente no degrau entre manúbrio e corpo esternal — esse degrau é visível na TC e serve de conferência da contagem.',
      reparos: ['Ângulo esternal (articulação anterior)', 'T2 (articulação posterior)', 'Carina (mesmo nível transversal)'],
      clinica: 'Fratura da 2ª costela partilha o significado de alta energia com a 1ª. O ângulo esternal é o marco que, num único corte, alinha carina, arco aórtico, bifurcação da traqueia e o disco T4-T5 — útil para conferir a numeração e localizar lesões.',
      alteracoes: [
        { nome: 'Fratura', achado: 'Trauma de alta energia; avaliar mediastino.' },
        { nome: 'Metástase costal', achado: 'Lesão lítica com destruição cortical e massa de partes moles associada.' },
      ],
    },
    {
      id: 'terceiro-arco-costal',
      nome: '3º arco costal',
      categoria: 'osso',
      resumo: 'Costela verdadeira, com cartilagem própria articulada ao esterno.',
      morfologia: 'Arco típico, com cabeça, colo, tubérculo, ângulo e corpo, e sulco costal na borda inferior por onde correm veia, artéria e nervo intercostais (de cima para baixo — VAN).',
      funcao: 'Proteção e mecânica ventilatória: na inspiração, as costelas superiores fazem o movimento em "alça de balde", aumentando o diâmetro anteroposterior do tórax.',
      densidade: 'Normal; a cartilagem costal calcifica progressivamente com a idade.',
      janela: 'Óssea.',
      comoIdentificar: 'Continue a contagem descendo. Uma dica prática: por serem oblíquas, as costelas aparecem em cada corte em dois pedaços de cada lado — um anterior e um posterior. O pedaço posterior de uma costela está no mesmo corte do pedaço anterior de outra, mais alta.',
      reparos: ['Esterno (via cartilagem)', 'Vértebra correspondente (articulação posterior)', 'Feixe intercostal na borda inferior'],
      clinica: 'O feixe vasculonervoso corre no sulco da borda INFERIOR de cada costela — por isso toracocentese e drenagem torácica são feitas rente à borda SUPERIOR da costela de baixo. Essa é uma das aplicações mais diretas de anatomia em procedimento à beira do leito.',
      alteracoes: [
        { nome: 'Fratura simples', achado: 'Traço cortical com ou sem desvio; procurar pneumotórax e contusão pulmonar subjacentes.' },
        { nome: 'Calcificação de cartilagem costal', achado: 'Densidade alta na porção anterior; achado fisiológico com a idade, frequentemente confundido com nódulo pulmonar na radiografia.' },
      ],
    },
    {
      id: 'quarto-arco-costal',
      nome: '4º arco costal',
      categoria: 'osso',
      resumo: 'Costela verdadeira no nível médio do tórax.',
      morfologia: 'Arco costal completo; anteriormente sua cartilagem chega ao corpo esternal.',
      funcao: 'Mecânica ventilatória e proteção; o 4º espaço intercostal na linha axilar média é o local padrão de inserção do dreno torácico.',
      densidade: 'Normal.',
      janela: 'Óssea.',
      comoIdentificar: 'Contagem sequencial a partir da 1ª. No corte axial, a costela mais anterior do lado é sempre a mais alta em numeração.',
      reparos: ['Corpo do esterno', 'Mamilo (referência de superfície próxima ao 4º espaço)', 'T4 (articulação posterior)'],
      clinica: 'O "triângulo de segurança" para dreno de tórax é delimitado pela borda lateral do peitoral maior, pela borda lateral do grande dorsal e por uma linha horizontal no nível do mamilo — na prática, o 4º ou 5º espaço intercostal na linha axilar média. A TC ajuda a confirmar a posição do dreno e a detectar posicionamento intrafissural ou intraparenquimatoso.',
      alteracoes: [
        { nome: 'Fratura com hemotórax', achado: 'Traço costal com coleção pleural hiperdensa (> 35 UH), indicando sangue.' },
        { nome: 'Dreno mal posicionado', achado: 'Dreno intrafissural ou dentro do parênquima; a TC é o exame que resolve a dúvida.' },
      ],
    },
    {
      id: 'quinto-arco-costal',
      nome: '5º arco costal',
      categoria: 'osso',
      resumo: 'Costela verdadeira; nível de referência para procedimentos pleurais.',
      morfologia: 'Arco completo com cartilagem articulada ao esterno.',
      funcao: 'Proteção e ventilação.',
      densidade: 'Normal.',
      janela: 'Óssea.',
      comoIdentificar: 'Contagem sequencial. Neste nível, o coração já domina o mediastino e o lobo médio aparece à direita.',
      reparos: ['Corpo do esterno', 'Coração (medialmente)', 'T5'],
      clinica: 'Fraturas de costelas médias (4ª a 9ª) são as mais comuns em trauma fechado; costumam ser tratadas com analgesia, mas três ou mais costelas consecutivas fraturadas em dois pontos configuram tórax instável, com movimento paradoxal e indicação de suporte ventilatório ou fixação cirúrgica.',
      alteracoes: [
        { nome: 'Tórax instável (flail chest)', achado: 'Fraturas duplas em três ou mais costelas consecutivas, com segmento livre; associa-se a contusão pulmonar subjacente.' },
        { nome: 'Contusão pulmonar', achado: 'Opacidade em vidro fosco/consolidação não segmentar, subjacente às costelas fraturadas, que aparece nas primeiras horas.' },
      ],
    },
    {
      id: 'sexto-arco-costal',
      nome: '6º arco costal',
      categoria: 'osso',
      resumo: 'Última costela verdadeira em muitos indivíduos, com cartilagem própria ao esterno.',
      morfologia: 'Arco completo; a partir daqui as cartilagens começam a se fundir entre si antes de alcançar o esterno.',
      funcao: 'Ventilação e proteção; nas costelas inferiores, o movimento é em "alça de bomba", aumentando o diâmetro transverso.',
      densidade: 'Normal.',
      janela: 'Óssea.',
      comoIdentificar: 'Contagem sequencial; neste nível o diafragma já se aproxima nos cortes mais baixos.',
      reparos: ['Rebordo costal', 'Diafragma', 'T6'],
      clinica: 'Fraturas neste nível já se aproximam do diafragma e das vísceras abdominais superiores — vale checar fígado e baço.',
      alteracoes: [
        { nome: 'Fratura com lesão diafragmática', achado: 'Descontinuidade do diafragma com herniação de conteúdo abdominal ("sinal do colar" quando a víscera se estrangula no defeito).' },
      ],
    },
    {
      id: 'setimo-arco-costal',
      nome: '7º arco costal',
      categoria: 'osso',
      resumo: 'Última costela cuja cartilagem alcança diretamente o esterno na maioria das pessoas.',
      morfologia: 'Arco longo, com cartilagem extensa que forma o rebordo costal junto com as das costelas 8 a 10.',
      funcao: 'Sustenta o rebordo costal, referência de superfície para o exame do abdome superior e para a palpação do fígado e do baço.',
      densidade: 'Normal; cartilagem frequentemente calcificada em adultos.',
      janela: 'Óssea.',
      comoIdentificar: 'Nos cortes baixos da série, é o arco que já se encontra ao nível do fígado e do estômago. A partir daqui, cada corte mostra tanto tórax quanto abdome.',
      reparos: ['Apêndice xifoide (medialmente, no mesmo nível)', 'Fígado e baço (abaixo do diafragma)', 'Rebordo costal'],
      clinica: 'Costelas inferiores fraturadas são bandeira vermelha para lesão de vísceras sólidas: à direita, fígado; à esquerda, baço; posteriormente, rins. Numa TC de trauma, encontrar fratura da 7ª à 12ª costela obriga a examinar essas vísceras com atenção redobrada.',
      alteracoes: [
        { nome: 'Fratura com lesão esplênica', achado: 'Fratura de costelas inferiores esquerdas com laceração esplênica, hematoma perisplênico e líquido livre.' },
        { nome: 'Costocondrite (síndrome de Tietze)', achado: 'Espessamento e aumento de partes moles na junção costocondral; achado sutil, muitas vezes normal na TC.' },
      ],
    },
    {
      id: 'esterno',
      nome: 'Esterno',
      categoria: 'osso',
      resumo: 'Osso chato da parede torácica anterior, formado por manúbrio, corpo e apêndice xifoide.',
      morfologia: 'O manúbrio articula-se com clavículas e as duas primeiras costelas; o corpo recebe as cartilagens da 3ª à 7ª; o ângulo esternal marca a junção manúbrio-corpo. Rico em medula óssea vermelha por toda a vida adulta — motivo de ser sítio de punção medular e alvo de infiltração hematológica.',
      funcao: 'Fecha anteriormente a caixa torácica e transmite as forças da respiração; protege coração e grandes vasos.',
      densidade: 'Cortical densa com medular relativamente hipodensa e gordurosa.',
      janela: 'Óssea; sagital é o plano ideal para ver fraturas transversais.',
      comoIdentificar: 'Estrutura óssea na linha média anterior, imediatamente à frente do mediastino, presente em quase todos os cortes torácicos.',
      reparos: ['Clavículas e 1ª costela (manúbrio)', 'Ângulo esternal (junção manúbrio-corpo)', 'Coração (posterior)', 'Timo/gordura tímica (posterior, em jovens)'],
      clinica: 'A fratura de esterno tem duas consequências: indica trauma frontal de alta energia (típico de cinto de segurança) e obriga a procurar contusão miocárdica, lesão aórtica e fratura vertebral torácica associada. Como o traço costuma ser transversal, o corte axial pode passar batido — o plano sagital é o que faz o diagnóstico. Após esternotomia, a TC avalia deiscência e mediastinite.',
      alteracoes: [
        { nome: 'Fratura transversal', achado: 'Traço horizontal com degrau; melhor visto em reconstrução sagital. Procurar hematoma retroesternal.' },
        { nome: 'Mediastinite pós-esternotomia', achado: 'Deiscência dos fios de aço, coleção retroesternal com gás e realce periférico.' },
        { nome: 'Metástase / mieloma', achado: 'Lesão lítica com massa de partes moles; o esterno é sítio frequente por sua medula vermelha.' },
        { nome: 'Pectus excavatum', achado: 'Depressão esternal com índice de Haller (razão entre diâmetro transverso e distância esterno-coluna) > 3,25 indicando gravidade.' },
      ],
    },
    {
      id: 'mama-direita',
      nome: 'Mama direita',
      categoria: 'partes-moles',
      resumo: 'Glândula sudorípara modificada situada sobre o músculo peitoral maior, entre a 2ª e a 6ª costelas.',
      morfologia: 'Composta por tecido fibroglandular e adiposo em proporções que variam com idade, paridade e status hormonal, organizada em 15 a 20 lobos que drenam por ductos até o mamilo. Apoia-se na fáscia peitoral, com o espaço retromamário de gordura entre elas.',
      funcao: 'Lactação. Do ponto de vista da imagem torácica, o que mais importa é a drenagem linfática: cerca de 75% vai para os linfonodos axilares, o restante para a cadeia mamária interna — território rotineiramente visível na TC de tórax e frequentemente ignorado.',
      densidade: 'Gordura −100 a −50 UH; tecido fibroglandular 20–40 UH. Calcificações são vistas mas a TC NÃO substitui a mamografia para microcalcificações.',
      janela: 'Partes moles.',
      comoIdentificar: 'Tecido de partes moles e gordura na parede torácica anterior, à frente do músculo peitoral maior. Em decúbito dorsal ela se espalha lateralmente.',
      reparos: ['Músculo peitoral maior (posterior)', 'Espaço retromamário', 'Axila e linfonodos axilares (lateral)', 'Vasos mamários internos (mediais ao esterno)'],
      clinica: 'A TC de tórax não é exame de rastreamento mamário, mas achados incidentais acontecem e devem ser relatados: massa espiculada, retração de pele, espessamento cutâneo assimétrico e linfonodomegalia axilar. Vale notar que a TC vê muito bem a cadeia mamária interna, que a mamografia não alcança — e essa cadeia é rota de disseminação de tumores mediais.',
      alteracoes: [
        { nome: 'Carcinoma de mama', achado: 'Massa espiculada com realce, retração cutânea, espessamento de pele e linfonodomegalia axilar ou mamária interna.' },
        { nome: 'Linfonodomegalia axilar', achado: 'Linfonodo com perda do hilo gorduroso e eixo curto > 1 cm; diferencial inclui infecção, vacina recente e linfoma.' },
        { nome: 'Implante mamário', achado: 'Estrutura oval de densidade uniforme; ruptura intracapsular gera o "sinal do linguini" (linhas onduladas do envelope colapsado dentro do gel).' },
        { nome: 'Alterações pós-radioterapia', achado: 'Espessamento cutâneo difuso e fibrose do parênquima pulmonar subjacente, com margens retas que respeitam o campo de irradiação.' },
      ],
    },
    {
      id: 'mama-esquerda',
      nome: 'Mama esquerda',
      categoria: 'partes-moles',
      resumo: 'Mama contralateral; a comparação entre os dois lados é a chave da leitura.',
      morfologia: 'Idêntica à direita, sobre o peitoral maior esquerdo, à frente do coração.',
      funcao: 'Igual à direita.',
      densidade: 'Igual à direita.',
      janela: 'Partes moles.',
      comoIdentificar: 'Mesma localização, do lado esquerdo. Compare sempre lado a lado: assimetria é o achado mais valioso.',
      reparos: ['Peitoral maior esquerdo', 'Coração (posteromedial)', 'Axila esquerda'],
      clinica: 'A mama esquerda recebe mais dose de radiação em radioterapia torácica esquerda e é a que mais fica exposta em irradiação de linfoma e de câncer de mama — a TC de seguimento avalia fibrose pulmonar radioinduzida e, a longo prazo, o risco cardiovascular pela dose no coração.',
      alteracoes: [
        { nome: 'Assimetria de densidade', achado: 'Diferença focal entre as mamas; sempre correlacionar com exame clínico e mamografia.' },
        { nome: 'Mastectomia prévia', achado: 'Ausência do tecido mamário com pele aderida ao peitoral; procurar recidiva na parede torácica.' },
        { nome: 'Ginecomastia (em homens)', achado: 'Tecido de partes moles retroareolar em disco ou em chama, bilateral ou não; causas medicamentosas e hepatopatia.' },
      ],
    },
    {
      id: 'apendice-xifoide',
      nome: 'Apêndice xifoide',
      categoria: 'osso',
      resumo: 'Menor e mais inferior parte do esterno; cartilaginoso no jovem, ossifica com a idade.',
      morfologia: 'Pequena lâmina de forma muito variável (pode ser bífida, perfurada ou desviada), unida ao corpo do esterno pela sincondrose xifoesternal. Ossifica progressivamente após os 40 anos.',
      funcao: 'Ponto de inserção do diafragma, da linha alba e dos músculos retos abdominais. É a referência de superfície do ápice cardíaco e o ponto abaixo do qual se posicionam as mãos na compressão torácica.',
      densidade: 'Cartilagem (~60 UH) no jovem; osso denso no idoso.',
      janela: 'Óssea; sagital ajuda muito.',
      comoIdentificar: 'É a última estrutura óssea na linha média anterior, no nível em que fígado e estômago já aparecem. Costuma ser pequena e às vezes desviada — daí ser confundida com nódulo ou corpo estranho.',
      reparos: ['Corpo do esterno (acima)', 'Diafragma e linha alba (inserção)', 'Lobo esquerdo do fígado (posterior)'],
      clinica: 'A variabilidade de forma do xifoide é grande e ele é uma das pseudolesões mais comuns: um xifoide desviado ou bífido é palpado como "nódulo" pelo paciente e visto como estrutura estranha na imagem. A síndrome xifoidalgia (dor à palpação) é benigna. Fratura de xifoide é rara e costuma decorrer de manobras de ressuscitação.',
      alteracoes: [
        { nome: 'Xifoide bífido ou desviado', achado: 'Variante anatômica sem significado clínico; explica o "caroço" que o paciente sente.' },
        { nome: 'Fratura pós-RCP', achado: 'Traço no xifoide ou na sincondrose, geralmente com fraturas costais anteriores associadas.' },
      ],
    },
    {
      id: 'figado-torax',
      nome: 'Fígado',
      categoria: 'viscera-parenquimatosa',
      resumo: 'Maior víscera sólida do corpo, que ocupa o hipocôndrio direito e aparece nos cortes inferiores da TC de tórax.',
      morfologia: 'Ocupa o espaço subdiafragmático direito, estendendo-se até o epigástrio. Nos cortes baixos do tórax aparece a cúpula hepática, coberta pelo diafragma.',
      funcao: 'Metabolismo intermediário, síntese proteica, detoxificação e produção de bile. Nesta série, o que interessa é sua posição: é o órgão logo abaixo do diafragma à direita, e portanto o primeiro a ser lesado em trauma de base de hemitórax direito.',
      densidade: 'Parênquima normal: 50–70 UH sem contraste — sempre 8 a 10 UH MAIS DENSO que o baço na fase sem contraste. Se o fígado estiver menos denso que o baço, pense em esteatose.',
      janela: 'Mediastinal / partes moles; janela hepática estreita para nódulos.',
      comoIdentificar: 'Nos últimos cortes da série, é a grande massa homogênea que ocupa quase todo o lado direito, abaixo do diafragma.',
      reparos: ['Diafragma (acima)', 'Veias hepáticas (convergem para a cava)', 'Estômago e baço (à esquerda)'],
      clinica: 'Nas TCs de tórax, a cúpula hepática é um achado incidental frequente e relevante: esteatose (fígado hipodenso), nódulos e lesões focais aparecem ali e não devem ser ignorados. Em trauma, fraturas de costelas inferiores direitas apontam para laceração hepática.',
      alteracoes: [
        { nome: 'Esteatose hepática', achado: 'Densidade < 40 UH ou fígado menos denso que o baço na fase sem contraste; vasos aparecem hiperdensos em relação ao parênquima.' },
        { nome: 'Laceração hepática', achado: 'Linha hipodensa irregular no parênquima com hematoma perihepático e líquido livre.' },
        { nome: 'Metástases', achado: 'Lesões hipodensas múltiplas com realce em anel na fase portal.' },
      ],
    },
    {
      id: 'baco-torax',
      nome: 'Baço',
      categoria: 'viscera-parenquimatosa',
      resumo: 'Órgão linfoide no hipocôndrio esquerdo, logo abaixo da cúpula diafragmática esquerda.',
      morfologia: 'Forma de meia-lua, com a face diafragmática convexa e a face visceral côncava. Estende-se da 9ª à 11ª costelas esquerdas. Comprimento normal até 12–13 cm.',
      funcao: 'Filtro de hemácias senescentes, reservatório de plaquetas e órgão de imunidade contra bactérias encapsuladas — daí a necessidade de vacinação após esplenectomia.',
      densidade: 'Sem contraste: 40–60 UH, sempre um pouco MENOS denso que o fígado. Na fase arterial apresenta realce heterogêneo, "listrado" ou "em zebra", que é NORMAL e desaparece na fase portal — uma das pseudolesões mais confundidas com laceração.',
      janela: 'Partes moles.',
      comoIdentificar: 'Nos cortes mais baixos, é a estrutura de partes moles em meia-lua no lado esquerdo, entre o diafragma e o estômago.',
      reparos: ['Diafragma (acima e lateral)', 'Estômago (medial)', 'Rim esquerdo (inferior)', 'Cauda do pâncreas (medial, no hilo esplênico)'],
      clinica: 'O baço é a víscera mais lesada no trauma abdominal fechado, e fraturas de costelas inferiores esquerdas na TC de tórax devem sempre disparar sua avaliação. Esplenomegalia é achado incidental com diagnóstico diferencial amplo — hipertensão portal, doenças hematológicas, infecções.',
      alteracoes: [
        { nome: 'Laceração esplênica', achado: 'Linha hipodensa com hematoma subcapsular ou perisplênico; sangramento ativo aparece como foco de contraste extravasado na fase arterial.' },
        { nome: 'Esplenomegalia', achado: 'Comprimento > 13 cm ou índice esplênico aumentado; investigar hipertensão portal e doença hematológica.' },
        { nome: 'Baço acessório', achado: 'Nódulo com densidade e realce idênticos ao baço, junto ao hilo; presente em 10–30% e confundido com linfonodo ou massa pancreática.' },
        { nome: 'Realce heterogêneo arterial', achado: 'Padrão "em zebra" fisiológico na fase arterial — não é laceração. Confirmar na fase portal, quando homogeneíza.' },
      ],
      armadilhas: ['O realce heterogêneo esplênico na fase arterial é a pseudolesão número um do abdome superior; nunca diagnostique laceração sem a fase portal.'],
    },
    {
      id: 'estomago-torax',
      nome: 'Estômago',
      categoria: 'viscera-oca',
      resumo: 'Víscera oca do hipocôndrio esquerdo, cuja porção proximal (fundo) toca a cúpula diafragmática.',
      morfologia: 'Nos cortes baixos da TC de tórax, aparece o fundo gástrico, geralmente cheio de ar em decúbito dorsal — uma bolha escura logo abaixo do diafragma esquerdo.',
      funcao: 'Reservatório e digestão inicial. Do ponto de vista da TC de tórax, sua importância é servir de marco: a bolha gástrica localiza o diafragma esquerdo e denuncia hérnia de hiato quando aparece acima dele.',
      densidade: 'Ar (−1000 UH) no fundo; conteúdo líquido 0–20 UH; parede de partes moles com realce.',
      janela: 'Partes moles.',
      comoIdentificar: 'Bolha de ar arredondada abaixo do diafragma esquerdo, medialmente ao baço.',
      reparos: ['Diafragma esquerdo (acima)', 'Baço (lateral)', 'Lobo esquerdo do fígado (medial/anterior)'],
      clinica: 'Quando parte do estômago aparece ACIMA do diafragma, há hérnia de hiato — achado extremamente comum e frequentemente incidental. Uma hérnia paraesofágica volumosa, porém, é diferente: pode encarcerar e sofrer volvo, uma emergência cirúrgica.',
      alteracoes: [
        { nome: 'Hérnia de hiato por deslizamento', achado: 'Junção esofagogástrica e fundo acima do diafragma, com anel de hiato alargado (> 15 mm).' },
        { nome: 'Hérnia paraesofágica', achado: 'Fundo gástrico herniado ao lado do esôfago, com a junção em posição normal; risco de volvo e encarceramento.' },
        { nome: 'Volvo gástrico', achado: 'Estômago rodado com dois níveis hidroaéreos e obstrução; emergência.' },
      ],
    },
    {
      id: 'pilar-diafragmatico-direito-torax',
      nome: 'Pilar diafragmático direito',
      sinonimos: ['crus direito'],
      categoria: 'musculo',
      resumo: 'Banda muscular que ancora o diafragma à coluna lombar à direita; mais longo e mais espesso que o esquerdo.',
      morfologia: 'Origina-se dos corpos vertebrais de L1 a L3 (e discos correspondentes) e sobe à direita da aorta, contribuindo com a maior parte das fibras do hiato esofágico. É consistentemente mais longo e mais robusto que o pilar esquerdo.',
      funcao: 'Ancoragem do diafragma e componente do esfíncter esofágico inferior: a contração do pilar direito durante a inspiração comprime o esôfago, contribuindo para a barreira antirrefluxo. Sua falência anatômica é parte da fisiopatologia da hérnia de hiato.',
      densidade: 'Músculo, 40–60 UH; realça discretamente.',
      janela: 'Partes moles.',
      comoIdentificar: 'Nos cortes na altura do hiato, é a banda muscular vertical e curva que corre à direita da aorta, à frente dos corpos vertebrais. Rolando os cortes de cima para baixo, você vê os dois pilares se afinarem e se aproximarem da coluna.',
      reparos: ['Aorta (entre os dois pilares, no hiato aórtico)', 'Corpos vertebrais L1-L3 (origem)', 'Veia cava inferior (à direita)', 'Espaço retrocrural (atrás dos pilares)'],
      clinica: 'O espaço retrocrural — atrás dos pilares — é uma estação linfonodal importante e frequentemente esquecida: linfonodos maiores que 6 mm aí são anormais e podem ser a única pista de linfoma ou de neoplasia abdominal em uma TC de tórax. Além disso, um pilar espessado e nodular é uma pseudolesão clássica confundida com linfonodo ou com nódulo adrenal.',
      alteracoes: [
        { nome: 'Pilar nodular / espessado', achado: 'Espessamento focal do músculo, especialmente em idosos e enfisematosos; pseudolesão que imita linfonodo ou adrenal.' },
        { nome: 'Linfonodomegalia retrocrural', achado: 'Nódulos > 6 mm atrás dos pilares — achado de alto valor para linfoma e neoplasias abdominais.' },
        { nome: 'Ruptura diafragmática', achado: 'Descontinuidade com herniação; à direita é protegida pelo fígado e por isso mais rara e mais difícil de ver.' },
      ],
      armadilhas: ['Pilares espessos e nodulares em idosos são a causa mais comum de "pseudolinfonodo" retrocrural.'],
      medidas: [{ rotulo: 'Espessura normal', valor: '≤ 5 mm' }, { rotulo: 'Linfonodo retrocrural anormal', valor: '> 6 mm' }],
    },
    {
      id: 'pilar-diafragmatico-esquerdo-torax',
      nome: 'Pilar diafragmático esquerdo',
      sinonimos: ['crus esquerdo'],
      categoria: 'musculo',
      resumo: 'Contraparte esquerda do pilar direito; mais curto, origina-se de L1-L2.',
      morfologia: 'Origina-se dos corpos de L1 e L2, sobe à esquerda da aorta e contribui menos que o direito para o hiato esofágico. Junto com o direito, forma o ligamento arqueado mediano, que arqueia sobre a aorta.',
      funcao: 'Ancoragem do diafragma e contribuição para o mecanismo antirrefluxo.',
      densidade: 'Músculo, 40–60 UH.',
      janela: 'Partes moles.',
      comoIdentificar: 'Banda muscular vertical à esquerda da aorta, simétrica ao pilar direito, mas visivelmente mais curta — nos cortes mais baixos ela some antes do direito.',
      reparos: ['Aorta (à direita dele)', 'Corpos vertebrais L1-L2', 'Espaço retrocrural esquerdo', 'Adrenal esquerda (anterolateral, abaixo)'],
      clinica: 'O ligamento arqueado mediano, formado pelos dois pilares, pode comprimir o tronco celíaco quando tem inserção baixa — é a síndrome do ligamento arqueado mediano (Dunbar), que causa dor abdominal pós-prandial e sopro epigástrico. Na TC sagital, o achado é uma indentação em "gancho" na face superior do tronco celíaco, que piora na expiração.',
      alteracoes: [
        { nome: 'Síndrome do ligamento arqueado mediano', achado: 'Indentação em gancho na face superior do tronco celíaco no plano sagital, com dilatação pós-estenótica; acentua-se na expiração.' },
        { nome: 'Ruptura diafragmática esquerda', achado: 'Mais comum que a direita (o fígado protege o lado direito): descontinuidade com herniação de estômago, cólon ou baço, "sinal do colar" e víscera dependente encostada na parede torácica posterior.' },
        { nome: 'Pilar nodular', achado: 'Pseudolesão que imita nódulo adrenal esquerdo — siga a estrutura em cortes contíguos e ela se revela contínua e muscular.' },
      ],
    },
  ],
  quiz: [
    {
      pergunta: 'Uma fratura da primeira costela deve alertar principalmente para:',
      alternativas: [
        'Nada, pois é fratura banal',
        'Trauma de altíssima energia com risco de lesão de vasos subclávios, plexo braquial e aorta',
        'Osteoporose grave',
        'Tosse crônica',
      ],
      correta: 1,
      explicacao: 'A 1ª costela é curta, espessa e protegida pela clavícula e pela musculatura cervical. Fraturá-la exige energia muito alta, e sua fratura funciona como marcador de gravidade que justifica investigar vasos e aorta.',
    },
    {
      pergunta: 'Por que a tireoide aparece hiperdensa (70–100 UH) numa TC sem contraste?',
      alternativas: [
        'Por calcificação fisiológica',
        'Pelo conteúdo de iodo concentrado no parênquima',
        'Por artefato de endurecimento do feixe',
        'Por alta vascularização',
      ],
      correta: 1,
      explicacao: 'A tireoide concentra iodo ativamente pelo simportador sódio-iodeto, e o iodo é justamente o elemento que atenua raios X. Por isso a glândula é espontaneamente densa, e qualquer nódulo aparece hipodenso em relação a ela.',
    },
    {
      pergunta: 'Na TC sem contraste, o baço aparece MENOS denso que o fígado. Se essa relação se inverte, o achado sugere:',
      alternativas: ['Esplenomegalia', 'Esteatose hepática', 'Hemocromatose esplênica', 'Achado normal em jovens'],
      correta: 1,
      explicacao: 'Normalmente o fígado é 8–10 UH mais denso que o baço na fase sem contraste. Fígado menos denso que o baço (ou < 40 UH em absoluto) é critério de esteatose hepática — um dos achados incidentais mais frequentes da TC.',
    },
    {
      pergunta: 'Qual o local correto para puncionar o espaço pleural, considerando o trajeto do feixe vasculonervoso intercostal?',
      alternativas: [
        'Rente à borda inferior da costela superior',
        'Rente à borda superior da costela inferior',
        'No meio do espaço intercostal',
        'Diretamente sobre a costela',
      ],
      correta: 1,
      explicacao: 'O feixe veia-artéria-nervo corre no sulco da borda INFERIOR de cada costela. Puncionar rente à borda SUPERIOR da costela de baixo mantém a agulha longe do feixe.',
    },
    {
      pergunta: 'Uma banda muscular vertical à direita da aorta, à frente dos corpos vertebrais, corresponde a:',
      alternativas: ['Linfonodo retrocrural', 'Pilar diafragmático direito', 'Veia ázigos', 'Adrenal direita'],
      correta: 1,
      explicacao: 'É o pilar (crus) diafragmático direito, que se origina de L1-L3 e é mais longo que o esquerdo. Quando espessado e nodular — comum em idosos — é uma pseudolesão clássica confundida com linfonodo ou adrenal.',
    },
    {
      pergunta: 'Três ou mais costelas consecutivas fraturadas em dois pontos cada configuram:',
      alternativas: ['Fratura patológica', 'Tórax instável (flail chest)', 'Costocondrite', 'Fratura de estresse'],
      correta: 1,
      explicacao: 'Esse padrão cria um segmento de parede torácica desconectado, com movimento paradoxal, e associa-se a contusão pulmonar subjacente e risco de insuficiência respiratória — pode exigir ventilação ou fixação cirúrgica.',
    },
  ],
}
