import type { SubsecaoTC } from '../tipos'

export const toraxCoracao: SubsecaoTC = {
  id: 'coracao',
  titulo: 'Coração',
  subtitulo: 'Câmaras, coronárias, grandes vasos e pericárdio no corte axial',
  secaoId: 'torax',
  pasta: '/TC_TORAX/TC_TORAX_CORAÇÃO',
  ext: 'png',
  totalCortes: 18,
  orientacao: 'cranio-caudal',
  icone: 'heart',
  cor: 'vermelho',
  janelaPadrao: 'mediastinal',
  protocolo:
    'TC de tórax com contraste iodado endovenoso, fase de equilíbrio/venosa (~60–70 s). Para estudar coronárias de verdade usa-se angio-TC coronária sincronizada ao ECG (gating), com frequência cardíaca controlada por betabloqueador e cortes submilimétricos — sem sincronismo, o coração se move durante a aquisição e as coronárias saem borradas.',
  introducao:
    'O coração ocupa o mediastino médio e, na TC axial, aparece como uma massa de partes moles homogênea suspensa entre os dois pulmões, apoiada no diafragma e envolta pelo pericárdio. A grande dificuldade de quem começa é que o coração não é simétrico nem "de frente": ele está rodado para a esquerda e inclinado, de modo que o ventrículo direito fica ANTERIOR (encostado no esterno) e o átrio esquerdo fica POSTERIOR (encostado no esôfago e na coluna) — quem procura o "direito à direita" erra tudo. A segunda dificuldade é o tempo: numa TC comum de tórax, o contraste já se distribuiu, então todas as câmaras opacificam juntas e a distinção é anatômica, não densitométrica. Percorrendo a pilha de cima para baixo, você vê primeiro os grandes vasos (aorta ascendente, tronco pulmonar, veia cava superior), depois os átrios, depois os ventrículos e, por fim, o ápice cardíaco sobre o diafragma. Aprender a rolar esses cortes na ordem certa é aprender a montar mentalmente o coração em três dimensões a partir de fatias.',
  roteiro: [
    { passo: '1. Ache o mediastino e a silhueta cardíaca', detalhe: 'Na janela mediastinal, o coração é a massa cinza-clara central. Delimite a borda direita (átrio direito), a borda esquerda (ventrículo esquerdo) e a face anterior (ventrículo direito, colado ao esterno).' },
    { passo: '2. Oriente-se pelos grandes vasos', detalhe: 'Nos cortes altos, identifique o trio aorta ascendente (centro), tronco pulmonar (à esquerda e anterior) e veia cava superior (à direita). Eles funcionam como a bússola de todo o resto.' },
    { passo: '3. Desça até o plano das quatro câmaras', detalhe: 'Procure o corte em que aparecem simultaneamente os dois átrios atrás e os dois ventrículos à frente. É o corte-chave do exame: nele se compara o tamanho relativo das câmaras.' },
    { passo: '4. Siga os sulcos para achar as coronárias', detalhe: 'A descendente anterior mora no sulco interventricular anterior; a circunflexa e a coronária direita moram no sulco atrioventricular, dentro da gordura epicárdica.' },
    { passo: '5. Feche pelo pericárdio', detalhe: 'Percorra a linha fina que contorna o coração procurando espessamento, derrame ou calcificação. É o último passo, e o mais esquecido.' },
    { passo: '6. Compare direito com esquerdo', detalhe: 'Relação VD/VE > 1 no corte de quatro câmaras é sinal de sobrecarga direita — achado que muda a conduta em embolia pulmonar.' },
  ],
  perolas: [
    'Ventrículo direito = anterior, colado ao esterno. Átrio esquerdo = posterior, colado ao esôfago. Essa é a regra que resolve 80% das dúvidas de câmara na TC axial.',
    'Numa TC de tórax comum, contraste denso só no lado direito (VCS, AD, VD, tronco pulmonar) significa fase precoce — não conclua "câmaras esquerdas vazias".',
    'Calcificação coronariana em TC sem contraste não é achado incidental sem valor: ela prediz risco cardiovascular e deve ser relatada.',
    'Refluxo de contraste para as veias hepáticas e para a cava inferior durante a injeção sugere pressão elevada em câmaras direitas — insuficiência tricúspide ou sobrecarga de VD.',
  ],
  estruturas: [
    {
      id: 'arteria-descendente-anterior',
      nome: 'Artéria descendente anterior',
      sinonimos: ['ADA', 'artéria interventricular anterior', 'LAD'],
      categoria: 'arteria',
      resumo: 'Ramo terminal da coronária esquerda que desce pelo sulco interventricular anterior e irriga a maior parte do ventrículo esquerdo — a artéria mais importante do coração.',
      morfologia: 'Nasce da bifurcação do tronco da coronária esquerda, contorna a base do tronco pulmonar e desce pelo sulco interventricular anterior até o ápice, onde frequentemente contorna e sobe alguns centímetros pela face diafragmática. Calibre proximal de 3–4 mm. Emite ramos septais (perpendiculares, para dentro do septo interventricular) e ramos diagonais (para a parede anterolateral do VE).',
      funcao: 'Irriga os dois terços anteriores do septo interventricular, toda a parede anterior do VE, boa parte da parede lateral e o ápice — algo entre 45% e 55% da massa do ventrículo esquerdo. É a artéria cuja oclusão proximal produz o infarto anterior extenso, o de pior prognóstico.',
      densidade: 'Em angio-TC coronária, a luz opacificada atinge 300–450 UH. A parede não é vista isoladamente quando normal. Placas calcificadas aparecem como focos hiperdensos > 130 UH (limiar do escore de cálcio); placas não calcificadas (as instáveis) medem 30–80 UH e só são vistas com contraste, como falhas de preenchimento excêntricas na parede.',
      janela: 'Angio (WW ~600 / WL ~150) para acompanhar a luz sem estourar o brilho; janela mais estreita para caracterizar placa mole. Na TC de tórax de rotina, sem gating, procure apenas o traço da artéria e as calcificações.',
      comoIdentificar: 'Suba até o corte logo abaixo da bifurcação do tronco pulmonar. A ADA aparece como um pontinho denso na gordura do sulco interventricular anterior, exatamente na linha que separa o ventrículo direito (à sua esquerda na tela) do ventrículo esquerdo. Descendo os cortes, esse ponto acompanha o sulco e vai se aproximando do ápice.',
      reparos: ['Sulco interventricular anterior', 'Gordura epicárdica anterior', 'Tronco pulmonar (a ADA passa logo atrás/abaixo dele na origem)', 'Ápice cardíaco'],
      clinica: 'Lesão proximal da ADA (antes do primeiro septal) é a chamada "lesão da viúva": o infarto resultante compromete septo, parede anterior e ápice de uma vez, com alto risco de choque cardiogênico, aneurisma apical e trombo mural. Na angio-TC, uma ADA com escore de cálcio zero tem valor preditivo negativo altíssimo para doença coronariana obstrutiva — é por isso que o exame virou porteiro da dor torácica de risco intermediário.',
      alteracoes: [
        { nome: 'Aterosclerose calcificada', achado: 'Focos hiperdensos (>130 UH) na parede, que causam artefato de florescência ("blooming") e superestimam a estenose. Quantificados pelo escore de Agatston.' },
        { nome: 'Placa não calcificada de alto risco', achado: 'Placa hipodensa (<30 UH, "napkin-ring sign"), remodelamento positivo (vaso alargado no local da placa) e microcalcificações puntiformes — marcadores de instabilidade.' },
        { nome: 'Ponte miocárdica', achado: 'Segmento da ADA mergulhado dentro do miocárdio em vez de correr na gordura epicárdica; na sístole, comprime. Variante comum, geralmente benigna.' },
        { nome: 'Oclusão total crônica', achado: 'Interrupção abrupta da opacificação com reenchimento distal tênue por colaterais; miocárdio anterior afilado e hipodenso.' },
        { nome: 'Infarto anterior estabelecido', achado: 'Parede anterior/apical afinada, hipodensa (gordura de substituição), às vezes com aneurisma e calcificação linear subendocárdica.' },
      ],
      armadilhas: [
        'Sem sincronização com ECG, o movimento cardíaco borra a ADA e cria pseudoestenoses — não laudar estenose coronariana em TC de tórax comum.',
        'O "blooming" do cálcio faz uma placa de 40% parecer de 70%. Calcificação muito extensa torna o exame não interpretável para estenose.',
      ],
      medidas: [{ rotulo: 'Calibre proximal', valor: '3–4 mm' }, { rotulo: 'Limiar de cálcio', valor: '≥ 130 UH' }],
    },
    {
      id: 'tronco-da-pulmonar',
      nome: 'Tronco da pulmonar',
      sinonimos: ['tronco pulmonar', 'artéria pulmonar principal', 'TAP'],
      categoria: 'arteria',
      resumo: 'Vaso que sai do ventrículo direito levando sangue venoso aos pulmões; é o único tronco arterial do corpo que transporta sangue pouco oxigenado.',
      morfologia: 'Emerge do infundíbulo do VD, à esquerda e à frente da aorta ascendente, sobe por 4–5 cm e bifurca-se, sob o arco aórtico, em artéria pulmonar direita e esquerda. Diâmetro normal de até 29 mm no adulto, medido perpendicularmente ao eixo, no nível da bifurcação.',
      funcao: 'Conduz todo o débito do ventrículo direito — cerca de 5 L/min em repouso — ao leito capilar pulmonar, num circuito de baixa pressão (pressão média normal ≤ 20 mmHg). É a via final comum da pequena circulação: qualquer obstáculo à frente (embolia, doença parenquimatosa, hipoxemia crônica) se traduz em dilatação deste tronco.',
      densidade: 'Na fase arterial pulmonar dedicada (angio-TC de artérias pulmonares, ~15–20 s pós-injeção) a luz atinge 250–400 UH. Na fase de equilíbrio de uma TC de tórax de rotina, fica em 100–150 UH, homogênea.',
      janela: 'Mediastinal para medir o calibre; angio para caçar falha de enchimento.',
      comoIdentificar: 'Nos cortes altos, é a estrutura arredondada e opacificada situada à ESQUERDA e à FRENTE da aorta ascendente. Descendo um ou dois cortes, ela se abre em "Y" ou "T" — a artéria pulmonar direita atravessa horizontalmente para a direita, passando atrás da aorta ascendente e da veia cava superior.',
      reparos: ['Aorta ascendente (medial e posterior a ele)', 'Arco aórtico (logo acima)', 'Carina (posterior à bifurcação)', 'Infundíbulo do VD (abaixo)'],
      clinica: 'A relação entre o diâmetro do tronco pulmonar e o da aorta ascendente no mesmo corte é um dos sinais mais úteis da TC de tórax: razão TP/Ao > 1 sugere hipertensão pulmonar, com boa especificidade. Um tronco pulmonar > 29 mm em paciente dispneico obriga a procurar a causa — DPOC, doença tromboembólica crônica, cardiopatia esquerda, doença intersticial.',
      alteracoes: [
        { nome: 'Tromboembolismo pulmonar agudo', achado: 'Falha de enchimento central hipodensa envolta por contraste ("sinal do trilho de trem" no corte longitudinal, "sinal do donut" no axial); êmbolo em sela cavalga a bifurcação.' },
        { nome: 'Hipertensão pulmonar', achado: 'Tronco > 29 mm, razão TP/aorta ascendente > 1, dilatação do VD, retificação/abaulamento do septo interventricular para a esquerda e refluxo de contraste para a cava inferior.' },
        { nome: 'Doença tromboembólica crônica', achado: 'Trombo excêntrico aderido à parede, bandas e teias intraluminais, calibre irregular, perfusão em mosaico no parênquima.' },
        { nome: 'Estenose valvar pulmonar', achado: 'Dilatação pós-estenótica desproporcional do tronco e da artéria pulmonar esquerda, com valva espessada.' },
        { nome: 'Aneurisma do tronco pulmonar', achado: 'Dilatação > 40 mm; raro, associado a cardiopatias congênitas e vasculites (Behçet).' },
      ],
      armadilhas: [
        'Artefato de fluxo: sangue não opacificado do território da cava inferior pode misturar-se mal e simular falha de enchimento — repare que o "trombo" tem limites mal definidos e muda entre cortes.',
        'Movimento respiratório cria degraus que simulam falha de enchimento; confirme sempre em mais de um corte.',
      ],
      medidas: [{ rotulo: 'Diâmetro normal', valor: '≤ 29 mm' }, { rotulo: 'Razão TP/Ao', valor: '< 1 no normal' }],
    },
    {
      id: 'aorta-ascendente',
      nome: 'Aorta ascendente',
      categoria: 'arteria',
      resumo: 'Primeiro segmento da aorta, do anel valvar até a origem do tronco braquiocefálico; recebe todo o débito do ventrículo esquerdo.',
      morfologia: 'Começa na valva aórtica, na raiz (que contém os seios de Valsalva, de onde nascem as coronárias), sobe cerca de 5 cm à direita e à frente, e se continua no arco. Diâmetro normal de até 40 mm; acima de 45 mm já se fala em dilatação, e 55 mm é limiar cirúrgico clássico na aortopatia degenerativa.',
      funcao: 'Além de conduzir o sangue, é o principal reservatório elástico do corpo: a distensão sistólica da aorta ascendente armazena energia que, na diástole, mantém o fluxo coronariano. Perder essa complacência (na aterosclerose, no envelhecimento) aumenta a pós-carga e a pressão sistólica.',
      densidade: 'Fase arterial: 250–400 UH. Fase de equilíbrio: 90–150 UH. Sem contraste, a luz fica isodensa às partes moles (~40 UH) e a parede só é vista se calcificada.',
      janela: 'Mediastinal para medir; angio para dissecção e aneurisma. Sem contraste, a janela mediastinal ainda mostra hematoma intramural — que é hiperdenso.',
      comoIdentificar: 'Nos cortes altos do coração, é o círculo opacificado CENTRAL, à direita e atrás do tronco pulmonar e à esquerda da veia cava superior. Esse trio — cava superior (direita), aorta (centro), tronco pulmonar (esquerda/anterior) — é a assinatura do mediastino médio.',
      reparos: ['Veia cava superior (à direita)', 'Tronco pulmonar (à esquerda e anterior)', 'Átrio esquerdo (posterior, mais abaixo)', 'Artéria pulmonar direita (cruza por trás dela)'],
      clinica: 'É onde moram as emergências aórticas. A dissecção tipo A (Stanford), que envolve a ascendente, é cirúrgica de imediato — mortalidade de 1–2% por hora sem tratamento. A TC define o diagnóstico ao mostrar o flap intimal separando luz verdadeira e falsa. Dilatação da ascendente também é rastreada em valva aórtica bicúspide, Marfan e Loeys-Dietz.',
      alteracoes: [
        { nome: 'Dissecção aórtica tipo A', achado: 'Flap intimal linear hipodenso dividindo a luz em duas; luz falsa maior, com opacificação mais lenta e sinal do "bico" no ângulo agudo. Procurar derrame pericárdico (tamponamento) e extensão às coronárias.' },
        { nome: 'Hematoma intramural', achado: 'Espessamento em crescente da parede, hiperdenso (50–70 UH) na fase SEM contraste, sem flap. Só é visto se a série sem contraste for feita — por isso ela não pode ser pulada.' },
        { nome: 'Úlcera aterosclerótica penetrante', achado: 'Nicho de contraste que ultrapassa a íntima calcificada e entra na parede, com aterosclerose difusa ao redor.' },
        { nome: 'Aneurisma', achado: 'Diâmetro > 45 mm; medir sempre perpendicular ao eixo do vaso, de parede externa a parede externa, no mesmo nível em exames seriados.' },
        { nome: 'Aortite', achado: 'Espessamento parietal circunferencial e homogêneo, com realce tardio (Takayasu, arterite de células gigantes, sífilis).' },
      ],
      armadilhas: [
        'Artefato de movimento pulsátil cria uma linha dupla na parede anterior direita que imita flap de dissecção — o flap verdadeiro se mantém em cortes consecutivos e em reconstruções.',
        'Medir a aorta no corte axial quando ela é oblíqua superestima o diâmetro; use reconstrução perpendicular ao eixo.',
      ],
      medidas: [{ rotulo: 'Diâmetro normal', valor: '≤ 40 mm' }, { rotulo: 'Limiar cirúrgico usual', valor: '≥ 55 mm (menor em Marfan/bicúspide)' }],
    },
    {
      id: 'veia-cava-superior',
      nome: 'Veia cava superior',
      sinonimos: ['VCS'],
      categoria: 'veia',
      resumo: 'Tronco venoso que drena cabeça, pescoço e membros superiores para o átrio direito.',
      morfologia: 'Formada pela junção das veias braquiocefálicas direita e esquerda, atrás da primeira cartilagem costal direita. Desce verticalmente por 6–8 cm à direita da aorta ascendente e desemboca no teto do átrio direito. Recebe a veia ázigos pela parede posterior (croça da ázigos), logo acima do brônquio principal direito. Calibre de 15–20 mm, seção oval ou levemente achatada.',
      funcao: 'Devolve ao coração cerca de um terço do retorno venoso sistêmico. É um sistema de baixíssima pressão (0–6 mmHg) e parede fina, o que a torna colapsável e facilmente compressível por qualquer massa mediastinal — origem clínica da síndrome da veia cava superior.',
      densidade: 'Extremamente variável e dependente da fase. Na fase arterial precoce, contraste ainda concentrado gera densidade > 500 UH e artefato de endurecimento do feixe (estrias escuras) que atrapalha ver o mediastino vizinho. Na fase venosa, homogeneíza em 100–150 UH.',
      janela: 'Mediastinal. Em caso de artefato intenso, reavaliar na fase tardia.',
      comoIdentificar: 'Nos cortes altos, é a estrutura ovalada opacificada à DIREITA da aorta ascendente e anterior à artéria pulmonar direita. Descendo, ela se afunila e desaparece ao entrar no átrio direito.',
      reparos: ['Aorta ascendente (medial)', 'Traqueia e brônquio principal direito (posterior)', 'Croça da ázigos (entra por trás)', 'Átrio direito (abaixo)'],
      clinica: 'A síndrome da veia cava superior — edema de face e membros superiores, turgência jugular, circulação colateral torácica — é a tradução clínica da obstrução deste vaso, geralmente por neoplasia (carcinoma pulmonar, linfoma) ou trombo de cateter. A TC mostra o ponto e a causa da obstrução e mapeia as colaterais (ázigos, mamárias internas, torácicas laterais), o que orienta stent ou radioterapia.',
      alteracoes: [
        { nome: 'Síndrome da veia cava superior', achado: 'Estreitamento ou amputação da VCS, com opacificação intensa de colaterais (ázigos dilatada, mamárias internas, veias de parede torácica) e realce heterogêneo do fígado no lobo IV ("hot quadrate sign").' },
        { nome: 'Trombose de cateter', achado: 'Falha de enchimento tubular aderida ao cateter, com parede venosa realçada.' },
        { nome: 'Persistência da VCS esquerda', achado: 'Vaso adicional à esquerda do arco aórtico drenando no seio coronário, que fica dilatado. Variante em ~0,3% da população, importante antes de colocar marca-passo.' },
        { nome: 'Artefato de fluxo/mistura', achado: 'Área hipodensa junto à parede pela chegada de sangue não opacificado da ázigos — imita trombo, mas some na fase tardia.' },
      ],
      armadilhas: ['Nunca diagnostique trombo de VCS na fase arterial precoce: a mistura incompleta de contraste é a maior fonte de falso-positivo do mediastino.'],
      medidas: [{ rotulo: 'Calibre', valor: '15–20 mm' }],
    },
    {
      id: 'ventriculo-direito',
      nome: 'Ventrículo direito',
      sinonimos: ['VD'],
      categoria: 'viscera-oca',
      resumo: 'Câmara anterior do coração, que bombeia sangue venoso para o tronco pulmonar num circuito de baixa pressão.',
      morfologia: 'Ocupa a face anterior (esternocostal) do coração, em contato direto com o esterno. Tem formato de crescente quando visto em corte transversal, moldando-se ao ventrículo esquerdo. Parede fina — 3 a 5 mm — e cavidade trabeculada, com a banda moderadora atravessando-a. Continua-se superiormente no infundíbulo (via de saída), que leva à valva pulmonar.',
      funcao: 'Ejeta o mesmo volume sistólico do VE, mas contra uma resistência seis a oito vezes menor. É uma bomba de volume, não de pressão: tolera bem sobrecarga de volume crônica e muito mal aumentos agudos de pós-carga — motivo de a embolia pulmonar maciça matar por falência de VD.',
      densidade: 'Sangue opacificado 100–200 UH na fase de equilíbrio; miocárdio 40–60 UH sem contraste, realçando de forma homogênea e menos intensa que a cavidade.',
      janela: 'Mediastinal. Para avaliar espessura de parede e gordura de substituição, uma janela mais estreita ajuda.',
      comoIdentificar: 'É a primeira câmara que você encontra ao entrar no coração vindo da parede anterior do tórax: aquela cavidade em forma de meia-lua logo atrás do esterno, à esquerda da linha média.',
      reparos: ['Esterno (imediatamente anterior)', 'Septo interventricular (posteromedial)', 'Sulco interventricular anterior com a ADA (limite com o VE)', 'Diafragma (inferior)'],
      clinica: 'A avaliação do VD é o que transforma uma TC de embolia pulmonar em ferramenta prognóstica: relação VD/VE > 1,0 medida no corte de quatro câmaras identifica disfunção ventricular direita e mortalidade aumentada, indicando internação e monitorização mais agressivas. Também é a câmara acometida na displasia arritmogênica, na sobrecarga por hipertensão pulmonar e no infarto de VD (que acompanha o infarto inferior e contraindica nitrato).',
      alteracoes: [
        { nome: 'Sobrecarga aguda de VD', achado: 'VD dilatado com relação VD/VE > 1, retificação ou abaulamento do septo interventricular para a esquerda e refluxo de contraste para a veia cava inferior e veias hepáticas.' },
        { nome: 'Hipertrofia de VD', achado: 'Parede > 5 mm, geralmente com dilatação do tronco pulmonar — resposta crônica à hipertensão pulmonar.' },
        { nome: 'Displasia arritmogênica do VD', achado: 'Dilatação, afilamento parietal, infiltração gordurosa (áreas de −50 a −100 UH na parede) e aneurismas focais na via de saída, parede inferior e ápice ("triângulo da displasia").' },
        { nome: 'Infarto de VD', achado: 'Parede inferior do VD hipoperfundida em associação a infarto inferior do VE; VD dilatado e hipocontrátil.' },
      ],
      armadilhas: [
        'A relação VD/VE deve ser medida do endocárdio ao endocárdio, no maior diâmetro transverso de cada ventrículo, em reconstrução de quatro câmaras — no axial puro ela superestima.',
        'A banda moderadora e as trabéculas grosseiras podem simular trombo intracavitário.',
      ],
      medidas: [{ rotulo: 'Espessura da parede', valor: '3–5 mm' }, { rotulo: 'Razão VD/VE de risco', valor: '> 1,0' }],
    },
    {
      id: 'atrio-direito',
      nome: 'Átrio direito',
      sinonimos: ['AD'],
      categoria: 'viscera-oca',
      resumo: 'Câmara que recebe o retorno venoso sistêmico das cavas e do seio coronário e forma a borda direita da silhueta cardíaca.',
      morfologia: 'Situa-se à direita e posteriormente ao ventrículo direito. Parede fina (2 mm), com a crista terminal separando a porção lisa posterior (derivada do seio venoso, onde chegam as cavas) da porção trabeculada anterior e da aurícula direita, que é larga e de base ampla. Contém a fossa oval no septo interatrial.',
      funcao: 'Reservatório e conduto: recebe o sangue durante a sístole ventricular e o transfere ao VD na diástole, acrescentando ~20% do enchimento com sua contração. Abriga o nó sinusal (junto à desembocadura da VCS) e o nó atrioventricular (no triângulo de Koch) — ou seja, é também a sala de máquinas elétrica do coração.',
      densidade: 'Fase de equilíbrio: 100–150 UH, homogênea. Na fase precoce, mistura de contraste denso da VCS com sangue não opacificado da VCI cria heterogeneidade marcante.',
      janela: 'Mediastinal.',
      comoIdentificar: 'É a câmara que forma a borda mais à DIREITA do coração, logo abaixo da entrada da veia cava superior. No corte de quatro câmaras, está atrás e à direita do ventrículo direito, separada dele pela valva tricúspide.',
      reparos: ['Veia cava superior (entra pelo teto)', 'Veia cava inferior (entra pelo assoalho)', 'Septo interatrial (medial, separa do AE)', 'Sulco atrioventricular direito com a coronária direita'],
      clinica: 'Átrio direito dilatado aponta para sobrecarga de volume ou pressão à direita: insuficiência tricúspide, hipertensão pulmonar, fibrilação atrial de longa data, comunicação interatrial. Massas nesta câmara — mixoma, extensão de carcinoma renal ou hepatocelular pela cava inferior, trombo em trânsito — mudam radicalmente a conduta e são muitas vezes achadas primeiro na TC.',
      alteracoes: [
        { nome: 'Dilatação atrial direita', achado: 'Aumento do diâmetro transverso; associado a cava inferior dilatada e refluxo de contraste para veias hepáticas.' },
        { nome: 'Trombo em trânsito', achado: 'Falha de enchimento móvel e serpiginosa cruzando a câmara, geralmente com embolia pulmonar concomitante — emergência.' },
        { nome: 'Extensão tumoral pela cava', achado: 'Coluna de tecido realçante subindo pela VCI até o AD, típica de carcinoma de células renais e hepatocarcinoma.' },
        { nome: 'Mixoma', achado: 'Massa lobulada, hipodensa e heterogênea, aderida ao septo interatrial (mais comum à esquerda, mas ocorre à direita).' },
        { nome: 'Lipomatose do septo interatrial', achado: 'Espessamento em halteres do septo, poupando a fossa oval, com densidade de gordura (−80 UH). Benigno — não confundir com tumor.' },
      ],
      armadilhas: ['A crista terminal e a válvula de Eustáquio (remanescente embrionário na entrada da cava inferior) são estruturas normais frequentemente confundidas com trombo.'],
    },
    {
      id: 'arteria-circunflexa',
      nome: 'Artéria circunflexa',
      sinonimos: ['Cx', 'circunflexa esquerda'],
      categoria: 'arteria',
      resumo: 'Segundo ramo terminal da coronária esquerda; corre no sulco atrioventricular esquerdo e irriga a parede lateral do ventrículo esquerdo.',
      morfologia: 'Origina-se do tronco da coronária esquerda em ângulo quase reto, mergulha no sulco atrioventricular esquerdo e contorna o coração pela esquerda, em direção posterior. Emite ramos marginais obtusos para a parede lateral. Em ~10% das pessoas é dominante, dando origem à descendente posterior.',
      funcao: 'Irriga a parede lateral e parte da parede posterior do VE, além do átrio esquerdo. Em corações com dominância esquerda, também irriga a parede inferior e o nó atrioventricular.',
      densidade: 'Idêntica à da ADA: luz 300–450 UH em angio-TC; calcificações > 130 UH.',
      janela: 'Angio para o trajeto, óssea/estreita para caracterizar cálcio.',
      comoIdentificar: 'Procure a gordura do sulco atrioventricular esquerdo — o sulco que separa o átrio esquerdo (atrás) do ventrículo esquerdo (à frente). A circunflexa é o ponto denso dentro dessa gordura, na lateral esquerda do coração. Ela e a coronária direita percorrem o mesmo sulco, em lados opostos.',
      reparos: ['Sulco atrioventricular esquerdo', 'Aurícula esquerda (a Cx passa logo abaixo dela na origem)', 'Seio coronário (corre paralelo, no mesmo sulco, mas posterior)'],
      clinica: 'Infartos de circunflexa são os "silenciosos" do eletrocardiograma: a parede lateral é mal representada nas 12 derivações clássicas, e o paciente pode ter oclusão total com ECG quase normal. Por isso a imagem tem papel desproporcional aqui. A proximidade da Cx com o anel mitral também a torna vulnerável em cirurgia valvar mitral.',
      alteracoes: [
        { nome: 'Estenose aterosclerótica', achado: 'Redução focal do calibre com placa mista; avaliar sempre em reconstrução curva ao longo do vaso.' },
        { nome: 'Dominância esquerda', achado: 'A Cx continua no sulco até dar a descendente posterior — nesse cenário, sua oclusão produz infarto muito extenso.' },
        { nome: 'Origem anômala da Cx da coronária direita', achado: 'Vaso adicional saindo do seio direito e cursando atrás da aorta (trajeto retroaórtico) — variante habitualmente benigna.' },
      ],
      armadilhas: ['O seio coronário, cheio de contraste, corre no mesmo sulco e é muito maior — não o confunda com uma circunflexa "gigante".'],
    },
    {
      id: 'ventriculo-esquerdo',
      nome: 'Ventrículo esquerdo',
      sinonimos: ['VE'],
      categoria: 'viscera-oca',
      resumo: 'Câmara de parede espessa que ejeta sangue oxigenado na aorta contra a resistência sistêmica; forma a borda esquerda e o ápice do coração.',
      morfologia: 'Cavidade cônica de secção circular, com parede de 6 a 11 mm no adulto normal (três vezes a do VD) e músculos papilares anterolateral e posteromedial projetando-se na cavidade. Ocupa a face posterolateral esquerda e o ápice cardíaco. O septo interventricular é compartilhado com o VD e pertence funcionalmente ao VE.',
      funcao: 'Gera pressões de 120 mmHg ou mais para vencer a resistência sistêmica. Sua eficiência depende de geometria (esférico é ruim), massa muscular e perfusão coronariana — que ocorre só na diástole, o que explica a isquemia subendocárdica quando a frequência cardíaca sobe.',
      densidade: 'Cavidade opacificada 100–200 UH; miocárdio realça homogeneamente 60–100 UH na fase de equilíbrio. Área de infarto agudo aparece hipodensa; infarto crônico pode ter densidade de gordura.',
      janela: 'Mediastinal; janela estreita (WW ~150) evidencia melhor as diferenças de realce miocárdico.',
      comoIdentificar: 'É a câmara com a parede claramente MAIS ESPESSA, situada posterior e à esquerda do VD. No corte de quatro câmaras, compare as duas paredes lado a lado: a diferença de espessura é o critério mais rápido e confiável.',
      reparos: ['Septo interventricular (à direita)', 'Sulco interventricular anterior com a ADA', 'Sulco atrioventricular esquerdo com a circunflexa', 'Átrio esquerdo (posterior, através da valva mitral)'],
      clinica: 'Praticamente toda a cardiologia mora aqui: hipertrofia por hipertensão ou estenose aórtica, dilatação nas miocardiopatias, afinamento e aneurisma pós-infarto, trombo apical após infarto anterior extenso (risco de AVC embólico). Mesmo numa TC feita por outro motivo, um VE dilatado e de parede afilada é um achado que precisa ser relatado.',
      alteracoes: [
        { nome: 'Hipertrofia ventricular esquerda', achado: 'Parede > 12 mm; concêntrica na sobrecarga pressórica, assimétrica e septal na miocardiopatia hipertrófica.' },
        { nome: 'Infarto crônico', achado: 'Parede afinada (< 6 mm), hipodensa, por vezes com infiltração gordurosa e calcificação subendocárdica linear.' },
        { nome: 'Aneurisma ventricular', achado: 'Abaulamento de colo largo da parede afinada, tipicamente apical/anterior, frequentemente com trombo mural aderido.' },
        { nome: 'Pseudoaneurisma', achado: 'Colo estreito, contido pelo pericárdio — ruptura contida, emergência cirúrgica. A relação colo/diâmetro < 0,5 diferencia do aneurisma verdadeiro.' },
        { nome: 'Trombo apical', achado: 'Falha de enchimento hipodensa junto ao endocárdio apical, sem realce, melhor vista na fase tardia.' },
        { nome: 'Miocardiopatia dilatada', achado: 'Cavidade globosa e aumentada, parede fina, sem território coronariano definido.' },
      ],
      armadilhas: ['Músculos papilares e trabéculas cortados transversalmente parecem massas intracavitárias; siga-os em cortes vizinhos até a parede.'],
      medidas: [{ rotulo: 'Espessura normal', valor: '6–11 mm' }, { rotulo: 'Hipertrofia', valor: '> 12 mm' }],
    },
    {
      id: 'arteria-coronaria-direita',
      nome: 'Artéria coronária direita',
      sinonimos: ['CD', 'RCA'],
      categoria: 'arteria',
      resumo: 'Artéria que nasce do seio de Valsalva direito e percorre o sulco atrioventricular direito, irrigando o coração direito e — na maioria das pessoas — a parede inferior do VE.',
      morfologia: 'Origina-se do seio coronário direito, corre para baixo e para a direita no sulco atrioventricular direito, contorna a borda aguda do coração (onde emite o ramo marginal agudo) e alcança a face diafragmática. Em 85% das pessoas (dominância direita) termina como artéria descendente posterior, no sulco interventricular posterior.',
      funcao: 'Irriga o átrio direito, a maior parte do ventrículo direito, o nó sinusal (em 60% dos casos) e o nó atrioventricular (em 90%), além do terço posterior do septo e da parede inferior do VE quando dominante.',
      densidade: 'Igual às demais coronárias: 300–450 UH na luz opacificada.',
      janela: 'Angio; a CD é a coronária que mais sofre com movimento por estar num sulco muito móvel.',
      comoIdentificar: 'Ache a gordura do sulco atrioventricular DIREITO, entre o átrio direito (posterior) e o ventrículo direito (anterior). O pontinho denso ali é a coronária direita. Ela é imagem em espelho da circunflexa, do outro lado do coração.',
      reparos: ['Sulco atrioventricular direito', 'Aurícula direita (a CD passa sob ela na origem)', 'Seio de Valsalva direito (origem)'],
      clinica: 'A oclusão proximal da CD produz o infarto inferior, com dois desdobramentos clássicos: bradiarritmia por comprometimento nodal (a CD irriga ambos os nós) e infarto de ventrículo direito, situação em que a pré-carga é essencial e o uso de nitrato pode causar colapso hemodinâmico. Saber que "inferior" quase sempre significa "coronária direita" muda a antecipação clínica no plantão.',
      alteracoes: [
        { nome: 'Doença aterosclerótica', achado: 'Placas calcificadas ou mistas no segmento proximal, logo após a origem; frequentemente é a primeira coronária a calcificar.' },
        { nome: 'Origem anômala do seio esquerdo com trajeto interarterial', achado: 'CD nascendo do seio esquerdo e passando entre aorta e tronco pulmonar — variante de risco, associada a morte súbita em jovens atletas.' },
        { nome: 'Ectasia coronariana', achado: 'Dilatação difusa e irregular; pensar em doença de Kawasaki prévia quando há aneurismas saculares.' },
      ],
      armadilhas: ['Por estar no sulco mais móvel do coração, a CD é a que mais mostra artefato de movimento — pseudoestenoses no segmento médio são comuns.'],
    },
    {
      id: 'veia-pulmonar',
      nome: 'Veia pulmonar',
      categoria: 'veia',
      resumo: 'Veias que trazem sangue oxigenado dos pulmões ao átrio esquerdo; normalmente são quatro, duas de cada lado.',
      morfologia: 'Veias pulmonares superior e inferior de cada lado desembocam na parede posterior do átrio esquerdo. A superior direita passa anteriormente à artéria pulmonar direita; a inferior direita corre quase horizontal. Variações são comuns: veia média direita separada (~25%) e tronco comum à esquerda (~15%).',
      funcao: 'Únicas veias do corpo que transportam sangue arterializado. Sua desembocadura no átrio esquerdo tem uma manga de miocárdio atrial que se estende alguns milímetros para dentro do vaso — é o foco elétrico que dispara a maioria das fibrilações atriais, e por isso o alvo da ablação por cateter.',
      densidade: 'Na fase venosa/equilíbrio, 100–180 UH, homogêneas.',
      janela: 'Mediastinal; reconstruções 3D são padrão no planejamento de ablação.',
      comoIdentificar: 'Nos cortes ao nível do átrio esquerdo, procure vasos que convergem para a parede POSTERIOR dele, entrando "como raios de uma roda". A veia pulmonar superior direita é a que passa à frente da artéria pulmonar direita — esse cruzamento é o melhor reparo.',
      reparos: ['Átrio esquerdo (destino de todas)', 'Artéria pulmonar direita (a veia superior direita passa à frente)', 'Esôfago (imediatamente atrás do AE e das veias — relevante na ablação)'],
      clinica: 'O mapa venoso pulmonar por TC é obrigatório antes da ablação de fibrilação atrial: define número, calibre e variantes dos óstios, e a distância do átrio esquerdo ao esôfago — a fístula átrio-esofágica é a complicação mais temida do procedimento. Depois da ablação, a TC procura estenose de veia pulmonar.',
      alteracoes: [
        { nome: 'Estenose pós-ablação', achado: 'Redução focal do óstio com dilatação a montante e, nos casos graves, congestão/infarto do segmento pulmonar correspondente.' },
        { nome: 'Drenagem venosa anômala', achado: 'Veia pulmonar drenando em cava superior, ázigos ou átrio direito; a forma parcial direita associa-se a comunicação interatrial tipo seio venoso. A "cimitarra" drena para a cava inferior, com pulmão direito hipoplásico.' },
        { nome: 'Invasão neoplásica', achado: 'Tumor pulmonar que se estende pelo óstio venoso até o átrio esquerdo — muda o estadiamento para T4 e o risco de embolia sistêmica.' },
        { nome: 'Congestão venosa pulmonar', achado: 'Veias dilatadas com espessamento de septos interlobulares na insuficiência cardíaca esquerda.' },
      ],
      armadilhas: ['Uma veia pulmonar cortada transversalmente perto do átrio parece um nódulo — role dois cortes e ela vira tubo.'],
    },
    {
      id: 'pericardio',
      nome: 'Pericárdio',
      categoria: 'serosa',
      resumo: 'Saco fibrosseroso de duas camadas que envolve o coração e a raiz dos grandes vasos.',
      morfologia: 'Composto por pericárdio fibroso externo (inelástico, ancorado ao diafragma e ao esterno) e pericárdio seroso, com folheto parietal e visceral (epicárdio) separados por 15–50 mL de líquido. Na TC aparece como uma linha fina de partes moles de 1–2 mm, mais bem vista onde é ladeada por gordura mediastinal anterior e gordura epicárdica. Forma recessos que se insinuam entre os grandes vasos — o recesso pericárdico superior, atrás da aorta ascendente, é o que mais gera dúvida.',
      funcao: 'Limita a distensão aguda das câmaras, mantém o coração posicionado, reduz o atrito e serve de barreira à propagação de infecção. Por ser inelástico, um acúmulo rápido de apenas 150–200 mL de líquido já causa tamponamento, enquanto derrames crônicos de mais de 1 L podem ser tolerados.',
      densidade: 'Folheto normal: 30–50 UH. Líquido simples: 0–20 UH. Exsudato/pus/hemopericárdio: 25–60 UH (quanto mais denso, mais provável sangue). Calcificação: > 200 UH.',
      janela: 'Mediastinal para o folheto e o derrame; óssea para confirmar calcificação.',
      comoIdentificar: 'Siga a linha fina que contorna a face anterior do ventrículo direito, entre a gordura mediastinal (à frente) e a gordura epicárdica (atrás). É ali, "no sanduíche de gorduras", que o pericárdio é sempre visível — nas faces laterais e posterior ele costuma ser indistinguível do miocárdio.',
      reparos: ['Gordura mediastinal anterior', 'Gordura epicárdica', 'Face anterior do ventrículo direito', 'Recesso pericárdico superior (atrás da aorta ascendente)'],
      clinica: 'Duas síndromes dominam: o tamponamento (derrame que impede o enchimento diastólico — na TC, derrame com achatamento das câmaras direitas, refluxo de contraste para a cava e cava inferior distendida) e a pericardite constritiva (pericárdio espessado > 4 mm, frequentemente calcificado, com ventrículos de forma tubular e cava dilatada). A TC é o exame de escolha para ver calcificação pericárdica, superando o ecocardiograma.',
      alteracoes: [
        { nome: 'Derrame pericárdico', achado: 'Coleção circunferencial hipodensa; > 5 mm já é anormal. Densidade > 30 UH sugere sangue ou exsudato.' },
        { nome: 'Tamponamento', achado: 'Derrame + achatamento/colapso das câmaras direitas, cava inferior e veias hepáticas distendidas, refluxo de contraste para a cava — sinais indiretos, mas o diagnóstico é clínico-ecocardiográfico.' },
        { nome: 'Pericardite constritiva', achado: 'Espessamento > 4 mm, calcificação em casca de ovo, ventrículos tubulares, dilatação atrial e da cava inferior.' },
        { nome: 'Pericardite aguda', achado: 'Espessamento com realce dos folhetos pelo contraste, com ou sem derrame associado.' },
        { nome: 'Cisto pericárdico', achado: 'Lesão de densidade líquida (0–20 UH), parede imperceptível, no ângulo cardiofrênico direito em 70% dos casos. Benigno.' },
        { nome: 'Agenesia pericárdica', achado: 'Ausência do folheto com deslocamento do coração para a esquerda e interposição de pulmão entre aorta e tronco pulmonar.' },
      ],
      armadilhas: [
        'O recesso pericárdico superior, cheio de líquido fisiológico atrás da aorta ascendente, é rotineiramente confundido com dissecção aórtica ou linfonodo — repare que ele tem densidade de água e formato de crescente que acompanha a aorta.',
        'Espessura pericárdica normal pode chegar a 3 mm em pacientes obesos sem significar doença; e constrição pode existir com pericárdio de espessura normal.',
      ],
      medidas: [{ rotulo: 'Espessura normal', valor: '1–2 mm (até 3)' }, { rotulo: 'Líquido fisiológico', valor: '15–50 mL' }],
    },
    {
      id: 'atrio-esquerdo',
      nome: 'Átrio esquerdo',
      sinonimos: ['AE'],
      categoria: 'viscera-oca',
      resumo: 'Câmara mais posterior do coração; recebe as quatro veias pulmonares e enche o ventrículo esquerdo.',
      morfologia: 'Cavidade de parede lisa, situada imediatamente à frente do esôfago e da aorta descendente, atrás da aorta ascendente. Sua aurícula é estreita, alongada e digitiforme (bem diferente da aurícula direita, larga), projetando-se para a esquerda, ao longo do sulco atrioventricular. Parede de 2–3 mm.',
      funcao: 'Reservatório na sístole ventricular, conduto na diástole precoce e bomba na diástole tardia. É também um sensor de pressão: sua dilatação é o marcador estrutural mais confiável de pressão de enchimento cronicamente elevada — por isso "átrio esquerdo aumentado" significa doença de câmara esquerda, mesmo que a fração de ejeção esteja normal.',
      densidade: 'Fase de equilíbrio: 100–180 UH. Trombo: falha de enchimento hipodensa (< 60 UH) que persiste na fase tardia.',
      janela: 'Mediastinal.',
      comoIdentificar: 'É a câmara mais POSTERIOR de todas: aquela que está encostada na coluna, logo à frente do esôfago. Se você encontrar uma câmara opacificada colada na frente da aorta descendente, é o átrio esquerdo — sempre.',
      reparos: ['Esôfago (imediatamente posterior)', 'Aorta descendente (posterolateral esquerda)', 'Veias pulmonares (chegam pela parede posterior)', 'Carina (logo acima do teto do AE)'],
      clinica: 'O átrio esquerdo é onde se forma o trombo da fibrilação atrial — em mais de 90% dos casos dentro da aurícula esquerda, que é um fundo de saco de fluxo lento. A TC cardíaca com fase tardia é alternativa ao ecocardiograma transesofágico para excluir trombo antes de cardioversão ou ablação. Dilatação atrial esquerda também empurra o esôfago e o brônquio principal esquerdo, achado visível já na radiografia.',
      alteracoes: [
        { nome: 'Dilatação atrial esquerda', achado: 'Diâmetro anteroposterior > 40 mm; empurra o esôfago posteriormente e eleva o brônquio principal esquerdo. Típica da valvopatia mitral e da insuficiência cardíaca com fração de ejeção preservada.' },
        { nome: 'Trombo de aurícula esquerda', achado: 'Falha de enchimento na aurícula que persiste na fase tardia (60 s). Se a hipodensidade desaparece na fase tardia, era estase de contraste, não trombo.' },
        { nome: 'Mixoma atrial esquerdo', achado: 'Massa pediculada aderida à fossa oval, lobulada, hipodensa, por vezes calcificada; pode obstruir a valva mitral em determinadas posições.' },
        { nome: 'Estenose mitral', achado: 'AE muito dilatado, calcificação do anel e dos folhetos mitrais, congestão pulmonar e, nos casos avançados, calcificação da parede atrial.' },
      ],
      armadilhas: [
        'A estase de contraste na aurícula é a maior fonte de falso-positivo para trombo: a fase tardia é obrigatória antes de afirmar trombo.',
        'Não confunda a aurícula esquerda, digitiforme, com uma massa ou com um aneurisma — siga-a até a câmara.',
      ],
      medidas: [{ rotulo: 'Diâmetro AP normal', valor: '≤ 40 mm' }],
    },
  ],
  quiz: [
    {
      pergunta: 'Na TC axial de tórax, qual câmara cardíaca fica imediatamente atrás do esterno?',
      alternativas: ['Átrio esquerdo', 'Ventrículo direito', 'Ventrículo esquerdo', 'Átrio direito'],
      correta: 1,
      explicacao: 'O coração é rodado à esquerda: o ventrículo direito ocupa a face esternocostal (anterior) e o átrio esquerdo, a face posterior, junto ao esôfago. Essa rotação é a fonte de quase todos os erros de identificação de câmara no corte axial.',
    },
    {
      pergunta: 'Um paciente com embolia pulmonar tem, no corte de quatro câmaras, relação VD/VE de 1,3. O que isso significa?',
      alternativas: [
        'Achado normal, pois o VD é sempre maior que o VE',
        'Disfunção ventricular direita, com pior prognóstico',
        'Hipertrofia ventricular esquerda',
        'Artefato de movimento cardíaco',
      ],
      correta: 1,
      explicacao: 'Relação VD/VE > 1,0 indica sobrecarga/disfunção do ventrículo direito e é marcador independente de mortalidade na embolia pulmonar, reclassificando o paciente para risco intermediário. No coração normal, o VE é maior que o VD nesse corte.',
    },
    {
      pergunta: 'Ao avaliar uma aorta ascendente sem contraste, qual achado sugere hematoma intramural?',
      alternativas: [
        'Flap intimal linear dividindo a luz',
        'Espessamento em crescente hiperdenso (50–70 UH) da parede',
        'Luz totalmente hipodensa',
        'Calcificação da parede deslocada para dentro',
      ],
      correta: 1,
      explicacao: 'O hematoma intramural é sangue dentro da parede, sem comunicação com a luz — aparece como crescente hiperdenso na fase SEM contraste, e pode ser mascarado depois da injeção. É por isso que a série sem contraste não pode ser omitida na suspeita de síndrome aórtica aguda.',
    },
    {
      pergunta: 'Uma imagem hipodensa em crescente atrás da aorta ascendente, com densidade de água, provavelmente corresponde a:',
      alternativas: ['Dissecção aórtica', 'Recesso pericárdico superior', 'Linfonodo necrótico', 'Abscesso mediastinal'],
      correta: 1,
      explicacao: 'O recesso pericárdico superior é uma extensão fisiológica do saco pericárdico com líquido, localizado atrás da aorta ascendente. É uma das pseudolesões mais clássicas do mediastino — densidade de água, formato em crescente moldado à aorta e ausência de efeito de massa.',
    },
    {
      pergunta: 'A artéria descendente anterior é identificada na TC por percorrer qual estrutura?',
      alternativas: [
        'O sulco atrioventricular direito',
        'O sulco interventricular anterior',
        'O sulco coronário posterior',
        'O interior do septo interatrial',
      ],
      correta: 1,
      explicacao: 'A ADA desce pelo sulco interventricular anterior, na gordura epicárdica que marca o limite entre VD e VE. A circunflexa e a coronária direita percorrem os sulcos atrioventriculares esquerdo e direito, respectivamente.',
    },
    {
      pergunta: 'Falha de enchimento na aurícula esquerda que desaparece na fase tardia corresponde a:',
      alternativas: ['Trombo organizado', 'Mixoma', 'Estase de contraste (fluxo lento)', 'Invasão tumoral'],
      correta: 2,
      explicacao: 'Fluxo lento na aurícula produz opacificação retardada que imita trombo na fase precoce. O trombo verdadeiro permanece hipodenso também na aquisição tardia — daí a regra de nunca laudar trombo atrial sem fase tardia.',
    },
  ],
}
