import type { SubsecaoTC } from '../tipos'

export const toraxPulmaoPleura: SubsecaoTC = {
  id: 'pulmao-pleura',
  titulo: 'Pulmão e pleura',
  subtitulo: 'Lobos, fissuras, árvore brônquica e as interfaces pleurais',
  secaoId: 'torax',
  pasta: '/TC_TORAX/TC_TORAX_PULMAO_PLEURA',
  ext: 'PNG',
  totalCortes: 46,
  orientacao: 'cranio-caudal',
  icone: 'wind',
  cor: 'ciano',
  janelaPadrao: 'pulmonar',
  protocolo:
    'TC de tórax em inspiração máxima e apneia, do ápice pulmonar às cúpulas diafragmáticas, com cortes finos (≤ 1,25 mm) reconstruídos com filtro de alta frequência ("pulmão"). O contraste endovenoso não é necessário para avaliar parênquima — só entra quando se quer estudar vasos, pleura espessada ou mediastino. Séries complementares em expiração (para aprisionamento aéreo) e em decúbito ventral (para separar densidade gravitacional de fibrose incipiente) são pedidas na doença intersticial.',
  introducao:
    'O pulmão é o único órgão em que a TC enxerga praticamente tudo: como é ar (−1000 UH) contra tecido, o contraste natural é o maior do corpo inteiro, e por isso a tomografia de alta resolução consegue mostrar estruturas de menos de meio milímetro. Aqui a janela deixa de ser detalhe técnico e vira condição de existência do exame — o mesmo corte, em janela mediastinal, mostra um pulmão preto e vazio; em janela pulmonar (WW 1500 / WL −600), revela vasos, brônquios, septos e fissuras. A lógica da leitura é dividir para conquistar: primeiro os lobos, delimitados pelas fissuras; depois a árvore brônquica, que se ramifica de forma previsível; depois os vasos, que acompanham os brônquios; e finalmente a periferia, onde moram as doenças da pleura e do interstício subpleural. Percorrer a pilha inteira, do ápice à base, é obrigatório: doenças pulmonares se distribuem por gradientes (apical na sarcoidose e na tuberculose de reativação, basal e subpleural na fibrose pulmonar idiopática), e um gradiente só é visível quando se vê a série toda em sequência.',
  roteiro: [
    { passo: '1. Confirme a janela', detalhe: 'Nada de parênquima é avaliável em janela mediastinal. Comece em janela pulmonar e só depois troque para procurar linfonodos, derrame e massas.' },
    { passo: '2. Ache as fissuras', detalhe: 'A fissura oblíqua aparece como uma linha fina ou uma faixa avascular. Ela define o que é lobo superior/médio (à frente) e inferior (atrás). Sem localizar a fissura, não há como nomear o lobo.' },
    { passo: '3. Siga a árvore brônquica', detalhe: 'Da traqueia à carina, depois brônquios principais, lobares e segmentares. Cada brônquio caminha ao lado de uma artéria de calibre semelhante — o "par broncoarterial".' },
    { passo: '4. Percorra do ápice à base', detalhe: 'Passe a série inteira olhando só o parênquima, procurando nódulos, vidro fosco, consolidação e enfisema. Depois repita olhando só a periferia.' },
    { passo: '5. Avalie a interface pleural', detalhe: 'Contorne cada pulmão pela borda. Derrame, espessamento, placas e pneumotórax vivem nesse contorno.' },
    { passo: '6. Descreva a distribuição', detalhe: 'Superior x inferior, central x periférica, difusa x focal. A distribuição vale mais que a lesão isolada para o diagnóstico diferencial.' },
  ],
  perolas: [
    'Regra do par broncoarterial: brônquio e artéria caminham juntos com calibres parecidos. Brônquio maior que a artéria = bronquiectasia (sinal do anel de sinete).',
    'O lobo médio existe só à direita. Se você "achou" lobo médio à esquerda, você está olhando a língula, que pertence ao lobo superior esquerdo.',
    'Fissura acessória mais comum: a da veia ázigos, no ápice direito, com o pequeno "cometa" da veia na ponta.',
    'Pneumotórax pequeno só aparece em janela pulmonar e no ponto mais alto do hemitórax — no paciente deitado, isso é a região anteromedial, não o ápice.',
  ],
  estruturas: [
    {
      id: 'traqueia',
      nome: 'Traqueia',
      categoria: 'via-aerea',
      resumo: 'Tubo fibrocartilaginoso que conduz o ar da laringe à carina, onde se bifurca nos brônquios principais.',
      morfologia: 'Cerca de 10–12 cm de comprimento no adulto, com 16 a 20 anéis cartilaginosos em forma de "C" abertos posteriormente, fechados pela membrana traqueal (parede posterior membranosa). Corte transversal em "D" ou oval, com diâmetro coronal de 13–25 mm e sagital de 13–27 mm. Desce na linha média, ligeiramente desviada à direita pelo arco aórtico, do nível de C6 até T4–T5.',
      funcao: 'Conduz, aquece e umidifica o ar; o epitélio ciliado com células caliciformes forma a escada rolante mucociliar que expulsa partículas. A cartilagem impede o colapso na inspiração forçada, e a parede posterior membranosa permite a variação de calibre na tosse — mecanismo essencial para gerar velocidade de fluxo e expelir secreção.',
      densidade: 'Luz preenchida por ar: −1000 UH. Parede: 1–3 mm de partes moles (~40 UH). Cartilagens calcificam com a idade, sobretudo em mulheres após os 40 anos, aparecendo hiperdensas.',
      janela: 'Pulmonar para a luz e a parede; mediastinal para relação com estruturas vizinhas e massas.',
      comoIdentificar: 'É a estrutura mais fácil de todo o tórax: um círculo preto (ar) na linha média, à frente do esôfago e da coluna. Comece por ela ao abrir qualquer TC de tórax — é a âncora da orientação.',
      reparos: ['Esôfago (imediatamente posterior e à esquerda)', 'Arco aórtico (empurra a traqueia levemente à direita)', 'Tireoide (envolve a traqueia no pescoço)', 'Carina (onde termina)'],
      clinica: 'Desvio traqueal é um dos sinais mais rápidos de leitura: massas e bócio empurram a traqueia para o lado oposto; atelectasia e fibrose a tracionam para o mesmo lado. Estenose traqueal pós-intubação, pós-traqueostomia, é uma complicação subdiagnosticada — a TC com reconstrução coronal e sagital define extensão e distância da carina, dados que o cirurgião precisa.',
      alteracoes: [
        { nome: 'Estenose pós-intubação', achado: 'Redução focal e circunferencial do calibre, geralmente 2–4 cm abaixo das cordas vocais; medir extensão longitudinal e distância à carina.' },
        { nome: 'Traqueomalácia', achado: 'Colapso > 50% do calibre na série expiratória, com aspecto "em bainha de sabre" ou em crescente. Só é diagnosticável comparando inspiração e expiração.' },
        { nome: 'Traqueia em bainha de sabre', achado: 'Diâmetro coronal reduzido e sagital aumentado (razão < 0,6), típica da DPOC avançada.' },
        { nome: 'Compressão extrínseca', achado: 'Achatamento e desvio por bócio mergulhante, linfonodomegalia ou massa mediastinal.' },
        { nome: 'Neoplasia traqueal', achado: 'Massa endoluminal séssil ou polipoide; carcinoma adenoide cístico e carcinoma escamoso são os mais frequentes.' },
        { nome: 'Traqueobroncomegalia (Mounier-Kuhn)', achado: 'Traqueia > 3 cm com divertículos entre os anéis e bronquiectasias associadas.' },
      ],
      armadilhas: ['Secreção aderida à parede simula massa endoluminal — peça para o paciente tossir e repita, ou procure nível ar-líquido e mudança de posição.'],
      medidas: [{ rotulo: 'Diâmetro coronal', valor: '13–25 mm (homem), 10–21 mm (mulher)' }, { rotulo: 'Espessura da parede', valor: '1–3 mm' }],
    },
    {
      id: 'lobo-superior-direito',
      nome: 'Lobo superior direito',
      sinonimos: ['LSD'],
      categoria: 'via-aerea',
      resumo: 'Lobo mais alto do pulmão direito, limitado abaixo pela fissura horizontal e atrás pela fissura oblíqua.',
      morfologia: 'Composto por três segmentos: apical (S1), posterior (S2) e anterior (S3). Ocupa a porção superior e anterior do hemitórax direito. Seu brônquio lobar nasce do brônquio principal direito precocemente — tão precocemente que, em alguns casos, sai da própria traqueia (brônquio traqueal ou "pig bronchus").',
      funcao: 'Como todo o pulmão superior, é uma zona de West tipo 1 na posição ereta: pressão alveolar tende a exceder a pressão capilar, a perfusão é relativamente menor e a relação ventilação/perfusão é alta. Essa maior tensão de oxigênio e menor drenagem linfática explicam a predileção da tuberculose de reativação pelos segmentos apical e posterior.',
      densidade: 'Parênquima normal: −850 a −900 UH em inspiração profunda. Acima de −800 UH sugere aumento de densidade (vidro fosco); abaixo de −950 UH, enfisema ou aprisionamento.',
      janela: 'Pulmonar, obrigatoriamente.',
      comoIdentificar: 'Nos primeiros cortes da série (ápice), quase tudo o que você vê à direita é lobo superior. Descendo, ele vai sendo delimitado por trás pela fissura oblíqua e, no nível do hilo, por baixo pela fissura horizontal. É o lobo que fica na frente e em cima.',
      reparos: ['Fissura horizontal (limite inferior, com o lobo médio)', 'Fissura oblíqua (limite posterior, com o lobo inferior)', 'Veia ázigos e traqueia (mediais)'],
      clinica: 'A localização lobar muda o diagnóstico diferencial: tuberculose de reativação, silicose e sarcoidose preferem os campos superiores; a fibrose pulmonar idiopática, os inferiores. Nódulo em lobo superior num tabagista é câncer até prova em contrário. Atelectasia do lobo superior direito desloca a fissura horizontal para cima e cria o "sinal de S de Golden" quando há massa hilar obstruindo o brônquio.',
      alteracoes: [
        { nome: 'Tuberculose de reativação', achado: 'Consolidação com cavitação nos segmentos apical e posterior, nódulos centrolobulares em "árvore em brotamento" ao redor (disseminação broncogênica).' },
        { nome: 'Atelectasia lobar', achado: 'Colapso com deslocamento superior da fissura horizontal, desvio traqueal ipsilateral e perda de volume do hemitórax.' },
        { nome: 'Enfisema centrolobular', achado: 'Áreas de baixa atenuação sem parede definida, com predomínio nos lobos superiores, centradas no bronquíolo — a marca do tabagismo.' },
        { nome: 'Silicose / pneumoconiose', achado: 'Nódulos centrolobulares e perilinfáticos de predomínio superior e posterior, que podem coalescer em massas fibróticas progressivas.' },
        { nome: 'Tumor de Pancoast', achado: 'Massa no sulco superior invadindo o plexo braquial, a artéria subclávia e os corpos vertebrais.' },
      ],
      armadilhas: ['O ápice pulmonar é a região onde mais aparecem falsas opacidades por músculos do pescoço e artefato de volume parcial.'],
    },
    {
      id: 'lobo-superior-esquerdo',
      nome: 'Lobo superior esquerdo',
      sinonimos: ['LSE'],
      categoria: 'via-aerea',
      resumo: 'Único lobo superior do pulmão esquerdo, que incorpora a língula — o equivalente funcional do lobo médio direito.',
      morfologia: 'Formado pela divisão superior (segmentos apicoposterior S1+2 e anterior S3) e pela divisão lingular (lingular superior S4 e inferior S5). Ocupa toda a metade anterior e superior do hemitórax esquerdo, moldando-se ao coração pela incisura cardíaca.',
      funcao: 'Idêntica à do lobo superior direito, com a peculiaridade de a língula ser especialmente vulnerável a infecções por micobactérias não tuberculosas em mulheres idosas (a chamada "síndrome de Lady Windermere", que também acomete o lobo médio).',
      densidade: 'Parênquima normal: −850 a −900 UH.',
      janela: 'Pulmonar.',
      comoIdentificar: 'À esquerda existe apenas UMA fissura, a oblíqua. Tudo o que estiver à frente dela é lobo superior esquerdo. Nos cortes baixos, a parte do lobo superior que se estende para baixo, ao lado do coração, é a língula.',
      reparos: ['Fissura oblíqua esquerda (único limite)', 'Coração (incisura cardíaca)', 'Arco aórtico (medial, nos cortes altos)'],
      clinica: 'Como não há fissura horizontal à esquerda, a atelectasia do lobo superior esquerdo tem aspecto totalmente diferente da direita: o lobo colapsa contra a parede anterior, produzindo uma faixa de opacidade anterior e o "sinal do luftsichel" (uma foice de ar entre o arco aórtico e o lobo colapsado, correspondente ao segmento superior do lobo inferior hiperinsuflado).',
      alteracoes: [
        { nome: 'Atelectasia do LSE', achado: 'Opacidade anterior em faixa, hiperinsuflação compensatória do lobo inferior e sinal do luftsichel na radiografia/TC coronal.' },
        { nome: 'Consolidação lingular', achado: 'Opacidade com broncograma aéreo adjacente à borda esquerda do coração, que apaga essa borda na radiografia (sinal da silhueta).' },
        { nome: 'Bronquiectasias lingulares', achado: 'Brônquios dilatados com sinal do anel de sinete e nódulos em árvore em brotamento; associação com micobacteriose não tuberculosa.' },
      ],
      armadilhas: ['Chamar de "lobo médio esquerdo" o que é língula é o erro nomenclatural mais comum entre estudantes — o pulmão esquerdo tem dois lobos, não três.'],
    },
    {
      id: 'lobo-medio-direito',
      nome: 'Lobo médio direito',
      sinonimos: ['LM'],
      categoria: 'via-aerea',
      resumo: 'Pequeno lobo cuneiforme entre as fissuras horizontal e oblíqua, exclusivo do pulmão direito.',
      morfologia: 'Formado pelos segmentos lateral (S4) e medial (S5). Tem forma de cunha com o vértice no hilo e a base na parede torácica anterolateral. Seu brônquio é longo, estreito e sai em ângulo agudo do brônquio intermédio — uma configuração anatômica desfavorável para a drenagem.',
      funcao: 'A anatomia do brônquio lobar médio, cercado por linfonodos e com ângulo desfavorável, faz dele o lobo mais propenso a atelectasia e infecção crônica de repetição — a "síndrome do lobo médio".',
      densidade: 'Parênquima normal: −850 a −900 UH.',
      janela: 'Pulmonar.',
      comoIdentificar: 'Nos cortes na altura do átrio direito, é a região pulmonar situada ENTRE as duas fissuras, à frente e lateralmente ao coração. Se você achar a fissura horizontal (uma linha ou faixa avascular quase horizontal, à direita), o lobo médio está logo abaixo dela.',
      reparos: ['Fissura horizontal (acima)', 'Fissura oblíqua direita (atrás)', 'Átrio direito (medial)', 'Diafragma (abaixo, nos cortes mais baixos)'],
      clinica: 'A síndrome do lobo médio — atelectasia e infecção recorrentes — tem duas formas: obstrutiva (tumor endobrônquico, linfonodo comprimindo o brônquio) e não obstrutiva (bronquiectasias com micobactéria não tuberculosa). Diferenciá-las é obrigação: a forma obstrutiva exige broncoscopia. Na TC, procurar sempre a causa no brônquio lobar médio.',
      alteracoes: [
        { nome: 'Atelectasia do lobo médio', achado: 'Faixa triangular de opacidade adjacente à borda direita do coração, com apagamento dessa borda; as duas fissuras se aproximam.' },
        { nome: 'Síndrome do lobo médio', achado: 'Atelectasia crônica com bronquiectasias, nódulos em árvore em brotamento e perda de volume persistente.' },
        { nome: 'Obstrução endobrônquica', achado: 'Massa ou linfonodo no brônquio lobar médio com atelectasia distal; sempre procurar a causa antes de atribuir à síndrome não obstrutiva.' },
      ],
      armadilhas: ['Uma atelectasia laminar do lobo médio pode ser confundida com derrame pleural loculado na radiografia — na TC, o broncograma e o formato triangular resolvem.'],
    },
    {
      id: 'lobo-inferior-direito',
      nome: 'Lobo inferior direito',
      sinonimos: ['LID'],
      categoria: 'via-aerea',
      resumo: 'Maior lobo do pulmão direito, situado posteriormente à fissura oblíqua e apoiado no diafragma.',
      morfologia: 'Cinco segmentos: superior (S6), basal medial (S7), basal anterior (S8), basal lateral (S9) e basal posterior (S10). Ocupa toda a porção posterior e inferior do hemitórax direito. Nos cortes altos, o segmento superior (S6) já aparece atrás da fissura, mesmo em nível de carina — motivo de confusão frequente.',
      funcao: 'É a região de maior perfusão em posição ereta (zona 3 de West) e a que mais ventila, por maior excursão diafragmática. Essa combinação faz dos segmentos basais e do S6 o destino preferencial do material aspirado e dos êmbolos.',
      densidade: 'Parênquima normal: −850 a −900 UH. Nas bases, em decúbito dorsal, há um gradiente fisiológico de aumento de densidade posterior por atelectasia gravitacional — que só é fisiológico se desaparecer em decúbito ventral.',
      janela: 'Pulmonar.',
      comoIdentificar: 'Tudo o que está ATRÁS da fissura oblíqua direita pertence ao lobo inferior. Já nos cortes da carina, a região paravertebral direita posterior é o segmento superior (S6) do lobo inferior — não é lobo superior.',
      reparos: ['Fissura oblíqua direita (limite anterior)', 'Diafragma (abaixo)', 'Coluna vertebral e aorta descendente (mediais)'],
      clinica: 'Pneumonia aspirativa em paciente acamado vai para o S6 e para o basal posterior; em paciente ereto, para os basais. A fibrose pulmonar idiopática começa exatamente aqui, subpleural e posterior, nas bases. E a atelectasia gravitacional das bases é a pseudolesão mais comum de toda a TC de tórax — a série em decúbito ventral existe para desfazê-la.',
      alteracoes: [
        { nome: 'Pneumonia aspirativa', achado: 'Consolidação com broncograma aéreo nos segmentos dependentes (S6 e basal posterior no acamado).' },
        { nome: 'Fibrose pulmonar idiopática', achado: 'Faveolamento subpleural e basal, bronquiectasias de tração, reticulado com gradiente apicobasal — padrão de PIU.' },
        { nome: 'Infarto pulmonar', achado: 'Opacidade em cunha de base pleural com vértice hilar (corcova de Hampton), frequentemente com centro poupado.' },
        { nome: 'Atelectasia gravitacional', achado: 'Faixa de densidade posterior, tênue, que desaparece em decúbito ventral. Não é doença.' },
        { nome: 'Sequestro pulmonar', achado: 'Massa ou área cística no segmento basal posterior, tipicamente à esquerda, irrigada por artéria sistêmica vinda da aorta — procurar o vaso nutridor.' },
      ],
      armadilhas: ['Não confundir S6 (lobo inferior) com o segmento posterior do lobo superior: o divisor é a fissura oblíqua, não o nível do corte.'],
    },
    {
      id: 'lobo-inferior-esquerdo',
      nome: 'Lobo inferior esquerdo',
      sinonimos: ['LIE'],
      categoria: 'via-aerea',
      resumo: 'Lobo posteroinferior do pulmão esquerdo, atrás da fissura oblíqua esquerda.',
      morfologia: 'Habitualmente quatro segmentos: superior (S6), basal anteromedial (S7+8, fundidos à esquerda), basal lateral (S9) e basal posterior (S10). É menor que o direito porque o coração ocupa espaço à esquerda.',
      funcao: 'Mesma lógica de zona dependente do lado direito. Sua posição retrocardíaca faz com que consolidações passem despercebidas na radiografia de frente — a TC não tem esse ponto cego.',
      densidade: 'Parênquima normal: −850 a −900 UH.',
      janela: 'Pulmonar.',
      comoIdentificar: 'Tudo posterior à fissura oblíqua esquerda. Nos cortes baixos, é a região atrás e à esquerda do coração, entre a aorta descendente e a parede torácica posterior.',
      reparos: ['Fissura oblíqua esquerda', 'Aorta descendente (medial)', 'Coração (anterior)', 'Diafragma (inferior)'],
      clinica: 'A região retrocardíaca esquerda é um clássico ponto cego da radiografia de tórax: pneumonias, atelectasias e até massas ficam escondidas atrás da silhueta cardíaca. Quando a suspeita clínica é alta e a radiografia é "normal", a TC costuma mostrar consolidação exatamente aqui.',
      alteracoes: [
        { nome: 'Atelectasia retrocardíaca', achado: 'Faixa triangular de opacidade atrás do coração, com apagamento da linha paraespinhal esquerda.' },
        { nome: 'Sequestro pulmonar intralobar', achado: 'Localização mais típica de todas — segmento basal posterior esquerdo, com artéria sistêmica nutridora da aorta torácica descendente.' },
        { nome: 'Hérnia diafragmática (Bochdalek)', achado: 'Defeito posterolateral esquerdo com conteúdo gorduroso ou visceral herniado no lobo inferior.' },
      ],
    },
    {
      id: 'bronquio-principal-direito',
      nome: 'Brônquio principal direito',
      categoria: 'via-aerea',
      resumo: 'Primeiro brônquio à direita da carina: curto, largo e verticalizado.',
      morfologia: 'Mede 1,5–2,5 cm, com ângulo de apenas 25° em relação ao eixo traqueal — muito mais vertical que o esquerdo. Origina o brônquio lobar superior direito precocemente e continua como brônquio intermédio, que depois se divide nos brônquios lobar médio e lobar inferior.',
      funcao: 'Conduz aproximadamente 55% da ventilação. Sua verticalidade e largura fazem dele a via preferencial de tudo o que cai na árvore brônquica: corpo estranho aspirado, conteúdo gástrico e a ponta do tubo orotraqueal introduzido demais.',
      densidade: 'Ar na luz (−1000 UH), parede fina de partes moles.',
      janela: 'Pulmonar.',
      comoIdentificar: 'Logo abaixo da carina, é o tubo aéreo que segue para a direita, mais horizontal e mais curto que o esquerdo na imagem axial. Descendo poucos cortes, ele já emite o brônquio lobar superior e vira brônquio intermédio.',
      reparos: ['Carina (origem)', 'Artéria pulmonar direita (anterior a ele)', 'Veia ázigos (arqueia sobre ele)'],
      clinica: 'Intubação seletiva do brônquio principal direito é um dos erros mais frequentes na via aérea de urgência: o tubo desce reto e entra à direita, deixando o pulmão esquerdo sem ventilação — na TC, atelectasia completa à esquerda com hiperinsuflação à direita. Corpos estranhos aspirados também vão preferencialmente para cá.',
      alteracoes: [
        { nome: 'Intubação seletiva', achado: 'Ponta do tubo além da carina, dentro do brônquio direito, com colapso do pulmão esquerdo.' },
        { nome: 'Corpo estranho aspirado', achado: 'Falha de enchimento endoluminal com aprisionamento aéreo distal (o pulmão afetado não esvazia na expiração) ou atelectasia.' },
        { nome: 'Tumor endobrônquico', achado: 'Massa que estreita a luz com atelectasia lobar distal; carcinoide e carcinoma escamoso são os mais comuns.' },
        { nome: 'Ruptura brônquica traumática', achado: 'Descontinuidade da parede, pneumomediastino volumoso e "sinal do pulmão caído" — o pulmão colapsa para baixo em vez de para o hilo.' },
      ],
      medidas: [{ rotulo: 'Ângulo com a traqueia', valor: '~25°' }, { rotulo: 'Comprimento', valor: '1,5–2,5 cm' }],
    },
    {
      id: 'bronquio-principal-esquerdo',
      nome: 'Brônquio principal esquerdo',
      categoria: 'via-aerea',
      resumo: 'Brônquio mais longo e mais horizontalizado, que passa sob o arco aórtico a caminho do hilo esquerdo.',
      morfologia: 'Mede 4–6 cm, com ângulo de 45° em relação à traqueia. Passa abaixo do arco aórtico e à frente do esôfago e da aorta descendente antes de se dividir nos brônquios lobar superior (que dá a língula) e lobar inferior.',
      funcao: 'Conduz cerca de 45% da ventilação. Seu trajeto longo e angulado é o que protege o pulmão esquerdo da aspiração — e o que torna difícil alcançá-lo com o broncoscópio ou com o tubo.',
      densidade: 'Ar (−1000 UH) com parede fina.',
      janela: 'Pulmonar.',
      comoIdentificar: 'A partir da carina, é o tubo aéreo que segue para a esquerda por uma distância notavelmente maior que o direito antes de se ramificar. Ele passa por baixo do arco aórtico — se você vê o arco no corte, o brônquio esquerdo está logo abaixo.',
      reparos: ['Carina', 'Arco aórtico (passa por cima)', 'Artéria pulmonar esquerda (arqueia sobre ele)', 'Esôfago e aorta descendente (posteriores)', 'Átrio esquerdo (anteroinferior)'],
      clinica: 'A relação com o átrio esquerdo tem consequência clínica direta: átrio muito dilatado (estenose mitral) eleva o brônquio principal esquerdo e alarga o ângulo da carina. Aneurisma de aorta e linfonodomegalia subaórtica também o comprimem.',
      alteracoes: [
        { nome: 'Compressão por átrio esquerdo dilatado', achado: 'Elevação do brônquio e aumento do ângulo carinal (> 90°).' },
        { nome: 'Atelectasia do pulmão esquerdo', achado: 'Obstrução do brônquio principal com colapso total do hemitórax, desvio mediastinal ipsilateral e elevação diafragmática.' },
        { nome: 'Compressão extrínseca por massa', achado: 'Estreitamento por linfonodomegalia da janela aortopulmonar ou aneurisma aórtico.' },
      ],
      medidas: [{ rotulo: 'Ângulo com a traqueia', valor: '~45°' }, { rotulo: 'Comprimento', valor: '4–6 cm' }],
    },
    {
      id: 'fissura-horizontal-direita',
      nome: 'Fissura horizontal direita',
      sinonimos: ['fissura menor', 'pequena fissura'],
      categoria: 'serosa',
      resumo: 'Prega de pleura visceral que separa o lobo superior do lobo médio; existe apenas à direita.',
      morfologia: 'Estende-se da fissura oblíqua, na linha axilar média, até a parede torácica anterior, aproximadamente ao nível da 4ª cartilagem costal. Como é quase paralela ao plano axial, ela raramente aparece como linha nítida no corte transversal — em vez disso, produz uma zona avascular larga, oval, porque o corte "raspa" o plano da fissura. É incompleta em até 90% das pessoas.',
      funcao: 'A pleura visceral que forma a fissura funciona como barreira parcial à disseminação de infecção e de tumor entre lobos, e como plano de deslizamento entre eles durante a respiração. Fissuras incompletas permitem ventilação colateral entre lobos — dado decisivo antes de válvulas endobrônquicas no enfisema.',
      densidade: 'Linha de partes moles de menos de 1 mm; na prática, o que se vê é a ausência de vasos.',
      janela: 'Pulmonar. Em cortes finos com reconstrução de alta resolução, aparece como linha; em cortes grossos, apenas como área avascular.',
      comoIdentificar: 'Nos cortes na altura do hilo direito, procure uma região oval, "vazia", sem vasos, na porção anterolateral do pulmão direito. Aquilo é a fissura horizontal vista de topo. Em reconstruções coronais ou sagitais ela vira uma linha nítida — por isso o coronal ajuda tanto aqui.',
      reparos: ['Fissura oblíqua direita (onde nasce)', 'Lobo superior direito (acima)', 'Lobo médio (abaixo)'],
      clinica: 'A fissura é a melhor referência para localizar uma lesão. Um nódulo justafissural muitas vezes é apenas um linfonodo intrapulmonar — lentiforme, de menos de 1 cm, colado à fissura — e não precisa de seguimento agressivo. Deslocamento da fissura horizontal para cima indica atelectasia do lobo superior; para baixo, atelectasia do lobo médio.',
      alteracoes: [
        { nome: 'Deslocamento por atelectasia', achado: 'Fissura tracionada na direção do lobo colapsado; é o sinal indireto mais confiável de perda volumétrica.' },
        { nome: 'Derrame subpulmonar/cissural', achado: 'Líquido acumulado dentro da fissura, com aspecto lenticular ("tumor fantasma" na radiografia, que desaparece com o tratamento).' },
        { nome: 'Espessamento fissural', achado: 'Linfangite carcinomatosa, edema intersticial ou infiltração tumoral espessam a fissura de modo nodular ou liso.' },
        { nome: 'Fissura incompleta', achado: 'Vasos cruzando o plano fissural — contraindica ou limita o uso de válvulas endobrônquicas.' },
      ],
      armadilhas: ['A "área avascular" da fissura horizontal é frequentemente lida como consolidação ou vidro fosco por iniciantes; a ausência de vasos, e não a densidade, é a pista.'],
    },
    {
      id: 'fissura-obliqua-direita',
      nome: 'Fissura oblíqua direita',
      sinonimos: ['fissura maior direita'],
      categoria: 'serosa',
      resumo: 'Separa os lobos superior e médio (à frente) do lobo inferior (atrás), no pulmão direito.',
      morfologia: 'Corre obliquamente de cima para baixo e de trás para a frente, do nível de T4–T5 posteriormente até o diafragma anteriormente. Como cruza o plano axial em ângulo, ela aparece nos cortes transversais como uma LINHA nítida (ou uma faixa avascular estreita), diferentemente da horizontal.',
      funcao: 'Delimita o compartimento posterior do pulmão. É referência cirúrgica fundamental: a lobectomia depende de identificar o plano fissural e a completude da fissura, que determina a técnica e o risco de fístula aérea pós-operatória.',
      densidade: 'Linha de menos de 1 mm de partes moles.',
      janela: 'Pulmonar.',
      comoIdentificar: 'Nos cortes altos, ela aparece perto da coluna; conforme você desce, ela "caminha" para a frente. Essa migração anterior progressiva ao rolar os cortes é a assinatura da fissura oblíqua — e é exatamente o tipo de coisa que só se aprende percorrendo a pilha, não olhando um corte isolado.',
      reparos: ['Lobo superior e médio (anteriores)', 'Lobo inferior (posterior)', 'Hilo direito (a fissura passa logo atrás dele)'],
      clinica: 'Identificar corretamente a fissura oblíqua é o que permite dizer se um nódulo está no lobo inferior (ressecção posterior) ou no superior/médio — informação que muda a cirurgia. Também é onde se acumula líquido em derrames pequenos.',
      alteracoes: [
        { nome: 'Deslocamento posterior', achado: 'Atelectasia do lobo inferior traciona a fissura para trás e para baixo.' },
        { nome: 'Espessamento nodular', achado: 'Disseminação pleural de neoplasia ou linfangite carcinomatosa.' },
        { nome: 'Derrame cissural', achado: 'Coleção lenticular alongada dentro da fissura, de densidade líquida.' },
      ],
    },
    {
      id: 'fissura-obliqua-esquerda',
      nome: 'Fissura oblíqua esquerda',
      sinonimos: ['fissura maior esquerda'],
      categoria: 'serosa',
      resumo: 'Única fissura do pulmão esquerdo; separa o lobo superior (com a língula) do lobo inferior.',
      morfologia: 'Trajeto semelhante ao da direita, porém tipicamente um pouco mais vertical e começando um nível acima. Costuma ser mais completa que as fissuras direitas.',
      funcao: 'Divide o pulmão esquerdo em seus dois únicos lobos. Sua completude relativa faz com que a ventilação colateral entre lobos seja menor à esquerda.',
      densidade: 'Linha fina de partes moles.',
      janela: 'Pulmonar.',
      comoIdentificar: 'Como não existe fissura horizontal à esquerda, qualquer linha fissural que você vir nesse pulmão é a oblíqua. Ela também migra da região paravertebral (cortes altos) para a região anterior (cortes baixos).',
      reparos: ['Lobo superior esquerdo e língula (anteriores)', 'Lobo inferior esquerdo (posterior)', 'Aorta descendente (medial)'],
      clinica: 'Vale a mesma regra da direita: a fissura é o mapa. Além disso, a maior completude da fissura esquerda torna o pulmão esquerdo um candidato melhor para redução volumétrica endoscópica no enfisema.',
      alteracoes: [
        { nome: 'Espessamento e retração', achado: 'Fibrose, asbestose e sequela de empiema retraem a fissura.' },
        { nome: 'Derrame loculado cissural', achado: 'Coleção lenticular de limites lisos, que não se desloca com a mudança de decúbito.' },
      ],
      armadilhas: ['Fissuras acessórias (a mais comum é a que separa o segmento superior do lobo inferior) podem ser confundidas com a oblíqua e levar a erro de localização lobar.'],
    },
  ],
  quiz: [
    {
      pergunta: 'Em janela pulmonar, um brônquio com diâmetro maior que a artéria que o acompanha indica:',
      alternativas: ['Enfisema centrolobular', 'Bronquiectasia (sinal do anel de sinete)', 'Nódulo centrolobular', 'Atelectasia laminar'],
      correta: 1,
      explicacao: 'No par broncoarterial normal, brônquio e artéria têm calibres semelhantes. Quando o brônquio fica maior, o conjunto lembra um anel com uma pedra ao lado — o sinal do anel de sinete, critério maior de bronquiectasia.',
    },
    {
      pergunta: 'Por que a fissura horizontal aparece como área avascular larga, e não como linha, nos cortes axiais?',
      alternativas: [
        'Porque é mais espessa que a oblíqua',
        'Porque é quase paralela ao plano do corte, que a atravessa tangencialmente',
        'Porque contém líquido fisiológico',
        'Porque só existe em janela mediastinal',
      ],
      correta: 1,
      explicacao: 'A fissura horizontal é quase paralela ao plano axial; o corte a "raspa" ao longo de sua superfície, produzindo uma zona avascular larga. A oblíqua cruza o plano em ângulo e por isso aparece como linha nítida.',
    },
    {
      pergunta: 'Densidade posterior nas bases pulmonares em decúbito dorsal, que desaparece em decúbito ventral, corresponde a:',
      alternativas: ['Fibrose pulmonar inicial', 'Atelectasia gravitacional (dependente)', 'Pneumonia em organização', 'Vidro fosco por infecção viral'],
      correta: 1,
      explicacao: 'É atelectasia por gravidade nas regiões dependentes — fisiológica. A série em decúbito ventral existe justamente para desfazê-la e evitar o falso diagnóstico de doença intersticial incipiente.',
    },
    {
      pergunta: 'Um corpo estranho aspirado tem maior probabilidade de alojar-se em qual brônquio, e por quê?',
      alternativas: [
        'Esquerdo, por ser mais longo',
        'Direito, por ser mais largo, curto e verticalizado',
        'Esquerdo, por passar sob o arco aórtico',
        'Ambos igualmente',
      ],
      correta: 1,
      explicacao: 'O brônquio principal direito faz ângulo de ~25° com a traqueia (contra ~45° do esquerdo) e é mais calibroso, funcionando como continuação quase direta da via aérea. Vale para corpo estranho, aspiração e intubação seletiva.',
    },
    {
      pergunta: 'Qual estrutura NÃO existe no pulmão esquerdo?',
      alternativas: ['Fissura oblíqua', 'Língula', 'Fissura horizontal', 'Segmento apicoposterior'],
      correta: 2,
      explicacao: 'A fissura horizontal (menor) existe apenas à direita, separando lobo superior de lobo médio. À esquerda há apenas a fissura oblíqua, e o equivalente funcional do lobo médio é a língula, que faz parte do lobo superior esquerdo.',
    },
    {
      pergunta: 'A distribuição basal e subpleural de reticulado com faveolamento sugere:',
      alternativas: ['Sarcoidose', 'Silicose', 'Padrão de pneumonia intersticial usual (fibrose pulmonar idiopática)', 'Tuberculose de reativação'],
      correta: 2,
      explicacao: 'O padrão de PIU tem gradiente apicobasal e predomínio subpleural, com faveolamento e bronquiectasias de tração. Sarcoidose, silicose e tuberculose de reativação têm predomínio nos campos superiores.',
    },
  ],
}
